### ISSUE TITLE
Remoted integration tests: Tier 0

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh-qa#1021]
Hi team,

We need to develop new tests for `remoted` daemon to cover basic functionality and ensure everything works as expected. This tier 0 will cover the basic functionality of the daemon and its configuration. 

Tier 0 tests:
- [x] Test every option for `remote`. `remoted` must start without errors for each option. This test consists of two different parts:
    - Input: modify the configuration file and check if `remoted` correctly starts.
    - Output: request `remoted` configuration using the API. The response must return the same configuration as the one set in the input section.
- [x] Test the communication between agents and managers for each protocol.
- [x] Test the communication between the manager and the agents. This is done when the user makes a request to the manager to get the agent configuration. 
- [x] Send the `ping-pong` message implemented with the new auto-enrollment function using the sockets.
- [x] Test syslog option for TCP and UDP.
