### ISSUE TITLE
Remoted integration tests: Tier 1

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh-qa#1024]
Hi team,

We need to develop new tests for `remoted` daemon to extend the test coverage of non-basic functionality. These tests will be enclosed in the tier 1. 

Tier 1 tests:
- [x] Check the manager pushes the configuration if the agent's checksum is different.
- [x] Check if the manager can send an _active response_ command.
- [x] Check if the manager sends the `ack` after receiving the start-up message of the agent.
- [x] Check if the manager correctly analyze syslog messages with PRI Header and multiple TCP messages

**Comment by BraulioV** [comment]
All the story points have been completed, so I'm closing this issue.
