### ISSUE TITLE
Remoted integration tests: Tier 2

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh-qa#1026]
Hi team,

We need to develop new tests for `remoted` daemon to cover as much as we can. These tests require the interaction of several components and may require more time to complete than the ones from tier 0 and 1.

Tier 2 tests:
- [x] Connect a manager and agent(s) and check the following points:
    - The agent sends its version.
    - The manager pushes the configuration correctly
    - The agent restarts and sends the start up message correctly
- [x] Connect several agents with different protocols at once. https://github.com/wazuh/wazuh-qa/issues/1114
- [x] Using both protocols at the same time, connect an agent, check if the agent connects without problems and then, change the agent protocol. It must re-connect to the manager again.
