### ISSUE TITLE
Logcollector integration tests: Tier 0

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh-qa#1027]
Hi team,

We need to develop new tests for `logcollector` daemon to cover basic functionality and ensure everything works as expected. This tier 0 will cover the basic functionality of the daemon and its configuration. 

Tier 0 tests:
- [x] [Check if every field of the configuration works.](https://github.com/wazuh/wazuh-qa/issues/1144)  @Rebits 
- [x] [Test different paths for `location` field.](https://github.com/wazuh/wazuh-qa/issues/1224) @juliamagan 
- [x] [Test each `log_format` available](https://github.com/wazuh/wazuh-qa/issues/1226) ([docs](https://documentation.wazuh.com/4.0/user-manual/reference/ossec-conf/localfile.html#log-format)). @damarisg 
- [x] [Test wildcard usage: set up a wildcard, create a bunch of logs and check if the daemon collects the logs.](https://github.com/wazuh/wazuh-qa/issues/1224) @juliamagan 
- [x] [Test `only-future-events` option: start the manager, turn it off and send 2 logs.](https://github.com/wazuh/wazuh-qa/issues/1229) Now, you have two possible scenarios:
    - `yes`: the daemon will continue reading from the end.
    - `no`: the daemon will continue reading from the same line where it was stopped and both logs must be read and reported.
- [x] [age: if we change the date of the host, logcollector must keep working and reporting.](https://github.com/wazuh/wazuh-qa/issues/1241) @Rebits 
- [x] [exclude: test wildcard usage to exclude reading some files of a directory.](https://github.com/wazuh/wazuh-qa/issues/1224) @juliamagan 
- [x] [`reconnect_time`: check if after disconnecting from Windows Event Channel and connecting again, the daemon continues reading events from it and reporting them.](https://github.com/wazuh/wazuh-qa/issues/1251)
- [x] [Check if logcollector keeps running once a log is rotated.](https://github.com/wazuh/wazuh-qa/issues/1250)
- [x] [Check `multiline_regex` field](https://github.com/wazuh/wazuh-qa/issues/1252) @damarisg 
- [x] [Test `command` monitoring.](https://github.com/wazuh/wazuh-qa/issues/1236) @mdengra
