### ISSUE TITLE
Remoted tier 0: configuration tests

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh-qa#1061]
In this issue, we need to create tests to cover each option for [remoted](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/remote.html). 
## Input tests
The options from `ossec.conf` must be modified and check there aren't any error
- [x] connection
- [x] port
- [x] protocol
- [ ] allowed-ips
- [ ] denied-ips
- [ ] local_ip
- [ ] ipv6
- [ ] queue_size
- [ ] rids_closing_time
## Output tests
For each option, we need to request its configuration using the API and check if the value from the `ossec.conf` and the value from the API response are the same.

**Comment by BraulioV** [comment]
In this issue, we need to create tests to cover each option for [remoted](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/remote.html). 
- [ ] connection
- [ ] port
- [ ] protocol
- [ ] allowed-ips
- [ ] denied-ips
- [ ] local_ip
- [ ] ipv6
- [ ] queue_size
- [ ] rids_closing_time

**Comment by SpotHound** [comment]
We're working on this on `1061-configuration-tests`

## TODO

- [ ] New test structure for remoted integration tests
- [ ] New functions to compare ossec.conf configuration with active one (API)

**Comment by SpotHound** [comment]
[I've added a new method to check the manager configuration using the Wazuh API ](https://github.com/wazuh/wazuh-qa/commit/964d2a50177206cfeadbf289e35a9ff3d757e0d0)

**Comment by SpotHound** [comment]
We've added first generic tests for a basic configuration that covers port, protocol and mode (secure or syslog).

We've been testing it and work as expected:

![image.png](https://images.zenhubusercontent.com/5aa6bef74b5806bc2bca822d/dc70f2d2-529a-404c-9aec-deb72b6f6685)

Checking that the test fails if, for example, we force the configuration to be UDP:

![image.png](https://images.zenhubusercontent.com/5aa6bef74b5806bc2bca822d/cfcde3e6-47df-48f4-b020-94c14674f988)
![image.png](https://images.zenhubusercontent.com/5aa6bef74b5806bc2bca822d/b1d0daea-dee5-435b-9396-1c3945928279)

**important:** this is because the log will check that the following log appears: `Started (pid: 30487). Listening on port 514/TCP (syslog)` and the information correspond with the configuration introduced. Also, it will make a query to WAZUH API to confirm that the entered value is returned by Wazuh API.

**Comment by BraulioV** [comment]
Closed by #1087 and #1100
