### ISSUE TITLE
Remove import conftest in integration tests

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#1071]
Some tests have unnecessary conftest module import. 

```
from conftest import *
```

This could cause errors in documentation generation along with scalability issues. It should be desirable to remove them.

List of tests with this import:
 - ` tests/integration/test_active_response/test_execd/test_execd_firewall_drop.py`
 -  `tests/integration/test_active_response/test_execd/test_execd_restart.py`
 -  `tests/integration/test_agentd/test_agent_auth_enrollment.py`
 - ` tests/integration/test_agentd/test_agentd_enrollment_params.py`
 -  `tests/integration/test_agentd/test_agentd_multi_server.py`
 -  `tests/integration/test_agentd/test_agentd_parametrized_reconnections.py`
 -  `tests/integration/test_agentd/test_agentd_reconnection.py`

# UPDATE

In addition, the following tasks will be performed on the above tests:
 -  Check for compliance with PEP-8 style guide.
 -  Add missing docstrings.
 -  Add missing documentation in wazuh-qa/doc.

**Comment by mdengra** [comment]
# Tasks performed:
- [x] Remove unneeded `conftest` imports.
- [ ] Check for compliance with PEP-8 style guide.
- [ ] Add missing docstrings.
- [ ] Add missing documentation in `wazuh-qa/doc`.
