### ISSUE TITLE
Remoted integration tests T1: Check manager ACK after receiving the start-up message of the agent

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#1102]
It is necessary to add a new integration test for checking if the manager sends the ACK message after receiving the start-up message of the agent.

The flow between agent and manager is as follows:

<p align="center">
  <img src="https://user-images.githubusercontent.com/23462183/109792263-9cb0fe00-7c13-11eb-889b-851b2245087f.jpg" />
</p>

The test will be based on checking that the manager sends the `ACK` message after receiving the star-up. This will be tested for `TCP`, `UDP`, and both protocols simultaneously.

## Estimated tasks
- [x] **1**: Investigate the communication flow, send the start-up message from the agent simulator, and observe the response sent by the manager.
- [x] **2**: Investigate and implement a way to obtain events received from the agent simulator.
- [x] **3**:  Create test module and configuration files (pytest).
- [x] **4**: Testing and debugging process.
- [x] **5**: Add test documentation

**Comment by jmv74211** [comment]
## Task 1

I have been sending start-up messages from the agent simulator and I have seen that the manager sends a response like the following (message already decrypted and processed):

```
c659fbffee9ba1dcf6b11eeb45c6707a405450000000010:1992:#!-agent ack
```

The test would be based on sending the message and checking that the manager has received a message with  `#!-agent ack` content.

I have been discussing with the QA team how we are going to monitor the events received by the manager. In principle it has been proposed:

- Enable certain flags through class attributes.
- Generate a log for the agent, and use the FileMonitor to see the events received by the agent.
- Create a buffer of messages received of limited size. All messages received will be stored here in the form of a queue.

Finally, it has been decided to implement the 3rd option, to create a buffer for the manager messages.

While this new buffer is being implemented, I am going to start with the 3rd task.

**Comment by jmv74211** [comment]
# Task 2

As a way to monitor the messages received by the agent, a new attribute has been added to the `Agent` class to store these messages.

Its implementation has been carried out through a `monitoring.Queue`, to be able to use the `QueueMonitor` tool.

These changes can be seen here https://github.com/wazuh/wazuh-qa/commit/135bcdca11ad3fcd5da425ec903af8236d2b920f

**Comment by jmv74211** [comment]
# Task 3

To check if the manager sends the ACK message correctly, a new test and configuration has been created.

The initial version is as follows: https://github.com/wazuh/wazuh-qa/commit/563580674fc3760b1c929763653391833bec7823
