### ISSUE TITLE
Remoted integration tests T1: Check if the manager can send an active response command

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#1104]
It is necessary to add a new remoted integration test for checking if the manager sends an active response command to the agent.

## Estimated tasks
- [x] **1**: Investigate the communication flow.
- [x] **2**: Simulate `execd` message in order to send to the agent active response command.
- [x] **3**:  Get with agent simulator active response command sent by the manager
- [x] **4**:  Create test module and configuration files (pytest).
- [x] **5**: Testing and debugging process.
- [x] **6**: Add test documentation

**Comment by Rebits** [comment]
## Task 1

I have investigated the format of the messages between execd and remoted. 

When active response is trigger, execd use `/var/ossec/queue/alerts/ar` socket to communicate with remoted. The message format is the following:#!-execd active-command0 admin ip-address (\d+).(\d+) 44 (agent-name) any->location

**Comment by Rebits** [comment]
## Task 2

Using the message format specified in the task1, we get the following logs from `ossec.log` when execd send an active response command.

`2021/03/04 15:59:30 wazuh-remoted[31027] ar-forward.c:40 at AR_Forward(): DEBUG: Active response request received: (local_source) [] NRN 004 restart-wazuh0 admin 1.1.1.1 1.1 44 (agent) any->localfile`

`2021/03/04 15:59:30 wazuh-remoted[31027] ar-forward.c:99 at AR_Forward(): DEBUG: Active response sent: #!-execd restart-wazuh0 admin 1.1.1.1 1.1 44 (agent) any->localfile`

The test should ensure these logs are shown in `ossec.log`.  The last part of the test should check that the message is sent correctly to the agent.
