### ISSUE TITLE
Remoted integration tests T2:  Connect several agents with different protocols at once.

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#1114]
It is required to create a new integration test for `remoted` to check if all agent communications are correct using different protocols.

The proposed design for this test is as follows:

### Case 1: Send events from agents and monitor queue socket

![Untitled Diagram](https://user-images.githubusercontent.com/23462183/110313521-d3698880-8006-11eb-8b23-addddd7ed16a.png)

In this case, it is proposed:

- Configure the manager's remote to listen over both `TCP` and `UDP`. 
- Connect two agents to the manager. Each of these will use a different communication protocol. 
- Each agent will send a message to the manager, and the test will check that the message has been written to the `queue` socket  (this means that remoted has received it correctly, decrypted it, and written it to the socket for `analysisd` to read).

### Case 2: Send keep-alive messages and monitor the agent's status in the global DB

![Untitled Diagram(1)](https://user-images.githubusercontent.com/23462183/110314280-ef215e80-8007-11eb-893a-e2102f57b80c.png)

-  Configure the manager's remote to listen over both `TCP` and `UDP`. 
- Send periodic keep-alive messages from agents (using different communication protocols).
- Observe if the agent's status is updated to "active" in the global DB.

**UPDATE**

The process of obtaining information through the database has been updated as follows:

![Untitled Diagram(2)](https://user-images.githubusercontent.com/23462183/110597963-8231d400-8181-11eb-881d-2ea7d0b5a1e4.png)

## Estimated tasks:

- [x] **1**: Propose a test design. It is necessary to know which checks need to be performed and the number of agents to be used.
- [x] **2**: Create test module and configuration files (pytest).
  -  [x] Case 1: Send events from agents and monitor queue socket.
  -  [x] Case 2: Send keep-alive messages and monitor the agent's status in the global DB.
- [ ] **3**:  Testing and debugging process.
- [ ] **4**:  Add test documentation.

**Comment by jmv74211** [comment]
# Task 1

I have been thinking about the possible test cases for this test.

The proposed use cases are in the description of the issue.
