### ISSUE TITLE
Scalability tests for Wazuh Manager

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh-qa#1130]
We need to create new tests to extract performance metrics for each daemon, to ensure a correct performance for different environments and configurations.
## Objectives
- [x] Get hardware metrics for each daemon:
    - [x] CPU.
    - [x] Memory (RSS, USS, PSS, SWAP, VMS).
    - [x] Descriptors files.
    - [x] Disk usage.
- [x] Get statistics of the status of the manager during the test
    - [x] Info about the events (total, dropped, how many for syscollector, fim, etc)
    - [x] The status for each queue.
    - [x] Statistis from remoted (events received, TCP sessions, bytes sent and received).
- [x] Get the saturation point for different environments. 
    - [x] Without setting up a cluster. 

## Initial infrastructure for the test
![image.png](https://images.zenhubusercontent.com/5d91c1bf3ab6b200010aecd1/101ae6ed-3fe1-4b03-bd83-61ecbc0324ea)

## Tasks
- [x] [Research to find the best way to generate events to increase the load of the managers](https://github.com/wazuh/wazuh-qa/issues/1133).
- [x] Develop the new tools and features necessary for this test (improvements for the agent_simulator, tools to collect data, etc.)
- [ ] Define metrics to help us to locate the saturation point (when it is considered a manager is under heavy load, response times, queue sizes, maximum ram/cpu allowed, etc).
- [x] [Implement the code to set `labels` to the simulated agents](https://github.com/wazuh/wazuh-qa/pull/1153#pullrequestreview-615199263)
- [x] Define deployment and infrastructure. At the moment, a regular computer (2 cores and 4GB of RAM) supports up to 40 simulated agents with the current implementation of the agent_simulator. So we need to decide how to improve the number of agents in the same host and the infrastructure to deploy thousands of agents.
- [x] [Define a new tool to generate events of a fixed size.](https://app.zenhub.com/workspaces/wazuh---qa-6013ee7425d3d80017069c76/issues/wazuh/wazuh-qa/1132)
- [ ] Jenkins automation.

**Comment by pacoqack** [comment]
We would need to add some statistic information to simulated agents based on `wazuh-agentd.state` content.
