### ISSUE TITLE
Performance test: Add new tools to collect system info and statistics

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh-qa#1131]
Our `monitor.py` from the _stress test_ already collects system info and statistics from Wazuh but we need to refactor this script to be able to re-use it in our performance tests.

## Tasks
- [x] Move it from our Jenkins repository to Wazuh QA
- [x] Refactor the script to be able to monitor just a single daemon or the complete daemon-set.
- [x] Add the data collection from the new `logcollector.state` file.
- [x] Generate data visualizations from the statistics file.

**Comment by BraulioV** [comment]
In this branch [1131-perf-tools](https://github.com/wazuh/wazuh-qa/tree/1131-perf-tools) I have added two new modules to collect the hardware statistics from any Wazuh daemon and collect statistics from Wazuh. There're two new scripts and modules:
- `wazuh-metrics`: this new module implements a class to collect hardware statistics from a daemon. These statistics are logged into a CSV file which contains this info:
    - Timestamp
    - CPU(%)
    - VMS
    - RSS
    - USS
    - PSS
    - SWAP
    - File descriptors
    - Read operations
    - Write operations
    - Disk read
    - Disk written
    - Disk usage(%)
- `wazuh-statistics`: this new module implements a class that parses the `.state` files from Wazuh and collects the statistics from there. As `wazuh-metrics`, these statistics are logged into a CSV file. It can collect info from:
    - wazuh-analysisd.state
    - wazuh-remoted.state
    - wazuh-agentd.state
    - wazuh-logcollector.state (WIP)

To use these tools, you only need to install the `wazuh-qa` module and its dependencies, and then, use the scripts as follow:
```shellsession
# pip3 install -r requirements.txt
# cd deps/wazuh_testing
# python3 setup.py install
# wazuh-metrics args
# wazuh-statistics args
```
Once the module is installed, both scripts are installed in `/usr/local/bin`, so you can use them directly from the shell in UNIX and Windows OS.

For example:
```shellesession
# # To collect Wazuh statistics from wazuh-remoted
# wazuh-statistics -t remote -s 5
# # To collect hardware metrics for different daemons
# wazuh-metrics -p wazuh-remoted wazuh-apid wazuh-logcollector -s 3 -u MB
```
