### ISSUE TITLE
Research about the manager's queues and how to properly load those queues

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh-qa#1133]
We need to improve our manager simulator module to properly load manager analysisd's queues. 

## Objective 
Define all analysisd's queues and how to load them. Then, add the required changes to the agent simulator module to be sure that all the existing and new modules work properly and generate the appropriate load for those analysisd's queues.

## Tasks.

- [x] Define the manager's analysisd's queues. 
- [x] Define the event format for each queue.
- [x] Make sure the keepalive module work as expected on the agent simulator.
- [x] Make sure the fim module work as expected on the agent simulator.
- [x] Make sure the fim_integrity module work as expected on the agent simulator.
- [x] Make sure the syscollector module work as expected on the agent simulator.
- [x] Make sure the rootcheck module work as expected on the agent simulator.
- [x] Make sure the receive_messages module work as expected on the agent simulator.
- [x] Define required new modules to create.
- [x] Create those required new modules.

@Rebits and me (@pacoqack) will be working on branch `1133-queues`

**Comment by pacoqack** [comment]
# Analysisd's queues

The analysisd queues could be enumerated from the `analsysisd.state` file. They are:

## Syscheck events

Receive syscheck events that could be simulated using `fim` and `fim_integrity` modules.

## Syscollector events

## Rootcheck events

## SCA events

## Hostinfo events

## Winevt events

## Firewall logs

## Other events

**Comment by pacoqack** [comment]
# Other changes in agent simulator

It would be required a better approach to enable/disable modules on agent definition, as well as their EPS. 

![image.png](https://images.zenhubusercontent.com/5aa6bef74b5806bc2bca822d/f1a8bd3d-7738-4939-83f6-fc1d4890d651)

Instead of the current way to do this, with some arbitrary modules being modified from the agent constructor... we will introduce two new parameters, one for active modules and others for their EPS.

**Comment by pacoqack** [comment]
# Syscollector module required changes

Currently, our syscollector modules read example events from a file and send them at a certain rate (EPS) one time for each selected interval. 

That's is not very useful because we plan to overload the manager by sending thons of events.  If I select an EPS of 500 events per second **I expect this module to send 500 events per second**. Also, we don't want to maintain a file with file examples, we want the messages to be generated automatically.

**Comment by pacoqack** [comment]
I'll continue with firewall logs

**Comment by pacoqack** [comment]
We've been talking with core team about this issue and we've decided that we'll only stress the queues defined in this switch statement: https://github.com/wazuh/wazuh/blob/2a96afbbafae5e4086c8938f431487aae0297a42/src/analysisd/analysisd.c#L1184-L1393

They are:

- [x] SYSCHECK_MQ
- [x] ROOTCHECK_MQ
- [x] SCA_MQ
- [x] SYSCOLLECTOR_MQ
- [x] HOSTINFO_MQ
- [ ] WIN_EVT_MQ
- [ ] DBSYNC_MQ
- [ ] UPGRADE_MQ
- [ ] Others
