### ISSUE TITLE
Performance test: agent_simulator horizontal scalability definition

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh-qa#1134]
At the moment, in our testing, a host with 4 cores and 8 GB of RAM can run up to ~50 simulated agents simultaneously without issues, but for our testing, we need to complete several tasks.

## Tasks
- [x] Define the horizontal scalability of the agent_simulator tool in AWS instances. 
    - [x] Tx instances.
    - [x] Cx instances.
    - [x] Mx instances.
- [x] Identify any bottleneck in this tool or bug.
- [x] Propose new improvements.

**Comment by BraulioV** [comment]
At the moment, in our testing, a host with 4 cores and 8 GB of RAM can run up to ~50 simulated agents simultaneously without issues, but for our testing, we need to complete several tasks.

## Tasks
- [ ] Define the horizontal scalability of the agent_simulator tool in AWS instances. 
    - [ ] Tx instances.
    - [ ] Cx instances.
    - [ ] Mx instances.
- [ ] Identify any bottleneck in this tool or bug.
- [ ] Propose new improvements.

**Comment by jmv74211** [comment]
I have been researching the requirements of this issue and thinking about the different solutions to carry it out.

My proposal is to create a set of tools that allow us to **deploy a number of simulated agents** in an environment and **generate a certain number of events per second**. This traffic will be carried out during a defined time interval. During this time the CPU and memory usage on the host that is supporting this agent deployment will be **monitored**.

On the other hand, a series of resources and characteristics will also be monitored in the manager while all the traffic is being received by the simulated agents. In principle, it is proposed to monitor the following (manager side):

- CPU.
- Mem usage.
- discard_count (from `wazuh-remoted.state`).
- events_edps (from `wazuh-analysisd.state`).
- events_dropped (from `wazuh-analysisd.state`).

This analysis by the agent as well as by the manager will be repeated for different variables such as:

- Manager instance type.
- Type of machine instance for the agents.
- Manager instance family.
- Machine instance family for agents.
- Number of events per second.
- Number of agents.


## Estimated tasks
- [x] **1**: Investigate issue requirements and propose a design.

**Comment by jmv74211** [comment]
# Metrics

## Legend

- **Agents number**: Number of agents connected.
- **EPS/agent**: Events per second sent by each agent.
- **A_CPU**: CPU usage by the host machine simulating all agents.
- **A_MEM**: Memory usage by the host machine simulating all agents.
- **M_CPU**: CPU usage by the machine hosting the manager.
- **M_MEM**: Memory usage by the machine hosting the manager.
- **M_EPS**: Events per second processed by manager's analysisd (`events_edps` from `wazuh-analysisd.state`).
- **M_EVD**: Number of dropped events (`events_dropped` from wazuh-analysisd.state).
- **M_RMD**: Connections discarded by manager's remoted (`discard_count` from `wazuh-remoted.state`).
- **M_TCPS**: Number of active manager sessions.

## Metrics by AWS Instance Type

### t2.medium

**Technical Specifications**

| vCPUs | Memory (GiB) | Network performance | 
|-----------|--------------------|-------------------------------|
|  2    |    4         |   Low to Moderate   | 

**Collected data**

| Agents number | EPS/agent | A_CPU | A_MEM | M_CPU | M_MEM | M_EPS | M_EVD | M_RMD | M_TCPS |
|---------------|-----------|-------|-------|-------|-------|-------|-------|-------|--------|
|  2            | 1000      |  41%  |  11%  |  32%  | 19%   | 2000  | 0     | 0     | 2      |
|  3            | 1000      |  62%  |  11%  |  49%  | 20%   | 3000  | 0     | 0     | 3      | 
|  4            | 1000      |  84%  |  12%  |  65%  | 20%   | 4000  | 0     | 0     | 4      | 
|  5            | 1000      |  87%  |  13%  |  65%  | 20%   | 4042  | 0     | 0     | 5      | 
|  6            | 1000      |  67%  |  14%  |  51%  | 20%   | 3107  | 0     | 0     | 6      |
|  100          | 50        |  95%  |  91%  |  72%  | 20%   | 3780  | 0     | 0     | 100    |
|  200          | 25        |  -    |  -    |  -    |  -    |  -    | -     | -     | 0      |

**Comment by jmv74211** [comment]
### m4.large

**Technical Specifications**

| vCPUs | CPU frequency | Memory (GiB) | Network performance | Price |
|-----------|----------------------|--------------------|------------------------------|-----|
|  2    | 2.4 GHz   | 8         |   Moderate   | $0.10 per Hour |

**Collected data**

| AN  | EPS/agent |  P       | A_CPU | A_MEM | M_CPU | M_MEM | M_EPS | B_RCV/s  | M_EVD | M_RMD | M_TCPS |
|-----|-----------|----------|-------|-------|-------|-------|-------|----------|-------|-------|--------|
|  2  | 1000      | 100% 🟢  | 69%   |  8%   |  44%  | 12%   | 2000  | 978126   |0      | 0     | 2      |
|  3  | 1000      | 56% 🔴   | 57%   |  7%   |  34%  | 10%   | 1688  | 809663   |0      | 0     | 3      |
|  25 | 100       | 99% 🟢   | 89%   |  15%  |  45%  | 11%   | 2477  | 1215170  | 0     | 0     | 25     |
|  50 | 70        | 69% 🔴   | 93%   |  25%  |  49%  | 11%   | 2432  | 1194995  | 0     | 0     | 50     |

**Comment by jmv74211** [comment]
### c5.large

**Technical Specifications**

| vCPUs | CPU frequency | Memory (GiB) | Network performance | Price           |
|-------|-------------- |--------------|---------------------|-----------------|
|  2    | 3.4 GHz       | 4            |  Up to 10 Gigabit   | $0.085 per Hour |

**Collected data**

| AN  | EPS/agent |  P       | A_CPU | A_MEM | M_CPU | M_MEM | M_EPS | B_RCV/s  | M_EVD | M_RMD | M_TCPS |
|-----|-----------|----------|-------|-------|-------|-------|-------|----------|-------|-------|--------|
|  3  | 1000      | 99% 🟢   | 69%   |  16%  |  41%  | 20%   | 2952  | 1417365  |0      | 0     | 3      |
|  4  | 1000      | 84% 🟡   | 80%   |  16%  |  47%  | 20%   | 3380  | 1670830  |0      | 0     | 4      |
|  25 | 100       | 99% 🟢   | 61%   |  29%  |  29%  | 21%   | 2459  | 1214575  |0      | 0     | 25     |
|  50 | 100       | 68% 🔴   | 90%   |  51%  |  48%  | 24%   | 3421  | 1794475  |0      | 0     | 50     |

**Comment by jmv74211** [comment]
After having tested some types of families and their almost smaller instances, it has been decided that the **best choice for now are `t.x` and `c.x`**.

Looking at the above data, it appears that a higher `evps/resources` ratio is achieved with `t2.medium`, but given the nature of the `t-family`, this benefit may not be persistent, but rather when making intensive cpu usage over a period of time, it causes us to run out of credits and limit the amount of CPU, decreasing the expected performance.

This has been demonstrated as follows: Two jobs have been launched in a `t2.medium` and a `c5.large` with 5 agents generating 1000 events per second during 1h 30m. The results obtained are as follows:

**t2.medium**

![manager_n5_e1000](https://user-images.githubusercontent.com/23462183/111808090-f41dc200-88d3-11eb-9a13-4c9ad6c831e3.png)

**c5.large**

![manager_n5_e1000](https://user-images.githubusercontent.com/23462183/111808199-10216380-88d4-11eb-823d-5be6fd775808.png)

As can be seen, the initial performance of `t2.medium` is higher, but as we run out of credits, it drops considerably, being worse than `c5.large`.

With this we know that **for short duration tests, the most convenient will be to use instances of type `tx` and for longer duration tasks use instances of type `cx`**.

Next, I will continue to take metrics for more powerful instance types, to allow us to generate a larger number of agents and events per second.

**Comment by jmv74211** [comment]
After deciding that in most cases, we will use instances of type `c.x` (as long as the test duration exceeds a threshold that we have to set), I have been investigating the load and agents that we can generate with `c5.xlarge` and `c5.2xlarge`.

Below, I show the obtained results:

### c5.xlarge

**Technical Specifications**

| vCPUs | CPU frequency | Memory (GiB) | Network performance | Price           |
|-------|-------------- |--------------|---------------------|-----------------|
|  4    | 3.4 GHz       | 8            |  Up to 10 Gigabit   | $0.17 per Hour |


| AN  | EPS/agent |  P       | A_CPU | A_MEM | M_CPU | M_MEM | M_EPS | B_RCV/s  | M_EVD | M_RMD | M_TCPS |
|-----|-----------|----------|-------|-------|-------|-------|-------|----------|-------|-------|--------|
|  7  | 1000      | 98% 🟢   | 80%   |  8%   |  52%  | 11%   | 6866  | 3349351  |0      | 0     | 7      |
|  8  | 1000      | 91% 🟡   | 87%   |  10%  |  55%  | 11%   | 7301  | 3586004  |0      | 0     | 8      |
|  9  | 1000      | 60% 🔴   | 62%   |  10%  |  40%  | 12%   | 5474  | 2691309  |0      | 0     | 9      |
| 100 | 70        | 98% 🟢   | 85%   |  49%  |  48%  | 14%   | 6858  | 3374758  |0      | 0     | 100    |
| 150 | 47        | 99% 🟡   | 87%   |  71%  |  48%  | 14%   | 6951  | 3379834  |336    | 0     | 150    |
| 200 | 35        | 86% 🔴   | 86%   |  92%  |  45%  | 14%   | 6018  | 3221077  |2066   | 0     | 200    |


### c5.2xlarge

**Technical Specifications**

| vCPUs | CPU frequency | Memory (GiB) | Network performance | Price           |
|-------|-------------- |--------------|---------------------|-----------------|
|  8    | 3.4 GHz       | 16           |  Up to 10 Gigabit   | $0.34 per Hour  |

| AN  | EPS/agent |  P       | A_CPU | A_MEM | M_CPU | M_MEM | M_EPS | B_RCV/s  | M_EVD | M_RMD | M_TCPS |
|-----|-----------|----------|-------|-------|-------|-------|-------|----------|-------|-------|--------|
|  12 | 1000      | 99% 🟢   | 68%   |  6%   |  43%  | 6%    | 11852 | 5830194  |0      | 0     | 12     |
|  15 | 1000      | 99% 🟡   | 86%   |  7%   |  54%  | 5%    | 14524 | 7233482  |663    | 0     | 15     |
|  16 | 1000      | 79% 🔴   | 88%   |  7%   |  44%  | 7%    | 12801 | 7156441  |12623  | 0     | 16     |
| 150 | 70        | 99% 🟢   | 52%   |  36%  |  37%  | 11%   | 10283 | 5072221  |0      | 0     | 150    |
| 200 | 75        | 87% 🔴   | 96%   |  46%  |  46%  | 7%    | 13046 | 6986362  |5448   | 0     | 200    |

Observing the results, and comparing the performance/price ratio, we have decided to use mostly instance `c5.xlarge`, replicating it `n` times if necessary.

With this instance type, we will use the following data to calculate the number of eps per second and agents supported per instance:

- Max eps: 7000
- Optimal combinations of agents and eps:
  - n_agents = 7, eps/agent = 1000
  - n_agents = 100, eps/agent = 70

(It remains to be determined how many agents at most we can simulate with a minimum load of 1 eps.)


In addition, I have been investigating with Braulio the possible spikes in the eps of the graphs and why events are being dropped at certain points.

We have seen in the `ossec.log` messages like the following one:

```
2021/03/22 09:57:59 wazuh-logcollector: INFO: Monitoring full output of command(360): last -n 20
2021/03/22 09:59:48 wazuh-analysisd: WARNING: Syscheck decoder queue is full.
2021/03/22 10:10:18 wazuh-remoted: WARNING: Message queue is full (131072). Events may be lost.
```

This means that the event queue is filling up (in this case from syscheck, since all the events sent are of this type), and it is not possible to analyze so many events.

As a possible solution is to increase this queue size, although we have to see the implications of this action.

```
# Syscheck queue size
syscheck_queue_size='16384'
```

**Comment by jmv74211** [comment]
Taking into account the following data:

- Max eps/simulated_agent: 7000
- Max number of agents = 200/agent_host (20 margin has been left for possible improvements in agent simulator that may increase memory usage).
- The maximum number of eps with the largest number of agents is 200 agents each reporting to 15eps.

Below is a summary table showing the number of resources and estimated cost for the case of maximizing the number of events per second and agents.

**Maximization of the number of connected and reporting agents**

| N agents   | Max eps    | N instances |Price/h  |
|------------|------------|-------------|---------|
|    1       |  7000      |   1         | 0.17$   |
|    200     |  3000      |   1         | 0.17$   |
|    500     |  7500      |   3         | 0.51$   |
|    1000    |  15000     |   5         | 0.85$   |
|    5000    |  75000     |   25        | 4.25$   |
|    10000   |  150000    |   50        | 8.5$    |
|    20000   |  300000    |   100       | 17$     |
|    50000   |  750000    |   250       | 42.5$   |
|    100000  |  1500000   |   500       | 85$     |

**Maximization of the number of events per second**

| Max eps    | N agents    | N instances | Price/h  |
|------------|-------------|-------------|----------|
|  1         | 1           | 1           | 0.17$    |
|  7000      | 100         | 1           | 0.17$    |
|  700000    | 500         | 3           | 0.51$    |
|  3500000   | 1000        | 5           | 0.85$    | 
|  7000000   | 5000        | 25          | 4.25$    |
|  70000000  | 10000       | 50          | 8.5$     |
|  140000000 | 20000       | 100         | 17$      |
|  350000000 | 50000       | 250         | 42.5$    |
|  700000000 | 100000      | 500         | 85$      |

**Comment by BraulioV** [comment]
Great job @jmv74211. We will use this data to continue with #1135 and #1136.

Finally, I'm closing this issue since all the main tasks have been covered.
