### ISSUE TITLE
Syscollector module should create events dinamically instead of read them from a file

### ISSUE THREAD

**Issue by pacoqack** [wazuh/wazuh-qa#1156]
## Objective

Our agent simulator module has a submodule for syscollector events which read log samples from a file and send them as events to the manager.

This limits the number of events that could be sent by this module and also doesn't generate alerts on the manager. 

We want to modify this behaviour so the events are generated dynamically from a pattern, with a correct timestamp, changing values, etc... and without the requirement of maintaining a file with log samples. 

## TODO

- [ ] Make a list of all the different type of event generated by the syscollector (packages, process, ports, network...) 
- [ ] Make a template for each type of event
- [ ] Modify the module so it generated new events dynamically of all available kinds  
- [ ] The module should send `EPS * (interval *0.5)` events on each interval.
- [ ] If the interval is set to 1 or less, the interval wait must be skipped and the module should send events continuously.

**Comment by Rebits** [comment]
List of events generated by the syscollector module

### Process

After a batch of process events syscollector return a `process_end` event:

```
2021 Mar 18 07:55:19 (centos3) any->syscollector {"type":"process","ID":1058207822,"timestamp":"2021/03/18 07:55:18","process":{"pid":9275,"name":"ls","state":"Z","ppid":9090,"utime":0,"stime":0,"euser":"root","ruser":"root","suser":"root","egroup":"root","rgroup":"root","sgroup":"root","fgroup":"root","priority":20,"nice":0,"size":0,"vm_size":0,"resident":0,"share":0,"start_time":244536,"pgrp":9090,"session":9090,"nlwp":1,"tgid":9275,"tty":0,"processor":0}}

2021 Mar 18 07:55:19 (centos3) any->syscollector {"type":"process_end","ID":1058207822,"timestamp":"2021/03/18 07:55:18"}

```

## Network

After a batch of network events syscollector return a `network_end` event:

```
2021 Mar 18 07:29:50 (centos3) any->syscollector {"type":"network","ID":215933738,"timestamp":"2021/03/18 07:29:51","iface":{"name":"eth1","type":"ethernet","state":"up","MAC":"08:00:27:6f:cc:74","tx_packets":986,"rx_packets":893,"tx_bytes":354254,"rx_bytes":77131,"tx_errors":0,"rx_errors":0,"tx_dropped":0,"rx_dropped":0,"MTU":1500,"IPv4":{"address":["172.17.1.13"],"netmask":["255.255.255.0"],"broadcast":["172.17.1.255"],"gateway":"unknown","DHCP":"disabled"},"IPv6":{"address":["fe80::a00:27ff:fe6f:cc74"],"netmask":["ffff:ffff:ffff:ffff::"],"DHCP":"enabled"}}}

2021 Mar 18 07:29:50 (centos3) any->syscollector {"type":"network_end","ID":215933738,"timestamp":"2021/03/18 07:29:51"}
 
```

## OS

``` 
2021 Mar 18 07:29:50 (centos3) any->syscollector {"type":"OS","ID":297063795,"timestamp":"2021/03/18 07:29:51","inventory":{"os_name":"CentOS Linux","os_major":"8","os_minor":"3","os_version":"8.3","os_platform":"centos","sysname":"Linux","hostname":"centos3","release":"4.18.0-240.1.1.el8_3.x86_64","version":"#1 SMP Thu Nov 19 17:20:08 UTC 2020","architecture":"x86_64"}}
``` 

## Hardware


``` 
2021 Mar 18 07:29:50 (centos3) any->syscollector {"type":"hardware","ID":2108659030,"timestamp":"2021/03/18 07:29:51","inventory":{"board_serial":"0","cpu_name":"AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx","cpu_cores":1,"cpu_MHz":2295.686,"ram_total":828084,"ram_free":60488,"ram_usage":93}}
```

## Port

After a batch of port events syscollector return a `port_end` event:

```
2021 Mar 18 07:37:03 (centos3) any->syscollector {"type":"port","ID":1391059292,"timestamp":"2021/03/18 07:37:03","port":{"protocol":"tcp","local_ip":"0.0.0.0","local_port":22,"remote_ip":"0.0.0.0","remote_port":0,"tx_queue":0,"rx_queue":0,"inode":22273,"state":"listening"}}

2021 Mar 18 07:37:03 (centos3) any->syscollector {"type":"port","ID":1391059292,"timestamp":"2021/03/18 07:37:03","port":{"protocol":"tcp","local_ip":"172.17.1.13","local_port":37822,"remote_ip":"172.17.1.11","remote_port":1514,"tx_queue":164,"rx_queue":0,"inode":453955,"state":"established"}}

2021 Mar 18 07:37:03 (centos3) any->syscollector {"type":"port","ID":1391059292,"timestamp":"2021/03/18 07:37:03","port":{"protocol":"udp","local_ip":"127.0.0.1","local_port":323,"remote_ip":"0.0.0.0","remote_port":0,"tx_queue":0,"rx_queue":0,"inode":21303}}

2021 Mar 18 07:37:03 (centos3) any->syscollector {"type":"port_end","ID":1391059292,"timestamp":"2021/03/18 07:37:03"}
```

**Comment by pacoqack** [comment]
Good job, I've increased the estimation from 3 to 5 as it seems that his issue could be a little most challenging than I would have expected.
