### ISSUE TITLE
Add SCA module to agent simulator

### ISSUE THREAD

**Issue by pacoqack** [wazuh/wazuh-qa#1162]
# Objective
Make agent simulator able to send SCA messages to the manager in order to stress out the "SCA events" analysisd queue.

## TODO
- [x] Recopilate some examples of SCA events.
- [x] Define an SCA event template that could be randomized to generate multiple different events.
- [x] Add an SCA module able to send those random events to the manager on the agent simulator.

**Comment by pacoqack** [comment]
# Log samples
## summary log
```
{\"type\":\"summary\",\"scan_id\":1947643412,\"name\":\"CIS Benchmark for CentOS Linux 8\",\"policy_id\":\"cis_centos8_linux\",\"file\":\"cis_centos8_linux.yml\",\"description\":\"This document provides prescriptive guidance for establishing a secure configuration posture for CentOS Linux 8 systems running on x86 and x64 platforms. This document was tested against CentOS Linux 8\",\"references\":\"https://www.cisecurity.org/cis-benchmarks/\",\"passed\":90,\"failed\":94,\"invalid\":2,\"total_checks\":186,\"score\":48.913043975830078,\"start_time\":1616067879,\"end_time\":1616067883,\"hash\":\"2b3765f9c3800aebdfeee1a317a7a14dcf11f7326674b028bc6f4824725579a2\",\"hash_file\":\"2dd71c1696661dba6f1c6a409dc9e4a303028ba9d20c0e13b962ffe435490988\",\"force_alert\":\"1\",\"force_alert\":\"1\"}
```

## Check
```
{\"type\":\"check\",\"id\":1947643412,\"policy\":\"CIS Benchmark for CentOS Linux 8\",\"policy_id\":\"cis_centos8_linux\",\"check\":{\"id\":6685,\"title\":\"Ensure root is the only UID 0 account\",\"description\":\"Any account with UID 0 has superuser privileges on the system.\",\"rationale\":\"This access must be limited to only the default root account and only from the system console. Administrative access must be through an unprivileged account using an approved mechanism as noted in Item 5.6 Ensure access to the su command is restricted.\",\"remediation\":\"Remove any users other than root with UID 0 or assign them a new UID if appropriate.\",\"compliance\":{\"cis\":\"6.2.6\",\"cis_csc\":\"5.1\",\"pci_dss\":\"10.2.5\",\"hipaa\":\"164.312.b\",\"nist_800_53\":\"AU.14,AC.7\",\"gpg_13\":\"7.8\",\"gdpr_IV\":\"35.7,32.2\",\"tsc\":\"CC6.1,CC6.8,CC7.2,CC7.3,CC7.4\"},\"rules\":[\"f:/etc/passwd -> !r:^# && !r:^\\\\s*\\\\t*root: && r:^\\\\w+:\\\\w+:0:\"],\"condition\":\"none\",\"file\":\"/etc/passwd\",\"result\":\"passed\"}}
```

**Comment by pacoqack** [comment]
```
** Alert 1616429864.15273543: - sca,gdpr_IV_35.7.d,pci_dss_2.2,nist_800_53_CM.1,tsc_CC7.1,tsc_CC7.2,
2021 Mar 22 16:17:44 (centos8a) any->sca
Rule: 19008 (level 3) -> 'CIS Benchmark for CentOS Linux 8: Ensure permissions on /etc/gshadow- are configured'
{"type":"check","id":1561419087,"policy":"CIS Benchmark for CentOS Linux 8","policy_id":"cis_centos8_linux","check":{"id":6680,"title":"Ensure permissions on /etc/gshadow- are configured","description":"The /etc/gshadow- file is used to store backup information about groups that is critical to the security of those accounts, such as the hashed password and other security information.","rationale":"It is critical to ensure that the /etc/gshadow- file is protected from unauthorized access. Although it is protected by default, the file permissions could be changed either inadvertently or through malicious actions.","remediation":"Run the one of the following chown commands as appropriate and the chmod to set permissions on /etc/gshadow- : # chown root:root /etc/gshadow-  # chown root:shadow /etc/gshadow-  # chmod o-rwx,g-rw /etc/gshadow-","compliance":{"cis":"6.1.9","cis_csc":"16.4","pci_dss":"2.2.4","nist_800_53":"CM.1","tsc":"CC5.2"},"rules":["c:stat /etc/gshadow- -> r:Access:\\s*\\(0\\d\\d0/-\\w\\w-\\w-----\\)\\s*Uid:\\s*\\(\\s*\\t*0/\\s*\\t*root\\)\\s*\\t*Gid:\\s*\\(\\s*\\t*0/\\s*\\t*root\\)|Access:\\s*\\(0\\d\\d0/-\\w\\w-\\w-----\\)\\s*Uid:\\s*\\(\\s*\\t*0/\\s*\\t*root\\)\\s*\\t*Gid:\\s*\\(\\s*\\t*\\w*/\\s*\\t*shadow\\)"],"condition":"all","command":"stat /etc/gshadow-","result":"passed"}}
sca.type: check
sca.scan_id: 1561419087
sca.policy: CIS Benchmark for CentOS Linux 8
sca.check.id: 6680
sca.check.title: Ensure permissions on /etc/gshadow- are configured
sca.check.description: The /etc/gshadow- file is used to store backup information about groups that is critical to the security of those accounts, such as the hashed password and other security information.
sca.check.rationale: It is critical to ensure that the /etc/gshadow- file is protected from unauthorized access. Although it is protected by default, the file permissions could be changed either inadvertently or through malicious actions.
sca.check.remediation: Run the one of the following chown commands as appropriate and the chmod to set permissions on /etc/gshadow- : # chown root:root /etc/gshadow-  # chown root:shadow /etc/gshadow-  # chmod o-rwx,g-rw /etc/gshadow-
sca.check.compliance.cis: 6.1.9
sca.check.compliance.cis_csc: 16.4
sca.check.compliance.pci_dss: 2.2.4
sca.check.compliance.nist_800_53: CM.1
sca.check.compliance.tsc: CC5.2
sca.check.command: ["stat /etc/gshadow-"]
sca.check.result: passed

** Alert 1616429864.15276205: - sca,gdpr_IV_35.7.d,pci_dss_2.2,nist_800_53_CM.1,tsc_CC7.1,tsc_CC7.2,
2021 Mar 22 16:17:44 (centos8a) any->sca
Rule: 19008 (level 3) -> 'CIS Benchmark for CentOS Linux 8: Ensure password fields are not empty'
{"type":"check","id":1561419087,"policy":"CIS Benchmark for CentOS Linux 8","policy_id":"cis_centos8_linux","check":{"id":6681,"title":"Ensure password fields are not empty","description":"An account with an empty password field means that anybody may log in as that user without providing a password.","rationale":"All accounts must have passwords or be locked to prevent the account from being used by an unauthorized user.","remediation":"If any accounts in the /etc/shadow file do not have a password, run the following command to lock the account until it can be determined why it does not have a password: passwd -l <username> || Also, check to see if the account is logged in and investigate what it is being used for to determine if it needs to be forced off.","compliance":{"cis":"6.2.1","cis_csc":"4.4","pci_dss":"8.2","tsc":"CC6.1"},"rules":["f:/etc/shadow -> !r:^# && r:^\\w+::"],"condition":"none","file":"/etc/shadow","result":"passed"}}
sca.type: check
sca.scan_id: 1561419087
sca.policy: CIS Benchmark for CentOS Linux 8
sca.check.id: 6681
sca.check.title: Ensure password fields are not empty
sca.check.description: An account with an empty password field means that anybody may log in as that user without providing a password.
sca.check.rationale: All accounts must have passwords or be locked to prevent the account from being used by an unauthorized user.
sca.check.remediation: If any accounts in the /etc/shadow file do not have a password, run the following command to lock the account until it can be determined why it does not have a password: passwd -l <username> || Also, check to see if the account is logged in and investigate what it is being used for to determine if it needs to be forced off.
sca.check.compliance.cis: 6.2.1
sca.check.compliance.cis_csc: 4.4
sca.check.compliance.pci_dss: 8.2
sca.check.compliance.tsc: CC6.1
sca.check.file: ["/etc/shadow"]
sca.check.result: passed

** Alert 1616429864.15278361: - sca,gdpr_IV_35.7.d,pci_dss_2.2,nist_800_53_CM.1,tsc_CC7.1,tsc_CC7.2,
2021 Mar 22 16:17:44 (centos8a) any->sca
Rule: 19008 (level 3) -> 'CIS Benchmark for CentOS Linux 8: Ensure no legacy "+" entries exist in /etc/passwd'
{"type":"check","id":1561419087,"policy":"CIS Benchmark for CentOS Linux 8","policy_id":"cis_centos8_linux","check":{"id":6682,"title":"Ensure no legacy \"+\" entries exist in /etc/passwd","description":"The character + in various files used to be markers for systems to insert data from NIS maps at a certain point in a system configuration file. These entries are no longer required on most systems, but may exist in files that have been imported from other platforms.","rationale":"These entries may provide an avenue for attackers to gain privileged access on the system.","remediation":"Remove any legacy '+' entries from /etc/passwd if they exist.","compliance":{"cis":"6.2.2","cis_csc":"16.2","pci_dss":"2.2.3","nist_800_53":"CM.1","gpg_13":"4.3","gdpr_IV":"35.7.d","hipaa":"164.312.b","tsc":"CC5.2"},"rules":["f:/etc/passwd -> !r:^# && r:^+:"],"condition":"none","file":"/etc/passwd","result":"passed"}}
sca.type: check
sca.scan_id: 1561419087
sca.policy: CIS Benchmark for CentOS Linux 8
sca.check.id: 6682
sca.check.title: Ensure no legacy "+" entries exist in /etc/passwd
sca.check.description: The character + in various files used to be markers for systems to insert data from NIS maps at a certain point in a system configuration file. These entries are no longer required on most systems, but may exist in files that have been imported from other platforms.
sca.check.rationale: These entries may provide an avenue for attackers to gain privileged access on the system.
sca.check.remediation: Remove any legacy '+' entries from /etc/passwd if they exist.
sca.check.compliance.cis: 6.2.2
sca.check.compliance.cis_csc: 16.2
sca.check.compliance.pci_dss: 2.2.3
sca.check.compliance.nist_800_53: CM.1
sca.check.compliance.gpg_13: 4.3
sca.check.compliance.gdpr_IV: 35.7.d
sca.check.compliance.hipaa: 164.312.b
sca.check.compliance.tsc: CC5.2
sca.check.file: ["/etc/passwd"]
sca.check.result: passed

** Alert 1616429864.15280524: - sca,gdpr_IV_35.7.d,pci_dss_2.2,nist_800_53_CM.1,tsc_CC7.1,tsc_CC7.2,
2021 Mar 22 16:17:44 (centos8a) any->sca
Rule: 19008 (level 3) -> 'CIS Benchmark for CentOS Linux 8: Ensure no legacy "+" entries exist in /etc/shadow'
{"type":"check","id":1561419087,"policy":"CIS Benchmark for CentOS Linux 8","policy_id":"cis_centos8_linux","check":{"id":6683,"title":"Ensure no legacy \"+\" entries exist in /etc/shadow","description":"The character + in various files used to be markers for systems to insert data from NIS maps at a certain point in a system configuration file. These entries are no longer required on most systems, but may exist in files that have been imported from other platforms.","rationale":"These entries may provide an avenue for attackers to gain privileged access on the system.","remediation":"Remove any legacy '+' entries from /etc/shadow if they exist.","compliance":{"cis":"6.2.4","cis_csc":"16.2","pci_dss":"2.2.3","nist_800_53":"CM.1","gpg_13":"4.3","gdpr_IV":"35.7.d","hipaa":"164.312.b","tsc":"CC5.2"},"rules":["f:/etc/shadow -> !r:^# && r:^+:"],"condition":"none","file":"/etc/shadow","result":"passed"}}
sca.type: check
sca.scan_id: 1561419087
sca.policy: CIS Benchmark for CentOS Linux 8
sca.check.id: 6683
sca.check.title: Ensure no legacy "+" entries exist in /etc/shadow
sca.check.description: The character + in various files used to be markers for systems to insert data from NIS maps at a certain point in a system configuration file. These entries are no longer required on most systems, but may exist in files that have been imported from other platforms.
sca.check.rationale: These entries may provide an avenue for attackers to gain privileged access on the system.
sca.check.remediation: Remove any legacy '+' entries from /etc/shadow if they exist.
sca.check.compliance.cis: 6.2.4
sca.check.compliance.cis_csc: 16.2
sca.check.compliance.pci_dss: 2.2.3
sca.check.compliance.nist_800_53: CM.1
sca.check.compliance.gpg_13: 4.3
sca.check.compliance.gdpr_IV: 35.7.d
sca.check.compliance.hipaa: 164.312.b
sca.check.compliance.tsc: CC5.2
sca.check.file: ["/etc/shadow"]
sca.check.result: passed

** Alert 1616429864.15282687: - sca,gdpr_IV_35.7.d,pci_dss_2.2,nist_800_53_CM.1,tsc_CC7.1,tsc_CC7.2,
2021 Mar 22 16:17:44 (centos8a) any->sca
Rule: 19008 (level 3) -> 'CIS Benchmark for CentOS Linux 8: Ensure no legacy "+" entries exist in /etc/group'
{"type":"check","id":1561419087,"policy":"CIS Benchmark for CentOS Linux 8","policy_id":"cis_centos8_linux","check":{"id":6684,"title":"Ensure no legacy \"+\" entries exist in /etc/group","description":"The character + in various files used to be markers for systems to insert data from NIS maps at a certain point in a system configuration file. These entries are no longer required on most systems, but may exist in files that have been imported from other platforms.","rationale":"These entries may provide an avenue for attackers to gain privileged access on the system.","remediation":"Remove any legacy '+' entries from /etc/group if they exist.","compliance":{"cis":"6.2.5","cis_csc":"16.2","pci_dss":"2.2.3","nist_800_53":"CM.1","gpg_13":"4.3","gdpr_IV":"35.7.d","hipaa":"164.312.b","tsc":"CC5.2"},"rules":["f:/etc/group -> !r:^# && r:^+:"],"condition":"none","file":"/etc/group","result":"passed"}}
sca.type: check
sca.scan_id: 1561419087
sca.policy: CIS Benchmark for CentOS Linux 8
sca.check.id: 6684
sca.check.title: Ensure no legacy "+" entries exist in /etc/group
sca.check.description: The character + in various files used to be markers for systems to insert data from NIS maps at a certain point in a system configuration file. These entries are no longer required on most systems, but may exist in files that have been imported from other platforms.
sca.check.rationale: These entries may provide an avenue for attackers to gain privileged access on the system.
sca.check.remediation: Remove any legacy '+' entries from /etc/group if they exist.
sca.check.compliance.cis: 6.2.5
sca.check.compliance.cis_csc: 16.2
sca.check.compliance.pci_dss: 2.2.3
sca.check.compliance.nist_800_53: CM.1
sca.check.compliance.gpg_13: 4.3
sca.check.compliance.gdpr_IV: 35.7.d
sca.check.compliance.hipaa: 164.312.b
sca.check.compliance.tsc: CC5.2
sca.check.file: ["/etc/group"]
sca.check.result: passed
```

Examples of logs that generate alerts.
