### ISSUE TITLE
Add hostinfo module to agent simulator

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#1163]
# Objective
Make agent simulator able to send hostinfo messages to the manager in order to stress out the "Hostinfo events" analysisd queue.

## TODO
- [x] Recopilate some examples of hostinfo events.
- [x] Define an hostinfo event template that could be randomized to generate multiple different events.
- [x] Add an hostinfo module able to send those random events to the manager on the agent simulator.

**Comment by Rebits** [comment]
### Host info message format

Hostinfo messages events are generated when hosts information changed. These events are generated when a nmapg format file is monitored and hosts information has changed or a new host is discovered. Example:

```
# Nmap 7.70 scan initiated Mon Mar 22 08:07:49 2021 as: nmap --append-output -sU -sT -oG /var/log/nmap-out.log 172.17.1.11-255
Host: 172.17.1.11 ()    Status: Up
Host: 172.17.1.11 ()    Ports: 22/open/tcp//ssh///      Ignored State: closed (1999)
# Nmap 7.70 scan initiated Mon Mar 22 08:19:10 2021 as: nmap --append-output -sU -sT -oG /var/log/nmap-out.log 172.17.1.11-255
Host: 172.17.1.11 ()    Status: Up
Host: 172.17.1.11 ()    Ports: 22/open/tcp//ssh///      Ignored State: closed (1999)
# Nmap 7.70 scan initiated Mon Mar 22 08:20:00 2021 as: nmap --append-output -sT -oG /var/log/nmap-out.log 172.17.1.11-255
Host: 172.17.1.11 ()    Status: Up
Host: 172.17.1.11 ()    Ports: 22/open/tcp//ssh///      Ignored State: closed (999)
Host: 172.17.1.17 ()    Status: Up
Host: 172.17.1.17 ()    Ports: 22/open/tcp//ssh///      Ignored State: closed (999)
# Nmap done at Mon Mar 22 08:20:05 2021 -- 245 IP addresses (2 hosts up) scanned in 4.98 seconds
```

This generates the following events in the Wazuh manager:

```
2021 Mar 22 08:07:56 centos1->/var/log/nmap-out.log Host: 172.17.1.11 (), open ports: 22(tcp)
2021 Mar 22 08:28:27 centos1->/var/log/nmap-out.log Host: 172.17.1.14 (), open ports: 22(tcp) 80(tcp)
```

These messages are sent to analisysd to to `HOSTINFO_MQ`  queue in the following format:

```
3:[agent-id] (agent-name) any->localfile:Host: 172.17.1.11 (), open ports: 22(tcp)'
```
