### ISSUE TITLE
Add Winevt module to agent simulator

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#1168]
# Objective
Make agent simulator able to send Winevt messages to the manager in order to stress out the "Winevt events" analysisd queue.

## TODO
- [x] Recopilate some examples of Winevt events.
- [x] Define an Winevt event template that could be randomized to generate multiple different events.
- [x] Add an Winevt module able to send those random events to the manager on the agent simulator.

**Comment by Rebits** [comment]
# Winenv event
Example of winenv message:
```
'f:[001] (winserver2019) any->EventChannel:{"Message":"System audit policy was changed.\r\n\r\nSubject:\r\n\tSecurity ID:\t\tS-1-5-21-1331263578-1683884876-2739179494-500\r\n\tAccount Name:\t\tAdministrator\r\n\tAccount Domain:\t\tWIN-ACL01C4DS88\r\n\tLogon ID:\t\t0x372C7\r\n\r\nAudit Policy Change:\r\n\tCategory:\t\tPolicy Change\r\n\tSubcategory:\t\tFiltering Platform Policy Change\r\n\tSubcategory GUID:\t{0cce9233-69ae-11d9-bed3-505054503030}\r\n\tChanges:\t\tSuccess Added, Failure added","Event":"<Event xmlns=\'http://schemas.microsoft.com/win/2004/08/events/event\'><System><Provider Name=\'Microsoft-Windows-Security-Auditing\' Guid=\'{54849625-5478-4994-a5ba-3e3b0328c30d}\'/><EventID>4719</EventID><Version>0</Version><Level>0</Level><Task>13568</Task><Opcode>0</Opcode><Keywords>0x8020000000000000</Keywords><TimeCreated SystemTime=\'2019-05-28T09:29:41.443963000Z\'/><EventRecordID>965047</EventRecordID><Correlation ActivityID=\'{1115b961-1535-0000-8bbb-15113515d501}\'/><Execution ProcessID=\'556\' ThreadID=\'6024\'/><Channel>Security</Channel><Computer>WIN-ACL01C4DS88</Computer><Security/></System><EventData><Data Name=\'SubjectUserSid\'>S-1-5-21-1331263578-1683884876-2739179494-500</Data><Data Name=\'SubjectUserName\'>Administrator</Data><Data Name=\'SubjectDomainName\'>WIN-ACL01C4DS88</Data><Data Name=\'SubjectLogonId\'>0x372c7</Data><Data Name=\'CategoryId\'>%%8277</Data><Data Name=\'SubcategoryId\'>%%13572</Data><Data Name=\'SubcategoryGuid\'>{0cce9233-69ae-11d9-bed3-505054503030}</Data><Data Name=\'AuditPolicyChanges\'>%%8449, %%8451</Data></EventData></Event>"'
```
