### ISSUE TITLE
Add agents templates to simulate_agent script

### ISSUE THREAD

**Issue by spothound** [wazuh/wazuh-qa#1180]
# Objective
We want to add a new feature for the simulate_agents script that allows us to define a series of agents with a certain configuration using a yaml template file.

The script then should allow us to load a custom template from a file and raise the required agents without any extra configuration.

# TODO
- [ ] Define template file format
- [ ] Add a parser/loader for the template
- [ ] Make the required changes to the script and test everything

**Comment by pacoqack** [comment]
# Template format

Some requirements for this template:

- [ ] Must allow us to define multiple agent blocks (with a concrete amount of similar agents)
- [ ] Each block must have a definition for the agent os, manager address and wazuh version
- [ ] Each block must have a list of active modules with their expected EPS
- [ ] Each block must contain labels definitions for the agents

**Comment by BraulioV** [comment]
Hi all, this will be delayed for now. We will implement this as soon as we have a structure and a standard to define several scenarios to measure the performance of each version. Once it is defined, we will implement the YAML templates to run the tests.
