### ISSUE TITLE
Performance tests: second iteration

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh-qa#1190]
This issue aims to cover a new iteration in our performance tests, add more use cases and new functionality:
**Data visualizer**
- [x] Improve the color palette. If the number of labels starts to grow, the same color is used more than once. [#1227](https://github.com/wazuh/wazuh-qa/issues/1227)

**Infrastructure improvements**
- [x] Extract data of the cluster. [#1139](https://github.com/wazuh/wazuh-qa/issues/1139)
  - [x] Define the number of nodes and apply load to them.
  - [x] Define the infrastructure of the cluster (who is the master node, if this node is isolated or not, etc).
- [x] Infrastructure calculator. Currently, the instance types and the number of them are calculated following simple rules. We should add new ways to improve this and select a much better infrastructure for the test to improve costs-savings, scalability of the test, deployment times, etc.
- [x] Adapt the infrastructure and tools to deploy simulated agents massively. #1240

**Agent simulator**
- [x] The agent must be able to be enrolled and connected on different hosts #1139
- [x] The agent must send messages of a fixed size [#1175](https://app.zenhub.com/workspace/o/wazuh/wazuh-qa/issues/1175).
- [x] Syscollector events must be sent with a constant throughput #1238

**Wazuh API**
- [x] Add a new tool to measure the API's endpoints performance. #1245
