### ISSUE TITLE
Performance tests: improve the deploy of the simulated agents 

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh-qa#1193]
The current implementation of this deployment adds a huge overhead in the pipeline because it is in charge of deploying the instances where the simulated agents will run, the toolset, and run the simulated agents.

We must move this deployment to Fargate to get rid of the instances deployment and the installation of the toolset. Using Fargate we can define a Docker image that will run the simulated agents, making it completely transparent to the pipeline.

**Tasks**
- [x] Create the ECS cluster.
- [x] Create a new Docker image to run the simulated agents.
- [x] Create a new ECS task to run it:
  - [x] Create the task.
  - [x] Analyze the behavior of the Docker and establish the best hardware resources for it.
