### ISSUE TITLE
Refactor the CI pipelines for GitHub Pull Requests

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh-qa#1198]
With the latest changes introduced in the pipeline, it is way more flexible than before. This allows better detection of what files have been modified and run the tests associated with specific functionality, files, etc.

This issue aims to refactor the CI environment and pipelines. The integration tests belonging to tiers 0 and 1 will be moved forward and they will be executed in PRs. They will also add the check to the Pull Request.

For example, this https://github.com/wazuh/wazuh/pull/7506 must run the tier 0 and 1 for [FIM](https://github.com/wazuh/wazuh-qa/tree/master/tests/integration/test_fim) and add two new checks to the PR summary:
- Integration tests: tier 0 :heavy_check_mark:
- Integration tests: tier 1 :heavy_check_mark:

Once the PR gets merged, the CI will run the post-merge tests including all the tests from Wazuh QA.

**Comment by spothound** [comment]
Working on this.

**Comment by spothound** [comment]
# Testing integration tests on master branch

## FIM
### Agent
#### Tier 0 
https://ci.wazuh.info/view/Tests/job/test_integration/1626/console
#### Tier 1
### Manager
#### Tier 0 
#### Tier 1

## Vulnerability detector
### Agent
#### Tier 0 
#### Tier 1
### Manager
#### Tier 0 
#### Tier 1

## Authd
### Agent
#### Tier 0 
#### Tier 1
### Manager
#### Tier 0 
#### Tier 1

## Remoted
### Agent
#### Tier 0 

#### Tier 1
### Manager
#### Tier 0 
#### Tier 1

**Comment by spothound** [comment]
![image](https://user-images.githubusercontent.com/15269938/115666362-ca2d4480-a344-11eb-99e4-a3d16f911f83.png)

These days we've added the Github checkruns to the Test_integration pipeline and we've been testing them.

![image](https://user-images.githubusercontent.com/15269938/115666409-d87b6080-a344-11eb-85cd-d3f1fe8ca269.png)
![image](https://user-images.githubusercontent.com/15269938/115666470-e92bd680-a344-11eb-8c25-09f94d70db37.png)

**Comment by spothound** [comment]
# Integration test status summary
Tested on 5d1ea4f0aa5a7e7abedfb9a21a800914a1de6592 (from master)

## Manager tests
- [ ] Test auth
- [ ] Test FIM
- [ ] Test vulnerability detector
- [ ] Test remoted
- [ ] Test rootcheck
- [ ] Test wazuh_db
- [ ] Test g_cloud
- [ ] Test cluster
- [ ] Test_api
- [ ] Test active_response
- [ ] Test analysisd
- [ ] Test logtest
## Agent tests
- [ ] Test agentd
- [ ] Test FIM
- [ ] Test wpk

**Comment by BraulioV** [comment]
Closed by https://github.com/wazuh/wazuh-jenkins/pull/2504
