### ISSUE TITLE
Logcollector integration tests T0: Check location values

### ISSUE THREAD

**Issue by spothound** [wazuh/wazuh-qa#1224]
It is necessary to add tests for the logcollector source location option as part of https://github.com/wazuh/wazuh-qa/issues/1027

# Objectives
- [x] Test different paths for location field.
- [x] Test wildcard usage: set up a wildcard, create a bunch of logs and check if the daemon collects the logs.
- [x] Test exclude: test wildcard usage to exclude reading some files of a directory.

# Organization

We will create a single file for these three tasks (as they are very similar) and will create various tests.

## Tasks
- [x] Recopilate logcollector logs that allow us to check if a file is being monitored or ignored.
- [x] Create a new test file (tier 0) to check location values 
- [x] Add single path test
- [x] Add wildcard test
- [x] Add ignore test

### Test single path
- [x] Check for log `Analyzing file: '/tmp/test.log'`
- [x] Must test multiple directory depths
- [x] Test file/directory doesn't exist: `ERROR: (1103): Could not open file '/tmp/test.log' due to [(2)-(No such file or directory)].`

### Test wildcard path
- [x] Must test files with date names as `file.log-2019-07-30` using formatted references such as `file.log-%Y-%m-%d`
- [x] Check if wildcard `*` works as expected (left) `*.txt`
- [x] Check if wildcard `*` works as expected (right) `testfile*`
- [x] Check if wildcard `*` works as expected (full) `*`
- [x] Check behavior with a wildcard for more than 200 files (The maximum amount of files monitored at the same time is limited to 200)
- [x] Check for this message `"(1957): New file that matches the '%s' pattern: '%s'."`when a new file is added and it matches an existing wildcard
- [x] Check for duplicated message error `"(1958): Log file '%s' is duplicated."`
- [x] Must test special characters and "foreign" language characters  ("ñ", "テスト", "ИСПЫТАНИЕ", "测试", "اختبار")

### Test exclude option
- [x] Exclude single file
- [x] Exclude some extension: `*py`
- [x] Exclude files containing a word: `*test*`
- [x] Exclude files starting by something: `test*`
- [x] Exclude all the files used in location wildcard (use  the same wildcard)
