### ISSUE TITLE
Logcollector integration tests T0: Check log_format values 

### ISSUE THREAD

**Issue by spothound** [wazuh/wazuh-qa#1226]
It is necessary to add tests for the logcollector source location option as part of https://github.com/wazuh/wazuh-qa/issues/1027

The purpose of this test is to check what happens when you put each one of the available formats for logcollector files.

We need to check if any error is logged when a format is specified but the file doesn't match that format, and which logs appear when the file matches the format and everything works.

## Objectives
- [x] Test all the different valid formats for logcollector. [docs](https://documentation.wazuh.com/4.0/user-manual/reference/ossec-conf/localfile.html#log-format)
- [x] Test invalid files with each valid format

# Organization

## Tasks
- [x] Recopilate syscollector logs that allow us to check if a file is being monitored or ignored.
- [x] Create a new test file (tier 0) to check format values -> Invalid files + Valid files

**Comment by spothound** [comment]
This issue could be related with https://github.com/wazuh/wazuh-qa/issues/1252

**Comment by damarisg** [comment]
### 10/05/2021

**Tests execution to check log format content:**
      -  These tests will check that if you add a file with `valid` content is accepted and showed in `ossec.log.`
      -  They will also make sure that the Wazuh manager shows an error in `ossec.log` when a file has `invalid` content.

- [ ] **Json** 
- [ ] **Syslog** 
- [ ] **Snort-full** 
- [ ] **Squid**

![imagen](https://user-images.githubusercontent.com/3978434/117708037-b471a900-b1a5-11eb-81db-1ea001e49aa6.png)
Solving some problems with **Audit** format

![imagen](https://user-images.githubusercontent.com/3978434/117712986-6b245800-b1ab-11eb-81bc-329b36af0328.png)
