### ISSUE TITLE
Logcollector integration tests T0: Check age option

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#1241]
It is necessary to add tests for the logcollector [age](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/localfile.html?highlight=localfile#age) option as part of https://github.com/wazuh/wazuh-qa/issues/1027

# Objectives
- [x] Test age option works correctly, ignoring files that have not been modified since specified values.
- [x] Test after change host date, logcollector still works and age value is applied correctly

# Organization

## Tasks
- [x] Recopilate logcollector logs that allow us to check if a file is being monitored or ignored.
- [x] Create a new test (tier 0) to check age option works correctly.
- [x] Create a new test (tier 0) to check logcollector works after changing host date.
- [x] Testing and debug new tests.
- [ ] Documentation new tests and  functions.

**Comment by Rebits** [comment]
## Update 23/04/2021

New tests have been created to check to fulfil this issue objectives:

![logcollector-age_tests](https://user-images.githubusercontent.com/11089305/115898133-7febb680-a45d-11eb-9cbe-d78170d3cf70.png)

These have been tested for Linux system but they don't work for Windows. A further investigation is necessary to determine if tests have some bugs for Windows systems or Wazuh fails in order to monitor every log file.

### Environment configuration
Is necessary, in order to run correctly these tests adds the following configuration in Vagrantfile:

`
        vb.customize ["setextradata", :id, "VBoxInternal/Devices/VMMDev/0/Config/GetHostTimeDisabled", 1]
`

This allows the test to change the host date, necessary for testing the age field correctly. Also is necessary to disable `timedatectl`  automatic time synchronization for Centos systems `(timedatectl set-ntp 0).` All these requirements should be implemented in `wazuh-jenkins` repository before merging these tests.
