### ISSUE TITLE
Performance cluster test - Third iteration

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#1258]
For this sprint, we want to add the following functionalities and improvements in the performance cluster test:

## Tasks

- [x] **1**: Add the implementation of custom labels to modify the content of keep-alive messages (https://github.com/wazuh/wazuh-qa/issues/1260).
- [x] **2**: Integrate the `simulate_api` script in the test to simulate API load from the UI (https://github.com/wazuh/wazuh-qa/issues/1281).
- [x] **3**: Review and adjust monitoring times, testing ... taking into account deployment time and environment circumstances (https://github.com/wazuh/wazuh-qa/issues/1303).
- [x] **4**: Add a new health check to check that all tasks of the simulated agents have been started. Right after this, we will have to launch the API tests. The current implementation estimates when the environment is ready (https://github.com/wazuh/wazuh-qa/issues/1285).
- [x] **5**: Implement a new mode to run `n` agents sending a fixed EPS (https://github.com/wazuh/wazuh-qa/issues/1286).
- [x] **6**: Parse the information from the cluster log and plot the results (https://github.com/wazuh/wazuh-qa/issues/1287).
- [x] **7**: Add a new feature in the pipeline to send messages of a fixed size in bytes (https://github.com/wazuh/wazuh-qa/issues/1288).
