### ISSUE TITLE
CVEs alerts inventory for Vulnerability Detector - Vulnerability Detector Integration Tests

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh-qa#1261]
### Description

As part of the epic https://github.com/wazuh/wazuh/issues/7749, we implemented a mechanism to have an inventory of the CVEs that affect each agent in which the Wazuh agents are installed. This epic changed the way in which the Vulnerability Detector generates alerts as well. Here some key points of the epic:

- Depending on the trigger of the Vulnerability detector scan, we could have three scan types: `BASELINE`, `PARTIAL_SCAN`, and `FULL_SCAN`.
- Each scan type will behave in different ways on the alert generation.
- There is a new alert type generated when a vulnerability no longer affects an agent because of a package upgrade/removal.
- The vulnerabilities could be in three different states in the inventory: `VALID`, `PENDING`, `OBSOLETE`, and `REMOVED`.
- There is a new setting called `min_full_scan_interval`, and the setting `ignore_time` was removed.

For details of all these key points to be taken into account in the test design and implementation, check the **description** section of the epic.

### Update 10/28/2021

After discussing with the QA team, and taking into account the new guidelines, we decided to implement the next set of improvements in this set of tests:

- https://github.com/wazuh/wazuh-qa/issues/2148
- https://github.com/wazuh/wazuh-qa/issues/2150

It is being evaluated also the possibility of unifying some of the scan results tests that seem to be repeated.

**Comment by BraulioV** [comment]
## Tasks
- [ ] Deprecation of the `test_general_settings_ignore_time.py`
- [ ] Rework the `vulnerability_detector.py` module:
    - [ ] Run queries to wazuh-db. 
    - [ ] Mock the new scan types.
- [ ] Rework of the `test_scan_results`. These tests now must check by running a query to the `vuln_cves` table if the vulnerability was added to the inventory. These tests must run in a `FULL` scan scenario.
- [ ] New tests implementation:
    - [ ] Configuration test for `min_full_scan_interval`.
    - [ ] `BASELINE` scans: no alert must be generated.
    - [ ] `PARTIAL`: no alert must be generated for already scanned packages.
    - [ ] Vulnerability removal: if a vulnerability is removed from the inventory, a new alert must be triggered.

**Comment by spothound** [comment]
### 5/18/21
- start working on this. We need to start by reworking vulnerability_detector.py to use queries to wazuh-db instead of to SQLite files.

**Comment by mdengra** [comment]
# Test for `min_full_scan_interval` configuration option.

## 2021/05/18
- I begin the implementation of the new test.

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh-qa/pull/1496 was merged.
