### ISSUE TITLE
Adapt current logcollector integration tests for macOS

### ISSUE THREAD

**Issue by spothound** [wazuh/wazuh-qa#1310]
#### Issue information
| Epic 	| QA base branch 	| Wazuh branch 	|
|-	|-	|-	|
| https://github.com/wazuh/wazuh-qa/issues/1200 	| master 	|  4572-dev-uls-logs-enhancement |

## Issue definition

We need to adapt our new logcollector tests to be launched in macOS agents.

The configuration block for macOS would be:

```
<localfile>
  <log_format>oslog</log_format>
  <location>oslog</location>
  <query type="trace" level="debug">processImagePath CONTAINS[c] "com.apple.geod"</query>
</localfile>
```

### TODO
- [x] Review status of current test and compatibility with macOS. Make a list of test that doesn't work on macOS.
- [x] Adapt the failed tests to run in macOS systems.
- [x] Adapt `only-future-event`  to macos ([Check this issue](https://github.com/wazuh/wazuh/issues/8138))
- [x] Test_log_format:  add `macos` option
- [x] Test _location: add  `macos option`
- [x] Add `query` label to localfile on macos test cases when required.
