### ISSUE TITLE
Find solutions for time-changing tests execution on AWS

### ISSUE THREAD

**Issue by spothound** [wazuh/wazuh-qa#1311]
## Context

There are some Integration Tests that require changes on the clock date of systems to work. These tests check that some activities are performed by Wazuh after an interval of time has passed and they need to simulate these time intervals by changing the clock date.

The problem is that those changes of time in virtual machines that run on AWS doesn't work right. There are two problems that we will discuss now.

## Problems

- First,  AWS has tools to synchronize the time in their EC2 instances machines. Nevertheless, this synchronization can be disabled. In fact, it seems that, at least for our custom testing AMIs, this synchronization is disabled right now. We need to confirm if this synchronization happens, in which systems do it happens and how could we disable it.
- Second, when we change the system date on an EC2 instance, after some time the connection with the instance is lost without apparent reason, but the system keeps running. Based on references [1] and [2] we have concluded that this missing connection could be caused by the client not being able to renew the system IP and thus, disconnecting from the network. This could be avoided **using static IP address**.

## Objectives

- [x] Investigate about AWS time synchronization, how it works, and if it applies to our testing environment. How could it be disabled?
- [x] Find a way to change dynamic IPs for static ones in our testing environment.
- [x] Confirm that using static IPs and disabling time synchronization ends with the problems described above.

## References

- [1] [AWS forum](https://forums.aws.amazon.com/thread.jspa?threadID=239374): here a user of the AWS forum stated that he has a similar problem with lost connection after some time with the date changed. He states that he asked for support to AWS and they told him that the problem was related with dhclient
- [2] [dhclient.conf docshf](https://linux.die.net/man/5/dhclient.con): this document indicates that dhclient stores dates like the renew, rebind and expire date. These dates have the time at which the client must ask DHCP to renew his IP, for example. If these dates are set to a past date (after a change on the time made by our tests), then they will never reach, for example. It also could be that messing with the clock time could lead to unknown behaviours with dhclient and it would never renew the server IP.

**Comment by spothound** [comment]
We've think the following solution:

We could create a pytest mark for those test that requires modifying the time of the machine to run. Then, create an option on Jenkins to launch tests in vagrant with that option enabled. 


If you launch IT for a module with this option, only those tests that require time changes would be launch. If you launch the same test without that option, only those tests that don't have the mark would be launch.

Ad for GitHub check runs, we would have, for example:

```
Test: Logcollector IT - Tier 1 - manager
Test: Logcollector IT - Tier 0 - manager
Test: Logcollector IT - Tier time - manager
```


# TODO
- [ ] Add support for agents tests (windows, macos, solaris) using time-changes. Actually, as solaris and macos are currently being launched using Vagrant this wouldn't be a big trouble, we only need to check that changing the clock of the machine works.
- [ ] List all those tests that use clock changes and add a mark for them
- [ ] Add an option on Jenkins to launch tests with time_changes mark

**Comment by spothound** [comment]
## Resources

- https://www.msystechnologies.com/blog/how-to-change-the-date-and-time-on-amazons-ec2-instance/
- https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-time.html

**Comment by spothound** [comment]
# About time synchronization in AWS

AWS time synchronization mechanism works using a tool called chronyd [1], it may be installed in some default AWS AMIs, but is not installed in our current testing environment custom AMIs.

### references
- [1] https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-time.html

**Comment by spothound** [comment]
# Behavior in Ubuntu Bionic.
On ubuntu Bionic (server) the mentioned files available on centOS do not exists. We can get the dhcp lease information by running:
```
root@ip-172-31-66-114:/var/lib/dhcp# netplan ip leases ens3
# This is private data. Do not parse.
ADDRESS=172.31.66.114
NETMASK=255.255.240.0
ROUTER=172.31.64.1
SERVER_ADDRESS=172.31.64.1
MTU=9001
T1=1800
T2=3150
LIFETIME=3600
DNS=172.31.0.2
DOMAINNAME=ec2.internal
HOSTNAME=ip-172-31-66-114
CLIENTID=ffb55e67ff00020000ab11ef146588f4df99f4
root@ip-172-31-66-114:/var/lib/dhcp# date +%Y%m%d -s "20120418"
20120418
root@ip-172-31-66-114:/var/lib/dhcp# date -s "19 APR 2022 11:14:00"
Tue Apr 19 11:14:00 UTC 2022
root@ip-172-31-66-114:/var/lib/dhcp# date
Tue Apr 19 11:14:03 UTC 2022

```



## References
- [1] https://askubuntu.com/questions/1039056/find-dhcp-lease-dns-info-in-18-04-lts
