### ISSUE TITLE
Automatic integration tests for logcollector on PRs and nightly.

### ISSUE THREAD

**Issue by spothound** [wazuh/wazuh-qa#1339]
We're launching automatic integration tests log logcollector on Jenkins and we've detected some errors that need to be fixed.

## TODO

- [x] Add logcollector context to pipelineHelper 
```
    Test_integration: [
    test_fim: 'FIM',
    test_vulnerability_detector: 'Vul. Det.',
    test_remoted: 'Remoted',
    test_authd: 'Authd',
    test_active_response: 'AR',
    test_agentd: 'Agentd',
    test_analysisd: 'Analysisd',
    test_authd: 'Authd',
    test_cluster: 'Cluster',
    test_gcloud: 'Gcloud',
    test_logtest: 'Logtest',
    test_logcollector: 'Logcollector',
    test_rids: 'Rids',
    test_rootcheck: 'Rootcheck',
    test_wdb: 'WDB',
    test_wpk: 'WPK',
    test_wazuh_db: 'Wazuh DB'
  ]
```
- [x] ~~Allow launching manager or centos agent with VM based on the current solution for vulnerability detector~~ We've decided to run the tests on AWS after [Find solutions for time-changing tests execution on AWS #1311 ](https://github.com/wazuh/wazuh-qa/issues/1311)

- [ ] Review that all logcollector tests pass without problem on Jenkins builds #1394.

**Comment by spothound** [comment]
We will open an issue in the Jenkins repository when these tests are ready.
