### ISSUE TITLE
Definition of the minimal infrastructure 

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh-qa#1352]
With the latest tools and changes added to our performance and scalability tests, we can measure quite accurately the limits of different infrastructures for Wazuh. This issue aims for the definition of the minimal infrastructure that must be deployed to support `N` EPS and its hardware requirements.

## Tasks for a single instance
- [x] Collection of new metrics:
    - [x] IO operations performance for each binary (#1364).
    - [x] API endpoints response time (#1365).
- [x] Target definition: for now, we will focus on hosts with this hardware characteristics (#1353) :
    - [x] 0.5 CPUs and 1 GB of memory (this must be a Docker instance).
    - [x] 1 CPUs and 2 GB of memory.
    - [x] 2 CPUs and 4 GB of memory.
    - [x] 4 CPUs and 8 GB of memory.
- [x] Changes in infrastructure deployment of the pipelines. (https://github.com/wazuh/wazuh-qa/issues/1353)
    - [x] Deploy managers using ECS with different size and limits.
    - [x] Deploy managers using EC2 instances.
- [x] Add support for lower versions than 4.2.0 in cluster performance test. (https://github.com/wazuh/wazuh-qa/issues/1367)
- [x] Cause intensive disk usage and get comparison between GP2 and GP3 using the cluster performance test pipeline (https://github.com/wazuh/wazuh-qa/issues/1370)
- [ ] Data collection for each analysisd queue:
    - [ ] File integrity monitoring (FIM). (https://github.com/wazuh/wazuh-qa/issues/1453)
    - [ ] Rootcheck.
    - [ ] Syscollector.
    - [ ] Logcollector.
    - [ ] Security configuration assessment.
    - [ ] Windows events.
    - [ ] Host info events.
    - [ ] FIM integrity events.
- [x] Logging impact for these cases:
    - [x] Enable `alerts.json` and `alerts.log`.
    - [x] Enable `alerts.json`, `alerts.log` and `archives.json`.
- [ ] Research to determine the optimal queue sizes for each infrastructure. 

## Afterwards tasks 
- [ ] Get scalability factor for a single node. (Vertical)
- [ ] Get scalability factor for a cluster environment. (Horizontal)

**Comment by jmv74211** [comment]
After a discussion with the rest of the teams, it has been determined that the research work is out of our scope and that we (QA team) will provide the necessary tools to carry out this analysis which will be performed by another team.
