### ISSUE TITLE
Create a footprint checkrun for Pull Requests

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh-qa#1356]
This issue is related to https://github.com/wazuh/wazuh-qa/issues/1355. The idea of this issue is to define a threshold limit for CPU, memory, I/O speed... and several use cases that must be checked on every PR.

## Tasks
- [ ] Define a threshold for each hardware metric.
- [ ] Define the test.
- [ ] Adapt PR_Wazuh pipeline to run these footprint tests.

**Comment by damarisg** [comment]
We decided to close them as it was not planned.
