### ISSUE TITLE
Add Wazuh's python framework on testing infrastructure

### ISSUE THREAD

**Issue by spothound** [wazuh/wazuh-qa#1357]
We've decided to find a way to add our Python framework libraries [1] to our testing environment so we could use work already done by our framework team for our tests instead of re-writing existing code.

On this issue, we will track the experiments required to confirm that this is viable and decide the best way to do it. Also, we will write up errors and problems found and solutions proposed to them. 

@spothound will manually test this framework as part of our tests
@BraulioV will find a way to upload the wazuh framework package to an s3 repository so it could be easily downloaded and installed as part of our tests.

#### References
[1] Wazuh python framework https://github.com/wazuh/wazuh/tree/master/framework

**Comment by BraulioV** [comment]
## Tasks
- [ ] Test the integration of Python's SDK made by the framework team.
- [ ] Build a wheel package of the framework.
- [ ] Create a PyPi repository to make easier the deployment of this framework.

**Comment by spothound** [comment]
After installing the package and  dependencies we got this error if we try to import any wazuh framework module:

```
>>> from wazuh import agent
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/wazuh-4.3.0-py3.8.egg/wazuh/__init__.py", line 11, in <module>
    from wazuh.core.wdb import WazuhDBConnection
  File "/usr/local/lib/python3.8/dist-packages/wazuh-4.3.0-py3.8.egg/wazuh/core/wdb.py", line 14, in <module>
    from wazuh.core.exception import WazuhInternalError, WazuhError
  File "/usr/local/lib/python3.8/dist-packages/wazuh-4.3.0-py3.8.egg/wazuh/core/exception.py", line 10, in <module>
    WAZUH_VERSION = 'current' if wazuh_full_version == '' else '.'.join(wazuh_full_version.split('.')[:2]).lstrip('v')
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by spothound** [comment]
https://ci.wazuh.info/job/Packages_builder/50121/console

**Comment by spothound** [comment]
We have decided to leave this for a later date. The issue is moved to the backlog.

**Comment by damarisg** [comment]
We decided to close them as it was not planned.
