### ISSUE TITLE
CVEs alerts inventory for Vulnerability Detector - Review of general tests

### ISSUE THREAD

**Issue by spothound** [wazuh/wazuh-qa#1410]
As part of issue #1261, we need to review the status of all the test that are supposed to keep working (they are not related with the scans).

## TODO

- [x] Review test_general_settings
![image](https://user-images.githubusercontent.com/15269938/120458981-09b16c80-c398-11eb-9d58-5108a547cb68.png)
- [x] Review test_providers
![image](https://user-images.githubusercontent.com/15269938/120481396-5c971e00-c3b0-11eb-9569-5ef1b94c584f.png)
- [x] Review test_feeds
![image](https://user-images.githubusercontent.com/15269938/120761020-0c859c00-c515-11eb-93e3-a57f6f866cd2.png)
![image](https://user-images.githubusercontent.com/15269938/120783782-a9533400-c52b-11eb-865f-2ee98c32aa76.png)
![image](https://user-images.githubusercontent.com/15269938/120784810-c76d6400-c52c-11eb-9f5f-56dfe2c2a164.png)

#### LAST_SCAN column has been removed/renamed and must be updated in vulnerability_detector.py 
- [x] Solved

~~Previous to the changes in vulnerability detector scans, there was a LAST_SCAN column in vuln_metadata table (on agents databases), now there are two columns instead: LAST_PARTIAL_SCAN and LAST_FULL_SCAN~~

This test can be removed as this option has been deprecated on 4.3

`2021/06/02 09:33:04 wazuh-modulesd[48253] wmodules-vuln-detector.c:429 at Read_Vuln(): WARNING: The <ignore_time> tag at module 'vulnerability-detector' is deprecated for version newer than 4.3.`

### review tests/integration/test_vulnerability_detector/test_providers/test_providers_update_from_year.py
- [x] Solved

It seems that this option is also deprecated:

```
2021/06/02 11:21:23 wazuh-modulesd[6862] wmodules-vuln-detector.c:890 at wm_vuldet_read_provider_content(): INFO: 'update_from_year' option at module 'vulnerability-detector' is deprecated. Use 'os' instead.
```

**Comment by spothound** [comment]
## To discuss with core team:

- Should we add a test to replace the deprecated 'test_ignore_time` test? We understand that now, as alerts are only generated when there is a change in the status of a vulnerability, the interval associated with the alert generation doesn't exist. But, maybe we need to define a test to detect, for example, if an alert is generated when a vulnerable package is patched.
- Should we add a new test for the deprecated option `update_from_year'?

**Comment by spothound** [comment]
This has been reviewed and everything is correct!
