### ISSUE TITLE
[REVIEW] Integration Test: Agentd for 4.2 branch

### ISSUE THREAD

**Issue by spothound** [wazuh/wazuh-qa#1418]
We need to review the status of agentd integration tests on the 4.2 branches. They were disabled because we detect too many false positives in their execution.

## TODO

- [x] [Check agentd IT tier 0 ](https://ci.wazuh.info/job/Test_integration/5300/consoleFull)
- [x] [Check agentd IT tier 1](https://ci.wazuh.info/view/Tests/job/Test_integration/5217/console)

Tier 1 seems to work perfectly on Jenkins, tier 0 has some reproducible errors:
Builds:
1. https://ci.wazuh.info/view/Tests/job/Test_integration/5218/console
2. https://ci.wazuh.info/view/Tests/job/Test_integration/5219/console
3. https://ci.wazuh.info/view/Tests/job/Test_integration/5220/console
The following two error appear in the three builds, on both, centos and ubuntu agents. 
![image](https://user-images.githubusercontent.com/15269938/121021045-410d8800-c7a1-11eb-898f-8693ac1da4f2.png)
![image](https://user-images.githubusercontent.com/15269938/121021113-5387c180-c7a1-11eb-918c-3bd27e596e04.png)

The first error seems to be caused by a wrong cleaning of logs. The test asserts that there is no error in logs but, as the purpose of the test is to check reconnection when a connection is lost, there will always be an error on the moment where the connection is (although the system recovers).

The proposed solution: clean logs after restarting the simulated manager and assert that there are no errors at the end.

**Comment by spothound** [comment]
# Manual, local testing 

- [x] tests/integration/test_agentd/test_agentd_reconnection.py
![image](https://user-images.githubusercontent.com/15269938/120995055-57a5e600-c785-11eb-8225-c9e620e255b3.png)

**Comment by spothound** [comment]
We've updated the `test_agentd_reconnection.py` with changes that we made on master but not for 4.2 and all the tests seem to work just right. The errors described above seems to be caused by errors in the test action orders, for example deleting the agent key too early or too late.

![image](https://user-images.githubusercontent.com/15269938/121144420-440a8600-c83e-11eb-8575-6fd204ff9b39.png)
