### ISSUE TITLE
FIM scheduled IT automatization

### ISSUE THREAD

**Issue by spothound** [wazuh/wazuh-qa#1443]
Now that we have managed to solve the problems with time travelling in AWS (https://github.com/wazuh/wazuh-qa/issues/1311) we can re-enable scheduled FIM Integration tests.

We need to confirm that these tests work as expected first, though. 

## TODO
- [x] Run scheduled FIM IT on Jenkins
- [ ] Apply required changes if some tests fail
- [ ] Add those tests to PR Wazuh and nightly

**Comment by spothound** [comment]
Testing of fim scheduled; https://ci.wazuh.info/job/Test_integration/5912/console

**Comment by damarisg** [comment]
This issue will be `closed` as there is an issue where the test failures will be worked on.

And once we have stable FIM they will be enabled nightly (will open an issue for it).

Also, a problem will be created to investigate the cause of Windows FIM crashes when we have `"scheduled" mode` in Jenkins.
