### ISSUE TITLE
Syscheck automated tests: 'ignore' option

### ISSUE THREAD

**Issue by crd1985** [wazuh/wazuh-qa#145]
## Description

This issue is part of the roadmap in #7.

The `ignore` tag is used to exclude some paths from the syscheck scan, so no events will be generated for them.

According to [documentation](https://documentation.wazuh.com/3.10/user-manual/capabilities/file-integrity/fim-configuration.html#configure-to-ignore-files), there are several ways to configure it:
```xml
<syscheck>
  <ignore>/etc/random-seed</ignore>
  <ignore>/root/dir</ignore>
  <ignore type="sregex">.log$|.tmp</ignore>
</syscheck>
```
so this issue will cover all possible use cases.

## Subtasks
- Realtime
  - [x] Ignore a directory
  - [x] Ignore a subdirectory
  - [x] Ignore a directory using sregex
  - [x] Ignore a subdirectory using sregex
  - [x] Ignore directories using empty sregex
  - [x] Ignore with a typo in configuration
- Whodata
  - [x] Ignore a directory
  - [x] Ignore a subdirectory
  - [x] Ignore a directory using sregex
  - [x] Ignore a subdirectory using sregex
  - [x] Ignore directories using empty sregex
  - [x] Ignore with a typo in configuration
- Scheduled
  - [x] Ignore a directory
  - [x] Ignore a subdirectory
  - [x] Ignore a directory using sregex
  - [x] Ignore a subdirectory using sregex
  - [x] Ignore directories using empty sregex
  - [x] Ignore with a typo in configuration

**Comment by crd1985** [comment]
## Summary

Now tests are running for `scheduled`, `whodata` and `realtime` mode.
A few changes have been made in the `load_wazuh_configurations` to let it dynamically modify configurations according to some parameters. Furthermore, adding metadata related to each param is also possible to document and parametrize tests, allowing reusing a single test function for a lot of configurations.

## Tests
```
[root@wazuh-master vagrant]# python3 -m pytest /vagrant/shared/test_wazuh/test_fim/test_ignore/test_ignore_valid.py 
================================================ test session starts =================================================
platform linux -- Python 3.6.8, pytest-5.2.0, py-1.8.0, pluggy-0.13.0
rootdir: /vagrant/shared/test_wazuh, inifile: pytest.ini
collected 567 items                                                                                                  

../../vagrant/shared/test_wazuh/test_fim/test_ignore/test_ignore_valid.py sssssssssssssssssss......s......ssss [  6%]
.sssss....s......ssss.sssss....s......ssss.sssss................s.sss..................sss..................ss [ 25%]
s....s......s.s..s.sss....s......s.s..ss.sssssssssssssssssssss......s......ssss.sssss....s......ssss.sssss.... [ 45%]
s......ssss.sssss................s.sss..................sss..................sss....s......s.s..s.sss....s.... [ 64%]
..s.s..ss.sssssssssssssssssssss......s......ssss.sssss....s......ssss.sssss....s......ssss.sssss.............. [ 83%]
..s.sss..................sss..................sss....s......s.s..s.sss....s......s.s..ss.ss                    [100%]

============================= 348 passed, 219 skipped in 5430135.99s (62 days, 20:22:15) =============================
```
