### ISSUE TITLE
Syscheck automated tests: basic usage

### ISSUE THREAD

**Issue by vicferpoy** [wazuh/wazuh-qa#147]
## Description

This issue is part of the roadmap in #7.

According to [documentation](https://documentation.wazuh.com/3.10/user-manual/capabilities/file-integrity/fim-configuration.html#basic-usage), you can configure basic monitoring in three different ways:

### Scheduled 
**Syscheck** is configured to run every certain amount of time using the `frequency` tag.

```xml
<syscheck>
  <frequency>36000</frequency>
  <directories>/etc,/usr/bin,/usr/sbin</directories>
  <directories>/bin,/sbin</directories>
</syscheck>
```

### Real-time
Real-time monitoring can be configured with the `realtime` tag. Real-time is only paused during periodic *syscheck* scans and reactivates as soon as these scans are complete.

```xml
<syscheck>
  <directories check_all="yes" realtime="yes">c:/tmp</directories>
</syscheck>
```

### Who-data
This monitoring replaces the `realtime` option adding its own information. This functionality uses Linux Audit subsystem and the Microsoft Windows SACL. It is configured with the `whodata` tag. 
```xml
<syscheck>
  <directories check_all="yes" whodata="yes">/etc</directories>
</syscheck>
```

This issue will cover all possible basic use cases.

## Subtasks
- Scheduled
  - [x] Ignore non existing directories
  - [x] Check regular files are created
  - [x] Check regular files with binary content are created
  - [x] Check regular files are modified
  - [x] Check regular files are removed
  - [x] Ignore special files are created 
  - [x] Check all the attributes in `check_all="yes"` appear in log
- Realtime
  - [x] Ignore non existing directories
  - [x] Check regular files are created
  - [x] Check regular files with binary content are created
  - [x] Check regular files are modified
  - [x] Check regular files are removed
  - [x] Ignore special files are created 
  - [x] Check all the attributes in `check_all="yes"` appear in log
- Whodata
  - [x] Ignore non existing directories
  - [x] Check regular files are created
  - [x] Check regular files with binary content are created
  - [x] Check regular files are modified
  - [x] Check regular files are removed
  - [x] Ignore special files are created 
  - [x] Check all the attributes in `check_all="yes"` appear in log

**Comment by vicferpoy** [comment]
# Status update
## Summary
Development is almost finished. Some tests fail due to a bug with special files (FIFO, socket) when `syscheck` stops monitoring a whole directory after it detects a special file within.

Also, `whodata` does not provide the correct event when files are removed (it did) and it makes tests to fail too.

Below there is an example of the logs when creating a regular file after adding a special file. This was with `realtime` monitoring.
```
2019 / 10 / 30 07: 44: 00 ossec - syscheckd[6176] create_db.c: 48 at fim_scan(): INFO: (6008): File integrity monitoring scan started.
2019 / 10 / 30 07: 44: 00 ossec - syscheckd[6176] create_db.c: 51 at fim_scan(): INFO: fim_scan(0): '/testdir1'
2019 / 10 / 30 07: 44: 00 ossec - syscheckd[6176] create_db.c: 232 at fim_process_event(): DEBUG: ~~Process event(mode: 0): '/testdir1'
2019 / 10 / 30 07: 44: 00 ossec - syscheckd[6176] create_db.c: 232 at fim_process_event(): DEBUG: ~~Process event(mode: 0): '/testdir1/fifo'
2019 / 10 / 30 07: 44: 00 ossec - syscheckd[6176] create_db.c: 51 at fim_scan(): INFO: fim_scan(0): '/testdir2'
2019 / 10 / 30 07: 44: 00 ossec - syscheckd[6176] create_db.c: 232 at fim_process_event(): DEBUG: ~~Process event(mode: 0): '/testdir2'
2019 / 10 / 30 07: 44: 00 ossec - syscheckd[6176] create_db.c: 64 at fim_scan(): INFO: (6009): File integrity monitoring scan ended.
2019 / 10 / 30 07: 44: 00 ossec - syscheckd[6176] create_db.c: 68 at fim_scan(): INFO: The scan has been running during: 0.002 sec(0.000 clock sec)
2019 / 10 / 30 07: 44: 00 ossec - syscheckd[6176] create_db.c: 1071 at print_hash_tables(): INFO: SCH '0'
2019 / 10 / 30 07: 44: 00 ossec - syscheckd[6176] create_db.c: 1072 at print_hash_tables(): INFO: RT '0'
2019 / 10 / 30 07: 44: 00 ossec - syscheckd[6176] create_db.c: 1073 at print_hash_tables(): INFO: WD '0'
2019 / 10 / 30 07: 44: 00 ossec - syscheckd[6176] create_db.c: 1074 at print_hash_tables(): INFO: Total: '0'
inodes: '20550000'
element_totali: '0'
```


And this is an example of `whodata` when removing files.
```
2019 / 11 / 24 05: 59: 11 ossec - syscheckd[2030] syscheck_audit.c: 1180 at filterkey_audit_events(): DEBUG: (6251): Match audit_key: 'key="wazuh_fim"'
2019 / 11 / 24 05: 59: 11 ossec - syscheckd[2030] syscheck_audit.c: 741 at audit_parse(): DEBUG: (6247): audit_event: uid = root, auid = vagrant, euid = root, gid = root, pid = 1781, ppid = 22717, inode = 52018326, path = /testdir1/regular_0, pname = /usr/bin / python3 .6
2019 / 11 / 24 05: 59: 11 ossec - syscheckd[2030] create_db.c: 300 at fim_audit_inode_event(): DEBUG: ~~Inode event: (52018326)
'/testdir1/regular_0'
2019 / 11 / 24 05: 59: 11 ossec - syscheckd[2030] create_db.c: 333 at fim_audit_inode_event(): DEBUG: ~~~~File '/testdir1/regular_0'
not in database and stat failed
2019 / 11 / 24 05: 59: 11 ossec - syscheckd[2030] syscheck_audit.c: 1180 at filterkey_audit_events(): DEBUG: (6251): Match audit_key: 'key="wazuh_fim"'
2019 / 11 / 24 05: 59: 11 ossec - syscheckd[2030] syscheck_audit.c: 741 at audit_parse(): DEBUG: (6247): audit_event: uid = root, auid = vagrant, euid = root, gid = root, pid = 1781, ppid = 22717, inode = 52055349, path = /testdir1/regular_1, pname = /usr/bin / python3 .6
2019 / 11 / 24 05: 59: 11 ossec - syscheckd[2030] create_db.c: 300 at fim_audit_inode_event(): DEBUG: ~~Inode event: (52055349)
'/testdir1/regular_1'
2019 / 11 / 24 05: 59: 11 ossec - syscheckd[2030] create_db.c: 333 at fim_audit_inode_event(): DEBUG: ~~~~File '/testdir1/regular_1'
not in database and stat failed
2019 / 11 / 24 05: 59: 12 ossec - syscheckd[2030] syscheck_audit.c: 1180 at filterkey_audit_events(): DEBUG: (6251): Match audit_key: 'key="wazuh_fim"'
2019 / 11 / 24 05: 59: 12 ossec - syscheckd[2030] syscheck_audit.c: 741 at audit_parse(): DEBUG: (6247): audit_event: uid = root, auid = vagrant, euid = root, gid = root, pid = 1781, ppid = 22717, inode = 52055351, path = /testdir1/regular_2, pname = /usr/bin / python3 .6
2019 / 11 / 24 05: 59: 12 ossec - syscheckd[2030] create_db.c: 300 at fim_audit_inode_event(): DEBUG: ~~Inode event: (52055351)
'/testdir1/regular_2'
2019 / 11 / 24 05: 59: 12 ossec - syscheckd[2030] create_db.c: 333 at fim_audit_inode_event(): DEBUG: ~~~~File '/testdir1/regular_2'
not in database and stat failed
```


## Difficulties
* I spent a lot of time making sure the special files and `whodata` errors were not test errors.
* I had to read and understand all the code from other tests to use already existing functions.

## Tests performed
Integrity tests for basic usage: `test_basic_usage`
```
========== 6 failed, 33 passed, 78 skipped in 608601.44s (7 days, 1:03:21) ==========
```

6 tests failed as expected due to the errors I already talked about. We have to change `date` for some tests so the time spent is not accurate.

## Pending
* I need to get some more information about pytest fixtures in order to isolate the tests more.
* I will update tests results once the errors get fixed.

**Comment by vicferpoy** [comment]
# Status update
## Summary
Development is finished. Previous errors were fixed and now tests work as intended.

## Tests performed
Integrity tests for basic usage: `test_basic_usage`
```
=============== 39 passed, 78 skipped in 702198.98s (8 days, 3:03:18) ===============
```
We have to change `date` for some tests so the time spent is not accurate.

**Comment by vicferpoy** [comment]
# Status update
## Summary
All tests are finished and refactored with the new changes to the dynamic environment creation.

## Tests performed
Integrity tests for basic usage: `test_basic_usage`
```
============== 42 passed, 48 skipped in 842695.08s (9 days, 18:04:55) ===============
```
We have to change `date` for some tests so the time spent is not accurate.
