### ISSUE TITLE
Syscheck automated tests: 'tags' option

### ISSUE THREAD

**Issue by albertomn86** [wazuh/wazuh-qa#148]
| Working branch |
| --- |
|[fim-integration-tests-tags](https://github.com/wazuh/wazuh-qa/tree/fim-integration-tests-tags)|

## Description

This issue is part of the roadmap in #7.

The `tags` attribute adds tags to the alerts for monitored directories.
The allowed value for the `tags` attribute must be a list separated by commas.

```XML
<directories whodata="yes" check_all="yes" tags="tag0,tag1,tag2,tag3,tag4,tag5,tag6,tag7,tag8,tag9">/testdir_tags</directories>
```
## Subtasks
- Realtime
  - [x] Add, modify and delete file using `tags`.
- Whodata
  - [x] Add, modify and delete file using `tags`.
- Scheduled
  - [x] Add, modify and delete file using `tags`.
