### ISSUE TITLE
Syscheck automated tests: 'report_changes' option

### ISSUE THREAD

**Issue by albertomn86** [wazuh/wazuh-qa#150]
| Working branch |
| --- |
|[fim-integration-tests-report-changes](https://github.com/wazuh/wazuh-qa/tree/fim-integration-tests-report-changes)|

## Description

This issue is part of the roadmap in #7.

The `report_changes` attribute is used to enable for reporting of the monitored files changes. This is limited to text files at this time.

## Subtasks
- Realtime
  - [x] Add, modify and delete file with `nodiff` option and `report_changes` enabled.
  - [x] Add, modify and delete file using `report_changes`. Check content of `queue/diff/local`.
  - [x] Set `report_changes` to *no* after using it and check that `queue/diff/local` has been emptied.
  - [x] Delete a `<directories>` entry with `report_changes` set to *yes* after using it and check that `queue/diff/local` has been emptied.
  - [ ] ~Set `report_changes` to *yes* with a large number of files and check that any file is being deleted inside`queue/diff/local`.~

- Whodata
  - [x] Add, modify and delete file with `nodiff` option and `report_changes` enabled.
  - [x] Add, modify and delete file using `report_changes`. Check content of `queue/diff/local`.
  - [x] Set `report_changes` to *no* after using it and check that `queue/diff/local` has been emptied.
  - [x] Delete a `<directories>` entry with `report_changes` set to *yes* after using it and check that `queue/diff/local` has been emptied.
  - [ ] ~Set `report_changes` to *yes* with a large number of files and check that any file is being deleted inside`queue/diff/local`.~

- Scheduled
  - [x] Add, modify and delete file with `nodiff` option and `report_changes` enabled.
  - [x] Add, modify and delete file using `report_changes`. Check content of `queue/diff/local`.
  - [x] Set `report_changes` to *no* after using it and check that `queue/diff/local` has been emptied.
  - [x] Delete a `<directories>` entry with `report_changes` set to *yes* after using it and check that `queue/diff/local` has been emptied.
  - [ ] ~Set `report_changes` to *yes* with a large number of files and check that any file is being deleted inside`queue/diff/local`.~

**Comment by vicferpoy** [comment]
# Status update
## Summary
Development is almost finished. Every test passes and they cover every check in the issue.

`Set report_changes to yes with a large number of files and check that any file is being deleted inside queue/diff/local` will be reasigned to another issue. It does not really match this issue.


## Difficulties
* I spent a lot of time figuring out how to reorganize the tests because of the limited scopes in pytest. It would share the same environment in certain tests that would make them fail.


## Tests performed

```
================================ test session starts ================================
platform linux -- Python 3.6.8, pytest-5.2.0, py-1.8.0, pluggy-0.13.0
rootdir: /vagrant/shared/wazuh-qa/test_wazuh, inifile: pytest.ini
collected 54 items                                                                  

test_report_changes_and_diff.py .ss.sss.ss.sss.ss.                            [ 33%]
test_report_deleted_diff.py .ss.sss.ss.sss.ss.ssssssssssssssssss              [100%]

==================== 12 passed, 42 skipped in 360.52s (0:06:00) =====================
```

_We have to change `date` for some tests so the time spent is not accurate._

## Pending
* I need to refactor the code using the new dynamic yaml functions. It should reduce the time spent because less tests would be skipped.

**Comment by vicferpoy** [comment]
# Status update
## Summary
Development is finished. Every test passes and they cover every check in the issue.

## Tests performed

```
================================ test session starts ================================
platform linux -- Python 3.6.8, pytest-5.2.0, py-1.8.0, pluggy-0.13.0
rootdir: /vagrant/shared/wazuh-qa/test_wazuh, inifile: pytest.ini
collected 12 items                                                                  

test_report_changes_and_diff.py ......                                        [ 50%]
test_report_deleted_diff.py ......                                            [100%]

==================== 12 passed in 421478.34s (4 days, 21:04:38) =====================
```

_We have to change `date` for some tests so the time spent is not accurate._
