### ISSUE TITLE
Automate testing for 'syscheck'

### ISSUE THREAD

**Issue by druizz90** [wazuh/wazuh-qa#152]
# Description

This issue is a subtask of #7. We need to test a lot of different configurations of Wazuh for each test. We should avoid using a new `ossec.conf` file for each different configuration that we want to use.

We could use an external `YAML` file for including multiple configurations and run the tests once for each configuration. We will consider sections of `ossec.conf` in this iteration. A new configuration will have the same content in `ossec.conf` except the section which is being tested.

# Branch

The progress of this issue could be found in branch https://github.com/wazuh/wazuh-qa/tree/fim-integration-tests-environments

# Implementation

New functions made for this development will be included in `wazuh_testing` package for testing more modules in the future. 

A collection of tests will include a `conftest.py` file for integrating the common `pytest` fixtures for these tests.

# Subtasks

- [x] Add in `wazuh_testing` package functions for conversing a configuration in `YAML` to `XML` (`ossec.conf`). `XML` syntax of Wazuh does not follow the standard. The order of `XML` attributes is important in the configuration of Wazuh. We should check that the conversion of `YAML` to `XML` does not change the order of the `XML` attributes.

- [x] Create `pytest` fixtures for loading the different configurations placed in the `YAML` file.

- [x] Adapt old tests to the new format.
