### ISSUE TITLE
Create integration tests for the agent key polling module

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh-qa#1522]
### Description

One of the requirements of https://github.com/wazuh/wazuh/issues/9092 is to create integration tests that cover the feature that will be added.

There exist a couple of tests to check the behavior of the agent key polling in a cluster:

**Deps files**
- [key_polling_api.py](https://github.com/wazuh/wazuh-qa/blob/master/deps/wazuh_testing/wazuh_testing/tools/key_polling_api.py)
- [key_polling_cluster.py](https://github.com/wazuh/wazuh-qa/blob/master/deps/wazuh_testing/wazuh_testing/tools/key_polling_cluster.py)

**Tests**
- [test_key_polling](https://github.com/wazuh/wazuh-qa/tree/master/tests/integration/test_cluster/test_key_polling)

We have to reuse as much code as possible.

### Use cases to test

- [ ] On a master node, the agent key polling request to Authd to register the agent
- [ ] On worker nodes, the request is forwarded to the master node

### Subtasks

**Module tools**

- [ ] Deps files with fixtures, config, tags, callbacks, etc.
- [ ] Monitor the output to Authd

**Mocks**

- [ ] Function to connect an unregistered agent (trigger)
- [ ] Script to provide the key to the agent key polling module

**Tests**
- [ ] Create test for use case 1 (master node)
- [ ] Create test for use case 2 (worker node)

**Misc**

- [ ] Add documentation for the added tests
