### ISSUE TITLE
Create tools to automate the deployment and configuration of a local environment for testing

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#1533]
To speed up the testing process, we want the person who launches the tests to be totally unconcerned about everything related to the environment.

To do this, we must be developed tools that allow us to automate the deployment and configuration of the **local** environment that will be used to launch the set of tests.

In the first place, it is proposed to automate the following:

- [ ] Deployment
  - [ ] Vagrant
  - [ ] Docker
- [ ] Setting:
  - [ ] Wazuh installation and configuration
  - [ ] Download and installation of the testing framework
- [ ] Script to automate the deployment and configuration of the environment

The objective is that a test(s) run is completely carried out in a clean environment and in an automated way.

**Comment by antoniomanuelfr** [comment]
# QA-CTL Documentation

## Introduction
QA-CTL is a tool that will help developers to launch several types of tests. This tool is able to create the test environment (it can be a Virtual Machine, a container, or an AWS instance), install the dependencies, install Wazuh and the Wazuh QA framework and finally execute the test and get the results.  

The following image shows a flow diagram of how the tool works:


The infrastructure module is in charge of creating the needed VMs, containers, or AWS instances. 
The provisioning module is in charge of installing Wazuh and the QA framework. This module also installs all the dependencies to execute the tests. 
Finally, the run_test module is responsible for executing the tests and collect the results.

The user will interact with each module using the qa-ctl tool. This tool takes a configuration file in YAML format with the information needed by each module.
## System requirements
- Linux Host 
- Python
- Docker
- Vagrant
- VirtualBox
- Ansible

This tool will also need the following python libraries installed:

- ansible-runner==2.0.1
- docker==5.0.0
- filetype==1.0.7
- lockfile==0.12.2
- pathlib==1.0.1
- python-vagrant==0.5.15
- PyYAML==5.4.1

## Infrastructure
The infrastructure module can create virtual machines using vagrant. To accomplish it, this module will take the information from the configuration file and will create the Vagrantfile using that information. 
This module can also use Docker to create containers.  It will use an existing Dockerfile (specified in the configuration file) to build an image that will be used to run the containers.

The configuration section for the infrastructure module must follow the next structure:
```yaml
host1:
       provider:
           vagrant:
               enabled: True/False (Required)
               vagrantfile_path: String (Required)
               vagrant_box: String (Required)
               vm_memory: Number(int) (Required)
               vm_cpu: Number(int) (Required)
               vm_name: String (Required)
               vm_system: String (Required)
               label: String (Required)
               vm_ip: IP address (Required)
               quiet_out: True/False (Optional) default: False
 
   
   host2:
       provider:
           docker:
               enabled: True/False (Required)
               dockerfile_path: String (Required)
               name: String (Required)
               remove: True/False (Optional) default: False
               ports: (optional) default: Empty
               detach: True/False (Optional) default: True
               stdout: True/False (Optional) default: False
               stderr: True/False (Optional) default: False

```

### Options using Vagrant as the provider:

- enabled: If False, the VM won’t be created.
- vagrantfile_path: Path where the vagrantfile will be created.
- vagrant_box: Path to the vagrant box file, link, or box specifying the box that will be used.
- vm_memory: Memory assigned to the VM.
- vm_cpu: Number of CPUs assigned to the VM.
- vm_system:  VM operative system.
- Label: Assign a label to the VM.
- quiet_out: Hides the vagrant output. Defaults to True.

### Options using Docker as the provider:
- enabled: If False, the VM won’t be created.
- dockerfile_path: Path to an existing dockerfile.
- name: Name assigned to the container.
- remove: Remove the container after the execution. Defaults to False.
- Ports: Ports to bind to the container.
- detach: Run the container in the background. Defaults to True.
- stdout: Return logs from STDOUT when detach=False.
- Stderr: Return logs from STDERR when detach=False.

## Deployment

The provisioning module takes care of the complete installation of Wazuh and the QA framework. Downloading the necessary files according to the type of installation configured. The different parameters are:

```yaml
   hosts:
       host1:
           host_info:
               connection_method: String with the connection method
                                  selected, example 'ssh' (Required)
               host: String with the IP or DNS of the host (Required)
               user: String with the user name (Required)
               password: String with the user password (Required)
               connection_port: String with the port number to connect (Required)
               ansible_python_interpreter: String with the python path (Required)
 
           wazuh_deployment:
               wazuh_installation:
                   type: String 'sources' or 'package' (Required)
                   target: String 'manager' or 'agent' (Required)
                   wazuh_branch: String with the branch (Required)
                   installation_file_path: String with the path where to place
                                           Wazuh repo (Required)
                   wazuh_install_path: String with the path (Not required,
                                       by default '/var/ossec')
 
           qa_framework:
               wazuh_qa_branch: String with the branch (Required)
               qa_workdir: String with the path where to place qa repo (Required)
 
       host2:
           host_info:
           ...
   groups:
       group_name1:
           hosts:
               - String with the IP or DNS of the host (Required)
               - String with the IP or DNS of the host (Required)
               - ...
       group_name2:
           hosts:
               - String with the IP or DNS of the host (Required)
               - String with the IP or DNS of the host (Required)
               - ...
       group_name3:
           ...
 
```

## Test Execution
The Pytest module is in charge of collecting all the tests from the configuration file and executing them. The current flow in the qa_ctl.py tool for this is the following: 

The syntax of the tests definition is the following:
```yaml
tests:
    - type: pytest
      path:
          test_files_path:
          test_results_path:
      parameters:
          tier: str
          stop_after_first_failure: boolean
          keyword_expression: str
          traceback: str
          dry_run: boolean
          custom_args: str
          verbose_level: int
          log_level: str
          markers: list(str)

```

QARunTests reads all the tests under the `tests` keyword, and for everyone, it saves all the data in an instance ready to be executed by TestLauncher. Every test keyword follows the syntax test1, test2, … tests. TestLauncher receives in the constructor a list of tests to be executed from the `RunQATests` instance. 

### Tests configuration fields:

    - hosts: A list of desired hosts where the test must be executed. Every host in this list is represented by the same ip address used in every particular host under provision: hosts: If this field value is empty, then the test will be executed in every host defined in ansible inventory.
    - type: Tool used to run the tests. Currently, this field has no effect, pytest is the only tool allowed.
 
    - path: this key holds the three following paths (the three are required)
    - test_files_path: The path pointing to the folder containing the desired tests to be executed.
    - run_tests_dir_path: The path to the folder from where we want to execute the tests (can be different from test_files_path)
            -test_results_path: The path to the folder in the local machine where the test reports will be stored.
    
    - parameters: extra parameters for pytest
        - tiers: a list containing all the tiers to launch
            - stop_after_first_failure: -x option, stop the execution after the first failure
            - keyword_expression: it works along test_files_path, if this value is empty then runs all the tests in test_file_path. If it’s not empty, then there must be a valid regex to select specific tests in that folder.
          - traceback: modify the traceback printing of python [auto, long, short, native, line, no]
          - dry_run: collects all the tests but don’t run them
          - custom_args: custom parameters for the tests, currently this option hasn’t been tested
          - verbose_level: add the option --verbose
          - log_level: sets the log level for the tests, currently this option hasn’t been tested
          - markers: allow to add markers to pytest command. If the test has a decorator with the same marker, then it will be executed.

## QA-CTL
The qa-ctl tool is the interface between the user and the modules explained above. This tool will read a configuration file containing the different options for each module and will execute each module (if it’s needed).

The tool will be installed alongside the wazuh_testing package. Once the wazuh_testing package is installed, this tool can be called from the command line.

The configuration file will contain a section for each module. Each section must follow the configuration syntax for each module. 
An example of this file can be found at https://github.com/wazuh/wazuh-qa/blob/qa-ctl/deps/conf.yaml.

Now. a successful execution of the qa-ctl tool using the previous configuration file with a custom vagrant box with all the dependencies installed, is going to be shown (the vagrant output is going to be omitted, as it produces a very long output when the quiet_out is set to False):


```
(QACTL) ➜  deps git:(qa-ctl) ✗ qa-ctl -c conf.yaml           
{'ubuntu': '{"ubuntu": {"box_image": "bento/ubuntu-20.04", "vm_label": "Label", "cpus": 1, "memory": 1024, "system": "/Linux", "private_ip": "10.2.0.3"}}', 'ubuntu2': '{"ubuntu2": {"box_image": "bento/ubuntu-20.04", "vm_label": "Label", "cpus": 1, "memory": 1024, "system": "/Linux", "private_ip": "10.2.0.4"}}'}

PLAY [10.2.0.3] ****************************************************************

TASK [Create None/wazuh path] **************************************************
changed: [10.2.0.3]

TASK [Clone wazuh repository] **************************************************
changed: [10.2.0.3]

PLAY RECAP *********************************************************************
10.2.0.3                   : ok=2    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   


PLAY [10.2.0.3] ****************************************************************

TASK [Gathering Facts] *********************************************************
ok: [10.2.0.3]

TASK [Render the "preloaded-vars.conf" file] ***********************************
changed: [10.2.0.3]

TASK [Executing "install.sh" script to build and install Wazuh] ****************


```
