### ISSUE TITLE
Create a tool to automate the Wazuh provisioning and QA framework

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#1534]
We want to develop a tool that allows us to provision a machine with everything we need to launch the tests. To do so, we propose to install the following:

- Everything related to the deployment and configuration of a Wazuh environment.
- Everything related to the testing framework and tools used for QA.

**Technical requirements**

- Provisioning can be performed locally or remotely. For the remote part, it is proposed to use ansible.
- Deployments of wazuh-manager and wazuh-agent can be performed.
- The design must support cluster wazuh environments.
- The wazuh installation can be done via packages or sources.
- A wazuh package when installing:
  - Can be downloaded from S3.
  - Can be shared from local.
- The initially supported systems must be the following:
  - Amazon Linux 2
  - Windows 2016
  - macOS Mojave
  - Solaris 11

**Proposed design (updated)**

![provision_class_diagram_model_2(1)](https://user-images.githubusercontent.com/23462183/124901702-87454980-dfe2-11eb-9e84-b291ca490f5a.png)

## Development of the issue

- [x] **Design of the provisioning package**: Contains what is needed to provision Wazuh and QA framework.
- [x] **Design of the ansible package**: Contains what is needed to manage calls to ansible to run remote provisioning playbooks.
- [x] **Design of the qa_provisioning script**: Receives a set of parameters and provision all specified hosts (local or remote).
- [x] Module implementation:
  - [x] https://github.com/wazuh/wazuh-qa/issues/1595
  - [x] https://github.com/wazuh/wazuh-qa/issues/1596
  - [x] https://github.com/wazuh/wazuh-qa/issues/1594

**Comment by jmv74211** [comment]
## Design of the provisioning package

To carry out the provisioning of Wazuh and the QA framework, the following design has been proposed:

![provision_class_diagram(1)](https://user-images.githubusercontent.com/23462183/124630350-a0cf7f80-de82-11eb-9ca4-7940532368b3.png)

This design is flexible to be able to create 1 or n Wazuh deployments, along with their specific configurations. It meets the requirements specified in the issue description.

**Comment by jmv74211** [comment]
## Design of the ansible package

In order to carry out the remote provisioning, it has been designed an ansible module that allows us to define and run remote tasks using `ansible-runner` python module.

![Untitled Diagram](https://user-images.githubusercontent.com/23462183/124909152-6a147900-dfea-11eb-95d6-040ff426d735.png)


This design allows defining the ansible inventory and playbook as a code instead of using only yaml files, although these files can also be loaded.

**Comment by jmv74211** [comment]
## Design of the QA provisioning script flow

The main objective of this script is to provide a parameterized tool that allows us to provision a machine with the needed dependencies to run the tests. These dependencies can be summarized in the wazuh environment and QA framework deployment.

This provisioning can be made in a local or remote machine, represented by the following flow:

![qa_provisioning_flow_chart](https://user-images.githubusercontent.com/23462183/124910913-713c8680-dfec-11eb-83d0-edfe449767f7.png)

**Comment by snaow** [comment]
Closed by https://github.com/wazuh/wazuh-qa/pull/1683
