### ISSUE TITLE
Content improvements for integration tests documentation

### ISSUE THREAD

**Issue by snaow** [wazuh/wazuh-qa#1536]
The team has the current need of improving the current integration tests documentation, currently, it is taking too much time to gather all the results and copy them manually into the.MDs files.

Moreover, the tests are not enough well documented in terms of metadata (tiers, modules, daemons, tags, versions, min version, max version).

It is required to create competitive and well-organized documentation. We should make it easier for all the teams (QA included) to consult and search for any executable test created. 
We should enforce as much as possible the in-code documentation within all the individual tests (docstrings).

This Epic should: 
- Create self-documented tests.
- Parse the required fields
- Create a structure of JSON files as the output.

## Tasks

- [x] https://github.com/wazuh/wazuh-qa/issues/1598
- [ ] https://github.com/wazuh/wazuh-qa/issues/1599
- [x] https://github.com/wazuh/wazuh-qa/issues/1601
- [ ] https://github.com/wazuh/wazuh-qa/issues/1626
- [x] https://github.com/wazuh/wazuh-qa/issues/1606
- [x] https://github.com/wazuh/wazuh-qa/issues/1608
- [x] https://github.com/wazuh/wazuh-qa/issues/1628
- [x] https://github.com/wazuh/wazuh-qa/issues/1639
- [x] https://github.com/wazuh/wazuh-qa/issues/1640
- [x] https://github.com/wazuh/wazuh-qa/issues/1642
- [x] https://github.com/wazuh/wazuh-qa/issues/1641
- [x] https://github.com/wazuh/wazuh-qa/issues/1664
