### ISSUE TITLE
Add new molecule testing scenario for elastic cluster with xpack

### ISSUE THREAD

**Issue by xr09** [wazuh/wazuh-qa#155]
# Description

In order to improve our Ansible tests we need to add a new Molecule testing scenario for an Elastic cluster with XPack enabled.

# Subtasks

- [x] Create new testing scenario in Molecule
- [x] Implement XPack specific tests with testinfra

**Comment by xr09** [comment]
Hi team,

Thinking of adding these tests for this  specific scenario:

- [ ] Test xpack settings are present in `/etc/elasticsearch/elasticsearch.yml`
- [ ] Get a valid response from port 9200 using `https`
- [ ] Check elasticsearch version number from previous response

If anyone thinks of anything else to test please add it to this issue.

Regards.

**Comment by xr09** [comment]
Hello team,

I'm hitting a wall here, when creating the tests for this xpack enabled scenario I'm deploying with `elasticsearch_network_host: 0.0.0.0` in order to be able to run a `curl localhost` from the testinfra task later.

But here's the issue, there is a task to wait for elasticsearch to be available:

https://github.com/wazuh/wazuh-ansible/blob/120ed163b6f131315848938beca65c1f1cad7f1b/roles/elastic-stack/ansible-elasticsearch/tasks/main.yml#L254-L258

This will make a request to `0.0.0.0` but elastic config (our `elasticsearch_network_host`) also accepts variables like `_[networkInterface]_` or `_local_`. Clearly not the intended behavior for this task.

In order to separate the `network.host` value on elasticsearch and the reachable address where we make requests to, let's add another variable and call it `elasticsearch_reachable_address`.

The playbook will look like this:

![Screenshot_20191001_100127](https://user-images.githubusercontent.com/1380243/65944638-6f668c00-e432-11e9-98a2-f2904a6589ef.png)

Regards.
