### ISSUE TITLE
Visualization improvements for integration tests documentation

### ISSUE THREAD

**Issue by palaciosjeremias** [wazuh/wazuh-qa#1600]
The team has the current need of improving the current integration tests documentation, currently, it is taking too much time to gather all the results and copy them manually into the.MDs files.

Moreover, the tests are not enough well documented in terms of metadata (tiers, modules, daemons, tags, versions, min version, max version....).

It is required to create competitive and well-organized documentation. We should make it easier for all the teams (QA included) to consult and search for any executable test created. 
We should enforce as much as possible the in-code documentation within all the individual tests (docstrings).

This Epic should: 
- Use the JSON files from Epic [1536](https://github.com/wazuh/wazuh-qa/issues/1536) as input.
- Display the information in a user-accessible interface.
- Bring the possibility of easily compile and preview the documentation in a local environment. (Under analysis)
- Add an  complete, complex and efficient search method to navigate the documentation (Under analysis to be a different epic)

## Tasks
- [x] https://github.com/wazuh/wazuh-qa/issues/1627
- [x] https://github.com/wazuh/wazuh-qa/issues/1666
- [x] https://github.com/wazuh/wazuh-qa/issues/1681
