### ISSUE TITLE
Disable unused modules for Vulnerability Detector Tests

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#1605]
## Description

After seeing a lot of [fails vulnerability Detector Tests](https://github.com/wazuh/wazuh-qa/issues/1531), we detect that when disabled sca, syscollector, and rootcheck modules it works successfully.

We can do a Cherry-pick using this commit: 
- https://github.com/wazuh/wazuh-qa/commit/bf821f487214b751fe52a48e44b7b11f2359306b

### Package Details
 
|  Jenkins branch  | QA branch   |  Version 	|   Revision | 
|- |- |- |- |
|  4.2 |   1516-4.2.0-full-green | 4.2  |  1.1493 | 

Type | Format | Architecture | Version | Revision | Tag | File name
-- | -- | -- | -- | -- | -- | --
Server | rpm | x86_64 | 4.2.0 | 40207 | v4.2.0-rc8 | wazuh-manager-4.2.0-1.1493.x86_64.rpm

### Environment 

Provider| Box| OS| CPU| Memory | 
--|--|--|--|--|
Vagrant | centos/8 | CentOS 8 | 2 | 1024 |

### Setup Local_internal_opcion.conf
```
wazuh_modules.debug=2
monitord.rotate_log=0
```

## Development 

- [x] Apply Fix (cherry-pick)
- [x] Full Green/ Full Yellow for 3 times to  https://github.com/wazuh/wazuh-qa/issues/1543
- [x] Full Green/ Full Yellow for 3 times to  https://github.com/wazuh/wazuh-qa/issues/1544
- [x] Full Green/ Full Yellow for 3 times to https://github.com/wazuh/wazuh-qa/issues/1551
- [x] Full Green/ Full Yellow for 3 times to https://github.com/wazuh/wazuh-qa/issues/1552
- [x] Full Green/ Full Yellow for 3 times to https://github.com/wazuh/wazuh-qa/issues/1554
- [x] Full Green/ Full Yellow for 3 times to https://github.com/wazuh/wazuh-qa/issues/1561
- [x] Full Green/ Full Yellow for 3 times to https://github.com/wazuh/wazuh-qa/issues/1566
- [x] Full Green/ Full Yellow for 3 times to https://github.com/wazuh/wazuh-qa/issues/1567
- [x] Full Green/ Full Yellow for 3 times to https://github.com/wazuh/wazuh-qa/issues/1568
- [x] Full Green/ Full Yellow for 3 times to https://github.com/wazuh/wazuh-qa/issues/1569
- [x] Merge to `1531-full-yellow-vuln-det`

**Comment by damarisg** [comment]
Closed by #1607
