### ISSUE TITLE
Syscheck automated tests: 'restrict' option

### ISSUE THREAD

**Issue by crd1985** [wazuh/wazuh-qa#164]
| Working branch |
| --- |
|[fim-integration-tests-restrict](https://github.com/wazuh/wazuh-qa/tree/fim-integration-tests-restrict) |

## Description

This issue is part of the roadmap in #7.

The `restrict` attribute limits checks to files containing the entered string in the file name.

## Subtasks
- Realtime
  - [x] Restrict to file/s in a directory
  - [x] Restrict to file/s in a subdirectory
  - [x] Restrict to file/s in a directory using sregex
  - [x] Restrict to file/s in a subdirectory using sregex
  - [x] Restrict to file/s using empty sregex
  - [x] Restrict with a typo in sregex

- Whodata

  - [x] Restrict to file/s in a directory
  - [x] Restrict to file/s in a subdirectory
  - [x] Restrict to file/s in a directory using sregex
  - [x] Restrict to file/s in a subdirectory using sregex
  - [x] Restrict to file/s using empty sregex
  - [x] Restrict with a typo in sregex

- Scheduled

  - [x] Restrict to file/s in a directory
  - [x] Restrict to file/s in a subdirectory
  - [x] Restrict to file/s in a directory using sregex
  - [x] Restrict to file/s in a subdirectory using sregex
  - [x] Restrict to file/s using empty sregex
  - [x] Restrict with a typo in sregex
