### ISSUE TITLE
Syscheck automated tests: 'follow_symbolic_link' option

### ISSUE THREAD

**Issue by crd1985** [wazuh/wazuh-qa#165]
------------------
| Working branch |
| --- |
| |
|[fim-integration-tests-follow-symbolic-link](https://github.com/wazuh/wazuh-qa/tree/fim-integration-tests-follow-symbolic-link)
## Description

This issue is part of the roadmap in #7.

~The `follow_symbolic_link` attribute activates the detection of file changes beyond a path containing a symbolic link.~ This attribute is deprecated. You need to add the symbolic link absolute path to make syscheck follow it. 
```XML
<directories>/testdir/symbolic_link</directories>
```

## Subtasks

The following tests should be implemented for Scheduled. Real-Time and Whodata using a configuration similar to this one: 
```XML
<directories>/testdir/</directories>
```
- [x] Create a symbolic link pointing to a file in a monitored directory. Modify the target file and ensure that no alerts are raised for the symbolic link file. Modify the target of the link. A modification event must be raised. Remove the new target file and then restore it. No events for the link should be raised.
- [x] Create a symbolic link pointing to a folder in a monitored directory. Modify some files in the folder and ensure that no alerts are raised for the symbolic link file. Change the target of the link to another folder. A modification event must be raised. Remove the new target folder and then restore it. No events for the link should be raised.

The following tests should be implemented for Scheduled. Real-Time and Whodata using a configuration similar to this one: 
```XML
<directories>/testdir/</directories>
<directories>/testdir/symlink</directories>
<directories>/anothermonitoreddir/</directories>
```
- [x] Having a symbolic link pointing to a file, modify and delete the file. Check that alerts are being raised.
- [x] Having a symbolic link pointing to a file, change the target of the link to another file. Ensure that the old file is being monitored and the new one is not before symlink_checker runs. Wait until symlink_checker runs and ensure that the new file is being monitored and the old one is not.
- [x] Having a symbolic link pointing to a file, remove that file and check that deleted event is detected. Once symlink_checker runs create the same file. No events should be raised. Wait again for symlink_checker run and modify the file. Modification event must be detected this time.
- [x] Having a symbolic link pointing to a file, remove that symbolic link file, wait for the symlink checker runs and modify the target file. No events should be detected. Restore the symbolic link and modify the target file again once symlink checker runs. Events should be detected now.
- [x] Having a symbolic link pointing to a file, change its target to another file inside a monitored folder. After symlink_checker runs check that no events for the previous target file are detected while events for the new target are still being raised.
- [x] Having a symbolic link pointing to a file, change its target to a folder. Check that the old file is not being monitored anymore and the new folder is. Revert the target change and ensure the file is being monitored and the folder is not.
- [x] Having a symbolic link pointing to a folder, create, modify and delete files inside that target folder. Check that alerts are raised.
- [x] Having a symbolic link pointing to a folder, change the target of the link to another folder. Ensure that the old folder is being monitored and the new one is not before symlink_checker runs. Wait until symlink_checker runs and ensure that the new folder is being monitored and the old one is not.
- [x] Having a symbolic link pointing to a folder that contains several files, remove that folder and check that deleted events for the files are detected. Once symlink_checker runs create the same folder with several files inside. No events should be raised. Wait again for symlink_checker run and modify one of these files. Modification events must be detected.
- [x] Having a symbolic link pointing to a folder that contains several files, remove that symbolic link file, wait for the symlink checker runs and modify files inside the folder. No events should be detected. Restore the symbolic link and modify files inside the folder once symlink checker runs. Events should be detected now.
- [x] Having a symbolic link pointing to a folder, change its target to another monitored folder. After symlink_checker runs check that no events for the previous target folder are detected while events for the new target are still being raised.

**Comment by vicferpoy** [comment]
## Status update
Tests for symbolic links that are not being monitored (scan is not following them) are finished. They are tested in scheduled, real-time and whodata modes.

## Tests performed
```
========================================== test session starts ==========================================
platform linux -- Python 3.6.8, pytest-5.3.0, py-1.8.0, pluggy-0.13.0
rootdir: /vagrant/wazuh-qa/test_wazuh, inifile: pytest.ini
collected 6 items                                                                                       

test_follow_symbolic_link.py ......                                                               [100%]

=============================== 6 passed in 374525.39s (4 days, 8:02:05) ================================
```
## Pending
- We need to implement tests for monitored symbolic links.
