### ISSUE TITLE
Syscheck automated tests: 'nodiff' option

### ISSUE THREAD

**Issue by crd1985** [wazuh/wazuh-qa#166]
| Working branch |
| --- |
|[fim-integration-tests-nodiff](https://github.com/wazuh/wazuh-qa/tree/fim-integration-tests-nodiff)|

## Description

This issue is part of the roadmap in #7.

The `nodiff` tag sets a list of files to not compute the diff (one entry per line). It should be used with the `report_changes` options enabled.

## Subtasks
All assuming `report_changes` is enabled.

- Realtime
  - [x] Set nodiff to file/s in a directory
  - [x] Set nodiff to file/s in a subdirectory
  - [x] Set nodiff to file/s in a directory using sregex
  - [x] Set nodiff to file/s in a subdirectory using sregex
  - [x] Set nodiff to file/s using empty sregex
  - [x] Set nodiff with a typo in sregex

- Whodata

  - [x] Set nodiff to file/s in a directory
  - [x] Set nodiff to file/s in a subdirectory
  - [x] Set nodiff to file/s in a directory using sregex
  - [x] Set nodiff to file/s in a subdirectory using sregex
  - [x] Set nodiff to file/s using empty sregex
  - [x] Set nodiff with a typo in sregex

- Scheduled

  - [x] Set nodiff to file/s in a directory
  - [x] Set nodiff to file/s in a subdirectory
  - [x] Set nodiff to file/s in a directory using sregex
  - [x] Set nodiff to file/s in a subdirectory using sregex
  - [x] Set nodiff to file/s using empty sregex
  - [x] Set nodiff with a typo in sregex

**Comment by vicferpoy** [comment]
# Status update
## Summary
Development is almost finished. Tests pass right now but I need to try them again after refactoring the new code from the branch `fim-integration-tests`.

## Difficulties
* I spent most of the time trying to fix errors caused by external functions. Those are fixed now.

## Pending
* I will update tests results once I refactor the code.

**Comment by vicferpoy** [comment]
# Status update
## Summary
Development is finished. Every test passes and they cover every check in the issue.

## Tests performed

```
================================ test session starts ================================
platform linux -- Python 3.6.8, pytest-5.2.0, py-1.8.0, pluggy-0.13.0
rootdir: /vagrant/shared/wazuh-qa/test_wazuh, inifile: pytest.ini
collected 568 items                                                                 

test_no_diff_invalid.py .                                                     [  0%]
test_no_diff_valid.py sssssssssssssssssss......s......ssss.sssss....s......ss [  9%]
ss.sssss....s......ssss.sssss................s.sss..................sss...... [ 23%]
............sss....s......s.s..s.sss....s......s.s..ss.sssssssssssssssssssss. [ 36%]
.....s......ssss.sssss....s......ssss.sssss....s......ssss.sssss............. [ 50%]
...s.sss..................sss..................sss....s......s.s..s.sss....s. [ 64%]
.....s.s..ss.sssssssssssssssssssss......s......ssss.sssss....s......ssss.ssss [ 77%]
s....s......ssss.sssss................s.sss..................sss............. [ 91%]
.....sss....s......s.s..s.sss....s......s.s..ss.ss                            [100%]

====================== 349 passed, 219 skipped in -4490579.17s ======================
```
