### ISSUE TITLE
Development of new pipeline to reproduce the problem when re-registering agents

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#1668]
It is required to develop a new pipeline that allows us automate the environment deployment which is composed of a wazuh cluster of n nodes and a large number of agents connected to these nodes.

Customized scripts will be launched in the cluster nodes as well as in the agents that will allow us to perform the re-registration tasks and the monitoring of the time it takes to reload the `client-keys`, `agent.timestamps` and the time to synchronize the `client.keys` in the cluster so that the API can finally see them connected.

Starting from the cluster performance test pipeline, we are asked to use this skeleton to build a new pipeline with the following requirements:

## Requirements

- 1 or n nodes can be deployed for the wazuh cluster (n<=25).
- A certain number of real agents have to be deployed. The goal is to deploy about 4,000 agents.
- The load of the agents has to be balanced among the different nodes of the cluster.
- The versions of wazuh are as follows:
  - Wazuh-managers: `4.1.2`
  - Wazuh-agents:
     - ~1k: `3.13`
     - ~3k: `4.x`

## Tasks

- [ ] Create a new pipeline in Jenkins staging UI.
- [ ] Development of the initial pipeline structure.
- [ ] Deployment of EC2 instances for Wazuh cluster nodes.
- [ ] Provisioning and configuration of cluster nodes.
- [ ] Research on the most optimal way to create n instances or dockers for agents.
- [ ] Deployment of agent instances.
- [ ] Deploying and configuring an AWS network load balancer.
- [ ] Integration of agent re-registration and monitoring scripts.

**Comment by jmv74211** [comment]
I have been working on this issue development. I have finished the following tasks:

- Create a new pipeline in Jenkins staging UI.
- Development of the initial pipeline structure.
- Deployment of EC2 instances for Wazuh cluster nodes.
- Provisioning and configuration of cluster nodes.
- Deploying and configuring an AWS network load balancer.

All this development has been done in this branch https://github.com/wazuh/wazuh-jenkins/tree/qa-1668-development

In addition, it has been tested in Jenkins and it works.

![image](https://user-images.githubusercontent.com/23462183/127532870-0a3414f7-f231-4e64-926a-ae9108a54e15.png)

Tomorrow, I will continue studying the best way to deploy the massive agents.

**Comment by jmv74211** [comment]
Today I have been investigating how we are going to deploy all the necessary agents.

In principle, the AWS Fargate service is going to be used, where we are going to raise one agent per container. The size of the container will be 0.5vcpu and 1GB of RAM. That container is going to be launched in a task, which will be deployed in parallel along with the rest grouped in batches of 10.

I have been adding parameters, creating the container image to upload to ECR, and then uploading it to ECS's Wazuh QA cluster.

I have also been working on the script that will run each agent, which basically consists of:

- Install the agent
- Register the agent
- Configure some specific parameters of enrollment
- Do a standby
- Uninstall
- Repeat the above process n times

**Comment by jmv74211** [comment]
Today I have been working on preparing the necessary environment where the agent is going to be installed, as well as designing and implementing the processes involved in installing, configuring and uninstalling the agents within the ECSTasks.


To do this, I built a docker image, and uploaded it to ECR. In addition, I have implemented the script that will execute each task in order to simulate the re-registration of agents. See https://github.com/wazuh/wazuh-jenkins/commit/3d5954b8339b00191d0e1ab2adf1199ec37ce574

Finally, I've been adding necessary changes in the re-registration agents pipeline to create the task groups dynamically and launch them using AWS fargate. See https://github.com/wazuh/wazuh-jenkins/commit/3aba090adf4c7227b5dda2a868a0b4a6699f08cb

It remains to verify the correct functioning integrated in the pipeline (everything has been tested in a unitary way), and once we have that, to test each time with a higher number of agents to see how the environment behaves.

As soon as this is finished and the core team has completed the monitoring scripts, these scripts will be integrated into the pipeline to collect and analyze the data obtained from the deployed environment.

**Comment by jmv74211** [comment]
Today I have been working on deploying the agents and checking that each one performs the desired process.

First of all, it was necessary to update the entrypoint to add new parameters, along with a timeout function to ensure that the task finishes after the expected time. These changes can be seen here https://github.com/wazuh/wazuh-jenkins/commit/b7c701848677b1c5bcba400af7b107b27df5f00b

We have also been updating the re-registration pipeline to dynamically calculate the times for each agent task, along with deployment and error control. The load balancer parameters have also been modified to allow registrations from the cluster. These changes can be seen here https://github.com/wazuh/wazuh-jenkins/commit/94ff7355e71d5cfca76445ac3511af4e3fcd0ebf

As development stands now, we are able to deploy a manager environment and connect x agents that are constantly performing the re-registration process.

Now we need to wait for the core team to provide us with the monitoring scripts, so that we can integrate them into the pipeline.

In the meantime, the full pipeline functionality will be further tested.

**Comment by jmv74211** [comment]
Today I have been developing the part of stopping the re-registration of the agents after a specified time, in order to monitor the subsequent behavior and the state of the environment.

To do this, I have added a new phase called "Valley", in which the agents are going to be connected but without performing any action. The related changes can be seen here https://github.com/wazuh/wazuh-jenkins/commit/9df0ae0967e85a1237c7a6cf9fdfce9bb6360101

I have also modified the re-registration pipeline to dynamically calculate this time and specify it to the agents' entrypoint https://github.com/wazuh/wazuh-jenkins/commit/e19f29074c5aca62b9b9a3d77f9464869e1158f6 .


On the other hand, I have been helping in the validation of the monitoring script, and I have been working on the realization of a script to draw graphs of the data from the CSV generated in the monitoring stage.

It remains to integrate the monitoring script (when the core team validates it), plot all the data and get them in the form of JenkinsArtifacts.

**Comment by jmv74211** [comment]
Today I have been working on the integration of the monitoring script and the development of the generation of graphs of the results https://github.com/wazuh/wazuh-jenkins/blob/qa-1668-development/quality/tests/custom/test_re_registering_agents/monitoring.sh.

The integration of the script has been done through ansible, because through a simple call, we can run the script on the remote nodes and get the results.

Regarding the plotting of the results, I have implemented a couple of python scripts that fits the data structure that the monitoring returns, and I have automated it
in a fargate task https://github.com/wazuh/wazuh-jenkins/commit/542b1b66740682f02da5680d01cc3e307d831a4b. 

I have also made all the necessary pipeline changes to integrate and automate the described task https://github.com/wazuh/wazuh-jenkins/commit/7d0076d8efc8ebe3aa55c88dd0ff5aaad84047b8.

In principle, all developments proposed in this issue are already completed. Here is a Jenkins build, with the results ([see artifacts]())

It remains to test executions with a larger number of agents and evaluate the results according to the parameters entered.

**Comment by jmv74211** [comment]
Today I have been working on the graphs improvements and debugging the re-registration pipeline.

It has been already finished the development stage, and all is ready to launch different stages and obtain the results.

The pipeline to use is https://devel.ci.wazuh.info/job/Test_re_registering_agents and an example of the obtained results is https://devel.ci.wazuh.info/job/Test_re_registering_agents/87/artifact/artifacts.tgz

**Comment by jmv74211** [comment]
Today we have been launching builds to try to reproduce the user scenario. In a build with 1000 agents we have seen that there is no problem. We decided to add by default a `client-keys `and an `agents-timestamps` file with 50000 entries each, and just after that we started to observe the reproduced behavior of the client.

On the other hand, I have been improving the script to generate graphs and investigating the way to be able to deploy the agents in a faster way. I am still working on it.

**Comment by jmv74211** [comment]
This issue has been closed because with the current changes we seem to be getting the expected results.

In principle no further development is needed on this part, it will be reopened or a new one will be opened if necessary.
