### ISSUE TITLE
Syscheck automated tests: 'scan_*' options

### ISSUE THREAD

**Issue by crd1985** [wazuh/wazuh-qa#167]
| Working branch |
| --- |
|[fim-integration-tests-scan](https://github.com/wazuh/wazuh-qa/tree/fim-integration-tests-scan)|

## Description

This issue is part of the roadmap in #7.

- The `scan_time` tag sets the time to run the scans. Times may be represented as 9pm or 8:30.
- The `scan_day` tag sets the day of the week to run the scans(one entry per line). Multiple lines may be entered to include multiple registry entries.
- The `scan_on_start` tag specifies if syscheck scans immediately when started.

## Subtasks
- Realtime
  - [ ] ~Check starting scan is performed with `scan_on_start` to `yes`~
  - [ ] ~Check starting scan is not performed with `scan_on_start` to `no`~

- Whodata
  - [ ] ~Check starting scan is performed with `scan_on_start` to `yes`~
  - [ ] ~Check starting scan is not performed with `scan_on_start` to `no`~

- Scheduled
  - [ ] ~Check starting scan is performed with `scan_on_start` to `yes`~
  - [ ] ~Check starting scan is not performed with `scan_on_start` to `no`~
  - [X] Set valid values of `scan_time` and check if scan starts at the scheduled time
  - [x] Set valid values of `scan_day` and check if scan starts at the scheduled time
  - [x] Set valid values of `scan_time` and `scan_day` and check if scan starts at the scheduled time
  - [x] Set valid values of `scan_time` and `scan_day` to force overlapping of two scans.
  - [x] Set invalid values of `scan_time`
  - [x] Set invalid values of `scan_day`

**Comment by vicferpoy** [comment]
# Status update
## Summary
Development is finished but tests do not always pass. This is due to syscheck running scans when it should not do it. This was reported.

## Difficulties
* It took me a while to realize that tests were doing their job and it was a syscheck bad behaviour.

## Pending
* I need to run every test again once I confirm that syscheck is working as intended to make sure they work.
