### ISSUE TITLE
Syscheck automated tests: 'auto_ignore' option

### ISSUE THREAD

**Issue by crd1985** [wazuh/wazuh-qa#168]
| Working branch |
| --- |
| |

## Description

This issue is part of the roadmap in #7.

The `auto_ignore` specifies whether or not syscheck will ignore files that change too many times (manager only).

## Subtasks
- Realtime
  - [ ] Set auto_ignore tag to yes with a valid timeframe and frequency and see if it ignores events from file/s in a directory
  - [ ] Set auto_ignore tag to yes with a valid timeframe and frequency and see if it ignores events from file/s in a subdirectory
  - [ ] Set auto_ignore tag to no with a valid timeframe and frequency and see if it does not ignore events from file/s in a directory
  - [ ] Set auto_ignore tag to no with a valid timeframe and frequency and see if it does not ignore events from file/s in a subdirectory
  - [ ] Set auto_ignore tag to yes/no with an valid timeframe
  - [ ] Set auto_ignore tag to yes/no with an invalid frequency

- Whodata
  - [ ] Set auto_ignore tag to yes with a valid timeframe and frequency and see if it ignores events from file/s in a directory
  - [ ] Set auto_ignore tag to yes with a valid timeframe and frequency and see if it ignores events from file/s in a subdirectory
  - [ ] Set auto_ignore tag to no with a valid timeframe and frequency and see if it does not ignore events from file/s in a directory
  - [ ] Set auto_ignore tag to no with a valid timeframe and frequency and see if it does not ignore events from file/s in a subdirectory
  - [ ] Set auto_ignore tag to yes/no with an valid timeframe
  - [ ] Set auto_ignore tag to yes/no with an invalid frequency

- Scheduled
  - [ ] Set auto_ignore tag to yes with a valid timeframe and frequency and see if it ignores events from file/s in a directory
  - [ ] Set auto_ignore tag to yes with a valid timeframe and frequency and see if it ignores events from file/s in a subdirectory
  - [ ] Set auto_ignore tag to no with a valid timeframe and frequency and see if it does not ignore events from file/s in a directory
  - [ ] Set auto_ignore tag to no with a valid timeframe and frequency and see if it does not ignore events from file/s in a subdirectory
  - [ ] Set auto_ignore tag to yes/no with an valid timeframe
  - [ ] Set auto_ignore tag to yes/no with an invalid frequency

**Comment by crd1985** [comment]
Close because `auto_ignore` option won't be available in next FIM version.
