### ISSUE TITLE
Syscheck automated tests: 'alert_new_files' option

### ISSUE THREAD

**Issue by crd1985** [wazuh/wazuh-qa#169]
| Working branch |
| --- |
| |

## Description

This issue is part of the roadmap in #7.

The `alert_new_files` specifies if syscheck should alert when new files are created.

## Subtasks
- Realtime
  - [ ] Set `alert_new_files` to `yes`/no and create a new file/s in a directory
  - [ ] Set `alert_new_files` to `yes`/no and create a new file/s in a subdirectory

- Whodata

  - [ ] Set `alert_new_files` to `yes`/no and create a new file/s in a directory
  - [ ] Set `alert_new_files` to `yes`/no and create a new file/s in a subdirectory

- Scheduled

  - [ ] Set `alert_new_files` to `yes`/no and create a new file/s in a directory
  - [ ] Set `alert_new_files` to `yes`/no and create a new file/s in a subdirectory

**Comment by crd1985** [comment]
Closed because `alert_new_files` option won't be available in next FIM version
