### ISSUE TITLE
Syscheck automated tests: 'prefilter_cmd' option

### ISSUE THREAD

**Issue by crd1985** [wazuh/wazuh-qa#171]
| Working branch |
| --- |
| |
|[fim-integration-tests-prefilter-cmd](https://github.com/wazuh/wazuh-qa/tree/fim-integration-tests-prefilter-cmd)|
## Description

This issue is part of the roadmap in #7.

The `prefilter_cmd` tag sets a command to be applied to each checked file.

## Subtasks
- Realtime
  - [x] Set `/usr/sbin/prelink -y` as a prefilter command and check it produces the same event without the prefilter tag.
  - [x] Check if `/usr/sbin/prelink` exists before restarting the service.

- Whodata
  - [x] Set `/usr/sbin/prelink -y` as a prefilter command and check it produces the same event without the prefilter tag.
  - [x] Check if `/usr/sbin/prelink` exists before restarting the service.

- Scheduled
  - [x] Set `/usr/sbin/prelink -y` as a prefilter command and check it produces the same event without the prefilter tag.
  - [x] Check if `/usr/sbin/prelink` exists before restarting the service.

**Comment by vicferpoy** [comment]
# Status update
## Summary
Development is finished.

## Tests performed

```
================================ test session starts ================================
platform linux -- Python 3.6.8, pytest-5.2.1, py-1.8.0, pluggy-0.13.0
rootdir: /vagrant/wazuh-qa/test_wazuh, inifile: pytest.ini
collected 3 items                                                                   

test_prefilter_cmd.py ...                                                     [100%]

=========================== 3 passed in 78.87s (0:01:18) ============================
```
