### ISSUE TITLE
QACTL: Validate configuration file input parameters

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#1711]
`qactl` tool receives a config file that contains all data parameters for deployment, provisioning, testing...

It is necessary that before launching all these processes, the content and structure for this config file are validated.

It is requested to add a new initial stage in `qactl` that validates all input user parameters and their structure.

## Tasks
In order to achieve this new initial stage, several tasks need to be done:
- [x] Read `jsonschema` documentation
- [x] Review  JSON schema validator file
- [x] Implement a validator function to check the conf.yaml parameters
- [x]  Review qa_ctl script code
- [x] Modify & improve JSON schema validator file
- [x] Create a new schema field for the test module
- [x] Check the functionality of the new function

**Comment by antoniomanuelfr** [comment]
working branch https://github.com/wazuh/wazuh-qa/tree/1711-qactl-validation

**Comment by jmv74211** [comment]
@fernandolojano will continue with this issue development

**Comment by fernandolojano** [comment]
During the first approach in implementing the new function and checking it's proper functionality, a few issues were found in the JSON schema file used as validator.
- There wasn't a proper object declared into the test module, this caused the failure of the validator function everytime we added the test module into the `conf.yaml` file.
- There were some format parameters inconsistencies between the schema file and the `conf.yaml` file.

After solving this problems and reviewing the validator function's code, It seems that the new implementation is working fine.

**However, in order to definitely confirm that the new script is working correctly, it is necessary to make a deep testing of all the possible error cases. We need to check and improve the json schema file configuration as well.**

**Comment by fernandolojano** [comment]
# Proven error case scenarios
## Deployment section
### Vagrant scenario

| Error Case |  Function's output|
| ------------- | ------------- |
| No main entry given for deployment module (host1)  | Error KeyError: 'provider'  |
| No provider entry given (provider) | Error KeyError: 'provider'  |
| No required entry given (enabled)  | ValidationError: 'enabled' is a required property  |
| Incorrect format entry given (vm_memory: '2048') | ValidationError: '2048' is not of type 'integer'  |

### Docker scenario

| Error Case |  Function's output|
| ------------- | ------------- |
| Empty optional field (IP)  | ValidationError: None is not of type 'string'|

**Comment by fernandolojano** [comment]
After an exhaustive study of most possible error cases for the validation function, it is safe to confirm that the function is working properly for the deployment and provisioning modules of the `conf.yaml` file.  It still remains to check it's proper working functionality for the testing module.


Some minor issues as new parameter inconsistencies between the schema file and the `conf.yaml` where found again while checking the JSON schema file. 

New modifications into the schema were added as well:
 - The `ports` field of the docker provider of the Deployment section was declared as an object type but didn't have any properties.
 - It was necessary to create conditional requirements in case of specific parameters entries for `type` and `target` fields of the Provisioning module

All this new additions can be seen and reviewed in this [commit ](https://github.com/wazuh/wazuh-qa/commit/44effaca43b91f7005196a782434953547ca076d#diff-74340690b2ce0822448a023a3beaf8c1ddf9faf8e7d615e8fad967507f6a55f4)

As a new requirement it was necessary to add a new field for the test module. This new field is similar to the actual `host_info` field given in the Provisioning module. See [this changes.](https://github.com/wazuh/wazuh-qa/commit/1da0a71fccf52cb93fd62895e380a9b341cc4224)
