### ISSUE TITLE
Syscheck automated tests: 'skip_*' options

### ISSUE THREAD

**Issue by crd1985** [wazuh/wazuh-qa#172]
| Working branch |
| --- |
| |
|[fim-integration-tests-skip](https://github.com/wazuh/wazuh-qa/tree/fim-integration-tests-skip)

## Description

This issue is part of the roadmap in #7.

- The `skip_nfs` option specifies if syscheck should scan network mounted filesystems (Works on Linux and FreeBSD). Currently, skip_nfs will exclude checking files on CIFS or NFS mounts.
- The `skip_dev` option specifies if should scan files inside a devnf file system (/dev).
- The `skip_proc` option specifies if should scan files inside a procfs file system (/proc).
- The `skip_sys` option specifies if should scan files inside a sysfs file system (/sys).

## Subtasks
- Scheduled
  - [x] Check if adding, modifying or deleting a file in a nfs generates an event setting `skip_nfs` to `yes`/`no`
  - [x] Check if adding, modifying or deleting a file in a devnf generates an event setting `skip_dev` to `yes`/`no`
  - [x] Check if opening a process generates an event setting `skip_proc` to `yes`/`no`
  - [x] Check if removing a module from a sysfs generates an event setting `skip_sys` to `yes`/`no`

**Comment by vicferpoy** [comment]
# Status update
## Summary
Development is finished. I updated the checks for `skip_proc` and `skip_sys` due to a different behaviour to the rest when scanning each directory.

## Difficulties
* Not every option behaves the same so I had to figure it out manually and adapt the tests.
* `skip_nfs` required an already configured NFS so I had to add some scripts to create it during the tests and clean everything up in the end.

## Tests performed
```
================================ test session starts =================================
platform linux -- Python 3.6.8, pytest-5.2.1, py-1.8.0, pluggy-0.13.0
rootdir: /vagrant/wazuh-qa/test_wazuh, inifile: pytest.ini
collected 96 items                                                                   

test_skip.py .ssss.ssss.ssss..ssss.ssss.ssss..ssss.ssss.ssss..ssss.ssss.ssss.. [ 67%]
ssss.ssss.ssss..ssss.ssss.ssss.                                                [100%]

=============== 24 passed, 72 skipped in 562203.07s (6 days, 12:10:03) ===============
```

**Comment by vicferpoy** [comment]
# Status update
## Summary
`skip_proc` and `skip_sys` checks were not accurate and I changed them.
They successfully detect alerts when there are changes in these file systems. 

## Difficulties
* Since even root doesn't have permissions for `/proc` and `/sys`, it was hard to think of a way to test alerts that were not from integrity.
