### ISSUE TITLE
QACTL does not download the boxes needed

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh-qa#1720]
In order to improve qa-ctl, boxes needed to be loaded with no errors.

When you try to use the qa-ctl boxes and you don't have them locally stored, you get an error trying to install the box.

## Tasks

- [x] Review Vagrantfile design
- [x] Investigate how to use custom box URLs
- [x] Add custom box URLs to Vagrantfile (development)
- [x] Tests and debugging changes made

**Comment by roronoasins** [comment]
I have added a parameter `box_url` that contains the remote url in order to download the box if you don't have it.

Now, the vagrantfile generated with Vagranfile class, will have the `box_url` field set.
```
node.vm.box_url = "#{vm_parameters['box_url']}"
```
