### ISSUE TITLE
QACTL review and fixes

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#1723]
The objective of this issue is to give a general review of the qactl tool for this first iteration, and to note any possible bugs or improvements needed to meet the main objectives of the tool.

## Improvements

- [x] Validation of the input parameters of the qactl configuration (https://github.com/wazuh/wazuh-qa/issues/1711)
- [x] Automatic download of customized vagrant boxes if necessary (https://github.com/wazuh/wazuh-qa/issues/1720)
- [x] Improve docker image generation. Right now it is necessary to copy entrypoint and Dockerfile to a custom directory and from there generate the image. (https://github.com/wazuh/wazuh-qa/issues/1749)
- [x] Add `healthcheck` parameter to `wazuh deployment` stage. If True health-check will be performed, False otherwise.
- [x] Remove uselss configuration keys: `wazuh_installation` from `wazuh deployment`
- [x] Rename ansible tasks in `run test` module.
- [x] QACTL logging (https://github.com/wazuh/wazuh-qa/issues/1713)
- [x] Install wazuh via S3 packages (https://github.com/wazuh/wazuh-qa/issues/1768)
- [x] Parallelize QACTL modules (https://github.com/wazuh/wazuh-qa/issues/1754)
  - [x] Parallelize deployment and destruction of instances.
  - [x] Parallelize the provisioning of instances.
  - [x] Parallelize the testing
- [x] Clean tmp files (https://github.com/wazuh/wazuh-qa/issues/1768)
- [x] Rename QACTL modules: Names have to be in format `snake_case` (https://github.com/wazuh/wazuh-qa/issues/1768)
- [x] Update and create new QACTL generic documentation  (https://github.com/wazuh/wazuh-qa/issues/1793)
- [x] Write a documentation for all the modules that aren't currently documented #1798 

## Fixes

- [x] Centos_8 box is not accessible by SSH
- [x] `Run test module` can not be run independently. https://github.com/wazuh/wazuh-qa/issues/1734
- [x] Deployment stage https://github.com/wazuh/wazuh-qa/issues/1743
   - [x] Containers are not deleted after test execution. It is necessary to kill them.
   - [x] Connection problems with docker instances.
      - [x] Amazon Linux instance inaccessible by ssh.
      - [x] Ansible cannot connect to the Ubuntu instance, although we can connect via SSH.
- [x] Run test stage (https://github.com/wazuh/wazuh-qa/issues/1728)
   - [x] HTML report is not generated correctly. `File not found error`.
   - [x] Update documentation. The issue documentation is outdated..
- [x] Fix ansible connection issue ([#C4](https://github.com/wazuh/wazuh-qa/issues/1723#issuecomment-901015155)) 

## Manual checks

- [x] Deployment:
   - [x] SSH host key checking 🟢  ([#C2](https://github.com/wazuh/wazuh-qa/issues/1723#issuecomment-901015155)) 
   - [x] Vagrant
     - [x]  Deploy 1 to `n` instances using Ubuntu 20.04 custom box 🟢 
     - [x]  Deploy 1 to `n` instances using CentOS 8 custom box 🟢 
   - [x] Docker
     - [x]  Deploy 1 to `n` instances using Amazon Linux 2 custom image 🟡  
     - [x]  Deploy 1 to `n` instances using Ubuntu 20.04 custom image 🟡 
- [x] Provision:
  - [x] Provision instance ([#C4](https://github.com/wazuh/wazuh-qa/issues/1723#issuecomment-901015155)) Fixed 🟢 
  - [x]  Provision `n` Ubuntu 20.04  instances 🟢 
  - [x]  Provision `n` CentOS 8  instances 🟢  ([#C3](https://github.com/wazuh/wazuh-qa/issues/1723#issuecomment-901015155)) Fixed
  - [x] Provision wazuh via sources 🟢  ([#C1](https://github.com/wazuh/wazuh-qa/issues/1723#issuecomment-901015155)) Fixed
  - [x] Provision wazuh via local packages. 🟢 
  - [x] Provision qa_framework with custom branches 🟢 . 
  - [x] Provision local machine 🟢

**Comment by jmv74211** [comment]
## C1: Provision wazuh via sources
### Error

```
TASK [Render the "preloaded-vars.conf" file] ***********************************
fatal: [172.16.1.60]: FAILED! => {"changed": false, "checksum": "961aba88b0af13a2bd3c5b7e6d2c475f36c116ba", "msg": "Destination directory /tmp/wazuh-v4.2.0-rc13/etc does not exist"}
```
