### ISSUE TITLE
QACTL: Fix HTML report generation and update documentation

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh-qa#1728]
## Description
When test are run, the HTML report file creation makes that program exits with `File not found error`

Also, the QACTL Test Execution [documentation](https://github.com/wazuh/wazuh-qa/issues/1533#issuecomment-895019665) is outdated, we need to check and update it.
## Tasks
- [x] HTML report is not generated correctly.
- [x] HTML report does not contain test info
- [x] Check and update documentation.
## Additional task
- [x] Use a new directory inside tests execution dir, in order to not fill the directory with assets, plain and html reports

**Comment by roronoasins** [comment]
I have created the necessary environment in order to execute the tests and check the HTML report generation error using the following `conf.yaml`:

```
deployment:
        host1:
                provider:
                        vagrant:
                                enabled: True
                                vagrantfile_path: '/tmp'
                                vagrant_box: 'qactl/ubuntu_20_04'
                                vm_memory: 1024
                                vm_cpu: 2
                                vm_name: 'ubu20'
                                vm_system: 'Linux'
                                label: 'qactl'
                                vm_ip: '172.16.1.10'
                                quiet_out: False

provision:
        hosts:
                host1:
                        host_info:
                                connection_method: 'ssh'
                                host: '172.16.1.10'
                                user: 'vagrant'
                                password: 'vagrant'
                                connection_port: '22'
                                ansible_python_interpreter: '/usr/bin/python3'

                        wazuh_deployment:
                                wazuh_installation:
                                        type: 'package'
                                        target: 'manager'
                                        local_package_path: '/home/luisgr/work/packages/wazuh-manager_4.2.0-1_amd64.deb'
                                        installation_files_path: '/tmp'

                        qa_framework:
                                wazuh_qa_branch: '4.2'
                                qa_workdir: '/tmp'

 tests:
         test1:
                 hosts: '172.16.1.10'
                 type: pytest
                 path:
                         test_files_path: '/tmp/wazuh-qa/tests/integration/test_analysisd/test_all_syscheckd_configuration/test_check_rare_socket_responses.py'
                         run_tests_dir_path: '/tmp/wazuh-qa/tests/integration'
                         test_results_path: '/home/luisgr/Documents/test'
                 parameters:
                         # #tier: str
                         # stop_after_first_failure: boolean
                         # keyword_expression: str
                         # traceback: str
                         dry_run: True
                         # custom_args: list(str)
                         # verbose_level: boolean
                         # log_level: str
                         # markers: list(str)
```

At test execution phase, I got this error:
```
UnboundLocalError: local variable 'qa_provisioning' referenced before assignment
```
Need to fix this error and find out why the HTML report generation fails.

Also updated the `Provisioning module` documentation [here](https://github.com/wazuh/wazuh-qa/issues/1533): provisioning was missing.

**Comment by roronoasins** [comment]
When you run the tests, is prompted the following error:

![image (1)](https://user-images.githubusercontent.com/33318890/130028657-ee399117-0bda-434e-b9a2-7cac562466e2.png)

Changing the path solves the error, html report and assets are generated in `/home/vagrant`. So that was the problem, when using that path all works as expected and report is located correctly.

Now the HTML report does not have test info, but time is spent anyway:
![image](https://user-images.githubusercontent.com/33318890/130053248-1b0e9152-125c-4f85-882e-93354433945d.png)

**Comment by roronoasins** [comment]
`provisioning` and `test execution` yaml syntax updated https://github.com/wazuh/wazuh-qa/issues/1533#issuecomment-895019665

**Comment by roronoasins** [comment]
I think we can use an ansible task that creates a `reports/` directory inside tests execution dir, in order to keep them together and not fill the directory with assets, plain and html reports.
