### ISSUE TITLE
Syscheck automated tests: whodata attributes

### ISSUE THREAD

**Issue by crd1985** [wazuh/wazuh-qa#173]
| Working branch |
| --- |
| |

## Description

This issue is part of the roadmap in #7.

- The `restart_audit` option allows the system to restart Auditd after installing the plugin
- The `audit_key` option sets up the FIM engine to collect the Audit events using keys with audit_key. Wazuh will include in its FIM baseline those events being monitored by Audit using audit_key. For those systems where Audit is already set to monitor folders for other purposes, Wazuh can collect events generated as a key from audit_key
- The `startup_healthcheck` allows to disable the Audit health check during the Whodata engine starting

An example of this configuration:
```xml
<whodata>
    <restart_audit>yes</restart_audit>
    <audit_key>auditkey1,auditkey2</audit_key>
    <startup_healthcheck>yes</startup_healthcheck>
</whodata>
```

## Subtasks
- Whodata
  - [x] Set `restart_audit` to `yes`/`no` and see if syscheck restarts auditd in the log
  - [x] Set `startup_healthcheck` to `yes`/`no` and see if syscheck restarts auditd in the log
  - [x] Configure other keys in auditd (check [this documentation](https://documentation.wazuh.com/3.10/user-manual/capabilities/auditing-whodata/who-linux.html?highlight=whodata) for more info. Try several values of `audit_key` and check if events are triggered if the keys match or not triggered otherwise.
