### ISSUE TITLE
QACTL: Separate run test module from the rest of the modules

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#1734]
QACTL has a module for running tests on remote machines. Given the initial design of the QACTL tool, it was intended that each of the different modules that make up the tool (deploy, provision and run tests) would be independent of each other.

Given the current scheme and approach of the run_test module, this is not possible, because there is a dependency with the provisioning module, since this is the one that creates the host inventory and knows in which path the QA framework files are located.

We want to modify this behavior, so that the run_test module can be executed without having previously launched the provisioning module.

To do this, it is necessary to change the configuration associated to this module and make the necessary modifications in the module to read this new configuration and process it.

The following configuration design is proposed:

```
tests:
    host1:
        host_info:
            connection_method: ssh
            host: 172.16.1.70
            user: xx
            password: xx
            connection_port: 22
            ansible_python_interpreter: /bin/python3

        test:
           type: pytest
            path:
                test_files_path: '/tmp/wazuh-qa/tests/integration/test_analysisd/test_all_syscheckd_configurations/test_check_rare_socket_responses.py'
                run_tests_dir_path: '/tmp/wazuh-qa/tests/integration'
                test_results_path: '/home/jmv74211/Documents/test'
            parameters:
                dry_run: True
```

## Tasks

- [x] Update `run_test` module configuration template
- [x] Update `run_test` configuration parser
- [x] Update `run_test` module to create new inventory
- [x] Test changes made
