### ISSUE TITLE
Syscheck automated tests: 'sync_interval' and 'response_timeout' option

### ISSUE THREAD

**Issue by crd1985** [wazuh/wazuh-qa#174]
| Working branch |
| --- |
|[fim-integration-tests-sync](https://github.com/wazuh/wazuh-qa/tree/fim-integration-tests-sync)|
## Description

This issue is part of the roadmap in #7.

- The `sync_interval` sets the synchronization interval, in seconds. `smhdw` suffixes allowed. Default `10m`.
- The `response_timeout` sets the minimum time since the last synchronization message received before starting a new synchronization stage, in seconds. smhdw suffixes allowed.

## Subtasks
- Realtime
  - [x] Set `sync_interval` to a time interval for each valid suffix. Advance the system time with our `TimeMachine` class the specified interval and detect if a new synchronization is triggered.
  - [x] Set `response_timeout` to a time value for each valid suffix. Advance the system time with our `TimeMachine` class and check if the synchronization does not start before the `response_timeout` value.

- Whodata
  - [x] Set `sync_interval` to a time interval for each valid suffix. Advance the system time with our `TimeMachine` class the specified interval and detect if a new synchronization is triggered.
  - [x] Set `response_timeout` to a time value for each valid suffix. Advance the system time with our `TimeMachine` class and check if the synchronization does not start before the `response_timeout` value.

- Scheduled
  - [x] Set `sync_interval` to a time interval for each valid suffix. Advance the system time with our `TimeMachine` class the specified interval and detect if a new synchronization is triggered.
  - [x] Set `response_timeout` to a time value for each valid suffix. Advance the system time with our `TimeMachine` class and check if the synchronization does not start before the `response_timeout` value.

- Other subtasks
  - [x] Try some invalid values to `sync_interval` (bad format, invalid suffix)
  - [x] Try some invalid values to `response_timeout` (bad format, invalid suffix)

**Comment by CarlosRS9** [comment]
# Status update
## Summary
Development of `sync_interval` tests is finished. I'm currently working on the invalid values and the `response_timeout`.

## Difficulties
* To be able to test <response_timeout> properly we need to setup an agent to use with our cluster.

**Comment by CarlosRS9** [comment]
# Status update
## Summary
Tests are now finished. Development of `response_timeout` was more difficult than we expected because we had to setup an agent, have the test on the manager and keep both in sync. Also, we were impacted by some failures on the current implementation of `response_timeout` that we found during the development. Those failures have been fixed by core team.

## Tests
This is the current status of the tests:
```
=================== test session starts ========================
collected 28 items 

test_invalid_sync_response.py ..                           [  7%]
test_response_timeout.py ....................              [ 78%]
test_sync_interval.py ......                               [100%]

========= 28 passed in 38360600.70s (443 days, 23:43:20) ======== 
```
The time indicated is not useful as we had to modify the internal clock of the machine during the tests.
