### ISSUE TITLE
QACTL: fix docker deployment and provisioning

### ISSUE THREAD

**Issue by mdengra** [wazuh/wazuh-qa#1743]
|Related issue|
|---|
|Closes: #1533|

This issue is created to solve the `Ansible` connection problems with the docker instances used (`Amazon Linux` and `Ubuntu 20.04`). It should also fix possible provisioning issues once the connection issues have been fixed.

## Tasks
In order to fix these problems, several tasks need to be done:
- [x] Deployment stage
   - [x] Containers are not deleted after test execution. It is necessary to kill them.
   - [x] Connection problems with docker instances.
      - [x] Amazon Linux instance inaccessible by ssh.
      - [x] Ansible cannot connect to the Ubuntu instance, although we can connect via SSH.
- [x] Provisioning stage: 
  - [x] Fix possible issues.

**Comment by mdengra** [comment]
### 2021-08-20

Working branch: `1743-fix-docker-dpl-and-prv`

**Comment by mdengra** [comment]
### 2021-08-23


#### Connection problems on `Ubuntu 20.04`

I am still looking for the source of the problem. It seems to be due to the permissions of the default user (wazuh). 

So far I have made the following findings:
- The `sudo` command is not installed by default in the container, so if the connection is made using a user that requires to execute privileged commands it could cause problems.

- When the **root** user is used in the QACTL configuration file to connect to the machine, both deployment and provisioning are performed without problems.
<details><summary>QACTL deployment and provisioning output (root user)</summary>
<p>

```python
PLAY [172.11.0.1] **************************************************************

TASK [Create /tmp path] ********************************************************
ok: [172.11.0.1]

TASK [Copy /(hidden path)/wazuh-manager_4.3.0-0.commit44a6dd9_amd64.deb package to                                                    /tmp] ***
changed: [172.11.0.1]

PLAY RECAP *********************************************************************
172.11.0.1                 : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   


PLAY [172.11.0.1] **************************************************************

TASK [Gathering Facts] *********************************************************
ok: [172.11.0.1]

TASK [Install Wazuh Agent from .deb packages] **********************************
changed: [172.11.0.1]

TASK [Install Wazuh Agent from .rpm packages | yum] ****************************
skipping: [172.11.0.1]

TASK [Install Wazuh Agent from .rpm packages | dnf] ****************************
skipping: [172.11.0.1]

TASK [Install Wazuh Agent from Windows packages] *******************************
skipping: [172.11.0.1]

TASK [Install macOS wazuh package] *********************************************
skipping: [172.11.0.1]

PLAY RECAP *********************************************************************
172.11.0.1                 : ok=2    changed=1    unreachable=0    failed=0    skipped=4    rescued=0    ignored=0   


PLAY [172.11.0.1] **************************************************************

TASK [Gathering Facts] *********************************************************
ok: [172.11.0.1]

TASK [Wazuh manager start service from systemd] ********************************
fatal: [172.11.0.1]: FAILED! => {"changed": false, "msg": "Service is in unknown state", "status": {}}
...ignoring

TASK [Wazuh agent start service from wazuh-control] ****************************
changed: [172.11.0.1]

TASK [Wazuh agent start service from Windows] **********************************
skipping: [172.11.0.1]

PLAY RECAP *********************************************************************
172.11.0.1                 : ok=3    changed=1    unreachable=0    failed=0    skipped=1    rescued=0    ignored=1   


PLAY [172.11.0.1] **************************************************************

TASK [Gathering Facts] *********************************************************
ok: [172.11.0.1]

TASK [Read ossec.log searching errors] *****************************************
changed: [172.11.0.1]

TASK [Read ossec.log searching errors] *****************************************
skipping: [172.11.0.1]

PLAY RECAP *********************************************************************
172.11.0.1                 : ok=2    changed=1    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   


PLAY [172.11.0.1] **************************************************************

TASK [Gathering Facts] *********************************************************
ok: [172.11.0.1]

TASK [Extract service status] **************************************************
changed: [172.11.0.1]

PLAY RECAP *********************************************************************
172.11.0.1                 : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   


PLAY [172.11.0.1] **************************************************************

TASK [Create /tmp/wazuh-qa path] ***********************************************
changed: [172.11.0.1]

TASK [Download https://github.com/wazuh/wazuh-qa.git QA repository] ************
changed: [172.11.0.1]

PLAY RECAP *********************************************************************
172.11.0.1                 : ok=2    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   


PLAY [172.11.0.1] **************************************************************

TASK [Install python dependencies] *********************************************
changed: [172.11.0.1]

PLAY RECAP *********************************************************************
172.11.0.1                 : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   


PLAY [172.11.0.1] **************************************************************

TASK [Install wazuh-qa framework] **********************************************
changed: [172.11.0.1]

PLAY RECAP *********************************************************************
172.11.0.1                 : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```
</p>
</details>

<details><summary>Manager status (root user)</summary>
<p>

```python
root@e6abbcacdb59:/# /var/ossec/bin/wazuh-control status
wazuh-clusterd not running...
wazuh-modulesd is running...
wazuh-monitord is running...
wazuh-logcollector is running...
wazuh-remoted is running...
wazuh-syscheckd is running...
wazuh-analysisd is running...
wazuh-maild not running...
wazuh-execd is running...
wazuh-db is running...
wazuh-authd is running...
wazuh-agentlessd not running...
wazuh-integratord not running...
wazuh-dbd not running...
wazuh-csyslogd not running...
wazuh-apid is running...
root@e6abbcacdb59:/# 
```
</p>
</details>

<details><summary>Wazuh-QA local repository (root user)</summary>
<p>

```python
root@e6abbcacdb59:/# cd /tmp/wazuh-qa/
root@e6abbcacdb59:/tmp/wazuh-qa# git branch
* master
root@e6abbcacdb59:/tmp/wazuh-qa# 
```
</p>
</details>

**Comment by mdengra** [comment]
### 2021-08-24


#### Error when a different SSH key exists in the `known_hosts` file.

The solution is to replace in the Ansible inventory the SSH option `StrictHostKeyChecking=no` by `UserKnownHostsFile=/dev/null`

####  Containers are not deleted after test execution.

Containers are deleted when using `--destroy` option of `qa_ctl.py`.
