### ISSUE TITLE
QACTL: Improve Docker image generation process

### ISSUE THREAD

**Issue by fernandolojano** [wazuh/wazuh-qa#1749]
This issue has been created with the purpose of improving the current docker image generation process of the qactl deployment section.
As for now, in order to generate a specific docker image (those given in the directory `dockerfiles`), we have to follow the next steps:
 - Copy the dockerfile we want to use and the `entrypoint.sh` in a different directory . 
 - Change the name of the specific dockerfile to `Dockerfile`. 
 - In the `conf.yaml `file we have to declare the directory path where the files were copied.
 
The first two steps given have to be done manually. A new implementation for generating a docker image is needed in order to avoid this manual process.

## Tasks
- [x] Investigate about different approaches for an automatic docker image generator process
- [x] Modify schema file for new possible parameters
- [x] Modify current docker image generator implementation

**Comment by fernandolojano** [comment]
This new changes are being made in the branch [1749-improve-docker-img-generator](https://github.com/wazuh/wazuh-qa/tree/1749-improve-docker-img-generator)

**Comment by fernandolojano** [comment]
The previous methodology implemented for improving the docker image generator has been discarded. Now, after checking that the image is been generated properly and checking the correct validation of the `conf.yaml` for the docker deployment section, there has been made some changes in the schema.

- `ports` : The format has been chosen following the [docker-py](https://docker-py.readthedocs.io/en/stable/containers.html) documentation. In this documentation, `ports` is a  field  with the form of a python dictionary where the keys are the ports to bind inside the container in the form port/protocol, and the values are integers corresponding to the ports we want to open in the host. A valid entry would be: `ports: {'1526/tcp': 1526}`
