### ISSUE TITLE
Generate packages from wazuh tag '4.2.0-rc13'

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#1758]
## Description 

To start to work on `[Research: Integration tests in 4.2.0-RC13](https://github.com/wazuh/wazuh-qa/issues/1757)` is required to generate some packages.  

When you finish it adds a Link of every package created like a comment in this issue and also adds this information on the `Package Information` section on `[Research: Integration tests in 4.2.0-RC13](https://github.com/wazuh/wazuh-qa/issues/1757)` 

## Tasks 

**Manager**

- [ ] Generate rpm package.

**Agents**

- [ ] Generate rpm package.
- [ ] Generate msi package.
- [ ] Generate wpk package for Windows.
- [ ] Generate wpk package for Linux.
- [ ] Generate package for macOS.
- [ ] Generate package for Solaris 11

**Comment by damarisg** [comment]
|Target | System | Build |
|--|--|--| 
| Manager | rpm | https://ci.wazuh.info/job/Packages_builder/62115/

**Comment by MizugorouZ** [comment]
|Target | System | Build |
|--|--|--| 
| Agent | rpm | [Build](https://ci.wazuh.info/job/Packages_builder/62163/) |
