### ISSUE TITLE
QACTL: Improvements for qactl tool implementation

### ISSUE THREAD

**Issue by fernandolojano** [wazuh/wazuh-qa#1768]
This issue has been created with the purpose of implement a few of the improvements listed in the issue [#1723](https://github.com/wazuh/wazuh-qa/issues/1723#issue-972693056).

## Tasks
 The tasks that are going to be realized in this issue are:
- [ ] Install wazuh via S3 packages
- [ ] Clean all possible tmp files created during the qactl tool execution
- [ ] Rename all QACTL modules, using the `snake_case` format

**Comment by fernandolojano** [comment]
The working branch for this issue is: [1768-qactl-improvements](https://github.com/wazuh/wazuh-qa/tree/1768-qactl-improvements)

**Comment by fernandolojano** [comment]
After searching and locating which temporary files are being created and the reason of them remaining after the execution of the qactl tool is over, we can conclude some terms:

- After several tests, it seems that the whole Deployment section doesn't leave any temp files in the host system.
- Regarding to the Provisioning section, there are a few points that needs to be solved.
     - The functions for removing the temp files after the execution are implemented, but some of then will only run if the execution of the tool was suceeded, In case that the execution had any possible failure, the temp files won't be deleted. 
     - The qactl tool uses the command _run_ from the  library `ansible_runner`. As far as I researched, this command will create a folder in the specified directory passed as an argument. The issue with this command is that it generates a folder with a random name everytime the command is executed. There is no way of knowing the exact name of the generated folder as there isn't a proper path argument return from the execution. I couldn't find a possible implementation for deleting this files.
