### ISSUE TITLE
QACTL: Show test results in stdout

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#1794]
It is requested that when the execution of a test using the QACTL tool is finished, the pytest output is displayed in the standard console output.

It is also necessary to modify some logging messages to indicate when an action starts and ends instead of showing messages like `Launching 3 tests...`

## Tasks

- [x] Add test result output to the QACTL stdout.
- [x] Add and update logging messages.
- [x] Test made changes
