### ISSUE TITLE
qa-docs: Automatize `qa-docs` using docker

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh-qa#1797]
## Description
To visualize SearchUI with the test info brought by [DocGenerator](https://github.com/wazuh/wazuh-qa/issues/1536)(as we can see [here](https://github.com/wazuh/wazuh-qa/issues/1600)) we need to create a way to provide this service automatically, by just run docker and access it via the web browser.

This module needs to use a specific wazuh-qa branch, get the test doc outputs with DocGenerator, index these outputs with ElasticSearch, and start React(SearchUI). In this first approach, master will be used for the environment(no tests documented with DocGenerator schema).

When the image is configured and ready, DocGenerator will bring us the test documentation output as JSON files and these will be indexed with ElasticSearch. Then SearchUI will be running so we can navigate thru the doc info using our web browser.

The tests we will use are being created here https://github.com/wazuh/wazuh-qa/issues/1796 using the current [schema](https://github.com/wazuh/wazuh-qa/issues/1694) we are working on

---

As a task from #1864, `qa-docs` needs the docker deployment to work correctly with this first `qa-docs` version.

## Branch
`DocGenerator`: [1797-docker-deployment](https://github.com/wazuh/wazuh-qa/tree/1797-docker-deployment) (deprecated)
`qa-docs`: [1797-qadocs-deployment](https://github.com/wazuh/wazuh-qa/tree/1797-qadocs-deployment)

## Tasks
- [x] Research about creating docker image via Dockerfile
- [x] Create custom Dockerfile for DocGenerator+ES+SearchUI
    - [x] Install and configure wazuh-qa
    - [x] Install DocGenerator and SearchUI requirements
    - [x] Run DocGenerator
    - [x] Index JSONs and launch SearchUI
    - [x] Visualize SearchUI correctly
    - [x] Migrate docker deployment to `qa-docs` tool

**Comment by roronoasins** [comment]
I have fixed an issue where ES was not running so JSONs were not indexed either. Now I have the following issue when I try to access the app:

![image](https://user-images.githubusercontent.com/33318890/131649761-30c6e562-afaa-4660-95ab-777bee9e4941.png)

When `CMD service elasticsearch start && python3 DocGenerator.py -l qa-docs` is executed, only ES and SearchUI are started, the JSONs are not indexed. 

![image](https://user-images.githubusercontent.com/33318890/131655333-84c2b639-e924-4735-818c-7b7f42da263e.png)

**Comment by roronoasins** [comment]
It is working now, was failing at reading the elastic response. Just need to name the index `qa-doc`, because it is hardcoded:
![image](https://user-images.githubusercontent.com/33318890/131799226-5505becd-95ac-4947-a8e1-565986c0bfe1.png)

And SearchUI is working now.
![image](https://user-images.githubusercontent.com/33318890/131799026-4408a1cf-2b0d-442f-8084-f023962c6896.png)

All you need is run `docs/DocGenerator/run-docgenerator.sh`

**Comment by roronoasins** [comment]
It is working now with the `qa-docs` update. I am working on using a branch as input to use that one as `qa-docs` input. So you can parse with it tests from another branch.

**Comment by roronoasins** [comment]
```
(docgen) luisgr@luisgr-pc:~/work/wazuh-qa/deps/wazuh_testing/wazuh_testing/qa_docs$ docker image list
REPOSITORY                          TAG       IMAGE ID       CREATED          SIZE
qa-docs/1796-migrate-doc-schema-2   0.1       8a62b2b554d2   10 minutes ago   2.8GB
qa-docs_base                        0.1       dd8369b5d244   11 minutes ago   2.66GB
```
`qa_docs_base` has all the dependencies and the framework installed and `qa_docs_tool` runs the tests parse using the branch that you specify.
