### ISSUE TITLE
Generate test output file using DocGenerator  

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh-qa#1800]
## Description
[DocGenerator](https://github.com/wazuh/wazuh-qa/issues/1536) provides test info from whole directories(search recursively the folders that you want and parse all tests in those directories) but no from a specific test. For example, [QACTL](https://github.com/wazuh/wazuh-qa/issues/1533) could use it to obtain versions and os details. That allows the tool to install and provide the correct (wazuh and os)version to run the test.

This is an example of how QACTL could use it
![image](https://user-images.githubusercontent.com/33318890/131820079-970dbb68-b04a-4d5b-b9d9-d99c58e15cf9.png)

Branch: [1800-parse-single-test](https://github.com/wazuh/wazuh-qa/tree/1800-parse-single-test)

## Tasks
- [x] Add an argument to DocGenerator so you can parse a single test, with its name or path as input
- [x] Search recursively the test specificated
- [x] Generate JSON output located in the path that receives as parameter

## Additional Tasks
- [x] Add qa-docs to wazuh framework
- [x] Change how qa-docs locate the required files
- [x] Test the whole tool
  - [x] sanity check
  - [x] indexing data to ES
  - [x] indexing data and then launch SearchUI
  - [x] search and parse a single test (standard output)
  - [x] search and parse a single test (json file creation)
  - [x] default behaviour

**Comment by roronoasins** [comment]
May the tool could define a new possible argument that specifies a test name/path, so only that test is parsed to get the data QACTL needs.

Both name or path could be used, so when the arg is the path it parses directly the test. And when the arg is the test name, it searches recursively and gets the needed info.

 The info we aim:
- test_path
- test_system(os_platform)
- test_wazuh_min_version(wazuh_min_version)
- test_vendor(os_vendor)
- test_os_version(os_version)
- test_target(component)

**Comment by roronoasins** [comment]
This is an example output using a single test but no output path.

![image](https://user-images.githubusercontent.com/33318890/131983554-31638199-0daf-4f57-92f8-8c22e860a5fe.png)

Now it has to use the keys that QACTL needs

**Comment by roronoasins** [comment]
qa-docs has been included in the `wazuh_testing` framework, so QACTL could use it properly just using `qa-docs` instead of `python3 DocGenerator`

```
(docgen) luisgr@luisgr-pc:~/work/wazuh-qa/deps/wazuh_testing$ qa-docs -h
usage: qa-docs [-h] [-s] [-v] [-t] [-d] [-i INDEX_NAME] [-l LAUNCH_APP] [-T TEST_INPUT] [-o OUTPUT_PATH]

optional arguments:
  -h, --help      show this help message and exit
  -s              Run a sanity check
  -v              Print version
  -t              Test configuration
  -d              Enable debug messages.
  -i INDEX_NAME   Indexes the data to elasticsearch.
  -l LAUNCH_APP   Indexes the data and launch the application.
  -T TEST_INPUT   Test name to parse.
  -o OUTPUT_PATH  Output directory path.

```

**Comment by roronoasins** [comment]
I got the following error when I try to run SearchUI using the `qa-docs` script

```
(docgen) luisgr@luisgr-pc:~/work/wazuh-qa/deps/wazuh_testing$ qa-docs -I ../../tests/ -l qa-doc

> Wazuh-QA_documentation@1.7.0 start /home/luisgr/work/docgen/lib/python3.8/site-packages/wazuh_testing-4.3.0-py3.8.egg/wazuh_testing/qa_docs/search_ui
> npm-run-all --parallel start:app start:server

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '../common/bootstrap'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/luisgr/work/docgen/lib/python3.8/site-packages/wazuh_testing-4.3.0-py3.8.egg/wazuh_testing/qa_docs/search_ui/node_modules/.bin/npm-run-all:13:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Wazuh-QA_documentation@1.7.0 start: `npm-run-all --parallel start:app start:server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Wazuh-QA_documentation@1.7.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
