### ISSUE TITLE
QA Docs: Migrate `test_agentd` documentation to schema 1.0

### ISSUE THREAD

**Issue by mdengra** [wazuh/wazuh-qa#1801]
### Description

This issue is created to migrate the `test_agentd` documentation to the new QA Docs schema as part of the epic https://github.com/wazuh/wazuh-qa/issues/1796.

In the QA Wiki there are two entries to help complete the tasks:

- [Documenting tests using the QA Docs schema](https://github.com/wazuh/wazuh-qa/wiki/Documenting-tests-using-the-QA-Docs-schema): This entry describes the steps needed to document the tests (schema to use, the position of blocks, allowed values for fields, etc.).
- [Documentation generation with DocGenerator tool](https://github.com/wazuh/wazuh-qa/wiki/Documentation-generation-with-DocGenerator-tool): Here is a brief description of how the `DocGenerator.py` module works to verify that the changes made in the tests have been done correctly.

#### Main branch
`1796-migrate-doc-schema-1`

#### Tasks
- [x] Migrate tests:
  - [x] `test_agent_auth_enrollment.py`
  - [x] `test_agentd_enrollment_params.py`
  - [x] `test_agentd_multi_server.py`
  - [x] `test_agentd_parametrized_reconnections.py`
  - [x] `test_agentd_reconnection.py`
  - [x] `test_agentd_state_config.py` (**Create new documentation**)
  - [x] `test_agentd_state.py` (**Create new documentation**)
- [x] Check `PEP-8` style guide (`pycodestyle --max-line-length=120`)
- [x] Merge issue branch to  `1796-migrate-doc-schema-1`

**Comment by mdengra** [comment]
## 2021-08-31
Working branch: `1801-qadocs-migrate-test-agentd`
