### ISSUE TITLE
QACTL launch tests without specifying a configuration file. Self-contained information in the tests

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#1803]
We want to add a new module to the QACTL tool to be able to launch a test without having to specify the associated information in the `config.yaml` configuration file.

The purpose of this is to eliminate the logic on the part of the user, which only a priori will know the name of the test to launch, and it is `qa-ctl` who must know how many machines need to be deployed, systems ...

An example of use could be the following:

```
qa-ctl -r test_general_settings_enabled -v 4.2.0
```

And the output obtained:

```
============================= test session starts ==============================
platform linux -- Python 3.8.10, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /tmp/wazuh-qa/tests/integration, configfile: pytest.ini
plugins: html-2.0.1, testinfra-6.0.0, metadata-1.11.0, testinfra-6.4.0
collected 4 items

../../tmp/wazuh-qa/tests/integration/test_vulnerability_detector/test_general_settings/test_general_settings_enabled.py . [ 25%]
ss.                                                                      [100%]

- generated html file: file:///tmp/wazuh-qa/tests/integration/reports/test_report-2021-08-27 15:24:03.619727.html -
========================= 2 passed, 2 skipped in 1.59s =========================
```

For compatibility reasons, we plan to add a new module that allows us to obtain the necessary information to launch the test, create the configuration file temporarily and from there continue using the `qa-ctl` tool as it is being used so far.

To obtain the test information, we will use the `qa-docs` tool, which given the test name, will return a JSON file with the information associated with the test that is needed for deployment, provisioning, run ....

## Tasks

- [x] Add new script parameters to `qa-ctl`.
- [x] Creation of a new module that is going to create the configuration file internally.
- [x] Mockeying the use of docs-generator to obtain the information associated with the test.
- [x] Change destruction behavior. By default it is destroyed and specified when not required.
- [x] Add test results retrieval.
- [x] Dynamically generate IP addresses from vagrant. Investigate local port forwarding connection.
- [x] Add dynamic package URLs.
- [x] Add tests info validation and give user feedback.
- [x] Get repository branches version from user input version.
- [x] Get last Wazuh version.
- [x] Code documentation.
- [x]  Configuration generation mode. The test information is processed and the configuration file is generated without launching anything else.
- [x] Integrating qa-docs in the qa-ctl tool.
- [x] Waiting for `qa-docs` test info generation.
- [x] Testing and debugging

**Comment by jmv74211** [comment]
Today I have been designing and implementing the `QACTLConfigGenerator` class to be able to auto-generate the QACTL configuration file based on the requirements of the test that the user is launching.

I have built the basic structure, and the whole file is already dynamically generated. I have had to mocke some parts such as networking, test information and the URL of the S3 packages.

I am currently investigating how I can generate automatic private IPs without any conflict for deployment.

**Comment by jmv74211** [comment]
Today I have been working on the part of generating dynamic IPS for vagrant, according to the dynamic information we get from the tests to run. These changes have been implemented and the configuration template is generated correctly (it is necessary to test these changes when the rest are integrated).

I have also been adding the necessary to complete the whole process of generating the dynamic configuration, mocking the external functions that we need to use.

I will continue with the development of these mocketed functions and then test all the new changes comprehensively with QA-CTL.

**Comment by jmv74211** [comment]
Today I have been working on the validation of test parameters along with those of the deployed environment according to the minimum user parameters such as the test(s) to be launched and the version of wazuh to be used.

In case there is an incorrect validation, the user is shown a message indicating the failure and is given the option to continue with the execution of `qactl` in case he has launched several tests. 

For example:

```
test_general_settings_enabled cannot be launched. Reason: Currently we do not support windows. Allowed values: ['linux']
Do you want to continue with qa-ctl running? [y/n]: y
```


```
The minimal version of wazuh to launch the test_general_settings_enabled is 4.2.0 and you are using 4.1.5
Do you want to continue with qa-ctl running? [y/n]:
```

If the user selects `n`, the execution will terminate.

I have also been working on obtaining the URL of the package to use for the provisioning of the machines. In this case, we will always use by default production packages for the specified version, taking into account the operating system needed to launch the test. In case of needing a development package, it is possible to specify parameters such as version, revision, system and repository to directly obtain the URL from S3.

It remains to finalize the revision of this functionality (URL generation) and continue with the rest of the pending tasks, indicated in the issue description, which a priori should not be long.

**Comment by jmv74211** [comment]
Today I have been working on parameter validations and finalizing the automatic generation of the configuration file.

Practically everything is finished, it remains to add the integration with QA-docs to get the information from the tests, and perform several test processes to verify the correct operation for various scenarios.

**Comment by jmv74211** [comment]
Today I have been making some improvements and finalizing the integration of `qa-docs` with `qa-ctl`.

Tomorrow we will merge the `qa-docs` PR and move on to the testing and debugging phase of the tool. This issue will be closed soon.

**Comment by jmv74211** [comment]
@fernandolojano and @jmv74211 (me) are performing a complete debugging process of the `qa-ctl` tool. 

# Checks performed

- [x] Installing the qa-ctl tool on Ubuntu and CentOS systems



# Problems found

| Legend | Description |
|-----------|-----------------|
|🟢 | Bug fixed |
|🟡 | Investigating bug and fixing it |
|🔴 | Could not fix it |

## 1: When running the test test_execd_restart test fails for the following reason

```bash
ModuleNotFoundError: No module named 'Crypto'
```

*Fix*


## 2: The libraries `docker`, `python-vagrant`, `ansible`, `ansible_runner` are missing in the `requirements.txt` file.

*Fix*


## 3: Error installing `qa-ctl` on centOS. Dependency failure:

```bash
FileNotFoundError: [Errno 2] No such file or directory: 'c++': 'c++'
```

*Fix*


## 4: Error installing grpcio dependency

```bash
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1
```

*Fix*

## 5: Error installing dependencies

```bash
AttributeError: 'Distribution' object has no attribute 'convert_2to3_doctests'
```

*Fix*

**Comment by jmv74211** [comment]
Today I have been doing the last adjustments, in addition to updating the parsing of the new schema presented by qa-docs. The first version (`0.0.1`) is already prepared
