### ISSUE TITLE
QA Docs: Migrate `test_analysisd` documentation to schema 1.0

### ISSUE THREAD

**Issue by mdengra** [wazuh/wazuh-qa#1804]
### Description

This issue is created to migrate the `test_analysisd` documentation to the new QA Docs schema as part of the epic https://github.com/wazuh/wazuh-qa/issues/1796.

In the QA Wiki there are two entries to help complete the tasks:

- [Documenting tests using the QA Docs schema](https://github.com/wazuh/wazuh-qa/wiki/Documenting-tests-using-the-QA-Docs-schema): This entry describes the steps needed to document the tests (schema to use, the position of blocks, allowed values for fields, etc.).
- [Documentation generation with DocGenerator tool](https://github.com/wazuh/wazuh-qa/wiki/Documentation-generation-with-DocGenerator-tool): Here is a brief description of how the `DocGenerator.py` module works to verify that the changes made in the tests have been done correctly.

#### Main branch
`1796-migrate-doc-schema-1`

#### Tasks
- [x] Migrate tests:
  - [x] **test_all_syscheckd_configurations**
    - [x] `test_check_rare_socket_responses.py` (**Create new documentation**)
    - [x] `test_check_socket_responses.py` (**Create new documentation**)
    - [x] `test_validate_linux_analysisd_alerts.py` (**Create new documentation**)
    - [x] `test_validate_rare_analysisd_alerts.py` (**Create new documentation**)
    - [x] `test_validate_win32_analysisd_alerts.py` (**Create new documentation**)
    - [x] `test_validate_win32_analysisd_registry_alerts.py` (**Create new documentation**)
  - [x] **test_error_messages**
    - [x] `test_error_messages.py` (**Create new documentation**)
  - [x] **test_event_messages**
    - [x] `test_event_messages.py` (**Create new documentation**)
  - [x] **test_integrity_messages**
    - [x] `test_integrity_messages.py` (**Create new documentation**)
  - [x] **test_mitre**
    - [x] `test_mitre_check_alert.py` 
  - [x] **test_scan_messages**
    - [x] `test_scan_messages.py` (**Create new documentation**)
- [x] Check `PEP-8` style guide (`pycodestyle --max-line-length=120`)
- [x] Merge issue branch to  `1796-migrate-doc-schema-1`

**Comment by mdengra** [comment]
## 2021-09-01
Working branch: `1804-qadocs-migrate-test-analysisd`
