### ISSUE TITLE
QA Docs: Migrate `test_api` documentation to schema 1.0

### ISSUE THREAD

**Issue by mdengra** [wazuh/wazuh-qa#1806]
### Description

This issue is created to migrate the `test_api` documentation to the new QA Docs schema as part of the epic https://github.com/wazuh/wazuh-qa/issues/1796.

In the QA Wiki there are two entries to help complete the tasks:

- [Documenting tests using the QA Docs schema](https://github.com/wazuh/wazuh-qa/wiki/Documenting-tests-using-the-QA-Docs-schema): This entry describes the steps needed to document the tests (schema to use, the position of blocks, allowed values for fields, etc.).
- [Documentation generation with DocGenerator tool](https://github.com/wazuh/wazuh-qa/wiki/Documentation-generation-with-DocGenerator-tool): Here is a brief description of how the `DocGenerator.py` module works to verify that the changes made in the tests have been done correctly.

#### Main branch
`1796-migrate-doc-schema-1`

#### Tasks
- [ ] Migrate tests:
  - [ ] **test_config**
    - [ ] **test_bruteforce_blocking_system**
      - [ ] `test_bruteforce_blocking_system.py`
    - [ ] **test_cache**
      - [ ] `test_cache.py`
    - [ ] **test_cors**
      - [ ] `test_cors.py`
    - [ ] **test_DOS_blocking_system**
      - [ ] `test_DOS_blocking_system.py`
    - [ ] **test_drop_privileges**
      - [ ] `test_drop_privileges.py`
    - [ ] **test_experimental_features**
      - [ ] `test_experimental_features.py`
    - [ ] **test_host_port**
      - [ ] `test_host_port.py`
    - [ ] **test_https**
      - [ ] `test_https.py`
    - [ ] **test_jwt_token_exp_timeout**
      - [ ] `test_jwt_token_exp_timeout.py`
    - [ ] **test_logs**
      - [ ] `test_logs.py`
    - [ ] **test_rbac**
      - [ ] `test_rbac_mode.py`
    - [ ] **test_request_timeout**
      - [ ] `test_request_timeout.py`
    - [ ] **test_use_only_authd **
      - [ ] `test_use_only_authd.py`
  - [ ] **test_rbac**
    - [ ] `test_add_old_resource.py`
    - [ ] `test_admin_resources.py`
    - [ ] `test_policy_position.py`
    - [ ] `test_remove_relationship.py`
    - [ ] `test_remove_resource.py`
- [ ] Check `PEP-8` style guide
- [ ] Merge issue branch to  `1796-migrate-doc-schema-1`

**Comment by mdengra** [comment]
## 2021-09-02
Working branch: `1806-qadocs-migrate-test-api`

**Comment by mdengra** [comment]
# 2021-09-08

## Update
I am migrating the provisional documentation of this issue to the final schema of the issue #1694.
