### ISSUE TITLE
qa-docs: Migrate `test_authd` documentation to schema 2.0

### ISSUE THREAD

**Issue by mdengra** [wazuh/wazuh-qa#1807]
### Description

This issue is created to migrate the `test_authd` documentation to the new **qa-docs** schema as part of the epic https://github.com/wazuh/wazuh-qa/issues/1796.

In the QA Wiki there are two entries to help complete the tasks:

- [Documenting tests using the qa-docs schema](https://github.com/wazuh/wazuh-qa/wiki/Documenting-tests-using-the-qadocs-schema): This entry describes the steps needed to document the tests (schema to use, the position of blocks, allowed values for fields, etc.).
- [Documentation generation with qa-docs tool](https://github.com/wazuh/wazuh-qa/wiki/Documentation-generation-with-qadocs-tool): Here is a brief description of how the `DocGenerator.py` module works to verify that the changes made in the tests have been done correctly.

## Main branch
`1796-migrate-doc-schema-2`

#### Tasks
- [x] Migrate tests:
  - [x] **test_authd**
    - [x] `test_authd_agents_ctx.py` (**Create new documentation**)
    - [x] `test_authd_local.py` (**Create new documentation**)
    - [x] `test_authd_name_ip_pass.py` (**Create new documentation**)
    - [x] `test_authd.py` (**Create new documentation**)
    - [x] `test_authd_ssl_certs.py` (**Create new documentation**)
    - [x] `test_authd_ssl_options.py` (**Create new documentation**)
    - [x] `test_authd_worker.py` (**Create new documentation**)
    - [x] `test_remote_enrollment.py`
- [x] Check `PEP-8` style guide (`pycodestyle --max-line-length=120 --show-source --show-pep8`)
- [x] Merge issue branch to  `1796-migrate-doc-schema-1`

**Comment by mdengra** [comment]
## 2021-09-16

Working branch: `1807-qadocs-migrate-test-authd`
