### ISSUE TITLE
qa-docs: Migrate `test_cluster` documentation to schema 2.0

### ISSUE THREAD

**Issue by mdengra** [wazuh/wazuh-qa#1808]
### Description

This issue is created to migrate the `test_cluster` documentation to the new **qa-docs** schema as part of the epic https://github.com/wazuh/wazuh-qa/issues/1796.

In the QA Wiki there are two entries to help complete the tasks:

- [Documenting tests using the qa-docs schema](https://github.com/wazuh/wazuh-qa/wiki/Documenting-tests-using-the-qadocs-schema): This entry describes the steps needed to document the tests (schema to use, the position of blocks, allowed values for fields, etc.).
- [Documentation generation with qa-docs tool](https://github.com/wazuh/wazuh-qa/wiki/Documentation-generation-with-qadocs-tool): Here is a brief description of how the `DocGenerator.py` module works to verify that the changes made in the tests have been done correctly.

## Main branch
`1796-migrate-doc-schema-2`

#### Tasks
- [x] Migrate tests:
  - [x] **test_key_polling**
    - [x] `test_key_polling_master.py` (**Create new documentation**)
    - [x] `test_key_polling_worker.py` (**Create new documentation**)
- [x] Check `PEP-8` style guide (`pycodestyle --max-line-length=120 --show-source --show-pep8`)
- [ ] Merge issue branch to  `1796-migrate-doc-schema-1`

**Comment by mdengra** [comment]
## 2021-09-17

Working branch: `1808-qadocs-migrate-test-cluster`
