### ISSUE TITLE
qa-docs: Migrate `test_logcollector` documentation to schema 2.0

### ISSUE THREAD

**Issue by mdengra** [wazuh/wazuh-qa#1813]
### Description

This issue is created to migrate the `test_logcollector` documentation to the new **qa-docs** schema as part of the epic https://github.com/wazuh/wazuh-qa/issues/1796.

In the QA Wiki there are two entries to help complete the tasks:

- [Documenting tests using the qa-docs schema](https://github.com/wazuh/wazuh-qa/wiki/QADOCS-tool-How-to-document-a-test): This entry describes the steps needed to document the tests (schema to use, the position of blocks, allowed values for fields, etc.).
- [Documentation generation with qa-docs tool](https://github.com/wazuh/wazuh-qa/wiki/QADOCS-tool): Here is a brief description of how the `qa-docs` tool works to verify that the changes made in the tests have been done correctly.

## Main branch
`master`

#### Tasks
- [x] Migrate tests:
  - [x] **test_age**
    - [x] `test_age_basic.py`
    - [x] `test_age_datetime_changed.py`
  - [x] **test_command_monitoring**
    - [x] `test_command_execution_freq.py`
    - [x] `test_command_execution.py`
  - [x] **test_configuration**
    - [x] `test_basic_configuration_age.py`
    - [x] `test_basic_configuration_alias.py`
    - [x] `test_basic_configuration_command.py`
    - [x] `test_basic_configuration_exclude.py`
    - [x] `test_basic_configuration_frequency.py`
    - [x] `test_basic_configuration_ignore_binaries.py`
    - [x] `test_basic_configuration_label.py`
    - [x] `test_basic_configuration_location.py`
    - [x] `test_basic_configuration_log_format.py`
    - [x] `test_basic_configuration_only_future_events.py`
    - [x] `test_basic_configuration_out_format.py`
    - [x] `test_basic_configuration_query.py`
    - [x] `test_basic_configuration_reconnect_time.py`
    - [x] `test_basic_configuration_target.py`
  - [x] **test_keep_running**
    - [x] `test_keep_running.py`
  - [x] **test_location**
    - [x] `test_location_exclude.py`
    - [x] `test_location.py`
  - [x] **test_location_custom_sockets**
    - [x] `test_location_custom_sockets.py`
  - [x] **test_log_format**
    - [x] `test_log_format_values.py`
  - [x] **test_macos**
    - [x]  `test_macos_file_status_basic.py`
    - [x] `test_macos_file_status_predicate.py`
    - [x] `test_macos_file_status_when_no_macos.py`
    - [x] `test_macos_format_basic.py`
    - [x] `test_macos_format_only_future_events.py`
    - [x] `test_macos_format_query.py`
    - [x] `test_macos_log_process.py`
    - [x] `test_macos_multiline_values.py`
  - [x] **test_only_future_events**
    - [x] `test_only_future_events.py`
  - [x] **test_options**
    - [x] `test_options_state_interval_no_file.py`
    - [x] `test_options_state_interval.py`
  - [x] **test_reconnect_time**
    - [x] `test_reconnect_time.py`
  - [x] **test_statistics**
    - [x] `test_statistics_macos.py` 
- [x] Check `PEP-8` style guide (`pycodestyle --max-line-length=120`)
