### ISSUE TITLE
qa-docs: Migrate `test_logtest` documentation to schema 2.0

### ISSUE THREAD

**Issue by mdengra** [wazuh/wazuh-qa#1814]
### Description

This issue is created to migrate the `test_logtest` documentation to the new **qa-docs** schema as part of the epic https://github.com/wazuh/wazuh-qa/issues/1796.

In the QA Wiki there are two entries to help complete the tasks:

- [Documenting tests using the qa-docs schema](https://github.com/wazuh/wazuh-qa/wiki/QADOCS-tool-How-to-document-a-test): This entry describes the steps needed to document the tests (schema to use, the position of blocks, allowed values for fields, etc.).
- [Documentation generation with qa-docs tool](https://github.com/wazuh/wazuh-qa/wiki/QADOCS-tool): Here is a brief description of how the `qa-docs` tool works to verify that the changes made in the tests have been done correctly.

#### Main branch
`master`

#### Tasks
- [x] Migrate tests:
  - [x] **test_configuration**
    - [x] `test_configuration_file.py`
    - [x] `test_get_configuration_sock.py`
  - [x] **test_invalid_rule_decoders_syntax**
    - [x] `test_invalid_decoder_syntax.py`
    - [x] `test_invalid_rules_syntax.py`
  - [x] **test_invalid_socket_input**
    - [x] `test_invalid_socket_input.py`
  - [x] **test_invalid_token**
    - [x] `test_invalid_session_token.py`
  - [x] **test_log_process_options**
    - [x] `test_rules_verbose.py`
  - [x] **test_remove_old_sessions**
    - [x] `test_remove_old_session_for_inactivity.py`
    - [x] `test_remove_old_sessions.py`
  - [x] **test_remove_session**
    - [x] `test_remove_session.py`
  - [x] **test_rules_decoders_load**
    - [x] `test_load_rules_decoders.py`
  - [x] **test_ruleset_refresh**
    - [x] `test_altert_labels.py`
    - [x] `test_cdb_labels.py`
    - [x] `test_decoder_labels.py`
    - [x] `test_rule_labels.py`
- [x] Check `PEP-8` style guide (`pycodestyle --max-line-length=120`)
- [x] Documentation correctly generated using the current `qa-docs` tool
- [ ] Merge issue branch to  `master`

**Comment by roronoasins** [comment]
Working branch: [1814-qadocs-migrate-logtest](https://github.com/wazuh/wazuh-qa/tree/1814-qadocs-migrate-logtest)
