### ISSUE TITLE
qa-docs: Migrate `test_remoted` documentation to schema 2.0

### ISSUE THREAD

**Issue by mdengra** [wazuh/wazuh-qa#1816]
### Description

This issue is created to migrate the `test_remoted` documentation to the new QA Docs schema as part of the epic https://github.com/wazuh/wazuh-qa/issues/1796.

In the QA Wiki there are two entries to help complete the tasks:

- [Documenting tests using the qa-docs schema](https://github.com/wazuh/wazuh-qa/wiki/QADOCS-tool-How-to-document-a-test): This entry describes the steps needed to document the tests (schema to use, the position of blocks, allowed values for fields, etc.).
- [Documentation generation with qa-docs tool](https://github.com/wazuh/wazuh-qa/wiki/QADOCS-tool): Here is a brief description of how the `qa-docs` tool works to verify that the changes made in the tests have been done correctly.

#### Main branch
`master`

#### Tasks
- [ ] Migrate tests:
  - [x] **test_active_response**
    - [x] `test_active_response_send_ar.py`
  - [x] **test_agent_communication**
    - [x] `test_agent_pending_status.py` 
    - [x] `test_agents_switching_protocols.py`
    - [x] `test_agent_version_shared_configuration_startup_message.py`
    - [x] `test_invalid_protocol_communication.py`
    - [x] `test_multi_agent_protocols_communication.py`
    - [x] `test_multi_agent_status.py`
    - [x] `test_protocols_communication.py`
    - [x] `test_request_agent_info.py`
    - [x] `test_shared_configuration.py`
  - [x] **test_configuration**
    - [x] `test_basic_configuration_connection_invalid_connection.py`
    - [x] `test_basic_configuration_connection_invalid_port.py`
    - [x] `test_basic_configuration_connection_invalid_protocol.py`
    - [x] `test_basic_configuration_connection_valid.py`
    - [x] `test_basic_configuration_ipv6.py`
    - [x] `test_basic_configuration_local_ip_invalid.py`
    - [x] `test_basic_configuration_local_ip_valid.py`
    - [x] `test_basic_configuration_queue_size_syslog.py`
    - [x] `test_basic_configuration_queue_size_too_big.py`
    - [x] `test_basic_configuration_queue_size_valid.py`
    - [x] `test_basic_configuration_rids_closing_time_invalid.py`
    - [x] `test_basic_configuration_rids_closing_time_valid.py`
    - [x] `test_basic_configuration_syslog_allowed_denied_ips_valid.py`
    - [x] `test_basic_configuration_syslog_allowed_ips_invalid.py`
    - [x] `test_basic_configuration_syslog_denied_ips_invalid.py`
    - [x] `test_basic_configuration_syslog_denied_ips.py`
    - [x] `test_basic_configuration_syslog_no_allowed_ips.py`
  - [ ] **test_manager_messages**
    - [ ] `test_manager_ack.py`
  - [ ] **test_socket_communication**
    - [ ] `test_ping_pong_message.py`
    - [ ] `test_syslog_message.py`
- [ ] Check `PEP-8` style guide (`pycodestyle --max-line-length=120`)
- [ ] Merge issue branch to  `master`

**Comment by mdengra** [comment]
## 2021-11-05

Working branch: `1816-qadocs-migrate-test-remoted`
