### ISSUE TITLE
qa-docs: Migrate `test_rids` documentation to schema 2.0

### ISSUE THREAD

**Issue by mdengra** [wazuh/wazuh-qa#1817]
### Description

This issue is created to migrate the `test_rids` documentation to the new QA Docs schema as part of the epic https://github.com/wazuh/wazuh-qa/issues/1796.

In the QA Wiki there are two entries to help complete the tasks:

- [Documenting tests using the qa-docs schema](https://github.com/wazuh/wazuh-qa/wiki/QA-Documentation---How-to-document-a-test-using-Schema-2.0#pre-defined-values): This entry describes the steps needed to document the tests (schema to use, the position of blocks, allowed values for fields, etc.).
- [Documentation generation with qa-docs tool](https://github.com/wazuh/wazuh-qa/wiki/QADOCS-tool-use-guide): Here is a brief description of how the `qa-docs` module works to verify that the changes made in the tests have been done correctly.

#### Main branch
`1817-qadocs-migrate-test-rids`

#### Tasks
- [x] Migrate tests:
  - [x] **test_rids**
    - [x] `test_rids_conf.py`
    - [x] `test_rids.py`
- [x] Check `PEP-8` style guide (`pycodestyle --max-line-length=120`)
- [ ] Merge issue branch to  `master`

**Comment by roronoasins** [comment]
# qa-docs run
The documentation can be generated without errors

```bash
$ qa-docs --tests-path ~/work/thunder/issues/1817/wazuh-qa/tests/ -t test_rids_conf test_rids
2021-12-30 16:34:28,623 - INFO - Looking for test_rids_conf.py
2021-12-30 16:34:28,624 - INFO - Looking for test_rids.py
2021-12-30 16:34:28,626 - INFO - Parsing the following test(s) ['test_rids_conf', 'test_rids']
2021-12-30 16:34:28,638 - INFO - Running QADOCS
2021-12-30 16:34:28,638 - INFO - Looking for test_rids_conf.py
2021-12-30 16:34:28,783 - INFO - Looking for test_rids.py
2021-12-30 16:34:28,881 - INFO - Run completed, documentation location: /tmp/qa_docs/output
```
