### ISSUE TITLE
qa-docs: Migrate `test_vulnerability_detector` documentation to schema 2.0

### ISSUE THREAD

**Issue by mdengra** [wazuh/wazuh-qa#1819]
### Description

This issue is created to migrate the `test_vulnerability_detector` documentation to the new QA Docs schema as part of the epic https://github.com/wazuh/wazuh-qa/issues/1796.

In the QA Wiki there are two entries to help complete the tasks:

- [Documenting tests using the QA Docs schema](https://github.com/wazuh/wazuh-qa/wiki/QA-Documentation---How-to-document-a-test-using-Schema-2.0): This entry describes the steps needed to document the tests (schema to use, the position of blocks, allowed values for fields, etc.).
- [Documentation generation with DocGenerator tool](https://github.com/wazuh/wazuh-qa/wiki/QADOCS-tool-use-guide): Here is a brief description of how the `DocGenerator.py` module works to verify that the changes made in the tests have been done correctly.

#### Main branch
`1796-migrate-doc-schema-1`

#### Tasks
- [x] Migrate tests:
  - [x] [**test_feeds**](https://github.com/wazuh/wazuh-qa/issues/2324)
    - [x] **archlinux**
      - [x] `test_extra_tags_archlinux_feed.py`
      - [x] `test_invalid_syntax_archlinux_feed.py`
      - [x] `test_invalid_values_archlinux_feed.py`
      - [x] `test_missing_tags_archlinux_feed.py`
    - [x] **canonical**
      - [x] `test_extra_tags_canonical_feed.py`
      - [x] `test_invalid_syntax_canonical_feed.py`
      - [x] `test_invalid_values_canonical_feed.py`
      - [x] `test_missing_tags_canonical_feed.py`
    - [x] **debian**
      - [x] `test_extra_tags_debian_feed.py`
      - [x] `test_invalid_syntax_debian_feed.py`
      - [x] `test_invalid_values_debian_feed.py`
      - [x] `test_missing_tags_debian_feed.py`
    - [x] **msu**
      - [x] `test_extra_fields_msu_feed.py`
      - [x] `test_invalid_syntax_msu_feed.py`
      - [x] `test_invalid_values_msu_feed.py`
      - [x] `test_missing_fields_msu_feed.py`
    - [x] **redhat**
      - [x] `test_extra_fields_redhat_feed.py`
      - [x] `test_invalid_syntax_redhat_feed.py`
      - [x] `test_invalid_values_redhat_feed.py`
      - [x] `test_missing_fields_redhat_feed.py`
    - [x] `test_download_feeds.py`
    - [x] `test_invalid_type_custom_feeds.py`
    - [x] `test_invalid_type_url_feeds.py`
    - [x] `test_validate_feed_content.py`
  - [x] [**test_general_settings**](https://github.com/wazuh/wazuh-qa/issues/2325)
    - [x] `test_general_settings_enabled.py`
    - [x] `test_general_settings_ignore_time.py`
    - [x] `test_general_settings_interval.py`
    - [x] `test_general_settings_run_on_start.py`
  - [x] [**test_providers**](https://github.com/wazuh/wazuh-qa/issues/2326)
    - [x] `test_providers_enabled.py`
    - [x] `test_providers_multiple_providers.py`
    - [x] `test_providers_no_os.py`
    - [x] `test_providers_os.py`
    - [x] `test_providers_update_from_year.py`
    - [x] `test_providers_update_interval.py`
  - [x] [**test_scan_results**](https://github.com/wazuh/wazuh-qa/issues/2327)
    - [x] `test_archliux_inventory_archlinux_feed.py`
    - [x] `test_debian_inventory_debian_feed.py`
    - [x] `test_macos_inventory.py`
    - [x] `test_msu_inventory_msu_feed.py`
    - [x] `test_redhat_duplicate_vulns.py`
    - [x] `test_redhat_inventory_redhat_feed.py`
    - [x] `test_scan_different_cves.py`
    - [x] `test_scan_nvd_feed.py`
    - [x] `test_scan_providers_and_nvd_feed.py`
    - [x] `test_ubuntu_inventory_canonical_feed.py`
  - [x] [**test_windows**](https://github.com/wazuh/wazuh-qa/issues/2328)
    - [x] `test_cpe_indexing.py`
- [x] Check `PEP-8` style guide (`pycodestyle --max-line-length=120`)
- [ ] Merge issue branch to  `master`
