### ISSUE TITLE
qa-docs: Migrate `test_wazuh_db` documentation to schema 2.0

### ISSUE THREAD

**Issue by mdengra** [wazuh/wazuh-qa#1820]
### Description

This issue is created to migrate the `test_wazuh_db` documentation to the new QA Docs schema as part of the epic https://github.com/wazuh/wazuh-qa/issues/1796.

In the QA Wiki there are two entries to help complete the tasks:

- [Documenting tests using the QA Docs schema](https://github.com/wazuh/wazuh-qa/wiki/Documenting-tests-using-the-QA-Docs-schema): This entry describes the steps needed to document the tests (schema to use, the position of blocks, allowed values for fields, etc.).
- [Documentation generation with DocGenerator tool](https://github.com/wazuh/wazuh-qa/wiki/Documentation-generation-with-DocGenerator-tool): Here is a brief description of how the `DocGenerator.py` module works to verify that the changes made in the tests have been done correctly.

#### Main branch
`1796-migrate-doc-schema-1`

#### Tasks
- [x] Migrate tests:
  - [x] **test_wazuh_db**
    - [x] `test_wazuh_db.py`
- [x] Check `PEP-8` style guide (`pycodestyle --max-line-length=120`)
- [x] Ckeck with QA-Doc style format
- [ ] Merge issue branch to  `1796-migrate-doc-schema-1`

**Comment by fedepacher** [comment]
Studying how to create test documentation using Wazuh wiki repository.

**Comment by fedepacher** [comment]
## QA-docs execution 

`qa-docs --tests-path /home/fede/Wazuh/Repo/issue/1820/wazuh-qa/tests/ --types integration --modules test_wazuh_db`

### Results
`2021-12-14 10:29:10,179 - INFO - Parsing the following test(s) type(s): ['integration']
2021-12-14 10:29:10,179 - INFO - Parsing the following test(s) modules(s): ['test_wazuh_db']
2021-12-14 10:29:10,193 - INFO - Running QADOCS
2021-12-14 10:29:10,781 - INFO - Run completed, documentation location: /tmp/qa_docs/output`

### Output File
[test_wazuh_db output results](https://github.com/wazuh/wazuh-qa/files/7711991/test_wazuh_db.zip)
