### ISSUE TITLE
QA Docs: Migrate `test_wpk` documentation to schema 1.0

### ISSUE THREAD

**Issue by mdengra** [wazuh/wazuh-qa#1821]
### Description

This issue is created to migrate the `test_wpk` documentation to the new QA Docs schema as part of the epic https://github.com/wazuh/wazuh-qa/issues/1796.

In the QA Wiki there are two entries to help complete the tasks:

- [Documenting tests using the QA Docs schema](https://github.com/wazuh/wazuh-qa/wiki/QA-Documentation---How-to-document-a-test-using-Schema-2.0): This entry describes the steps needed to document the tests (schema to use, the position of blocks, allowed values for fields, etc.).
- [Documentation generation with DocGenerator tool](https://github.com/wazuh/wazuh-qa/wiki/QA-Documentation---How-to-document-a-test-using-Schema-2.0): Here is a brief description of how the `DocGenerator.py` module works to verify that the changes made in the tests have been done correctly.

#### Main branch
`1796-migrate-doc-schema-1`

#### Tasks
- [ ] Migrate tests:
  - [ ] **test_wpk**
    - [ ] `test_wpk_agent.py`
    - [ ] `test_wpk_manager.py`
    - [ ] `test_wpk_manager_task_states.py`
- [ ] Check `PEP-8` style guide (`pycodestyle --max-line-length=120`)
- [ ] Merge issue branch to  `1796-migrate-doc-schema-1`
