### ISSUE TITLE
QACTL: Write a complete documentation for the qactl tool

### ISSUE THREAD

**Issue by fernandolojano** [wazuh/wazuh-qa#1839]
This issue has been created in order to create a more complete documentation of the QACTL tool. It is needed to create an installation guide documentation, a guide of use, a changelog file for qactl, and a version file.

## Tasks
In order to complete the issue, the next tasks have to be done:
- [x] Write an installation guide for the tool
- [x] Write a guide of use for the tool
- [x] Search for all the current features of the tool.
- [x] Add all the features in a changelog file
- [x] Add a version file for the tool
- [x]  Create a checklist for QACTL releases

**Comment by fernandolojano** [comment]
As for now, there are a qactl-installation-guide, qactl-use-guide, changelog, and version files written. All that documents are in a pending review status. 
The next task is to create a checklist for the QACTL tool release. In order to test its features before releasing the tool, it is needed to create several checks for the tool.
