### ISSUE TITLE
QA Docs: Documenting tests for QACTL 0.1

### ISSUE THREAD

**Issue by mdengra** [wazuh/wazuh-qa#1840]
### Description

This issue is created to document several tests whose execution time is fast to use with **QACTL** version `0.1`. The tests will be documented following the scheme proposed by the `qactl` team.

#### Main branch
`1800-parse-single-test`

#### Working branch
`1840-migrate-test-doc-qactl`

#### Tasks
- [x] Migrate tests:
  - [x] **test_active_response/test_execd**
    - [x] `test_execd_restart.py`
    - [x] `test_execd_firewall_drop.py`
  - [x] **test_api/test_config**
    - [x] **test_cache**
      - [x] `test_cache.py`
    - [x] **test_cors**
      - [x] `test_cors.py`
- [x] Check `PEP-8` style guide (`pycodestyle --max-line-length=120`)
