### ISSUE TITLE
Design and develop cluster performance tests

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh-qa#1845]
The goal of this set of issues is to investigate, design, and create automatic tests for the Wazuh cluster. These tests should allow us to determine if the different tasks of the cluster have an anomalous behavior, as well as to check that the use of resources is normal.

### Tasks
- [ ] Research and establish thresholds for resource usage.
- [ ] Investigate and determine the thresholds for the different cluster tasks.
- [ ] Define the different phases of the cluster within the test (Setup phase, Stable phase).
- [ ] Design and develop the test for the setup phase.
- [ ] Design and develop the test for the stable phase.
- [ ] Design and develop a test that analyzes the logs and indicates if there is any unexpected behavior.
- [ ] Get the time/resource specification for a given number of agents/workers on given hardware.
