### ISSUE TITLE
Set a maximum threshold for the time consumed by cluster tasks

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh-qa#1856]
In this issue, we are going to define some thresholds that will help us determine when the cluster has an anomalous behavior. We will have to set the time which will be considered normal for the different cluster tasks.

These thresholds will be established by using a hardware standard which will be detailed in this issue. These thresholds will be determined by reviewing several executions of an environment with different configurations.

We will also check if there is a linear relationship between the time consumed by the different configurations. If so, we could establish dynamic thresholds according to each configuration.

### Tasks

- [ ] Analyze the results with 5 workers 25000 agents.
- [ ] Analyze the results with 10 workers 50000 agents.
- [ ] Analyze the results with 25 workers 50000 agents.
- [ ] Analyze the results with 50 workers 50000 agents.
