### ISSUE TITLE
FIM Windows Agent - Case: ignores duplicate entries

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#1860]
## Description 

FIM tests has a lot of tests to fix because fails inconsistent times.

| Related to | 
|--|
| https://github.com/wazuh/wazuh-qa/issues/1873

### Pipeline parameters

|  Jenkins branch  | QA branch   | 
|- |- |
|  v4.2.1-rc1 |   1873-4.2.1-fim-windows-agent |

## Packages Info

| Type | Format | Architecture | Versión | Revision |  Tag | File name |
|:--:|:--:|:--:|:--:|:--:|:--:|:--:|
| Server | rpm | x86_64 | v4.2.1 | 40214| v4.2.1 | wazuh-manager-4.2.1-0.1873.x86_64.rpm |
| Agent | rpm | x86_64 | v4.2.1 | 40214|v4.2.1| wazuh-agent-4.2.1-0.1873.x86_64.rpm |
| Agent | msi (Windows) | x86_64 | v4.2.1 | 40214| v4.2.1| wazuh-agent-4.2.1-0.1873.msi |
| Agent | pkg (macOS) | x86_64 | v4.2.1 | 40214| v4.2.1| wazuh-agent-4.2.1-0.1873.pkg |
|Agent | p5p (Solaris 11) | x86_64 | v4.2.1 | 40214|v4.2.1| wazuh-agent_v4.2.1-0.1873-sol11-i386.p5p​|
|Agent | p5p (Solaris 10) | x86_64 | v4.2.1 | 40214|v4.2.1| wazuh-agent_v4.2.1-0.1873-sol10-i386.pkg
|Agent | wpk (Linux) | x86_64 | v4.2.1 | 40214| v4.2.1 | wazuh_agent_v4.2.1-0.1873_linux_x86_64.wpk
|Agent | wpk (Windows) | x86_64 | v4.2.1 | 40214|v4.2.1| wazuh_agent_v4.2.1-0.1873_windows.wpk

**Note**: The tag is `v4.2.1` but for now, to create it on jenkins you need to use `v4.2.1-rc1`.

#### Manager
```
syscheck.debug=2
analysisd.debug=2
monitord.rotate_log=0
```

#### Agent
```
agent.debug=2
syscheck.debug=2
monitord.rotate_log=0
```

### Environment 
Provider| Box| OS| CPU| Memory | 
--|--|--|--|--|
Vagrant |  | Windows | 2 | 1024 |

### pytest_args
`-v --tier 0 --tier 1 --tier 2 --fim_mode="realtime" --fim_mode="whodata"`

## Development

Fix `tests\integration\test_fim\test_files\test_ambiguous_confs\test_duplicate_entries.py` to Windows. 

If the test work successfully after 2 times, you should see if other member could be verify that it woks successfully. 

## Tasks
- [ ] Research about the Test Case.
- [ ] Fix the Test Case.
- [x] Verify that each execution works successfully. (Full Green - Attach evidence.)
- [x] Verify that cover `scheduled`, `realtime`, and  `whodata`. Research if this case require all args, or only one.

**Comment by danisan90** [comment]
Tests results:
| Name  |  Type  | Note |
|--|--|--|

**Comment by MizugorouZ** [comment]
### Local Results
These are the results of the `tests\integration\test_fim\test_files\test_ambiguous_confs\test_duplicate_entries.py` test for Windows with all the combinations of `--fim_mode` parameters (`realtime, whodata, scheduled`):
| Test | Date | By | Results | Status |
|:--:|:--:|:--:|:--:|:--:|
| `test_basic_usage_starting_agent.py` | 2021/09/16 | @MizugorouZ | [ResultsAmbiguousConfsDuplicateEntries](https://github.com/wazuh/wazuh-qa/files/7186026/ResultsDuplicateEntries.zip) | :green_circle: |

**Comment by damarisg** [comment]
This issue is closed because we couldn't reproduce these failures.

### Test Results 
| Results | Date | By | Status |
|--|--|--|--|
| [ResultsAmbiguiousDuplicateEntries.zip](https://github.com/wazuh/wazuh-qa/files/7220643/ResultsAmbiguiousDuplicateEntries.zip)  |  2021/09/23 | Seyla | 🟢
