### ISSUE TITLE
 FIM Windows Agent - Case: Basic Usage 

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#1861]
## Description 

FIM tests has a lot of tests to fix because fails inconsistent times.

| Related to | 
|--|
| https://github.com/wazuh/wazuh-qa/issues/1873

### Pipeline parameters

|  Jenkins branch  | QA branch   | 
|- |- |
|  v4.2.1-rc1 |   1873-4.2.1-fim-windows-agent |

### Packages details

| Type | Format | Architecture | Versión | Revision |  Tag | File name |
|:--:|:--:|:--:|:--:|:--:|:--:|:--:|
| Server | rpm | x86_64 | v4.2.1 | 40214| v4.2.1 | wazuh-manager-4.2.1-0.1873.x86_64.rpm |
| Agent | rpm | x86_64 | v4.2.1 | 40214|v4.2.1| wazuh-agent-4.2.1-0.1873.x86_64.rpm |
| Agent | msi (Windows) | x86_64 | v4.2.1 | 40214| v4.2.1| wazuh-agent-4.2.1-0.1873.msi |
| Agent | pkg (macOS) | x86_64 | v4.2.1 | 40214| v4.2.1| wazuh-agent-4.2.1-0.1873.pkg |
|Agent | p5p (Solaris 11) | x86_64 | v4.2.1 | 40214|v4.2.1| wazuh-agent_v4.2.1-0.1873-sol11-i386.p5p​|
|Agent | p5p (Solaris 10) | x86_64 | v4.2.1 | 40214|v4.2.1| wazuh-agent_v4.2.1-0.1873-sol10-i386.pkg
|Agent | wpk (Linux) | x86_64 | v4.2.1 | 40214| v4.2.1 | wazuh_agent_v4.2.1-0.1873_linux_x86_64.wpk
|Agent | wpk (Windows) | x86_64 | v4.2.1 | 40214|v4.2.1| wazuh_agent_v4.2.1-0.1873_windows.wpk

**Note**: The tag is `v4.2.1` but for now, to create it on jenkins you need to use `v4.2.1-rc1`.

#### Manager
```
syscheck.debug=2
analysisd.debug=2
monitord.rotate_log=0
```

#### Agent
```
agent.debug=2
syscheck.debug=2
monitord.rotate_log=0
```

### Environment 

Provider| Box| OS| CPU| Memory | 
--|--|--|--|--|
Vagrant |  | Windows | 2 | 1024 |

### pytest_args
`-v  --fim_mode="realtime" --fim_mode="whodata"`

## Development

This folder contains a lot of test. You need to verify that all tests from  `test_fim\test_files\test_basic_usage` works successfully on Windows. 

If there any failure, you need to fix. On last executions, we detected some failres on `test_fim\test_files\test_basic_usage\test_basic_usage_create_after_delete_dir.py` and on `test_fim/test_files/test_basic_usage/test_basic_usage_rename.py`. 

If the test work successfully after 3 executions, you should see if other member could be verify that it woks successfully. 

## Tasks
- [x] Research about the Test Case.
- [x] Fix the Test Case  if there are failures.
- [x] Verify that each execution cover `scheduled`, `realtime`, and  `whodata` mode. And It works successfully . (Full Green - Attach evidence.)

**Comment by MizugorouZ** [comment]
### Local Results

These are the results of executing `test_fim\test_files\test_basic_usage\` in Windows with all the combinations of `fim_mode` (`realtime, whodata, scheduled`):

| Pytest arguments | Date | By | Results | Status |
|:--:|:--:|:--:|:--:|:--:|
| `--fim_mode="realtime" --fim_mode="whodata" --fim_mode="scheduled"` | 2021/09/17 | @MizugorouZ | [ResultsBasicUsage](https://github.com/wazuh/wazuh-qa/files/7187408/ResultsBasicUsage_rt_who_sch.zip) | :green_circle: |
| `--fim_mode="realtime" --fim_mode="whodata"` | 2021/09/17 | @MizugorouZ | [ResultsBasicUsage](https://github.com/wazuh/wazuh-qa/files/7187416/ResultsBasicUsage_rt_who.zip) | :green_circle: |
| `--fim_mode="realtime" --fim_mode="scheduled"` | 2021/09/17 | @MizugorouZ | [ResultsBasicUsage](https://github.com/wazuh/wazuh-qa/files/7187420/ResultsBasicUsage_rt_sch.zip) | :green_circle: |
| `--fim_mode="whodata" --fim_mode="scheduled"` | 2021/09/17 | @MizugorouZ | [ResultsBasicUsage](https://github.com/wazuh/wazuh-qa/files/7187422/ResultsBasicUsage_who_sch.zip) | :green_circle: |
| `--fim_mode="realtime"` | 2021/09/17 | @MizugorouZ | [ResultsBasicUsage](https://github.com/wazuh/wazuh-qa/files/7187425/ResultsBasicUsage_rt.zip) | :green_circle: |
| `--fim_mode="whodata"` | 2021/09/17 | @MizugorouZ | [ResultsBasicUsage](https://github.com/wazuh/wazuh-qa/files/7187426/ResultsBasicUsage_who_ERROR.zip) | :red_circle: |
| `--fim_mode="scheduled"` | 2021/09/17 | @MizugorouZ | [ResultsBasicUsage](https://github.com/wazuh/wazuh-qa/files/7187433/ResultsBasicUsage_sch.zip) | :green_circle: |

As the results show, `--fim_mode="whodata"` didn't pass the test. Due to this parameter being the only one who had an error, we executed the test with this parameter several times to check if the error appeared again. However, we couldn't replicate the error:
| Pytest arguments | Date | By | Results | Status |
|:--:|:--:|:--:|:--:|:--:|
| `--fim_mode="whodata"` | 2021/09/17 | @MizugorouZ | [ResultsBasicUsage_whodata](https://github.com/wazuh/wazuh-qa/files/7187472/ResultsBasicUsage_who.zip) | :green_circle: |
| `--fim_mode="whodata"` | 2021/09/17 | @MizugorouZ | [ResultsBasicUsage_whodata2](https://github.com/wazuh/wazuh-qa/files/7187473/ResultsBasicUsage_who_2.zip) | :green_circle: |
| `--fim_mode="whodata"` | 2021/09/17 | @MizugorouZ | [ResultsBasicUsage_whodata3](https://github.com/wazuh/wazuh-qa/files/7187474/ResultsBasicUsage_who_3.zip) | :green_circle: |

**Comment by Deblintrake09** [comment]
**Local Results**

 Pytest arguments | Date | By | Results | Status |
|:--:|:--:|:--:|:--:|:--:|
| `--fim_mode="realtime" --fim_mode="whodata" --fim_mode="scheduled"` | 2021/09/20 | @Deblintrake09  | [ResultsBasicUsage.zip](https://github.com/wazuh/wazuh-qa/files/7202678/ResultsBasicUsage.zip)   | :red_circle: |
| `--fim_mode="realtime" --fim_mode="whodata" --fim_mode="scheduled"` | 2021/09/17 | @Deblintrake | [ResultsBasicUsage2.zip](https://github.com/wazuh/wazuh-qa/files/7202685/ResultsBasicUsage2.zip) | :red_circle: |

**Comment by MizugorouZ** [comment]
### Local results
These are the results of executing 6 times `test_fim\test_files\test_basic_usage\` with the parameters `--fim_mode="realtime" --fim_mode="whodata" --fim_mode="scheduled"`. All the executions passed the test:
| Results | Date | By | Status |
|:--:|:--:|:--:|:--:|
| [ResultsBasicUsage](https://github.com/wazuh/wazuh-qa/files/7212759/ResultsBasicUsage.zip) | 2021/09/22 | @MizugorouZ | :green_circle: |

**Comment by danisan90** [comment]
**Local Results**


These are the results of executing  `test_fim\test_files\test_basic_usage\` with the parameters `--fim_mode="realtime" --fim_mode="whodata" --fim_mode="scheduled"`
| Results |Date| By | Status |
|:--:|:--:|:--:|:--:|
|[Resultsbasic1](https://github.com/wazuh/wazuh-qa/files/7226847/Resultsbasic1.zip)| 2021/09/23 | @danisan90|  🔴 
|[Resultsbasic2](https://github.com/wazuh/wazuh-qa/files/7226851/Resultsbasic2.zip)| 2021/09/23 | @danisan90| 🔴

**Comment by damarisg** [comment]
## Update 2021/09/24

This issue requires a new review of Antonio because these tests continue working inconsistently. We can see the lists of results inconsistents.

| Results | Date | By | Status |
|--|--|--|--|
[ResultsBasicUsage.zip](https://github.com/wazuh/wazuh-qa/files/7227897/ResultsBasicUsage.zip) | 2021/09/24 | Seyla | 🟢

**Comment by damarisg** [comment]
Closed by #1946. 

I attach the result after it merged, to verify that it continues working.
 
 | Results | Date | By | Status |
|--|--|--|--|
[ResultsBasicUsageFinal.zip](https://github.com/wazuh/wazuh-qa/files/7262031/ResultsBasicUsageFinal.zip)| 2021/09/30| Seyla | 🟢
