### ISSUE TITLE
 FIM Windows Agent - Case: Checks events from existing files

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#1863]
## Description 

FIM tests has a lot of tests to fix because fails inconsistent times.

| Related to | 
|--|
| https://github.com/wazuh/wazuh-qa/issues/1873

### Pipeline parameters

|  Jenkins branch  | QA branch   | 
|- |- |
|  v4.2.1-rc1 |   1873-4.2.1-fim-windows-agent |

## Packages Info

| Type | Format | Architecture | Versión | Revision |  Tag | File name |
|:--:|:--:|:--:|:--:|:--:|:--:|:--:|
| Server | rpm | x86_64 | v4.2.1 | 40214| v4.2.1 | wazuh-manager-4.2.1-0.1873.x86_64.rpm |
| Agent | rpm | x86_64 | v4.2.1 | 40214|v4.2.1| wazuh-agent-4.2.1-0.1873.x86_64.rpm |
| Agent | msi (Windows) | x86_64 | v4.2.1 | 40214| v4.2.1| wazuh-agent-4.2.1-0.1873.msi |
| Agent | pkg (macOS) | x86_64 | v4.2.1 | 40214| v4.2.1| wazuh-agent-4.2.1-0.1873.pkg |
|Agent | p5p (Solaris 11) | x86_64 | v4.2.1 | 40214|v4.2.1| wazuh-agent_v4.2.1-0.1873-sol11-i386.p5p​|
|Agent | p5p (Solaris 10) | x86_64 | v4.2.1 | 40214|v4.2.1| wazuh-agent_v4.2.1-0.1873-sol10-i386.pkg
|Agent | wpk (Linux) | x86_64 | v4.2.1 | 40214| v4.2.1 | wazuh_agent_v4.2.1-0.1873_linux_x86_64.wpk
|Agent | wpk (Windows) | x86_64 | v4.2.1 | 40214|v4.2.1| wazuh_agent_v4.2.1-0.1873_windows.wpk

**Note**: The tag is `v4.2.1` but for now, to create it on jenkins you need to use `v4.2.1-rc1`.

#### Manager
```
syscheck.debug=2
analysisd.debug=2
monitord.rotate_log=0
```

#### Agent
```
agent.debug=2
syscheck.debug=2
monitord.rotate_log=0
```
### Environment 

Provider| Box| OS| CPU| Memory | 
--|--|--|--|--|
Vagrant |  | Windows | 2 | 1024 |

### pytest_args
`-v --tier 0 --tier 1 --tier 2 --fim_mode="realtime" --fim_mode="whodata"`

## Development

Fix `test_fim\test_files\test_basic_usage\test_basic_usage_starting_agent.py` to Windows. 

If the test work successfully after 2 times, you should see if other member could be verify that it woks successfully. 

## Tasks
- [ ] Research about the Test Case.
- [ ] Fix the Test Case.
- [ ] Verify that each execution works successfully. (Full Green - Attach evidence.)
- [ ] Use the [Schema 2.0](https://github.com/wazuh/wazuh-qa/issues/1694) of our Documentation on each test.
- [ ] Verify that cover `scheduled`, `realtime`, and  `whodata`. Research if this case require all args, or only one.
- [ ] Add evidence of time improved. (time previous to improves - Time after to improves applied.)

**Comment by MizugorouZ** [comment]
After having executed the tests for a while, I couldn't replicate the error. These are the results of the `test_fim\test_files\test_basic_usage\test_basic_usage_starting_agent.py` test for Windows, before and after executing a different test to check if that influenced future results. R1 and R2 have been executed with all the combinations of `fim_mode` (`realtime, whodata, scheduled`):
| Test | Date | By | Status | Results |
|:--:|:--:|:--:|:--:|:--:|
| `...starting_agent.py` | 2021/09/16 | @MizugorouZ | :green_circle: | [R1](https://github.com/wazuh/wazuh-qa/files/7178777/R1.zip) |
| `...rename.py` | 2021/09/16 | @MizugorouZ | :green_circle: | [Rename](https://github.com/wazuh/wazuh-qa/files/7178778/Rename.zip) |
| `...starting_agent.py` | 2021/09/16 | @MizugorouZ | :green_circle: | [R2](https://github.com/wazuh/wazuh-qa/files/7178779/R2.zip) |

**Comment by danisan90** [comment]
### Local Results
These are the results of the `test_fim\test_files\test_basic_usage\test_basic_usage_starting_agent.py` test for Windows.It have been executed with all the combinations of `fim_mode` (`realtime, whodata, scheduled`):
| Test | Date | By | Results | Status |
|:--:|:--:|:--:|:--:|:--:|
| `` | | |  |  |
|  |  |  | ) | |
| |  |  |  | |

**Comment by damarisg** [comment]
It is closed because we can't reproduce it.
