### ISSUE TITLE
QA Docs: Migrate `test_active_response` documentation to schema 2.0

### ISSUE THREAD

**Issue by mdengra** [wazuh/wazuh-qa#1870]
# Description

This issue is created to migrate the `test_active_response` documentation to the new QA Docs schema as part of the epic https://github.com/wazuh/wazuh-qa/issues/1796.

In the QA Wiki there are two entries to help complete the tasks:

- [Documenting tests using the QA Docs schema](https://github.com/wazuh/wazuh-qa/wiki/Documenting-tests-using-the-QA-Docs-schema): This entry describes the steps needed to document the tests (schema to use, the position of blocks, allowed values for fields, etc.).
- [Documentation generation with DocGenerator tool](https://github.com/wazuh/wazuh-qa/wiki/Documentation-generation-with-DocGenerator-tool): Here is a brief description of how the `DocGenerator.py` module works to verify that the changes made in the tests have been done correctly.

## Main branch
`1796-migrate-doc-schema-2`

## Tasks
- [x] Migrate tests:
  - [x] **test_analysisd**
    - [x] `test_os_exec.py`
  - [x] **test_execd**
    - [x] `test_execd_firewall_drop.py`
    - [x] `test_execd_restart.py`
- [x] Check `PEP-8` style guide (`pycodestyle --max-line-length=120 --show-source --show-pep8`)
- [x] Merge issue branch to  `1796-migrate-doc-schema-2`

**Comment by mdengra** [comment]
## 2021-09-13
Working branch: `1870-qadocs-migrate-test-active-response`
