### ISSUE TITLE
Full Yellow FIM - Windows Agent 

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#1873]
## Description 

The QA Team has as aim to increase the quality of the test and increase time execution of these.

FIM has a lot of tests to improve.

To start, our focus will be on WINDOWS.

## Development

Fix `tests\integration\test_fim\test_files\test_ambiguous_confs\test_duplicate_entries.py` to Windows. 

If the test work successfully, you should see if it could be refactored to better work. 

The refactor consists in improve the test, but if you think that it requires removing the test and write it again, you can do it.

## Tasks
- [ ] Research about the Test Case.
- [ ] Refactor the Test Case.
- [ ] Verify that each execution works successfully. (Full Green - Attach evidence.)
- [ ] Use the [Schema 2.0](https://github.com/wazuh/wazuh-qa/issues/1694) of our Documentation on each test.
- [ ] Verify that cover `scheduled`, `realtime`, and  `whodata`.
- [ ] Add evidence of time improved. (time previous to improves - Time after to improves applied.)

**Comment by damarisg** [comment]
## Summary

To research if there are new failures locally, we executed by each folder of FIM all tests. This helps to find new fixes to do if required.

### Test Results

| Folder Path | Results |Date | By | Status| Issue Created|
|--|--|--|--|--|--|
test_fim/test_synchronization |[ResultsSynchronization.zip](https://github.com/wazuh/wazuh-qa/files/7251391/ResultsSynchronization.zip) | 2021/09/24 | Andres | 🟢 
test_fim/test_registry | [ResultsRegistry.zip](https://github.com/wazuh/wazuh-qa/files/7251395/ResultsRegistry.zip)  | 2021/09/24 | Andres | 
test_fim/test_files/test_multiple_dirs | [TestMultipleDirs.zip](https://github.com/wazuh/wazuh-qa/files/7251444/TestMultipleDirs.zip)  | 2021/09/28 | Andres | 
test_fim/test_files/test_max_eps | [ResultsMaxEps.zip](https://github.com/wazuh/wazuh-qa/files/7251460/ResultsMaxEps.zip)  | 2021/09/29 | Seyla | 🟢 | 
test_fim/test_files/test_follow_symbolic_link | [ResultsFollowSymbolicLink.zip](https://github.com/wazuh/wazuh-qa/files/7251468/ResultsFollowSymbolicLink.zip)   | 2021/09/29 | Seyla | 🟢 |
