### ISSUE TITLE
Generate packages from wazuh '4.2.1' 

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#1875]
## Description 

To start to work on [FIM - Windows Agent in 4.2.1](https://github.com/wazuh/wazuh-qa/issues/1873) is required to generate some packages.  

When you finish it adds a Link of every package created like a comment in this issue and also adds this information on the `Package Information` section on [FIM - Windows Agent in 4.2.1](https://github.com/wazuh/wazuh-qa/issues/1873).

|Related issue|
|---|
|#1873  |

## Packages Info

| Type | Format | Architecture | Versión | Revision |  Tag | File name |
|:--:|:--:|:--:|:--:|:--:|:--:|:--:|
| Server | rpm | x86_64 | v4.2.1 | 40214| v4.2.1 | wazuh-manager-4.2.1-0.1873.x86_64.rpm |
| Agent | rpm | x86_64 | v4.2.1 | 40214|v4.2.1| wazuh-agent-4.2.1-0.1873.x86_64.rpm |
| Agent | msi (Windows) | x86_64 | v4.2.1 | 40214| v4.2.1| wazuh-agent-4.2.1-0.1873.msi |
| Agent | pkg (macOS) | x86_64 | v4.2.1 | 40214| v4.2.1| wazuh-agent-4.2.1-0.1873.pkg |
|Agent | p5p (Solaris 11) | x86_64 | v4.2.1 | 40214|v4.2.1| wazuh-agent_v4.2.1-0.1873-sol11-i386.p5p​|
|Agent | p5p (Solaris 10) | x86_64 | v4.2.1 | 40214|v4.2.1| wazuh-agent_v4.2.1-0.1873-sol10-i386.pkg
|Agent | wpk (Linux) | x86_64 | v4.2.1 | 40214| v4.2.1 | wazuh_agent_v4.2.1-0.1873_linux_x86_64.wpk
|Agent | wpk (Windows) | x86_64 | v4.2.1 | 40214|v4.2.1| wazuh_agent_v4.2.1-0.1873_windows.wpk

Note: The tag is `v4.2.1` but for now, to create it on jenkins you need to use `v4.2.1-rc1`.

## Tasks 

**Manager**

- [x] Generate rpm package.

**Agents**

- [x] Generate rpm package.
- [x] Generate msi package.
- [x] Generate wpk package for Windows.
- [x] Generate wpk package for Linux.
- [x] Generate package for macOS.
- [x] Generate package for Solaris 11
- [x] Generate package for Solaris 10
