### ISSUE TITLE
qa-docs: Automatize SearchUI dependencies installation

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh-qa#1877]
## Description
Task from #1864.

Currently, when you want to run SearchUI using `qa-docs -I tests_dir_path -l index_name`, you need to do a previous dependencies installation via `npm install`.

We need to automatize that installation, so the user doesn't need to worry about dependencies.

We have two installation options:
- Via framework `setup.py`
- When you run SearchUI, check that `node_modules/` exists. If not, install the dependencies

## Branch
[1877-deps-installation](https://github.com/wazuh/wazuh-qa/tree/1877-deps-installation)

## Tasks
- [x] Check that `node_modules/` exists before launching `SearchUI`
- [x] Install the dependencies if it is necessary
- [x] merge `1877-deps-installation` to `1864-qa-docs-fixes`
