### ISSUE TITLE
qa-docs: Migrate logger and improve logging

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh-qa#1879]
### Description:

We want to fix and improve the logging in QADOCS. Now we have more than one module for logging warnings, for example. 

In #1876 `qadocs_logger` has been included. Now we need to use it properly. Now only this logger will be used to register the logging.

### Branch
1879-qadocs-logging

### Tasks:

- [x] Migrate from old logger to qadocs_logger
    - [x] `qa-docs` script
    - [x] `doc_generator` module
    - [x] `code_parser` module 
    - [x] `config` module
    - [x] `index_data` module
    - [x] `pytest_wrap` module
    - [x] `sanity` module
    - [x] `utils` module
- [x] Remove log messages generated by the warnings module
- [x] Fix logging: both standard and log file working

**Comment by roronoasins** [comment]
Sample output when debug mode is enabled and only config file is loaded.

```
(docgen) luisgr@luisgr-pc:~/work/wazuh-qa/deps/wazuh_testing$ qa-docs -d -I /home/luisgr/work/wazuh-qa/tests/ -t
2021-09-15 12:30:10,190 - DEBUG - Validating input parameters
2021-09-15 12:30:10,191 - DEBUG - Input parameters validation successfully finished
2021-09-15 12:30:10,191 - DEBUG - Loading qa-docs configuration
2021-09-15 12:30:10,191 - DEBUG - Loading config file
2021-09-15 12:30:10,194 - DEBUG - Reading the regular expressions to include test methods from config file
2021-09-15 12:30:10,194 - DEBUG - Reading mandatory and optional module fields from config file
2021-09-15 12:30:10,194 - DEBUG - Reading mandatory and optional test fields from config file
2021-09-15 12:30:10,194 - DEBUG - Reading Test Case key from config file
2021-09-15 12:30:10,194 - DEBUG - Reading include paths from config file
2021-09-15 12:30:10,194 - DEBUG - Reading the regular expressions to include files from config file
2021-09-15 12:30:10,194 - DEBUG - Reading group files from config file
2021-09-15 12:30:10,194 - DEBUG - Reading the paths to be ignored from config file
2021-09-15 12:30:10,194 - DEBUG - Setting the path documentation
2021-09-15 12:30:10,194 - DEBUG - qa-docs configuration loaded
```
