### ISSUE TITLE
FIM Windows Agent - Case: Check that FIM sleeps when the option max_files_per_second is enabled

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#1883]
## Description 

FIM tests has a lot of tests to fix because fails inconsistent times.

| Related to | 
|--|
| https://github.com/wazuh/wazuh-qa/issues/1873

### Pipeline parameters

|  Jenkins branch  | QA branch   | 
|- |- |
|  v4.2.1-rc1 |   1873-4.2.1-fim-windows-agent |

## Packages Info

| Type | Format | Architecture | Versión | Revision |  Tag | File name |
|:--:|:--:|:--:|:--:|:--:|:--:|:--:|
| Server | rpm | x86_64 | v4.2.1 | 40214| v4.2.1 | wazuh-manager-4.2.1-0.1873.x86_64.rpm |
| Agent | rpm | x86_64 | v4.2.1 | 40214|v4.2.1| wazuh-agent-4.2.1-0.1873.x86_64.rpm |
| Agent | msi (Windows) | x86_64 | v4.2.1 | 40214| v4.2.1| wazuh-agent-4.2.1-0.1873.msi |
| Agent | pkg (macOS) | x86_64 | v4.2.1 | 40214| v4.2.1| wazuh-agent-4.2.1-0.1873.pkg |
|Agent | p5p (Solaris 11) | x86_64 | v4.2.1 | 40214|v4.2.1| wazuh-agent_v4.2.1-0.1873-sol11-i386.p5p​|
|Agent | p5p (Solaris 10) | x86_64 | v4.2.1 | 40214|v4.2.1| wazuh-agent_v4.2.1-0.1873-sol10-i386.pkg
|Agent | wpk (Linux) | x86_64 | v4.2.1 | 40214| v4.2.1 | wazuh_agent_v4.2.1-0.1873_linux_x86_64.wpk
|Agent | wpk (Windows) | x86_64 | v4.2.1 | 40214|v4.2.1| wazuh_agent_v4.2.1-0.1873_windows.wpk

**Note**: The tag is `v4.2.1` but for now, to create it on jenkins you need to use `v4.2.1-rc1`.

#### Manager
```
syscheck.debug=2
analysisd.debug=2
monitord.rotate_log=0
```

#### Agent
```
agent.debug=2
syscheck.debug=2
monitord.rotate_log=0
```

### Environment 

Provider| Box| OS| CPU| Memory | 
--|--|--|--|--|
Vagrant |  | Windows | 2 | 1024 |

### pytest_args
`-v --tier 0 --tier 1 --tier 2 --fim_mode="realtime" --fim_mode="whodata"`

## Development

Fix `test_fim\test_files\test_max_files_per_second\test_max_files_per_second.py` to Windows. 

If the test work successfully after 2 times, you should see if other member could be verify that it woks successfully. 

## Tasks
- [x] Research about the Test Case.
- [x] Fix the Test Case.
- [x] Verify that each execution works successfully. (Full Green - Attach evidence.)
- [x] Use the [Schema 2.0](https://github.com/wazuh/wazuh-qa/issues/1694) of our Documentation on each test.
- [x] Verify that cover `scheduled`, `realtime`, and  `whodata`. Research if this case require all args, or only one.

**Comment by Deblintrake09** [comment]
### Test Results 
| Results | Status| Date | By 
|--|--|--|--|
| [ResultsMaxFPS.zip](https://github.com/wazuh/wazuh-qa/files/7205198/ResultsMaxFPS.zip) | :green_circle: | 2021/09/21 | @Deblintrake09 |
| [ResultsMaxFPS2.zip](https://github.com/wazuh/wazuh-qa/files/7205200/ResultsMaxFPS2.zip) | :green_circle: | 2021/09/21 | @Deblintrake09 |
| [ResultsMaxFPS3.zip](https://github.com/wazuh/wazuh-qa/files/7205201/ResultsMaxFPS3.zip) | :green_circle: | 2021/09/21 | @Deblintrake09 |

Started applying Schema 2.0 to test documentation

**Comment by damarisg** [comment]
Closed by #1934
