### ISSUE TITLE
FIM Windows Agent - Case: Multiple Directories

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#1885]
## Description 

FIM tests have many flaws inconsistently. So our goal is to achieve consistent behavior.
The results are attached.

| Folder Path | Results |Date | By | Status| 
|--|--|--|--|--|
test_fim/test_files/test_multiple_dirs | [TestMultipleDirs.zip](https://github.com/wazuh/wazuh-qa/files/7251444/TestMultipleDirs.zip)  | 2021/09/28 | Andres |  🔴 

| Related to | 
|--|
| https://github.com/wazuh/wazuh-qa/issues/1873

### Pipeline parameters

|  Jenkins branch  | QA branch   | 
|- |- |
|  v4.2.1-rc1 |   1873-4.2.1-fim-windows-agent |

## Packages Info

| Type | Format | Architecture | Versión | Revision |  Tag | File name |
|:--:|:--:|:--:|:--:|:--:|:--:|:--:|
| Server | rpm | x86_64 | v4.2.1 | 40214| v4.2.1 | wazuh-manager-4.2.1-0.1873.x86_64.rpm |
| Agent | rpm | x86_64 | v4.2.1 | 40214|v4.2.1| wazuh-agent-4.2.1-0.1873.x86_64.rpm |
| Agent | msi (Windows) | x86_64 | v4.2.1 | 40214| v4.2.1| wazuh-agent-4.2.1-0.1873.msi |
| Agent | pkg (macOS) | x86_64 | v4.2.1 | 40214| v4.2.1| wazuh-agent-4.2.1-0.1873.pkg |
|Agent | p5p (Solaris 11) | x86_64 | v4.2.1 | 40214|v4.2.1| wazuh-agent_v4.2.1-0.1873-sol11-i386.p5p​|
|Agent | p5p (Solaris 10) | x86_64 | v4.2.1 | 40214|v4.2.1| wazuh-agent_v4.2.1-0.1873-sol10-i386.pkg
|Agent | wpk (Linux) | x86_64 | v4.2.1 | 40214| v4.2.1 | wazuh_agent_v4.2.1-0.1873_linux_x86_64.wpk
|Agent | wpk (Windows) | x86_64 | v4.2.1 | 40214|v4.2.1| wazuh_agent_v4.2.1-0.1873_windows.wpk

**Note**: The tag is `v4.2.1` but for now, to create it on jenkins you need to use `v4.2.1-rc1`.

#### Manager
```
syscheck.debug=2
analysisd.debug=2
monitord.rotate_log=0
```

#### Agent
```
agent.debug=2
syscheck.debug=2
monitord.rotate_log=0
windows.debug=2
```

### Environment 

Provider| Box| OS| CPU| Memory | 
--|--|--|--|--|
Vagrant | "gusztavvargadr/windows-10" | Windows | 2 | 2048 |

### pytest_args
`-v --tier 0 --tier 1 --tier 2 --fim_mode="realtime" --fim_mode="whodata"`

## Development

Fix `test_fim/test_files/test_multiple_dirs` to Windows. 

If the test work successfully after 2 times, you should see if other member could be verify that it woks successfully. 

## Tasks
- [x] Research about the Test Case.
- [ ] Fix the Test Case.
- [x] Verify that each execution works successfully. (Full Green - Attach evidence.)
- [ ] Verify that cover `scheduled`, `realtime`, and  `whodata`. Research if this case require all args, or only one.

**Comment by Deblintrake09** [comment]
### Local Test Results

Tests were run locally from a clean VM. Using all three FIM modes.

| Result | Status | Date | By |
|--|--|--|--|
| [ResultMultipleDirs.zip](https://github.com/wazuh/wazuh-qa/files/7259713/ResultMultipleDirs.zip) | :green_circle: | 2021/09/30 | @Deblintrake09 |
| [ResultMultipleDirs2.zip](https://github.com/wazuh/wazuh-qa/files/7259714/ResultMultipleDirs2.zip) | :green_circle: | 2021/09/30 | @Deblintrake09 |
| [ResultMultipleDirs3.zip](https://github.com/wazuh/wazuh-qa/files/7259715/ResultMultipleDirs3.zip) | :green_circle: | 2021/09/30 | @Deblintrake09 |

**Comment by MizugorouZ** [comment]
These are the results of `test_fim/test_files/test_multiple_dirs`
| Results | Date | By | Status |
|:--:|:--:|:--:|:--:|
| [ResultsMultipleDirs_1](https://github.com/wazuh/wazuh-qa/files/7261149/ResultsMultipleDirs_1.zip) | 2021/09/30 | @MizugorouZ | :green_circle: |
| [ResultsMultipleDirs_2](https://github.com/wazuh/wazuh-qa/files/7261154/ResultsMultipleDirs_2.zip) | 2021/09/30 | @MizugorouZ | :green_circle: |
| [ResultsMultipleDirs_3](https://github.com/wazuh/wazuh-qa/files/7261159/ResultsMultipleDirs_3.zip) | 2021/09/30 | @MizugorouZ | :green_circle: |

**Comment by damarisg** [comment]
Closed because we can't reproduce it.
