### ISSUE TITLE
WPK tests - Failed because 'count_file_lines' method was removed on 4.2

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#1898]
# Description
A lot of merges were applied in 4.2, and this led to some issues.

Working in [Analysis: Integration tests for 4.2.2-rc1](https://github.com/wazuh/wazuh-qa/issues/1880) was detected that WPK did not work, after investigating it was found that the applied changes were removed by another PR.

This caused the test to fail because the 'count_file_lines' method was not found.

Details of branch after to apply merged with package used it. 

| Wazuh QA: Branch | Wazuh QA: Commit | Wazuh: Tag | Wazuh: Commit |
|:--:|:--:|:--:|:--:|
| 4.2 | https://github.com/wazuh/wazuh-qa/commit/c6981d83a644cd9fe9b2644680ae26e4bd5ea217 |v4.2.2-rc1 |https://github.com/wazuh/wazuh/commit/411389188f449c3e7a2d97ff059c25035d32f38a |

| Type | Format | Architecture | Versión | Revision |  Tag | File name |
|:--:|:--:|:--:|:--:|:--:|:--:|:--:|
| Server | rpm | x86_64 | v4.2.2 |40215| v4.2.2-rc1 | wazuh-manager-4.2.2-1.x86_64.rpm |
| Agent | rpm | x86_64 | v4.2.2 | 40215| v4.2.2-rc1 | wazuh-agent-4.2.2-1.x86_64.rpm |
| Agent | msi (Windows) | x86_64 | v4.2.2 |40215| v4.2.2-rc1 | wazuh-agent-4.2.2-1.msi|

We are going to check that after to add this method all wpk tests work successfully. 

### local_internal_options.conf

<table>
 <tr>
  <td rowspan="2">WPK</td>
  <td>(Manager, Agent) - Linux</td>
  <td>wazuh_modules.debug=2</td>
    <td>--wpk_version=v4.x.x</td>
 </tr>
  <td>Agent - Windows</td>
  <td>windows.debug=2</td>
  <td>--wpk_version=v4.x.x</td>
 </tr>

</table>

### Environment 

Provider| Box| OS| CPU| Memory | 
--|--|--|--|--|
Vagrant |  | Windows | 2 | 1024 |
Vagrant | centos/8 | CentOS 8 | 2 | 1024 |

## Tasks
- [x] Research about possible method removed.
- [x] Fix the Test Cases.
- [ ] Verify that each execution works successfully on `4.2.2`. (Full Green - Attach evidence.)

**Comment by damarisg** [comment]
## Update 2021/09/20

While researching about it. I detected methods deleted. Also that the test failed because some paths were hardcoded. 

I fixed these problems, but I'm continuing research because there are other failures related to `memory error to allocate` error, these tests use the agent simulator.

I'm working on `1898-wpk-fixed-and-new-args-for-the-execution` branch.

**Comment by danisan90** [comment]
### test_wpk
These are the results of the execution of `test_wpk` in the branch `1898-wpk-fixed-and-new-args-for-the-execution` in Linux.
|Trype| Results | Date | By | Status |
|:--:|:--:|:--:|:--:|:--:|
|Manager|[ResutsWpk1](https://github.com/wazuh/wazuh-qa/files/7226099/ResutsWpk1.log)| 2021/09/23| @danisan90 | 🟢
|Manager| [ResutsWpk2](https://github.com/wazuh/wazuh-qa/files/7226154/ResutsWpk2.log)| 2021/09/24| @danisan90 | 🟢 
|Manager|[ResutsWpk3](https://github.com/wazuh/wazuh-qa/files/7226139/ResutsWpk3.log)| 2021/09/24| @danisan90 | 🟢 |
|Agent|[ResutsWpkAgent](https://github.com/wazuh/wazuh-qa/files/7226161/ResutsWpkAgent.log)| 2021/09/24| @danisan90 | 🟢 |

**Comment by snaow** [comment]
Closed by https://github.com/wazuh/wazuh-qa/pull/1928

GJ.
