### ISSUE TITLE
qa-docs: Update all modules documentation and style.

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh-qa#1899]
## Description
A task from #1864. Since qa-docs has been modified and is not documented at all, we need that anyone could understand each module's behaviour.

Also, only the script `qa_docs.py` satisfies `pycodestyle --max-line-length=120 --show-source --show-pep8`. That needs to be fixed.

All module files must pass the following command:
`pycodestyle --max-line-length=120 --show-source --show-pep8 file.py`

And documentation must follow [Google](https://google.github.io/styleguide/pyguide.html#244-decision) python style standards.

## Working branch:
`1899-qa-docs-doc`

## Tasks:
- [x] Fix style in:
    - [x] `coder_parser.py`
    - [x] `config.py`
    - [x] `index_data.py`
    - [x] `pytest_wrap.py`
    - [x] `sanity.py`
    - [x] `utils.py`
    - [x] `doc_generator.py`
 - [x] Create/Update documentation in:
    - [x] `qa_docs.py`
    - [x] `coder_parser.py`
    - [x] `config.py`
    - [x] `index_data.py`
    - [x] `pytest_wrap.py`
    - [x] `sanity.py`
    - [x] `utils.py`
    - [x] `doc_generator.py`
- [x] Merge `1899-qa-docs-doc` into `1864-qa-docs-fixes`
