### ISSUE TITLE
qa-docs: Migrate `test_fim/test_files/test_ambiguous_confs` documentation to schema 2.0

### ISSUE THREAD

**Issue by mdengra** [wazuh/wazuh-qa#1914]
### Description

This issue is created to migrate the `test_fim/test_files/test_ambiguous_confs` documentation to the new **qa-docs** schema as part of the issue #1810 and the epic https://github.com/wazuh/wazuh-qa/issues/1796.

In the QA Wiki there are two entries to help complete the tasks:

- [Documenting tests using the qa-docs schema](https://github.com/wazuh/wazuh-qa/wiki/Documenting-tests-using-the-qadocs-schema): This entry describes the steps needed to document the tests (schema to use, the position of blocks, allowed values for fields, etc.).
- [Documentation generation with qa-docs tool](https://github.com/wazuh/wazuh-qa/wiki/Documentation-generation-with-qadocs-tool): Here is a brief description of how the `DocGenerator.py` module works to verify that the changes made in the tests have been done correctly.

## Main branch
`1810-qadocs-migrate-test-fim`

#### Tasks
- [x] Migrate tests:
  - [x] **test_files**
    - [x] **test_ambiguous_confs**
      - [x] `test_ambiguous_complex.py` (**Create new documentation**)
      - [x] `test_ambiguous_simple.py` (**Create new documentation**)
      - [x] `test_ambiguous_whodata_thread.py` (**Create new documentation**)
      - [x] `test_duplicate_entries.py` (**Create new documentation**)
      - [x] `test_ignore_works_over_restrict.py` (**Create new documentation**)
      - [x] `test_whodata_prevails_over_realtime.py` (**Create new documentation**)
- [x] Check `PEP-8` style guide (`pycodestyle --max-line-length=120`)
- [x] Merge issue branch to  `1810-qadocs-migrate-test-fim`

**Comment by mdengra** [comment]
## 2021-09-22

Working branch: `1914-qadocs-migrate-test-fim-ambiguous-confs`
