### ISSUE TITLE
Unify the `qa-ctl` loggers and manage it from the` qa-ctl` script parameters

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#1916]
Until now, `qa-ctl` has two loggers. One for the script itself and one for the modules used for the deployment, provisioning, and execution of the tests.

It is requested to define a global logger and that its level can be determined from a parameter of the `qa-ctl` script.

## Tasks

- [x] Define global logger
- [x] Unify loggers
- [x] Add new script parameter to handle the logging level
- [x] Test new changes
