### ISSUE TITLE
qa-docs: Migrate `test_fim/test_files/test_audit` documentation to schema 2.0

### ISSUE THREAD

**Issue by mdengra** [wazuh/wazuh-qa#1918]
### Description

This issue is created to migrate the `test_fim/test_files/test_audit` documentation to the new **qa-docs** schema as part of the issue #1810 and the epic https://github.com/wazuh/wazuh-qa/issues/1796.

In the QA Wiki there are two entries to help complete the tasks:

- [Documenting tests using the qa-docs schema](https://github.com/wazuh/wazuh-qa/wiki/Documenting-tests-using-the-qadocs-schema): This entry describes the steps needed to document the tests (schema to use, the position of blocks, allowed values for fields, etc.).
- [Documentation generation with qa-docs tool](https://github.com/wazuh/wazuh-qa/wiki/Documentation-generation-with-qadocs-tool): Here is a brief description of how the `DocGenerator.py` module works to verify that the changes made in the tests have been done correctly.

## Main branch
`1810-qadocs-migrate-test-fim`

#### Tasks
- [x] Migrate tests:
  - [x] **test_files**
    - [x] **test_audit**
      - [x] `test_audit_after_initial_scan.py`
      - [x] `test_audit_no_dir.py`
      - [x] `test_audit.py`
      - [x] `test_remove_audit.py`
      - [x] `test_remove_rule_five_times.py`
- [x] Check `PEP-8` style guide (`pycodestyle --max-line-length=120`)
- [x] Merge issue branch to  `1810-qadocs-migrate-test-fim`

**Comment by mdengra** [comment]
## 2021-09-22

Working branch: `1918-qadocs-migrate-test-fim-audit`
