### ISSUE TITLE
qa-docs: Migrate `test_fim/test_files/test_basic_usage` documentation to schema 2.0

### ISSUE THREAD

**Issue by mdengra** [wazuh/wazuh-qa#1927]
### Description

This issue is created to migrate the `test_fim/test_files/test_basic_usage` documentation to the new **qa-docs** schema as part of the issue #1810 and the epic https://github.com/wazuh/wazuh-qa/issues/1796.

In the QA Wiki there are two entries to help complete the tasks:

- [Documenting tests using the qa-docs schema](https://github.com/wazuh/wazuh-qa/wiki/Documenting-tests-using-the-qadocs-schema): This entry describes the steps needed to document the tests (schema to use, the position of blocks, allowed values for fields, etc.).
- [Documentation generation with qa-docs tool](https://github.com/wazuh/wazuh-qa/wiki/Documentation-generation-with-qadocs-tool): Here is a brief description of how the `DocGenerator.py` module works to verify that the changes made in the tests have been done correctly.

## Main branch
`1810-qadocs-migrate-test-fim`

#### Tasks
- [x] Migrate tests:
  - [x] **test_files**
    - [x] **test_basic_usage**
      - [x] `test_basic_usage_baseline_generation.py` (**Create new documentation**)
      - [x] `test_basic_usage_changes.py` (**Create new documentation**)
      - [x] `test_basic_usage_create_after_delete_dir.py` (**Create new documentation**)
      - [x] `test_basic_usage_create_rt_wd.py` (**Create new documentation**)
      - [x] `test_basic_usage_create_scheduled.py` (**Create new documentation**)
      - [x] `test_basic_usage_db_inode_check.py`
      - [x] `test_basic_usage_delete_folder.py` (**Create new documentation**)
      - [x] `test_basic_usage_dir_with_commas.py` (**Create new documentation**)
      - [x] `test_basic_usage_disabled.py` (**Create new documentation**)
      - [x] `test_basic_usage_entries_match_path_count.py` (**Create new documentation**)
      - [x] `test_basic_usage_move_dir.py` (**Create new documentation**)
      - [x] `test_basic_usage_move_file.py` (**Create new documentation**)
      - [x] `test_basic_usage_new_dirs.py` (**Create new documentation**)
      - [x] `test_basic_usage_no_dir.py` (**Create new documentation**)
      - [x] `test_basic_usage_quick_changes.py` (**Create new documentation**)
      - [x] `test_basic_usage_rename.py` (**Create new documentation**)
      - [x] `test_basic_usage_starting_agent.py` (**Create new documentation**)
      - [x] `test_basic_usage_wildcards.py`
      - [x] `test_basic_usage_wildcards_runtime.py`
- [x] Check `PEP-8` style guide (`pycodestyle --max-line-length=120`)
- [x] Merge issue branch to  `1810-qadocs-migrate-test-fim`

**Comment by mdengra** [comment]
## 2021-09-23

Working branch: `1927-qadocs-migrate-test-fim-basic-usage`
