### ISSUE TITLE
Design and develop a test that analyzes the logs and indicates if there is any unexpected behavior

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh-qa#1940]
In this issue, we are looking to develop a test that, having as input the cluster log, is able to determine when there is an unexpected behavior. This could be, for example, two or more simultaneous integrity sync tasks, as we can see in the following log:

```
2021/09/23 14:54:56 DEBUG: [Worker CLUSTER-Workload_benchmarks_metrics_B55_manager_19] [Main] Command received: b'str_upd'
2021/09/23 14:54:57 DEBUG: [Worker CLUSTER-Workload_benchmarks_metrics_B55_manager_19] [Main] Command received: b'syn_a_w_m'
2021/09/23 14:54:58 INFO: [Worker CLUSTER-Workload_benchmarks_metrics_B55_manager_19] [Agent-info sync] Starting
2021/09/23 14:54:58 DEBUG: [Worker CLUSTER-Workload_benchmarks_metrics_B55_manager_19] [Agent-info sync] All chunks updated in wazuh-db in 0.073404s.
2021/09/23 14:55:00 DEBUG: [Worker CLUSTER-Workload_benchmarks_metrics_B55_manager_19] [Main] Command received: b'syn_i_w_m_p'
2021/09/23 14:55:00 INFO: [Worker CLUSTER-Workload_benchmarks_metrics_B55_manager_19] [Agent-info sync] Finished in 2.476s (23 chunks updated).
2021/09/23 14:55:03 INFO: [Worker CLUSTER-Workload_benchmarks_metrics_B55_manager_19] [Integrity sync] Finished in 179.970s.      <-------
2021/09/23 14:55:07 INFO: [Worker CLUSTER-Workload_benchmarks_metrics_B55_manager_19] [Integrity sync] Finished in 184.673s.      <-------
2021/09/23 14:55:07 DEBUG: [Worker CLUSTER-Workload_benchmarks_metrics_B55_manager_19] [Main] Command received: b'syn_a_w_m_p'
2021/09/23 14:55:09 DEBUG: [Worker CLUSTER-Workload_benchmarks_metrics_B55_manager_19] [Main] Command received: b'new_str'
2021/09/23 14:55:11 DEBUG: [Worker CLUSTER-Workload_benchmarks_metrics_B55_manager_19] [Main] Command received: b'str_upd'
2021/09/23 14:55:11 DEBUG: [Worker CLUSTER-Workload_benchmarks_metrics_B55_manager_19] [Main] Command received: b'syn_i_w_m_p'
2021/09/23 14:55:12 DEBUG: [Worker CLUSTER-Workload_benchmarks_metrics_B55_manager_19] [Main] Command received: b'syn_a_w_m'
2021/09/23 14:55:12 DEBUG: [Worker CLUSTER-Workload_benchmarks_metrics_B55_manager_19] [Main] Command received: b'syn_i_w_m'
2021/09/23 14:55:13 INFO: [Worker CLUSTER-Workload_benchmarks_metrics_B55_manager_19] [Agent-info sync] Starting
2021/09/23 14:55:13 DEBUG: [Worker CLUSTER-Workload_benchmarks_metrics_B55_manager_19] [Agent-info sync] All chunks updated in wazuh-db in 0.075327s.
2021/09/23 14:55:13 DEBUG: [Worker CLUSTER-Workload_benchmarks_metrics_B55_manager_19] [Integrity check] Waiting to receive zip file from worker.
2021/09/23 14:55:15 DEBUG: [Worker CLUSTER-Workload_benchmarks_metrics_B55_manager_19] [Main] Command received: b'new_file'
2021/09/23 14:55:17 INFO: [Worker CLUSTER-Workload_benchmarks_metrics_B55_manager_19] [Agent-info sync] Finished in 4.041s (23 chunks updated).
2021/09/23 14:55:28 INFO: [Worker CLUSTER-Workload_benchmarks_metrics_B55_manager_19] [Integrity sync] Finished in 205.112s.      <-------
2021/09/23 14:55:36 DEBUG: [Worker CLUSTER-Workload_benchmarks_metrics_B55_manager_19] [Main] Command received: b'file_upd'
```

### Tasks

- [x] Investigate several logs of different builds.
- [x] Establish all the cases in which the test should fail.
- [x] Develop the test.
- [x] Check that it works correctly with several logs, both ,legitimate and modified logs.

**Comment by Selutario** [comment]
## Issue update

### Logs order test
The cluster `logs order` test is finished and it is working correctly. Now, if there is any log being printed when it shouldn't, the test would fail as below:
```
python3 -m pytest test_cluster_logs_order.py --artifacts_path='/home/selu/Descargas/cluster_performance/59' --html=report.html --self-contained-html
============================================================================================ test session starts ============================================================================================
platform linux -- Python 3.8.10, pytest-5.0.0, py-1.8.2, pluggy-0.13.1
rootdir: /home/selu/Git/wazuh-qa/tests/performance/test_cluster/test_cluster_logs
plugins: metadata-1.10.0, html-3.1.1, testinfra-5.0.0, tavern-1.2.2, pep8-1.0.6, cov-2.10.0, asyncio-0.14.0
collected 1 item                                                                                                                                                                                            

test_cluster_logs_order.py F                                                                                                                                                                          [100%]

================================================================================================= FAILURES ==================================================================================================
_______________________________________________________________________________________ test_check_logs_order_workers _______________________________________________________________________________________

artifacts_path = '/home/selu/Descargas/cluster_performance/59'

    def test_check_logs_order_workers(artifacts_path):
        """Check that cluster logs appear in the expected order.
    
        Check that for each group of logs (agent-info, integrity-check, etc), each message
        appears in the order it should. If any log is duplicated, skipped, etc. the test will fail.
    
        Args:
            artifacts_path (str): Path where folders with cluster information can be found.
        """
        if not artifacts_path:
            pytest.fail('Parameter "--artifacts_path=<path>" is required.')
    
        if len(cluster_log_files := glob(join(artifacts_path, 'worker_*', 'logs', 'cluster.log'))) == 0:
            pytest.fail(f'No files found inside {artifacts_path}.')
    
        for log_file in cluster_log_files:
            with open(log_file) as file:
                for line in file.readlines():
                    if result := logs_format.search(line):
                        if result.group(1) in logs_order:
                            for child in logs_order[result.group(1)].get_children():
                                if re.search(str(child), result.group(2)):
                                    # Status of the logs_order is updated so it points to the next expected log.
                                    logs_order[result.group(1)] = child if not child.is_leaf() else child.get_root()
                                    break
                            else:
                                # Log can be different to the expected one only if permission was not granted.
                                if "Master didn't grant permission to start a new" not in result.group(2):
                                    incorrect_order.append({
                                        'node': node_name.search(log_file)[1],
                                        'log_type': result.group(1),
                                        'found_log': result.group(0),
                                        'expected_logs': [str(log) for log in logs_order[result.group(1)].get_children()]
                                    })
                                    break
    
            # Update status of all logs so they point to their tree root.
            logs_order.update({log_type: tree.get_root() for log_type, tree in logs_order.items()})
    
>       assert not incorrect_order, '\n\n'.join('{node}:\n'
                                                ' - Log type: {log_type}\n'
                                                ' - Expected logs: {expected_logs}\n'
                                                ' - Found log: {found_log}'.format(**item) for item in incorrect_order)
E       AssertionError: worker_4:
E          - Log type: Agent-info sync
E          - Expected logs: ['Permission to synchronize granted.*']
E          - Found log: 2021/09/29 12:05:57 INFO: [Worker CLUSTER-Workload_benchmarks_metrics_B59_manager_4] [Agent-info sync] Finished in 6.936s (67 chunks updated).
E       assert not [{'expected_logs': ['Permission to synchronize granted.*'], 'found_log': '2021/09/29 12:05:57 INFO: [Worker CLUSTER-Wo...ager_4] [Agent-info sync] Finished in 6.936s (67 chunks updated).', 'log_type': 'Agent-info sync', 'node': 'worker_4'}]

test_cluster_logs_order.py:193: AssertionError
--------------------------------------------- generated html file: file:///home/selu/Git/wazuh-qa/tests/performance/test_cluster/test_cluster_logs/report.html ----------------------------------------------
========================================================================================= 1 failed in 0.20 seconds ==========================================================================================
```

The logs of all workers are analyzed before marking the test as failed. This information is displayed in an HTML report if option `--html=report.html` is used:
![image](https://user-images.githubusercontent.com/23361101/139860273-8ffe1121-eb46-44ea-be16-99dbe3ec7f01.png)

### Correct sync test
I have also finished the development of the integrity sync test (docstrings and some similar details still need to be added). This test looks for the following line in the cluster.log of all workers:
```
Files to create: N | Files to update: N | Files to delete: N | Files to send: N
```

If that line contains the same values multiple times in a row for a worker, it is considered that there may be some problem in the synchronization (for example, modulesd is deleting files when it receives them) and the test is marked as failed.

## Common HTML report
All these tests generate a common HTML report with the results of each one.
![image](https://user-images.githubusercontent.com/23361101/139861888-122cc100-755b-4421-8159-158229528c36.png)

In addition, some of them may contain extra information/details as we have already mentioned in previous issues updates:
![image](https://user-images.githubusercontent.com/23361101/139862019-8f074216-284e-419e-a308-eb2f6d8212a3.png)

**Comment by Selutario** [comment]
## Issue update

The [test_cluster_sync](https://github.com/wazuh/wazuh-qa/tree/1940-cluster-logs-tests/tests/performance/test_cluster/test_cluster_logs/test_cluster_sync) is a bit tricky since it can mark some logs as errors o problematic, even if they are ok. 

In short, this test checks that the cluster sync log is not identical multiple times in a row. However, it doesn't mean that there is an error in the synchronization. For example, in an environment where agents are registered (not connected), only the `client.keys` will be synchronized, but it can do it multiple times in a row. The same happens with agent-groups files, which are merged into a single one even though it contains information to create many files.
```
2021/11/18 11:21:55 INFO: [Worker CLUSTER-Workload_benchmarks_metrics_B107_manager_2] [Integrity sync] Files to create: 0 | Files to update: 1 | Files to delete: 0 | Files to send: 0
...
2021/11/18 11:22:03 INFO: [Worker CLUSTER-Workload_benchmarks_metrics_B107_manager_2] [Integrity sync] Files to create: 0 | Files to update: 1 | Files to delete: 0 | Files to send: 0
...
2021/11/18 11:22:20 INFO: [Worker CLUSTER-Workload_benchmarks_metrics_B107_manager_2] [Integrity sync] Files to create: 0 | Files to update: 1 | Files to delete: 0 | Files to send: 0
```

This problem could happen not only with the `client.keys` or agent-groups. For example, it may happen that the same number of missing files are created in a worker during multiple sync iterations. To review if this is due to a coincidence or because there is a real error that causes the files not to be synchronized, we could compare the number of files obtained during `Integrity check`:
```
[Integrity check] Compressing 'files_metadata.json' of 35647 files.
```

If (for example) the same number of missing files are synced multiple times in a row but the amount of MD5 calculated has changed between each iteration, it could be inferred that the synchronization was indeed successful:
```
2021/11/18 11:21:55 INFO: [Worker CLUSTER-Workload_benchmarks_metrics_B107_manager_2] [Integrity sync] Files to create: 0 | Files to update: 1 | Files to delete: 0 | Files to send: 0
2021/11/18 11:22:01 DEBUG: [Worker CLUSTER-Workload_benchmarks_metrics_B107_manager_2] [Integrity check] Compressing 'files_metadata.json' of 35647 files.
...
2021/11/18 11:22:03 INFO: [Worker CLUSTER-Workload_benchmarks_metrics_B107_manager_2] [Integrity sync] Files to create: 0 | Files to update: 1 | Files to delete: 0 | Files to send: 0
2021/11/18 11:22:12 DEBUG: [Worker CLUSTER-Workload_benchmarks_metrics_B107_manager_2] [Integrity check] Compressing 'files_metadata.json' of 35704 files.
...
2021/11/18 11:22:20 INFO: [Worker CLUSTER-Workload_benchmarks_metrics_B107_manager_2] [Integrity sync] Files to create: 0 | Files to update: 1 | Files to delete: 0 | Files to send: 0
2021/11/18 11:22:27 DEBUG: [Worker CLUSTER-Workload_benchmarks_metrics_B107_manager_2] [Integrity check] Compressing 'files_metadata.json' of 35819 files.
```

At the moment a condition has been added so that, if the synchronization includes only one shared file and nothing else, these logs are not counted as repeated. However, a more intelligent system that takes into account the aforementioned values (`Compressing 'files_metadata.json' of 35704 files.`) must be implemented. This will avoid false positives.

**Comment by Selutario** [comment]
## Issue update

I have applied the changes suggested in the last issue update to fine-tune the `test_cluster_sync`.

Now, in case that the number of files synced is identical multiple times in a row, the number of files for which the MD5 is calculated is also checked. If multiple identical syncs are repeated and the number of calculated MD5s does not change, the test is marked as failed.
