### ISSUE TITLE
qa-docs: Migrate `test_fim/test_files/test_follow_symbolic_link` documentation to schema 2.0

### ISSUE THREAD

**Issue by mdengra** [wazuh/wazuh-qa#1948]
### Description

This issue is created to migrate the `test_fim/test_files/test_follow_symbolic_link` documentation to the new **qa-docs** schema as part of the issue #1810 and the epic https://github.com/wazuh/wazuh-qa/issues/1796.

In the QA Wiki there are two entries to help complete the tasks:

- [Documenting tests using the qa-docs schema](https://github.com/wazuh/wazuh-qa/wiki/Documenting-tests-using-the-qadocs-schema): This entry describes the steps needed to document the tests (schema to use, the position of blocks, allowed values for fields, etc.).
- [Documentation generation with qa-docs tool](https://github.com/wazuh/wazuh-qa/wiki/Documentation-generation-with-qadocs-tool): Here is a brief description of how the `DocGenerator.py` module works to verify that the changes made in the tests have been done correctly.

## Main branch
`1810-qadocs-migrate-test-fim`

#### Tasks
- [x] Migrate tests:
  - [x] **test_files**
    - [x] **test_follow_symbolic_link**
      - [x] `test_audit_rules_removed_after_change_link.py`
      - [x] `test_change_target_inside_folder.py`
      - [x] `test_change_target.py`
      - [x] `test_change_target_with_nested_directory.py`
      - [x] `test_delete_symlink.py`
      - [x] `test_delete_target.py`
      - [x] `test_follow_symbolic_disabled.py`
      - [x] `test_monitor_symlink.py`
      - [x] `test_not_following_symbolic_link.py`
      - [x] `test_revert_symlink.py`
      - [x] `test_symlink_and_dir.py`
      - [x] `test_symlink_dir_inside_monitored_dir.py`
      - [x] `test_symlink_to_dir_between_scans.py`
      - [x] `test_symlink_within_dir.py`
- [x] Check `PEP-8` style guide (`pycodestyle --max-line-length=120`)
- [x] Merge issue branch to  `1810-qadocs-migrate-test-fim`

**Comment by mdengra** [comment]
## 2021-09-30

Working branch: `1948-qadocs-migrate-test-fim-follow-symbolic-link`
