### ISSUE TITLE
qa-docs: Migrate `test_ignore`, `test_inotify`, and `test_invalid` of `test_fim/test_files` documentation to schema 2.0

### ISSUE THREAD

**Issue by mdengra** [wazuh/wazuh-qa#1970]
### Description

This issue is created to migrate the `test_ignore`, `test_inotify`, and `test_invalid` of `test_fim/test_files` documentation to the new **qa-docs** schema as part of the issue #1810 and the epic https://github.com/wazuh/wazuh-qa/issues/1796.

In the QA Wiki there are two entries to help complete the tasks:

- [Documenting tests using the qa-docs schema](https://github.com/wazuh/wazuh-qa/wiki/Documenting-tests-using-the-qadocs-schema): This entry describes the steps needed to document the tests (schema to use, the position of blocks, allowed values for fields, etc.).
- [Documentation generation with qa-docs tool](https://github.com/wazuh/wazuh-qa/wiki/Documentation-generation-with-qadocs-tool): Here is a brief description of how the `DocGenerator.py` module works to verify that the changes made in the tests have been done correctly.

## Main branch
`1810-qadocs-migrate-test-fim`

#### Tasks
- [x] Migrate tests:
  - [x] **test_files**
    - [x] **test_ignore**
      - [x] `test_ignore_valid.py` (**Create new documentation**)
    - [x] **test_inotify**
      - [x] `test_max_fd_rt.py`
      - [x] `test_num_watches.py` (**Create new documentation**)
      - [x] `test_remove_rename_folder.py` (**Create new documentation**)
    - [x] **test_invalid**
      - [x] `test_invalid.py` (**Create new documentation**)
- [x] Check `PEP-8` style guide (`pycodestyle --max-line-length=120`)
- [x] Merge issue branch to  `1810-qadocs-migrate-test-fim`

**Comment by mdengra** [comment]
## 2021-10-04

Working branch: `1970-qadocs-migrate-test-fim-ignore-inotify-invalid`
