### ISSUE TITLE
qa-docs: Migrate `test_fim/test_files/test_report_changes` documentation to schema 2.0

### ISSUE THREAD

**Issue by mdengra** [wazuh/wazuh-qa#1995]
### Description

This issue is created to migrate the `test_fim/test_files/test_report_changes` documentation to the new **qa-docs** schema as part of the issue #1810 and the epic https://github.com/wazuh/wazuh-qa/issues/1796.

In the QA Wiki there are two entries to help complete the tasks:

- [Documenting tests using the qa-docs schema](https://github.com/wazuh/wazuh-qa/wiki/Documenting-tests-using-the-qadocs-schema): This entry describes the steps needed to document the tests (schema to use, the position of blocks, allowed values for fields, etc.).
- [Documentation generation with qa-docs tool](https://github.com/wazuh/wazuh-qa/wiki/Documentation-generation-with-qadocs-tool): Here is a brief description of how the `DocGenerator.py` module works to verify that the changes made in the tests have been done correctly.

## Main branch
`1810-qadocs-migrate-test-fim`

#### Tasks
- [x] Migrate tests:
  - [x] **test_files**
    - [x] **test_report_changes**
      - [x] `test_diff_size_limit_configured.py` (**Create new documentation**)
      - [x] `test_diff_size_limit_default.py` (**Create new documentation**)
      - [x] `test_disk_quota_default.py` (**Create new documentation**)
      - [x] `test_disk_quota_disabled.py` (**Create new documentation**)
      - [x] `test_disk_quota_values.py` (**Create new documentation**)
      - [x] `test_file_size_default.py` (**Create new documentation**)
      - [x] `test_file_size_disabled.py` (**Create new documentation**)
      - [x] `test_file_size_values.py` (**Create new documentation**)
      - [x] `test_large_changes.py` (**Create new documentation**)
      - [x] `test_report_changes_and_diff.py` (**Create new documentation**)
      - [x] `test_report_deleted_diff.py` (**Create new documentation**)
- [x] Check `PEP-8` style guide (`pycodestyle --max-line-length=120`)
- [x] Merge issue branch to  `1810-qadocs-migrate-test-fim`
