### ISSUE TITLE
Development of `qa-ctl` `v0.2`

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#2021]
The `qa-ctl` `v0.2` improves some aspects of the `v0.1` as well as adding support for Windows tests and making tests run in docker environments (so far only possible using vagrant).

The status of the planned set of tasks is shown below:

## General improvements

- [x] https://github.com/wazuh/wazuh-qa/issues/2008
- [x] https://github.com/wazuh/wazuh-qa/issues/2009
- [x] https://github.com/wazuh/wazuh-qa/issues/2011
- [x] https://github.com/wazuh/wazuh-qa/issues/2012
- [x] https://github.com/wazuh/wazuh-qa/issues/2013
- [x] https://github.com/wazuh/wazuh-qa/issues/2016
- [x] https://github.com/wazuh/wazuh-qa/issues/2017
- [x] https://github.com/wazuh/wazuh-qa/issues/2018
- [x] https://github.com/wazuh/wazuh-qa/issues/2019
- [ ] ~https://github.com/wazuh/wazuh-qa/issues/1999~
- [x] https://github.com/wazuh/wazuh-qa/issues/2023
- [x] https://github.com/wazuh/wazuh-qa/issues/2080

## New issues
- [x] https://github.com/wazuh/wazuh-qa/issues/2139
- [x] https://github.com/wazuh/wazuh-qa/issues/2140
- [x] https://github.com/wazuh/wazuh-qa/issues/2143
- [x] https://github.com/wazuh/wazuh-qa/issues/2164

## Add Windows tests support

- [x] https://github.com/wazuh/wazuh-qa/issues/1901
- [x] https://github.com/wazuh/wazuh-qa/issues/2020

## Add docker deployment support

- [ ] ~https://github.com/wazuh/wazuh-qa/issues/2024~
- [ ] ~https://github.com/wazuh/wazuh-qa/issues/2025~

## Documentation
- [x] https://github.com/wazuh/wazuh-qa/issues/2079
- [x] https://github.com/wazuh/wazuh-qa/issues/2071

**Comment by jmv74211** [comment]
The `v0.2` development has been finished. The testing and preparation of the release continues [here](https://github.com/wazuh/wazuh-qa/issues/2173)
