### ISSUE TITLE
qa-docs: Migrate `test_registry_ambiguous_confs` of `test_fim/test_registry` documentation to schema 2.0

### ISSUE THREAD

**Issue by mdengra** [wazuh/wazuh-qa#2048]
### Description

This issue is created to migrate the `test_tags`, `test_timezone_changes`, `test_wildcards_complex`, and `test_windows_audit_interval` of `test_fim/test_files` documentation to the new **qa-docs** schema as part of the issue #1810 and the epic https://github.com/wazuh/wazuh-qa/issues/1796.

In the QA Wiki there are two entries to help complete the tasks:

- [Documenting tests using the qa-docs schema](https://github.com/wazuh/wazuh-qa/wiki/QADOCS-tool-How-to-document-a-test): This entry describes the steps needed to document the tests (schema to use, the position of blocks, allowed values for fields, etc.).
- [Documentation generation with qa-docs tool](https://github.com/wazuh/wazuh-qa/wiki/QADOCS-tool): Here is a brief description of how the `qa-docs` tool works to verify that the changes made in the tests have been done correctly.

## Main branch
`1810-qadocs-migrate-test-fim`

#### Tasks
- [ ] Migrate tests:
  - [ ] **test_registry** 
    - [ ] **test_registry_ambiguous_confs**
      - [ ] `test_registry_ambiguous_complex.py`
      - [ ] `test_registry_ambiguous_duplicated_entries.py`
      - [ ] `test_registry_ambiguous_ignore_works_over_restrict.py`
      - [ ] `test_registry_ambiguous_simple.py`
- [ ] Check `PEP-8` style guide (`pycodestyle --max-line-length=120`)
- [ ] Merge issue branch to  `1810-qadocs-migrate-test-fim`
