### ISSUE TITLE
Make simple syscheck automated tests work for Windows platform

### ISSUE THREAD

**Issue by crd1985** [wazuh/wazuh-qa#207]
## Description
Now we have a decent set of integration tests for simple configurations, we should make them work also for windows agents. Although Python is cross-platform, syscheck does not work the same way for Unix and Windows.

## Tasks
- [x] Prepare an environment to run syscheck in a Windows agent

Run all simple tests iteratively until the same results as Unix tests are obtained:
- [x] ~Test_audit~ (Does not apply on Windows as Auditd is not available)
- [x] Test_basic_usage
- [x] Test_benchmark
- [x] Test_checks
- [x] Test_ignore
- [x] Test_invalid
- [x] Test_nodiff
- [x] ~Test_prefilter_cmd~
- [x] Test_recursion_level
- [x] Test_report_changes
- [x] Test_restrict
- [x] Test_scan
- [x] ~Test_sync~ (No need to test this on Windows as its a Manager only functionality)
- [x] Test_tags

**Comment by CarlosRS9** [comment]
# Status update

## Summary

The first part of the development is now completed. An environment consisting of a windows virtual machine correctly configured to run wazuh agent, connect to the manager and run the python code of the tests

Several changes had to be made on `fim.py`, `tools.py` and `conftest.py` in order to have them running on a windows environment. The current version support Linux and Windows OS now.

`Test_basic_usage` has been adapted to use the new cross-platform version of the code and now is able to run properly on Linux and Windows.


## Dificulties

- Tweaks and modifications were needed to be able to run the code on Windows environments. Modifications related to windows file system were also needed.
- Some random errors related to permissions apeared during the first windows tests.


## Test performed

Tests were executed both on Windows and Linux to ensure both platforms are running ok.

Here are the results of `test_basic_usage` on Linux:

```
============================ test session starts ============================
platform linux -- Python 3.6.8, pytest-5.2.2, py-1.8.0, pluggy-0.13.0
rootdir: /vagrant/wazuh-qa/test_wazuh, inifile: pytest.ini
collected 42 items

test_basic_usage_changes.py ......                                      [ 14%]
test_basic_usage_create_rt_wd.py ........................               [ 71%]
test_basic_usage_create_scheduled.py ............                       [100%]
================= 42 passed in 842618.02s (9 days, 18:03:38) =================
```

Here are the results of `test_basic_usage` on Windows:
```
============================ test session starts ============================
platform win32 -- Python 3.7.3, pytest-5.1.2, py-1.8.0, pluggy-0.13.0
rootdir: C:\Users\jmv74211\Desktop\wazuh-qa\test_wazuh, inifile: pytest.ini
collected 28 items

test_basic_usage_changes.py ....                                       [ 14%] 
test_basic_usage_create_rt_wd.py ............                           [ 57%] 
test_basic_usage_create_scheduled.py ............                       [100%]

================= 28 passed in 842547.00s (9 days, 18:02:27) ================
```


## To do

Adapt the rest of the tests to windows and ensure everything runs ok.

**Comment by CarlosRS9** [comment]
# Status update

## Summary

All tests have been migrated to windows and work properly. Several changes had to be made on `fim.py`, `tools.py` and `conftest.py` in order to have them running on a windows environment. The current version support Linux and Windows OS now.

## Test performed

Tests were executed both on Windows and Linux to ensure both platforms are running properly.

**Comment by CarlosRS9** [comment]
# Tests Examples on Linux

Here are the results of the tests on Linux:

**test_ambiguous_confs**

```
============================= test session starts ==============================
platform linux -- Python 3.6.8, pytest-5.2.2, py-1.8.0, pluggy-0.13.0
rootdir: /vagrant/wazuh-qa/test_wazuh, inifile: pytest.ini
collected 63 items
wazuh-qa/test_wazuh/test_fim/test_ambiguous_confs/test_ambiguous_complex.py . [  1%]
........                                                                 [ 14%]
wazuh-qa/test_wazuh/test_fim/test_ambiguous_confs/test_ambiguous_simple.py . [ 15%]
sssssssss.sssssssss.sssssssss.sssssssss.sssssssss....                    [100%]
=========== 18 passed, 45 skipped in 3370338.98s (39 days, 0:12:18) ============
```

**test_audit**

```
============================= test session starts ==============================
platform linux -- Python 3.6.8, pytest-5.2.2, py-1.8.0, pluggy-0.13.0
rootdir: /vagrant/wazuh-qa/test_wazuh, inifile: pytest.ini
collected 24 items
wazuh-qa/test_wazuh/test_fim/test_audit/test_audit.py .....sssssssss.sss [ 75%]
sssss.                                                                   [100%]
=================== 7 passed, 17 skipped in 70.30s (0:01:10) ===================
```

**test_basic_usage**

```
============================= test session starts ==============================
platform linux -- Python 3.6.8, pytest-5.2.2, py-1.8.0, pluggy-0.13.0
rootdir: /vagrant/wazuh-qa/test_wazuh, inifile: pytest.ini
collected 42 items
wazuh-qa/test_wazuh/test_fim/test_basic_usage/test_basic_usage_changes.py . [  2%]
.....                                                                    [ 14%]
wazuh-qa/test_wazuh/test_fim/test_basic_usage/test_basic_usage_create_rt_wd.py . [ 16%]
.......................                                                  [ 71%]
wazuh-qa/test_wazuh/test_fim/test_basic_usage/test_basic_usage_create_scheduled.py . [ 73%]
...........                                                              [100%]
================== 42 passed in 842613.66s (9 days, 18:03:33) ==================
```

**test_benchmark**

```
============================= test session starts ==============================
platform linux -- Python 3.6.8, pytest-5.2.2, py-1.8.0, pluggy-0.13.0
rootdir: /vagrant/wazuh-qa/test_wazuh, inifile: pytest.ini
collected 8 items
wazuh-qa/test_wazuh/test_fim/test_benchmark/test_benchmark.py ...FFFFF   [100%]
=================================== FAILURES ===================================
```

**test_checks**

```
========================================================================== test session starts ==========================================================================
platform linux -- Python 3.6.8, pytest-5.2.2, py-1.8.0, pluggy-0.13.0
rootdir: /vagrant/wazuh-qa/test_wazuh, inifile: pytest.ini
collected 378 items                                                                                                                                                     

test_check_all.py ..........ssssssssssssssssss..................ssssssssssssssssss..................ssssssssssssssssss........                                    [ 28%]
test_check_others.py ..........ssssssssssssssssss..................ssssssssssssssssss..................ssssssssssssssssss........                                 [ 57%]
test_checksums.py .............sssssssssssssssssssssssss.........................sssssssssssssssssssssssss.........................sssssssssssssssssssssssss..... [ 94%]
.......                                                                                                                                                           [ 96%]
test_hard_link.py ............                                                                                                                                    [100%]

====================================================== 195 passed, 183 skipped in 9408022.01s (108 days, 21:20:22) ======================================================
```

**test_ignore**

```
========================================================================== test session starts ==========================================================================
platform linux -- Python 3.6.8, pytest-5.2.2, py-1.8.0, pluggy-0.13.0
rootdir: /vagrant/wazuh-qa/test_wazuh, inifile: pytest.ini
collected 690 items                                                                                                                                                     

test_ignore_valid.py sssssssssssssssssss..ss....s......ssss.sssssss....s......ssss.sssssss....s......ssss.sssssss................s.sssss..................sssss.. [ 20%]
................sssss....s......s.s..s.sssss....s......s.s..ss.sssssssssssssssssssssssss..sssssssssssssssssss..ss....s......ssss.sssssss....s......ssss.sssssss.. [ 43%]
..s......ssss.sssssss................s.sssss..................sssss..................sssss....s......s.s..s.sssss....s......s.s..ss.sssssssssssssssssssssssss..ss [ 66%]
sssssssssssssssss..ss....s......ssss.sssssss....s......ssss.sssssss....s......ssss.sssssss................s.sssss..................sssss..................sssss.. [ 90%]
..s......s.s..s.sssss....s......s.s..ss.sssssssssssssssssssssssss..                                                                                               [100%]

====================================================== 354 passed, 336 skipped in 5523485.53s (63 days, 22:18:05) =======================================================
```

**test_invalid**

```
============================= test session starts ==============================
platform linux -- Python 3.6.8, pytest-5.2.2, py-1.8.0, pluggy-0.13.0
rootdir: /vagrant/wazuh-qa/test_wazuh, inifile: pytest.ini
collected 4 items
wazuh-qa/test_wazuh/test_fim/test_invalid/test_invalid.py ....           [100%]
============================== 4 passed in 29.20s ==============================
```

**test_nodiff**

```
============================= test session starts ==============================
platform linux -- Python 3.6.8, pytest-5.2.2, py-1.8.0, pluggy-0.13.0
rootdir: /vagrant/wazuh-qa/test_wazuh, inifile: pytest.ini
collected 567 items
wazuh-qa/test_wazuh/test_fim/test_nodiff/test_no_diff_valid.py sssssssss [  1%]
ssssssssss......s......ssss.sssss....s......ssss.sssss....s......ssss.ss [ 14%]
sss................s.sss..................sss..................sss....s. [ 26%]
.....s.s..s.sss....s......s.s..ss.sssssssssssssssssssss......s......ssss [ 39%]
.sssss....s......ssss.sssss....s......ssss.sssss................s.sss... [ 52%]
...............sss..................sss....s......s.s..s.sss....s......s [ 65%]
.s..ss.sssssssssssssssssssss......s......ssss.sssss....s......ssss.sssss [ 77%]
....s......ssss.sssss................s.sss..................sss......... [ 90%]
.........sss....s......s.s..s.sss....s......s.s..ss.ss                   [100%]
========= 348 passed, 219 skipped in 16288208.87s (188 days, 12:30:08) =========
```

**test_prefilter_cmd**

```
============================= test session starts ==============================
platform linux -- Python 3.6.8, pytest-5.2.2, py-1.8.0, pluggy-0.13.0
rootdir: /vagrant/wazuh-qa/test_wazuh, inifile: pytest.ini
collected 3 items
wazuh-qa/test_wazuh/test_fim/test_prefilter_cmd/test_prefilter_cmd.py .. [ 66%]
.                                                                        [100%]
========================= 3 passed in 76.21s (0:01:16) =========================
```

**test_recursion_level**

```
============================= test session starts ==============================
platform linux -- Python 3.6.8, pytest-5.2.2, py-1.8.0, pluggy-0.13.0
rootdir: /vagrant/wazuh-qa/test_wazuh, inifile: pytest.ini
collected 48 items

test_recursion_level/test_recursion_level.py ........................... [ 56%]
.....................                                                    [100%]

================= 48 passed in 8425386.72s (97 days, 12:23:06) =================
```

**test_report_changes**

```
============================= test session starts ==============================
platform linux -- Python 3.6.8, pytest-5.2.2, py-1.8.0, pluggy-0.13.0
rootdir: /vagrant/wazuh-qa/test_wazuh, inifile: pytest.ini
collected 12 items

test_report_changes/test_report_changes_and_diff.py ......               [ 50%]
test_report_changes/test_report_deleted_diff.py ......                   [100%]

================== 12 passed in 421412.02s (4 days, 21:03:32) ==================
```

**test_restrict**

```
============================= test session starts ==============================
platform linux -- Python 3.6.8, pytest-5.2.2, py-1.8.0, pluggy-0.13.0
rootdir: /vagrant/wazuh-qa/test_wazuh, inifile: pytest.ini
collected 432 items

test_restrict/test_restrict_valid.py ssssssssssssssss........sssssssssss [  8%]
s................ssssssss....ssssssssssssssss........ssssssss....sssssss [ 24%]
sssssssss........ssssssss....ssssssssssssssssssssssss........sssssssssss [ 41%]
s................ssssssss....ssssssssssssssss........ssssssss....sssssss [ 58%]
sssssssss........ssssssss....ssssssssssssssssssssssss........sssssssssss [ 74%]
s................ssssssss....ssssssssssssssss........ssssssss....sssssss [ 91%]
sssssssss........ssssssss....ssssssss                                    [100%]

========== 156 passed, 276 skipped in 2434153.42s (28 days, 4:09:13) ===========
```

**test_scan**

```
============================= test session starts ==============================
platform linux -- Python 3.6.8, pytest-5.2.2, py-1.8.0, pluggy-0.13.0
rootdir: /vagrant/wazuh-qa/test_wazuh, inifile: pytest.ini
collected 8 items
wazuh-qa/test_wazuh/test_fim/test_scan/test_scan_day.py ...              [ 37%]
wazuh-qa/test_wazuh/test_fim/test_scan/test_scan_day_and_time.py ..      [ 62%]
wazuh-qa/test_wazuh/test_fim/test_scan/test_scan_time.py ...             [100%]
================= 8 passed in 2158054.08s (24 days, 23:27:34) ==================
```

**test_sync**

```
	Failing as Core Team is currently working on this.
```

**test_tags**

```
============================= test session starts ==============================
platform linux -- Python 3.6.8, pytest-5.2.2, py-1.8.0, pluggy-0.13.0
rootdir: /vagrant/wazuh-qa/test_wazuh, inifile: pytest.ini
collected 48 items

test_tags/test_tags.py ................................................  [100%]

================= 48 passed in 2246689.83s (26 days, 0:04:49) ==================
```

**Comment by CarlosRS9** [comment]
# Status update
## Tests Examples on Windows

Here are the results of the tests on Linux. There are a few errors on some tests because syscheck is not working as expected. Those errors have been reported.

**test_ambiguous_confs**
```
================================================================= test session starts ==================================================================
platform win32 -- Python 3.7.3, pytest-5.1.2, py-1.8.0, pluggy-0.13.0
rootdir: C:\Users\jmv74211\Desktop\wazuh-qa\test_wazuh, inifile: pytest.ini
collected 171 items
test_ambiguous_confs\test_ambiguous_complex.py .........                                                                                          [  5%] 
test_ambiguous_confs\test_ambiguous_simple.py .sssssssss.sssssssss.sssssssss.sssssssss.sssssssss.....sssssssss.sssssssss.sssssssss.sssssssss.ssss [ 63%] sssss.....sssssssss.sssssssss.sssssssss.sssssssss.sssssssss....                                                                                   [100%]
=============================================== 36 passed, 135 skipped in 5898843.01s (68 days, 6:34:03) ===============================================
```

**test_basic_usage**
```
========================================================================= test session starts ==========================================================================
platform win32 -- Python 3.7.3, pytest-5.1.2, py-1.8.0, pluggy-0.13.0
rootdir: C:\Users\jmv74211\Desktop\wazuh-qa\test_wazuh, inifile: pytest.ini
collected 42 items
test_basic_usage_changes.py ......                                                                                                                                [ 14%]
test_basic_usage_create_rt_wd.py ........................                                                                                                         [ 71%] 
test_basic_usage_create_scheduled.py ............                                                                                                                 [100%]
============================================================== 42 passed in 842621.50s (9 days, 18:03:41) ==============================================================
```

**test_benchmark**
```
============================= test session starts =============================
platform win32 -- Python 3.7.3, pytest-5.1.2, py-1.8.0, pluggy-0.13.0
rootdir: C:\Users\jmv74211\Desktop\wazuh-qa\test_wazuh, inifile: pytest.ini
collected 8 items

test_benchmark.py ..FF...F                                                [100%]

=================================== FAILURES ===================================
```

**test_checks**
```
========================================================= test session starts ===================================================
platform win32 -- Python 3.7.3, pytest-5.1.2, py-1.8.0, pluggy-0.13.0
rootdir: C:\Users\jmv74211\Desktop\wazuh-qa\test_wazuh, inifile: pytest.ini
collected 360 items

test_check_all.py .........ssssssssssssssss................ssssssssssssssss................ssssssssssssssss.......          [ 27%]
test_check_others.py .........sssssssssssssssss.................sssssssssssssssss.................sssssssssssssssss........ [ 55%]
test_checksums.py .............sssssssssssssssssssssssss.........................sssssssssssssssssssssssss................. [ 84%]
........sssssssssssssssssssssssss...........                                                                                [ 97%]
test_hard_link.py ssssssssssss                                                                                              [100%]
```

**test_ignore**
```
Currently failing. Core Team is working on it.
```

**test_invalid**
```
============================= test session starts =============================
platform win32 -- Python 3.7.3, pytest-5.1.2, py-1.8.0, pluggy-0.13.0
rootdir: C:\Users\jmv74211\Desktop\wazuh-qa\test_wazuh, inifile: pytest.ini
collected 4 items

wazuh-qa\test_wazuh\test_fim\test_invalid\test_invalid.py ....           [100%]

============================= 4 passed in 26.97s ==============================
```

**test_nodiff**

```
================================================= test session starts ================================================= 
platform win32 -- Python 3.7.3, pytest-5.1.2, py-1.8.0, pluggy-0.13.0
rootdir: C:\Users\jmv74211\Desktop\wazuh-qa\test_wazuh, inifile: pytest.ini
collected 567 items

test_nodiff\test_no_diff_valid.py sssssssssssssssssss......s......ssss.sssss....s......ssss.sssss....s......ssss [ 13%] .sssss................s.sss..................sss..................sss....s......s.s..s.sss....s......s.s..ss.sss [ 33%] ssssssssssssssssss......s......ssss.sssss....s......ssss.sssss....s......ssss.sssss................s.sss........ [ 53%] ..........sss..................sss....s......s.s..s.sss....s......s.s..ss.sssssssssssssssssssss......s......ssss [ 73%] .sssss....s......ssss.sssss....s......ssss.sssss................s.sss..................sss..................sss. [ 92%] ...s......s.s..s.sss....s......s.s..ss.ss                                                                        [100%]

============================ 348 passed, 219 skipped in 16289039.77s (188 days, 12:43:59) =============================
```

**test_recursion_level**

```
============================= test session starts =============================
platform win32 -- Python 3.7.3, pytest-5.1.2, py-1.8.0, pluggy-0.13.0
rootdir: C:\Users\jmv74211\Desktop\wazuh-qa\test_wazuh, inifile: pytest.ini
collected 24 items

wazuh-qa\test_wazuh\test_fim\test_recursion_level\test_recursion_level.py . [  4%]
.......................                                                  [100%]

================= 48 passed in 8425375.66s (97 days, 12:22:55) =================
```

**test_report_changes**
```
=============================================== test session starts =============================================== 
platform win32 -- Python 3.7.3, pytest-5.1.2, py-1.8.0, pluggy-0.13.0
rootdir: C:\Users\jmv74211\Desktop\wazuh-qa\test_wazuh, inifile: pytest.ini
collected 12 items

test_report_changes_and_diff.py ......                                                                       [ 50%] 
test_report_deleted_diff.py .F.F.F                                                                           [100%]

==================================================== FAILURES =====================================================
```


**test_restrict**
```
============================= test session starts =============================
platform win32 -- Python 3.7.3, pytest-5.1.2, py-1.8.0, pluggy-0.13.0
rootdir: C:\Users\jmv74211\Desktop\wazuh-qa\test_wazuh, inifile: pytest.ini
collected 432 items

wazuh-qa\test_wazuh\test_fim\test_restrict\test_restrict_valid.py ssssss [  1%]
ssssssssss........ssssssssssss................ssssssss....ssssssssssssss [ 18%]
ss........ssssssss....ssssssssssssssss........ssssssss....ssssssssssssss [ 34%]
ssssssssss........ssssssssssss................ssssssss....ssssssssssssss [ 51%]
ss........ssssssss....ssssssssssssssss........ssssssss....ssssssssssssss [ 68%]
ssssssssss........ssssssssssss................ssssssss....ssssssssssssss [ 84%]
ss........ssssssss....ssssssssssssssss........ssssssss....ssssssss       [100%]

========== 156 passed, 276 skipped in 2434217.48s (28 days, 4:10:17) ==========
```

**test_scan**
```
=============================================== test session starts =============================================== 
platform win32 -- Python 3.7.3, pytest-5.1.2, py-1.8.0, pluggy-0.13.0
rootdir: C:\Users\jmv74211\Desktop\wazuh-qa\test_wazuh, inifile: pytest.ini
collected 8 items

test_scan_day.py ...                                                                                         [ 37%] 
test_scan_day_and_time.py ..                                                                                 [ 62%] 
test_scan_time.py ...                                                                                        [100%]

=================================== 8 passed in 2249278.81s (26 days, 0:47:58) ====================================
```


**test_tags**

```
=============================================== test session starts =============================================== 
platform win32 -- Python 3.7.3, pytest-5.1.2, py-1.8.0, pluggy-0.13.0
rootdir: C:\Users\jmv74211\Desktop\wazuh-qa\test_wazuh, inifile: pytest.ini
collected 48 items

test_tags.py ................................................                                                [100%]

=================================== 48 passed in 2246813.48s (26 days, 0:06:53) ===================================
```
