### ISSUE TITLE
qa-docs: Migrate `test_registry_checks`, `test_registry_ignore`, and `test_registry_nodiff` of `test_fim/test_registry` documentation to schema 2.0

### ISSUE THREAD

**Issue by mdengra** [wazuh/wazuh-qa#2073]
### Description

This issue is created to migrate the `test_registry_checks`, `test_registry_ignore`, and `test_registry_nodiff` of `test_fim/test_registry` documentation to the new **qa-docs** schema as part of the issue #1810 and the epic https://github.com/wazuh/wazuh-qa/issues/1796.

In the QA Wiki there are two entries to help complete the tasks:

- [Documenting tests using the qa-docs schema](https://github.com/wazuh/wazuh-qa/wiki/QADOCS-tool-How-to-document-a-test): This entry describes the steps needed to document the tests (schema to use, the position of blocks, allowed values for fields, etc.).
- [Documentation generation with qa-docs tool](https://github.com/wazuh/wazuh-qa/wiki/QADOCS-tool): Here is a brief description of how the `qa-docs` tool works to verify that the changes made in the tests have been done correctly.

## Main branch
`1810-qadocs-migrate-test-fim`

#### Tasks
- [x] Migrate tests:
  - [x] **test_registry** 
    - [x] **test_registry_checks**
      - [x] `test_registry_checkers.py` (**Create new documentation**)
      - [x] `test_registry_check_others.py` (**Create new documentation**)
    - [x] **test_registry_ignore**
      - [x] `test_ignore_registry.py` (**Create new documentation**)
    - [x] **test_registry_nodiff**
      - [x] `test_registry_no_diff.py` (**Create new documentation**)
- [x] Check `PEP-8` style guide (`pycodestyle --max-line-length=120`)
- [x] Merge issue branch to  `1810-qadocs-migrate-test-fim`
