### ISSUE TITLE
qa-docs: Prepare `v0.1` tool release

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh-qa#2075]
We want to release the first version of the `qa-docs` tool. For this purpose, it is proposed to make the last improvements to the tool and to proceed with the testing and the necessary checks to verify the correct operation. So we are using the last `qa-docs` changes made in #1864.

## Improvements
- [x] Create auto fields in `schema.yaml`
- [x] Fix `inputs` Auto/Manual generation

## Tasks
- [x] Update `qa-docs` tool entry in the [wiki](https://github.com/wazuh/wazuh-qa/wiki/QADOCS-tool)
- [x] Fix examples in `How to document a test` wiki entry
- [x] Update `entrypoint`
- [x] Add new tags to `schema.yaml`
- [x] Update how `qa-ctl` uses `qa-docs`
- [x] Prepare the tests input branch to perform the run checks

## Additional tasks
- [x] Change default path to `tempdir`
- [x] Extend `-o` use to all parse options
- [x] Generate only one format file(add format selection within tool parameters)
- [x] Improve indexing data logging info
- [x] Select with `-o` the Docker and host shared volume 
- [x] Deprecate `-I` option
- [x] Extend incompatibilites/validation check to new parameters.
- [ ] #2196

## Checks
- [x] Update `qa-docs` ChangeLog
- [x] `qa-docs` installation in Linux following the [installation guide](https://github.com/wazuh/wazuh-qa/wiki/QADOCS-tool-installation-guide#linux-dependencies)
- [x] `qa-docs` installation in Windows following the [installation guide](https://github.com/wazuh/wazuh-qa/wiki/QADOCS-tool-installation-guide#windows-dependencies)
    - [x] `qa-docs` tool
    - [x] ElasticSearch
    - [x] Docker
    - [x] npm

## Run Checks

To test the `qa-docs` tool, I am creating a new branch with the tests to use as input because there are no modules documented in master following the `qa-docs` schema 2.0.

**`Branch`**: [2075-tests-input](https://github.com/wazuh/wazuh-qa/tree/2075-tests-input)

### Linux

- [x] Check that a test exists
`qa-docs --tests-path /path/to/tests -e test_os_exec`
- [x] Parse a single test
`qa-docs --tests-path /path/to/tests  -t test_os_exec -o /tmp`
- [x] Parse two integration modules
`qa-docs --tests-path /path/to/tests --types integration --modules test_active_response test_analysisd`
- [x] Perform a sanity check
`qa-docs --tests-path /path/to/tests -s` 
- [x] Index that parsed data
`qa-docs -i index`
- [x] Launch `search-ui` with the index previously created
`qa-docs -l index`
- [x] Docker runs
`qa-docs --docker-run --types integration --modules test_active_response  --qa-branch 2075-tests-input`
`qa-docs --docker-run --types integration --modules test_active_response  --qa-branch 2075-tests-input -d -o /tmp -i qa`

### Windows

- [x] Check that a test exists
`qa-docs --tests-path /path/to/tests -e test_os_exec`
- [x] Parse a single test
`qa-docs --tests-path /path/to/tests  -t test_os_exec -o %TEMP%`
- [x] Parse two integration modules
`qa-docs --tests-path /path/to/tests --types integration --modules test_active_response`
- [x] Perform a sanity check
`qa-docs --tests-path /path/to/tests -s` 
- [x] Index that parsed data
`qa-docs -i index`
- [x] Launch `search-ui` with the index previously created
`qa-docs -l index`
- [x] Docker runs
`qa-docs --docker-run --types integration --modules test_active_response  --qa-branch 2075-tests-input`
`qa-docs --docker-run --types integration --modules test_active_response  --qa-branch 2075-tests-input -d -o /tmp -i qa`

## Invalid `qa-docs` script parameters

- [x] `-v, --version` must be run in isolation
- [x] `-s, --sanity-check` cannot be run with `-t, --tests, --types, --modules, -e, --exist`
- [x] `-t, --tests, --types, --modules, -e, --exist, -s, --sanity-check` must to be run with `-I`
- [x] `-e, --exist, -t, --tests` cannot be run with `-i, -l, -il`
- [x] `--types, --modules` cannot be run with `-o, -t, --tests, -e, --exist`
