### ISSUE TITLE
qa-docs: Migrate `test_registry_restrict` and `test_registry_tags` of `test_fim/test_registry`, and `test_fim/test_synchronization` documentation to schema 2.0

### ISSUE THREAD

**Issue by mdengra** [wazuh/wazuh-qa#2085]
### Description

This issue is created to migrate the `test_registry_restrict` and  `test_registry_tags` of `test_fim/test_registry`, and `test_fim/test_synchronization` documentation to the new **qa-docs** schema as part of the issue #1810 and the epic https://github.com/wazuh/wazuh-qa/issues/1796.

In the QA Wiki there are two entries to help complete the tasks:

- [Documenting tests using the qa-docs schema](https://github.com/wazuh/wazuh-qa/wiki/QADOCS-tool-How-to-document-a-test): This entry describes the steps needed to document the tests (schema to use, the position of blocks, allowed values for fields, etc.).
- [Documentation generation with qa-docs tool](https://github.com/wazuh/wazuh-qa/wiki/QADOCS-tool): Here is a brief description of how the `qa-docs` tool works to verify that the changes made in the tests have been done correctly.

## Main branch
`1810-qadocs-migrate-test-fim`

#### Tasks
- [x] Migrate tests:
  - [x] **test_registry** 
    - [x] **test_registry_restrict**
      - [x] `test_registry_restrict.py` (**Create new documentation**)
    - [x] **test_registry_tags**
      - [x] `test_registry_tags.py` (**Create new documentation**)
  - [x] **test_synchronization**
    - [x] `test_invalid_sync_response.py` (**Create new documentation**)
    - [x] `test_registry_responses_win32.py` (**Create new documentation**)
    - [x] `test_response_timeout.py` (**Create new documentation**)
    - [x] `test_sync_disabled.py` (**Create new documentation**)
    - [x] `test_sync_disabled_win32.py` (**Create new documentation**)
    - [x] `test_synchronize_integrity_scan.py` (**Create new documentation**)
    - [x] `test_synchronize_integrity_win32.py` (**Create new documentation**)
    - [x] `test_sync_interval.py` (**Create new documentation**)
    - [x] `test_sync_interval_win32.py` (**Create new documentation**)
- [x] Check `PEP-8` style guide (`pycodestyle --max-line-length=120`)
- [x] Merge issue branch to  `1810-qadocs-migrate-test-fim`
