### ISSUE TITLE
Add Hard Link tests to Syscheck automated tests: 'check_inode' option 

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh-qa#209]
| Working branch |
| --- |
|[fim-integration-tests-inode](https://github.com/wazuh/wazuh-qa/tree/fim-integration-tests-inode)|

## Description

Although Syscheck automated tests for `check_inode` has been completed on #149 we need to expand them to add two new tests to ensure proper behaviour.

The first test will be related to `hard links`. Having more than one hard link to the same file we need to ensure that `FIM` reports as many alerts as hard links we have when some of them are modified even with `check_inode="no"`.

The other  test will consist of the modification the _inode_ of a file by having two copies of the same file and replacing file _A_ with _B_ when using `check_inode="no". This must not trigger an alert as we will not be monitoring the _inode_.

## Tasks

- Realtime:
  - [x] Ensure we are receiving the correct number of alerts when `check_inode="yes"`
  - [x] Ensure we are receiving the correct number of alerts when `check_inode="no"`
  - [x] Check if the modification of an _inode_ is detected when `check_inode="no"`

- Whodata:
  - [x] Ensure we are receiving the correct number of alerts when `check_inode="yes"`
  - [x] Ensure we are receiving the correct number of alerts when `check_inode="no"`
  - [x] Check if the modification of an _inode_ is detected when `check_inode="no"`

- Scheduled:
  - [x] Ensure we are receiving the correct number of alerts when `check_inode="yes"`
  - [x] Ensure we are receiving the correct number of alerts when `check_inode="no"`
  - [x] Check if the modification of an _inode_ is detected when `check_inode="no"`

**Comment by CarlosRS9** [comment]
## Summary

The test for checking if the modification of an inode is detected when check_inode="no" is already done. Further improvements on the other `check_*` tests have been done.

## Pending
* Test for checking if we are receiving the correct number of alerts when working with `hard links`. I am currently working on this.
