### ISSUE TITLE
Elasticsearch fails to allocate shards due to low space

### ISSUE THREAD

**Issue by xr09** [wazuh/wazuh-qa#210]
## Description

Due to Elasticsearch default settings while [allocating shards](https://www.elastic.co/guide/en/elasticsearch/reference/current/disk-allocator.html) our testing environment is randomly failing due to low percentage of disk space, which is actually more than enough for the tests to run.

```
[2019-10-21T13:14:39,866][INFO ][o.e.c.r.a.DiskThresholdMonitor] [elasticsearch_centos7-1] low disk watermark [85%] exceeded on [zHJ54NavStykv3Pr-EQK8Q][elasticsearch_centos7-1][/var/lib/elasticsearch/nodes/0] free: 125.4gb[12.6%], replicas will not be assigned to this node
```

We need to tweak those settings to lower the requirements for the testing environment.

A proposed config could be the following:

```
cluster.routing.allocation.disk.threshold_enabled: true
cluster.routing.allocation.disk.watermark.flood_stage: 200mb
cluster.routing.allocation.disk.watermark.low: 500mb
cluster.routing.allocation.disk.watermark.high: 300mb
```

## Tasks
- [x] Tweak `elasticsearch.yml` to allow setting lower disk requirements
- [x] Use proposed values for the testing environemt
- [x] Test a complete execution of the elasticsearch-xpack scenario

**Comment by xr09** [comment]
Tests are already passing on the testing branch.

![Screenshot_20191022_082447](https://user-images.githubusercontent.com/1380243/67262523-69018800-f4a5-11e9-8520-f95c618a85f6.png)

The cluster on our testing env already allows for user creation and API testing.
