### ISSUE TITLE
Syscheck automated tests: 'recursion_level' and 'check_inode' options on the same directory

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh-qa#212]
| Working branch |
| --- |
| |

## Description

As an advanced configuration for `Automated tests for Syscheck` this is intented to test how 
syscheckd works when using `recursion_level` and `check_inode` options at the same time.

To test _inodes_ we need to modify the _inode_ of a file by having two copies of the same file and replacing file _A_ with _B_. This must not trigger an alert when using `check_inode="no".

## Subtasks
- Realtime
  - [ ] Verify `check_inode` is working as expected using recursion level 0.
  - [ ] Verify `check_inode` is working as expected using recursion level 1.
  - [ ] Verify `check_inode` is working as expected using recursion level 50.
  - [ ] Verify `check_inode` is working as expected using recursion level 320.

- Whodata
  - [ ] Verify `check_inode` is working as expected using recursion level 0.
  - [ ] Verify `check_inode` is working as expected using recursion level 1.
  - [ ] Verify `check_inode` is working as expected using recursion level 50.
  - [ ] Verify `check_inode` is working as expected using recursion level 320.

- Scheduled
  - [ ] Verify `check_inode` is working as expected using recursion level 0.
  - [ ] Verify `check_inode` is working as expected using recursion level 1.
  - [ ] Verify `check_inode` is working as expected using recursion level 50.
  - [ ] Verify `check_inode` is working as expected using recursion level 320.

**Comment by CarlosRS9** [comment]
# Status update
## Summary
Development is finished.

## Test performed

This is the current status of `test_recursion_level.py` after the modification:
```
================================== test session starts ==================================
platform linux -- Python 3.6.8, pytest-5.2.2, py-1.8.0, pluggy-0.13.0
rootdir: /vagrant/wazuh-qa/test_wazuh, inifile: pytest.ini
collected 48 items

test_recursion_level.py ................................................           [100%]

===================== 48 passed in 8425024.97s (97 days, 12:17:04) ======================
```
