### ISSUE TITLE
qa-docs: Run `qa-docs` using a docker container

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh-qa#2145]
# Description
`qa-docs` have a way to deploy `search-ui` with the desired documentation but it is necessary to also have a way that does not require installing a manager to get the test cases.  This is a new subtask within #2075.

It is needed to remove the script use and add the docker deployment within the `qa-docs` tool.

# Branch
[2145-docker-shared-dir](https://github.com/wazuh/wazuh-qa/tree/2145-docker-shared-dir)

# Tasks
- [x] Change entrypoint
- [x] Add docker build and run to `qa-docs` tool commands

# Additional tasks
- [x] Add parameters validation before starting services in entrypoint

# Checks
- [x] Works in Linux
- [x] Works in Windows
