### ISSUE TITLE
Roadmap of refactor and test blocked

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#2174]
FIM has too many tests that need refactoring as their tests are unstable and needs maintenance. 

For this reason, the `2174-skipped-fim-tests-that-need-refactoring-4.4` branch of 4.4 contains the list of skipped tests that will be refactored.

The branch skipped tests will be listed below.

# FIM Tests 

## To fix

- [ ] tests/integration/test_fim/test_files/test_ambiguous_confs/test_ambiguous_complex.py
- [ ] tests/integration/test_fim/test_files/test_ambiguous_confs/test_ambiguous_simple.py
- [ ] tests/integration/test_fim/test_files/test_ambiguous_confs/test_duplicate_entries.py
- [ ] tests/integration/test_fim/test_files/test_env_variables/test_ignore.py
- [ ] tests/integration/test_fim/test_files/test_audit/test_audit.py
- [ ] tests/integration/test_fim/test_files/test_audit/test_audit_after_initial_scan.py
- [ ] tests/integration/test_fim/test_files/test_audit/test_audit_no_dir.py
- [ ] tests/integration/test_fim/test_files/test_audit/test_remove_rule_five_times.py
- [ ] tests/integration/test_fim/test_files/test_basic_usage/test_basic_usage_access_opened_files.py
- [ ] tests/integration/test_fim/test_files/test_basic_usage/test_basic_usage_baseline_generation.py
- [ ] tests/integration/test_fim/test_files/test_basic_usage/test_basic_usage_changes.py
- [ ] tests/integration/test_fim/test_files/test_basic_usage/test_basic_usage_create_rt_wd.py
- [ ] tests/integration/test_fim/test_files/test_basic_usage/test_basic_usage_create_scheduled.py
- [ ] tests/integration/test_fim/test_files/test_basic_usage/test_basic_usage_currently_open.py
- [ ] tests/integration/test_fim/test_files/test_basic_usage/test_basic_usage_db_inode_check.py
- [ ] tests/integration/test_fim/test_files/test_basic_usage/test_basic_usage_dir_with_commas.py
- [ ] tests/integration/test_fim/test_files/test_basic_usage/test_basic_usage_new_dirs.py
- [ ] tests/integration/test_fim/test_files/test_basic_usage/test_basic_usage_quick_changes.py
- [ ] tests/integration/test_fim/test_files/test_basic_usage/test_basic_usage_wildcards.py
- [ ] tests/integration/test_fim/test_files/test_basic_usage/test_basic_usage_wildcards_runtime.py
- [ ] tests/integration/test_fim/test_files/test_checks/data/wazuh_checksums_windows.yaml
- [ ] tests/integration/test_fim/test_files/test_checks/test_check_all.py
- [ ] tests/integration/test_fim/test_files/test_checks/test_check_others.py
- [ ] tests/integration/test_fim/test_files/test_checks/test_checksums.py
- [ ] tests/integration/test_fim/test_files/test_follow_symbolic_link/test_delete_target.py
- [ ] tests/integration/test_fim/test_files/test_follow_symbolic_link/test_symlink_dir_inside_monitored_dir.py
- [ ] tests/integration/test_fim/test_files/test_follow_symbolic_link/test_symlink_within_dir.py
- [ ] tests/integration/test_fim/test_files/test_inotify/test_max_fd_rt.py
- [ ] tests/integration/test_fim/test_files/test_inotify/test_remove_rename_folder.py
- [ ] tests\integration\test_fim\test_files\test_invalid\test_invalid.py
- [ ] tests\integration\test_fim\test_files\test_max_files_per_second\test_max_files_per_second.py
- [ ] tests/integration/test_fim/test_files/test_multiple_dirs/common.py
- [ ] tests/integration/test_fim/test_files/test_multiple_dirs/test_multiple_dirs.py
- [ ] tests/integration/test_fim/test_files/test_multiple_dirs/test_multiple_entries.py
- [ ] tests/integration/test_fim/test_files/test_nodiff/test_no_diff_valid.py
- [ ] tests/integration/test_fim/test_files/test_report_changes/test_disk_quota_values.py
- [ ] tests\integration\test_fim\test_files\test_skip\test_skip.py
- [ ] tests/integration/test_fim/test_files/test_wildcards_complex/test_wildcards_complex.py
- [ ] tests/integration/test_fim/test_files/test_wildcards_complex/test_wildcards_complex_runtime.py
- [ ] tests/integration/test_fim/test_registry/test_registry_ambiguous_confs/test_registry_ambiguous_ignore_works_over_restrict.py
- [ ] tests/integration/test_fim/test_registry/test_registry_ambiguous_confs/test_registry_ambiguous_simple.py
- [ ] tests/integration/test_fim/test_registry/test_registry_basic_usage/test_basic_usage_registry_changes.py
- [ ] tests/integration/test_fim/test_registry/test_registry_checks/test_registry_check_others.py
- [ ] tests/integration/test_fim/test_registry/test_registry_recursion_level/test_recursion_level_registry.py
- [ ] tests/integration/test_fim/test_registry/test_registry_report_changes/test_disk_quota/test_registry_disk_quota_default.py
- [ ] tests/integration/test_fim/test_registry/test_registry_report_changes/test_registry_file_size_default.py
- [ ] tests/integration/test_fim/test_registry/test_registry_report_changes/test_registry_report_changes_deleted.py
- [ ] tests/integration/test_fim/test_synchronization/test_sync_registry_disabled_win32.py
- [ ] tests/integration/test_fim/test_synchronization/test_sync_interval.py

# Logcollector
- [ ] test_logcollector/test_age/test_age_datetime_changed.py - Fails because of use TimeMachine.travel_to_future function

**Comment by Deblintrake09** [comment]
## Research Update 17/05/2023

- Tests related to https://github.com/wazuh/wazuh/issues/9298 - Are skipped, but the error was related to Windows. Should change `skip` to `skipif` until they are refactored.
- Tests in `test_ambiguous_confs` have been refactored in https://github.com/wazuh/wazuh-qa/issues/3591

**Comment by vikman90** [comment]
Closing this issue. Superseded by version 5.0.
