### ISSUE TITLE
qa-docs: Improve SearchUI style

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh-qa#2196]
# Description
`qa-docs` tool allows us to parse test documentation and up a search engine with this test data. Now it is just raw data from the documentation previously parsed, so it is necessary to give SearchUI some style.

As the last part of #2075, the documentation app needs a better presentation instead of just plain text.

# Branch 
[2196-searchui-style](https://github.com/wazuh/wazuh-qa/tree/2196-searchui-style)

# Tasks
- [x] Research about react app structure
- [ ] Change the format of the fields within the tests in SearchUI.

# Additional tasks
- [x] Fix filter issue
- [x] Add missing test/module fields
