### ISSUE TITLE
Development and automation of tests to detect possible alterations by Wazuh in the system check-files.

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#2231]
The objective of this issue is to propose new tests that allow us to check if an installation, upgrade, execution or uninstallation of a Wazuh environment has any influence on the permissions, owners, or groups of the rest of the files in the system.

For this, the following tasks are proposed:

- [x] https://github.com/wazuh/wazuh-qa/issues/2232
- [x] https://github.com/wazuh/wazuh-qa/issues/2235
- [x] https://github.com/wazuh/wazuh-qa/issues/2233
- [x] https://github.com/wazuh/wazuh-qa/issues/2234
- [x] https://github.com/wazuh/wazuh-qa/issues/2239
- [x] https://github.com/wazuh/wazuh-qa/issues/2240
- [x] https://github.com/wazuh/wazuh-qa/issues/2268
- [x] https://github.com/wazuh/wazuh-qa/issues/2241
 - [x] https://github.com/wazuh/wazuh-qa/issues/2243
- [x] https://github.com/wazuh/wazuh-qa/issues/2242
- [x] https://github.com/wazuh/wazuh-qa/issues/2277
- [x] https://github.com/wazuh/wazuh-qa/issues/2291
- [x] https://github.com/wazuh/wazuh-qa/issues/2244
- [x] https://github.com/wazuh/wazuh-qa/issues/2245
- [x] https://github.com/wazuh/wazuh-qa/issues/2309
- [x] https://github.com/wazuh/wazuh-qa/issues/2310
- [x] https://github.com/wazuh/wazuh-qa/issues/2311
