### ISSUE TITLE
System check-files test: Test development and documentation

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#2233]
# Description
The purpose of this test is to check if the system check-files are the same as they were initially before deploying or initiating any action with Wazuh. In short, it can be summarized in that Wazuh does not modify any system file not related to its installation.

For this purpose, the following design is proposed.

The test receives two input files corresponding to the system check-files (representing the state before and after the action performed) and will pass if they are the same or, otherwise it will fail.

# Tasks
- [x] Research about using parameters in pytest
- [x] Create the check-files test that checks if two files are the same
- [x] Check that the test passes the PEP8 style
- [x] Add documentation following the google style guide

**Comment by roronoasins** [comment]
I have created a test that receives two arguments, added using the `conftest.py`:
```
def pytest_add_argument(parser):
    parser.pytest_add_argument("--file1", action="store")
    parser.pytest_add_argument("--file2", action="store")
```


Now it loads the JSONs and compares them, it asserts if they are not equal.

Tomorrow I will research about a faster way to compare them.

**Comment by roronoasins** [comment]
The current state of `test_system_check_file.py`:

It generates a JSON with the changes:
```JSON
{
    "values_changed": {
        "root['data'][0]['description']['prot']": {
            "new_value": "drwxr-xrwx",
            "old_value": "drwxr-xr-x"
        }
    },
    "iterable_item_removed": {
        "root['data'][10]": {
            "id": 10,
            "name": "/home/fede/Downloads/wazuh-manager-4.3.0-fedepache.master.todelete.x86_64.rpm",
            "description": {
                "class": "static",
                "group": "fede",
                "mode": "0664",
                "prot": "-rw-rw-r--",
                "type": "file",
                "user": "fede"
            }
        }
    }
}


```

Tomorrow I will change the JSON output to make it more understandable(replacing the keys like `root['data'][0]['description']['prot']` with the file name and the field that has changed)
