### ISSUE TITLE
Creation of a new Centos 7 box for `qa-ctl`.

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#2241]
It is requested to create a new vagrant box for the `CentOS 7` operating system. This box has to be provisioned with the following dependencies:

- `Python (>=3.6.0)`.
- `Python3-devtools`
- Wazuh-qa [python dependencies](https://github.com/wazuh/wazuh-qa/blob/master/requirements.txt).

# Update

# Tasks
- [x] Read information about creating a new box for vagrants. 
- [x] Create a Centos 7 VirtualBox machine.
- [x] Install Python tools.
- [x] Install Wazuh-qa dependencies.
- [x] Create a Centos 7 vagrant box.

**Comment by roronoasins** [comment]
Today I have created a CentOS 7 box, the first time it connected returning 0 and being able to connect using ssh. After that, when I try to do that again, the vagrant up command does not finish.

Also, I have used the `centos/7` box from vagrant cloud, and this one works fine but it uses sudo to install and manage things, so I have to search for another predefined box that does not require sudo(or find out why `vagrant up` is not working with the custom centos7 minimal box).

**Comment by roronoasins** [comment]
I have created a few custom boxes from CentOS 7 minimal iso, but I could not successfully perform a `vagrant up`. I tried to use the `qa-ctl` official CentOS 8 box, but I had the same issue.

It may is not related to the custom boxes created, but with my PC or vagrantfile. Tomorrow I will research this problem.

**Comment by fedepacher** [comment]
I start research to create Centos 7 box

**Comment by jmv74211** [comment]
The `centos_7` vagrant box has been finished and uploaded to S3
