### ISSUE TITLE
Development of new playbooks to perform the desired actions: installation, upgrade, uninstallation ...

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#2243]
In order to test if an action performed by Wazuh (installation, update...) can alter the system check-files, it is necessary to perform these actions in the testing environment. To do so, we will use the `qa-ctl` module that allows executing tasks by `ansible`.

We are asked to develop the corresponding ansible-playbooks that allow us to perform the following actions

- Install Wazuh
- Update Wazuh
- Uninstall Wazuh
- Copy files from the remote machine to the localhost.

on the following operating systems:

- Linux RPM
- Linux DEB
- Windows

These playbooks will be located at the following location

```
test_check_files/
├── launcher.py
├── playbooks
│   ├── install_wazuh.yaml
│   ├── uninstall_wazuh.yaml
│   └── upgrade_wazuh.yaml
└── test_system_check_files.py
```
# Update
## New Requirement

We will replace all the playbooks to install, uninstall and upgrade with python code. 

# Tasks
- [x] Convert YAML playbooks to a python dictionary. 
- [ ] Create methods to read dictionaries.
- [ ] Create methods that based on the dictionary can install, uninstall and upgrade Wazuh.
- [ ] Create separated methods for rpm and Debian packages

**Comment by fedepacher** [comment]
Reading Ansible tutorial to create playbooks

**Comment by fedepacher** [comment]
Creating python method to convert YAML to a dictionary.
