### ISSUE TITLE
Fix: wazuh-puppet dockerfile does not merge source branch into target branch

### ISSUE THREAD

**Issue by rshad** [wazuh/wazuh-qa#225]
Hi all!

We detected that the corresponding `dockerfile` for  `wazuh-puppet` does not merge the source branch into the target branch before testing.

**Tasks to Do:**

- [x] Add the corresponding `dockerfile`'s tasks to run such a merge process.
- [x] Test the changes in a local machine.
- [x] AFTER implementing the corresponding changes in `wazuh-jenkins`, test it with a testing PR.

Note: The issue description would be updated in the future if needed.

Kr,

Rshad

**Comment by rshad** [comment]
Hi all!

We are working here [feature-225-puppet-merge-source-in-target](https://github.com/wazuh/wazuh-qa/tree/feature-225-puppet-merge-source-in-target).

Kind regards,

Rshad

**Comment by rshad** [comment]
Hi all!

To solve such issue we modified the following task.

https://github.com/wazuh/wazuh-qa/blob/e28e633b7cfaee6d4d45ea625e6db6e1544def97/kitchen/wazuh-puppet/dockerfile#L9-L16

As you can see we added the required merge statement to merge the target branch into the source branch.

**Testing**

We ran the tests locally `VM` and also in Jenkins Pipeline, once we made the required changes to Jenkins also. For details. check https://github.com/wazuh/wazuh-jenkins/issues/902

Kr,

Rshad
