### ISSUE TITLE
Create new integration tests for `log rotation`

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh-qa#2259]
|QA Epic Branch|Component|
|:--:|:--:|
||Manager / Agent|

## Description
With this _Epic issue_ it is intended to create the necessary integrated tests to support the new functionalities created in development: wazuh/wazuh#3072

Most possible cases should be covered to verify that there are no errors and everything works as expected.

These new tests to be created are based on the tests carried out in issue #90, where all possible cases were checked manually.

## List of ITs
- [ ] [Create test for `logging` configuration](https://github.com/wazuh/wazuh-qa/issues/2260)
- [ ] [Create test for `log rotation` file creation](https://github.com/wazuh/wazuh-qa/issues/2261)
- [ ] [Create test for `log rotation` compression](https://github.com/wazuh/wazuh-qa/issues/2262)
- [ ] [Create test for removing `log rotation` files](https://github.com/wazuh/wazuh-qa/issues/2263)
- [ ] [Create miscellaneous tests for `log rotation`](https://github.com/wazuh/wazuh-qa/issues/2264)

**Comment by vikman90** [comment]
Closing this issue as it will be superseded by version 5.0.
