### ISSUE TITLE
Create test for `log rotation` file creation

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh-qa#2261]
|QA Branch|
|:--:|
||

## Description

We need to support and verify that the file creation functionalities of the `log rotation` work correctly.

To do this, we must check some variables inside the `<rotation>` configuration block like `max_size`, `min_size` or `schedule`.

### Tasks to check
- [ ] Force `max_size` rotation, `schedule` rotation and both _true_ situations.
- [ ] Joint functionality between `schedule` and `min_size`. Check does not create file if it does not exceed the `min_size` after `schedule` and the case is successful.
- [ ] `max_size` and `min_size` set in the same configuration (they are not supported)
- [ ] Invalid configuration.
- [ ] Nonexistent configuration

**Comment by damarisg** [comment]
We decided to close them.
