### ISSUE TITLE
Create miscellaneous tests for `log rotation`

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh-qa#2264]
|QA Branch|
|:--:|
||

## Description

We need to support and verify that the file creation functionalities of the `log rotation` work correctly.

To do this, we need to check for situations where the daemon is restarted or uses an old configuration, and it should continue to work as expected.

### Tasks to check
- [ ] The indexes continue from the last one if there are previous logs created when restarting the daemon.
- [ ] The indexes are reset if there are no previous logs created when restarting the daemon.
- [ ] The old configuration is still functional although it shows a deprecation message.
- [ ] Duplicate configuration.

**Comment by damarisg** [comment]
We decided to close them.
