### ISSUE TITLE
Add integration tests to check the manager's Active Response configuration

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-qa#2271]
|Related issue|
|---|
|https://github.com/wazuh/wazuh/issues/10911|

We need some checks for the Active Response configuration. The goal is to ensure that no wrong settings are allowed by Analysisd.

### Related documentation

- [active-response reference manual](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/active-response.html).

## Tasks

- [ ] When `<disabled>` is set to `yes` and `<command>` is set to any value, Analysisd shall ignore that stanza and print this log:
```
DEBUG: active response command 'X' is disabled
```
- [ ] When `<location>` is not set, Analysisd shall print this error:
```
ERROR: (1281): Missing options in the active response configuration.
```
- [ ] When `<command>` is not set, Analysisd shall print this error:
```
ERROR: (1281): Missing options in the active response configuration.
```
- [ ] `<location>` must be either `AS`, `analysisd`, `analysis-server`, `server`, `defined-agent`, `all` or `any`. Otherwise, Analysisd shall reject the configuration and print this error:
```
ERROR: (1302): Invalid active response location: 'X'.
```
- [ ] When `<location>` is set to `defined-agent`, `<agent_id>` must be set. Otherwise, Analysisd shall reject the configuration and print this log:
```
ERROR: (1304): No agent defined for response.
```
- [ ] When `<location>` is set to `defined-agent`, and `<agent_id>` is set to `0`, `000` or an invalid number, the system shall discard that stanza and print this warning:
```
WARN:  (1306): Invalid agent ID. Use location=server to run AR on the manager.
```
- [ ] `<command>` must match any defined `<command>` stanza in the configuration. Otherwise, the system shall reject the configuration and print this error:
```
ERROR: (1303): Invalid command 'X' in the active response.
```
- [ ] If the related command has `<timeout_allowed>` set to `no` and the AR stanza has `<timeout>` defined, the system shall print this log and continue normally:
```
INFO: (1305): Timeout not allowed for command: 'X'.
```

**Comment by damarisg** [comment]
We decided to close them.
