### ISSUE TITLE
Performance testing: PoC v2 - Ingestion rate

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh-qa#2279]
|**Epic**|
|---|
|#2229|

### Objetive

This issue has been opened to implement the 2nd version of the performance test described in this [Epic](https://github.com/wazuh/wazuh-qa/issues/2229).

The purpose of the new test is to check that the performance of Analysisd does not decrease when upgrading the version of Wazuh. We will test different combinations of hardware, EPS, and Wazuh configurations.

### Tasks

- [x] Send messages through a socket to Analysisd to generate events and alerts.
- [x] Detect dropping events.
- [x] Synchronize the sends and detections threads.
- [x] Configure Wazuh manager (depends on the test case that is executed)
- [x] Calculate the EPS decoded average and the EPS dropped average through a certain execution time.
- [x] Use QA-CTL to upgrade Wazuh.
- [x] Calculate the average under the same conditions and compare it with the first results.
- [x] Design the different combinations of hardware, EPS, and Wazuh configurations. (#2247)

**Comment by fernandolojano** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/QA---Earthquake-61940be5780ab80010c8ac35/issues/wazuh/wazuh-qa/2279?planning-poker) with ZenHub @danisan90 @mauromalara

**Comment by fernandolojano** [comment]
The working branch for this issue is: [2279-analysisd-islolated-stress-test](https://github.com/wazuh/wazuh-qa/tree/2279-analysisd-isolated-stress-test)

**Comment by mauromalara** [comment]
I'll be working on the [2279-PoCv2-qa-ctlv0.3-playbooks](https://github.com/wazuh/wazuh-qa/tree/2279-PoCv2-qa-ctlv0.3-playbooks) temp branch because I need some changes from other branches until them being merged.

**Comment by mauromalara** [comment]
## Style guide
| Command | Status |
| --- | --- |
| `pycodestyle --max-line-length=120 <FILE-PATH>` | PASSED :green_circle: |

## QA-Docs execution

### test_analysisd_ingestion_avg
qa-docs --tests-path $HOME/Documents/Wazuh/issue/2279/tests/performance/test_analysisd/test_analysisd_ingestion_rate/ -t test_analysisd_ingestion_avg

### Results
2022-01-21 09:01:23,910 - INFO - Looking for test_analysisd_ingestion_avg.py
2022-01-21 09:01:23,910 - INFO - Parsing the following test(s) ['test_analysisd_ingestion_avg']
2022-01-21 09:01:23,919 - INFO - Running QADOCS
2022-01-21 09:01:23,919 - INFO - Looking for test_analysisd_ingestion_avg.py
2022-01-21 09:01:24,062 - INFO - Run completed, documentation location: /tmp/qa_docs/output

### Output file
[test_analysisd_ingestion_avg.zip](https://github.com/wazuh/wazuh-qa/files/7913909/test_analysisd_ingestion_avg.zip)
