### ISSUE TITLE
Find out which paths need to be omitted when running check_files

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh-qa#2291]
# Description
We need to be sure that `check_files` obtains the necessary information, but not less.

In order to accomplish this, I have started this research in this [issue](https://github.com/wazuh/wazuh-qa/issues/2268#issuecomment-982503756).

# Tasks 
- [x] `centos/7`
  - [x] List the paths that do not retrieve `stat_info` or `checksum`
  - [x] List the paths that do not finish in hours
  - [x] List the paths that change when obtaining the check files after a lapse of time
  - [x] List the paths that change but are related with wazuh installation/uninstallation/upgrade

- [x] `qactl/ubuntu_20_04`
  - [x] List the paths that do not retrieve `stat_info` or `checksum`
  - [x] List the paths that do not finish in hours
  - [x] List the paths that change when obtaining the check files after a lapse of time
  - [x] List the paths that change but are related with wazuh installation/uninstallation/upgrade

- [x] `qactl/centos_8`
  - [x] List the paths that do not retrieve `stat_info` or `checksum`
  - [x] List the paths that do not finish in hours
  - [x] List the paths that change when obtaining the check files after a lapse of time
  - [x] List the paths that change but are related with wazuh installation/uninstallation/upgrade

# Additional tasks

- [x] Update the warning list attempt
  - [x] `qactl/ubuntu_20_04`
  - [x] `qactl/centos_8`
  - [x] `qactl/centos_7`

**Comment by roronoasins** [comment]
# centos/7 environment

The paths below have been obtained using the `check_files.py` script.

## Paths that do not end in a short amount of time

These are the paths that spent hours running and did not finish:
- `/sys`
- `/run`
- `/proc`
- `/dev`.

## Paths that fail when running

From the other subdirectories, these are the paths that do not retrieve their stat_info or checksum:
- `/var/lib/gssproxy/default.sock`
- `/var/spool/`, `/usr/lib/gcc`
- `/usr/lib/debug/usr/.dwz`
- `/usr/lib/modules`
- `/lib/debug/usr/.dwz`
- `/lib/modules`
- `/lib/gcc`.

## Paths that change when running after a lapse of time
When `check_files` is run after a time lapse, these files checksum and last_update change:

- `/swapfile` -> swapping related
- `/etc/mtab`
- `/var/log/secure` -> related to sudo
- `/var/log/audit/audit.log` -> related to audit framework

## Paths that change due to installing/uninstalling/upgrading wazuh component

- Installing a manager/agent:
  - `/etc/group-`
  - `/etc/group`
  - `/etc/gshadow-`
  - `/etc/gshadow`
  - `/etc/passwd-`
  - `/etc/passwd`
  - `/etc/shadow`
  - `/etc/shadow-`
  - `/etc/pki/nssdb`
  - `/etc/yum.repos.d`
  - `/var/log`
  - `/var/lib/`
  - `/var/cache/yum`
  - `/usr/lib`
  - `/etc/selinux/targeted`

- Uninstalling a manager/agent:
  - `/etc/group-`
  - `/etc/group`
  - `/etc/gshadow-`
  - `/etc/gshadow`
  - `/etc/passwd-`
  - `/etc/passwd`
  - `/etc/shadow`
  - `/etc/shadow-`
  - `/etc/selinux/targeted`
  - `/etc/rc.d/init.d`
  - `/var/lib/`
  - `/var/log`
  - `/usr/lib`

**Comment by roronoasins** [comment]
# `qactl/centos_8` environment

The paths below have been obtained using the `check_files.py` script.

- working on it

## Paths that do not end in a short amount of time

## Paths that fail when running

## Paths that change when running after a lapse of time

## Paths that change due to installing/uninstalling/upgrading wazuh component

**Comment by roronoasins** [comment]
# `qactl/ubuntu_20_04` environment

The paths below have been obtained using the `check_files.py` script.

- working on it

## Paths that do not end in a short amount of time

## Paths that fail when running

## Paths that change when running after a lapse of time

## Paths that change due to installing/uninstalling/upgrading wazuh component

**Comment by roronoasins** [comment]
Here is the [warning_list_attempt.txt](https://github.com/wazuh/wazuh-qa/files/7717978/warning_list_attempt.txt) that includes all the paths above.
