### ISSUE TITLE
Update the `check-files` tool: New fields changes

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh-qa#2309]
# Description
As a #2268 continuation, we need to make some changes related to the fields that the JSON contains.

This is the actual structure:
```json
{
.
.
.
"/boot": {
      "type": "directory",
      "user": "root",
      "group": "root",
      "mode": "755",
      "permissions": "drwxr-xr-x",
      "last_update": "2021-09-24 08:40:57"
    },
"/boot/System.map-5.4.0-86-generic": {
      "type": "file",
      "user": "root",
      "group": "root",
      "mode": "600",
      "permissions": "-rw-------",
      "last_update": "2021-09-17 18:35:09",
      "checksum": "0c897754248a85d1743dc4cc1b47ae83"
    },
.
.
.
}
```
# Working  branch
2309-check-files-fields-changes

# Tasks
It is required to:
- [x] Change the checksum field name
- [x] Research about if it is necessary to have both modify and change times
- [x] Add size field

**Comment by roronoasins** [comment]
# Changes
- `checksum` has been renamed as `md5sum` because the algorithm that generates the hash value is md5
- `last_update` is the `mtime` or modify time that implies the `atime`(access) and `ctime`(change, when the file's properties changes). [reference link](https://nicolasbouliane.com/blog/knowing-difference-mtime-ctime-atime)
- `size` has been added(format: XY, where X is the count and Y the unit)

# Example

```json
{
.
.
.
"/home/luisgr/work/thunder/issues/2309/wazuh-qa/docs/deps/wazuh-testing/tools.md": {
        "type": "file",
        "user": "luis",
        "group": "luis",
        "mode": "664",
        "permissions": "-rw-rw-r--",
        "last_update": "2021-12-10 11:27:49",
        "md5sum": "0b43778f2132312e0c88e945de5e6fbb",
        "size": "866B"
    },
    "/home/luisgr/work/thunder/issues/2309/wazuh-qa/docs/deps/wazuh-testing/wazuh_testing.md": {
        "type": "file",
        "user": "luis",
        "group": "luis",
        "mode": "664",
        "permissions": "-rw-rw-r--",
        "last_update": "2021-12-10 11:27:49",
        "md5sum": "893a4ca13585768563da4bd06b62dd98",
        "size": "2.53KB"
    },
    .
    .
    .
}
```
