### ISSUE TITLE
Modify the `check-files` test logic

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh-qa#2310]
# Description
Now, the test fails os pass depending on the given files. As we can see in #2291, there are so many paths/files that make the test fail.

We need to create a new logic, where the test will have a warning list as input. This list allows us to handle all these files that change, checking manually if they are critical or can be omitted.

# Tasks
- [x] Add the warning list approach for array instances
- [x] Add the warning list approach for dict instances
- [x] Add the warning state and red state to the test
- [x] Add old and new values to each changed value type

# Additional tasks
- [x] Research about not showing the test as `passed` when a warning is logged
- [x] Test that the test behavior is valid

**Comment by roronoasins** [comment]
# Status
The test generates a `yellow JSON` and a `red JSON` depending on the warning list:

- If the test finds a path that is not listed on the warning list within the differences between the inputs, it is logged within the `red JSON`
- If the test finds a path that is listed on the warning list within the differences between the inputs, it is logged within the `yellow JSON`

I am working on how to avoid the `passed` after the test execution because this test only returns a `warning` or `fail` status and the report is manually checked, in order to determine the final test status.

```
====================================================== 1 passed, 4 warnings in 18.78s ======================================================
```
