### ISSUE TITLE
Improve the differences JSON within the `check-files` test

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh-qa#2311]
# Description
It is required to enhance the JSON structure that contains the differences between the two given files.

The diffs are stored in a JSON like this one:
```json
{
    "dictionary_item_added": [
        "['/home/vagrant/20211207093001_checkfiles.json']"
    ],
    "dictionary_item_removed": [
        "['/home/vagrant/20211207090121_checkfiles.json']",
        "['/home/vagrant/20211207090053']"
    ],
    "values_changed": {
        "['/var/log/auth.log']['last_update']": {
            "new_value": "2021-12-07 10:03:06",
            "old_value": "2021-12-07 09:30:01"
        },
        "['/var/log/auth.log']['checksum']": {
            "new_value": "99a2177fa49d2e3d33e8a3965d0349df",
            "old_value": "0f113491e941710abb35097ced510135"
        },
        "['/var/log/syslog']['last_update']": {
            "new_value": "2021-12-07 10:00:01",
            "old_value": "2021-12-07 09:30:01"
        },
        .
        .
        .
}
```

# Tasks
- [x] Extract the absolute path from each JSON item
- [x] Create a new custom JSON with a better structure
- [x] Test that it works with added, removed and changed fields

**Comment by roronoasins** [comment]
This has been solved in #2310
