### ISSUE TITLE
Test Ansible PR on Amazon Linux 2

### ISSUE THREAD

**Issue by xr09** [wazuh/wazuh-qa#232]
### Description

In order to have better feedback we require adding Amazon Linux 2 as a testing platform for our Molecule tests.

### Tasks

- [x] Pick a valid image with systemd
- [x] Add support for Amazon Linux 2 on Molecule playbooks
- [x] Run the complete test suite
