### ISSUE TITLE
qa-docs: Migrate test_feeds of test_vulnerability_detector documentation to schema 2.0

### ISSUE THREAD

**Issue by fedepacher** [wazuh/wazuh-qa#2324]
### Description

This issue is created to migrate the `test_vulnerability_detector` documentation to the new QA Docs schema as part of the epic https://github.com/wazuh/wazuh-qa/issues/1796.

In the QA Wiki there are two entries to help complete the tasks:

- [Documenting tests using the QA Docs schema](https://github.com/wazuh/wazuh-qa/wiki/QA-Documentation---How-to-document-a-test-using-Schema-2.0): This entry describes the steps needed to document the tests (schema to use, the position of blocks, allowed values for fields, etc.).
- [Documentation generation with DocGenerator tool](https://github.com/wazuh/wazuh-qa/wiki/QADOCS-tool-use-guide): Here is a brief description of how the `DocGenerator.py` module works to verify that the changes made in the tests have been done correctly.

#### Main branch
`1796-migrate-doc-schema-1`

#### Tasks
- [x] Migrate tests:
  - [x] **test_feeds**
    - [x] **alas**
      - [x] `test_extra_tags_alas_feed.py`
      - [x] `test_invalid_syntax_alas_feed.py`
      - [x] `test_invalid_values_alas_feed.py`
      - [x] `test_missing_tags_alas_feed.py`
    - [x] **archlinux**
      - [x] `test_extra_tags_archlinux_feed.py`
      - [x] `test_invalid_syntax_archlinux_feed.py`
      - [x] `test_invalid_values_archlinux_feed.py`
      - [x] `test_missing_tags_archlinux_feed.py`
    - [x] **canonical**
      - [x] `test_extra_tags_canonical_feed.py`
      - [x] `test_invalid_syntax_canonical_feed.py`
      - [x] `test_invalid_values_canonical_feed.py`
      - [x] `test_missing_tags_canonical_feed.py`
    - [x] **debian**
      - [x] `test_extra_tags_debian_feed.py`
      - [x] `test_invalid_syntax_debian_feed.py`
      - [x] `test_invalid_values_debian_feed.py`
      - [x] `test_missing_tags_debian_feed.py`
    - [x] **msu**
      - [x] `test_extra_fields_msu_feed.py`
      - [x] `test_invalid_syntax_msu_feed.py`
      - [x] `test_invalid_values_msu_feed.py`
      - [x] `test_missing_fields_msu_feed.py`
    - [x] **redhat**
      - [x] `test_extra_fields_redhat_feed.py`
      - [x] `test_invalid_syntax_redhat_feed.py`
      - [x] `test_invalid_values_redhat_feed.py`
      - [x] `test_missing_fields_redhat_feed.py`
    - [x] `test_download_feeds.py`
    - [x] `test_invalid_type_custom_feeds.py`
    - [x] `test_invalid_type_url_feeds.py`
    - [x] `test_validate_feed_content.py`
- [x] Check `PEP-8` style guide (`pycodestyle --max-line-length=120`)
- [x] Ckeck with QA-Doc style format
- [ ] Merge issue branch to  `master`

**Comment by fedepacher** [comment]
- Study how vulnerability detector works.
- Comment test_feeds schema block

**Comment by fedepacher** [comment]
Documentation of test_feeds of test_vulnerability_detector completed. The next step is to create a PR in order to be reviewed by @roronoasins

**Comment by fedepacher** [comment]
Failed to create a PR with the following error message:

`Pull request creation failed. Validation failed: Body is too long (maximum is 65536 characters)`

The problem is that I try to add all the JSON files generated with the QA-Docs.
