### ISSUE TITLE
qa-docs: Migrate test_general_settings of test_vulnerability_detector documentation to schema 2.0

### ISSUE THREAD

**Issue by fedepacher** [wazuh/wazuh-qa#2325]
### Description

This issue is created to migrate the `test_vulnerability_detector` documentation to the new QA Docs schema as part of the epic https://github.com/wazuh/wazuh-qa/issues/1796.

In the QA Wiki there are two entries to help complete the tasks:

- [Documenting tests using the QA Docs schema](https://github.com/wazuh/wazuh-qa/wiki/QA-Documentation---How-to-document-a-test-using-Schema-2.0): This entry describes the steps needed to document the tests (schema to use, the position of blocks, allowed values for fields, etc.).
- [Documentation generation with DocGenerator tool](https://github.com/wazuh/wazuh-qa/wiki/QADOCS-tool-use-guide): Here is a brief description of how the `DocGenerator.py` module works to verify that the changes made in the tests have been done correctly.

#### Main branch
`1796-migrate-doc-schema-1`

#### Tasks
- [x] Migrate tests:
  - [x] **test_general_settings**
    - [x] `test_general_settings_enabled.py`
    - [x] `test_general_settings_ignore_time.py`
    - [x] `test_general_settings_interval.py`
    - [x] `test_general_settings_run_on_start.py`  
- [x] Check `PEP-8` style guide (`pycodestyle --max-line-length=120`)
- [x] Ckeck with QA-Doc style format
- [ ] Merge issue branch to  `1796-migrate-doc-schema-1`

**Comment by fedepacher** [comment]
Study and start commenting test_general_setting test of test_vulnerability_detector.

**Comment by fedepacher** [comment]
- Style guide (pycodestyle --max-line-length=120) (PASSED)

## QA-docs execution 

### test_general_settings_enabled
`qa-docs --tests-path ../test_vulnerability_detector/test_general_settings/ -t test_general_settings_enabled`

### Results
`2021-12-20 16:16:03,474 - INFO - Looking for test_general_settings_enabled.py
2021-12-20 16:16:03,474 - INFO - Parsing the following test(s) ['test_general_settings_enabled']
2021-12-20 16:16:03,489 - INFO - Running QADOCS
2021-12-20 16:16:03,489 - INFO - Looking for test_general_settings_enabled.py
2021-12-20 16:16:03,693 - INFO - Run completed, documentation location: /tmp/qa_docs/output`

### Output File
[test_general_settings_enabled](https://github.com/wazuh/wazuh-qa/files/7747509/test_general_settings_enabled.zip)

### test_general_settings_ignore_time
`qa-docs --tests-path ../test_vulnerability_detector/test_general_settings/ -t test_general_settings_ignore_time`

### Results
`2021-12-20 16:16:19,432 - INFO - Looking for test_general_settings_ignore_time.py
2021-12-20 16:16:19,433 - INFO - Parsing the following test(s) ['test_general_settings_ignore_time']
2021-12-20 16:16:19,447 - INFO - Running QADOCS
2021-12-20 16:16:19,447 - INFO - Looking for test_general_settings_ignore_time.py
2021-12-20 16:16:19,663 - INFO - Run completed, documentation location: /tmp/qa_docs/output`

### Output File
[test_general_settings_ignore_time](https://github.com/wazuh/wazuh-qa/files/7747515/test_general_settings_ignore_time.zip)

### test_general_settings_interval
`qa-docs --tests-path ../test_vulnerability_detector/test_general_settings/ -t test_general_settings_interval`

### Results
`2021-12-20 16:16:31,210 - INFO - Looking for test_general_settings_interval.py
2021-12-20 16:16:31,210 - INFO - Parsing the following test(s) ['test_general_settings_interval']
2021-12-20 16:16:31,224 - INFO - Running QADOCS
2021-12-20 16:16:31,224 - INFO - Looking for test_general_settings_interval.py
2021-12-20 16:16:31,431 - INFO - Run completed, documentation location: /tmp/qa_docs/output`

### Output File
[test_general_settings_interval](https://github.com/wazuh/wazuh-qa/files/7747528/test_general_settings_interval.zip)

### test_general_settings_run_on_start
`qa-docs --tests-path ../test_vulnerability_detector/test_general_settings/ -t test_general_settings_run_on_start`

### Results
`2021-12-20 16:16:50,963 - INFO - Looking for test_general_settings_run_on_start.py
2021-12-20 16:16:50,963 - INFO - Parsing the following test(s) ['test_general_settings_run_on_start']
2021-12-20 16:16:50,978 - INFO - Running QADOCS
2021-12-20 16:16:50,978 - INFO - Looking for test_general_settings_run_on_start.py
2021-12-20 16:16:51,175 - INFO - Run completed, documentation location: /tmp/qa_docs/output`

### Output File
[test_general_settings_run_on_start](https://github.com/wazuh/wazuh-qa/files/7747531/test_general_settings_run_on_start.zip)
