### ISSUE TITLE
qa-docs: Migrate test_providers of test_vulnerability_detector documentation to schema 2.0

### ISSUE THREAD

**Issue by fedepacher** [wazuh/wazuh-qa#2326]
### Description

This issue is created to migrate the `test_vulnerability_detector` documentation to the new QA Docs schema as part of the epic https://github.com/wazuh/wazuh-qa/issues/1796.

In the QA Wiki there are two entries to help complete the tasks:

- [Documenting tests using the QA Docs schema](https://github.com/wazuh/wazuh-qa/wiki/QA-Documentation---How-to-document-a-test-using-Schema-2.0): This entry describes the steps needed to document the tests (schema to use, the position of blocks, allowed values for fields, etc.).
- [Documentation generation with DocGenerator tool](https://github.com/wazuh/wazuh-qa/wiki/QADOCS-tool-use-guide): Here is a brief description of how the `DocGenerator.py` module works to verify that the changes made in the tests have been done correctly.

#### Main branch
`1796-migrate-doc-schema-1`

#### Tasks
- [x] Migrate tests:
  - [x] **test_providers**
    - [x] `test_providers_enabled.py`
    - [x] `test_providers_multiple_providers.py`
    - [x] `test_providers_no_os.py`
    - [x] `test_providers_os.py`
    - [x] `test_providers_update_from_year.py`
    - [x] `test_providers_update_interval.py`  
- [x] Check `PEP-8` style guide (`pycodestyle --max-line-length=120`)
- [x] Ckeck with QA-Doc style format
- [ ] Merge issue branch to  `1796-migrate-doc-schema-1`

**Comment by fedepacher** [comment]
- Style guide (pycodestyle --max-line-length=120) (PASSED) 🟢 

## QA-docs execution 

### test_providers_enabled
`qa-docs --tests-path ../test_vulnerability_detector/test_providers/ -t test_providers_enabled`

### Results
`2021-12-21 14:23:27,710 - INFO - Looking for test_providers_enabled.py
2021-12-21 14:23:27,710 - INFO - Parsing the following test(s) ['test_providers_enabled']
2021-12-21 14:23:27,725 - INFO - Running QADOCS
2021-12-21 14:23:27,725 - INFO - Looking for test_providers_enabled.py
2021-12-21 14:23:27,973 - INFO - Run completed, documentation location: /tmp/qa_docs/output`

### Output File
[test_providers_enabled](https://github.com/wazuh/wazuh-qa/files/7757030/test_providers_enabled.zip)

### test_providers_multiple_providers
`qa-docs --tests-path ../test_vulnerability_detector/test_providers/ -t test_providers_multiple_providers`

### Results
`2021-12-21 14:23:50,987 - INFO - Looking for test_providers_multiple_providers.py
2021-12-21 14:23:50,987 - INFO - Parsing the following test(s) ['test_providers_multiple_providers']
2021-12-21 14:23:51,002 - INFO - Running QADOCS
2021-12-21 14:23:51,002 - INFO - Looking for test_providers_multiple_providers.py
2021-12-21 14:23:51,229 - INFO - Run completed, documentation location: /tmp/qa_docs/output`

### Output File
[test_providers_multiple_providers](https://github.com/wazuh/wazuh-qa/files/7757032/test_providers_multiple_providers.zip)

### test_providers_no_os
`qa-docs --tests-path ../test_vulnerability_detector/test_providers/ -t test_providers_no_os`

### Results
`2021-12-21 14:25:09,938 - INFO - Looking for test_providers_no_os.py
2021-12-21 14:25:09,938 - INFO - Parsing the following test(s) ['test_providers_no_os']
2021-12-21 14:25:09,952 - INFO - Running QADOCS
2021-12-21 14:25:09,953 - INFO - Looking for test_providers_no_os.py
2021-12-21 14:25:10,158 - INFO - Run completed, documentation location: /tmp/qa_docs/output`

### Output File
[test_providers_no_os](https://github.com/wazuh/wazuh-qa/files/7757049/test_providers_no_os.zip)

### test_providers_os
`qa-docs --tests-path ../test_vulnerability_detector/test_providers/ -t test_providers_os`

### Results
`2021-12-21 14:25:25,908 - INFO - Looking for test_providers_os.py
2021-12-21 14:25:25,908 - INFO - Parsing the following test(s) ['test_providers_os']
2021-12-21 14:25:25,922 - INFO - Running QADOCS
2021-12-21 14:25:25,922 - INFO - Looking for test_providers_os.py
2021-12-21 14:25:26,129 - INFO - Run completed, documentation location: /tmp/qa_docs/output`

### Output File
[test_providers_os](https://github.com/wazuh/wazuh-qa/files/7757056/test_providers_os.zip)

### test_providers_update_from_year
`qa-docs --tests-path ../test_vulnerability_detector/test_providers/ -t test_providers_update_from_year`

### Results
`2021-12-21 14:25:42,226 - INFO - Looking for test_providers_update_from_year.py
2021-12-21 14:25:42,226 - INFO - Parsing the following test(s) ['test_providers_update_from_year']
2021-12-21 14:25:42,251 - INFO - Running QADOCS
2021-12-21 14:25:42,252 - INFO - Looking for test_providers_update_from_year.py
2021-12-21 14:25:42,489 - INFO - Run completed, documentation location: /tmp/qa_docs/output`

### Output File
[test_providers_update_from_year](https://github.com/wazuh/wazuh-qa/files/7757065/test_providers_update_from_year.zip)

### test_providers_update_interval
`qa-docs --tests-path ../test_vulnerability_detector/test_providers/ -t test_providers_update_interval`

### Results
`2021-12-21 14:25:55,336 - INFO - Looking for test_providers_update_interval.py
2021-12-21 14:25:55,336 - INFO - Parsing the following test(s) ['test_providers_update_interval']
2021-12-21 14:25:55,351 - INFO - Running QADOCS
2021-12-21 14:25:55,351 - INFO - Looking for test_providers_update_interval.py
2021-12-21 14:25:55,618 - INFO - Run completed, documentation location: /tmp/qa_docs/output`

### Output File
[test_providers_update_interval](https://github.com/wazuh/wazuh-qa/files/7757073/test_providers_update_interval.zip)
