### ISSUE TITLE
qa-docs: Migrate test_scan_results of test_vulnerability_detector documentation to schema 2.0

### ISSUE THREAD

**Issue by fedepacher** [wazuh/wazuh-qa#2327]
### Description

This issue is created to migrate the `test_vulnerability_detector` documentation to the new QA Docs schema as part of the epic https://github.com/wazuh/wazuh-qa/issues/1796.

In the QA Wiki there are two entries to help complete the tasks:

- [Documenting tests using the QA Docs schema](https://github.com/wazuh/wazuh-qa/wiki/QA-Documentation---How-to-document-a-test-using-Schema-2.0): This entry describes the steps needed to document the tests (schema to use, the position of blocks, allowed values for fields, etc.).
- [Documentation generation with DocGenerator tool](https://github.com/wazuh/wazuh-qa/wiki/QADOCS-tool-use-guide): Here is a brief description of how the `DocGenerator.py` module works to verify that the changes made in the tests have been done correctly.

#### Main branch
`1796-migrate-doc-schema-1`

#### Tasks
- [x] Migrate tests:
  - [x] **test_scan_results**
    - [x] `test_alas_inventory_alas_feed.py`
    - [x] `test_archliux_inventory_archlinux_feed.py`
    - [x] `test_debian_inventory_debian_feed.py`
    - [x] `test_macos_inventory.py`
    - [x] `test_msu_inventory_msu_feed.py`
    - [x] `test_redhat_duplicate_vulns.py`
    - [x] `test_redhat_inventory_redhat_feed.py`
    - [x] `test_scan_different_cves.py`
    - [x] `test_scan_nvd_feed.py`
    - [x] `test_scan_providers_and_nvd_feed.py`
    - [x] `test_ubuntu_inventory_canonical_feed.py`  
- [x] Check `PEP-8` style guide (`pycodestyle --max-line-length=120`)
- [x] Ckeck with QA-Doc style format
- [ ] Merge issue branch to  `1796-migrate-doc-schema-1`

**Comment by fedepacher** [comment]
- Style guide (pycodestyle --max-line-length=120) (PASSED) 🟢 

## QA-docs execution 

### test_alas_inventory_alas_feed
`qa-docs --tests-path ../test_vulnerability_detector/test_scan_scan_results/ -t test_alas_inventory_alas_feed`

### Results
`2021-12-22 17:00:34,142 - INFO - Looking for test_alas_inventory_alas_feed.py
2021-12-22 17:00:34,142 - INFO - Parsing the following test(s) ['test_alas_inventory_alas_feed']
2021-12-22 17:00:34,156 - INFO - Running QADOCS
2021-12-22 17:00:34,156 - INFO - Looking for test_alas_inventory_alas_feed.py
2021-12-22 17:00:34,349 - INFO - Run completed, documentation location: /tmp/qa_docs/output`

### Output File
[test_alas_inventory_alas_feed](https://github.com/wazuh/wazuh-qa/files/7764972/test_alas_inventory_alas_feed.zip)

### test_archliux_inventory_archlinux_feed
`qa-docs --tests-path ../test_vulnerability_detector/test_scan_scan_results/ -t test_archliux_inventory_archlinux_feed`

### Results
`2021-12-22 17:01:39,531 - INFO - Looking for test_archliux_inventory_archlinux_feed.py
2021-12-22 17:01:39,531 - INFO - Parsing the following test(s) ['test_archliux_inventory_archlinux_feed']
2021-12-22 17:01:39,545 - INFO - Running QADOCS
2021-12-22 17:01:39,545 - INFO - Looking for test_archliux_inventory_archlinux_feed.py
2021-12-22 17:01:39,732 - INFO - Run completed, documentation location: /tmp/qa_docs/output`

### Output File
[test_archliux_inventory_archlinux_feed](https://github.com/wazuh/wazuh-qa/files/7764975/test_archliux_inventory_archlinux_feed.zip)

### test_debian_inventory_debian_feed
`qa-docs --tests-path ../test_vulnerability_detector/test_scan_scan_results/ -t test_debian_inventory_debian_feed`

### Results
`2021-12-22 17:01:52,772 - INFO - Looking for test_debian_inventory_debian_feed.py
2021-12-22 17:01:52,772 - INFO - Parsing the following test(s) ['test_debian_inventory_debian_feed']
2021-12-22 17:01:52,786 - INFO - Running QADOCS
2021-12-22 17:01:52,786 - INFO - Looking for test_debian_inventory_debian_feed.py
2021-12-22 17:01:52,978 - INFO - Run completed, documentation location: /tmp/qa_docs/output`

### Output File
[test_debian_inventory_debian_feed](https://github.com/wazuh/wazuh-qa/files/7764980/test_debian_inventory_debian_feed.zip)

### test_macos_inventory
`qa-docs --tests-path ../test_vulnerability_detector/test_scan_scan_results/ -t test_macos_inventory`

### Results
`2021-12-22 17:02:07,505 - INFO - Looking for test_macos_inventory.py
2021-12-22 17:02:07,505 - INFO - Parsing the following test(s) ['test_macos_inventory']
2021-12-22 17:02:07,519 - INFO - Running QADOCS
2021-12-22 17:02:07,520 - INFO - Looking for test_macos_inventory.py
2021-12-22 17:02:07,707 - INFO - Run completed, documentation location: /tmp/qa_docs/output`

### Output File
[test_macos_inventory](https://github.com/wazuh/wazuh-qa/files/7764982/test_macos_inventory.zip)

### test_macos_inventory
`qa-docs --tests-path ../test_vulnerability_detector/test_scan_scan_results/ -t test_macos_inventory`

### Results
`2021-12-22 17:02:07,505 - INFO - Looking for test_macos_inventory.py
2021-12-22 17:02:07,505 - INFO - Parsing the following test(s) ['test_macos_inventory']
2021-12-22 17:02:07,519 - INFO - Running QADOCS
2021-12-22 17:02:07,520 - INFO - Looking for test_macos_inventory.py
2021-12-22 17:02:07,707 - INFO - Run completed, documentation location: /tmp/qa_docs/output`

### Output File
[test_macos_inventory](https://github.com/wazuh/wazuh-qa/files/7764995/test_macos_inventory.zip)


### test_msu_inventory_msu_feed
`qa-docs --tests-path ../test_vulnerability_detector/test_scan_scan_results/ -t test_msu_inventory_msu_feed`

### Results
`2021-12-22 17:02:21,183 - INFO - Looking for test_msu_inventory_msu_feed.py
2021-12-22 17:02:21,184 - INFO - Parsing the following test(s) ['test_msu_inventory_msu_feed']
2021-12-22 17:02:21,198 - INFO - Running QADOCS
2021-12-22 17:02:21,198 - INFO - Looking for test_msu_inventory_msu_feed.py
2021-12-22 17:02:21,385 - INFO - Run completed, documentation location: /tmp/qa_docs/output`

### Output File
[test_msu_inventory_msu_feed](https://github.com/wazuh/wazuh-qa/files/7764991/test_msu_inventory_msu_feed.zip)

### test_redhat_duplicate_vulns
`qa-docs --tests-path ../test_vulnerability_detector/test_scan_scan_results/ -t test_redhat_duplicate_vulns`

### Results
`2021-12-22 17:03:27,319 - INFO - Looking for test_redhat_duplicate_vulns.py
2021-12-22 17:03:27,319 - INFO - Parsing the following test(s) ['test_redhat_duplicate_vulns']
2021-12-22 17:03:27,334 - INFO - Running QADOCS
2021-12-22 17:03:27,334 - INFO - Looking for test_redhat_duplicate_vulns.py
2021-12-22 17:03:27,534 - INFO - Run completed, documentation location: /tmp/qa_docs/output`

### Output File
[test_redhat_duplicate_vulns](https://github.com/wazuh/wazuh-qa/files/7764999/test_redhat_duplicate_vulns.zip)

### test_redhat_inventory_redhat_feed
`qa-docs --tests-path ../test_vulnerability_detector/test_scan_scan_results/ -t test_redhat_inventory_redhat_feed`

### Results
`2021-12-22 17:03:50,294 - INFO - Looking for test_redhat_inventory_redhat_feed.py
2021-12-22 17:03:50,294 - INFO - Parsing the following test(s) ['test_redhat_inventory_redhat_feed']
2021-12-22 17:03:50,308 - INFO - Running QADOCS
2021-12-22 17:03:50,308 - INFO - Looking for test_redhat_inventory_redhat_feed.py
2021-12-22 17:03:50,496 - INFO - Run completed, documentation location: /tmp/qa_docs/output`

### Output File
[test_redhat_inventory_redhat_feed](https://github.com/wazuh/wazuh-qa/files/7765002/test_redhat_inventory_redhat_feed.zip)

### test_scan_different_cves
`qa-docs --tests-path ../test_vulnerability_detector/test_scan_scan_results/ -t test_scan_different_cves`

### Results
`2021-12-22 17:04:20,565 - INFO - Looking for test_scan_different_cves.py
2021-12-22 17:04:20,565 - INFO - Parsing the following test(s) ['test_scan_different_cves']
2021-12-22 17:04:20,579 - INFO - Running QADOCS
2021-12-22 17:04:20,579 - INFO - Looking for test_scan_different_cves.py
2021-12-22 17:04:20,843 - INFO - Run completed, documentation location: /tmp/qa_docs/output`

### Output File
[test_scan_different_cves](https://github.com/wazuh/wazuh-qa/files/7765004/test_scan_different_cves.zip)

### test_scan_nvd_feed
`qa-docs --tests-path ../test_vulnerability_detector/test_scan_scan_results/ -t test_scan_nvd_feed`

### Results
`2021-12-22 17:04:35,536 - INFO - Looking for test_scan_nvd_feed.py
2021-12-22 17:04:35,536 - INFO - Parsing the following test(s) ['test_scan_nvd_feed']
2021-12-22 17:04:35,550 - INFO - Running QADOCS
2021-12-22 17:04:35,550 - INFO - Looking for test_scan_nvd_feed.py
2021-12-22 17:04:35,827 - INFO - Run completed, documentation location: /tmp/qa_docs/output`

### Output File
[test_scan_nvd_feed](https://github.com/wazuh/wazuh-qa/files/7765007/test_scan_nvd_feed.zip)

### test_scan_providers_and_nvd_feed
`qa-docs --tests-path ../test_vulnerability_detector/test_scan_scan_results/ -t test_scan_providers_and_nvd_feed`

### Results
`2021-12-22 17:04:50,341 - INFO - Looking for test_scan_providers_and_nvd_feed.py
2021-12-22 17:04:50,341 - INFO - Parsing the following test(s) ['test_scan_providers_and_nvd_feed']
2021-12-22 17:04:50,355 - INFO - Running QADOCS
2021-12-22 17:04:50,355 - INFO - Looking for test_scan_providers_and_nvd_feed.py
2021-12-22 17:04:50,616 - INFO - Run completed, documentation location: /tmp/qa_docs/output`

### Output File
[test_scan_providers_and_nvd_feed](https://github.com/wazuh/wazuh-qa/files/7765010/test_scan_providers_and_nvd_feed.zip)

### test_ubuntu_inventory_canonical_feed
`qa-docs --tests-path ../test_vulnerability_detector/test_scan_scan_results/ -t test_ubuntu_inventory_canonical_feed`

### Results
`2021-12-22 17:05:05,055 - INFO - Looking for test_ubuntu_inventory_canonical_feed.py
2021-12-22 17:05:05,055 - INFO - Parsing the following test(s) ['test_ubuntu_inventory_canonical_feed']
2021-12-22 17:05:05,069 - INFO - Running QADOCS
2021-12-22 17:05:05,069 - INFO - Looking for test_ubuntu_inventory_canonical_feed.py
2021-12-22 17:05:05,255 - INFO - Run completed, documentation location: /tmp/qa_docs/output`

### Output File
[test_ubuntu_inventory_canonical_feed](https://github.com/wazuh/wazuh-qa/files/7765017/test_ubuntu_inventory_canonical_feed.zip)
