### ISSUE TITLE
qa-docs: Migrate test_windows of test_vulnerability_detector documentation to schema 2.0

### ISSUE THREAD

**Issue by fedepacher** [wazuh/wazuh-qa#2328]
### Description

This issue is created to migrate the `test_vulnerability_detector` documentation to the new QA Docs schema as part of the epic https://github.com/wazuh/wazuh-qa/issues/1796.

In the QA Wiki there are two entries to help complete the tasks:

- [Documenting tests using the QA Docs schema](https://github.com/wazuh/wazuh-qa/wiki/QA-Documentation---How-to-document-a-test-using-Schema-2.0): This entry describes the steps needed to document the tests (schema to use, the position of blocks, allowed values for fields, etc.).
- [Documentation generation with DocGenerator tool](https://github.com/wazuh/wazuh-qa/wiki/QADOCS-tool-use-guide): Here is a brief description of how the `qa-docs` module works to verify that the changes made in the tests have been done correctly.

#### Main branch
`2328-qa-docs-migrate-test-windows `
#### Tasks
- [x] Migrate tests:
  - [x] **test_windows**
    - [x] `test_cpe_indexing.py`
- [x] Check `PEP-8` style guide (`pycodestyle --max-line-length=120`)
- [x] Ckeck with QA-Doc style format
- [ ] Merge issue branch to  `master`

**Comment by fedepacher** [comment]
- Style guide (pycodestyle --max-line-length=120) (PASSED) 🟢 

## QA-docs execution 

### test_providers_enabled
`qa-docs --tests-path ../test_vulnerability_detector/test_windows/ -t test_cpe_indexing`

### Results
`2021-12-24 15:07:37,779 - INFO - Looking for test_cpe_indexing.py
2021-12-24 15:07:37,779 - INFO - Parsing the following test(s) ['test_cpe_indexing']
2021-12-24 15:07:37,793 - INFO - Running QADOCS
2021-12-24 15:07:37,793 - INFO - Looking for test_cpe_indexing.py
2021-12-24 15:07:37,969 - INFO - Run completed, documentation location: /tmp/qa_docs/output`

### Output File
[test_cpe_indexing.zip](https://github.com/wazuh/wazuh-qa/files/7774982/test_cpe_indexing.zip)
