### ISSUE TITLE
Ansible PR Pipeline: Create Manager + Agent scenario

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-qa#237]
**Wazuh version:** Any

**Elastic version:** Any

**Environment:**

Ansible PR tests in Jenkins

**Is this a bug report or a feature requests?:**

Feature request

**What is the current behavior?**

The Wazuh Agent installation is not being tested. I recently faced installations errors on Amazon Linux 2 when installing Wazuh Agent.

Those errors could be easily detected by a scenario of Manager + Agent (installation and registration)

**What is the motivation/use case for changing the behavior?**

Implement a scenario that installs Manager and Agent and connects them.

**Description**: 

Tasks required to implement this change are:

### Tasks

- [x] Develop required scenario of Manager + Agent

- [x] Test scenario manually and verify the Agent installs and registers properly

- [x] Update documentation and CHANGELOG.md

Best regards,

Jose

**Comment by xr09** [comment]
The scenario is running and passing the tests, tried first CentOS 7, testing other platforms now.

![Screenshot_20191105_165044](https://user-images.githubusercontent.com/1380243/68223083-69913700-ffec-11e9-844c-a668996688ff.png)

The agent was registered correctly, one of the tests is checking this.

```
def test_agents_registered_on_manager(host):
    cmd = host.run("/var/ossec/bin/manage_agents -l")
    assert 'agent_{}'.format(MOL_PLATFORM) in cmd.stdout
```

```
[root@manager_centos7 /]# /var/ossec/bin/manage_agents -l

Available agents: 
   ID: 001, Name: agent_centos7, IP: 172.18.0.3
```

**Comment by jm404** [comment]
Done in #240
