### ISSUE TITLE
Logcollector - Test 'multiline_regex' configuration in 'localfile'

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh-qa#2413]
| Wazuh version | Component | Install type |
| -- | -- | -- |
| 4.2.0 | Logcollector | Manager/Agent |

# Context

The localfile configurations tests were created in issue #1144 and a new option called `multiline_regex` was added in 4.2.0. That option was requested in wazuh/wazuh#5652. So, we need to cover the multiline_regex option with its different values.

# Objetive

To cover all the configurations in `localfile` we must test the `multiline_regex` option with its different attributes, using valid and invalid values.

# Tasks

The basic use of multiline_regex is described in wazuh/wazuh#6670

- [ ] Define all the possible combinations of attributes and values (valid and invalid combinations)
- [ ] Create a YAML with these combinations and the expected result for each
- [ ] Parse the YAML file and set the configuration
- [ ] Compare the configuration result with the expected result
- [ ] Document the test

**Comment by fedepacher** [comment]
# Update 2023/01/26

At this point, it has the template of the test where the manager and agent are configurated with the required `localfile` option.
For the analysis of the different cases, it is reading the following [pull request](https://github.com/wazuh/wazuh/pull/6670).

**Comment by vikman90** [comment]
Closing this issue. Superseded by version 5.0.
