### ISSUE TITLE
Prepare `filesystem_integrity` release

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh-qa#2432]
# Description

We want to add a filesystem integrity test developed in #2231, but lastly, we need to do some arrangements.

# Tasks

 - [x] Move the test to `system/filesystem_integrity`
 - [x] Fix `gid` issue: there are some files that cannot retrieve their `gid` because it is not mapped in `/etc/group` after an installation
 - [x] Add README
 - [ ] Check that works in Windows
 - [x] Merge these changes to the epic branch
 - [x] Create PR to master
 - [ ] Create release 4.3.0 - rc3 issue 

# Additional tasks

- [x] Research about the cost of adding agent support

**Comment by roronoasins** [comment]
Working branch: [2432-prepare-filesystem-integrity](https://github.com/wazuh/wazuh-qa/tree/2432-prepare-filesystem-integrity)

**Comment by roronoasins** [comment]
In Windows, it raises an error when running `qa-ctl` via launcher, because the configuration file generated has no config section and Windows expects a `qa-branch`. If this is fixed, the docker run returns `1` as result code(maybe is a timeout because my native windows are very slow).
