### ISSUE TITLE
Research on Vulnerability Detector status in order to merge new tests to master 

### ISSUE THREAD

**Issue by fedepacher** [wazuh/wazuh-qa#2448]
This issue pretends to research the status of the vulnerability detector module associated with issues 7749 and 8727 merged to wazuh/wazuh release 4.3. 

### Tasks
- [ ] Study how the VDT module works
- [ ] Understand the new principle of VDT flow

Based on the description of issue 7749, it pretends to study the workflow of the pull request 1243 of wazuh/wazuh-qa repository.

### Tasks
- [ ] Check files changed
- [ ] Check that the test matches with the changes  of issues 7749 and 8727
- [ ] Launch 3 local instances of the tests and check the status in 4.3
- [ ] Launch 3 Jenkins instances of the tests and check the status in 4.3 
- [ ] Check for failed tests and fix them
- [ ] Check for expected failures
- [ ] Check for the skipped tests based on other issues and fix them
