### ISSUE TITLE
Full green of vulnerability detector for 4.3

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#2450]
In `4.3` version new changes have been added to the vulnerability detector module. Consequently, it has also been necessary to modify the corresponding integration tests.

We want to have a "full green" state, in which all tests are stable and reliable. To this end, a health check of the vulnerability detector tests is requested, and disable those that fail or are unstable.

- [x] https://github.com/wazuh/wazuh-qa/issues/2448
- [x] https://github.com/wazuh/wazuh-qa/issues/2451
- [x] https://github.com/wazuh/wazuh-qa/issues/2452

**Comment by jmv74211** [comment]
We have "full green" (many tests disabled) in the `dev-cves-alerts-inventory` branch.
