### ISSUE TITLE
Vulnerability detector test suite refactor: Basic configuration

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#2460]
We want to fix and refactor the following integration tests:

- [x] https://github.com/wazuh/wazuh-qa/issues/2461
- [x] https://github.com/wazuh/wazuh-qa/issues/2455
- [x] https://github.com/wazuh/wazuh-qa/issues/2469
- [x] https://github.com/wazuh/wazuh-qa/issues/2463
- [x] https://github.com/wazuh/wazuh-qa/issues/2464
- [x] https://github.com/wazuh/wazuh-qa/issues/2465
- [x] https://github.com/wazuh/wazuh-qa/issues/2467
- [x] https://github.com/wazuh/wazuh-qa/issues/2517
