### ISSUE TITLE
Refactor of the testing framework for vulnerability_detector

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#2462]
Refactoring the testing framework for vulnerability_detector

So far, the module structure of the QA framework for vulnerability detector is quite simple and messy. Basically everything used for vulnerability detector testing is located in the `vulnerability_detector.py` module without taking into account that much of that functionality is duplicated or can be used by other different modules.

A refactor of the testing framework for vulnerability detector is requested, designing a reusable organization separated by functionalities.

After such a rework, the same results should be obtained in all related testing as at the beginning.

## Tasks

- [x] Perform modular and reusable design.
- [x] Review used functions and refactor them.
- [x] Distribute functions in the new modules.
- [x] Update all the code that uses the modified testing framework.
- [x] Test that all tests involved work correctly (using the modified testing framework).
