### ISSUE TITLE
Vulnerability detector test module refactor: `test_providers_os`

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#2464]
It is asked to refactor the test module named `test_providers_os.py`.

It is disabled for now, as it was failing or unstable, causing false positives.

## Tasks

- [x] Make a study of the objectives of the test, and what is being tested.
- [x] Refactor the test. Clean and modularizable code.
- [x] Check that the test always starts from the same state and restores it completely at the end of the test (independent of the tests previously executed in that environment).
- [x] Review test documentation, and modify if necessary.
- [x] Proven that tests **pass** when they have to pass.
- [x] Proven that tests **fail** when they have to fail.
- [ ] Test in 5-10 rounds of execution that the test always shows the same result.

## Checks

- [ ] The code complies with the standard PEP-8 format.
- [ ] Python codebase is documented following the Google Style for Python docstrings.
- [ ] The test is processed by `qa-docs` tool without errors.

**Comment by fedepacher** [comment]
## Test design

### Name

`test_providers_os.py`

---

### Objective

Check if modulesd downloads the feeds for each os version.

---

### Test checks

- Check that the feeds download and index it in the database.

---

### Initial stage (setup)

- All modules except vulnerability detector must be disabled
- `cve.db` tables must be empty.
- Clean the `ossec.log` file

---

### Test phases

**Diferent providers cases**

- Update `ossec.conf` configuration
- Restart `wazuh-modulesd` daemon
- Monitor `ossec.log` and check the provider update log.
- Monitor `ossec.log` and wait until the provider database is updated.
- Query the vulnerabilities table rows number for that provider (must be >0).

---

### Final stage (teardown)

- `cve.db` tables must be empty.
- Initial `ossec.conf` file must be restored.
- Clean the `ossec.log` file

---

### Test cases (7 total):

- `{'PROVIDER': 'alas', 'OS': 'amazon-linux'}`
- `{'PROVIDER': 'alas', 'OS': 'amazon-linux-2'}`
- `{'PROVIDER': 'canonical', 'OS': 'trusty'}`
- `{'PROVIDER': 'canonical', 'OS': 'xenial'}`
- `{'PROVIDER': 'canonical', 'OS': 'bionic'}`
- `{'PROVIDER': 'debian', 'OS': 'stretch'}`
- `{'PROVIDER': 'debian', 'OS': 'buster'}`
- `{'PROVIDER': 'redhat', 'OS': '5'}`
-  `{'PROVIDER': 'redhat', 'OS': '6'}`
- `{'PROVIDER': 'redhat', 'OS': '7'}`
- `{'PROVIDER': 'redhat', 'OS': '8'}`
- `{'PROVIDER': 'nvd', 'OS': ''}`
- `{'PROVIDER': 'msu', 'OS': ''}`
