### ISSUE TITLE
Update `test_integrity_sync` system test

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh-qa#2475]
## Description

It is necessary to update the [test_integrity_sync](https://github.com/wazuh/wazuh-qa/blob/master/tests/system/test_cluster/test_integrity_sync/test_integrity_sync.py) system test to verify the correct operation of the synchronization in the cluster after the changes performed in https://github.com/wazuh/wazuh/issues/11945. That includes:
- [x] Check that the dynamic zip size limit increases or decreases according to what is set in https://github.com/wazuh/wazuh/issues/11946.
- [x] Create multiple groups with files inside and determine if the content of multigroups is correctly synced when using `zlib` (developed in https://github.com/wazuh/wazuh/issues/11184).
- [x] Check that the zips do not exceed the maximum allowed size (https://github.com/wazuh/wazuh/issues/10980).
- [x] Check that the task is canceled after a timeout (https://github.com/wazuh/wazuh/issues/10735).

**Comment by Selutario** [comment]
## Status update

To carry out what is requested in this test, it will be necessary to modify the following file in all the managers of the environment:
```
/var/ossec/framework/python/lib/python*/site-packages/wazuh-*-py*.egg/wazuh/core/cluster/cluster.json
```

I've added new methods to the HostManager class to find a file recursively (since the path will change in each version). I am also creating a fixture that modifies the content of the `cluster.json` before starting the tests (module scope) and restores it at the end.

It will be necessary to add new tests for some of the requisites, while for others it will be enaugh with modifying the existing ones.

**Comment by Selutario** [comment]
## Status update

To check the correct operation of the zip size limitation, as well as the rest of the requirements, the test will follow these steps:
- Reduce timeout var (`timeout_receiving_file`) for files reception (in `cluster.json`).
- Create many large files (1 MB) in the master node.
- Create a file that exceeds the maximum size in master node.
- Monitor logs and capture these messages:
  - `File too large to be synced: X`
  - `Decreasing sync size limit to X MB`
  - `Increasing sync size limit to X MB`

I have updated some of the existing tests so that they generate binary code files and check their correct synchronization. Now I'm looking into the fastest way to generate a large number of files in Ansible, since each individual command execution is slow.

**Comment by Selutario** [comment]
## Status update

The test is almost working and, based on the captured logs, it is able to determine if everything mentioned [here](https://github.com/wazuh/wazuh-qa/issues/2475#issue-1113919430) is fulfilled. In short, this is what it does:
- Update the `cluster.json` to reduce the timeout and maximum zip size.
- Create multiple files that are big but do not exceed the maximum size.
- Create a file which is too big to be synced.
- Logs are monitored to determine if [requirements](https://github.com/wazuh/wazuh-qa/issues/2475#issue-1113919430) are met.

**Comment by Selutario** [comment]
## Status update

An encoding error was reported here: https://github.com/wazuh/wazuh-qa/pull/2582#pullrequestreview-892155945. 

The reason for the error is that now, in the missing files test, files with random content (which is usually largely binary) are created. Then, the test tries to compare the content of the file between multiple cluster nodes, but there may be characters that Python can't handle correctly.

To fix it, I now use the `stat` ansible method, which returns, among other parameters, the checksum of the file. When comparing checksums there should be no danger of causing a Python error like the one reported. It worked fine when I run the test:
```
python3 -m pytest test_integrity_sync.py -vv
============================================================================================ test session starts ============================================================================================
platform linux -- Python 3.8.10, pytest-5.0.0, py-1.8.2, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
metadata: {'Python': '3.8.10', 'Platform': 'Linux-5.4.0-99-generic-x86_64-with-glibc2.29', 'Packages': {'pytest': '5.0.0', 'py': '1.8.2', 'pluggy': '0.13.1'}, 'Plugins': {'metadata': '1.10.0', 'html': '3.1.1', 'testinfra': '5.0.0', 'tavern': '1.2.2', 'pep8': '1.0.6', 'cov': '2.10.0', 'asyncio': '0.14.0'}}
rootdir: /home/selu/Git/wazuh-qa/tests/system/test_cluster/test_integrity_sync
plugins: metadata-1.10.0, html-3.1.1, testinfra-5.0.0, tavern-1.2.2, pep8-1.0.6, cov-2.10.0, asyncio-0.14.0
collected 5 items                                                                                                                                                                                           

test_integrity_sync.py::test_missing_file PASSED                                                                                                                                                      [ 20%]
test_integrity_sync.py::test_shared_files PASSED                                                                                                                                                      [ 40%]
test_integrity_sync.py::test_extra_files PASSED                                                                                                                                                       [ 60%]
test_integrity_sync.py::test_extra_valid_files PASSED                                                                                                                                                 [ 80%]
test_integrity_sync.py::test_zip_size_limit[5] PASSED                                                                                                                                                 [100%]

======================================================================================== 5 passed in 824.26 seconds =========================================================================================
```

To avoid the API token error that occurs in the extra_valid files test, simply increase the token lifetime on the master before running the test.
