### ISSUE TITLE
Make simple syscheck automated tests work for MacOS platform

### ISSUE THREAD

**Issue by vicferpoy** [wazuh/wazuh-qa#248]
| Working branch |
| --- |
|[dev-248-macos](https://github.com/wazuh/wazuh-qa/tree/dev-248-macos)|

## Description
Now that we have a decent set of integration tests for simple configurations, we should make them work for MacOS agents too. 

## Tasks
- [x] Prepare an environment to run syscheck in a MacOS agent
- [x] Assure only scheduled monitoring will be tested in a MacOS agent

Run all simple tests iteratively until the same results as Unix tests are obtained:
- [ ] ~test_audit~ (whodata is not available on MacOS)
- [x] test_basic_usage
- [ ] ~test_benchmark~
- [x] test_checks
- [x] test_ignore
- [x] test_invalid
- [x] test_nodiff
- [ ] ~test_prefilter_cmd~
- [x] test_recursion_level
- [x] test_report_changes
- [x] test_restrict
- [x] test_scan
- [ ] ~test_sync~ (No need to test this on MacOS as it's a Manager only functionality)
- [x] test_tags
- [x] test_ambiguous_configurations
- [x] test_skip (skip_nfs and skip_dev)

**Comment by vicferpoy** [comment]
# Status update
We cannot test anything due to a compilation error with the agent on MacOS.
This is reported and we will continue the tests once it is fixed.

**Comment by vicferpoy** [comment]
# Status update

Package compilation for MacOS was fixed and we already have a working environment. We are working on the test adaptation to make them work in MacOS.

**Comment by vicferpoy** [comment]
# Status update

Tests are working. We are facing errors in some tests due to the MacOS agent getting disconnected everytime we modify the system date or time. 

As soon as this gets fixed we will resume this issue.

**Comment by vicferpoy** [comment]
# Status update

FIM integration tests are now adapted for MacOS.
