### ISSUE TITLE
E2E test: Auditing commands run by user

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh-qa#2482]
# Context
[This](https://github.com/wazuh/wazuh/wiki/Proof-of-concept-guide#auditing-commands-run-by-user) use case needs to be tested automatically to speed up the testing process.

# Tasks
Following the [guide](https://github.com/wazuh/wazuh/wiki/Proof-of-concept-guide#auditing-commands-run-by-user), is necessary to achieve these tasks to successfully test the scenario:
## In the agent:
- [x] Check that `auditd` daemon is running
- [x] Check the `auditd` configuration
- [x] Configure `audit` to audit commands run by the user
- [x] Generate an alert as the previously configured user

### Test:
- [x] Test that the alert is generated as is expected

## DoD

- [x] Python codebase satisfies PEP-8 style style guide. `pycodestyle --max-line-length=120 --show-source --show-pep8 file.py`.
- [x] QA-Docs executed from branch `1864-qa-docs-fixes`
- [x] Prove that the tests fail when they have to
- [x] Prove that the tests pass when they have to
- [x] 3 local executions (Generate the report)
- [ ] 3 Jenkins executions (Link the job in Jenkins)

**Comment by ani-albano** [comment]
Working branch 2482-test-auditing-commands
