### ISSUE TITLE
E2E test: AWS infrastructure monitoring

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh-qa#2483]
# Context
We need to create a test based on [this](https://github.com/wazuh/wazuh/wiki/Proof-of-concept-guide#amazon-aws-infrastructure-monitoring) use case.

# Tasks
Is necessary to achieve these tasks to successfully test the scenario:
## In the manager
- [ ] Enable the aws-s3 wodle in `/var/ossec/etc/ossec.conf`
- [ ] Restart the manager
- [ ] Generate alerts in AWS
- [ ] Test that the alerts are generated as is expected
