### ISSUE TITLE
E2E test: Detecting a brute-force attack

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh-qa#2484]
# Context
We need to create a test based on [this](https://github.com/wazuh/wazuh/wiki/Proof-of-concept-guide#brute_force) use case.

# Tasks
Is necessary to achieve these tasks to successfully test the scenario:
- [ ] Configure an agent (CentOS) with ssh
- [ ] Configure an agent (Windows) with RDP
- [ ] Generate alerts in both endpoints (using ssh, and hydra for RDP)
- [ ] Test that the alerts are generated as is expected
