### ISSUE TITLE
Wazuh-DB: Migration of agent-group files

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#2504]
## Description 

This issue is part of Epic: [Migrate agent group files to wazuh-db](https://github.com/wazuh/wazuh/issues/10771).

After a meeting with the teams involved, a series of scenarios were defined to take into account when validating the changes made.

This epic contains the list of systems tests and Integration tests that we will start working on with the team.

### System Tests
- [x] https://github.com/wazuh/wazuh-qa/issues/2507
- [x] https://github.com/wazuh/wazuh-qa/issues/2506
- [x] https://github.com/wazuh/wazuh-qa/issues/2508
- [x] https://github.com/wazuh/wazuh-qa/issues/2513
- [x] https://github.com/wazuh/wazuh-qa/issues/2516 (*)
- [x] https://github.com/wazuh/wazuh-qa/issues/2505
- [x] https://github.com/wazuh/wazuh-qa/issues/2512
- [x] https://github.com/wazuh/wazuh-qa/issues/2511
- [x] https://github.com/wazuh/wazuh-qa/issues/2510
- [x] https://github.com/wazuh/wazuh-qa/issues/2514
- [x] https://github.com/wazuh/wazuh-qa/issues/2515

### Integration Tests

- [x] https://github.com/wazuh/wazuh-qa/issues/2584
- [x] https://github.com/wazuh/wazuh-qa/issues/2532

**Comment by damarisg** [comment]
> 2022/04/19
- Issue https://github.com/wazuh/wazuh-qa/issues/2516 blocked by https://github.com/wazuh/wazuh/issues/13172
- In `wazuh-qa` repository a branch was created to merge with the master when all WazuhDB development is in `wazuh`  repository.
