### ISSUE TITLE
Vulnerability detector test suite refactor: Scan results

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#2519]
We want to fix and refactor the following integration tests:

- [x] https://github.com/wazuh/wazuh-qa/issues/2520
- [x] https://github.com/wazuh/wazuh-qa/issues/2521
- [x] https://github.com/wazuh/wazuh-qa/issues/2522
- [x] https://github.com/wazuh/wazuh-qa/issues/2523
- [x] https://github.com/wazuh/wazuh-qa/issues/2524
- [x] https://github.com/wazuh/wazuh-qa/issues/2525
- [x] https://github.com/wazuh/wazuh-qa/issues/2526
- [x] https://github.com/wazuh/wazuh-qa/issues/2527
- [x] https://github.com/wazuh/wazuh-qa/issues/2528
- [x] https://github.com/wazuh/wazuh-qa/issues/2529
- [x] https://github.com/wazuh/wazuh-qa/issues/2530
- [x] https://github.com/wazuh/wazuh-qa/issues/2531
