### ISSUE TITLE
Vulnerability detector test module refactor: `test_alert_vulnerability_removal`

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#2520]
It is asked to refactor the test module named `test_alert_vulnerability_removal.py`.

It is disabled for now, as it was failing or unstable, causing false positives.

## Tasks

- [x] Make a study of the objectives of the test, and what is being tested.
- [x] Refactor the test. Clean and modularizable code.
- [x] Check that the test always starts from the same state and restores it completely at the end of the test (independent of the tests previously executed in that environment).
- [x] Review test documentation, and modify if necessary.
- [x] Proven that tests **pass** when they have to pass.
- [x] Proven that tests **fail** when they have to fail.
- [x] Test in 5-10 rounds of execution that the test always shows the same result.
- [x] Run all Vulnerability detector integration tests and check the "full green".

## Checks

- [x] The code complies with the standard PEP-8 format.
- [x] Python codebase is documented following the Google Style for Python docstrings.
- [ ] The test is processed by `qa-docs` tool without errors.

**Comment by fedepacher** [comment]
## Test design

### Name

`test_alert_vulnerability_removal.py`

---

### Objective

Check that the Vulnerability Detector module generates an alert when a vulnerability is removed from the inventory.

---

### Test checks

- Check that the alerts are generated when a package is removed and the other package is updated for a non-vulnerable version. 

---

### Initial stage (setup)

- All modules except vulnerability detector must be disabled
- `cve.db` tables must be empty.
- Clean the `ossec.log` file
- Insert vulnerable packages in vuln_cves table of agent db.
- Insert offline feeds

---

### Test phases

**Test cases**

- Update `ossec.conf` configuration.
- Restart `wazuh-modulesd` daemon.
- Monitor `ossec.log` and wait until the provider database is updated.
- Delete a vulnerable package in the agent database.
- Update package with a non-vulnerable version.
- Monitor `alerts.json` and wait for removal package message.
- Check that the vulnerable packages are removed from vuln_cve table of the database.

---

### Final stage (teardown)

- `cve.db` tables must be empty.
- `000.db` tables must be empty.
- Initial `ossec.conf` file must be restored.
- Clean the `ossec.log` file.
- Clean the `alerts.json` file.

---

### Test cases (1 total):

- `{'PROVIDER_1': 'redhat', 'OS': '8'
     'PROVIDER_2': 'nvd', 'OS': ' '}`
