### ISSUE TITLE
Vulnerability detector test module refactor: `test_redhat_duplicate_vulns`

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#2525]
It is asked to refactor the test module named `test_redhat_duplicate_vulns.py`.

It is disabled for now, as it was failing or unstable, causing false positives.

## Tasks

- [ ] Make a study of the objectives of the test, and what is being tested.
- [ ] Refactor the test. Clean and modularizable code.
- [ ] Check that the test always starts from the same state and restores it completely at the end of the test (independent of the tests previously executed in that environment).
- [ ] Review test documentation, and modify if necessary.
- [ ] Proven that tests **pass** when they have to pass.
- [ ] Proven that tests **fail** when they have to fail.
- [ ] Test in 5-10 rounds of execution that the test always shows the same result.
- [ ] Run all Vulnerability detector integration tests and check the "full green".

## Checks

- [ ] The code complies with the standard PEP-8 format.
- [ ] Python codebase is documented following the Google Style for Python docstrings.
- [ ] The test is processed by `qa-docs` tool without errors.

**Comment by fedepacher** [comment]
## Test design

### Name

`test_duplicate_feeds.py`

---

### Objective

Check that the vulnerabilities are not repeated in the database when it is updated.

---

### Test checks

- Check database `cve.db` that contains the same number of vulnerabilities inserted after updating the feeds.

---

### Initial stage (setup)

- All modules except vulnerability detector must be disabled
- `cve.db` tables must be empty.
- Clean the `ossec.log` file
- Insert vulnerable packages in vuln_cves table of agent db.
- Insert offline feeds

---

### Test phases

**Test cases**

- Update `ossec.conf` configuration.
- Restart `wazuh-modulesd` daemon.
- Monitor `ossec.log` and wait until the provider database is updated.
- Check the number of vulnerabilities inserted.
- Wait for the next update of the feed.
- Check again the number of vulnerabilities inserted.
- Check that the number of vulnerabilities inserted before updating is the same as the number of vulnerabilities after updating.

---

### Final stage (teardown)

- `cve.db` tables must be empty.
- Initial `ossec.conf` file must be restored.
- Clean the `ossec.log` file.

---

### Test cases (1 total):

- `{'PROVIDER': 'redhat', 'OS': '8'
     'PROVIDER': 'debian', 'OS': 'buster'
     'PROVIDER': 'canonical', 'OS': 'bionic'
     'PROVIDER': 'alas', 'OS': 'amazon-linux'
     'PROVIDER': 'arch', 'OS': ' '
     'PROVIDER': 'nvd', 'OS': ' '
     'PROVIDER': 'msu', 'OS': ' '}`
