### ISSUE TITLE
Vulnerability detector test module refactor: `test_scan_different_cves`

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#2527]
It is asked to refactor the test module named `test_scan_different_cves.py`.

It is disabled for now, as it was failing or unstable, causing false positives.

## Tasks

- [ ] Make a study of the objectives of the test, and what is being tested.
- [ ] Refactor the test. Clean and modularizable code.
- [ ] Check that the test always starts from the same state and restores it completely at the end of the test (independent of the tests previously executed in that environment).
- [ ] Review test documentation, and modify if necessary.
- [ ] Proven that tests **pass** when they have to pass.
- [ ] Proven that tests **fail** when they have to fail.
- [ ] Test in 5-10 rounds of execution that the test always shows the same result.
- [ ] Run all Vulnerability detector integration tests and check the "full green".

## Checks

- [ ] The code complies with the standard PEP-8 format.
- [ ] Python codebase is documented following the Google Style for Python docstrings.
- [ ] The test is processed by `qa-docs` tool without errors.

**Comment by jmv74211** [comment]
This issue es closed in favor of https://github.com/wazuh/wazuh-qa/issues/2690 due to it is necessary to design the possible combination cases and develop a new testing module.
