### ISSUE TITLE
Optimize Molecule image creation process

### ISSUE THREAD

**Issue by xr09** [wazuh/wazuh-qa#253]
### Description

Molecule's default behavior is to build images capable of testing Ansible from a vendor default image, this is no longer needed since it is possible to build a molecule-ready images which can safely bypass the build step.

Among the most used images in the community are [paulfantom's](https://hub.docker.com/u/paulfantom/) and [geerlinguy's](https://hub.docker.com/u/geerlingguy/).

### Tasks
- [x] Switch to molecule-ready images
- [x] Remove the image build step
- [x] Test all roles with this new workflow
