### ISSUE TITLE
Add more Kitchen scenarios and unit tests

### ISSUE THREAD

**Issue by rshad** [wazuh/wazuh-qa#256]
Hi all!

We propose to make the testing approach more complete for `wazuh-chef` by adding more Kitchen testing suites and the corresponding unit tests.

**Tasks to Do**

- [X] Add Testing Suites (Elasticsearch, Kibana and Ngina SSL Authentication for Kibana)

- [X] Add the corresponding unit tests for each suite.
- - [X] Elasticsearch
- - [X] Kibana
- - [X] Ngina SSL Authentication for Kibana.

- [X] Test the changes.

`Note`: This description may be updated in the future if needed.

Kr,

Rshad

**Comment by rshad** [comment]
Hi all!

Today started the implementation of the required tasks and we reached to have done:

1. Add the corresponding suite configuration for a unique global suite for all 3 components.
2. Add the corresponding unit tests for Elasticsearch and Kibana.

Let's comment on some details!

- When running the following task from the cookbook [`cookbooks/wazuh_elastic/recipes/repository.rb`](https://github.com/wazuh/wazuh-chef/blob/devel/cookbooks/wazuh_elastic/recipes/repository.rb#L14-L21)

```ruby
  apt_repository "elastic-7.x" do
    uri "https://artifacts.elastic.co/packages/7.x/apt"
    key "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    distribution "stable"
    components ["main"]
    not_if do
      File.exists?("/etc/apt/sources.list.d/elastic-7.x.list")
    end
```

We got the error message:
```
“ERROR: The method driver /usr/lib/apt/methods/https could not be found.”
```

To solve this issue, we need to first install the packages:
- apt-transport-https 
- ca-certificates
```
apt-get install apt-transport-https ca-certificates
```

To do so, `kitchen-docker` provides a directive `provision_command` to run provisioning commands in the container creation time, so the solution would be:

https://github.com/wazuh/wazuh-qa/blob/85e7bad5dd978123a9a67114db9e3e0eb96fed92/kitchen/wazuh-chef/manager/files/kitchen.yml#L12-L13


- The complete suite, look like:

https://github.com/wazuh/wazuh-qa/blob/4f48ab73de15b977820689abdb71168d15d7e745/kitchen/wazuh-chef/manager/files/kitchen.yml#L64-L86

- - As you can see we assign the IP `127.0.0.1` as Elasticsearch IP.

https://github.com/wazuh/wazuh-qa/blob/4f48ab73de15b977820689abdb71168d15d7e745/kitchen/wazuh-chef/manager/files/kitchen.yml#L80

- - We also specify the order in which the cookbooks will be executed:

https://github.com/wazuh/wazuh-qa/blob/4f48ab73de15b977820689abdb71168d15d7e745/kitchen/wazuh-chef/manager/files/kitchen.yml#L75-L79

- - Finally we specify our unit test verifier and the script's path:

https://github.com/wazuh/wazuh-qa/blob/4f48ab73de15b977820689abdb71168d15d7e745/kitchen/wazuh-chef/manager/files/kitchen.yml#L84-L86

The tests are simple, in which we check if Elasticsearch is installed or not, it's version, it's enabled or not and if it's running or not. 

https://github.com/wazuh/wazuh-qa/blob/4f48ab73de15b977820689abdb71168d15d7e745/kitchen/wazuh-chef/manager/test/base/test_wazuh_elastic.py#L1-L19

Unfortunately, `Testinfra-Pytest` failed when checking if the service is running however when the check it manually we find it up and running with no errors. We think that this error is caused because the docker image we use does not have `systemd` installed and it's a requirement for `Testinfra` in this case. `Being investigated`.

Kr,

Rshad

**Comment by rshad** [comment]
Hi all!

Today we were working on adding new tests and adapt the tests so they could be more dynamical when checking tested components versions. 

- For Dynamical Approach, check https://github.com/wazuh/wazuh-qa/issues/259

- We also added new tests for Kibana functionality testing:

https://github.com/wazuh/wazuh-qa/blob/5c356b77cd77b61c644d6b0fe51e54ace8299573/kitchen/wazuh-chef/manager/test/base/test_wazuh_elastic.py#L27-L41

Kr,

rSHAD

**Comment by rshad** [comment]
Hi all!

We added a simple test just to check if the port 443 is open and therefore we suppose Nginx is listening on it.

https://github.com/wazuh/wazuh-qa/blob/ee282aac4da3f124536f1c9ba84705e0c9d60d7e/kitchen/wazuh-chef/manager/test/base/test_wazuh_elastic.py#L35-L37

Kr,

Rshad
