### ISSUE TITLE
qa-docs: Adapt the tool to the framework rework

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh-qa#2588]
# Description
As we are making a rework of the testing framework, we need to check and adapt the `qa-docs` tool to this rework.

Also, this issue will finish the 0.1 development that was blocked by `SearchUI`. So, this issue will extend #1864 and #2196 will be sent to the Icebox. Then, we can continue with #2075, closing both of them.

# Tasks
- [x] Test the tool with the rework environment and get the needed changes
- [x] Adapt qa-docs to the framework rework
  - [x] Add `--suites` parameter
  - [x] Rename `--modules` as `--components`
  - [x] Rename `--tests` as `--modules`
  - [x] Change the behavior when parsing a single module. With the rework now different suites have modules with the same module name

**Comment by roronoasins** [comment]
The way we name the test framework items has changed, so it is needed to change some qa-docs parameters, code, and doc to avoid any confusion:

- type: integration, system, etc.
- component: test_vulnerability_detector, test_fim, etc.
- suite: test_general_settings, test_scan_results, etc
- module: test_enabled, test_min_full_scan_interval
- test: test within a module
