### ISSUE TITLE
Adapt the usage of qa-docs in qa-ctl related to the framework changes

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh-qa#2589]
# Description
We are working on a framework rework that may cause some changes to `qa-docs` and how it is used. This implies that `qa-ctl` must change the way it uses `qa-docs`.

# Tasks
- [x] Change the `qa-docs` command in `qa-ctl`
- [x] Update `-e` parameter in `qa-docs`
- [x] Check that `qa-ctl` creates the configuration file correctly
- [x] Check that `qa-ctl` runs modules correctly

**Comment by roronoasins** [comment]
```bash
$ qa-ctl --run --test-types integration --test-components test_api --test-suites test_config --test-modules test_https --qa-branch 2589-update-qa-ctl -dd
.
.
.
============================= test session starts ==============================
platform linux -- Python 3.6.8, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /tmp/wazuh_qa_ctl/wazuh-qa/tests/integration, configfile: pytest.ini
plugins: metadata-1.11.0, testinfra-5.0.0, html-3.1.1
collected 4 items

test_api/test_config/test_https/test_https.py .ss.                       [100%]

- generated html file: file:///tmp/wazuh_qa_ctl/wazuh-qa/tests/integration/reports/test_report_2022_03_07_10_25_18_133685.html -
======================== 2 passed, 2 skipped in 38.77s =========================


2022-03-07 10:26:02,902 - INFO - The test run is finished
2022-03-07 10:26:02,902 - INFO - The results of /tmp/wazuh_qa_ctl/wazuh-qa/tests/integration/test_api/test_config/test_https/test_https.py tests have been saved in /tmp/wazuh_qa_ctl/test_https_1646644885.167545
2022-03-07 10:26:02,902 - INFO - Destroying 1 instances
==> manager-test-https-1646644885-167044: Forcing shutdown of VM...
==> manager-test-https-1646644885-167044: Destroying VM and associated drives...
2022-03-07 10:26:07,090 - INFO - The instances have been destroyed sucessfully

```
