### ISSUE TITLE
Dynamic unit tests when checking components versions - Kitchen

### ISSUE THREAD

**Issue by rshad** [wazuh/wazuh-qa#259]
Hi all!

In the actual approach, Wazuh's components versions are being hard-coded in the corresponding unit tests to the latest version on each release. But this way the unit tests will always fail if we want to test old releases.

To fix so, we need to make the unit tests as dynamic as possible, so we first detect which are the component's version and run the tests in correspond to it.

**Tasks to Do:**

- [x] Study the different alternative solutions.
- [x] Choose the proper one and add the corresponding configuration.
- [x] Verify the changes.

- `Note`: This description may be updated in the future if needed.

Kr,

Rshad

**Comment by rshad** [comment]
Hi all!

To do so and based on https://github.com/inspec/inspec/issues/541 and http://www.hurryupandwait.io/blog/accessing-chef-node-attributes-from-kitchen-tests

we would add a new cookbook with a unique purpose and it's `testing`. Such cookbook consists of 1 simple recipe with the following task.

```ruby
ruby_block "Save node attributes" do
  block do
    File.write("/tmp/kitchen_chef_node.json", node.to_json)
  end
end
```

This way we will save all the corresponding node's variables in a temporary file in the corresponding kitchen instance in `/tmp/kitchen_chef_node.json`.

Then and in order to load such file as a JSON object, in the testing script, we run 
```python
node = json("/tmp/kitchen_chef_node.json").params
```

**Comment by rshad** [comment]
Hi all!

We finally selected the Approach 1, and to get it implemented we followed:

1- Added the test cookbook we already described in the previous commit.

2- Include the testing cookbook in the runlist of each suite, as follows:

https://github.com/wazuh/wazuh-qa/blob/20397cd6fc2053982177498c9fdf87f058cdb563/kitchen/wazuh-chef/manager/files/kitchen.yml#L35-L36

3- Define a `Fixture` function to save load the file where the attributes were saved.
https://github.com/wazuh/wazuh-qa/blob/20397cd6fc2053982177498c9fdf87f058cdb563/kitchen/wazuh-chef/manager/test/conftest.py#L12-L14

4- For each testing script, we added a function which gets the corresponding variable/s

***manager case***
https://github.com/wazuh/wazuh-qa/blob/20397cd6fc2053982177498c9fdf87f058cdb563/kitchen/wazuh-chef/manager/test/base/test_wazuh_agent.py#L7-L11

Then we use it, as follows:
https://github.com/wazuh/wazuh-qa/blob/20397cd6fc2053982177498c9fdf87f058cdb563/kitchen/wazuh-chef/manager/test/base/test_wazuh_agent.py#L17

Kr,

Rshad
