### ISSUE TITLE
qa-docs: Update every module documentation because of schema changes

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh-qa#2591]
# Description
We may change the current documentation schema in #2590, so it is needed to update the current module and tests documentation within the repo.

This issue aims to rename some fields and add a few like `suite` but not pretend to remake the documentation.

# Tasks
- [x] Change the fields section in `schema.yaml`
- [x] Update current documentation
- [x] Add new predefined values to the `schema.yaml`
- [x] Check that `qa-docs` parses all the documented tests
- [x] Modify `-m` behavior when there are no suites or it is deeper than module-level within directories

**Comment by roronoasins** [comment]
# Parsing the whole documentation
Vulnerability detector's documentation has not been fully updated because the refactor has not been completed yet. Wazuh db has not been parsed because it has a test with the documentation missing.
```bash
qa-docs -p /tmp/wazuh-qa/tests --types integration -c test_active_response test_agentd test_analysisd test_api test_authd test_enrollment test_fim test_gcloud test_github test_logcollector test_logtest test_office365 test_remoted test_rids test_rootcheck test_wpk
2022-03-02 18:11:28,918 - INFO - Parsing the following test(s) type(s): ['integration']
2022-03-02 18:11:28,918 - INFO - Parsing the following test(s) components(s): ['test_active_response', 'test_agentd', 'test_analysisd', 'test_api', 'test_authd', 'test_enrollment', 'test_fim', 'test_gcloud', 'test_github', 'test_logcollector', 'test_logtest', 'test_office365', 'test_remoted', 'test_rids', 'test_rootcheck', 'test_wpk']
2022-03-02 18:11:28,931 - INFO - Running QADOCS
2022-03-02 18:11:30,774 - INFO - Run completed, documentation location: /tmp/qa_docs/output
```

---

Modules and tests that are not documented:

- Module block missing:
  - `integration/test_fim/test_registry/test_registry_basic_usage/test_basic_usage_registry_duplicated_entries.py`
  - `integration/test_fim/test_files/test_basic_usage/test_basic_usage_deferred_delete_folder.py`
  - `integration/test_remoted/test_agent_communication/test_agent_pending_status.py`

- Test block missing:
    - `integration/test_wazuh_db/test_wazuh_db.py` -> `test_wazuh_db_timeout`()
