### ISSUE TITLE
Vulnerability detector test module refactor: `test_download_feeds`

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#2596]
It is asked to refactor the test module named `test_download_feeds.py`.

It is disabled for now, as it was failing or unstable, causing false positives.

## Tasks

- [x] Make a study of the objectives of the test, and what is being tested.
- [x] Refactor the test. Clean and modularizable code.
- [x] Check that the test always starts from the same state and restores it completely at the end of the test (independent of the tests previously executed in that environment).
- [x] Review test documentation, and modify if necessary.
- [x] Proven that tests **pass** when they have to pass.
- [x] Proven that tests **fail** when they have to fail.
- [x] Test in 5-10 rounds of execution that the test always shows the same result.
- [x] Run all Vulnerability detector integration tests and check the "full green".

## Checks

- [x] The code complies with the standard PEP-8 format.
- [x] Python codebase is documented following the Google Style for Python docstrings.
- [x] The test is processed by `qa-docs` tool without errors.

**Comment by fedepacher** [comment]
## Test design

### Name

`test_download_feeds.py`

---

### Objective

Check that the Vulnerability Detector module downloads successfully the feeds from different providers and os.

---

### Test checks

- Check that the respective logs are generated when a feed is downloaded.

---

### Initial stage (setup)

- All modules except vulnerability detector must be disabled
- `cve.db` tables must be empty.
- Clean the `ossec.log` file

---

### Test phases

**Test cases**

- Update `ossec.conf` configuration.
- Restart `wazuh-modulesd` daemon.
- Monitor `ossec.log` and wait until the provider database is updated.
- Check that the feeds start downloading.
- Check that the feed is outdated.
- Check that the feed is in the latest version.
- Check that the feed was downloaded successfully.

---

### Final stage (teardown)

- `cve.db` tables must be empty.
- Initial `ossec.conf` file must be restored.
- Clean the `ossec.log` file.

---

### Test cases (15 total):

- `{'PROVIDER': 'redhat', 'OS': ['5', '6', '7', '8']
     'PROVIDER': 'canonical', 'OS': ['trusty', 'xenial', 'bionic', 'focal']
     'PROVIDER': 'debian', 'OS': ['stretch', 'buster']
     'PROVIDER': 'nvd', 'OS': ' '
     'PROVIDER': 'msu', 'OS': ' '
     'PROVIDER': 'arch', 'OS': ' '
     'PROVIDER': 'alas', 'OS': ['amazon-linux', 'amazon-linux-2']}`
