### ISSUE TITLE
Dynamic unit tests when checking package versions - Molecule

### ISSUE THREAD

**Issue by xr09** [wazuh/wazuh-qa#260]
### Description
Currently package versions are hardcoded on Testinfra, so for every version bump on `wazuh-ansible` we need to bump the version checks here too.

Int would be less problematic to dynamically infer the desired version to install from the role itself.

### Tasks
- [x] Study possible features of Molecule, Testinfra or Pytest to solve this
- [x] Implement changes and avoid version info duplication on Testinfra tests
- [x] Test all scenarios
