### ISSUE TITLE
Test the new changes to qa-docs `0.1` and qa-ctl 

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh-qa#2600]
# Description
With the new changes in the `qa-docs` `0.1` release(#2588 and #2590) and how `qa-ctl` uses it(#2589) it is needed to test all the new changes before their release.

# Tasks
- [x] Check that a module exists
`qa-docs -p /path/to/tests --types integration --components test_active_response --suites test_analysd -e test_os_exec`
- [x] Parse a list of modules
`qa-docs -p tests/ --types integration --components test_gcloud --suites test_functionality --modules test_day_wday test_logging`
- [x] Parse two integration components
`qa-docs -p /path/to/tests --types integration --components test_active_response test_agentd`
- [x] Parse two component suites
`qa-docs -p /path/to/tests --types integration --components test_active_response --suites test_analysd test_execd`
- [x] Index that parsed data
`qa-docs -i qa`
- [x] Launch `search-ui` with the index previously created
`qa-docs -l qa`
- [x] Parse, index and launch the app in a single run
`qa-docs -p /path/to/tests --types integration --components test_fim -il `
- [x] Docker runs
`qa-docs --docker-run --types integration --components test_api  --qa-branch 2600-test-qa-docs`
`qa-docs --docker-run --types integration --components test_api -o /tmp/testing --qa-branch 2600-test-qa-docs`
`qa-docs --docker-run --types integration --components test_api  -il qa --qa-branch 2600-test-qa-docs`
