### ISSUE TITLE
Use full package versions for testinfra tests

### ISSUE THREAD

**Issue by xr09** [wazuh/wazuh-qa#263]
### Description

When comparing package versions in testinfra we're using `package.version`, this works fine for Debian/Ubuntu systems which return the full package version in that property, but for EL/CentOS systems this value is splitted between `version` and `release`. It is required to use both properties on these systems.

### Tasks
- [x] Build a function which detects if this property exists and bundles both values
- [x] Establish a common module to import from all tests
- [x] Test this method on all scenarios
