### ISSUE TITLE
Automation of system tests in Jenkins

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#2673]
We want to be able to integrate the system tests into the continuous integration and release process. The estimated tasks are as follows:

## Preparatory tasks

- [x] https://github.com/wazuh/wazuh-qa/issues/2674
- [x] https://github.com/wazuh/wazuh-qa/issues/2675
- [x] https://github.com/wazuh/wazuh-qa/issues/2676
- [x] https://github.com/wazuh/wazuh-qa/issues/2677

## Development tasks

- [x] https://github.com/wazuh/wazuh-qa/issues/2697
- [x] https://github.com/wazuh/wazuh-qa/issues/2698
- [x] https://github.com/wazuh/wazuh-qa/issues/2699
- [x] https://github.com/wazuh/wazuh-qa/issues/2700
- [x] https://github.com/wazuh/wazuh-qa/issues/2701
