### ISSUE TITLE
Test file integrity monitoring

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh-qa#270]
# Testing: file integrity monitoring

| Version | Revision | Branch |
| --- | --- | --- |
| 3.12.0 | rev | 3.12-fim-rework-3319-symlinkconf |

## Any

- [ ] Check if ignore files and folders using tag <ignore> and restrict option (string or sregex) in both options.
- [ ] Check if delete content in _/var/ossec/queue/diff_ when deleting any tag <directories report_changes="yes">
- [ ] Check if delete content in _/var/ossec/queue/diff_ when report_changes option passed yes to no.
- [ ] Check that duplicate entries are ignored. Include entries with a trailing slash in a single comma-separated stanza.

### Linux

- [x] Check syscheck alert for files that exist when starting the agent
- [x] Check syscheck alert for adding a file
- [x] Check syscheck alert for adding text to a file
- [x] Check syscheck alert with report_changes option
- [x] Check syscheck alert for moving a file
- [x] Check syscheck alert for moving a folder with a file in it
- [x] Check syscheck alert for modifying a file
- [x] Check syscheck alert for renaming a file
- [x] Check that the add file alert does not contain modification information. To do this, create a file with content in the folder being monitored, delete it and add a new file with the name of the deleted file
- [x] Check syscheck alert for renaming a folder
- [x] Check syscheck alert for deleting a file
- [x] Check syscheck alert for deleting a folder
- [x] Check syscheck alert for changing owner of file
- [x] Check syscheck alert for changing group of file
- [x] Check syscheck alert for changing file permissions
- [x] Check values different values for options 'check_sum', 'check_md5sum', 'check_sha1sum','check_sha256sum'
- [x] Check the "nodiff" option to don't show the changes of a file
- [ ] Check syscheck flag auto_ignore with attributes "frequency" and "timeframe" (1)
- [x] Check recursion level option (recursion_level=0, recursion_level=2 check folder level 0, 1, 2 and 3)
- [ ] Check syscheck alert for nested monitoring with <tags> option
- [ ] Check syscheck alert for monitoring folder with <restrict> option

### Links

- [x] Check syscheck alert for adding a link to a file/folder.
- [x] Check syscheck doesn't generate alerts if the pointed file is modified or if content is added to the pointed folder.
- [x] Check syscheck generate modify alerts if the link changes the path where it points.
- [x] Check syscheck doesn't generate alerts if the pointed file/folder is deleted.
- [x] Check syscheck doesn't generate alerts if the pointed file/folder is restored (re-create the previous deleted file/folder.
- [x] Check syscheck alert for deleting a link to a file/folder.
- [x] Check syscheck add alerts in a monitored link that points to a folder.
- [x] Check syscheck modify alerts in a monitored link that points to a folder.
- [x] Check syscheck delete alerts in a monitored link that points to a folder.
- [x] Check syscheck doesn't generate any alerts when changing the destination of the link to another folder.
- [x] Check that, before `symlink_checker` passes the alerts are generated in the former folder (and not in the new one).
- [x] Check that, after `symlink_checker` passes the alerts are generated in the new pointed folder (and not in the former one).
- [x] Check syscheck delete alerts if the pointed folder is deleted (by the next scan) wether `symlink_checker` has been performed or not.
- [x] Restore the previously deleted folder, check that no alerts are generated in the next scan (`symlink_checker` is not performed).
- [x] Check that alerts are generated for that folder once `symlink_checker` is performed (next scan).
- [x] Delete the monitored link, check that alerts are generated in the next scan (`symlink_checker` is not performed).
- [x]  Check that no alerts are generated for the previously pointed folder once `symlink_checker` is performed (next scan).
- [x] Re-create the previously deleted link (monitored), no alerts should be generated in the pointed folder in the next scan (`symlink_checker` is not performed).
- [x] Check that the folder generates alerts again once `symlink_checker` is performed (in the next scan).
- [x] Change the destination of a monitored link to an already monitored folder. The alerts generated should remain the same as before making this operation (before `symlink_checker` is performed).
- [x] Once `symlink_checker` is performed, check that no alerts are generated from the previously pointed folder and that the already monitored folder still generating alerts with its former options.
- [x] Restore the link to point to the previous folder and wait for `symlink_checker` to be performed. Alerts should be generated in both folders as they were before.
- [x] Change the destination of a link (that points to a folder) to a file. Modify both (before `symlink_checker`). Alerts should be generated from the folder and not from the file.
- [x] Modify both again and check that this time alerts are generated from the file and not the folder.
- [x] Perform the same operation but backward: change the destination of a monitored link from a file to a folder.

### Windows

- [x] Check syscheck alert for files that exist when starting the agent
- [x] Check syscheck alert for adding a file
- [x] Check syscheck alert for adding text to a file
- [x] Check syscheck alert for deleting text from a file
- [x] Check syscheck alert for moving a file
- [x] Check syscheck alert for moving a folder with a file in it
- [x] Check syscheck alert for modifying a file
- [x] Check syscheck alert for renaming a file
- [ ] Check that the add file alert does not contain modification information. To do this, create a file with content in the folder being monitored, delete it and add a new file with the name of the deleted file
- [x] Check syscheck alert for renaming a folder
- [x] Check syscheck alert with report_changes option and `last-entry` files are stored compressed.
- [x] Check syscheck alert for changing owner of file
- [x] Check syscheck alert for changing file permissions
- [x] Check syscheck alert for changing attributes of a file
- [x] Check values diferent values for options 'check_sum', 'check_md5sum', 'check_sha1sum','check_sha256sum'
- [x] Check syscheck alert for deleting a file
- [x] Check recursion level option (recursion_level=0, recursion_level=2 check folder level 0, 1, 2 and 3)
- [x] Check syscheck alert for nested monitoring with <tags> option
- [x] Check syscheck alert for monitoring folder with <restrict> option
- [ ] Check the "nodiff" option to don't show the changes of a file
- [x] Check syscheck flag auto_ignore with attributes "frequency" and "timeframe" (1)
- [x] Check syscheck alert for monitoring windows registry with <windows_registry> option
- [x] Check syscheck alert for adding a registry with <windows_registry> option
- [x] Check syscheck alert for modifying a registry with <windows_registry> option
- [x] Check syscheck alert for delete a registry with <windows_registry> option
- [x] Check syscheck alert with "arch" option (32, 64 and both)
- [ ] Check that no double alerts when using "arch=both" option

### Linux

- [x] Check syscheck alert for files that exist when starting the agent
- [x] Check syscheck alert for adding a file
- [x] Check syscheck alert for adding text to a file
- [x] Check syscheck alert with report_changes option
- [x] Check syscheck alert for moving a file
- [ ] Check syscheck alert for moving a folder with a file in it
- [x] Check syscheck alert for modifying a file
- [x] Check syscheck alert for renaming a file
- [ ] Check that the add file alert does not contain modification information. To do this, create a file with content in the folder being monitored, delete it and add a new file with the name of the deleted file
- [ ] Check syscheck alert for renaming a folder
- [x] Check syscheck alert for deleting a file
- [x] Check syscheck alert for deleting a folder
- [x] Check syscheck alert for changing owner of file
- [x] Check syscheck alert for changing group of file
- [x] Check syscheck alert for changing file permissions
- [ ] Check values different values for options 'check_sum', 'check_md5sum', 'check_sha1sum','check_sha256sum'
- [x] Check the "nodiff" option to don't show the changes of a file
- [ ] Check syscheck flag auto_ignore with attributes "frequency" and "timeframe" (1)
- [x] Check recursion level option (recursion_level=0, recursion_level=2 check folder level 0, 1, 2 and 3)
- [ ] Check syscheck alert for nested monitoring with <tags> option
- [x] Check syscheck alert for monitoring folder with <restrict> option

### Links

- [x] Check syscheck alert for adding link to a file/folder.
- [x] Check syscheck doesn't generate alerts if the pointed file is modified or if content is added to the pointed folder.
- [x] Check syscheck generate modify alerts if the link changes the path where it points.
- [x] Check syscheck doesn't generate alerts if the pointed file/folder is deleted.
- [x] Check syscheck doesn't generate alerts if the pointed file/folder is restored (re-create the previous deleted file/folder.
- [x] Check syscheck alert for deleting a link to a file/folder.

- [x] Check syscheck add alerts in a monitored link that points to a folder.
- [x] Check syscheck modify alerts in a monitored link that points to a folder.
- [x] Check syscheck delete alerts in a monitored link that points to a folder.
- [x] Check syscheck doesn't generate any alerts when changing the destination of the link to another folder.
- [x] Check that, before `symlink_checker` passes the alerts are generated in the former folder (and not in the new one).
- [x] Check that, after `symlink_checker` passes the alerts are generated in the new pointed folder (and not in the former one).
- [x] Check syscheck delete alerts if the pointed folder is deleted wether `symlink_checker` has been performed or not.
- [x] Restore the previously deleted folder, check that no alerts are generated (`symlink_checker` is not performed).
- [x] Check that alerts are generated for that folder once `symlink_checker` is performed.
- [x] Delete the monitored link, check that alerts are generated (`symlink_checker` is not performed).
- [x]  Check that no alerts are generated for the previously pointed folder once `symlink_checker` is performed.
- [x] Re-create the previously deleted link (monitored), no alerts should be generated in the pointed folder(`symlink_checker` is not performed).
- [x] Check that the folder generates alerts again once `symlink_checker` is performed.
- [x] Change the destination of a monitored link to an already monitored folder. The alerts generated should remain the same as before making this operation (before `symlink_checker` is performed).
- [x] Once `symlink_checker` is performed, check that no alerts are generated from the previously pointed folder and that the already monitored folder still generating alerts with its former options.
- [x] Restore the link to point to the previous folder and wait for `symlink_checker` to be performed. Alerts should be generated in both folders as they were before.
- [x] Change the destination of a link (that points to a folder) to a file. Modify both (before `symlink_checker`). Alerts should be generated from the folder and not from the file.
- [x] Modify both again and check that this time alerts are generated from the file and not the folder.
- [x] Perform the same operation but backward: change the destination of a monitored link from a file to a folder.

### Windows

- [x] Check syscheck alert for files that exist when starting the agent
- [x] Check syscheck alert for adding a file
- [x] Check syscheck alert for adding text to a file
- [x] Check syscheck alert for deleting text from a file
- [x] Check syscheck alert for moving a file
- [ ] Check syscheck alert for moving a folder with a file in it
- [x] Check syscheck alert for modifying a file
- [x] Check syscheck alert for renaming a file
- [ ] Check that the add file alert does not contain modification information. To do this, create a file with content in the folder being monitored, delete it and add a new file with the name of the deleted file
- [ ] Check syscheck alert for renaming a folder
- [x] Check syscheck alert with report_changes option and `last-entry` files are stored compressed.
- [x] Check syscheck alert for changing owner of file
- [x] Check syscheck alert for changing file permissions
- [x] Check syscheck alert for changing attributes of a file
- [ ] Check values diferent values for options 'check_sum', 'check_md5sum', 'check_sha1sum','check_sha256sum'
- [x] Check syscheck alert for deleting a file
- [x] Check recursion level option (recursion_level=0, recursion_level=2 check folder level 0, 1, 2 and 3)
- [x] Check syscheck alert for nested monitoring with <tags> option
- [x] Check syscheck alert for monitoring folder with <restrict> option
- [x] Check the "nodiff" option to don't show the changes of a file
- [ ] Check syscheck flag auto_ignore with attributes "frequency" and "timeframe" https://github.com/wazuh/wazuh/pull/605

### Linux

- [x] Check syscheck alert for files that exist when starting the agent
- [x] Check syscheck alert for adding a file
- [x] Check syscheck alert for adding text to a file
- [x] Check syscheck alert with report_changes option
- [x] Check syscheck alert for moving a file
- [ ] Check syscheck alert for moving a folder with a file in it
- [x] Check syscheck alert for modifying a file
- [x] Check syscheck alert for renaming a file
- [ ] Check that the add file alert does not contain modification information. To do this, create a file with content in the folder being monitored, delete it and add a new file with the name of the deleted file
- [ ] Check syscheck alert for renaming a folder
- [x] Check syscheck alert for deleting a file
- [ ] Check syscheck alert for deleting a folder
- [x] Check syscheck alert for changing owner of file
- [x] Check syscheck alert for changing group of file
- [x] Check syscheck alert for changing file permissions
- [ ] Check values different values for options 'check_sum', 'check_md5sum', 'check_sha1sum','check_sha256sum'
- [x] Check the "nodiff" option to don't show the changes of a file
- [ ] Check syscheck flag auto_ignore with attributes "frequency" and "timeframe" (1)
- [x] Check recursion level option (recursion_level=0, recursion_level=2 check folder level 0, 1, 2 and 3)
- [ ] Check syscheck alert for nested monitoring with <tags> option
- [x] Check syscheck alert for monitoring folder with <restrict> option
- [x] Check audit rules added (auditctl -l)
- [x] Check audit rules removed (auditctl -l)
- [x] Remove audit rule manually and check if the rule is reloaded. (Auto-reload each 30 seconds)
- [x] Remove rules 5 times and check if whodata stops and realtime is started. (Check alert)
- [x] Remove monitored folder and check if the rule is removed and re-add the folder. The rule must be re-added.
- [x] Restart auditd. Check whodata connection retries.
- [x] Check modifications in a file changed from whodata to realtime.
- [x] Check if  whodata changes to realtime if auditd is disabled while wazuh is running.
- [x] Check that `realtime` works if `whodata` is used in the configuration without auditd installed.
- [x] Check that `realtime` works if `whodata` is used in the configuration with auditd disabled.

### Links

- [x] Check syscheck alert for adding link to a file/folder.
- [x] Check syscheck doesn't generate alerts if the pointed file is modified or if content is added to the pointed folder.
- [x] Check syscheck generate modify alerts if the link changes the path where it points.
- [x] Check syscheck doesn't generate alerts if the pointed file/folder is deleted.
- [x] Check syscheck doesn't generate alerts if the pointed file/folder is restored (re-create the previous deleted file/folder.
- [x] Check syscheck alert for deleting a link to a file/folder.

- [x] Check syscheck add alerts in a monitored link that points to a folder.
- [x] Check syscheck modify alerts in a monitored link that points to a folder.
- [x] Check syscheck delete alerts in a monitored link that points to a folder.
- [x] Check syscheck doesn't generate any alerts when changing the destination of the link to another folder.
- [x] Check that, before `symlink_checker` passes the alerts are generated in the former folder (and not in the new one).
- [x] Check that, after `symlink_checker` passes the alerts are generated in the new pointed folder (and not in the former one).
- [x] Check syscheck delete alerts if the pointed folder is deleted wether `symlink_checker` has been performed or not.
- [x] Restore the previously deleted folder, check that no alerts are generated (`symlink_checker` is not performed).
- [x] Check that alerts are generated for that folder once `symlink_checker` is performed.
- [x] Delete the monitored link, check that alerts are generated (`symlink_checker` is not performed).
- [x]  Check that no alerts are generated for the previously pointed folder once `symlink_checker` is performed.
- [x] Re-create the previously deleted link (monitored), no alerts should be generated in the pointed folder(`symlink_checker` is not performed).
- [x] Check that the folder generates alerts again once `symlink_checker` is performed.
- [x] Change the destination of a monitored link to an already monitored folder. The alerts generated should remain the same as before making this operation (before `symlink_checker` is performed).
- [x] Once `symlink_checker` is performed, check that no alerts are generated from the previously pointed folder and that the already monitored folder still generating alerts with its former options.
- [x] Restore the link to point to the previous folder and wait for `symlink_checker` to be performed. Alerts should be generated in both folders as they were before.
- [x] Change the destination of a link (that points to a folder) to a file. Modify both (before `symlink_checker`). Alerts should be generated from the folder and not from the file.
- [x] Modify both again and check that this time alerts are generated from the file and not the folder.
- [x] Perform the same operation but backward: change the destination of a monitored link from a file to a folder.

### Windows

- [x] Check syscheck alert for files that exist when starting the agent
- [x] Check syscheck alert for adding a file
- [x] Check syscheck alert for adding text to a file
- [x] Check syscheck alert for deleting text from a file
- [x] Check syscheck alert for moving a file
- [ ] Check syscheck alert for moving a folder with a file in it
- [x] Check syscheck alert for modifying a file
- [x] Check syscheck alert for renaming a file
- [ ] Check that the add file alert does not contain modification information. To do this, create a file with content in the folder being monitored, delete it and add a new file with the name of the deleted file
- [ ] Check syscheck alert for renaming a folder
- [x] Check syscheck alert with report_changes option and `last-entry` files are stored compressed.
- [x] Check syscheck alert for changing owner of file
- [x] Check syscheck alert for changing file permissions
- [x] Check syscheck alert for changing attributes of a file
- [x] Check values diferent values for options 'check_sum', 'check_md5sum', 'check_sha1sum','check_sha256sum'
- [x] Check syscheck alert for deleting a file
- [x] Check recursion level option (recursion_level=0, recursion_level=2 check folder level 0, 1, 2 and 3)
- [x] Check syscheck alert for nested monitoring with <tags> option
- [x] Check syscheck alert for monitoring folder with <restrict> option
- [ ] Check the "nodiff" option to don't show the changes of a file
- [x] Check syscheck flag auto_ignore with attributes "frequency" and "timeframe" (1)
- [x] Check that the audit policies are restored
- [x] Verify that whodata does not block files. https://github.com/wazuh/wazuh/pull/3872

### General
- [ ] Daylight saving induced false positives: https://github.com/wazuh/wazuh/issues/4167
- [ ] Syscheck frequency values under 10 seconds behaviour: https://github.com/wazuh/wazuh/issues/4003
- [ ] Information message number 6022 can flood the Windows agent log file: https://github.com/wazuh/wazuh/issues/3998
- [ ] Simple and sregex syscheck <registry_ignore> stanzas are incompatible: https://github.com/wazuh/wazuh/issues/3990 (When combining <registry_ignore> and <registry_ignore type="sregex"> stanzas, only the non-sregex ones will be taken into account at the registry ignore process.)
- [ ] Different behavior in configuration while monitoring a drive in whodata and realtime: https://github.com/wazuh/wazuh/issues/3934
- [ ] Failure to monitor directories in real-time when configuring Windows audit policies: https://github.com/wazuh/wazuh/issues/3812
- [ ] Realtime syscheck alerts are not queued if agent is offline: https://github.com/wazuh/wazuh/issues/3811
- [ ] Too generic error when adding an inotify watcher: https://github.com/wazuh/wazuh/issues/3770
- [ ] Receive alert of realtime instead of whodata: https://github.com/wazuh/wazuh/issues/3733
- [ ] Incompatible field types in Kibana: https://github.com/wazuh/wazuh/issues/3171
- [ ] Real time events moving files or directories: https://github.com/wazuh/wazuh/issues/2863
- [ ] Realtime syscheck scan doesn't start: https://github.com/wazuh/wazuh/issues/2798
- [ ] FIM full_log field is being truncated : https://github.com/wazuh/wazuh/issues/2632
- [ ] Add timezone option for syscheck <scan_time>: https://github.com/wazuh/wazuh/issues/2555
- [ ] Executing whodata with inmutable audit configuration: https://github.com/wazuh/wazuh/issues/2432
- [ ] FIM DB synchronization between managers: https://github.com/wazuh/wazuh/issues/2404
- [ ] Syscheck is not attaching the timestamp of a deleted file event when having realtime enabled: https://github.com/wazuh/wazuh/issues/2397
- [ ] Sregex is not useful in restrict option: https://github.com/wazuh/wazuh/issues/2064
- [ ] Whodata for auditd logs: https://github.com/wazuh/wazuh/issues/2042
- [ ] FIM output inconsistency: https://github.com/wazuh/wazuh/issues/2005
- [ ] False positives about new files in FIM: https://github.com/wazuh/wazuh/issues/1881
- [ ] Error with real-time + NFS: https://github.com/wazuh/wazuh/issues/1269
- [ ] Filtering by event type: https://github.com/wazuh/wazuh/issues/1247

### Linux:
- [ ] Syscheck directories tag doesn't recognize directory / it needs /.: https://github.com/wazuh/wazuh/issues/3705
- [ ] FIM is not able to parse some symbols in a Windows Agent: https://github.com/wazuh/wazuh/issues/3310
- [ ] Syscheck hangs analyzing /dev/core: https://github.com/wazuh/wazuh/issues/3007
- [ ] FIM keeps alerting after removing a symbolic link: https://github.com/wazuh/wazuh/issues/2433
- [ ] Ignore option for Syscheck makes global ignores on the manager: https://github.com/wazuh/wazuh/issues/2378
- [ ] Syscheck in realtime doesn't detect changes in hardlinks: https://github.com/wazuh/wazuh/issues/2355

### Windows:
- [ ] Unexpected behavior with links to System32 and SysWOW64 in Syscheck: https://github.com/wazuh/wazuh/issues/3739
- [ ] Wrong ownership value in Windows agent: https://github.com/wazuh/wazuh/issues/2220
- [ ] FIM alerts of Windows Registry keys with empty-string MD5: https://github.com/wazuh/wazuh/issues/858

**FIM rework:**
- https://github.com/wazuh/wazuh/issues/3073 
- https://github.com/wazuh/wazuh/issues/3319

**Comment by JcabreraC** [comment]
# Test: Windows Realtime

**Comment by crolopez** [comment]
# Test: Windows Common

## Inconsistency when displaying the attributes

We can differentiate two types of alerts using a Syscheck rework manager when an attributes change is reported:

- If the agent is 3.10.2 or before, the attributes will be displayed as an array.

![image](https://user-images.githubusercontent.com/20266121/68958391-53ddf780-07cc-11ea-8093-253e28a24295.png)

- If the agent that reports the attributes change has been compiled from the rework, the attributes field is a string.

![image](https://user-images.githubusercontent.com/20266121/68958646-cbac2200-07cc-11ea-902a-5d7a18706f86.png)


We are giving two different types of data for the same field.


## Inconsistency when displaying the permissions

We can differentiate two types of alerts using a Syscheck rework manager when a permissions change is reported:

- If the agent is 3.10.2 or before, the permissions will be displayed using the old (and prettier for me) format.

![image](https://user-images.githubusercontent.com/20266121/68958835-2d6c8c00-07cd-11ea-80da-bcd31ddffc38.png)

- If the agent that reports the permissions change has been compiled from the rework, the permissions field is a long string.

![image](https://user-images.githubusercontent.com/20266121/68958929-6147b180-07cd-11ea-9c92-99ce1c152f87.png)

In this case, we don't have a permission conflict.

## The before fields should not be displayed if the field has not changed

Previously, the manager did not show the `_before` field if it had not changed. In the rework, this field is always shown.

![image](https://user-images.githubusercontent.com/20266121/68959035-96540400-07cd-11ea-8641-18f6b1aff1e7.png)

## The file diff needs a line break in the non-JSON alerts

![image](https://user-images.githubusercontent.com/20266121/68959298-0cf10180-07ce-11ea-922a-688a92cf7c42.png)


## The file diff is not shown if the event is generated from a rework agent

However, if the agent that sends the event which includes the file diff is from 3.10.2 or before, this field is shown as expected in the JSON alert.

![image](https://user-images.githubusercontent.com/20266121/68959266-fea2e580-07cd-11ea-8034-5000ce973b25.png)

**Comment by sergiovp** [comment]
## The content of a deleted file is shown after deleting this file and creating a new one with the same name, in spite of the new file created is empty.

~~~
root@AgentUbuntu18:/home/vagrant$ touch my_test.txt
root@AgentUbuntu18:/home/vagrant$ echo this is my test >> my_test.txt
root@AgentUbuntu18:/home/vagrant$ cat my_test.txt 
this is my test
~~~ 
~~~
Attributes:
 - Size: 16
 - Permissions: rw-r--r--
 - Date: Tue Nov 19 09:52:40 2019
 - Inode: 3407876
 - User: root (0)
 - Group: root (0)
 - MD5: 77f44a94675a6731a81698b2fd3979e6
 - SHA1: 3c21bf30b1a7456ffb85481148bb943c85a24926
 - SHA256: 9819c4fef4355da1fd4e681a7596319066ef518bbefe40cc396b7ed41a0e9ba8

What changed: 0a1
> this is my test
~~~
~~~
root@AgentUbuntu18:/home/vagrant$ rm my_test.txt 
root@AgentUbuntu18:/home/vagrant$ touch my_test.txt
root@AgentUbuntu18:/home/vagrant$ cat my_test.txt 
root@AgentUbuntu18:/home/vagrant$
~~~
~~~
Attributes:
 - Size: 0
 - Permissions: rw-r--r--
 - Date: Tue Nov 19 09:54:09 2019
 - Inode: 3407876
 - User: root (0)
 - Group: root (0)
 - MD5: d41d8cd98f00b204e9800998ecf8427e
 - SHA1: da39a3ee5e6b4b0d3255bfef95601890afd80709
 - SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

What changed: 1d0
< this is my test
~~~
