### ISSUE TITLE
Automation of code and dependencies vulnerabilities scanning in Jenkins

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#2719]
We want to automate the execution of the [scan tests](https://github.com/wazuh/wazuh-qa/tree/master/tests/scans) from the `wazuh-qa` repository.

For this, it is proposed to create a new pipeline in Jenkins that runs locally that tests and generates a custom report with the results.

### Dependencies test
- [x] (**T1**): Build the pipeline.
- [x] (**T2**): Run the test and provide the status.

### Code analysis test
- [x] (**T1**): Build the pipeline.
- [x] (**T2**): Provisioning the Wazuh instance. 
- [x] (**T3**): Run the test and provide files status.

**Comment by fedepacher** [comment]
I have created a function to obtain the status code of the Wazuh repository.
With this function, it pretends to avoid using the `apiCall` function that uses the API Github.

**Comment by fedepacher** [comment]
Working on this issue

## Estimated Tasks

### Dependencies test
- [ ] (**T1**): Build the pipeline.
- [ ] (**T2**): Run the test and provide files status.

### Code analysis test
- [ ] (**T1**): Build the pipeline.
- [ ] (**T2**): Provisioning the instance. 
- [ ] (**T3**): Run the test and provide files status.

**Comment by fedepacher** [comment]
## Dependencies test

## Task 1

In the following [link](https://devel.ci.wazuh.info/job/Test_dependencies_vulnerabilities/build?delay=0sec), it can be checked the pipeline configuration.

![Screenshot from 2022-04-11 11-54-51](https://user-images.githubusercontent.com/28990973/162767098-bddf05b6-d39b-48b6-a1cc-e4d4f50c91f3.png)

An example of the pipeline result cab be checked in the [link](https://devel.ci.wazuh.info/job/Test_dependencies_vulnerabilities/163/) below.

**Comment by fedepacher** [comment]
## Code analysis test

## Task 1

In the following [link](https://devel.ci.wazuh.info/job/Test_code_vulnerabilities/build?delay=0sec), it can be checked the pipeline configuration.

![Screenshot from 2022-04-11 12-42-07](https://user-images.githubusercontent.com/28990973/162779608-ac8748d7-606b-4fe9-8fa2-cb43dda54ee8.png)

An example of the pipeline result can be checked in the [link](https://devel.ci.wazuh.info/job/Test_code_vulnerabilities/65/) below.

**Comment by fedepacher** [comment]
## Task 2

In the following [link](https://devel.ci.wazuh.info/job/Test_code_vulnerabilities/91/console) it can be checked the status of the test.
At the time, I am deploying an instance in `Jenkins` node but, I am facing the following error:

```
18:58:31  + sudo chown -R ec2-user:ec2-user provider.tf
18:58:31  chown: cannot access ‘provider.tf’: No such file or directory
```

**Comment by fedepacher** [comment]
## Task 2 Updates 2022/04/13

In the following [link](https://devel.ci.wazuh.info/job/Test_code_vulnerabilities/build?delay=0sec), it can be checked the new pipeline configuration.

![Screenshot from 2022-04-20 16-38-42](https://user-images.githubusercontent.com/28990973/164310121-73c73301-dbc3-42f6-a5fb-c4ac6cbe09d8.png)

**Comment by fedepacher** [comment]
## Task 2 Updates 2022/04/20

It has created an ansible playbook to perform the following tasks:

- Create a new dir to store qa repository
- Clone wazuh-qa repository
- Install wazuh from package
- Update pip
- Install pytest package
- Install bandit package
- Install Wazuh framework
- Launch pytests block
- Generate stdout txt logs
- Move report files

In order to avoid vulnerabilities introduced for python3 library of the instance, the test has been run using the python3 installed in the Wazuh manager.

**Comment by fedepacher** [comment]
# Update 2022/04/29

## Pipeline production

### Test dependencies vulnerabilities

The pipeline production of this test can be found [here](https://ci.wazuh.info/job/Test_dependencies_vulnerabilities/) 

### Test code vulnerabilities

The pipeline production of this test can be found [here] (https://ci.wazuh.info/job/Test_code_vulnerabilities/)
