### ISSUE TITLE
Make simple syscheck automated tests work for Solaris platform

### ISSUE THREAD

**Issue by vicferpoy** [wazuh/wazuh-qa#273]
## Description
Now we have a decent set of integration tests for simple configurations, we should make them work also for solaris agents. 

## Tasks
- [x] Prepare an environment to run syscheck in a solaris agent

Run all simple tests iteratively until the same results as Unix tests are obtained:
- [x] Test_audit
- [x] Test_basic_usage
- [x] Test_benchmark
- [x] Test_checks
- [x] Test_ignore
- [x] Test_invalid
- [x] Test_nodiff
- [x] Test_prefilter_cmd
- [x] Test_recursion_level
- [x] Test_report_changes
- [x] Test_restrict
- [x] Test_scan
- [x] Test_tags
- [x] Test_skip

**Comment by vicferpoy** [comment]
# Status update
We cannot test anything due to a compilation error with the agent on solaris.
This is reported and we will continue the tests once it is fixed.

**Comment by CarlosRS9** [comment]
# Status Update

The development have been completed.

## Test Results
### test_ambiguous_confs
```
===================================== test session starts =====================================
platform sunos5 -- Python 3.6.9, pytest-5.3.2, py-1.8.0, pluggy-0.13.1
rootdir: /vagrant/wazuh-qa/test_wazuh, inifile: pytest.ini
collected 101 items                                                                           

test_fim/test_ambiguous_confs/test_ambiguous_complex.py ...                             [  2%]
test_fim/test_ambiguous_confs/test_ambiguous_simple.py .sssssssssss.sssssssssss.sssssss [ 34%]
ssss.sssssssssss.sssssssssss.sssssssssss.sssssssssss....                                [ 90%]
test_fim/test_ambiguous_confs/test_ignore_works_over_restrict.py ..sssss...             [100%]

================== 19 passed, 82 skipped in 7254764.14s (83 days, 23:12:44) ===================
```

### test_basic_usage
```
===================================== test session starts =====================================
platform sunos5 -- Python 3.6.9, pytest-5.3.2, py-1.8.0, pluggy-0.13.1
rootdir: /vagrant/wazuh-qa/test_wazuh, inifile: pytest.ini
collected 40 items                                                                            

test_fim/test_basic_usage/test_basic_usage_baseline_generation.py .                     [  2%]
test_fim/test_basic_usage/test_basic_usage_changes.py ..                                [  7%]
test_fim/test_basic_usage/test_basic_usage_create_rt_wd.py ssssssssssss                 [ 37%]
test_fim/test_basic_usage/test_basic_usage_create_scheduled.py ............             [ 67%]
test_fim/test_basic_usage/test_basic_usage_delete_folder.py ..                          [ 72%]
test_fim/test_basic_usage/test_basic_usage_entries_match_path_count.py .                [ 75%]
test_fim/test_basic_usage/test_basic_usage_move_file.py .....                           [ 87%]
test_fim/test_basic_usage/test_basic_usage_rename.py ..                                 [ 92%]
test_fim/test_basic_usage/test_basic_usage_starting_agent.py ...                        [100%]

=================== 28 passed, 12 skipped in 2106219.51s (24 days, 9:03:39) ===================
```

### test_checks
```
==================================== test session starts ====================================
platform sunos5 -- Python 3.6.9, pytest-5.3.2, py-1.8.0, pluggy-0.13.1
rootdir: /vagrant/wazuh-qa/test_wazuh, inifile: pytest.ini
collected 126 items                                                                         

test_fim/test_checks/test_check_all.py ..........ssssssssssssssssss........           [ 28%]
test_fim/test_checks/test_check_others.py ..........ssssssssssssssssss........        [ 57%]
test_fim/test_checks/test_checksums.py .............sssssssssssssssssssssssss........ [ 93%]
....                                                                                  [ 96%]
test_fim/test_checks/test_hard_link.py ....                                           [100%]
```


### test_follow_symbolic_link
```
==================================== test session starts ====================================
platform sunos5 -- Python 3.6.9, pytest-5.3.2, py-1.8.0, pluggy-0.13.1
rootdir: /vagrant/wazuh-qa/test_wazuh, inifile: pytest.ini
collected 23 items                                                                          

test_fim/test_follow_symbolic_link/test_change_target.py .ss.                         [ 17%]
test_fim/test_follow_symbolic_link/test_change_target_inside_folder.py .ss.           [ 34%]
test_fim/test_follow_symbolic_link/test_delete_symlink.py .ss.                        [ 52%]
test_fim/test_follow_symbolic_link/test_delete_target.py .ss.                         [ 69%]
test_fim/test_follow_symbolic_link/test_monitor_symlink.py .ss.                       [ 86%]
test_fim/test_follow_symbolic_link/test_not_following_symbolic_link.py ..             [ 95%]
test_fim/test_follow_symbolic_link/test_revert_symlink.py .                           [100%]
```

### test_ignore
```
==================================== test session starts ====================================
platform sunos5 -- Python 3.6.9, pytest-5.3.2, py-1.8.0, pluggy-0.13.1
rootdir: /vagrant/wazuh-qa/test_wazuh, inifile: pytest.ini
collected 230 items                                                                         

test_fim/test_ignore/test_ignore_valid.py sssssssssssssssssss..ss....s......ssss.ssss [ 18%]
sss....s......ssss.sssssss....s......ssss.sssssss................s.sssss............. [ 55%]
.....sssss..................sssss....s......s.s..s.sssss....s......s.s..ss.ssssssssss [ 92%]
sssssssssssssss..                                                                     [100%]

================ 118 passed, 112 skipped in 5526300.51s (63 days, 23:05:00) =================
```

### test_invalid
```
==================================== test session starts ====================================
platform sunos5 -- Python 3.6.9, pytest-5.3.2, py-1.8.0, pluggy-0.13.1
rootdir: /vagrant/wazuh-qa/test_wazuh, inifile: pytest.ini
collected 4 items                                                                           

test_fim/test_invalid/test_invalid.py ....                                            [100%]

==================================== 4 passed in 23.02s =====================================
```

### test_max_eps
```
===================================== test session starts =====================================
platform sunos5 -- Python 3.6.9, pytest-5.3.2, py-1.8.0, pluggy-0.13.1
rootdir: /vagrant/wazuh-qa/test_wazuh, inifile: pytest.ini
collected 5 items                                                                             

test_fim/test_max_eps/test_max_eps.py .....                                             [100%]

================================ 5 passed in 179.40s (0:02:59) ================================
```

### test_nodiff
```
==================================== test session starts =====================================
platform sunos5 -- Python 3.6.9, pytest-5.3.2, py-1.8.0, pluggy-0.13.1
rootdir: /vagrant/wazuh-qa/test_wazuh, inifile: pytest.ini
collected 189 items                                                                          

test_fim/test_nodiff/test_no_diff_valid.py sssssssssssssssssss......s......ssss.sssss. [ 22%]
...s......ssss.sssss....s......ssss.sssss................s.sss..................sss... [ 68%]
...............sss....s......s.s..s.sss....s......s.s..ss.ss                           [100%]

================ 116 passed, 73 skipped in 16283345.21s (188 days, 11:09:05) =================
```


### test_recursion_level
```
===================================== test session starts =====================================
platform sunos5 -- Python 3.6.9, pytest-5.3.2, py-1.8.0, pluggy-0.13.1
rootdir: /vagrant/wazuh-qa/test_wazuh, inifile: pytest.ini
collected 16 items                                                                            

test_fim/test_recursion_level/test_recursion_level.py ................                  [100%]

======================== 16 passed in 5054870.21s (58 days, 12:07:50) =========================
```

### test_process_priority
```
===================================== test session starts =====================================
platform sunos5 -- Python 3.6.9, pytest-5.3.2, py-1.8.0, pluggy-0.13.1
rootdir: /vagrant/wazuh-qa/test_wazuh, inifile: pytest.ini
collected 3 items                                                                             

test_fim/test_process_priority/test_process_priority.py FFF                             [100%]

========================================== FAILURES ===========================================
```
Those errors have been reported.

### test_report_changes
```
===================================== test session starts =====================================
platform sunos5 -- Python 3.6.9, pytest-5.3.2, py-1.8.0, pluggy-0.13.1
rootdir: /vagrant/wazuh-qa/test_wazuh, inifile: pytest.ini
collected 4 items                                                                             

test_fim/test_report_changes/test_report_changes_and_diff.py ..                         [ 50%]
test_fim/test_report_changes/test_report_deleted_diff.py FF                             [100%]

========================================== FAILURES ===========================================
```
test_report_deleted_diff.py fails because a reported issue for Solaris. The issue can be found here: https://github.com/wazuh/wazuh-qa/issues/350


### test_restrict
```
==================================== test session starts =====================================
platform sunos5 -- Python 3.6.9, pytest-5.3.2, py-1.8.0, pluggy-0.13.1
rootdir: /vagrant/wazuh-qa/test_wazuh, inifile: pytest.ini
collected 144 items                                                                          

test_fim/test_restrict/test_restrict_valid.py ssssssssssssssss........ssssssssssss.... [ 27%]
............ssssssss....ssssssssssssssss........ssssssss....ssssssssssssssss........ss [ 87%]
ssssss....ssssssss                                                                     [100%]

================== 52 passed, 92 skipped in 2433800.78s (28 days, 4:03:20) ===================
```

### test_scan
```
==================================== test session starts =====================================
platform sunos5 -- Python 3.6.9, pytest-5.3.2, py-1.8.0, pluggy-0.13.1
rootdir: /vagrant/wazuh-qa/test_wazuh, inifile: pytest.ini
collected 8 items                                                                            

test_fim/test_scan/test_scan_day.py ...                                                [ 37%]
test_fim/test_scan/test_scan_day_and_time.py ..                                        [ 62%]
test_fim/test_scan/test_scan_time.py ...                                               [100%]

========================= 8 passed in 1990582.65s (23 days, 0:56:22) =========================
```

### test_tags
```
================================= test session starts =================================
platform sunos5 -- Python 3.6.9, pytest-5.3.2, py-1.8.0, pluggy-0.13.1
rootdir: /vagrant/wazuh-qa/test_wazuh, inifile: pytest.ini
collected 40 items                                                                    

test_fim/test_tags/test_tags.py ........................................        [100%]

==================== 40 passed in 5612608.38s (64 days, 23:03:28) =====================
```
