### ISSUE TITLE
Syscheck automated tests: Check syscheck alert for moving a folder with a file in it

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh-qa#275]
## Description

Update `test_basic_usage` to implement a simple test that will move a folder with files inside and check if syscheck generates alerts.

During the test a new folder within the monitored one will be created and several files will be created inside. Then, that new folder will be moved to another location and the corresponding events (`added` and `deleted`) must be detected.

The following cases must be checked:

1. Move the subdirectory to another monitored directory (for example: from `testdir1/subdir`r to `/testdir2`)
2. Move the subdirectory to a non-monitored directory (for example: from `testdir1/subdir` to `/`)
3. Move a subdirectory of a non-monitored directory to a monitored one (for example: from `/subdir` to `/testdir1`)

## Expected output

The files in the folder must generate `deleted` events when moving outside of a monitored directory and `added` events in the new directory if this one is also being monitored.

For example: when moving `/testdir1/subdir` to `/testdir2/subdir` a `deleted` event for each file inside `/testdir1/subdir` must be detected on `/testdir1` while `added` events should be detected on `/testdir2/subdir`.

## Subtasks
**Unix**
- [x] Create a test that moves a subdirectory with files inside in a monitored path to another monitored folder (for example: from `testdir1/subdir` to `/testdir2`)
- [x] Create a test that moves the subdirectory to a non-monitored path (for example: from `testdir1/subdir` to `/`)
- [x] Create a test that moves a subdirectory of a non-monitored path to a monitored one (for example: from `/subdir` to `/testdir1`)

**Windows**
- [x] Create a test that moves a subdirectory with files inside in a monitored path to another monitored folder (for example: from `testdir1/subdir` to `/testdir2`)
- [x] Create a test that moves the subdirectory to a non-monitored path (for example: from `testdir1/subdir` to `/`)
- [x] Create a test that moves a subdirectory of a non-monitored path to a monitored one (for example: from `/subdir` to `/testdir1`)

**MacOS**
- [x] Create a test that moves a subdirectory with files inside in a monitored path to another monitored folder (for example: from `testdir1/subdir` to `/testdir2`)
- [x] Create a test that moves the subdirectory to a non-monitored path (for example: from `testdir1/subdir` to `/`)
- [x] Create a test that moves a subdirectory of a non-monitored path to a monitored one (for example: from `/subdir` to `/testdir1`)

**Comment by 0xN3utr0n** [comment]
### Update 1
#352 Has been successfully tested in Linux and Windows. On MacOS a bug has appeared that makes it impossible to execute any test. Currently @Selutario is debugging the issue.

**Comment by Selutario** [comment]
### Update2
The error, which occurred with the execution of any test performed on MacOs, launched the following output:

`typeError: cannot unpack non-iterable nonetype object`

The problem was as follows. When `get_fim_mode_param(mode)` was called, two results were expected, however, a single None was returned in MacOs since no conditions were met. The error has been corrected by adding an else clause that returns two None when no other condition is met.

The solution has already been committed [here](https://github.com/wazuh/wazuh-qa/commit/ffef58116e860db0b84ecee1fd466c70a7365bba#diff-2dcade4f29094a09ed1a1e637f4f551b).
