### ISSUE TITLE
Syscheck automated tests: Check syscheck alert for renaming a file

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh-qa#276]
## Description

Update `test_basic_usage` to implement a simple test to check the behaviour of syscheck when a file of a folder is renamed.

To properly test this a folder will be created in the monitored directory and a file inside that folder. The test will rename the file and then the folder itself, capturing the events generated.

## Expected output

On Unix environments this operation will raise a `modified` event when renaming the file while on Windows a `deleted` and `added` evnets will be raised when renaming the file as Windows do not count renaming as modification (because syscheck uses filename as identifier for the file on windows)

When a folder that contains files is renamed only `added` event will be raised of each file on the new directory on both Unix and Windows.

## Subtasks

- [x] Check Syscheck when renaming a file on Unix
- [x] Check Syscheck when renaming a file on Windows
- [x] Check Syscheck when renaming a non-empty directory on Unix
- [x] Check Syscheck when renaming a non-empty directory on Windows

**Comment by vicferpoy** [comment]
# Status update
Syscheck does not send the 'deleted' event when renaming a non-empty directory on Unix in `realtime` and `whodata` monitoring, assuming frequency is set to default (that means we avoid that field in `<syscheck>`. With smaller frequency values (I tested 20 seconds), it works.
The 'deleted' event should have the old name in its `path` key.

# Tests performed
### Linux
```
========================================== test session starts ==========================================
platform linux -- Python 3.6.8, pytest-5.2.4, py-1.8.0, pluggy-0.13.0
rootdir: /vagrant/wazuh-qa/test_wazuh, inifile: pytest.ini
collected 6 items                                                                                       

test_basic_usage/test_basic_usage_rename.py ...F.F                                                [100%]

=============================================== FAILURES ================================================
```

**Comment by vicferpoy** [comment]
# Status update
Windows agents have the same behaviour as Linux ones. Tests fail in the same cases. Test development is finished.

# Difficulties
- It was really hard to test on windows due to its inconsistency on timeouts and the `ossec.log` known bug in testing.

# Tests performed
### Windows
```
================================================================= test session starts ================================================================== 
platform win32 -- Python 3.7.3, pytest-5.1.2, py-1.8.0, pluggy-0.13.0
rootdir: C:\Users\jmv74211\Desktop\wazuh-qa\test_wazuh, inifile: pytest.ini
collected 6 items

test_basic_usage_rename.py ...F.F                                                                                                                 [100%]

======================================================================= FAILURES =======================================================================
```
