### ISSUE TITLE
Syscheck automated tests: Check syscheck alert for nested monitoring with <tags> option

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh-qa#278]
## Description

The main goal of this issue is to test the behaviour of syscheck when using `tags` and `recursion_level` over a monitored directory

The `tags` attribute adds tags to the alerts for monitored directories. The allowed value for the `tags` attribute must be a list separated by commas:

```XML
<directories tags="tag0,tag1,tag2,tag3,tag4,tag5,tag6,tag7,tag8,tag9">/testdir_tags</directories>
```

The `recursion_level` tag is used to configure the maximum recursion level allowed for a specific directory so `syscheck` will generate alerts for all files up to the indicated directory level but will ignore the rest.

According to [documentation](https://documentation.wazuh.com/3.10/user-manual/capabilities/file-integrity/fim-configuration.html#configure-maximum-recursion-level-allowed), using the following directory structure and `recursion_level="3"`. We will receive alerts for all files up to `folder_test/level_1/level_2/level_3/` but we won’t receive alerts from any directory deeper than level_3:

```
folder_test
├── file_0.txt
└── level_1
    ├── file_1.txt
    └── level_2
        ├── file_2.txt
        └── level_3
            ├── file_3.txt
            └── level_4
                ├── file_4.txt
                └── level_5
                    └── file_5.txt
```

The `maximum_recursion_level` must be an integer *between 0 and 320*.

## Expected output

Both options must work in the same way as they would if used separately. The tags must appear in the events on any monitored directory level. We also need to ensure that no events will be raised on directories

## Subtasks
**Unix**
  - [x] Check both options on the same directory. Catch tags on a folder with recursion level 0.
  - [x] Check both options on the same directory. Catch tags on a folder and its subdirectories with recursion level 2.

**Windows**
  - [x] Check both options on the same directory. Catch tags on a folder with recursion level 0.
  - [x] Check both options on the same directory. Catch tags on a folder and its subdirectories with recursion level 2.

**MacOS**
  - [ ] Check both options on the same directory. Catch tags on a folder with recursion level 0.
  - [ ] Check both options on the same directory. Catch tags on a folder and its subdirectories with recursion level 2.

**Solaris**
  - [ ] Check both options on the same directory. Catch tags on a folder with recursion level 0.
  - [ ] Check both options on the same directory. Catch tags on a folder and its subdirectories with recursion level 2.
