### ISSUE TITLE
Syscheck automated tests: Update test_audit

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh-qa#279]
## Description

Update `test_audit` to add the following tests, having a directory being monitored with `whodata` option:

1. Add more than  5 rules to `auditctl`, move the system clock forward and then remove rules 5 times. Check if `Whodata` stops and `Real-Time` is started. This action is taken as a security meassure as it will be considered an external manipulation of `Whodata`. Once `Real-Time` monitoring has started, please modify a file and ensure that `Whodata` information is not showing.

2. Add an `auditctl` rule for a monitored folder. Remove that folder and check if the rule is also removed. Create the folder again. The rule must be re-added.

3. Restart `auditd` and check if `Whodata` connection retries.

4. Uninstall `auditd`, restart syscheck and test that `whodata` changes to `Real-Time` as there is no `auditd`.

## Subtasks

_Note: All the test must be executed only with `whodata` monitoring on Unix environments as `auditd` is not present in Windows._

- [x] Remove rules 5 times and check if whodata stops and realtime is started. (Test 1)
- [x] Remove monitored folder and check if the rule is removed and re-add the folder. The rule must be re-added. (Test 2)
- [x] Restart auditd. Check whodata connection retries. (Test 3)
- [x] Check if whodata changes to realtime if auditd is not installed. (Test 4)
