### ISSUE TITLE
Release 4.3.0 - Manual tests - Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-qa#2803]
We want to test the Wazuh `v4.3.0-rc6` behavior using the new system: `Ubuntu 22.04 LTS`. To do this, the following tasks are required:

## Preparatory tasks

- [x]  (**T1**): - Prepare Ubuntu 22.04 Beta AMI 
- [x]  (**T2**): - Deploy the manager and agent environment

## Test tasks
- [x]  (**T3**): - `wazuh-manager` installation 🟡
- [x]  (**T4**): - `wazuh-agent` installation 🟡
- [x]  (**T5**): - `wazuh-agent`connection with `wazuh-manager` 🟢
- [x]  (**T6**): - `wazuh-manager` uninstallation 🟡
- [x]  (**T7**): - `wazuh-agent` uninstallation 🟢
- [x]  (**T8**): - `wazuh-manager` upgrade 🟢
- [x]  (**T9**): - `wazuh-agent` upgrade 🟢

> Note: The task list can be increased over time.

**Comment by jmv74211** [comment]
Working on this issue

## Conclusion 🔵

**Comment by jmv74211** [comment]
## Task 1 - Prepare Ubuntu 22.04 Beta AMI

I have been searching some Ubuntu 22.04 AMI in the AWS marketplace, but I have not found any. This is normal, since this system has not oficially been released.

Next, I have created an EC2 instance with Ubuntu 20.04 AMI, and I have launched the following commands to upgrade to Ubuntu 22.04

```
apt update && sudo apt upgrade && sudo reboot 
```

After the reboot...

```
sudo do-release-upgrade -d
```

After finishing all this process, the Ubuntu has been successfully upgraded to `22.04 (Jammy Jellyfish)`

```
# cat /etc/os-release 

PRETTY_NAME="Ubuntu 22.04 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04 (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

```
# uname -mrs

Linux 5.15.0-1004-aws x86_64
```

Finally, I have created a new AMI from that EC2 instance. This new AMI has been added as `[QA]Ubuntu_22_04_Beta` name.

**Comment by jmv74211** [comment]
## Task 2

In order to make the basic testing, I have deployed two EC2 instances using the `[QA]Ubuntu_22_04_Beta` AMI:

- AWS workspace: `wazuh-qa`
- Instance 1: 
  - name: `jmv74211_ubuntu_22_04_manager`
  - type: `c5.large`
- Instance 2: 
  - name: `jmv74211_ubuntu_22_04_agent`
  - type: `c5.large`

**Comment by jmv74211** [comment]
## Task 3 - `wazuh-manager` installation

To do the `wazuh-manager` installation, I have followed the [4.3 development documentation](https://documentation-dev.wazuh.com/current/installation-guide/wazuh-server/step-by-step.html#wazuh-server-node-installation).

The `wazuh-installation` has been successfully done, but I obtained the following deprecated warnings:

- When adding GPG key:

  ```
  # curl -s https://s3-us-west-1.amazonaws.com/packages-dev.wazuh.com/key/GPG-KEY-WAZUH | apt-key add -
  
  Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
    OK
  ```

- When running `apt update` after adding wazuh repository

  ```
  # echo "deb https://s3-us-west-1.amazonaws.com/packages-dev.wazuh.com/pre-release/apt/ unstable main" | tee -a /etc/apt/sources.list.d/wazuh_pre_release.list && apt-get update

  W: https://s3-us-west-1.amazonaws.com/packages-dev.wazuh.com/pre-release/apt/dists/unstable/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
  ```

Otherwise, the installation process has been successfully done:

<details>
<summary><code>wazuh-manager</code> service status 🟢</summary>

```
🟢 wazuh-manager.service - Wazuh manager
     Loaded: loaded (/lib/systemd/system/wazuh-manager.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2022-04-19 10:16:58 UTC; 10s ago
    Process: 39669 ExecStart=/usr/bin/env /var/ossec/bin/wazuh-control start (code=exited, status=0/SUCCESS)
      Tasks: 115 (limit: 4441)
     Memory: 749.1M
        CPU: 22.385s
     CGroup: /system.slice/wazuh-manager.service
             ├─39785 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
             ├─39825 /var/ossec/bin/wazuh-authd
             ├─39841 /var/ossec/bin/wazuh-db
             ├─39854 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
             ├─39857 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
             ├─39870 /var/ossec/bin/wazuh-execd
             ├─39884 /var/ossec/bin/wazuh-analysisd
             ├─39927 /var/ossec/bin/wazuh-syscheckd
             ├─39943 /var/ossec/bin/wazuh-remoted
             ├─39974 /var/ossec/bin/wazuh-logcollector
             ├─39997 /var/ossec/bin/wazuh-monitord
             ├─40010 /var/ossec/bin/wazuh-modulesd
             ├─40519 sh -c "/bin/ps -p 91 > /dev/null 2>&1"
             └─40520 "[ps]"

Apr 19 10:16:49 ip-172-31-26-40 env[39669]: Started wazuh-db...
Apr 19 10:16:50 ip-172-31-26-40 env[39669]: Started wazuh-execd...
Apr 19 10:16:51 ip-172-31-26-40 env[39669]: Started wazuh-analysisd...
Apr 19 10:16:52 ip-172-31-26-40 env[39669]: Started wazuh-syscheckd...

```

</details>

<details>
<summary><code>wazuh-manager</code> started daemons 🟢</summary>

```
root@ip-172-31-26-40:/home/ubuntu# /var/ossec/bin/wazuh-control status
wazuh-clusterd not running...
wazuh-modulesd is running...
wazuh-monitord is running...
wazuh-logcollector is running...
wazuh-remoted is running...
wazuh-syscheckd is running...
wazuh-analysisd is running...
wazuh-maild not running...
wazuh-execd is running...
wazuh-db is running...
wazuh-authd is running...
wazuh-agentlessd not running...
wazuh-integratord not running...
wazuh-dbd not running...
wazuh-csyslogd not running...
wazuh-apid is running...
```

</details>

</details>

<details>
<summary>No ERROR or WARNING in <code>ossec.log</code> 🟢</summary>

```
#egrep -i "ERROR|WARNING" /var/ossec/logs/ossec.log 
#
```

</details>

<details>
<summary>System detected in <code>ossec.conf</code> 🟢</summary>

```
<!--
  Wazuh - Manager - Default configuration for ubuntu 22.04
  More info at: https://documentation.wazuh.com
  Mailing list: https://groups.google.com/forum/#!forum/wazuh
-->
```

</details>

**Comment by jmv74211** [comment]
## Task 4 - `wazuh-agent` installation

To do the `wazuh-agent` installation, I have followed the [4.3 development documentation](https://documentation-dev.wazuh.com/current/installation-guide/wazuh-agent/wazuh-agent-package-linux.html#deploying-wazuh-agents-on-linux-systems) using the `pre-release` repository.

The `wazuh-installation` has been successfully done, but I obtained the following deprecated warnings:

- When adding GPG key:

  ```
  # curl -s https://s3-us-west-1.amazonaws.com/packages-dev.wazuh.com/key/GPG-KEY-WAZUH | apt-key add -
  
  Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
    OK
  ```

- When running `apt update` after adding wazuh repository

  ```
  # echo "deb https://s3-us-west-1.amazonaws.com/packages-dev.wazuh.com/pre-release/apt/ unstable main" | tee -a /etc/apt/sources.list.d/wazuh_pre_release.list && apt-get update

  W: https://s3-us-west-1.amazonaws.com/packages-dev.wazuh.com/pre-release/apt/dists/unstable/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
  ```

Otherwise, the installation process has been successfully done:

First, the `wazuh-manager-ip` has ben set in the `wazuh-agent` `ossec.conf` and the `wazuh-agent` service has been started with `systemctl start wazuh-agent`.

<details>
<summary><code>wazuh-agent</code> service status 🟢</summary>

```
🟢 wazuh-agent.service - Wazuh agent
     Loaded: loaded (/lib/systemd/system/wazuh-agent.service; disabled; vendor preset: enabled)
     Active: active (running) since Tue 2022-04-19 11:16:20 UTC; 45s ago
    Process: 3572 ExecStart=/usr/bin/env /var/ossec/bin/wazuh-control start (code=exited, status=0/SUCCESS)
      Tasks: 28 (limit: 4407)
     Memory: 452.5M
        CPU: 8.367s
     CGroup: /system.slice/wazuh-agent.service
             ├─3594 /var/ossec/bin/wazuh-execd
             ├─3605 /var/ossec/bin/wazuh-agentd
             ├─3619 /var/ossec/bin/wazuh-syscheckd
             ├─3632 /var/ossec/bin/wazuh-logcollector
             └─3649 /var/ossec/bin/wazuh-modulesd

Apr 19 11:16:13 ip-172-31-19-46 systemd[1]: Starting Wazuh agent...
Apr 19 11:16:13 ip-172-31-19-46 env[3572]: Starting Wazuh v4.3.0...
Apr 19 11:16:14 ip-172-31-19-46 env[3572]: Started wazuh-execd...
Apr 19 11:16:15 ip-172-31-19-46 env[3572]: Started wazuh-agentd...
Apr 19 11:16:16 ip-172-31-19-46 env[3572]: Started wazuh-syscheckd...
Apr 19 11:16:17 ip-172-31-19-46 env[3572]: Started wazuh-logcollector...
Apr 19 11:16:18 ip-172-31-19-46 env[3572]: Started wazuh-modulesd...
Apr 19 11:16:20 ip-172-31-19-46 env[3572]: Completed.
Apr 19 11:16:20 ip-172-31-19-46 systemd[1]: Started Wazuh agent.
```

</details>

<details>
<summary><code>wazuh-manager</code> started daemons 🟢</summary>

```
root@ip-172-31-19-46:/home/ubuntu# /var/ossec/bin/wazuh-control status
wazuh-modulesd is running...
wazuh-logcollector is running...
wazuh-syscheckd is running...
wazuh-agentd is running...
wazuh-execd is running...
```

</details>

</details>

<details>
<summary>No ERROR or WARNING in <code>ossec.log</code> 🟢</summary>

```
#egrep -i "ERROR|WARNING" /var/ossec/logs/ossec.log 
#
```

</details>

<details>
<summary>System detected in <code>ossec.conf</code> 🟢</summary>

```
<!--
  Wazuh - Agent - Default configuration for ubuntu 22.04
  More info at: https://documentation.wazuh.com
  Mailing list: https://groups.google.com/forum/#!forum/wazuh
-->

...

<client>
  <config-profile>ubuntu, ubuntu22, ubuntu22.04</config-profile>
  ...
</client>
```

</details>

<details>
<summary>Connection with <code>wazuh-manager</code> 🟢</summary>

```
# egrep -i "connected" /var/ossec/logs/ossec.log 

2022/04/19 11:16:12 wazuh-agentd: INFO: (4102): Connected to the server (172.31.26.40:1514/tcp).
2022/04/19 11:16:14 wazuh-agentd: INFO: (4102): Connected to the server (172.31.26.40:1514/tcp).
```

</details>

**Comment by jmv74211** [comment]
## Task 5 - `wazuh-agent` connection with `wazuh-manager`


<details>
<summary><code>wazuh-agent</code> is active 🟢</summary>

```
# /var/ossec/bin/agent_control -l

Wazuh agent_control. List of available agents:
   ID: 000, Name: ip-172-31-26-40 (server), IP: 127.0.0.1, Active/Local
   ID: 001, Name: ip-172-31-19-46, IP: any, Active
```

</details>


<details>
<summary><code>wazuh-agent</code> is reporting events to the <code>wazuh-manager</code>, and the <code>wazuh-manager</code> is generating alerts 🟢</summary>

```
# egrep '"agent":{"id":"001"' /var/ossec/logs/alerts/alerts.json | wc -l

198
```

</details>


<details>
<summary><code>UDP</code> connection (reporting events and generating alerts) 🟢</summary>

```
** Alert 1650376390.1070609: - ossec,pci_dss_10.6.1,pci_dss_10.2.6,gpg13_10.1,gdpr_IV_35.7.d,hipaa_164.312.b,nist_800_53_AU.6,nist_800_53_AU.14,nist_800_53_AU.5,tsc_CC7.2,tsc_CC7.3,tsc_CC6.8,
2022 Apr 19 13:53:10 (ip-172-31-19-46) any->ossec
Rule: 503 (level 3) -> 'Ossec agent started.'
ossec: Agent started: 'ip-172-31-19-46->any'.
```

</details>

**Comment by jmv74211** [comment]
## Task 6 - `wazuh-manager` uninstallation 🟡

After uninstalling the `wazuh-manager` according to the documentation:

```
# apt remove --purge wazuh-manager -y
```

everything has been successfully deleted.

<details>
<summary>No errors when uninstalling 🟢</summary>

```
# apt remove --purge wazuh-manager -y

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libpython2-dev libpython2.7 libpython2.7-dev python2-dev python2.7-dev
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  wazuh-manager*
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 455 MB disk space will be freed.
(Reading database ... 109485 files and directories currently installed.)
Removing wazuh-manager (4.3.0-1) ...
(Reading database ... 90833 files and directories currently installed.)
Purging configuration files for wazuh-manager (4.3.0-1) ...
```

</details>

<details>
<summary><code>/var/ossec</code> files have been deleted 🟢</summary>

```
# ls /var/ossec

ls: cannot access /var/ossec: No such file or directory
```

</details>


<details>
<summary><code>wazuh-manager</code> service has been deleted 🔴</summary>

We can see that the service has not been removed correctly:

```
# systemctl status wazuh-manager

Warning: The unit file, source configuration file or drop-ins of wazuh-manager.service changed on disk. >
○ wazuh-manager.service - LSB: Start and stop Wazuh
     Loaded: loaded (/etc/init.d/wazuh-manager; generated)
     Active: inactive (dead) since Wed 2022-04-20 10:02:43 UTC; 5min ago
       Docs: man:systemd-sysv-generator(8)
        CPU: 34.232s

Apr 20 10:02:42 ip-172-31-26-40 env[7578]: Killing wazuh-authd...
Apr 20 10:02:43 ip-172-31-26-40 env[7578]: wazuh-agentlessd not running...
Apr 20 10:02:43 ip-172-31-26-40 env[7578]: wazuh-integratord not running...
Apr 20 10:02:43 ip-172-31-26-40 env[7578]: wazuh-dbd not running...
Apr 20 10:02:43 ip-172-31-26-40 env[7578]: wazuh-csyslogd not running...
Apr 20 10:02:43 ip-172-31-26-40 env[7578]: Killing wazuh-apid...
Apr 20 10:02:43 ip-172-31-26-40 env[7578]: Wazuh v4.3.0 Stopped
Apr 20 10:02:43 ip-172-31-26-40 systemd[1]: wazuh-manager.service: Deactivated successfully.
Apr 20 10:02:43 ip-172-31-26-40 systemd[1]: Stopped Wazuh manager.
Apr 20 10:02:43 ip-172-31-26-40 systemd[1]: wazuh-manager.service: Consumed 34.232s CPU time.

```

```
# ls -l /etc/systemd/system/multi-user.target.wants/ | grep wazuh

lrwxrwxrwx 1 root root 41 Apr 19 10:16 wazuh-manager.service -> /lib/systemd/system/wazuh-manager.service
```

</details>

**Comment by jmv74211** [comment]
## Task 7 - `wazuh-agent`  uninstallation 🟢

After uninstalling the `wazuh-agent` according to the documentation:

```
# apt-get remove --purge wazuh-agent
```

everything has been successfully deleted.

<details>
<summary>No errors when uninstalling 🟢</summary>

```
# apt-get remove wazuh-agent

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libpython2-dev libpython2.7 libpython2.7-dev python2-dev python2.7-dev
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  wazuh-agent
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 26.6 MB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 91155 files and directories currently installed.)
Removing wazuh-agent (4.3.0-1) ...
```

</details>


<details>
<summary>The <code>wazuh-agent</code> has been disconnected from the <code>wazuh-manager</code> 🟢</summary>

```
ID: 001, Name: ip-172-31-19-46, IP: any, Disconnected
```

</details>


<details>
<summary><code>/var/ossec</code> files have been deleted 🟢</summary>

```
# ls /var/ossec

ls: cannot access /var/ossec: No such file or directory
```

</details>

<details>
<summary><code>wazuh-agent</code> service has been deleted 🟢</summary>

```
# systemctl status wazuh-agent

Unit wazuh-agent.service could not be found.
```

</details>

**Comment by jmv74211** [comment]
## Task 8 - `wazuh-manager` upgrade 🟢

The upgrade process from `4.2.6` to `4.3.0` has been successfully done.

<details>
<summary>Upgrade process 🟢</summary>

```

# /var/ossec/bin/wazuh-control info -v
v4.2.6

# apt-get install wazuh-manager -y
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libpython2-dev libpython2.7 libpython2.7-dev python2-dev python2.7-dev
Use 'sudo apt autoremove' to remove them.
Suggested packages:
  expect
The following packages will be upgraded:
  wazuh-manager
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/119 MB of archives.
After this operation, 7,758 kB of additional disk space will be used.
(Reading database ... 109364 files and directories currently installed.)
Preparing to unpack .../wazuh-manager_4.3.0-1_amd64.deb ...
Unpacking wazuh-manager (4.3.0-1) over (4.2.6-1) ...
Setting up wazuh-manager (4.3.0-1) ...
Installing new version of config file /etc/init.d/wazuh-manager ...
Scanning processes...                                                                                   
Scanning linux images...                                                                                
Running kernel seems to be up-to-date.
No services need to be restarted.
No containers need to be restarted.
No user sessions are running outdated binaries.
No VM guests are running outdated hypervisor (qemu) binaries on this host.

# /var/ossec/bin/wazuh-control info -v
v4.3.0
```

</details>


<details>
<summary>Connected agents reconnection 🟢</summary>

```
# egrep -i "ERROR|WARNING|connected" /var/ossec/logs/ossec.log

2022/04/20 14:36:25 wazuh-agentd: INFO: (4102): Connected to the server (172.31.26.40:1514/tcp).
2022/04/20 14:36:27 wazuh-agentd: INFO: (4102): Connected to the server (172.31.26.40:1514/tcp).
2022/04/20 14:40:27 wazuh-agentd: ERROR: (1137): Lost connection with manager. Setting lock.
2022/04/20 14:40:27 wazuh-agentd: ERROR: (1216): Unable to connect to '172.31.26.40:1514/tcp': 'Connection refused'.
2022/04/20 14:40:27 wazuh-syscheckd: WARNING: Process locked due to agent is offline. Waiting for connection...
2022/04/20 14:40:37 wazuh-agentd: ERROR: (1216): Unable to connect to '172.31.26.40:1514/tcp': 'Connection refused'.
2022/04/20 14:40:47 wazuh-agentd: ERROR: (1216): Unable to connect to '172.31.26.40:1514/tcp': 'Connection refused'.
2022/04/20 14:40:57 wazuh-agentd: ERROR: (1216): Unable to connect to '172.31.26.40:1514/tcp': 'Connection refused'.
2022/04/20 14:41:07 wazuh-agentd: ERROR: (1216): Unable to connect to '172.31.26.40:1514/tcp': 'Connection refused'.
2022/04/20 14:41:07 wazuh-agentd: ERROR: Unable to connect to 172.31.26.40:1515
2022/04/20 14:41:17 wazuh-agentd: WARNING: (4101): Waiting for server reply (not started). Tried: '172.31.26.40'.
2022/04/20 14:41:17 wazuh-agentd: WARNING: Unable to connect to any server.
2022/04/20 14:41:17 wazuh-agentd: INFO: (4102): Connected to the server (172.31.26.40:1514/tcp).
```

</details>


<details>
<summary>No errors in <code>ossec.log</code> 🟢</summary>

```
# egrep -i "ERROR|WARNING|connected" /var/ossec/logs/ossec.log

2022/04/20 14:41:05 wazuh-modulesd: WARNING: The <ignore_time> tag at module 'vulnerability-detector' is deprecated for version newer than 4.3.
2022/04/20 14:41:16 wazuh-modulesd: WARNING: The <ignore_time> tag at module 'vulnerability-detector' is deprecated for version newer than 4.3.
```

</details>


<details>
<summary>New API processes and process users 🟢</summary>

```
root@ip-172-31-26-40:/home/ubuntu# ps -aux | grep wazuh

wazuh      81610  1.0  2.4 583576 93444 ?        Sl   14:57   0:06 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
root       81653  0.4  0.1 114276  5672 ?        Sl   14:57   0:02 /var/ossec/bin/wazuh-authd
wazuh      81672  0.0  0.3 695296 12420 ?        Sl   14:57   0:00 /var/ossec/bin/wazuh-db
wazuh      81685  0.0  1.5 154444 59100 ?        S    14:57   0:00 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
wazuh      81688  0.0  1.6 309144 61260 ?        S    14:57   0:00 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
root       81704  0.0  0.0  24184  3092 ?        Sl   14:57   0:00 /var/ossec/bin/wazuh-execd
wazuh      81721  0.1  0.7 1276248 26804 ?       Sl   14:57   0:00 /var/ossec/bin/wazuh-analysisd
root       81767  1.7  0.2 189708  8148 ?        SNl  14:57   0:11 /var/ossec/bin/wazuh-syscheckd
wazuh      81786  0.1  0.1 1164072 5604 ?        Sl   14:57   0:00 /var/ossec/bin/wazuh-remoted
root       81820  0.0  0.1 466612  4564 ?        Sl   14:57   0:00 /var/ossec/bin/wazuh-logcollector
wazuh      81847  0.0  0.0  24156  3248 ?        Sl   14:57   0:00 /var/ossec/bin/wazuh-monitord
root       81874  0.0  0.3 1028704 14844 ?       Sl   14:57   0:00 /var/ossec/bin/wazuh-modulesd
```

</details>


<details>
<summary>Clean old <code>ossec</code> users and add <code>wazuh</code> one 🟢</summary>

```
v4.2.6
------
# grep ossec /etc/passwd
ossec:x:113:120::/var/ossec:/sbin/nologin
ossecm:x:114:120::/var/ossec:/sbin/nologin
ossecr:x:115:120::/var/ossec:/sbin/nologin

v4.3.0
------

# grep ossec /etc/passwd
wazuh:x:116:121::/var/ossec:/sbin/nologin

# grep wazuh /etc/passwd
wazuh:x:116:121::/var/ossec:/sbin/nologin
```

</details>

**Comment by jmv74211** [comment]
## Task 9 - `wazuh-agent` upgrade 🟢

The upgrade process from `4.2.6` to `4.3.0` has been successfully done.

<details>
<summary>Upgrade process 🟢</summary>

```
# /var/ossec/bin/wazuh-control info -v
v4.2.6

# apt-get install wazuh-agent -y
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libpython2-dev libpython2.7 libpython2.7-dev python2-dev python2.7-dev
Use 'sudo apt autoremove' to remove them.
The following packages will be upgraded:
  wazuh-agent
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 8,244 kB of archives.
After this operation, 4,364 kB of additional disk space will be used.
Get:1 https://s3-us-west-1.amazonaws.com/packages-dev.wazuh.com/pre-release/apt unstable/main amd64 wazuh-agent amd64 4.3.0-1 [8,244 kB]
Fetched 8,244 kB in 4s (2,306 kB/s)      
Preconfiguring packages ...
(Reading database ... 91112 files and directories currently installed.)
Preparing to unpack .../wazuh-agent_4.3.0-1_amd64.deb ...
Unpacking wazuh-agent (4.3.0-1) over (4.2.6-1) ...
Setting up wazuh-agent (4.3.0-1) ...
Installing new version of config file /etc/init.d/wazuh-agent ...
needrestart is being skipped since dpkg has failed

# /var/ossec/bin/wazuh-control info -v
v4.3.0
```

</details>


<details>
<summary><code>wazuh-agent</code> reconnected to the <code>wazuh-manager</code> 🟢</summary>

```
# /var/ossec/bin/agent_control -l | grep "ID: 001"

ID: 001, Name: ip-172-31-19-46, IP: any, Active
```

</details>


<details>
<summary>No errors in <code>ossec.log</code> 🟢</summary>

```
# egrep -i "ERROR|WARNING|connected" /var/ossec/logs/ossec.log
#
```

</details>


<details>
<summary>New API processes and process users 🟢</summary>

```
v4.2.6
------
# ps -aux | grep wazuh

root       12059  0.0  0.0  21800  2720 ?        Sl   15:30   0:00 /var/ossec/bin/wazuh-execd
ossec      12070  0.4  0.1 243536  5020 ?        Sl   15:30   0:00 /var/ossec/bin/wazuh-agentd
root       12084  9.8  0.2 253464  7764 ?        SNl  15:30   0:10 /var/ossec/bin/wazuh-syscheckd
root       12098  0.0  0.1 464268  4140 ?        Sl   15:30   0:00 /var/ossec/bin/wazuh-logcollector
root       12115  0.5  0.5 722820 19260 ?        Sl   15:30   0:00 /var/ossec/bin/wazuh-modulesd

v4.3.0
------
# ps -aux | grep wazuh

root        9067  0.0  0.0  23536  2760 ?        Sl   15:01   0:00 /var/ossec/bin/wazuh-execd
wazuh       9078  0.0  0.1 245180  5284 ?        Sl   15:01   0:00 /var/ossec/bin/wazuh-agentd
root        9092  0.3  0.1 253348  4820 ?        SNl  15:01   0:04 /var/ossec/bin/wazuh-syscheckd
root        9108  0.0  0.1 465872  4372 ?        Sl   15:01   0:00 /var/ossec/bin/wazuh-logcollector
root        9129  0.0  0.3 724688 13172 ?        Sl   15:01   0:00 /var/ossec/bin/wazuh-modulesd
```

</details>


<details>
<summary>Clean old <code>ossec</code> user and add `wazuh` one 🟢</summary>

```
v4.2.6
------
# grep ossec /etc/passwd
ossec:x:113:120::/var/ossec:/sbin/nologin

v4.3.0
------
# grep ossec /etc/passwd
wazuh:x:116:121::/var/ossec:/sbin/nologin

# grep wazuh /etc/passwd
wazuh:x:116:121::/var/ossec:/sbin/nologin
```

</details>
