### ISSUE TITLE
Add test_feeds cases for SUSE Linux Enterprise

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#2807]
| Related problem |
| --- |
| https://github.com/wazuh/wazuh-qa/issues/2792 |

### Description

As part of https://github.com/wazuh/wazuh-qa/issues/2792, it is necessary to add cases in the test_feeds suite related to SUSE Linux Enterprise support for the Wazuh Vulnerability Detector module.

**Suite test_feeds**

- `Test download feeds`: Prove that it is downloaded, and that the update date is recent.
- `Test duplicate feeds`: Test that after downloading the feed again, the vulnerabilities of the feeds are not duplicated
- `Test import invalid feed type`: Test behavior when an invalid feed URL is entered
- `Test validate feed content`: It downloads the feed files and checks that they are parseable (XML or JSON).

### To Do 

- [x] Add new custom SUSE feed
- [x] Add download feeds tests
- [x] Add duplicate feeds tests.
- [x] Add import invalid feed type tests.
- [x] Add validate feed content tests.
- [x] Add SUSE OS to the test documentation

**Comment by damarisg** [comment]
### Task 1 - Add new custom SUSE feed

- This was added on `2792-add-support-for-SUSE-OVAL-in-Vulnerability-Detector` temporal branch.

**Comment by damarisg** [comment]
### Task 2 - Add download feeds tests

- I create a branch 2807-add-test-feeds-cases to make it work.
- I see test_download_feeds.
- I check PR with changes related to test_downaload_feed
- I set up an environment to check how to work VD with SUSE manually.
      - Problems with the installation of SUSE.
      - Investigation of installation failures.
      - Problems solved.
- Add cases of download feeds for SUSE.

**Comment by CamiRomero** [comment]
## Task 2 - Add new custom SUSE feed

Modify cases in `tests/integration/test_vulnerability_detector/test_feeds/test_download_feeds.py`

> - name: 'SUSE Linux Enterprise Server 11'
  description: 'SUSE Linux Enterprise provider'
  configuration_parameters:
    PROVIDER: 'suse'
    OS: '11-server'
  metadata:
    provider_name: 'SUSE Linux Enterprise Server 11'
    provider_os: 'SLES11'
    download_timeout: 360
    update_treshold_weeks: 2

> - name: 'SUSE Linux Enterprise Server 12'
  description: 'SUSE Linux Enterprise provider'
  configuration_parameters:
    PROVIDER: 'suse'
    OS: '12-server'
  metadata:
    provider_name: 'SUSE Linux Enterprise Server 12'
    provider_os: 'SLES12'
    download_timeout: 360
    update_treshold_weeks: 2

> - name: 'SUSE Linux Enterprise Server 15'
  description: 'SUSE Linux Enterprise provider'
  configuration_parameters:
    PROVIDER: 'suse'
    OS: '15-server'
  metadata:
    provider_name: 'SUSE Linux Enterprise Server 15'
    provider_os: 'SLES15'
    download_timeout: 360
    update_treshold_weeks: 2

> - name: 'SUSE Linux Enterprise Desktop 11'
  description: 'SUSE Linux Enterprise provider'
  configuration_parameters:
    PROVIDER: 'suse'
    OS: '11-desktop'
  metadata:
    provider_name: 'SUSE Linux Enterprise Desktop 11'
    provider_os: 'SLED11'
    download_timeout: 360
    update_treshold_weeks: 2

> - name: 'SUSE Linux Enterprise Desktop 12'
  description: 'SUSE Linux Enterprise provider'
  configuration_parameters:
    PROVIDER: 'suse'
    OS: '12-desktop'
  metadata:
    provider_name: 'SUSE Linux Enterprise Desktop 12'
    provider_os: 'SLED12'
    download_timeout: 360
    update_treshold_weeks: 2

> - name: 'SUSE Linux Enterprise Desktop 13'
  description: 'SUSE Linux Enterprise provider'
  configuration_parameters:
    PROVIDER: 'suse'
    OS: '15-desktop'
  metadata:
    provider_name: 'SUSE Linux Enterprise Desktop 15'
    provider_os: 'SLED15'
    download_timeout: 360
    update_treshold_weeks: 2

Results: 

![imagen](https://user-images.githubusercontent.com/37776796/165558401-f4e9a9f7-1188-4687-9990-a9c1f0cec705.png)

**Comment by CamiRomero** [comment]
## Task 3: Add duplicate feeds tests.

Add case in tests/integration/test_vulnerability_detector/test_feeds/cases_duplicate_feeds.yml

> - name: 'SUSE'
  description: 'SUSE Linux Enterprise'
  configuration_parameters:
    PROVIDER: 'suse'
    OS: '11-desktop'
    OS_PATH: CUSTOM_SUSE_OVAL_FEED
  metadata:
    provider_name: 'SUSE Linux Enterprise Desktop 11'
    provider_json_name: ''

Result:

![imagen](https://user-images.githubusercontent.com/37776796/165563525-08509f94-63e2-465b-88a5-015651ad9304.png)

**Comment by CamiRomero** [comment]
## Task 4 -  Add import invalid feed type tests.

Add case in tests/integration/test_vulnerability_detector/test_feeds/data/test_cases/cases_import_invalid_feed_type.yaml

> - name: 'SUSE - JPG'
  description: 'Check downloading and parsing of JPG file as invalid feed in Suse provider'
  configuration_parameters: null
  metadata:
    target: 'suse'
    custom_feed_url: https://s3.amazonaws.com/ci.wazuh.com/qa/testing_files/dummy_files/dummy.jpg
    provider_feed_names:
      - "suse SLED11"

Add configuration for suse in tests/integration/test_vulnerability_detector/test_feeds/data/configuration_template/configuration_import_invalid_feed_type.yaml:

>   SUSE configuration

**Comment by CamiRomero** [comment]
## Task 7 - Add SUSE OS to the test documentation

Added OS in tests involved

>  - SUSE Linux Enterprise Desktop 11
    - SUSE Linux Enterprise Desktop 12
    - SUSE Linux Enterprise Desktop 15
    - SUSE Linux Enterprise Server 11
    - SUSE Linux Enterprise Server 12
    - SUSE Linux Enterprise Server 15

**Comment by damarisg** [comment]
It was merge to `2792-add-support-for-SUSE-OVAL-in-Vulnerability-Detector` branch.
