### ISSUE TITLE
Add test_scan_results cases for SUSE Linux Enterprise (1/2)

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#2809]
| Related problem |
| --- |
| https://github.com/wazuh/wazuh-qa/issues/2792 |

### Description

As part of https://github.com/wazuh/wazuh-qa/issues/2792, it is necessary to add cases in the test_scan_results suite related to SUSE Linux Enterprise support for the Wazuh Vulnerability Detector module.

**Suite test_scan_results**

- `Test scan provider and NVD vulnerabilities`: Test that vulnerable packages are reported using the OVAL and NVD feed.
- `Test scan provider vulnerabilities`: Test that vulnerable packages are reported using the OVAL feed (NVD contains different vulnerabilities).
- `Test scan vulnerability removal`: Check that it generates vulnerability alert fixed after removing or updating a vulnerable package.

### To Do 

- [x] Add new custom SUSE feed
- [x] Add scan provider vulnerabilities tests.
- [ ] Add scan provider and NVD vulnerabilities tests
- [ ] Add scan vulnerability removal tests.
- [x] Add SUSE OS to the test documentation

**Comment by Deblintrake09** [comment]
## Task 5 - Add SUSE OS to the test documentation

Added OS in tests involved

>  - SUSE Linux Enterprise Desktop 11
    - SUSE Linux Enterprise Desktop 12
    - SUSE Linux Enterprise Desktop 15
    - SUSE Linux Enterprise Server 11
    - SUSE Linux Enterprise Server 12
    - SUSE Linux Enterprise Server 15

**Comment by Deblintrake09** [comment]
### TASK 2 - Add test cases to test_scan_provider_vulnerabilities

- Working to add test cases to test_scan_providers_vulnerabilities
- Error on Manager when trying to do manual testing
- Create new testing environment
- Tests get stuck when running on package
```
test_vulnerability_detector/test_scan_results/test_scan_provider_vulnerabilities.py::test_scan_provider_vulnerabilities[RHEL] ^C

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! KeyboardInterrupt !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
/usr/local/lib/python3.6/site-packages/wazuh_testing/db_interface/__init__.py:83: KeyboardInterrupt
(to show a full traceback on KeyboardInterrupt use --full-trace)
================================================ no tests ran in 289.26s (0:04:49) ================================================
```

**Comment by Deblintrake09** [comment]
# Task 3 - Add scan vulnerability removal tests.

- Start analyzing test_scan_vulnerabilities_removal.

**Comment by damarisg** [comment]
Closed. This issue continues in the next sprint https://github.com/wazuh/wazuh-qa/issues/2899
