### ISSUE TITLE
Release 4.3.0 - Manual tests - Demo environment

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#2819]
The following issue aims to run the specified test for the current release candidate, report the results, and open new issues for any encountered errors.

## Test information
|                         |                                            |
|-------------------------|--------------------------------------------|
| **Test name**           |Demo environment|
| **Category**            |Wazuh App|
| **Deployment option**   |Demo environment|
| **Main release issue**  |https://github.com/wazuh/wazuh/issues/10954|
| **Release candidate #** |RC6|

## Test tasks
- [x]  ([**T1**](https://github.com/wazuh/wazuh-qa/issues/2819#issuecomment-1108504090)): - No errors or warnings found in logs
- [x]  ([**T2**](https://github.com/wazuh/wazuh-qa/issues/2819#issuecomment-1108714151)): - The daemons are running with the correct user
- [x]  ([**T3**](https://github.com/wazuh/wazuh-qa/issues/2819#issuecomment-1108772794)): - The status of the Wazuh Indexer clusters is as expected.
- [x]  ([**T4**](https://github.com/wazuh/wazuh-qa/issues/2819#issuecomment-1109900247)): - No errors in the browser's developer console when browsing the App
- [x]  ([**T5**](https://github.com/wazuh/wazuh-qa/issues/2819#issuecomment-1109970465)): - Alerts are being generated for each of the modules configured for this purpose.
- [x]  ([**T6**](https://github.com/wazuh/wazuh-qa/issues/2819#issuecomment-1109991358)): - No warning symbols in Discover when expanding a document.

### Open issues 

- https://github.com/wazuh/wazuh-kibana-app/issues/4104
- https://github.com/wazuh/wazuh-kibana-app/issues/4095
- https://github.com/wazuh/wazuh-kibana-app/issues/4093
- https://github.com/wazuh/wazuh-kibana-app/issues/4092
- https://github.com/wazuh/wazuh-kibana-app/issues/4105
- https://github.com/wazuh/wazuh-kibana-app/issues/4107
- https://github.com/wazuh/wazuh-kibana-app/issues/4108
- https://github.com/wazuh/wazuh-packages/issues/1489
- https://github.com/wazuh/wazuh-automation/issues/800
- https://github.com/wazuh/wazuh-automation/issues/801
- https://github.com/wazuh/wazuh-automation/issues/802
- https://github.com/wazuh/wazuh-automation/issues/803
- https://github.com/wazuh/wazuh-packages/issues/1490

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [x] @jmv74211 
- [x] @alberpilot 
- [x] @gdiazlo

**Comment by juliamagan** [comment]
## Task 1: No errors or warnings found in logs

### Agents

<details>
<summary>Amazon Linux 🟢 </summary>

- `journalctl -xe -u wazuh-agent.service`:

```
-- Unit wazuh-agent.service has begun shutting down.
abr 22 16:51:13 ip-10-0-1-42.us-west-1.compute.internal env[26184]: Killing wazuh-modulesd...
abr 22 16:51:13 ip-10-0-1-42.us-west-1.compute.internal env[26184]: Killing wazuh-logcollector...
abr 22 16:51:13 ip-10-0-1-42.us-west-1.compute.internal env[26184]: Killing wazuh-syscheckd...
abr 22 16:51:13 ip-10-0-1-42.us-west-1.compute.internal env[26184]: Killing wazuh-agentd...
abr 22 16:51:13 ip-10-0-1-42.us-west-1.compute.internal env[26184]: Killing wazuh-execd...
abr 22 16:51:14 ip-10-0-1-42.us-west-1.compute.internal env[26184]: Wazuh v4.3.0 Stopped
abr 22 16:51:14 ip-10-0-1-42.us-west-1.compute.internal systemd[1]: Starting Wazuh agent...
-- Subject: Unit wazuh-agent.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit wazuh-agent.service has begun starting up.
abr 22 16:51:14 ip-10-0-1-42.us-west-1.compute.internal env[26249]: Starting Wazuh v4.3.0...
abr 22 16:51:15 ip-10-0-1-42.us-west-1.compute.internal env[26249]: Started wazuh-execd...
abr 22 16:51:16 ip-10-0-1-42.us-west-1.compute.internal env[26249]: Started wazuh-agentd...
abr 22 16:51:17 ip-10-0-1-42.us-west-1.compute.internal env[26249]: Started wazuh-syscheckd...
abr 22 16:51:18 ip-10-0-1-42.us-west-1.compute.internal env[26249]: Started wazuh-logcollector...
abr 22 16:51:18 ip-10-0-1-42.us-west-1.compute.internal crontab[26416]: (root) LIST (root)
abr 22 16:51:19 ip-10-0-1-42.us-west-1.compute.internal env[26249]: Started wazuh-modulesd...
abr 22 16:51:21 ip-10-0-1-42.us-west-1.compute.internal env[26249]: Completed.
abr 22 16:51:21 ip-10-0-1-42.us-west-1.compute.internal systemd[1]: Started Wazuh agent.
-- Subject: Unit wazuh-agent.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit wazuh-agent.service has finished starting up.
-- 
-- The start-up result is done.
```

- `egrep -i "ERROR|WARNING| /var/ossec/logs/ossec.log`:

```
[root@ip-10-0-1-42 wazuh-user]# egrep -i "ERROR|WARNING" /var/ossec/logs/ossec.log
```

- `systemctl status wazuh-agent -l`:

```
[root@ip-10-0-1-42 wazuh-user]# systemctl status wazuh-agent -l
● wazuh-agent.service - Wazuh agent
   Loaded: loaded (/usr/lib/systemd/system/wazuh-agent.service; enabled; vendor preset: disabled)
   Active: active (running) since vie 2022-04-22 16:51:21 UTC; 2 days ago
  Process: 26184 ExecStop=/usr/bin/env /var/ossec/bin/wazuh-control stop (code=exited, status=0/SUCCESS)
  Process: 26249 ExecStart=/usr/bin/env /var/ossec/bin/wazuh-control start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/wazuh-agent.service
           ├─26277 /var/ossec/bin/wazuh-execd
           ├─26289 /var/ossec/bin/wazuh-agentd
           ├─26304 /var/ossec/bin/wazuh-syscheckd
           ├─26318 /var/ossec/bin/wazuh-logcollector
           └─26340 /var/ossec/bin/wazuh-modulesd

abr 22 16:51:14 ip-10-0-1-42.us-west-1.compute.internal env[26249]: Starting Wazuh v4.3.0...
abr 22 16:51:15 ip-10-0-1-42.us-west-1.compute.internal env[26249]: Started wazuh-execd...
abr 22 16:51:16 ip-10-0-1-42.us-west-1.compute.internal env[26249]: Started wazuh-agentd...
abr 22 16:51:17 ip-10-0-1-42.us-west-1.compute.internal env[26249]: Started wazuh-syscheckd...
abr 22 16:51:18 ip-10-0-1-42.us-west-1.compute.internal env[26249]: Started wazuh-logcollector...
abr 22 16:51:18 ip-10-0-1-42.us-west-1.compute.internal crontab[26416]: (root) LIST (root)
abr 22 16:51:19 ip-10-0-1-42.us-west-1.compute.internal env[26249]: Started wazuh-modulesd...
abr 22 16:51:21 ip-10-0-1-42.us-west-1.compute.internal env[26249]: Completed.
abr 22 16:51:21 ip-10-0-1-42.us-west-1.compute.internal systemd[1]: Started Wazuh agent.
abr 23 04:51:19 ip-10-0-1-42.us-west-1.compute.internal crontab[30469]: (root) LIST (root)
```

- `/var/ossec/bin/wazuh-control status`:

```
[root@ip-10-0-1-42 wazuh-user]# /var/ossec/bin/wazuh-control status
wazuh-modulesd is running...
wazuh-logcollector is running...
wazuh-syscheckd is running...
wazuh-agentd is running...
wazuh-execd is running...
```


</details>

<details>
<summary>RHEL</summary>
</details>
### Managers

### Wazuh Indexer

### Wazuh Dashboard

**Comment by juliamagan** [comment]
## Task 2: The daemons are running with the correct user

### Agents

<details>
<summary>Amazon Linux  </summary>




</details>

<details>
<summary>RHEL </summary>



</details>

<details>
<summary>Ubuntu  </summary>



</details>

<details>
<summary>Centos  </summary>



</details>

<details>
<summary>Debian  </summary>



</details>

<details>
<summary>Windows  </summary>




</details>

### Managers

<details>
<summary>Master env 1  </summary>



</details>

<details>
<summary>Master env 2  </summary>



</details>


### Wazuh Indexer

<details>
<summary>Bootstrap  </summary>



</details>


<details>
<summary>Master B  </summary>



</details>

<details>
<summary>Master C  </summary>



</details>

### Wazuh Dashboard

<details>
<summary>wazuh-indexer  </summary>



</details>

<details>
<summary>wazuh-dashboard  </summary>



</details>

**Comment by juliamagan** [comment]
## Task 3: The status of the Wazuh Indexer clusters is as expected.

```
[root@ip-10-0-0-184 wazuh-user]# curl -k -u wazuh:ToKDVUeRwxAey3xM https://10.0.0.184:9200/_cat/nodes?v
ip         heap.percent ram.percent cpu load_1m load_5m load_15m node.role master name
10.0.2.167           27          91   1    0.00    0.00     0.00 dimr      -      node-1
10.0.0.184           61          98   1    0.00    0.00     0.00 dimr      -      node-7
10.0.2.249           42          91   1    0.00    0.01     0.00 dimr      -      node-3
10.0.2.198           21          91   1    0.03    0.03     0.00 dimr      *      node-2
```

**Comment by juliamagan** [comment]
## Task 4: No errors in the browser's developer console when browsing the App

If we search a rule file, we get:

```
Uncaught TypeError: this.inputRef is undefined
```

If we modify a rule and restart the manager, we get:

```
Element.setCapture() is deprecated. Use Element.setPointerCapture() instead. For more help https://developer.mozilla.org/docs/Web/API/Element/setPointerCapture

Element.releaseCapture() is deprecated. Use Element.releasePointerCapture() instead. For more help https://developer.mozilla.org/docs/Web/API/Element/releasePointerCapture
```

If we go to an agent and click on the path of an FIM event, we get:

```
Uncaught TypeError: right-hand side of 'in' should be an object, got boolean
```

If we get more information in API Console, we get:
```
Storage access automatically granted for origin “https://documentation.wazuh.com” on “https://demo.wazuh.info”.
```

If we logout, we get:

```
Cookie “security_authentication” has been rejected because it is already expired. 
Cookie “security_authentication” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite 
Cookie “security_authentication” has been rejected because it is already expired. 
Cookie “security_authentication” has been rejected because it is already expired. 
Some cookies are misusing the recommended “SameSite“ attribute 
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). 
Cookie “security_authentication” has been rejected because it is already expired.
^ A single error about an inline script not firing due to content security policy is expected! 
window.controllers/Controllers is deprecated. Do not use it for UA detection. 
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. 
XHRGEThttps://demo.wazuh.info/api/v1/restapiinfo
[HTTP/1.1 401 Unauthorized 202ms]

Cookie “security_authentication” has been rejected because it is already expired. 
Error: Unauthorized
    _construct https://demo.wazuh.info/1/bundles/core/core.entry.js:6
    Wrapper https://demo.wazuh.info/1/bundles/core/core.entry.js:6
    _createSuperInternal https://demo.wazuh.info/1/bundles/core/core.entry.js:6
    HttpFetchError https://demo.wazuh.info/1/bundles/core/core.entry.js:6
    _callee3$ https://demo.wazuh.info/1/bundles/core/core.entry.js:6
    tryCatch https://demo.wazuh.info/1/bundles/plugin/reportsDashboards/reportsDashboards.plugin.js:1
    invoke https://demo.wazuh.info/1/bundles/plugin/reportsDashboards/reportsDashboards.plugin.js:1
    method https://demo.wazuh.info/1/bundles/plugin/reportsDashboards/reportsDashboards.plugin.js:1
    fetch_asyncGeneratorStep https://demo.wazuh.info/1/bundles/core/core.entry.js:6
    _next https://demo.wazuh.info/1/bundles/core/core.entry.js:6
    promise callback*fetch_asyncGeneratorStep https://demo.wazuh.info/1/bundles/core/core.entry.js:6
    _next https://demo.wazuh.info/1/bundles/core/core.entry.js:6
    promise callback*fetch_asyncGeneratorStep https://demo.wazuh.info/1/bundles/core/core.entry.js:6
    _next https://demo.wazuh.info/1/bundles/core/core.entry.js:6
    fetch_asyncToGenerator https://demo.wazuh.info/1/bundles/core/core.entry.js:6
    fetch_asyncToGenerator https://demo.wazuh.info/1/bundles/core/core.entry.js:6
    fetchResponse https://demo.wazuh.info/1/bundles/core/core.entry.js:6
    _callee$ https://demo.wazuh.info/1/bundles/core/core.entry.js:6
    tryCatch https://demo.wazuh.info/1/bundles/plugin/reportsDashboards/reportsDashboards.plugin.js:1
    invoke https://demo.wazuh.info/1/bundles/plugin/reportsDashboards/reportsDashboards.plugin.js:1
    method https://demo.wazuh.info/1/bundles/plugin/reportsDashboards/reportsDashboards.plugin.js:1
    fetch_asyncGeneratorStep https://demo.wazuh.info/1/bundles/core/core.entry.js:6
    _next https://demo.wazuh.info/1/bundles/core/core.entry.js:6
    promise callback*fetch_asyncGeneratorStep https://demo.wazuh.info/1/bundles/core/core.entry.js:6
    _next https://demo.wazuh.info/1/bundles/core/core.entry.js:6
    fetch_asyncToGenerator https://demo.wazuh.info/1/bundles/core/core.entry.js:6
    fetch_asyncToGenerator https://demo.wazuh.info/1/bundles/core/core.entry.js:6
    _callee2$/</< https://demo.wazuh.info/1/bundles/core/core.entry.js:6
    _callee2$ https://demo.wazuh.info/1/bundles/core/core.entry.js:6
    tryCatch https://demo.wazuh.info/1/bundles/plugin/reportsDashboards/reportsDashboards.plugin.js:1
    invoke https://demo.wazuh.info/1/bundles/plugin/reportsDashboards/reportsDashboards.plugin.js:1
    method https://demo.wazuh.info/1/bundles/plugin/reportsDashboards/reportsDashboards.plugin.js:1
    fetch_asyncGeneratorStep https://demo.wazuh.info/1/bundles/core/core.entry.js:6
    _next https://demo.wazuh.info/1/bundles/core/core.entry.js:6
    fetch_asyncToGenerator https://demo.wazuh.info/1/bundles/core/core.entry.js:6
    fetch_asyncToGenerator https://demo.wazuh.info/1/bundles/core/core.entry.js:6
    Fetch https://demo.wazuh.info/1/bundles/core/core.entry.js:6
    shorthand https://demo.wazuh.info/1/bundles/core/core.entry.js:6
    _callee5$ https://demo.wazuh.info/1/bundles/plugin/securityDashboards/securityDashboards.plugin.js:13
    tryCatch https://demo.wazuh.info/1/bundles/plugin/reportsDashboards/reportsDashboards.plugin.js:1
    invoke https://demo.wazuh.info/1/bundles/plugin/reportsDashboards/reportsDashboards.plugin.js:1
    method https://demo.wazuh.info/1/bundles/plugin/reportsDashboards/reportsDashboards.plugin.js:1
    public_plugin_asyncGeneratorStep https://demo.wazuh.info/1/bundles/plugin/securityDashboards/securityDashboards.plugin.js:13
    _next https://demo.wazuh.info/1/bundles/plugin/securityDashboards/securityDashboards.plugin.js:13
    public_plugin_asyncToGenerator https://demo.wazuh.info/1/bundles/plugin/securityDashboards/securityDashboards.plugin.js:13
    public_plugin_asyncToGenerator https://demo.wazuh.info/1/bundles/plugin/securityDashboards/securityDashboards.plugin.js:13
    _hasApiPermission https://demo.wazuh.info/1/bundles/plugin/securityDashboards/securityDashboards.plugin.js:13
    hasApiPermission https://demo.wazuh.info/1/bundles/plugin/securityDashboards/securityDashboards.plugin.js:13
    _callee4$ https://demo.wazuh.info/1/bundles/plugin/securityDashboards/securityDashboards.plugin.js:13
    tryCatch https://demo.wazuh.info/1/bundles/plugin/reportsDashboards/reportsDashboards.plugin.js:1
    invoke https://demo.wazuh.info/1/bundles/plugin/reportsDashboards/reportsDashboards.plugin.js:1
    method https://demo.wazuh.info/1/bundles/plugin/reportsDashboards/reportsDashboards.plugin.js:1

XHR GET https://demo.wazuh.info/api/v1/configuration/account HTTP/1.1 401 Unauthorized 291ms]

Cookie “security_authentication” has been rejected because it is already expired. 

XHR GET https://demo.wazuh.info/api/v1/configuration/account [HTTP/1.1 401 Unauthorized 185ms]

XHR GET https://demo.wazuh.info/api/v1/multitenancy/tenant [HTTP/1.1 401 Unauthorized 216ms]

Cookie “security_authentication” has been rejected because it is already expired. 
Cookie “security_authentication” has been rejected because it is already expired.

failed to get user tenant: Error: Unauthorized
```


### Extra

Issues opened by @Rebits:

- https://github.com/wazuh/wazuh-kibana-app/issues/4095
- https://github.com/wazuh/wazuh-kibana-app/issues/4093
- https://github.com/wazuh/wazuh-kibana-app/issues/4092

**Comment by juliamagan** [comment]
## Task 5: Alerts are being generated for each of the modules configured for this purpose.

The only module that is not generating alerts is Security Auditing in environment 2, however, this module appears by default. The Amazon agent does have the audit log configured in localfile, but there are no rules created, while the Ubuntu agent does not even have the log.

**Comment by juliamagan** [comment]
## Task 6:  No warning symbols in Discover when expanding a document.

After performing several tests both in Discover and in different modules, we have not been able to find any warning.
