### ISSUE TITLE
System tests: Create containers for the deployment tool

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh-qa#2828]
## Description

As we are providing ECS support(https://github.com/wazuh/wazuh-jenkins/issues/3448) for the new deployment tool development(https://github.com/wazuh/wazuh-qa/issues/2788), we need to have some containers in ECR for each OS.

This issue aims to have a collection of the containers that the tool needs to deploy images.

## Tasks
- [x] Get a list of the required containers to be created
- [ ] Create every image dockerfile
  - [x] Ubuntu 22
  - [ ] Centos 8 (on hold)
  - [x] Debian 11
  - [ ] Solaris 11
  - [ ] RedHat 8 (on hold)
  - [ ] ALAS 2 (on hold)

**Comment by roronoasins** [comment]
### 27/04/22

I have created the dockerfile for Ubuntu Jammy(both compiling and using ppa repo) with the following requirements:

- `python 3.10`
- `pip 21.3.1`
- `ip`
- `ifconfig`
- editor: `vim, nano`
- `sudo`, `visudo`
- passwordless ssh
- custom qa user
- custom qa user and root passwords

**Comment by roronoasins** [comment]
Issue moved to [wazuh/wazuh-jenkins #3514](https://github.com/wazuh/wazuh-jenkins/issues/3514) via [**ZenHub**](https://www.zenhub.com/)
