### ISSUE TITLE
E2E Research: Brute force

### ISSUE THREAD

**Issue by BelenValdivia** [wazuh/wazuh-qa#2838]
## Description
This issue aims to test manually the Brute force attack (SSH and RDP) to define the requirements to develop an automated test.

We follow these guides:

- Detect a SSH brute-force attack: https://documentation.wazuh.com/current/learning-wazuh/ssh-brute-force.html

- Detect a RDP brute-force attack: https://documentation.wazuh.com/current/learning-wazuh/rdp-brute-force.html

## Steps to detect a SSH brute-force attack.
- [x] (T1) Configure manager, filebeat, elasticsearch, kibana.
- [x] (T2) Configure a Linux agent.
- [x] (T3) Using SSH client, try to login as user "test_user" (user not authorized) to the Linux instance. Example: ssh test_user@10.0.0.10. Do this a total of 8 times, making sure to get all the attemps in the same 2-minute time windows.
- [x] (T4) Check alerts on Wazuh manager instance.
- [x] (T5) Check alerts on Kibana. 
- [x] ([T6](https://github.com/wazuh/wazuh-qa/issues/2838#issuecomment-1116460863)) Check alerts through API.

## Steps to detect a RDP brute-force attack.
- [x] (T1) Configure manager, filebeat, elasticsearch, kibana.
- [x] (T2) Configure a Windows agent.
- [x] (T3) Using a Windows Remote Desktop client, attempt to log in as user “testuser” to Windows Agent instance eight times in a fairly small time window.
- [x] (T4) Check alerts on Wazuh manager instance.
- [x] (T5) Check alerts on Kibana. 
- [x] ([T6](https://github.com/wazuh/wazuh-qa/issues/2838#issuecomment-1117261104)) Check alerts through API.

## Conclusion 🟢 
The different use cases tested were successful. I configured a manager, filebeat, kibana and elastic in the same machine (Centos 8). I configured two agents Linux(Centos 8) and Windows(Windows Server 2019)

**Comment by BelenValdivia** [comment]
## Tasks to detect a SSH brute-force attack.

**Alert.log**
![alert log brute force](https://user-images.githubusercontent.com/26927338/166232935-8a30a680-1059-410a-9169-ef84e9240417.png)

**Kibana events**
![kibana brute force](https://user-images.githubusercontent.com/26927338/166233228-adc23241-930e-452f-8ab1-9a25f15f1826.png)

![brute force log](https://user-images.githubusercontent.com/26927338/166233635-34b97802-06f7-4b31-bbd9-90c7288c1d42.png)

**Comment by BelenValdivia** [comment]
## RDP brute-force attack

**Kibana:**
Added fields: rule.description, rule.id, data.win.eventdata.targetUserName, data.win.eventdata.ipAddress

![brute force windows](https://user-images.githubusercontent.com/26927338/166234608-12d9f659-7c40-4419-9f0f-bd770ee61377.png)

Multiple logon failures:

![brute force windows multiple logon failures](https://user-images.githubusercontent.com/26927338/166234960-ee405c6c-6420-4868-b603-ea0b3fbc547d.png)

Logon failure:

![windows brute force logon failure](https://user-images.githubusercontent.com/26927338/166235100-952678f6-2139-463a-bd80-718c5dc998c2.png)

**Comment by BelenValdivia** [comment]
## Check alerts through API

1. Request
```
curl --insecure -XGET -u 'USER:PASSWORD' "https://localhost:9200/wazuh-alerts-4.x-*/_search?pretty" -H 'Content-Type: application/json' -d '
{
  "query": {
    "term": {
      "rule.id": "5712"
    }
  }
}
'

```
2. Alert
    <details>
    <summary>alert</summary>

    ```
    {
      "took" : 21,
      "timed_out" : false,
      "_shards" : {
        "total" : 18,
        "successful" : 18,
        "skipped" : 0,
        "failed" : 0
      },
      "hits" : {
        "total" : {
          "value" : 1,
          "relation" : "eq"
        },
        "max_score" : 4.9272532,
        "hits" : [
          {
            "_index" : "wazuh-alerts-4.x-2022.04.28",
            "_type" : "_doc",
            "_id" : "XXX",
            "_score" : XXXX,
            "_source" : {
              "agent" : {
                "ip" : "X.X.X.X",
                "name" : "centos-agent",
                "id" : "001"
              },
              "data" : {
                "srcuser" : "test",
                "srcip" : "X.X.X.X"
              },
              "rule" : {
                "mail" : false,
                "level" : 10,
                "pci_dss" : [
                  "11.4",
                  "10.2.4",
                  "10.2.5"
                ],
                "hipaa" : [
                  "164.312.b"
                ],
                "tsc" : [
                  "CC6.1",
                  "CC6.8",
                  "CC7.2",
                  "CC7.3"
                ],
                "description" : "sshd: brute force trying to get access to the system.",
                "groups" : [
                  "syslog",
                  "sshd",
                  "authentication_failures"
                ],
                "nist_800_53" : [
                  "SI.4",
                  "AU.14",
                  "AC.7"
                ],
                "frequency" : 8,
                "gdpr" : [
                  "IV_35.7.d",
                  "IV_32.2"
                ],
                "firedtimes" : 1,
                "mitre" : {
                  "technique" : [
                    "Brute Force"
                  ],
                  "id" : [
                    "T1110"
                  ],
                  "tactic" : [
                    "Credential Access"
                  ]
                },
                "id" : "5712"
              },
              "full_log" : "Apr 28 21:12:19 centos-agent sshd[4532]: Failed password for invalid user test from X.X.X.X port 55804 ssh2",
              "id" : "XXXXXX",
              "timestamp" : "2022-04-28T21:12:20.667+0000",
              "predecoder" : {
                "hostname" : "centos-agent",
                "program_name" : "sshd",
                "timestamp" : "Apr 28 21:12:19"
              },
              "previous_output" : "Apr 28 21:12:19 centos-agent sshd[4532]: Failed password for invalid user test from X.X.X.X port 55804 ssh2\nApr 28 21:12:19 centos-agent sshd[4532]: Failed none fo
                r invalid user test from X.X.X.X port 55804 ssh2\nApr 28 21:12:18 centos-agent sshd[4532]: Invalid user test from X.X.X.X port 55804\nApr 28 21:12:17 centos-agent sshd[4530]: Failed password f
                or invalid user test from X.X.X.X port 55803 ssh2\nApr 28 21:12:16 centos-agent sshd[4530]: Failed password for invalid user test from X.X.X.X port 55803 ssh2\nApr 28 21:12:16 centos-agent ssh
                d[4530]: Failed none for invalid user test from 172.17.1.1 port 55803 ssh2\nApr 28 21:12:15 centos-agent sshd[4530]: Invalid user test from X.X.X.X port 55803",
              "manager" : {
                "name" : "centos-manager-kibana"
              },
              "decoder" : {
                "parent" : "sshd",
                "name" : "sshd"
              },
              "input" : {
                "type" : "log"
              },
              "@timestamp" : "2022-04-28T21:12:20.667Z",
              "location" : "/var/log/secure"
            }
          }
        ]
      }
    }
    ```
    
    </details>

**Comment by BelenValdivia** [comment]
## Check alert RDP brute force through API
1. Request

```
curl --insecure -XGET -u 'wazuh:pGT86aDkSLdGeUTB22LtzltWxpfua6D4' "https://172.17.1.18:9200/wazuh-alerts-4.x-*/_search?pretty" -H 'Content-Type: application/json' -d '
{
  "query": {
    "term": {
      "rule.id": "60204"
    }
  }
}
'
```

2.  Alert
    <details>
    <summary>alert</summary>
    
    ```
          {
            "_index" : "wazuh-alerts-4.x-2022.04.29",
            "_type" : "_doc",
            "_id" : "XXXX",
            "_score" : xxxxx,
            "_source" : {
              "agent" : {
                "ip" : "xx.xx.xx.xx",
                "name" : "WIN-JLGVA4CR4VI",
                "id" : "002"
              },
              "previous_output" : "xxx",
              "manager" : {
                "name" : "centos-manager-kibana"
              },
              "data" : {
                "win" : {
                  "eventdata" : {
                    "subjectLogonId" : "0x0",
                    "ipAddress" : "X.X.X.X",
                    "authenticationPackageName" : "NTLM",
                    "workstationName" : "WIN-JLGVA4CR4VI",
                    "subStatus" : "0xc0000064",
                    "logonProcessName" : "NtLmSsp",
                    "targetUserName" : "testuser",
                    "keyLength" : "0",
                    "subjectUserSid" : "S-1-0-0",
                    "processId" : "0x0",
                    "ipPort" : "0",
                    "failureReason" : "%%2313",
                    "targetDomainName" : "WIN-JLGVA4CR4VI",
                    "targetUserSid" : "S-1-0-0",
                    "logonType" : "3",
                    "status" : "0xc000006d"
                  },
                  "system" : {
                    "eventID" : "X",
                    "keywords" : "0x8010000000000000",
                    "providerGuid" : "{X}",
                    "level" : "0",
                    "channel" : "Security",
                    "opcode" : "0",
                    "message" : "\"An account failed to log on.\r\n\r\nSubject:\r\n\tSecurity ID:\t\tS-1-0-0\r\n\tAccount Name:\t\t-\r\n\tAccount Domain:\t\t-\r\n\tLogon ID:\t\t0x0\r\n\r\nLogon Type:\t\
    t\t3\r\n\r\nAccount For Which Logon Failed:\r\n\tSecurity ID:\t\tS-1-0-0\r\n\tAccount Name:\t\ttestuser\r\n\tAccount Domain:\t\tWIN-JLGVA4CR4VI\r\n\r\nFailure Information:\r\n\tFailure Reason:\t\tUn
    known user name or bad password.\r\n\tStatus:\t\t\t0xC000006D\r\n\tSub Status:\t\t0xC0000064\r\n\r\nProcess Information:\r\n\tCaller Process ID:\t0x0\r\n\tCaller Process Name:\t-\r\n\r\nNetwork Info
    rmation:\r\n\tWorkstation Name:\tWIN-JLGVA4CR4VI\r\n\tSource Network Address:\tX.X.X.X\r\n\tSource Port:\t\t0\r\n\r\nDetailed Authentication Information:\r\n\tLogon Process:\t\tNtLmSsp \r\n\tAuthe
    ntication Package:\tNTLM\r\n\tTransited Services:\t-\r\n\tPackage Name (NTLM only):\t-\r\n\tKey Length:\t\t0\r\n\r\nThis event is generated when a logon request fails. It is generated on the compute
    r where access was attempted.\r\n\r\nThe Subject fields indicate the account on the local system which requested the logon. This is most commonly a service such as the Server service, or a local pro
    cess such as Winlogon.exe or Services.exe.\r\n\r\nThe Logon Type field indicates the kind of logon that was requested. The most common types are 2 (interactive) and 3 (network).\r\n\r\nThe Process I
    nformation fields indicate which account and process on the system requested the logon.\r\n\r\nThe Network Information fields indicate where a remote logon request originated. Workstation name is no
    t always available and may be left blank in some cases.\r\n\r\nThe authentication information fields provide detailed information about this specific logon request.\r\n\t- Transited services indicat
    e which intermediate services have participated in this logon request.\r\n\t- Package name indicates which sub-protocol was used among the NTLM protocols.\r\n\t- Key length indicates the length of t
    he generated session key. This will be 0 if no session key was requested.\"",
                    "version" : "0",
                    "systemTime" : "2022-04-29T13:01:07.679431700Z",
                    "eventRecordID" : "1449",
                    "threadID" : "4316",
                    "computer" : "WIN-JLGVA4CR4VI",
                    "task" : "12544",
                    "processID" : "612",
                    "severityValue" : "AUDIT_FAILURE",
                    "providerName" : "Microsoft-Windows-Security-Auditing"
                  }
                }
              },
              "rule" : {
                "mail" : false,
                "level" : 10,
                "pci_dss" : [
                  "10.2.4",
                  "10.2.5",
                  "11.4"
                ],
                "hipaa" : [
                  "164.312.b"
                ],
                "tsc" : [
                  "CC6.1",
                  "CC6.8",
                  "CC7.2",
                  "CC7.3"
                ],
                "description" : "Multiple Windows Logon Failures",
                "groups" : [
                  "windows",
                  "windows_security",
                  "authentication_failures"
                ],
                "nist_800_53" : [
                  "AU.14",
                  "AC.7",
                  "SI.4"
                ],
                "frequency" : 8,
                "gdpr" : [
                  "IV_35.7.d",
                  "IV_32.2"
                ],
                "firedtimes" : 1,
                "mitre" : {
                  "technique" : [
                    "Brute Force"
                  ],
                  "id" : [
                    "T1110"
                  ],
                  "tactic" : [
                    "Credential Access"
                  ]
                },
                "id" : "60204"
              },
              "decoder" : {
                "name" : "windows_eventchannel"
              },
              "input" : {
                "type" : "log"
              },
              "@timestamp" : "2022-04-29T13:01:06.742Z",
              "location" : "EventChannel",
              "id" : "1651237266.306309",
              "timestamp" : "2022-04-29T13:01:06.742+0000"
            }
          }
        ]
      }
    }
    
    ```
    
    </details>
