### ISSUE TITLE
E2E Research: Monitoring Docker

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh-qa#2839]
## Description

This issue aims to test manually the `docker-listener` wodle to define the requirements to develop an automated E2E test.

To achieve this we will follow these guides:
1. https://documentation-dev.wazuh.com/4.3-rc/proof-of-concept-guide/monitoring-docker.html
2. https://documentation-dev.wazuh.com/4.3-rc/container-security/docker-monitor/index.html#docker-monitor-index

## Tasks

- [x] (**[T1](https://github.com/wazuh/wazuh-qa/issues/2839#issuecomment-1113873692)**) Configure the docker-listener wodle and generate alerts
- [x] (**[T2](https://github.com/wazuh/wazuh-qa/issues/2839#issuecomment-1115473694)**) Get the alerts through the API
- [x] (**[T3](https://github.com/wazuh/wazuh-qa/issues/2839#issuecomment-1116702098)**) Configure the wodle in an agent and check if the alerts are generated in the manager

## Conclusion 🟢 

The manual test and investigation were successfully completed and the following requirements were determined during the manual test and investigation:
| Requirements |
|---|
| 1 endpoint with Ubuntu 20.04 and wazuh manager installed. |
| 1 endpoint with CentOS 8 and wazuh agent installed (along with the wodle dependencies) |
| Opensearch queries to search for alerts (described in the las task of this issue) |
| List of docker commands and the expected fields in the JSON of the alert in YAML format |

**Comment by mauromalara** [comment]
## Task 1: 🔵 Configure the docker-listener wodle and generate alerts

1. I create a VM with Ubuntu 20.04
2. I installed Docker
3. I installed the dependencies (https://documentation-dev.wazuh.com/4.3-rc/container-security/docker-monitor/dependencies.html)
4. I configure the docker-listener module
```
    <wodle name="docker-listener">
        <interval>10m</interval>
        <attempts>5</attempts>
        <run_on_start>yes</run_on_start>
        <disabled>no</disabled>
    </wodle>
```
6. I run some docker commands:
```
docker stop `docker ps -a -q` && docker rm `docker ps -a -q`
docker pull nginx
docker run -d -P --name nginx_container nginx
docker exec -ti nginx_container cat /etc/passwd
docker exec -ti nginx_container /bin/bash
exit
docker stop nginx_container
docker rm nginx_container
```

**Comment by mauromalara** [comment]
## Task 2: 🟢 

**Conclusion:**
It is possible to get the alerts in JSON format through the opensearch API by using, for example, Python or cURL.
Doing this we'll be able to check if the `docker-listener` wodle works as expected.

***

I researched how to send queries to the OpenSearch REST API and I found [this section](https://opensearch.org/docs/latest/opensearch/rest-api/search/) in the docs, and [this section too](https://opensearch.org/docs/latest/opensearch/query-dsl/full-text/). Then, I was able to search for data using the API as follows:

```
curl --insecure -XGET -u 'USER:PASS' "https://localhost:9200/wazuh-alerts-4.x-*/_search?pretty" -H 'Content-Type: application/json' -d '
{
  "query": {
    "term": {
      "rule.groups": "docker"
    }
  }
}
'
```

<details>
<summary>Alert obtained (example)</summary>

```
{
   "_index":"wazuh-alerts-4.x-2022.05.02",
   "_type":"_doc",
   "_id":"YgqihoABqKBUIO5u5SzG",
   "_score":1.522236,
   "_source":{
      "agent":{
         "name":"manager-4-3-0-ubuntu",
         "id":"000"
      },
      "manager":{
         "name":"manager-4-3-0-ubuntu"
      },
      "data":{
         "integration":"docker",
         "docker":{
            "Type":"container",
            "Action":"start",
            "Actor":{
               "Attributes":{
                  "image":"nginx",
                  "name":"nginx_container",
                  "maintainer":"NGINX Docker Maintainers <docker-maint@nginx.com>"
               },
               "ID":"0fb69bdbade658cc095abc6ffee6d683ed1e3bef36dc22533ee8644a8fcd7656"
            },
            "scope":"local",
            "from":"nginx",
            "timeNano":"1651526255979615744.000000",
            "id":"0fb69bdbade658cc095abc6ffee6d683ed1e3bef36dc22533ee8644a8fcd7656",
            "time":"1651526255",
            "status":"start"
         }
      },
      "rule":{
         "firedtimes":1,
         "mail":false,
         "level":3,
         "description":"Docker: Container nginx_container started",
         "groups":[
            "docker"
         ],
         "id":"87903"
      },
      "decoder":{
         "name":"json"
      },
      "input":{
         "type":"log"
      },
      "@timestamp":"2022-05-02T21:17:35.980Z",
      "location":"Wazuh-Docker",
      "id":"1651526255.21372",
      "timestamp":"2022-05-02T21:17:35.980+0000"
   }
}
```
</details>

**Comment by mauromalara** [comment]
# Task 3: Configure the wodle in an agent and check if the alerts are generated in the manager 🔵 

WIP.
