### ISSUE TITLE
Add test_scan_results cases for Ubuntu 22

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#2840]
| Related problem |
| --- |
| https://github.com/wazuh/wazuh-qa/issues/2836 |

### Description

As part of [Integration tests for Vulnerability Detector: Ubuntu 22 support](https://github.com/wazuh/wazuh-qa/issues/2836), it is necessary to add cases in the test_scan_results suite related to Ubuntu 22 support for the Wazuh Vulnerability Detector module.

**Suite test_scan_results**

- `Test scan provider and NVD vulnerabilities`: Test that vulnerable packages are reported using the OVAL and NVD feed.
- `Test scan provider vulnerabilities`: Test that vulnerable packages are reported using the OVAL feed (NVD contains different vulnerabilities).
- `Test scan vulnerability removal`: Check that it generates vulnerability alert fixed after removing or updating a vulnerable package.

### To Do 

- [x] Add new custom OVAL feed offered by Canonical – [OVAL Ubuntu Jammy](https://security-metadata.canonical.com/oval/com.ubuntu.jammy.cve.oval.xml.bz2)
- [x] Add scan provider vulnerabilities tests.
- [ ] Add scan provider and NVD vulnerabilities tests
- [ ] Add scan vulnerability removal tests.
- [x] Add Ubuntu 22OS to the test documentation

**Comment by CamiRomero** [comment]
## Task 1 - Add new custom OVAL feed offered by Canonical 

Create files in branch: `2840-test-scan-results-ubuntu-22`

- tests/integration/test_vulnerability_detector/data/feeds/ubuntu22/custom_ubuntu22_oval_feed.xml

**Comment by CamiRomero** [comment]
## Task 2 -  Add scan provider vulnerabilities tests.

**Comment by CamiRomero** [comment]
## Task 3 - 

- Add configuration for JAMMY in `tests/integration/test_vulnerability_detector/test_scan_results/data/configuration_template/configuration_scan_provider_and_nvd_vulnerabilities.yaml`
- Add test cases for JAMMY in `tests/integration/test_vulnerability_detector/test_scan_results/data/test_cases/cases_scan_provider_and_nvd_vulnerabilities.yaml`
- Add skip for the same reason as explained in task 2

**Comment by CamiRomero** [comment]
## Task 4 - Add scan vulnerability removal tests.

This test will be modified when the OVAL does have any vulnerability.

**Comment by CamiRomero** [comment]
Task 5 - Add Ubuntu 22 OS to the test documentation

- Add Ubuntu 22 in:
> tests/integration/test_vulnerability_detector/test_scan_results/test_scan_provider_and_nvd_vulnerabilities.py
> tests/integration/test_vulnerability_detector/test_scan_results/test_scan_provider_vulnerabilities.py
