### ISSUE TITLE
Add test_providers cases for Ubuntu 22

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#2841]
| Related problem |
| --- |
| https://github.com/wazuh/wazuh-qa/issues/2836 |

### Description

As part of [Integration tests for Vulnerability Detector: Ubuntu 22 support](https://github.com/wazuh/wazuh-qa/issues/2836), it is necessary to add cases in the test_providers suite related to Ubuntu 22 support for the Wazuh Vulnerability Detector module.

**Suite test_providers**

- `Test enabled/disabled`: Check that the provider's feeds start downloading when activated.
- `Test missing os`: Test the behavior when the <os> tag is omitted. Check failure if the tag is required, and in case it is not, it starts downloading the feeds as normal
- `Test OS`: Test that it starts downloading the feeds of the specified OS.
- `Test update from year`: Test if the feed is updated from a specific date. If the option does not apply, check warning warning.
- `Test update interval`: Test that the feed is updated at the specified interval

### To Do 

- [x] Add enabled/disabled tests
- [x] Add  missing os tests.
- [x] Add OS tests.
- [x] Add update from year tests.
- [x] Add update interval tests.
- [x] Add Ubuntu 22 OS to the test documentation (Add on each Tests)

**Comment by damarisg** [comment]
### Task 1 - Add enabled/disabled tests

Working on branch: `2841-test-providers-ubuntu22`.

- Add case for Ubuntu Jammy on `test_vulnerability_detector/test_providers/data/test_cases/cases_disabled.yaml` file.
- Add cases for Ubuntu Jammy on `test_vulnerability_detector/test_providers/data/test_cases/cases_enabled.yaml` file.
<details>
<summary>Test Executions</summary>

  ![imagen](https://user-images.githubusercontent.com/3978434/166676688-b6cb4410-f16a-45ae-9828-3dd87459f8d7.png)
</details>

**Comment by damarisg** [comment]
### Task 2 - Add missing os tests.

- It was only necessary to add the coverage in the documentation because the test covered this case.

<details>
<summary>Test Executions</summary>

  ![imagen](https://user-images.githubusercontent.com/3978434/166683830-6a630c31-d1a2-41e4-89df-788f6bcb68f2.png)
</details>

**Comment by damarisg** [comment]
### Task 3: Add OS tests

- Add case for Ubuntu Jammy on `test_vulnerability_detector/test_providers/data/test_cases/cases_os.yaml` file.
- Update documentation with new coverage.

<details>
<summary>Test Executions</summary>

  ![imagen](https://user-images.githubusercontent.com/3978434/166688632-107d6839-c9b4-4099-ae6e-c775864e1741.png)
</details>

**Comment by damarisg** [comment]
### Task 5 - Add update interval  tests.

- Add the coverage in the documentation.
- Add cases Ubuntu Xenial, Ubuntu  Boinic, Ubuntu Trusty and Ubuntu Jammy on` test_vulnerability_detector/test_providers/data/test_cases/cases_update_interval.yaml` file.

<details>
<summary>Test Executions</summary>

  ![imagen](https://user-images.githubusercontent.com/3978434/166741797-fc092f78-3845-4626-8a73-09245a2efc6f.png)
</details>

**Comment by damarisg** [comment]
It was merged to `2836-support-for-ubuntu22-vdt` branch.
