### ISSUE TITLE
Add test_feeds cases for Ubuntu 22 (1/2)

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#2842]
| Related problem |
| --- |
| https://github.com/wazuh/wazuh-qa/issues/2836 |

### Description

As part of [Integration tests for Vulnerability Detector: Ubuntu 22 support](https://github.com/wazuh/wazuh-qa/issues/2836), it is necessary to add cases in the test_feeds suite related to Ubuntu 22 support for the Wazuh Vulnerability Detector module.

**Suite test_feeds**

- `Test download feeds`: Prove that it is downloaded, and that the update date is recent.
- `Test duplicate feeds`: Test that after downloading the feed again, the vulnerabilities of the feeds are not duplicated
- `Test import invalid feed type`: Test behavior when an invalid feed URL is entered
- `Test validate feed content`: It downloads the feed files and checks that they are parseable (XML or JSON).

### To Do 

- [x] Add download feeds tests
- [x] Add duplicate feeds tests.
- [x] Add import invalid feed type tests.
- [x] Add validate feed content tests.
- [x] Add Ubuntu 22 OS to the test documentation

**Comment by Deblintrake09** [comment]
# Task 1 - Add download feed tests

Added test case for Ubuntu Jammy
![Captura de pantalla de 2022-05-05 12-00-50](https://user-images.githubusercontent.com/14501079/166956899-804e34eb-9d10-40e9-ba75-4b5b230b4541.png)

**Comment by Deblintrake09** [comment]
# Task 2 - Add duplicate feed tests

Added test cases for Ubuntu Trusty, Xenial, Focal and Jammy.
![Captura de pantalla de 2022-05-05 12-15-43](https://user-images.githubusercontent.com/14501079/166957130-34cb60b1-68ba-431e-b27f-7bc9da434a67.png)

**Comment by Deblintrake09** [comment]
# Task 3 - Add import invalid feed type tests

Did not add additional case for canonical, since test is not related to os provider, but makes sure that when downloading an invalid type of file, no data is added.

**Comment by damarisg** [comment]
Closed. This issue continues in the next sprint https://github.com/wazuh/wazuh-qa/issues/2897
