### ISSUE TITLE
Add test_scan_results cases for Amazon Linux 2022

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#2843]
| Related problem |
| --- |
| https://github.com/wazuh/wazuh-qa/issues/2813 |

### Description

As part of [Integration tests for Vulnerability Detector: Amazon Linux 2022 support](https://github.com/wazuh/wazuh-qa/issues/2813), it is necessary to add cases in the test_scan_results suite related to Amazon Linux 2022 support for the Wazuh Vulnerability Detector module.

**Suite test_scan_results**

- `Test scan provider and NVD vulnerabilities`: Test that vulnerable packages are reported using the OVAL and NVD feed.
- `Test scan provider vulnerabilities`: Test that vulnerable packages are reported using the OVAL feed (NVD contains different vulnerabilities).
- `Test scan vulnerability removal`: Check that it generates vulnerability alert fixed after removing or updating a vulnerable package.

### To Do 

- [x] Add new custom ALAS 2022  feed.
- [x] Add scan provider vulnerabilities tests.
- [x] Add scan provider and NVD vulnerabilities tests
- [x] Add scan vulnerability removal tests.
- [x] Add Amazon Linux 2022 OS to the test documentation

**Comment by CamiRomero** [comment]
## Task 1 - Add new custom ALAS 2022 feed
Add custom feed for ALAS 2022 in `tests/integration/test_vulnerability_detector/data/feeds/alas/custom_alas2022_feed.json`

Branch: `2843-add-test-scan-results-amazon-linux-2022`

**Comment by CamiRomero** [comment]
## Task 2 - Add scan provider vulnerabilities tests.

Add ALAS2022 to system data for mocking: 
> 'ALAS2022': {'hostname': 'alas2022', 'architecture': 'x86_64', 'os_name': 'Amazon Linux', 'os_version': '2022',
              'os_codename': '', 'os_major': '2022', 'os_minor': '', 'os_patch': '', 'os_build': '', 'os_platform': 'amzn',
              'sysname': 'Linux', 'release': '5.15.29-16.111.amzn2022.x86_64'},

Edit ALAS configuration in `tests/integration/test_vulnerability_detector/test_scan_results/data/configuration_template/configuration_scan_provider_vulnerabilities.yaml`

Edit ALAS test cases in `tests/integration/test_vulnerability_detector/test_scan_results/data/test_cases/cases_scan_provider_vulnerabilities.yaml`

**Comment by CamiRomero** [comment]
## Task 4 - Add scan vulnerability removal tests.

Edit configuration, test cases, and python test to support more than one OS.

Add ALAS test: In progress.

**Comment by CamiRomero** [comment]
## Task 5 - Add Amazon Linux 2022 OS to the test documentation

Add `Amazon Linux 2022` in:

- tests/integration/test_vulnerability_detector/test_scan_results/test_scan_provider_and_nvd_vulnerabilities.py
- tests/integration/test_vulnerability_detector/test_scan_results/test_scan_provider_vulnerabilities.py
- tests/integration/test_vulnerability_detector/test_scan_results/test_scan_vulnerability_removal.py

**Comment by damarisg** [comment]
Note: Merged into `2813-support-for-amazon-linux-2022-vdt` branch.
