### ISSUE TITLE
Add test_providers cases for Amazon Linux 2022 (1/2)

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#2844]
| Related problem |
| --- |
| https://github.com/wazuh/wazuh-qa/issues/2813 |

### Description

As part of [Integration tests for Vulnerability Detector: Amazon Linux 2022 support](https://github.com/wazuh/wazuh-qa/issues/2813), it is necessary to add cases in the test_providers suite related to Amazon Linux 2022 support for the Wazuh Vulnerability Detector module.

**Suite test_providers**

- `Test enabled/disabled`: Check that the provider's feeds start downloading when activated.
- `Test missing os`: Test the behavior when the <os> tag is omitted. Check failure if the tag is required, and in case it is not, it starts downloading the feeds as normal
- `Test OS`: Test that it starts downloading the feeds of the specified OS.
- `Test update from year`: Test if the feed is updated from a specific date. If the option does not apply, check warning warning.
- `Test update interval`: Test that the feed is updated at the specified interval

### To Do 

- [x] Add enabled/disabled tests
- [x] Add  missing os tests.
- [x] Add OS tests.
- [x] Add update from year tests.
- [x] Add update interval tests.
- [x] Add Amazon Linux 2022 OS to the test documentation

**Comment by Deblintrake09** [comment]
# Task 1 - Add enabled/disabled tests

- Added new test cases for test_enabled/disabled.

## Note: The development has not been tested. Will be tested when we can generate packages for this ongoing development.

**Comment by Deblintrake09** [comment]
# Task 2 - Add test_os tests

- Added new test cases for Amazon Linux 2022 for test_os.

### Note: The development has not been tested. Will be tested when we can generate packages for this ongoing development.

**Comment by Deblintrake09** [comment]
# Task 5 - Add test_update_interval tests

- Added new test cases for Amazon Linux 2022 and Amazon Linux 2 for test_update_interval.

### Note: The development has not been tested. Will be tested when we can generate packages for this ongoing development.

**Comment by Deblintrake09** [comment]
# Task 5 - Add test_update_interval tests

- Added new test cases for Amazon Linux 2022 and Amazon Linux 2 for test_update_interval.

### Note: The development has not been tested. Will be tested when we can generate packages for this ongoing development.

**Comment by Deblintrake09** [comment]
# Task 5 - Add test_update_interval tests

- Added new test cases for Amazon Linux 2022 and Amazon Linux 2 for test_update_interval.

### Note: The development has not been tested. Will be tested when we can generate packages for this ongoing development.

**Comment by damarisg** [comment]
Closed. This issue continues in the next sprint https://github.com/wazuh/wazuh-qa/issues/2900
