### ISSUE TITLE
Add test_feeds cases for Amazon Linux 2022 (1/2)

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#2845]
| Related problem |
| --- |
| https://github.com/wazuh/wazuh-qa/issues/2813 |

### Description

As part of [Integration tests for Vulnerability Detector: Amazon Linux 2022 support](https://github.com/wazuh/wazuh-qa/issues/2813), it is necessary to add cases in the test_feeds suite related to Amazon Linux 2022 support for the Wazuh Vulnerability Detector module.

**Suite test_feeds**

- `Test download feeds`: Prove that it is downloaded, and that the update date is recent.
- `Test duplicate feeds`: Test that after downloading the feed again, the vulnerabilities of the feeds are not duplicated
- `Test import invalid feed type`: Test behavior when an invalid feed URL is entered
- `Test validate feed content`: It downloads the feed files and checks that they are parseable (XML or JSON).

### To Do 

- [x] Add download feeds tests
- [x] Add duplicate feeds tests.
- [x] Add import invalid feed type tests.
- [x] Add validate feed content tests.
- [x] Add Amazon Linux 2022 OS to the test documentation

**Comment by CamiRomero** [comment]
## Task 1 - Add download feeds tests

Add case in `tests/integration/test_vulnerability_detector/test_feeds/data/test_cases/cases_download_feeds.yaml`

Branch: `2845-test-feeds-for-amazon-linux-2022`

**Comment by CamiRomero** [comment]
## Task 2 - Add duplicate feeds tests.

This test is already covered by cases `ALAS` in `tests/integration/test_vulnerability_detector/test_feeds/data/test_cases/cases_duplicate_feeds.yaml`

**Comment by CamiRomero** [comment]
## Task 3 - Add import invalid feed type tests.

This test is already covery by case `ALAS - DOC` in `tests/integration/test_vulnerability_detector/test_feeds/data/test_cases/cases_import_invalid_feed_type.yaml`

**Comment by CamiRomero** [comment]
## Task 4 - Add validate feed content tests.

It is not possible to add a case for `Amazon-Linux-2022` because  there is no URL that contains the oval in `xml` format

**Comment by CamiRomero** [comment]
This Issue is blocked until [2813](https://github.com/wazuh/wazuh-qa/issues/2813) is ready

**Comment by damarisg** [comment]
Closed. This issue continues in the next sprint https://github.com/wazuh/wazuh-qa/issues/2901
