### ISSUE TITLE
E2E Research: Virustotal

### ISSUE THREAD

**Issue by BelenValdivia** [wazuh/wazuh-qa#2846]
## Description
This issue aims to test manually the Virus total integration to define the requirements to develop an automated test.

We follow these guides:

- https://documentation.wazuh.com/current/user-manual/capabilities/active-response/ar-use-cases/removing-malware.html?highlight=virus%20total

- https://documentation.wazuh.com/current/user-manual/capabilities/virustotal-scan/integration.html#virustotal-integration-alerts
- https://documentation.wazuh.com/current/user-manual/manager/manual-integration.html#manual-integration
- https://documentation.wazuh.com/current/user-manual/capabilities/virustotal-scan/about.html

## Tasks
- [x] ([T1](https://github.com/wazuh/wazuh-qa/issues/2846#issuecomment-1115039690)) Create virus total account.
- [x] ([T2](https://github.com/wazuh/wazuh-qa/issues/2846#issuecomment-1115051045)) Use case - Scanning a file - Linux
- [x] [(T3](https://github.com/wazuh/wazuh-qa/issues/2846#issuecomment-1115100620)) Use case - Detecting and removing malware - Virus Total integration
- [x] ([T4](https://github.com/wazuh/wazuh-qa/issues/2846#issuecomment-1115323854)) Use case- Scanning file - Windows
- [x] ([T5](https://github.com/wazuh/wazuh-qa/issues/2846#issuecomment-1116421304)) Get the alerts through the API 

## Conclusion 🟢 
The different use cases tested were successful. I configured a manager, filebeat, kibana and elastic in the same machine (Centos 8). I configured two agents Linux(Centos 8) and Windows(Windows Server 2019).
Virus total public API has a limitation:  no more than four requests per minute

**Comment by BelenValdivia** [comment]
##Task 2 - Test use case - Scanning a file

<details>
<summary> 1. Configuration in ossec.conf</summary>

  ```
  <ossec_config>
      <syscheck>
      ...
        <directories check_all="yes" realtime="yes">/test</directories>
      ...
      </syscheck>
  
     <integration>
        <name>virustotal</name>
        <api_key>API KEY</api_key>
        <group>syscheck</group>
        <alert_format>json</alert_format>
      </integration>
  
  </ossec_config>
  ```

</details>

<details>
<summary> 2. Check alerts. Alerts.log</summary>
** Alert 1651502580.18449: - ossec,syscheck,syscheck_entry_added,syscheck_file,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,tsc_PI1.4,tsc_PI1.5,tsc_CC6.
1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,
2022 May 02 14:43:00 centos-manager-kibana->syscheck
Rule: 554 (level 5) -> 'File added to the system.'
File '/test/virus_total.exe' added
Mode: realtime

Attributes:
 - Size: 7
 - Permissions: rw-r--r--
 - Date: Mon May  2 14:43:00 2022
 - Inode: 25836478
 - User: root (0)
 - Group: root (0)
 - MD5: xxxxxxx
 - SHA1: yyyyyyy
 - SHA256: xxxxxxx

** Alert 1651502582.19142: - virustotal,
2022 May 02 14:43:02 centos-manager-kibana->virustotal
Rule: 87103 (level 3) -> 'VirusTotal: Alert - No records in VirusTotal database'
{"virustotal": {"found": 0, "malicious": 0, "source": {"alert_id": "xxxxxxx", "file": "/test/virus_total.exe", "md5": "xxxxxxx", "sha1": "yyyyyyy"}}, "integration": "virustotal"}
virustotal.found: 0
virustotal.malicious: 0
virustotal.source.alert_id: 1651502580.18449
virustotal.source.file: /test/virus_total.exe
virustotal.source.md5: xxxxxxx
virustotal.source.sha1: yyyyyyy
integration: virustotal
</details>

3. Check alerts in kibana
![image](https://user-images.githubusercontent.com/26927338/166263143-15992933-cdec-4c54-8b97-dc7e828c2caf.png)

![vt alert kibana](https://user-images.githubusercontent.com/26927338/166263844-6a687259-3b92-487b-96e6-7ab528ccce32.png)

**Comment by BelenValdivia** [comment]
## Task 3 - Detecting and removing malware - Virus Total integration - IN PROGRESS

1. Confingure VT integracion in /var/ossec/etc/ossec.conf
2. Create custom rules in  /var/ossec/etc/rules/local_rules.xml
3. Configure Active Response to remove malicious files - Configure Wazuh manager (in progress)
4. Configure Active Response to remove malicious files - Configure Wazuh agent (in progress)

**Comment by BelenValdivia** [comment]
## Task 4 - Test use case - Scanning a file - Windows

1. Configure ossec.conf agent.
      <details>
      <summary>ossec.conf</summary>
      
       ```
        <ossec_config>
            <syscheck>
            ...
              <directories check_all="yes" realtime="yes">C:\wazuh</directories>
            ...
            </syscheck>
        
        </ossec_config>
       ```
      
      </details>

2. Configure ossec.conf manager.
    <details>
    <summary>ossec.conf</summary>
    
    ```
     <ossec_config>
           <integration>
                  <name>virustotal</name>
                  <api_key>API KEY</api_key>
                  <group>syscheck</group>
                  <alert_format>json</alert_format>
                </integration>
     </ossec_config>
    ```
    
    </details>

3. Check alerts.
    <details>
    <summary>alerts.log</summary>
    ** Alert 1651522083.145387: - ossec,syscheck,syscheck_entry_modified,syscheck_registry,pci_dss_11.5,gpg13_4.13,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,tsc_PI1.4,tsc_PI1.5,
    tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,
    2022 May 02 20:08:03 (WIN-JLGVA4CR4VI) any->syscheck
    Rule: 750 (level 5) -> 'Registry Value Integrity Checksum Changed'
    Registry Value '[x32] HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\W32Time\Config\LastKnownGoodTime' modified
    Mode: scheduled
    Changed attributes: md5,sha1,sha256
    Old md5sum was: 'da94069f9c657316c45fb543f5fa4130'
    New md5sum is : '8c5a6f9c4dd010479ed196bab51bcbd7'
    Old sha1sum was: '140543aef2a5145f0d7d5781237449a02b3e6bd1'
    New sha1sum is : 'f713787869cabc766971580fb6da16e1b90e0aaf'
    Old sha256sum was: '17cca53efdf33c09ceb705d525792d28d3577d458e5aec984d379ce12173be72'
    New sha256sum is : 'd1784e8a62f793b9271c23cced0d5f4214f929a4b1f0c865d556c14cc72667d5'
    
    Attributes:
     - Size: 8
     - MD5: 8c5a6f9c4dd010479ed196bab51bcbd7
     - SHA1: f713787869cabc766971580fb6da16e1b90e0aaf
     - SHA256: d1784e8a62f793b9271c23cced0d5f4214f929a4b1f0c865d556c14cc72667d5
    
    ** Alert 1651522087.146502: - virustotal,
    2022 May 02 20:08:07 (WIN-JLGVA4CR4VI) 10.0.2.15->virustotal
    Rule: 87103 (level 3) -> 'VirusTotal: Alert - No records in VirusTotal database'
    {"virustotal": {"found": 0, "malicious": 0, "source": {"alert_id": "1651522083.145387", "file": "HKEY_LOCAL_MACHINE\\System\\CurrentControlSet\\Services\\W32Time\\Config", "md5": "8c5a6f9c4dd010479e
    d196bab51bcbd7", "sha1": "f713787869cabc766971580fb6da16e1b90e0aaf"}}, "integration": "virustotal"}
    virustotal.found: 0
    virustotal.malicious: 0
    virustotal.source.alert_id: 1651522083.145387
    virustotal.source.file: HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\W32Time\Config
    virustotal.source.md5: 8c5a6f9c4dd010479ed196bab51bcbd7
    virustotal.source.sha1: f713787869cabc766971580fb6da16e1b90e0aaf
    integration: virustotal
    
    </details>

**Comment by BelenValdivia** [comment]
## Task 5 - Get the alerts through the API

1. Request
```
curl --insecure -XGET -u 'USER:PASS' "https://localhost:9200/wazuh-alerts-4.x-*/_search?pretty" -H 'Content-Type: application/json' -d '
{
  "query": {
    "term": {
      "rule.groups": "virustotal"
    }
  }
}
'
```

2. Alerts
    <details>
    <summary>alerts windows scanning file</summary>
    
    ```
    {
    "_index": "wazuh-alerts-4.x-2022.05.02",
    "_type": "_doc",
    "_id": "xxxxx",
    "_score": 3.5427325,
    "_source": {
	    "agent": {
		    "ip": "xx.xx.xx.xx",
		    "name": "WIN-JLGVA4CR4VI",
		    "id": "002"
	    },
	    "manager": {
		    "name": "centos-manager-kibana"
	    },
	    "data": {
		    "integration": "virustotal",
		    "virustotal": {
			    "malicious": "0",
			    "found": "0",
			    "source": {
				    "sha1": "YYYYYYYYY",
				    "file": "HKEY_LOCAL_MACHINE\\System\\CurrentControlSet\\Services\\bam\\State\\UserSettings\\XX",
				    "alert_id": "XXX",
				    "md5": "ZZZZZZZZ"
			    }
		    }
	    },
	    "rule": {
		    "firedtimes": 5,
		    "mail": false,
		    "level": 3,
		    "description": "VirusTotal: Alert - No records in VirusTotal database",
		    "groups": [
			    "virustotal"
		    ],
		    "id": "87103"
	    },
	    "decoder": {
		    "name": "json"
	    },
	    "input": {
		    "type": "log"
	    },
	    "@timestamp": "2022-05-02T20:06:03.097Z",
	    "location": "virustotal",
	    "id": "XXXXXXX",
	    "timestamp": "2022-05-02T20:06:03.097+0000"
    }
    }
    ```
    
    <details>
