### ISSUE TITLE
E2E Research: Netcat

### ISSUE THREAD

**Issue by BelenValdivia** [wazuh/wazuh-qa#2848]
This issue aims to test manually the Netcat to define the requirements to develop an automated test.

We follow these guides:
https://documentation.wazuh.com/current/proof-of-concept-guide/detect-unauthorized-processes-netcat.html?highlight=netcat
https://www.youtube.com/watch?v=Cx2rIpGA3V8

## Tasks
- [x] ([T1](https://github.com/wazuh/wazuh-qa/issues/2848#issuecomment-1116037624)) Configure agent
- [x] ([T2](https://github.com/wazuh/wazuh-qa/issues/2848#issuecomment-1116110276)) Configure manager
- [x] ([T3](https://github.com/wazuh/wazuh-qa/issues/2848#issuecomment-1116136076)) Generate the alert
- [x] ([T4](https://github.com/wazuh/wazuh-qa/issues/2848#issuecomment-1116362033)) Get the alert through the API

## Conclusion 🟢 
Using a manager (OS: Centos 8) and a linux agent (OS: Centos 8) I could test how Wazuh is capable of detecting if Netcat is running on a monitored host.

**Comment by BelenValdivia** [comment]
## Task 1 - Configure agent

1. Configure ossec.conf in the manager to periodically get a list of running processes.
    <details>
    <summary>ossec.conf</summary>
    
      ```
    <ossec_config>
          <localfile>
              <log_format>full_command</log_format>
              <alias>process list</alias>
              <command>ps -e -o pid,uname,command</command>
              <frequency>30</frequency>
          </localfile>
      </ossec_config>
    ```
    
    </details>

2. Restart Wazuh agent to load the changes: `systemctl restart wazuh-agent`
3. Install Netcat and required dependencies: `yum install nmap-ncat`

**Comment by BelenValdivia** [comment]
## Task 2 - Configure manager

1. Add local rules in /var/ossec/etc/rules/local_rules.xml
    <details>
    <summary>local_rules.xml</summary>
    
    ```
    <group name="ossec,">
        <rule id="100050" level="0">
            <if_sid>530</if_sid>
            <match>^ossec: output: 'process list'</match>
            <description>List of running processes.</description>
            <group>process_monitor,</group>
        </rule>
        <rule id="100051" level="7" ignore="900">
            <if_sid>100050</if_sid>
            <match>nc -l</match>
            <description>Netcat listening for incoming connections.</description>
            <group>process_monitor,</group>
        </rule>
    </group>
    ```
    
    </details>

**Comment by BelenValdivia** [comment]
## Task 4 - Get the alert through the API

1. Request
```
curl --insecure -XGET -u 'wazuh:pGT86aDkSLdGeUTB22LtzltWxpfua6D4' "https://172.17.1.18:9200/wazuh-alerts-4.x-*/_search?pretty" -H 'Content-Type: application/json' -d '
{
  "query": {
    "term": {
      "rule.id": "100051"
    }
  }
}
'
```

2. Alert obtained
    <details>
    <summary>alert</summary>
    
    ```
    {
	    "took": 6,
	    "timed_out": false,
	    "_shards": {
		    "total": 18,
		    "successful": 18,
		    "skipped": 0,
		    "failed": 0
	    },
	    "hits": {
		    "total": {
			    "value": 2,
			    "relation": "eq"
		    },
		    "max_score": 4.199705,
		    "hits": [{
				    "_index": "wazuh-alerts-4.x-2022.05.02",
				    "_type": "_doc",
				    "_id": "ay1_hoABJm5Op0-wpb4X",
				    "_score": 4.199705,
				    "_source": {
					    "agent": {
						    "ip": "10.0.2.15",
						    "name": "centos-agent",
						    "id": "001"
					    },
					    "manager": {
						    "name": "centos-manager-kibana"
					    },
					    "rule": {
						    "firedtimes": 1,
						    "mail": false,
						    "level": 7,
						    "description": "Netcat listening for incoming connections.",
						    "groups": [
							    "ossec",
							    "process_monitor"
						    ],
						    "id": "100051"
					    },
					    "decoder": {
						    "name": "ossec"
					    },
					    "full_log": "ossec: output: 'process list':\n    PID USER     COMMAND\n      1 root     /usr/lib/systemd/systemd --switched-root --system --deserialize 17\n      2 root     [kthreadd]\n
					    3 root[rcu_gp]\ n 4 root[rcu_par_gp]\ n 6 root[kworker / 0: 0 H - events_highpri]\ n 9 root[mm_percpu_wq]\ n 10 root[ksoftirqd / 0]\ n 11 root[rcu_sched]\
					    n 12 root[migration / 0]\ n 13 root[watchdog / 0]\ n 14 root[cpuhp / 0]\ n 15 root[cpuhp / 1]\ n 16 root[watchdog / 1]\ n 17 root[migration / 1]\ n 18 root[ksoftirqd / 1]\ n 20 root[kworker / 1: 0 H - events_highpri]\ n 22 root[kworker / u4: 1 - flush - 8: 0]\ n 23 root[kdevtmpfs]\ n 24 root[netns]\ n 25 root[kauditd]\ n 2
					    6 root[khungtaskd]\ n 27 root[oom_reaper]\ n 28 root[writeback]\ n 29 root[kcompactd0]\ n 30 root[ksmd]\ n 31 root[khugepaged]\ n 32 root[crypto]\ n 33 root[kintegrityd]\ n 34 root[kblockd]\ n 35 root[blkcg_punt_bio]\ n 36 root[tpm_dev_wq]\ n 37 root[md]\ n 38 root[edac - poller]\ n 39 root[watchdogd]\ n 41 root[kworker / 0: 1 H - kblockd]\ n 56 root[kswapd0]\ n 149 root[kthrotld]\ n 150 root[acpi_thermal_pm]\ n 151 root[kmpath_rdacd]\ n 152 root[kaluad]\ n 154 root[ipv6_addrconf]\ n 155 root[kstrp]\ n 267 root[kworker / 1: 1 H - kblockd]\ n 395 root[iprt - VBoxWQueue]\ n 398 root[ata_sff]\ n 399 root[scsi _eh_0]\ n 400 root[scsi_tmf_0]\ n 401 root[scsi_eh_1]\ n 402 root[scsi_tmf_1]\ n 420 root[ttm_swap]\ n 439 root[xfsalloc]\ n 440 root[xfs_mru_cache]\ n 44
					    1 root[xfs - buf / sda1]\ n 442 root[xfs - conv / sda1]\ n 443 root[xfs - cil / sda1]\ n 444 root[xfs - reclaim / sda]\ n 445 root[xfs - eofblocks / s]\ n 446 root[xfs - log / sda1]\
					    n 447 root[xfsaild / sda1]\ n 531 root / usr / lib / systemd / systemd - journald\ n 550 root[kworker / 1: 5 - events]\ n 566 root / usr / lib / systemd / systemd - udevd\ n 580 rpc / usr / bi
					    n / rpcbind - w - f\ n 615 root[rpciod]\ n 616 root[kworker / u5: 0]\ n 617 root[xprtiod]\ n 620 root / usr / sbin / sssd - i--logger = files\ n 621 root / usr / sbin / irqbalance--fo
					    reground\ n 624 polkitd / usr / lib / polkit - 1 / polkitd--no - debug\ n 632 dbus / usr / bin / dbus - daemon--system--address = systemd: --nofork--nopidfile--systemd - activation--syslog - only\ n 641 rn
					    gd / sbin / rngd - f--fill - watermark = 0\ n 701 root / usr / sbin / sshd - D - u0 - oCiphers = aes256 - gcm @openssh.com,
					    chacha20 - poly1305 @openssh.com,
					    aes256 - ctr,
					    aes256 - cbc,
					    aes128 - gcm @openssh.com,
					    aes128 - ctr,
					    aes128 - cbc - oMACs = hmac - sha2 - 256 - etm @openssh.com,
					    hmac - sha1 - etm @openssh.com,
					    umac - 128 - etm @openssh.com,
					    hmac - sha2 - 512 - etm @openssh.com,
					    hmac - sha2 - 256,
					    hmac - sha1,
					    umac - 128 @openssh.com,
					    hmac - sha2 - 512 - oGSSAPIK
					    exAlgorithms = gss - curve25519 - sha256 - ,
					    gss - nistp256 - sha256 - ,
					    gss - group14 - sha256 - ,
					    gss - group16 - sha512 - ,
					    gss - gex - sha1 - ,
					    gss - group14 - sha1 - -oKexAlgorithms = curve25519 - sha256,
					    curve25519 - sha256 @libssh.org,
					    ecdh - s
					    ha2 - nistp256,
					    ecdh - sha2 - nistp384,
					    ecdh - sha2 - nistp521,
					    diffie - hellman - group - exchange - sha256,
					    diffie - hellman - group14 - sha256,
					    diffie - hellman - group16 - sha512,
					    diffie - hellman - group18 - sha512,
					    diffie - hellman - group -
					    exchange - sha1,
					    diffie - hellman - group14 - sha1 - oHostKeyAlgorithms = ecdsa - sha2 - nistp256,
					    ecdsa - sha2 - nistp256 - cert - v01 @openssh.com,
					    ecdsa - sha2 - nistp384,
					    ecdsa - sha2 - nistp384 - cert - v01 @openssh.com,
					    ecdsa - sha2 - ni
					    stp521,
					    ecdsa - sha2 - nistp521 - cert - v01 @openssh.com,
					    ssh - ed25519,
					    ssh - ed25519 - cert - v01 @openssh.com,
					    rsa - sha2 - 256,
					    rsa - sha2 - 256 - cert - v01 @openssh.com,
					    rsa - sha2 - 512,
					    rsa - sha2 - 512 - cert - v01 @openssh.com,
					    ssh - rsa,
					    ssh -
					    rsa - cert - v01 @openssh.com - oPubkeyAcceptedKeyTypes = ecdsa - sha2 - nistp256,
					    ecdsa - sha2 - nistp256 - cert - v01 @openssh.com,
					    ecdsa - sha2 - nistp384,
					    ecdsa - sha2 - nistp384 - cert - v01 @openssh.com,
					    ecdsa - sha2 - nistp521,
					    ecdsa -
					    sha2 - nistp521 - cert - v01 @openssh.com,
					    ssh - ed25519,
					    ssh - ed25519 - cert - v01 @openssh.com,
					    rsa - sha2 - 256,
					    rsa - sha2 - 256 - cert - v01 @openssh.com,
					    rsa - sha2 - 512,
					    rsa - sha2 - 512 - cert - v01 @openssh.com,
					    ssh - rsa,
					    ssh - rsa - cert - v0
					    1 @openssh.com - oCASignatureAlgorithms = ecdsa - sha2 - nistp256,
					    ecdsa - sha2 - nistp384,
					    ecdsa - sha2 - nistp521,
					    ssh - ed25519,
					    rsa - sha2 - 256,
					    rsa - sha2 - 512,
					    ssh - rsa\ n 712 root / usr / sbin / gssproxy - D\ n 720 root /
					    usr / libexec / sssd / sssd_be--domain implicit_files--uid 0--gid 0--logger = files\ n 721 root / usr / libexec / sssd / sssd_nss--uid 0--gid 0--logger = files\ n 729 root / usr / sbin / rsyslogd -
					    n\ n 733 root / usr / lib / systemd / systemd - logind\ n 736 root / usr / sbin / crond - n\ n 737 root / sbin / agetty - o - p--\\u--noclear tty1 linux\ n 1676 root / usr / sbin / VBoxService--p
					    idfile /
					    var / run / vboxadd - service.sh\ n 1933 root / usr / sbin / NetworkManager--no - daemon\ n 2280 root sshd: vagrant[priv]\ n 2283 vagrant / usr / lib / systemd / systemd--user\ n 2286 vagrant(
							    sd - pam)\ n 2292 vagrant sshd: vagrant @pts / 0\ n 2293 vagrant - bash\ n 2435 root sudo su\ n 2436 root su\ n 2437 root bash\ n 49410 root / sbin / auditd\ n 49493 root[audit_pr une_tre]\ n 50592 root[kworker / 1: 2 - events]\ n 50743 root[kworker / u4: 0 - events_unbound]\ n 50753 root[kworker / 0: 1 - events]\ n 50826 root[kworker / 0: 3 - events]\ n 50852 root /
						    var / o
					    ssec / bin / wazuh - execd\ n 50861 ossec /
					    var / ossec / bin / wazuh - agentd\ n 50876 root /
					    var / ossec / bin / wazuh - syscheckd\ n 50889 root /
					    var / ossec / bin / wazuh - logcollector\ n 50897 root /
					    var / ossec / b in /wazuh-modulesd\n  51863 root     nc -l 8000\n  51864 root     ps -e -o pid,uname,command",
					    "input": {
						    "type": "log"
					    },
					    "@timestamp": "2022-05-02T20:39:11.546Z",
					    "location": "process list",
					    "id": "1651523951.368747",
					    "timestamp": "2022-05-02T20:39:11.546+0000"
				    }
			    },
			    {
				    "_index": "wazuh-alerts-4.x-2022.05.03",
				    "_type": "_doc",
				    "_id": "Cy23ioABJm5Op0-wzsFr",
				    "_score": 2.1594841,
				    "_source": {
					    "agent": {
						    "ip": "10.0.2.15",
						    "name": "centos-agent",
						    "id": "001"
					    },
					    "manager": {
						    "name": "centos-manager-kibana"
					    },
					    "rule": {
						    "firedtimes": 1,
						    "mail": false,
						    "level": 7,
						    "description": "Netcat listening for incoming connections.",
						    "groups": [
							    "ossec",
							    "process_monitor"
						    ],
						    "id": "100051"
					    },
					    "decoder": {
						    "name": "ossec"
					    },
					    "full_log": "ossec: output: 'process list':\n    PID USER     COMMAND\n      1 root     /usr/lib/systemd/systemd --switched-root --system --deseri
					    alize 17\ n 2 root[kthreadd]\ n 3 root[rcu_gp]\ n 4 root[rcu_par_gp]\ n 6 root[kworker / 0: 0 H - events_highpri]\ n 9 root[mm_percpu_wq]\ n 10 root[ksoftirqd / 0]\ n 11 root[rcu_sched]\ n 12 root[migration / 0]\ n 13 root[watchdog / 0]\ n 14 roo
					    t[cpuhp / 0]\ n 15 root[cpuhp / 1]\ n 16 root[watchdog / 1]\ n 17 root[migration / 1]\ n 18 root[ksoftirqd / 1]\ n 20 root[kworker / 1: 0 H - events_highpri]\ n 23 ro
					    ot[kdevtmpfs]\ n 24 root[netns]\ n 25 root[kauditd]\ n 26 root[khungtaskd]\ n 27 root[oom_reaper]\ n 28 root[writeback]\ n 29 root[kcompactd0]\ n
					    30 root[ksmd]\ n 31 root[khugepaged]\ n 32 root[crypto]\ n 33 root[kintegrityd]\ n 34 root[kblockd]\ n 35 root[blkcg_punt_bio]\ n 36 root[tpm _dev_wq]\ n 37 root[md]\ n 38 root[edac - poller]\ n 39 root[watchdogd]\ n 41 root[kworker / 0: 1 H - kblockd]\ n 56 root[kswapd0]\ n 149 root[kthrotld]\ n 1
					    50 root[acpi_thermal_pm]\ n 151 root[kmpath_rdacd]\ n 152 root[kaluad]\ n 154 root[ipv6_addrconf]\ n 155 root[kstrp]\ n 267 root[kworker / 1: 1 H - kblockd]\ n 39
					    5 root[iprt - VBoxWQueue]\ n 398 root[ata_sff]\ n 399 root[scsi_eh_0]\ n 400 root[scsi_tmf_0]\ n 401 root[scsi_eh_1]\ n 402 root[scsi_tmf_1]\ n 420 root[
						    ttm_swap]\ n 439 root[xfsalloc]\ n 440 root[xfs_mru_cache]\ n 441 root[xfs - buf / sda1]\ n 442 root[xfs - conv / sda1]\ n 443 root[xfs - cil / sda1]\ n 444 root[xfs - re claim / sda]\ n 445 root[xfs - eofblocks / s]\ n 446 root[xfs - log / sda1]\ n 447 root[xfsaild / sda1]\ n 531 root / usr / lib / systemd / systemd - journald\ n 566 root / usr / lib / system
					    d / systemd - udevd\ n 580 rpc / usr / bin / rpcbind - w - f\ n 615 root[rpciod]\ n 616 root[kworker / u5: 0]\ n 617 root[xprtiod]\ n 620 root / usr / sbin / sssd - i--logger = files\ n
					    621 root / usr / sbin / irqbalance--foreground\ n 624 polkitd / usr / lib / polkit - 1 / polkitd--no - debug\ n 632 dbus / usr / bin / dbus - daemon--system--address = systemd: --nofork--nopidfile--sys
					    temd - activation--syslog - only\ n 641 rngd / sbin / rngd - f--fill - watermark = 0\ n 701 root / usr / sbin / sshd - D - u0 - oCiphers = aes256 - gcm @openssh.com,
					    chacha20 - poly1305 @openssh.com,
					    aes256 - ctr,
					    aes
					    256 - cbc,
					    aes128 - gcm @openssh.com,
					    aes128 - ctr,
					    aes128 - cbc - oMACs = hmac - sha2 - 256 - etm @openssh.com,
					    hmac - sha1 - etm @openssh.com,
					    umac - 128 - etm @openssh.com,
					    hmac - sha2 - 512 - etm @openssh.com,
					    hmac - sha2 - 256,
					    hmac - sha1,
					    uma
					    c - 128 @openssh.com,
					    hmac - sha2 - 512 - oGSSAPIKexAlgorithms = gss - curve25519 - sha256 - ,
					    gss - nistp256 - sha256 - ,
					    gss - group14 - sha256 - ,
					    gss - group16 - sha512 - ,
					    gss - gex - sha1 - ,
					    gss - group14 - sha1 - -oKexAlgorithms = curve25519 - s
					    ha256,
					    curve25519 - sha256 @libssh.org,
					    ecdh - sha2 - nistp256,
					    ecdh - sha2 - nistp384,
					    ecdh - sha2 - nistp521,
					    diffie - hellman - group - exchange - sha256,
					    diffie - hellman - group14 - sha256,
					    diffie - hellman - group16 - sha512,
					    diffie - he
					    llman - group18 - sha512,
					    diffie - hellman - group - exchange - sha1,
					    diffie - hellman - group14 - sha1 - oHostKeyAlgorithms = ecdsa - sha2 - nistp256,
					    ecdsa - sha2 - nistp256 - cert - v01 @openssh.com,
					    ecdsa - sha2 - nistp384,
					    ecdsa - sha2 - ni
					    stp384 - cert - v01 @openssh.com,
					    ecdsa - sha2 - nistp521,
					    ecdsa - sha2 - nistp521 - cert - v01 @openssh.com,
					    ssh - ed25519,
					    ssh - ed25519 - cert - v01 @openssh.com,
					    rsa - sha2 - 256,
					    rsa - sha2 - 256 - cert - v01 @openssh.com,
					    rsa - sha2 - 512,
					    rsa -
					    sha2 - 512 - cert - v01 @openssh.com,
					    ssh - rsa,
					    ssh - rsa - cert - v01 @openssh.com - oPubkeyAcceptedKeyTypes = ecdsa - sha2 - nistp256,
					    ecdsa - sha2 - nistp256 - cert - v01 @openssh.com,
					    ecdsa - sha2 - nistp384,
					    ecdsa - sha2 - nistp384 - cert -
					    v01 @openssh.com,
					    ecdsa - sha2 - nistp521,
					    ecdsa - sha2 - nistp521 - cert - v01 @openssh.com,
					    ssh - ed25519,
					    ssh - ed25519 - cert - v01 @openssh.com,
					    rsa - sha2 - 256,
					    rsa - sha2 - 256 - cert - v01 @openssh.com,
					    rsa - sha2 - 512,
					    rsa - sha2 - 512 - cer
					    t - v01 @openssh.com,
					    ssh - rsa,
					    ssh - rsa - cert - v01 @openssh.com - oCASignatureAlgorithms = ecdsa - sha2 - nistp256,
					    ecdsa - sha2 - nistp384,
					    ecdsa - sha2 - nistp521,
					    ssh - ed25519,
					    rsa - sha2 - 256,
					    rsa - sha2 - 512,
					    ssh - rsa\ n 712 root /
					    usr / sbin / gssproxy - D\ n 720 root / usr / libexec / sssd / sssd_be--domain implicit_files--uid 0--gid 0--logger = files\ n 721 root / usr / libexec / sssd / sssd_nss--uid 0--gid 0--logger = fi
					    les\ n 729 root / usr / sbin / rsyslogd - n\ n 733 root / usr / lib / systemd / systemd - logind\ n 736 root / usr / sbin / crond - n\ n 737 root / sbin / agetty - o - p--\\u--noclear tty1 linux\ n
					    1676 root / usr / sbin / VBoxService--pidfile /
					    var / run / vboxadd - service.sh\ n 1933 root / usr / sbin / NetworkManager--no - daemon\ n 2280 root sshd: vagrant[priv]\ n 2283 vagrant / usr / lib / s
					    ystemd / systemd--user\ n 2286 vagrant(sd - pam)\ n 2292 vagrant sshd: vagrant @pts / 0\ n 2293 vagrant - bash\ n 2435 root sudo su\ n 2436 root su\ n 2437 root bash\ n 49410 root /
						    sbin / auditd\ n 49493 root[audit_prune_tre]\ n 50852 root /
						    var / ossec / bin / wazuh - execd\ n 50861 ossec /
						    var / ossec / bin / wazuh - agentd\ n 50876 root /
						    var / ossec / bin / wazuh - syscheckd\ n 50889
					    root /
					    var / ossec / bin / wazuh - logcollector\ n 50897 root /
					    var / ossec / bin / wazuh - modulesd\ n 58474 root[kworker / u4: 1 - flush - 8: 0]\ n 58568 root[kworker / u4: 2 - xfs - cil / sda1]\ n 58950 root[kworker / 1: 0 - events]\ n 59160 root[kworker / 1: 1 - events]\ n 59234 root[kworker / 0: 3 - events]\ n 59276 root[kworker / 0: 1 - events]\ n 59308 root nc - l 8000\ n 59309 root ps - e - o pid,
					    uname,
					    command ",
					    "input": {
						    "type": "log"
					    },
					    "@timestamp": "2022-05-03T16:18:55.635Z",
					    "location": "process list",
					    "id": "1651594735.38756",
					    "timestamp": "2022-05-03T16:18:55.635+0000"
				    }
			    }
		    ]
	    }
    }
    ```
    
    </details>
