### ISSUE TITLE
Syscheck automated tests: windows_registry option

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh-qa#285]
| Working branch |
| --- |
| |

## Description

`windows_registry` option is used to monitor specified Windows registry entries (one entry per line). Multiple lines may be entered to include multiple registry entries.

| Default value | HKEY_LOCAL_MACHINE\Software |
| --- | --- |
| Allowed values | Any registry entry. |

Take into account... 
- New entries will not trigger alerts, only changes to existing registry entries.
- Syscheck ignores empty Windows Registry keys. (see https://github.com/wazuh/wazuh/issues/858)

`windows_registry` also accepts `arch` and `tags` parameters:

- `arch`
Select the Registry view depending on the architecture.
**Default value:** 32bit
**Allowed values:** 32bit, 64bit, both

- `tags`
Add tags to alerts for monitored registry entries.
**Allowed values:** Tags list separated by commas

## Subtasks

- [x] Check that windows_registry does not trigger alerts for empty keys
- [x] Check that windows_registry trigger alerts for new entries
- [x] Check that windows_registry trigger alerts when modifying existing keys
- [x] Check that windows_registry trigger alerts when modifying existing keys using 'arch' option
- [x] Check that windows_registry trigger alerts when modifying existing keys using 'tag' option

**Comment by DFolchA** [comment]
Hello team,
I have  started to create this test, I have foun that we can create and edit Windows registers by using the winreg module.

I have manually tested all the use cases mentioned in the issue by manually editing the registers with regedit and by using the python module.

To finish I am currently coding all this into a test with the different configurations that need to be tested.

Regards, 
Daniel Folch

**Comment by DFolchA** [comment]
Hello team,

Next I will add a brief guide of how to create, edit and delete windows registries:

To create a registry use the following command in the python script:

`key =  winreg.CreateKeyEx( winreg.HKEY_LOCAL_MACHINE,r'SOFTWARE\\Classes\\testkey',access=winreg.KEY_SET_VALUE)`

or

`key =  winreg.CreateKeyEx( winreg.HKEY_LOCAL_MACHINE,r'SOFTWARE\\Classes\\testkey')`

This creates a new key or opens it it it already existed, the return value of this functions is the handle of the generated key, that will be used later to edit the value of the registry.

To  edit the value of a key we can use:

`winreg.SetValueEx(key, test_value, winreg.REG_SZ, 1)`

or

`winreg.SetValue( winreg.HKEY_LOCAL_MACHINE,r'SOFTWARE\\Classes\\testkey', winreg.REG_SZ, 1)`

To delete the key we use:

winreg.DeleteKeyEx(key)

or

`winreg.DeleteKey(winreg.HKEY_LOCAL_MACHINE,r'SOFTWARE\\Classes\\testkey')`

For more information consult the official documentation:
https://docs.python.org/3/library/winreg.html

Remember that starting from Windows 7 registry reflection cant be disabled so we cannot edit 32 or 64 bit registries independently in 64bit systems, so there is no point in using the `winreg.DisableReflectionKey` function.

For more information consult this link:
https://docs.microsoft.com/en-us/windows/win32/winprog64/shared-registry-keys

Regard,
Daniel Folch
