### ISSUE TITLE
E2E Research: Audit

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#2853]
## Description

In this issue, we will study the audit test case described [here](https://github.com/wazuh/wazuh-automation/wiki/Wazuh-demo:-Execution-guide#audit). All the info obtained will be used in the future for the design and implementation of E2E tests.

## Tasks

- [x] ([**T1**](https://github.com/wazuh/wazuh-qa/issues/2853#issuecomment-1116160164)):  Environment provision
- [x] ([**T2**](https://github.com/wazuh/wazuh-qa/issues/2853#issuecomment-1116181420)): Test case configuration
- [x] ([**T3**](https://github.com/wazuh/wazuh-qa/issues/2853#issuecomment-1116187353)): Generate events
- [x] ([**T4**](https://github.com/wazuh/wazuh-qa/issues/2853#issuecomment-1116187353)): Check alerts

## Conclusion

We have only used a Linux manager (CentOS), in which audit was installed by default and the configuration and rules were already by default. No additional configuration was needed.

**Comment by juliamagan** [comment]
## Task 1: Environment provision 

I've followed the [Quickstart guide](https://documentation-dev.wazuh.com/4.3-rc/quickstart.html#installing-wazuh) and set up an all-in-one environment.

|Install type|OS|CPU|RAM|
|:--:|:--:|:--:|:--:|
|All-in-one|Centos 8|2|4096|

**Comment by juliamagan** [comment]
## Task 2: Test case configuration

Audit can be only used in Linux systems. 

1. We have verified that it was already installed by executing the following command:

```
systemctl status auditd.service
```

2. We have verified that the following configuration is in `/var/ossec/etc/ossec.conf` (it should be by default):

```
<localfile>
  <log_format>audit</log_format>
  <location>/var/log/audit/audit.log</location>
</localfile>
```
3. We got our current euid in the CentOS 8 endpoint:

```
echo $EUID
```

4. We have created the `/etc/audit/rules.d/wazuh.rules` file and added the following rules:

```
-a exit,always -F euid=your_user_id -F arch=b32 -S execve -k audit-wazuh-c
-a exit,always -F euid=your_user_id -F arch=b64 -S execve -k audit-wazuh-c
```
 5. We have loaded the rules:

```
auditctl -R /etc/audit/rules.d/wazuh.rules
```

6. Finally, we have executed a ping to _www.google.com_

**Comment by juliamagan** [comment]
## Task 3: Generate events

We have executed a ping to _www.google.com_

We can see the events generated in `/var/log/audit/audit.log`:

```
type=SYSCALL msg=audit(1651589118.760:1315): arch=c000003e syscall=59 success=yes exit=0 a0=5563d8932e20 a1=5563d887fc50 a2=5563d894d4a0 a3=8 items=2 ppid=11441 pid=11499 auid=1000 uid=1000 gid=1000 euid=1000 suid=1000 fsuid=1000 egid=1000 sgid=1000 fsgid=1000 tty=pts1 ses=8 comm="ping" exe="/usr/bin/ping" subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 key="audit-wazuh-c"ARCH=x86_64 SYSCALL=execve AUID="vagrant" UID="vagrant" GID="vagrant" EUID="vagrant" SUID="vagrant" FSUID="vagrant" EGID="vagrant" SGID="vagrant" FSGID="vagrant"
type=BPRM_FCAPS msg=audit(1651589118.760:1315): fver=2 fp=0000000000003000 fi=0 fe=0 old_pp=0 old_pi=0 old_pe=0 old_pa=0 pp=0000000000003000 pi=0 pe=0 pa=0 frootid=0
type=EXECVE msg=audit(1651589118.760:1315): argc=2 a0="ping" a1="www.google.com"
type=CWD msg=audit(1651589118.760:1315): cwd="/home/vagrant"
type=PATH msg=audit(1651589118.760:1315): item=0 name="/usr/bin/ping" inode=25585470 dev=08:01 mode=0100755 ouid=0 ogid=0 rdev=00:00 obj=system_u:object_r:ping_exec_t:s0 nametype=NORMAL cap_fp=0000000000003000 cap_fi=0 cap_fe=0 cap_fver=2 cap_frootid=0OUID="root" OGID="root"
type=PATH msg=audit(1651589118.760:1315): item=1 name="/lib64/ld-linux-x86-64.so.2" inode=153852 dev=08:01 mode=0100755 ouid=0 ogid=0 rdev=00:00 obj=system_u:object_r:ld_so_t:s0 nametype=NORMAL cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0OUID="root" OGID="root"
type=PROCTITLE msg=audit(1651589118.760:1315): proctitle=70696E67007777772E676F6F676C652E636F6D
```

```

**Comment by juliamagan** [comment]
## Task 4: Check alerts

- `/var/ossec/logs/alerts/alerts.log`:

```
** Alert 1651589430.1023638: - audit,audit_command,gdpr_IV_30.1.g,
2022 May 03 14:50:30 localhost->/var/log/audit/audit.log
Rule: 80792 (level 3) -> 'Audit: Command: /usr/bin/ping.'
type=SYSCALL msg=audit(1651589429.921:1318): arch=c000003e syscall=59 success=yes exit=0 a0=5563d88836b0 a1=5563d887cc60 a2=5563d894d4a0 a3=8 items=2 ppid=11441 pid=11517 auid=1000 uid=1000 gid=1000 euid=1000 suid=1000 fsuid=1000 egid=1000 sgid=1000 fsgid=1000 tty=pts1 ses=8 comm="ping" exe="/usr/bin/ping" subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 key="audit-wazuh-c"ARCH=x86_64 SYSCALL=execve AUID="vagrant" UID="vagrant" GID="vagrant" EUID="vagrant" SUID="vagrant" FSUID="vagrant" EGID="vagrant" SGID="vagrant" FSGID="vagrant" type=BPRM_FCAPS msg=audit(1651589429.921:1318): fver=2 fp=0000000000003000 fi=0 fe=0 old_pp=0 old_pi=0 old_pe=0 old_pa=0 pp=0000000000003000 pi=0 pe=0 pa=0 frootid=0 type=EXECVE msg=audit(1651589429.921:1318): argc=2 a0="ping" a1="www.google.com" type=CWD msg=audit(1651589429.921:1318): cwd="/home/vagrant" type=PATH msg=audit(1651589429.921:1318): item=0 name="/usr/bin/ping" inode=25585470 dev=08:01 mode=0100755 ouid=0 ogid=0 rdev=00:00 obj=system_u:object_r:ping_exec_t:s0 nametype=NORMAL cap_fp=0000000000003000 cap_fi=0 cap_fe=0 cap_fver=2 cap_frootid=0OUID="root" OGID="root" type=PATH msg=audit(1651589429.921:1318): item=1 name="/lib64/ld-linux-x86-64.so.2" inode=153852 dev=08:01 mode=0100755 ouid=0 ogid=0 rdev=00:00 obj=system_u:object_r:ld_so_t:s0 nametype=NORMAL cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0OUID="root" OGID="root" type=PROCTITLE msg=audit(1651589429.921:1318): proctitle=70696E67007777772E676F6F676C652E636F6D
audit.type: SYSCALL
audit.id: 1318
audit.arch: c000003e
audit.syscall: 59
audit.success: yes
audit.exit: 0
audit.ppid: 11441
audit.pid: 11517
audit.auid: 1000
audit.uid: 1000
audit.gid: 1000
audit.euid: 1000
audit.suid: 1000
audit.fsuid: 1000
audit.egid: 1000
audit.sgid: 1000
audit.fsgid: 1000
audit.tty: pts1
audit.session: 8
audit.command: ping
audit.exe: /usr/bin/ping
audit.key: audit-wazuh-c
audit.execve.a0: ping
audit.execve.a1: www.google.com
audit.cwd: /home/vagrant
audit.file.name: /usr/bin/ping
audit.file.inode: 25585470
audit.file.mode: 0100755
```
