### ISSUE TITLE
E2E Research: Osquery integration

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh-qa#2854]
## Description

This issue aims to test manually the `osquery` wodle to define the requirements to develop an automated E2E test.

To achieve this we will follow these guides:
1. https://documentation-dev.wazuh.com/4.3-rc/proof-of-concept-guide/integrate-osquery.html
2. https://documentation-dev.wazuh.com/4.3-rc/user-manual/capabilities/osquery.html#osquery

## Tasks

- [x] (**[T1](https://github.com/wazuh/wazuh-qa/issues/2854#issuecomment-1116320020)**) Install and configure the Osquery integration in a Manager
- [x] (**[T2](https://github.com/wazuh/wazuh-qa/issues/2854#issuecomment-1116342891)**) Install and configure the Osquery integration in an Agent and check if the alerts are generated in the Manager
- [x] (**[T3](https://github.com/wazuh/wazuh-qa/issues/2854#issuecomment-1117292302)**) Configure Osquery through [centralized configuration](https://documentation-dev.wazuh.com/4.3-rc/user-manual/reference/centralized-configuration.html) and generate alerts

## Conclusion 🟢 

| Requirements |
|---|
| A list of installation commands for each OS |
| 1 endpoint with Ubuntu 20.04 and wazuh manager installed. |
| 1 endpoint with CentOS 8 and wazuh agent installed (along with Osquery installed) |
| A configuration sample file to configure osquery |
| Wazuh API credentials |

**Comment by mauromalara** [comment]
# Task 1: Install and configure the Osquery integration in a Manager 🟢

## Conclusion 🟢

It is possible to get the alerts in JSON format through the opensearch API by using, for example, Python or cURL.
By doing this we'll be able to check if the integration works as expected.

***

## Step by step

1. Install Osquery:
```
wget https://pkg.osquery.io/deb/osquery_4.5.1_1.linux.amd64.deb
apt install ./osquery_4.5.1_1.linux.amd64.deb -y
```
2. Configure Osquery with the following configuration sample:
```
{
"options": {
    "config_plugin": "filesystem",
    "logger_plugin": "filesystem",
    "utc": "true"
},

"schedule": {
    "system_info": {
        "query": "SELECT hostname, cpu_brand, physical_memory FROM system_info;",
        "interval": 3600
    },
    "high_load_average": {
        "query": "SELECT period, average, '70%' AS 'threshold' FROM load_average WHERE period = '15m' AND average > '0.7';",
        "interval": 900,
        "description": "Report if load charge is over 70 percent."
    },
    "low_free_memory": {
        "query": "SELECT memory_total, memory_free, CAST(memory_free AS real) / memory_total AS memory_free_perc, '10%' AS threshold FROM memory_info WHERE memory_free_perc < 0.1;",
        "interval": 1800,
        "description": "Free RAM is under 10%."
    }
},

"packs": {
    "osquery-monitoring": "/usr/share/osquery/packs/osquery-monitoring.conf",
    "incident-response": "/usr/share/osquery/packs/incident-response.conf",
    "it-compliance": "/usr/share/osquery/packs/it-compliance.conf",
    "vuln-management": "/usr/share/osquery/packs/vuln-management.conf",
    "hardware-monitoring": "/usr/share/osquery/packs/hardware-monitoring.conf",
    "ossec-rootkit": "/usr/share/osquery/packs/ossec-rootkit.conf"
    }
}
```
3. Enable the `osquery` wodle by adding the following XML block in the `/var/ossec/etc/ossec.conf` file:
```
  <wodle name="osquery">
      <disabled>no</disabled>
      <run_daemon>yes</run_daemon>
      <bin_path>/usr/bin</bin_path>
      <log_path>/var/log/osquery/osqueryd.results.log</log_path>
      <config_path>/etc/osquery/osquery.conf</config_path>
      <add_labels>no</add_labels>
  </wodle>
```
4. Start Osqueryd service: `systemctl start osqueryd`
5. Restart the manager: `systemctl restart wazuh-agent`

## Result

<details>
<summary>Alerts related to Osquery (index: wazuh-alerts-*)</summary>

```
{
   "took":5,
   "timed_out":false,
   "_shards":{
      "total":3,
      "successful":3,
      "skipped":0,
      "failed":0
   },
   "hits":{
      "total":{
         "value":79,
         "relation":"eq"
      },
      "max_score":1.7367972,
      "hits":[
         {
            "_index":"wazuh-alerts-4.x-2022.05.03",
            "_type":"_doc",
            "_id":"7S2AioABAzFAnxU3Ij0X",
            "_score":1.7367972,
            "_source":{
               "agent":{
                  "name":"manager-4-3-0-ubuntu-2",
                  "id":"000"
               },
               "manager":{
                  "name":"manager-4-3-0-ubuntu-2"
               },
               "data":{
                  "osquery":{
                     "calendarTime":"Tue May 3 15:18:05 2022 UTC",
                     "subquery":"osquery_info",
                     "hostIdentifier":"manager-4-3-0-ubuntu-2",
                     "unixTime":"1651591085",
                     "columns":{
                        "watcher":"47344",
                        "system_time":"20",
                        "config_valid":"1",
                        "pid":"47347",
                        "counter":"18",
                        "uuid":"ac3cb238-b6af-ef49-bf17-953fe64c85b4",
                        "version":"4.5.1",
                        "config_hash":"de20698496ca774c9b149c35d22a1e504a8a9e52",
                        "build_platform":"1",
                        "start_time":"1651591051",
                        "extensions":"active",
                        "instance_id":"06bd87d9-f979-4d08-b220-dead63b3a35b",
                        "platform_mask":"9",
                        "build_distro":"centos7",
                        "resident_size":"23824000",
                        "user_time":"40"
                     },
                     "name":"pack_osquery-monitoring_osquery_info",
                     "numerics":"false",
                     "action":"added",
                     "epoch":"0",
                     "counter":"0",
                     "pack":"osquery-monitoring"
                  }
               },
               "rule":{
                  "firedtimes":1,
                  "mail":false,
                  "level":4,
                  "description":"osquery: osquery-monitoring osquery_info: Osquery version is 4.5.1 build on 1 centos7",
                  "groups":[
                     "osquery",
                     "osquery_monitoring"
                  ],
                  "id":"24023"
               },
               "decoder":{
                  "name":"json"
               },
               "input":{
                  "type":"log"
               },
               "@timestamp":"2022-05-03T15:18:05.874Z",
               "location":"osquery",
               "id":"1651591085.543685",
               "timestamp":"2022-05-03T15:18:05.874+0000"
            }
         }
         .
         .
         .
      ]
   }
}
```

</details>

**Comment by mauromalara** [comment]
Task 2: Install and configure the Osquery integration in an Agent and check if the alerts are generated in the Manager 🔵

**Comment by mauromalara** [comment]
# Task 3: Configure Osquery through [centralized configuration](https://documentation-dev.wazuh.com/4.3-rc/user-manual/reference/centralized-configuration.html) and generate alerts 🔵

WIP.
