### ISSUE TITLE
E2E Research: SQL Injection

### ISSUE THREAD

**Issue by BelenValdivia** [wazuh/wazuh-qa#2857]
This issue aims to test manually the Virus total integration to define the requirements to develop an automated test.

We follow these guides:

- https://documentation.wazuh.com/current/proof-of-concept-guide/detect-web-attack-sql-injection.html?highlight=sql%20injection
- https://github.com/wazuh/wazuh/wiki/Proof-of-concept-guide#detecting-a-web-attack---sql-injection

## Tasks
- [x] [(T1](https://github.com/wazuh/wazuh-qa/issues/2857#issuecomment-1117402457)) Configure Apache in the monitored agent.
- [x] ([T2](https://github.com/wazuh/wazuh-qa/issues/2857#issuecomment-1117637724)) Configure ossec.conf to monitor the access logs of the Apache server.
- [x] ([T3](https://github.com/wazuh/wazuh-qa/issues/2857#issuecomment-1117666479)) Generate and check the alerts.

## Conlusion 🟢 
The use case tested were successful. I configured a manager, filebeat, kibana and elastic in the same machine (Centos 8). I configured a agent Linux(Centos 8). Prerequisite: Have Apache running in the agent.

**Comment by BelenValdivia** [comment]
## Task 1 - Configure Apache

1. Install apache in the monitored endpoint. I follow this guide https://www.digitalocean.com/community/tutorials/how-to-install-the-apache-web-server-on-centos-8

2. Check apache status: `systemctl status httpd`
![image](https://user-images.githubusercontent.com/26927338/166705157-3ae1790e-4451-4053-a708-93a1ad432a85.png)

**Comment by BelenValdivia** [comment]
## Task 2 -  Configuration

1. Add the following lines to /var/ossec/etc/ossec.conf at the monitored host.
<details>
<summary>ossec.conf</summary>

```
<localfile>
<log_format>apache</log_format>
<location>/var/log/httpd/access_log</location>
</localfile>
```

</details>

**Comment by BelenValdivia** [comment]
## Task 3 - Generate and check the alerts

1.  Replace <web_server_address> with the appropriate value and execute the following command from a system external to the monitored endpoint (the attacker).
`curl -XGET "http://replace_by_web_server_address/?id=SELECT+*+FROM+users";`

2.  Check alerts.log in wazuh manager
    <details>
    <summary>alerts.log</summary>
    ** Alert 1651606249.61408: - web,accesslog,attack,sql_injection,pci_dss_6.5,pci_dss_11.4,pci_dss_6.5.1,gdpr_IV_35.7.d,nist_800_53_SA.11,nist_800_53_SI.4,tsc_CC6.6,tsc_CC7.1,tsc_CC8.1,tsc_CC6.1,tsc_C
    C6.8,tsc_CC7.2,tsc_CC7.3,
    2022 May 03 19:30:49 (centos-agent) any->/var/log/httpd/access_log
    Rule: 31103 (level 7) -> 'SQL injection attempt.'
    Src IP: 172.17.1.1
    172.17.1.1 - - [03/May/2022:19:30:47 +0000] "GET /?id=SELECT+*+FROM+users HTTP/1.1" 403 199691 "-" "curl/7.64.0"
    </details>

3. Check events in the UI
![sql injection](https://user-images.githubusercontent.com/26927338/166773973-a1149230-f7f4-4f83-97a4-3d7dc4c500de.png)

4. Check the alerts through the API

- Request:

```
curl --insecure -XGET -u 'USER:PASSWORD' "https://localhost:9200/wazuh-alerts-4.x-*/_search?pretty" -H 'Content-Type: application/json' -d '
{
  "query": {
    "term": {
      "rule.id": "31103"
    }
  }
}
'
```

- Response:
    <details>
    <summary>alert</summary>

    ```
    {
      "took" : 4,
      "timed_out" : false,
      "_shards" : {
        "total" : 18,
        "successful" : 18,
        "skipped" : 0,
        "failed" : 0
      },
      "hits" : {
        "total" : {
          "value" : 1,
          "relation" : "eq"
        },
        "max_score" : 2.9267395,
        "hits" : [
          {
            "_index" : "wazuh-alerts-4.x-2022.05.03",
            "_type" : "_doc",
            "_id" : "x",
            "_score" : 2.9267395,
            "_source" : {
              "agent" : {
                "ip" : "X.X.X.X",
                "name" : "centos-agent",
                "id" : "001"
              },
              "manager" : {
                "name" : "centos-manager-kibana"
              },
              "data" : {
                "protocol" : "GET",
                "srcip" : "X.X.X.X",
                "id" : "403",
                "url" : "/?id=SELECT+*+FROM+users"
              },
              "rule" : {
                "firedtimes" : 1,
                "mail" : false,
                "level" : 7,
                "pci_dss" : [
                  "6.5",
                  "11.4",
                  "6.5.1"
                ],
                "tsc" : [
                  "CC6.6",
                  "CC7.1",
                  "CC8.1",
                  "CC6.1",
                  "CC6.8",
                  "CC7.2",
                  "CC7.3"
                ],
                "description" : "SQL injection attempt.",
                "groups" : [
                  "web",
                  "accesslog",
                  "attack",
                  "sql_injection"
                ],
                "mitre" : {
                  "technique" : [
                    "Exploit Public-Facing Application"
                  ],
                  "id" : [
                    "T1190"
                  ],
                  "tactic" : [
                    "Initial Access"
                  ]
                },
                "id" : "31103",
                "nist_800_53" : [
                  "SA.11",
                  "SI.4"
                ],
                "gdpr" : [
                  "IV_35.7.d"
                ]
              },
              "decoder" : {
                "name" : "web-accesslog"
              },
              "full_log" : "X.X.X.X - - [03/May/2022:19:30:47 +0000] \"GET /?id=SELECT+*+FROM+users HTTP/1.1\" 403 199691 \"-\" \"curl/7.64.0\"",
              "input" : {
                "type" : "log"
              },
              "@timestamp" : "2022-05-03T19:30:49.515Z",
              "location" : "/var/log/httpd/access_log",
              "id" : "X",
              "timestamp" : "2022-05-03T19:30:49.515+0000"
            }
          }
        ]
      }
    }
    ```
    
    </details>
