### ISSUE TITLE
Syscheck automated tests: registry_ignore

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh-qa#286]
## Description

Create a new test for `registry_ignore`. This option is used in Windows to create a list of registry entries to be ignored. (one entry per line). Multiple lines may be entered to include multiple registry entries.

- **Default value:** n/a
- **Allowed values:** Any registry entry.

Available attributes for `registry_ignore`:

- arch
Select the Registry to ignore depending on the architecture.
**Default value:** 32bit
**Allowed values:** 32bit, 64bit, both

- type
This is a simple regex pattern to filter out files so alerts are not generated.
**Allowed values:** sregex

One of the configuration used on this test must be use both `<registry_ignore>` and `<registry_ignore type="sregex">` stanzas. Both should be taken into account at the registry ignore process but due to a known bug only the non-sregex ones  could be applied. The bug was reported here: https://github.com/wazuh/wazuh/issues/3990

To test this particular behaviour is recommended to use the following configuration:

```XML
      <registry_ignore>HKEY_LOCAL_MACHINE\Security</registry_ignore>
      <registry_ignore type="sregex">HKEY_LOCAL_MACHINE\System</registry_ignore>
      <registry_ignore type="sregex">HKEY_LOCAL_MACHINE\Software</registry_ignore>
      <registry_ignore arch='64bit'>HKEY_LOCAL_MACHINE\Software\Microsoft\Internet Explorer</registry_ignore>
```

## Subtasks
- [x] Check the registry entries are ignored using registry_ignore without any other parameters.
- [x] Check the registry entries are ignored using registry_ignore with `arch` parameter.
- [x] Check the registry entries are ignored using registry_ignore with `type` parameter.
- [x] Check the registry entries using the advanced configuration proposed.
