### ISSUE TITLE
E2E Research: Detecting a Shellshock attack

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh-qa#2861]
## Description
This issue aims to test manually the Wazuh capability of detecting Shellshock attacks to define the requirements to develop an automated E2E test.

To achieve this we will follow these guides:

1. https://documentation-dev.wazuh.com/4.3-rc/proof-of-concept-guide/detect-web-attack-shellshock.html
2. https://documentation-dev.wazuh.com/4.3-rc/learning-wazuh/shellshock.html#learning-wazuh-shellshock

## Tasks

- [x] (**[T1](https://github.com/wazuh/wazuh-qa/issues/2861#issuecomment-1117954171)**) Configure the VMs and install Wazuh (manager and agent) in both VMs
- [x] (**[T2](https://github.com/wazuh/wazuh-qa/issues/2861#issuecomment-1118483732)**) Configure an Apache server in the agent endpoint
- [x] (**[T3](https://github.com/wazuh/wazuh-qa/issues/2861#issuecomment-1118528061)**) Attack and query the alert

## Conclusion 🟢 

| Requirements
|--
| A CentOS 8 machine with the Wazuh manager installed on it.
| An Ubuntu 20.04 machine with the Wazuh agent and an Apache server installed on it.
| A CentOS 8 machine that will be the attacker.
| The XML configuration block for the agent to monitor the access logs of the Apache server.
| The query to get the alert from the manager.

**Comment by mauromalara** [comment]
# Task 1: Configure the VMs and install Wazuh (manager and agent) in both VMs 🟢 

I configure 2 VMs using the qa-ctl tool and then I install manually the Wazuh manager and agent.

|Endpoint type | OS | Installation |
|-- | -- |--|
| Manager | CentOS 8 | Using the 4.3.0 quickstart guide |
| Agent | Ubuntu 20.04 | Using the pre-release package |

**Comment by mauromalara** [comment]
# Task 2: Configure an Apache server in the agent endpoint 🟢 

## Step by step

1. Run the following commands
```
sudo apt update
sudo apt install apache2 -y
```

**Comment by mauromalara** [comment]
# Task 3: Attack and query the alert 🟢 

## Step by step

1. Add the following XML block to the `/var/ossec/etc/ossec.conf` configuration file of the agent:
```
  <localfile>
    <log_format>apache</log_format>
    <location>/var/log/apache2/access.log</location>
  </localfile>
```
2. Restart the agent: `systemctl restart wazuh-agent`
3. From the VM of the attacker execute (replace <AGENT_IP> with a valid IP):
```
curl -H "User-Agent: () { :; }; /bin/cat /etc/passwd" <AGENT_IP>
```
4. Finally, from the manager endpoint run the following command to query the generated alert:


## Result

<details>

<summary>Alert from "wazuh-alerts-*" index &#8595</summary>

```
{
  "took" : 50,
  "timed_out" : false,
  "_shards" : {
    "total" : 3,
    "successful" : 3,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 1,
      "relation" : "eq"
    },
    "max_score" : 4.591747,
    "hits" : [
      {
        "_index" : "wazuh-alerts-4.x-2022.05.05",
        "_type" : "_doc",
        "_id" : "N75ClIAB4rtrks33HdGj",
        "_score" : 4.591747,
        "_source" : {
          "agent" : {
            "ip" : "10.0.2.15",
            "name" : "agent-2861",
            "id" : "001"
          },
          "manager" : {
            "name" : "manager-2861"
          },
          "data" : {
            "protocol" : "GET",
            "srcip" : "10.150.50.42",
            "id" : "200",
            "url" : "/"
          },
          "rule" : {
            "firedtimes" : 1,
            "mail" : true,
            "level" : 15,
            "pci_dss" : [
              "11.4"
            ],
            "tsc" : [
              "CC6.1",
              "CC6.8",
              "CC7.2",
              "CC7.3"
            ],
            "description" : "Shellshock attack detected",
            "groups" : [
              "web",
              "accesslog",
              "attack"
            ],
            "mitre" : {
              "technique" : [
                "Exploitation for Privilege Escalation",
                "Exploit Public-Facing Application"
              ],
              "id" : [
                "T1068",
                "T1190"
              ],
              "tactic" : [
                "Privilege Escalation",
                "Initial Access"
              ]
            },
            "id" : "31168",
            "nist_800_53" : [
              "SI.4"
            ],
            "info" : "CVE-2014-6271https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-6271",
            "gdpr" : [
              "IV_35.7.d"
            ]
          },
          "decoder" : {
            "name" : "web-accesslog"
          },
          "full_log" : "10.150.50.42 - - [05/May/2022:12:46:37 +0000] \"GET / HTTP/1.1\" 200 11173 \"-\" \"() { :; }; /bin/cat /etc/passwd\"",
          "input" : {
            "type" : "log"
          },
          "@timestamp" : "2022-05-05T12:46:37.806Z",
          "location" : "/var/log/apache2/access.log",
          "id" : "1651754797.1068307",
          "timestamp" : "2022-05-05T12:46:37.806+0000"
        }
      }
    ]
  }
}
```

</details>

![image](https://user-images.githubusercontent.com/39094716/166929496-78701059-0550-4e73-b12b-1bdd3b725327.png)
