### ISSUE TITLE
E2E Research: Vulnerability Detector

### ISSUE THREAD

**Issue by BelenValdivia** [wazuh/wazuh-qa#2863]
This issue aims to test manually Vulnerability Detector to define the requirements to develop an automated E2E test.

To achieve this we will follow these guides:

- https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/running-vu-scan.html
- https://documentation-dev.wazuh.com/4.3-rc/user-manual/capabilities/vulnerability-detection/running-vu-scan.html?highlight=vulnerability%20detector

## Tasks
- [x] ([T1](https://github.com/wazuh/wazuh-qa/issues/2863#issuecomment-1119048628)) Configure agent.
- [x] ([T2](https://github.com/wazuh/wazuh-qa/issues/2863#issuecomment-1119540707)) Configure manager.
- [x] ([T3](https://github.com/wazuh/wazuh-qa/issues/2863#issuecomment-1119564473)) Generate and check alerts Windows.
- [x] ([T4](https://github.com/wazuh/wazuh-qa/issues/2863#issuecomment-1119628229)) Generate and check alerts Linux.

## Conclusion 🟢 
The different use cases tested were successful. I configured a manager, filebeat, kibana and elastic in the same machine (Centos 8). I configured two agents Linux(Centos 8) and Windows(Windows Server 2019).
Prerequisite: Have previously installed a package with vulnerabilities so when the scan start, alerts are generated.

**Comment by BelenValdivia** [comment]
## Task 1 - Configure agent
 1. Enable the agent module used to collect installed packages on the monitored system.
 <details>
<summary>ossec.conf</summary>

```
<wodle name="syscollector">
  <disabled>no</disabled>
  <interval>1h</interval>
  <os>yes</os>
  <packages>yes</packages>
</wodle>
```

</details>

If you want to scan vulnerabilities in Windows agents, you will also have to add the `hotfixes` scan:
 <details>
<summary>ossec.conf</summary>

```
<wodle name="syscollector">
  <disabled>no</disabled>
  <interval>1h</interval>
  <os>yes</os>
  <packages>yes</packages>
  <hotfixes>yes</hotfixes>
</wodle>
```

</details>

**Comment by BelenValdivia** [comment]
## Task 2 - Configure manager 

1. Enable the manager module used to detect vulnerabilities.
<details>
<summary>ossec.conf</summary>

```
 <vulnerability-detector>
    <enabled>yes</enabled>
    <interval>5m</interval>
    <ignore_time>6h</ignore_time>
    <run_on_start>yes</run_on_start>

    <!-- Ubuntu OS vulnerabilities -->
    <provider name="canonical">
      <enabled>no</enabled>
      <os>trusty</os>
      <os>xenial</os>
      <os>bionic</os>
      <os>focal</os>
      <update_interval>1h</update_interval>
    </provider>

    <!-- Debian OS vulnerabilities -->
    <provider name="debian">
      <enabled>no</enabled>
      <os>stretch</os>
      <os>buster</os>
      <update_interval>1h</update_interval>
    </provider>

    <!-- RedHat OS vulnerabilities -->
    <provider name="redhat">
      <enabled>yes</enabled>
      <os>5</os>
      <os>6</os>
      <os>7</os>
      <os>8</os>
      <update_interval>1h</update_interval>
    </provider>

    <!-- Windows OS vulnerabilities -->
    <provider name="msu">
      <enabled>yes</enabled>
      <update_interval>1h</update_interval>
    </provider>

    <!-- Aggregate vulnerabilities -->
    <provider name="nvd">
      <enabled>yes</enabled>
      <update_from_year>2010</update_from_year>
      <update_interval>1h</update_interval>
    </provider>

  </vulnerability-detector>
```

</details>

**Comment by BelenValdivia** [comment]
## Generate and check alerts Linux
1. Have already installed a vulnerability package, in this case I used Python.
2. Alerts
<details>
<summary>alerts.log</summary>

```
** Alert 1651834200.26098876: - vulnerability-detector,gdpr_IV_35.7.d,pci_dss_11.2.1,pci_dss_11.2.3,tsc_CC7.1,tsc_CC7.2,
2022 May 06 10:50:00 (centos-agent) any->vulnerability-detector
Rule: 23504 (level 7) -> 'CVE-2021-20095 affects python38'
{"vulnerability":{"package":{"name":"python38","version":"3.8.6-3.module_el8.4.0+665+abc3a503","architecture":"x86_64","condition":"Package less than 3.8.8-4.module+el8.5.0+12205+a865257a"},"cvss":{"cvss3":{
"vector":{"attack_vector":"local","access_complexity":"low","privileges_required":"low","user_interaction":"none","scope":"unchanged","confidentiality_impact":"high","integrity_impact":"high","availability":
"high"},"base_score":7.8}},"cve":"CVE-2021-20095","title":"CVE-2021-20095 affects python38","rationale":"** REJECT ** DO NOT USE THIS CANDIDATE NUMBER. ConsultIDs: none. Reason: This candidate was withdrawn
by its CNA. Notes: none.","severity":"Medium","published":"2021-04-29","updated":"2021-06-16","cwe_reference":"CWE-22","advisories_ids":["RHSA-2021:3252","RHSA-2021:3254","RHSA-2021:4151","RHSA-2021:4162","R
HSA-2021:4201"],"bugzilla_references":["https://bugzilla.redhat.com/show_bug.cgi?id=1955615"],"references":["https://nvd.nist.gov/vuln/detail/CVE-2021-20095","https://access.redhat.com/security/cve/CVE-2021-
20095"],"assigner":"vulnreport@tenable.com","cve_version":"4.0"}}
vulnerability.package.name: python38
vulnerability.package.version: 3.8.6-3.module_el8.4.0+665+abc3a503
vulnerability.package.architecture: x86_64
vulnerability.package.condition: Package less than 3.8.8-4.module+el8.5.0+12205+a865257a
vulnerability.cvss.cvss3.vector.attack_vector: local
vulnerability.cvss.cvss3.vector.access_complexity: low
vulnerability.cvss.cvss3.vector.privileges_required: low
vulnerability.cvss.cvss3.vector.user_interaction: none
vulnerability.cvss.cvss3.vector.scope: unchanged
vulnerability.cvss.cvss3.vector.confidentiality_impact: high
vulnerability.cvss.cvss3.vector.integrity_impact: high
vulnerability.cvss.cvss3.vector.availability: high
vulnerability.cvss.cvss3.base_score: 7.800000
vulnerability.cve: CVE-2021-20095
vulnerability.title: CVE-2021-20095 affects python38
vulnerability.rationale: ** REJECT ** DO NOT USE THIS CANDIDATE NUMBER. ConsultIDs: none. Reason: This candidate was withdrawn by its CNA. Notes: none.
vulnerability.severity: Medium
vulnerability.published: 2021-04-29
vulnerability.updated: 2021-06-16
vulnerability.cwe_reference: CWE-22
vulnerability.advisories_ids: ["RHSA-2021:3252", "RHSA-2021:3254", "RHSA-2021:4151", "RHSA-2021:4162", "RHSA-2021:4201"]
vulnerability.bugzilla_references: ["https://bugzilla.redhat.com/show_bug.cgi?id=1955615"]
vulnerability.references: ["https://nvd.nist.gov/vuln/detail/CVE-2021-20095", "https://access.redhat.com/security/cve/CVE-2021-20095"]
vulnerability.assigner: vulnreport@tenable.com
vulnerability.cve_version: 4.0

```
</details>

3. Check UI
![vulnerability detector linux python 1](https://user-images.githubusercontent.com/26927338/167139016-6a4b7568-3255-4ce7-b586-ed6074d71a90.png)

![vulnerability detector linux python 2](https://user-images.githubusercontent.com/26927338/167139227-a0da77ab-591a-4660-b9f1-b50bd9e4ebef.png)

4. Check alerts through API
- Request:
```
curl --insecure -XGET -u 'USER:PASS' "https://localhost:9200/wazuh-alerts-4.x-*/_search?pretty" -H 'Content-Type: application/json' -d '
{
  "query": {
    "bool": {
      "must": [{
          "term": {
            "rule.id": "23504"
          }
      },{
          "term": {
            "data.vulnerability.cve": "CVE-2021-20095"
          }
      },{
          "term": {
            "agent.name": "centos-agent"
          }
      }]
    }
  }
}
'
```

- Response:
<details>
<summary>response</summary>

```
{
  "took" : 47,
  "timed_out" : false,
  "_shards" : {
    "total" : 3,
    "successful" : 3,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 6,
      "relation" : "eq"
    },
    "max_score" : 13.941629,
    "hits" : [
      {
        "_index" : "wazuh-alerts-4.x-2022.05.05",
        "_type" : "_doc",
        "_id" : "X",
        "_score" : 13.941629,
        "_source" : {
          "agent" : {
            "ip" : "X.X.X.X",
            "name" : "centos-agent",
            "id" : "003"
          },
          "manager" : {
            "name" : "centos-manager-kibana"
          },
          "data" : {
            "vulnerability" : {
              "severity" : "Medium",
              "package" : {
                "condition" : "Package less than 3.8.8-4.module+el8.5.0+12205+a865257a",
                "name" : "python38",
                "version" : "3.8.6-3.module_el8.4.0+665+abc3a503",
                "architecture" : "x86_64"
              },
              "references" : [
                "https://nvd.nist.gov/vuln/detail/CVE-2021-20095",
                "https://access.redhat.com/security/cve/CVE-2021-20095"
              ],
              "cve_version" : "4.0",
              "assigner" : "vulnreport@tenable.com",
              "published" : "2021-04-29",
              "cwe_reference" : "CWE-22",
              "title" : "CVE-2021-20095 affects python38",
              "rationale" : "** REJECT ** DO NOT USE THIS CANDIDATE NUMBER. ConsultIDs: none. Reason: This candidate was withdrawn by its CNA. Notes: none.",
              "advisories_ids" : [
                "RHSA-2021:3252",
                "RHSA-2021:3254",
                "RHSA-2021:4151",
                "RHSA-2021:4162",
                "RHSA-2021:4201"
              ],
              "cve" : "CVE-2021-20095",
              "bugzilla_references" : [
                "https://bugzilla.redhat.com/show_bug.cgi?id=1955615"
              ],
              "cvss" : {
                "cvss3" : {
                  "base_score" : "7.800000",
                  "vector" : {
                    "user_interaction" : "none",
                    "integrity_impact" : "high",
                    "scope" : "unchanged",
                    "confidentiality_impact" : "high",
                    "availability" : "high",
                    "attack_vector" : "local",
                    "access_complexity" : "low",
                    "privileges_required" : "low"
                  }
                }
              },
              "updated" : "2021-06-16"
            }
          },
          "rule" : {
            "firedtimes" : 2597,
            "mail" : false,
            "level" : 7,
            "pci_dss" : [
              "11.2.1",
              "11.2.3"
            ],
            "tsc" : [
              "CC7.1",
              "CC7.2"
            ],
            "description" : "CVE-2021-20095 affects python38",
            "groups" : [
              "vulnerability-detector"
            ],
            "id" : "23504",
            "gdpr" : [
              "IV_35.7.d"
            ]
          },
          "decoder" : {
            "name" : "json"
          },
          "input" : {
            "type" : "log"
          },
          "@timestamp" : "2022-05-05T22:49:29.325Z",
          "location" : "vulnerability-detector",
          "id" : "1651790969.19450254",
          "timestamp" : "2022-05-05T22:49:29.325+0000"
        }
      },
      
      {
        "_index" : "wazuh-alerts-4.x-2022.05.06",
        "_type" : "_doc",
        "_id" : "Y",
        "_score" : 12.667187,
        "_source" : {
          "agent" : {
            "ip" : "X.X.X.X",
            "name" : "centos-agent",
            "id" : "003"
          },
          "manager" : {
            "name" : "centos-manager-kibana"
          },
          "data" : {
            "vulnerability" : {
              "severity" : "Medium",
              "package" : {
                "condition" : "Package less than 3.8.8-4.module+el8.5.0+12205+a865257a",
                "name" : "python38",
                "version" : "3.8.6-3.module_el8.4.0+665+abc3a503",
                "architecture" : "x86_64"
              },
              "references" : [
                "https://nvd.nist.gov/vuln/detail/CVE-2021-20095",
                "https://access.redhat.com/security/cve/CVE-2021-20095"
              ],
              "cve_version" : "4.0",
              "assigner" : "vulnreport@tenable.com",
              "published" : "2021-04-29",
              "cwe_reference" : "CWE-22",
              "title" : "CVE-2021-20095 affects python38",
              "rationale" : "** REJECT ** DO NOT USE THIS CANDIDATE NUMBER. ConsultIDs: none. Reason: This candidate was withdrawn by its CNA. Notes: none.",
              "advisories_ids" : [
                "RHSA-2021:3252",
                "RHSA-2021:3254",
                "RHSA-2021:4151",
                "RHSA-2021:4162",
                "RHSA-2021:4201"
              ],
              "cve" : "CVE-2021-20095",
              "bugzilla_references" : [
                "https://bugzilla.redhat.com/show_bug.cgi?id=1955615"
              ],
              "cvss" : {
                "cvss3" : {
                  "base_score" : "7.800000",
                  "vector" : {
                    "user_interaction" : "none",
                    "integrity_impact" : "high",
                    "scope" : "unchanged",
                    "confidentiality_impact" : "high",
                    "availability" : "high",
                    "attack_vector" : "local",
                    "access_complexity" : "low",
                    "privileges_required" : "low"
                  }
                }
              },
              "updated" : "2021-06-16"
            }
          },
          "rule" : {
            "firedtimes" : 2243,
            "mail" : false,
            "level" : 7,
            "pci_dss" : [
              "11.2.1",
              "11.2.3"
            ],
            "tsc" : [
              "CC7.1",
              "CC7.2"
            ],
            "description" : "CVE-2021-20095 affects python38",
            "groups" : [
              "vulnerability-detector"
            ],
            "id" : "23504",
            "gdpr" : [
              "IV_35.7.d"
            ]
          },
          "decoder" : {
            "name" : "json"
          },
          "input" : {
            "type" : "log"
          },
          "@timestamp" : "2022-05-06T10:50:00.237Z",
          "location" : "vulnerability-detector",
          "id" : "1651834200.26098876",
          "timestamp" : "2022-05-06T10:50:00.237+0000"
        }
      },
      {
        "_index" : "wazuh-alerts-4.x-2022.05.06",
        "_type" : "_doc",
        "_id" : "TuKzl4ABhHNCzmRu5jJo",
        "_score" : Z,
        "_source" : {
          "agent" : {
            "ip" : "X.X.X.X",
            "name" : "centos-agent",
            "id" : "003"
          },
          "manager" : {
            "name" : "centos-manager-kibana"
          },
          "data" : {
            "vulnerability" : {
              "severity" : "Medium",
              "package" : {
                "condition" : "Package less than 3.8.8-4.module+el8.5.0+12205+a865257a",
                "name" : "python38",
                "version" : "3.8.6-3.module_el8.4.0+665+abc3a503",
                "architecture" : "x86_64"
              },
              "references" : [
                "https://nvd.nist.gov/vuln/detail/CVE-2021-20095",
                "https://access.redhat.com/security/cve/CVE-2021-20095"
              ],
              "cve_version" : "4.0",
              "assigner" : "vulnreport@tenable.com",
              "published" : "2021-04-29",
              "cwe_reference" : "CWE-22",
              "title" : "CVE-2021-20095 affects python38",
              "rationale" : "** REJECT ** DO NOT USE THIS CANDIDATE NUMBER. ConsultIDs: none. Reason: This candidate was withdrawn by its CNA. Notes: none.",
              "advisories_ids" : [
                "RHSA-2021:3252",
                "RHSA-2021:3254",
                "RHSA-2021:4151",
                "RHSA-2021:4162",
                "RHSA-2021:4201"
              ],
              "cve" : "CVE-2021-20095",
              "bugzilla_references" : [
                "https://bugzilla.redhat.com/show_bug.cgi?id=1955615"
              ],
              "cvss" : {
                "cvss3" : {
                  "base_score" : "7.800000",
                  "vector" : {
                    "user_interaction" : "none",
                    "integrity_impact" : "high",
                    "scope" : "unchanged",
                    "confidentiality_impact" : "high",
                    "availability" : "high",
                    "attack_vector" : "local",
                    "access_complexity" : "low",
                    "privileges_required" : "low"
                  }
                }
              },
              "updated" : "2021-06-16"
            }
          },
          "rule" : {
            "firedtimes" : 2243,
            "mail" : false,
            "level" : 7,
            "pci_dss" : [
              "11.2.1",
              "11.2.3"
            ],
            "tsc" : [
              "CC7.1",
              "CC7.2"
            ],
            "description" : "CVE-2021-20095 affects python38",
            "groups" : [
              "vulnerability-detector"
            ],
            "id" : "23504",
            "gdpr" : [
              "IV_35.7.d"
            ]
          },
          "decoder" : {
            "name" : "json"
          },
          "input" : {
            "type" : "log"
          },
          "@timestamp" : "2022-05-06T04:49:49.705Z",
          "location" : "vulnerability-detector",
          "id" : "1651812589.13035353",
          "timestamp" : "2022-05-06T04:49:49.705+0000"
        }
      }
    ]
  }
}
```

</summary>
