### ISSUE TITLE
E2E design and implementation: Monitoring Docker

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh-qa#2873]
| Type
|--
| E2E

## Description

The test research was accomplished in [this issue](https://github.com/wazuh/wazuh-qa/issues/2839). So, in this issue, we will design and develop the E2E test to cover those use cases.

## Tasks

- [x] (**[T1](https://github.com/wazuh/wazuh-qa/issues/2873#issuecomment-1121598289)**): Design the test
- [x] (**[T2](https://github.com/wazuh/wazuh-qa/issues/2873#issuecomment-1138913804)**): Implement the test locally
- [ ] ~~Refactor the test for it to work in the test environment~~

## Conclusion 🟡 

The test was not finished yet, only the setup stage has been started and the sprint was closed in the middle of the development. So, the test development will be finished in this issue: #2935.

**Comment by mauromalara** [comment]
Task 1: Design the test

1. I created the branch: [2873-e2e-test-monitoring-docker](https://github.com/wazuh/wazuh-qa/tree/2873-e2e-test-monitoring-docker)
2. I installed the QA framework following the [Wiki](https://github.com/wazuh/wazuh-qa/wiki/QACTL-tool-installation-guide)

**Comment by mauromalara** [comment]
# Task 2: Implement test locally

- I prepared the environment (docker, wazuh, wazuh-qa)

**Comment by juliamagan** [comment]
This issue is closed by the end of the sprint. Work will continue on #2935
