### ISSUE TITLE
E2E Reserach: IP Reputation

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#2875]
## Description

In this issue, we will study the IP Reputation test case described [here](https://github.com/wazuh/wazuh-automation/wiki/Wazuh-demo:-Execution-guide#ip_reputation). All the info obtained will be used in the future for the design and implementation of E2E tests.

## Tasks

- [x] ([**T1**](https://github.com/wazuh/wazuh-qa/issues/2875#issuecomment-1122591609)):  Environment provision
- [x] ([**T2**](https://github.com/wazuh/wazuh-qa/issues/2875#issuecomment-1122593603)): Test case configuration
- [x] ([**T3**](https://github.com/wazuh/wazuh-qa/issues/2875#issuecomment-1123541058)): Generate events
- [x] ([**T4**](https://github.com/wazuh/wazuh-qa/issues/2875#issuecomment-1123570435)): Check alerts

**Comment by juliamagan** [comment]
## Task 1: Environment provision 

I've followed the [Quickstart guide](https://documentation-dev.wazuh.com/4.3-rc/quickstart.html#installing-wazuh) and set up an all-in-one environment.

|Install type|OS|CPU|RAM|
|:--:|:--:|:--:|:--:|
|All-in-one|CentOS 8|2|4096|

**Comment by juliamagan** [comment]
## Task 2: Test case configuration

We need to install Apache and add the following configuration:

```
    <localfile>
       <log_format>apache</log_format>
       <location>/var/log/httpd/access_log</location>
    </localfile>
```

**Comment by juliamagan** [comment]
## Task 3: Generate events

To generate events, we have accessed the Apache server from the Windows machine:

```
http://<apache_server_address>:80
```

**Comment by juliamagan** [comment]
## Task 4: Check alerts


- Wazuh dashboard
![host_blocked](https://user-images.githubusercontent.com/80041853/167831558-20661cbd-204e-4cd3-b999-ab67af33d60c.png)
  <details><summary>Wazuh indexer API</summary>
  
  - Query:

  ```
  curl --insecure -XGET -u 'USER:PASS' https://localhost:9200/wazuh-alerts-4.x-*/_search?pretty -H "Content-Type:application/json" -d '{"query":{"term":{"rule.groups": "attack"}}}'
  ```
 
  - Response:

  ```
  {
  "took" : 10,
  "timed_out" : false,
  "_shards" : {
    "total" : 6,
    "successful" : 6,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 3,
      "relation" : "eq"
    },
    "max_score" : 3.5412922,
    "hits" : [
      {
        "_index" : "wazuh-alerts-4.x-2022.05.11",
        "_type" : "_doc",
        "_id" : "Av14soABu16aFzjUwrcb",
        "_score" : 3.5412922,
        "_source" : {
          "agent" : {
            "name" : "localhost.localdomain",
            "id" : "000"
          },
          "manager" : {
            "name" : "localhost.localdomain"
          },
          "data" : {
            "protocol" : "GET",
            "srcip" : "172.17.1.55",
            "id" : "200",
            "url" : "/icons/poweredby.png"
          },
          "rule" : {
            "firedtimes" : 1,
            "mail" : false,
            "level" : 10,
            "description" : "IP address found in AlienVault reputation database.",
            "groups" : [
              "attack"
            ],
            "id" : "100100"
          },
          "decoder" : {
            "name" : "web-accesslog"
          },
          "full_log" : "172.17.1.55 - - [11/May/2022:09:34:58 +0000] \"GET /icons/poweredby.png HTTP/1.1\" 200 643 \"http://172.17.1.53/\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0\"",
          "input" : {
            "type" : "log"
          },
          "@timestamp" : "2022-05-11T09:34:58.120Z",
          "location" : "/var/log/httpd/access_log",
          "id" : "1652261698.141147",
          "timestamp" : "2022-05-11T09:34:58.120+0000"
        }
      },
      {
        "_index" : "wazuh-alerts-4.x-2022.05.11",
        "_type" : "_doc",
        "_id" : "A_14soABu16aFzjUwrcb",
        "_score" : 3.1294947,
        "_source" : {
          "agent" : {
            "name" : "localhost.localdomain",
            "id" : "000"
          },
          "manager" : {
            "name" : "localhost.localdomain"
          },
          "data" : {
            "protocol" : "GET",
            "srcip" : "172.17.1.55",
            "id" : "403",
            "url" : "/"
          },
          "rule" : {
            "firedtimes" : 2,
            "mail" : false,
            "level" : 10,
            "description" : "IP address found in AlienVault reputation database.",
            "groups" : [
              "attack"
            ],
            "id" : "100100"
          },
          "decoder" : {
            "name" : "web-accesslog"
          },
          "full_log" : "172.17.1.55 - - [11/May/2022:09:34:57 +0000] \"GET / HTTP/1.1\" 403 199691 \"-\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0\"",
          "input" : {
            "type" : "log"
          },
          "@timestamp" : "2022-05-11T09:34:58.120Z",
          "location" : "/var/log/httpd/access_log",
          "id" : "1652261698.141539",
          "timestamp" : "2022-05-11T09:34:58.120+0000"
        }
      },
      {
        "_index" : "wazuh-alerts-4.x-2022.05.11",
        "_type" : "_doc",
        "_id" : "BP14soABu16aFzjUwrcb",
        "_score" : 3.1294947,
        "_source" : {
          "agent" : {
            "name" : "localhost.localdomain",
            "id" : "000"
          },
          "manager" : {
            "name" : "localhost.localdomain"
          },
          "data" : {
            "protocol" : "GET",
            "srcip" : "172.17.1.55",
            "id" : "200",
            "url" : "/poweredby.png"
          },
          "rule" : {
            "firedtimes" : 3,
            "mail" : false,
            "level" : 10,
            "description" : "IP address found in AlienVault reputation database.",
            "groups" : [
              "attack"
            ],
            "id" : "100100"
          },
          "decoder" : {
            "name" : "web-accesslog"
          },
          "full_log" : "172.17.1.55 - - [11/May/2022:09:34:58 +0000] \"GET /poweredby.png HTTP/1.1\" 200 5714 \"http://172.17.1.53/\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0\"",
          "input" : {
            "type" : "log"
          },
          "@timestamp" : "2022-05-11T09:34:58.120Z",
          "location" : "/var/log/httpd/access_log",
          "id" : "1652261698.141897",
          "timestamp" : "2022-05-11T09:34:58.120+0000"
        }
      }
    ]
   }
  }

  ```

 
  - Query:

  ```
  curl --insecure -XGET -u 'USER:PASS' https://localhost:9200/wazuh-alerts-4.x-*/_search?pretty -H "Content-Type:application/json" -d '{"query":{"term":{"rule.id": "651"}}}'
  ```
 
  - Response:

  ```
  {
  "took" : 8,
  "timed_out" : false,
  "_shards" : {
    "total" : 6,
    "successful" : 6,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 3,
      "relation" : "eq"
    },
    "max_score" : 2.0794415,
    "hits" : [
      {
        "_index" : "wazuh-alerts-4.x-2022.05.11",
        "_type" : "_doc",
        "_id" : "Bf14soABu16aFzjUwrcb",
        "_score" : 2.0794415,
        "_source" : {
          "agent" : {
            "name" : "localhost.localdomain",
            "id" : "000"
          },
          "manager" : {
            "name" : "localhost.localdomain"
          },
          "data" : {
            "origin" : {
              "module" : "wazuh-execd",
              "name" : "node01"
            },
            "version" : "1",
            "parameters" : {
              "alert" : {
                "agent" : {
                  "name" : "localhost.localdomain",
                  "id" : "000"
                },
                "manager" : {
                  "name" : "localhost.localdomain"
                },
                "data" : {
                  "protocol" : "GET",
                  "srcip" : "172.17.1.55",
                  "id" : "200",
                  "url" : "/icons/poweredby.png"
                },
                "rule" : {
                  "firedtimes" : "1",
                  "mail" : "false",
                  "level" : "10",
                  "description" : "IP address found in AlienVault reputation database.",
                  "groups" : [
                    "attack"
                  ],
                  "id" : "100100"
                },
                "location" : "/var/log/httpd/access_log",
                "id" : "1652261698.141147",
                "decoder" : {
                  "name" : "web-accesslog"
                },
                "timestamp" : "2022-05-11T09:34:58.120+0000",
                "full_log" : "172.17.1.55 - - [11/May/2022:09:34:58 +0000] \"GET /icons/poweredby.png HTTP/1.1\" 200 643 \"http://172.17.1.53/\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0\""
              },
              "extra_args" : [ ],
              "program" : "active-response/bin/firewall-drop"
            },
            "command" : "add"
          },
          "rule" : {
            "firedtimes" : 1,
            "mail" : false,
            "level" : 3,
            "pci_dss" : [
              "11.4"
            ],
            "tsc" : [
              "CC6.1",
              "CC6.8",
              "CC7.2",
              "CC7.3",
              "CC7.4"
            ],
            "description" : "Host Blocked by firewall-drop Active Response",
            "groups" : [
              "ossec",
              "active_response"
            ],
            "id" : "651",
            "nist_800_53" : [
              "SI.4"
            ],
            "gpg13" : [
              "4.13"
            ],
            "gdpr" : [
              "IV_35.7.d"
            ]
          },
          "decoder" : {
            "name" : "ar_log_json"
          },
          "full_log" : "2022/05/11 09:34:58 active-response/bin/firewall-drop: {\"version\":1,\"origin\":{\"name\":\"node01\",\"module\":\"wazuh-execd\"},\"command\":\"add\",\"parameters\":{\"extra_args\":[],\"alert\":{\"timestamp\":\"2022-05-11T09:34:58.120+0000\",\"rule\":{\"level\":10,\"description\":\"IP address found in AlienVault reputation database.\",\"id\":\"100100\",\"firedtimes\":1,\"mail\":false,\"groups\":[\"attack\"]},\"agent\":{\"id\":\"000\",\"name\":\"localhost.localdomain\"},\"manager\":{\"name\":\"localhost.localdomain\"},\"id\":\"1652261698.141147\",\"full_log\":\"172.17.1.55 - - [11/May/2022:09:34:58 +0000] \\\"GET /icons/poweredby.png HTTP/1.1\\\" 200 643 \\\"http://172.17.1.53/\\\" \\\"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0\\\"\",\"decoder\":{\"name\":\"web-accesslog\"},\"data\":{\"protocol\":\"GET\",\"srcip\":\"172.17.1.55\",\"id\":\"200\",\"url\":\"/icons/poweredby.png\"},\"location\":\"/var/log/httpd/access_log\"},\"program\":\"active-response/bin/firewall-drop\"}}",
          "input" : {
            "type" : "log"
          },
          "@timestamp" : "2022-05-11T09:34:58.690Z",
          "location" : "/var/ossec/logs/active-responses.log",
          "id" : "1652261698.142284",
          "timestamp" : "2022-05-11T09:34:58.690+0000"
        }
      },
      {
        "_index" : "wazuh-alerts-4.x-2022.05.11",
        "_type" : "_doc",
        "_id" : "Bv14soABu16aFzjUxLfu",
        "_score" : 2.0794415,
        "_source" : {
          "agent" : {
            "name" : "localhost.localdomain",
            "id" : "000"
          },
          "manager" : {
            "name" : "localhost.localdomain"
          },
          "data" : {
            "origin" : {
              "module" : "wazuh-execd",
              "name" : "node01"
            },
            "version" : "1",
            "parameters" : {
              "alert" : {
                "agent" : {
                  "name" : "localhost.localdomain",
                  "id" : "000"
                },
                "manager" : {
                  "name" : "localhost.localdomain"
                },
                "data" : {
                  "protocol" : "GET",
                  "srcip" : "172.17.1.55",
                  "id" : "403",
                  "url" : "/"
                },
                "rule" : {
                  "firedtimes" : "2",
                  "mail" : "false",
                  "level" : "10",
                  "description" : "IP address found in AlienVault reputation database.",
                  "groups" : [
                    "attack"
                  ],
                  "id" : "100100"
                },
                "location" : "/var/log/httpd/access_log",
                "id" : "1652261698.141147",
                "decoder" : {
                  "name" : "web-accesslog"
                },
                "timestamp" : "2022-05-11T09:34:58.120+0000",
                "full_log" : "172.17.1.55 - - [11/May/2022:09:34:57 +0000] \"GET / HTTP/1.1\" 403 199691 \"-\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0\""
              },
              "extra_args" : [ ],
              "program" : "active-response/bin/firewall-drop"
            },
            "command" : "add"
          },
          "rule" : {
            "firedtimes" : 2,
            "mail" : false,
            "level" : 3,
            "pci_dss" : [
              "11.4"
            ],
            "tsc" : [
              "CC6.1",
              "CC6.8",
              "CC7.2",
              "CC7.3",
              "CC7.4"
            ],
            "description" : "Host Blocked by firewall-drop Active Response",
            "groups" : [
              "ossec",
              "active_response"
            ],
            "id" : "651",
            "nist_800_53" : [
              "SI.4"
            ],
            "gpg13" : [
              "4.13"
            ],
            "gdpr" : [
              "IV_35.7.d"
            ]
          },
          "decoder" : {
            "name" : "ar_log_json"
          },
          "full_log" : "2022/05/11 09:34:58 active-response/bin/firewall-drop: {\"version\":1,\"origin\":{\"name\":\"node01\",\"module\":\"wazuh-execd\"},\"command\":\"add\",\"parameters\":{\"extra_args\":[],\"alert\":{\"timestamp\":\"2022-05-11T09:34:58.120+0000\",\"rule\":{\"level\":10,\"description\":\"IP address found in AlienVault reputation database.\",\"id\":\"100100\",\"firedtimes\":2,\"mail\":false,\"groups\":[\"attack\"]},\"agent\":{\"id\":\"000\",\"name\":\"localhost.localdomain\"},\"manager\":{\"name\":\"localhost.localdomain\"},\"id\":\"1652261698.141147\",\"full_log\":\"172.17.1.55 - - [11/May/2022:09:34:57 +0000] \\\"GET / HTTP/1.1\\\" 403 199691 \\\"-\\\" \\\"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0\\\"\",\"decoder\":{\"name\":\"web-accesslog\"},\"data\":{\"protocol\":\"GET\",\"srcip\":\"172.17.1.55\",\"id\":\"403\",\"url\":\"/\"},\"location\":\"/var/log/httpd/access_log\"},\"program\":\"active-response/bin/firewall-drop\"}}",
          "input" : {
            "type" : "log"
          },
          "@timestamp" : "2022-05-11T09:34:58.691Z",
          "location" : "/var/ossec/logs/active-responses.log",
          "id" : "1652261698.144613",
          "timestamp" : "2022-05-11T09:34:58.691+0000"
        }
      },
      {
        "_index" : "wazuh-alerts-4.x-2022.05.11",
        "_type" : "_doc",
        "_id" : "B_14soABu16aFzjUxLfu",
        "_score" : 2.0794415,
        "_source" : {
          "agent" : {
            "name" : "localhost.localdomain",
            "id" : "000"
          },
          "manager" : {
            "name" : "localhost.localdomain"
          },
          "data" : {
            "origin" : {
              "module" : "wazuh-execd",
              "name" : "node01"
            },
            "version" : "1",
            "parameters" : {
              "alert" : {
                "agent" : {
                  "name" : "localhost.localdomain",
                  "id" : "000"
                },
                "manager" : {
                  "name" : "localhost.localdomain"
                },
                "data" : {
                  "protocol" : "GET",
                  "srcip" : "172.17.1.55",
                  "id" : "200",
                  "url" : "/poweredby.png"
                },
                "rule" : {
                  "firedtimes" : "3",
                  "mail" : "false",
                  "level" : "10",
                  "description" : "IP address found in AlienVault reputation database.",
                  "groups" : [
                    "attack"
                  ],
                  "id" : "100100"
                },
                "location" : "/var/log/httpd/access_log",
                "id" : "1652261698.141897",
                "decoder" : {
                  "name" : "web-accesslog"
                },
                "timestamp" : "2022-05-11T09:34:58.120+0000",
                "full_log" : "172.17.1.55 - - [11/May/2022:09:34:58 +0000] \"GET /poweredby.png HTTP/1.1\" 200 5714 \"http://172.17.1.53/\" \"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0\""
              },
              "extra_args" : [ ],
              "program" : "active-response/bin/firewall-drop"
            },
            "command" : "add"
          },
          "rule" : {
            "firedtimes" : 3,
            "mail" : false,
            "level" : 3,
            "pci_dss" : [
              "11.4"
            ],
            "tsc" : [
              "CC6.1",
              "CC6.8",
              "CC7.2",
              "CC7.3",
              "CC7.4"
            ],
            "description" : "Host Blocked by firewall-drop Active Response",
            "groups" : [
              "ossec",
              "active_response"
            ],
            "id" : "651",
            "nist_800_53" : [
              "SI.4"
            ],
            "gpg13" : [
              "4.13"
            ],
            "gdpr" : [
              "IV_35.7.d"
            ]
          },
          "decoder" : {
            "name" : "ar_log_json"
          },
          "full_log" : "2022/05/11 09:34:58 active-response/bin/firewall-drop: {\"version\":1,\"origin\":{\"name\":\"node01\",\"module\":\"wazuh-execd\"},\"command\":\"add\",\"parameters\":{\"extra_args\":[],\"alert\":{\"timestamp\":\"2022-05-11T09:34:58.120+0000\",\"rule\":{\"level\":10,\"description\":\"IP address found in AlienVault reputation database.\",\"id\":\"100100\",\"firedtimes\":3,\"mail\":false,\"groups\":[\"attack\"]},\"agent\":{\"id\":\"000\",\"name\":\"localhost.localdomain\"},\"manager\":{\"name\":\"localhost.localdomain\"},\"id\":\"1652261698.141897\",\"full_log\":\"172.17.1.55 - - [11/May/2022:09:34:58 +0000] \\\"GET /poweredby.png HTTP/1.1\\\" 200 5714 \\\"http://172.17.1.53/\\\" \\\"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0\\\"\",\"decoder\":{\"name\":\"web-accesslog\"},\"data\":{\"protocol\":\"GET\",\"srcip\":\"172.17.1.55\",\"id\":\"200\",\"url\":\"/poweredby.png\"},\"location\":\"/var/log/httpd/access_log\"},\"program\":\"active-response/bin/firewall-drop\"}}",
          "input" : {
            "type" : "log"
          },
          "@timestamp" : "2022-05-11T09:34:58.691Z",
          "location" : "/var/ossec/logs/active-responses.log",
          "id" : "1652261698.146836",
          "timestamp" : "2022-05-11T09:34:58.691+0000"
        }
      }
    ]
   }
  }
  ```
  </details>

  <details><summary><code>alerts.json</code></summary>

  ```
  {"timestamp":"2022-05-10T14:38:36.932+0000","rule":{"level":5,"description":"File added to the system.","id":"554","firedtimes":1,"mail":false,"groups":["ossec","syscheck","syscheck_entry_added","syscheck_file"],"pci_dss":["11.5"],"gpg13":["4.11"],"gdpr":["II_5.1.f"],"hipaa":["164.312.c.1","164.312.c.2"],"nist_800_53":["SI.7"],"tsc":["PI1.4","PI1.5","CC6.1","CC6.8","CC7.2","CC7.3"]},"agent":{"id":"001","name":"centos_agent","ip":"10.0.2.15"},"manager":{"name":"localhost.localdomain"},"id":"1652193516.1016405","full_log":"File '/home/vagrant/test/test.txt' added\nMode: whodata\n","syscheck":{"path":"/home/vagrant/test/test.txt","mode":"whodata","size_after":"0","perm_after":"rw-r--r--","uid_after":"0","gid_after":"0","md5_after":"d41d8cd98f00b204e9800998ecf8427e","sha1_after":"da39a3ee5e6b4b0d3255bfef95601890afd80709","sha256_after":"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855","uname_after":"root","gname_after":"root","mtime_after":"2022-05-10T14:38:36","inode_after":25675706,"event":"added","audit":{"user":{"id":"0","name":"root"},"process":{"id":"26862","name":"/usr/bin/touch","cwd":"/home/vagrant","parent_name":"/usr/bin/bash","parent_cwd":"/home/vagrant","ppid":"3883"},"group":{"id":"0","name":"root"},"login_user":{"id":"1000","name":"vagrant"},"effective_user":{"id":"0","name":"root"}}},"decoder":{"name":"syscheck_new_entry"},"location":"syscheck"}
  {"timestamp":"2022-05-10T14:39:05.976+0000","rule":{"level":7,"description":"Integrity checksum changed.","id":"550","mitre":{"id":["T1565.001"],"tactic":["Impact"],"technique":["Stored Data Manipulation"]},"firedtimes":1,"mail":false,"groups":["ossec","syscheck","syscheck_entry_modified","syscheck_file"],"pci_dss":["11.5"],"gpg13":["4.11"],"gdpr":["II_5.1.f"],"hipaa":["164.312.c.1","164.312.c.2"],"nist_800_53":["SI.7"],"tsc":["PI1.4","PI1.5","CC6.1","CC6.8","CC7.2","CC7.3"]},"agent":{"id":"001","name":"centos_agent","ip":"10.0.2.15"},"manager":{"name":"localhost.localdomain"},"id":"1652193545.1017453","full_log":"File '/home/vagrant/test/test.txt' modified\nMode: whodata\nChanged attributes: size,mtime,md5,sha1,sha256\nSize changed from '0' to '8'\nOld modification time was: '1652193516', now it is '1652193545'\nOld md5sum was: 'd41d8cd98f00b204e9800998ecf8427e'\nNew md5sum is : 'ec4d59b2732f2f153240a8ff746282a6'\nOld sha1sum was: 'da39a3ee5e6b4b0d3255bfef95601890afd80709'\nNew sha1sum is : 'e9f9b899cc7161e1eb0b1e4c042fdfabccf7958c'\nOld sha256sum was: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'\nNew sha256sum is : '41920b348e0c6ff2ef9b7e3ee9308726aa5250fa717883e073ff6a936a9325a4'\n","syscheck":{"path":"/home/vagrant/test/test.txt","mode":"whodata","size_before":"0","size_after":"8","perm_after":"rw-r--r--","uid_after":"0","gid_after":"0","md5_before":"d41d8cd98f00b204e9800998ecf8427e","md5_after":"ec4d59b2732f2f153240a8ff746282a6","sha1_before":"da39a3ee5e6b4b0d3255bfef95601890afd80709","sha1_after":"e9f9b899cc7161e1eb0b1e4c042fdfabccf7958c","sha256_before":"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855","sha256_after":"41920b348e0c6ff2ef9b7e3ee9308726aa5250fa717883e073ff6a936a9325a4","uname_after":"root","gname_after":"root","mtime_before":"2022-05-10T14:38:36","mtime_after":"2022-05-10T14:39:05","inode_after":25675706,"changed_attributes":["size","mtime","md5","sha1","sha256"],"event":"modified","audit":{"user":{"id":"0","name":"root"},"process":{"id":"3883","name":"/usr/bin/bash","cwd":"/home/vagrant","parent_name":"/usr/bin/su","parent_cwd":"/","ppid":"3882"},"group":{"id":"0","name":"root"},"login_user":{"id":"1000","name":"vagrant"},"effective_user":{"id":"0","name":"root"}}},"decoder":{"name":"syscheck_integrity_changed"},"location":"syscheck"}
  {"timestamp":"2022-05-10T14:39:27.900+0000","rule":{"level":7,"description":"File deleted.","id":"553","mitre":{"id":["T1070.004","T1485"],"tactic":["Defense Evasion","Impact"],"technique":["File Deletion","Data Destruction"]},"firedtimes":1,"mail":false,"groups":["ossec","syscheck","syscheck_entry_deleted","syscheck_file"],"pci_dss":["11.5"],"gpg13":["4.11"],"gdpr":["II_5.1.f"],"hipaa":["164.312.c.1","164.312.c.2"],"nist_800_53":["SI.7"],"tsc":["PI1.4","PI1.5","CC6.1","CC6.8","CC7.2","CC7.3"]},"agent":{"id":"001","name":"centos_agent","ip":"10.0.2.15"},"manager":{"name":"localhost.localdomain"},"id":"1652193567.1019027","full_log":"File '/home/vagrant/test/test.txt' deleted\nMode: whodata\n","syscheck":{"path":"/home/vagrant/test/test.txt","mode":"whodata","size_after":"8","perm_after":"rw-r--r--","uid_after":"0","gid_after":"0","md5_after":"ec4d59b2732f2f153240a8ff746282a6","sha1_after":"e9f9b899cc7161e1eb0b1e4c042fdfabccf7958c","sha256_after":"41920b348e0c6ff2ef9b7e3ee9308726aa5250fa717883e073ff6a936a9325a4","uname_after":"root","gname_after":"root","mtime_after":"2022-05-10T14:39:05","inode_after":25675706,"event":"deleted","audit":{"user":{"id":"0","name":"root"},"process":{"id":"26871","name":"/usr/bin/rm","cwd":"/home/vagrant","parent_name":"/usr/bin/bash","parent_cwd":"/home/vagrant","ppid":"3883"},"group":{"id":"0","name":"root"},"login_user":{"id":"1000","name":"vagrant"},"effective_user":{"id":"0","name":"root"}}},"decoder":{"name":"syscheck_deleted"},"location":"syscheck"}
  ```

  </details>
