### ISSUE TITLE
E2E Research: Slack

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#2876]
## Description

In this issue, we will study the Slack test case described [here](https://github.com/wazuh/wazuh-automation/wiki/Wazuh-demo:-Execution-guide#slack). All the info obtained will be used in the future for the design and implementation of E2E tests.

## Tasks

- [x] ([**T1**](https://github.com/wazuh/wazuh-qa/issues/2876#issuecomment-1123745404)):  Environment provision
- [x] ([**T2**](https://github.com/wazuh/wazuh-qa/issues/2876#issuecomment-1123787613)): Test case configuration
- [x] ([**T3**](https://github.com/wazuh/wazuh-qa/issues/2876#issuecomment-1123792398)): Generate events
- [ ] ([**T4**]()): Check alerts

**Comment by juliamagan** [comment]
## Task 1: Environment provision 

I've followed the [Quickstart guide](https://documentation-dev.wazuh.com/4.3-rc/quickstart.html#installing-wazuh) and set up an all-in-one environment.

|Install type|OS|CPU|RAM|
|:--:|:--:|:--:|:--:|
|All-in-one|CentOS 8|2|4096|

**Comment by juliamagan** [comment]
## Task 2: Test case configuration

We have created an app in Slack and added the following configuration:

```
<integration>
    <name>slack</name>
    <hook_url>${replace_by_SlackHook}</hook_url>
    <level>10</level>
    <alert_format>json</alert_format>
</integration>
```

Finally, we have restarted the manager.

**Comment by juliamagan** [comment]
## Task 3: Generate event

We will receive a message in Slack when a level 10 or higher alert is triggered, so we have generated a brute force attack alert.
