### ISSUE TITLE
E2E Research: Suricata

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#2877]
## Description

In this issue, we will study the Suricata test case described [here](https://github.com/wazuh/wazuh-automation/wiki/Wazuh-demo:-Execution-guide#suricata). All the info obtained will be used in the future for the design and implementation of E2E tests.

## Tasks

- [x] ([**T1**](https://github.com/wazuh/wazuh-qa/issues/2877#issuecomment-1123922760)):  Environment provision
- [x] ([**T2**](https://github.com/wazuh/wazuh-qa/issues/2877#issuecomment-1124800812)): Test case configuration
- [x] ([**T3**](https://github.com/wazuh/wazuh-qa/issues/2877#issuecomment-1124879182)): Generate events
- [x] ([**T4**]()): Check alerts

## Conclusion

We have used a CentOS 8 manager with all-in-one and installed Suricata in it.

**Comment by juliamagan** [comment]
## Task 1: Environment provision 

I've followed the [Quickstart guide](https://documentation-dev.wazuh.com/4.3-rc/quickstart.html#installing-wazuh) and set up an all-in-one environment.

|Install type|OS|CPU|RAM|
|:--:|:--:|:--:|:--:|
|All-in-one|CentOS 8|2|4096|

**Comment by juliamagan** [comment]
## Task 2: Test case configuration

We need to install Suricata. We used a CentOS 7 machine because we couldn't install in CentOS 8 Suricata due to:

```
[root@c3 vagrant]# yum install suricata
Copr repo for suricata-6.0 owned by @oisf        23 kB/s |  26 kB     00:01    
Module yaml error: Unexpected key in data: static_context [line 9 col 3]
Module yaml error: Unexpected key in data: static_context [line 9 col 3]
Error: 
 Problem: cannot install the best candidate for the job
  - nothing provides libjansson.so.4(libjansson.so.4)(64bit) needed by suricata-1:6.0.5-2.el8.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

**Comment by juliamagan** [comment]
## Task 3: Generate events 🟢 

- Execute:

```
curl http://testmyids.com
```

**Comment by juliamagan** [comment]
## Task 4: Check alerts

- Wazuh dashboard

![image](https://user-images.githubusercontent.com/80041853/168103959-13888691-fff1-4dc7-9a4c-74763bbe7955.png)

 <details><summary>Wazuh indexer API</summary>
   
  - Query:

  ```
  curl --insecure -XGET -u 'USER:PASS' https://localhost:9200/wazuh-alerts-4.x-*/_search?pretty -H "Content-Type:application/json" -d '{"query":{"term":{"rule.groups": "suricata"}}}'
  ```
 
  - Response:

  ```
  {
  "took" : 16,
  "timed_out" : false,
  "_shards" : {
    "total" : 3,
    "successful" : 3,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 1,
      "relation" : "eq"
    },
    "max_score" : 4.0358505,
    "hits" : [
      {
        "_index" : "wazuh-alerts-4.x-2022.05.12",
        "_type" : "_doc",
        "_id" : "bHcAuIABpeEoaOazVoau",
        "_score" : 4.0358505,
        "_source" : {
          "agent" : {
            "name" : "c3",
            "id" : "000"
          },
          "manager" : {
            "name" : "c3"
          },
          "data" : {
            "tx_id" : "0",
            "app_proto" : "http",
            "in_iface" : "eth0",
            "src_ip" : "10.0.2.15",
            "src_port" : "56576",
            "event_type" : "alert",
            "alert" : {
              "severity" : "2",
              "signature_id" : "2013028",
              "rev" : "7",
              "metadata" : {
                "updated_at" : [
                  "2022_05_03"
                ],
                "created_at" : [
                  "2011_06_14"
                ]
              },
              "gid" : "1",
              "signature" : "ET POLICY curl User-Agent Outbound",
              "action" : "allowed",
              "category" : "Attempted Information Leak"
            },
            "flow_id" : "986665348815831.000000",
            "dest_ip" : "31.3.245.133",
            "proto" : "TCP",
            "http" : {
              "redirect" : "https://testmyids.com/",
              "hostname" : "testmyids.com",
              "protocol" : "HTTP/1.1",
              "http_method" : "GET",
              "http_content_type" : "text/html",
              "length" : "169",
              "url" : "/",
              "http_user_agent" : "curl/7.61.1",
              "status" : "301"
            },
            "dest_port" : "80",
            "flow" : {
              "pkts_toserver" : "4",
              "start" : "2022-05-12T11:21:04.383959+0000",
              "bytes_toclient" : "540",
              "bytes_toserver" : "313",
              "pkts_toclient" : "3"
            },
            "timestamp" : "2022-05-12T11:21:04.518350+0000"
          },
          "rule" : {
            "firedtimes" : 1,
            "mail" : false,
            "level" : 3,
            "description" : "Suricata: Alert - ET POLICY curl User-Agent Outbound",
            "groups" : [
              "ids",
              "suricata"
            ],
            "id" : "86601"
          },
          "decoder" : {
            "name" : "json"
          },
          "input" : {
            "type" : "log"
          },
          "@timestamp" : "2022-05-12T11:21:05.181Z",
          "location" : "/var/log/suricata/eve.json",
          "id" : "1652354465.506612",
          "timestamp" : "2022-05-12T11:21:05.181+0000"
        }
      }
    ]
   }
  }
  ```
  </details>

  <details><summary><code>alerts.json</code></summary>

  ```
  {"timestamp":"2022-05-12T11:21:05.181+0000","rule":{"level":3,"description":"Suricata: Alert - ET POLICY curl User-Agent Outbound","id":"86601","firedtimes":1,"mail":false,"groups":["ids","suricata"]},"agent":{"id":"000","name":"c3"},"manager":{"name":"c3"},"id":"1652354465.506612","decoder":{"name":"json"},"data":{"timestamp":"2022-05-12T11:21:04.518350+0000","flow_id":"986665348815831.000000","in_iface":"eth0","event_type":"alert","src_ip":"10.0.2.15","src_port":"56576","dest_ip":"31.3.245.133","dest_port":"80","proto":"TCP","tx_id":"0","alert":{"action":"allowed","gid":"1","signature_id":"2013028","rev":"7","signature":"ET POLICY curl User-Agent Outbound","category":"Attempted Information Leak","severity":"2","metadata":{"updated_at":["2022_05_03"],"created_at":["2011_06_14"]}},"http":{"hostname":"testmyids.com","url":"/","http_user_agent":"curl/7.61.1","http_content_type":"text/html","http_method":"GET","protocol":"HTTP/1.1","status":"301","redirect":"https://testmyids.com/","length":"169"},"app_proto":"http","flow":{"pkts_toserver":"4","pkts_toclient":"3","bytes_toserver":"313","bytes_toclient":"540","start":"2022-05-12T11:21:04.383959+0000"}},"location":"/var/log/suricata/eve.json"}
  ```

  </details>
