### ISSUE TITLE
E2E Research: Windows Defender

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#2878]
## Description

In this issue, we will study the Windows Defender test case described [here](https://github.com/wazuh/wazuh-automation/wiki/Wazuh-demo:-Execution-guide#defender). All the info obtained will be used in the future for the design and implementation of E2E tests.

## Tasks

- [x] ([**T1**](https://github.com/wazuh/wazuh-qa/issues/2878#issuecomment-1125906764)):  Environment provision
- [x] ([**T2**](https://github.com/wazuh/wazuh-qa/issues/2878#issuecomment-1125915072)): Test case configuration
- [x] ([**T3**](https://github.com/wazuh/wazuh-qa/issues/2878#issuecomment-1125934844)): Generate events
- [x] ([**T4**](https://github.com/wazuh/wazuh-qa/issues/2878#issuecomment-1125945205)): Check alerts

## Conclusion

We needed a CentOS 8 manager and a Windows agent. It is also important to add, that in order to have the same alerts as the demo environments, we have added a custom rules file.

**Comment by juliamagan** [comment]
## Task 1: Environment provision 🟢 

I've followed the [Quickstart guide](https://documentation-dev.wazuh.com/4.3-rc/quickstart.html#installing-wazuh) and set up an all-in-one environment. For the agent, we have [installed a Windows agent](https://documentation-dev.wazuh.com/4.3-rc/installation-guide/wazuh-agent/wazuh-agent-package-windows.html).

|Install type|OS|CPU|RAM|
|:--:|:--:|:--:|:--:|
|All-in-one|CentOS 8|2|4096|
|Agent|Windows|2|4096|

**Comment by juliamagan** [comment]
## Task 2: Test case configuration 🟢 

We need to add the following configuration to our Windows agent:

```
  <localfile>
    <location>Microsoft-Windows-Windows Defender/Operational</location>
    <log_format>eventchannel</log_format>
  </localfile>
```

**Comment by juliamagan** [comment]
## Task 3: Generate events 🟢 

We can generate events by disabling real-time protection. There are two ways:

1. Security settings:

![image](https://user-images.githubusercontent.com/80041853/168270463-d45ea077-8cd9-4935-9c80-e2d3116acc69.png)

2. Powershell:

```
Set-MpPreference -DisableRealtimeMonitoring 1 
```

**Comment by juliamagan** [comment]
## Task 4: Check alerts 🟢 

### Default rules:

- Wazuh dashboard:

![image](https://user-images.githubusercontent.com/80041853/168271962-708ba15b-ed6d-4a36-9b84-b281dee3bca4.png)

  <details><summary>Wazuh indexer API</summary>
  
  - Query:

  ```
  curl --insecure -XGET -u 'USER:PASS' https://localhost:9200/wazuh-alerts-4.x-*/_search?pretty -H "Content-Type:application/json" -d '{"query":{"term":{"rule.id": "62152"}}}'
  ```
 
  - Response:

  ```
  {
  "took" : 4,
  "timed_out" : false,
  "_shards" : {
    "total" : 9,
    "successful" : 9,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 2,
      "relation" : "eq"
    },
    "max_score" : 3.109061,
    "hits" : [
      {
        "_index" : "wazuh-alerts-4.x-2022.05.13",
        "_type" : "_doc",
        "_id" : "ATH9vIABbpZiSD6fKw6a",
        "_score" : 3.109061,
        "_source" : {
          "agent" : {
            "ip" : "10.0.2.15",
            "name" : "WIN-JLGVA4CR4VI",
            "id" : "002"
          },
          "manager" : {
            "name" : "localhost.localdomain"
          },
          "data" : {
            "win" : {
              "eventdata" : {
                "product Name" : "Microsoft Defender Antivirus",
                "product Version" : "4.18.2203.5"
              },
              "system" : {
                "eventID" : "5001",
                "keywords" : "0x8000000000000000",
                "providerGuid" : "{11cd958a-c507-4ef3-b3f2-5fd9dfbd2c78}",
                "level" : "4",
                "channel" : "Microsoft-Windows-Windows Defender/Operational",
                "opcode" : "0",
                "message" : "\"Microsoft Defender Antivirus Real-time Protection scanning for malware and other potentially unwanted software was disabled.\"",
                "version" : "0",
                "systemTime" : "2022-05-13T10:35:45.089114200Z",
                "eventRecordID" : "111",
                "threadID" : "3968",
                "computer" : "WIN-JLGVA4CR4VI",
                "task" : "0",
                "processID" : "2508",
                "severityValue" : "INFORMATION",
                "providerName" : "Microsoft-Windows-Windows Defender"
              }
            }
          },
          "rule" : {
            "firedtimes" : 1,
            "mail" : false,
            "level" : 5,
            "pci_dss" : [
              "5.1",
              "10.2.6",
              "10.6.1"
            ],
            "hipaa" : [
              "164.312.b"
            ],
            "tsc" : [
              "A1.2",
              "CC6.8",
              "CC7.2",
              "CC7.3"
            ],
            "description" : "Windows Defender: Antivirus real-time protection is disabled",
            "groups" : [
              "windows",
              "windows_defender"
            ],
            "id" : "62152",
            "nist_800_53" : [
              "SI.3",
              "AU.14",
              "AU.5",
              "AU.6"
            ],
            "gpg13" : [
              "4.14",
              "10.1"
            ],
            "gdpr" : [
              "IV_35.7.d"
            ]
          },
          "decoder" : {
            "name" : "windows_eventchannel"
          },
          "input" : {
            "type" : "log"
          },
          "@timestamp" : "2022-05-13T10:35:45.881Z",
          "location" : "EventChannel",
          "id" : "1652438145.148206",
          "timestamp" : "2022-05-13T10:35:45.881+0000"
        }
      },
      {
        "_index" : "wazuh-alerts-4.x-2022.05.13",
        "_type" : "_doc",
        "_id" : "2jgfvYABSHboxrt5LJ9C",
        "_score" : 3.109061,
        "_source" : {
          "agent" : {
            "ip" : "10.0.2.15",
            "name" : "WIN-JLGVA4CR4VI",
            "id" : "002"
          },
          "manager" : {
            "name" : "localhost.localdomain"
          },
          "data" : {
            "win" : {
              "eventdata" : {
                "product Name" : "Microsoft Defender Antivirus",
                "product Version" : "4.18.2203.5"
              },
              "system" : {
                "eventID" : "5001",
                "keywords" : "0x8000000000000000",
                "providerGuid" : "{11cd958a-c507-4ef3-b3f2-5fd9dfbd2c78}",
                "level" : "4",
                "channel" : "Microsoft-Windows-Windows Defender/Operational",
                "opcode" : "0",
                "message" : "\"Microsoft Defender Antivirus Real-time Protection scanning for malware and other potentially unwanted software was disabled.\"",
                "version" : "0",
                "systemTime" : "2022-05-13T11:12:49.114795700Z",
                "eventRecordID" : "123",
                "threadID" : "5588",
                "computer" : "WIN-JLGVA4CR4VI",
                "task" : "0",
                "processID" : "2508",
                "severityValue" : "INFORMATION",
                "providerName" : "Microsoft-Windows-Windows Defender"
              }
            }
          },
          "rule" : {
            "firedtimes" : 1,
            "mail" : false,
            "level" : 5,
            "pci_dss" : [
              "5.1",
              "10.2.6",
              "10.6.1"
            ],
            "hipaa" : [
              "164.312.b"
            ],
            "tsc" : [
              "A1.2",
              "CC6.8",
              "CC7.2",
              "CC7.3"
            ],
            "description" : "Windows Defender: Antivirus real-time protection is disabled",
            "groups" : [
              "windows",
              "windows_defender"
            ],
            "id" : "62152",
            "nist_800_53" : [
              "SI.3",
              "AU.14",
              "AU.5",
              "AU.6"
            ],
            "gpg13" : [
              "4.14",
              "10.1"
            ],
            "gdpr" : [
              "IV_35.7.d"
            ]
          },
          "decoder" : {
            "name" : "windows_eventchannel"
          },
          "input" : {
            "type" : "log"
          },
          "@timestamp" : "2022-05-13T11:12:49.897Z",
          "location" : "EventChannel",
          "id" : "1652440369.198619",
          "timestamp" : "2022-05-13T11:12:49.897+0000"
        }
      }
    ]
   }
  }
  ```
  </details>

  <details><summary><code>alerts.json</code></summary>

  ```
  {"timestamp":"2022-05-13T10:35:45.881+0000","rule":{"level":5,"description":"Windows Defender: Antivirus real-time protection is disabled","id":"62152","firedtimes":1,"mail":false,"groups":["windows","windows_defender"],"pci_dss":["5.1","10.2.6","10.6.1"],"gpg13":["4.14","10.1"],"gdpr":["IV_35.7.d"],"hipaa":["164.312.b"],"nist_800_53":["SI.3","AU.14","AU.5","AU.6"],"tsc":["A1.2","CC6.8","CC7.2","CC7.3"]},"agent":{"id":"002","name":"WIN-JLGVA4CR4VI","ip":"10.0.2.15"},"manager":{"name":"localhost.localdomain"},"id":"1652438145.148206","decoder":{"name":"windows_eventchannel"},"data":{"win":{"system":{"providerName":"Microsoft-Windows-Windows Defender","providerGuid":"{11cd958a-c507-4ef3-b3f2-5fd9dfbd2c78}","eventID":"5001","version":"0","level":"4","task":"0","opcode":"0","keywords":"0x8000000000000000","systemTime":"2022-05-13T10:35:45.089114200Z","eventRecordID":"111","processID":"2508","threadID":"3968","channel":"Microsoft-Windows-Windows Defender/Operational","computer":"WIN-JLGVA4CR4VI","severityValue":"INFORMATION","message":"\"Microsoft Defender Antivirus Real-time Protection scanning for malware and other potentially unwanted software was disabled.\""},"eventdata":{"product Name":"Microsoft Defender Antivirus","product Version":"4.18.2203.5"}}},"location":"EventChannel"}
  {"timestamp":"2022-05-13T11:12:49.897+0000","rule":{"level":5,"description":"Windows Defender: Antivirus real-time protection is disabled","id":"62152","firedtimes":1,"mail":false,"groups":["windows","windows_defender"],"pci_dss":["5.1","10.2.6","10.6.1"],"gpg13":["4.14","10.1"],"gdpr":["IV_35.7.d"],"hipaa":["164.312.b"],"nist_800_53":["SI.3","AU.14","AU.5","AU.6"],"tsc":["A1.2","CC6.8","CC7.2","CC7.3"]},"agent":{"id":"002","name":"WIN-JLGVA4CR4VI","ip":"10.0.2.15"},"manager":{"name":"localhost.localdomain"},"id":"1652440369.198619","decoder":{"name":"windows_eventchannel"},"data":{"win":{"system":{"providerName":"Microsoft-Windows-Windows Defender","providerGuid":"{11cd958a-c507-4ef3-b3f2-5fd9dfbd2c78}","eventID":"5001","version":"0","level":"4","task":"0","opcode":"0","keywords":"0x8000000000000000","systemTime":"2022-05-13T11:12:49.114795700Z","eventRecordID":"123","processID":"2508","threadID":"5588","channel":"Microsoft-Windows-Windows Defender/Operational","computer":"WIN-JLGVA4CR4VI","severityValue":"INFORMATION","message":"\"Microsoft Defender Antivirus Real-time Protection scanning for malware and other potentially unwanted software was disabled.\""},"eventdata":{"product Name":"Microsoft Defender Antivirus","product Version":"4.18.2203.5"}}},"location":"EventChannel"}
  ```

  </details>

### Demo rules:

- Wazuh dashboard:

![image](https://user-images.githubusercontent.com/80041853/168270985-bb7b3678-ac00-4d05-acbf-47293e3b96f5.png)


  <details><summary>Wazuh indexer API</summary>
  
  - Query:

  ```
  curl --insecure -XGET -u 'USER:PASS' https://localhost:9200/wazuh-alerts-4.x-*/_search?pretty -H "Content-Type:application/json" -d '{"query":{"term":{"rule.id": "255303"}}}'
  ```
 
  - Response:

  ```
  {
  "took" : 15,
  "timed_out" : false,
  "_shards" : {
    "total" : 9,
    "successful" : 9,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 1,
      "relation" : "eq"
    },
    "max_score" : 3.4863553,
    "hits" : [
      {
        "_index" : "wazuh-alerts-4.x-2022.05.13",
        "_type" : "_doc",
        "_id" : "yjgRvYABSHboxrt5MJ9p",
        "_score" : 3.4863553,
        "_source" : {
          "agent" : {
            "ip" : "10.0.2.15",
            "name" : "WIN-JLGVA4CR4VI",
            "id" : "002"
          },
          "manager" : {
            "name" : "localhost.localdomain"
          },
          "data" : {
            "win" : {
              "eventdata" : {
                "product Name" : "Microsoft Defender Antivirus",
                "product Version" : "4.18.2203.5"
              },
              "system" : {
                "eventID" : "5001",
                "keywords" : "0x8000000000000000",
                "providerGuid" : "{11cd958a-c507-4ef3-b3f2-5fd9dfbd2c78}",
                "level" : "4",
                "channel" : "Microsoft-Windows-Windows Defender/Operational",
                "opcode" : "0",
                "message" : "\"Microsoft Defender Antivirus Real-time Protection scanning for malware and other potentially unwanted software was disabled.\"",
                "version" : "0",
                "systemTime" : "2022-05-13T10:57:33.892162800Z",
                "eventRecordID" : "117",
                "threadID" : "3968",
                "computer" : "WIN-JLGVA4CR4VI",
                "task" : "0",
                "processID" : "2508",
                "severityValue" : "INFORMATION",
                "providerName" : "Microsoft-Windows-Windows Defender"
              }
            }
          },
          "rule" : {
            "firedtimes" : 1,
            "mail" : true,
            "level" : 12,
            "description" : "Windows Defender Real-time Protection was disabled.",
            "groups" : [
              "Defense Evasion",
              "Windows Defenderdefender",
              "attack.t1089"
            ],
            "id" : "255303"
          },
          "decoder" : {
            "name" : "windows_eventchannel"
          },
          "full_log" : "{\"win\":{\"system\":{\"providerName\":\"Microsoft-Windows-Windows Defender\",\"providerGuid\":\"{11cd958a-c507-4ef3-b3f2-5fd9dfbd2c78}\",\"eventID\":\"5001\",\"version\":\"0\",\"level\":\"4\",\"task\":\"0\",\"opcode\":\"0\",\"keywords\":\"0x8000000000000000\",\"systemTime\":\"2022-05-13T10:57:33.892162800Z\",\"eventRecordID\":\"117\",\"processID\":\"2508\",\"threadID\":\"3968\",\"channel\":\"Microsoft-Windows-Windows Defender/Operational\",\"computer\":\"WIN-JLGVA4CR4VI\",\"severityValue\":\"INFORMATION\",\"message\":\"\\\"Microsoft Defender Antivirus Real-time Protection scanning for malware and other potentially unwanted software was disabled.\\\"\"},\"eventdata\":{\"product Name\":\"Microsoft Defender Antivirus\",\"product Version\":\"4.18.2203.5\"}}}",
          "input" : {
            "type" : "log"
          },
          "@timestamp" : "2022-05-13T10:57:34.674Z",
          "location" : "EventChannel",
          "id" : "1652439454.183894",
          "timestamp" : "2022-05-13T10:57:34.674+0000"
        }
      }
    ]
   }
  }

  ```
  </details>

  <details><summary><code>alerts.json</code></summary>

  ```
  {"timestamp":"2022-05-13T10:57:34.674+0000","rule":{"level":12,"description":"Windows Defender Real-time Protection was disabled.","id":"255303","firedtimes":1,"mail":true,"groups":["Defense Evasion","Windows Defenderdefender","attack.t1089"]},"agent":{"id":"002","name":"WIN-JLGVA4CR4VI","ip":"10.0.2.15"},"manager":{"name":"localhost.localdomain"},"id":"1652439454.183894","full_log":"{\"win\":{\"system\":{\"providerName\":\"Microsoft-Windows-Windows Defender\",\"providerGuid\":\"{11cd958a-c507-4ef3-b3f2-5fd9dfbd2c78}\",\"eventID\":\"5001\",\"version\":\"0\",\"level\":\"4\",\"task\":\"0\",\"opcode\":\"0\",\"keywords\":\"0x8000000000000000\",\"systemTime\":\"2022-05-13T10:57:33.892162800Z\",\"eventRecordID\":\"117\",\"processID\":\"2508\",\"threadID\":\"3968\",\"channel\":\"Microsoft-Windows-Windows Defender/Operational\",\"computer\":\"WIN-JLGVA4CR4VI\",\"severityValue\":\"INFORMATION\",\"message\":\"\\\"Microsoft Defender Antivirus Real-time Protection scanning for malware and other potentially unwanted software was disabled.\\\"\"},\"eventdata\":{\"product Name\":\"Microsoft Defender Antivirus\",\"product Version\":\"4.18.2203.5\"}}}","decoder":{"name":"windows_eventchannel"},"data":{"win":{"system":{"providerName":"Microsoft-Windows-Windows Defender","providerGuid":"{11cd958a-c507-4ef3-b3f2-5fd9dfbd2c78}","eventID":"5001","version":"0","level":"4","task":"0","opcode":"0","keywords":"0x8000000000000000","systemTime":"2022-05-13T10:57:33.892162800Z","eventRecordID":"117","processID":"2508","threadID":"3968","channel":"Microsoft-Windows-Windows Defender/Operational","computer":"WIN-JLGVA4CR4VI","severityValue":"INFORMATION","message":"\"Microsoft Defender Antivirus Real-time Protection scanning for malware and other potentially unwanted software was disabled.\""},"eventdata":{"product Name":"Microsoft Defender Antivirus","product Version":"4.18.2203.5"}}},"location":"EventChannel"}
  ```

  </details>
