### ISSUE TITLE
E2E design and implementation: Osquery

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#2887]
## Description

The test research was accomplished in [this issue](https://github.com/wazuh/wazuh-qa/issues/2854). So, in this issue, we will design and develop the E2E test to cover those use cases.

## Tasks

- [x] (**[T1](https://github.com/wazuh/wazuh-qa/issues/2887#issuecomment-1154548489)**) Design the test
- [x] (**[T2](https://github.com/wazuh/wazuh-qa/issues/2887#issuecomment-1164791760)**) Implement the test locally
- [ ] Refactor the test for it to work in the test environment

## Conclusion

The added module tests the integration with Osquery. Only [one test case](https://github.com/wazuh/wazuh-qa/issues/2854#issuecomment-1116320020) was developed at this stage with the aim of implementing the first iteration of the end-to-end test.

The only precondition to run: Create an inventory as follows
```
all:
  hosts:
    wazuh-manager:
      ansible_connection: ssh
      ansible_user: <VM USER>
      ansible_ssh_private_key_file: <PRIVATE KEY PATH>
      ansible_python_interpreter: <PYTHON INTERPRETER PATH>
      dashboard_user: <USER>
      dashboard_password: <PASS>
```

Execute the test:

<code>
python -m pytest tests/end_to_end/TEST-PATH --inventory_path PATH-TO-INVENTORY
</code>

### Test execution

||Results|
|:--:|:--:|
|R1| [🟢 ](https://github.com/wazuh/wazuh-qa/files/8976594/r1.zip)
|R2| [🟢 ](https://github.com/wazuh/wazuh-qa/files/8976595/r2-CentOS-manager-2948.zip)
|R3| [🟢 ](https://github.com/wazuh/wazuh-qa/files/8976596/r3-CentOS-manager-2948.zip)

**Comment by mauromalara** [comment]
## Design

![image](https://user-images.githubusercontent.com/39094716/173462250-02f1131d-08e0-437f-8977-94e2978c581a.png)

### General steps
- Generate the test cases (config, metadata, and ids) using the YAML's inside the `test_cases` folder
- Configure the environment using a pytest fixture from the `end_to_end` test suite
  - Run each playbook defined in the test module using the inventory passed by parameter to the `pytest` library
- Get the dashboard credentials using the fixture from the `end_to_end` test suite
- Generate the events using a playbook from the `playbooks` folder
- Get the alerts (if they were generated) from the wazuh-indexer API
- Check if the expected alert matched one of the alerts obtained from the API
  - If an exception is raised, check if the alert at least is found in the log file
    - If not, raise a TimeoutError
    - If yes, raise the previously captured exception (AssertionError)

**Comment by mauromalara** [comment]
## Task 2: Test development 🔵 

|Development branch|Pull Request|
|--|--
|[2887-e2e-test-osquery](https://github.com/wazuh/wazuh-qa/tree/2887-e2e-test-osquery)|#3012|
