### ISSUE TITLE
Release 4.3.1-RC1 - Manual tests: Demo environment

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#2892]
The following issue aims to run the specified test for the current release candidate, report the results, and open new issues for any encountered errors.

## Test information
|                         |                                            |
|-------------------------|--------------------------------------------|
| **Test name**           |Demo environment|
| **Category**            |Wazuh App|
| **Deployment option**   |Demo environment|
| **Main release issue**  |https://github.com/wazuh/wazuh/issues/13448|
| **Release candidate #** |RC1| 

## Test tasks
- [x]  ([**T1**](https://github.com/wazuh/wazuh-qa/issues/2892#issuecomment-1127849456)): - No errors or warnings found in logs
- [x]  ([**T2**](https://github.com/wazuh/wazuh-qa/issues/2892#issuecomment-1128943916)): - The daemons are running with the correct user
- [x]  ([**T3**](https://github.com/wazuh/wazuh-qa/issues/2892#issuecomment-1128947171)): - The status of the Wazuh Indexer clusters is as expected.
- [x]  ([**T4**](https://github.com/wazuh/wazuh-qa/issues/2892#issuecomment-1128986012)): - No errors in the browser's developer console when browsing the App
- [x]  ([**T5**](https://github.com/wazuh/wazuh-qa/issues/2892#issuecomment-1129012169)): - Alerts are being generated for each of the modules configured for this purpose.
- [x]  ([**T6**](https://github.com/wazuh/wazuh-qa/issues/2892#issuecomment-1129017844)): - No warning symbols in Discover when expanding a document.

## Conclusion 🟡    

The behavior is the same as in the [last test performed](https://github.com/wazuh/wazuh-qa/issues/2856). All the problems encountered have been reported previously. You can see the issues reported in the previous tests:

- #2795 
- #2819 
- #2856 

## Auditors validation

The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [ ] @jmv74211 
- [x] @alberpilot 
- [ ] @gdiazlo

**Comment by juliamagan** [comment]
## Task 1: No errors or warnings found in logs

### Agents

<details>
<summary>Amazon Linux  🟡  </summary>

- `journalctl -xe -u wazuh-agent.service`:

```
may 16 12:42:15 ip-10-0-1-206.us-west-1.compute.internal env[15167]: Wazuh v4.3.1 Stopped
may 16 12:42:15 ip-10-0-1-206.us-west-1.compute.internal systemd[1]: Starting Wazuh agent...
-- Subject: Unit wazuh-agent.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit wazuh-agent.service has begun starting up.
may 16 12:42:15 ip-10-0-1-206.us-west-1.compute.internal env[15231]: Starting Wazuh v4.3.1...
may 16 12:42:15 ip-10-0-1-206.us-west-1.compute.internal env[15231]: Started wazuh-execd...
may 16 12:42:16 ip-10-0-1-206.us-west-1.compute.internal env[15231]: Started wazuh-agentd...
may 16 12:42:17 ip-10-0-1-206.us-west-1.compute.internal env[15231]: Started wazuh-syscheckd...
may 16 12:42:18 ip-10-0-1-206.us-west-1.compute.internal env[15231]: Started wazuh-logcollector...
may 16 12:42:18 ip-10-0-1-206.us-west-1.compute.internal crontab[15394]: (root) LIST (root)
may 16 12:42:19 ip-10-0-1-206.us-west-1.compute.internal env[15231]: Started wazuh-modulesd...
may 16 12:42:21 ip-10-0-1-206.us-west-1.compute.internal env[15231]: Completed.
may 16 12:42:21 ip-10-0-1-206.us-west-1.compute.internal systemd[1]: Started Wazuh agent.
-- Subject: Unit wazuh-agent.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit wazuh-agent.service has finished starting up.
-- 
-- The start-up result is done.

```

- `egrep -i "ERROR|WARNING" /var/ossec/logs/ossec.log`:

```
2022/05/16 15:55:51 wazuh-logcollector: WARNING: (1958): Log file '/var/log/messages' is duplicated.
2022/05/16 15:55:51 wazuh-logcollector: WARNING: (1958): Log file '/var/log/secure' is duplicated.
2022/05/16 15:55:51 wazuh-logcollector: WARNING: (1958): Log file '/var/log/maillog' is duplicated.
```

- `systemctl status wazuh-agent -l`:

```
[root@ip-10-0-1-206 wazuh-user]# systemctl status wazuh-agent -l
● wazuh-agent.service - Wazuh agent
   Loaded: loaded (/usr/lib/systemd/system/wazuh-agent.service; enabled; vendor preset: disabled)
   Active: active (running) since lun 2022-05-16 15:55:55 UTC; 33s ago
  Process: 13315 ExecStop=/usr/bin/env /var/ossec/bin/wazuh-control stop (code=exited, status=0/SUCCESS)
  Process: 13380 ExecStart=/usr/bin/env /var/ossec/bin/wazuh-control start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/wazuh-agent.service
           ├─13409 /var/ossec/bin/wazuh-execd
           ├─13421 /var/ossec/bin/wazuh-agentd
           ├─13436 /var/ossec/bin/wazuh-syscheckd
           ├─13450 /var/ossec/bin/wazuh-logcollector
           └─13472 /var/ossec/bin/wazuh-modulesd

may 16 15:55:47 ip-10-0-1-206.us-west-1.compute.internal systemd[1]: Starting Wazuh agent...
may 16 15:55:47 ip-10-0-1-206.us-west-1.compute.internal env[13380]: Starting Wazuh v4.3.1...
may 16 15:55:48 ip-10-0-1-206.us-west-1.compute.internal env[13380]: Started wazuh-execd...
may 16 15:55:50 ip-10-0-1-206.us-west-1.compute.internal env[13380]: Started wazuh-agentd...
may 16 15:55:51 ip-10-0-1-206.us-west-1.compute.internal env[13380]: Started wazuh-syscheckd...
may 16 15:55:52 ip-10-0-1-206.us-west-1.compute.internal env[13380]: Started wazuh-logcollector...
may 16 15:55:53 ip-10-0-1-206.us-west-1.compute.internal env[13380]: Started wazuh-modulesd...
may 16 15:55:55 ip-10-0-1-206.us-west-1.compute.internal env[13380]: Completed.
may 16 15:55:55 ip-10-0-1-206.us-west-1.compute.internal systemd[1]: Started Wazuh agent.
```

- `/var/ossec/bin/wazuh-control status`:

```
[root@ip-10-0-1-206 wazuh-user]# /var/ossec/bin/wazuh-control status
wazuh-modulesd is running...
wazuh-logcollector is running...
wazuh-syscheckd is running...
wazuh-agentd is running...
wazuh-execd is running...
```


</details>

**Comment by juliamagan** [comment]
## Task 2: The daemons are running with the correct user

### Agents

<details>
<summary>Amazon Linux  🟢 </summary>

```
root     13409  0.0  0.2  37708  2880 ?        Sl   may16   0:01 /var/ossec/bin/wazuh-execd
wazuh    13421  0.0  0.5 263692  5532 ?        Sl   may16   0:15 /var/ossec/bin/wazuh-agentd
root     13436  0.0  0.8 203832  8480 ?        SNl  may16   0:20 /var/ossec/bin/wazuh-syscheckd
root     13450  0.0  0.4 480236  4728 ?        Sl   may16   0:06 /var/ossec/bin/wazuh-logcollector
root     13472  0.0  1.7 740780 17028 ?        Sl   may16   0:10 /var/ossec/bin/wazuh-modulesd
```


</details>

<details>
<summary>RHEL 🟢</summary>

```
root     24503  0.0  0.0  35524  1628 ?        Sl   may16   0:03 /var/ossec/bin/wazuh-execd
wazuh    24515  0.0  0.1 261256  5376 ?        Sl   may16   1:15 /var/ossec/bin/wazuh-agentd
root     24530  0.0  0.1 480508  7288 ?        SNl  may16   1:02 /var/ossec/bin/wazuh-syscheckd
root     24543  0.0  0.0 477940  2716 ?        Sl   may16   0:29 /var/ossec/bin/wazuh-logcollector
root     24567  0.0  0.9 1033464 36744 ?       Sl   may16   0:35 /var/ossec/bin/wazuh-modulesd
```

</details>

<details>
<summary>Ubuntu 🟢 </summary>

```
root     11537  0.0  0.3  42728  3024 ?        Sl   May16   0:01 /var/ossec/bin/wazuh-execd
wazuh    11548  0.0  0.5 268668  5320 ?        Sl   May16   0:14 /var/ossec/bin/wazuh-agentd
root     11562  0.0  0.7 208168  7508 ?        SNl  May16   0:18 /var/ossec/bin/wazuh-syscheckd
root     11578  0.0  0.4 485124  4224 ?        Sl   May16   0:06 /var/ossec/bin/wazuh-logcollector
root     11619  0.0  1.6 748316 15932 ?        Sl   May16   0:11 /var/ossec/bin/wazuh-modulesd
```


</details>

<details>
<summary>Centos 🟢 </summary>

```
root     19237  0.0  0.1  35436  1464 ?        Sl   08:41   0:00 /var/ossec/bin/wazuh-execd
wazuh    19249  0.0  0.5 261260  5096 ?        Sl   08:42   0:11 /var/ossec/bin/wazuh-agentd
root     19264  0.0  0.5 201152  5172 ?        SNl  08:42   0:11 /var/ossec/bin/wazuh-syscheckd
root     19278  0.0  0.2 477812  2384 ?        Sl   08:42   0:03 /var/ossec/bin/wazuh-logcollector
root     19300  0.0  2.4 738416 24040 ?        Sl   08:42   0:04 /var/ossec/bin/wazuh-modulesd
```


</details>

<details>
<summary>Debian 🟢 </summary>

```
root     10191  0.0  0.2  41412  2716 ?        Sl   08:53   0:00 /var/ossec/bin/wazuh-execd
wazuh    10202  0.0  0.5 267436  5152 ?        Sl   08:54   0:03 /var/ossec/bin/wazuh-agentd
root     10216  0.0  0.7 272216  7336 ?        SNl  08:54   0:06 /var/ossec/bin/wazuh-syscheckd
root     10235  0.0  0.4 484056  4248 ?        Sl   08:54   0:01 /var/ossec/bin/wazuh-logcollector
root     10264  0.0  1.2 744888 12124 ?        Sl   08:54   0:02 /var/ossec/bin/wazuh-modulesd
```


</details>

<details>
<summary>Windows  🟢</summary>

```
wazuh-agent.exe               6236 WazuhSvc
```


</details>

### Managers

<details>
<summary>Master env 1 🟢 </summary>

```
wazuh     4633  0.1  2.7 830060 109972 ?       Sl   11:36   0:19 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
wazuh     4656  0.0  0.1  38436  4176 ?        Sl   11:36   0:00 /var/ossec/bin/wazuh-integratord
root      4678  0.2  0.1 194168  5832 ?        Sl   11:36   0:27 /var/ossec/bin/wazuh-authd
wazuh     4695  0.1  0.5 775172 22720 ?        Sl   11:36   0:11 /var/ossec/bin/wazuh-db
wazuh     4707  0.0  1.5 317508 61928 ?        S    11:36   0:00 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
wazuh     4710  0.0  1.5 465404 63496 ?        S    11:36   0:09 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
root      4725  0.0  0.0  38480  3204 ?        Sl   11:36   0:00 /var/ossec/bin/wazuh-execd
wazuh     4740  0.4  2.2 1292720 88740 ?       Sl   11:36   0:41 /var/ossec/bin/wazuh-analysisd
root      4752  0.1  0.2 269760  8516 ?        SNl  11:36   0:12 /var/ossec/bin/wazuh-syscheckd
wazuh     4772  0.5  0.1 1178436 7880 ?        Sl   11:36   0:56 /var/ossec/bin/wazuh-remoted
root      4805  0.0  0.1 480876  5060 ?        Sl   11:36   0:01 /var/ossec/bin/wazuh-logcollector
wazuh     4828  0.0  0.0  38452  3148 ?        Sl   11:36   0:00 /var/ossec/bin/wazuh-monitord
root      4876  7.2  4.6 1301148 184780 ?      Sl   11:36  12:05 /var/ossec/bin/wazuh-modulesd
wazuh     5004  0.1  1.5 444432 60304 ?        Sl   11:36   0:10 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh-clusterd.py
wazuh     5006  0.0  1.0 279736 43324 ?        S    11:36   0:06 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh-clusterd.py
wazuh     5009  0.0  1.0 361664 43000 ?        S    11:36   0:05 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh-clusterd.py
```


</details>

<details>
<summary>Worker env 1 🟢</summary>

```
wazuh      930  0.0  1.0 440052 43532 ?        S    11:45   0:00 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh-clusterd.py
wazuh    32094  0.1  2.3 740904 95024 ?        Sl   11:42   0:11 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
wazuh    32120  0.0  0.0  38440  3408 ?        Sl   11:42   0:00 /var/ossec/bin/wazuh-integratord
wazuh    32137  0.0  0.3 775156 14484 ?        Sl   11:42   0:07 /var/ossec/bin/wazuh-db
root     32161  0.0  0.0  38480  3200 ?        Sl   11:42   0:00 /var/ossec/bin/wazuh-execd
wazuh    32163  0.0  1.4 309300 57300 ?        S    11:42   0:00 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
wazuh    32166  0.0  1.4 463956 59784 ?        S    11:42   0:00 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
wazuh    32182  0.0  0.7 1292580 28844 ?       Sl   11:42   0:02 /var/ossec/bin/wazuh-analysisd
root     32194  0.1  0.2 204124  8488 ?        SNl  11:43   0:11 /var/ossec/bin/wazuh-syscheckd
wazuh    32214  0.1  0.1 522996  4732 ?        Sl   11:43   0:14 /var/ossec/bin/wazuh-remoted
root     32247  0.0  0.1 480868  4952 ?        Sl   11:43   0:01 /var/ossec/bin/wazuh-logcollector
wazuh    32267  0.0  0.0  38452  3180 ?        Sl   11:43   0:00 /var/ossec/bin/wazuh-monitord
root     32318  1.9  4.5 1079868 181024 ?      Sl   11:43   3:13 /var/ossec/bin/wazuh-modulesd
wazuh    32443  0.1  1.4 590496 59228 ?        Sl   11:43   0:09 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh-clusterd.py
wazuh    32661  0.0  1.1 287436 45572 ?        S    11:43   0:03 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh-clusterd.py

```
</details>
<details>
<summary>Master env 2  🟢</summary>

```
wazuh     2793  0.1  2.5 820584 100104 ?       Sl   11:54   0:14 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
wazuh     2818  0.0  0.0  38440  3352 ?        Sl   11:54   0:00 /var/ossec/bin/wazuh-integratord
root      2838  0.2  0.1 194168  5820 ?        Sl   11:54   0:24 /var/ossec/bin/wazuh-authd
wazuh     2855  0.0  0.3 709632 14180 ?        Sl   11:54   0:07 /var/ossec/bin/wazuh-db
wazuh     2867  0.0  1.5 317580 61880 ?        S    11:54   0:00 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
wazuh     2870  0.0  1.5 465388 63492 ?        S    11:54   0:06 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
root      2885  0.0  0.0  38476  3244 ?        Sl   11:54   0:00 /var/ossec/bin/wazuh-execd
wazuh     2900  0.0  2.2 1292612 89992 ?       Sl   11:54   0:07 /var/ossec/bin/wazuh-analysisd
root      2912  0.1  0.2 269768  8504 ?        SNl  11:54   0:11 /var/ossec/bin/wazuh-syscheckd
wazuh     2933  0.1  0.1 1178432 6800 ?        Sl   11:54   0:13 /var/ossec/bin/wazuh-remoted
root      2965  0.0  0.1 480880  5180 ?        Sl   11:54   0:00 /var/ossec/bin/wazuh-logcollector
wazuh     2984  0.0  0.0  38452  3200 ?        Sl   11:54   0:00 /var/ossec/bin/wazuh-monitord
root      3035  2.4  5.3 1335788 215332 ?      Sl   11:54   3:39 /var/ossec/bin/wazuh-modulesd
wazuh     3176  0.0  1.1 427684 45784 ?        Sl   11:54   0:02 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh-clusterd.py
wazuh     3184  0.0  1.0 279668 42880 ?        S    11:54   0:02 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh-clusterd.py
wazuh     3187  0.0  1.0 361596 42300 ?        S    11:54   0:02 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh-clusterd.py
```


</details>


### Wazuh Indexer

<details>
<summary>Bootstrap  🟢</summary>

```
wazuh-i+ 20887  3.7 56.6 7319612 4578728 ?     Ssl  12:01   5:29 /usr/share/wazuh-indexer/jdk/bin/java -Xshare:auto -Dopensearch.networkaddress.cache.ttl=60 -Dopensearch.networkaddress.cache.negative.ttl=10 -XX:+AlwaysPreTouch -Xss1m -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djna.nosys=true -XX:-OmitStackTraceInFastThrow -XX:+ShowCodeDetailsInExceptionMessages -Dio.netty.noUnsafe=true -Dio.netty.noKeySetOptimization=true -Dio.netty.recycler.maxCapacityPerThread=0 -Dio.netty.allocator.numDirectArenas=0 -Dlog4j.shutdownHookEnabled=false -Dlog4j2.disable.jmx=true -Djava.locale.providers=SPI,COMPAT -Xms3948m -Xmx3948m -XX:+UseG1GC -XX:G1ReservePercent=25 -XX:InitiatingHeapOccupancyPercent=30 -Djava.io.tmpdir=/tmp/opensearch-1636768103364031185 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=data -XX:ErrorFile=/var/log/wazuh-indexer/hs_err_pid%p.log -Xlog:gc*,gc+age=trace,safepoint:file=/var/log/wazuh-indexer/gc.log:utctime,pid,tags:filecount=32,filesize=64m -Dclk.tck=100 -Djdk.attach.allowAttachSelf=true -Djava.security.policy=file:///usr/share/wazuh-indexer/plugins/opensearch-performance-analyzer/pa_config/opensearch_security.policy -XX:MaxDirectMemorySize=2069889024 -Dopensearch.path.home=/usr/share/wazuh-indexer -Dopensearch.path.conf=/etc/wazuh-indexer -Dopensearch.distribution.type=rpm -Dopensearch.bundled_jdk=true -cp /usr/share/wazuh-indexer/lib/* org.opensearch.bootstrap.OpenSearch -p /run/wazuh-indexer/wazuh-indexer.pid --quiet
```

</details>


<details>
<summary>Master B  🟢</summary>

```
wazuh-i+ 20377  4.5 56.7 7284160 4588408 ?     Ssl  12:08   6:23 /usr/share/wazuh-indexer/jdk/bin/java -Xshare:auto -Dopensearch.networkaddress.cache.ttl=60 -Dopensearch.networkaddress.cache.negative.ttl=10 -XX:+AlwaysPreTouch -Xss1m -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djna.nosys=true -XX:-OmitStackTraceInFastThrow -XX:+ShowCodeDetailsInExceptionMessages -Dio.netty.noUnsafe=true -Dio.netty.noKeySetOptimization=true -Dio.netty.recycler.maxCapacityPerThread=0 -Dio.netty.allocator.numDirectArenas=0 -Dlog4j.shutdownHookEnabled=false -Dlog4j2.disable.jmx=true -Djava.locale.providers=SPI,COMPAT -Xms3948m -Xmx3948m -XX:+UseG1GC -XX:G1ReservePercent=25 -XX:InitiatingHeapOccupancyPercent=30 -Djava.io.tmpdir=/tmp/opensearch-3965706697535532938 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=data -XX:ErrorFile=/var/log/wazuh-indexer/hs_err_pid%p.log -Xlog:gc*,gc+age=trace,safepoint:file=/var/log/wazuh-indexer/gc.log:utctime,pid,tags:filecount=32,filesize=64m -Dclk.tck=100 -Djdk.attach.allowAttachSelf=true -Djava.security.policy=file:///usr/share/wazuh-indexer/plugins/opensearch-performance-analyzer/pa_config/opensearch_security.policy -XX:MaxDirectMemorySize=2069889024 -Dopensearch.path.home=/usr/share/wazuh-indexer -Dopensearch.path.conf=/etc/wazuh-indexer -Dopensearch.distribution.type=rpm -Dopensearch.bundled_jdk=true -cp /usr/share/wazuh-indexer/lib/* org.opensearch.bootstrap.OpenSearch -p /run/wazuh-indexer/wazuh-indexer.pid --quiet
```

</details>

<details>
<summary>Master C  🟢</summary>

```
wazuh-i+ 20399  3.0 56.5 7248288 4574612 ?     Ssl  12:13   4:10 /usr/share/wazuh-indexer/jdk/bin/java -Xshare:auto -Dopensearch.networkaddress.cache.ttl=60 -Dopensearch.networkaddress.cache.negative.ttl=10 -XX:+AlwaysPreTouch -Xss1m -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djna.nosys=true -XX:-OmitStackTraceInFastThrow -XX:+ShowCodeDetailsInExceptionMessages -Dio.netty.noUnsafe=true -Dio.netty.noKeySetOptimization=true -Dio.netty.recycler.maxCapacityPerThread=0 -Dio.netty.allocator.numDirectArenas=0 -Dlog4j.shutdownHookEnabled=false -Dlog4j2.disable.jmx=true -Djava.locale.providers=SPI,COMPAT -Xms3948m -Xmx3948m -XX:+UseG1GC -XX:G1ReservePercent=25 -XX:InitiatingHeapOccupancyPercent=30 -Djava.io.tmpdir=/tmp/opensearch-10778734451785800734 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=data -XX:ErrorFile=/var/log/wazuh-indexer/hs_err_pid%p.log -Xlog:gc*,gc+age=trace,safepoint:file=/var/log/wazuh-indexer/gc.log:utctime,pid,tags:filecount=32,filesize=64m -Dclk.tck=100 -Djdk.attach.allowAttachSelf=true -Djava.security.policy=file:///usr/share/wazuh-indexer/plugins/opensearch-performance-analyzer/pa_config/opensearch_security.policy -XX:MaxDirectMemorySize=2069889024 -Dopensearch.path.home=/usr/share/wazuh-indexer -Dopensearch.path.conf=/etc/wazuh-indexer -Dopensearch.distribution.type=rpm -Dopensearch.bundled_jdk=true -cp /usr/share/wazuh-indexer/lib/* org.opensearch.bootstrap.OpenSearch -p /run/wazuh-indexer/wazuh-indexer.pid --quiet
```

</details>

### Wazuh Dashboard

<details>
<summary>wazuh-indexer 🟢 </summary>

```
wazuh-i+ 24643 17.6 37.2 5636764 3014156 ?     Ssl  13:53   1:25 /usr/share/wazuh-indexer/jdk/bin/java -Xshare:auto -Dopensearch.networkaddress.cache.ttl=60 -Dopensearch.networkaddress.cache.negative.ttl=10 -XX:+AlwaysPreTouch -Xss1m -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djna.nosys=true -XX:-OmitStackTraceInFastThrow -XX:+ShowCodeDetailsInExceptionMessages -Dio.netty.noUnsafe=true -Dio.netty.noKeySetOptimization=true -Dio.netty.recycler.maxCapacityPerThread=0 -Dio.netty.allocator.numDirectArenas=0 -Dlog4j.shutdownHookEnabled=false -Dlog4j2.disable.jmx=true -Djava.locale.providers=SPI,COMPAT -Xms2560m -Xmx2560m -XX:+UseG1GC -XX:G1ReservePercent=25 -XX:InitiatingHeapOccupancyPercent=30 -Djava.io.tmpdir=/tmp/opensearch-4602623764530087920 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=data -XX:ErrorFile=/var/log/wazuh-indexer/hs_err_pid%p.log -Xlog:gc*,gc+age=trace,safepoint:file=/var/log/wazuh-indexer/gc.log:utctime,pid,tags:filecount=32,filesize=64m -Dclk.tck=100 -Djdk.attach.allowAttachSelf=true -Djava.security.policy=file:///usr/share/wazuh-indexer/plugins/opensearch-performance-analyzer/pa_config/opensearch_security.policy -XX:MaxDirectMemorySize=1342177280 -Dopensearch.path.home=/usr/share/wazuh-indexer -Dopensearch.path.conf=/etc/wazuh-indexer -Dopensearch.distribution.type=rpm -Dopensearch.bundled_jdk=true -cp /usr/share/wazuh-indexer/lib/* org.opensearch.bootstrap.OpenSearch -p /run/wazuh-indexer/wazuh-indexer.pid --quiet
```

</details>

<details>
<summary>wazuh-dashboard 🟢 </summary>

```
wazuh-d+ 24896  2.9  1.9 999412 155712 ?       Ssl  13:55   0:09 /usr/share/wazuh-dashboard/bin/../node/bin/node --no-warnings --max-http-header-size=65536 --unhandled-rejections=warn /usr/share/wazuh-dashboard/bin/../src/cli/dist -c /etc/wazuh-dashboard/opensearch_dashboards.yml
```

</details>

**Comment by juliamagan** [comment]
## Task 3: The status of the Wazuh Indexer clusters is as expected. 🟢 

```
[root@ip-10-0-2-125 wazuh-user]# curl -k -u USER:PASS https://10.0.2.125:9200/_cat/nodes?v
ip         heap.percent ram.percent cpu load_1m load_5m load_15m node.role master name
10.0.2.222           58          85   1    0.00    0.00     0.00 dimr      *      node-1
10.0.2.121           28          86   2    0.00    0.00     0.00 dimr      -      node-3
10.0.0.19            59          82   2    0.00    0.01     0.00 dimr      -      node-7
10.0.2.125           12          84   1    0.00    0.02     0.00 dimr      -      node-2
```

**Comment by juliamagan** [comment]
## Task 6:  No warning symbols in Discover when expanding a document. 🟢 

After performing several tests both in Discover and in different modules, we have not been able to find any warning.
