### ISSUE TITLE
Syscheck automated tests: windows_audit_interval option

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh-qa#290]
| Working branch |
| --- |
| |

## Description

Create a new test for windows_audit_interval. This option sets the frequency in seconds with which the Windows agent will check that the SACLs of the directories monitored in whodata mode are correct. If the SACLs are not correct Whodata will be disabled for that directory and Real-Time will be enabled. In this case, once the SACLs are restored Whodata monitoring will be enabled again.

- **Default value:** 300 seconds
- **Allowed values:** Any number from 1 to 9999

A issue  due to a race condition between the Whodata state checker and an external software that needs to access with remove permissions to a monitored file was discovered and reported. A test to verify this was solved is also needed. The steps to simulate this bug can be found here: https://github.com/wazuh/wazuh/pull/3872

## Subtasks

- [x] Check Real-Time monitoring is enabled when Windows audit policies fails.
- [x] Check that the audit policies are restored
- [ ] ~Verify that whodata does not block files. https://github.com/wazuh/wazuh/pull/3872~ This should have its own issue and be tested independently.
