### ISSUE TITLE
New integration tests development: RBAC database upgrade and migration

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#2913]
|Version|Component|Framework development branch | QA development branch |
|-|-|-|-|
| 4.5.0 | Master | [dev-13109-rbac-upgrade-migration](https://github.com/wazuh/wazuh/tree/dev-13109-rbac-upgrade-migration) | |

## Introduction

Wazuh version `4.5.0` applies some modifications to the existing `RBAC.db`.
Considering that the user may have applied some changes to the database, like adding new roles, policies, etc.

As a QA team we must verify that the migration process applies the new changes without affecting the existing information stored in the database. 
Our team must develop new integration tests to cover these changes. 

This issue is part of wazuh/wazuh#13109 and wazuh/wazuh#13110.

## Development stage

- [x] In research
- [ ] Planning and estimating
- [ ] In development
- [ ] In testing phase 
- [ ] In Review
- [ ] Completed

## Use cases

- [ ] Migrate from an older version all kind of resources and relations (cloud and user).
- [ ] Migrate from an older version having an identical user policy defined as `DEFAULT` in the new version. The policy should be migrated to a new ID range along with its relationships.
- [ ] Migrate from an older version removing some of the `DEFAULT` resources. These resources must be related to other `USER` ones. When migrated, those relationships should disappear. 
- [ ] Migrate from an older version modifying one of the `DEFAULT` resources. These resources must be related to other `USER` ones. Relationships must be kept.
- [ ] Migrate from an older version deleting a `DEFAULT` resource and adding a new one with the same ID. This resource must be related to other `USER` one. After the migration, previous relationships should be deleted as the resources are not the same.
- [ ] Faulty migration leads to the Wazuh API not starting.
- [ ] Proper logs must be retrieved when user resources are modified.
- [ ] Proper logs must be retrieved when default resources are modified.

## Note

Cases proposed by the framework team, but we need to check if there are new cases to add.

## Related Issues

- #4253

**Comment by EduLeon12** [comment]
## Issue Update 

The first approach will be to test the current ITs and UTs to understand the current reach and status of tests, then a first mock-up of the design for the migration test. I will be testing on a fresh ec2 installation to have records or logs from scratch.

**Comment by EduLeon12** [comment]
A Meeting has been scheduled to begin with the design and first implementation of the ITs.

**Comment by EduLeon12** [comment]
## Issue Update 

After Analyzing with the help of the team the proposed use cases for the tests it was decided that instead of creating them inside API/test and following the tavern framework specifications, system tests will be developed instead.

The reason behind this decision is that to test all the use cases we will need to constantly upgrade and downgrade the manager to specific versions and since downgrading is not currently supported it would be extremely inefficient to build multiple containers instead of using only one.

System tests will allow us to design the test to address this issue and install the version needed for every use case.

**Comment by damarisg** [comment]
We decided to close them.
