### ISSUE TITLE
FIM IT: Remove all skipped tests

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#2927]
## Description

To have a stable and reliable test suite of the FIM module. 
It is required to create a `DRAFT branch` with all tests skipped for future revisions and refactors.
And a branch that will be merged into `master 4.4`, where all skipped tests will be removed.

After such a rework, the same results should be obtained in all related tests as at the beginning.

**Note:** Each test skipped should be added on https://github.com/wazuh/wazuh-qa/issues/2174

## Tasks

- [x] Create a branch with all tests skipped in 4.4
          -   `2174-skipped-fim-tests-that-need-refactoring-4.4`  
- [x] Create a branch with stable test from 4.4 
          -   `2927-remove-skipped-fim-tests-4.4`
- [x] Run tests to merge into 4.4
