### ISSUE TITLE
E2E design and implementation: Brute Force - Second iteration

### ISSUE THREAD

**Issue by BelenValdivia** [wazuh/wazuh-qa#2932]
## Description

The test research was accomplished in [this issue](https://github.com/wazuh/wazuh-qa/issues/2838). So, in this issue, we will design and develop the E2E test to cover those use cases.

## Tasks

- [ ] Design the test
- [ ] Implement the test locally
- [ ] Refactor the test for it to work in the test environment

## Conclusion

**Comment by BelenValdivia** [comment]
**5/30/2022**
- Test to run ssh brute force attack implemented locally. PR in progress [here](https://github.com/wazuh/wazuh-qa/pull/2916)

**Comment by juliamagan** [comment]
This issue is closed by the end of the sprint. Work will continue on #3004
