### ISSUE TITLE
Release 4.3.2 - Vulnerabilitty  Detector: Segmentation fault in modulesd 

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#2934]
The goal is to verify that once a package that is considered vulnerable is installed, the corresponding alerts are generated and there is no problem with the `modulesd` daemon, thus solving the `segmentation fault in modulesd` issue.

## Test information
|                         |                                            |
|-------------------------|--------------------------------------------|
| **Test name**           |Segmentation fault in modulesd|
| **Category**            |Manual testing|
| **Deployment option**   |AWS  environment|
| **Release candidate #** | 4.3.2, 4.2.7, 3.13.4 |

## Research tasks

**`4.3.2`**
- [x] Reproduced segmentation fault in `modulesd`. [Details](https://github.com/wazuh/wazuh-qa/issues/2934#issuecomment-1141367222).
- [x] Clean installation of `wazuh-manager` `4.3.2`. [Details](https://github.com/wazuh/wazuh-qa/issues/2934#issuecomment-1141367222).
    - [x] Installed `Mozilla Firefox 78.6.0esr` on Windows agent.
    - [x] Vulnerability scan is performed 
    - [x] Vulnerability alert is generated successfully
    - [x] No segmentation fault occurs
    - [x] No `wazuh-modulesd` process crashes
- [x] Upgrade of `wazuh-manager` from `4.3.1` to `4.3.2`. [Details](https://github.com/wazuh/wazuh-qa/issues/2934#issuecomment-1141367222).
    - [x] Segmentation fault occurs in `4.3.1` (services crash...).
    - [x] Upgrade the `wazuh-manager` version to `4.3.2`.
    - [x] Mozilla `Mozilla Firefox 78.6.0esr` package is removed from Windows agent. Alert is generated correctly with no `modules` crashes.
    - [x] Mozilla `Mozilla Firefox 78.6.0esr` is installed on Windows agent.
    - [x] Vulnerability alert is generated successfully
    - [x] No segmentation fault occurs
    - [x] No `wazuh-modulesd` process crashes.

**`4.2.7`**
- [x] Reproduced segmentation fault in `modulesd`.
- [x] Clean installation of `wazuh-manager` `4.2.7`.
    - [x] Installed `Mozilla Firefox 78.6.0esr` on Windows agent.
    - [x] Vulnerability scan is performed 
    - [x] Vulnerability alert is generated successfully
    - [x] No segmentation fault occurs
    - [x] No `wazuh-modulesd` process crashes
- [x] Upgrade of `wazuh-manager` from `4.2.6` to `4.2.7`:
    - [x] Segmentation fault occurs in `4.2.6` (services crash...).
    - [x] Upgrade the `wazuh-manager` version to `4.2.7`.
    - [x] Mozilla `Mozilla Firefox 78.6.0esr` package is removed from Windows agent. Alert is generated correctly with no `modules` crashes.
    - [x] Mozilla `Mozilla Firefox 78.6.0esr` is installed on Windows agent.
    - [x] Vulnerability alert is generated successfully
    - [x] No segmentation fault occurs
    - [x] No `wazuh-modulesd` process crashes.

**`3.13.4`**
- [x] Reproduced segmentation fault in `modulesd`.
- [x] Clean installation of `wazuh-manager` `3.13.4`.
    - [x] Installed `Thunderbird 68.1.0` on Windows agent.
    - [x] Vulnerability scan is performed 
    - [x] Vulnerability alert is generated successfully
    - [x] No segmentation fault occurs
    - [x] No `wazuh-modulesd` process crashes
- [x] Upgrade of `wazuh-manager` from `3.13.3` to `3.13.4`:
    - [x] Segmentation fault occurs in `3.13.3` (services crash...).
    - [x] Upgrade the `wazuh-manager` version to `3.13.4`.
    - [x] Mozilla `Thunderbird 68.1.0` is installed on Windows agent.
    - [x] Vulnerability alert is generated successfully
    - [x] No segmentation fault occurs
    - [x] No `wazuh-modulesd` process crashes.
- [x] Alerts are displayed in Kibana

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [x] @jmv74211

**Comment by damarisg** [comment]
# Fresh Install 4.3.1: There is segmentation error in `modulesd` modules. 🟢

## Steps by Step:

1. Install Wazuh Manager 4.3.1 

    ![imagen](https://user-images.githubusercontent.com/3978434/171028603-0970334b-5a10-49a3-a7df-e0c685c20a04.png)

2. In the Manager, I modify the ossec.conf file with: 

>     <vulnerability-detector>
>      <enabled>yes</enabled>
>      <interval>30s</interval>
>      <min_full_scan_interval>1m</min_full_scan_interval>
>      <run_on_start>yes</run_on_start>
> 
>     
>     <provider name="msu">
>       <enabled>yes</enabled>
>       <update_interval>1h</update_interval>
>     </provider>
> 
>     
>     <provider name="nvd">
>       <enabled>yes</enabled>
>       <update_from_year>2017</update_from_year>
>       <update_interval>1h</update_interval>
>     </provider>
> 
>   </vulnerability-detector>

3. Start Wazuh Manager
4. Install Wazuh agent with 4.3.1
5. In the Agent, I modify the ossec.conf file with:

>     <wodle name="syscollector">
>      <disabled>no</disabled>
>      <interval>1m</interval>
>      <scan_on_start>yes</scan_on_start>
>      <hardware>yes</hardware>
>      <os>yes</os>
>      <network>yes</network>
>      <packages>yes</packages>
>      <ports all="no">yes</ports>
>      <processes>yes</processes>
>    </wodle>

**Comment by damarisg** [comment]
# Upgrade 4.3.1 - 4.3.2: There is no segmentation error in modulesd daemon.🟢

## Steps by Step:

1. Install Wazuh Manager 4.3.1 

    ![imagen](https://user-images.githubusercontent.com/3978434/171028603-0970334b-5a10-49a3-a7df-e0c685c20a04.png)

2. In the Manager, I modify the ossec.conf file with: 

>     <vulnerability-detector>
>      <enabled>yes</enabled>
>      <interval>30s</interval>
>      <min_full_scan_interval>1m</min_full_scan_interval>
>      <run_on_start>yes</run_on_start>
> 
>     
>     <provider name="msu">
>       <enabled>yes</enabled>
>       <update_interval>1h</update_interval>
>     </provider>
> 
>     
>     <provider name="nvd">
>       <enabled>yes</enabled>
>       <update_from_year>2017</update_from_year>
>       <update_interval>1h</update_interval>
>     </provider>
> 
>   </vulnerability-detector>

3. Start Wazuh Manager
4. Install Wazuh agent with 4.3.1
5. In the Agent, I modify the ossec.conf file with:

>     <wodle name="syscollector">
>      <disabled>no</disabled>
>      <interval>1m</interval>
>      <scan_on_start>yes</scan_on_start>
>      <hardware>yes</hardware>
>      <os>yes</os>
>      <network>yes</network>
>      <packages>yes</packages>
>      <ports all="no">yes</ports>
>      <processes>yes</processes>
>    </wodle>

**Comment by damarisg** [comment]
Fresh Install 4.2.7: There is segmentation error in modulesd daemon.

**Comment by damarisg** [comment]
Upgrade 4.2.6 - 4.2.7: There is no segmentation error in modulesd daemon.
