### ISSUE TITLE
Fim testing Windows

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh-qa#294]
# Test file integrity monitoring

## Windows

Compile with flag DEBUGAD=1:
>`make TARGET=[server|agent] DEBUG=1 DEBUGAD=1 -j8`

With the flag DEBUGAD we can see the content of the databases information in the agent.
We had two structures:

|structure|key|data|
|----|----|----|
|red&black tree|path|fim_entry_data|
|inode/dev hash table|inode:device|path|

```c
typedef struct fim_entry_data {
    // Checksum attributes
    unsigned int size;
    char * perm;
    char * attributes;
    char * uid;
    char * gid;
    char * user_name;
    char * group_name;
    unsigned int mtime;
    unsigned long int inode;
    os_md5 hash_md5;
    os_sha1 hash_sha1;
    os_sha256 hash_sha256;
    // Options
    fim_event_mode mode;
    time_t last_event;
    const char * entry_type;
    unsigned long int dev;
    unsigned int scanned;
    int options;
    os_sha1 checksum;
} fim_entry_data;
```

Configure in local_internal_options.conf:
>`syscheck.debug=2`

During the test, check `ossec.log` looking for debug, error or warning messages that may be unnecessarily repetitive or useless.

### FIM start:
- [x] FIM should not report any alerts until the first scan has finished and generated a base line.
- [x] After the first scan, FIM should synchronize the database with the manager's. The number of entries in both databases must be the same and with the same elements.
- [x] Check disable option, set to no, shouldn't show any message about performing scans.
    `wdb 002 "select count(*) from fim_entry" "count(*)": 3372`
    `DEBUG: (6335):Fim entries: 3372`
- [ ] Check that if the number of inodes is different from the number of entries, then, the sum of all paths in the inode table is equal to the number of entries.
    `DEBUG: (6336): Fim inode entries: 3342, path count: 3372`
    `DEBUG: (6335): Fim entries: 3372`

### Configure file and directory in scheduled mode.
```xml
<directories>/test, /testfile/file</directories>
```
Check FIM alerts ADD, DELETE, MODIFICATION
- [ ] File alerts added.
- [ ] Modified file alerts.
- [ ] Deleted file alerts.
```xml
<directories check_all="no" check_size="yes">/testsize</directories>
<directories check_all="no" check_perm="yes">/testperm</directories>
<directories check_all="no" check_owner="yes">/testowner</directories>
<directories check_all="no" check_group="yes">/testgroup</directories>
<directories check_all="no" check_mtime="yes">/testmtime</directories>
<directories check_all="no" check_inode="yes">/testinode</directories>
<directories check_all="no" check_md5sum="yes">/testmd5sum</directories>
<directories check_all="no" check_sha1sum="yes">/testsha1sum</directories>
<directories check_all="no" check_sha256sum="yes">/testsha256sum</directories>
<directories check_all="no" check_attrs="yes">/testattrs</directories>
<directories check_all="no" report_changes="yes">/testseechanges</directories>
```
Check FIM alerts ADD, DELETE, MODIFICATION
- [x] Check option check_size for file and directory (added, modified and deleted alerts).
- [x] Check option check_perm for file and directory (added, modified and deleted alerts).
- [x] Check option check_owner for file and directory (added, modified and deleted alerts).
- [x] Check option check_group for file and directory (added and deleted alerts).
- [x] Check option check_mtime for file and directory (added, modified and deleted alerts).
- [x] Check option check_inode for file and directory (added and deleted alerts).
- [x] Check option check_md5sum for file and directory (added, modified and deleted alerts).
- [x] Check option check_sha1sum for file and directory (added, modified and deleted alerts).
- [x] Check option check_sha256sum for file and directory (added, modified and deleted alerts).
- [ ] Check option check_attrs for file and directory (added, modified and deleted alerts).
- [x] Check option report_changes for file and directory (added, modified and deleted alerts).

### Configure file and directory in real-time mode.
```xml
<directories realtime="yes">/testrealtime, /testrealtimefile/file</directories>
```
Check FIM alerts ADD, DELETE, MODIFICATION
- [ ] File alerts added.
- [ ] Modified file alerts.
- [ ] Deleted file alerts.
```xml
<directories check_all="no" realtime="yes" check_size="yes">/testsize</directories>
<directories check_all="no" realtime="yes" check_perm="yes">/testperm</directories>
<directories check_all="no" realtime="yes" check_owner="yes">/testowner</directories>
<directories check_all="no" realtime="yes" check_group="yes">/testgroup</directories>
<directories check_all="no" realtime="yes" check_mtime="yes">/testmtime</directories>
<directories check_all="no" realtime="yes" check_inode="yes">/testinode</directories>
<directories check_all="no" realtime="yes" check_md5sum="yes">/testmd5sum</directories>
<directories check_all="no" realtime="yes" check_sha1sum="yes">/testsha1sum</directories>
<directories check_all="no" realtime="yes" check_sha256sum="yes">/testsha256sum</directories>
<directories check_all="no" realtime="yes" check_attrs="yes">/testattrs</directories>
<directories check_all="no" realtime="yes" report_changes="yes">/testseechanges</directories>
```
Check FIM alerts ADD, DELETE, MODIFICATION
- [x] Check option check_size for file and directory (added, modified and deleted alerts).
- [x] Check option check_perm for file and directory (added, modified and deleted alerts).
- [x] Check option check_owner for file and directory (added, modified and deleted alerts).
- [x] Check option check_group for file and directory (added and deleted alerts).
- [x] Check option check_mtime for file and directory (added, modified and deleted alerts).
- [x] Check option check_inode for file and directory (added and deleted alerts).
- [x] Check option check_md5sum for file and directory (added, modified and deleted alerts).
- [x] Check option check_sha1sum for file and directory (added, modified and deleted alerts).
- [x] Check option check_sha256sum for file and directory (added, modified and deleted alerts).
- [ ] Check option check_attrs for file and directory (added, modified and deleted alerts).
- [x] Check option report_changes for file and directory (added, modified and deleted alerts).

### Configure file and directory in whodata mode.
```xml
<directories whodata="yes">/testwhodata, /testwhodatafile/file</directories>
```
Check FIM alerts ADD, DELETE, MODIFICATION
- [ ] File alerts added.
- [ ] Modified file alerts.
- [ ] Deleted file alerts.
```xml
<directories check_all="no" whodata="yes" check_size="yes">/testsize, /testfilesize/file</directories>
<directories check_all="no" whodata="yes" check_perm="yes">/testperm, /testpermfile/file</directories>
<directories check_all="no" whodata="yes" check_owner="yes">/testowner, /testownerfile/file</directories>
<directories check_all="no" whodata="yes" check_group="yes">/testgroup, /testgroupfile/file</directories>
<directories check_all="no" whodata="yes" check_mtime="yes">/testmtime, /testmtimefile/file</directories>
<directories check_all="no" whodata="yes" check_inode="yes">/testinode, /testinodefile/file</directories>
<directories check_all="no" whodata="yes" check_md5sum="yes">/testmd5sum, /testmd5sumfile/file</directories>
<directories check_all="no" whodata="yes" check_sha1sum="yes">/testsha1sum, /testsha1sumfile/file</directories>
<directories check_all="no" whodata="yes" check_sha256sum="yes">/testsha256sum, /testsha256sumfile/file</directories>
<directories check_all="no" whodata="yes" check_attrs="yes">/testattrs, /testattrsfile/file</directories>
<directories check_all="no" whodata="yes" report_changes="yes">/testseechanges, /testseechangesfile/file</directories>
```
Check FIM alerts ADD, DELETE, MODIFICATION
- [x] Check option check_size for file and directory (added, modified and deleted alerts).
- [x] Check option check_perm for file and directory (added, modified and deleted alerts).
- [x] Check option check_owner for file and directory (added, modified and deleted alerts).
- [x] Check option check_group for file and directory (added and deleted alerts).
- [x] Check option check_mtime for file and directory (added, modified and deleted alerts).
- [x] Check option check_inode for file and directory (added and deleted alerts).
- [x] Check option check_md5sum for file and directory (added, modified and deleted alerts).
- [x] Check option check_sha1sum for file and directory (added, modified and deleted alerts).
- [x] Check option check_sha256sum for file and directory (added, modified and deleted alerts).
- [x] Check option check_attrs for file and directory (added, modified and deleted alerts).
- [x] Check option report_changes for file and directory (added, modified and deleted alerts).
- [x] Check that the audit policies are restored when Wazuh stops.
- [x] Check that if an user modify a folder audit policies, making them incompatibles with Whodata, they are not restored when Wazuh stops.
- [x] Check that if an user modify a folder audit policies, making them incompatibles with Whodata, the folder is starts to be monitored in realtime.
- [x] Check that if a monitored folder is removed, it continues to be monitored when it reappears.
- [x] Verify that whodata does not block files. https://github.com/wazuh/wazuh/pull/3872

### Check ignore and restrict options:
- [x] Configure ignore `<ignore>file</ignore>`
- [x] Configure ignore sregex using '^' `<ignore type="sregex">^string</ignore>`
- [x] Configure ignore sregex using '$' `<ignore type="sregex">string$</ignore>`
- [x] Configure ignore sregex using '|' `<ignore type="sregex">string1|string2</ignore>`
- [x] Configure ignore sregex using '!' `<ignore type="sregex">!string</ignore>`
- [x] Configure restrict sregex using '^' <directories restrict="^string">/test</directories>
- [x] Configure restrict sregex using '$' <directories restrict="string$">/test</directories>
- [x] Configure restrict sregex using '|' <directories restrict="string1|string2">/test</directories>
- [x] Configure restrict sregex using '!' <directories restrict="!string">/test</directories>

### Configure directories with strange characteres
- [x] Configure paths with backslashes `<directories>C:\test</directories>`
- [x] Configure paths with regular slashes `<directories>C:/test</directories>`
- [x] Configure paths with mixed regular and backslashes in it `<directories>C:\folder/test</directories>`
- [ ] Configure paths with a driver letter different from `C:`, for example `<directories>F:</directories>`

### Check <windows_registry> option

```xml
<windows_registry>HKEY_LOCAL_MACHINE\Software\Classes\batfile</windows_registry>
<windows_registry arch="both">HKEY_LOCAL_MACHINE\HARDWARE\DESCRIPTION</windows_registry>
```
- [x] Check syscheck alert for monitoring windows registry.
- [x] Check syscheck alert for adding a registry.
- [x] Check syscheck alert for modifying a registry.
- [x] Check syscheck alert for delete a registry.
- [ ] Check syscheck alert with "arch" option (32, 64 and both).
- [ ] Check that no double alerts when using "arch=both" option.

### Check process priority and max_eps (performance) options:
- [ ] Configure `process_priority` option with different values and check the configured priority is set (with `top` or `htop` in Linux).
- [x] Configure `max_eps` option.

### Centralized configuration and on-demand configuration
- [x] Check that `<directories>` in `syscheck` configuration block are overwritten by a configuration specified in the centralized configuration (`agent.conf`) including entries with a trailing slash in a single comma-separated stanza.
- [x] Check the `syscheck` on-demand configuration (agent configured with `agent.conf` file).

### Updates
- [ ] Check for false positives when an old manager is updated.
- [ ] Check for false positives when an old agent is updated.

### Others
- [x] Check nodiff option `<nodiff>/test/file</nodiff>`
- [x] Check that back up files (created by `report_changes` option) are deleted wether the agent is restarted or a monitored file (with `report_changes`) is deleted.
- [x] Check if ignore files and folders using tag <ignore> and restrict option (string or sregex) in both options.
- [ ] Check if delete content in `C:\Program Files (x86)\ossec-agent\queue\diff\local\c` when deleting any tag <directories report_changes="yes">
- [x] Check if delete content in `C:\Program Files (x86)\ossec-agent\queue\diff\local\c` when report_changes option passed yes to no.
- [x] Check that duplicate entries are ignored. Include entries with a trailing slash in a single comma-separated stanza.
- [x] Check syscheck alert for moving a file.
- [ ] Check syscheck alert for moving a folder with a file in it.
- [x] Check that the add file alert does not contain modification information. To do this, create a file with content in the folder being monitored, delete it and add a new file with the name of the deleted file.
- [x] Check syscheck alert for renaming a file.
- [x] Check syscheck alert for renaming a folder.
- [x] Check syscheck alert for deleting a folder.
- [x] Check recursion level option (recursion_level=0, recursion_level=2 check folder level 0, 1, 2 and 3).
- [x] Check syscheck alert for nested monitoring with <tags> option.

### Integrity
- [ ] Add/Modify/Delete a file. Connect the agent with another administrator (if you have two or more managers in the configuration, the agent doesn't need to be restarted). Check that the database is up to date, but there is no alert in the new administrator.
- [ ] Stop the agent. Add a file. Start the agent. The new file must be in the database after the scan but there must not be any alert.
- [ ] Stop the agent. Remove a file. Start the agent. The removed file must not be in the database after the scan and there must not be any alert.
- [ ] Add/Modify/Remove a regitry. Connect the agent to another manager (if you have two or more managers in the configuration, the agent doesn't need to be restarted). Check the database is updated but there is no alert in the new manager.
- [ ] Stop the agent. Add a registry. Start the agent. The new file must be in the database after the scan but there must not be any alert.
- [ ] Stop the agent. Remove a registry. Start the agent. The removed file must not be in the database after the scan and there must not be any alert.
- [ ] Set the inventory paramete `sync_interval` to 0 in the agent's ossec.conf. Syscheck must log a Warning message. The value of `sync_interval` must be 300. It can be queried with the API: `curl -u foo:bar -k -X GET "http://127.0.0.1:55000/agents/001/config/syscheck/syscheck?pretty"`
- [ ] In the configuration, put only files. Wait for a full scan.  Checks the integrity between the agent data and the database.
- [ ] In the configuration, put only registries. Wait for a full scan. Checks the integrity between the agent data and the database.
- [ ] Checks syscheck configuration for consistency, looking for errors when typing incorrect fields.

### General
- [ ] Daylight saving induced false positives: https://github.com/wazuh/wazuh/issues/4167
- [ ] Syscheck frequency values under 10 seconds behaviour: https://github.com/wazuh/wazuh/issues/4003
- [ ] Information message number 6022 can flood the Windows agent log file: https://github.com/wazuh/wazuh/issues/3998
- [ ] Simple and sregex syscheck <registry_ignore> stanzas are incompatible: https://github.com/wazuh/wazuh/issues/3990 (When combining <registry_ignore> and <registry_ignore type="sregex"> stanzas, only the non-sregex ones will be taken into account at the registry ignore process.)
- [ ] Different behavior in configuration while monitoring a drive in whodata and realtime: https://github.com/wazuh/wazuh/issues/3934
- [ ] Failure to monitor directories in real-time when configuring Windows audit policies: https://github.com/wazuh/wazuh/issues/3812
- [ ] Realtime syscheck alerts are not queued if agent is offline: https://github.com/wazuh/wazuh/issues/3811
- [ ] Too generic error when adding an inotify watcher: https://github.com/wazuh/wazuh/issues/3770
- [ ] Receive alert of realtime instead of whodata: https://github.com/wazuh/wazuh/issues/3733
- [ ] Incompatible field types in Kibana: https://github.com/wazuh/wazuh/issues/3171
- [ ] Real time events moving files or directories: https://github.com/wazuh/wazuh/issues/2863
- [ ] Realtime syscheck scan doesn't start: https://github.com/wazuh/wazuh/issues/2798
- [ ] FIM full_log field is being truncated : https://github.com/wazuh/wazuh/issues/2632
- [ ] Add timezone option for syscheck <scan_time>: https://github.com/wazuh/wazuh/issues/2555
- [ ] Executing whodata with inmutable audit configuration: https://github.com/wazuh/wazuh/issues/2432
- [ ] FIM DB synchronization between managers: https://github.com/wazuh/wazuh/issues/2404
- [ ] Syscheck is not attaching the timestamp of a deleted file event when having realtime enabled: https://github.com/wazuh/wazuh/issues/2397
- [ ] Sregex is not useful in restrict option: https://github.com/wazuh/wazuh/issues/2064
- [ ] Whodata for auditd logs: https://github.com/wazuh/wazuh/issues/2042
- [ ] FIM output inconsistency: https://github.com/wazuh/wazuh/issues/2005
- [ ] False positives about new files in FIM: https://github.com/wazuh/wazuh/issues/1881
- [ ] Error with real-time + NFS: https://github.com/wazuh/wazuh/issues/1269
- [ ] Filtering by event type: https://github.com/wazuh/wazuh/issues/1247
- [ ] Syscheck directories tag doesn't recognize directory / it needs /.: https://github.com/wazuh/wazuh/issues/3705
- [ ] FIM is not able to parse some symbols in a Windows Agent: https://github.com/wazuh/wazuh/issues/3310
- [ ] Syscheck hangs analyzing /dev/core: https://github.com/wazuh/wazuh/issues/3007
- [ ] FIM keeps alerting after removing a symbolic link: https://github.com/wazuh/wazuh/issues/2433
- [ ] Ignore option for Syscheck makes global ignores on the manager: https://github.com/wazuh/wazuh/issues/2378
- [ ] Syscheck in realtime doesn't detect changes in hardlinks: https://github.com/wazuh/wazuh/issues/2355

**FIM rework:**
- https://github.com/wazuh/wazuh/issues/3073 
- https://github.com/wazuh/wazuh/issues/3319

**Comment by crolopez** [comment]
The following bugs have been fixed recently:
- Memory leak when using the registry scan: https://github.com/wazuh/wazuh/commit/f0f5f21c385029045af7b6000d6e5abda931fac8
- The priority option does not allow negative values: https://github.com/wazuh/wazuh/commit/9549556bb915892ddc7693df7b50039010bc4951
- The `event_time` field should not appear in the alerts: https://github.com/wazuh/wazuh/commit/d68870e8d2881c48a31636c9b44b9dd1e783b458
- Invalid `event_time` in deletion alerts. It is not necessary to fix it because this field has been removed from the alert.
- The agent does not decode the attributes field properly: https://github.com/wazuh/wazuh/commit/2149eecb80925f981fb1d83b332f3c359213f729
- False positives when removing a monitored link: https://github.com/wazuh/wazuh/commit/8e9faef97924e3a1ed86dd1ccefb87193790e859
- Segfault when scanning Windows registries: https://github.com/wazuh/wazuh/commit/0e15655cb1c4d262ad6844b7b8af79c2aca2e8fc
- False positives when not all Windows agent checks are active: https://github.com/wazuh/wazuh/commit/55a06800f4acf2e1f7ce624240c43e6f661004fa
The next testing round continues in this issue: https://github.com/wazuh/wazuh-qa/issues/303
