### ISSUE TITLE
QA testing - Syscollector cannot retrieve the windows package installation date if the registry does not have it

### ISSUE THREAD

**Issue by HanesSciarrone** [wazuh/wazuh-qa#2943]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
| v4.5 | wazuh/wazuh#10703  | wazuh/wazuh#14499|

### Short description
Some packages installed on Windows do not register their installation time. Suggested changes found a way to guess it.
### Long description
Syscollector isn't able to get a package install date when the package itself did not register Installation time in the registry `HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\<PACKAGENAME>>` value of (`InstallDate`)
![image](https://user-images.githubusercontent.com/58960358/171411458-630062e0-b799-464b-b730-993fe49e8a32.png)
Suggested change consist, in case of package does not have `InstallDate` included, get its parent register last modification time (somehow is guessing the install time)

## Proposed checks

- [x] Install a package that saves `InstallDate` and validate that inventory shows it (Any method allowed: API or DB query)
- [x] Install a package that doesn't save `InstallDate` and validate that inventory shows it as well (Any method allowed: API or DB query)
- [x] Install a package and update the version by installing it, not via `Registry`
- [x] Check that version changes in the unfixed version are autofixed after wazuh's update

## Steps to reproduce
0- On a Windows env, install any software that does not save `InstallDate`. 7zip might be one of them
1- Install a Windows Wazuh agent and enroll with a Wazuh Manager
2- Check that agent's syscollector is enabled and packages retrieving as well
3- Check syscollector scan was run

## Expected results before changes
Inventory information regarding such package shown empry `install_date` information
## Expected results after changes
Inventory information regarding such package shown `install_date` information

**Comment by roronoasins** [comment]
## Review data

| Tester | PR commit               | 
|--------|-------------------------|
| @roronoasins   |  [a75fa57](https://github.com/wazuh/wazuh/pull/14499/commits/a75fa57e6b387eb442b11f39c4c70d94863001c4)   | 

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
|  Ubuntu  | 22.04 | `AWS` | `ami-003530de8839921c4`| Deployed and provisioned with internal pipeline |
|  Windows Server  | 2022 | `AWS` | `ami-047e29beecff33db0` | Deployed and provisioned with internal pipeline |

### Tested packages

| `wazuh-manager` | `wazuh-agent` | 
|-----------------|---------------|
|  [deb](https://packages-dev.wazuh.com/warehouse/pullrequests/4.5/deb/var/)  | [msi](https://packages-dev.wazuh.com/warehouse/pullrequests/4.5/)  | 

### Status

- [x] In progress
- [ ] Pending Review
- [ ] Team leader approved
- [ ] Manager approved

### Conclusion :large_blue_circle:

**Comment by roronoasins** [comment]
# Task results

## Unfixed

<details><summary>Syscollector cannot retrieve the windows package installation date if the Registry does not have it :red_circle:</summary>

- Deploy and provision a manager and winagent

- Check that there are packages with `install_date` empty
  ```
  root@ip-172-31-8-236:/home/qa# sqlite3 /var/ossec/queue/db/001.db "select * from sys_programs where install_time is null"
  0|2022/09/12 15:29:15|win|Microsoft Visual C++ 2015-2019 Redistributable (x64) - 14.29.30135|||0|Microsoft Corporation||14.29.30135.0|i686|||||0|||3f9a738810e7154df12d011ca0da77a5794fa535|37f817683b81226be14605ab35f1812f27eac031
  0|2022/09/12 15:29:16|win|Microsoft Word LTSC - en-us|||0|Microsoft Corporation||16.0.14332.20358|x86_64||||C:\Program Files\Microsoft Office|0|||aa7fdbadea1ffe21bb6747b40cf37c95582c0c0c|517c3ac2d627d0cd277538bdbf11034a2fa6f59a
  0|2022/09/12 15:29:16|win|Vim 8.2|||0|Bram Moolenaar et al.||8.2|x86_64|||||0|||ea24f5c04f3011b126bc6f82d763e7617512a231|695fd9e2c1b8c454bd39923e15e30c2e40be1a50
  0|2022/09/12 15:29:16|win|aws-cfn-bootstrap|||0|Amazon Web Services||2.0.10|i686|||||0|||cb3d9494bfd89f8b0f32f3fbdf2938fa8fb62f1f|6b27221a98e71c89ddd9eb61f58529178b7f2c9a
  0|2022/09/12 15:29:16|win|Amazon SSM Agent|||0|Amazon Web Services||3.1.1188.0|i686|||||0|||941fda3f39ed4317b8edbc5780ad0c56a896fb57|7021562d7bd3aa3f3c35180d5849569b2ebd1086
  0|2022/09/12 15:29:18|win|Microsoft OneDrive|||0|Microsoft Corporation||21.030.0211.0002|i686|||||0|||25890973468fb8e86b8f106fe2c7d215042dfc8d|ef56483a8018148bc2619eb690761dbc5fc8a517
  0|2022/09/12 15:29:18|win|Microsoft Edge Update|||0|||1.3.167.21|i686|||||0|||7378b46d929d6742ef54370b71e0531e327708b1|ffafca9f7a8edb55b5bd7899e673356cb73a8c52
  ```

  As we can see, the field next to the version is empty, for example for `Vim` package that has `8.2` version: `Vim 8.2|||0|Bram Moolenaar et al.||8.2`

- Install new package that has no `InstallDate` field within the `Registry`

  Download the package from the [official website](https://www.7-zip.org/a/7z2201-x64.exe), install it, and restart the agent via ui. Then, check its db entry:
  ```
  root@ip-172-31-8-236:/home/qa# sqlite3 /var/ossec/queue/db/001.db "select * from sys_programs where instr(name, 'Zip')"
  0|2022/09/12 15:45:54|win|7-Zip 22.01 (x64)|||0|Igor Pavlov||22.01|x86_64||||C:\Program Files\7-Zip\|0|||e5e0ce3d71d6e6f0c80625292c5cf61d38369e4a|996df2f69b2bb0c883570ac5d0e02cced5d84043
  ```

  The db entry has the `install_date` empty
  ```
  root@ip-172-31-8-236:/home/qa# sqlite3 /var/ossec/queue/db/001.db "select install_time from sys_programs where instr(name, 'Zip')"


  ```

  Control panel's initial state
  ![initial_cp](https://user-images.githubusercontent.com/33318890/189704074-44ec756a-4449-4156-bd28-26e7fb691c9e.png)

- Modify the package metadata via `Registry editor`

  We have to navigate to `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall` and look for the packages we want to modify.

  ![7zip_registry](https://user-images.githubusercontent.com/33318890/189704267-ef23eb16-309d-422a-9734-aad8b4b464e3.png)
  ![7zip_update](https://user-images.githubusercontent.com/33318890/189704343-ce3bf554-4ed8-4bb2-ad04-a090a7086b4a.png)

  After restarting the agent to gather the `7Zip` changes, check if the db has the `install_time`:
  ```
  root@ip-172-31-8-236:/home/qa# sqlite3 /var/ossec/queue/db/001.db "select * from sys_programs where instr(name, 'Zip')"
  0|2022/09/12 15:54:49|win|7-Zip 22.01 (x64)|||0|Igor Pavlov||26|x86_64||||C:\Program Files\7-Zip\|0|||bd0b1cb353c36bea07446b4823fc23eb2606fd69|2d2f4551f913f4995defa5baa20d9831f67225b7
  ```
  So, the version is updated but the `install_time` field doesn't as expected.

  Extra checks:

  - Check this workaround with a package with `InstallDate` within the `Registry` - e.g. `Git` package :green_circle:

    ![Git_registry2](https://user-images.githubusercontent.com/33318890/189706627-db6bc41d-c876-4e66-83f5-17178a453bb1.png)

    ```
    root@ip-172-31-8-236:/home/qa# sqlite3 /var/ossec/queue/db/001.db "select * from sys_programs where instr(name, 'Git')"
    0|2022/09/12 15:29:16|win|Git|||0|The Git Development Community|20220714|2.37.1|x86_64||||C:\Program Files\Git\|0|||e66a693cecbcbad5dce7cc4efdce279bfff13557|adb375dadf226df40532f228b14e260628945aa4
    ```

    After replacing the `DisplayedVersion` value from `2.37.1` to `13` via `Registry` and restarting the agent:
    ```
    root@ip-172-31-8-236:/home/qa# sqlite3 /var/ossec/queue/db/001.db "select * from sys_programs where instr(name, 'Git')"
    0|2022/09/12 16:03:59|win|Git|||0|The Git Development Community|20220714|13|x86_64||||C:\Program Files\Git\|0|||008dd795fe12f8a88afc26c0c571915c53c2758b|6ced33846580e345d62881ee8bcd4743ad98d4c0
    ```
    We can see how the `install_time` value `20220714` doesn't change even forcing via Registry, it still have the `InstallDate` field value from the `Registry`
    ![GitInstallDate](https://user-images.githubusercontent.com/33318890/189708848-27ba12a4-1cf3-4218-82b8-063c7949f42d.png)

    
  - Check this workaround with a package that is already installed :red_circle:

    We can see in the Control Panel's picture above that `Vim` package installation date is `7/14/2022`. 
    
    ```
    root@ip-172-31-8-236:/home/qa# sqlite3 /var/ossec/queue/db/001.db "select * from sys_programs where instr(name, 'Vim')"
    0|2022/09/12 15:29:16|win|Vim 8.2|||0|Bram Moolenaar et al.||8.2|x86_64|||||0|||ea24f5c04f3011b126bc6f82d763e7617512a231|695fd9e2c1b8c454bd39923e15e30c2e40be1a50
    ```

    After forcing the new version value via `Registry` we can see that the `install_time` still missing and the control panel date is updated.
    
    ![VimUpdated](https://user-images.githubusercontent.com/33318890/189708315-6a6f1e08-ec88-483d-958b-0c22e38cf81d.png)
    ```
    root@ip-172-31-8-236:/home/qa# sqlite3 /var/ossec/queue/db/001.db "select * from sys_programs where instr(name, 'Vim')"
    0|2022/09/12 16:29:48|win|Vim 8.2|||0|Bram Moolenaar et al.||9|x86_64|||||0|||f2a71faa3fa43b72a15dc2d4eec66af2329a484c|afecceaa29560c25cc241e1e1399eac3564e30ec
    ```

</details>

## Upgrade

## Fresh install

**Comment by jmv74211** [comment]
## Closing conclusion 👍🏼  

Everything seems to be working properly after the proposed fixes.
