### ISSUE TITLE
Integration tests: Add update field and new options in the CPE Helper

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh-qa#2950]
|Related issue|
|---|
|https://github.com/wazuh/wazuh/issues/8434|

## Description

After the following changes in the CPE Helper: https://github.com/wazuh/wazuh/compare/4.4...8434-update-field-in-cpe-helper, it is necessary to cover the new fields and variables added in the CPE_Helper to check that everything works as expected.
The new field would be: `update`.
This `update` is obtained with the options, using a regex to the `product name`:
- `VU_SET_UPDATE_IF_PROD_MATCHES`
- `VU_SET_UPDATE_ONLY_IF_PROD_MATCHES`

And in addition, a variable `$(UPDATE)` has been created that can be used in both `msu_name` and `update`, and is obtained from the regex of the `update` field.

However, before making these changes, it would be necessary to make the following issues to cover all existing options for the CPE Helper:
- https://github.com/wazuh/wazuh-qa/issues/796
- https://github.com/wazuh/wazuh-qa/issues/798

These options can be checked in the following section of the documentation:
https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/cpe-helper.html

### Subtasks

- [x] Research
- [x] Development
    - [x] Add new `update` field in the `test_cases` of CPE_Helper integration test
    - [x]  In the testing phase it was determined that the code added in the previous process was incomplete, for this reason it is necessary to modify part of the code and add new code.
- [x] Testing phase
    - [x] Check that the tests pass after adding the `update` field
- [ ] Review
- [ ] Completed

**Comment by fedepacher** [comment]
# Update 2023/01/19

At this point, it has read the documentation and has started with the test based on issues [796](https://github.com/wazuh/wazuh-qa/issues/796) and [798](https://github.com/wazuh/wazuh-qa/issues/798).

**Comment by fedepacher** [comment]
# Update 2023/01/20

To proceed with this issue it will wait for issues [796](https://github.com/wazuh/wazuh-qa/issues/796) and [798](https://github.com/wazuh/wazuh-qa/issues/798) to be merged.
