### ISSUE TITLE
Release 4.3.4-RC1 - Manual tests: Demo environment

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#2960]
The following issue aims to run the specified test for the current release candidate, report the results, and open new issues for any encountered errors.

## Test information
|                         |                                            |
|-------------------------|--------------------------------------------|
| **Test name**           |Demo environment|
| **Category**            |Wazuh App|
| **Deployment option**   |Demo environment|
| **Main release issue**  |https://github.com/wazuh/wazuh/issues/13669|
| **Release candidate #** |RC1| 

## Test tasks
- [ ]  (**T1**): - No errors or warnings found in logs
- [ ]  (**T2**): - The daemons are running with the correct user
- [ ]  (**T3**): - The status of the Wazuh Indexer clusters is as expected.
- [ ]  (**T4**): - No errors in the browser's developer console when browsing the App
- [ ]  (**T5**): - Alerts are being generated for each of the modules configured for this purpose.
- [ ]  (**T6**): - No warning symbols in Discover when expanding a document.

## Auditors validation

The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [ ] @jmv74211 
- [ ] @alberpilot 
- [ ] @gdiazlo

**Comment by BelenValdivia** [comment]
## Task 1: No errors or warnings found in logs

### Agents

<details>
<summary>Amazon Linux /summary>

- `journalctl -xe -u wazuh-agent.service`:

**Comment by BelenValdivia** [comment]
## Task 2: The daemons are running with the correct user

### Agents

<details>
<summary>Amazon Linux :green_circle: </summary>

```
root     15276  0.0  0.2  37708  2892 ?        Sl   15:07   0:00 /var/ossec/bin/wazuh-execd
wazuh    15285  0.0  0.5 263692  5352 ?        Sl   15:07   0:05 /var/ossec/bin/wazuh-agentd
root     15300  0.0  0.8 203684  8336 ?        SNl  15:07   0:10 /var/ossec/bin/wazuh-syscheckd
root     15314  0.0  0.4 480232  4704 ?        Sl   15:07   0:02 /var/ossec/bin/wazuh-logcollector
root     15336  0.0  1.5 740780 15380 ?        Sl   15:07   0:04 /var/ossec/bin/wazuh-modulesd
```
</details>

<details>
<summary>RHEL :green_circle: </summary>

```
root     29908  0.0  0.0  35520  1628 ?        Sl   15:36   0:01 /var/ossec/bin/wazuh-execd
wazuh    29920  0.0  0.0 261256  3120 ?        Sl   15:36   0:11 /var/ossec/bin/wazuh-agentd
root     29935  0.1  0.2 480420  8980 ?        SNl  15:36   0:29 /var/ossec/bin/wazuh-syscheckd
root     29948  0.0  0.0 477936  2648 ?        Sl   15:36   0:08 /var/ossec/bin/wazuh-logcollector
root     29972  0.0  0.8 1033468 31432 ?       Sl   15:36   0:12 /var/ossec/bin/wazuh-modulesd
```

</details>

<details>
<summary>Ubuntu :green_circle: </summary>

```
root     10178  0.0  0.3  42728  3076 ?        Sl   15:07   0:00 /var/ossec/bin/wazuh-execd
wazuh    10189  0.0  0.5 268672  5684 ?        Sl   15:07   0:05 /var/ossec/bin/wazuh-agentd
root     10203  0.0  0.8 208128  8140 ?        SNl  15:07   0:08 /var/ossec/bin/wazuh-syscheckd
root     10216  0.0  0.4 485124  4652 ?        Sl   15:07   0:02 /var/ossec/bin/wazuh-logcollector
root     10255  0.0  1.4 748316 14312 ?        Sl   15:07   0:04 /var/ossec/bin/wazuh-modulesd
```

</details>

<details>
<summary>Centos :green_circle: </summary>

```
root      6368  0.0  0.1  35436  1476 ?        Sl   15:07   0:01 /var/ossec/bin/wazuh-execd
wazuh     6380  0.0  0.3 261256  3060 ?        Sl   15:07   0:09 /var/ossec/bin/wazuh-agentd
root      6395  0.0  0.7 201156  7216 ?        SNl  15:07   0:12 /var/ossec/bin/wazuh-syscheckd
root      6409  0.0  1.2 477812 12560 ?        Sl   15:07   0:04 /var/ossec/bin/wazuh-logcollector
root      6431  0.0  2.2 738416 22020 ?        Sl   15:07   0:06 /var/ossec/bin/wazuh-modulesd
```

</details>

<details>
<summary>Debian :green_circle: </summary>

```
root      6878  0.0  0.2  41412  2588 ?        Sl   15:07   0:00 /var/ossec/bin/wazuh-execd
wazuh     6889  0.0  0.5 267440  5204 ?        Sl   15:07   0:05 /var/ossec/bin/wazuh-agentd
root      6903  0.0  0.7 206680  7268 ?        SNl  15:07   0:07 /var/ossec/bin/wazuh-syscheckd
root      6920  0.0  0.4 484060  4356 ?        Sl   15:07   0:02 /var/ossec/bin/wazuh-logcollector
root      6959  0.0  1.1 744888 11924 ?        Sl   15:07   0:04 /var/ossec/bin/wazuh-modulesd
```

</details>

<details>
<summary>Windows (WIP)</summary>
</details>

### Managers

<details>
<summary>Master env 1 :green_circle: </summary>

```
wazuh    24405  0.0  2.7 830044 110188 ?       Sl   15:07   0:28 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
wazuh    24428  0.0  0.1  38440  4260 ?        Sl   15:07   0:06 /var/ossec/bin/wazuh-integratord
root     24450  0.2  0.1 259704  5820 ?        Sl   15:07   1:24 /var/ossec/bin/wazuh-authd
wazuh    24467  0.0  0.5 775172 22928 ?        Sl   15:07   0:23 /var/ossec/bin/wazuh-db
wazuh    24479  0.0  1.5 317656 62304 ?        S    15:07   0:01 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
wazuh    24482  0.0  1.5 465576 63620 ?        S    15:07   0:25 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
root     24497  0.0  0.0  38480  3184 ?        Sl   15:07   0:00 /var/ossec/bin/wazuh-execd
wazuh    24512  4.3  3.9 1292884 159152 ?      Sl   15:07  22:23 /var/ossec/bin/wazuh-analysisd
root     24524  0.0  0.2 335312  8700 ?        SNl  15:07   0:12 /var/ossec/bin/wazuh-syscheckd
wazuh    24545  0.4  0.2 1187020 8296 ?        Sl   15:07   2:09 /var/ossec/bin/wazuh-remoted
root     24577  0.0  0.1 480880  5276 ?        Sl   15:07   0:02 /var/ossec/bin/wazuh-logcollector
wazuh    24624  0.0  0.0  38456  3152 ?        Sl   15:07   0:00 /var/ossec/bin/wazuh-monitord
root     24648  6.1  8.5 1458996 341348 ?      Sl   15:07  31:23 /var/ossec/bin/wazuh-modulesd
wazuh    24787  0.1  1.5 444412 60356 ?        Sl   15:07   0:37 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh-clusterd.py
wazuh    24796  0.0  1.0 279676 43460 ?        S    15:07   0:19 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh-clusterd.py
wazuh    24799  0.0  1.0 361604 43400 ?        S    15:07   0:19 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh-clusterd.py
```

</details>

<details>
<summary>Worker env 1</summary>

```
wazuh    17055  0.0  2.3 740896 94272 ?        Sl   15:25   0:11 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
wazuh    17081  0.0  0.1  38436  4328 ?        Sl   15:25   0:01 /var/ossec/bin/wazuh-integratord
wazuh    17098  0.1  0.5 775164 21100 ?        Sl   15:25   0:31 /var/ossec/bin/wazuh-db
root     17122  0.0  0.0  38476  3144 ?        Sl   15:25   0:00 /var/ossec/bin/wazuh-execd
wazuh    17124  0.0  1.4 309332 57240 ?        S    15:25   0:00 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
wazuh    17127  0.0  1.5 463988 59892 ?        S    15:25   0:00 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
wazuh    17143  0.0  2.6 1292680 105732 ?      Sl   15:25   0:16 /var/ossec/bin/wazuh-analysisd
root     17155  0.0  0.2 269664  8512 ?        SNl  15:25   0:12 /var/ossec/bin/wazuh-syscheckd
wazuh    17176  0.1  0.1 1178484 7568 ?        Sl   15:25   0:54 /var/ossec/bin/wazuh-remoted
root     17208  0.0  0.1 480872  5072 ?        Sl   15:25   0:02 /var/ossec/bin/wazuh-logcollector
wazuh    17232  0.0  0.0  38452  3224 ?        Sl   15:26   0:01 /var/ossec/bin/wazuh-monitord
root     17279  5.4  7.4 1205976 297844 ?      Sl   15:26  26:53 /var/ossec/bin/wazuh-modulesd
wazuh    17406  0.1  1.4 590520 59132 ?        Sl   15:26   0:34 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh-clusterd.py
wazuh    17625  0.0  1.1 287428 45156 ?        S    15:26   0:10 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh-clusterd.py
wazuh    18346  0.0  1.1 440048 44180 ?        S    15:30   0:00 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh-clusterd.py
```

</details>

<details>
<summary>Master env 2 :green_circle: </summary>

```
wazuh    24180  0.0  2.7 830300 110192 ?       Sl   15:07   0:24 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
wazuh    24203  0.0  0.1  38440  4312 ?        Sl   15:07   0:06 /var/ossec/bin/wazuh-integratord
root     24225  0.2  0.1 259708  5808 ?        Sl   15:07   1:26 /var/ossec/bin/wazuh-authd
wazuh    24242  0.0  0.4 709628 19132 ?        Sl   15:07   0:19 /var/ossec/bin/wazuh-db
wazuh    24254  0.0  1.5 317500 61952 ?        S    15:07   0:00 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
wazuh    24257  0.0  1.5 465320 63336 ?        S    15:07   0:19 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
root     24272  0.0  0.0  38480  3168 ?        Sl   15:07   0:00 /var/ossec/bin/wazuh-execd
wazuh    24287  4.2  3.4 1292636 138632 ?      Sl   15:07  21:55 /var/ossec/bin/wazuh-analysisd
root     24299  0.0  0.2 335308  8640 ?        SNl  15:07   0:12 /var/ossec/bin/wazuh-syscheckd
wazuh    24320  0.1  0.1 1186624 7036 ?        Sl   15:07   0:43 /var/ossec/bin/wazuh-remoted
root     24352  0.0  0.1 480880  5020 ?        Sl   15:07   0:02 /var/ossec/bin/wazuh-logcollector
wazuh    24375  0.0  0.0  38452  3244 ?        Sl   15:07   0:00 /var/ossec/bin/wazuh-monitord
root     24423  4.5  8.5 1524404 340132 ?      Sl   15:07  23:23 /var/ossec/bin/wazuh-modulesd
wazuh    24543  0.0  1.1 427680 45816 ?        Sl   15:07   0:07 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh-clusterd.py
wazuh    24553  0.0  1.0 279664 43012 ?        S    15:07   0:09 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh-clusterd.py
wazuh    24558  0.0  1.0 361592 43000 ?        S    15:07   0:09 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh-clusterd.py
```

</details>

### Wazuh Indexer

<details>
<summary>Bootstrap</summary>

`wazuh-i+ 15535  3.2 56.7 7153080 4588564 ?     Ssl  14:40  17:59 /usr/share/wazuh-indexer/jdk/bin/java -Xshare:auto -Dopensearch.networkaddress.cache.ttl=60 -Dopensearch.networkaddress.cache.negative.ttl=10 -XX:+AlwaysPreTouch -Xss1m -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djna.nosys=true -XX:-OmitStackTraceInFastThrow -XX:+ShowCodeDetailsInExceptionMessages -Dio.netty.noUnsafe=true -Dio.netty.noKeySetOptimization=true -Dio.netty.recycler.maxCapacityPerThread=0 -Dio.netty.allocator.numDirectArenas=0 -Dlog4j.shutdownHookEnabled=false -Dlog4j2.disable.jmx=true -Djava.locale.providers=SPI,COMPAT -Xms3948m -Xmx3948m -XX:+UseG1GC -XX:G1ReservePercent=25 -XX:InitiatingHeapOccupancyPercent=30 -Djava.io.tmpdir=/tmp/opensearch-10545042338456622215 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=data -XX:ErrorFile=/var/log/wazuh-indexer/hs_err_pid%p.log -Xlog:gc*,gc+age=trace,safepoint:file=/var/log/wazuh-indexer/gc.log:utctime,pid,tags:filecount=32,filesize=64m -Dclk.tck=100 -Djdk.attach.allowAttachSelf=true -Djava.security.policy=file:///usr/share/wazuh-indexer/plugins/opensearch-performance-analyzer/pa_config/opensearch_security.policy -XX:MaxDirectMemorySize=2069889024 -Dopensearch.path.home=/usr/share/wazuh-indexer -Dopensearch.path.conf=/etc/wazuh-indexer -Dopensearch.distribution.type=rpm -Dopensearch.bundled_jdk=true -cp /usr/share/wazuh-indexer/lib/* org.opensearch.bootstrap.OpenSearch -p /run/wazuh-indexer/wazuh-indexer.pid --quiet
`

</details>

**Comment by BelenValdivia** [comment]
## Task 3: The status of the Wazuh Indexer clusters is as expected :green_circle: 

```
[root@ip-10-0-0-165 wazuh-user]# curl -k -u USER:PASS https://10.0.0.165:9200/_cat/nodes?v
ip         heap.percent ram.percent cpu load_1m load_5m load_15m node.role master name
10.0.0.165           46          85   1    0.00    0.00     0.00 dimr      -      node-7
10.0.2.188            6          83   1    0.10    0.06     0.01 dimr      -      node-2
10.0.2.12            29          87   1    0.00    0.00     0.00 dimr      -      node-3
10.0.2.226           48          88   1    0.12    0.07     0.02 dimr      *      node-1

```

**Comment by BelenValdivia** [comment]
## Task 4 No errors in browser's developer console when browsing the App

**Comment by BelenValdivia** [comment]
## Task 5: Alerts are being generated for each of the modules configured for this purpose 🟢

**Comment by BelenValdivia** [comment]
## Task 6: No warning symbols in Discover when expanding a document 🟢
