### ISSUE TITLE
Release 4.3.4 - Release Candidate 1 - E2E UX tests - Active Response

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#2964]
The following issue aims to run the specified test for the current release candidate, report the results, and open new issues for any encountered errors.

## Test information
|                         |                                            |
|-------------------------|--------------------------------------------|
| **Test name**           | Active Response |
| **Category**            | Active Response|
| **Main E2E UX test issue**  | https://github.com/wazuh/wazuh/issues/13670                                          |
| **Release candidate #** | RC1                                          |

## Installation procedure
Wazuh indexer:
- Installation: [Quickstart](https://documentation.wazuh.com/current/quickstart.html)
- Type: -
- OS: Red Hat Enterprise Linux 7

Wazuh manager:
- Installation: [Quickstart](https://documentation.wazuh.com/current/quickstart.html)
- Type: -
- OS: Red Hat Enterprise Linux 7

Wazuh dashboard:
- Installation: [Quickstart](https://documentation.wazuh.com/current/quickstart.html)
- OS: Red Hat Enterprise Linux 7

Wazuh agent:
- Installation: [Installing Wazuh agents](https://documentation.wazuh.com/current/installation-guide/wazuh-agent/index.html)
- OS: Red Hat Enterprise Linux 7

## Test description

- [ ] Blocking a malicious actor. ([here](https://documentation.wazuh.com/current/proof-of-concept-guide/block-malicious-actor-ip-reputation.html))
- [ ] Detecting and removing malware using VirusTotal integration. ([here](https://documentation.wazuh.com/current/proof-of-concept-guide/detect-remove-malware-virustotal.html))
- [ ] Integrattion of YARA with Wazuh. ([here](https://wazuh.com/blog/how-to-integrate-yara-with-wazuh/))

## Test report procedure

All test results must have one of the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed result. |
| :yellow_circle:  | There is at least one expected failure or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. 

An extended report of the test results can be attached as a ZIP or TXT file. Please attach any documents, screenshots, or tables to the issue update with the results. This report can be used by the auditors to dig deeper into any possible failures and details.

## Conclusions

All tests have been executed and the results can be found in the issue updates.

|                |             |                     |                |
|----------------|-------------|---------------------|----------------|
| **Status**     | **Test**    | **Failure type**    | **Notes**      |

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [ ]

**Comment by Deblintrake09** [comment]
# Task 2 - Detecting and removing malware using VirusTotal integration

**Comment by Deblintrake09** [comment]
# Task 3 - Integration of YARA with Wazuh
