### ISSUE TITLE
Manual testing - New multigroup generation mechanism - Backport to 4.3

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh-qa#2967]
|Related issue|
|---|
|https://github.com/wazuh/wazuh/issues/13675|

### Description

In order to validate the changes of the branch [backport_merged_optimization](https://github.com/wazuh/wazuh/tree/backport_merged_optimization), some manual testing of the multigroup generation mechanism enhancement is required.

A description of the problem and the improvement introduced can be found in the following issues:

## Proposed Checks
- [x] [Improve the multi-group generation mechanism](https://github.com/wazuh/wazuh/issues/11054)
  - [x] Verify that the multi-group is generated correctly (check the generation of the `merged.mg` file)
  - [x] Verify that the `merged.mg` file is generated only when any file inside `/var/ossec/etc/shared/{group-name}` has changed 
  - [x] Verify that the multigroup folder is deleted when no agents are associated with it 
- [x] [Pushing the shared custom folder into the agent host does not work correctly, If the agent belongs more than one group](https://github.com/wazuh/wazuh/issues/8593)
  - [x] Verify that a custom folder is pushed correctly into the Agent when it belongs to a multigroup 
  - [x] Verify that a custom folder is upload correctly into the Agent when the folder contains different files for each group of the Agent 
  - [x] Check what if there is group priority when a file with the same name is in to group folders
- [x] [The 'guess_agent_group' mechanism does not work](https://github.com/wazuh/wazuh/issues/13071)
   - [x] Verify that the group is correctly assigned after it gets reconnected

**Comment by mauromalara** [comment]
## Conclusion 🔵

WIP.

**Comment by mauromalara** [comment]
## Task 1: Test manually [Improve the multi-group generation mechanism](https://github.com/wazuh/wazuh/issues/11054)

1. I created 2 VMs
2. I installed the manager and indexer in one of them
3. I created a group `/var/ossec/bin/agent_groups -a -g mauro`
4. I created another group `/var/ossec/bin/agent_groups -a -g mauro_2`
5. I installed the agent in the other VM using the deployment variables `WAZUH_MANAGER="192.168.56.8" WAZUH_AGENT_GROUP="default,mauro" yum install wazuh-agent -y`
6. I added the group "mauro_2" to the agent `/var/ossec/bin/agent_groups -a -i 001 -g mauro_2`
7. I checked that all groups were assigned correctly by running `curl -k -X GET "https://localhost:55000/agents?pretty=true&agents_list=001&select=group" -H  "Authorization: Bearer $TOKEN"`
8. I modified the mauro_2 `agent.conf` and I saved its content
9. I checked if the agent had the `<auto_restart>` option enabled and if the centralized configuration was synced with the agent configuration by running `curl -k -X GET "https://localhost:55000/agents/001/group/is_sync?pretty=true" -H  "Authorization: Bearer $TOKEN"`

I realized that the multi-group folder in `/var/ossec/var/multigroups/` was updated after a minute and not when the centralized configuration was changed. I did it by running `watch -n0 'ls -lt /var/ossec/var/multigroups/'`.

**Comment by mauromalara** [comment]
## Task 2: [Pushing the shared custom folder into the agent host does not work correctly, If the agent belongs more than one group.](https://github.com/wazuh/wazuh/issues/8593)


WIP.

**Comment by mauromalara** [comment]
## Task 3: Test manually ["The 'guess_agent_group' mechanism does not work"](https://github.com/wazuh/wazuh/issues/13071) 🔴

### Conclusion 🔴

1. The agent only has the "default" group:
```
[root@manual-testing-manager ~]# /var/ossec/bin/agent_groups -s -i 009
The agent 'manual-testing-agent' with ID '009' belongs to groups: default.
```

### 

1. Edit the `/var/ossec/etc/local_internal_options.conf` on manager:

> remoted.guess_agent_group=1

3. Restart the manager to apply the configuration

4. Disable the `auto-enrollment` in the agent configuration (by adding `<enabled>no</enabled>` in the `<enrollment>` tag)
   3.1. Remove the agent using the `manage_agents` script: `/var/ossec/bin/manage_agents -r 004`
   3.2. Register the agent: `/var/ossec/bin/manage_agents -a 192.168.56.9 -n manual-testing-agent`
   3.3. Copy the key in `client.keys` from manager to agent
   3.4. Restart the agent

5. Assign a group to the agent:

> /var/ossec/bin/agent_groups -q -a -i 008 -g mauro

6. Check with the `agent_groups` script if the registered agent was assigned to the group `mauro`

> /var/ossec/bin/agent_groups -s -i 008

7. Remove the key from `client.keys` on the agent

8. Repeat step 3

9. Check with the `agent_groups` script if the registered agent was assigned to the group `mauro`

> /var/ossec/bin/agent_groups -s -i 009

**Comment by Deblintrake09** [comment]
## Task 1: Test manually [Improve the multi-group generation mechanism](https://github.com/wazuh/wazuh/issues/11054) 🟢

### Use cases

<details>
<summary>Verify that the multi-group is generated correctly (check the generation of the `merged.mg` file) :green_circle: </summary>

- Create 2 groups called 'TestGroup1' and 'TestGroup2' respectively and verify that no agents are assigned to them
```
/var/ossec/bin/agent_groups -a -g TestGroup1 -q
Group 'TestGroup1' created.
/var/ossec/bin/agent_groups -a -g TestGroup2 -q
Group 'TestGroup2' created.

/var/ossec/bin/agent_groups
Groups (3):
  TestGroup1 (0)
  TestGroup2 (0)
  default (1)
Unassigned agents: 0.
```
- Assign both groups to the agent
```
/var/ossec/bin/agent_groups -a -i 001 -g TestGroup1
Group 'TestGroup1' added to agent '001'.
/var/ossec/bin/agent_groups -a -i 001 -g TestGroup2
Group 'TestGroup2' added to agent '001'.
```
- Check that the multigroup has been generated:
```
# ls /var/ossec/var/multigroups/
0138e6d1
```
- Check the merged.mg file content:
```
!357 agent.conf
<!-- Source file: default/agent.conf -->
<agent_config>
  <!-- Shared agent configuration here -->
</agent_config>
  <!-- Source file: mauro/agent.conf -->
<agent_config>
  <!-- Shared agent configuration here -->
</agent_config>
  <!-- Source file: mauro_2/agent.conf -->
<agent_config>
  <!-- Shared agent configuration here -->
</agent_config>
```

</details>

<details>
<summary>Verify that the `merged.mg` file is generated only when any file inside `/var/ossec/etc/shared/{group-name}` has changed :green_circle: </summary>

- Edit the agent.conf file of the first 2 groups ("default,TestGroup1") with the same content:
```
<localfile>
    <log_format>syslog</log_format>
    <location>/var/logs/*</location>
</localfile>
```
- Check that the merged.mg file was updated:
```
# stat -c %y /var/ossec/var/multigroups/bac80533/merged.mg
2022-07-06 14:42:30.001148094 +0000

# date
Wed Jul  6 14:43:05 UTC 2022
```
- Modify the content of the agent.conf file of the last group assigned ("Testgroup2")
```
<localfile>
    <log_format>syslog</log_format>
    <location>/var/logs/*</location>
    <exclude>/var/logs/e*</exclude>
</localfile>
```
- Check that the merged.mg content is correct:
```
!695 agent.conf
<!-- Source file: default/agent.conf -->
<agent_config>

  <!-- Shared agent configuration here -->
  <localfile>
    <log_format>syslog</log_format>
    <location>/var/logs/*</location>
  </localfile>

</agent_config>
<!-- Source file: TestGroup2/agent.conf -->
<agent_config>

  <!-- Shared agent configuration here -->
<localfile>
    <log_format>syslog</log_format>
    <location>/var/logs/*</location>
    <exclude>/var/logs/e*</exclude>
</localfile>

</agent_config>
<!-- Source file: TestGroup1/agent.conf -->
<agent_config>

  <!-- Shared agent configuration here -->
  <localfile>
    <log_format>syslog</log_format>
    <location>/var/logs/*</location>
  </localfile>

</agent_config>
```
- Verify that the configuration in the agent is correct:
```
<!-- Source file: default/agent.conf -->
<agent_config>

  <!-- Shared agent configuration here -->
  <localfile>
    <log_format>syslog</log_format>
    <location>/var/logs/*</location>
  </localfile>

</agent_config>
<!-- Source file: TestGroup2/agent.conf -->
<agent_config>

  <!-- Shared agent configuration here -->
<localfile>
    <log_format>syslog</log_format>
    <location>/var/logs/*</location>
    <exclude>/var/logs/e*</exclude>
</localfile>

</agent_config>
<!-- Source file: TestGroup1/agent.conf -->
<agent_config>

  <!-- Shared agent configuration here -->
  <localfile>
    <log_format>syslog</log_format>
    <location>/var/logs/*</location>
  </localfile>

</agent_config>
```
</details>

<details>
<summary>Verify that the multigroup folder is deleted when no agents are associated with it :green_circle: </summary>

- Delete the agent from the highest priority group (last added)
- Check that the `agent.conf` file of the Agent was correctly updated
```
<!-- Source file: default/agent.conf -->
<agent_config>

<localfile>
    <log_format>syslog</log_format>
    <location>/var/logs/*</location>
</localfile>

</agent_config>
<!-- Source file: mauro/agent.conf -->
<agent_config>

<localfile>
    <log_format>syslog</log_format>
    <location>/var/logs/*</location>
</localfile>

</agent_config>
```
- Delete the agent from the first added group
- Check that the multigroups folder was deleted after removing the agent from both groups
```
# ls -l /var/ossec/var/multigroups/
total 0
```
- Check if there were any errors in the log
```
# [ -z $(egrep -iE "ERROR|WARNING" /var/ossec/logs/ossec.log) ] && echo "NO ERRORS OR WARNINGS." || echo "ERRORS OR WARNINGS FOUND."

NO ERRORS OR WARNINGS.
```
- Verify the content of the agent.conf file in the agent endpoint:
```
<agent_config>

<localfile>
    <log_format>syslog</log_format>
    <location>/var/logs/*</location>
</localfile>

</agent_config>
```
</details>

**Comment by Deblintrake09** [comment]
# Task 2: Test manually [Pushing the shared custom folder into the agent host does not work correctly, If the agent belongs more than one group.](https://github.com/wazuh/wazuh/issues/8593) 🟢

### Use cases

<details>
<summary>Verify that a custom folder is pushed correctly into the Agent when it belongs to a multigroup :green_circle: </summary>

- Remove the groups `TestGroup1` and `TestGroup2` from the agent (leaving only the 'default' group)
- Create a directory and added some files to it (in the "default" group folder in the manager)
```
# ls -l /var/ossec/etc/shared/default/testfolder/
total 8
-rw-r--r-- 1 root root 75 Jul  6 15:12 file1.yml
-rw-r--r-- 1 root root 83 Jul  6 15:12 file2.yml
```
- Add the group `Testgroup1` to the Agent
```
# /var/ossec/bin/agent_groups -a -i 001 -g TestGroup1 -q
Group 'TestGroup1' added to agent '001'.
```
- Check if the folder has been transformed into an empty file in the Agent
```
# ls -l /var/ossec/etc/shared/ | grep testfolder

drwxr-x--- 2 wazuh wazuh     40 Jul  6 15:12 testfolder
```
- Check if there were any errors in the logs
```
# [ -z $(egrep -iE "ERROR|WARNING" /var/ossec/logs/ossec.log) ] && echo "NO ERRORS OR WARNINGS." || echo "ERRORS OR WARNINGS FOUND."

NO ERRORS OR WARNINGS.
```
- Add the group `Testgroup2` to the Agent
```
# /var/ossec/bin/agent_groups -a -i 001 -g TestGroup2 -q
Group 'TestGroup2' added to agent '001'.
```

- Check if the folder has been transformed into an empty file in the Agent
```
# ls -la  /var/ossec/etc/shared/ | grep testfolder
drwxr-x--- 2 wazuh wazuh     40 Jul  6 15:14 testfolder
```

</details>

<details>
<summary>Verify that a custom folder is upload correctly into the Agent when the folder contains different files for each group of the Agent :green_circle: </summary>

- Create a directory and added some files to it (in the "default" group folder in the manager)
```
ls -l /var/ossec/etc/shared/default/testfolder/
total 8
-rw-r--r-- 1 root root 75 Jul  6 15:12 file1.yml
-rw-r--r-- 1 root root 83 Jul  6 15:12 file2.yml
```
- Copy the created folder in the "TestGroup1" group folder
```
# cp -r /var/ossec/etc/shared/default/testfolder /var/ossec/etc/shared/TestGroup1
# ls -l /var/ossec/etc/shared/TestGroup1/testfolder/
total 8
-rw-r--r-- 1 root root 75 Jul  6 15:17 file1.yml
-rw-r--r-- 1 root root 83 Jul  6 15:17 file2.yml
```
- Add a different file in the TestGroup1 group inside the custom folder
```
# ls -l /var/ossec/etc/shared/TestGroup1/testfolder/
total 10
-rw-r--r-- 1 root root 81 Jul  6 15:19 file3.yml
```
- Check if the folder has not been transformed into an empty file in the Agent
```
# ls -la  /var/ossec/etc/shared/ |grep test
drwxr-x--- 2 wazuh wazuh     57 Jul  6 15:20 testfolder

```
- Check if all files are in the custom folder inside the Agent
```
# ls -la  /var/ossec/etc/shared/testfolder/
total 16
-rw-r--r-- 1 wazuh wazuh   75 Jul  6 15:20 file1.yml
-rw-r--r-- 1 wazuh wazuh   83 Jul  6 15:20 file2.yml
-rw-r--r-- 1 wazuh wazuh   81 Jul  6 15:20 file3.yml
```
- Check if there were any errors in the logs
```
# [ -z $(egrep -iE "ERROR|WARNING" /var/ossec/logs/ossec.log) ] && echo "NO ERRORS OR WARNINGS." || echo "ERRORS OR WARNINGS FOUND."

NO ERRORS OR WARNINGS.
```
</details>

**Comment by Deblintrake09** [comment]
# Task 3: Test manually ["The 'guess_agent_group' mechanism does not work"](https://github.com/wazuh/wazuh/issues/13071) 🟢

### Use cases

<details>
<summary>Verify that the group is correctly assigned after it gets reconnected :green_circle: </summary>

1. Edit the `/var/ossec/etc/local_internal_options.conf` on manager:
```
remoted.guess_agent_group=1
```
2. Restart the manager to apply the configuration

3. Assign a group to the agent and delete the default group from the agent (We do this because otherwise the agent will be assigned to a multigroup and the hash will be different from the added group):
```
# /var/ossec/bin/agent_groups -a -i 001 -g TestGroup1 -q
Group 'TestGroup1' added to agent '001'.
# /var/ossec/bin/agent_groups -r -i 001 -g default -q
Agent '001' removed from 'default'.

```
4. Check with the `agent_groups` script if the registered agent was assigned to the group `Testgroup1`
```
# /var/ossec/bin/agent_groups -s -i 001
The agent 'Linux1' with ID '001' belongs to groups: TestGroup1.
```
5. Disconnect the agent and connect it again
   5.0. Stop de agent `systemctl stop wazuh-agent`
   5.1. In the manager, remove the agent using the `manage_agents` script:
   ```
   # /var/ossec/bin/manage_agents -r {agent_id}
   Available agents: 
      ID: 001, Name: Linux1, IP: any
   Provide the ID of the agent to be removed (or '\q' to quit): 001
   Confirm deleting it?(y/n): y
   Agent '001' removed.
   ```
   5.2. In the agent, remove the `client.keys` file by running `rm -f /var/ossec/etc/client.keys`
   5.3. Start the agent `systemctl start wazuh-agent`

6. Check with the `agent_groups` script if the registered agent was assigned to the group `TestGroup1`
```
# /var/ossec/bin/agent_groups -s -i 002
The agent 'manual-testing-agent' with ID '002' belongs to groups: TestGroup1.
```

</details>
