### ISSUE TITLE
Manual testing - Enhance RPM packages retrieving support - Backport to 4.3

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh-qa#2968]
| Related issue |
|---|
| Original development wazuh/wazuh#10324 |
| Backport to 4.3 wazuh/wazuh#13716 |

# Description

It's desirable to validate that wazuh/wazuh#10324 and its 4.3 backport wazuh/wazuh#13716 works as desired, meaning:

- Wazuh is still capable of retrieving packages from OSes that still use BarkleyDB for its RPM installation
- Wazuh is now capable of retrieving packages from OSes that use new RPM backends like ndb or SQLite

# Test cases
Backward compatibility: distros that should still work
- [x] Centos 5
- [x] Centos 8 and older
- [x] Amazon Linux 1/2
- [x] Fedora 32 and older
- [x] RHEL8 and older

The next distros should now support packages retrieving
- [x] openSUSE Tumbleweed -> Related issue https://github.com/wazuh/wazuh-packages/issues/1036#issuecomment-1012507230, https://github.com/wazuh/wazuh/issues/10191
- [x] Fedora 33 or newer -> Related issue https://github.com/wazuh/wazuh/issues/13553
- [x] Amazon Linux 2022 -> Related issue https://github.com/wazuh/wazuh/issues/13114
- [x] RHEL9

## Configuration details
| Wazuh Commit | Agent Package | Manager Package|
|--|--|--|
| https://github.com/wazuh/wazuh/commit/c16e88e077f9df37ed1808b487276052114d5de1 | https://packages-dev.wazuh.com/warehouse/pullrequests/4.3/rpm/var/wazuh-manager-4.3.4-0.commitc16e88e.x86_64.rpm | https://packages-dev.wazuh.com/warehouse/pullrequests/4.3/rpm/var/wazuh-agent-4.3.4-0.commitc16e88e.x86_64.rpm |
- Local Internal option on Agent:
```
wazuh_modules.debug=2
```

**Comment by Deblintrake09** [comment]
# New Distros Compatibility

**Comment by Deblintrake09** [comment]
# Backward Compatibility checks

<details>
<summary>Check that Syscollector detects packages on Centos 8 :green_circle: </summary>
- Install agent in Centos 8 VM
- Start Agent with Syscollector packages section enabled
- Check agent's `ossec.log`

```
022/06/07 19:04:30 wazuh-modulesd:syscollector[3958] wm_syscollector.c:151 at wm_sys_main(): DEBUG: Starting Syscollector.
2022/06/07 19:06:00 wazuh-modulesd:syscollector[4150] wm_syscollector.c:98 at wm_sys_log(): DEBUG: Sync sent: {"component":"syscollector_packages","data":{"attributes":{"architecture":"noarch","checksum":"7fb70ffeb3198fd06e6302318f5b4b5c85d57698","description":"A firewall daemon with D-Bus interface providing a dynamic firewall","format":"rpm","groups":"Unspecified","install_time":"1628853812","item_id":"039ee97881ddda6a9eb7b689be24d05d0794c48e","name":"firewalld","scan_time":"2022/06/07 19:06:00","size":2018292,"vendor":"CentOS","version":"0.8.2-7.el8_4"},"index":"039ee97881ddda6a9eb7b689be24d05d0794c48e","timestamp":""},"type":"state"}
2022/06/07 19:06:00 wazuh-modulesd:syscollector[4150] wm_syscollector.c:98 at wm_sys_log(): DEBUG: Sync sent: {"component":"syscollector_packages","data":{"attributes":{"architecture":"x86_64","checksum":"22024d3c0251854a8dd42a374a14d4e0c35e5e59","description":"X Composite Extension library","format":"rpm","groups":"System Environment/Libraries","install_time":"1628855158","item_id":"04a90b51d64feba0b5f87b1c5466b25cbf2a3ce0","name":"libXcomposite","scan_time":"2022/06/07 19:06:00","size":35952,"vendor":"CentOS","version":"0.4.4-14.el8"},"index":"04a90b51d64feba0b5f87b1c5466b25cbf2a3ce0","timestamp":""},"type":"state"}

```
- Check packages are present in agents's db on Manager
- Check Packages show in Dashboard
![imagen](https://user-images.githubusercontent.com/14501079/172462692-0fb32cdc-623f-4c90-a279-17e8a8c61fab.png)

</details>
