### ISSUE TITLE
Make tests selectable by tier

### ISSUE THREAD

**Issue by crd1985** [wazuh/wazuh-qa#297]
## Description
Now the tier level can be added to our tests thanks to the marker `tier` in the following way:
```python
@pytest.mark.tier(level=3)
def test_mytest():
    pass
```
Furthermore, all the following commands select the previous test:
```
$pytest --tier 3
$pytest --tier-minimum 0
$pytest --tier-maximum 10
$pytest --tier-minimum 2 --tier-maximum 4
```

## Tasks
- Classify all tests in tiers according to criticality and cost:
- [x] test_ambiguous_confs
- [x] test_audit
- [x] test_basic_usage
- [x] test_benchmark
- [x] test_checks
- [x] test_frequency
- [x] test_ignore
- [x] test_invalid
- [x] test_nodiff
- [x] test_prefilter_cmd
- [x] test_recursion_level
- [x] test_report_changes
- [x] test_restrict
- [x] test_scan
- [x] test_skip
- [x] test_sync
- [x] test_tags

**Comment by Selutario** [comment]
## Summary
This is a very first sketch of the classification of tests based on their importance. Some of the criteria to follow have been:
- The more used and basic is the function that is checked, the more important it is.
- If the test is similar to another one closer to tier 0, the test is less important.
- If the test verifies that the files are ignored or skipped, the test is less important.

## Tiers
### Tier 0
- **test_basic_usage** Verify if syscheck correctly detects basic behaviors, such as creating/modifying/deleting files in different FIM modes.
- **test_scan** Check that scans occur at specific and established times.

### Tier 1
- **test_audit/test_audit.py** Verify the proper working of the most basic and important audit parts.
- **test_audit/test_remove_audit.py** Check folders monitored with Whodata change to Real-time if auditd is not installed.
- **test_audit/test_audit_after_initial_scan.py** Restart auditd and check Wazuh reconnect to auditd.
- **test_windows_audit_interval** 

### Tier 2
- **test_ambiguous_confs/test_ambiguous_complex.py** Verify the correct application of important and different configurations in subdirectories (checks, report_changes).
- **test_ambiguous_confs/test_ambiguous_simple.py** Verify the correct application of important and different configurations such as 'recursion_level', 'report_changes' and different checks.
- **test_follow_symbolic_link/test_monitor_symlink.py** Check what happens with a symlink and its target when syscheck monitors it.

### Tier 3
- **test_checks** Verify different combinations of checks. It is already checked less deeply in test_ambiguous.
- **test_follow_symbolic_link (rest of tests)** 
- **test_moving_files** Verify the behavior of syscheck when moving files from a directory in 'whodata' to another in 'realtime' and vice versa.
- **test_report_changes/test_reports_file_and_nodiff.py** Check if report_changes events and diff truncated files are correct.

### Tier 4
- **test_audit/test_remove_rule_five_times.py** Remove auditd rule using auditctl five times and check Wazuh ignores folder.
- **test_frequency** Checks if a non existing directory is monitored in realtime after the frequency time has passed.
- **test_invalid** Checks if an invalid configuration is detected
- **test_report_changes/test_report_deleted_diff.py** Check if duplicated directories in diff are deleted when changing report_changes to 'no' or deleting the monitored directories.
- **test_restrict** Checks the only files detected are those matching the restrict regex.
- **test_benchmark** Checks syscheckd detects a certain volume of file changes (add, modify, delete).

### Tier 5
- **test_ambiguous_confs/test_ignore_works_over_restrict.py** Checks if the ignore tag prevails over the restrict one when using both in the same directory.
- **test_ignore** Checks files are ignored in subdirectory according to configuration.
- **test_nodiff** Checks files are ignored in subdirectory according to configuration.
- **test_recursion_level**  It is already checked less deeply in test_ambiguous. Checks that events are generated in the first and last 'edge_limit' directory levels.
- **test_skip** Check if syscheck is skipping the directory based on its skip configuration
- **test_sync** Checks if an invalid ignore configuration is detected by catching the warning message displayed on the log.

### Tier 6
- **test_prefilter_cmd** Checks if prelink is installed and syscheck works.
- **test_tags** Checks the tags functionality by applying some tags an ensuring the events raised for the monitored directory has the expected tags.
- **test_process_priority** Check if the ossec-syscheckd service priority is updated correctly using 'process_priority' tag.
