### ISSUE TITLE
Manual testing - Avoids including update_time in task module responses when update_time is null

### ISSUE THREAD

**Issue by Nicogp** [wazuh/wazuh-qa#2978]
### Description

In order to validate the changes of the PR [Avoids including update_time in task module responses when update_time is null](https://github.com/wazuh/wazuh/pull/13662), some manual testing of `agent_upgrade `is required.

The error occurred when the script launched agents to update and then began to check the status of the tasks and in one of them if the update_time field does not match format `'%Y/%m/%d %H:%M:%S'` the script fails.

The script fails because, when wazuh API queries for upgrade_status, it expects the update_time field to have the format '`%Y/%m/%d %H:%M:%S'` or be null, but when the field was null, the task module added it with the value `"0"`

The implemented solution was to remove the `update_time` field from the response when the value is `0` or `null`.

One possible way to test it could be setting [max_threads](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/agent-upgrade.html#max-threads) to 1 in the agent-upgrade module configuration in the manager and then upgrading more than one agent with the `agent_upgrade` script. This way, only one thread will perform the updates, so it will take longer for one of the tasks to go from `Pending` to `In-Progress` and update the update_time field in the `task` database.

## Tasks

- [x] 4.3.4: Reproduce failure to upgrade the Wazuh agent using the agent-upgrade tool. ([details](https://github.com/wazuh/wazuh-qa/issues/2978#issuecomment-1151286522))
- [x] 4.3.5: Clean Install: Upgrade the Wazuh Agent using the agent-upgrade tool. ([details](https://github.com/wazuh/wazuh-qa/issues/2978#issuecomment-1151312722))
- [x]  4.3.4 to 4.3.5: Upgrade the Wazuh Agent using the agent-upgrade tool. ([details]())

**Comment by CamiRomero** [comment]
## Test information
---
First of all, we executed the test cases on a Wazuh manager with the failure in order to check that the problem is replicated

## Test information
|Wazuh version| Wazuh revision | Component|Install type|Install method|Platform|
|---|---|---|---|---|---|
| 4.3.4 | 40316 | [agent-upgrade](https://documentation.wazuh.com/current/user-manual/reference/tools/agent-upgrade.html) | Manager | Packages | CentOS-8 |

|Wazuh version| Wazuh revision | Component|Install type|Install method|Platform|
|---|---|---|---|---|---|
| 4.2.7 | 40222 | [agent-upgrade](https://documentation.wazuh.com/current/user-manual/reference/tools/agent-upgrade.html) | Agent | Packages | CentOS-8 |

<details>
<summary>Upgrade Wazuh agent using agent-upgrade tool :red_circle: </summary>

1. Edit the /var/ossec/etc/ossec.conf configuration on manager adding:
```
  <agent-upgrade>
    <max_threads>1</max_threads>
  </agent-upgrade>
```
With this, we can ensure that only one thread is processing upgrades.

2. Restart the manager in order to apply the changes
3. List outdated agents:
```
/var/ossec/bin/agent_upgrade -l
```
Output: 
![imagen](https://user-images.githubusercontent.com/37776796/172885852-c7703528-bfe8-4c7e-b6c4-00c2e9aeb863.png)

4. Upgrade agents: 
```
/var/ossec/bin/agent_upgrade -a 001 002
```
output: 
![imagen](https://user-images.githubusercontent.com/37776796/172886483-5ddee74a-fc67-4a07-b224-ce295d4af7b8.png)

**Comment by CamiRomero** [comment]
We executed the test cases with the fix development in PR [Avoids including update_time in task module responses when update_time is null](https://github.com/wazuh/wazuh/pull/13662)

## Test information
|Wazuh version| Wazuh revision | Component|Install type|Install method|Platform|
|---|---|---|---|---|---|
| [4.3.4](https://packages-dev.wazuh.com/warehouse/test/4.3/rpm/var/wazuh-manager-4.3.4-2978.qa.09.06.x86_64.rpm) | 40316 | [agent-upgrade](https://documentation.wazuh.com/current/user-manual/reference/tools/agent-upgrade.html) | Manager | Packages | CentOS-8 |

|Wazuh version| Wazuh revision | Component|Install type|Install method|Platform|
|---|---|---|---|---|---|
| 4.2.7 | 40222 | [agent-upgrade](https://documentation.wazuh.com/current/user-manual/reference/tools/agent-upgrade.html) | Agent | Packages | CentOS-8 |

<details>
<summary>Upgrade Wazuh agent using agent-upgrade tool :green_circle: </summary>

1. Edit the /var/ossec/etc/ossec.conf configuration on manager adding:
```
  <agent-upgrade>
    <max_threads>1</max_threads>
  </agent-upgrade>
```
With this, we can ensure that only one thread is processing upgrades.

2. Restart the manager in order to apply the changes
3. List outdated agents:
```
/var/ossec/bin/agent_upgrade -l
```
Output: 
![imagen](https://user-images.githubusercontent.com/37776796/172885852-c7703528-bfe8-4c7e-b6c4-00c2e9aeb863.png)

4. Upgrade agents: 
```
/var/ossec/bin/agent_upgrade -a 001 002
```
output: 

![imagen](https://user-images.githubusercontent.com/37776796/172890165-6bb300db-d586-47bd-815c-78b0c8066cac.png)

**Comment by CamiRomero** [comment]
##  4.3.4 to 4.3.5: Upgrade the Wazuh Agent using the agent-upgrade tool.

<details>
<summary>Package details </summary>

## Test information
|Wazuh version| Wazuh revision |  PR Core | Component|Install type|Install method|Platform|
|---|---|---|---|---|---|---|
| 4.3.4 upgrade to [4.3.5](https://packages-dev.wazuh.com/warehouse/test/4.3/rpm/var/wazuh-manager-4.3.4-2978.qa.09.06.x86_64.rpm) | 40316 | https://github.com/wazuh/wazuh/pull/13662 | [agent-upgrade](https://documentation.wazuh.com/current/user-manual/reference/tools/agent-upgrade.html) | Manager | Packages | CentOS-8 |

|Wazuh version| Wazuh revision | Component|Install type|Install method|Platform|
|---|---|---|---|---|---|
| 4.2.7 | 40222 | [agent-upgrade](https://documentation.wazuh.com/current/user-manual/reference/tools/agent-upgrade.html) | Agent | Packages | CentOS-8 |

</details>

<details>
<summary>Upgrade Wazuh agent using agent-upgrade tool :green_circle: </summary>

1. Dowloaded 4.3.5 package
```
curl -LO https://packages-dev.wazuh.com/warehouse/test/4.3/rpm/var/wazuh-manager-4.3.4-2978.qa.09.06.x86_64.rpm
```

2. Upgrade Wazuh Manager
```
yum upgrade wazuh-manager-4.3.4-2978.qa.09.06.x86_64.rpm
```

3. Edit the /var/ossec/etc/ossec.conf configuration on manager adding:
```
  <agent-upgrade>
    <max_threads>1</max_threads>
  </agent-upgrade>
```
With this, we can ensure that only one thread is processing upgrades.

4. Restart the manager in order to apply the changes
5. List outdated agents:
```
/var/ossec/bin/agent_upgrade -l
```
Output: 
![imagen](https://user-images.githubusercontent.com/37776796/172885852-c7703528-bfe8-4c7e-b6c4-00c2e9aeb863.png)

6. Upgrade agents: 
```
/var/ossec/bin/agent_upgrade -a 001 002
```
Output: 

![imagen](https://user-images.githubusercontent.com/37776796/172890165-6bb300db-d586-47bd-815c-78b0c8066cac.png)
