### ISSUE TITLE
qa-docs: Adapt documentation tool for E2E tests

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#2983]
## Description

After the implementation of the E2E tests done in #2872, we need to document these tests. However, we need first to update some mandatory fields and add new ones for qa-docs to work properly.

## Tasks

- [x] (**T1**): Adapt mandatory fields
- [x] (**T2**): Create necessary fields
- [x] (**T3**): Document tests:
  - [x] `test_audit/`
  - [x] `test_aws_infraestructure_monitoring/`
  - [x] `test_brute_force/`
  - [x] `test_detecting_suspicious_binaries/`
  - [x] `test_docker_monitoring/`
  - [x] `test_emotet/`
  - [x] `test_fim/`
  - [x] `test_ip_reputation/ `
  - [x] `test_netcat/` >> **RENAMED**: `test_unauthorized_processes_detection/`
  - [x] `test_osquery_integration/`
  - [x] `test_shellshock_attack_detection/`
  - [x] `test_slack_integration/`
  - [x] `test_sql_injection/`
  - [x] `test_suricata_integration/`
  - [x] `test_virustotal_integration/`
  - [x] `test_vulnerability_detector/`
  - [x] `test_windows_defender/`
  - [x] `test_yara_integration/`

Working branch: [2983-e2e-documentation](https://github.com/wazuh/wazuh-qa/tree/2983-e2e-documentation)
