### ISSUE TITLE
System tests: Automatic Provision - Custom playbooks creation

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#2985]
**_Issue moved from https://github.com/wazuh/wazuh-ansible/issues/785_**

| Related Issue |
| --- | 
| https://github.com/wazuh/wazuh-jenkins/issues/3453 |

| Development branch |
| --- | 
| `poc-qa-provisioning-tool` |

### Description

According to  https://github.com/wazuh/wazuh-jenkins/issues/3453, it is necessary to create custom playbooks to provision different Wazuh environments. The current repository provides multiple playbooks for Wazuh environment provision. However, these are not versatile enough to support every kind of infrastructure.

### ToDo
- [x] Research current supported environments
- [x] Playbooks creation
   -  [x] Wazuh manager without filebeat
- [x] Edit playbooks to avoid ask for connection password
