### ISSUE TITLE
Onboarding Task

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#2989]
Welcome to Wazuh!

As an introduction, we have selected a series of activities so that you can begin to learn a little more about Wazuh, as well as the processes and tools used by the team.

## Tasks

- [x] Join the Wazuh organization on Github, and set your profile visibility to the public.
- [x] Check Wazuh's tools 
- [x] Getting to know Wazuh
    - [x] Knowing Wazuh - Initial task related to Wazuh
    - [x] Knowing the processes of the QA team - Initial task related to the QA Team

**Comment by QU3B1M** [comment]
Finished tools installation and setup (Vagrant, VirtualBox, Terminator, VSCode), continuing with VMs creation and configuration

**Comment by QU3B1M** [comment]
# Update 2022/06/14
- All indexers installed

**Comment by QU3B1M** [comment]
## Update 2022/06/15
- Started with fresh VMs, one indexer working correctly
