### ISSUE TITLE
Refactor system tests to use new Deployment and ProvisioningTool

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#2992]
### Description
It is required in order to use DeploymentTool and ProvisioningTool to refactor system tests inventory and provisioning playbooks, creating a global YAML file for automatic provision and deployment in the Jenkins environment

### TODO
- [ ] Refactor system environment `agentless_cluster`
- [ ] Refactor system environment `basic_cluster`
- [ ] Refactor system environment `basic_environment`
- [ ] Refactor system environment `big_cluster_40_agents`
- [ ] Refactor system environment `enrollment_cluster`
- [ ] Refactor system environment `four_manager_disconnected_node`
- [ ] Refactor system environment `manager_agent`
- [ ] Refactor system environment `one_manager_agent`
