### ISSUE TITLE
Validate Apple Silicon architecture retrieving

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh-qa#3009]
| Related issue |
|---|
| wazuh/wazuh#12341|

# Description
This issue aims to validate wazuh/wazuh#12341 implementation by checking retrieved architecture from Apple Silicon devices a.k.a Apple M1/M2

# Test cases
- [x] Clean Install macOS agent on Apple Silicon device and check that hardware architecture is shown as `arm64`
- [x] Clean Install macOS agent on regular Apple device (Intel-based) and check that hardware architecture is shown as `x86_64`
- [x] Upgrade to dev branch -  Install macOS agent on regular Apple device (Intel-based) and check that hardware architecture is shown as `x86_64`
- [x] Upgrade to dev branch -  Install macOS agent on regular Apple device (Intel-based) and check that hardware architecture is shown as `arm64`

## Configuration details
PR: https://github.com/wazuh/wazuh/pull/13835
| Wazuh Commit | Agent Package | Manager Package|
|--|--|--|
| https://github.com/wazuh/wazuh/pull/13835/commits/e71e44fd6a15b7dae762115250ce87c2d6f0b423 | https://packages-dev.wazuh.com/warehouse/test/4.5/macos/wazuh-agent-4.5.0-3009.validate.syscollector.apple.silicon.pkg |  https://packages-dev.wazuh.com/warehouse/test/4.5/rpm/var/wazuh-manager-4.5.0-3009.validate.syscollector.apple.silicon.x86_64.rpm |

**Comment by Deblintrake09** [comment]
<details>
<summary>Check macOS architecture is registered correctly (x86_64) :green_circle: </summary>

- Install macOS agent
- Register and start agent
- Check agent's architecture
   ```
   sh-3.2# uname -a
   Darwin macos-1015 19.0.0 Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64 x86_64
   ```
- Check agent's `ossec.log` for syscollector log
   ```
   2022/06/28 11:21:31 wazuh-modulesd:syscollector[2480] wm_syscollector.c:107 at wm_sys_log(): DEBUG: Sync sent: {"component":"syscollector_osinfo","data":{"attributes":{"architecture":"x86_64","checksum":"1656440489919610","hostname":"macos-1015","os_build":"19B88","os_codename":"Catalina","os_major":"10","os_minor":"15","os_name":"Mac OS X","os_patch":"1","os_platform":"darwin","os_version":"10.15.1","release":"19.0.0","scan_time":"2022/06/28 18:21:31","sysname":"Darwin","version":"Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64"},"index":"Mac OS X","timestamp":""},"type":"state"}
   ```
- Check data in the agent's database on the manager
   ```   
   sqlite3 /var/ossec/queue/db/001.db
   select * FROM sys_osinfo;
   0|2022/06/28 18:21:31|macos-1015|x86_64|Mac OS X|10.15.1|Catalina|10|15|1|19B88|darwin|Darwin|19.0.0|Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64||1656440489919610||0|d11f4fc419eb26c305cf095e1ce2970ed4670714
   ```
</details>

**Comment by Deblintrake09** [comment]
# Research for M1 machine

-  Generated new packages
- Installed packages
- Try to connect Agent to manager. agent cannot ping manager VM or connect to Authd. It can download packages so it has access to the internet

**Comment by damarisg** [comment]
## Review data

| Tester | PR commit               |
|--------|-------------------------|
| @Deblintrake09 |  [d12aa3b](https://github.com/wazuh/wazuh/commit/d12aa3bf49e8895bfc675ed8ee2b8ee4e4e27717)   |

### Testing environment

| OS | OS version | Deployment                             | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
| Centos    |     8     | `Remote/AWS` |   ami-029496e60f56b4b13          |
| macOS | | `Remote/macmini`


### Tested packages

| `wazuh-manager` | `wazuh-agent` |
|-----------------|---------------|
|  [4.4.0](https://packages-dev.wazuh.com/warehouse/test/4.5/macos/wazuh-agent-4.5.0-3009.validate.syscollector.apple.silicon.pkg)   |   [4.5.0 .rpm agent](https://packages-dev.wazuh.com/warehouse/test/4.5/macos/wazuh-agent-4.5.0-3009.validate.syscollector.apple.silicon.pkg)  |

### Status

- [x] In progress
- [x] Pending Review
- [ ] Team leader approved
- [ ] Manager approved

--- 

## Task results

<details>
<summary>Check macOS architecture is registered correctly (x86_64) :green_circle: </summary>

- Install macOS agent
- Register and start agent
- Check agent's architecture
   ```
   sh-3.2# uname -a
   Darwin macos-1015 19.0.0 Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64 x86_64
   ```
- Check agent's `ossec.log` for syscollector log
   ```
   2022/06/28 11:21:31 wazuh-modulesd:syscollector[2480] wm_syscollector.c:107 at wm_sys_log(): DEBUG: Sync sent: {"component":"syscollector_osinfo","data":{"attributes":{"architecture":"x86_64","checksum":"1656440489919610","hostname":"macos-1015","os_build":"19B88","os_codename":"Catalina","os_major":"10","os_minor":"15","os_name":"Mac OS X","os_patch":"1","os_platform":"darwin","os_version":"10.15.1","release":"19.0.0","scan_time":"2022/06/28 18:21:31","sysname":"Darwin","version":"Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64"},"index":"Mac OS X","timestamp":""},"type":"state"}
   ```
- Check data in the agent's database on the manager
   ```   
   sqlite3 /var/ossec/queue/db/001.db
   select * FROM sys_osinfo;
   0|2022/06/28 18:21:31|macos-1015|x86_64|Mac OS X|10.15.1|Catalina|10|15|1|19B88|darwin|Darwin|19.0.0|Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64||1656440489919610||0|d11f4fc419eb26c305cf095e1ce2970ed4670714
   ```

- Check dashboard inventory section
![imagen](https://user-images.githubusercontent.com/14501079/176263934-61214689-1f7a-4b0c-af90-ad2c900e08ea.png)

</details>


<details>
<summary>Check macOS architecture is registered correctly (arm64 / M1) :green_circle: </summary>

- Install macOS agent
- Register and start agent
- Check agent's architecture
   ```
   sh-3.2# uname -a
   Darwin jenkinss-Virtual-Machine.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:19 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_VMAPPLE arm64
   ```
- Check agent's `ossec.log` for syscollector log
   ```
   2022/08/25 17:44:20 wazuh-modulesd:syscollector[11811] wm_syscollector.c:107 at wm_sys_log(): DEBUG: Message pushed: syscollector_hwinfo dbsync no_data {"begin":"ZCV0T0LG42","end":"ZCV0T0LG42","id":1661442259}
   2022/08/25 17:44:20 wazuh-modulesd:syscollector[11811] wm_syscollector.c:107 at wm_sys_log(): DEBUG: Message pushed: syscollector_osinfo dbsync no_data {"begin":"macOS","end":"macOS","id":1661442259}
   2022/08/25 17:44:20 wazuh-modulesd:syscollector[11811] wm_syscollector.c:107 at wm_sys_log(): DEBUG: Sync sent: {"component":"syscollector_hwinfo","data":{"attributes":{"board_serial":"ZCV0T0LG42","checksum":"1a2829ce562d0161e2cf6e4b0204d3ba855828e6","cpu_cores":2,"cpu_mhz":2400,"cpu_name":"VirtualMac2,1","ram_free":86448,"ram_total":4194304,"ram_usage":98,"scan_time":"2022/08/25 15:44:20"},"index":"ZCV0T0LG42","timestamp":""},"type":"state"}
   2022/08/25 17:44:20 wazuh-modulesd:syscollector[11811] wm_syscollector.c:107 at wm_sys_log(): DEBUG: Sync sent: {"component":"syscollector_osinfo","data":{"attributes":{"architecture":"arm64","checksum":"1661442259012266","hostname":"jenkinss-Virtual-Machine.local","os_build":"21E258","os_codename":null,"os_major":"12","os_minor":"3","os_name":"macOS","os_patch":"1","os_platform":"darwin","os_version":"12.3.1","release":"21.4.0","scan_time":"2022/08/25 15:44:20","sysname":"Darwin","version":"Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:19 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_VMAPPLE"},"index":"macOS","timestamp":""},"type":"state"}
   ```
- Check data in the agent's database on the manager
   ```   
   sqlite3 /var/ossec/queue/db/001.db
   select * FROM sys_osinfo;
   0|2022/08/25 16:34:03|jenkinss-Virtual-Machine.local|arm64|macOS|12.3.1||12|3|1|21E258|darwin|Darwin|21.4.0|Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:19 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_VMAPPLE||1661445242454871||0|e21a61121213fcb09653c8233109b350c9923a3e
   ```
- Check agent's data through the API
   ```
   # curl -k -X GET "https://localhost:55000/syscollector/005/os" -H "Authorization: Bearer $TOKEN"
   {"data": {"affected_items": [{"os": {"build": "21E258", "major": "12", "minor": "3", "name": "macOS", "platform": "darwin", "version": "12.3.1"}, "scan": {"id": 0, "time": "2022-08-25T15:45:09+00:00"}, "release": "21.4.0", "architecture": "arm64", "sysname": "Darwin", "version": "Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:19 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_VMAPPLE", "hostname": "jenkinss-Virtual-Machine.local", "agent_id": "005"}], "total_affected_items": 1, "total_failed_items": 0, "failed_items": []}, "message": "All specified syscollector information was returned", "error": 0}
   ```

- Check dashboard inventory section

![image](https://user-images.githubusercontent.com/14501079/186721686-b4075b3c-9bf5-4cf6-b07f-867699adc9e9.png)

</details>
