### ISSUE TITLE
Manual testing - Fix possible NULL dereference in wm_exec.c 

### ISSUE THREAD

**Issue by antoniomanuelfr** [wazuh/wazuh-qa#3017]
|Related issue|Related PR|
|---|---|
|https://github.com/wazuh/wazuh/issues/13923|https://github.com/wazuh/wazuh/pull/13924|

## Description

The goal of this issue is to manually test the change in `wm_exec` to avoid a possible NULL dereference.
## Test cases

- [x] Checks on dev-branch
   - [x] Check that scan-build 14 is not triggering any error for manager
   - [x] Check that scan-build 14 is not triggering any error for agent
- [x]  Checks on master
   - [x] Check that scan-build 14 is triggering errors for manager
   - [x] Check that scan-build 14 is triggering errors for agent

## Configuration and considerations

The system requires `scan-build 14` tool to be run. Fedora 36 has the required dependency already installed with the OS.

### Install required build dependencies
   ```
   sudo dnf install gcc-g++ cmake libstdc++-static clang-analyzer
   sudo dnf install geoip
   ```

**Comment by Deblintrake09** [comment]
# Task results

<details><summary>Install wazuh from sources :green_circle: </summary>

### Steps taken

-  Follow documentation to install wazuh from sources
   ```
   yum install make cmake gcc gcc-c++ python3 python3-policycoreutils automake autoconf libtool openssl-devel yum-utils
   yum-config-manager --enable powertools
   yum install libstdc++-static -y
   curl -OL https://packages.wazuh.com/utils/cmake/cmake-3.18.3.tar.gz && tar -zxf cmake-3.18.3.tar.gz && cd cmake-3.18.3 &&   ./bootstrap --no-system-curl && make -j$(nproc) && make install
   cd .. && rm -rf cmake-*
   export PATH=/usr/local/bin:$PATH
   yum install epel-release yum-utils -y
   yum-builddep python34 -y
   ```
- Download repo data on branch 
   ```
   curl -OL curl -OL https://github.com/wazuh/wazuh/archive/refs/heads/13923-fix-scan-build-error.zip && unzip 13923-fix-scan-build-error.zip 
   ```
- Launch install script
   ```
   cd wazuh-13923-fix-scan-build-error/
   ./install.sh
   Extracting api-4.5.0-py3.9.egg to /var/ossec/framework/python/lib/python3.9/site-packages
   Adding api 4.5.0 to easy-install.pth file

   Installed /var/ossec/framework/python/lib/python3.9/site-packages/api-4.5.0-py3.9.egg
Processing dependencies for api==4.5.0
   Finished processing dependencies for api==4.5.0
   cd ../tools/mitre && /var/ossec/framework/python/bin/python3 mitredb.py -d /var/ossec/var/db/mitre.db
   chcon: can't apply partial context to unlabeled file '/var/ossec/lib/libjemalloc.so.2'
   Generating self-signed certificate for wazuh-authd...


   Created symlink /etc/systemd/system/multi-user.target.wants/wazuh-manager.service → /usr/lib/systemd/system/wazuh-manager.service.
   Starting Wazuh...

    - Configuration finished properly.
   ```
</details>

**Comment by Deblintrake09** [comment]
## Tasks on master - Check scan-build reports bug
<details><summary>Test scan-build 14 - Build Manager :green_circle: </summary>

- Download repository
   ```
   curl -OL https://github.com/wazuh/wazuh/archive/refs/heads/13923-fix-scan-build-error.zip
   unzip 13923-fix-scan-build-error.zip
   cd 13923-fix-scan-build-error/src
   ```
- Run build command
   ```
    LDFLAGS           '-Wl,-rpath,/../lib' -pthread -lrt -ldl  -Lshared_modules/dbsync/build/lib -Lshared_modules/rsync/build/lib  -Lwazuh_modules/syscollector/build/lib -Ldata_provider/build/lib
    LIBS              -lrt -ldl -lm 
    CC                /usr/bin/../libexec/ccc-analyzer
    MAKE              make
   make[1]: Leaving directory '/home/vagrant/wazuh-13923-fix-scan-build-error/src'

   Done building server

   scan-build: Analysis run complete.
   scan-build: Removing directory '/tmp/scan-build-2022-06-28-121733-14996-1' because it contains no reports.
   scan-build: No bugs found.
   ```
</details>

<details><summary>Test scan-build 14 - Build Agent :green_circle: </summary>

- Download repository
   ```
   curl -OL https://github.com/wazuh/wazuh/archive/refs/heads/master.zip
   unzip master.zip
   cd wazuh-master/src
   ```
- Run build command
   ```
   make[1]: Leaving directory '/home/vagrant/wazuh-master/src'

   Done building agent

   scan-build: Analysis run complete.
   scan-build: 1 bug found.
   scan-build: Run 'scan-view /tmp/scan-build-2022-06-28-133505-22910-1' to examine bug reports.
   ```
</details>

**Comment by jmv74211** [comment]
🟢 Nothing to highlight. Everything seems to work properly.
