### ISSUE TITLE
IT: Add min_interval option for RSync FIM

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3020]
## Description

A new option for FIM to set the RSync minSyncInterval in order to avoid the synchronization overlapping that was experienced while executing the stress tests.

The new option is called `min_interval` inside the `synchronization` block and the default value is 10 seconds.

## Configuration options

```xml
  <syscheck>
    <!-- Database synchronization settings -->
    <synchronization>
      <enabled>yes</enabled>
      <min_interval>x</min_interval>
      <interval>5m</interval>
      <max_eps>10</max_eps>
    </synchronization>
  </syscheck>
```

**Note**: It is to Linux.

## Tasks

- [ ] Modify the sync tests settings, adding the new `min_interval` setting with a value less than the `interval` setting
- [ ] Create a case that adds the new `min_interval` setting with a value greater than the configured `interval`
- [ ] Create a case that does not contain the new `min_interval` setting included, to verify that it takes the default value.
- [ ] Validate that each test works correctly
