### ISSUE TITLE
Nightly report: 2022-06-28

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3022]
## Description

| Date|  Commit | Commit title | Build | Notes |
|--|--|--|--|--|
| 2022-06-28| 4a0c134| Adding UTs to send_msg() (#13930) | https://ci.wazuh.info/job/test_nightly/1077/ |  |

### Execution to Research

- [ ]  Authd Tier 0: Several test fails [#2922 ](https://github.com/wazuh/wazuh-qa/issues/2922)
- [ ]  Fix FIM Ubuntu IT: Nightly 2022-06-09 [#2980](https://github.com/wazuh/wazuh-qa/issues/2980) 

### Failures detected from 2022-05-12

- [ ] Reliability tests: Generic Environent launcher error [#3465](https://github.com/wazuh/wazuh-jenkins/issues/3465)  (Reported to wazuh-jenkins)
- [ ] AR IT: Nightly report - Failed test_execd_restart [#2769](https://github.com/wazuh/wazuh-qa/issues/2769)  (Reported a [bug](https://github.com/wazuh/wazuh/issues/13077) to Core) 
- [ ] IT pipeline: Unexpected Windows test launch error [#3487](https://github.com/wazuh/wazuh-jenkins/issues/3487)  (Reported to wazuh-jenkins)

**Comment by damarisg** [comment]
Our nightly report showed differents failures. 
First, we launch executions again to validate the fails.

If it fails then a new issue is created to research and fix the error.
Else, the executions is launched five times to verify that it works successfully

| Test Module | OS | Build Execution | Final Executions|
|--|--|--|--|
test_vulnerability_detector/ | CentOS - Manager | [🔴](https://ci.wazuh.info/job/Test_integration/28196/)  | [🟢](https://ci.wazuh.info/job/Test_integration/28222/)[🟢](https://ci.wazuh.info/job/Test_integration/28225/)[🟢](https://ci.wazuh.info/job/Test_integration/28226/)[🟢](https://ci.wazuh.info/job/Test_integration/28227/)[🟢](https://ci.wazuh.info/job/Test_integration/28228/) | 
test_fim | MacOS - Solaris | [🟡](https://ci.wazuh.info/job/Test_integration/28201/) | [🟢](https://ci.wazuh.info/job/Test_integration/28220/)[🟢](https://ci.wazuh.info/job/Test_integration/28221/)🟢🟢🟢
