### ISSUE TITLE
Release 4.3.5 - Release Candidate 1 - E2E UX tests - Demo environment

### ISSUE THREAD

**Issue by BelenValdivia** [wazuh/wazuh-qa#3030]
# Description
The following issue aims to run the specified test for the current release candidate, report the results, and open new issues for any encountered errors.

## Test information
|                         |                                            |
|-------------------------|--------------------------------------------|
| **Test name**           |Demo environment|
| **Category**            |Wazuh App|
| **Deployment option**   |Demo environment|
| **Main release issue**  | https://github.com/wazuh/wazuh/issues/13966|
| **Release candidate #** |RC1| 

## Proposed checks

- [x]  (**T1**): - No errors or warnings found in logs
- [x]  (**T2**): - The daemons are running with the correct user
- [x]  (**T3**): - The status of the Wazuh Indexer clusters is as expected.
- [x]  (**T4**): - No errors in the browser's developer console when browsing the App
- [x]  (**T5**): - Alerts are being generated for each of the modules configured for this purpose
- [x]  (**T6**): - No warning symbols in Discover when expanding a document

## Conclusion 🟢 

Nothing serious to note was found. A total of 3 issues have been reported, 2 of them previously created and one new.

Regarding to the issue ["Non existent process wazuh-apid and wazuh-clusterd logs found in managers in demo environment "](https://github.com/wazuh/wazuh-automation/issues/851), it seems to have been a momentary thing with no repercussions, although the development team is looking into it.

## Issues found

**Detected issues and previously reported**

- https://github.com/wazuh/wazuh-packages/issues/1511
- https://github.com/wazuh/wazuh-kibana-app/issues/4074

**New opened issues**

- https://github.com/wazuh/wazuh-automation/issues/851

## Auditors validation

The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [x] @jmv74211 
- [x] @alberpilot 

#### References

|Color|Status |
|:--:|:--|
|🟢|All tests passed successfully|
|🟡|All tests passed but there are some warnings|
|🔴|Some tests have failures or errors|

**Comment by BelenValdivia** [comment]
## Task 2: The daemos are running with the correct user

### Agents

<details>
<summary> Amazon Linux </summary>
```

root      2475  0.0  0.2  38492  2912 ?        Sl   16:54   0:00 /var/ossec/bin/wazuh-execd
wazuh     2520  0.0  0.5 264492  5420 ?        Sl   16:54   0:00 /var/ossec/bin/wazuh-agentd
root      2534  1.0  0.8 269972  8348 ?        SNl  16:54   0:08 /var/ossec/bin/wazuh-syscheckd
root      2547  0.0  0.4 481028  4548 ?        Sl   16:54   0:00 /var/ossec/bin/wazuh-logcollector
root      2566  0.0  1.4 741604 14368 ?        Sl   16:54   0:00 /var/ossec/bin/wazuh-modulesd
```


</details>

**Comment by BelenValdivia** [comment]
### Task 3: The status of the Wazuh Indexer clusters is as expected :green_circle: 
```

[root@ip-10-0-0-101 wazuh-user]# curl -k -u USER:PASSWORD  https://10.0.0.101:9200/_cat/nodes?v
ip         heap.percent ram.percent cpu load_1m load_5m load_15m node.role master name
10.0.2.34             4          61   2    0.02    0.03     0.00 dimr      *      node-2
10.0.2.200           50          61   2    0.02    0.03     0.05 dimr      -      node-3
10.0.2.232           41          61   1    0.05    0.04     0.01 dimr      -      node-1
10.0.0.101           38          45   2    0.00    0.02     0.03 dimr      -      node-7
```

**Comment by BelenValdivia** [comment]
## No errors in the browser's developer console when browsing the App 🟢
