### ISSUE TITLE
Release 4.3.5 - Release Candidate 1 - E2E UX tests - Github integration

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3031]
# Description

The following issue aims to run the specified test for the current release candidate, report the results, and open new issues for any encountered errors.

## Test information
|                         |                                            |
|-------------------------|--------------------------------------------|
| **Test name**           | Github integration|
| **Category**            |Cloud security|
| **Deployment option**   | Installation by sources|
| **Main RC issue**  |https://github.com/wazuh/wazuh/issues/13966|
| **Release candidate #** |RC1| 

On CentOS 8:

|Related issue| Instalation |  Installation Type |
|---|---|--|
| Wazuh Indexer |[Step by step](https://documentation.wazuh.com/current/installation-guide/wazuh-indexer/step-by-step.html)| Single node
| Wazuh Dashboard | [Step by step](https://documentation.wazuh.com/current/installation-guide/wazuh-indexer/step-by-step.html) | -
| Wazuh Server | [Installation from sources](https://documentation.wazuh.com/current/deployment-options/wazuh-from-sources/index.html) |Single node
| Wazuh agent | [Installation from sources](https://documentation.wazuh.com/current/deployment-options/wazuh-from-sources/index.html) | -

## Tasks

- [x] Monitoring GitHub Activity - Validate that the events/alerts generated.
     - [x] Create a repository
     - [x] Clone a repository
     - [x] Push a change
     - [x] Add member to organization 
     - [x] Remove member to organization 
     - [x] Modify Organization configuration 
     - [x] Multiple organization monitoring 
     - [x] Multiple organization monitoring generates alerts

- [x] On each message log check (related to https://github.com/wazuh/wazuh-qa/issues/3013):
    - [x] Messages appears with default parameters
    - [x] Menssages appears with interval set to 1000d 
    - [x] Mensages appears with interval set to 1s
    - [x] Github integration only_future_events to no
    - [x] Github integration events are gathered correctly

- [x] Execute Test integration

Note: 
- [Documentation ](https://documentation-dev.wazuh.com/4.3-rc/github/index.html)

#### References

|Color|Status |
|:--:|:--|
|🟢|All tests passed successfully|
|🟡|All tests passed but there are some warnings|
|🔴|Some tests have failures or errors|
|🔵|Test execution in progress|
|⚫|To Do|
|🟠|Jenkins provision fails|
|:purple_circle:| All skipped |

## Conclusion    

- **Status**: Approved  🟢 
- **Comments**: Nothing to highlight. Everything seems to work properly

## Auditors validation

The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [x] @jmv74211

**Comment by Deblintrake09** [comment]
# Preconditions


<details>

<summary> ossec.conf </summary>

```
<github>
    <enabled>yes</enabled>
    <interval>1m</interval>
    <time_delay>1s</time_delay>
    <curl_max_size>1M</curl_max_size>
    <only_future_events>yes</only_future_events>
    <api_auth>
        <org_name><ORG_NAME></org_name>
        <api_token><API_TOKEN></api_token>
    </api_auth>
    <api_parameters>
        <event_type>git</event_type>
    </api_parameters>
</github>
```

</details>

<details>

<summary> local_internal_options.conf </summary>

```
wazuh_modules.debug=2
```

</details>

# Tests cases
## Messages appears with default parameters :green_circle: 

<details>

<summary> First scan log </summary>

```
2022/06/24 20:14:19 wazuh-modulesd[71762] main.c:94 at main(): DEBUG: Created new thread for the 'github' module.
2022/06/24 20:14:19 wazuh-modulesd:github[71762] wm_github.c:83 at wm_github_main(): INFO: Module GitHub started.
2022/06/24 20:14:19 wazuh-modulesd:github[71762] wm_github.c:225 at wm_github_execute_scan(): DEBUG: Scanning organization: 'WazuhTestOrg'
2022/06/24 20:14:19 wazuh-modulesd:github[71762] wm_github.c:256 at wm_github_execute_scan(): DEBUG: Bookmark updated to '2022-06-24T20:13:49Z' for organization 'WazuhTestOrg' and event type 'git', waiting '60' seconds to run first scan.
2022/06/24 20:14:19 wazuh-modulesd:github[71762] wm_github.c:256 at wm_github_execute_scan(): DEBUG: Bookmark updated to '2022-06-24T20:13:49Z' for organization 'WazuhTestOrg' and event type 'web', waiting '60' seconds to run first scan.

```


</details>


<details>

<summary> Next scan log </summary>


```
2022/06/24 20:15:19 wazuh-modulesd:github[71762] wm_github.c:225 at wm_github_execute_scan(): DEBUG: Scanning organization: 'WazuhTestOrg'
2022/06/24 20:15:19 wazuh-modulesd:github[71762] wm_github.c:274 at wm_github_execute_scan(): DEBUG: GitHub API URL: 'https://api.github.com/orgs/WazuhTestOrg/audit-log?phrase=created:2022-06-24T20:13:50Z..2022-06-24T20:14:49Z&include=git&order=asc&per_page=100'
2022/06/24 20:15:19 wazuh-modulesd:github[71762] wm_github.c:361 at wm_github_execute_scan(): DEBUG: Bookmark updated to '2022-06-24T20:14:49Z' for organization 'WazuhTestOrg' and event type 'git', waiting '60' seconds to run next scan.
2022/06/24 20:15:19 wazuh-modulesd:github[71762] wm_github.c:274 at wm_github_execute_scan(): DEBUG: GitHub API URL: 'https://api.github.com/orgs/WazuhTestOrg/audit-log?phrase=created:2022-06-24T20:13:50Z..2022-06-24T20:14:49Z&include=web&order=asc&per_page=100'
2022/06/24 20:15:19 wazuh-modulesd:github[71762] wm_github.c:361 at wm_github_execute_scan(): DEBUG: Bookmark updated to '2022-06-24T20:14:49Z' for organization 'WazuhTestOrg' and event type 'web', waiting '60' seconds to run next scan.

```

</details>

**Comment by Deblintrake09** [comment]
<details>

<summary> Create Repository :green_circle: </summary>


The message appears as expected
```
2022/06/24 20:27:32 wazuh-modulesd:github[73282] wm_github.c:312 at wm_github_execute_scan(): DEBUG: Sending GitHub log: '{"integration":"github","github":{"action":"repo.change_merge_setting","repo":"WazuhTestOrg/RC435-tests","visibility":"private","@timestamp":1656102393656,"actor":"Deblintrake09","org":"WazuhTestOrg","public_repo":false,"_document_id":"uOaxo5OEPODOV30ign9wcg","created_at":1656102393656,"actor_location":{"country_code":"AR"}}}'
2022/06/24 20:27:32 wazuh-modulesd:github[73282] wm_github.c:312 at wm_github_execute_scan(): DEBUG: Sending GitHub log: '{"integration":"github","github":{"action":"repo.change_merge_setting","repo":"WazuhTestOrg/RC435-tests","visibility":"private","@timestamp":1656102393684,"actor":"Deblintrake09","org":"WazuhTestOrg","public_repo":false,"_document_id":"4NV-OsF4bNcnztXZ4aLIuQ","created_at":1656102393684,"actor_location":{"country_code":"AR"}}}'
2022/06/24 20:27:32 wazuh-modulesd:github[73282] wm_github.c:312 at wm_github_execute_scan(): DEBUG: Sending GitHub log: '{"integration":"github","github":{"action":"repo.create","repo":"WazuhTestOrg/RC435-tests","visibility":"private","@timestamp":1656102394105,"actor":"Deblintrake09","org":"WazuhTestOrg","public_repo":false,"_document_id":"uxlxrgLeBuS0zmR5t0Dngg","created_at":1656102394105,"actor_location":{"country_code":"AR"}}}'
```

</details>

**Comment by Deblintrake09** [comment]
# Run Integration Tests

```
[root@ip-172-31-6-110 integration]# python3 -m pytest test_github/ -vvv
======================================= test session starts ========================================
platform linux -- Python 3.6.8, pytest-6.2.2, py-1.10.0, pluggy-0.13.1 -- /bin/python3
cachedir: .pytest_cache
metadata: {'Python': '3.6.8', 'Platform': 'Linux-3.10.0-693.11.6.el7.x86_64-x86_64-with-centos-7.4.1708-Core', 'Packages': {'pytest': '6.2.2', 'py': '1.10.0', 'pluggy': '0.13.1'}, 'Plugins': {'metadata': '1.8.0', 'testinfra': '5.0.0', 'html': '3.1.1'}}
rootdir: /tmp/Test_integration_B28132_20220627121532/tests/integration, configfile: pytest.ini
plugins: metadata-1.8.0, testinfra-5.0.0, html-3.1.1
collected 8 items                                                                                  

test_github/test_configuration/test_invalid.py::test_invalid[get_configuration0] PASSED      [ 12%]
test_github/test_configuration/test_invalid.py::test_invalid[get_configuration1] PASSED      [ 25%]
test_github/test_configuration/test_invalid.py::test_invalid[get_configuration2] PASSED      [ 37%]
test_github/test_configuration/test_invalid.py::test_invalid[get_configuration3] PASSED      [ 50%]
test_github/test_configuration/test_invalid.py::test_invalid[get_configuration4] PASSED      [ 62%]
test_github/test_configuration/test_invalid.py::test_invalid[get_configuration5] PASSED      [ 75%]
test_github/test_configuration/test_invalid.py::test_invalid[get_configuration6] PASSED      [ 87%]
test_github/test_configuration/test_invalid.py::test_invalid[get_configuration7] PASSED      [100%]

================================== 8 passed in 192.78s (0:03:12) ===================================
```
