### ISSUE TITLE
E2E design and implementation: Virustotal

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#3037]
## Description

The test research was accomplished in [this issue](https://github.com/wazuh/wazuh-qa/issues/2846). So, in this issue, we will design and develop the E2E test to cover those use cases.

## Tasks

- [ ] Design the test
- [ ] Implement the test locally
- [ ] Refactor the test for it to work in the test environment

## Conclusion

WIP.

**Comment by BelenValdivia** [comment]
28/7
- Worked on test for scanning files:

1. Test structure done
2. Working on generate events

**Comment by BelenValdivia** [comment]
30/6

- Worked and finished scanning file test
- Started active response test

**Comment by BelenValdivia** [comment]
Meet with core about integratord:

Integratord reads from the alerts.json. It starts reading from the end of the file all the new alerts that arrive. The position where it has to read saves it in a pointer to the file. When the file is truncated (different than rotating and creating a new one), the pointer to the file does not move to the start so integratord misses reading any alerts that arrive before reaching the pointer position where it left off before being truncated. Once there are alerts in the position where it was left off, integratord reads all the alerts again.

**Comment by BelenValdivia** [comment]
5/7
- Updated PR with changes requested
- Updated issue PR with new tests performed
