### ISSUE TITLE
QA testing - VD on Windows 8 and Windows 8.1

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh-qa#3042]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
| v4.3.6 |     https://github.com/wazuh/wazuh/issues/13939    |   https://github.com/wazuh/wazuh/pull/13957  |

## Proposed checks

On 4.3.5: 
- [x] Validate that VD works on Windows 8
- [x] Validate that VD works on Windows 8.1

On dev branch: 
- [x] Validate that VD works on Windows 8
- [x] Validate that VD works on Windows 8.1

## Steps to reproduce
- [x] Install the Wazuh Agent on Windows 8 and connect it to a Wazuh Manager with VD enabled (NVD and MSU feeds)
- [x] Install the Wazuh Agent on Windows 8.1 and connect it to a Wazuh Manager with VD enabled (NVD and MSU feeds)

## Expected results
- [x] Logs show that Windows 8 agent was scanned
- [x] Logs show that Windows 8.1 agent was scanned
- [x] Logs like `WARNING: (5443): Unable to get the OS release for agent '<agentid>'. It may not have the OS inventory enabled."` should not be shown for both Windows 8 and Windows 8.1

## Configuration and considerations

| Wazuh Commit | Agent Package | Manager Package|
|--|--|--|
| https://github.com/wazuh/wazuh/pull/13957/commits/4bb8ce240917c9eb136310d104cc95e608ef6e48 | https://packages-dev.wazuh.com/warehouse/pullrequests/4.3/windows/wazuh-agent-4.3.6-0.commit4bb8ce2.msi | https://packages-dev.wazuh.com/warehouse/pullrequests/4.3/deb/var/wazuh-manager_4.3.6-0.commit4bb8ce2_amd64.deb https://packages-dev.wazuh.com/warehouse/pullrequests/4.3/rpm/var/wazuh-manager-4.3.6-0.commit4bb8ce2.x86_64.rpm |

**Comment by Deblintrake09** [comment]
# Tasks Results on 4.3.5
<details>
<summary> Logs show that Windows 8 agent was scanned </summary>

- Setup and start manager
- Connect agent
- Wait for vulnerability scan
- Check vulnerability alerts are generated
</details>

<details>
<summary> Logs show that Windows 8.1 agent was scanned </summary>

- Setup and start manager
- Connect agent
- Wait for vulnerability scan
- Check vulnerability alerts are generated
</details>

**Comment by Deblintrake09** [comment]
# Tasks results on dev branch
<details>
<summary> Logs show that Windows 8 agent was scanned </summary>

- Setup and start manager
- Connect agent
- Wait for vulnerability scan
- Check vulnerability alerts are generated
</details>

<details>
<summary> Logs show that Windows 8.1 agent was scanned </summary>

- Setup and start manager
- Connect agent
- Wait for vulnerability scan
- Check vulnerability alerts are generated
</details>

**Comment by Deblintrake09** [comment]
# Tasks results on dev branch :green_circle: 
<details>
<summary> Logs show that Windows 8 agent was scanned :green_circle:  </summary>

- Setup and start manager
- Connect agent
   ```
   /var/ossec/bin/agent_control -l

   Wazuh agent_control. List of available agents:
      ID: 000, Name: c3 (server), IP: 127.0.0.1, Active/Local
      ID: 001, Name: win8, IP: any, Active
   ```
- Wait for vulnerability scan
   ```
   2022/07/06 12:13:49 wazuh-modulesd:vulnerability-detector[5636] wm_vuln_detector_nvd.c:3615 at wm_vuldet_check_hotfix(): DEBUG: (5454): We have not found a hotfix that solves 'CVE-2015-2362' for agent '001' in the Microsoft feed, so it is not possible to know it is vulnerable.
   2022/07/06 12:13:49 wazuh-modulesd:vulnerability-detector[5636] wm_vuln_detector_nvd.c:1834 at wm_vuldet_win_nvd_vulnerabilities(): DEBUG: (5470): It took '0' seconds to 'find NVD' vulnerabilities in agent '001'
   2022/07/06 12:13:49 wazuh-modulesd:vulnerability-detector[5636] wm_vuln_detector_nvd.c:1836 at wm_vuldet_win_nvd_vulnerabilities(): DEBUG: (5466): Sending vulnerabilities report for agent '001'
   2022/07/06 12:13:49 wazuh-modulesd:vulnerability-detector[5636] wm_vuln_detector_nvd.c:2329 at wm_vuldet_process_agent_nvd_vulnerabilities(): DEBUG: (5467): Agent '001' is vulnerable to 'CVE-2016-0018'. Condition: 'KB3121461 patch is not installed'
   2022/07/06 12:13:49 wazuh-modulesd:vulnerability-detector[5636] wm_vuln_detector_nvd.c:2329 at wm_vuldet_process_agent_nvd_vulnerabilities(): DEBUG: (5467): Agent '001' is vulnerable to 'CVE-2016-0014'. Condition: 'KB3121918 patch is not installed'
   2022/07/06 12:13:49 wazuh-modulesd:vulnerability-detector[5636] wm_vuln_detector_nvd.c:2329 at wm_vuldet_process_agent_nvd_vulnerabilities(): DEBUG: (5467): Agent '001' is vulnerable to 'CVE-2016-0007'. Condition: 'KB3121212 patch is not installed'
   2022/07/06 12:13:49 wazuh-modulesd:vulnerability-detector[5636] wm_vuln_detector_nvd.c:2329 at wm_vuldet_process_agent_nvd_vulnerabilities(): DEBUG: (5467): Agent '001' is vulnerable to 'CVE-2016-0006'. Condition: 'KB3121212 patch is not installed'
   2022/07/06 12:13:49 wazuh-modulesd:vulnerability-detector[5636] wm_vuln_detector_nvd.c:2329 at wm_vuldet_process_agent_nvd_vulnerabilities(): DEBUG: (5467): Agent '001' is vulnerable to 'CVE-2017-0050'. Condition: 'KB4012213 patch is not installed'
   2022/07/06 12:13:49 wazuh-modulesd:vulnerability-detector[5636] wm_vuln_detector_nvd.c:1846 at wm_vuldet_win_nvd_vulnerabilities(): DEBUG: (5470): It took '0' seconds to 'report' vulnerabilities in agent '001'
   ```
- Check vulnerability alerts are generated
   ```
   {"timestamp":"2022-07-06T12:13:49.890+0000","rule":{"level":10,"description":"CVE-2016-0007 affects Windows 8","id":"23505","firedtimes":3,"mail":false,"groups":["vulnerability-detector"],"gdpr":["IV_35.7.d"],"pci_dss":["11.2.1","11.2.3"],"tsc":["CC7.1","CC7.2"]},"agent":{"id":"001","name":"win8","ip":"10.0.2.15"},"manager":{"name":"c3"},"id":"1657109629.780509","decoder":{"name":"json"},"data":{"vulnerability":{"package":{"name":"Windows 8","version":"6.2.9200","architecture":"x64","condition":"KB3121212 patch is not installed"},"cvss":{"cvss2":{"vector":{"attack_vector":"local","access_complexity":"medium","authentication":"none","confidentiality_impact":"complete","integrity_impact":"complete","availability":"complete"},"base_score":"6.900000"},"cvss3":{"vector":{"attack_vector":"local","access_complexity":"low","privileges_required":"none","user_interaction":"required","scope":"unchanged","confidentiality_impact":"high","integrity_impact":"high","availability":"high"},"base_score":"7.800000"}},"cve":"CVE-2016-0007","title":"CVE-2016-0007 affects Windows 8","rationale":"The sandbox implementation in Microsoft Windows Vista SP2, Windows Server 2008 SP2 and R2 SP1, Windows 7 SP1, Windows 8, Windows 8.1, Windows Server 2012 Gold and R2, Windows RT Gold and 8.1, and Windows 10 Gold and 1511 mishandles reparse points, which allows local users to gain privileges via a crafted application, aka \"Windows Mount Point Elevation of Privilege Vulnerability,\" a different vulnerability than CVE-2016-0006.","severity":"High","published":"2016-01-13","updated":"2019-05-17","cwe_reference":"CWE-264","status":"Active","type":"OS","references":["http://www.securityfocus.com/bid/79898","http://www.securitytracker.com/id/1034645","https://code.google.com/p/google-security-research/issues/detail?id=589","https://www.exploit-db.com/exploits/39310/","https://www.exploit-db.com/exploits/39311/","https://docs.microsoft.com/en-us/security-updates/securitybulletins/2016/ms16-008","https://nvd.nist.gov/vuln/detail/CVE-2016-0007"],"assigner":"secure@microsoft.com","cve_version":"4.0"}},"location":"vulnerability-detector"}
   {"timestamp":"2022-07-06T12:13:49.902+0000","rule":{"level":10,"description":"CVE-2016-0006 affects Windows 8","id":"23505","firedtimes":4,"mail":false,"groups":["vulnerability-detector"],"gdpr":["IV_35.7.d"],"pci_dss":["11.2.1","11.2.3"],"tsc":["CC7.1","CC7.2"]},"agent":{"id":"001","name":"win8","ip":"10.0.2.15"},"manager":{"name":"c3"},"id":"1657109629.784710","decoder":{"name":"json"},"data":{"vulnerability":{"package":{"name":"Windows 8","version":"6.2.9200","architecture":"x64","condition":"KB3121212 patch is not installed"},"cvss":{"cvss2":{"vector":{"attack_vector":"local","access_complexity":"medium","authentication":"none","confidentiality_impact":"complete","integrity_impact":"complete","availability":"complete"},"base_score":"6.900000"},"cvss3":{"vector":{"attack_vector":"local","access_complexity":"low","privileges_required":"low","user_interaction":"required","scope":"unchanged","confidentiality_impact":"high","integrity_impact":"high","availability":"high"},"base_score":"7.300000"}},"cve":"CVE-2016-0006","title":"CVE-2016-0006 affects Windows 8","rationale":"The sandbox implementation in Microsoft Windows Vista SP2, Windows Server 2008 SP2 and R2 SP1, Windows 7 SP1, Windows 8, Windows 8.1, Windows Server 2012 Gold and R2, Windows RT Gold and 8.1, and Windows 10 Gold and 1511 mishandles reparse points, which allows local users to gain privileges via a crafted application, aka \"Windows Mount Point Elevation of Privilege Vulnerability,\" a different vulnerability than CVE-2016-0007.","severity":"High","published":"2016-01-13","updated":"2019-05-17","cwe_reference":"CWE-264","status":"Active","type":"OS","references":["http://www.securityfocus.com/bid/79882","http://www.securitytracker.com/id/1034645","https://www.exploit-db.com/exploits/39311/","https://docs.microsoft.com/en-us/security-updates/securitybulletins/2016/ms16-008","https://nvd.nist.gov/vuln/detail/CVE-2016-0006"],"assigner":"secure@microsoft.com","cve_version":"4.0"}},"location":"vulnerability-detector"}
   {"timestamp":"2022-07-06T12:13:49.913+0000","rule":{"level":10,"description":"CVE-2017-0050 affects Windows 8","id":"23505","firedtimes":5,"mail":false,"groups":["vulnerability-detector"],"gdpr":["IV_35.7.d"],"pci_dss":["11.2.1","11.2.3"],"tsc":["CC7.1","CC7.2"]},"agent":{"id":"001","name":"win8","ip":"10.0.2.15"},"manager":{"name":"c3"},"id":"1657109629.788669","decoder":{"name":"json"},"data":{"vulnerability":{"package":{"name":"Windows 8","version":"6.2.9200","architecture":"x64","condition":"KB4012213 patch is not installed"},"cvss":{"cvss2":{"vector":{"attack_vector":"local","access_complexity":"low","authentication":"none","confidentiality_impact":"complete","integrity_impact":"complete","availability":"complete"},"base_score":"7.200000"},"cvss3":{"vector":{"attack_vector":"local","access_complexity":"low","privileges_required":"low","user_interaction":"none","scope":"unchanged","confidentiality_impact":"high","integrity_impact":"high","availability":"high"},"base_score":"7.800000"}},"cve":"CVE-2017-0050","title":"CVE-2017-0050 affects Windows 8","rationale":"The kernel API in Microsoft Windows Vista SP2; Windows Server 2008 SP2 and R2 SP1; Windows 7; Windows 8; Windows 10 Gold, 1511, and 1607; Windows RT 8.1; Windows Server 2012 Gold and R2; and Windows Server 2016 does not properly enforce permissions, which allows local users to spoof processes, spoof inter-process communication, or cause a denial of service via a crafted application, aka \"Windows Kernel Elevation of Privilege Vulnerability.\"","severity":"High","published":"2017-03-17","updated":"2019-10-03","cwe_reference":"NVD-CWE-noinfo","status":"Active","type":"OS","references":["https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/CVE-2017-0050","http://www.securityfocus.com/bid/96025","http://www.securitytracker.com/id/1038013","https://nvd.nist.gov/vuln/detail/CVE-2017-0050"],"assigner":"secure@microsoft.com","cve_version":"4.0"}},"location":"vulnerability-detector"}
   ```
</details>

<details>
<summary> Logs show that Windows 8.1 agent was scanned :green_circle: </summary>

- Setup and start manager
- Connect agent
   ```
   2022/07/05 11:38:21 wazuh-authd: INFO: New connection from 192.168.56.1
   2022/07/05 11:38:21 wazuh-authd: INFO: Received request for a new agent (vm81) from: 192.168.56.1
   2022/07/05 11:38:21 wazuh-authd: INFO: Agent key generated for 'vm81' (requested by any)
   2022/07/05 11:38:31 wazuh-remoted: INFO: (1409): Authentication file changed. Updating.
   2022/07/05 11:38:31 wazuh-remoted: INFO: (1410): Reading authentication keys file.
   ```
- Wait for vulnerability scan
   ```
   2022/07/05 11:45:08 wazuh-modulesd:vulnerability-detector: INFO: (5430): The update of the 'National Vulnerability Database' feed finished successfully.
   2022/07/05 11:45:08 wazuh-modulesd:vulnerability-detector: INFO: (5400): Starting 'Microsoft Security Update' database update.
   2022/07/05 11:45:12 wazuh-modulesd:vulnerability-detector: INFO: (5430): The update of the 'Microsoft Security Update' feed finished successfully.
   2022/07/05 11:45:12 wazuh-modulesd:vulnerability-detector: INFO: (5431): Starting vulnerability scan.
   2022/07/05 11:45:12 wazuh-modulesd:vulnerability-detector: INFO: (5450): Analyzing agent '001' vulnerabilities.
   2022/07/05 11:45:42 wazuh-modulesd:vulnerability-detector: INFO: (5471): Finished vulnerability assessment for agent '001'
   2022/07/05 11:45:42 wazuh-modulesd:vulnerability-detector: INFO: (5472): Vulnerability scan finished.
   ```
- Check vulnerability alerts are generated
   ```
   {"timestamp":"2022-07-05T11:45:42.692+0000","rule":{"level":7,"description":"CVE-2016-0070 affects Windows 8.1","id":"23504","firedtimes":508,"mail":false,"groups":["vulnerability-detector"],"gdpr":["IV_35.7.d"],"pci_dss":["11.2.1","11.2.3"],"tsc":["CC7.1","CC7.2"]},"agent":{"id":"001","name":"vm81","ip":"10.0.2.15"},"manager":{"name":"c3"},"id":"1657021542.5957067","decoder":{"name":"json"},"data":{"vulnerability":{"package":{"name":"Windows 8.1","version":"6.3.9600","architecture":"x64","condition":"KB3192392 patch is not installed"},"cvss":{"cvss2":{"vector":{"attack_vector":"network","access_complexity":"medium","authentication":"none","confidentiality_impact":"partial","integrity_impact":"none","availability":"none"},"base_score":"4.300000"},"cvss3":{"vector":{"attack_vector":"local","access_complexity":"low","privileges_required":"none","user_interaction":"required","scope":"unchanged","confidentiality_impact":"high","integrity_impact":"none","availability":"none"},"base_score":"5.500000"}},"cve":"CVE-2016-0070","title":"CVE-2016-0070 affects Windows 8.1","rationale":"The kernel in Microsoft Windows Vista SP2, Windows Server 2008 SP2 and R2 SP1, Windows 7 SP1, Windows 8.1, Windows Server 2012 Gold and R2, Windows RT 8.1, and Windows 10 Gold, 1511, and 1607 allows local users to gain privileges via a crafted application that makes an API call to access sensitive information in the registry, aka \"Windows Kernel Local Elevation of Privilege Vulnerability.\"","severity":"Medium","published":"2016-10-14","updated":"2018-10-12","cwe_reference":"CWE-200","status":"Active","type":"OS","references":["http://www.securityfocus.com/bid/93354","https://docs.microsoft.com/en-us/security-updates/securitybulletins/2016/ms16-124","https://nvd.nist.gov/vuln/detail/CVE-2016-0070"],"assigner":"secure@microsoft.com","cve_version":"4.0"}},"location":"vulnerability-detector"}
   {"timestamp":"2022-07-05T11:45:42.744+0000","rule":{"level":10,"description":"CVE-2016-0026 affects Windows 8.1","id":"23505","firedtimes":1082,"mail":false,"groups":["vulnerability-detector"],"gdpr":["IV_35.7.d"],"pci_dss":["11.2.1","11.2.3"],"tsc":["CC7.1","CC7.2"]},"agent":{"id":"001","name":"vm81","ip":"10.0.2.15"},"manager":{"name":"c3"},"id":"1657021542.5960776","decoder":{"name":"json"},"data":{"vulnerability":{"package":{"name":"Windows 8.1","version":"6.3.9600","architecture":"x64","condition":"KB3197873 patch is not installed"},"cvss":{"cvss2":{"vector":{"attack_vector":"network","access_complexity":"medium","authentication":"none","confidentiality_impact":"complete","integrity_impact":"complete","availability":"complete"},"base_score":"9.300000"},"cvss3":{"vector":{"attack_vector":"local","access_complexity":"low","privileges_required":"none","user_interaction":"required","scope":"unchanged","confidentiality_impact":"high","integrity_impact":"high","availability":"high"},"base_score":"7.800000"}},"cve":"CVE-2016-0026","title":"CVE-2016-0026 affects Windows 8.1","rationale":"The Common Log File System (CLFS) driver in Microsoft Windows Vista SP2, Windows Server 2008 SP2 and R2 SP1, Windows 7 SP1, Windows 8.1, Windows Server 2012 Gold and R2, Windows RT 8.1, Windows 10 Gold, 1511, and 1607, and Windows Server 2016 allows local users to gain privileges via a crafted application, aka \"Windows Common Log File System Driver Elevation of Privilege Vulnerability,\" a different vulnerability than CVE-2016-3332, CVE-2016-3333, CVE-2016-3334, CVE-2016-3335, CVE-2016-3338, CVE-2016-3340, CVE-2016-3342, CVE-2016-3343, and CVE-2016-7184.","severity":"High","published":"2016-11-10","updated":"2018-10-12","cwe_reference":"CWE-119","status":"Active","type":"OS","references":["http://www.securityfocus.com/bid/93998","http://www.securitytracker.com/id/1037252","https://docs.microsoft.com/en-us/security-updates/securitybulletins/2016/ms16-134","https://nvd.nist.gov/vuln/detail/CVE-2016-0026"],"assigner":"secure@microsoft.com","cve_version":"4.0"}},"location":"vulnerability-detector"}
   ```
</details>

**Comment by jmv74211** [comment]
🟢 Everything seems to be working properly although it has not been possible to reproduce the original problem reported by a user. Several Windows 8 AMIs have been tested and everything seems to work correctly.
