### ISSUE TITLE
Nightly report: 2022-07-01 (WIP)

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3057]
## Description

| Date|  Commit | Commit title | Build | Notes |
|--|--|--|--|--|
| 2022-07-01| [2efe60e](https://github.com/wazuh/wazuh/commit/2efe60ec9dc95475f1fe93a206771546d0bf35f4) | Merge pull request https://github.com/wazuh/wazuh/pull/13264 from wazuh/10555-fix-ignore-restrict-directories | [#1086](https://ci.wazuh.info/job/test_nightly/1086/) |  |

### Execution to Research

- [ ]  Authd Tier 0: Several test fails [#2922 ](https://github.com/wazuh/wazuh-qa/issues/2922)
- [ ] 

### Failures detected from 2022-05-12

- [ ] Reliability tests: Generic Environent launcher error [#3465](https://github.com/wazuh/wazuh-jenkins/issues/3465)  (Reported to wazuh-jenkins)
- [ ] AR IT: Nightly report - Failed test_execd_restart [#2769](https://github.com/wazuh/wazuh-qa/issues/2769)  (Reported a [bug](https://github.com/wazuh/wazuh/issues/13077) to Core) 
- [ ] IT pipeline: Unexpected Windows test launch error [#3487](https://github.com/wazuh/wazuh-jenkins/issues/3487)  (Reported to wazuh-jenkins)

**Comment by damarisg** [comment]
The research will continue on https://github.com/wazuh/wazuh-qa/issues/3161
