### ISSUE TITLE
QA testing - Validate macOS agent retrieve package vendor if it's available

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh-qa#3059]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|  v4.3.6 | https://github.com/wazuh/wazuh/issues/14074 | https://github.com/wazuh/wazuh/pull/14100 |  

## Description
It's desirable to validate that the macOS agent can retrieve the package vendor if such information is available.
Currently, brew/homebrew packages do not contain vendor information.

## Proposed checks
- [x] Validate that package vendor information is not populated to the manager on 4.3.5
- [x] Validate that package vendor information is populated to the manager on 4.3.6
- [x] Validate that package vendor information is populated to the manager when Wazuh is upgrade

## Steps to reproduce
1. Install Wazuh macOS agent and connect to Wazuh Manager
2. Wait until Wazuh macOS agent ends syscollector scan
3. Check using /syscollector/packages API request
## Current results
3- No package contains vendor information
## Expected results
3- At least macOS factory packages include vendor information

## Configuration and considerations

| Wazuh Commit | Agent Package | Manager Package|
|--|--|--|
| https://github.com/wazuh/wazuh/pull/14100/commits/3dc1b313ebe55d5da1b4ccf93a36fd640ae5060f | https://packages-dev.wazuh.com/warehouse/pullrequests/4.3/macos/wazuh-agent-4.3.6-0.commit3dc1b31.pkg | https://packages-dev.wazuh.com/warehouse/pullrequests/4.3/deb/var/wazuh-manager_4.3.6-0.commit3dc1b31_amd64.deb https://packages-dev.wazuh.com/warehouse/pullrequests/4.3/rpm/var/wazuh-manager-4.3.6-0.commit3dc1b31.x86_64.rpm |

**Comment by CamiRomero** [comment]
## Validate macOS agent retrieve package vendor - 4.3.5.

<details>
<summary>Package details</summary>

## Test information
|Wazuh version| Wazuh revision | Component|Install type|Install method|Platform|
|---|---|---|---|---|---|
| 4.3.5 | 40500 | [Syscollector - Packages](https://documentation.wazuh.com/current/user-manual/capabilities/syscollector.html#packages) | Manager | Packages | CentOS-8 |


</details>

<details>
<summary>Test case :green_circle: </summary>

1. Get agent packages

```
curl --location --request GET 'https://HOST_IP:55000/syscollector/001/packages' \
--header 'Authorization: Bearer TOKEN'
```
Output: 

```
   ...
    {
                    "scan": {
                        "id": 0,
                        "time": "2021-11-24T01:22:33Z"
                    },
                    "architecture": " ",
                    "size": 0,
                    "name": "Mail",
                    "location": "/System/Applications/Mail.app/Contents/Info.plist",
                    "version": "14.0",
                    "source": "utilities",
                    "format": "pkg",
                    "description": "com.apple.mail",
                    "section": "public.app-category.productivity",
                    "agent_id": "001"
                },
```

**Comment by CamiRomero** [comment]
## Validate macOS agent retrieve package vendor - 4.3.6.

<details>
<summary>Package details</summary>

## Test information
|Wazuh version| Wazuh revision | Component|Install type|Install method|Platform|
|---|---|---|---|---|---|
| [4.3.6](https://packages-dev.wazuh.com/warehouse/pullrequests/4.3/rpm/var/wazuh-manager-4.3.6-0.commit3dc1b31.x86_64.rpm) | 40318 | [Syscollector - Packages](https://documentation.wazuh.com/current/user-manual/capabilities/syscollector.html#packages) | Manager | Packages | CentOS-8 |
| [4.3.6](https://packages-dev.wazuh.com/warehouse/pullrequests/4.3/macos/wazuh-agent-4.3.6-0.commit3dc1b31.pkg) | 40318 | [Syscollector - Packages](https://documentation.wazuh.com/current/user-manual/capabilities/syscollector.html#packages) | Agent | Packages | macOS |


</details>

<details>
<summary>Test case :green_circle: </summary>

1. Get agent packages

```
curl --location --request GET 'https://HOST_IP:55000/syscollector/001/packages' \
--header 'Authorization: Bearer TOKEN'
```
Output: 

```
   ...
                 {
                    "scan": {
                        "id": 0,
                        "time": "2021-11-24T01:41:17Z"
                    },
                    "architecture": " ",
                    "vendor": "apple",
                    "size": 0,
                    "format": "pkg",
                    "section": "public.app-category.productivity",
                    "version": "14.0",
                    "description": "com.apple.mail",
                    "source": "utilities",
                    "location": "/System/Applications/Mail.app/Contents/Info.plist",
                    "name": "Mail",
                    "agent_id": "001"
                },
                {
                    "scan": {
                        "id": 0,
                        "time": "2021-11-24T01:41:25Z"
                    },
                    "architecture": " ",
                    "vendor": " ",
                    "size": 0,
                    "format": "pkg",
                    "version": "2.33.0",
                    "description": "Distributed revision control system",
                    "source": "homebrew",
                    "location": "/usr/local/Cellar",
                    "name": "git",
                    "agent_id": "001"
                },

```

**Comment by CamiRomero** [comment]
## Validate macOS agent retrieve package vendor - Upgrade 4.3.5 ----> 4.3.6.

<details>
<summary>Package details</summary>

## Test information
|Wazuh version| Wazuh revision | Component|Install type|Install method|Platform|
|---|---|---|---|---|---|
| [4.3.6](https://packages-dev.wazuh.com/warehouse/pullrequests/4.3/rpm/var/wazuh-manager-4.3.6-0.commit3dc1b31.x86_64.rpm) | 40318 | [Syscollector - Packages](https://documentation.wazuh.com/current/user-manual/capabilities/syscollector.html#packages) | Manager | Packages | CentOS-8 |
| [4.3.6](https://packages-dev.wazuh.com/warehouse/pullrequests/4.3/macos/wazuh-agent-4.3.6-0.commit3dc1b31.pkg) | 40318 | [Syscollector - Packages](https://documentation.wazuh.com/current/user-manual/capabilities/syscollector.html#packages) | Agent | Packages | macOS |


</details>

<details>
<summary>Test case :green_circle: </summary>
1. Check version of Wazuh:

```
Manager:
    /var/ossec/bin/wazuh-control info
    WAZUH_VERSION="v4.3.5"
    WAZUH_REVISION="40317"
    WAZUH_TYPE="server"
    
Agent:
    /var/ossec/bin/wazuh-control info
    sh: /var/ossec/bin/wazuh-control: No such file or directory
    sh-3.2# /Library/Ossec/bin/wazuh-control info
    WAZUH_VERSION="v4.3.5"
    WAZUH_REVISION="40317"
    WAZUH_TYPE="agent"
```
2. Downloaded Wazuh manager 4.3.6
```
Manager:
    curl -LO https://packages-dev.wazuh.com/warehouse/pullrequests/4.3/rpm/var/wazuh-manager-4.3.6-0.commit3dc1b31.x86_64.rpm
    
Agent:
    curl -LO https://packages-dev.wazuh.com/warehouse/pullrequests/4.3/macos/wazuh-agent-4.3.6-0.commit3dc1b31.pkg -k
```
3. Upgrade Wazuh:

```
Manager:
    yum upgrade wazuh-manager-4.3.6-0.commit3dc1b31.x86_64.rpm
    
Agent:
    installer -pkg wazuh-agent-4.3.6-0.commit3dc1b31.pkg -target /
```

4. Check version of Wazuh:
```
Manager:
    /var/ossec/bin/wazuh-control info
    WAZUH_VERSION="v4.3.6"
    WAZUH_REVISION="40318"
    WAZUH_TYPE="server"
    
Agent:
    /Library/Ossec/bin/wazuh-control info
    WAZUH_VERSION="v4.3.6"
    WAZUH_REVISION="40318"
    WAZUH_TYPE="agent"
    1. Get agent packages
```

5. Get agent packages
```
curl --location --request GET 'https://HOST_IP:55000/syscollector/001/packages' \
--header 'Authorization: Bearer TOKEN'
```
Output: 

```
       ...
        {
                    "scan": {
                        "id": 0,
                        "time": "2021-11-24T01:36:09Z"
                    },
                    "format": "pkg",
                    "version": "14.0",
                    "name": "Mail",
                    "size": 0,
                    "architecture": " ",
                    "location": "/System/Applications/Mail.app/Contents/Info.plist",
                    "vendor": "apple",
                    "section": "public.app-category.productivity",
                    "description": "com.apple.mail",
                    "source": "utilities",
                    "agent_id": "001"
                },
                {
                    "scan": {
                        "id": 0,
                        "time": "2021-11-24T01:36:15Z"
                    },
                    "format": "pkg",
                    "version": "2.33.0",
                    "name": "git",
                    "size": 0,
                    "architecture": " ",
                    "location": "/usr/local/Cellar",
                    "vendor": " ",
                    "description": "Distributed revision control system",
                    "source": "homebrew",
                    "agent_id": "001"
                },
```

**Comment by CamiRomero** [comment]
## Task results upgrade 4.3.5 ----> 4.3.6

</details>

<details>
<summary>Validate macOS agent retrieve package vendor :green_circle: </summary>

1. Check version of Wazuh:

    Manager:
    ```
        /var/ossec/bin/wazuh-control info
        WAZUH_VERSION="v4.3.5"
        WAZUH_REVISION="40317"
        WAZUH_TYPE="server"
    ```    
    Agent:
    ```
        /var/ossec/bin/wazuh-control info
        sh: /var/ossec/bin/wazuh-control: No such file or directory
        sh-3.2# /Library/Ossec/bin/wazuh-control info
        WAZUH_VERSION="v4.3.5"
        WAZUH_REVISION="40317"
        WAZUH_TYPE="agent"
    ```
    
2. Downloaded Wazuh manager 4.3.6
      
      Manager:
      ```
      curl -LO https://packages-dev.wazuh.com/warehouse/pullrequests/4.3/rpm/var/wazuh-manager-4.3.6-0.commit3dc1b31.x86_64.rpm
      ```    
      Agent:
      ```
      curl -LO https://packages-dev.wazuh.com/warehouse/pullrequests/4.3/macos/wazuh-agent-4.3.6-0.commit3dc1b31.pkg -k
      ```
3. Upgrade Wazuh:

    Manager:
    ```
        yum upgrade wazuh-manager-4.3.6-0.commit3dc1b31.x86_64.rpm
    ```    
    Agent:
    ```
        installer -pkg wazuh-agent-4.3.6-0.commit3dc1b31.pkg -target /
    ```

4. Check version of Wazuh:

    Manager:
    ```
        /var/ossec/bin/wazuh-control info
        WAZUH_VERSION="v4.3.6"
        WAZUH_REVISION="40318"
        WAZUH_TYPE="server"
    ```    
    Agent:
    ```
        /Library/Ossec/bin/wazuh-control info
        WAZUH_VERSION="v4.3.6"
        WAZUH_REVISION="40318"
        WAZUH_TYPE="agent"
        1. Get agent packages
    ```

5. Get agent packages
    ```
    curl --location --request GET 'https://HOST_IP:55000/syscollector/001/packages' \
    --header 'Authorization: Bearer TOKEN'
    ```
    
   Output: 

    ```
           ...
            {
                "scan": {
                    "id": 0,
                    "time": "2021-11-24T01:36:09Z"
                },
                "format": "pkg",
                "version": "14.0",
                "name": "Mail",
                "size": 0,
                "architecture": " ",
                "location": "/System/Applications/Mail.app/Contents/Info.plist",
                "vendor": "apple",
                "section": "public.app-category.productivity",
                "description": "com.apple.mail",
                "source": "utilities",
                "agent_id": "001"
            },
            {
                "scan": {
                    "id": 0,
                    "time": "2021-11-24T01:36:15Z"
                },
                "format": "pkg",
                "version": "2.33.0",
                "name": "git",
                "size": 0,
                "architecture": " ",
                "location": "/usr/local/Cellar",
                "vendor": " ",
                "description": "Distributed revision control system",
                "source": "homebrew",
                "agent_id": "001"
            },
    ```

**Comment by jnasselle** [comment]
Hi @CamiRomero ,

A few comments:
- The last commit https://github.com/wazuh/wazuh/pull/14100/commits/9ea4d5a760076e6cbcb58da527ae73a8f1ab36eb includes UT and does not change functional aspects of this PRs. Your test execution results are still valid.
- Current implementation for pkgs info retrieving is
  - The next directories are scanned
    - /Applications
    - /Applications/Utilities
    - /System/Applications
    - /System/Applications/Utilities
    - /System/Library/CoreServices
  - For example, the next cmdline retrieve the raw content where vendor information is retrieved: `find /Applications/*/Contents/Info.plist -exec grep "CFBundleIdentifier" -A1 {} \; `
- Package fields count may vary according to OS and available information.

**Comment by jmv74211** [comment]
🟢 Everything seems to be working properly
