### ISSUE TITLE
Fix FIM IT: test_ignore_works_over_restrict.py not received expected message

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3061]
|Related issue|
|---|
|https://github.com/wazuh/wazuh-qa/issues/3057

| Date|  Commit | Commit title | Build | |
|--|--|--|--|--|
| 2022-07-01| [2efe60e](https://github.com/wazuh/wazuh/commit/2efe60ec9dc95475f1fe93a206771546d0bf35f4) | Merge pull request https://github.com/wazuh/wazuh/pull/13264 from wazuh/10555-fix-ignore-restrict-directories | [#28316- Manager](https://ci.wazuh.info/job/Test_integration/28316/)  [#28562- Agent](https://ci.wazuh.info/job/Test_integration/28562)  |  |

## Case 

| Tier| Wazuh Type | OS
|--|--|--|
| 2 | Manager|  centOS
| 2 | Agent |  centOS - Ubuntu- MacOS

### Description

```
FAILED test_fim/test_files/test_ambiguous_confs/test_ignore_works_over_restrict.py::test_ignore_works_over_restrict[get_configuration0-/testdir1-testfile-False-tags_to_apply0]
20:45:48  FAILED test_fim/test_files/test_ambiguous_confs/test_ignore_works_over_restrict.py::test_ignore_works_over_restrict[get_configuration1-/testdir1-testfile2-False-tags_to_apply2]
20:45:48  FAILED test_fim/test_files/test_ambiguous_confs/test_ignore_works_over_restrict.py::test_ignore_works_over_restrict[get_configuration1-/testdir1-ignore_testfile2-False-tags_to_apply3]
20:45:48  FAILED test_fim/test_files/test_ambiguous_confs/test_ignore_works_over_restrict.py::test_ignore_works_over_restrict[get_configuration2-/testdir1-testfile-False-tags_to_apply0]
20:45:48  FAILED test_fim/test_files/test_ambiguous_confs/test_ignore_works_over_restrict.py::test_ignore_works_over_restrict[get_configuration3-/testdir1-testfile2-False-tags_to_apply2]
20:45:48  FAILED test_fim/test_files/test_ambiguous_confs/test_ignore_works_over_restrict.py::test_ignore_works_over_restrict[get_configuration3-/testdir1-ignore_testfile2-False-tags_to_apply3]
```

**Note:** 
- Reported by Nightly [2022-07-01](https://github.com/wazuh/wazuh-qa/issues/3057)

## Tasks
- [x] Run tests in Jenkins
- [x] Run tests in local enviroment
- [x] Read test code & docs and run tests manually
- [x] Fix failures

**Comment by QU3B1M** [comment]
## Update 04/07/2022
- Prepared local environment (Ubuntu VMs with dependencies)
- Installed manager to test
- Working on Local tests execution

### Packages
| Component | Link to package|
|--|--|
|Manager| |
|Agent|

### Run tests in local environment

| Test Path | Os |  Local | Date | By | Notes |
|--|--|--|--|--|--|
| test_fim/ | Centos |  [:red_circle:]  [:red_circle:]  [:red_circle:]| 04/07/2022 | Kevin | |

## Update 27/06/2022
- Agent & Manager .deb packages builded 
- Executed tests by Jenkin's job 6 times, result was green (OK) everytime

### Run tests using Jenkins

| Test Path | Os |  Jenkins | Date | By | Notes |
|--|--|--|--|--|--|
| test_fim/ | Centos | [:red_circle:](https://ci.wazuh.info/job/Test_integration/28577/console)|  04/07/2022 |  Kevin   | |
