### ISSUE TITLE
QA testing - RHEL/CentOS 9 support for Vulnerability Detector

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh-qa#3064]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|         4.3.6               |             https://github.com/wazuh/wazuh/issues/13745           |        https://github.com/wazuh/wazuh/pull/14117            |

## Description

The goal of this issue is to test the support for the latest _RHEL 9_ and _CentOS 9 (Stream)_ in Vulnerability Detector.

## Proposed checks

- [x] Validate that the OVAL feed for RHEL/CentOS 9 is properly downloaded and indexed in the vulnerability database
- [x] Validate that `RHEL 9` and `CentOS 9 Stream` agents are properly scanned by Vulnerability Detector

## Steps to reproduce

1. Install the manager in any supported OS. Configure Vulnerability Detector to pull the RHEL 9 OVAL
2. Connect an RHEL/CentOS 9 agent
3. Wait until the inventory is synced, and the vulnerability detector scans the agent
4. Review results and no errors appear

## Expected results

Expected results are explained in the pull request description, in the *Logs/Alerts example* section
- https://github.com/wazuh/wazuh/pull/14117

## Configuration and considerations

Apply the following configuration in the manager side:
```xml
    <!-- RedHat OS vulnerabilities -->
    <provider name="redhat">
      <enabled>yes</enabled>
      <os>5</os>
      <os>6</os>
      <os>7</os>
      <os>8</os>
      <os>9</os>
      <update_interval>1h</update_interval>
    </provider>
```

**Comment by Deblintrake09** [comment]
## Review data

| Tester | PR commit               | Conclusion                   |
|--------|-------------------------|------------------------------|
| @Deblintrake  |  4bb8ce2   | :yellow_circle: (In progress) |

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
| Linux   |  Centos9 | `LOCAL\| AWS` |  |       |
| Linux | RHEL9 | `LOCAL\| AWS` |  |       |


### Tested packages

| `wazuh-manager` | `wazuh-agent` | 
|-----------------|---------------|
| [RPM Manager](https://packages-dev.wazuh.com/warehouse/test/4.3/rpm/var/wazuh-manager-4.3.6-3064.centos9.rhel9.support.x86_64.rpm)  |  [RPM agent](https://packages-dev.wazuh.com/warehouse/test/4.3/rpm/var/wazuh-agent-4.3.6-3064.centos9.rhel9.support.x86_64.rpm) |

### Status

- [x] In progress
- [ ] Pending Review
- [ ] Team leader approved
- [ ] Manager approved








# Tasks Results
<details>
<summary> Logs show that RHEL9 system was scanned </summary>

- Setup and start manager
- Wait for vulnerability scan
   ```
   2022/07/05 13:37:09 wazuh-modulesd:vulnerability-detector[5047] wm_vuln_detector.c:7738 at wm_vuldet_run_scan(): INFO: (5472): Vulnerability scan finished.
   2022/07/05 13:37:09 wazuh-modulesd:vulnerability-detector[5047] wm_vuln_detector.c:1523 at wm_vuldet_process_agent_vulnerabilities(): DEBUG: (5468): The 'rpm-plugin-selinux' package (4.16.1.3-7.el9) from agent '000' is vulnerable to 'CVE-2021-35939'. Condition: 'Package unfixed'
   2022/07/05 13:37:09 wazuh-modulesd:vulnerability-detector[5047] wm_vuln_detector.c:1523 at wm_vuldet_process_agent_vulnerabilities(): DEBUG: (5468): The 'rpm-plugin-systemd-inhibit' package (4.16.1.3-7.el9) from agent '000' is vulnerable to 'CVE-2021-35939'. Condition: 'Package unfixed'
   2022/07/05 13:37:09 wazuh-modulesd:vulnerability-detector[5047] wm_vuln_detector.c:1523 at wm_vuldet_process_agent_vulnerabilities(): DEBUG: (5468): The 'rpm-sign-libs' package (4.16.1.3-7.el9) from agent '000' is vulnerable to 'CVE-2021-35939'. Condition: 'Package unfixed'
   2022/07/05 13:37:09 wazuh-modulesd:vulnerability-detector[5047] wm_vuln_detector.c:1523 at wm_vuldet_process_agent_vulnerabilities(): DEBUG: (5468): The 'vim-minimal' package (2:8.2.2637-5.el9) from agent '000' is vulnerable to 'CVE-2022-1621'. Condition: 'Package less than 2:8.2.2637-16.el9_0.2'
   2022/07/05 13:37:09 wazuh-modulesd:vulnerability-detector[5047] wm_vuln_detector.c:1551 at wm_vuldet_process_agent_vulnerabilities(): DEBUG: (5482): A total of '27' vulnerabilities have been reported for agent '000' thanks to the 'NVD' feed.
   2022/07/05 13:37:09 wazuh-modulesd:vulnerability-detector[5047] wm_vuln_detector.c:1552 at wm_vuldet_process_agent_vulnerabilities(): DEBUG: (5482): A total of '282' vulnerabilities have been reported for agent '000' thanks to the 'vendor' feed.
   2022/07/05 13:37:09 wazuh-modulesd:vulnerability-detector[5047] wm_vuln_detector.c:1554 at wm_vuldet_process_agent_vulnerabilities(): DEBUG: (5469): A total of '282' vulnerabilities have been reported for agent '000'
   ```
- Check vulnerability alerts are generated
   ```
   {"timestamp":"2022-07-05T13:37:09.810+0000","rule":{"level":7,"description":"CVE-2021-35939 affects rpm-plugin-selinux","id":"23504","firedtimes":227,"mail":false,"groups":["vulnerability-detector"],"gdpr":["IV_35.7.d"],"pci_dss":["11.2.1","11.2.3"],"tsc":["CC7.1","CC7.2"]},"agent":{"id":"000","name":"ip-172-31-81-59.ec2.internal","ip":"127.0.0.1"},"manager":{"name":"ip-172-31-81-59.ec2.internal"},"id":"1657028229.753924","decoder":{"name":"json"},"data":{"vulnerability":{"package":{"name":"rpm-plugin-selinux","version":"4.16.1.3-7.el9","architecture":"x86_64","condition":"Package unfixed"},"cvss":{"cvss3":{"vector":{"attack_vector":"local","access_complexity":"low","privileges_required":"high","user_interaction":"required","scope":"unchanged","confidentiality_impact":"high","integrity_impact":"high","availability":"high"},"base_score":"6.500000"}},"cve":"CVE-2021-35939","title":"CVE-2021-35939 affects rpm-plugin-selinux","rationale":"rpm: checks for unsafe symlinks are not performed for intermediary directories","severity":"Medium","published":"2021-06-30T00:00:00Z","cwe_reference":"CWE-59","status":"Active","type":"PACKAGE","bugzilla_references":["https://bugzilla.redhat.com/show_bug.cgi?id=1964129"],"references":["https://access.redhat.com/security/cve/CVE-2021-35939"]}},"location":"vulnerability-detector"}
   {"timestamp":"2022-07-05T13:37:09.857+0000","rule":{"level":7,"description":"CVE-2021-35939 affects rpm-plugin-systemd-inhibit","id":"23504","firedtimes":228,"mail":false,"groups":["vulnerability-detector"],"gdpr":["IV_35.7.d"],"pci_dss":["11.2.1","11.2.3"],"tsc":["CC7.1","CC7.2"]},"agent":{"id":"000","name":"ip-172-31-81-59.ec2.internal","ip":"127.0.0.1"},"manager":{"name":"ip-172-31-81-59.ec2.internal"},"id":"1657028229.756246","decoder":{"name":"json"},"data":{"vulnerability":{"package":{"name":"rpm-plugin-systemd-inhibit","version":"4.16.1.3-7.el9","architecture":"x86_64","condition":"Package unfixed"},"cvss":{"cvss3":{"vector":{"attack_vector":"local","access_complexity":"low","privileges_required":"high","user_interaction":"required","scope":"unchanged","confidentiality_impact":"high","integrity_impact":"high","availability":"high"},"base_score":"6.500000"}},"cve":"CVE-2021-35939","title":"CVE-2021-35939 affects rpm-plugin-systemd-inhibit","rationale":"rpm: checks for unsafe symlinks are not performed for intermediary directories","severity":"Medium","published":"2021-06-30T00:00:00Z","cwe_reference":"CWE-59","status":"Active","type":"PACKAGE","bugzilla_references":["https://bugzilla.redhat.com/show_bug.cgi?id=1964129"],"references":["https://access.redhat.com/security/cve/CVE-2021-35939"]}},"location":"vulnerability-detector"}
   {"timestamp":"2022-07-05T13:37:09.903+0000","rule":{"level":7,"description":"CVE-2021-35939 affects rpm-sign-libs","id":"23504","firedtimes":229,"mail":false,"groups":["vulnerability-detector"],"gdpr":["IV_35.7.d"],"pci_dss":["11.2.1","11.2.3"],"tsc":["CC7.1","CC7.2"]},"agent":{"id":"000","name":"ip-172-31-81-59.ec2.internal","ip":"127.0.0.1"},"manager":{"name":"ip-172-31-81-59.ec2.internal"},"id":"1657028229.758608","decoder":{"name":"json"},"data":{"vulnerability":{"package":{"name":"rpm-sign-libs","version":"4.16.1.3-7.el9","architecture":"x86_64","condition":"Package unfixed"},"cvss":{"cvss3":{"vector":{"attack_vector":"local","access_complexity":"low","privileges_required":"high","user_interaction":"required","scope":"unchanged","confidentiality_impact":"high","integrity_impact":"high","availability":"high"},"base_score":"6.500000"}},"cve":"CVE-2021-35939","title":"CVE-2021-35939 affects rpm-sign-libs","rationale":"rpm: checks for unsafe symlinks are not performed for intermediary directories","severity":"Medium","published":"2021-06-30T00:00:00Z","cwe_reference":"CWE-59","status":"Active","type":"PACKAGE","bugzilla_references":["https://bugzilla.redhat.com/show_bug.cgi?id=1964129"],"references":["https://access.redhat.com/security/cve/CVE-2021-35939"]}},"location":"vulnerability-detector"}
   {"timestamp":"2022-07-05T13:37:09.949+0000","rule":{"level":7,"description":"CVE-2022-1621 affects vim-minimal","id":"23504","firedtimes":230,"mail":false,"groups":["vulnerability-detector"],"gdpr":["IV_35.7.d"],"pci_dss":["11.2.1","11.2.3"],"tsc":["CC7.1","CC7.2"]},"agent":{"id":"000","name":"ip-172-31-81-59.ec2.internal","ip":"127.0.0.1"},"manager":{"name":"ip-172-31-81-59.ec2.internal"},"id":"1657028229.760905","decoder":{"name":"json"},"data":{"vulnerability":{"package":{"name":"vim-minimal","version":"2:8.2.2637-5.el9","architecture":"x86_64","condition":"Package less than 2:8.2.2637-16.el9_0.2"},"cvss":{"cvss2":{"vector":{"attack_vector":"network","access_complexity":"medium","authentication":"none","confidentiality_impact":"partial","integrity_impact":"partial","availability":"partial"},"base_score":"6.800000"},"cvss3":{"vector":{"attack_vector":"local","access_complexity":"low","privileges_required":"none","user_interaction":"required","scope":"unchanged","confidentiality_impact":"high","integrity_impact":"high","availability":"high"},"base_score":"7.800000"}},"cve":"CVE-2022-1621","title":"CVE-2022-1621 affects vim-minimal","rationale":"Heap buffer overflow in vim_strncpy find_word in GitHub repository vim/vim prior to 8.2.4919. This vulnerability is capable of crashing software, Bypass Protection Mechanism, Modify Memory, and possible remote execution","severity":"Medium","published":"2022-05-10","updated":"2022-05-18","cwe_reference":"CWE-787","status":"Active","type":"PACKAGE","advisories_ids":["RHSA-2022:5242","RHSA-2022:5319"],"bugzilla_references":["https://bugzilla.redhat.com/show_bug.cgi?id=2083924"],"references":["https://huntr.dev/bounties/520ce714-bfd2-4646-9458-f52cd22bb2fb","https://github.com/vim/vim/commit/7c824682d2028432ee082703ef0ab399867a089b","https://lists.debian.org/debian-lts-announce/2022/05/msg00022.html","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HIP7KG7TVS5YF3QREAY2GOGUT3YUBZAI/","https://nvd.nist.gov/vuln/detail/CVE-2022-1621","https://access.redhat.com/security/cve/CVE-2022-1621"],"assigner":"security@huntr.dev","cve_version":"4.0"}},"location":"vulnerability-detector"}
   ```
</details>

<details>
<summary> Logs show that Windows 8.1 agent was scanned </summary>

- Setup and start manager
   ```
   ```
- Connect agent
   ```
   ```
- Wait for vulnerability scan
   ```
   ```
- Check vulnerability alerts are generated
   ```
   ```
</details>

**Comment by Deblintrake09** [comment]
# Tasks Results
<details>
<summary> Logs show that RHEL9 system was scanned </summary>

- Setup and start manager
- Wait for vulnerability scan
   ```
   2022/07/05 13:37:09 wazuh-modulesd:vulnerability-detector[5047] wm_vuln_detector.c:7738 at wm_vuldet_run_scan(): INFO: (5472): Vulnerability scan finished.
   2022/07/05 13:37:09 wazuh-modulesd:vulnerability-detector[5047] wm_vuln_detector.c:1523 at wm_vuldet_process_agent_vulnerabilities(): DEBUG: (5468): The 'rpm-plugin-selinux' package (4.16.1.3-7.el9) from agent '000' is vulnerable to 'CVE-2021-35939'. Condition: 'Package unfixed'
   2022/07/05 13:37:09 wazuh-modulesd:vulnerability-detector[5047] wm_vuln_detector.c:1523 at wm_vuldet_process_agent_vulnerabilities(): DEBUG: (5468): The 'rpm-plugin-systemd-inhibit' package (4.16.1.3-7.el9) from agent '000' is vulnerable to 'CVE-2021-35939'. Condition: 'Package unfixed'
   2022/07/05 13:37:09 wazuh-modulesd:vulnerability-detector[5047] wm_vuln_detector.c:1523 at wm_vuldet_process_agent_vulnerabilities(): DEBUG: (5468): The 'rpm-sign-libs' package (4.16.1.3-7.el9) from agent '000' is vulnerable to 'CVE-2021-35939'. Condition: 'Package unfixed'
   2022/07/05 13:37:09 wazuh-modulesd:vulnerability-detector[5047] wm_vuln_detector.c:1523 at wm_vuldet_process_agent_vulnerabilities(): DEBUG: (5468): The 'vim-minimal' package (2:8.2.2637-5.el9) from agent '000' is vulnerable to 'CVE-2022-1621'. Condition: 'Package less than 2:8.2.2637-16.el9_0.2'
   2022/07/05 13:37:09 wazuh-modulesd:vulnerability-detector[5047] wm_vuln_detector.c:1551 at wm_vuldet_process_agent_vulnerabilities(): DEBUG: (5482): A total of '27' vulnerabilities have been reported for agent '000' thanks to the 'NVD' feed.
   2022/07/05 13:37:09 wazuh-modulesd:vulnerability-detector[5047] wm_vuln_detector.c:1552 at wm_vuldet_process_agent_vulnerabilities(): DEBUG: (5482): A total of '282' vulnerabilities have been reported for agent '000' thanks to the 'vendor' feed.
   2022/07/05 13:37:09 wazuh-modulesd:vulnerability-detector[5047] wm_vuln_detector.c:1554 at wm_vuldet_process_agent_vulnerabilities(): DEBUG: (5469): A total of '282' vulnerabilities have been reported for agent '000'
   ```
- Check vulnerability alerts are generated
   ```
   {"timestamp":"2022-07-05T13:37:09.810+0000","rule":{"level":7,"description":"CVE-2021-35939 affects rpm-plugin-selinux","id":"23504","firedtimes":227,"mail":false,"groups":["vulnerability-detector"],"gdpr":["IV_35.7.d"],"pci_dss":["11.2.1","11.2.3"],"tsc":["CC7.1","CC7.2"]},"agent":{"id":"000","name":"ip-172-31-81-59.ec2.internal","ip":"127.0.0.1"},"manager":{"name":"ip-172-31-81-59.ec2.internal"},"id":"1657028229.753924","decoder":{"name":"json"},"data":{"vulnerability":{"package":{"name":"rpm-plugin-selinux","version":"4.16.1.3-7.el9","architecture":"x86_64","condition":"Package unfixed"},"cvss":{"cvss3":{"vector":{"attack_vector":"local","access_complexity":"low","privileges_required":"high","user_interaction":"required","scope":"unchanged","confidentiality_impact":"high","integrity_impact":"high","availability":"high"},"base_score":"6.500000"}},"cve":"CVE-2021-35939","title":"CVE-2021-35939 affects rpm-plugin-selinux","rationale":"rpm: checks for unsafe symlinks are not performed for intermediary directories","severity":"Medium","published":"2021-06-30T00:00:00Z","cwe_reference":"CWE-59","status":"Active","type":"PACKAGE","bugzilla_references":["https://bugzilla.redhat.com/show_bug.cgi?id=1964129"],"references":["https://access.redhat.com/security/cve/CVE-2021-35939"]}},"location":"vulnerability-detector"}
   {"timestamp":"2022-07-05T13:37:09.857+0000","rule":{"level":7,"description":"CVE-2021-35939 affects rpm-plugin-systemd-inhibit","id":"23504","firedtimes":228,"mail":false,"groups":["vulnerability-detector"],"gdpr":["IV_35.7.d"],"pci_dss":["11.2.1","11.2.3"],"tsc":["CC7.1","CC7.2"]},"agent":{"id":"000","name":"ip-172-31-81-59.ec2.internal","ip":"127.0.0.1"},"manager":{"name":"ip-172-31-81-59.ec2.internal"},"id":"1657028229.756246","decoder":{"name":"json"},"data":{"vulnerability":{"package":{"name":"rpm-plugin-systemd-inhibit","version":"4.16.1.3-7.el9","architecture":"x86_64","condition":"Package unfixed"},"cvss":{"cvss3":{"vector":{"attack_vector":"local","access_complexity":"low","privileges_required":"high","user_interaction":"required","scope":"unchanged","confidentiality_impact":"high","integrity_impact":"high","availability":"high"},"base_score":"6.500000"}},"cve":"CVE-2021-35939","title":"CVE-2021-35939 affects rpm-plugin-systemd-inhibit","rationale":"rpm: checks for unsafe symlinks are not performed for intermediary directories","severity":"Medium","published":"2021-06-30T00:00:00Z","cwe_reference":"CWE-59","status":"Active","type":"PACKAGE","bugzilla_references":["https://bugzilla.redhat.com/show_bug.cgi?id=1964129"],"references":["https://access.redhat.com/security/cve/CVE-2021-35939"]}},"location":"vulnerability-detector"}
   {"timestamp":"2022-07-05T13:37:09.903+0000","rule":{"level":7,"description":"CVE-2021-35939 affects rpm-sign-libs","id":"23504","firedtimes":229,"mail":false,"groups":["vulnerability-detector"],"gdpr":["IV_35.7.d"],"pci_dss":["11.2.1","11.2.3"],"tsc":["CC7.1","CC7.2"]},"agent":{"id":"000","name":"ip-172-31-81-59.ec2.internal","ip":"127.0.0.1"},"manager":{"name":"ip-172-31-81-59.ec2.internal"},"id":"1657028229.758608","decoder":{"name":"json"},"data":{"vulnerability":{"package":{"name":"rpm-sign-libs","version":"4.16.1.3-7.el9","architecture":"x86_64","condition":"Package unfixed"},"cvss":{"cvss3":{"vector":{"attack_vector":"local","access_complexity":"low","privileges_required":"high","user_interaction":"required","scope":"unchanged","confidentiality_impact":"high","integrity_impact":"high","availability":"high"},"base_score":"6.500000"}},"cve":"CVE-2021-35939","title":"CVE-2021-35939 affects rpm-sign-libs","rationale":"rpm: checks for unsafe symlinks are not performed for intermediary directories","severity":"Medium","published":"2021-06-30T00:00:00Z","cwe_reference":"CWE-59","status":"Active","type":"PACKAGE","bugzilla_references":["https://bugzilla.redhat.com/show_bug.cgi?id=1964129"],"references":["https://access.redhat.com/security/cve/CVE-2021-35939"]}},"location":"vulnerability-detector"}
   {"timestamp":"2022-07-05T13:37:09.949+0000","rule":{"level":7,"description":"CVE-2022-1621 affects vim-minimal","id":"23504","firedtimes":230,"mail":false,"groups":["vulnerability-detector"],"gdpr":["IV_35.7.d"],"pci_dss":["11.2.1","11.2.3"],"tsc":["CC7.1","CC7.2"]},"agent":{"id":"000","name":"ip-172-31-81-59.ec2.internal","ip":"127.0.0.1"},"manager":{"name":"ip-172-31-81-59.ec2.internal"},"id":"1657028229.760905","decoder":{"name":"json"},"data":{"vulnerability":{"package":{"name":"vim-minimal","version":"2:8.2.2637-5.el9","architecture":"x86_64","condition":"Package less than 2:8.2.2637-16.el9_0.2"},"cvss":{"cvss2":{"vector":{"attack_vector":"network","access_complexity":"medium","authentication":"none","confidentiality_impact":"partial","integrity_impact":"partial","availability":"partial"},"base_score":"6.800000"},"cvss3":{"vector":{"attack_vector":"local","access_complexity":"low","privileges_required":"none","user_interaction":"required","scope":"unchanged","confidentiality_impact":"high","integrity_impact":"high","availability":"high"},"base_score":"7.800000"}},"cve":"CVE-2022-1621","title":"CVE-2022-1621 affects vim-minimal","rationale":"Heap buffer overflow in vim_strncpy find_word in GitHub repository vim/vim prior to 8.2.4919. This vulnerability is capable of crashing software, Bypass Protection Mechanism, Modify Memory, and possible remote execution","severity":"Medium","published":"2022-05-10","updated":"2022-05-18","cwe_reference":"CWE-787","status":"Active","type":"PACKAGE","advisories_ids":["RHSA-2022:5242","RHSA-2022:5319"],"bugzilla_references":["https://bugzilla.redhat.com/show_bug.cgi?id=2083924"],"references":["https://huntr.dev/bounties/520ce714-bfd2-4646-9458-f52cd22bb2fb","https://github.com/vim/vim/commit/7c824682d2028432ee082703ef0ab399867a089b","https://lists.debian.org/debian-lts-announce/2022/05/msg00022.html","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HIP7KG7TVS5YF3QREAY2GOGUT3YUBZAI/","https://nvd.nist.gov/vuln/detail/CVE-2022-1621","https://access.redhat.com/security/cve/CVE-2022-1621"],"assigner":"security@huntr.dev","cve_version":"4.0"}},"location":"vulnerability-detector"}
   ```
</details>

<details>
<summary> Logs show that Windows 8.1 agent was scanned </summary>

- Setup and start manager
   ```
   ```
- Connect agent
   ```
   ```
- Wait for vulnerability scan
   ```
   ```
- Check vulnerability alerts are generated
   ```
   ```
</details>

**Comment by jmv74211** [comment]
🟢 Everything seems to be working properly
