### ISSUE TITLE
QA testing - Replace C++ exception handling library for Windows agent

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-qa#3067]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|      4.4                  |            https://github.com/wazuh/wazuh/issues/11025            |     https://github.com/wazuh/wazuh/pull/11354               |

## Description

As of MinGW 10 (included in Ubuntu 21.04+, the C++ exception handling library (SJLJ) has been replaced by DWARF2. So, if we compile the Windows agent with MinGW 10, the package must include `libgcc_s_dw2-1.dll` instead of `libgcc_s_sjlj-1.dll`.

## Proposed checks

The same as described at https://github.com/wazuh/wazuh/pull/11354:

- [x] Compile the agent for Windows on Ubuntu 22.04 (MinGW >= 10).
- [x] Clean installation with NSIS package.
- [x] Clean installation with MSI package (Administrator user only).
- [x] Upgrade from 4.3 (NSIS) to 4.4 (NSIS).
- [x] Upgrade from 4.3 (NSIS) to 4.4 (MSI).
- [x] Upgrade from 4.3 (MSI) to 4.4 (MSI).

During the agent tests, we checked that:

## Expected results

- The agent gets installed successfully.
- The agent requests a key (enrollment).
- The agent connects to the manager.
- The agent reports the system inventory (Syscollector).

**Comment by Deblintrake09** [comment]
## Task Results
<details>
<summary> Compile the agent for Windows on Ubuntu 21.04 (MinGW 10). </summary>
1. Install dependencies
   ```
   # apt-get install curl gcc-mingw-w64 g++-mingw-w64-i686 g++-mingw-w64-x86-64 nsis make cmake
   ```
2. Clone repository
   ```
   # curl -OL https://github.com/wazuh/wazuh/archive/refs/heads/11025-win-dw2-dll.zip
   # unzip 11025-win-dw2-dll.zip
   # cd wazuh-11025-win-dw2-dll/src
   ```
3. Build package
   ```
   # make deps TARGET=winagent
   # make TARGET=winagent
       LIBS              
       CC                gcc
       MAKE              make
   make[1]: Leaving directory '/home/qa/wazuh-11025-win-dw2-dll/src'

   Done building winagent
    ```
4. Copy repository to windows machine
5.     
</details>





<details>
<summary> Clean installation with NSIS package :green_circle: </summary>

1. Execute `wazuh-11025-win-dw2-dll/src/win32/wazuh-agent-4.4.0.exe`
![imagen](https://user-images.githubusercontent.com/14501079/177994637-fb0354f7-1fd6-4343-93bc-9604c2c802c5.png)
![imagen](https://user-images.githubusercontent.com/14501079/177994712-2133a9df-394b-404d-b917-2776c6e6bb80.png)

6. Start the agent
![imagen](https://user-images.githubusercontent.com/14501079/177994913-ee1591ed-3f29-451c-ad9f-623a57a4c13c.png)

7. Check agent's logs
   ```
   2022/07/08 12:47:36 wazuh-agent: INFO: (1950): Analyzing file: 'active-response\active-responses.log'.
   2022/07/08 12:47:36 wazuh-modulesd:syscollector: INFO: Module started.
   2022/07/08 12:47:36 wazuh-modulesd:syscollector: INFO: Starting evaluation.
   2022/07/08 12:47:36 wazuh-agent: INFO: Started (pid: 3604).
   2022/07/08 12:47:36 rootcheck: INFO: Starting rootcheck scan.
   2022/07/08 12:47:36 wazuh-agent: INFO: (6000): Starting daemon...
   2022/07/08 12:47:36 wazuh-agent: INFO: (6010): File integrity monitoring scan frequency: 43200 seconds
   2022/07/08 12:47:36 wazuh-agent: INFO: (6008): File integrity monitoring scan started.
   2022/07/08 12:47:36 wazuh-modulesd:syscollector: INFO: Evaluation finished.
   2022/07/08 12:47:39 sca: INFO: Evaluation finished for policy 'C:\Program Files\ossec-agent\ruleset\sca\sca_win_audit.yml'
   2022/07/08 12:47:39 sca: INFO: Security Configuration Assessment scan finished. Duration: 3 seconds.
   2022/07/08 12:47:41 rootcheck: INFO: Ending rootcheck scan.
   2022/07/08 12:47:52 wazuh-agent: INFO: (6009): File integrity monitoring scan ended.
   2022/07/08 12:47:52 wazuh-agent: INFO: (6012): Real-time file integrity monitoring started.
   ``` 
8. Check agent is connected to manager
   ```
   # /var/ossec/bin/agent_control -l

   Wazuh agent_control. List of available agents:
      ID: 000, Name: c3 (server), IP: 127.0.0.1, Active/Local
      ID: 001, Name: Linux1, IP: any, Disconnected
      ID: 002, Name: DESKTOP-PS9K7NM, IP: any, Unknown
   ```
</details>




<details>
<summary> Clean installation with MSI package </summary>

1. Execute `wazuh-11025-win-dw2-dll/src/win32/wazuh-agent-4.4.0.exe`


2. Start the agent


3. Check agent's logs
   ```
   
   ``` 
4. Check agent is connected to manager
   ```
  
   ```
</details>

**Comment by Deblintrake09** [comment]
LIBS              
    CC                gcc
    MAKE              make
make[1]: Leaving directory '/home/vagrant/wazuh-4.3.5/src'

Done building winagent

**Comment by Deblintrake09** [comment]
### Compilation on 4.4

<details>
<summary> Compile the agent for Windows on Ubuntu  20.04 (MinGW<= 10). :yellow_circle: </summary>

1. Check GCC version
   ```
   # gcc --version
   gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0
   ```
2. Install dependencies.
    This was done following the documentation [here](https://documentation.wazuh.com/current/deployment-options/wazuh-from-sources/wazuh-agent/index.html)
   ```
   # apt-get install curl gcc-mingw-w64 g++-mingw-w64-i686 g++-mingw-w64-x86-64 nsis make cmake --fix-missing -y
   ```
3. Clone repository
   ```
   # curl -OL https://github.com/wazuh/wazuh/archive/refs/heads/4.4.zip
   # unzip 4.4.zip
   # cd wazuh-4.4/src
   ```
4. Build package :red_circle: 
```
   # make deps TARGET=winagent
   # make TARGET=winagent
make win32/wazuh-agent.exe win32/wazuh-agent-eventchannel.exe win32/manage_agents.exe win32/setup-windows.exe win32/setup-syscheck.exe win32/setup-iis.exe win32/os_win32ui.exe win32/agent-auth.exe win32/syscollector CFLAGS="-DCLIENT -D_POSIX_C_SOURCE -DWIN32 -DPSAPI_VERSION=1" LIBS="-lwsock32 -lwevtapi -lshlwapi -lcomctl32 -ladvapi32 -lkernel32 -lpsapi -lgdi32 -liphlpapi -lws2_32 -lcrypt32"
make[1]: Entering directory '/home/vagrant/wazuh-4.4/src'
    CC rootcheck/check_rc_files.o
    CC rootcheck/win-process.o
    CC rootcheck/common.o
    CC rootcheck/check_rc_ports.o
    CC rootcheck/common_rcl.o
    CC rootcheck/unix-process.o
    CC rootcheck/config.o
    CC rootcheck/check_rc_trojans.o
    CC rootcheck/check_rc_if.o
    CC rootcheck/check_open_ports.o
    CC rootcheck/os_string.o
    CC rootcheck/win-common.o
    CC rootcheck/check_rc_readproc.o
    CC rootcheck/check_rc_dev.o
    CC rootcheck/check_rc_sys.o
    CC rootcheck/run_rk_check.o
    CC rootcheck/check_rc_policy.o
    CC rootcheck/check_rc_pids.o
    CC rootcheck/rootcheck.o
    CC client-agent/state.o
In file included from ./headers/enrollment_op.h:24,
                 from ./headers/shared.h:297,
                 from client-agent/state.h:28,
                 from client-agent/state.c:14:
external/openssl/include/openssl/ssl.h:2078:1: internal compiler error: Segmentation fault
 2078 | __owur const COMP_METHOD *SSL_get_current_compression(const SSL *s);
      | ^~~~~~
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
make[1]: *** [Makefile:1770: client-agent/state.o] Error 1
make[1]: Leaving directory '/home/vagrant/wazuh-4.4/src'
make: *** [Makefile:756: winagent] Error 2

```
5. Copy repository to windows machine
6. Execute build command `/wazuh-11025-win-dw2-dll/src/win32/wazuh-installer-build-msi.bat`
![imagen](https://user-images.githubusercontent.com/14501079/178000411-f58672b6-7879-44b2-8418-5dc1866f9872.png)
7. Check file was built properly
![imagen](https://user-images.githubusercontent.com/14501079/178001841-05dee0ed-a276-450c-a1ba-60eb6b730af8.png)


### Note
Even though the package was generated correctly and worked properly, there was an error that appeared in the build logs. It should be checked that this error was introduced in this branch or if it was present in earlier versions.
</details>

**Comment by jmv74211** [comment]
🟢 Everything seems to be working properly
