### ISSUE TITLE
Fix Remoted IT: Multiple Failures

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3070]
|Related issue|
|---|
|https://github.com/wazuh/wazuh-qa/issues/3057

| Date|  Commit | Commit title | Build | Version|
|--|--|--|--|--|
| 2022-07-06| [c62d985](https://github.com/wazuh/wazuh/commit/c62d985f729591fb2f7b0026ec08bb1756dd031b) | disable filebeat metrics (https://github.com/wazuh/wazuh/pull/14121) | [#28638](https://ci.wazuh.info/job/Test_integration/28638) | 4.3.6 |

## Case 

| Tier| Wazuh Type | OS
|--|--|--|
| 0 | Manager |  CentOS 

### Description

```
09:53:23  FAILED test_remoted/test_configuration/test_basic_configuration_connection_invalid_protocol.py::test_invalid_protocol[Testing,UDP_secure_1514]
09:53:23  FAILED test_remoted/test_configuration/test_basic_configuration_connection_invalid_protocol.py::test_invalid_protocol[TCP,Testing_secure_1514]
09:53:23  FAILED test_remoted/test_configuration/test_basic_configuration_connection_invalid_protocol.py::test_invalid_protocol[Testing,Testing_secure_1514]
09:53:23  FAILED test_remoted/test_configuration/test_basic_configuration_connection_invalid_protocol.py::test_invalid_protocol[TCP,UDP,Testing_secure_1514]
09:53:23  FAILED test_remoted/test_configuration/test_basic_configuration_connection_invalid_protocol.py::test_invalid_protocol[Testing,UDP_syslog_514]
09:53:23  FAILED test_remoted/test_configuration/test_basic_configuration_connection_invalid_protocol.py::test_invalid_protocol[TCP,Testing_syslog_514]
09:53:23  FAILED test_remoted/test_configuration/test_basic_configuration_connection_invalid_protocol.py::test_invalid_protocol[Testing,Testing_syslog_514]
09:53:23  FAILED test_remoted/test_configuration/test_basic_configuration_connection_invalid_protocol.py::test_invalid_protocol[TCP,UDP,Testing_syslog_514]
09:53:23  FAILED test_remoted/test_configuration/test_basic_configuration_connection_valid.py::test_connection_valid[UDP_secure_1514]
09:53:23  FAILED test_remoted/test_configuration/test_basic_configuration_connection_valid.py::test_connection_valid[UDP_syslog_514]
09:53:23  FAILED test_remoted/test_configuration/test_basic_configuration_connection_valid.py::test_connection_valid[TCP_syslog_553]
09:53:23  FAILED test_remoted/test_configuration/test_basic_configuration_connection_valid.py::test_connection_valid[TCP_secure_23467]
09:53:23  FAILED test_remoted/test_configuration/test_basic_configuration_connection_valid.py::test_connection_valid[TCP,UDP_secure_1209]
09:53:23  FAILED test_remoted/test_configuration/test_basic_configuration_connection_valid.py::test_connection_valid[TCP,UDP_syslog_2134]
09:53:23  FAILED test_remoted/test_configuration/test_basic_configuration_connection_valid.py::test_connection_valid[UDP,TCP_secure_55632]
09:53:23  FAILED test_remoted/test_configuration/test_basic_configuration_connection_valid.py::test_connection_valid[UDP,TCP_syslog_2134]
09:53:23  FAILED test_remoted/test_configuration/test_basic_configuration_local_ip_invalid.py::test_local_ip_invalid[::ffff:909:909]
09:53:23  FAILED test_remoted/test_configuration/test_basic_configuration_local_ip_invalid.py::test_local_ip_invalid[::ffff:101:101]
09:53:23  FAILED test_remoted/test_configuration/test_basic_configuration_local_ip_valid.py::test_local_ip_valid[127.0.0.1]
09:53:23  FAILED test_remoted/test_configuration/test_basic_configuration_local_ip_valid.py::test_local_ip_valid[172.31.1.226]
09:53:23  FAILED test_remoted/test_configuration/test_basic_configuration_queue_size_too_big.py::test_big_queue_size[('secure', '1514', '99999999')]
09:53:23  FAILED test_remoted/test_configuration/test_basic_configuration_queue_size_valid.py::test_queue_size_valid[('secure', '1514', '1')]
09:53:23  FAILED test_remoted/test_configuration/test_basic_configuration_queue_size_valid.py::test_queue_size_valid[('secure', '1514', '1200')]
09:53:23  FAILED test_remoted/test_configuration/test_basic_configuration_queue_size_valid.py::test_queue_size_valid[('secure', '1514', '262144')]
09:53:23  FAILED test_remoted/test_configuration/test_basic_configuration_rids_closing_time_valid.py::test_rids_closing_time_valid[('secure', '1514', '1s')]
09:53:23  FAILED test_remoted/test_configuration/test_basic_configuration_rids_closing_time_valid.py::test_rids_closing_time_valid[('secure', '1514', '30s')]
09:53:23  FAILED test_remoted/test_configuration/test_basic_configuration_rids_closing_time_valid.py::test_rids_closing_time_valid[('secure', '1514', '1m')]
09:53:23  FAILED test_remoted/test_configuration/test_basic_configuration_rids_closing_time_valid.py::test_rids_closing_time_valid[('secure', '1514', '30m')]
09:53:23  FAILED test_remoted/test_configuration/test_basic_configuration_rids_closing_time_valid.py::test_rids_closing_time_valid[('secure', '1514', '1h')]
09:53:23  FAILED test_remoted/test_configuration/test_basic_configuration_rids_closing_time_valid.py::test_rids_closing_time_valid[('secure', '1514', '30h')]
09:53:23  FAILED test_remoted/test_configuration/test_basic_configuration_rids_closing_time_valid.py::test_rids_closing_time_valid[('secure', '1514', '1d')]
09:53:23  FAILED test_remoted/test_configuration/test_basic_configuration_rids_closing_time_valid.py::test_rids_closing_time_valid[('secure', '1514', '30d')]
09:53:23  FAILED test_remoted/test_configuration/test_basic_configuration_syslog_allowed_denied_ips_valid.py::test_allowed_denied_ips_syslog[127.0.0.0/24_192.168.1.1/24_no]
09:53:23  FAILED test_remoted/test_configuration/test_basic_configuration_syslog_denied_ips.py::test_denied_ips_syslog[127.0.0.0/24_127.0.0.1]
09:53:23  FAILED test_remoted/test_configuration/test_basic_configuration_syslog_denied_ips_invalid.py::test_denied_ips_syslog_invalid[::1_ec97:6bcc:8675:20e8:1c27:da5a:fdbf:fd3f:1c27]
09:53:23  FAILED test_remoted/test_configuration/test_basic_configuration_syslog_denied_ips_invalid.py::test_denied_ips_syslog_invalid[::1_ec97:6bcc:8675:20e8]
09:53:23  FAILED test_remoted/test_configuration/test_basic_configuration_syslog_denied_ips_invalid.py::test_denied_ips_syslog_invalid[::1_ec97::8675::20e8]
09:53:23  FAILED test_remoted/test_configuration/test_basic_configuration_syslog_denied_ips_invalid.py::test_denied_ips_syslog_invalid[::1_Testing]
09:53:23  FAILED test_remoted/test_configuration/test_basic_configuration_syslog_denied_ips_invalid.py::test_denied_ips_syslog_invalid[::1_ec97:6bcc:8675:20e8:1c27:da5a:fdbf:fd3f/512]
09:53:23  FAILED test_remoted/test_configuration/test_basic_configuration_syslog_denied_ips_invalid.py::test_denied_ips_syslog_invalid[::1_::fd3f/512]
09:53:23  ERROR test_remoted/test_configuration/test_basic_configuration_syslog_allowed_denied_ips_valid.py::test_allowed_denied_ips_syslog[0000:0000:0000:0000:0000:0000:0000:0001/64_fe80::1003:889f:a584:0101/64_yes]
09:53:23  ERROR test_remoted/test_configuration/test_basic_configuration_syslog_allowed_denied_ips_valid.py::test_allowed_denied_ips_syslog[::1/64_fe80::1003:889f:a584:0101/64_yes]
09:53:23  ERROR test_remoted/test_configuration/test_basic_configuration_syslog_allowed_denied_ips_valid.py::test_allowed_denied_ips_syslog[0000:0000:0000:0000:0000:0000:0000:0001/64_0000:0000:0000:0000:0000:0000:0000:0002/64_fe80::1003:889f:a584:0101/64_yes]
09:53:23  ERROR test_remoted/test_configuration/test_basic_configuration_syslog_allowed_denied_ips_valid.py::test_allowed_denied_ips_syslog[::1/64_::2/64_fe80::1003:889f:a584:0101/64_yes]
09:53:23  ERROR test_remoted/test_configuration/test_basic_configuration_syslog_allowed_denied_ips_valid.py::test_allowed_denied_ips_syslog[127.0.0.0/24_0000:0000:0000:0000:0000:0000:0000:0001/64_192.168.1.1/24_yes]
09:53:23  ERROR test_remoted/test_configuration/test_basic_configuration_syslog_allowed_denied_ips_valid.py::test_allowed_denied_ips_syslog[127.0.0.0/24_::1/64_192.168.1.1/24_yes]
09:53:23  ERROR test_remoted/test_configuration/test_basic_configuration_syslog_allowed_denied_ips_valid.py::test_allowed_denied_ips_syslog[::1/64_0000:0000:0000:0000:0000:0000:0000:0002/64_192.168.1.1/24_yes]
09:53:23  ERROR test_remoted/test_configuration/test_basic_configuration_syslog_denied_ips.py::test_denied_ips_syslog[0000:0000:0000:0000:0000:0000:0000:0001/64_::1]
09:53:23  ERROR test_remoted/test_configuration/test_basic_configuration_syslog_denied_ips.py::test_denied_ips_syslog[::1/64_::1]
09:53:23  ERROR test_remoted/test_multi_groups/test_merged_mg_file_content.py::test_merged_mg_file_content[check_that_the_new_file_is_added]
09:53:23  ERROR test_remoted/test_multi_groups/test_merged_mg_file_content.py::test_merged_mg_file_content[check_that_the_old_file_is_delete
```

## Tasks
- [ ] Run tests in Jenkins
- [ ] If it fails in Jenkins, run tests in local environment
- [ ] If it fails in Jenkins, Read test code & docs and run tests manually
- [ ] If it fails (Local/Jenkins), Fix failures
