### ISSUE TITLE
Fix Vulnerability Detector IT: Tier 0 - Multiple Failures

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3072]
|Related issue|
|---|
|https://github.com/wazuh/wazuh-qa/issues/3057

| Date|  Commit | Commit title | Build | Version|
|--|--|--|--|--|
| 2022-07-06| [c62d985](https://github.com/wazuh/wazuh/commit/c62d985f729591fb2f7b0026ec08bb1756dd031b) | disable filebeat metrics (https://github.com/wazuh/wazuh/pull/14121) | [#28644](https://ci.wazuh.info/job/Test_integration/28644) | 4.3.6 |

## Case 

| Tier| Wazuh Type | OS
|--|--|--|
| 0 | Manager |  CentOS 

### Description

```
09:53:18  FAILED test_vulnerability_detector/test_providers/test_enabled.py::test_enabled[SUSE Linux Enterprise Server 11]
09:53:18  FAILED test_vulnerability_detector/test_providers/test_enabled.py::test_enabled[SUSE Linux Enterprise Server 12]
09:53:18  FAILED test_vulnerability_detector/test_providers/test_enabled.py::test_enabled[SUSE Linux Enterprise Server 15]
09:53:18  FAILED test_vulnerability_detector/test_providers/test_enabled.py::test_enabled[SUSE Linux Enterprise Desktop 11]
09:53:18  FAILED test_vulnerability_detector/test_providers/test_enabled.py::test_enabled[SUSE Linux Enterprise Desktop 12]
09:53:18  FAILED test_vulnerability_detector/test_providers/test_enabled.py::test_enabled[SUSE Linux Enterprise Desktop 15]
09:53:18  FAILED test_vulnerability_detector/test_providers/test_missing_os.py::test_providers_missing_os[SUSE Linux Enterprise]
09:53:18  FAILED test_vulnerability_detector/test_providers/test_os.py::test_providers_os[SUSE Linux Enterprise Desktop 11]
09:53:18  FAILED test_vulnerability_detector/test_providers/test_os.py::test_providers_os[SUSE Linux Enterprise Desktop 12]
09:53:18  FAILED test_vulnerability_detector/test_providers/test_os.py::test_providers_os[SUSE Linux Enterprise Desktop 15]
09:53:18  FAILED test_vulnerability_detector/test_providers/test_os.py::test_providers_os[SUSE Linux Enterprise Server 11]
09:53:18  FAILED test_vulnerability_detector/test_providers/test_os.py::test_providers_os[SUSE Linux Enterprise Server 12]
09:53:18  FAILED test_vulnerability_detector/test_providers/test_os.py::test_providers_os[SUSE Linux Enterprise Server 15]
09:53:18  FAILED test_vulnerability_detector/test_providers/test_update_from_year.py::test_update_from_year[SUSE]
09:53:18  FAILED test_vulnerability_detector/test_providers/test_update_interval.py::test_update_interval[SUSE]
09:53:18  FAILED test_vulnerability_detector/test_scan_results/test_scan_nvd_vulnerabilities.py::test_no_agent_data[SLED11]
09:53:18  FAILED test_vulnerability_detector/test_scan_results/test_scan_nvd_vulnerabilities.py::test_no_agent_data[SLED12]
09:53:18  FAILED test_vulnerability_detector/test_scan_results/test_scan_nvd_vulnerabilities.py::test_no_agent_data[SLED15]
09:53:18  FAILED test_vulnerability_detector/test_scan_results/test_scan_nvd_vulnerabilities.py::test_no_agent_data[SLES11]
09:53:18  FAILED test_vulnerability_detector/test_scan_results/test_scan_nvd_vulnerabilities.py::test_no_agent_data[SLES12]
09:53:18  FAILED test_vulnerability_detector/test_scan_results/test_scan_nvd_vulnerabilities.py::test_no_agent_data[SLES15]
09:53:18  ERROR test_vulnerability_detector/test_providers/test_enabled.py::test_enabled[Amazon Linux 2022]
09:53:18  ERROR test_vulnerability_detector/test_providers/test_os.py::test_providers_os[Amazon Linux 2022]
09:53:18  ERROR test_vulnerability_detector/test_providers/test_update_interval.py::test_update_interval[Amazon Linux 2022]

```

## Tasks
- [ ] Run tests in Jenkins
- [ ] Run tests in local enviroment
- [ ] Read test code & docs and run tests manually
- [ ] Fix failures

**Comment by QU3B1M** [comment]
# Update 18-07-2022

##  Run tests in Jenkins

| Test Path | Os |  Executions | Date | By | Notes |
|--|--|--|--|--|--|
| test_vulnerability_detector/ | Centos | [:green_circle:](https://ci.wazuh.info/job/Test_integration/29426) [:green_circle: ](https://ci.wazuh.info/job/Test_integration/29428) [:green_circle: ](https://ci.wazuh.info/job/Test_integration/29429)  [:green_circle: ](https://ci.wazuh.info/job/Test_integration/29430) [:green_circle: ](https://ci.wazuh.info/job/Test_integration/29430 ) |  18/07/2022 |  Kevin | tier 0 tests
