### ISSUE TITLE
Fix Vulnerability Detector IT: Tier 1 - test_scan_results 

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3073]
|Related issue|
|---|
|https://github.com/wazuh/wazuh-qa/issues/3057

| Date|  Commit | Commit title | Build | Version|
|--|--|--|--|--|
| 2022-07-06| [c62d985](https://github.com/wazuh/wazuh/commit/c62d985f729591fb2f7b0026ec08bb1756dd031b) | disable filebeat metrics (https://github.com/wazuh/wazuh/pull/14121) | [#28645](https://ci.wazuh.info/job/Test_integration/28645) | 4.3.6 |

## Case 

| Tier| Wazuh Type | OS
|--|--|--|
| 1 | Manager |  CentOS 

### Description

```
09:47:51  FAILED test_vulnerability_detector/test_scan_results/test_scan_nvd_vulnerabilities.py::test_no_agent_data[SLED11]
09:47:51  FAILED test_vulnerability_detector/test_scan_results/test_scan_nvd_vulnerabilities.py::test_no_agent_data[SLED12]
09:47:51  FAILED test_vulnerability_detector/test_scan_results/test_scan_nvd_vulnerabilities.py::test_no_agent_data[SLED15]
09:47:51  FAILED test_vulnerability_detector/test_scan_results/test_scan_nvd_vulnerabilities.py::test_no_agent_data[SLES11]
09:47:51  FAILED test_vulnerability_detector/test_scan_results/test_scan_nvd_vulnerabilities.py::test_no_agent_data[SLES12]
09:47:51  FAILED test_vulnerability_detector/test_scan_results/test_scan_nvd_vulnerabilities.py::test_no_agent_data[SLES15]
09:47:51  FAILED test_vulnerability_detector/test_scan_results/test_scan_provider_and_nvd_vulnerabilities.py::test_scan_provider_and_nvd_vulnerabilities[SUSE]
09:47:51  FAILED test_vulnerability_detector/test_scan_results/test_scan_provider_vulnerabilities.py::test_scan_provider_vulnerabilities[SUSE]
09:47:51  FAILED test_vulnerability_detector/test_scan_results/test_scan_vulnerability_removal.py::test_vulnerability_removal_update_package[Alert vulnerability removal - SUSE]
09:47:51  FAILED test_vulnerability_detector/test_scan_results/test_scan_vulnerability_removal.py::test_vulnerability_removal_delete_package[Alert vulnerability removal - SUSE]
09:47:51  ERROR test_vulnerability_detector/test_scan_results/test_scan_provider_and_nvd_vulnerabilities.py::test_scan_provider_and_nvd_vulnerabilities[ALAS]
09:47:51  ERROR test_vulnerability_detector/test_scan_results/test_scan_provider_vulnerabilities.py::test_scan_provider_vulnerabilities[ALAS]
09:47:51  ERROR test_vulnerability_detector/test_scan_results/test_scan_vulnerability_removal.py::test_vulnerability_removal_update_package[Alert vulnerability removal - ALAS 2022]
09:47:51  ERROR test_vulnerability_detector/test_scan_results/test_scan_vulnerability_removal.py::test_vulnerability_removal_delete_package[Alert vulnerability removal - ALAS 2022]
```

## Tasks
- [ ] Run tests in Jenkins
- [ ] Run tests in local enviroment
- [ ] Read test code & docs and run tests manually
- [ ] Fix failures

**Comment by QU3B1M** [comment]
# Update 15-07-2022

##  Run tests in Jenkins

| Test Path | Os |  Executions | Date | By | Notes |
|--|--|--|--|--|--|
| test_vulnerability_detector/ | Centos | [:red_circle:](https://ci.wazuh.info/job/Test_integration/29341) [:red_circle: ](https://ci.wazuh.info/job/Test_integration/29342) [:red_circle: ](https://ci.wazuh.info/job/Test_integration/29343) |  15/07/2022 |  Kevin |Jenkins master / Using --tier 1 /  The execution fails but in different test cases than those indicated in this issue |
| test_vulnerability_detector/ | Centos | [:white_circle:](https://ci.wazuh.info/job/Test_integration/29349) [:red_circle: ](https://ci.wazuh.info/job/Test_integration/29350) [:red_circle: ](https://ci.wazuh.info/job/Test_integration/29351) |  15/07/2022 |  Kevin |Jenkins 4.3 / Using --tier 1 / The failing tests cases are the same that in the previous execution |
| test_vulnerability_detector/ | Centos | [:red_circle:](https://ci.wazuh.info/job/Test_integration/29298) [:red_circle: ](https://ci.wazuh.info/job/Test_integration/29328) [:red_circle: ](https://ci.wazuh.info/job/Test_integration/29334) |  15/07/2022 |  Kevin | Jenkins master / Not using --tier / The execution also fails in other test cases, and 2 of the executions were running for hours and from the time this comment is created, they are still running |


## Run tests in local enviroment

| Test Path | Os |  Executions | Date | By | Notes |
|--|--|--|--|--|--|
| test_vulnerability_detector/ | Centos |  [:red_circle:](https://github.com/wazuh/wazuh-qa/files/9123787/report1.zip) [:red_circle: ](https://github.com/wazuh/wazuh-qa/files/9123789/report2.zip)[:red_circle: ](https://github.com/wazuh/wazuh-qa/files/9123819/report3.zip)   |  15/07/2022 |  Kevin | Locally I only have one test case failing|
