### ISSUE TITLE
Fix Wazuh DB IT: Multiple Failures

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3074]
|Related issue|
|---|
|https://github.com/wazuh/wazuh-qa/issues/3057

| Date|  Commit | Commit title | Build | Version|
|--|--|--|--|--|
| 2022-07-06| [c62d985](https://github.com/wazuh/wazuh/commit/c62d985f729591fb2f7b0026ec08bb1756dd031b) | disable filebeat metrics (https://github.com/wazuh/wazuh/pull/14121) | [#28646](https://ci.wazuh.info/job/Test_integration/28646) | 4.3.6 |

## Case 

| Tier| Wazuh Type | OS
|--|--|--|
| 0 | Manager |  CentOS 

### Description

```
09:39:16  FAILED test_wazuh_db/test_db_backup.py::test_wdb_backup_command[/var/ossec/backup/db-/tmp/Test: Create One Backup File]
09:39:16  FAILED test_wazuh_db/test_db_backup.py::test_wdb_backup_command[/var/ossec/backup/db-/tmp/Test: Create Three Backups Files]
09:39:16  FAILED test_wazuh_db/test_db_backup.py::test_wdb_backup_command[/var/ossec/backup/db-/tmp/Test: Restore backup file saving previous state - save_pre_restore_state == false]
09:39:16  FAILED test_wazuh_db/test_db_backup.py::test_wdb_backup_command[/var/ossec/backup/db-/tmp/Test: Restore backup file saving previous state - save_pre_restore_state == true]
09:39:16  FAILED test_wazuh_db/test_db_backup.py::test_wdb_backup_command[/var/ossec/backup/db-/tmp/Test: Restore backup from pre_restore backup - database should not have the test_values]
09:39:16  FAILED test_wazuh_db/test_db_backup.py::test_wdb_backup_command[/var/ossec/backup/db-/tmp/Test: Restore backup with no save_pre_restore_state - pre_restore backup is generated normally]
09:39:16  FAILED test_wazuh_db/test_db_backup.py::test_wdb_backup_command[/var/ossec/backup/db-/tmp/Test: ERROR - Restore backup with empty pre_restore value - save_pre_restore_state ==''  ]
09:39:16  FAILED test_wazuh_db/test_db_backup.py::test_wdb_backup_command[/var/ossec/backup/db-/tmp/Test: ERROR - Restore backup with invalid pre_restore value - save_pre_restore_state == value  ]
09:39:16  FAILED test_wazuh_db/test_db_backup.py::test_wdb_backup_command[/var/ossec/backup/db-/tmp/Test: ERROR - Restore backup with invalid snapshot value - snapshot == invalid_snapshot_value]
09:39:16  FAILED test_wazuh_db/test_db_backup.py::test_wdb_backup_command[/var/ossec/backup/db-/tmp/Test: ERROR - Restore backup with empty snapshot value - snapshot =='']
09:39:16  FAILED test_wazuh_db/test_db_backup.py::test_wdb_backup_command[/var/ossec/backup/db-/tmp/Test: ERROR - Restore backup with no snapshot parameter]
09:39:16  FAILED test_wazuh_db/test_get_groups_integrity.py::test_get_groups_integrity[/tmp/Test: No Agents Registered - No Hash - Error]
09:39:16  FAILED test_wazuh_db/test_get_groups_integrity.py::test_get_groups_integrity[/tmp/Test: Two Agents Registered - Valid Hash - Both Synced => Synced]
09:39:16  FAILED test_wazuh_db/test_get_groups_integrity.py::test_get_groups_integrity[/tmp/Test: Two Agents Registered - Valid Hash - Both Syncreq => Syncreq]
09:39:16  FAILED test_wazuh_db/test_get_groups_integrity.py::test_get_groups_integrity[/tmp/Test: Two Agents Registered - Valid Hash - Syncreq and Synced => Syncreq]
09:39:16  FAILED test_wazuh_db/test_get_groups_integrity.py::test_get_groups_integrity[/tmp/Test: Two Agents Registered - Invalid Hash length. => error hash Less than 40 chars]
09:39:16  FAILED test_wazuh_db/test_get_groups_integrity.py::test_get_groups_integrity[/tmp/Test: Two Agents Registered - Hash param Empty. => error hash Less than 40 chars]
09:39:16  FAILED test_wazuh_db/test_get_groups_integrity.py::test_get_groups_integrity[/tmp/Test: Two Agents Registered - Both Synced - Hash does not match DB Hash => hash_mismatch]
09:39:16  FAILED test_wazuh_db/test_get_groups_integrity.py::test_get_groups_integrity[/tmp/Test: Two Agents Registered - Syncreq - Hash does not match DB Hash => syncreq]
09:39:16  FAILED test_wazuh_db/test_set_agent_groups.py::test_set_agent_groups[/tmp/Test: Group Append - Add TestGroup1]
09:39:16  FAILED test_wazuh_db/test_set_agent_groups.py::test_set_agent_groups[/tmp/Test: Group Append Empty groups - Agent has no groups - No groups added]
09:39:16  FAILED test_wazuh_db/test_set_agent_groups.py::test_set_agent_groups[/tmp/Test: Group Append Empty groups - Agent has default group - No groups affected]
09:39:16  FAILED test_wazuh_db/test_set_agent_groups.py::test_set_agent_groups[/tmp/Test: Group Append Add same group twice - Has only one group]
09:39:16  FAILED test_wazuh_db/test_set_agent_groups.py::test_set_agent_groups[/tmp/Test: Group Append Two groups - Agent Has two groups]
09:39:16  FAILED test_wazuh_db/test_set_agent_groups.py::test_set_agent_groups[/tmp/Test: Group Empty-Only - Agent Has no groups. One Group is Added]
09:39:16  FAILED test_wazuh_db/test_set_agent_groups.py::test_set_agent_groups[/tmp/Test: Group Empty-Only - Agent Has no groups. No new groups added]
09:39:16  FAILED test_wazuh_db/test_set_agent_groups.py::test_set_agent_groups[/tmp/Test: Group Override - Agent Has one group.  New group replaces old group]
09:39:16  FAILED test_wazuh_db/test_set_agent_groups.py::test_set_agent_groups[/tmp/Test: Group Override - Agent has Group - Pass no new group.  Error - groups not affected]
09:39:16  FAILED test_wazuh_db/test_set_agent_groups.py::test_set_agent_groups[/tmp/Test: Group Remove - Agent has one Group - Remove the group.  Agent has default assigned]
09:39:16  FAILED test_wazuh_db/test_set_agent_groups.py::test_set_agent_groups[/tmp/Test: Group Remove - Agent has TestGroup1 and TestGroup2 - Remove Tesgroup1.  Agent has TestGroup2 assigned]
09:39:16  FAILED test_wazuh_db/test_set_agent_groups.py::test_set_agent_groups[/tmp/Test: Group Remove - Agent has no groups - Try remove a group.  Agent has default assigned ]
09:39:16  FAILED test_wazuh_db/test_set_agent_groups.py::test_set_agent_groups[/tmp/Test: Invalid Mode - use an Invalid mode - no groups added]
09:39:16  FAILED test_wazuh_db/test_set_agent_groups.py::test_set_agent_groups[/tmp/Test: No Mode - No mode is passed - no groups affected]
09:39:16  FAILED test_wazuh_db/test_set_agent_groups.py::test_set_agent_groups[/tmp/Test: sync_status Synced - Assign a group using Synced Sync Status - agent has TestGroup1 assigned]
09:39:16  FAILED test_wazuh_db/test_set_agent_groups.py::test_set_agent_groups[/tmp/Test: Wrong sync_status - Assign a group using and invalid Sync_Status - agent has no group]
09:39:16  FAILED test_wazuh_db/test_set_agent_groups.py::test_set_agent_groups[/tmp/Test: No sync_status - Assign a group using and empty Sync_Status field - agent has no group assigned]
09:39:16  FAILED test_wazuh_db/test_set_agent_groups.py::test_set_agent_groups[/tmp/Test: Missing Fields - Assign a group using without data field - agent has no group assigned]
09:39:16  FAILED test_wazuh_db/test_set_agent_groups.py::test_set_agent_groups[/tmp/Test: Missing Fields - Assign a group using without data groups field - agent has no group assigned]
09:39:16  FAILED test_wazuh_db/test_set_agent_groups.py::test_set_agent_groups[/tmp/Test: Missing Fields - Assign a group using without data id field - agent has no group assigned]
09:39:16  FAILED test_wazuh_db/test_set_agent_groups.py::test_set_agent_groups[/tmp/Test: Missing Fields - Assign a group using without mode field - agent has no group assigned]
09:39:16  FAILED test_wazuh_db/test_set_agent_groups.py::test_set_agent_groups[/tmp/Test: Missing Fields - Assign a group using without sync_status field - agent has TestGroup1 assigned]
09:39:16  FAILED test_wazuh_db/test_set_agent_groups.py::test_set_agent_groups[/tmp/Test: Wrong group name format - Assign a group with an invalid group name (has invalid '.' character)]
09:39:16  FAILED test_wazuh_db/test_set_agent_groups.py::test_set_agent_groups[/tmp/Test: Wrong group name format - Assign a group with an invalid group name (has invalid ',' character)]
09:39:16  FAILED test_wazuh_db/test_set_agent_groups.py::test_set_agent_groups[/tmp/Test: Wrong group name format - Assign a group with an invalid group name (has invalid '@' character)]
09:39:16  FAILED test_wazuh_db/test_wazuh_db.py::test_wazuh_db_messages_agent[syscollector: miscellaneous]
09:39:16  FAILED test_wazuh_db/test_wazuh_db.py::test_wazuh_db_messages_agent[syscollector: ports]
09:39:16  FAILED test_wazuh_db/test_wazuh_db.py::test_wazuh_db_messages_agent[syscollector: processes]
09:39:16  FAILED test_wazuh_db/test_wazuh_db.py::test_wazuh_db_messages_agent[syscollector: packages]
09:39:16  FAILED test_wazuh_db/test_wazuh_db.py::test_wazuh_db_messages_agent[syscollector: osinfo]
09:39:16  FAILED test_wazuh_db/test_wazuh_db.py::test_wazuh_db_messages_agent[syscollector: hwinfo]
09:39:16  FAILED test_wazuh_db/test_wazuh_db.py::test_wazuh_db_messages_agent[syscollector: hotfixes]
09:39:16  FAILED test_wazuh_db/test_wazuh_db.py::test_wazuh_db_messages_global[/tmp/Test: Insert commands]
09:39:16  FAILED test_wazuh_db/test_wazuh_db.py::test_wazuh_db_messages_global[/tmp/Test: Update commands]
09:39:16  FAILED test_wazuh_db/test_wazuh_db.py::test_wazuh_db_messages_global[/tmp/Test: get-all-agents command]
09:39:16  FAILED test_wazuh_db/test_wazuh_db.py::test_wazuh_db_messages_global[/tmp/Test: sync-agent-info-set command]
09:39:16  FAILED test_wazuh_db/test_wazuh_db.py::test_wazuh_db_messages_global[/tmp/Test: Reset connection status]
09:39:16  FAILED test_wazuh_db/test_wazuh_db.py::test_wazuh_db_messages_global[/tmp/Test: get-agents-by-connection-status command]
09:39:16  FAILED test_wazuh_db/test_wazuh_db.py::test_wazuh_db_messages_global[/tmp/Test: disconnect-agents command]
09:39:16  FAILED test_wazuh_db/test_wazuh_db.py::test_wazuh_db_messages_global[/tmp/Test: Manager keepalive]
09:39:16  FAILED test_wazuh_db/test_wazuhdb_getconfig.py::test_sync_agent_groups[/tmp/Test: Get config empty parameter]
09:39:16  FAILED test_wazuh_db/test_wazuhdb_getconfig.py::test_sync_agent_groups[/tmp/Test: Get config wrong parameter]
09:39:16  FAILED test_wazuh_db/test_wazuhdb_getconfig.py::test_sync_agent_groups[/tmp/Test: Get internal config]
09:39:16  FAILED test_wazuh_db/test_wazuhdb_getconfig.py::test_sync_agent_groups[/tmp/Test: Get wdb config]
09:39:16  FAILED test_wazuh_db/test_wdb_backup_configs.py::test_wdb_backup_configs[get_configuration0-/var/ossec/backup/db]
09:39:16  FAILED test_wazuh_db/test_wdb_backup_configs.py::test_wdb_backup_configs[get_configuration1-/var/ossec/backup/db]
09:39:16  FAILED test_wazuh_db/test_wdb_backup_configs.py::test_wdb_backup_configs[get_configuration2-/var/ossec/backup/db]
09:39:16  FAILED test_wazuh_db/test_wdb_backup_configs.py::test_wdb_backup_configs[get_configuration3-/var/ossec/backup/db]
09:39:16  FAILED test_wazuh_db/test_wdb_backup_configs.py::test_wdb_backup_configs[get_configuration4-/var/ossec/backup/db]
09:39:16  FAILED test_wazuh_db/test_wdb_backup_configs.py::test_wdb_backup_configs[get_configuration5-/var/ossec/backup/db]
09:39:16  FAILED test_wazuh_db/test_wdb_backup_configs.py::test_wdb_backup_configs[get_configuration6-/var/ossec/backup/db]
09:39:16  FAILED test_wazuh_db/test_wdb_backup_configs.py::test_wdb_backup_configs[get_configuration7-/var/ossec/backup/db]
09:39:16  ERROR test_wazuh_db/test_sync_agent_groups_get.py::test_sync_agent_groups[/tmp/Test: Test sync_status with response]
09:39:16  ERROR test_wazuh_db/test_sync_agent_groups_get.py::test_sync_agent_groups[/tmp/Test: Test sync_status without response]
09:39:16  ERROR test_wazuh_db/test_sync_agent_groups_get.py::test_sync_agent_groups[/tmp/Test: Test 'all' condition when agent groups are in 'sync_req']
09:39:16  ERROR test_wazuh_db/test_sync_agent_groups_get.py::test_sync_agent_groups[/tmp/Test: Test 'all' condition when agent groups are in 'synced']
09:39:16  ERROR test_wazuh_db/test_sync_agent_groups_get.py::test_sync_agent_groups[/tmp/Test: Test 'sync_status' condition when one agent groups are in 'synced']
09:39:16  ERROR test_wazuh_db/test_sync_agent_groups_get.py::test_sync_agent_groups[/tmp/Test: Test 'all' condition when one agent groups are in 'synced']
09:39:16  ERROR test_wazuh_db/test_sync_agent_groups_get.py::test_sync_agent_groups[/tmp/Test: Test with and invalid filter in condition]
09:39:16  ERROR test_wazuh_db/test_sync_agent_groups_get.py::test_sync_agent_groups[/tmp/Test: Test without condition]
09:39:16  ERROR test_wazuh_db/test_sync_agent_groups_get.py::test_sync_agent_groups[/tmp/Test: Test set_synced in True]
09:39:16  ERROR test_wazuh_db/test_sync_agent_groups_get.py::test_sync_agent_groups[/tmp/Test: Test set_synced with invalid value - false]
09:39:16  ERROR test_wazuh_db/test_sync_agent_groups_get.py::test_sync_agent_groups[/tmp/Test: Test set_synced with invalid value - String]
09:39:16  ERROR test_wazuh_db/test_sync_agent_groups_get.py::test_sync_agent_groups[/tmp/Test: Test get_global_hash in true]
09:39:16  ERROR test_wazuh_db/test_sync_agent_groups_get.py::test_sync_agent_groups[/tmp/Test: Test get_global_hash in false]
09:39:16  ERROR test_wazuh_db/test_sync_agent_groups_get.py::test_sync_agent_groups[/tmp/Test: Test get_global_hash with invalid value]
09:39:16  ERROR test_wazuh_db/test_sync_agent_groups_get.py::test_sync_agent_groups[/tmp/Test: Test 'agent_registration_delta' in 0 and sync_status]
09:39:16  ERROR test_wazuh_db/test_sync_agent_groups_get.py::test_sync_agent_groups[/tmp/Test: Test 'agent_registration_delta' in 0 and all condition ]
09:39:16  ERROR test_wazuh_db/test_sync_agent_groups_get.py::test_sync_agent_groups[/tmp/Test: Test 'agent_registration_delta' with delta in 10000 and sync_status]
09:39:16  ERROR test_wazuh_db/test_sync_agent_groups_get.py::test_sync_agent_groups[/tmp/Test: Test 'agent_registration_delta' with delta in 10000 and all]
09:39:16  ERROR test_wazuh_db/test_sync_agent_groups_get.py::test_sync_agent_groups[/tmp/Test: Test last_id - by default]
09:39:16  ERROR test_wazuh_db/test_sync_agent_groups_get.py::test_sync_agent_groups[/tmp/Test: Test last_id - obtain from second group]
09:39:16  ERROR test_wazuh_db/test_sync_agent_groups_get.py::test_sync_agent_groups[/tmp/Test: Test last_id - with not exist id]
09:39:16  ERROR test_wazuh_db/test_sync_agent_groups_get.py::test_sync_agent_groups[/tmp/Test: Test last_id - with negative value]
```

## Tasks
- [ ] Run tests in Jenkins
- [ ] Run tests in local enviroment
- [ ] Read test code & docs and run tests manually
- [ ] Fix failures

**Comment by damarisg** [comment]
# Update 2022/07/15

## Run tests using Jenkins


Test Path | Os | Build | Date | By | Notes
-- | -- | -- | -- | -- | --
test_wazuh_db/ | CentOS - Manager|  [:green_circle: ](https://ci.wazuh.info/view/Tests/job/Test_integration/29340/) [:green_circle: ](https://ci.wazuh.info/view/Tests/job/Test_integration/29339/)[:green_circle: ](https://ci.wazuh.info/view/Tests/job/Test_integration/29338/)[:green_circle: ](https://ci.wazuh.info/view/Tests/job/Test_integration/29337/)[:green_circle: ](https://ci.wazuh.info/view/Tests/job/Test_integration/29335/consoleFull) | 2022/07/58 | @damarisg |  


This issue was closed because we couldn't reproduce it.
