### ISSUE TITLE
Fix Vulnerability Detector IT: Tier 2 - Multiple Failures

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3075]
|Related issue|
|---|
|https://github.com/wazuh/wazuh-qa/issues/3057

| Date|  Commit | Commit title | Build | Version|
|--|--|--|--|--|
| 2022-07-07| [394f627](https://github.com/wazuh/wazuh/commit/394f627b3915f64dfc1a5b7ba55f61076159d2d2) | Review and update Azure unit tests (https://github.com/wazuh/wazuh/pull/14104) | [#28804](https://ci.wazuh.info/job/Test_integration/28804) | 4.5 |

## Case 

| Tier| Wazuh Type | OS
|--|--|--|
| 2 | Manager |  CentOS 

### Description

```
21:20:19  FAILED test_vulnerability_detector/test_feeds/test_download_feeds.py::test_download_feeds[RHEL5]
21:20:19  FAILED test_vulnerability_detector/test_feeds/test_download_feeds.py::test_download_feeds[RHEL6]
21:20:19  FAILED test_vulnerability_detector/test_feeds/test_download_feeds.py::test_download_feeds[RHEL7]
21:20:19  FAILED test_vulnerability_detector/test_feeds/test_download_feeds.py::test_download_feeds[RHEL8]
21:20:19  FAILED test_vulnerability_detector/test_feeds/test_download_feeds.py::test_download_feeds[ALAS]
21:20:19  FAILED test_vulnerability_detector/test_feeds/test_download_feeds.py::test_download_feeds[ALAS-2]
21:20:19  FAILED test_vulnerability_detector/test_feeds/test_download_feeds.py::test_download_feeds[ALAS-2022]
21:20:19  FAILED test_vulnerability_detector/test_feeds/test_validate_feed_content.py::test_validate_json_feed_content[Red Hat Enterprise Linux]

```

## Tasks
- [x] Run tests in Jenkins
- [ ] Run tests in local enviroment
- [ ] Read test code & docs and run tests manually
- [ ] Fix failures

**Comment by damarisg** [comment]
# Update 2022/07/16

## Run tests using Jenkins


Test Path | Os | Build | Date | By | Notes
-- | -- | -- | -- | -- | --
test_vulnerability_detector/ | CentOS - Manager|  [:green_circle: ](https://ci.wazuh.info/view/Tests/job/Test_integration/29406/) [:green_circle: ](https://ci.wazuh.info/view/Tests/job/Test_integration/29411/)[:green_circle: ](https://ci.wazuh.info/view/Tests/job/Test_integration/29412/)[:green_circle: ](https://ci.wazuh.info/view/Tests/job/Test_integration/29409/)[:green_circle: ](https://ci.wazuh.info/view/Tests/job/Test_integration/29410/) | 2022/07/16 | @damarisg |  


This issue was closed because we couldn't reproduce it.
