### ISSUE TITLE
Fix Agentd IT:  test_agentd_state test

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3076]
|Related issue|
|---|
|https://github.com/wazuh/wazuh-qa/issues/3057

| Date|  Commit | Commit title | Build | Version|
|--|--|--|--|--|
| 2022-07-07| [394f627](https://github.com/wazuh/wazuh/commit/394f627b3915f64dfc1a5b7ba55f61076159d2d2) | Review and update Azure unit tests (https://github.com/wazuh/wazuh/pull/14104) | [#28854](https://ci.wazuh.info/job/Test_integration/28854) | 4.5 |

## Case 

| Tier| Wazuh Type | OS
|--|--|--|
| 0 | Agent|  CentOS - Ubuntu - Windows

### Description

```
13:43:11  FAILED test_agentd/test_agentd_state.py::test_agentd_state[-Successful connection with remoted]

```

## Tasks
- [x] Run tests in Jenkins
- [ ] If it fails in Jenkins, run tests in local environment
- [ ] If it fails in Jenkins, Read test code & docs and run tests manually
- [ ] If it fails (Local/Jenkins), Fix failures

**Comment by QU3B1M** [comment]
# Update 12/07/2022
## Run tests using Jenkins


Test Path | Os | Build | Date | By | Notes
-- | -- | -- | -- | -- | --
test_fim/ | Centos |  [:green_circle: ](https://ci.wazuh.info/job/Test_integration/29160/console) [:green_circle: ](https://ci.wazuh.info/job/Test_integration/29161/console)[:green_circle: ](https://ci.wazuh.info/job/Test_integration/29162/console)[:green_circle: ](https://ci.wazuh.info/job/Test_integration/29163/console)[:green_circle: ](https://ci.wazuh.info/job/Test_integration/29164/console) | 11/07/2022 | Kevin |

**Comment by damarisg** [comment]
This issue was closed because we couldn't reproduce it.
