### ISSUE TITLE
QA testing - Instalation script (create user wazuh)

### ISSUE THREAD

**Issue by juliancnn** [wazuh/wazuh-qa#3089]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|       4.3            | https://github.com/wazuh/wazuh/issues/14063 | https://github.com/wazuh/wazuh/pull/14207 |

## Description

Currently, all versions of Wazuh (Agent and Manager), have a bug in the installation script.
   When installing from source or when upgrading wazuh from a version lower than 4.2, i.e. when the user and group are still ossec, it is necessary to create the user and group wazuh.
    The installation script, under certain conditions, does not detect that the user wazuh does not exist, so it does not create, triggering a series of errors in the installation or update. 

The PR  https://github.com/wazuh/wazuh/pull/14207  fixes the error in the installation script, when the[ grep filter detects the beginning of the user name and ignores the rest.](https://github.com/wazuh/wazuh/blob/394f627b3915f64dfc1a5b7ba55f61076159d2d2/src/init/adduser.sh#L75)

The passwd file:  `/etc/passwd` contains one line for each user account, with seven fields delimited by colons (“:”). The first its the login name.
The grep command filters for users that do not begin with `wazuh`, ignoring how they end, so if a `wazuh-indexer` user exists, the filtered grep will be positive, the if condition false, and then the user is never created at [line 83](https://github.com/wazuh/wazuh/blob/394f627b3915f64dfc1a5b7ba55f61076159d2d2/src/init/adduser.sh#L83).
## Proposed checks

- [x] Test on 4.3.5
   - [x] In a clean environment, create a user starting with `wazuh`, for example `useradd -m wazuh123` and install the Manager from source
      - [x] Centos
      - [x] Ubuntu
   - [x] In a clean environment, create a user starting with `wazuh`, for example `useradd -m wazuh123` and install the Manager from package
      - [x] Centos
   - [x] In a clean environment, create a user starting with `wazuh`, for example `useradd -m wazuh123` and install the Agent from source.
      - [x] Centos
      - [x] Ubuntu
   - [x] In an environment with an old version of wazuh-manager, using user and group ossec (4.2 <) and no wazuh user exists. Create a user starting with wazuh (`useradd -m wazuh123`) and update from sources.
      - [x] Centos
      - [x] Ubuntu
   - [x] In an environment with an old version of wazuh-manager, using user and group ossec (4.2 <) and no wazuh user exists. Create a user starting with wazuh (`useradd -m wazuh123`) and update from package.
      - [x] Centos
   - [x] In an environment with an old version of wazuh-agent, using user and group ossec (4.2 <) and no wazuh user exists. Create 
a user starting with wazuh (`useradd -m wazuh123`) and update from sources.
      - [x] Centos
      - [x] Ubuntu
   - [x] In an environment with an old version of wazuh, using user and group ossec (4.2 <) and no wazuh user exists. Create a user starting with wazuh (`useradd -m wazuh123`) and update by WPK.
      - [x] Centos
      - [x] Ubuntu

- [x] Test on Dev Branch
   - [x] In a clean environment, create a user starting with `wazuh`, for example `useradd -m wazuh123` and install the Manager from source
      - [x] Centos
      - [x] Ubuntu
   - [x] In a clean environment, create a user starting with `wazuh`, for example `useradd -m wazuh123` and install the Agent from source.
      - [x] Centos
      - [x] Ubuntu
   - [x] In an environment with an old version of wazuh-manager, using user and group ossec (4.2 <) and no wazuh user exists. Create a user starting with wazuh (`useradd -m wazuh123`) and update from sources.
      - [x] Centos
      - [x] Ubuntu
   - [x] In an environment with an old version of wazuh-manager, using user and group ossec (4.2 <) and no wazuh user exists. Create a user starting with wazuh (`useradd -m wazuh123`) and update from package.
      - [x] Centos
      - [x] Ubuntu
   - [x] In an environment with an old version of wazuh-agent, using user and group ossec (4.2 <) and no wazuh user exists. Create 
a user starting with wazuh (`useradd -m wazuh123`) and update from sources.
      - [x] Centos
      - [x] Ubuntu
   - [x] In an environment with an old version of wazuh-agent, using user and group ossec (4.2 <) and no wazuh user exists. Create 
a user starting with wazuh (`useradd -m wazuh123`) and update from package.
      - [x] Centos
      - [x] Ubuntu
   - [x] In an environment with an old version of wazuh, using user and group ossec (4.2 <) and no wazuh user exists. Create a user starting with wazuh (`useradd -m wazuh123`) and update by WPK.
      - [x] Centos
      - [x] Ubuntu
## Steps to reproduce

0. Optional:, only for update test: Install old version of Wazuh Manager or Agent (4.2<=)

1.  Verify that the user `wazuh` does not exist in the system, the following output should be empty:
```
╭─root@206-c7 ~/repos/wazuh ‹master●› 
╰─# getent passwd | grep ^wazuh:
╭─root@206-c7 ~/repos/wazuh ‹master●› 
╰─# 
```

2. Create a user other than `wazuh` but starting with wazuh, e.g. `useradd -m wazuh123`

3. Install or update wazuh by fonts or WPK

## Expected results
Error-free instalation

### standar ouput or upgrade.log (wpk)
```
Wait for success...
success
Removing old SCA policies...
Installing SCA policies...


Created symlink from /etc/systemd/system/multi-user.target.wants/wazuh-agent.service to /usr/lib/systemd/system/wazuh-agent.service.

 - Configuration finished properly.

 - To start Wazuh:
      /var/ossec/bin/wazuh-control start

 - To stop Wazuh:
      /var/ossec/bin/wazuh-control stop

 - The configuration can be viewed or modified at /var/ossec/etc/ossec.conf


   Thanks for using Wazuh.
   Please don't hesitate to contact us if you need help or find
   any bugs.

   Use our public Mailing List at:
          https://groups.google.com/forum/#!forum/wazuh

   More information can be found at:
          - http://www.wazuh.com

    ---  Press ENTER to finish (maybe more information below). ---

 - More information at: 
   https://documentation.wazuh.com/



...
```

## Actual results
```
Wait for success...
success
install: invalid user ‘wazuh’
install: invalid user ‘wazuh’
install: invalid user ‘wazuh’
install: invalid user ‘wazuh’
install: invalid user ‘wazuh’
install: invalid user ‘wazuh’
install: invalid user ‘wazuh’
install: invalid user ‘wazuh’
install: invalid user ‘wazuh’
install: invalid user ‘wazuh’
install: invalid user ‘wazuh’
install: invalid user ‘wazuh’
install: invalid user ‘wazuh’
install: invalid user ‘wazuh’
Removing old SCA policies...
Installing SCA policies...
install: invalid user ‘wazuh’


chown: invalid user: ‘wazuh:wazuh’
chown: invalid user: ‘wazuh:wazuh’
chown: invalid user: ‘wazuh:wazuh’
chown: invalid user: ‘wazuh:wazuh’
chown: invalid user: ‘wazuh:wazuh’
chown: invalid user: ‘wazuh:wazuh’
chown: invalid user: ‘wazuh:wazuh’
chown: invalid user: ‘wazuh:wazuh’
chown: invalid user: ‘wazuh:wazuh’
chown: invalid user: ‘wazuh:wazuh’
chown: invalid user: ‘wazuh:wazuh’
chown: invalid user: ‘wazuh:wazuh’
chown: invalid user: ‘wazuh:wazuh’
chown: invalid user: ‘wazuh:wazuh’
chown: invalid user: ‘wazuh:wazuh’
chown: invalid user: ‘wazuh:wazuh’
chown: invalid user: ‘wazuh:wazuh’
chown: invalid user: ‘wazuh:wazuh’
chown: invalid user: ‘wazuh:wazuh’
chown: invalid user: ‘wazuh:wazuh’
chown: invalid user: ‘wazuh:wazuh’
chown: invalid user: ‘wazuh:wazuh’
chown: invalid user: ‘wazuh:wazuh’
chown: invalid user: ‘wazuh:wazuh’
Wait for success...
success
Starting Wazuh...
Job for wazuh-agent.service failed because the control process exited with error code.
See "systemctl status wazuh-agent.service" and "journalctl -xe" for details.

 - Configuration finished properly.

 - To start Wazuh:
      /var/ossec/bin/wazuh-control start

 - To stop Wazuh:
      /var/ossec/bin/wazuh-control stop

 - The configuration can be viewed or modified at /var/ossec/etc/ossec.conf


   Thanks for using Wazuh.
   Please don't hesitate to contact us if you need help or find
   any bugs.

   Use our public Mailing List at:
          https://groups.google.com/forum/#!forum/wazuh

   More information can be found at:
          - http://www.wazuh.com

    ---  Press ENTER to finish (maybe more information below). ---

 - Update completed.

2022/06/28 00:54:40 - Installation result = 0
./var/upgrade/src/init/pkg_installer.sh: line 209: ./var/run/wazuh-agentd.state: No such file or directory
2022/06/28 00:54:41 - Waiting connection... Status = pending. Remaining attempts: 29.
./var/upgrade/src/init/pkg_installer.sh: line 209: ./var/run/wazuh-agentd.state: No such file or directory
2022/06/28 00:54:42 - Waiting connection... Status = pending. Remaining attempts: 28.
./var/upgrade/src/init/pkg_installer.sh: line 209: ./var/run/wazuh-agentd.state: No such file or directory
2022/06/28 00:54:43 - Waiting connection... Status = pending. Remaining attempts: 27.
./var/upgrade/src/init/pkg_installer.sh: line 209: ./var/run/wazuh-agentd.state: No such file or directory
2022/06/28 00:54:44 - Waiting connection... Status = pending. Remaining attempts: 26.
```

**Comment by Deblintrake09** [comment]
## Task results on dev branch





<details>
<summary>Clean Install Manager from Sources (Centos 8) :green_circle: </summary>

1. Add **wazuh123** user `useradd -m wazuh123`
   ```
   getent passwd | grep wazuh
   wazuh123:x:1001:1001::/home/wazuh123:/bin/bash
   ```
2. Install dependencies
   ```
   yum install make cmake gcc gcc-c++ python3 python3-policycoreutils automake autoconf libtool openssl-devel yum-utils
   yum-config-manager --enable powertools
   yum install libstdc++-static -y
   curl -OL https://packages.wazuh.com/utils/cmake/cmake-3.18.3.tar.gz && tar -zxf cmake-3.18.3.tar.gz && cd cmake-3.18.3 && ./bootstrap --no-system-curl && make -j$(nproc) && make install
   cd .. && rm -rf cmake-*
   export PATH=/usr/local/bin:$PATH
   ```
3. Download Repository
   ```
   curl -OL https://github.com/wazuh/wazuh/archive/refs/heads/14063-fix-installation-script.zip && unzip 14063-fix-installation-script.zip
   cd wazuh-14063-fix-installation-script
   ```
4. Build Manager 
   ```
   ./install.sh 
   ```
![imagen](https://user-images.githubusercontent.com/14501079/178482341-df0c9e6a-ae21-4054-9b4f-c51daba85e84.png)
```
Generating self-signed certificate for wazuh-authd...


 - System is Redhat Linux.
 - Init script modified to start Wazuh during boot.
Starting Wazuh...
server
Starting Wazuh v4.3.6...
Started wazuh-apid...
Started wazuh-csyslogd...
Started wazuh-dbd...
2022/07/12 12:06:58 wazuh-integratord: INFO: Remote integrations not configured. Clean exit.
Started wazuh-integratord...
Started wazuh-agentlessd...
Started wazuh-authd...
Started wazuh-db...
Started wazuh-execd...
Started wazuh-analysisd...
Started wazuh-syscheckd...
Started wazuh-remoted...
Started wazuh-logcollector...
Started wazuh-monitord...
Started wazuh-modulesd...
Completed.

 - Configuration finished properly.

 - To start Wazuh:
      /var/ossec/bin/wazuh-control start

 - To stop Wazuh:
      /var/ossec/bin/wazuh-control stop

 - The configuration can be viewed or modified at /var/ossec/etc/ossec.conf


   Thanks for using Wazuh.
   Please don't hesitate to contact us if you need help or find
   any bugs.

   Use our public Mailing List at:
          https://groups.google.com/forum/#!forum/wazuh

   More information can be found at:
          - http://www.wazuh.com

    ---  Press ENTER to finish (maybe more information below). ---
```
</details>










<details>
<summary>Clean install Agent from sources (Centos8) :green_circle: </summary>

1. Add **wazuh123** user `useradd -m wazuh123`
   ```
   getent passwd | grep wazuh
   wazuh123:x:1001:1001::/home/wazuh123:/bin/bash
   ```
2. Install dependencies
   ```
   yum install make cmake gcc gcc-c++ python3 python3-policycoreutils automake autoconf libtool openssl-devel yum-utils
   yum-config-manager --enable powertools
   yum install libstdc++-static -y
   curl -OL https://packages.wazuh.com/utils/cmake/cmake-3.18.3.tar.gz && tar -zxf cmake-3.18.3.tar.gz && cd cmake-3.18.3 && ./bootstrap --no-system-curl && make -j$(nproc) && make install
   cd .. && rm -rf cmake-*
   export PATH=/usr/local/bin:$PATH
   ```
3. Download Repository
   ```
   curl -OL https://github.com/wazuh/wazuh/archive/refs/heads/14063-fix-installation-script.zip && unzip 14063-fix-installation-script.zip
   cd wazuh-14063-fix-installation-script
   ```
4. Build Agent
![imagen](https://user-images.githubusercontent.com/14501079/178482449-bc19e8a1-6408-4b9c-ade7-4d361532c092.png)
```
    LDFLAGS           '-Wl,-rpath,/../lib' -pthread -lrt -ldl -O2 -Lshared_modules/dbsync/build/lib -Lshared_modules/rsync/build/lib  -Lwazuh_modules/syscollector/build/lib -Ldata_provider/build/lib
    LIBS              -lrt -ldl -lm 
    CC                cc
    MAKE              make
make[1]: Leaving directory '/home/qa/wazuh-14063-fix-installation-script/src'

Done building agent

Wait for success...
success
Removing old SCA policies...
Installing SCA policies...


 - System is Redhat Linux.
 - Init script modified to start Wazuh during boot.

 - Configuration finished properly.

 - To start Wazuh:
      /var/ossec/bin/wazuh-control start

 - To stop Wazuh:
      /var/ossec/bin/wazuh-control stop

 - The configuration can be viewed or modified at /var/ossec/etc/ossec.conf


   Thanks for using Wazuh.
   Please don't hesitate to contact us if you need help or find
   any bugs.

   Use our public Mailing List at:
          https://groups.google.com/forum/#!forum/wazuh

   More information can be found at:
          - http://www.wazuh.com

    ---  Press ENTER to finish (maybe more information below). ---
```
</details>






<details>
<summary>Clean install Agent from sources (Ubuntu) :green_circle: </summary>

1. Add **wazuh123** user `useradd -m wazuh123`
   ```
   getent passwd | grep wazuh
   wazuh123:x:1001:1001::/home/wazuh123:/bin/bash
   ```
2. Install dependencies
   ```
   apt-get update
   apt-get install python gcc g++ make libc6-dev curl policycoreutils automake autoconf libtool libssl-dev
   curl -OL https://packages.wazuh.com/utils/cmake/cmake-3.18.3.tar.gz && tar -zxf cmake-3.18.3.tar.gz && cd cmake-3.18.3 && ./bootstrap --no-system-curl && make -j$(nproc) && make install
    cd .. && rm -rf cmake-*
   ```
3. Download Repository
   ```
   curl -OL https://github.com/wazuh/wazuh/archive/refs/heads/14063-fix-installation-script.zip && unzip 14063-fix-installation-script.zip
   cd wazuh-14063-fix-installation-script
   ```
4. Build Agent
![imagen](https://user-images.githubusercontent.com/14501079/178486174-8326e4ae-dd0b-45c6-86ad-17ed9366b794.png)

</details>
