### ISSUE TITLE
Fix Remoted IT(4.4): Multiple Failures

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3119]
| Date|  Commit | Commit title | Build | Version| Status 
|--|--|--|--|--|--|
| 2022-07-20|  |  | [#29491](https://ci.wazuh.info/job/Test_integration/29491/ ) | 4.4 | 🔴 
| 2022-07-20|  |  | [#29491](https://ci.wazuh.info/job/Test_integration/29477/) | 4.4 | 🟢 

## Case 

| Wazuh Type | OS
|--|--|
| Manager |  CentOS 

### Description

```
15:07:38  =========================== short test summary info ============================
15:07:38  FAILED test_remoted/test_agent_communication/test_agents_switching_protocols.py::test_agents_switching_protocols[56000]
15:07:38  FAILED test_remoted/test_agent_communication/test_invalid_protocol_communication.py::test_invalid_protocol_communication[UDP_56000]
15:07:38  FAILED test_remoted/test_agent_communication/test_multi_agent_protocols_communication.py::test_multi_agents_protocols_communication[TCP_1514]
15:07:38  FAILED test_remoted/test_agent_communication/test_multi_agent_protocols_communication.py::test_multi_agents_protocols_communication[TCP,UDP_1514]
15:07:38  FAILED test_remoted/test_agent_communication/test_protocols_communication.py::test_protocols_communication[UDP_56000]
15:07:38  FAILED test_remoted/test_agent_communication/test_protocols_communication.py::test_protocols_communication[TCP,UDP_56000]
15:07:38  FAILED test_remoted/test_agent_communication/test_protocols_communication.py::test_protocols_communication[UDP,TCP_56000]
15:07:38  FAILED test_remoted/test_configuration/test_basic_configuration_connection_invalid_protocol.py::test_invalid_protocol[Testing,UDP_secure_1514]
15:07:38  FAILED test_remoted/test_configuration/test_basic_configuration_connection_invalid_protocol.py::test_invalid_protocol[TCP,Testing_secure_1514]
15:07:38  FAILED test_remoted/test_configuration/test_basic_configuration_connection_invalid_protocol.py::test_invalid_protocol[Testing,Testing_secure_1514]
15:07:38  FAILED test_remoted/test_configuration/test_basic_configuration_connection_invalid_protocol.py::test_invalid_protocol[TCP,UDP,Testing_secure_1514]
15:07:38  FAILED test_remoted/test_configuration/test_basic_configuration_connection_invalid_protocol.py::test_invalid_protocol[Testing,UDP_syslog_514]
15:07:38  FAILED test_remoted/test_configuration/test_basic_configuration_connection_invalid_protocol.py::test_invalid_protocol[TCP,Testing_syslog_514]
15:07:38  FAILED test_remoted/test_configuration/test_basic_configuration_connection_invalid_protocol.py::test_invalid_protocol[Testing,Testing_syslog_514]
15:07:38  FAILED test_remoted/test_configuration/test_basic_configuration_connection_invalid_protocol.py::test_invalid_protocol[TCP,UDP,Testing_syslog_514]
15:07:38  FAILED test_remoted/test_configuration/test_basic_configuration_connection_valid.py::test_connection_valid[UDP_secure_1514]
15:07:38  FAILED test_remoted/test_configuration/test_basic_configuration_connection_valid.py::test_connection_valid[UDP_syslog_514]
15:07:38  FAILED test_remoted/test_configuration/test_basic_configuration_connection_valid.py::test_connection_valid[TCP_syslog_553]
15:07:38  FAILED test_remoted/test_configuration/test_basic_configuration_connection_valid.py::test_connection_valid[TCP_secure_23467]
15:07:38  FAILED test_remoted/test_configuration/test_basic_configuration_connection_valid.py::test_connection_valid[TCP,UDP_secure_1209]
15:07:38  FAILED test_remoted/test_configuration/test_basic_configuration_connection_valid.py::test_connection_valid[TCP,UDP_syslog_2134]
15:07:38  FAILED test_remoted/test_configuration/test_basic_configuration_connection_valid.py::test_connection_valid[UDP,TCP_secure_55632]
15:07:38  FAILED test_remoted/test_configuration/test_basic_configuration_connection_valid.py::test_connection_valid[UDP,TCP_syslog_2134]
15:07:38  FAILED test_remoted/test_configuration/test_basic_configuration_local_ip_valid.py::test_local_ip_valid[127.0.0.1]
15:07:38  FAILED test_remoted/test_configuration/test_basic_configuration_local_ip_valid.py::test_local_ip_valid[172.31.10.90]
15:07:38  FAILED test_remoted/test_configuration/test_basic_configuration_queue_size_too_big.py::test_big_queue_size[('secure', '1514', '99999999')]
15:07:38  FAILED test_remoted/test_configuration/test_basic_configuration_queue_size_valid.py::test_queue_size_valid[('secure', '1514', '1')]
15:07:38  FAILED test_remoted/test_configuration/test_basic_configuration_queue_size_valid.py::test_queue_size_valid[('secure', '1514', '1200')]
15:07:38  FAILED test_remoted/test_configuration/test_basic_configuration_queue_size_valid.py::test_queue_size_valid[('secure', '1514', '262144')]
15:07:38  FAILED test_remoted/test_configuration/test_basic_configuration_rids_closing_time_valid.py::test_rids_closing_time_valid[('secure', '1514', '1s')]
15:07:38  FAILED test_remoted/test_configuration/test_basic_configuration_rids_closing_time_valid.py::test_rids_closing_time_valid[('secure', '1514', '30s')]
15:07:38  FAILED test_remoted/test_configuration/test_basic_configuration_rids_closing_time_valid.py::test_rids_closing_time_valid[('secure', '1514', '1m')]
15:07:38  FAILED test_remoted/test_configuration/test_basic_configuration_rids_closing_time_valid.py::test_rids_closing_time_valid[('secure', '1514', '30m')]
15:07:38  FAILED test_remoted/test_configuration/test_basic_configuration_rids_closing_time_valid.py::test_rids_closing_time_valid[('secure', '1514', '1h')]
15:07:38  FAILED test_remoted/test_configuration/test_basic_configuration_rids_closing_time_valid.py::test_rids_closing_time_valid[('secure', '1514', '30h')]
15:07:38  FAILED test_remoted/test_configuration/test_basic_configuration_rids_closing_time_valid.py::test_rids_closing_time_valid[('secure', '1514', '1d')]
15:07:38  FAILED test_remoted/test_configuration/test_basic_configuration_rids_closing_time_valid.py::test_rids_closing_time_valid[('secure', '1514', '30d')]
15:07:38  FAILED test_remoted/test_configuration/test_basic_configuration_syslog_allowed_denied_ips_valid.py::test_allowed_denied_ips_syslog[127.0.0.0/24_192.168.1.1/24_no]
15:07:38  FAILED test_remoted/test_configuration/test_basic_configuration_syslog_allowed_denied_ips_valid.py::test_allowed_denied_ips_syslog[0000:0000:0000:0000:0000:0000:0000:0001/64_fe80::1003:889f:a584:0101/64_yes]
15:07:38  FAILED test_remoted/test_configuration/test_basic_configuration_syslog_allowed_denied_ips_valid.py::test_allowed_denied_ips_syslog[::1/64_fe80::1003:889f:a584:0101/64_yes]
15:07:38  FAILED test_remoted/test_configuration/test_basic_configuration_syslog_denied_ips.py::test_denied_ips_syslog[127.0.0.0/24_127.0.0.1]
15:07:38  FAILED test_remoted/test_configuration/test_basic_configuration_syslog_denied_ips.py::test_denied_ips_syslog[0000:0000:0000:0000:0000:0000:0000:0001/64_::1]
15:07:38  FAILED test_remoted/test_configuration/test_basic_configuration_syslog_denied_ips.py::test_denied_ips_syslog[::1/64_::1]
15:07:38  FAILED test_remoted/test_socket_communication/test_ping_pong_message.py::test_ping_pong_message[UDP_56000]
15:07:38  FAILED test_remoted/test_socket_communication/test_ping_pong_message.py::test_ping_pong_message[UDP,TCP_56000]
15:07:38  FAILED test_remoted/test_socket_communication/test_ping_pong_message.py::test_ping_pong_message[TCP,UDP_56000]
15:07:38  FAILED test_remoted/test_socket_communication/test_ping_pong_message.py::test_ping_pong_message[UDP,UDP_56000]
15:07:38  FAILED test_remoted/test_socket_communication/test_ping_pong_message.py::test_ping_pong_message[udp_56000]
15:07:38  FAILED test_remoted/test_socket_communication/test_ping_pong_message.py::test_ping_pong_message[udp,tcp_56000]
15:07:38  FAILED test_remoted/test_socket_communication/test_ping_pong_message.py::test_ping_pong_message[tcp,udp_56000]
15:07:38  FAILED test_remoted/test_socket_communication/test_ping_pong_message.py::test_ping_pong_message[udp,udp_56000]
15:07:38  FAILED test_remoted/test_socket_communication/test_syslog_message.py::test_syslog_message[syslog_UDP_514-dummy]
15:07:38  FAILED test_remoted/test_socket_communication/test_syslog_message.py::test_syslog_message[syslog_UDP_514-failed_login_sshd]
15:07:38  FAILED test_remoted/test_socket_communication/test_syslog_message.py::test_syslog_message[syslog_UDP_514-failed_login_sshd_pri_header]
15:07:38  FAILED test_remoted/test_socket_communication/test_syslog_message.py::test_syslog_message[syslog_UDP_514-dummy_pri_header]
15:07:38  FAILED test_remoted/test_socket_communication/test_syslog_message.py::test_syslog_message[syslog_UDP_514-dummy_bad_formatted_pri_header]
15:07:38  ERROR test_remoted/test_agent_communication/test_agent_pending_status.py::test_protocols_communication[UDP_56000]
15:07:38  ERROR test_remoted/test_agent_communication/test_agent_pending_status.py::test_protocols_communication[TCP,UDP_56000]
15:07:38  ERROR test_remoted/test_agent_communication/test_agent_version_shared_configuration_startup_message.py::test_agent_remote_configuration[TCP-debian7_420]
15:07:38  ERROR test_remoted/test_agent_communication/test_agent_version_shared_configuration_startup_message.py::test_agent_remote_configuration[TCP-debian9_4.4.0]
15:07:38  ERROR test_remoted/test_agent_communication/test_agent_version_shared_configuration_startup_message.py::test_agent_remote_configuration[UDP-debian7_420]
15:07:38  ERROR test_remoted/test_agent_communication/test_agent_version_shared_configuration_startup_message.py::test_agent_remote_configuration[UDP-debian9_4.4.0]
15:07:38  ERROR test_remoted/test_agent_communication/test_agent_version_shared_configuration_startup_message.py::test_agent_remote_configuration[TCP,UDP-debian7_420]
15:07:38  ERROR test_remoted/test_agent_communication/test_agent_version_shared_configuration_startup_message.py::test_agent_remote_configuration[TCP,UDP-debian9_4.4.0]
15:07:38  ERROR test_remoted/test_agent_communication/test_multi_agent_protocols_communication.py::test_multi_agents_protocols_communication[UDP_56000]
15:07:38  ERROR test_remoted/test_agent_communication/test_multi_agent_protocols_communication.py::test_multi_agents_protocols_communication[TCP,UDP_56000]
15:07:38  ERROR test_remoted/test_agent_communication/test_shared_configuration.py::test_push_shared_config[TCP]
15:07:38  ERROR test_remoted/test_agent_communication/test_shared_configuration.py::test_push_shared_config[UDP]
15:07:38  ERROR test_remoted/test_agent_communication/test_shared_configuration.py::test_push_shared_config[TCP,UDP]
15:07:38  ERROR test_remoted/test_multi_groups/test_merged_mg_file_content.py::test_merged_mg_file_content[check_that_the_new_file_is_added]
15:07:38  ERROR test_remoted/test_multi_groups/test_merged_mg_file_content.py::test_merged_mg_file_content[check_that_the_old_file_is_deleted]
15:07:38  = 56 failed, 117 passed, 28 skipped, 6 xfailed, 15 errors in 1448.32s (0:24:08) =
  

```
## Notes:

Some of these tests are still failing in 4.4: https://github.com/wazuh/wazuh/pull/13713/checks?check_run_id=7412534976
```
ERROR test_remoted/test_multi_groups/test_merged_mg_file_content.py::test_merged_mg_file_content[check_that_the_new_file_is_added]
ERROR test_remoted/test_multi_groups/test_merged_mg_file_content.py::test_merged_mg_file_content[check_that_the_old_file_is_deleted]
```

## Tasks
- [x] Run tests in Jenkins
- [ ] If it fails in Jenkins, run tests in local environment
- [ ] If it fails in Jenkins, Read test code & docs and run tests manually
- [ ] If it fails (Local/Jenkins), Fix failures

**Comment by QU3B1M** [comment]
# Update 22/07/2022

##  Run tests in Jenkins

| Test Path | Os |  Executions | Date | By | Notes |
|--|--|--|--|--|--|
| test_remoted/  | Centos |  [:green_circle: ](https://ci.wazuh.info/job/Test_integration/29525/console) [:green_circle: ](https://ci.wazuh.info/job/Test_integration/29531/console) [:green_circle: ](https://ci.wazuh.info/job/Test_integration/29530/console) [:green_circle: ](https://ci.wazuh.info/job/Test_integration/29526/console) [:green_circle: ](https://ci.wazuh.info/job/Test_integration/29527/console) [:green_circle: ](https://ci.wazuh.info/job/Test_integration/29528/console)  |  22/07/2022 |  Kevin |  |

**Comment by QU3B1M** [comment]
# Update 08/08/2022

### Run tests in local environment

| Test Path | Os |  Executions | Date | By | Notes |
|--|--|--|--|--|--|
| test_remoted/ | Centos |  [:green_circle: ](https://github.com/wazuh/wazuh-qa/files/9283272/results1.zip) [:green_circle: ](https://github.com/wazuh/wazuh-qa/files/9283273/results2.zip) [:red_circle: ](https://github.com/wazuh/wazuh-qa/files/9283274/results3.zip)   | 08/08/2022 | Kevin | |
