### ISSUE TITLE
QA testing - Include enrollment block when WAZUH_REGISTRATION_PASSWORD variable is defined

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh-qa#3124]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|             4.4.0           |           https://github.com/wazuh/wazuh-packages/issues/1565             |         https://github.com/wazuh/wazuh/pull/14241           |

## Description

We want to test if WAZUH_REGISTRATION_PASSWORD auto deploy variable create the enrollment block with the password file path attached

## Proposed checks

- [x] Enrollment block created with this variable defined
- [x] Enrollment block not created with WAZUH_MANAGER variable or another not related with enrollment
- [x] Enrollment block has `authorization_pass_path` if WAZUH_REGISTRATION_PASSWORD is defined
- [x] Include another enrollment variables like WAZUH_REGISTRATION_SERVER

## Expected results

Check PR for more information

## Configuration and considerations

Check PR for more information

**Comment by Deblintrake09** [comment]
## Review data

| Tester | PR commit               | Conclusion                   |
|--------|-------------------------|------------------------------|
| @Deblintrake09 |     | :yellow_circle: |

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
|  Centos  |   8         | `<LOCAL \| Vagrant` |   qactl/centos_8        |       |
|  Ubuntu  |   20.04         | `<LOCAL \| Vagrant` |   qactl/ubuntu20_04        |       |
|  Windows10  |            | `<LOCAL \| Vagrant` |   qactl/ubuntu20_04        |       |


### Tested packages

| `wazuh-manager` | `wazuh-agent` | 
|-----------------|---------------|
|     [.rpm Manager](https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/rpm/var/wazuh-manager-4.4.0-0.commit2ecd999.x86_64.rpm)            |  [.rpm agent](https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/rpm/var/wazuh-agent-4.4.0-0.commit2ecd999.x86_64.rpm)   -  [.deb agent](https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/deb/var/wazuh-agent_4.4.0-0.commit2ecd999_amd64.deb) -  win agent        |

### Status

- [x] In progress
- [ ] Pending Review
- [ ] Team leader approved
- [ ] Manager approved

**Comment by Deblintrake09** [comment]
## Task results

<details>
<summary>Install Ubuntu Agent :green_circle: </summary>

1. Download package
   ```
   curl -OL https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/deb/var/wazuh-agent_4.4.0-0.commit2ecd999_amd64.deb
   ```
2. Install agent
![imagen](https://user-images.githubusercontent.com/14501079/180856649-91403929-03ee-488f-a4c8-093dc118991c.png)
3. Check agent's configuration
![imagen](https://user-images.githubusercontent.com/14501079/180856771-71ca8249-0121-4c7c-a198-f65b9342a73b.png)
4. Start agent
   ```
   /home/vagrant# /var/ossec/bin/wazuh-control start
   Starting Wazuh v4.4.0...
   Started wazuh-execd...
   Started wazuh-agentd...
   Started wazuh-syscheckd...
   Started wazuh-logcollector...
   Started wazuh-modulesd...
   Completed.
   ```
5. Check agent is connected with manager :red_circle: 
   ```
   [root@c3 vagrant]# /var/ossec/bin/agent_control -l
   Wazuh agent_control. List of available agents:
      ID: 000, Name: c3 (server), IP: 127.0.0.1, Active/Local
   ```
6. Check `/var/ossec` folder for auth.pass file
   ```
   ls /var/ossec/etc/
   client.keys            local_internal_options.conf  ossec.conf  wpk_root.pem
   internal_options.conf  localtime                    shared
   ```
7. Check agent's ossec.log
   ```
   2022/07/25 19:36:11 wazuh-modulesd:syscollector: INFO: Evaluation finished.
   2022/07/25 19:36:12 wazuh-agentd: INFO: Requesting a key from server: 192.168.56.10
   2022/07/25 19:36:12 wazuh-agentd: INFO: No authentication password provided
   2022/07/25 19:36:12 wazuh-agentd: INFO: Using agent name as: test
   2022/07/25 19:36:12 wazuh-agentd: INFO: Waiting for server reply
   2022/07/25 19:36:12 wazuh-agentd: ERROR: Invalid password (from manager)
   2022/07/25 19:36:12 wazuh-agentd: ERROR: Unable to add agent (from manager)
   ```
8. Generate `auth.pass` file in agent
   ```
   echo "<SuperSecret>" > /var/ossec/etc/authd.pass
   ```
9. Check agent is connected with manager
   ```
   [root@c3 vagrant]# /var/ossec/bin/agent_control -l
   Wazuh agent_control. List of available agents:
      ID: 000, Name: c3 (server), IP: 127.0.0.1, Active/Local
      ID: 001, Name: test, IP: any, Active
   ```
</details>


<details>
<summary>Install Centos Agent :green_apple: </summary>

1. Download package
![imagen](https://user-images.githubusercontent.com/14501079/180859320-a7dfd5d8-b58c-4801-8725-fed0897e07cf.png)
2. Install agent
   ```
   # WAZUH_MANAGER=192.168.56.10 WAZUH_REGISTRATION_PASSWORD='SuperSecret' WAZUH_REGISTRATION_SERVER=192.168.56.10 yum -y install wazuh-agent-4.4.0-0.commit2ecd999.x86_64.rpm
   Verifying        : wazuh-agent-4.4.0-0.commit2ecd999.x86_64                         1/1 

   Installed:
     wazuh-agent-4.4.0-0.commit2ecd999.x86_64                                                

   Complete!
   ```
3. Check agent's configuration
   ```
     <client>
       <server>
         <address>192.168.56.10</address>
         <port>1514</port>
         <protocol>tcp</protocol>
       </server>
       <config-profile>centos, centos8, centos8.4</config-profile>
       <notify_time>10</notify_time>
       <time-reconnect>60</time-reconnect>
       <auto_restart>yes</auto_restart>
       <crypto_method>aes</crypto_method>
       <enrollment>
         <enabled>yes</enabled>
         <manager_address>192.168.56.10</manager_address>
         <authorization_pass_path>etc/authd.pass</authorization_pass_path>
       </enrollment>
     </client>
   ```
4. Start agent
   ```
   /home/vagrant# /var/ossec/bin/wazuh-control start
   Starting Wazuh v4.4.0...
   Started wazuh-execd...
   Started wazuh-agentd...
   Started wazuh-syscheckd...
   Started wazuh-logcollector...
   Started wazuh-modulesd...
   Completed.
   ```
5. Check agent is connected with manager
   ```
   [root@c3 vagrant]# /var/ossec/bin/agent_control -l
   Wazuh agent_control. List of available agents:
      ID: 000, Name: c3 (server), IP: 127.0.0.1, Active/Local
      ID: 001, Name: test, IP: any, Active
   ```

6. Check `/var/ossec` folder for auth.pass file
   ```
   ls /var/ossec/etc/
   client.keys            local_internal_options.conf  ossec.conf  wpk_root.pem
   internal_options.conf  localtime                    shared
   ```
7. Check agent's ossec.log
   ```
   2022/07/25 19:40:25 wazuh-modulesd:syscollector: INFO: Evaluation finished.
   2022/07/25 19:40:26 wazuh-agentd: INFO: Requesting a key from server: 192.168.56.10
   2022/07/25 19:40:26 wazuh-agentd: INFO: No authentication password provided
   2022/07/25 19:40:26 wazuh-agentd: INFO: Using agent name as: Centos1
   2022/07/25 19:40:26 wazuh-agentd: INFO: Waiting for server reply
   2022/07/25 19:40:26 wazuh-agentd: ERROR: Invalid password (from manager)
   2022/07/25 19:40:26 wazuh-agentd: ERROR: Unable to add agent (from manager)
   ```
8. Generate `auth.pass` file in agent
   ```
   echo "<SuperSecret>" > /var/ossec/etc/authd.pass
   ```
9. Check agent is connected with manager
   ```
   [root@c3 vagrant]# /var/ossec/bin/agent_control -l
   Wazuh agent_control. List of available agents:
      ID: 000, Name: c3 (server), IP: 127.0.0.1, Active/Local
      ID: 001, Name: test, IP: any, Active
      ID: 002, Name: Centos1, IP: any, Never connected
   ```
</details>

**Comment by DFolchA** [comment]
## Update

Fixed issue described in https://github.com/wazuh/wazuh-qa/issues/3124#issuecomment-1194544025

### Packages
- https://s3.us-west-1.amazonaws.com/packages-dev.wazuh.com/warehouse/test/4.4/rpm/var/wazuh-agent-4.4.0-0.0.0.registration.x86_64.rpm
- https://s3.us-west-1.amazonaws.com/packages-dev.wazuh.com/warehouse/test/4.4/deb/var/wazuh-agent_4.4.0-0.0.0.registration_amd64.deb

**Comment by Deblintrake09** [comment]
## Linux testing Round 2

<details>
<summary>Install Ubuntu Agent :green_circle: </summary>

1. Download package
   ```
   curl -OL https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/deb/var/wazuh-agent_4.4.0-0.commit2ecd999_amd64.deb
   ```
2. Install agent
   ```
      # WAZUH_MANAGER=10.0.10.2 WAZUH_REGISTRATION_PASSWORD='SuperSecret' WAZUH_REGISTRATION_SERVER=10.0.10.2 apt install -y /home/vagrant/wazuh-agent_4.4.0-0.0.0.registration_amd64.debReading package lists... Done
   Building dependency tree       
   Reading state information... Done
   Note, selecting 'wazuh-agent' instead of '/home/vagrant/wazuh-agent_4.4.0-0.0.0.registration_amd64.deb'
   The following NEW packages will be installed:
     wazuh-agent
   0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
   Need to get 0 B/8,731 kB of archives.
   After this operation, 28.1 MB of additional disk space will be used.
   Get:1 /home/vagrant/wazuh-agent_4.4.0-0.0.0.registration_amd64.deb wazuh-agent amd64 4.4.0-0.0.0.registration [8,731 kB]
   Preconfiguring packages ...       
   Selecting previously unselected package wazuh-agent.
   (Reading database ... 77698 files and directories currently installed.)
   Preparing to unpack .../wazuh-agent_4.4.0-0.0.0.registration_amd64.deb ...
   Unpacking wazuh-agent (4.4.0-0.0.0.registration) ...
   Setting up wazuh-agent (4.4.0-0.0.0.registration) ...
   Processing triggers for systemd (245.4-4ubuntu3.13) ...
   ```
3. Check agent's configuration
   ```
      <ossec_config>
     <client>
       <server>
         <address>10.0.10.2</address>
         <port>1514</port>
         <protocol>tcp</protocol>
       </server>
       <config-profile>ubuntu, ubuntu20, ubuntu20.04</config-profile>
       <notify_time>10</notify_time>
       <time-reconnect>60</time-reconnect>
       <auto_restart>yes</auto_restart>
       <crypto_method>aes</crypto_method>
       <enrollment>
         <enabled>yes</enabled>
         <manager_address>10.0.10.2</manager_address>
         <authorization_pass_path>etc/authd.pass</authorization_pass_path>
       </enrollment>
     </client>
   ```
4. Check `/var/ossec` folder for auth.pass file
   ```
   # ls /var/ossec/etc/
   authd.pass   internal_options.conf        localtime   shared
   client.keys  local_internal_options.conf  ossec.conf  wpk_root.pem
   ```
5. Start agent
   ```
   /home/vagrant# /var/ossec/bin/wazuh-control start
   Starting Wazuh v4.4.0...
   Started wazuh-execd...
   Started wazuh-agentd...
   Started wazuh-syscheckd...
   Started wazuh-logcollector...
   Started wazuh-modulesd...
   Completed.
   ```
5. Check agent is connected with manager :red_circle: 
   ```
   [root@c3 vagrant]# /var/ossec/bin/agent_control -l
   Wazuh agent_control. List of available agents:
      ID: 000, Name: c3 (server), IP: 127.0.0.1, Active/Local
      ID: 001, Name: test, IP: any, Active
   ```
7. Check agent's ossec.log
   ```
   2022/07/26 11:45:35 wazuh-agentd: INFO: Requesting a key from server: 10.0.10.2
   2022/07/26 11:45:35 wazuh-agentd: INFO: Using agent name as: test
   2022/07/26 11:45:35 wazuh-agentd: INFO: Waiting for server reply
   2022/07/26 11:46:20 wazuh-agentd: INFO: Valid key received
   ```
</details>


<details>
<summary>Install Centos Agent :green_circle: </summary>

1. Download package
   ```
   # curl -OL https://s3.us-west-1.amazonaws.com/packages-dev.wazuh.com/warehouse/test/4.4/rpm/var/wazuh-agent-4.4.0-0.0.0.registration.x86_64.rpm
   ```
2. Install agent
   ```
   # WAZUH_MANAGER=10.0.10.2 WAZUH_REGISTRATION_PASSWORD='SuperSecret' WAZUH_REGISTRATION_SERVER=10.0.10.2 yum -y install install wazuh-agent-4.4.0-0.0.0.registration.x86_64.rpm
    Verifying        : wazuh-agent-4.4.0-0.0.0.registration.x86_64                                 1/1 

   Installed:
     wazuh-agent-4.4.0-0.0.0.registration.x86_64                                                        

   Complete!
   ```
3. Check agent's configuration
   ```
     <client>
       <server>
         <address>10.0.10.2</address>
         <port>1514</port>
         <protocol>tcp</protocol>
       </server>
       <config-profile>centos, centos8, centos8.4</config-profile>
       <notify_time>10</notify_time>
       <time-reconnect>60</time-reconnect>
       <auto_restart>yes</auto_restart>
       <crypto_method>aes</crypto_method>
       <enrollment>
         <enabled>yes</enabled>
         <manager_address>10.0.10.2</manager_address>
         <authorization_pass_path>etc/authd.pass</authorization_pass_path>
       </enrollment>
     </client>
   ```
4. Check `/var/ossec` folder for auth.pass file
   ```
   # ls /var/ossec/etc/
   authd.pass   internal_options.conf        localtime   shared
   client.keys  local_internal_options.conf  ossec.conf  wpk_root.pem
   ```
5. Start agent
   ```
   /home/vagrant# /var/ossec/bin/wazuh-control start
   Starting Wazuh v4.4.0...
   Started wazuh-execd...
   Started wazuh-agentd...
   Started wazuh-syscheckd...
   Started wazuh-logcollector...
   Started wazuh-modulesd...
   Completed.
   ```
6. Check agent is connected with manager
   ```
   [root@c3 vagrant]# /var/ossec/bin/agent_control -l
   Wazuh agent_control. List of available agents:
      ID: 000, Name: c3 (server), IP: 127.0.0.1, Active/Local
      ID: 001, Name: test, IP: any, Active
      ID: 002, Name: Centos1, IP: any, Active
   ```
7. 
   ```
   2022/07/26 11:54:33 wazuh-agentd: INFO: Requesting a key from server: 10.0.10.2
   2022/07/26 11:54:33 wazuh-agentd: INFO: Using password specified on file: etc/authd.pass
   2022/07/26 11:54:33 wazuh-agentd: INFO: Using agent name as: Centos1
   2022/07/26 11:54:33 wazuh-agentd: INFO: Waiting for server reply
   2022/07/26 11:54:33 wazuh-agentd: INFO: Valid key received
   ```
</details>

**Comment by Deblintrake09** [comment]
## Linux testing Round 2

<details>
<summary>Install Ubuntu Agent :green_circle: </summary>

1. Download package
   ```
   curl -OL https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/deb/var/wazuh-agent_4.4.0-0.commit2ecd999_amd64.deb
   ```
2. Install agent
   ```
      # WAZUH_MANAGER=10.0.10.2 WAZUH_REGISTRATION_PASSWORD='SuperSecret' WAZUH_REGISTRATION_SERVER=10.0.10.2 apt install -y /home/vagrant/wazuh-agent_4.4.0-0.0.0.registration_amd64.debReading package lists... Done
   Building dependency tree       
   Reading state information... Done
   Note, selecting 'wazuh-agent' instead of '/home/vagrant/wazuh-agent_4.4.0-0.0.0.registration_amd64.deb'
   The following NEW packages will be installed:
     wazuh-agent
   0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
   Need to get 0 B/8,731 kB of archives.
   After this operation, 28.1 MB of additional disk space will be used.
   Get:1 /home/vagrant/wazuh-agent_4.4.0-0.0.0.registration_amd64.deb wazuh-agent amd64 4.4.0-0.0.0.registration [8,731 kB]
   Preconfiguring packages ...       
   Selecting previously unselected package wazuh-agent.
   (Reading database ... 77698 files and directories currently installed.)
   Preparing to unpack .../wazuh-agent_4.4.0-0.0.0.registration_amd64.deb ...
   Unpacking wazuh-agent (4.4.0-0.0.0.registration) ...
   Setting up wazuh-agent (4.4.0-0.0.0.registration) ...
   Processing triggers for systemd (245.4-4ubuntu3.13) ...
   ```
3. Check agent's configuration
   ```
      <ossec_config>
     <client>
       <server>
         <address>10.0.10.2</address>
         <port>1514</port>
         <protocol>tcp</protocol>
       </server>
       <config-profile>ubuntu, ubuntu20, ubuntu20.04</config-profile>
       <notify_time>10</notify_time>
       <time-reconnect>60</time-reconnect>
       <auto_restart>yes</auto_restart>
       <crypto_method>aes</crypto_method>
       <enrollment>
         <enabled>yes</enabled>
         <manager_address>10.0.10.2</manager_address>
         <authorization_pass_path>etc/authd.pass</authorization_pass_path>
       </enrollment>
     </client>
   ```
4. Check `/var/ossec` folder for authd.pass file
   ```
   # ls /var/ossec/etc/
   authd.pass   internal_options.conf        localtime   shared
   client.keys  local_internal_options.conf  ossec.conf  wpk_root.pem
   ```
5. Start agent
   ```
   /home/vagrant# /var/ossec/bin/wazuh-control start
   Starting Wazuh v4.4.0...
   Started wazuh-execd...
   Started wazuh-agentd...
   Started wazuh-syscheckd...
   Started wazuh-logcollector...
   Started wazuh-modulesd...
   Completed.
   ```
5. Check agent is connected with manager :green_circle: 
   ```
   [root@c3 vagrant]# /var/ossec/bin/agent_control -l
   Wazuh agent_control. List of available agents:
      ID: 000, Name: c3 (server), IP: 127.0.0.1, Active/Local
      ID: 001, Name: test, IP: any, Active
   ```
7. Check agent's ossec.log
   ```
   2022/07/26 11:45:35 wazuh-agentd: INFO: Requesting a key from server: 10.0.10.2
   2022/07/26 11:45:35 wazuh-agentd: INFO: Using agent name as: test
   2022/07/26 11:45:35 wazuh-agentd: INFO: Waiting for server reply
   2022/07/26 11:46:20 wazuh-agentd: INFO: Valid key received
   ```
</details>


<details>
<summary>Install Centos Agent :green_circle: </summary>

1. Download package
   ```
   # curl -OL https://s3.us-west-1.amazonaws.com/packages-dev.wazuh.com/warehouse/test/4.4/rpm/var/wazuh-agent-4.4.0-0.0.0.registration.x86_64.rpm
   ```
2. Install agent
   ```
   # WAZUH_MANAGER=10.0.10.2 WAZUH_REGISTRATION_PASSWORD='SuperSecret' WAZUH_REGISTRATION_SERVER=10.0.10.2 yum -y install install wazuh-agent-4.4.0-0.0.0.registration.x86_64.rpm
    Verifying        : wazuh-agent-4.4.0-0.0.0.registration.x86_64                                 1/1 

   Installed:
     wazuh-agent-4.4.0-0.0.0.registration.x86_64                                                        

   Complete!
   ```
3. Check agent's configuration
   ```
     <client>
       <server>
         <address>10.0.10.2</address>
         <port>1514</port>
         <protocol>tcp</protocol>
       </server>
       <config-profile>centos, centos8, centos8.4</config-profile>
       <notify_time>10</notify_time>
       <time-reconnect>60</time-reconnect>
       <auto_restart>yes</auto_restart>
       <crypto_method>aes</crypto_method>
       <enrollment>
         <enabled>yes</enabled>
         <manager_address>10.0.10.2</manager_address>
         <authorization_pass_path>etc/authd.pass</authorization_pass_path>
       </enrollment>
     </client>
   ```
4. Check `/var/ossec` folder for authd.pass file
   ```
   # ls /var/ossec/etc/
   authd.pass   internal_options.conf        localtime   shared
   client.keys  local_internal_options.conf  ossec.conf  wpk_root.pem
   ```
5. Start agent
   ```
   /home/vagrant# /var/ossec/bin/wazuh-control start
   Starting Wazuh v4.4.0...
   Started wazuh-execd...
   Started wazuh-agentd...
   Started wazuh-syscheckd...
   Started wazuh-logcollector...
   Started wazuh-modulesd...
   Completed.
   ```
6. Check agent is connected with manager
   ```
   [root@c3 vagrant]# /var/ossec/bin/agent_control -l
   Wazuh agent_control. List of available agents:
      ID: 000, Name: c3 (server), IP: 127.0.0.1, Active/Local
      ID: 001, Name: test, IP: any, Active
      ID: 002, Name: Centos1, IP: any, Active
   ```
7.  Check agent ossec.logs
   ```
   2022/07/26 11:54:33 wazuh-agentd: INFO: Requesting a key from server: 10.0.10.2
   2022/07/26 11:54:33 wazuh-agentd: INFO: Using password specified on file: etc/authd.pass
   2022/07/26 11:54:33 wazuh-agentd: INFO: Using agent name as: Centos1
   2022/07/26 11:54:33 wazuh-agentd: INFO: Waiting for server reply
   2022/07/26 11:54:33 wazuh-agentd: INFO: Valid key received
   ```
</details>

**Comment by jmv74211** [comment]
🟢 Everything seems to be working properly
