### ISSUE TITLE
QA testing - Add tool to generate X509 certificates

### ISSUE THREAD

**Issue by antoniomanuelfr** [wazuh/wazuh-qa#3143]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|               4.5         |       https://github.com/wazuh/wazuh/issues/11295                 |       https://github.com/wazuh/wazuh/pull/13559             |

## Description

We have seen that the manager cannot be installed if OpenSSL is not installed on the target system because the manager certificates couldn't be generated. When installing the Wazuh manager, a version of the OpenSSL is downloaded and linked to several Wazuh modules. This dependency is not necessary at all, as Wazuh can use the downloaded OpenSSL lib to generate those certificates. 

The https://github.com/wazuh/wazuh/pull/13559  aims to add this functionality to authd in order to remove this dependency.

## Proposed checks

- [x] Check installation of Wazuh manager without OpenSSL in 4.3.6 
- [x] Check that the manager can be installed on a system without OpenSSL
- [x] Check that the manager can be installed on a system with OpenSSL
- [x] Upgrade the manager from 4.3.6 with OpenSSL installed
- [x] Upgrade the manager from 4.3.6 without OpenSSL installed
- [x] Check embedded tool to generate certificate works correctly (Change duration and encryption)
- [x] Check embedded tool to generate certificate works correctly (Change issuer information)
- [x] Check embedded tool to generate certificate works correctly (missing parameter)
- [x] Check embedded tool to generate certificate works correctly (wrong parameter flag)
- [x] Check embedded tool to generate certificate works correctly (Empty parameter)
- [x] Check embedded tool to generate certificate works correctly (Invalid parameter)
- [ ] ~~Check that the newly generated certificate is equal to the previous.~~

## Steps to reproduce
You can reproduce the issue by uninstalling OpenSSL before installing Wazuh.

## Expected results

Wazuh can be installed on systems without OpenSSL installed.

## Configuration and considerations

The tool is embedded into wazuh-authd:

`wazuh-authd -C 265 -B 2048 -K /var/ossec/etc/sslmanager.key -X /var/ossec/etc/sslmanager.cert -S "/C=US/ST=California/CN=wazuh/"`

- `-C` Specify the certificate validity in days.
- `-B` Specify the certificate key size in bits.
- `-K` Specify the path to store the certificate key.
- `-X` Specify the path to store the certificate.
- `-S` Specify the certificate subject.

**Comment by CamiRomero** [comment]
## Review data

| Tester | PR commit               |
|--------|-------------------------|
| @CamiRomero   |  [9b9e19fe](https://github.com/wazuh/wazuh/pull/13559/commits/9b9e19fefcfadc7c952197f9b18953e1d943221d)   |

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
|  Centos  |  8        | Local |    qactl/centos_8         |


### Tested packages

| `wazuh-manager` | `wazuh-agent` | 
|-----------------|---------------|
|  []()               | -     |

### Status

- [x] In progress
- [ ] Pending Review
- [ ] Team leader approved
- [ ] Manager approved

**Comment by CamiRomero** [comment]
## Check installation of Wazuh manager without OpenSSL in 4.3.6

<details>
<summary> Check installation of Wazuh manager :red_circle: (Error reproduced)</summary>

1. Check that the machine not contain OpenSSL:
    ```
    openssl version -a
    ```

    Output:
    ```
    bash: /bin/openssl: No such file or directory
    ```

2. Download and install Wazuh manager
3. Start Wazuh Manager:
    ```
    systemctl start wazuh-manager
    ```

    Output:
    ```
    Job for wazuh-manager.service failed because the control process exited with error code.
    See "systemctl status wazuh-manager.service" and "journalctl -xe" for details.

    ```
4. Check the status of Wazuh manager:
    ```
    systemctl status wazuh-manager.service
    ```
    
    Output:
    ```
    ●   wazuh-manager.service - Wazuh manager
       Loaded: loaded (/usr/lib/systemd/system/wazuh-manager.service; enabled; vendor preset: disabled)
       Active: failed (Result: exit-code) since Thu 2022-08-11 12:30:06 UTC; 26s ago
      Process: 7263 ExecStart=/usr/bin/env /var/ossec/bin/wazuh-control start (code=exited, status=1/FAILURE)
        Tasks: 11 (limit: 50720)
       Memory: 135.4M
       CGroup: /system.slice/wazuh-manager.service
               ├─7319 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
               ├─7365 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
               └─7368 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
    
    Aug 11 12:29:55 centos-manager2 env[7263]: Started wazuh-apid...
    Aug 11 12:29:55 centos-manager2 env[7263]: Started wazuh-csyslogd...
    Aug 11 12:29:55 centos-manager2 env[7263]: Started wazuh-dbd...
    Aug 11 12:29:55 centos-manager2 env[7263]: 2022/08/11 12:29:55 wazuh-integratord: INFO: Remote integrations not configured. Clean exit.
    Aug 11 12:29:55 centos-manager2 env[7263]: Started wazuh-integratord...
    Aug 11 12:29:55 centos-manager2 env[7263]: Started wazuh-agentlessd...
    Aug 11 12:30:06 centos-manager2 env[7263]: wazuh-authd did not start correctly.
    Aug 11 12:30:06 centos-manager2 systemd[1]: wazuh-manager.service: Control process exited, code=exited status=1
    Aug 11 12:30:06 centos-manager2 systemd[1]: wazuh-manager.service: Failed with result 'exit-code'.
    Aug 11 12:30:06 centos-manager2 systemd[1]: Failed to start Wazuh manager.
    ```

6. Check the logs in `/var/ossec/logs/ossec.log`:

    ```
    2022/08/11 12:29:55 wazuh-authd: ERROR: Unable to read certificate file (not found): etc/sslmanager.cert
    2022/08/11 12:29:55 wazuh-authd: ERROR: SSL error. Exiting.

    ```
    

</details>

**Comment by CamiRomero** [comment]
## Check installation of Wazuh manager without OpenSSL in 4.5.0

<details>
<summary> Check installation of Wazuh manager :large_blue_circle: </summary>

1. Check that the machine not contain OpenSSL:
    ```
    openssl version -a
    ```

    Output:
    ```
    bash: /bin/openssl: No such file or directory
    ```
2. Download and install Wazuh manager:
    ```
    curl -LO https://packages-dev.wazuh.com/warehouse/test/4.5/rpm/var/wazuh-manager-4.5.0-qa.3143.x86_64.rpm

    yum install -y wazuh-manager-4.5.0-qa.3143.x86_64.rpm
    ```
4. Start Wazuh Manager:

    ```
    systemctl daemon-reload
    systemctl enable wazuh-manager
    systemctl start wazuh-manager
    ```

    Output:
    ```
    Job for wazuh-manager.service failed because the control process exited with error code.
    See "systemctl status wazuh-manager.service" and "journalctl -xe" for details.
    ```
6. Check the logs in `/var/ossec/logs/ossec.log`::
    ```
    2022/08/11 12:56:15 wazuh-authd: ERROR: Unable to read certificate file (not found): etc/sslmanager.cert
    2022/08/11 12:56:15 wazuh-authd: ERROR: SSL error. Exiting.
    ```
   
7.  Execute the tool  embedded into wazuh-authd:
    ```
    wazuh-authd -C 265 -B 2048 -K /var/ossec/etc/sslmanager.key -X /var/ossec/etc/sslmanager.cert -S "/C=US/ST=California/CN=wazuh/"
    ```

8. Start Wazuh manager:

    ```
    systemctl start wazuh-manager
    ```
9. Check the status of Wazuh manager:
    ```
    systemctl status wazuh-manager.service
    ```
    
    Output:
    ```
        ● wazuh-manager.service - Wazuh manager
       Loaded: loaded (/usr/lib/systemd/system/wazuh-manager.service; enabled; vendor preset: disabled)
       Active: active (running) since Thu 2022-08-11 13:07:50 UTC; 4min 28s ago
      Process: 10164 ExecStart=/usr/bin/env /var/ossec/bin/wazuh-control start (code=exited, status=0/SUCCESS)
        Tasks: 135 (limit: 50720)
       Memory: 306.9M
       CGroup: /system.slice/wazuh-manager.service
               ├─ 9937 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
               ├─ 9987 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
               ├─ 9990 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
               ├─10251 /var/ossec/bin/wazuh-authd
               ├─10265 /var/ossec/bin/wazuh-db
               ├─10292 /var/ossec/bin/wazuh-execd
               ├─10304 /var/ossec/bin/wazuh-analysisd
               ├─10314 /var/ossec/bin/wazuh-syscheckd
               ├─10380 /var/ossec/bin/wazuh-remoted
               ├─10426 /var/ossec/bin/wazuh-logcollector
               ├─10437 /var/ossec/bin/wazuh-monitord
               └─10448 /var/ossec/bin/wazuh-modulesd
    
    Aug 11 13:07:45 centos-manager2 env[10164]: Started wazuh-execd...
    Aug 11 13:07:45 centos-manager2 env[10164]: Started wazuh-analysisd...
    Aug 11 13:07:46 centos-manager2 env[10164]: Started wazuh-syscheckd...
    Aug 11 13:07:47 centos-manager2 env[10164]: Started wazuh-remoted...
    Aug 11 13:07:47 centos-manager2 env[10164]: Started wazuh-logcollector...
    Aug 11 13:07:47 centos-manager2 env[10164]: Started wazuh-monitord...
    Aug 11 13:07:48 centos-manager2 crontab[10538]: (root) LIST (root)
    Aug 11 13:07:48 centos-manager2 env[10164]: Started wazuh-modulesd...
    Aug 11 13:07:50 centos-manager2 env[10164]: Completed.
    Aug 11 13:07:50 centos-manager2 systemd[1]: Started Wazuh manager.
    ```

Note: 
</details>

**Comment by jmv74211** [comment]
In order to address further testing, we find it necessary that this testing be blocked until this [issue](https://github.com/wazuh/wazuh-packages/issues/1676) is completed.

**Comment by Deblintrake09** [comment]
## Task Results

<details><summary>Check installation of Wazuh manager with OpenSSL in 4.5.0</summary>

1. Check OpenSSL installed Version
```
# openssl version
OpenSSL 1.1.1g FIPS  21 Apr 2020
```
2. Install and start the Wazuh Manager
```
Running transaction
  Preparing        :                                                        1/1 
  Running scriptlet: wazuh-manager-4.5.0-0.commit878af9e.x86_64             1/1 
  Installing       : wazuh-manager-4.5.0-0.commit878af9e.x86_64             1/1 
  Running scriptlet: wazuh-manager-4.5.0-0.commit878af9e.x86_64             1/1 
  Verifying        : wazuh-manager-4.5.0-0.commit878af9e.x86_64             1/1 

Installed:
  wazuh-manager-4.5.0-0.commit878af9e.x86_64                                    

Complete!

# /var/ossec/bin/wazuh-control start
Starting Wazuh v4.5.0...
Started wazuh-apid...
Started wazuh-csyslogd...
Started wazuh-dbd...
2022/08/31 15:48:49 wazuh-integratord: INFO: Remote integrations not configured. Clean exit.
Started wazuh-integratord...
Started wazuh-agentlessd...
Started wazuh-authd...
Started wazuh-db...
Started wazuh-execd...
Started wazuh-analysisd...
Started wazuh-syscheckd...
Started wazuh-remoted...
Started wazuh-logcollector...
Started wazuh-monitord...
Started wazuh-modulesd...
Completed.
```
3. Check Wazuh's status
```
# systemctl status wazuh-manager
● wazuh-manager.service - Wazuh manager
   Loaded: loaded (/usr/lib/systemd/system/wazuh-manager.service; enabled; vendor preset: disabled)
   Active: active (exited) since Wed 2022-08-31 15:51:34 UTC; 2s ago
  Process: 12342 ExecStart=/usr/bin/env /var/ossec/bin/wazuh-control start (code=exited, status=0/SUCCESS)

Aug 31 15:51:32 c3 env[12342]: wazuh-db already running...
Aug 31 15:51:32 c3 env[12342]: wazuh-execd already running...
Aug 31 15:51:32 c3 env[12342]: wazuh-analysisd already running...
Aug 31 15:51:32 c3 env[12342]: wazuh-syscheckd already running...
Aug 31 15:51:32 c3 env[12342]: wazuh-remoted already running...
Aug 31 15:51:32 c3 env[12342]: wazuh-logcollector already running...
Aug 31 15:51:32 c3 env[12342]: wazuh-monitord already running...
Aug 31 15:51:32 c3 env[12342]: wazuh-modulesd already running...
Aug 31 15:51:34 c3 env[12342]: Completed.
Aug 31 15:51:34 c3 systemd[1]: Started Wazuh manager.
```
4. Check OpenSSL certificate
```
# openssl x509 -text -in /var/ossec/etc/sslmanager.cert 
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            46:dc:d4:ed:2b:39:92:82:5f:79:78:59:9a:46:af:6c:cd:98:50:42
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = US, ST = California, CN = Wazuh
        Validity
            Not Before: Aug 31 15:47:53 2022 GMT
            Not After : Aug 31 15:47:53 2023 GMT
        Subject: C = US, ST = California, CN = Wazuh
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)
                Modulus:
                    00:ed:fd:43:5b:b9:4c:2c:af:aa:69:54:7b:83:e3:
                    48:11:ea:b6:c6:f3:e4:4d:cf:8b:f6:ab:1a:b8:f0:
                    28:f0:0d:ca:ec:b4:91:cd:83:d5:ef:dc:79:d7:18:
                    80:8f:b1:b5:fe:29:4e:de:0e:9d:22:48:2f:52:c5:
                    23:ce:9d:44:10:2e:92:a4:f9:9f:bf:2b:8c:77:ad:
                    9c:e0:ff:a5:f3:9f:6f:56:f0:1a:18:3a:bd:e6:29:
                    60:bd:ea:3a:89:c4:74:23:85:4d:54:73:80:18:f0:
                    78:c8:fb:1e:f7:5d:4a:cf:df:0d:35:9c:38:cd:3f:
                    92:bc:c7:e3:4f:91:dc:8f:12:7e:ae:f1:7b:7c:04:
                    2d:14:ac:bf:33:cb:1c:ca:e6:c6:22:8a:63:2e:8c:
                    dc:77:63:53:e4:e7:48:d9:af:84:97:0b:37:d8:44:
                    8d:b1:15:f0:77:a3:e9:83:c0:a6:9f:cb:57:94:8e:
                    61:cd:60:f1:e4:15:86:c6:d5:1b:a4:11:de:7d:0e:
                    35:1e:8b:a7:62:57:ff:cd:76:81:e4:c5:ea:97:54:
                    b5:04:10:91:d9:77:01:52:d1:3c:4b:2e:61:83:0b:
                    15:28:f3:85:ac:e1:3b:50:43:67:26:91:02:72:17:
                    29:72:f3:f1:01:05:19:a2:3c:02:a9:d2:4c:bb:da:
                    7f:c7
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Subject Key Identifier: 
                28:17:88:95:7E:8B:2C:E7:AA:31:72:84:57:9E:EB:9E:CC:01:E9:FF
            X509v3 Authority Key Identifier: 
                keyid:28:17:88:95:7E:8B:2C:E7:AA:31:72:84:57:9E:EB:9E:CC:01:E9:FF

            X509v3 Basic Constraints: critical
                CA:TRUE
    Signature Algorithm: sha256WithRSAEncryption
         53:3f:6c:87:41:7c:b1:27:14:40:20:cf:1b:57:03:ee:92:e3:
         06:02:10:26:94:8d:77:7c:30:65:8d:af:b1:bf:5f:b2:65:8b:
         71:02:7f:52:36:81:42:01:b8:c5:9a:0f:c0:d0:90:30:42:f4:
         94:92:1f:88:9f:b6:c3:d6:e8:6f:b4:17:9c:a3:fc:2e:05:a9:
         08:b1:f3:bc:a8:1a:48:5d:49:fb:96:b0:c4:e4:b8:1b:83:d8:
         cc:05:68:66:7f:0c:4a:56:13:a4:77:31:5a:dd:e3:98:51:1f:
         9e:26:4e:cf:83:39:38:a1:82:41:50:dd:bf:01:85:ed:9a:2a:
         cc:f8:a7:5b:bc:3d:35:b6:95:d8:7a:e8:3f:b9:cb:c5:be:17:
         fa:97:57:75:ef:ff:4f:39:29:ef:ba:73:4e:4e:e4:22:69:7c:
         df:6d:62:5d:86:6c:88:f1:e6:d5:d3:4a:a6:4c:b0:e3:49:af:
         60:4f:11:a9:be:75:c1:99:9f:52:c8:64:e2:92:33:cc:1d:8b:
         06:23:75:43:92:b3:32:cd:6d:42:6f:18:70:3a:de:e5:1d:f0:
         56:47:fb:77:ed:6e:52:3e:ab:ac:a8:b3:51:04:0a:72:7c:98:
         5f:cf:eb:c6:09:8e:36:41:be:20:a7:32:f2:64:55:9e:e0:c7:
         4f:c9:40:ac
-----BEGIN CERTIFICATE-----
MIIDRTCCAi2gAwIBAgIURtzU7Ss5koJfeXhZmkavbM2YUEIwDQYJKoZIhvcNAQEL
BQAwMjELMAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExDjAMBgNVBAMM
BVdhenVoMB4XDTIyMDgzMTE1NDc1M1oXDTIzMDgzMTE1NDc1M1owMjELMAkGA1UE
BhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExDjAMBgNVBAMMBVdhenVoMIIBIjAN
BgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA7f1DW7lMLK+qaVR7g+NIEeq2xvPk
Tc+L9qsauPAo8A3K7LSRzYPV79x51xiAj7G1/ilO3g6dIkgvUsUjzp1EEC6SpPmf
vyuMd62c4P+l859vVvAaGDq95ilgveo6icR0I4VNVHOAGPB4yPse911Kz98NNZw4
zT+SvMfjT5HcjxJ+rvF7fAQtFKy/M8scyubGIopjLozcd2NT5OdI2a+Elws32ESN
sRXwd6Ppg8Cmn8tXlI5hzWDx5BWGxtUbpBHefQ41HounYlf/zXaB5MXql1S1BBCR
2XcBUtE8Sy5hgwsVKPOFrOE7UENnJpECchcpcvPxAQUZojwCqdJMu9p/xwIDAQAB
o1MwUTAdBgNVHQ4EFgQUKBeIlX6LLOeqMXKEV57rnswB6f8wHwYDVR0jBBgwFoAU
KBeIlX6LLOeqMXKEV57rnswB6f8wDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0B
AQsFAAOCAQEAUz9sh0F8sScUQCDPG1cD7pLjBgIQJpSNd3wwZY2vsb9fsmWLcQJ/
UjaBQgG4xZoPwNCQMEL0lJIfiJ+2w9bob7QXnKP8LgWpCLHzvKgaSF1J+5awxOS4
G4PYzAVoZn8MSlYTpHcxWt3jmFEfniZOz4M5OKGCQVDdvwGF7ZoqzPinW7w9NbaV
2HroP7nLxb4X+pdXde//Tzkp77pzTk7kIml8321iXYZsiPHm1dNKpkyw40mvYE8R
qb51wZmfUshk4pIzzB2LBiN1Q5KzMs1tQm8YcDre5R3wVkf7d+1uUj6rrKizUQQK
cnyYX8/rxgmONkG+IKcy8mRVnuDHT8lArA==
-----END CERTIFICATE-----
```
</details>



<details><summary>Check installation of Wazuh manager without OpenSSL in 4.5.0</summary>

1. Remove OpenSSL
```
# yum remove -y  openssl
Removed:
  openssl-1:1.1.1g-15.el8_3.x86_64                                 openssl-pkcs11-0.4.10-2.el8.x86_64                           perl-Digest-1.17-395.el8.noarch    perl-Digest-MD5-2.55-396.el8.x86_64   
  perl-IO-Socket-SSL-2.066-4.module_el8.3.0+410+ff426aa3.noarch    perl-Net-SSLeay-1.88-1.module_el8.3.0+410+ff426aa3.x86_64    perl-URI-1.73-3.el8.noarch         perl-libnet-3.11-3.el8.noarch         
  rng-tools-6.8-3.el8.x86_64 
```
2. Check OpenSSL installed Version
```
# openssl version
bash: /bin/openssl: No such file or directory
```
3. Install and start the Wazuh Manager
```
Running transaction
  Preparing        :
 Running scriptlet: wazuh-manager-4.5.0-0.commit878af9e.x86_64                                                                                                                                  
  Installing       : wazuh-manager-4.5.0-0.commit878af9e.x86_64                                                                                                                                     
  Running scriptlet: wazuh-manager-4.5.0-0.commit878af9e.x86_64                                                                                                                                       
  Verifying        : wazuh-manager-4.5.0-0.commit878af9e.x86_64                                                                                                                                       

Installed:
  wazuh-manager-4.5.0-0.commit878af9e.x86_64                                                                                                                                                               

Complete!

# systemctl daemon-reload
# systemctl enable wazuh-manager
Synchronizing state of wazuh-manager.service with SysV service script with /usr/lib/systemd/systemd-sysv-install.
Executing: /usr/lib/systemd/systemd-sysv-install enable wazuh-manager
# systemctl start wazuh-manager
```
4. Check Wazuh's status
```
# systemctl status wazuh-manager
● wazuh-manager.service - Wazuh manager
   Loaded: loaded (/usr/lib/systemd/system/wazuh-manager.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2022-08-31 16:42:00 UTC; 8s ago
  Process: 60172 ExecStart=/usr/bin/env /var/ossec/bin/wazuh-control start (code=exited, status=0/SUCCESS)
    Tasks: 114 (limit: 24918)
   Memory: 219.4M
   CGroup: /system.slice/wazuh-manager.service
           ├─60231 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
           ├─60273 /var/ossec/bin/wazuh-authd
           ├─60290 /var/ossec/bin/wazuh-db
           ├─60303 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
           ├─60306 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
           ├─60321 /var/ossec/bin/wazuh-execd
           ├─60336 /var/ossec/bin/wazuh-analysisd
           ├─60379 /var/ossec/bin/wazuh-syscheckd
           ├─60400 /var/ossec/bin/wazuh-remoted
           ├─60437 /var/ossec/bin/wazuh-logcollector
           ├─60492 /var/ossec/bin/wazuh-monitord
           └─60543 /var/ossec/bin/wazuh-modulesd

Aug 31 16:41:52 c3 env[60172]: Started wazuh-execd...
Aug 31 16:41:53 c3 env[60172]: Started wazuh-analysisd...
Aug 31 16:41:54 c3 env[60172]: Started wazuh-syscheckd...
Aug 31 16:41:55 c3 env[60172]: Started wazuh-remoted...
Aug 31 16:41:56 c3 env[60172]: Started wazuh-logcollector...
Aug 31 16:41:57 c3 env[60172]: Started wazuh-monitord...
Aug 31 16:41:57 c3 crontab[60621]: (root) LIST (root)
Aug 31 16:41:58 c3 env[60172]: Started wazuh-modulesd...
Aug 31 16:42:00 c3 env[60172]: Completed.
Aug 31 16:42:00 c3 systemd[1]: Started Wazuh manager.
```
5. Check x509 certificate
```
# cat /var/ossec/etc/sslmanager.cert 
-----BEGIN CERTIFICATE-----
MIIDRTCCAi2gAwIBAgIUHQnbLibt5UKXK9hXTcBieZjuOYIwDQYJKoZIhvcNAQEL
BQAwMjELMAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExDjAMBgNVBAMM
BXdhenVoMB4XDTIyMDgzMTE2NDgxOVoXDTIzMDUyMzE2NDgxOVowMjELMAkGA1UE
BhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExDjAMBgNVBAMMBXdhenVoMIIBIjAN
BgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAw4JaZb9FKV96xpq5VAr7YpzofhGA
8ksfbg/1LDNAAzkqntTg6jXEoXC2MlPOA+hSwftkzuHAUK8A+fTt9Ib07TPpAH00
6lapP8BwPjrvVXQWbk/0cOhVGqQrAnAKzRANzD2DXknAdFk+n73vIIsYqcTr3AJT
/mvbYuZ1UhgfVfzFM3bHCGj7/YxwI10UBealSmsOd91Kb3ga6WyqN9HBX5tTUW4X
ua3dy3XDBBLwjxpihyZO8nGMnnO8bDYbUqXy5bIks121pEcKzJmJKtm1N+T/9q7K
K/bmURA2Fo+1GhOh2sppYTv1AOCpwpK5y9hwzL15tG1fyLZoHFAkC8xkVQIDAQAB
o1MwUTAdBgNVHQ4EFgQUMlvi9aBHyjq3Ag3RVFUh2UwqilkwHwYDVR0jBBgwFoAU
Mlvi9aBHyjq3Ag3RVFUh2UwqilkwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0B
AQsFAAOCAQEARpywcyt3GC9zQR9Lq1GLoY9kamehSYcEMQOCRrUhKA7CP0Kl3ixq
8cNKgW2ZCAIjydLD7uyiamIwi1WxNru6Z6QQq4tRkvUPQMOeN+RDer0FxURkP70d
3xAOmTRIv/gYV+mBzF8AOvhdF8GlLIa62ix6CAVxXd770zeHDeoGIQKno69lQPqY
5oKwon4zcr8kw0vr/wAaBmuBu5HwXUhhI3AVmRZEDHwPZnpz72O3uPnVEZmU0ZzE
MbHKrKyVnJNuuNYN1FdyksGV6WuecLKzHlKE364sW1bA8kDsxQotR1Ztn+751XeJ
mJlOdLNRbtjzn47OlxhHtD8hrOOSKpJaqQ==
-----END CERTIFICATE-----
```
</details>

**Comment by jmv74211** [comment]
🟢 Everything seems to be working properly
