### ISSUE TITLE
Manual testing - Fix CPE Helper to find vulnerabilities in unversioned packages

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh-qa#3147]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|master|https://github.com/wazuh/wazuh/issues/13434|https://github.com/wazuh/wazuh/pull/14356|

## Description
This issue aims to run manual testing on the Vulnerability Detector fix to detect and scan packages that don't have the version field, such as the one shown in the [issue](https://github.com/wazuh/wazuh/issues/13434) (_Tomcat 7_). For this purpose, several changes have been added to the CPE Helper, which are mentioned in [PR](https://github.com/wazuh/wazuh/pull/14356).

## Proposed checks
For the following test cases, verify that no issue (memory leaks, service down...) appears during the feed parsing, and the vulnerability database (`cve.db`) is properly filled with the vulnerabilities from the feeds. 
- [x] Run Vulnerability Detector with a connected Windows agent that has a _Tomcat 7_ package.
    - [x] An old Tomcat 7 package (which has neither vendor nor version), such as [Tomcat 7.0.27](https://archive.apache.org/dist/tomcat/tomcat-7/v7.0.27/bin/apache-tomcat-7.0.27.exe).
    > For this case it will be necessary to add the PoC explained in the PR.
    - [x] A recent Tomcat 7 package with vulnerabilities, such as [Tomcat 7.0.103](https://archive.apache.org/dist/tomcat/tomcat-7/v7.0.103/bin/apache-tomcat-7.0.103.exe).
- [x] Test that the CPE Helper fix works correctly.
    - [x] Test mock package without version and vendor (adding its corresponding translation) to find its respective vulnerabilities.
    - [x] Add translation to the CPE Helper as explained in the [PR PoC](https://github.com/wazuh/wazuh/pull/14356) and test that it shows the corresponding vulnerabilities.
    - [x] Add translation to the CPE Helper of a package without version without specifying the action `set_version_if_product_matches`, so that it shows the new _Debug_ message.

## Configuration and considerations

- The following configuration should be applied:

```xml
  <vulnerability-detector>
    <enabled>yes</enabled>
    <interval>5m</interval>
    <min_full_scan_interval>6h</min_full_scan_interval>
    <run_on_start>yes</run_on_start>

    <!-- Windows OS vulnerabilities -->
    <provider name="msu">
      <enabled>yes</enabled>
      <update_interval>1h</update_interval>
    </provider>

    <!-- Aggregate vulnerabilities -->
    <provider name="nvd">
      <enabled>yes</enabled>
      <update_from_year>2010</update_from_year>
      <update_interval>1h</update_interval>
    </provider>

  </vulnerability-detector>
```

> Note that by default the fix is not tested (as it was producing false positives), so it is necessary to add the [PoC](https://github.com/wazuh/wazuh/pull/14356) or similar input to test it.

**Comment by Deblintrake09** [comment]
asd

**Comment by Deblintrake09** [comment]
# Task Results on dev branch

<details> 
<summary>Run vulnerability detector with old package (no vendor or version) </summary>
- Install Tomcat package on Windows agent


- Wait for syscollector on Agent
   ``` 
   
   ```
- Check agent's database in the manager for the package
   ``` 
   
   ```
- Wait for Vulnerability Detector scan
   ``` 
   ```
- Check alerts generated
   ``` 
   ```
</details>

<details> 
<summary>Run vulnerability detector with new package (no vendor or version) </summary>
- Install Tomcat package on Windows agent
![imagen](https://user-images.githubusercontent.com/14501079/183150334-ac87c30e-925c-4383-8395-037f188a01e7.png)

- Wait for syscollector on Agent
- Check agent's database in the manager for the package
   ```
   scan_id|scan_time|format|name|priority|section|size|vendor|install_time|version|architecture|multiarch|source|description|location|triaged|cpe|msu_name|checksum|item_id
   0|2022/08/05 19:40:08|win|Apache Tomcat 7.0 Tomcat72 (remove only)|||0|The Apache Software Foundation||7.0.103|x86_64|||||1|||bdeef860661a7f5b5f8f4113c37a2dd0ea902a3e|68385a2c7db756658f3186f0ae5dea79f202f928
   
   ```
- Wait for Vulnerability Detector scan
   ``` 
   2022/08/05 19:40:48 wazuh-modulesd:vulnerability-detector[9059] wm_vuln_detector.c:5421 at wm_vuldet_collect_agent_software(): DEBUG: (5437): Collecting agent '001' software.
2022/08/05 19:40:48 wazuh-modulesd:vulnerability-detector[9059] wm_vuln_detector_nvd.c:3195 at wm_vuldet_add_dic_cpe(): DEBUG: (5446): The CPE 'a:apache:tomcat:7.0.103::::::x64:' from the agent '001' was indexed.
   2022/08/05 19:40:48 wazuh-modulesd:vulnerability-detector[9059] wm_vuln_detector.c:2731 at wm_vuldet_check_agent_vulnerabilities(): INFO: (5450): Analyzing agent '001' vulnerabilities.
   2022/08/05 19:40:48 wazuh-modulesd:vulnerability-detector[9059] wm_vuln_detector_nvd.c:1822 at wm_vuldet_win_nvd_vulnerabilities(): DEBUG: (5451): Analyzing NVD vulnerabilities for agent '001'
   2022/08/05 19:40:48 wazuh-modulesd:vulnerability-detector[9059] wm_vuln_detector_nvd.c:1834 at wm_vuldet_win_nvd_vulnerabilities(): DEBUG: (5470): It took '0' seconds to 'find NVD' vulnerabilities in agent '001'
   2022/08/05 19:40:48 wazuh-modulesd:vulnerability-detector[9059] wm_vuln_detector_nvd.c:1836 at wm_vuldet_win_nvd_vulnerabilities(): DEBUG: (5466): Sending vulnerabilities report for agent '001'
   2022/08/05 19:40:48 wazuh-modulesd:vulnerability-detector[9059] wm_vuln_detector_nvd.c:2335 at wm_vuldet_process_agent_nvd_vulnerabilities(): DEBUG: (5468): The 'Apache Tomcat 7.0 Tomcat72 (remove only)' package (7.0.103) from agent '001' is vulnerable to 'CVE-2021-30640'. Condition: 'greater than or equal 7.0.0 and less than 7.0.109'
   2022/08/05 19:40:48 wazuh-modulesd:vulnerability-detector[9059] wm_vuln_detector_nvd.c:2335 at wm_vuldet_process_agent_nvd_vulnerabilities(): DEBUG: (5468): The 'Apache Tomcat 7.0 Tomcat72 (remove only)' package (7.0.103) from agent '001' is vulnerable to 'CVE-2021-25329'. Condition: 'greater than or equal 7.0.0 and less than or equal 7.0.107'
   2022/08/05 19:40:48 wazuh-modulesd:vulnerability-detector[9059] wm_vuln_detector_nvd.c:2335 at wm_vuldet_process_agent_nvd_vulnerabilities(): DEBUG: (5468): The 'Apache Tomcat 7.0 Tomcat72 (remove only)' package (7.0.103) from agent '001' is vulnerable to 'CVE-2021-24122'. Condition: 'greater than or equal 7.0.0 and less than or equal 7.0.106'
   2022/08/05 19:40:48 wazuh-modulesd:vulnerability-detector[9059] wm_vuln_detector_nvd.c:2335 at wm_vuldet_process_agent_nvd_vulnerabilities(): DEBUG: (5468): The 'Apache Tomcat 7.0 Tomcat72 (remove only)' package (7.0.103) from agent '001' is vulnerable to 'CVE-2020-9484'. Condition: 'greater than or equal 7.0.0 and less than 7.0.108'
   2022/08/05 19:40:48 wazuh-modulesd:vulnerability-detector[9059] wm_vuln_detector_nvd.c:2335 at wm_vuldet_process_agent_nvd_vulnerabilities(): DEBUG: (5468): The 'Apache Tomcat 7.0 Tomcat72 (remove only)' package (7.0.103) from agent '001' is vulnerable to 'CVE-2020-13935'. Condition: 'greater than or equal 7.0.27 and less than or equal 7.0.104'
   2022/08/05 19:40:48 wazuh-modulesd:vulnerability-detector[9059] wm_vuln_detector_nvd.c:2335 at wm_vuldet_process_agent_nvd_vulnerabilities(): DEBUG: (5468): The 'Apache Tomcat 7.0 Tomcat72 (remove only)' package (7.0.103) from agent '001' is vulnerable to 'CVE-2012-5568'. Condition: 'greater than or equal 7.0.0 and less than or equal 7.0.105'
   2022/08/05 19:40:48 wazuh-modulesd:vulnerability-detector[9059] wm_vuln_detector_nvd.c:1846 at wm_vuldet_win_nvd_vulnerabilities(): DEBUG: (5470): It took '0' seconds to 'report' vulnerabilities in agent '001'

   ```
- Check alerts generated
   ``` 
   {"timestamp":"2022-08-05T19:40:48.146+0000","rule":{"level":10,"description":"CVE-2020-13935 affects Apache Tomcat 7.0 Tomcat72 (remove only)","id":"23505","firedtimes":3,"mail":false,"groups":["vulnerability-detector"],"gdpr":["IV_35.7.d"],"pci_dss":["11.2.1","11.2.3"],"tsc":["CC7.1","CC7.2"]},"agent":{"id":"001","name":"WIN-JLGVA4CR4VI","ip":"FE80:0000:0000:0000:B1E6:42AF:E199:1398"},"manager":{"name":"c3"},"id":"1659728448.7696509","decoder":{"name":"json"},"data":{"vulnerability":{"package":{"name":"Apache Tomcat 7.0 Tomcat72 (remove only)","version":"7.0.103","architecture":"x64","condition":"greater than or equal 7.0.27 and less than or equal 7.0.104"},"cvss":{"cvss2":{"vector":{"attack_vector":"network","access_complexity":"low","authentication":"none","confidentiality_impact":"none","integrity_impact":"none","availability":"partial"},"base_score":"5"},"cvss3":{"vector":{"attack_vector":"network","access_complexity":"low","privileges_required":"none","user_interaction":"none","scope":"unchanged","confidentiality_impact":"none","integrity_impact":"none","availability":"high"},"base_score":"7.500000"}},"cve":"CVE-2020-13935","title":"CVE-2020-13935 affects Apache Tomcat 7.0 Tomcat72 (remove only)","rationale":"The payload length in a WebSocket frame was not correctly validated in Apache Tomcat 10.0.0-M1 to 10.0.0-M6, 9.0.0.M1 to 9.0.36, 8.5.0 to 8.5.56 and 7.0.27 to 7.0.104. Invalid payload lengths could trigger an infinite loop. Multiple requests with invalid payload lengths could lead to a denial of service.","severity":"High","published":"2020-07-14","updated":"2022-05-12","cwe_reference":"CWE-835","status":"Active","type":"PACKAGE","references":["https://lists.apache.org/thread.html/rd48c72bd3255bda87564d4da3791517c074d94f8a701f93b85752651%40%3Cannounce.tomcat.apache.org%3E","https://www.debian.org/security/2020/dsa-4727","https://lists.debian.org/debian-lts-announce/2020/07/msg00017.html","https://security.netapp.com/advisory/ntap-20200724-0003/","http://lists.opensuse.org/opensuse-security-announce/2020-07/msg00084.html","http://lists.opensuse.org/opensuse-security-announce/2020-07/msg00088.html","https://usn.ubuntu.com/4448-1/","https://kc.mcafee.com/corporate/index?page=content&id=SB10332","https://www.oracle.com/security-alerts/cpuoct2020.html","https://usn.ubuntu.com/4596-1/","https://lists.apache.org/thread.html/r4e5d3c09f4dd2923191e972408b40fb8b42dbff0bc7904d44b651e50@%3Cusers.tomcat.apache.org%3E","https://www.oracle.com/security-alerts/cpujan2021.html","https://www.oracle.com/security-alerts/cpuApr2021.html","https://www.oracle.com//security-alerts/cpujul2021.html","https://www.oracle.com/security-alerts/cpuoct2021.html","https://www.oracle.com/security-alerts/cpujan2022.html","https://www.oracle.com/security-alerts/cpuapr2022.html","https://nvd.nist.gov/vuln/detail/CVE-2020-13935"],"assigner":"security@apache.org","cve_version":"4.0"}},"location":"vulnerability-detector"}
{"timestamp":"2022-08-05T19:40:48.158+0000","rule":{"level":7,"description":"CVE-2012-5568 affects Apache Tomcat 7.0 Tomcat72 (remove only)","id":"23504","firedtimes":3,"mail":false,"groups":["vulnerability-detector"],"gdpr":["IV_35.7.d"],"pci_dss":["11.2.1","11.2.3"],"tsc":["CC7.1","CC7.2"]},"agent":{"id":"001","name":"WIN-JLGVA4CR4VI","ip":"FE80:0000:0000:0000:B1E6:42AF:E199:1398"},"manager":{"name":"c3"},"id":"1659728448.7702246","decoder":{"name":"json"},"data":{"vulnerability":{"package":{"name":"Apache Tomcat 7.0 Tomcat72 (remove only)","version":"7.0.103","architecture":"x64","condition":"greater than or equal 7.0.0 and less than or equal 7.0.105"},"cvss":{"cvss2":{"vector":{"attack_vector":"network","access_complexity":"low","authentication":"none","confidentiality_impact":"none","integrity_impact":"none","availability":"partial"},"base_score":"5"}},"cve":"CVE-2012-5568","title":"CVE-2012-5568 affects Apache Tomcat 7.0 Tomcat72 (remove only)","rationale":"Apache Tomcat through 7.0.x allows remote attackers to cause a denial of service (daemon outage) via partial HTTP requests, as demonstrated by Slowloris.","severity":"Medium","published":"2012-11-30","updated":"2021-01-11","cwe_reference":"NVD-CWE-noinfo","status":"Active","type":"PACKAGE","references":["http://openwall.com/lists/oss-security/2012/11/26/2","http://captainholly.wordpress.com/2009/06/19/slowloris-vs-tomcat/","http://tomcat.10.n6.nabble.com/How-does-Tomcat-handle-a-slow-HTTP-DoS-tc2147776.html","http://tomcat.10.n6.nabble.com/How-does-Tomcat-handle-a-slow-HTTP-DoS-tc2147779.html","https://bugzilla.redhat.com/show_bug.cgi?id=880011","http://lists.opensuse.org/opensuse-updates/2012-12/msg00089.html","http://lists.opensuse.org/opensuse-updates/2012-12/msg00090.html","http://www.securityfocus.com/bid/56686","http://lists.opensuse.org/opensuse-updates/2013-01/msg00037.html","https://exchange.xforce.ibmcloud.com/vulnerabilities/80317","https://nvd.nist.gov/vuln/detail/CVE-2012-5568"],"assigner":"secalert@redhat.com","cve_version":"4.0"}},"location":"vulnerability-detector"}
   ```
</details>

**Comment by Deblintrake09** [comment]
# Task Results on dev branch

<details> 
<summary>Run vulnerability detector with old package (no vendor or version) </summary>

- Install Tomcat package on Windows agent


- Wait for syscollector on Agent
   ``` 
   
   ```
- Check agent's database in the manager for the package
   ``` 
   
   ```
- Wait for Vulnerability Detector scan
   ``` 
   ```
- Check alerts generated
   ``` 
   ```
</details>

<details> 
<summary>Run vulnerability detector with new package (no vendor or version) :green_circle: </summary>

- Install Tomcat package on Windows agent
![imagen](https://user-images.githubusercontent.com/14501079/183150334-ac87c30e-925c-4383-8395-037f188a01e7.png)

- Wait for syscollector on Agent
- Check agent's database in the manager for the package
   ```
   scan_id|scan_time|format|name|priority|section|size|vendor|install_time|version|architecture|multiarch|source|description|location|triaged|cpe|msu_name|checksum|item_id
   0|2022/08/05 19:40:08|win|Apache Tomcat 7.0 Tomcat72 (remove only)|||0|The Apache Software Foundation||7.0.103|x86_64|||||1|||bdeef860661a7f5b5f8f4113c37a2dd0ea902a3e|68385a2c7db756658f3186f0ae5dea79f202f928
   
   ```
- Wait for Vulnerability Detector scan
   ``` 
   2022/08/05 19:40:48 wazuh-modulesd:vulnerability-detector[9059] wm_vuln_detector.c:5421 at wm_vuldet_collect_agent_software(): DEBUG: (5437): Collecting agent '001' software.
   2022/08/05 19:40:48 wazuh-modulesd:vulnerability-detector[9059] wm_vuln_detector_nvd.c:3195 at wm_vuldet_add_dic_cpe(): DEBUG: (5446): The CPE 'a:apache:tomcat:7.0.103::::::x64:' from the agent '001' was indexed.
   2022/08/05 19:40:48 wazuh-modulesd:vulnerability-detector[9059] wm_vuln_detector.c:2731 at wm_vuldet_check_agent_vulnerabilities(): INFO: (5450): Analyzing agent '001' vulnerabilities.
   2022/08/05 19:40:48 wazuh-modulesd:vulnerability-detector[9059] wm_vuln_detector_nvd.c:1822 at wm_vuldet_win_nvd_vulnerabilities(): DEBUG: (5451): Analyzing NVD vulnerabilities for agent '001'
   2022/08/05 19:40:48 wazuh-modulesd:vulnerability-detector[9059] wm_vuln_detector_nvd.c:1834 at wm_vuldet_win_nvd_vulnerabilities(): DEBUG: (5470): It took '0' seconds to 'find NVD' vulnerabilities in agent '001'
   2022/08/05 19:40:48 wazuh-modulesd:vulnerability-detector[9059] wm_vuln_detector_nvd.c:1836 at wm_vuldet_win_nvd_vulnerabilities(): DEBUG: (5466): Sending vulnerabilities report for agent '001'
   2022/08/05 19:40:48 wazuh-modulesd:vulnerability-detector[9059] wm_vuln_detector_nvd.c:2335 at wm_vuldet_process_agent_nvd_vulnerabilities(): DEBUG: (5468): The 'Apache Tomcat 7.0 Tomcat72 (remove only)' package (7.0.103) from agent '001' is vulnerable to 'CVE-2021-30640'. Condition: 'greater than or equal 7.0.0 and less than 7.0.109'
   2022/08/05 19:40:48 wazuh-modulesd:vulnerability-detector[9059] wm_vuln_detector_nvd.c:2335 at wm_vuldet_process_agent_nvd_vulnerabilities(): DEBUG: (5468): The 'Apache Tomcat 7.0 Tomcat72 (remove only)' package (7.0.103) from agent '001' is vulnerable to 'CVE-2021-25329'. Condition: 'greater than or equal 7.0.0 and less than or equal 7.0.107'
   2022/08/05 19:40:48 wazuh-modulesd:vulnerability-detector[9059] wm_vuln_detector_nvd.c:2335 at wm_vuldet_process_agent_nvd_vulnerabilities(): DEBUG: (5468): The 'Apache Tomcat 7.0 Tomcat72 (remove only)' package (7.0.103) from agent '001' is vulnerable to 'CVE-2021-24122'. Condition: 'greater than or equal 7.0.0 and less than or equal 7.0.106'
   2022/08/05 19:40:48 wazuh-modulesd:vulnerability-detector[9059] wm_vuln_detector_nvd.c:2335 at wm_vuldet_process_agent_nvd_vulnerabilities(): DEBUG: (5468): The 'Apache Tomcat 7.0 Tomcat72 (remove only)' package (7.0.103) from agent '001' is vulnerable to 'CVE-2020-9484'. Condition: 'greater than or equal 7.0.0 and less than 7.0.108'
   2022/08/05 19:40:48 wazuh-modulesd:vulnerability-detector[9059] wm_vuln_detector_nvd.c:2335 at wm_vuldet_process_agent_nvd_vulnerabilities(): DEBUG: (5468): The 'Apache Tomcat 7.0 Tomcat72 (remove only)' package (7.0.103) from agent '001' is vulnerable to 'CVE-2020-13935'. Condition: 'greater than or equal 7.0.27 and less than or equal 7.0.104'
   2022/08/05 19:40:48 wazuh-modulesd:vulnerability-detector[9059] wm_vuln_detector_nvd.c:2335 at wm_vuldet_process_agent_nvd_vulnerabilities(): DEBUG: (5468): The 'Apache Tomcat 7.0 Tomcat72 (remove only)' package (7.0.103) from agent '001' is vulnerable to 'CVE-2012-5568'. Condition: 'greater than or equal 7.0.0 and less than or equal 7.0.105'
   2022/08/05 19:40:48 wazuh-modulesd:vulnerability-detector[9059] wm_vuln_detector_nvd.c:1846 at wm_vuldet_win_nvd_vulnerabilities(): DEBUG: (5470): It took '0' seconds to 'report' vulnerabilities in agent '001'

   ```
- Check alerts generated
   ``` 
   {"timestamp":"2022-08-05T19:40:48.146+0000","rule":{"level":10,"description":"CVE-2020-13935 affects Apache Tomcat 7.0 Tomcat72 (remove only)","id":"23505","firedtimes":3,"mail":false,"groups":["vulnerability-detector"],"gdpr":["IV_35.7.d"],"pci_dss":["11.2.1","11.2.3"],"tsc":["CC7.1","CC7.2"]},"agent":{"id":"001","name":"WIN-JLGVA4CR4VI","ip":"FE80:0000:0000:0000:B1E6:42AF:E199:1398"},"manager":{"name":"c3"},"id":"1659728448.7696509","decoder":{"name":"json"},"data":{"vulnerability":{"package":{"name":"Apache Tomcat 7.0 Tomcat72 (remove only)","version":"7.0.103","architecture":"x64","condition":"greater than or equal 7.0.27 and less than or equal 7.0.104"},"cvss":{"cvss2":{"vector":{"attack_vector":"network","access_complexity":"low","authentication":"none","confidentiality_impact":"none","integrity_impact":"none","availability":"partial"},"base_score":"5"},"cvss3":{"vector":{"attack_vector":"network","access_complexity":"low","privileges_required":"none","user_interaction":"none","scope":"unchanged","confidentiality_impact":"none","integrity_impact":"none","availability":"high"},"base_score":"7.500000"}},"cve":"CVE-2020-13935","title":"CVE-2020-13935 affects Apache Tomcat 7.0 Tomcat72 (remove only)","rationale":"The payload length in a WebSocket frame was not correctly validated in Apache Tomcat 10.0.0-M1 to 10.0.0-M6, 9.0.0.M1 to 9.0.36, 8.5.0 to 8.5.56 and 7.0.27 to 7.0.104. Invalid payload lengths could trigger an infinite loop. Multiple requests with invalid payload lengths could lead to a denial of service.","severity":"High","published":"2020-07-14","updated":"2022-05-12","cwe_reference":"CWE-835","status":"Active","type":"PACKAGE","references":["https://lists.apache.org/thread.html/rd48c72bd3255bda87564d4da3791517c074d94f8a701f93b85752651%40%3Cannounce.tomcat.apache.org%3E","https://www.debian.org/security/2020/dsa-4727","https://lists.debian.org/debian-lts-announce/2020/07/msg00017.html","https://security.netapp.com/advisory/ntap-20200724-0003/","http://lists.opensuse.org/opensuse-security-announce/2020-07/msg00084.html","http://lists.opensuse.org/opensuse-security-announce/2020-07/msg00088.html","https://usn.ubuntu.com/4448-1/","https://kc.mcafee.com/corporate/index?page=content&id=SB10332","https://www.oracle.com/security-alerts/cpuoct2020.html","https://usn.ubuntu.com/4596-1/","https://lists.apache.org/thread.html/r4e5d3c09f4dd2923191e972408b40fb8b42dbff0bc7904d44b651e50@%3Cusers.tomcat.apache.org%3E","https://www.oracle.com/security-alerts/cpujan2021.html","https://www.oracle.com/security-alerts/cpuApr2021.html","https://www.oracle.com//security-alerts/cpujul2021.html","https://www.oracle.com/security-alerts/cpuoct2021.html","https://www.oracle.com/security-alerts/cpujan2022.html","https://www.oracle.com/security-alerts/cpuapr2022.html","https://nvd.nist.gov/vuln/detail/CVE-2020-13935"],"assigner":"security@apache.org","cve_version":"4.0"}},"location":"vulnerability-detector"}
{"timestamp":"2022-08-05T19:40:48.158+0000","rule":{"level":7,"description":"CVE-2012-5568 affects Apache Tomcat 7.0 Tomcat72 (remove only)","id":"23504","firedtimes":3,"mail":false,"groups":["vulnerability-detector"],"gdpr":["IV_35.7.d"],"pci_dss":["11.2.1","11.2.3"],"tsc":["CC7.1","CC7.2"]},"agent":{"id":"001","name":"WIN-JLGVA4CR4VI","ip":"FE80:0000:0000:0000:B1E6:42AF:E199:1398"},"manager":{"name":"c3"},"id":"1659728448.7702246","decoder":{"name":"json"},"data":{"vulnerability":{"package":{"name":"Apache Tomcat 7.0 Tomcat72 (remove only)","version":"7.0.103","architecture":"x64","condition":"greater than or equal 7.0.0 and less than or equal 7.0.105"},"cvss":{"cvss2":{"vector":{"attack_vector":"network","access_complexity":"low","authentication":"none","confidentiality_impact":"none","integrity_impact":"none","availability":"partial"},"base_score":"5"}},"cve":"CVE-2012-5568","title":"CVE-2012-5568 affects Apache Tomcat 7.0 Tomcat72 (remove only)","rationale":"Apache Tomcat through 7.0.x allows remote attackers to cause a denial of service (daemon outage) via partial HTTP requests, as demonstrated by Slowloris.","severity":"Medium","published":"2012-11-30","updated":"2021-01-11","cwe_reference":"NVD-CWE-noinfo","status":"Active","type":"PACKAGE","references":["http://openwall.com/lists/oss-security/2012/11/26/2","http://captainholly.wordpress.com/2009/06/19/slowloris-vs-tomcat/","http://tomcat.10.n6.nabble.com/How-does-Tomcat-handle-a-slow-HTTP-DoS-tc2147776.html","http://tomcat.10.n6.nabble.com/How-does-Tomcat-handle-a-slow-HTTP-DoS-tc2147779.html","https://bugzilla.redhat.com/show_bug.cgi?id=880011","http://lists.opensuse.org/opensuse-updates/2012-12/msg00089.html","http://lists.opensuse.org/opensuse-updates/2012-12/msg00090.html","http://www.securityfocus.com/bid/56686","http://lists.opensuse.org/opensuse-updates/2013-01/msg00037.html","https://exchange.xforce.ibmcloud.com/vulnerabilities/80317","https://nvd.nist.gov/vuln/detail/CVE-2012-5568"],"assigner":"secalert@redhat.com","cve_version":"4.0"}},"location":"vulnerability-detector"}
   ```
</details>

**Comment by jmv74211** [comment]
🟢 Everything seems to be working properly
