### ISSUE TITLE
 Nightly report: 2022-08-09

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3161]
## Data

| Date|  Commit | Commit title | Build | Notes |
|--|--|--|--|--|
| 2022-08-09| [9a767d7](https://github.com/wazuh/wazuh/commit/9a767d7820ebf3e7ca33556a21c0b56f907ce13b) | Merge branch '4.4'  | [#1154](https://ci.wazuh.info/job/test_nightly/1154/) | 4.5 |

## Description

- [x] Fix FIM IT: test_ignore_works_over_restrict.py not received expected message [#3061](https://github.com/wazuh/wazuh-qa/issues/3061)
- [x] Fix Agentd IT: test_agentd_multi_server Assert Error [#3162](https://github.com/wazuh/wazuh-qa/issues/3162) 

### Faults detected to be solved by other teams since 2022-05-12

- [ ] Reliability tests: Generic Environent launcher error [#3465](https://github.com/wazuh/wazuh-jenkins/issues/3465)  (Reported to wazuh-jenkins)
- [x] AR IT: Nightly report - Failed test_execd_restart [#2769](https://github.com/wazuh/wazuh-qa/issues/2769)  (Reported a [bug](https://github.com/wazuh/wazuh/issues/13077) to Core) 
- [ ] IT pipeline: Unexpected Windows test launch error [#3487](https://github.com/wazuh/wazuh-jenkins/issues/3487)  (Reported to wazuh-jenkins)

**Note**: This issue also has information about Nightly launched previous than 2022-08-09

**Comment by damarisg** [comment]
Our nightly report showed differents failures. 
First, we launch executions again to validate the fails.

If it fails then a new issue is created to research and fix the error.
Else, the executions is launched five times to verify that it works successfully

| Test Module | OS | Tier | Build Execution | Final Executions| Notes
|--|--|--|--|--|--|
test_gcloud | centOS | 0 | [🔴 ](https://ci.wazuh.info/job/Test_integration/30338/console) - Unexpected error during deployment | [🟢](https://ci.wazuh.info/job/Test_integration/30388/)[🟢](https://ci.wazuh.info/job/Test_integration/30390/)[🟢](https://ci.wazuh.info/job/Test_integration/30399/)[🟢](https://ci.wazuh.info/job/Test_integration/30423/)[🟢](https://ci.wazuh.info/job/Test_integration/30437/)  |
