### ISSUE TITLE
Fix Agentd IT: test_agentd_multi_server Assert Error

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3162]
|Related issue|
|---|
|https://github.com/wazuh/wazuh-qa/issues/3161

| Date|  Commit | Commit title | Build | Version |
|--|--|--|--|--|
| 2022-08-05| [9a767d7]((https://github.com/wazuh/wazuh/commit/9a767d7820ebf3e7ca33556a21c0b56f907ce13b) | Merge branch '4.4' | [30320](https://ci.wazuh.info/job/Test_integration/30320)  | 4.5 |

## Case 

| Tier| Wazuh Type | OS
|--|--|--|
| 0 | Agent |  centOS - Ubuntu- MacOS

### Description

```
21:41:29  FAILED test_agentd/test_agentd_multi_server.py::test_agentd_multi_server[refuse_remoted_accept_enrollment]
```

## Tasks
- [x] Run tests in Jenkins
- [ ] Run tests in local enviroment
- [ ] Read test code & docs and run tests manually
- [ ] Fix failures

**Comment by damarisg** [comment]
# Update 2022/08/10

## Run tests using Jenkins

Test Path | Os | Build | Date | By | Notes
-- | -- | -- | -- | -- | --
test_agentd/ | CentOS - Windows - Ubuntu|  [:green_circle: ](https://ci.wazuh.info/job/Test_integration/30460) [:green_circle: ](https://ci.wazuh.info/job/Test_integration/30461/)[:green_circle: ](https://ci.wazuh.info/job/Test_integration/30462/)[:green_circle: ](https://ci.wazuh.info/job/Test_integration/30463/)[:green_circle: ](https://ci.wazuh.info/job/Test_integration/30456/) | 2022/08/10| @damarisg |  


This issue was closed because we couldn't reproduce it.
