### ISSUE TITLE
QA testing - Endpoint to get cluster ruleset synchronization status

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh-qa#3169]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
| 4.3.7 |https://github.com/wazuh/wazuh/issues/14533| https://github.com/wazuh/wazuh/pull/14552|

## Description
Right now, when a decoder, rule or CDB list is modified from the dashboard or the API, there is no way of knowing when the change has been synchronized to the rest of the nodes. As a consequence, it waits for a preset time (15 seconds) before restarting all managers for the changes to take effect.

To improve this situation, a mechanism has been added to the cluster that allows the API to efficiently obtain and compare the hash of the ruleset files. In addition, this endpoint has been added to the API:
```
GET /cluster/ruleset/synchronization
```

It returns something similar to this:
```JSON
{
  "data": {
    "affected_items": [
      {
        "name": "master-node",
        "synced": True
      },
      {
        "name": "worker1",
        "synced": True
      }
    ],
    "total_affected_items": 2,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "Nodes ruleset synchronization status was successfully read",
  "error": 0
}
```

## Proposed checks
A cluster environment is required for this tests:
- [x] Change `local_rules.xml` file in the master node. Verify that `synced` status is False for all workers and it changes to True in each one after synchronization.
- [x] Change `local_decoders.xml` file in the master node. Verify that `synced` status is False for all workers and it changes to True in each one after synchronization.
- [x] Change any CDB list file in the master node. Verify that `synced` status is False for all workers and it changes to True in each one after synchronization.
- [x] Create a new file in `etc/rules/`. Verify that `synced` status is False for all workers and it changes to True in each one after synchronization.
- [x] Create a new file in `etc/decoders/`. Verify that `synced` status is False for all workers and it changes to True in each one after synchronization.
- [x] Create a new file in `etc/lists/`. Verify that `synced` status is False for all workers and it changes to True in each one after synchronization.
- [x] Delete a file in `etc/rules/`. Verify that `synced` status is False for all workers and it changes to True in each one after synchronization.
- [x] Delete a file in `etc/decoders/`. Verify that `synced` status is False for all workers and it changes to True in each one after synchronization.
- [x] Delete a file in `etc/lists/`. Verify that `synced` status is False for all workers and it changes to True in each one after synchronization.
- [x] Create any rule/decoder/list file in a worker. Verify that `synced` status is False for said worker and it changes to True after a while (when synchronization happens).
- [x] Change any rule/decoder/list file in a worker. Verify that `synced` status is False for said worker and it changes to True after a while (when synchronization happens).

## Expected results
The sync status of the master must always be `True`. Workers will be `synced: False` when modifying/adding/removing a file in the mentioned directories or any subdirectories within them, until a full sync iteration occurs.

**Comment by Deblintrake09** [comment]
## Review data

| Tester | PR commit               | 
|--------|-------------------------|
| @Deblintrake  |  Tag v4.3.7 |

### Testing environment

| OS | OS version | Deployment                            |  Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
| Linux   |  Centos8 | `LOCAL\| Vagrant` | qactl/centos8 |       

### Tested packages

| `wazuh-manager` | `wazuh-agent` | 
|-----------------|---------------|
| [RPM Manager](https://packages-dev.wazuh.com/pre-release/yum/wazuh-manager-4.3.7-1.x86_64.rpm)  | 

### Status

- [x] In progress
- [ ] Pending Review
- [ ] Team leader approved
- [ ] Manager approved

**Comment by Deblintrake09** [comment]
# Tasks 
<details>
<summary>Configuration details</summary>

- Install  v4.3.7-1 Manager in 3 machines
![imagen](https://user-images.githubusercontent.com/14501079/184419747-f6cc3226-0e9c-481f-91ff-7a1e4fe0847e.png)
- Configure and start cluster
![imagen](https://user-images.githubusercontent.com/14501079/184419828-adcfac1e-bd95-4226-8470-7c90e2ea3105.png)

- Check that Ruleset is synchronized

   ```
   # curl -k -X GET "https://localhost:55000/cluster/ruleset/synchronization" -H "Authorization: Bearer $TOKEN"
   ```
```json
{
   "data": {
      "affected_items": [
         {
            "name": "master-node",
            "synced": true
         },
         {
            "name": "worker1",
            "synced": true
         },
         {
            "name": "worker2",
            "synced": true
         }
      ],
      "total_affected_items": 3,
      "total_failed_items": 0,
      "failed_items": []
   },
   "message": "Nodes ruleset synchronization status was successfully read",
   "error": 0
```
</details>

<details>
<summary>Change `local_rules.xml` in master node - check is synced</summary>
- Modify `local_rules.xml`
- Check it is not synched
- Wait for sync and check it has been synced

</details>

**Comment by jmv74211** [comment]
🟢 Everything seems to be working properly
