### ISSUE TITLE
Manual testing - Deprecate Debian Stretch in Vulnerability Detector

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh-qa#3171]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|4.4|https://github.com/wazuh/wazuh/issues/14354|https://github.com/wazuh/wazuh/pull/14542|

## Description
With the changes applied in PR wazuh/wazuh#14542, the support for Debian Stretch in Vulnerablity Detector has been removed, so it is necessary to check that even with this change the other options of the module work correctly.

## Proposed checks

- [x] VD works as expected with Debian block active (no `stretch` specified).
- [x] VD shows the `Warning` and does not scan the agent when specifying `stretch`.

## Steps to reproduce
Without the changes, when trying to scan a Debian Stretch agent, the following `Warning` will occur, as there is no vulnerability in the JSON feed:
```
WARNING: (5575): Unavailable vulnerability data for the agent '254' OS. Skipping it.
```

## Configuration and considerations
Default VD configuration by activating the Debian block. 
And specify (or not) the `<os>stretch</os>` target.

**Comment by Deblintrake09** [comment]
## Review data

| Tester | PR commit               |
|--------|-------------------------|
| @Deblintrake09 |   [2b22023](https://github.com/wazuh/wazuh/commit/2b22023da3e85c6fcf08863a27f1031175d381e7)    | 

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
|  Centos  |   8         | `<LOCAL \| Vagrant` |   qactl/centos_8        |       |
|  Debian  |   Stretch         | `<LOCAL \| Vagrant` |   qactl/centos_8        |       |


### Tested packages

| `wazuh-manager` | `wazuh-agent` | 
|-----------------|---------------|
|     [.rpm Manager](https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/rpm/var/wazuh-manager-4.4.0-0.commit2b22023.x86_64.rpm)            |  [.deb agent](https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/deb/var/wazuh-agent_4.4.0-0.commit2b22023_amd64.deb)      |

### Status

- [x] In progress
- [ ] Pending Review
- [ ] Team leader approved
- [ ] Manager approved

**Comment by Deblintrake09** [comment]
# Task results

<details>
<summary>VD works as expected with Debian block active (no stretch).</summary>
- Install Manager
- Connect Debian Stretch Agent
- Start Agent
- Wait for Vulnerability Scan
- Check modules is still running
- Check no segfault occured
</details>

**Comment by Deblintrake09** [comment]
### Update 2022/08/11

During testing a series of segfaults were found on modules. making it Impossible to finish the vulnerability scan. VDT crashed during the update

- Ossec Log
```
2022/08/11 19:12:12 wazuh-modulesd:vulnerability-detector[60646] wm_vuln_detector_nvd.c:957 at wm_vuldet_fetch_nvd_cve(): DEBUG: (5407): The feed 'National Vulnerability Database (2021)' is outdated. Fetching the last version.
2022/08/11 19:12:12 wazuh-modulesd:download[60646] wm_download.c:230 at wm_download_dispatch(): DEBUG: Downloading 'https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2021.json.gz' to 'tmp/req-542709641'
2022/08/11 19:12:16 wazuh-modulesd:download[60646] wm_download.c:250 at wm_download_dispatch(): DEBUG: Download of 'https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2021.json.gz' finished.
2022/08/11 19:12:17 wazuh-modulesd[60646] url.c:424 at wurl_request_uncompress_bz2_gz(): DEBUG: File from URL 'https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2021.json.gz' was successfully uncompressed into 'tmp/vuln-temp-fitted'
2022/08/11 19:12:17 wazuh-modulesd:vulnerability-detector[60646] wm_vuln_detector.c:7736 at wm_vuldet_index_json(): DEBUG: (5408): Updating from 'tmp/vuln-temp-fitted'
2022/08/11 19:13:28 wazuh-modulesd:vulnerability-detector[60646] wm_vuln_detector.c:4616 at wm_vuldet_index_feed(): DEBUG: (5414): Refreshing 'National Vulnerability Database' databases.
2022/08/11 19:13:28 wazuh-modulesd:vulnerability-detector[60646] wm_vuln_detector.c:3130 at wm_vuldet_insert(): DEBUG: (5415): Inserting vulnerabilities.
2022/08/11 19:13:28 wazuh-modulesd:vulnerability-detector[60646] wm_vuln_detector.c:3173 at wm_vuldet_insert(): DEBUG: (5419): Inserting NVD vulnerabilities section.
```
- Segfault showing in dme
![imagen](https://user-images.githubusercontent.com/14501079/184222580-a8a2d00b-bbba-4f16-997c-cf41aa38d166.png)
sg

#### Config Details
- Default Wazuh configuration with VDT enabled and Debian enabled
- Local Internal Options : `wazuh_modules.debug=2`
- Debian Stretch agent connected

**Comment by jmv74211** [comment]
🟢 Everything seems to be working properly.

It is proposed an improvement of the following description log, since it is produced when a system already deprecated (stretch) has been put, the message indicates that it has an unsupported version of Debian, but not which one.

```
2022/08/12 13:18:09 wazuh-modulesd:vulnerability-detector[3836] wm_vuln_detector.c:5842 at wm_vuldet_collect_agents_to_scan(): DEBUG: (5434): Agent '001' has an unsupported OS version: 'Debian'
```

It will be discussed with the development team and it will be decided whether to create an enhancement issue or not.
