### ISSUE TITLE
Release 4.3.7 - Release Candidate 1 - E2E UX tests - Wazuh Dashboard

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3176]
The following issue aims to run the specified test for the current release candidate, report the results, and open new issues for any encountered errors.
## Modules tests information

|||
|----------------------------------|------ |
| **Main release candidate issue** | [#14562](https://github.com/wazuh/wazuh/issues/14562)     |
| **Main E2E UX test issue** | [#14614](https://github.com/wazuh/wazuh/issues/14614)    |
| **Version**                      | 4.3.7 |
| **Release candidate #**          | RC1   |
| **Tag**                          | [v4.3.7-rc1](https://github.com/wazuh/wazuh/tree/v4.3.7-rc1) |
| **Previous modules tests issue** |    |

## Installation procedure
- Wazuh Indexer
  - [Step by Step](https://documentation.wazuh.com/current/installation-guide/wazuh-indexer/step-by-step.html)
- Wazuh Server
  - [Step by Step](https://documentation.wazuh.com/current/installation-guide/wazuh-indexer/step-by-step.html)
- Wazuh Dashboard
  - [Step by Step](https://documentation.wazuh.com/current/installation-guide/wazuh-indexer/step-by-step.html)
- Wazuh Agent
  - Wazuh WUI one-liner deploy IP GROUP (created beforehand)

## Test description

Best efford to test Wazuh dashboard package. Think critically and at least review/test:

 - [x] [Wazuh dashboard package specs](https://github.com/wazuh/wazuh-qa/issues/3176#issuecomment-1217898090)
 - [x] [Dashboard package size](https://github.com/wazuh/wazuh-qa/issues/3176#issuecomment-1217915330)
 - [x] [Dashboard package metadata (description)](https://github.com/wazuh/wazuh-qa/issues/3176#issuecomment-1217990799)
 - [x] [Dashboard package digital signature](https://github.com/wazuh/wazuh-qa/issues/3176#issuecomment-1218140697)
 - [x] [Installed files location, size and permissions](https://github.com/wazuh/wazuh-qa/issues/3176#issuecomment-1218228264)
 - [x] [Installation footprint (check that no unnecessary files are modified/broken in the file system. For example that operating system files do keep their right owner/pemissions and that the installer did not break the system.)](https://github.com/wazuh/wazuh-qa/issues/3176#issuecomment-1218373582)
 - [x] [Installed service (test that it works correctly)](https://github.com/wazuh/wazuh-qa/issues/3176#issuecomment-1218376807)
 - [x] [Wazuh Dashboard logs when installed](https://github.com/wazuh/wazuh-qa/issues/3176#issuecomment-1219419831)
 - [x] [Wazuh Dashboard configuration (Try to find anomalies compared with 4.3.6)](https://github.com/wazuh/wazuh-qa/issues/3176#issuecomment-1219494469)
 - [x] [Wazuh Dashboard (included the Wazuh WUI) communication with Wazuh manager API and Wazuh indexer](https://github.com/wazuh/wazuh-qa/issues/3176#issuecomment-1219661168)
 - [x] [Register Wazuh Agents](https://github.com/wazuh/wazuh-qa/issues/3176#issuecomment-1219742384)
 - [x] [Basic browsing throguh the WUI](https://github.com/wazuh/wazuh-qa/issues/3176#issuecomment-1220027690)
 - [x] [Basic experience with WUI performance.](https://github.com/wazuh/wazuh-qa/issues/3176#issuecomment-1220033939)
 - [x] [Anything else that could have been overlooked when creating the new package](https://github.com/wazuh/wazuh-qa/issues/3176#issuecomment-1220033939)

## Test report procedure

All test results must have one of the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed result. |
| :yellow_circle:  | There is at least one expected failure or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. 

An extended report of the test results can be attached as a ZIP or TXT file. Please attach any documents, screenshots, or tables to the issue update with the results. This report can be used by the auditors to dig deeper into any possible failures and details.

## Conclusions

All tests have been executed and the results can be found in the issue updates.

| **Status**     | **Test**    | **Failure type**    | **Notes**      |
|----------------|-------------|---------------------|----------------|
| :green_circle: | Wazuh dashboard package specs | Functional |  
| :green_circle: | Dashboard package size  | Functional |  
| :green_circle: | Dashboard package metadata (description) | Usability |  
| :green_circle: | Dashboard package digital signature | Usability |  
| :green_circle: | Installed files location, size and permissions  | Functional |  
| :green_circle: | Installation footprint  | Functional |  
| :green_circle: | Wazuh Dashboard logs when installed  | Functional | 
| :green_circle: | Wazuh Dashboard configuration  | Functional | 
| :green_circle: | Wazuh Dashboard (included the Wazuh WUI) communication with Wazuh manager API and Wazuh indexer | Functional |  
| :green_circle: | Register Wazuh Agents  | Functional |  
| :green_circle: | Basic browsing through the WUI | Usability |  
| :green_circle: | Basic experience with WUI performance | Usability |  

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [x] @jmv74211 
- [x] @vikman90

**Comment by QU3B1M** [comment]
# Wazuh Dashboard Package Specs

```yaml
apt show ./wazuh-dashboard_4.3.7-1_amd64.deb 

Package: wazuh-dashboard
Version: 4.3.7-1
Priority: extra
Section: admin
Maintainer: Wazuh, Inc <info@wazuh.com>
Installed-Size: 638 MB
Depends: debconf, adduser, curl, tar, libcap2-bin
Homepage: https://www.wazuh.com
Download-Size: 131 MB
APT-Manual-Installed: yes
APT-Sources: /vagrant/wazuh-dashboard_4.3.7-1_amd64.deb
Description: Wazuh dashboard is a user interface and visualization tool for security-related data. This Wazuh central component enables exploring, visualizing, and analyzing the stored security alerts generated by the Wazuh server. Wazuh dashboard enables inspecting the status and managing the configurations of the Wazuh cluster and agents as well as creating and managing users and roles. In addition, it allows testing the ruleset and making calls to the Wazuh API. Documentation can be found at https://documentation.wazuh.com/current/getting-started/components/wazuh-dashboard.html

```


![image](https://user-images.githubusercontent.com/44633633/185109356-3cd58d9b-8c1a-4182-9bc5-cadcf2c35707.png)

**Comment by QU3B1M** [comment]
# Dashboard Package Size :green_circle: 

![image](https://user-images.githubusercontent.com/44633633/185112645-b4884e30-d349-4563-9cdf-b870c2837a98.png)


```sh
 dpkg-query -Wf '${Installed-Size}\t${Package}\n'  | sort -n | tail -n 10 | grep "wazuh-dashboard"


622586	wazuh-dashboard
```
![image](https://user-images.githubusercontent.com/44633633/185112994-c2eb81e7-1f91-43a5-a404-1481bfc19c85.png)

**Comment by QU3B1M** [comment]
Dashboard Package Metadata

```
dpkg -f ./wazuh-dashboard_4.3.7-1_amd64.deb Description

Wazuh dashboard is a user interface and visualization tool for security-related data. This Wazuh central component enables exploring, visualizing, and analyzing the stored security alerts generated by the Wazuh server. Wazuh dashboard enables inspecting the status and managing the configurations of the Wazuh cluster and agents as well as creating and managing users and roles. In addition, it allows testing the ruleset and making calls to the Wazuh API. Documentation can be found at https://documentation.wazuh.com/current/getting-started/components/wazuh-dashboard.html

```

![image](https://user-images.githubusercontent.com/44633633/185115506-16f04504-c742-4b20-ae76-2c90775bb6b6.png)

**Comment by QU3B1M** [comment]
# Dashboard package digital signature :red_circle: 

On centos: 
![image](https://user-images.githubusercontent.com/44633633/185173082-1dc4b787-ccb3-4343-b34e-9445c588b564.png)

On Ubuntu:
![image](https://user-images.githubusercontent.com/44633633/185173590-ab700cbe-4abc-466d-9ff7-89db097f00cb.png)

**Comment by QU3B1M** [comment]
# Installed files location, size and permissions green_circle

**Comment by QU3B1M** [comment]
# Installation footprint :green_circle: 

<details>
<summary>Console debug log</summary>

root@dashboard:/vagrant# dpkg --debug=1 -i wazuh-dashboard_4.3.7-1_amd64.deb 
D000001: ensure_diversions: new, (re)loading
D000001: ensure_statoverrides: new, (re)loading
Selecting previously unselected package wazuh-dashboard.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 41077 files and directories currently installed.)
Preparing to unpack wazuh-dashboard_4.3.7-1_amd64.deb ...
D000001: process_archive oldversionstatus=not installed
Creating wazuh-dashboard group... OK
Creating wazuh-dashboard user... OK
D000001: ensure_diversions: same, skipping
Unpacking wazuh-dashboard (4.3.7-1) ...
D000001: process_archive updating info directory
D000001: generating infodb hashfile
D000001: process queue pkg wazuh-dashboard:amd64 queue.len 0 progress 1, try 1
Setting up wazuh-dashboard (4.3.7-1) ...
D000001: deferred_configure updating conffiles
D000001: ensure_diversions: same, skipping

```

</details>

**Comment by QU3B1M** [comment]
# Installed Service :green_circle: 

### `systemctl status wazuh-dashboard`
```bash
● wazuh-dashboard.service - wazuh-dashboard
     Loaded: loaded (/etc/systemd/system/wazuh-dashboard.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2022-08-17 18:50:25 UTC; 12s ago
   Main PID: 45851 (node)
      Tasks: 11 (limit: 2274)
     Memory: 162.9M
     CGroup: /system.slice/wazuh-dashboard.service
             └─45851 /usr/share/wazuh-dashboard/bin/../node/bin/node --no-warnings --max-http-header-size=65536 --unhandled-rejections=warn /usr/>

Aug 17 18:50:25 dashboard systemd[1]: wazuh-dashboard.service: Succeeded.
Aug 17 18:50:25 dashboard systemd[1]: Stopped wazuh-dashboard.
Aug 17 18:50:25 dashboard systemd[1]: Started wazuh-dashboard.
Aug 17 18:50:28 dashboard opensearch-dashboards[45851]: {"type":"log","@timestamp":"2022-08-17T18:50:28Z","tags":["info","plugins-service"],"pid">
Aug 17 18:50:29 dashboard opensearch-dashboards[45851]: {"type":"log","@timestamp":"2022-08-17T18:50:29Z","tags":["info","plugins-system"],"pid":>
Aug 17 18:50:29 dashboard opensearch-dashboards[45851]: {"type":"log","@timestamp":"2022-08-17T18:50:29Z","tags":["info","savedobjects-service"],>
Aug 17 18:50:29 dashboard opensearch-dashboards[45851]: {"type":"log","@timestamp":"2022-08-17T18:50:29Z","tags":["info","savedobjects-service"],>
Aug 17 18:50:29 dashboard opensearch-dashboards[45851]: {"type":"log","@timestamp":"2022-08-17T18:50:29Z","tags":["info","plugins-system"],"pid":>
Aug 17 18:50:29 dashboard opensearch-dashboards[45851]: {"type":"log","@timestamp":"2022-08-17T18:50:29Z","tags":["listening","info"],"pid":45851>
Aug 17 18:50:30 dashboard opensearch-dashboards[45851]: {"type":"log","@timestamp":"2022-08-17T18:50:30Z","tags":["info","http","server","OpenSea>
```

**Comment by QU3B1M** [comment]
# Wazuh Dashboard logs when installed 

### dpkg installation
```

2022-08-17 18:44:16 startup archives install
2022-08-17 18:44:16 install wazuh-dashboard:amd64 <none> 4.3.7-1
2022-08-17 18:44:16 status half-installed wazuh-dashboard:amd64 4.3.7-1
2022-08-17 18:45:35 status unpacked wazuh-dashboard:amd64 4.3.7-1
2022-08-17 18:45:35 configure wazuh-dashboard:amd64 4.3.7-1 4.3.7-1
2022-08-17 18:45:35 status half-configured wazuh-dashboard:amd64 4.3.7-1
2022-08-17 18:45:36 status installed wazuh-dashboard:amd64 4.3.7-1

```

**Comment by QU3B1M** [comment]
# Wazuh Dashboard configuration :green_circle: 

### Updates on the config file `wazuh.yml` as supposed (issue [#4402](https://github.com/wazuh/wazuh-kibana-app/issues/4402)) 

![1-X](https://user-images.githubusercontent.com/44633633/185403847-7ed8edb9-5919-416b-92f3-467259c1728e.png)
![2-x](https://user-images.githubusercontent.com/44633633/185403856-0c1fcf72-0e5e-48bf-9737-36768965418e.png)
![3-x](https://user-images.githubusercontent.com/44633633/185402517-4c6a08d5-c029-466b-8f03-08237f44d291.png)
![4-x](https://user-images.githubusercontent.com/44633633/185402523-938325e9-78c8-4c7b-903d-8caf12219104.png)
![5-x](https://user-images.githubusercontent.com/44633633/185402527-84fe9f45-2f84-49e4-a2c9-1e3976551977.png)
![6-x](https://user-images.githubusercontent.com/44633633/185402533-e423539b-2dfe-496d-8abb-adbbe2b7dbe0.png)

![last-x](https://user-images.githubusercontent.com/44633633/185404162-9a7eed3a-a091-45c0-bcba-617363f7bbbd.png)

**Comment by QU3B1M** [comment]
#  Wazuh Dashboard communication with Wazuh manager API and Wazuh indexer :green_circle: 

### `GET /manager/info`
![image](https://user-images.githubusercontent.com/44633633/185437252-235d5f01-ed9d-4a4d-adf5-c5fabe6211f2.png)
Server log: 
```
2022/08/18 15:27:14 INFO: wazuh-wui 192.168.56.12 "GET /manager/info" with parameters {} and body {} done in 0.015s: 200

```

### `GET /syscollector/000/packages?search=ssh&limit=1`
![image](https://user-images.githubusercontent.com/44633633/185436433-10ff4ff5-f1bb-46c7-ae69-c1739c4ffa6d.png)
Server log: 
```
2022/08/18 15:28:33 INFO: wazuh-wui 192.168.56.12 "GET /syscollector/000/packages" with parameters {"search": "ssh", "limit": "1"} and body {} done in 0.024s: 200
```

### Security Events

![image](https://user-images.githubusercontent.com/44633633/185436885-6c2367d2-f42e-4c07-a648-5956a71f6232.png)

**Comment by QU3B1M** [comment]
# Register Wazuh Agents

### Ubuntu Agent in default group
<details>
<summary>Installation steps</summary>

- Install agent 
```
root@vagrant:/home/vagrant# dpkg -i /vagrant/wazuh-agent_4.3.7-1_amd64.deb 
Selecting previously unselected package wazuh-agent.
(Reading database ... 41035 files and directories currently installed.)
Preparing to unpack .../wazuh-agent_4.3.7-1_amd64.deb ...
Unpacking wazuh-agent (4.3.7-1) ...
Setting up wazuh-agent (4.3.7-1) ...
Processing triggers for systemd (245.4-4ubuntu3.17) ...
```
- Edit ossec.conf just setting the correct manager IP
- Start the agent
```
root@vagrant:/home/vagrant# systemctl daemon-reload
root@vagrant:/home/vagrant# systemctl enable wazuh-agent
Synchronizing state of wazuh-agent.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable wazuh-agent
Created symlink /etc/systemd/system/multi-user.target.wants/wazuh-agent.service → /lib/systemd/system/wazuh-agent.service.
root@vagrant:/home/vagrant# systemctl start wazuh-agent

```
</details>

![image](https://user-images.githubusercontent.com/44633633/185446858-928601ee-25cd-4c02-8064-327c9932a28b.png)

**Comment by QU3B1M** [comment]
# Register Wazuh Agents 

### Ubuntu Agent

![image](https://user-images.githubusercontent.com/44633633/185446858-928601ee-25cd-4c02-8064-327c9932a28b.png)

### Windows Agent
![Screenshot from 2022-08-18 14-12-58](https://user-images.githubusercontent.com/44633633/185455455-df79c324-0aa2-4574-969f-07953ddbe489.jpg)
![image](https://user-images.githubusercontent.com/44633633/185455668-13c8b964-088b-47ea-9cb1-3edbd4eeb20f.png)

**Comment by QU3B1M** [comment]
# Basic browsing through the WUI

### Wazuh APP > Modules

https://user-images.githubusercontent.com/44633633/185501118-e1352467-768a-475c-9995-ee074585f5dc.mp4

### Wazuh APP > Management 

https://user-images.githubusercontent.com/44633633/185502124-76d661ab-bd62-423e-87c6-e74d6d53ff36.mp4

### Wazuh APP > Agents

https://user-images.githubusercontent.com/44633633/185503111-ffb3e443-61a3-404b-8c5a-7279368b57b7.mp4


### Wazuh APP > Tools 

https://user-images.githubusercontent.com/44633633/185503822-1e954ff0-597b-40f6-85c3-28f9ab215fc7.mp4


### Wazuh APP > Settings and general test

https://user-images.githubusercontent.com/44633633/185504388-acaf9c0c-faa5-4a68-9967-dd50504eef03.mp4

**Comment by QU3B1M** [comment]
# Basic experience with WUI performance. :green_circle: 
### `GET /rules & GET /decoders`

https://user-images.githubusercontent.com/44633633/185505368-65af6e13-5974-40da-a533-28fb400d580b.mp4
```
2022/08/18 22:04:47 INFO: wazuh-wui 192.168.56.12 "GET /decoders" with parameters {} and body {} done in 0.290s: 200
2022/08/18 22:04:56 INFO: wazuh-wui 192.168.56.12 "GET /rules" with parameters {} and body {} done in 0.588s: 200

```
