### ISSUE TITLE
QA testing - Behaviour of cluster restart procedure in the UI

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-qa#3178]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|           4.3.7             |      https://github.com/wazuh/wazuh-kibana-app/issues/4277                  |        https://github.com/wazuh/wazuh-kibana-app/pull/4365            |

## Description

We need to ensure these situations work as expected, and check if we should test more situations we haven't identified yet.

## Proposed checks

 - Restart correctly
   - [x] Synchronizes cluster and restarts correctly
   - [x] Restart node successfully

 - Failed to restart
   - [x] Cluster failed to restart
   - [x] Restart Node - Node disconnected during restart
   - [x] Failed to restart - unexpected API response
   - [ ] Failed to synchronize after a successful restart
   - [ ] Synchronize failed after an error on restart
   - [ ] Synchronize successful and error on restart
   - [x] Error restarting node

## Expected results

All the cases inform the user about what happened and what to do.

## Configuration and considerations

It would be interesting to test timeouts between the API and the UI in the middle of a restart cycle.

**Comment by Deblintrake09** [comment]
## Review data

| Tester | PR commit               |
|--------|-------------------------|
| @Deblintrake09 |   Tag v4.3.7-1     | 

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
|  Centos  |   8         | `<LOCAL \| Vagrant` |   qactl/centos_8        |       |


### Tested packages
- Installed Indexer, Manager and Dashboard using the [wazuh-install.sh](https://packages-dev.wazuh.com/4.3/wazuh-install.sh) script

### Status

- [x] In progress
- [ ] Pending Review
- [ ] Team leader approved
- [ ] Manager approved

**Comment by Deblintrake09** [comment]
# Task Results

## Restart correctly
<details>
<summary>Synchronizes cluster and restarts correctly</summary>
- Check that cluster is running and synchronized
- Restart Cluster
- Check that cluster restarted correctly and is synchronized
</details>

<details>
<summary>Restart node successfully</summary>
- Check that cluster is running and synchronized
- Restart a worker node `wazuh-1`
- Check that the node restarted correctly and is synchronized
</details>

**Comment by jmv74211** [comment]
After testing the proposed changes of this issue and supervising all the results obtained, it has been decided that the new development **does not meet the expected expectations**, and therefore, it will be necessary to give it a new iteration to improve all the following aspects:

Regarding the restart/synchronization waiting modal:

- The loading bar does not have uniform progress, and does not indicate to the user how long approximately he/she is going to have to wait. It is proposed that the bar progresses continuously, or in case of not knowing how long the task is going to take, instead of using a horizontal bar, a circular loading bar should be used that only indicates that it is doing things.

- It does not have elements that show the status information about what is being done. For example, "Synchronizing Wazuh," synchronizing what?

Regarding performance:

- When doing data synchronizations of several GB of data (see tests performed), the app is unmanageable, giving API timeouts all over the place and even making the `wazuh-indexer` crash.

**Comment by jmv74211** [comment]
Following the reports made, we have proceeded to perform a rollback of the changes made to the interface that have been tested in this issue. In the future, a better design will be made and its development will be included in a future release.

In the meantime, the next testing issue https://github.com/wazuh/wazuh-qa/issues/3178 has been opened to test the behavior after the rollback.
