### ISSUE TITLE
QA testing - Update WPK upgrade root CA certificate

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-qa#3189]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|          4.4.0             |           https://github.com/wazuh/wazuh/issues/14558              |          https://github.com/wazuh/wazuh/pull/14696          |

## Description

In this PR, we're updating the root CA to validate WPK upgrades.

## Proposed checks

- [x] The root CA validates the certificate (provided in the PR).
- [x] Agents on version 4.3.* refuse to upgrade to 4.4.0.
- [x] Agents on version 4.3.* upgrade to 4.4.0 after replacing wpk_root.pem.
- [x] Agents on version 4.4.0 (that branch) accept to upgrade to the same version.
- [x] Agents on version 4.4.0 (that branch) accept to downgrade to lower version with new wpk_cert.

**Comment by CamiRomero** [comment]
## Review data

| Tester | PR commit               |
|--------|-------------------------|
| @CamiRomero   |  [00718e](https://github.com/wazuh/wazuh/pull/14696/commits/00718e3720d127c44d73d7c9b093d90a918790a0)   |

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
| Centos    |     8     | AWS |   ami-029496e60f56b4b13          |


### Tested packages

| `wazuh-manager` | `wazuh-agent` | 
|-----------------|---------------|
|  [4.4.0](https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/rpm/var/wazuh-manager-4.4.0-0.commit00718e3.x86_64.rpm)               | -     |

### Status

- [x] In progress
- [ ] Pending Review
- [ ] Team leader approved
- [ ] Manager approved

**Comment by Deblintrake09** [comment]
# Task results

<details>
<summary> Agents on version 4.3.* refuse to upgrade to 4.4.0 :green_circle: </summary>
- Replace certificate WPK certificate on agent
- Restart agent
- Run upgrade command from manager
   ```
   # /var/ossec/bin/agent_upgrade -a 001 -f /home/qa/wazuh_agent_v4.4.0-3189.test.wpk.rootca_windows.wpk -x upgrade.sh

   Upgrading...

   Failed upgrades:
   	Agent 001 status: Send open file error
   ```
- Check agent's /upgrade folder - wpk file has been copied but not installed
![imagen](https://user-images.githubusercontent.com/14501079/185658362-cc443289-034e-480e-a6e4-f8ae5bd22b74.png)

</details>

**Comment by Deblintrake09** [comment]
# Update 22/08/2022
- Manual Testing :red_circle:
- Asked Core - Packages are not yet signed with new WPK cert. 
- CICD will generate signed packages so testing can be done

**Comment by Deblintrake09** [comment]
# Task results

<details>
<summary> Agents on version 4.3.* refuse to upgrade to agent :green_circle: </summary>


- Run upgrade command from manager
   ```
   # /var/ossec/bin/agent_upgrade -a 003 -f /home/qa/wazuh_agent_v4.3.0_linux_x86_64.wpk

   Upgrading...

   Failed upgrades:
	Agent 003 status: Send upgrade command error
   ```
- Check agent's `ossec.log` for fail
   ```
   2022/08/23 15:39:23 wazuh-syscheckd: INFO: (6009): File integrity monitoring scan ended.
   2022/08/23 15:39:59 wazuh-modulesd: ERROR: Error verifying WPK certificate.
   2022/08/23 15:39:59 wazuh-modulesd:agent-upgrade: ERROR: (8139): At unsign(): Could not unsign package file 'var/incoming/wazuh_agent_v4.3.0_linux_x86_64.wpk'
   2022/08/23 15:39:59 wazuh-modulesd:agent-upgrade: ERROR: (8131): At upgrade: 'Could not verify signature'
   ```
</details>

<details>
<summary> Agents on version 4.3.* upgrade after replacing wpk_root.pem :green_circle: </summary>

- Replace `wpk_root.pem` with cert from PR
- Run upgrade command from manager
   ```
   # /var/ossec/bin/agent_upgrade -a 003 -f /home/qa/wazuh_agent_v4.3.0_linux_x86_64.wpk

   Upgrading...

   Upgraded agents:
	Agent 003 upgraded: Wazuh v4.3.6 -> Wazuh v4.3.0
   ```

- Check agent's `ossec.log` for fail
   ```
   2022/08/23 16:38:34 wazuh-modulesd:syscollector: INFO: Stop received for Syscollector.
   2022/08/23 16:38:34 wazuh-modulesd:syscollector: INFO: Module finished.
   2022/08/23 16:38:34 wazuh-logcollector: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
   2022/08/23 16:38:34 wazuh-syscheckd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
   2022/08/23 16:38:34 wazuh-agentd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
   2022/08/23 16:38:34 wazuh-execd: INFO: (1314): Shutdown received. Deleting responses.
   2022/08/23 16:38:34 wazuh-execd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
   ```

- Check agent's version
   ```
   # /var/ossec/bin/wazuh-control info
   WAZUH_VERSION="v4.3.0"
   WAZUH_REVISION="40310"
   WAZUH_TYPE="agent"
   ```
</details>

**Comment by jmv74211** [comment]
🟢 Everything seems to be working properly. 

[A case](https://github.com/wazuh/wazuh/issues/14747) has been detected where the update fails if the agent is running a scan, but is not related to this issue.
