### ISSUE TITLE
QA Testing - Release 4.3.7-RC2 - Behavior of cluster restart procedure in the UI

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#3192]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|  4.3.7-rc2   |  https://github.com/wazuh/wazuh-kibana-app/issues/4277    |  https://github.com/wazuh/wazuh-kibana-app/pull/4405  |

## Description

Whe need to ensure the correct behavior of the Cluster during restarts generated from the Wazuh Dashboard.

## Proposed checks

- [x] Restart cluster successfully
- [x] Modify a rules/decoders/list file and restart cluster successfully
- [x] Restart cluster - changing page during restart causes crash and goes to healthcheck
- [x] Restart cluster during big files synchronization - No overwrite tag
- [x] Restart cluster during big files synchronization - Use Overwrite tag

## Configuration and considerations

Setup cluster with default configuration.

**Comment by Deblintrake09** [comment]
## Review data

| Tester | PR commit               |
|--------|-------------------------|
| @Deblintrake09 |   Tag v4.3.7-1     | 

### Testing environment

| OS | OS version | Deployment              |Image/AMI | Notes |
|----|------------|-----------------------------------|-----------|-------|
|  Centos  |   8         | `<REMOTE \| Deployer - EC2` |   ami-0e65b7ce2dab78ec9    |  **Box Size** c5.xlarge     |


### Tested packages
- Installed Indexer, Manager and Dashboard using the [wazuh-install.sh](https://packages-dev.wazuh.com/4.3/wazuh-install.sh) script


### Status

- [x] In progress
- [ ] Pending Review
- [ ] Team leader approved
- [ ] Manager approved

**Comment by Deblintrake09** [comment]
## Task Results

<details>
<summary>Restart cluster successfully :green_circle: </summary>
- Check cluster is synchronized
```
# curl -k -X GET "https://localhost:55000/cluster/ruleset/synchronization?pretty=true" -H "Authorization: Bearer $TOKEN"
{
   "data": {
      "affected_items": [
         {
            "name": "master",
            "synced": true
         },
         {
            "name": "worker1",
            "synced": true
         },
         {
            "name": "worker2",
            "synced": true
         }
      ],
      "total_affected_items": 3,
      "total_failed_items": 0,
      "failed_items": []
   },
   "message": "Nodes ruleset synchronization status was successfully read",
   "error": 0
}
```
- Restart the cluster from the `/management/status` page
- Change to other page during restart
- Check UI does not crash :green_circle: 

**VIDEO EVIDENCE**
https://user-images.githubusercontent.com/14501079/185956360-627daaeb-071a-4ff3-b525-0f228f344684.mp4
</details>


<details>
<summary>Restart cluster - changing page during restart causes crash :green_circle: </summary>
- Check cluster is synchronized
```
# curl -k -X GET "https://localhost:55000/cluster/ruleset/synchronization?pretty=true" -H "Authorization: Bearer $TOKEN"
{
   "data": {
      "affected_items": [
         {
            "name": "master",
            "synced": true
         },
         {
            "name": "worker1",
            "synced": true
         },
         {
            "name": "worker2",
            "synced": true
         }
      ],
      "total_affected_items": 3,
      "total_failed_items": 0,
      "failed_items": []
   },
   "message": "Nodes ruleset synchronization status was successfully read",
   "error": 0
}
```
- Restart the cluster from the `/management/status` page
- Change to other page during restart
- Check UI does not crash :green_circle: 

**VIDEO EVIDENCE**
https://user-images.githubusercontent.com/14501079/185956572-c581ef64-9694-430d-86a4-7572be89aacf.mp4
</details>

**Comment by Deblintrake09** [comment]
## Error testing results

The errors found were tested and replicated in 4.3.6, so they are not introduced in this version. It seems that the timeout is generated when big rule files are added to the rules directory. It was tested with 10Mb and 100Kb files. The error was found when the file was large.

### Video Evidence

- 10Megabyte file with no overwrite in 4.3.6 - 3 copies :red_circle: 

https://user-images.githubusercontent.com/14501079/186155949-a243f28c-9bd4-4c43-81e4-f6f952a21a81.mp4




- 10Megabyte file with no overwrite in 4.3.7-2 - 3 copies :red_circle: 
 
https://user-images.githubusercontent.com/14501079/186154931-3381a259-0b9c-4848-97c1-728e63c945b3.mp4

- 100 Megabyte file with no overwrite in 4.3.7-2 - 100 copies :green_circle: 

https://user-images.githubusercontent.com/14501079/186154955-0a5fd2f8-1720-4d2f-9e5b-5be271d03145.mp4

**Comment by jmv74211** [comment]
The following issues have been opened to report the problems detected in this testing issue:
- [App crashes with large rules files](https://github.com/wazuh/wazuh-kibana-app/issues/4410)
- [Improve warning message when exceeding file upload limits](https://github.com/wazuh/wazuh-kibana-app/issues/4411)
