### ISSUE TITLE
E2E tests: Adapt E2E tests to allow jenkins atomation

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#3194]
### Description
In order to automate E2E tests, it is necessary to create the required configuration files in order to allow the deployment and the provision of the environment
Also, it is required to adapt E2E tests, in order to respect expected parameters and the inventory provided by the automation tool.

### TODO
- [x] Create E2E environment configuration file
- [x] Create a JSON file that maps the environment with its configuration file along with supported tests
- [x] Refactor expected inventory groups
- [ ] Ensure full green in deployed environments
