### ISSUE TITLE
Fix Logcollector IT: test_basic_configuration_age.py not received expected message

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3195]
|Related issue|
|---|
|https://github.com/wazuh/wazuh-qa/issues/3196

## Data

| Date|  Commit | Commit title | Build | Notes |
|--|--|--|--|--|
| 2022-08-22| [6cce5b8](6cce5b8465ecdc8008950e6fc0a2bfd0ebb251c1) | Merge branch '4.4'  |[#30852](https://ci.wazuh.info/job/Test_integration/30852) | 4.5 |

## Case 

| Tier| Wazuh Type | OS
|--|--|--|
| 0 | Agent |  centOS - Ubuntu- Windows

### Description

```
21:51:29  FAILED test_logcollector/test_configuration/test_basic_configuration_age.py::test_configuration_age[C:\\testing\\file.txt_syslog_3s]

21:51:29  FAILED test_logcollector/test_configuration/test_basic_configuration_age.py::test_configuration_age[C:\\testing\\file.txt_syslog_4000s]

21:51:29  FAILED test_logcollector/test_configuration/test_basic_configuration_age.py::test_configuration_age[C:\\testing\\file.txt_syslog_5m]

21:51:29  FAILED test_logcollector/test_configuration/test_basic_configuration_age.py::test_configuration_age[C:\\testing\\file.txt_syslog_99h]

21:51:29  FAILED test_logcollector/test_configuration/test_basic_configuration_age.py::test_configuration_age[C:\\testing\\file.txt_syslog_94201d]
```

## Tasks
- [x] Run tests in Jenkins
- [x] Run tests in local enviroment
- [x] Read test code & docs and run tests manually
- [ ] Fix failures
