### ISSUE TITLE
Nightly report: 2022-08-22

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3196]
## Data

| Date|  Commit | Commit title | Build | Notes |
|--|--|--|--|--|
| 2022-08-22| [6cce5b8](6cce5b8465ecdc8008950e6fc0a2bfd0ebb251c1) | Merge branch '4.4'  | [#1175](https://ci.wazuh.info/job/test_nightly/1175/) | 4.5 |

## Description

- [x] Fix Logcollector IT: test_ignore_works_over_restrict.py not received expected message [#3195](https://github.com/wazuh/wazuh-qa/issues/3195)
- [ ] Reliability tests: Generic Environent launcher error [#3465](https://github.com/wazuh/wazuh-jenkins/issues/3465)  (Reported to wazuh-jenkins)
- [ ] IT pipeline: Unexpected Windows test launch error [#3487](https://github.com/wazuh/wazuh-jenkins/issues/3487)  (Reported to wazuh-jenkins)

**Note**: This issue also has information about Nightly launched previous than 2022-08-09

**Comment by damarisg** [comment]
It will close, and it updates in [#3279](https://github.com/wazuh/wazuh-qa/issues/3279).
