### ISSUE TITLE
QA testing - Malformed merged.mg file

### ISSUE THREAD

**Issue by cborla** [wazuh/wazuh-qa#3201]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|4.5|https://github.com/wazuh/wazuh/issues/14375|https://github.com/wazuh/wazuh/pull/14659|

## Description
The goal of this fix is avoid malformed merged.mg file as the [issue 14375](https://github.com/wazuh/wazuh/issues/14375) mentions.
The propouse is increase the robustness of the file append process to merged.mg file. It was not possible to reproduce the error, it's difficult make `fseek` function fail.
Another definition is allow add zero size files, notifying it in ossec.log as a WARNING.

## Proposed checks

- [x] Check that `merged.mg` file is updated correctly at manager starting.

- [x] Check that `merged.mg` file is updated correctly every 10 seconds approx.

- [x] Add a new non zero size file in default folder and check that `merged.mg` file is updated correctly at the manager starting.

- [x] Add a new non zero size file in default folder and check that `merged.mg` file is updated correctly every 10 seconds approx.

- [x] Add a new non zero size file in a custom group and Check that `merged.mg` file is updated correctly at the manager starting.

- [x] Add a new non zero size file in a custom group and check that `merged.mg` file is updated correctly every 10 seconds approx.

- [x] Add a new zero size file in default folder and check that `merged.mg` file is updated correctly at the manager starting, check in ossec.log file a size zero file warning message notification.

- [x] Add a new zero size file in default folder and check that `merged.mg` file is updated correctly every 10 seconds approx, check in ossec.log file a size zero file warning message notification.

- [x] Add a new zero size file in a custom group and check that `merged.mg` file is updated correctly at the manager starting, check in ossec.log file a size zero file warning message notification.

- [x] Add a new zero size file in a custom group and check that `merged.mg` file is updated correctly every 10 seconds approx, check in ossec.log file a size zero file warning message notification.

- [x] Add several files in default folder group and check that `merged.mg` file is updated correctly at the manager starting.

- [x] Add several files in a custom group and check that `merged.mg` file is updated correctly at the manager starting.

## Steps to reproduce
It was not possible reproduce a malformed merged.mg file.
 
## Expected results
Merged.mg file is created at wazuh manager initialization or every 10 seconds. the process includes all files in a group directory. 
By default it inclues the default group  `/var/ossec/etc/shared/default/`.

Default folder configuration:
```
agent.conf
agent-template.conf
cis_apache2224_rcl.txt
cis_debian_linux_rcl.txt
cis_mysql5-6_community_rcl.txt
cis_mysql5-6_enterprise_rcl.txt
cis_rhel5_linux_rcl.txt
cis_rhel6_linux_rcl.txt
cis_rhel7_linux_rcl.txt
cis_rhel_linux_rcl.txt
cis_sles11_linux_rcl.txt
cis_sles12_linux_rcl.txt
cis_win2012r2_domainL1_rcl.txt
cis_win2012r2_domainL2_rcl.txt
cis_win2012r2_memberL1_rcl.txt
cis_win2012r2_memberL2_rcl.txt
merged.mg
rootkit_files.txt
rootkit_trojans.txt
system_audit_rcl.txt
system_audit_ssh.txt
win_applications_rcl.txt
win_audit_rcl.txt
win_malware_rcl.txt
```
merged.mg must includes the content of all files in the folder, except for binaries files.

## Configuration and considerations

Default `/etc/internal_options.conf`
```  
  # Shared files reloading interval (sec) [1..18000]
  remoted.shared_reload=10
```

**Comment by Deblintrake09** [comment]
## Review data

| Tester | PR commit               |
|--------|-------------------------|
| @Deblintrake09 | [784e37d](https://github.com/wazuh/wazuh/commit/784e37de95875093b4a64fbf84c1ca0a5d97d4d6)    | 

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
|  Centos  |    8       | `<Local \| Vagrant` | qactl/centos_8         |       |


### Tested packages

| `wazuh-manager` | `wazuh-agent` | 
|-----------------|---------------|
|     [.rpm Manager](https://packages-dev.wazuh.com/warehouse/pullrequests/4.5/rpm/var/wazuh-manager-4.5.0-0.commit784e37d.x86_64.rpm)          |   |

### Status

- [x] In progress
- [x] Pending Review
- [ ] Team leader approved
- [ ] Manager approved

**Comment by Deblintrake09** [comment]
## Task results - Clean Install

<details><summary>Check that <code>merged.mg</code> is updated correctly every 10 seconds approx. :green_circle: </summary>

- Check that `merged.md` file does not exist
```
# ls /var/ossec/etc/shared/default -la | grep merged
```
- Start manager
```
# /var/ossec/bin/wazuh-control start
Starting Wazuh v4.5.0...
Started wazuh-apid...
Started wazuh-csyslogd...
Started wazuh-dbd...
2022/08/29 13:36:34 wazuh-integratord: INFO: Remote integrations not configured. Clean exit.
Started wazuh-integratord...
Started wazuh-agentlessd...
Started wazuh-authd...
Started wazuh-db...
Started wazuh-execd...
Started wazuh-analysisd...
Started wazuh-syscheckd...
Started wazuh-remoted...
Started wazuh-logcollector...
Started wazuh-monitord...
Started wazuh-modulesd...
Completed.
```
- Check `merged.md` file exists
```
# ls /var/ossec/etc/shared/default -la | grep merged.mg
-rw-rw----. 1 wazuh wazuh 899315 ago 29 13:36 merged.mg
```
- Check `merged.md` is not malformed :green_circle: 
</details>

<details><summary>Check that <code>merged.mg</code> is updated correctly every 10 seconds approx. :green_circle: </summary>

- Check that `merged.md` file does not exist
```
# ls /var/ossec/etc/shared/default -la | grep merged
-rw-rw----. 1 wazuh wazuh 899315 ago 29 13:54 merged.mg
```
- Remove `merged.md` and wait 10s for it to be recreated
```
# rm /var/ossec/etc/shared/default/merged.mg -f
# ls /var/ossec/etc/shared/default -la | grep merged
```
- Check that `merged.md` file exists
```
# ls /var/ossec/etc/shared/default -la | grep merged.mg
# ls /var/ossec/etc/shared/default -la | grep merged
-rw-rw----. 1 wazuh wazuh 899315 ago 29 13:55 merged.mg
```
- Check `merged.md` is not malformed :green_circle: 
</details>
---

<details><summary> Add a new group and check that <code>merged.mg</code> file is updated correctly at manager starting. :red_circle: </summary>

- Check that `merged.md` file does not exist
```
# ls /var/ossec/etc/shared/default -la | grep merged
```
- Add new `Testgroup` group and start manager   :red_circle:  - **Cannot add groups with stopped manager**
```
# /var/ossec/bin/agent_groups -a -g TestGroup1
Do you want to create the group 'TestGroup1'? [y/N]: y
Error 1017: Some Wazuh daemons are not ready yet in node "node01" (wazuh-modulesd->stopped, wazuh-analysisd->stopped, wazuh-execd->stopped, wazuh-db->stopped, wazuh-remoted->stopped)
```
</details>


<details><summary>Add a new group and check that <code>merged.mg</code> is updated correctly every 10 seconds approx. :red_circle: </summary>

- Add a new group and check it is added within 10 seconds
```
# /var/ossec/bin/agent_groups -a -g TestGroup1
Do you want to create the group 'TestGroup1'? [y/N]: y
Group 'TestGroup1' created.
```
- Check that `merged.md` file exists
```
# ls /var/ossec/etc/shared/default -la | grep merged.mg
-rw-rw----. 1 wazuh wazuh 899315 ago 29 14:01 /var/ossec/etc/shared/default/merged.mg
```
- Check `merged.md` is not malformed :green_circle: 
</details>
---

<details><summary>Add a new non zero zise file in default folder and check that  <code>merged.mg</code> is created correctly when starting </summary>

- Add a new non empty file
```
# echo "Data in file" >> /var/ossec/etc/shared/default/TestFile.txt
```
- Start manager
- Check that `merged.md` file exists
```
# ls /var/ossec/etc/shared/default -la | grep merged.mg
-rw-rw----. 1 wazuh wazuh 899345 ago 29 14:43 /var/ossec/etc/shared/default/merged.mg
```
- Check `merged.md` is not malformed :green_circle: 
```
#default
!228 ar.conf
restart-ossec0 - restart-ossec.sh - 0
restart-ossec0 - restart-ossec.cmd - 0
restart-wazuh0 - restart-ossec.sh - 0
restart-wazuh0 - restart-ossec.cmd - 0
restart-wazuh0 - restart-wazuh - 0
restart-wazuh0 - restart-wazuh.exe - 0
!13 TestFile.txt
Data in file
!76 agent.conf
<agent_config>
```
</details>

<details><summary>Add a new non zero zise file in default folder and check that  <code>merged.mg</code> is updated correctly every 10 seconds approx. :red_circle: </summary>

- Add a new non empty file
```
# echo "Data in file" >> /var/ossec/etc/shared/default/TestFile2.txt
```
- Wait for 10 seconds and check that `merged.md` is updated
```
# ls /var/ossec/etc/shared/default -la | grep merged.mg
-rw-rw----. 1 wazuh wazuh 899345 ago 29 14:43 /var/ossec/etc/shared/default/merged.mg
```
- Check `merged.md` is not malformed :green_circle: 
```
#default
!228 ar.conf
restart-ossec0 - restart-ossec.sh - 0
restart-ossec0 - restart-ossec.cmd - 0
restart-wazuh0 - restart-ossec.sh - 0
restart-wazuh0 - restart-ossec.cmd - 0
restart-wazuh0 - restart-wazuh - 0
restart-wazuh0 - restart-wazuh.exe - 0
!13 TestFile.txt
Data in file
!13 TestFile2.txt
Data in file
!76 agent.conf
<agent_config>
```
</details>

**Comment by Deblintrake09** [comment]
<details><summary>Add a new zero zise file in TestGroup1 folder and check that  <code>merged.mg</code> is updated correctly when manager is started :green_circle: </summary>

- Stop the manager
- Add a new empty file
```
# touch /var/ossec/etc/shared/TestGroup1/EmptyFileInGroup2.txt
```
- Start the manager and check that `merged.md` is updated
```
# ls /var/ossec/etc/shared/TestGroup1 -la | grep merged.mg
-rw-rw----. 1 wazuh wazuh 476 ago 29 15:24 /var/ossec/etc/shared/TestGroup1/merged.mg
```
- Check `merged.md` is not malformed :green_circle: 
```
#TestGroup1
!228 ar.conf
restart-ossec0 - restart-ossec.sh - 0
restart-ossec0 - restart-ossec.cmd - 0
restart-wazuh0 - restart-ossec.sh - 0
restart-wazuh0 - restart-ossec.cmd - 0
restart-wazuh0 - restart-wazuh - 0
restart-wazuh0 - restart-wazuh.exe - 0
!0 EmptyFileInGroup.txt
!0 EmptyFileInGroup2.txt
!13 TestFileInTestGroup.txt
Data in file
!13 TestFileInTestGroup2.txt
Data in file
!76 agent.conf
<agent_config>
```
- Check `ossec.log` for empty file warning :green_circle: 
```
2022/08/29 15:24:00 wazuh-remoted: INFO: Started (pid: 14552). Listening on port 1514/TCP (secure).
2022/08/29 15:24:00 wazuh-remoted: WARNING: file 'etc/shared/default/EmptyFile.txt' is empty.
2022/08/29 15:24:00 wazuh-remoted: WARNING: file 'etc/shared/default/EmptyFile2.txt' is empty.
2022/08/29 15:24:01 wazuh-remoted: WARNING: file 'etc/shared/TestGroup1/EmptyFileInGroup.txt' is empty.
2022/08/29 15:24:01 wazuh-remoted: WARNING: file 'etc/shared/TestGroup1/EmptyFileInGroup2.txt' is empty.
```
</details>


<details><summary>Add a new zero zise file in TestGroup1 folder and check that  <code>merged.mg</code> is updated correctly every 10 seconds aprox. :green_circle: </summary>

- Add a new empty file
```
# touch /var/ossec/etc/shared/TestGroup1/EmptyFileInGroup.txt
```
- Wait for 10 seconds check that `merged.md` is updated
```
# ls /var/ossec/etc/shared/TestGroup1 -la | grep merged.mg
-rw-rw----. 1 wazuh wazuh 451 ago 29 15:20 /var/ossec/etc/shared/TestGroup1/merged.mg
```
- Check `merged.md` is not malformed :green_circle: 
```
#TestGroup1
!228 ar.conf
restart-ossec0 - restart-ossec.sh - 0
restart-ossec0 - restart-ossec.cmd - 0
restart-wazuh0 - restart-ossec.sh - 0
restart-wazuh0 - restart-ossec.cmd - 0
restart-wazuh0 - restart-wazuh - 0
restart-wazuh0 - restart-wazuh.exe - 0
!0 EmptyFileInGroup.txt
!13 TestFileInTestGroup.txt
Data in file
!13 TestFileInTestGroup2.txt
Data in file
!76 agent.conf
<agent_config>

```
- Check `ossec.log` for empty file warning :green_circle: 
```
2022/08/29 15:20:09 wazuh-remoted: WARNING: file 'etc/shared/TestGroup1/EmptyFileInGroup.txt' is empty.
```
</details>

**Comment by jmv74211** [comment]
🟢 Everything seems to be working properly. We will discuss with the development team the @Deblintrake09 proposal about `merged.mg` file recreation
