### ISSUE TITLE
E2E tests: Improve validation stage

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#3203]
## Description

After the debugging and testing done in #3166 we could see that the validation stage needs some improvements:

- [x] ([**T1**](https://github.com/wazuh/wazuh-qa/issues/3203#issuecomment-1231549919)): Check that the names of the groups are valid.
- [x] ([**T2**](https://github.com/wazuh/wazuh-qa/issues/3203#issuecomment-1231694604)): Check that hostnames have a valid format (`<os>-<wazuh-installation-type>`).
- [x] ([**T3**](https://github.com/wazuh/wazuh-qa/issues/3203#issuecomment-1231713900)): Display an error when the IP is invalid.
- [x] ([**T4**](https://github.com/wazuh/wazuh-qa/issues/3203#issuecomment-1231897546)): Check invalid indexer credentials in the validation stage.
- [x] ([**T5**](https://github.com/wazuh/wazuh-qa/issues/3203#issuecomment-1232004055)): Check the distro considering the Wazuh installation type.
- [x] ([**T6**](https://github.com/wazuh/wazuh-qa/issues/3203#issuecomment-1232852956)): Check if a Windows agent is stopped.
- [x] [**Extra**](https://github.com/wazuh/wazuh-qa/issues/3203#issuecomment-1232903758): Change the way the validation stage checks the connection with the Wazuh Indexer

**Comment by mauromalara** [comment]
Working branch: 3203-validation-stage-improvement

**Comment by mauromalara** [comment]
T1: Check that the names of the groups are valid. 🔵 

We must check the following allowed names:
- managers
- agents
- linux
- windows
- all

**Comment by mauromalara** [comment]
## T2: Check that hostnames have a valid format (<os>-<wazuh-installation-type>)

We must check 2 scenarios:
1. The inventory hostname is not valid
2. The inventory hostname is not necessary for the test execution (I mean if the test only needs a Manager and the inventory has an Ubuntu agent the validation must fail).

### Performing a test to validate the implementation:

#### Scenario 1

1. Force the error by modifying the inventory:
```
managers:
  hosts:
    manager-centos: <--- FORCE THE ERROR (expected: centos-manager)
```

**Result 🟢**

```
E           Exception: The hostname 'manager-centos' doesn't follow our standard: <os>-<installation-type> or isn't a necessary host for the execution of the selected tests.
E           Read the README.md file inside the E2E suite to build a valid inventory.
```

***

#### Scenario 2

1. The `test_audit` test needs only a CentOS manager, so we force the error by modifying the inventory:
```
agents:
  children:
    linux:
      hosts:
        ubuntu-agent: <------ Force the error
```

**Result 🟢**

```
E           Exception: The hostname 'ubuntu-agent' doesn't follow our standard: <os>-<installation-type> or isn't a necessary host for the execution of the selected tests.
E           Read the README.md file inside the E2E suite to build a valid inventory.
```

***

**Comment by mauromalara** [comment]
## T3: Display an error when the IP is invalid. 🔵

**Comment by mauromalara** [comment]
## T3: Display an error when the IP is invalid. 🔵

**Comment by mauromalara** [comment]
## T4: Check invalid indexer credentials in the validation stage. 🔵 

WIP.

**Comment by mauromalara** [comment]
## T6: 🟢 

### Performing manual testing

1. Force the error by stopping the Windows agent
2. Run `test_emotet`

**Result 🟢**

```
E   Exception: The general validations have failed. Please check that the environments meet the expected requirements. Result:
E   WazuhSvc is not running (Windows).
```

| Result
|--
| [🟢]

**Comment by mauromalara** [comment]
## Extra: Change the way the validation stage checks the connection with the Wazuh Indexer 🔵

WIP.
