### ISSUE TITLE
QA testing - WModules - Database: Clean artifacts function wrongly deletes diff folder.

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh-qa#3206]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|4.4                   |https://github.com/wazuh/wazuh/issues/13875                        |https://github.com/wazuh/wazuh/pull/13892                    |

## Description

The module `wm_database` during the synchronization deletes artifacts from old agents. The artifacts include agent database at `/var/ossec/var/db/agents/<agent_db>` and information at `/var/ossec/queue/diff/<agent_hostname>`
The `clean_artifacts()` function verifies the non-existence of an agent in the `global.db` to perform the cleaning, but when it does not exist, it uses that agent name value (empty string) to delete the previously mentioned files deleting the diff folder.

## Proposed checks

- [x] Attempt to clean artifacts when the agent exists in the global database (nothing should be removed)
   - [x] Reproduce steps with Unfixed package
   - [x] Reproduce steps with Fixed package - Fresh install
   - [x] Reproduce steps with Fixed package - Upgrade
- [x] Attempt to clean artifacts when the agent is not present in the global database (artifacts should be removed without analysis errors and keeping the root diff folder intact)
   - [x] Reproduce steps with Unfixed package
   - [x] Reproduce steps with Fixed package - Fresh install
   - [x] Reproduce steps with Fixed package - Upgrade

## Steps to reproduce

The behavior was reproduced following 
- https://github.com/wazuh/wazuh/issues/13875#issue-1271084215
- https://github.com/wazuh/wazuh/issues/13875#issuecomment-1158081104

## Expected results

- Logs like the following are no longer displayed 
```
  2022/06/14 14:48:10 wazuh-analysisd: ERROR: (1107): Could not create directory 'queue/diff/ubuntu-bionic' due to [(2)-(No such file or directory)].
  2022/06/14 14:48:10 wazuh-analysisd: ERROR: Unable to create last file: queue/diff/ubuntu-bionic
  2022/06/14 14:48:10 wazuh-analysisd: ERROR: (1107): Could not create directory 'queue/diff/ubuntu-bionic' due to [(2)-(No such file or directory)].
  2022/06/14 14:48:10 wazuh-analysisd: ERROR: Unable to create last file: queue/diff/ubuntu-bionic
```
- The directory `/var/ossec/queue/diff` is not deleted when the module performs the artifacts cleaning.

**Comment by QU3B1M** [comment]
## Review data

| Tester | PR commit               | 
|--------|-------------------------|
| @QU3B1M   |  [1aa1966](https://github.com/wazuh/wazuh/pull/13892/commits/1aa19668fdb8fb662721f7130900ebae5e21fb364)   | 

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
|  Centos  | 8 | ` LOCAL \|  Vagrant` | [bento/centos-8](https://app.vagrantup.com/bento/boxes/centos-8) |       |
|  Ubuntu  | 20.04 | ` LOCAL \|  Vagrant` | [bento/ubuntu-20.04](https://app.vagrantup.com/bento/boxes/ubuntu-20.04) |       |


### Tested packages

| `wazuh-manager` | `wazuh-agent` | 
|-----------------|---------------|
| [rpm]() - [deb]() | [rpm]() - [deb]() |

### Status

- [x] In progress
- [ ] Pending Review
- [ ] Team leader approved
- [ ] Manager approved

**Comment by QU3B1M** [comment]
# Task results

<details><summary>Ubuntu - Unfixed - Attempt to clean artifacts when the agent exists in the global database :red_circle: </summary>

- Let the agent register for first time
    ```
    systemctl start wazuh-agent
    ```
    ```
    cat /var/ossec/logs/ossec.logs
    ...
    2022/08/31 13:30:45 wazuh-agentd: INFO: Started (pid: 33965).
    2022/08/31 13:30:45 wazuh-agentd: INFO: Using AES as encryption method.
    2022/08/31 13:30:45 wazuh-agentd: INFO: Trying to connect to server ([192.168.56.10]:1514/tcp).
    2022/08/31 13:30:45 wazuh-agentd: INFO: (4102): Connected to the server ([192.168.56.10]:1514/tcp).
    ...
    ```
- Stop Wazuh manager service
    ```
     systemctl stop wazuh-manager
    ```
- Delete entry in the manager global database for the agent
    ```
    slite3 /var/ossec/queue/db/global.db
    sqlite> delete from agent where name='ubuntu-test';
    ```
- Delete entry in client.keys for the agent
    ```
    rm -rf /var/ossec/etc/client.keys
    ```
- Start Wazuh manager service
    ```
    systemctl start wazuh-manager
    ```
    ```
    grep -E "ERR" /var/ossec/logs/ossec.log 
    2022/08/31 13:33:59 wazuh-analysisd[141722] dodiff.c:42 at _add2last(): ERROR: (1107): Could not create directory 'queue/diff/ubuntu-test' due to [(2)-(No such file or directory)].
    2022/08/31 13:33:59 wazuh-analysisd[141722] dodiff.c:113 at doDiff(): ERROR: Unable to create last file: queue/diff/ubuntu-test
    ```
</details>

<details><summary>Ubuntu - Fixed [fresh-install] - </summary>

**Comment by jmv74211** [comment]
🟢 Everything seems to be working properly.
