### ISSUE TITLE
FIM v2.0: Service tests

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh-qa#322]
|Implied teams|
|---|
| @wazuh/core , @wazuh/framework , @wazuh/cicd , @wazuh/devops |

The goal of service tests for FIM is to test all the implied components working together, as independent services (_syscheckd_, _analysisd_, and _wazuh-db_). These tests allow checking the whole flow of data from the files monitorization to the alert generation and database storage.

- Number of tests in scope: 4
- Number of tests ready: 0
- Number of pending tests: 4

_Current status:_ To be designed and developed.
_Coverage:_ 0%
_ETA:_
_Completion date:_ x/x/x

## Proposed use cases (draft)
 
- [ ] Generate a Syscheck event and check the corresponding alert appears. Daemons: _Syscheck, Analysisd_

- [ ] Check the table `fim_entry` is filled after the first scan. Daemons: _Syscheck, WazuhDB_

- [ ] Switch an agent between two nodes of the cluster. Check that the FIM database is synchronized.  _Daemons : Syscheck, WazuhDB, Agentd_

- [ ] Create a CDB list and create a rule to be triggered with a syscheck event: _Syscheck, Analysisd_

**Comment by chemamartinez** [comment]
Treated at other issues.
