### ISSUE TITLE
QA Planning: The "LookupAccountSid" error description improved 

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3226]
## Description

This problem aims to investigate [FIM: Error in LookupAccountSid](https://github.com/wazuh/wazuh/issues/14713) to define the test cases to be carried out.

# Development stage

- [x] Research the applied change.
- [x] Research if we have a test for this case.
- [ ] Define the test cases. Identify the base cases, and then the rest of the tests as tier 2.
- [ ] Define whether it is necessary to test systems, integration, or E2E. Create the corresponding issues.

**Comment by Deblintrake09** [comment]
# Task Results

## Research the applied change
The change is an enhancement of the error message that is displayed when the LookupAccountSid fails, now displaying what was the specific error message that was reported. It causes no changes to the current working behaviour of the FIM module. 

[Asked](https://wazuh-team.slack.com/archives/C019A838R6Y/p1662552648841919) core for Information on the Issue
