### ISSUE TITLE
QA planning: Vulnerability Detector refactor

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3233]
## Description

This problem aims to investigate [Vulnerability Detector refactor](https://github.com/wazuh/wazuh/issues/14153 ) to define the test cases to be carried out.

# Development stage

- [x] Research the applied change.
- [x] Research if we have a test for this case.
- [x] Identify if IT refactoring is required and in which of them.
- [x] Define the new test cases. 
- [x] Define whether it is necessary to test systems, integration, or E2E. Create the corresponding issues.

**Comment by BelenValdivia** [comment]
# Task results

<details><summary>Research the applied change.</summary>

This change applies a refactor in the Vulnerability Detector module. The objectives of this development are:

- Sanitize third-party vulnerabilities information and deliver it through the Wazuh Content model
- Reduce the Vulnerability Detector time-to-value by
   - Fetching Wazuh Content deltas if possible
   - Provide Wazuh Content baseline at installation time
- Improve UX by reducing Vulnerability Detector configuration options.
- Simplify vulnerability scan by removing current complexity handling from code to Wazuh Content generation step.
- Enhance the vulnerability scanner to avoid unnecessary scans by changing to an event-driven approach.
- Push Vulnerability detector results to Wazuh Indexer
</details>

<details><summary>Research if we have a test for this case.</summary>

We have test cases, but the behavior of the module changes completely
</details>

<details><summary>Define the test cases. Identify the base cases</summary>


Resultados de traducción
Integration test:
- Validate that no information is lost during formatting (compare downloaded feed and formatted feed)(one test for each vendor)
- Validate that the format is CVE 5 (not broken)
- Validate feed content
- Validate that if the feed is updated in the vendor, it is updated in the Wazuh content server (one test for each vendor)
- Validate that if the vendor page crashes, VD continues to work (one test for each vendor)

- Validate wazuh content download when the repository is online
- Validate wazuh content download when the repository is offline

- New scan in each new packages installed
- New scan in each updated package
- New scan on every package removed
- New scan in each hotfixes installed
- New scan on every hostfix removed.
- Validate that a new scan is done in each feed update
- Check that the scan result is in the database
   
</details>




</details>

<details><summary>Define whether it is necessary to test systems, integration, or E2E. Create the corresponding issues.</summary>
It's necessary create a system test with the following steps:
- Configure feed download.
- Configure VD in the manager.
- Configure an agent.
- Install a vulnerable package.
- Validate that the vulnerability appears in the alert.json and  in the indexer.

</details>
