### ISSUE TITLE
QA testing - Expand MSU supersedences in Vulnerability Detector

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh-qa#3234]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|            Current            |          https://github.com/wazuh/wazuh/issues/14523              |          https://github.com/wazuh/wazuh-tools/pull/193          |

## Description

Hi team,

The goal of this issue is to test the changes introduced at https://github.com/wazuh/wazuh-tools/pull/193 where fixed the correlation between MSU dependencies to avoid false positives during the Windows scans.

This issue has no target since the fix is applied to the MSU generation process, so once done a new MSU with the applied fix is uploaded to feed.wazuh.com.

## Proposed checks

- [ ] Diff both MSU (current and fixed) to ensure no data is lost and the format is correct.
- [ ] Scan a Windows agent with the current MSU and the fixed one to verify false positives are solved.

## Steps to reproduce
To speed up the testing process here is attached the current MSU at feed.wazuh.com, as well as the one with the fix applied.

**Current MSU**
[msu-updates.json.gz](https://github.com/wazuh/wazuh-qa/files/9470979/msu-updates.json.gz)
Downloaded from https://feed.wazuh.com/vulnerability-detector/windows/msu-updates.json.gz

**Fixed MSU**
[msu-updates-fixed.json.gz](https://github.com/wazuh/wazuh-qa/files/9471034/msu-updates-fixed.json.gz)

Here you can see the generated logs during the process of expanding the Windows patches.
[output.txt](https://github.com/wazuh/wazuh-qa/files/9471040/output.txt)

## Expected results

Both MSU feeds are properly indexed, the fixed one makes the false positives to be removed from the vulnerability report of the Windows agent.

## Configuration and considerations
To test a local MSU follow these steps:
- Stop the manager
- Remove the vulnerability database
```
# rm -f /var/ossec/queue/vulnerabilities/cve.db
```
- Store the MSU file in the host, for example at `/tmp/msu-updates.json.gz`
- Apply the following configuration
```xml
<!-- Windows OS vulnerabilities -->
<provider name="msu">
    <enabled>yes</enabled>
    <path>/tmp/msu-updates.json.gz</path>
    <update_interval>1h</update_interval>
</provider>
```
- Restart the manager and connect the Windows agent

**Comment by Rebits** [comment]
## Review data

| Tester | PR commit               |
|--------|-------------------------|
| @Rebits    |  [44de461576b5b1441599b04a163e587479fabf4e](https://github.com/wazuh/wazuh-tools/pull/193/commits)   |

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
| Ubuntu   |    22     | AWS |    ami-003530de8839921c4         |
| Windows Server    |    2022      | AWS |    ami-047e29beecff33db0         |

### Tested packages

| `wazuh-manager` | `wazuh-agent` | 
|-----------------|---------------|
|  4.3.7              | 4.3.7   |

### Status

- [x] In progress
- [ ] Pending Review
- [ ] Team leader approved
- [ ] Manager approved

**Comment by Rebits** [comment]
## Task results

<details>

<summary> Diff both MSU (current and fixed) to ensure no data is lost and the format is correct. :black_circle:   </summary>

</details>



<details>

<summary> 
Scan a Windows agent with the current MSU and the fixed one to verify false positives are solved. :black_circle: </summary>

</details>

**Comment by jmv74211** [comment]
🟢 Everything seems to be working properly
