### ISSUE TITLE
QA Planning: Wazuh-modulesd crashes on startup

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3241]
## Description

This problem aims to investigate [Wazuh-modulesd crashes on startup](https://github.com/wazuh/wazuh/issues/14018) to define the test cases to be carried out.

There is a bug in Wazuh 4.2.7. When Wazuh runs on a GCP VM, the Wazuh manager service is not starting.
This occurs in centOS7 with kernel 3.10.0-1160.66.1

# Development stage

- [x] Research the applied change.
- [ ] Research if we have a test for this case.
- [x] Define the test cases. Identify the base cases, and then the rest of the tests as tier 2.
- [ ] Define whether it is necessary to test systems, integration, or E2E. Create the corresponding issues.

**Comment by BelenValdivia** [comment]
# Task results

<details><summary>Research the applied change.</summary>
This change affects the process`modulesd`, it distribute the necessary libraries for compiled C++ projects, the reason for this is the associated issue, which is because of symbol interposition between two different versions of libstdc++.

There is a bug in Wazuh 4.2.7. When Wazuh runs on a GCP VM, the Wazuh manager service is not starting.
This occurs in centOS7 with kernel 3.10.0-1160.66.1.


</details>

<details><summary>Research if we have a test for this case.</summary>

Add system test for this case
</details>

<details><summary>Define the test cases. Identify the base cases, and then the rest of the tests as tier 2.</summary>

<details><summary>Test cases </summary>

- <details><summary>Fresh install Linux -Wazuh version 4.2.7- GCP VM and os-login enabled</summary> 

    1. Install wazuh-manager
    2.  The Wazuh manager service is not starting
    3.  Check services after starting Wazuh `./wazuh-control status`
    4. Check error in '/var/ossec/bin/wazuh-modulesd': free(): invalid pointer: 0x00007f90f716ac80 ***
    5. Check error wm_sca:1840: at wm_sca_pattern_matches() -> aborted
    6.  Deactivate syscollector and check Wazuh works correctly
    </details>


- <details><summary>Fresh install Linux - Core branch with fix - GCP VM and os-login enabled</summary>

    1. Install wazuh-manager 
    2.  The Wazuh manager service is starting
    3. Check services after starting Wazuh `./wazuh-control status`
    4. No errors in '/var/ossec/bin/wazuh-modulesd': free(): invalid pointer: 0x00007f90f716ac80 ***
    5. No error wm_sca:1840: at wm_sca_pattern_matches() -> aborted
    6. Vulnerability detector module works correctly
    7. Check that binaries are loading the libraries with `ldd`

    </details>


- <details><summary>Fresh install Windows - Wazuh version 4.2.7</summary>

    1. Install  wazuh-agent
    2. Check that binaries are not loading the libraries
   
    </details>

- <details><summary>Fresh install Windows- Core branch fix  </summary> 

    1.  Install  wazuh-agent
    2. Check that binaries are loading the libraries with https://hshrzd.wordpress.com/pe-bear/ 
     
    </details>
</details>


   

<details><summary>Define whether it is necessary to test systems, integration, or E2E. Create the corresponding issues.</summary>

</details>
