### ISSUE TITLE
QA testing - Wazuh-modulesd crashes on startup

### ISSUE THREAD

**Issue by BelenValdivia** [wazuh/wazuh-qa#3255]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|     4.4                   |    https://github.com/wazuh/wazuh/issues/14018                    |         https://github.com/wazuh/wazuh/pull/14190           |

## Description
This change affects the process **modulesd** , it distribute the necessary libraries for compiled C++ projects, because of symbol interposition between two different versions of libstdc++.
There is a bug in Wazuh 4.2.7. When Wazuh runs on a GCP VM, the Wazuh manager service is not starting.
This occurs in centOS7 with kernel 3.10.0-1160.66.1.

### Test cases

- [x] Fresh install - Linux -Wazuh version 4.2.7- GCP VM and os-login enabled
    - <details><summary> Steps</summary> 
    
        1. Install wazuh-manager
        2.  The Wazuh manager service is not starting
        3.  Check services after starting Wazuh `./wazuh-control status`. Modulesd not started
        4. Check errors in '/var/ossec/bin/wazuh-modulesd'
        5. Check errors in ossec log
        6. Check package and installation folder sizes
        </details>

- [x] Fresh install - Linux - Core branch with fix - GCP VM and os-login enabled
    - <details><summary>Steps</summary>
    
        1. Install wazuh-manager 
        2.  The Wazuh manager service is starting
        3. Check services after starting Wazuh `./wazuh-control status`. Modulesd started
        4. No errors in '/var/ossec/bin/wazuh-modulesd'
        5. No errors in ossec log
        6. Vulnerability detector module works correctly
        7. Check that binaries are loading the libraries with `ldd`. Should be: 
              - libstdc++.so.6
              - libgcc_s.so.1
        8. Check size between packages and installation folder
        9. Check size libraries dbsync+sysinfo+syscollector+rsync+libstdc++ with changes 
        10. Check size libraries dbsync+sysinfo+syscollector+rsync+libstdc++ without changes (Wazuh 4.4)

    </details>

- [x] Upgrade Linux from 4.2.7 to Core branch with fix - GCP VM and os-login enabled

    - <details><summary>Steps</summary>
    
        1. Upgrade wazuh-manager 
        2.  The Wazuh manager service is starting
        3. Check services after starting Wazuh `./wazuh-control status`. Modulesd started
        4. No errors in '/var/ossec/bin/wazuh-modulesd'
        5. No error in ossec log
        6. Vulnerability detector module works correctly
        7. Check that binaries are loading the libraries with `ldd`
        8.  Check size between packages and installation folder

    </details>

- [x] Upgrade Windows from 4.2.7 to Core branch with fix - GCP VM and os-login enabled
     - <details><summary>Steps </summary> 
        
          1.  Upgrade wazuh-agent
          2. Check that binaries are loading the libraries with https://hshrzd.wordpress.com/pe-bear/ 
             -  libstdc++-6.dll
             - libgcc_s_dw2-1.dll
          3. Check size between packages and installation folder
             
        </details>

- [x] Fresh install Windows- Core branch fix 
    - <details><summary>Steps  </summary> 
    
        1.  Install  wazuh-agent
        2. Check that binaries are loading the libraries with https://hshrzd.wordpress.com/pe-bear/ 
            - libstdc++-6.dll
            - libgcc_s_dw2-1.dll
        3. Check each dll with https://processhacker.sourceforge.io/
        4. Check size between packages and installation folder
        5. Check syscollector is working correctly
        6. Check size libraries dbsync+sysinfo+syscollector+rsync+libstdc++ with changes
        7. Check size libraries dbsync+sysinfo+syscollector+rsync+libstdc++ without changes (Wazuh 4.4)
         
        </details>

- [x] Fresh install Linux with 32bit package
    - <details><summary>Steps  </summary> 
    
         1.  Check vulnerability detector works correctly
         2.  Check syscollector works correctly
      
        </details>

</details>

**Comment by BelenValdivia** [comment]
## T1:  Fresh install - Linux -Wazuh version 4.2.7- GCP VM and os-login enabled

1- Wazuh server not started 
![image](https://user-images.githubusercontent.com/26927338/188909859-5b13f255-8cce-4761-a9bf-2492148f2e30.png)

2- Modulesd not running
![image](https://user-images.githubusercontent.com/26927338/188910002-0383a155-85dc-4ed7-b315-25b028d72aea.png)

3- Errors ossec.log
![image](https://user-images.githubusercontent.com/26927338/188914943-5b923b45-5442-4b12-8ff5-99dd6ee6ebc4.png)

**Comment by BelenValdivia** [comment]
T2- Fresh install - Linux - Core branch with fix - GCP VM and os-login enabled (WIP)
 

<details><summary>Check libraries:</summary>

 -  `ldd /var/ossec/lib/libsysinfo.so`
 
```
 [root@instance-1 belen_valdivia_wazuh_com]# ldd /var/ossec/lib/libsysinfo.so
        linux-vdso.so.1 =>  (0x00007ffd36dfe000)
        libwazuhext.so => /var/ossec/lib/libwazuhext.so (0x00007fbaf7938000)
        libstdc++.so.6 => /var/ossec/lib/libstdc++.so.6 (0x00007fbaf754a000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fbaf7248000)
        libgcc_s.so.1 => /var/ossec/lib/libgcc_s.so.1 (0x00007fbaf7031000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fbaf6c63000)
        librt.so.1 => /lib64/librt.so.1 (0x00007fbaf6a5b000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fbaf6857000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fbaf663b000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fbaf86da000)
 
```

-  `ldd /var/ossec/lib/libdbsync.so`

```
root@instance-1 belen_valdivia_wazuh_com]# ldd /var/ossec/lib/libdbsync.so 
        linux-vdso.so.1 =>  (0x00007ffcef552000)
        libwazuhext.so => /var/ossec/lib/libwazuhext.so (0x00007f6a8a37e000)
        libstdc++.so.6 => /var/ossec/lib/libstdc++.so.6 (0x00007f6a89f90000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f6a89c8e000)
        libgcc_s.so.1 => /var/ossec/lib/libgcc_s.so.1 (0x00007f6a89a77000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f6a8985b000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f6a8948d000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f6a89285000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f6a890810
```

- `ldd /var/ossec/lib/libsyscollector.so`

```
[root@instance-1 belen_valdivia_wazuh_com]# ldd /var/ossec/lib/libsyscollector.so
        linux-vdso.so.1 =>  (0x00007ffc02bbb000)
        libdbsync.so => /var/ossec/lib/libdbsync.so (0x00007f4c8b19c000)
        librsync.so => /var/ossec/lib/librsync.so (0x00007f4c8af51000)
        libsysinfo.so => /var/ossec/lib/libsysinfo.so (0x00007f4c8acd0000)
        libwazuhext.so => /var/ossec/lib/libwazuhext.so (0x00007f4c8a1af000)
        libstdc++.so.6 => /var/ossec/lib/libstdc++.so.6 (0x00007f4c89dc1000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f4c89abf000)
        libgcc_s.so.1 => /var/ossec/lib/libgcc_s.so.1 (0x00007f4c898a8000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f4c8968c000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f4c892be000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f4c8b686000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f4c890b6000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f4c88eb2000)
```

- 
</details>

**Comment by BelenValdivia** [comment]
## T3- Upgrade Linux from 4.2.7 to Core branch with fix - GCP VM and os-login enabled (WIP)
 
<details><summary>Wazuh server started 🟢 </summary>

```
● wazuh-manager.service - Wazuh manager
   Loaded: loaded (/usr/lib/systemd/system/wazuh-manager.service; disabled; vendor preset: disabled)
   Active: active (exited) since Thu 2022-09-08 17:33:08 UTC; 4s ago
  Process: 5522 ExecStart=/usr/bin/env /var/ossec/bin/wazuh-control start (code=exited, status=0/SUCCESS)

Sep 08 17:33:06 instance-1 env[5522]: wazuh-db already running...
Sep 08 17:33:06 instance-1 env[5522]: wazuh-execd already running...
Sep 08 17:33:06 instance-1 env[5522]: wazuh-analysisd already running...
Sep 08 17:33:06 instance-1 env[5522]: wazuh-syscheckd already running...
Sep 08 17:33:06 instance-1 env[5522]: wazuh-remoted already running...
Sep 08 17:33:06 instance-1 env[5522]: wazuh-logcollector already running...
Sep 08 17:33:06 instance-1 env[5522]: wazuh-monitord already running...
Sep 08 17:33:06 instance-1 env[5522]: wazuh-modulesd already running...
Sep 08 17:33:08 instance-1 env[5522]: Completed.
Sep 08 17:33:08 instance-1 systemd[1]: Started Wazuh manager.
```

</details>

<details><summary>Modulesd status running 🟢 </summary>

```
[root@instance-1 belen_valdivia_wazuh_com]# /var/ossec/bin/wazuh-control status
wazuh-clusterd not running...
wazuh-modulesd is running...
wazuh-monitord is running...
wazuh-logcollector is running...
wazuh-remoted is running...
wazuh-syscheckd is running...
wazuh-analysisd is running...
wazuh-maild not running...
wazuh-execd is running...
wazuh-db is running...
wazuh-authd is running...
wazuh-agentlessd not running...
wazuh-integratord not running...
wazuh-dbd not running...
wazuh-csyslogd not running...
wazuh-apid is running...

```


</details>

<details><summary>Check libraries 🟢  </summary>

 -  `ldd /var/ossec/lib/libsysinfo.so`
 
```
[root@instance-1 belen_valdivia_wazuh_com]# ldd /var/ossec/lib/libsysinfo.so
        linux-vdso.so.1 =>  (0x00007fff95bfe000)
        libwazuhext.so => /var/ossec/lib/libwazuhext.so (0x00007f0536c40000)
        libstdc++.so.6 => /var/ossec/lib/libstdc++.so.6 (0x00007f0536852000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f0536550000)
        libgcc_s.so.1 => /var/ossec/lib/libgcc_s.so.1 (0x00007f0536339000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f0535f6b000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f0535d63000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f0535b5f000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f0535943000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f05379e2000)
 
```

-  `ldd /var/ossec/lib/libdbsync.so`

```
[root@instance-1 belen_valdivia_wazuh_com]# ldd /var/ossec/lib/libdbsync.so
        linux-vdso.so.1 =>  (0x00007ffc03e2e000)
        libwazuhext.so => /var/ossec/lib/libwazuhext.so (0x00007f113a8dd000)
        libstdc++.so.6 => /var/ossec/lib/libstdc++.so.6 (0x00007f113a4ef000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f113a1ed000)
        libgcc_s.so.1 => /var/ossec/lib/libgcc_s.so.1 (0x00007f1139fd6000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f1139dba000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f11399ec000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f11397e4000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f11395e0000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f113b671000)
```

- `ldd /var/ossec/lib/libsyscollector.so`

```
[root@instance-1 belen_valdivia_wazuh_com]# ldd /var/ossec/lib/libsyscollector.so
        linux-vdso.so.1 =>  (0x00007ffc720b8000)
        libdbsync.so => /var/ossec/lib/libdbsync.so (0x00007f96a4186000)
        librsync.so => /var/ossec/lib/librsync.so (0x00007f96a3f3b000)
        libsysinfo.so => /var/ossec/lib/libsysinfo.so (0x00007f96a3cba000)
        libwazuhext.so => /var/ossec/lib/libwazuhext.so (0x00007f96a3199000)
        libstdc++.so.6 => /var/ossec/lib/libstdc++.so.6 (0x00007f96a2dab000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f96a2aa9000)
        libgcc_s.so.1 => /var/ossec/lib/libgcc_s.so.1 (0x00007f96a2892000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f96a2676000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f96a22a8000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f96a4670000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f96a20a0000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f96a1e9c000)
```

-  `ldd /var/ossec/bin/wazuh-modulesd`

```
[root@instance-1 belen_valdivia_wazuh_com]# ldd /var/ossec/bin/wazuh-modulesd
        linux-vdso.so.1 =>  (0x00007ffcd2fba000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f0451237000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f0451033000)
        libwazuhext.so => /var/ossec/bin/../lib/libwazuhext.so (0x00007f0450512000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f0450210000)
        libjemalloc.so.2 => /var/ossec/bin/../lib/libjemalloc.so.2 (0x00007f044fd6c000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f044fb50000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f044f782000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f045143f000)
```
</details>

<details><summary>No log errors 🟢 </summary>

- ` /var/ossec/bin/wazuh-modulesd `
```
[root@instance-1 belen_valdivia_wazuh_com]# /var/ossec/bin/wazuh-modulesd 
[root@instance-1 belen_valdivia_wazuh_com]# 
```
-  `cat /var/ossec/logs/ossec.log `

```
2022/09/08 17:36:47 wazuh-modulesd: INFO: Started (pid: 5737).
2022/09/08 17:36:47 wazuh-modulesd:agent-upgrade: INFO: (8153): Module Agent Upgrade started.
2022/09/08 17:36:47 wazuh-modulesd:ciscat: INFO: Module disabled. Exiting...
2022/09/08 17:36:47 wazuh-modulesd:osquery: INFO: Module disabled. Exiting...
2022/09/08 17:36:47 wazuh-modulesd:task-manager: INFO: (8200): Module Task Manager started.
2022/09/08 17:36:47 sca: INFO: Module started.
2022/09/08 17:36:47 sca: INFO: Loaded policy '/var/ossec/ruleset/sca/cis_centos7_linux.yml'
2022/09/08 17:36:47 wazuh-modulesd:database: INFO: Module started
2022/09/08 17:36:47 wazuh-modulesd:control: INFO: Starting control thread.
2022/09/08 17:36:47 wazuh-modulesd:download: INFO: Module started.
2022/09/08 17:36:47 sca: INFO: Starting Security Configuration Assessment scan.
2022/09/08 17:36:47 wazuh-modulesd:syscollector: INFO: Module started.
2022/09/08 17:36:47 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2022/09/08 17:36:47 sca: INFO: Starting evaluation of policy: '/var/ossec/ruleset/sca/cis_centos7_linux.yml'
2022/09/08 17:36:47 wazuh-modulesd:syscollector: INFO: Evaluation finished.
```

</details>

<details><summary>Vulnerability detector module works correctly 🟢 </summary>

- Scan done
2022/09/08 17:56:18 wazuh-modulesd:vulnerability-detector: INFO: (5400): Starting 'Red Hat Enterprise Linux 5' database update.
2022/09/08 17:56:18 wazuh-modulesd:syscollector: INFO: Module started.
2022/09/08 17:56:18 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2022/09/08 17:56:19 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2022/09/08 17:56:21 wazuh-modulesd:vulnerability-detector: INFO: (5430): The update of the 'Red Hat Enterprise Linux 5' feed finished successfully.
2022/09/08 17:56:21 wazuh-modulesd:vulnerability-detector: INFO: (5400): Starting 'Red Hat Enterprise Linux 6' database update.
2022/09/08 17:56:26 wazuh-modulesd:vulnerability-detector: INFO: (5430): The update of the 'Red Hat Enterprise Linux 6' feed finished successfully.
2022/09/08 17:56:26 wazuh-modulesd:vulnerability-detector: INFO: (5400): Starting 'Red Hat Enterprise Linux 7' database update.
2022/09/08 17:56:33 wazuh-modulesd:vulnerability-detector: INFO: (5430): The update of the 'Red Hat Enterprise Linux 7' feed finished successfully.
2022/09/08 17:56:33 wazuh-modulesd:vulnerability-detector: INFO: (5400): Starting 'National Vulnerability Database' database update.
2022/09/08 17:56:45 wazuh-syscheckd: INFO: (6009): File integrity monitoring scan ended.
2022/09/08 17:57:17 sca: INFO: Evaluation finished for policy '/var/ossec/ruleset/sca/cis_centos7_linux.yml'
2022/09/08 17:57:17 sca: INFO: Security Configuration Assessment scan finished. Duration: 59 seconds.
2022/09/08 17:57:45 rootcheck: INFO: Ending rootcheck scan.
2022/09/08 18:01:50 wazuh-modulesd:vulnerability-detector: INFO: (5430): The update of the 'National Vulnerability Database' feed finished successfully.
2022/09/08 18:01:50 wazuh-modulesd:vulnerability-detector: INFO: (5400): Starting 'Microsoft Security Update' database update.
2022/09/08 18:01:56 wazuh-modulesd:vulnerability-detector: INFO: (5430): The update of the 'Microsoft Security Update' feed finished successfully.
2022/09/08 18:01:56 wazuh-modulesd:vulnerability-detector: INFO: (5431): Starting vulnerability scan.
2022/09/08 18:01:56 wazuh-modulesd:vulnerability-detector: INFO: (5450): Analyzing agent '000' vulnerabilities.

- Alerts in `/var/ossec/logs/alerts/alerts.log`


</details>

**Comment by BelenValdivia** [comment]
T4: Upgrade Windows from 4.2.7 to Core branch with fix - GCP VM and os-login enabled

**Comment by BelenValdivia** [comment]
T5: Fresh install Windows- Core branch fix

**Comment by BelenValdivia** [comment]
Check size libraries dbsync+sysinfo+syscollector+rsync without changes (Wazuh 4.4)

```
[root@centos7 lib]# ls -lh
total 17M
-rwxr-x---. 1 root wazuh 1.9M Sep 12 13:11 libdbsync.so
-rwxr-x---. 1 root wazuh 331K Sep 12 13:11 librsync.so
-rwxr-x---. 1 root wazuh 499K Sep 12 13:11 libsyscollector.so
-rwxr-x---. 1 root wazuh 1.9M Sep 12 13:11 libsysinfo.so
```
`Total size: 4.63 M`

**Comment by BelenValdivia** [comment]
## Review data

| Tester | PR commit               | 
|--------|-------------------------|
| @BelenValdivia    |  937a9cd9d930680f2c91af0fc29cd5613637e3b6  | 

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
|  CentOS  | 7 | ` Google Cloud` | [CentOS 7 provided by GCC](https://console.cloud.google.com/compute/instancesAdd?project=wazuh-dev-258815)

### Tested packages

Packages with changes:
| `wazuh-manager` | `wazuh-agent` | 
|-----------------|---------------|
|  [rpm](https://packages-dev.wazuh.com/warehouse/test/4.4/rpm/var/wazuh-manager-4.4.0-12.09.0.modulescrash.x86_64.rpm)  | [rpm-64bit](https://packages-dev.wazuh.com/warehouse/test/4.4/rpm/var/wazuh-agent-4.4.0-12.09.0.modulescrash.x86_64.rpm) [rpm-32bit](https://packages-dev.wazuh.com/warehouse/test/4.4/rpm/var/wazuh-agent-4.4.0-12.09.0.modulescrash.i386.rpm)  [windows](https://packages-dev.wazuh.com/warehouse/test/4.4/windows/wazuh-agent-4.4.0-07.09.0.modulesdcrash.msi)| 

Packages without changes:
| `wazuh-manager` | `wazuh-agent` | 
|-----------------|---------------|
|  [rpm](https://packages-dev.wazuh.com/warehouse/test/4.4/rpm/var/wazuh-manager-4.4.0-12.09.0.withoutmodulesdcrach.x86_64.rpm)  | [rpm](https://packages-dev.wazuh.com/warehouse/test/4.4/rpm/var/wazuh-agent-4.4.0-12.09.0.withoutmodulesdcrach.x86_64.rpm) [ windows](https://packages-dev.wazuh.com/warehouse/test/4.4/windows/wazuh-agent-4.4.0-12.09.0.withoutmodulesdcrash.msi) | 

### Status

- [x] In progress
- [ ] Pending Review
- [ ] Team leader approved
- [ ] Manager approved

### Conclusion

**Comment by BelenValdivia** [comment]
# Task results

##  Fresh install - Linux -Wazuh version 4.2.7- GCP VM and os-login enabled 🟢 

<details><summary>Wazuh server not started 🟢 </summary>

```
[root@instance-1 belen_valdivia_wazuh_com]# systemctl status wazuh-manager
● wazuh-manager.service - Wazuh manager
   Loaded: loaded (/usr/lib/systemd/system/wazuh-manager.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2022-09-07 20:26:32 UTC; 10min ago
  Process: 1807 ExecStart=/usr/bin/env /var/ossec/bin/wazuh-control start (code=exited, status=1/FAILURE)
   CGroup: /system.slice/wazuh-manager.service
           ├─1904 /var/ossec/bin/wazuh-authd
           ├─1921 /var/ossec/bin/wazuh-db
           ├─1946 /var/ossec/bin/wazuh-execd
           ├─1960 /var/ossec/bin/wazuh-analysisd
           ├─2004 /var/ossec/bin/wazuh-syscheckd
           ├─2020 /var/ossec/bin/wazuh-remoted
           ├─2053 /var/ossec/bin/wazuh-logcollector
           ├─2073 /var/ossec/bin/wazuh-monitord
           └─2523 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py

Sep 07 20:26:18 instance-1 env[1807]: Started wazuh-syscheckd...
Sep 07 20:26:19 instance-1 env[1807]: Started wazuh-remoted...
Sep 07 20:26:20 instance-1 env[1807]: Started wazuh-logcollector...
Sep 07 20:26:21 instance-1 env[1807]: Started wazuh-monitord...
Sep 07 20:26:23 instance-1 env[1807]: wazuh-modulesd: Process 2095 not used by Wazuh, removing...
Sep 07 20:26:32 instance-1 env[1807]: wazuh-modulesd did not start correctly.
Sep 07 20:26:32 instance-1 systemd[1]: wazuh-manager.service: control process exited, code=exited status=1
Sep 07 20:26:32 instance-1 systemd[1]: Failed to start Wazuh manager.
Sep 07 20:26:32 instance-1 systemd[1]: Unit wazuh-manager.service entered failed state.
Sep 07 20:26:32 instance-1 systemd[1]: wazuh-manager.service failed.
```


</details>

<details><summary>Modulesd not running 🟢 </summary>

```
[root@instance-1 belen_valdivia_wazuh_com]# /var/ossec/bin/wazuh-control status
wazuh-clusterd not running...
wazuh-modulesd not running...
wazuh-monitord is running...
wazuh-logcollector is running...
wazuh-remoted is running...
wazuh-syscheckd is running...
wazuh-analysisd is running...
wazuh-maild not running...
wazuh-execd is running...
wazuh-db is running...
wazuh-authd is running...
wazuh-agentlessd not running...
wazuh-integratord not running...
wazuh-dbd not running...
wazuh-csyslogd not running...
wazuh-apid not running...
```


</details>

<details><summary>Log errors 🟢 </summary>

![image](https://user-images.githubusercontent.com/26927338/188914943-5b923b45-5442-4b12-8ff5-99dd6ee6ebc4.png)
</details>

<details><summary>Check package and installation folder sizes 🟢 </summary>

- Package `4.2.7`:

```
[root@instance-1 belen_valdivia_wazuh_com]# ls -lh wazuh-manager-4.2.7-1.x86_64.rpm 
-rw-r--r--. 1 root root 112M Sep  8 17:15 wazuh-manager-4.2.7-1.x86_64.rpm
```

- Installation folder `4.2.7`:

```
[root@instance-1 belen_valdivia_wazuh_com]# du -sh /var/ossec/
466M    /var/ossec/
```

</details>

**Comment by jmv74211** [comment]
🟢 Everything seems to be working properly
