### ISSUE TITLE
Test deprecated force_insert authd option

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#3262]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|     4.5.0       | https://github.com/wazuh/wazuh/issues/14137     |   https://github.com/wazuh/wazuh/pull/14549   |

# Description
This change adds a Warning message when the `force_insert` and `force_time` options are used in the authd section of the manager's configuration.  This testing will be done to check the message does not appear when `force_insert` is disabled and that the functionality works as expected.

When enabled, the following messages will be displayed on the manager's ossec.log:
```
2022/08/17 14:10:37 wazuh-authd: WARNING: The <force_insert> tag is deprecated. Use <force> instead.
2022/08/17 14:10:37 wazuh-authd: WARNING: The <force_time> tag is deprecated. Use <force> instead.
```

# Proposed checks

## Testing on 4.3.8

   - [x] Check that `force_insert` and `force_time` are working when enabled
      <details> <summary>Steps to reproduce</summary>
      
      - Configure `force_insert` = yes and `force_time` = 0
      - Start Manager
      - Connect agent without registering it
      - Wait for agent registration and check that agent is connected with `agent_control -l`
      - Remove the agent and reinstall it without removing it from the manager
      - Start the new agent and check that it cannot register and the following message appears
      ```
      2022/09/06 19:32:24 wazuh-authd: WARNING: Duplicate name 'agent-name, rejecting enrollment. Agent '001' has not been disconnected long enough to be replaced.
      ```
      
      **NOTE: ** On dev branch this is tested using IT's on Issue #3374 
      </details>

## Testing on Fixed Branch (Upgrade from 4.3.8 + Fresh Install )

   - [x] Check that new force option overrides force_insert (`force_insert` enabled and `force` disabled)
   - [x] Check that disconnect_time override force_time option
   - [x] Check force_insert invalid value (number) 
   - [x] Check force_insert invalid value (String)
   - [x] Check force_insert invalid value (Empty)
   - [x] Check force_time invalid value (string)
   - [x] Check force_time invalid value (empty)
   - [x] Check force_time = 0 
   - [x] Check force_time = 10 
   - [x] Check force_time = 10 and add key_mismatch = no 
   - [x] Check force_time = 10 and add key_mismatch = no after_registration_time = 0 
   - [x] Check force_time = 10 and add key_mismatch = yes after_registration_time = 0 
   - [x] Check force_time = 10 and add key_mismatch = yes

## Steps to reproduce

1. Configure Manager
2. Start Manager
3. Register Agent with `agent_auth`
4. Try to register agent again with same name
5. Check if agent was removed or not

**Comment by Deblintrake09** [comment]
## Review data

| Tester | PR commit               |
|--------|-------------------------|
| @Deblintrake09     |  [9ed9dd5](https://github.com/wazuh/wazuh/commit/9ed9dd5428905a3d2bd88519b528d95f6564aee3)  |

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
| Centos   |    8     | LOCAL / Vagrant |    qa-ctl/centos_8         |

### Tested packages

| `wazuh-manager` | `wazuh-agent` | 
|-----------------|---------------|
|  [4.5.0](https://packages-dev.wazuh.com/warehouse/test/4.5/rpm/var/wazuh-manager-4.5.0-3232.force.insert.rework.x86_64.rpm)              |    |

### Status

- [x] In progress
- [ ] Pending Review
- [ ] Team leader approved
- [ ] Manager approved

**Comment by Deblintrake09** [comment]
# Task results

## Upgrade Install

<details>
<summary>Check new force options work over force_insert :green_circle: </summary>

- Configure manager
```xml
    <force_insert>yes</force_insert>
    <force_time>0</force_time>
    <force>
      <enabled>no</enabled>
      <disconnected_time enabled="yes">1m</disconnected_time>
      <after_registration_time>2m</after_registration_time>
      <key_mismatch>yes</key_mismatch>
    </force>
```
- Start Manager and check logs
```
[root@c3 vagrant]# /var/ossec/bin/wazuh-control start
2022/09/23 15:40:49 wazuh-authd: WARNING: The <force_insert> tag is deprecated. Use <force> instead.
2022/09/23 15:40:49 wazuh-authd: WARNING: The <force_time> tag is deprecated. Use <force> instead.
wazuh-clusterd started...
```
- Register the agent
- Try to enroll agent again
```
# /var/ossec/bin/agent-auth -m 10.0.10.2 -A Agent1
2022/09/23 16:01:02 agent-auth: INFO: Started (pid: 4171).
2022/09/23 16:01:02 agent-auth: INFO: Requesting a key from server: 10.0.10.2
2022/09/23 16:01:02 agent-auth: INFO: No authentication password provided
2022/09/23 16:01:02 agent-auth: INFO: Using agent name as: Agent1
2022/09/23 16:01:02 agent-auth: INFO: Waiting for server reply
2022/09/23 16:01:02 agent-auth: ERROR: Duplicate agent name: Agent1 (from manager)
2022/09/23 16:01:02 agent-auth: ERROR: Unable to add agent (from manager)
```
- Check the manager's log
```
# cat /var/ossec/logs/ossec.log
2022/09/23 16:01:01 wazuh-authd[5716] auth.c:104 at w_auth_parse_data(): INFO: Received request for a new agent (Agent1) from: 10.0.10.1
2022/09/23 16:01:01 wazuh-authd[5716] auth.c:315 at w_auth_validate_data(): WARNING: Duplicate name 'Agent1', rejecting enrollment. Agent '001' won't be removed because the force option is disabled.
```
</details>


<details>
<summary>Check that disconnected_time works over force_time :green_circle: </summary>

- Configure manager
```xml
    <force_insert>yes</force_insert>
    <force_time>0</force_time>
    <force>
      <enabled>yes</enabled>
      <disconnected_time enabled="yes">1m</disconnected_time>
      <after_registration_time>2m</after_registration_time>
      <key_mismatch>no</key_mismatch>
    </force>
```
- Start Manager
- Try to enroll agent again while connected and check the logs
```
2022/09/23 16:09:12 wazuh-authd[6233] auth.c:104 at w_auth_parse_data(): INFO: Received request for a new agent (Agent1) from: 10.0.10.1
2022/09/23 16:09:12 wazuh-authd[6233] auth.c:315 at w_auth_validate_data(): WARNING: Duplicate name 'Agent1', rejecting enrollment. Agent '001' can't be replaced since it is not disconnected.
```
- Stop the agent and try to re-enroll
```
# /var/ossec/bin/wazuh-control stop
Killing wazuh-modulesd... 
Killing wazuh-logcollector... 
Killing wazuh-syscheckd... 
Killing wazuh-agentd... 
Killing wazuh-execd... 
Wazuh v4.3.8 Stopped

# /var/ossec/bin/agent-auth -m 10.0.10.2 -A Agent1
2022/09/23 16:09:39 agent-auth: INFO: Started (pid: 5341).
2022/09/23 16:09:39 agent-auth: INFO: Requesting a key from server: 10.0.10.2
2022/09/23 16:09:39 agent-auth: INFO: No authentication password provided
2022/09/23 16:09:39 agent-auth: INFO: Using agent name as: Agent1
2022/09/23 16:09:39 agent-auth: INFO: Waiting for server reply
2022/09/23 16:09:39 agent-auth: ERROR: Duplicate agent name: Agent1 (from manager)
2022/09/23 16:09:39 agent-auth: ERROR: Unable to add agent (from manager)
```
- Check the manager's log
```
2022/09/23 16:09:39 wazuh-authd[6233] auth.c:104 at w_auth_parse_data(): INFO: Received request for a new agent (Agent1) from: 10.0.10.1
2022/09/23 16:09:39 wazuh-authd[6233] auth.c:315 at w_auth_validate_data(): WARNING: Duplicate name 'Agent1', rejecting enrollment. Agent '001' has not been disconnected long enough to be replaced.
```
- Wait for more than 1m to re-enroll
```
2022/09/23 16:12:50 wazuh-authd[6870] main-server.c:578 at run_dispatcher(): INFO: New connection from 10.0.10.1
2022/09/23 16:12:50 wazuh-authd[6870] main-server.c:621 at run_dispatcher(): DEBUG: Request received: <OSSEC A:'Agent1' K:'f5e3e42477ba384fc96a325e3fe3f0881d80ae59'
>
2022/09/23 16:12:50 wazuh-authd[6870] auth.c:104 at w_auth_parse_data(): INFO: Received request for a new agent (Agent1) from: 10.0.10.1
2022/09/23 16:12:50 wazuh-authd[6870] auth.c:313 at w_auth_validate_data(): INFO: Duplicate name. Removing old agent 'Agent1' (id '001').
2022/09/23 16:12:50 wazuh-authd[6870] main-server.c:651 at run_dispatcher(): INFO: Agent key generated for 'Agent1' (requested by any)
2022/09/23 16:12:50 wazuh-authd[6870] main-server.c:828 at run_writer(): DEBUG: Dumping changes into disk.
2022/09/23 16:12:50 wazuh-authd[6870] main-server.c:850 at run_writer(): DEBUG: [Writer] OS_WriteKeys(): 139 µs.
2022/09/23 16:12:50 wazuh-authd[6870] main-server.c:860 at run_writer(): DEBUG: [Writer] OS_WriteTimestamps(): 58 µs.
2022/09/23 16:12:50 wazuh-authd[6870] main-server.c:868 at run_writer(): DEBUG: [Writer] Performing insert([002] Agent1).
2022/09/23 16:12:50 wazuh-authd[6870] main-server.c:875 at run_writer(): DEBUG: [Writer] wdb_insert_agent(): 417 µs.
2022/09/23 16:12:50 wazuh-authd[6870] main-server.c:890 at run_writer(): DEBUG: [Writer] wdb_set_agent_groups_csv(): 0 µs.
2022/09/23 16:12:50 wazuh-authd[6870] main-server.c:907 at run_writer(): DEBUG: [Writer] Performing delete([001] Agent1).
2022/09/23 16:12:50 wazuh-authd[6870] main-server.c:912 at run_writer(): DEBUG: [Writer] delete_agentinfo(): 200 µs.
2022/09/23 16:12:50 wazuh-authd[6870] main-server.c:917 at run_writer(): DEBUG: [Writer] OS_RemoveCounter(): 36 µs.
2022/09/23 16:12:50 wazuh-authd[6870] main-server.c:922 at run_writer(): DEBUG: [Writer] OS_RemoveAgentTimestamp(): 79 µs.
2022/09/23 16:12:50 wazuh-authd[6870] main-server.c:929 at run_writer(): DEBUG: [Writer] wdb_remove_agent(): 242 µs.
2022/09/23 16:12:50 wazuh-authd[6870] main-server.c:935 at run_writer(): DEBUG: [Writer] wdbc_query_ex(): 335 µs.
2022/09/23 16:12:50 wazuh-authd[6870] main-server.c:948 at run_writer(): DEBUG: [Writer] Inserted agents: 1
2022/09/23 16:12:50 wazuh-authd[6870] main-server.c:949 at run_writer(): DEBUG: [Writer] Removed agents: 1
2022/09/23 16:12:50 wazuh-authd[6870] main-server.c:950 at run_writer(): DEBUG: [Writer] Loop: 1 ms.
```
</details>




<details>
<summary></summary>

- Configure manager
```xml
    <force_insert>yes</force_insert>
    <force_time>0</force_time>
    <force>
      <enabled>no</enabled>
      <disconnected_time enabled="yes">1m</disconnected_time>
      <after_registration_time>2m</after_registration_time>
      <key_mismatch>yes</key_mismatch>
    </force>
```
- Start Manager

</details>

**Comment by Deblintrake09** [comment]
# Task Round 2

After the requested changes to Core about further logs reporting the manager's configuration, the following messages where added:

```
2022/10/20 11:25:17 wazuh-authd[2982] authd-config.c:249 at Read_Authd(): DEBUG: The tag <force><after_registration_time> is not defined. Applied default value: '3600'
2022/10/20 11:25:17 wazuh-authd[2982] authd-config.c:251 at Read_Authd(): DEBUG: The tag <force><key_mismatch> is not defined. Applied default value: 'true'
```
This log messages appear when the whole `<force>` block is missing, this will give more information to a user that has just upgraded from an old version and has not added the new configuration options.

## Task Results

<details><summary>The force option not defined messages appears when force block missing :green_circle: </summary>

1. Configure ossec.conf
```
  <auth>
    .
    . 
    .
    <force_insert>yes</force_insert>
    <force_time>0</force_time>
  </auth>
```
2. Restart manager
3. Check logs
```
2022/10/20 11:25:17 wazuh-authd[2982] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
2022/10/20 11:25:17 wazuh-authd[2982] config.c:23 at authd_read_config(): DEBUG: Reading configuration 'etc/ossec.conf'
2022/10/20 11:25:17 wazuh-authd[2982] authd-config.c:125 at Read_Authd(): WARNING: The <force_insert> tag is deprecated. Use <force> instead.
2022/10/20 11:25:17 wazuh-authd[2982] authd-config.c:133 at Read_Authd(): WARNING: The <force_time> tag is deprecated. Use <force> instead.
2022/10/20 11:25:17 wazuh-authd[2982] authd-config.c:237 at Read_Authd(): DEBUG: Setting <force><enabled> tag to 'yes' to comply with the legacy <force_insert> option found.
2022/10/20 11:25:17 wazuh-authd[2982] authd-config.c:246 at Read_Authd(): DEBUG: Setting <force><disconnected_time> tag to '0' to comply with the legacy <force_time> option found.
2022/10/20 11:25:17 wazuh-authd[2982] authd-config.c:249 at Read_Authd(): DEBUG: The tag <force><after_registration_time> is not defined. Applied default value: '3600'
2022/10/20 11:25:17 wazuh-authd[2982] authd-config.c:251 at Read_Authd(): DEBUG: The tag <force><key_mismatch> is not defined. Applied default value: 'true'
2022/10/20 11:25:17 wazuh-authd[2982] main-server.c:442 at main(): DEBUG: Wazuh home directory: /var/ossec
Started wazuh-authd...
```
</details>

<details><summary>The force option not defined messages do not appear when force block appears :green_circle: </summary>

1. Configure ossec.conf
```
  <auth>
    .
    . 
    <force>
        <key_mismatch>no</key_mismatch>
    </force>
    <force_insert>yes</force_insert>
    <force_time>0</force_time>
  </auth>
```
2. Restart manager
3. Check logs
```
2022/10/19 20:51:01 wazuh-authd[5415] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
2022/10/19 20:51:01 wazuh-authd[5415] config.c:23 at authd_read_config(): DEBUG: Reading configuration 'etc/ossec.conf'
2022/10/19 20:51:01 wazuh-authd[5415] authd-config.c:125 at Read_Authd(): WARNING: The <force_insert> tag is deprecated. Use <force> instead.
2022/10/19 20:51:01 wazuh-authd[5415] authd-config.c:133 at Read_Authd(): WARNING: The <force_time> tag is deprecated. Use <force> instead.
2022/10/19 20:51:01 wazuh-authd[5415] main-server.c:442 at main(): DEBUG: Wazuh home directory: /var/ossec
2022/10/19 20:51:01 wazuh-authd[5415] main-server.c:491 at main(): INFO: Started (pid: 5418).
2022/10/19 20:51:01 wazuh-authd[5415] ssl.c:75 at os_ssl_keys(): DEBUG: Returning CTX for server.
2022/10/19 20:51:01 wazuh-authd[5415] main-server.c:546 at main(): INFO: Accepting connections on port 1515. No password required.
2022/10/19 20:51:01 wazuh-authd[5415] main-server.c:644 at run_dispatcher(): DEBUG: Dispatch thread ready.
2022/10/19 20:51:01 wazuh-authd[5415] local-server.c:89 at run_local_server(): DEBUG: Local server thread ready.
2022/10/19 20:51:01 wazuh-authd[5415] main-server.c:822 at run_remote_server(): INFO: Setting network timeout to 1.000000 sec.
2022/10/19 20:51:01 wazuh-authd[5415] main-server.c:827 at run_remote_server(): DEBUG: Remote server ready.
2022/10/19 20:51:01 wazuh-authd[5415] main-server.c:911 at run_writer(): DEBUG: Writer thread ready.
2022/10/19 20:51:02 wazuh-db: INFO: Started (pid: 5436).
```
</details>

**Comment by jmv74211** [comment]
## Closing conclusion 👍🏼  

|| |
|-|-|
| 🟢 | Solved 
| 🔵 | Proposed to be fixed in future versions or developments | 

The development has been approved taking into account the following considerations proposed in the [QA review](https://github.com/wazuh/wazuh-qa/issues/3262#issuecomment-1254153772):

***(1)*: Notify to the user of default re-registration behavior when using deprecated options.** 🟢 

When a user has only the old authd force configuration options, the agent will not be re-registered because of the new force options `key_mismatch` and `after_registration_time`. This has been solved in the tested development [wazuh#14549](https://github.com/wazuh/wazuh/pull/14549).

***(2)*: Inconsistent behaviors when using invalid configurations in the authd module** 🔵 

The following issue [wazuh#15257](https://github.com/wazuh/wazuh/issues/15257) has been opened to report the detected problem. It will be fixed in future releases.
