### ISSUE TITLE
QA testing - Fix arbitrary code execution in Active Response (backport to 3.13)

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-qa#3264]
| Target version |  Related PR |
|--------------------|----------------|
|  3.13.6                      |         https://github.com/wazuh/wazuh/pull/14823               |

## Description

This PR applies the same changes into ossec-execd as https://github.com/wazuh/wazuh/pull/14801.

## Proposed checks

- [x] Send a custom AR command to Execd containing a reference to the parent folder.
- [x] The API rejects custom ARs with commands referring to the parent folder.

## Steps to reproduce

On unfixed versions, we can send a command like `../../../../bin/ls`, and the agent will run it.

## Expected results

- If we run an API request with a command containing a reference to the parent folder (`/..`), it should return this error:

```
{"title": "Bad Request", "detail": "'!../../../../../../bin/ls' is not a 'active_response_command' - 'command'"}
```

- If we send an AR request directly to wazuh-execd, these logs must appear in _ossec.log_:
```sh
echo -n '!../../../../../../bin/ls' | nc -w0 -Uu /var/ossec/queue/alerts/execq
```
```
2022/09/07 16:38:33 ossec-execd[97673] exec.c:163 at GetCommandbyName(): WARNING: Active response command '../../../../../../bin/ls' vulnerable to directory traversal attack. Ignoring.
2022/09/07 16:38:33 ossec-execd[97673] execd.c:461 at ExecdStart(): ERROR: (1311): Invalid command name '!../../../../../../bin/ls' provided.
```

**Comment by Rebits** [comment]
## Review data

| Tester | PR commit               |
|--------|-------------------------|
| @Rebits| https://github.com/wazuh/wazuh/pull/14823/commits/84b7665c77ba963a94d4387c98d9b898f3939caa|


### Testing environment

| OS: Instance | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
| Ubuntu: Manager |  22  | AWS |    ami-029496e60f56b4b13         |
| Ubuntu: Agent |    22      | AWS |    ami-029496e60f56b4b13         |
| Windows Server: Agent |    2022      | AWS |    ami-047e29beecff33db0         |

### Tested packages

| `wazuh-manager`                                                                                                          | `wazuh-agent`                                                                                                          |  `wazuh-api`   | 
| ------------------------------------------------------------------------------------------------------------------------ | ---------------------------------------------------------------------------------------------------------------------- | --- |
| [Manager](https://packages-dev.wazuh.com/warehouse/test/3.13/deb/var/wazuh-manager_3.13.5-0.fixarcustomcomm_amd64.deb)  | [Windows agent](https://packages-dev.wazuh.com/warehouse/test/3.13/windows/wazuh-agent-3.13.5-0.fixarcustomcomm.msi) - [Linux agent](https://packages-dev.wazuh.com/warehouse/test/3.13/deb/var/wazuh-agent_3.13.5-0.fixarcustomcomm_amd64.deb) |  [API](https://packages-dev.wazuh.com/warehouse/test/3.13/deb/var/wazuh-api_3.13.6-1_amd64.deb)   |


### Status

- [x] In progress
- [ ] Pending Review
- [ ] Team leader approved
- [ ] Manager approved

**Comment by Rebits** [comment]
## Task results

### Windows Agent commands:

<details>

 
<summary>  <code> ..\\..\\..\\example.ps1 </code> :green_circle:  </summary>

- API

```
root@ip-172-31-4-179:/home/qa# curl -u foo:bar -k -X PUT -d '{"command": "..\\..\\..\\example.ps1", "arguments": ["-", "null", "(from_the_server)", "(no_rule_id)"], "custom": true}' -H 'Content-Type:application/json' "https://127.0.0.1:55000/active-response/001?pretty"
{
   "error": 602,
   "message": "Param not valid. Invalid command.  Field: command"
}
```

- AR socket

Not applicable


</details>


<details>

<summary> <code> ..\\\\..\\\\example.ps1 </code> :green_circle: </summary>


- API 

```
root@ip-172-31-4-179:/home/qa# curl -u foo:bar -k -X PUT -d '{"command": "!..\\\\..\\\\example.ps1 ", "arguments": ["-", "null", "(from_the_server)", "(no_rule_id)"], "custom": true}' -H 'Content-Type:application/json' "https://127.0.0.1:55000/active-response/002?pretty"
{
   "error": 602,
   "message": "Param not valid. Invalid command.  Field: command"
}
```

- AR socket

Not applicable


</details>

<details>

<summary> <code>...\\..\\example.ps1</code>  :green_circle: </summary>


- API

```
root@ip-172-31-4-179:/home/qa# curl -u foo:bar -k -X PUT -d '{"command": "...\\..\\example.ps1 ", "arguments": ["-", "null", "(from_the_server)", "(no_rule_id)"], "custom": true}' -H 'Content-Type:application/json' "https://127.0.0.1:55000/active-response/002?pretty"
{
   "error": 602,
   "message": "Param not valid. Invalid command.  Field: command"
}

```
- AR socket

Not applicable


</details>

<details>


<summary> <code> ..\\...\\..\\example.ps1 </code> :green_circle:  </summary>

- API


```
root@ip-172-31-4-179:/home/qa# curl -u foo:bar -k -X PUT -d '{"command": "..\\...\\..\\example.ps1", "arguments": ["-", "null", "(from_the_server)", "(no_rule_id)"], "custom": true}' -H 'Content-Type:application/json' "https://127.0.0.1:55000/active-response/002?pretty"
{
   "error": 602,
   "message": "Param not valid. Invalid command.  Field: command"
}

```

- AR socket

Not applicable


</details>

<details>

<summary> <code> .\\..\\\\\\\\example.ps1 </code> :green_circle:  </summary>

- API

```
root@ip-172-31-4-179:/home/qa# curl -u foo:bar -k -X PUT -d '{"command": "!.\\..\\\\\\\\example.ps1", "arguments": ["-", "null", "(from_the_server)", "(no_rule_id)"], "custom": true}' -H 'Content-Type:application/json' "https://127.0.0.1:55000/active-response/002?pretty"
{
   "error": 602,
   "message": "Param not valid. Invalid command.  Field: command"
}
```

- AR socket

Not applicable


</details>



<details>

<summary> <code> ./../../example.ps1 </code> :green_circle: </summary>

- API

```
root@ip-172-31-4-179:/home/qa# curl -u foo:bar -k -X PUT -d '{"command": "./../../example.ps1", "arguments": ["-", "null", "(from_the_server)", "(no_rule_id)"], "custom": true}' -H 'Content-Type:application/json' "https://127.0.0.1:55000/active-response/002?pretty"
{
   "error": 602,
   "message": "Param not valid. Invalid command.  Field: command"
}

```

- AR socket

Not applicable


</details>


<details>

<summary> <code> ./.../../example.ps1 </code> :green_circle: </summary>

- API

```
root@ip-172-31-4-179:/home/qa# curl -u foo:bar -k -X PUT -d '{"command": "./.../../example.ps1", "arguments": ["-", "null", "(from_the_server)", "(no_rule_id)"], "custom": true}' -H 'Content-Type:application/json' "https://127.0.0.1:55000/active-response/002?pretty"
{
   "error": 602,
   "message": "Param not valid. Invalid command.  Field: command"
}
```

- AR socket

Not applicable


</details>



<details>

<summary> <code> ..\\/example.ps1 </code>  :green_circle:  </summary>

- API

```
root@ip-172-31-4-179:/home/qa# curl -u foo:bar -k -X PUT -d '{"command": "..\\/example.ps1", "arguments": ["-", "null", "(from_the_server)", "(no_rule_id)"], "custom": true}' -H 'Content-Type:application/json' "https://127.0.0.1:55000/active-response/002?pretty"
{
   "error": 602,
   "message": "Param not valid. Invalid command.  Field: command"
}

```
- AR socket

Not applicable


</details>



###  Ubuntu Agent commands


<details>

<summary> <code> ../../../../../../bin/example.sh </code>  :black_circle:  </summary>

- API
```
root@ip-172-31-4-179:/home/qa# curl -u foo:bar -k -X PUT -d '{"command": "../../../../../../bin/example.sh", "arguments": ["-", "null", "(from_the_server)", "(no_rule_id)"], "custom": true}' -H 'Content-Type:application/json' "https://127.0.0.1:55000/active-response/002?pretty"
{
   "error": 602,
   "message": "Param not valid. Invalid command.  Field: command"
}

```

- AR socket

Not applicable



</details>


<details>

<summary> <code> ./././test.sh </code> :black_circle:  </summary>

- API

```
root@ip-172-31-4-179:/home/qa# curl -u foo:bar -k -X PUT -d '{"command": "./././test.sh", "arguments": ["-", "null", "(from_the_server)", "(no_rule_id)"], "custom": true}' -H 'Content-Type:application/json' "https://127.0.0.1:55000/active-response/002?pretty"
{
   "error": 0,
   "data": "Command sent."
}
```


- AR
```
```

</details>


<details>

<summary> <code> !   example.sh </code> :black_circle:  </summary>

- API
```
root@ip-172-31-4-179:/home/qa# curl -u foo:bar -k -X PUT -d '{"command": "!   example.sh", "arguments": ["-", "null", "(from_the_server)", "(no_rule_id)"], "custom": true}' -H 'Content-Type:application/json' "https://127.0.0.1:55000/active-response/002?pretty"
{
   "error": 602,
   "message": "Param not valid. Invalid command.  Field: command"
}
```

- AR


</details>



<details>

<summary> <code> !..\/example.sh </code>  :black_circle:  </summary>

- API
```
root@ip-172-31-4-179:/home/qa# curl -u foo:bar -k -X PUT -d '{"command": "!..\/example.sh", "arguments": ["-", "null", "(from_the_server)", "(no_rule_id)"], "custom": true}' -H 'Content-Type:application/json' "https://127.0.0.1:55000/active-response/002?pretty"
{
   "error": 602,
   "message": "Param not valid. Invalid command.  Field: command"
}

```


</details>



<details>

<summary> <code>  !~example.sh </code> :black_circle:   </summary>

- API

```
root@ip-172-31-4-179:/home/qa# curl -u foo:bar -k -X PUT -d '{"command": "!~example.sh", "arguments": ["-", "null", "(from_the_server)", "(no_rule_id)"], "custom": true}' -H 'Content-Type:application/json' "https://127.0.0.1:55000/active-response/002?pretty"
{
   "error": 602,
   "message": "Param not valid. Invalid command.  Field: command"
}

```


</details>



<details>

<summary> <code> !./.././example.sh </code> :black_circle:  </summary>

- API

```
root@ip-172-31-4-179:/home/qa# curl -u foo:bar -k -X PUT -d '{"command": "!./.././example.sh", "arguments": ["-", "null", "(from_the_server)", "(no_rule_id)"], "custom": true}' -H 'Content-Type:application/json' "https://127.0.0.1:55000/active-response/002?pretty"
{
   "error": 602,
   "message": "Param not valid. Invalid command.  Field: command"
}

```

</details>


<details>

<summary> <code> !..././example.sh </code> :black_circle:  </summary>

```
root@ip-172-31-4-179:/home/qa# curl -u foo:bar -k -X PUT -d '{"command": "!..././example.sh", "arguments": ["-", "null", "(from_the_server)", "(no_rule_id)"], "custom": true}' -H 'Content-Type:application/json' "https://127.0.0.1:55000/active-response/002?pretty"
{
   "error": 602,
   "message": "Param not valid. Invalid command.  Field: command"
}
```


</details>


<details>

<summary> <code> ...\.\example.sh </code> :black_circle:  </summary>

- API
```
{"error":614,"message":"Invalid request. Body is not correct."}root@ip-172-31-4-179:/home/qa# 
root@ip-172-31-4-179:/home/qa# curl -u foo:bar -k -X PUT -d '{"command": "...\\.\\example.sh", "arguments": ["-", "null", "(from_the_server)", "(no_rule_id)"], "custom": true}' -H 'Content-Type:application/json' "https://127.0.0.1:55000/active-response/002?pretty"
{
   "error": 602,
   "message": "Param not valid. Invalid command.  Field: command"
}
```

</details>

**Comment by jmv74211** [comment]
🟢 Everything seems to be working properly
