### ISSUE TITLE
QA testing - Avoid multigroup files deletion in worker nodes when the node is restarted

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh-qa#3269]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|  4.3.8  |  https://github.com/wazuh/wazuh/issues/14814  |  https://github.com/wazuh/wazuh/pull/14825  |

## Description

In order to validate the changes of the branch https://github.com/wazuh/wazuh/tree/14814_avoid_multigroup_deletion, some manual testing is required.

A performance issue was detected when rebooting a wazuh node in a cluster architecture. This was related to the fact that all multigroups are deleted when rebooting a node, but this task is not necessary to perform on worker nodes since the cluster already controls when there are changes that require re-synchronization between master and workers.

## Configuration

Configure at least a master node and a worker node.

https://documentation.wazuh.com/current/user-manual/configuring-cluster/index.html

### Unfixed
- [x] Cluster doesn't re-synchronize multigroups files when any worker node is restarted 
### Fresh Install
- [x] Cluster doesn't re-synchronize multigroups files when a worker node is restarted.
- [x] Cluster doesn't re-synchronize multigroups files when a the master node is restarted.
- [x] Cluster only synchronize multigroups files when a change is detected in a multigroup. It only synchronize the multigroups that changed, not all of them.

### Upgrade

- [x] Cluster doesn't re-synchronize multigroups files when a worker node is restarted.
- [x] Cluster doesn't re-synchronize multigroups files when a the master node is restarted.
- [x] Cluster only synchronize multigroups files when a change is detected in a multigroup. It only synchronize the multigroups that changed, not all of them.

## Steps to reproduce

- Create a new group.
- Add an agent to the group.
- Restart any node.
- Verify that the cluster doesn't re-synchronize multigroups files.

## Expected results

At any case, the cluster has to synchronize a multigroup only when a change to the files in the multigroup is detected.

**Comment by QU3B1M** [comment]
## Review data

| Tester | PR commit               | 
|--------|-------------------------|
| @QU3B1M   |  [a2bda79](https://github.com/wazuh/wazuh/pull/14706/commits/a2bda795ce02f6345beb4e0cf239ddf317f5e92e)   | 

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
|  Ubuntu  | 20.04 | ` LOCAL \|  Vagrant` | [bento/ubuntu-20.04](https://app.vagrantup.com/bento/boxes/ubuntu-20.04)

### Tested packages

| `wazuh-manager` | `wazuh-agent` | 
|-----------------|---------------|
|  [deb](https://packages-dev.wazuh.com/warehouse/pullrequests/4.3/deb/var/wazuh-manager_4.3.8-0.commita2bda79_amd64.deb)  | [deb](https://packages-dev.wazuh.com/warehouse/pullrequests/4.3/deb/var/wazuh-agent_4.3.8-0.commita2bda79_amd64.deb)  | 

### Status

- [x] In progress
- [ ] Pending Review
- [ ] Team leader approved
- [ ] Manager approved

### Conclusion

**Comment by QU3B1M** [comment]
# Task results

## Fresh install

<details><summary>Cluster doesn't re-synchronize multigroups files when a worker node is restarted :green_circle:</summary>

  - Configure a cluster setup with one master and two workers
    ```
    /var/ossec/bin/cluster_control -l

    NAME     TYPE    VERSION  ADDRESS        
    master   master  4.3.8    192.168.56.10  
    worker2  worker  4.3.8    192.168.56.12  
    worker1  worker  4.3.8    192.168.56.11  
    ```
  - Create the groups `testOne` - `testTwo`.
    ```
    /var/ossec/bin/agent_groups -a -g testOne
    ```
    ```
    /var/ossec/bin/agent_groups -a -g testTwo
    ```
  - Add an agent to the groups `testOne` & `testTwo` and another agent only to the group `testTwo`.
    ```
    /var/ossec/bin/agent_groups -a -i 001 -g testOne
    ```
    ```
    /var/ossec/bin/agent_groups -a -i 001 -g testTwo
    ```
    ```
    /var/ossec/bin/agent_groups -a -i 002 -g testTwo
    ```
  - Check the multigroups files are generated in all nodes.\
    `master`
    ```
    ll /var/ossec/var/multigroups/

    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 18:10 9d3068c4/
    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 18:09 a37bc030/
    ```
    `worker-1`
    ```
    ll /var/ossec/var/multigroups/

    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 18:11 9d3068c4/
    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 18:10 a37bc030/
    ```
    `worker-2`
    ```
    ll /var/ossec/var/multigroups/

    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 18:11 9d3068c4/
    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 18:10 a37bc030/
    ```
  - Restart any worker.\
    `worker-2`
    ```
    systemctl restart wazuh-manager
    ```
  - Verify that the cluster doesn't re-synchronize multigroups files :green_circle:\
    `worker-2`
    ```
    ll /var/ossec/var/multigroups/

    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 18:11 9d3068c4/
    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 18:10 a37bc030/
    ```

</details>

<details><summary>Cluster doesn't re-synchronize multigroups files when a the master node is restarted :green_circle:</summary>

  - Configure a cluster setup with one master and two workers
    ```
    /var/ossec/bin/cluster_control -l

    NAME     TYPE    VERSION  ADDRESS        
    master   master  4.3.8    192.168.56.10  
    worker2  worker  4.3.8    192.168.56.12  
    worker1  worker  4.3.8    192.168.56.11  
    ```
  - Create the groups `testOne` - `testTwo`.
    ```
    /var/ossec/bin/agent_groups -a -g testOne
    ```
    ```
    /var/ossec/bin/agent_groups -a -g testTwo
    ```
  - Add an agent to the groups `testOne` & `testTwo` and another agent only to the group `testTwo`.
    ```
    /var/ossec/bin/agent_groups -a -i 001 -g testOne
    ```
    ```
    /var/ossec/bin/agent_groups -a -i 001 -g testTwo
    ```
    ```
    /var/ossec/bin/agent_groups -a -i 002 -g testTwo
    ```
  - Check the multigroups files are generated in all nodes.\
    `master`
    ```
    ll /var/ossec/var/multigroups/

    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 18:10 9d3068c4/
    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 18:09 a37bc030/
    ```
    `worker-1`
    ```
    ll /var/ossec/var/multigroups/

    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 18:11 9d3068c4/
    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 18:10 a37bc030/
    ```
    `worker-2`
    ```
    ll /var/ossec/var/multigroups/

    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 18:11 9d3068c4/
    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 18:10 a37bc030/
    ```
  - Restart the master node.
    ```
    systemctl restart wazuh-manager
    ```
  - Verify that the cluster doesn't re-synchronize multigroups files in workers :green_circle:
    `master`
    ```
    ll /var/ossec/var/multigroups/

    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 18:47 9d3068c4/
    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 18:47 a37bc030/
    ```
    `worker-1`
    ```
    ll /var/ossec/var/multigroups/

    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 18:11 9d3068c4/
    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 18:10 a37bc030/
    ```

</details>

<details><summary>Cluster only synchronize multigroups files when a change is detected in a multigroup. It only synchronize the multigroups that changed, not all of them :green_circle:</summary>

  - Configure a cluster setup with one master and two workers
    ```
    /var/ossec/bin/cluster_control -l

    NAME     TYPE    VERSION  ADDRESS        
    master   master  4.3.8    192.168.56.10  
    worker2  worker  4.3.8    192.168.56.12  
    worker1  worker  4.3.8    192.168.56.11  
    ```
  - Create the groups `testOne` - `testTwo`.
    ```
    /var/ossec/bin/agent_groups -a -g testOne
    ```
    ```
    /var/ossec/bin/agent_groups -a -g testTwo
    ```
  - Add an agent to the groups `testOne` & `testTwo` and another agent only to the group `testTwo`.
    ```
    /var/ossec/bin/agent_groups -a -i 001 -g testOne
    ```
    ```
    /var/ossec/bin/agent_groups -a -i 001 -g testTwo
    ```
    ```
    /var/ossec/bin/agent_groups -a -i 002 -g testTwo
    ```
  - Check the multigroups files are generated in all nodes.\
    `master`
    ```
    ll /var/ossec/var/multigroups/

    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 18:10 9d3068c4/
    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 18:09 a37bc030/
    ```
    `worker-1`
    ```
    ll /var/ossec/var/multigroups/

    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 18:11 9d3068c4/
    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 18:10 a37bc030/
    ```
    `worker-2`
    ```
    ll /var/ossec/var/multigroups/

    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 18:11 9d3068c4/
    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 18:10 a37bc030/
    ```
  - Create a new file inside the `testOne` group's folder.
    ```
    echo "testing" > /var/ossec/etc/shared/testOne/test.txt
    ```
  - Verify that the cluster updates and re-synchronize multigroups files :green_circle:\
    `worker-1`
    ```
    ll /var/ossec/var/multigroups/

    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 18:11 9d3068c4/
    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 19:21 a37bc030/
    ```
    `worker-2`
    ```
    ll /var/ossec/var/multigroups/

    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 18:11 9d3068c4/
    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 19:21 a37bc030/
    ```

</details>

## Upgrade

<details><summary>Cluster doesn't re-synchronize multigroups files when a worker node is restarted :green_circle:</summary>

  - With a cluster setup with one master and two workers using `wazuh 4.3.7`, and agents in multigroups.
  - Upgrade all the nodes to `wazuh 4.3.8` (fixed version)
    ```
    dpkg -i wazuh-manager_4.3.8-0.commita2bda79_amd64.deb 

    (Reading database ... 59728 files and directories currently installed.)
    Preparing to unpack wazuh-manager_4.3.8-0.commita2bda79_amd64.deb ...
    Unpacking wazuh-manager (4.3.8-0.commita2bda79) over (4.3.7-1) ...
    Setting up wazuh-manager (4.3.8-0.commita2bda79) ...
    Processing triggers for systemd (245.4-4ubuntu3.17) ...
    ```
    ```
    /var/ossec/bin/cluster_control -l

    NAME     TYPE    VERSION  ADDRESS        
    master   master  4.3.8    192.168.56.10  
    worker2  worker  4.3.8    192.168.56.12  
    worker1  worker  4.3.8    192.168.56.11  
    ```
  - Check the multigroups files generated in all nodes.\
    `master`
    ```
    ll /var/ossec/var/multigroups/

    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 20:11 9d3068c4/
    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 20:11 a37bc030/
    ```
    `worker-1`
    ```
    ll /var/ossec/var/multigroups/

    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 20:11 9d3068c4/
    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 20:11 a37bc030/
    ```
    `worker-2`
    ```
    ll /var/ossec/var/multigroups/

    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 20:11 9d3068c4/
    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 20:11 a37bc030/
    ```
  - Restart any worker.\
    `worker-2`
    ```
    systemctl restart wazuh-manager
    ```
  - Verify that the cluster doesn't re-synchronize multigroups files :green_circle:\
    `worker-1`
    ```
    ll /var/ossec/var/multigroups/

    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 20:11 9d3068c4/
    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 20:11 a37bc030/
    ```
    `worker-2`
    ```
    ll /var/ossec/var/multigroups/

    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 20:11 9d3068c4/
    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 20:11 a37bc030/
    ```

</details>

<details><summary>Cluster doesn't re-synchronize multigroups files when a the master node is restarted :green_circle:</summary>

  - With a cluster setup with one master and two workers using `wazuh 4.3.7`, and agents in multigroups.
  - Upgrade all the nodes to `wazuh 4.3.8` (fixed version)
    ```
    dpkg -i wazuh-manager_4.3.8-0.commita2bda79_amd64.deb 
    ```
  - Check the multigroups files generated in all nodes.\
    `master`
    ```
    ll /var/ossec/var/multigroups/

    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 20:11 9d3068c4/
    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 20:11 a37bc030/
    ```
    `worker-1`
    ```
    ll /var/ossec/var/multigroups/

    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 20:11 9d3068c4/
    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 20:11 a37bc030/
    ```
    `worker-2`
    ```
    ll /var/ossec/var/multigroups/

    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 20:11 9d3068c4/
    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 20:11 a37bc030/
    ```
  - Restart the master node.
    ```
    systemctl restart wazuh-manager
    ```
  - Verify that the cluster doesn't re-synchronize multigroups files in workers :green_circle:\
    `master`
    ```
    ll /var/ossec/var/multigroups/

    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 20:15 9d3068c4/
    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 20:15 a37bc030/
    ```
    `worker-1`
    ```
    ll /var/ossec/var/multigroups/

    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 20:11 9d3068c4/
    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 20:11 a37bc030/
    ```

</details>

<details><summary>Cluster only synchronize multigroups files when a change is detected in a multigroup. It only synchronize the multigroups that changed, not all of them :green_circle:</summary>


  - With a cluster setup with one master and two workers using `wazuh 4.3.7`, and agents in multigroups.
  - Upgrade all the nodes to `wazuh 4.3.8` (fixed version)
    ```
    dpkg -i wazuh-manager_4.3.8-0.commita2bda79_amd64.deb 
    ```
  - Check the multigroups files generated in all nodes.\
    `master`
    ```
    ll /var/ossec/var/multigroups/

    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 20:11 9d3068c4/
    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 20:11 a37bc030/
    ```
    `worker-1`
    ```
    ll /var/ossec/var/multigroups/

    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 20:11 9d3068c4/
    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 20:11 a37bc030/
    ```
    `worker-2`
    ```
    ll /var/ossec/var/multigroups/

    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 20:11 9d3068c4/
    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 20:11 a37bc030/
    ```
    `master`
    ```
    ll /var/ossec/var/multigroups/

    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 18:10 9d3068c4/
    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 18:09 a37bc030/
    ```
    `worker-1`
    ```
    ll /var/ossec/var/multigroups/

    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 18:11 9d3068c4/
    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 18:10 a37bc030/
    ```
    `worker-2`
    ```
    ll /var/ossec/var/multigroups/

    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 18:11 9d3068c4/
    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 18:10 a37bc030/
    ```
  - Create a new file inside the `testOne` group's folder.
    ```
    echo "testing" > /var/ossec/etc/shared/testOne/test.txt
    ```
  - Verify that the cluster updates and re-synchronize multigroups files in workers :green_circle:\
    `worker-1`
    ```
    ll /var/ossec/var/multigroups/

    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 20:11 9d3068c4/
    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 20:18 a37bc030/
    ```
    `worker-2`
    ```
    ll /var/ossec/var/multigroups/

    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 20:11 9d3068c4/
    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 20:18 a37bc030/
    ```

</details>


## Unfixed
<details><summary>Cluster doesn't re-synchronize multigroups files when any worker node is restarted :red_circle:</summary>

  - Configure a cluster setup with one master and two workers
    ```
    /var/ossec/bin/cluster_control -l

    NAME     TYPE    VERSION  ADDRESS          
    master   master  4.3.7    192.168.56.10  
    worker1  worker  4.3.7    192.168.56.11  
    worker2  worker  4.3.7    192.168.56.12  
    ```
  - Create the groups `testOne` - `testTwo`.
    ```
    /var/ossec/bin/agent_groups -a -g testOne
    ```
    ```
    /var/ossec/bin/agent_groups -a -g testTwo
    ```
  - Add an agent to the groups `testOne` & `testTwo` and another agent only to the group `testTwo`.
    ```
    /var/ossec/bin/agent_groups -a -i 001 -g testOne
    ```
    ```
    /var/ossec/bin/agent_groups -a -i 001 -g testTwo
    ```
    ```
    /var/ossec/bin/agent_groups -a -i 002 -g testTwo
    ```
  - Check the multigroups files are generated in all nodes.\
    `master`
    ```
    ll /var/ossec/var/multigroups/

    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 19:51 9d3068c4/
    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 19:51 a37bc030/
    ```
    `worker-1`
    ```
    ll /var/ossec/var/multigroups/

    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 19:51 9d3068c4/
    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 19:51 a37bc030/
    ```
    `worker-2`
    ```
    ll /var/ossec/var/multigroups/

    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 19:51 9d3068c4/
    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 19:51 a37bc030/
    ```
  - Restart any worker.\
    `worker-2`
    ```
    systemctl restart wazuh-manager
    ```
  - Verify that the cluster doesn't re-synchronize multigroups files for that worker :red_circle:
    `worker-2`
    ```
    ll /var/ossec/var/multigroups/

    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 19:52 9d3068c4/
    drwxrwx--- 2 wazuh wazuh 4096 Sep  8 19:52 a37bc030/
    ```

</details>

**Comment by Rebits** [comment]
# Benchmark Test
## Environments

### Environment 1:  v4.3.5 (not bug included)

| Wazuh version | N Workers | N Agents |
| ------------- | --------- | -------- |
| v4.3.5        | 4         | 200 for each worker       |

### Environment 2: v4.3.7 (bug included)

| Wazuh version | N Workers | N Agents |
| ------------- | --------- | -------- |
| v4.3.7        | 4         | 200         |

### Environment 3: v4.3.8-a2bda79 (bug fixed)

| Wazuh version | N Workers | N Agents |
| ------------- | --------- | -------- |
| v4.3.8-a2bda79        | 4         | 200         |


### Environment configuration

<details>


### Agent simulation
- To register the required agents, we are going to use the qa `simulate_agents.py` tool:
```
python simulate_agents.py -a 172.17.0.1 -n 200 -t 15
```
- Once the simulation ends, we are going to maintain all the agents as active using the `activate_agents` script (Credits to @Selutario )


### Groups creation
For group creation, we are going to use a simple script that makes use of the wazuh binary `/var/ossec/bin/agent_groups`. It will create 200 groups (`Group[1-200]`) with a customs `agent.conf` and a cis template file.


### Assignation of multiple groups for each agent
We are going to assign each agent to 10 groups. For this step, we are going to make use of the script `agent_group_assign`.


</details>

## Tests cases
### Initial Synchronization

<details>

With all nodes down, we generate will create 200 groups and we will assign 10 of them to each agent. Once multi groups are created, we will start every cluster by measuring the total amount of time that takes the synchronization process.

<details>

<summary> Comparision :black_circle:</summary>

__work_to_do__



</details>

<details>

<summary> v4.3.5 </summary>




| Master cluster logs | Average Integrity sync | Average Integrity check |
| ------------------- | ---------------------- | ----------------------- |
| Worker 1            |                        |                         |
| Worker 2            |                        |                         |
| Worker 3            |                        |                         |


| Average Local integrity |
| ----------- |
|                    |


| Artifacts | cluster.log |
| --------- | ----------- |
| Worker 1  |             |
| Worker 2  |             |
| Worker 3  |             |
| Master          |             |



</details>

<details>

<summary> v4.3.7 </summary>




| Master cluster logs | Average Integrity sync | Average Integrity check |
| ------------------- | ---------------------- | ----------------------- |
| Worker 1            |                        |                         |
| Worker 2            |                        |                         |
| Worker 3            |                        |                         |


| Average Local integrity |
| ----------- |
|                    |


| Artifacts | cluster.log |
| --------- | ----------- |
| Worker 1  |             |
| Worker 2  |             |
| Worker 3  |             |
| Master          |             |



</details>

<details>

<summary> v4.3.8 </summary>




| Master cluster logs | Average Integrity sync | Average Integrity check |
| ------------------- | ---------------------- | ----------------------- |
| Worker 1            |                        |                         |
| Worker 2            |                        |                         |
| Worker 3            |                        |                         |


| Average Local integrity |
| ----------- |
|                    |


| Artifacts | cluster.log |
| --------- | ----------- |
| Worker 1  |             |
| Worker 2  |             |
| Worker 3  |             |
| Master          |             |



</details>


</details>



### All cluster nodes restating

<details>

With all workers synchronized with the master node and with updated group information, restart all the nodes at the same time.


<details>

<summary> Comparision :black_circle:</summary>

__work_to_do__



</details>

<details>

<summary> v4.3.5 </summary>




| Master cluster logs | Average Integrity sync | Average Integrity check |
| ------------------- | ---------------------- | ----------------------- |
| Worker 1            |                        |                         |
| Worker 2            |                        |                         |
| Worker 3            |                        |                         |


| Average Local integrity |
| ----------- |
|                    |


| Artifacts | cluster.log |
| --------- | ----------- |
| Worker 1  |             |
| Worker 2  |             |
| Worker 3  |             |
| Master          |             |



</details>

<details>

<summary> v4.3.7 </summary>




| Master cluster logs | Average Integrity sync | Average Integrity check |
| ------------------- | ---------------------- | ----------------------- |
| Worker 1            |                        |                         |
| Worker 2            |                        |                         |
| Worker 3            |                        |                         |


| Average Local integrity |
| ----------- |
|                    |


| Artifacts | cluster.log |
| --------- | ----------- |
| Worker 1  |             |
| Worker 2  |             |
| Worker 3  |             |
| Master          |             |



</details>

<details>

<summary> v4.3.8 </summary>




| Master cluster logs | Average Integrity sync | Average Integrity check |
| ------------------- | ---------------------- | ----------------------- |
| Worker 1            |                        |                         |
| Worker 2            |                        |                         |
| Worker 3            |                        |                         |


| Average Local integrity |
| ----------- |
|                    |


| Artifacts | cluster.log |
| --------- | ----------- |
| Worker 1  |             |
| Worker 2  |             |
| Worker 3  |             |
| Master          |             |



</details>


</details>

### One cluster node restating

<details>

With all nodes synchronized with the manager and with updated group information, restart one of the nodes.


<details>

<summary> Comparision :black_circle:</summary>

__work_to_do__



</details>

<details>

<summary> v4.3.5 </summary>




| Master cluster logs | Average Integrity sync | Average Integrity check |
| ------------------- | ---------------------- | ----------------------- |
| Worker 1            |                        |                         |
| Worker 2            |                        |                         |
| Worker 3            |                        |                         |


| Average Local integrity |
| ----------- |
|                    |


| Artifacts | cluster.log |
| --------- | ----------- |
| Worker 1  |             |
| Worker 2  |             |
| Worker 3  |             |
| Master          |             |



</details>

<details>

<summary> v4.3.7 </summary>




| Master cluster logs | Average Integrity sync | Average Integrity check |
| ------------------- | ---------------------- | ----------------------- |
| Worker 1            |                        |                         |
| Worker 2            |                        |                         |
| Worker 3            |                        |                         |


| Average Local integrity |
| ----------- |
|                    |


| Artifacts | cluster.log |
| --------- | ----------- |
| Worker 1  |             |
| Worker 2  |             |
| Worker 3  |             |
| Master          |             |



</details>

<details>

<summary> v4.3.8 </summary>




| Master cluster logs | Average Integrity sync | Average Integrity check |
| ------------------- | ---------------------- | ----------------------- |
| Worker 1            |                        |                         |
| Worker 2            |                        |                         |
| Worker 3            |                        |                         |


| Average Local integrity |
| ----------- |
|                    |


| Artifacts | cluster.log |
| --------- | ----------- |
| Worker 1  |             |
| Worker 2  |             |
| Worker 3  |             |
| Master          |             |



</details>

</details>

### All cluster nodes restarting and API cluster stress

<details>


With all workers synchronized with the master node and with updated group information, restart all the nodes at the same time along with heavy API cluster stress requests.

<details>

<summary> Comparision :black_circle:</summary>

__work_to_do__



</details>

<details>

<summary> v4.3.5 </summary>




| Master cluster logs | Average Integrity sync | Average Integrity check |
| ------------------- | ---------------------- | ----------------------- |
| Worker 1            |                        |                         |
| Worker 2            |                        |                         |
| Worker 3            |                        |                         |


| Average Local integrity |
| ----------- |
|                    |


| Artifacts | cluster.log |
| --------- | ----------- |
| Worker 1  |             |
| Worker 2  |             |
| Worker 3  |             |
| Master          |             |



</details>

<details>

<summary> v4.3.7 </summary>




| Master cluster logs | Average Integrity sync | Average Integrity check |
| ------------------- | ---------------------- | ----------------------- |
| Worker 1            |                        |                         |
| Worker 2            |                        |                         |
| Worker 3            |                        |                         |


| Average Local integrity |
| ----------- |
|                    |


| Artifacts | cluster.log |
| --------- | ----------- |
| Worker 1  |             |
| Worker 2  |             |
| Worker 3  |             |
| Master          |             |



</details>

<details>

<summary> v4.3.8 </summary>




| Master cluster logs | Average Integrity sync | Average Integrity check |
| ------------------- | ---------------------- | ----------------------- |
| Worker 1            |                        |                         |
| Worker 2            |                        |                         |
| Worker 3            |                        |                         |


| Average Local integrity |
| ----------- |
|                    |


| Artifacts | cluster.log |
| --------- | ----------- |
| Worker 1  |             |
| Worker 2  |             |
| Worker 3  |             |
| Master          |             |



</details>


</details>

### Adding multiple files to a group

<details>

With all workers synchronized with the master node and with updated group information, create multiple files at the same time in one of the groups.

<details>

<summary> Comparision :black_circle:</summary>

__work_to_do__



</details>

<details>

<summary> v4.3.5 </summary>




| Master cluster logs | Average Integrity sync | Average Integrity check |
| ------------------- | ---------------------- | ----------------------- |
| Worker 1            |                        |                         |
| Worker 2            |                        |                         |
| Worker 3            |                        |                         |


| Average Local integrity |
| ----------- |
|                    |


| Artifacts | cluster.log |
| --------- | ----------- |
| Worker 1  |             |
| Worker 2  |             |
| Worker 3  |             |
| Master          |             |



</details>

<details>

<summary> v4.3.7 </summary>




| Master cluster logs | Average Integrity sync | Average Integrity check |
| ------------------- | ---------------------- | ----------------------- |
| Worker 1            |                        |                         |
| Worker 2            |                        |                         |
| Worker 3            |                        |                         |


| Average Local integrity |
| ----------- |
|                    |


| Artifacts | cluster.log |
| --------- | ----------- |
| Worker 1  |             |
| Worker 2  |             |
| Worker 3  |             |
| Master          |             |



</details>

<details>

<summary> v4.3.8 </summary>




| Master cluster logs | Average Integrity sync | Average Integrity check |
| ------------------- | ---------------------- | ----------------------- |
| Worker 1            |                        |                         |
| Worker 2            |                        |                         |
| Worker 3            |                        |                         |


| Average Local integrity |
| ----------- |
|                    |


| Artifacts | cluster.log |
| --------- | ----------- |
| Worker 1  |             |
| Worker 2  |             |
| Worker 3  |             |
| Master          |             |



</details>

</details>

### Big file update synchronization

<details>

With all nodes synchronized with the manager and with updated group information, create a new big file in one of the groups.


<details>

<summary> Comparision :black_circle:</summary>

__work_to_do__



</details>

<details>

<summary> v4.3.5 </summary>




| Master cluster logs | Average Integrity sync | Average Integrity check |
| ------------------- | ---------------------- | ----------------------- |
| Worker 1            |                        |                         |
| Worker 2            |                        |                         |
| Worker 3            |                        |                         |


| Average Local integrity |
| ----------- |
|                    |


| Artifacts | cluster.log |
| --------- | ----------- |
| Worker 1  |             |
| Worker 2  |             |
| Worker 3  |             |
| Master          |             |



</details>

<details>

<summary> v4.3.7 </summary>




| Master cluster logs | Average Integrity sync | Average Integrity check |
| ------------------- | ---------------------- | ----------------------- |
| Worker 1            |                        |                         |
| Worker 2            |                        |                         |
| Worker 3            |                        |                         |


| Average Local integrity |
| ----------- |
|                    |


| Artifacts | cluster.log |
| --------- | ----------- |
| Worker 1  |             |
| Worker 2  |             |
| Worker 3  |             |
| Master          |             |



</details>

<details>

<summary> v4.3.8 </summary>




| Master cluster logs | Average Integrity sync | Average Integrity check |
| ------------------- | ---------------------- | ----------------------- |
| Worker 1            |                        |                         |
| Worker 2            |                        |                         |
| Worker 3            |                        |                         |


| Average Local integrity |
| ----------- |
|                    |


| Artifacts | cluster.log |
| --------- | ----------- |
| Worker 1  |             |
| Worker 2  |             |
| Worker 3  |             |
| Master          |             |



</details>


</details>


### Remove all groups synchronization

<details>

With all nodes synchronized with the manager and with updated group information, remove all groups.


<details>

<summary> Comparision :black_circle:</summary>

__work_to_do__



</details>

<details>

<summary> v4.3.5 </summary>




| Master cluster logs | Average Integrity sync | Average Integrity check |
| ------------------- | ---------------------- | ----------------------- |
| Worker 1            |                        |                         |
| Worker 2            |                        |                         |
| Worker 3            |                        |                         |


| Average Local integrity |
| ----------- |
|                    |


| Artifacts | cluster.log |
| --------- | ----------- |
| Worker 1  |             |
| Worker 2  |             |
| Worker 3  |             |
| Master          |             |



</details>

<details>

<summary> v4.3.7 </summary>




| Master cluster logs | Average Integrity sync | Average Integrity check |
| ------------------- | ---------------------- | ----------------------- |
| Worker 1            |                        |                         |
| Worker 2            |                        |                         |
| Worker 3            |                        |                         |


| Average Local integrity |
| ----------- |
|                    |


| Artifacts | cluster.log |
| --------- | ----------- |
| Worker 1  |             |
| Worker 2  |             |
| Worker 3  |             |
| Master          |             |



</details>

<details>

<summary> v4.3.8 </summary>




| Master cluster logs | Average Integrity sync | Average Integrity check |
| ------------------- | ---------------------- | ----------------------- |
| Worker 1            |                        |                         |
| Worker 2            |                        |                         |
| Worker 3            |                        |                         |


| Average Local integrity |
| ----------- |
|                    |


| Artifacts | cluster.log |
| --------- | ----------- |
| Worker 1  |             |
| Worker 2  |             |
| Worker 3  |             |
| Master          |             |



</details>

</details>

**Comment by davidjiglesias** [comment]
After reviewing the test results I conclude the fix from https://github.com/wazuh/wazuh/issues/14814 works as intended, bringing the generation of the multigroup files to its state prior to v4.3.6.
