### ISSUE TITLE
Testing - new feature: Limit EPS

### ISSUE THREAD

**Issue by jesuslinares** [wazuh/wazuh-qa#3272]
In this issue, we will perform some tests of the new feature for limiting EPS: 

- Development issue: https://github.com/wazuh/wazuh/issues/12512 https://github.com/wazuh/wazuh/issues/12698
- Manual testing issue: https://github.com/wazuh/wazuh-qa/issues/2995
- Performance analysis https://github.com/wazuh/wazuh/issues/14527
- Documentation: [Events per second limits added to ossec.conf global section](https://github.com/wazuh/wazuh-documentation/pull/5346#top).
- Testing package: https://packages-dev.wazuh.com/warehouse/branches/4.4/rpm/var/wazuh-manager-4.4.0-10.x86_64.rpm.

## Tasks
- [x] Build package
- [x] Build docker image and deploy
- [x] Tests
  - [x] Test EPS limit cases. ✔️ 
  - [x] Obtain EPS information using the API. ✔️ 
  - [x] Check credit system. ✔️ 
  - [x] Validate API protection for EPS changes ⛔ 
  - [x] Check logging ⛔

**Comment by francobep** [comment]
## Tests cases - fresh install

<details>
<summary> Prerequisites </summary>

 1. Docker image with Wazuh 4.4.0 based on https://github.com/wazuh/wazuh-docker/tree/cloud-1.16.
 2. Managers and agents deployed inside Kubernetes.
</details>

<details>
<summary> Check that wazuh-analysisd stops processing events when the limit is reached :green_circle: </summary>

1. Add configuration for EPS in `/var/ossec/logs/ossec.log`:

    ```
    <global>
       <limits>
          <eps>
             <maximum>50</maximum>
             <timeframe>30</timeframe>
          </eps>
      </limits>
   </global>

    ```
2. Restart Wazuh manager in order to apply changes:

    ```
    systemctl restart wazuh-manager
    ```
    
    Output:
    ```
    wazuh-clusterd not running...
    wazuh-modulesd is running...
    wazuh-monitord is running...
    wazuh-logcollector is running...
    wazuh-remoted is running...
    wazuh-syscheckd is running...
    wazuh-analysisd is running...
    wazuh-maild not running...
    wazuh-execd is running...
    wazuh-db is running...
    wazuh-authd is running...
    wazuh-agentlessd not running...
    wazuh-integratord not running...
    wazuh-dbd not running...
    wazuh-csyslogd not running...
    wazuh-apid is running...
    
    ```
3. Check logs located in `/var/ossec/logs/ossec.log`:

    ```
    2022/08/18 13:21:36 wazuh-analysisd: INFO: EPS limit enabled, EPS: '50', timeframe: '30'
    ```

4. Generate logs with `simulate-agents` tool:

    ```
    simulate-agents -a MANAGER_IP -n 1 -m logcollector -s 1000
    ```

5. Check State files vs Stats:

    ```
    events_processed='1000'
    events_received='1000'
    events_dropped='0'
    event_queue_usage='0.00'

    ...  

    events_processed='0'
    events_received='1000'
    events_dropped='0'
    event_queue_usage='0.37'
    ```
</details>

**Comment by francobep** [comment]
## Test - API configuration.

### Check default `api.yaml`
The content of the default `api.yaml` template is incorrect and does not match what is specified in the issue:

<details><summary>api.yaml</summary>

```
[root@wazuh-manager-master-0 /]# cat /var/ossec/api/configuration/api.yaml
# USE THIS FILE AS A TEMPLATE. UNCOMMENT LINES TO APPLY CUSTOM CONFIGURATION

# host: 0.0.0.0
# port: 55000

# Advanced configuration

# https:
#  enabled: yes
#  key: "server.key"
#  cert: "server.crt"
#  use_ca: False
#  ca: "ca.crt"
#  ssl_protocol: "TLSv1.2"
#  ssl_ciphers: ""

# Modify API's intervals (time in seconds)
# intervals:
#   request_timeout: 10

# Logging configuration
# Values for API log level: disabled, info, warning, error, debug, debug2 (each level includes the previous level).
# logs:
#  level: "info"
#  format: "plain"

# Cross-origin resource sharing: https://github.com/aio-libs/aiohttp-cors#usage
# cors:
#  enabled: no
#  source_route: "*"
#  expose_headers: "*"
#  allow_headers: "*"
#  allow_credentials: no

# Cache (time in seconds)
# cache:
#  enabled: yes
#  time: 0.750

# Access parameters
# access:
#  max_login_attempts: 50
#  block_time: 300
#  max_request_per_minute: 300

# Drop privileges (Run as wazuh user)
# drop_privileges: yes

# Enable features under development
experimental_features: yes

# Maximum body size that the API can accept, in bytes (0 -> limitless)
# max_upload_size: 10485760

# Enable remote commands
# remote_commands:
#   localfile:
#      enabled: yes
#      exceptions: []
#
#   wodle_command:
#     enabled: yes
#     exceptions: []`
```

</details>


### Check API protection.

Related Links
https://github.com/wazuh/wazuh-documentation/blob/1143c7521ac63a431c9d5759b08192097a08103b/source/user-manual/api/configuration.rst#upload_configuration

https://github.com/wazuh/wazuh/issues/13572#issuecomment-1174791517

Default values
``` 
upload_configuration:
  remote_commands:
    localfile:
      allow: True
      exceptions: []
    wodle_command:
      allow: True
      exceptions: []
  limits:
    eps:
      allow: True
``` 

<details><summary>master api.yaml</summary>

```
[root@wazuh-manager-master-0 /]# cat /var/ossec/api/configuration/api.yaml
# USE THIS FILE AS A TEMPLATE. UNCOMMENT LINES TO APPLY CUSTOM CONFIGURATION

# host: 0.0.0.0
# port: 55000

# Advanced configuration

# https:
#  enabled: yes
#  key: "server.key"
#  cert: "server.crt"
#  use_ca: False
#  ca: "ca.crt"
#  ssl_protocol: "TLSv1.2"
#  ssl_ciphers: ""

# Modify API's intervals (time in seconds)
# intervals:
#   request_timeout: 10

# Logging configuration
# Values for API log level: disabled, info, warning, error, debug, debug2 (each level includes the previous level).
# logs:
#  level: "info"
#  format: "plain"

# Cross-origin resource sharing: https://github.com/aio-libs/aiohttp-cors#usage
# cors:
#  enabled: no
#  source_route: "*"
#  expose_headers: "*"
#  allow_headers: "*"
#  allow_credentials: no

# Cache (time in seconds)
# cache:
#  enabled: yes
#  time: 0.750

# Access parameters
# access:
#  max_login_attempts: 50
#  block_time: 300
#  max_request_per_minute: 300

# Drop privileges (Run as wazuh user)
# drop_privileges: yes

# Enable features under development
#experimental_features: yes

# Maximum body size that the API can accept, in bytes (0 -> limitless)
# max_upload_size: 10485760

# Enable remote commands
# remote_commands:
#   localfile:
#      enabled: yes
#      exceptions: []
#
#   wodle_command:
#     enabled: yes
#     exceptions: []
upload_configuration:
  remote_commands:
    localfile:
      allow: True
      exceptions: []
    wodle_command:
      allow: True
      exceptions: []
  limits:
    eps:
      allow: no
```

</details>

<details><summary>worker-0 api.yaml</summary>

```
[root@wazuh-manager-worker-0 /]# cat /var/ossec/api/configuration/api.yaml
# USE THIS FILE AS A TEMPLATE. UNCOMMENT LINES TO APPLY CUSTOM CONFIGURATION

# host: 0.0.0.0
# port: 55000

# Advanced configuration

# https:
#  enabled: yes
#  key: "server.key"
#  cert: "server.crt"
#  use_ca: False
#  ca: "ca.crt"
#  ssl_protocol: "TLSv1.2"
#  ssl_ciphers: ""

# Modify API's intervals (time in seconds)
# intervals:
#   request_timeout: 10

# Logging configuration
# Values for API log level: disabled, info, warning, error, debug, debug2 (each level includes the previous level).
# logs:
#  level: "info"
#  format: "plain"

# Cross-origin resource sharing: https://github.com/aio-libs/aiohttp-cors#usage
# cors:
#  enabled: no
#  source_route: "*"
#  expose_headers: "*"
#  allow_headers: "*"
#  allow_credentials: no

# Cache (time in seconds)
# cache:
#  enabled: yes
#  time: 0.750

# Access parameters
# access:
#  max_login_attempts: 50
#  block_time: 300
#  max_request_per_minute: 300

# Drop privileges (Run as wazuh user)
# drop_privileges: yes

# Enable features under development
# experimental_features: no

# Maximum body size that the API can accept, in bytes (0 -> limitless)
# max_upload_size: 10485760

# Enable remote commands
# remote_commands:
#   localfile:
#     enabled: yes
#     exceptions: []
#
#   wodle_command:
#     enabled: yes
#     exceptions: []
upload_configuration:
  remote_commands:
    localfile:
      allow: True
      exceptions: []
    wodle_command:
      allow: True
      exceptions: []
  limits:
    eps:
      allow: no
```

</details>

Following the configurations described in the issue, we have verified that the EPS configuration **can be modified via the API, even if it has protection enabled.**

```
[root@wazuh-manager-master-0 /]#  grep "<eps>" -A 3 /tmp/ossec.conf.changed
          <eps>
            <maximum>101</maximum>
            <timeframe>30</timeframe>
          </eps>
[root@wazuh-manager-master-0 /]# curl -Ss -k --upload-file "/tmp/ossec.conf.changed" -X PUT 'https://localhost:55000/cluster/wazuh-manager-worker-0/configuration' -H "Authorization: Bearer $TOKEN"

{
  "data": {
    "affected_items": [
      "wazuh-manager-worker-0"
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "Configuration was successfully updated in specified node",
  "error": 0
}
```

**Comment by francobep** [comment]
## New package version
The @wazuh/cicd has provided a new package with a new version of the product. We must repeat the tests based on this new version.
http://packages-dev.wazuh.com/warehouse/test/4.4/rpm/var/wazuh-manager-4.4.0-0.0.0.devcloudlimits.x86_64.rpm

**Comment by jesuslinares** [comment]
There are two pending issues:

**Must fix**
API protection: The EPS configuration can be modified via the API, even if it has protection enabled.

**Should fix**
There are no messages in the log neither in the manager nor in the agent when they run out of credits. This prevents keeping a historical record only taking into account the logs produced by the product.

**Comment by jmv74211** [comment]
Thanks @jesuslinares and @francobep for the testing done. We attach your requests to the [main testing issue](https://github.com/wazuh/wazuh-qa/issues/2995), where all requests related to this development will be listed and discussed with the development team.
