### ISSUE TITLE
E2E Tests: Mark unstable tests as skipped

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh-qa#3275]
| Related issue
|--
| #3194

## Description

We have decided to mark as "skipped" some tests in the E2E. This is because they pass successfully in several runs but fail in others.

❗❗ **Therefore, it is stated that _the tests are not stable enough_ to be added to the automated run.**

| Tests marked | Further info about the failures
|-- |--
| `test_slack_integration` | [More info](https://github.com/wazuh/wazuh-qa/issues/3274#issuecomment-1241289029)
| `test_docker_monitoring` | [More info](https://github.com/wazuh/wazuh-qa/issues/3274#issuecomment-1241289029)
| `test_fim_windows` | [More info](https://github.com/wazuh/wazuh-qa/issues/3274#issuecomment-1241289029)
| `test_fim_linux` |  After running 21 rounds of all E2E tests we've found this test fails 11 times (~52%) [reference](https://github.com/wazuh/wazuh-qa/issues/3275#issuecomment-1242075581)

## Tasks

- [x] ([T1](https://github.com/wazuh/wazuh-qa/issues/3275#issuecomment-1242428440)): **Find unstable tests and skip them**
- [x] ([T2](https://github.com/wazuh/wazuh-qa/issues/3275#issuecomment-1243772587)): **Run E2E test suite to verify the changes**

***

Also, some minor changes will be needed:
- [x] Change the name of the credentials identifiers in the `check_controller_indexer` task (in the host_checker role): Done in 65f4001
- [x] Enable the validation stage again: Done in 44daf5a
- [x] Remove marks warnings: Done in 3c7375b

**Comment by mauromalara** [comment]
### Several executions to define which tests are unstable

| Build | R1 | R2 | R3
|-- |-- |-- |--
| [No. 497](https://devel.ci.wazuh.info/job/Test_system_WQA/497/) | 🔵 | 🔵 | 🔵
| [No. 498](https://devel.ci.wazuh.info/job/Test_system_WQA/498/) | 🔵 | 🔵 | 🔵
| [No. 499](https://devel.ci.wazuh.info/job/Test_system_WQA/499/) | 🔵 | 🔵 | 🔵
| [No. 500](https://devel.ci.wazuh.info/job/Test_system_WQA/500/) | 🔵 | 🔵 | 🔵
| [No. 501](https://devel.ci.wazuh.info/job/Test_system_WQA/501/) | 🔵 | 🔵 | 🔵

**Comment by mauromalara** [comment]
## Run E2E suite to check if full green is achieved 

| Build | R1 | R2 | R3
|-- |-- |-- |--
| [504](https://devel.ci.wazuh.info/job/Test_system_WQA/504/) | 🔵 | ⚫ | ⚫

**Comment by mauromalara** [comment]
## T2: Run E2E test suite after changes 🔵

### Run E2E suite to check if full green is achieved 

| Build | R1 | R2 | R3 | Notes
|-- |-- |-- |-- |--
| [504](https://devel.ci.wazuh.info/job/Test_system_WQA/504/) | [🟢](https://github.com/wazuh/wazuh-qa/files/9538919/Test_system_WQA_504_test_basic_cases.zip) | [🔴](https://github.com/wazuh/wazuh-qa/files/9539398/Test_system_WQA_504_test_basic_cases-2.zip)  | [🟢](https://github.com/wazuh/wazuh-qa/files/9539397/Test_system_WQA_504_test_basic_cases-3.zip) | R2 -> Brute Force (ssh)
| [505](https://devel.ci.wazuh.info/job/Test_system_WQA/505/) |  |
| [506](https://devel.ci.wazuh.info/job/Test_system_WQA/506/) |  |
| [507](https://devel.ci.wazuh.info/job/Test_system_WQA/507/) |  |
