### ISSUE TITLE
Nightly report: 2022-09-09

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3279]
## Data

| Date|  Commit | Commit title | Build | Notes |
|--|--|--|--|--|
| 2022-09-09| [8b46241](https://github.com/wazuh/wazuh/commit/8b4624107d36970222425dfa8336a487eee4b963) | Remove migrate_from_38 method and refactor migrate (https://github.com/wazuh/wazuh/pull/14684)  | [#31567](https://ci.wazuh.info/job/test_nightly/1215/) | 4.5 |

## Description

- [x]  Fix Vulnerability detectorIT: test_validate_feed_content.py file extension not expected. [#3282](https://github.com/wazuh/wazuh-qa/issues/3282) 
- [x]  Fix GCloud IT: test_rules.py not received expected behaviour [#3281](https://github.com/wazuh/wazuh-qa/issues/3281) 
- [ ] Reliability tests: Generic Environent launcher error [#3465](https://github.com/wazuh/wazuh-jenkins/issues/3465)  (Reported to wazuh-jenkins)
- [ ] IT pipeline: Unexpected Windows test launch error [#3487](https://github.com/wazuh/wazuh-jenkins/issues/3487)  (Reported to wazuh-jenkins)

**Note**: This issue also has information about Nightly launched previous than 2022-08-09

**Comment by damarisg** [comment]
The nightly report showed many paused executions, so we launched them again. 
It allowed seeing that Agentd, AR, fim, logcollector, and rootcheck tests work correctly.
