### ISSUE TITLE
Fix GCloud IT: test_rules.py not received expected behaviour 

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3281]
|Related issue|
|---|
|https://github.com/wazuh/wazuh-qa/issues/3279

## Data

| Date|  Commit | Commit title | Build | Notes |
|--|--|--|--|--|
| 2022-09-09| [8b46241](https://github.com/wazuh/wazuh/commit/8b4624107d36970222425dfa8336a487eee4b963) | Remove migrate_from_38 method and refactor migrate (https://github.com/wazuh/wazuh/pull/14684)   |[#31567](https://ci.wazuh.info/job/Test_integration/31567) | 4.5 |

## Case 

| Tier| Wazuh Type 
|--|--|
| 0 | Manager|  

### Description

```
11:07:59  FAILED test_gcloud/test_functionality/test_rules.py::test_rules[get_configuration0]
```

## Tasks
- [x] Run tests in Jenkins
- [ ] Run tests in local enviroment
- [ ] Read test code & docs and run tests manually
- [ ] Fix failures

**Comment by damarisg** [comment]
| Tester             | Test path | Jenkins | OS |  Notes                |
|--------------------|-----------|---------|--------|-----|
| Seyla |  test_gcloud | [:green_circle: ](https://ci.wazuh.info/job/Test_integration/31654/) [:green_circle: ](https://ci.wazuh.info/job/Test_integration/31725/) [:green_circle: ](https://ci.wazuh.info/job/Test_integration/31726/) | CentOS |
