### ISSUE TITLE
Fix Vulnerability detectorIT: test_validate_feed_content.py file extension not expected.

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3282]
|Related issue|
|---|
|https://github.com/wazuh/wazuh-qa/issues/3279

## Data

| Date|  Commit | Commit title | Build | Notes |
|--|--|--|--|--|
| 2022-09-09| [8b46241](https://github.com/wazuh/wazuh/commit/8b4624107d36970222425dfa8336a487eee4b963) | Remove migrate_from_38 method and refactor migrate (https://github.com/wazuh/wazuh/pull/14684)  |[#30852](https://ci.wazuh.info/job/Test_integration/31579/) | 4.5 |

## Case 

| Tier| Wazuh Type |
|--|--|
| 2 | Manager| 

### Description

```
21:27:01  FAILED test_vulnerability_detector/test_feeds/test_validate_feed_content.py::test_validate_xml_feed_content[Red Hat Enterprise Linux0]
21:27:01  FAILED test_vulnerability_detector/test_feeds/test_validate_feed_content.py::test_validate_xml_feed_content[Red Hat Enterprise Linux1]
21:27:01  FAILED test_vulnerability_detector/test_feeds/test_validate_feed_content.py::test_validate_xml_feed_content[Red Hat Enterprise Linux2]
21:27:01  FAILED test_vulnerability_detector/test_feeds/test_validate_feed_content.py::test_validate_xml_feed_content[Red Hat Enterprise Linux3]
21:27:01  FAILED test_vulnerability_detector/test_feeds/test_validate_feed_content.py::test_validate_xml_feed_content[Canonical Jammy]
21:27:01  FAILED test_vulnerability_detector/test_feeds/test_validate_feed_content.py::test_validate_xml_feed_content[Canonical Focal]
21:27:01  FAILED test_vulnerability_detector/test_feeds/test_validate_feed_content.py::test_validate_xml_feed_content[Canonical Bionic]
21:27:01  FAILED test_vulnerability_detector/test_feeds/test_validate_feed_content.py::test_validate_xml_feed_content[Canonical Xenial]
21:27:01  FAILED test_vulnerability_detector/test_feeds/test_validate_feed_content.py::test_validate_xml_feed_content[Canonical Trusty]
```

## Tasks
- [x] Run tests in Jenkins
- [x] Run tests in local enviroment
- [x] Read test code & docs and run tests manually
- [x] Fix failures

**Comment by roronoasins** [comment]
## 15/09/22

After manually test that the cases were making the test fail, some rounds have been run for both `4.4` and `4.5`

### Test rounds

| Test path                    | Local                                        | Jenkins                                                     | Build                                                                             | Version |
|------------------------------|----------------------------------------------|-------------------------------------------------------------|-----------------------------------------------------------------------------------|---------|
| test_vulnerability_detector/ | :green_circle: :green_circle: :green_circle: | :green_circle: :large_blue_circle: :large_blue_circle:      | [Build1](https://ci.wazuh.info/job/Test_integration/31916/) [Build2](https://ci.wazuh.info/job/Test_integration/31918/) [Build3](https://ci.wazuh.info/job/Test_integration/31920/) | 4.4.0   |
| test_vulnerability_detector/ | :green_circle: :green_circle: :green_circle: | :large_blue_circle: :large_blue_circle: :large_blue_circle: | [Build1](https://ci.wazuh.info/job/Test_integration/31917/) [Build2](https://ci.wazuh.info/job/Test_integration/31919/) [Build3](https://ci.wazuh.info/job/Test_integration/31921/)                                                  | 4.5.0   |
