### ISSUE TITLE
QA testing - Test FIM for LookupAccountSid dev branch

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#3294]
| Target version | Related issue | Related PR | QA Research Issue |
|--------------------|--------------------|-----------------|---------|
| 4.5.0               |  https://github.com/wazuh/wazuh/issues/14713                      |    https://github.com/wazuh/wazuh/pull/14723                | #3226 |

## Description
During research done for the Issue #3226 (and it's associated Core development) no possible way to reproduce the error was found. Since the change is mainly an enhancement of a log message, and there's no current effective way to test this, it has been resolved that it is needed to run the fim test suite to validate that the changes do not break the tests.

## Proposed checks

- [x] Run IT tests on all systems
   - [x] Manager
   - [x] Windows Agent
   - [x] Linux Agent
   - [x] Solaris Agent
   - [x] macOSAgent

## Expected results
All tests :green_circle:

**Comment by Deblintrake09** [comment]
## Review data

| Tester | PR commit               |
|--------|-------------------------|
| @Deblintrake09    |  [7b47586](https://github.com/wazuh/wazuh/commit/7b475861f843e53807812492db51f2799a21c44d)   |

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
|  Centos  |  8        | `REMOTE\ Jenkins IT Pipeline` |             |


### Tested packages

| `wazuh-manager` | `wazuh-agent` | 
|-----------------|---------------|
|  [manager](https://packages-dev.wazuh.com/warehouse/test/4.5/rpm/var/wazuh-manager-4.5.0-3226.lookupaccountsid.error.x86_64.rpm)               |  [win agent](https://packages-dev.wazuh.com/warehouse/test/4.5/windows/wazuh-agent-4.5.0-3226.lookupaccountsid.error.msi) - [rpm agent](https://packages-dev.wazuh.com/warehouse/test/4.5/rpm/var/wazuh-agent-4.5.0-3226.lookupaccountsid.error.x86_64.rpm) - [solaris agent](https://packages-dev.wazuh.com/warehouse/test/4.5/solaris/i386/11/wazuh-agent_v4.5.0-3226.lookupaccountsid.error-sol11-i386.p5p) - macos agent    |

### Status

- [ ] In progress
- [ ] Pending Review
- [ ] QA team leader approved
- [ ] QA manager approved
- [ ] Development team leader approved

## Conclusion

**Comment by Deblintrake09** [comment]
# Task results

| Path | OS - package | Results | Notes |
|---|---|---|---|
| test_fim | Centos Manager | [:green_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/31910/) [:large_blue_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/31912/) [:large_blue_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/31913/)  ||
| test_fim | Windows Agent | [:large_blue_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/31911/) ||
| test_fim | Centos Agent | [:large_blue_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/31911/) ||
| test_fim | Solaris Agent | [:large_blue_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/31911/) ||
| test_fim | macOS Agent | [:large_blue_circle:](https://ci.wazuh.info/view/Tests/job/Test_integration/31911/) ||

**Comment by jmv74211** [comment]
🟢 Everything seems to be working properly
