### ISSUE TITLE
QA testing - Vulnerability detector refactor

### ISSUE THREAD

**Issue by BelenValdivia** [wazuh/wazuh-qa#3306]
| Target version | Related issue | 
|--------------------|--------------------|
|                        |     https://github.com/wazuh/wazuh/issues/14153                   |      

## Description

This change applies a refactor in the Vulnerability Detector module. The objectives of this development are:

- Sanitize third-party vulnerabilities information and deliver it through the Wazuh Content model
- Reduce the Vulnerability Detector time-to-value
- Improve UX
- Simplify vulnerability scan
- Enhance the vulnerability scanner to avoid unnecessary scans by changing to an event-driven approach.
- Push Vulnerability detector results to Wazuh Indexer

## Proposed checks

- [x] https://github.com/wazuh/wazuh-qa/issues/3527
- [x] https://github.com/wazuh/wazuh-qa/issues/3519
- [x] https://github.com/wazuh/wazuh-qa/issues/3522
- [x] https://github.com/wazuh/wazuh-qa/issues/3524
- [x] https://github.com/wazuh/wazuh-qa/issues/3525
- [x] https://github.com/wazuh/wazuh-qa/issues/3526

**Comment by BelenValdivia** [comment]
- Cloned intelligence platform repository
- Followed the steps to build and install the migration tool. 
- Some problems with cmake solved installing cmake from sources

**Comment by BelenValdivia** [comment]
- Test content migration tool, but the execution returns an error message.
![image](https://github.com/wazuh/wazuh-qa/assets/26927338/72fd1d3c-b6f2-45b2-9597-5f052fd66162)

**Comment by BelenValdivia** [comment]
- Test migration tool on Debian, Alas1, Alas2, Alas 2022

    <details>
    <summary>Results</summary> 
    
   -  Debian:
    
    ```
    root@belen-VirtualBox:/home/belen# /var/wazuh/bin/content_migration -i /var/wazuh/config/vendors/debian.json
    
    ################ Wazuh Content Migration ################
    
    Content migration has been processed for 1 vendor/s in 00:00:00.
    
    => Debian security tracker content migration (1 remote/s)
    ```
    
    - Alas 1:
    
    ```
    root@belen-VirtualBox:/home/belen# /var/wazuh/bin/content_migration -i /var/wazuh/config/vendors/alas1.json
    
    ################ Wazuh Content Migration ################
    
    Content migration has been processed for 1 vendor/s in 00:00:26.
    
    => ALAS 1 content migration (1 remote/s)
    
    ```
    
    - Alas 2022
    
    ```
    root@belen-VirtualBox:/home/belen# /var/wazuh/bin/content_migration -i /var/wazuh/config/vendors/alas2022.json
    
    ################ Wazuh Content Migration ################
    
    Content migration has been processed for 1 vendor/s in 00:00:00.
    
    => ALAS 2022 content migration (1 remote/s)
    ```
    
    
    - Alas 2:
    
    ```
    root@belen-VirtualBox:/home/belen# /var/wazuh/bin/content_migration -i /var/wazuh/config/vendors/alas2.json
    
    ################ Wazuh Content Migration ################
    
    Content migration has been processed for 1 vendor/s in 00:00:00.
    
    => ALAS 2 content migration (1 remote/s)
    ```
    
    </details>

**Comment by BelenValdivia** [comment]
- Test migration tool on NVD

<details>
<summary>Results</summary>

- NVD:

```
root@belen-VirtualBox:/home/belen# /var/wazuh/bin/content_migration -i /var/wazuh/config/vendors/nvd.json 

################ Wazuh Content Migration ################

Content migration has been processed for 1 vendor/s in 00:00:02.

=> National Vulnerability Database content migration (14 remote/s)
```


</details>

**Comment by BelenValdivia** [comment]
Testing redefined
