### ISSUE TITLE
Vulnerability detector refactor - New Wazuh content validations

### ISSUE THREAD

**Issue by BelenValdivia** [wazuh/wazuh-qa#3307]
## Description

The tests that are proposed in the issue are related to the feeds of the new Wazuh Content.

### Integration tests:

- [x] Validate that the format is CVE 5 (not broken)
- [x] Validate invalid feeds
- [x] Validate feed content
- [x] Validate that the feed downloaded from a vendor, after run the tool, the output has the correct format

## Tasks

- [x] Research about QA framework for integration tests
- [ ] Do manual testing.
- [x] Start tests development

>Note:  _Manual testing could not be done, because the migration tool is not ready yet_

**Comment by BelenValdivia** [comment]
### Manual testing migration tool:
- Clone de repository https://github.com/wazuh/wazuh-content with submodules: 
   ` git clone --recursive git@github.com:wazuh/wazuh-content.git`

- Build the tool:

  ```
  mkdir build && cd build
  cmake .. -GNinja
  ninja
  ```
- Execute the tool (WIP)

**Comment by BelenValdivia** [comment]
### Task 1: Validate migration tool (WIP)

- [ ]  Create cases
  
  - [ ] Run the tool with a json and set XML formar
  - [ ] Run the tool with not include input (ex. .txt)
  - [ ] Run the tool with an empty input
  - [ ] Run the tool with rare characters
  - [ ] Run the tool with an invalid json
  - [ ] Run the tool with an invalid xml

</details>

<details><summary>Research behavior</details>
The tool is not finished yet. I ran it manually but I got an error that is being analyzed by the Core team.
</details>

**Comment by BelenValdivia** [comment]
## Task 2 : Validate feed content
- Started test to validate NVD feed content

**Comment by BelenValdivia** [comment]
10/14/2022
- Worked in cve 5 format validation test:
  - Solved problems with references in JSON schema
  - Added test cases with different feed inputs
  - Updated branch  https://github.com/wazuh/wazuh-qa/tree/3307-wazuh-content-validations

**Comment by BelenValdivia** [comment]
10/17/2022
- Added validation for problem types in validating content test
- On hold due to manual testing

**Comment by BelenValdivia** [comment]
10/19/2022
- Research how to get a specific CVE in NVD through API:
  https://nvd.nist.gov/developers/vulnerabilities
- Tested it manually

**Comment by BelenValdivia** [comment]
10/20/2022
- Added a test case that downloads the feed from the vendor API and checks if the tool output is correct.
- Added test case for rejected feeds

**Comment by BelenValdivia** [comment]
## Conclusion: First Iteration

3 modules were added:

1. `test_validate_cve_format.py`: This module checks if an input feed (mocked or not), after running the tool, the output feed has the correct format CVE 5.
2. `test_validate_content.py`: This module checks if the output feed, after running the tool has the correct content compared with the input feed.
3. `test_invalid_feed.py`: This module checks that when the tool receives an invalid feed, it fails

Each module has the following test functions with its set of test cases:

- `test_validate_cve_format.py`:
  - `test_format_cve5()`: Checks if when runs the tool with a mocked feed for each vendor, the output feed has the correct format
    - Test cases:
      - Check output format NVD feed
      - Check output format Debian feed
      - Check output format Canonical feed
      - Check output format Alas feed
      - Check output format RedHat feed
      - Check output format Arch feed
      - Check output format MSU feed
      
  - `test_format_vendor_feed`:  Checks if when runs the tool with a real feed downloaded from each vendor page, the output feed has the correct format.
     - Test cases:
       - Check output format NVD feed
       - Check output format Debian feed
       - Check output format Canonical feed
       - Check output format Alas feed
       - Check output format RedHat feed
       - Check output format Arch feed
       - Check output format MSU feed
      
- `test_validate_feed_content.py`:
  - `test_feed_content()`: Checks if the output feed, after running the tool has the correct content compared with the input feed (Basic content depends on the state that can be PUBLISHED or REJECTED).
    - Test cases:
       - Check output content NVD feed
       - Check output content Debian feed
       - Check output content Canonical feed
       - Check output content Alas feed
       - Check output content RedHat feed
       - Check output content Arch feed
       - Check output content MSU feed

- `test_invalid_feed.py`:
  - `test_invalid_feed()`: Checks invalid inputs feed
    - Test cases:
       - Check an empty feed
       - Check invalid JSON feed
       - Check invalid XML feed
       - Check invalid format feed (txt extension)
      
- 

***

This issue will remain `Blocked` until the Core team finish development (https://github.com/wazuh/wazuh-content/issues/2 and https://github.com/wazuh/wazuh-content/issues/149), and when this issue is taken up again it will be necessary:

- Test the migration tool manually again to check that has no errors
- Test the migration tool with an invalid input format and update the test
- Mock the following inputs for the test:
  - A feed with state rejected
  - A feed for each vendor (except NVD, it is already searched) 
- Search how to download a feed from the vendor page (except NVD, it is already searched) 

  

***

This first approach has been developed in: [3307-wazuh-content-validations](https://github.com/wazuh/wazuh-qa/tree/3307-wazuh-content-validations)
