### ISSUE TITLE
Vulnerability detector refactor - Validate scans and database with the new structure

### ISSUE THREAD

**Issue by BelenValdivia** [wazuh/wazuh-qa#3309]
The tests that are proposed in the issue are related to event-driven scans in the Vulnerability detector refactor.

### Proposed tests (IT):

- New scan in each new package installed
- New scan in each updated package
- New scan on every package removed
- New scan in each hotfix installed
- New scan on every hotfix removed
- Validate that a new scan is done in each feed update
- Check that the scan result is indexed

### Tasks

- [x] Research available information on the scanning process
- [x] Mock the necessary information
- [x] Create test cases and test

**Comment by mauromalara** [comment]
Update 13/10/2022

...

**Comment by mauromalara** [comment]
### Tasks results

<details><summary>Update 13/10/2022</summary>

<br>

#### Research available information on the scanning process

The scanner will be event-oriented, that is, every time an event is generated, the Vulnerability Detector (VD) will scan it and will publish the result.

So it's necessary to define how to:
- Generate events in the OS related to packages/hotfixes or in the feed
- Check the result of the scan

#### Mock the necessary information



</details>

**Comment by mauromalara** [comment]
## Update 14/10/2022

### Create test cases and test

- Start working on test structure

**Comment by mauromalara** [comment]
## Update 17/10/2022

### Create test cases and test

- Meeting with Nicolás to address some doubts
- Created basic structure:
```
tests/integration/test_vulnerability_detector_v2/
├── data
│   ├── configuration (contains all necessary configurations to be applied)
│   └── test_cases
│       └── cases_scan_on_event_<OS>.yaml
└── test_scanner
    ├── test_scan_on_event.py
    └── test_scan_result.py
```
- Tests created:
  - `test_scan_on_event`: checks that VD starts a scan when a new event is generated
    - Cases:
      - New scan in each new package installed
      - New scan in each updated package
      - New scan on every package removed
      - New scan in each hotfix installed (Windows only)
      - New scan on every hotfix removed (Windows only)
      - Validate that a new scan is done in each feed update
  - `test_scan_result`: checks that the VD scan result is indexed/stored correctly (both the format and the target where it is stored, indexer or database)
    - Cases:
      - A vulnerable package is upgraded to a fixed version and marked as solved
      - A non-vulnerable package does not appear in the scan result
      - A non-vulnerable package is upgraded to a vulnerable version and marked as vulnerable

**Comment by mauromalara** [comment]
## Update 19/10/2022

Added test cases:
- Validate that the scan is triggered in all agents when the vulnerability affects all of them

CA confirmed:
- The scan will be run even if the last execution of `syscollector` is old

**Comment by mauromalara** [comment]
## Conclusion
