### ISSUE TITLE
Change authd.pass ownership and permissions

### ISSUE THREAD

**Issue by miguelfdez99** [wazuh/wazuh-qa#3317]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|               4.4         |            https://github.com/wazuh/wazuh-packages/issues/1787            |           https://github.com/wazuh/wazuh/pull/14967         |

# Description

Installing the wazuh-agent using the deployment variable ```WAZUH_REGISTRATION_PASSWORD``` sets wrong ownership and permissions, now it is expected that the permissions are set to ```640``` and the ownership to ```root:wazuh```

# Checks

The following checks have been done in multiple scenarios: production, after upgrading the product with the bug(with the fix), and a fresh installation that contains the fix. Also, in Windows environment they have been tested, just verifying that it is not broken

## Proposed checks

- [x] authd.pass ownership is root:wazuh
- [x] authd.pass permissions are set to ```640```

## Additional checks

- [x] Check that agents enroll using `WAZUH_REGISTRATION_PASSWORD`
- [x] Check that  password can be empty
- [x] Check that password can has spaces

## Expected results

````
root@7c5749dadb1d:/# ll /var/ossec/etc/
total 56
drwxrwx---  3 wazuh wazuh  4096 Sep 19 14:05 ./
drwxr-x--- 15 root  wazuh  4096 Sep 19 14:04 ../
-rw-r-----  1 root  wazuh    10 Sep 19 14:04 authd.pass
-rw-r-----  1 wazuh wazuh    86 Sep 19 14:05 client.keys
-rw-r-----  1 root  wazuh 13408 Sep 19 11:49 internal_options.conf
-rw-r-----  1 root  wazuh   320 Sep 19 11:49 local_internal_options.conf
-rw-r-----  1 root  wazuh   118 Sep 19 11:49 localtime
-rw-rw----  1 root  wazuh  5459 Sep 19 14:04 ossec.conf
drwxrwx---  2 root  wazuh  4096 Sep 19 14:05 shared/
-rw-r-----  1 root  wazuh  1367 Sep 19 11:49 wpk_root.pem
````

## Configuration and considerations

Generate the wazuh-agent package using the branch of the PR https://github.com/wazuh/wazuh/pull/14967

**Comment by roronoasins** [comment]
## Review data

| Tester | PR commit               | 
|--------|-------------------------|
| @roronoasins   |  [ce045ec](https://github.com/wazuh/wazuh/pull/14967/commits/ce045ecc1f45f8001861dec2c8a5742a7c659039)   | 

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
|  Amazon Linux  | 2 | `AWS` | `ami-06cfe42abdba039eb`| Deployed and provisioned with internal pipeline |

### Tested packages

| `wazuh-manager` | `wazuh-agent` | 
|-----------------|---------------|
|  [4.4.0 - deb](https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/deb/var/)  | [4.4.0 - deb](https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/)  | 

### Status

- [x] In progress (@roronoasins)
- [ ] Pending Review
- [ ] QA team leader approved (@damarisg)
- [ ] QA manager approved (@jmv74211)
- [ ] Development team leader approved

### Conclusion :large_blue_circle:

**Comment by roronoasins** [comment]
# Tasks

## Unfixed version

<details><summary>Check that `authd.pass` ownership is `root:wazuh` :red_circle:</summary>

1. Install the agent using `WAZUH_REGISTRATION_PASSWORD`

    ```
    root@ip-172-31-15-10:/home/qa# WAZUH_MANAGER="172.31.12.94" WAZUH_REGISTRATION_PASSWORD="123456Aa." apt install ./wazuh-agent_4.3.7-1_amd64.deb 
    Reading package lists... Done
    Building dependency tree... Done
    Reading state information... Done
    Note, selecting 'wazuh-agent' instead of './wazuh-agent_4.3.7-1_amd64.deb'
    The following packages were automatically installed and are no longer required:
    libpython2-dev libpython2.7 libpython2.7-dev linux-image-5.13.0-1021-aws linux-modules-5.13.0-1021-aws python2-dev python2.7-dev
    Use 'sudo apt autoremove' to remove them.
    The following NEW packages will be installed:
    wazuh-agent
    0 upgraded, 1 newly installed, 0 to remove and 88 not upgraded.
    Need to get 0 B/8877 kB of archives.
    After this operation, 29.6 MB of additional disk space will be used.
    Get:1 /home/qa/wazuh-agent_4.3.7-1_amd64.deb wazuh-agent amd64 4.3.7-1 [8877 kB]
    Preconfiguring packages ...      
    Selecting previously unselected package wazuh-agent.
    (Reading database ... 120124 files and directories currently installed.)
    Preparing to unpack .../wazuh-agent_4.3.7-1_amd64.deb ...
    Unpacking wazuh-agent (4.3.7-1) ...
    Setting up wazuh-agent (4.3.7-1) ...
    Scanning processes...                                                                                                                                                                                         
    Scanning linux images...                                                                                                                                                                      
    Running kernel seems to be up-to-date.

    No services need to be restarted.

    No containers need to be restarted.

    No user sessions are running outdated binaries.

    No VM guests are running outdated hypervisor (qemu) binaries on this host.      
    ```  

2. Check `authd.pass` ownership

    ```
    root@ip-172-31-15-10:/home/qa# ll /var/ossec/etc/
    total 52
    drwxrwx---  3 wazuh wazuh  4096 Sep 20 14:32 ./
    drwxr-x--- 15 root  wazuh  4096 Sep 20 14:32 ../
    -rw-r--r--  1 root  root     10 Sep 20 14:32 authd.pass
    -rw-r-----  1 root  wazuh     0 Aug 19 08:02 client.keys
    -rw-r-----  1 root  wazuh 13478 Aug 19 08:02 internal_options.conf
    -rw-r-----  1 root  wazuh   320 Aug 19 08:02 local_internal_options.conf
    -rw-r-----  1 root  wazuh   114 Mar 21  2022 localtime
    -rw-rw----  1 root  wazuh  5764 Sep 20 14:32 ossec.conf
    drwxrwx---  2 root  wazuh  4096 Sep 20 14:32 shared/
    -rw-r-----  1 root  wazuh  1229 Aug 19 08:02 wpk_root.pem
    ```

    > As we could see, the `authd.pass` file has wrong ownership. It has `root:root` but it should be `root:wazuh`.
    > ```
    > -rw-r--r--  1 root  root     10 Sep 20 14:32 authd.pass
    > ```


</details>

<details><summary>Check that authd.pass permissions are set to `640` :red_circle:</summary>

1. Install the agent using `WAZUH_REGISTRATION_PASSWORD`

    ```
    root@ip-172-31-15-10:/home/qa# WAZUH_MANAGER="172.31.12.94" WAZUH_REGISTRATION_PASSWORD="123456Aa." apt install ./wazuh-agent_4.3.7-1_amd64.deb 
    Reading package lists... Done
    Building dependency tree... Done
    Reading state information... Done
    Note, selecting 'wazuh-agent' instead of './wazuh-agent_4.3.7-1_amd64.deb'
    The following packages were automatically installed and are no longer required:
    libpython2-dev libpython2.7 libpython2.7-dev linux-image-5.13.0-1021-aws linux-modules-5.13.0-1021-aws python2-dev python2.7-dev
    Use 'sudo apt autoremove' to remove them.
    The following NEW packages will be installed:
    wazuh-agent
    0 upgraded, 1 newly installed, 0 to remove and 88 not upgraded.
    Need to get 0 B/8877 kB of archives.
    After this operation, 29.6 MB of additional disk space will be used.
    Get:1 /home/qa/wazuh-agent_4.3.7-1_amd64.deb wazuh-agent amd64 4.3.7-1 [8877 kB]
    Preconfiguring packages ...      
    Selecting previously unselected package wazuh-agent.
    (Reading database ... 120124 files and directories currently installed.)
    Preparing to unpack .../wazuh-agent_4.3.7-1_amd64.deb ...
    Unpacking wazuh-agent (4.3.7-1) ...
    Setting up wazuh-agent (4.3.7-1) ...
    Scanning processes...                                                                                                                                                                                         
    Scanning linux images...                                                                                                                                                                      
    Running kernel seems to be up-to-date.

    No services need to be restarted.

    No containers need to be restarted.

    No user sessions are running outdated binaries.

    No VM guests are running outdated hypervisor (qemu) binaries on this host.      
    ```  

2. Check the `authd.pass` permissions

    ```
    root@ip-172-31-15-10:/home/qa# ll /var/ossec/etc/
    total 52
    drwxrwx---  3 wazuh wazuh  4096 Sep 20 14:32 ./
    drwxr-x--- 15 root  wazuh  4096 Sep 20 14:32 ../
    -rw-r--r--  1 root  root     10 Sep 20 14:32 authd.pass
    -rw-r-----  1 root  wazuh     0 Aug 19 08:02 client.keys
    -rw-r-----  1 root  wazuh 13478 Aug 19 08:02 internal_options.conf
    -rw-r-----  1 root  wazuh   320 Aug 19 08:02 local_internal_options.conf
    -rw-r-----  1 root  wazuh   114 Mar 21  2022 localtime
    -rw-rw----  1 root  wazuh  5764 Sep 20 14:32 ossec.conf
    drwxrwx---  2 root  wazuh  4096 Sep 20 14:32 shared/
    -rw-r-----  1 root  wazuh  1229 Aug 19 08:02 wpk_root.pem
    ```

    > As we could see, the `authd.pass` file has the expected wrong permissions. It should be `-rw-r-----`(`640`).
    > ```
    > -rw-r--r--  1 root  root     10 Sep 20 14:32 authd.pass
    > ```

</details>

## Upgrade to fixed version

<details><summary>Check that authd.pass ownership is root:wazuh :red_circle:</summary>

</details>

<details><summary>Check that authd.pass permissions are set to 640 :red_circle:</summary>

</details>

## Fresh install fixed version

<details><summary>Check that authd.pass ownership is root:wazuh :red_circle:</summary>

</details>

<details><summary>Check that authd.pass permissions are set to 640 :red_circle:</summary>

</details>

**Comment by jmv74211** [comment]
## QA review

- **Type**: Manual testing.
- **Status**: Requested improvements  🟡 
- **Comments**: We have found reasons for which we cannot approve the PR. These are as follows:
    - *(1)* When upgrading from 4.3.7 to version with the fix, the `authd.pass` does not have the expected permissions and ownership.
    - *(2)* When using an empty password for agent authentication, the authd.pass file is not created. So the agent won't connect.
    - *(3)* When using a password that contains spaces within it for agent authentication, the authd.pass file is not created. So the agent won't connect.

This will be discussed with the development team, and the PR will be approved or not on this basis.

**Comment by jmv74211** [comment]
Talking to the development team, the following considerations will be taken:

- **(1) When upgrading from 4.3.7 to version with the fix, the authd.pass does not have the expected permissions and ownership**.

  This is a behavior that is considered normal, since it is a file that in principle the user creates and owns and that after the upgrade should not be modified can cause unexpected behavior for the user.
  
- **(2) When using an empty password for agent authentication, the authd.pass file is not created. So the agent won't connect**.

  First, you have to test if `authd` is the one that allows such configuration. If yes, then the expected behavior is that it works correctly for both `enrollment`, `agent-auth` and auto-deployment variables.
  
  Whether or not it should actually be allowed is another matter, the important thing is that if it is not an expected case, then `authd` will report the error and will not start.
  
- **(3) When using a password that contains spaces within it for agent authentication, the authd.pass file is not created. So the agent won't connect**.

  The same as for case (2).

**Comment by roronoasins** [comment]
The (2) case discussed above, that was tested with the deployment variable will be tested creating the `authd.pass` and using the `agent-auth` from the agent and try to enroll. With these cases we can check the auth behavior, errors, logs, etc.

<details><summary>Perform the enrollment with <code>agent-auth</code></summary

- Agent side
    1. Install the agent
    2. Run `agent-auth`
        ```
        root@agentauth:/home/vagrant# /var/ossec/bin/agent-auth -m "192.168.56.10" -P "" -d
        2022/10/24 14:06:26 agent-auth[9268] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
        2022/10/24 14:06:26 agent-auth[9268] main-client.c:228 at main(): DEBUG: Wazuh home directory: /var/ossec
        2022/10/24 14:06:26 agent-auth[9268] main-client.c:271 at main(): INFO: Started (pid: 9268).
        2022/10/24 14:06:26 agent-auth[9268] keys.c:328 at OS_ReadKeys(): DEBUG: (1751): File client.keys not found or empty.
        2022/10/24 14:06:26 agent-auth[9268] enrollment_op.c:121 at w_enrollment_request_key(): INFO: Requesting a key from server: 192.168.56.10
        2022/10/24 14:06:26 agent-auth[9268] ssl.c:83 at os_ssl_keys(): DEBUG: Returning CTX for client.
        2022/10/24 14:06:26 agent-auth[9268] enrollment_op.c:243 at w_enrollment_connect(): DEBUG: (1209): Connected to the Auth service at '192.168.56.10:1515'.
        2022/10/24 14:06:26 agent-auth[9268] enrollment_op.c:481 at w_enrollment_verify_ca_certificate(): DEBUG: Registering agent to unverified manager
        2022/10/24 14:06:26 agent-auth[9268] enrollment_op.c:272 at w_enrollment_send_message(): INFO: Using agent name as: agentauth
        2022/10/24 14:06:26 agent-auth[9268] enrollment_op.c:312 at w_enrollment_send_message(): DEBUG: Request sent to manager
        2022/10/24 14:06:26 agent-auth[9268] enrollment_op.c:337 at w_enrollment_process_response(): INFO: Waiting for server reply
        2022/10/24 14:06:26 agent-auth[9268] enrollment_op.c:348 at w_enrollment_process_response(): ERROR: Invalid password (from manager)
        2022/10/24 14:06:26 agent-auth[9268] enrollment_op.c:348 at w_enrollment_process_response(): ERROR: Unable to add agent (from manager)
        ```

- Manager side
    1. Configure the manager auth with empty pass
    2. Restart the manager
    3. After running `agent-auth` check the `ossec.log`
        ```
        2022/10/24 14:06:26 wazuh-authd: INFO: New connection from 192.168.56.22
        2022/10/24 14:06:26 wazuh-authd: ERROR: Invalid password provided by 192.168.56.22. Closing connection.
        ```

</details>

<details><summary>Perform the enrollment by writing the authd.pass</summary>

- Agent side
    1. Create the authd.pass with an empty pass
        ```
        root@agentauth:/home/vagrant# echo "" > /var/ossec/etc/authd.pass
        root@agentauth:/home/vagrant# chmod 640 /var/ossec/etc/authd.pass
        root@agentauth:/home/vagrant# chown root:wazuh /var/ossec/etc/authd.pass
        ```
    2. Add manager's ip
    3. Restart the agent
    4. Check the `ossec.log`
        ```
        2022/10/24 14:15:47 wazuh-agentd: INFO: Requesting a key from server: 192.168.56.10
        2022/10/24 14:15:47 wazuh-agentd: INFO: Using password specified on file: etc/authd.pass
        2022/10/24 14:15:47 wazuh-agentd: INFO: No authentication password provided
        2022/10/24 14:15:47 wazuh-agentd: INFO: Using agent name as: agentauth
        2022/10/24 14:15:47 wazuh-agentd: INFO: Waiting for server reply
        2022/10/24 14:15:47 wazuh-agentd: ERROR: Invalid password (from manager)
        2022/10/24 14:15:47 wazuh-agentd: ERROR: Unable to add agent (from manager)
        ```


- Manager side
    1. Check the agent status
        ```
        root@managerauth:/home/vagrant# /var/ossec/bin/agent_control -l

        Wazuh agent_control. List of available agents:
        ID: 000, Name: managerauth (server), IP: 127.0.0.1, Active/Local
        ID: 001, Name: agentauth, IP: any, Never connected
        ```

    2. Check the `ossec.log`
        ```
        2022/10/24 14:13:42 wazuh-authd: INFO: New connection from 192.168.56.22
        2022/10/24 14:13:42 wazuh-authd: ERROR: Invalid password provided by 192.168.56.22. Closing connection.
        ````

</details>

With the empty pass configuration the agents won't enroll

**Comment by jmv74211** [comment]
According to the analysis of @roronoasins, it has been found that (1) and (2) is a generic problem that does not affect this particular development, but (3) seems to be a problem only of the auto-deployment variables, so we request to the @wazuh/cicd  team to investigate and fix it to approve this development.

**Comment by roronoasins** [comment]
## Testing after required changes
The (3) case discussed above, needs to be tested again after the requested changes.

## Results

### Linux

<details><summary>Check that agent enrolls as expected when using spaces within <code>authd.pass</code> :green_circle:</summary>

1. Configure the manager to use password authentication

    ```
    echo "123 asd" > /var/ossec/etc/authd.pass
    chmod 640 /var/ossec/etc/authd.pass
    chown root:wazuh /var/ossec/etc/authd.pass
    ```

2. Set the pass auth method using the `ossec.conf`
    ```
    <use_password>yes</use_password>
    ```

3. Restart the manager

    ```
    systemctl restart wazuh-manager
    ```

4. Install the agent using `WAZUH_REGISTRATION_PASSWORD`

    ```
    WAZUH_MANAGER="172.31.7.232" WAZUH_REGISTRATION_PASSWORD="123 asd" apt install ./wazuh-agent_4.4.0-0.commitce045ec_amd64.deb 
    ```

5. Check the enrollment logs

    ```
    2022/11/04 10:27:54 wazuh-authd: INFO: New connection from 172.31.6.117
    2022/11/04 10:27:54 wazuh-authd: INFO: Received request for a new agent (ip-172-31-6-117) from: 172.31.6.117
    2022/11/04 10:27:54 wazuh-authd: INFO: Agent key generated for 'ip-172-31-6-117' (requested by any)
    2022/11/04 10:27:58 wazuh-remoted: INFO: (1409): Authentication file changed. Updating.
    2022/11/04 10:27:58 wazuh-remoted: INFO: (1410): Reading authentication keys file.
    ```

6. The `auth.pass` is now created

    ```
    root@ip-172-31-6-117:/home/qa# ll /var/ossec/etc/authd.pass
    -rw-r----- 1 root wazuh 8 Nov  4 10:18 /var/ossec/etc/authd.pass

    ```

7. Verify that the agent is active
```
root@ip-172-31-11-241:/home/qa# /var/ossec/bin/agent_control -l

Wazuh agent_control. List of available agents:
   ID: 000, Name: ip-172-31-11-241 (server), IP: 127.0.0.1, Active/Local
   ID: 001, Name: ip-172-31-6-117, IP: any, Active
```

</details>

### Linux

<details><summary>Check that agent enrolls as expected when using spaces within <code>authd.pass</code> :red_circle:</summary>

1. Configure the manager to use password authentication

    ```
    echo "123 asd" > /var/ossec/etc/authd.pass
    chmod 640 /var/ossec/etc/authd.pass
    chown root:wazuh /var/ossec/etc/authd.pass
    ```

2. Set the pass auth method using the `ossec.conf`
    ```
    <use_password>yes</use_password>
    ```

3. Restart the manager

    ```
    systemctl restart wazuh-manager
    ```

4. Install the agent using `WAZUH_REGISTRATION_PASSWORD`

    ```
    .\wazuh-agent-4.4.0-0.commit359bd37.msi /q WAZUH_MANAGER="172.31.11.241" WAZUH_REGISTRATION_PASSWORD="123 asd" 
    ```
    ![2022-11-04_12-15](https://user-images.githubusercontent.com/33318890/199962176-3eb9e402-16d5-42f3-a1f0-e5004ed19c6f.png)



</details>

## Conclusion :red_circle:

It seems to be solved in linux but in Windows passwords without spaces can't be used, the installer helper is triggered.

**Comment by roronoasins** [comment]
## Testing after required changes

After the Windows case previously reported, @DFolchA did research in https://github.com/wazuh/wazuh/issues/15304 about the PowerShell issue, so we need to verify that it is correct.

## Results

<details><summary>Use single quotes plus double to pass the password with spaces :green_circle:</summary>

1. Configure the manager to use password authentication

    ```
    echo "123 asd" > /var/ossec/etc/authd.pass
    chmod 640 /var/ossec/etc/authd.pass
    chown root:wazuh /var/ossec/etc/authd.pass
    ```

2. Set the pass auth method using the `ossec.conf`
    ```
    <use_password>yes</use_password>
    ```

3. Restart the manager

    ```
    systemctl restart wazuh-manager
    ```

4. Install the agent using `WAZUH_REGISTRATION_PASSWORD`

    ```
    .\wazuh-agent-4.4.0-0.commit359bd37.msi /q WAZUH_MANAGER="172.31.2.204" WAZUH_REGISTRATION_PASSWORD='"123 asd"'
    ```

    `ossec.log`:
    ```
    2022/11/07 15:21:34 wazuh-authd: INFO: New connection from 172.31.6.178
    2022/11/07 15:21:34 wazuh-authd: INFO: Received request for a new agent (EC2AMAZ-N9OLJ1L) from: 172.31.6.178
    2022/11/07 15:21:34 wazuh-authd: INFO: Agent key generated for 'EC2AMAZ-N9OLJ1L' (requested by any)
    ```

</details>

<details><summary>Use triple-double quotes to pass the password with spaces :green_circle:</summary>

1. Configure the manager to use password authentication

    ```
    echo "123 asd" > /var/ossec/etc/authd.pass
    chmod 640 /var/ossec/etc/authd.pass
    chown root:wazuh /var/ossec/etc/authd.pass
    ```

2. Set the pass auth method using the `ossec.conf`
    ```
    <use_password>yes</use_password>
    ```

3. Restart the manager

    ```
    systemctl restart wazuh-manager
    ```

4. Install the agent using `WAZUH_REGISTRATION_PASSWORD`

    ```
    .\wazuh-agent-4.4.0-0.commit359bd37.msi /q WAZUH_MANAGER="172.31.2.204" WAZUH_REGISTRATION_PASSWORD="""123 asd"""
    ```

5. Verify that agent is connected
    
    ```
    root@ip-172-31-2-204:/home/qa# /var/ossec/bin/agent_control -l

        Wazuh agent_control. List of available agents:
        ID: 000, Name: ip-172-31-2-204 (server), IP: 127.0.0.1, Active/Local
        ID: 001, Name: EC2AMAZ-N9OLJ1L, IP: any, Active

    List of agentless devices:
    ```

    `ossec.log`:
    ```
    2022/11/07 15:26:45 wazuh-authd: INFO: New connection from 172.31.6.178
    2022/11/07 15:26:45 wazuh-authd: INFO: Received request for a new agent (EC2AMAZ-N9OLJ1L) from: 172.31.6.178
    2022/11/07 15:26:45 wazuh-authd: INFO: Agent key generated for 'EC2AMAZ-N9OLJ1L' (requested by any)
    ```

</details>

## Conclusion :green_circle: 

We could verify that this issue can be avoided by the options provided by @DFolchA in https://github.com/wazuh/wazuh/issues/15304. All seems to be working as we could expect.

**Comment by jmv74211** [comment]
## Closing conclusion 👍🏼  

|| |
|-|-|
| 🟢 | Solved 
| 🔵 | Proposed to be fixed in future versions or developments | 
| ⚫ |Discarded |

The development has been approved taking into account the following considerations:

**(1) When upgrading from 4.3.7 to version with the fix, the authd.pass does not have the expected permissions and ownership.** ⚫ 

After discussing with the development team, this is a behavior that is considered normal, since it is a file that in principle the user creates and owns so after the upgrade should not be modified can cause unexpected behavior for the user.

**(2) When using an empty password for agent authentication, the authd.pass file is not created. So the agent won't connect.** 🔵

After discussing with the development team, it was felt that the best way to fix this is for the `authd` module itself to check this at startup, and fail if the status is invalid. The following issue has been opened [wazuh#15230](https://github.com/wazuh/wazuh/issues/15230) and will be fixed in future releases.

**(3) When using a password that contains spaces, it does not work** 🟢

This has been fixed in this current development https://github.com/wazuh/wazuh/pull/14967/commits/359bd372d8b9a014c141c9c8024bd996966007bb

**(4) When using a password that contains spaces, it does not work for Windows autodeploy variable** 🔵

After researching this issue, it appears that in powershell it is necessary to use a different syntax with the `"` characters. The following issue has been opened [wazuh-documentation#5738](https://github.com/wazuh/wazuh-documentation/issues/5738) to add a note in the corresponding section of the documentation to tell the user what to do in this case.
