### ISSUE TITLE
QA testing - Fix data race conditions reported by ThreadSanitizer

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-qa#3326]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|  4.4.0  |https://github.com/wazuh/wazuh/issues/12731| https://github.com/wazuh/wazuh/pull/14981 |

## Description

This PR includes a series of changes that shall fix multiple race conditions detected by ThreadSanitizer. It should not cause visible changes (except fixing undefined behavior issues detected in the past).

## Proposed checks
- [x] Remoted should keep working as before. No lateral effects should appear.

## Steps to reproduce

The steps to launch multiple agents with Docker and to run Remoted on ThreadSanitizer are described at https://github.com/wazuh/wazuh/pull/14981.

## Expected results

No visible changes should be detected. When running on ThreadSanitizer, no reports should appear.

**Comment by QU3B1M** [comment]
## Review data

| Tester | PR commit               | 
|--------|-------------------------|
| @QU3B1M   |  [0d18914](https://github.com/wazuh/wazuh/pull/14981/commits/0d18914449c91a9b8c73d452f961d7abb44b481f)   | 

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
|  Ubuntu  | 20.04 | ` LOCAL \|  Vagrant` | [ubuntu/focal64](https://app.vagrantup.com/ubuntu/boxes/focal64)


### Status

- [x] In progress @QU3B1M 
- [ ] Pending Review
- [ ] QA team leader approved @damarisg 
- [ ] QA manager approved @jmv74211 
- [ ] Development team leader approved @TomasTurina 

### Conclusion

**Comment by QU3B1M** [comment]
# Task results

## Remoted should keep working as before. No lateral effects should appear.


| Os | Component | Executions | Date | By | Notes |
|--|--|--|--|--|--|
 | `Centos8`  | Manager |  [:green_circle: ](https://ci.wazuh.info/job/Packages_builder_tier/2382) [:green_circle: ](https://ci.wazuh.info/job/Packages_builder_tier/32160) [:green_circle: ](https://ci.wazuh.info/job/Packages_builder_tier/32155)  |  10/08/2022 |  @QU3B1M  |   |

**Comment by jmv74211** [comment]
🟢 Everything seems to be working properly
