### ISSUE TITLE
External modules integration tests proposal

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh-qa#3332]
We should add new integration tests for the AWS, Azure and GCP cloud modules.

There are no integration tests available for our AWS and Azure integrations at the time of writing this. Gcloud has some basic integration tests, but these are limited to simple testing, mostly related to the configuration itself.

Currently, every time we make an important change in the module or simply every time there is a new release, our team must perform intensive manual testing to ensure that everything is working properly. These manual tests are slow, cumbersome and prone to errors. That is why we consider it important to create a new suite of integration tests for all these modules to help us guarantee the quality and functionality of our modules in each new release.

Our intention is that each of these cloud integrations will have its own epic to track the development. This issue serves as a proposal to define the basic requirements and common topics for these epics.

## Key points

- The `Wazuh-QA` environment will be used for AWS testing. Azure and GCP to be determined.

- It will be necessary to define the different `Tiers` in which we intend to divide these tests. This should be done by the QA team or at least the criteria to be applied when determining when a test should belong to a particular tier or another should be properly defined.

- Check the following issues to get an idea of the tests we want to automate:
https://github.com/wazuh/wazuh/issues/12529
https://github.com/wazuh/wazuh/issues/13325
https://github.com/wazuh/wazuh/issues/14376

## Proposed structure

Regarding the repository dependency files and tools, there is a `deps/wazuh_testing/wazuh_testing/gcloud.py` file that should be deprecated. Instead the following structure will be created, adding modules containing the necessary auxiliary functions for the respective tests:

<details>
    <summary>deps structure</summary>

    deps/
	    wazuh_testing/
		    wazuh_testing/
			    modules/
				    aws/
					    __init__.py 
					    <any required module here>
					    
				    azure/
					    __init__.py 
					    <any required module here>
					    
				    gcloud/
					    __init__.py 
					    <any required module here>

</details>

With respect to the actual tests structure, we propose the following one:

<details>
    <summary>tests structure</summary>
    
    tests/
	    integration/
		    conftest.py
		    test_aws/
			    conftest.py
			    data/
				    configuration_template	
				    wazuh_conf.yml
				    ...
			    test_cloudtrail/
				    test_configuration.py
				    test_1.py
				    test_2.py
				    ...
			    test_guardduty/
				    test_configuration.py
				    test_1.py
				    test_2.py
				    ...
			    ...
			    test_cloudwatch/
				    test_configuration.py
				    test_1.py
				    test_2.py
				    ...
		    test_azure/
			    conftest.py
			    data/
				    configuration_template	
				    wazuh_conf.yml
				    ...
			    test_graph/
				    test_configuration.py
				    test_1.py
				    test_2.py
				    ...
			    test_log_analytics/
				    test_configuration.py
				    test_1.py
				    test_2.py
				    ...
			    test_storage/
				    test_configuration.py
				    test_1.py
				    test_2.py
				    ...
		    test_gcloud/
			    conftest.py
			    data/
				    configuration_template	
				    wazuh_conf.yml
				    ...
			    test_buckets/
				    test_configuration.py
				    test_1.py
				    test_2.py
				    ...
			    test_storage/
				    test_configuration.py
				    test_1.py
				    test_2.py
				    ...
</details>

For each cloud integration (AWS, Azure and GCP) a new test folder must be created, containing:
- A `data` folder containing all the files required for the tests to run, such as `ossec.conf` configuration files. 
- The tests themselves will be grouped in different directories according to the logic to be tested. 
- Each test will contain a test for the configuration and as many other tests for the functionality as needed.

## Tasks

- [x] Define the different `Tiers` into which we want to divide the tests and which type of test cases will be covered by each one.
- [x] Decide whether we should implement every single test case for all the `Tiers` or stick to one or more `Tiers` at the moment.
- [x] Study any changes that will be necessary for these tests to integrate correctly with Jenkins.
- [x] Determine and design which fixtures will need to be created for the different cloud integrations and if they will be placed in the generic conftest, in a common conftest for all the wodles or in a specific conftest for each module.
- [x] Define the final structure for these tests. Use the proposal as a draft.
- [x] Determine in which cloud environment the data for these tests will be created and stored for each cloud integration. Create new `Wazuh-QA` environments if necessary. Request the necessary permissions for the team members for these environments.

**Comment by CarlosRS9** [comment]
## Tier levels

We have discussed with the team how many tier levels we are going to use and which tests will be available for each tier level. Unfortunately, at the moment we have no firm criteria to determine which tiers should exist and what kind of tests each tier level covers across the entire repository. That is why we are going to start by defining the tiers ourselves, as a proposal, and if we need to change any of them, once QA team defines the criteria for the tier levels in the future, we will update them.

Analysing the current state of the existing tests in the repository, we can see that most of the test cases we have belongs to tier 0:
```
Tier 0 = 159
Tier 1 = 101
Tier 2 = 36
```

In the most recent tests the team have chosen to indicate the tier level of the test for each `test` function by setting `pytest.mark.tier(level=x)`, while in the old cases the tier level was defined at module level, so each of the tests contained in a single module had the same tier level. We consider the most appropriate way to do this is the first one, allowing us to group related tests in the same module, regardless of their tier level.


Having this in mind, to determine when a test belongs to one tier level or another, we will look at two criteria: test complexity and test execution time. Thus, we propose the following tier levels:

- `Tier 0`: Basic tests using the minimum configuration to guarantee that the integration works at its most basic level. Only those parameters that are essential would be included in the configuration. This will ensure that the python interpreter and its dependencies are compatible with the integrations, as well as the basic functionality of the configuration parser.

- `Tier 1`: Basic testing, but using the simplest configuration available for each of the parameters of each module. That is, the modules will be run with a basic value for parameters such as `only_logs_after`, `prefix` or the different parameters for credentials. The goal is to ensure that the basic functionality for each parameter works correctly.

- `Tier 2`: More advanced testing for each parameter available. For example, how the `only_logs_after` parameter behaves when the module is run twice in a row, checking that there are no duplicate logs; ensuring that using a prefix ignores the other directories in a bucket, and so on. Here would be the more complex combinations that we currently test by hand, in order to ensure that the module behaves properly in complex but critical scenarios.


All of the manual tests that we currently carry out during the manual tests that we perform for each Release candidate would fit in these 3 tiers, so we consider that it would be appropriate to implement each of these tiers in the developments that will take place once this proposal is closed.

**Comment by CarlosRS9** [comment]
## Jenkins integration

Regarding the modifications to our Jenkins to incorporate the new integration tests into the pipeline, it will be necessary to apply the following modifications to the different relevant files. Some of these changes will only be necessary for AWS and Azure, as GCloud currently already has integration tests that will be replaced.


- `jenkins-files/tests/test_integration.groovy`: It will be necessary to add a piece of code for each of the new integrations similar to the one that already exists for Gcloud. This code is in charge of the provisioning of the credentials for the environments through the different `playbooks.PROVISION_{AWS|AZURE|GCLOUD}_TESTS_PLAYBOOK` entities.

- `src/org/wazuh/Check.groovy`: We need to add AWS and Azure to the test SUITE of this file and create the corresponding `amd64_integration_test_{aws|azure}_manager`.

- `src/org/wazuh/QA/Data/IntegrationTestData.groovy`: Add the path to the new integration tests as well as modify the existing one for Gcloud. In addition, in this file we also have to define the configuration for `local_internal_conf` for Azure and AWS as it already exists for gcloud.


- `vars/pipelineHelper.groovy`: Add Azure and AWS to the `test_integration` list.
	

- `vars/playbooks.groovy`: Add the different `PROVISION_{AWS|AZURE}_TESTS_PLAYBOOK` for AWS and Azure.


Finally, we will also need to create the provisioning files for the AWS and Azure credentials.

**Comment by CarlosRS9** [comment]
## GCloud integration tests

Regarding the our GCloud module implementation, we can divide it into 2 different parts: `Pub/Sub` and `Storage`. Both work differently and use different resources. `Pub/Sub` makes use of `topics`, `subscriptions` and `sinks`, while `Storage` makes use of `buckets`. These resources will be created and stored in our `Wazuh-dev` environment as we currently do not have a `Wazuh-QA` environment.

There is one factor that differentiates the GCloud integration tests from those for AWS and Azure, and that is that we already have simple integration tests for GCloud available. Specifically, the tests we have are currently testing the `Pub/Sub` integration. We will need to replace these existing tests with new ones that are consistent with the ones we are going to implement for AWS and Azure, while testing all the important use cases for both `Pub/Sub` and `Storage`.


### Pub/Sub testing

Currently our existing test publishes messages to a topic called `qa_integration_tests` and then runs the integration to consume those messages.

To simplify the implementation of the new tests we will opt to create a topic in the `Wazuh-dev` environment, similar to the current `qa_integration_tests` which will not have any `sink` associated with it. This will allow us to have a clean topic in which no messages will be stored, preventing the activity of the rest of the environment from affecting our tests. The test itself will publish messages with a proper structure, similar to how our current test works.

Our implementation of `Pub/Sub` does not use any database file as it is not necessary to avoid duplication of events due to the nature of the service.

We will need to create tests in which logs are processed for each of the different types of services that we support through `Pub/Sub`. The list of supported services can be found [here](https://documentation.wazuh.com/current/gcp/supported-services/index.html#supported-services-using-google-cloud-pub-sub).


### Storage

Similar to the AWS S3 implementation, for the `Storage` tests we will need to create a number of static resources during the beginning of development. These static resources will be processed by our integration during testing. As with AWS, we will also need to create resources at runtime for certain test cases. In these cases we will make use of fixtures that generate the necessary resources at runtime and finally remove them after successful or unsuccessful completion. 

Our `Storage` implementation makes use of a database file to avoid processing duplicated events. This file must be taken into consideration and must be updated or even deleted during some of the test cases.

We will need to create tests in which logs are processed for each of the different types of services that we support through `Storage`. The list of supported services can be found [here](https://documentation.wazuh.com/current/gcp/supported-services/index.html#supported-services-using-google-cloud-`storage`-buckets).



### Fixtures needed

- Create a log file with a valid structure (we could use templates) and upload it to a bucket. You will need to be able to specify both the bucket and the desired path within the bucket.
- Delete files in a bucket. This will mainly be used to purge our environments once testing is finished.
- Delete the database file, regardless of whether it exists or not. This will be used both to clean up the environment after testing and to run certain tests that will require several consecutive runs.
- Create a database file with custom data stored in it. This will be necessary to be able to run certain test cases such as only_logs_after, which will allow us to test how the module behaves depending on the possible states of the database.
- Manually invoke the module with the desired parameters. This will be necessary for level 1 testing.
- Publish a message in a given topic.
- Delete messages from a given topic. This will mainly be used to purge our environments after testing is complete.



### Conclusions
- We will use the `Wazuh-dev` environment to store the data.
- We will replace the existing tests with the new ones to extend the coverage and make them homogeneous with the new ones.
- We will use a topic without any sink for `Pub/Sub`.
- We will use static data for the `Storage` tests as much as possible.
- We need to create a number of fixtures and functions to be able to interact with the environment during certain complex tests.

**Comment by CarlosRS9** [comment]
## Azure integration tests

Our Azure module integrates 3 different Azure services: `Microsoft Graph`, `Log analytics` and `Storage`.

The main difference between our Azure module and the AWS and GCP modules is that while the integration with `Storage` makes use of the official Azure library to communicate with the cloud environment, the integrations for `Microsoft Graph` and `Log Analytics` are implemented differently. Specifically, these 2 integrations communicate with Azure through requests to the corresponding REST API.

### Required resources

Currently we do not have a `Wazuh-QA` environment for Azure as is the case with AWS. This is a problem when it comes to maintaining the integrity and immutability of the data for the tests. This is due to the fact that the results returned by the `Microsoft Graph` and `Log Analytics` APIs calls will reflect the changes that are produced in this environment manually by other users, such as the creation of new resources or the assignment of permissions. It would be advisable to use an isolated environment, where possible. This problem affects both `Microsoft Graph` and `Log Analytics` but not `Storage`, as a bucket with static data can be created and not be affected by the rest of the environment usage.

In addition, it's important to note that in order to properly test `sign-in logs` for `Microsoft Graph` we will need to have an Azure AD Premium P1 or P2 license, as this is a requirement to be able to download sign-in logs using the `Microsoft Graph` API.


### Microsoft Graph resources

In order to know how the Wazuh Azure module works in conjunction with the `Microsoft Graph` REST API, it is important to understand first what are the Azure AD activity reports and what kind of information they provide. Wazuh can process the logs from the following Azure AD activity reports, each one requiring different resources to be tested: `Directory audits`, `Sign-ins` and `Provisioning`.

To test this we will have to generate some events during the test executions as opposed to `Storage`, which can have and use static data instead.

We will need an Active Directory `App Registration` with the necessary API permissions, as indicated in [our documentation](https://documentation.wazuh.com/current/azure/activity-services/active-directory/graph.html#azure-configuration). This `App Registration` will be used both by the auxiliary tools or fixtures we have to create to modify the environment to generate events, and also by Wazuh to request and process the logs associated to those events.


#### Directory Audits

[Directory audit](https://learn.microsoft.com/en-us/graph/api/resources/directoryaudit?view=graph-rest-1.0) logs include audit logs generated by various services within Azure AD, including user, app, device and group management, privileged identity management, access reviews, terms of use, identity protection, password management, and self-service group management, and so on.

For our tests we can force the generation of events using Graph's own API. In particular we can make use of POST requests using endpoints such as [Create group](https://learn.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-1.0&tabs=http).



#### Sign-ins

As stated in the official Azure documentation [here](https://learn.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-1.0) application sign-in activity for a tenant [directory] are included and registered here. With this in mind, we could use our tests' own sign-in events generated by using the token to access `Microsoft Graph` or if not possible then manually trigger a sign-in event during the execution.

The [official Azure documentation](https://learn.microsoft.com/en-us/azure/active-directory/reports-monitoring/quickstart-access-log-with-graph-api) states that to ensure that we will find a record of the sign-in attempt we should wait for 5 minutes. We should bear this in mind when creating our tests.


Finally, as stated before, we will need to have an Azure AD Premium P1 or P2 license to download sign-in logs using the `Microsoft Graph` API.


#### Provisioning

The Provisioning logs represent actions performed by the Azure AD Provisioning service and its associated properties. To test this we have to configure and use the [Azure AD Provisioning service](https://learn.microsoft.com/en-us/azure/active-directory/app-provisioning/how-provisioning-works). The test will require the provisioning of a simple application using the Microsoft Graph API as indicated [here](https://learn.microsoft.com/en-us/azure/active-directory/app-provisioning/application-provisioning-configuration-api).

### Log Analytics


The following resources are required, configured and assigned permissions as indicated in [our official documentation](https://documentation.wazuh.com/current/azure/activity-services/services/log-analytics.html):


- `App Registration`: This will be used by the Wazuh module to access the Log Analytics logs using the corresponding token.

- `Log Analytics Workspace`: This is used to collect data from the different applications and services. 

These resources should be created at the beginning of the development and will be static. However, the tests themselves will need to trigger events during their execution, similar to Graph. A valid example would be the creation of a user or a group.

It is important to take into account that, as we said before, if we finally use the `Wazuh-dev` environment, this Workspace may capture other events triggered by actions from the rest of the users, so the tests will have to validate that the captured events correspond to the ones generated by the test themselves.


### Storage

The implementation of Azure Storage is similar to that of the AWS S3 buckets, so it will be possible to generate static resources. Specifically, it will be necessary to create and configure a storage bucket as well as to provision it with the relevant logs for the correct execution of the test. We must keep in mind that as with AWS certain tests will require the creation and deletion of logs in real time.

Finally, it is important to bear in mind that for this storage bucket we should avoid configuring any `Activity Log export` as doing so could contaminate our bucket with logs from activities outside the test itself.

### Fixtures needed

- Create a log file with a valid structure and upload it to a Storage bucket. We could use templates for this. It will be necessary to be able to specify both the bucket and the desired path within it.
- Delete files in a bucket. This will be used mainly to purge our environments once the tests are finished.
- Delete the database file. This will be used both for cleaning up the environment after tests and for running certain tests that will require multiple consecutive runs.
- Create a database file with custom data stored. This will be necessary to be able to perform certain test cases such as those of offset, which will allow us to check how the module behaves depending on the possible states of the database.
- Manually invoke the module with the desired parameters. This will be necessary for `Tier 1` tests.
- Force the creation of a sign-in event.
- Force the creation of a directory audit event, such as creating a new group. This will be also used for the Log Analytics tests.
- Force the creation of a provisioning event.


### Conclusions

- We could use the `Wazuh-dev` environment but it would be advisable to use a separate one.
- We will use static data for Storage tests and create realtime events for Graph and Log Analytics.
- We need to create a number of fixtures and functions to be able to interact with the AWS environment during certain complex tests.
- Some tests, mainly the ones related to Graph, require an Azure AD Premium P1 or P2 license

### Useful links
- [Wazuh Azure documentation](https://documentation.wazuh.com/current/azure/activity-services/index.html)
- [Quickstart: Access Azure AD logs with the Microsoft Graph API](https://learn.microsoft.com/en-us/azure/active-directory/reports-monitoring/quickstart-access-log-with-graph-api)
- [Understand how provisioning integrates with Azure Monitor logs](https://learn.microsoft.com/en-us/azure/active-directory/app-provisioning/application-provisioning-log-analytics)
- [Configure provisioning using Microsoft Graph APIs](https://learn.microsoft.com/en-us/azure/active-directory/app-provisioning/application-provisioning-configuration-api)
- [Managing user account provisioning for enterprise apps in the Azure portal](https://learn.microsoft.com/en-us/azure/active-directory/app-provisioning/configure-automatic-user-provisioning-portal)
- [Tutorial: Archive Azure AD logs to an Azure storage account](https://learn.microsoft.com/en-us/azure/active-directory/reports-monitoring/quickstart-azure-monitor-route-logs-to-storage-account)

**Comment by CarlosRS9** [comment]
## How to validate test results

**Comment by CarlosRS9** [comment]
## Proposed structure

We will use the structure proposed in the issue's body.

As stated, currently the repository has a different structure for the dependencies but it should be deprecated. Instead the following structure will be created, adding modules containing the necessary auxiliary functions for the respective tests:

<details>
    <summary>deps structure</summary>

    deps/
	    wazuh_testing/
		    wazuh_testing/
			    modules/
				    aws/
					    __init__.py 
					    <any required module here>
					    
				    azure/
					    __init__.py 
					    <any required module here>
					    
				    gcloud/
					    __init__.py 
					    <any required module here>

</details>

With respect to the actual tests structure, we propose the following one:

<details>
    <summary>tests structure</summary>
    
    tests/
	    integration/
		    conftest.py
		    test_aws/
			    conftest.py
			    data/
				    configuration_template	
				    wazuh_conf.yml
				    ...
			    test_cloudtrail/
				    test_configuration.py
				    test_1.py
				    test_2.py
				    ...
			    test_guardduty/
				    test_configuration.py
				    test_1.py
				    test_2.py
				    ...
			    ...
			    test_cloudwatch/
				    test_configuration.py
				    test_1.py
				    test_2.py
				    ...
		    test_azure/
			    conftest.py
			    data/
				    configuration_template	
				    wazuh_conf.yml
				    ...
			    test_graph/
				    test_configuration.py
				    test_1.py
				    test_2.py
				    ...
			    test_log_analytics/
				    test_configuration.py
				    test_1.py
				    test_2.py
				    ...
			    test_storage/
				    test_configuration.py
				    test_1.py
				    test_2.py
				    ...
		    test_gcloud/
			    conftest.py
			    data/
				    configuration_template	
				    wazuh_conf.yml
				    ...
			    test_buckets/
				    test_configuration.py
				    test_1.py
				    test_2.py
				    ...
			    test_storage/
				    test_configuration.py
				    test_1.py
				    test_2.py
				    ...
</details>


Each cloud integration should have:
- A exclusive conftest.py file with the necessary fixtures. Some 
- A `data` folder containing all the files required for the tests to run, such as `ossec.conf` configuration files. 
- The tests themselves will be grouped in different directories according to the logic to be tested. 
- Each test will contain a test for the configuration and as many other tests for the functionality as needed.
