### ISSUE TITLE
Design the test cases for the GCP integration tests

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh-qa#3350]
Taking into account the different `Tiers` defined in https://github.com/wazuh/wazuh-qa/issues/3332 we should list and design the different test cases we want to add for the `tiers` agreed to implement.

Check the following issues to get an idea of the manual tests we want to automate:

- https://github.com/wazuh/wazuh/issues/12529
- https://github.com/wazuh/wazuh/issues/13325
- https://github.com/wazuh/wazuh/issues/14376

An important **difference between our AWS integration and this GCP integration** that allows us to simplify the design of the test cases is the fact that although we support different [GCP services](https://documentation.wazuh.com/current/gcp/supported-services/index.html) through GCP, they all work by configuring the module in the same way in the `ossec.conf`, being the configuration on the GCP side by the user the only difference between processing logs from one service or another. With this in mind, it would not be necessary to create different integration tests for each type of service supported by `Pub/Sub` or `Storage buckets` since the configurations are identical.

## Tasks
- [x] Create GCP Pub/Sub test cases
- [x] Create GCP Storage buckets test cases
- [x] Create Parser integration test cases

**Comment by nico-stefani** [comment]
# Pub/Sub Test Cases

## Tier 0

- <details><summary>Pub/Sub integration works properly using the default configuration</summary>

    ### Pre-conditions

    * There are already configured credentials in `wodles/gcp-pubsub/credentials.json`.
    * There is already created subscription `qa_subscription`
    * Debug mode is enabled in the internal_configuration file.

    ### Cases

    <table>
    <tr>
    <td>Case</td>
    <td>Expected Result</td>
    <td>Configuration</td>
    </tr>

    <tr>
    <td>Generate events and consume with defaults option</td>
    <td>The module is invoked with the expected parameters and no error occurs</td>
    <td>
    <details><summary>ossec.conf</summary>

    ```XML
    <gcp-pubsub>
        <pull_on_start>yes</pull_on_start>
        <logging>debug</logging>
        <project_id>wazuh-dev</project_id>
        <subscription_name>qa_subscription</subscription_name>
        <credentials_file>wodles/gcp-pubsub/credentials.json</credentials_file>
    </gcp-pubsub>
    ```

    </details>
    </td>
    </tr>

    </table>

    ### Steps

    1. Apply the test case configuration to the `ossec.conf`
    1. Restart wazuh-manager service
    1. Monitor the `ossec.log` waiting until the wazuh service is restarted or there is a timeout
    1. Monitor the `ossec.log` waiting until the module is triggered or there is a timeout
    1. Check the command was called with the correct parameters
    1. Check no error messages are present in the `ossec.log`

</details>

- <details><summary>Pub/Sub integration works properly with max_messages option</summary>

    ### Pre-conditions

    * There are already configured credentials in `wodles/gcp-pubsub/credentials.json`.
    * There is already created subscription `qa_subscription`
    * Debug mode is enabled in the internal_configuration file.

    ### Cases

    <table>
    <tr>
    <td>Case</td>
    <td>Expected Result</td>
    <td>Configuration</td>
    </tr>

    <tr>
    <td>Generate events and consume with defaults option</td>
    <td>The module is invoked with the default max_messages values and no error occurs</td>
    <td>
    <details><summary>ossec.conf</summary>

    ```XML
    <gcp-pubsub>
        <pull_on_start>yes</pull_on_start>
        <logging>debug</logging>
        <project_id>wazuh-dev</project_id>
        <subscription_name>qa_subscription</subscription_name>
        <credentials_file>wodles/gcp-pubsub/credentials.json</credentials_file>
    </gcp-pubsub>
    ```

    </details>
    </td>
    </tr>

    <tr>
    <td>Generate events and consume with max_messages setted with 250</td>
    <td>The module is invoked with the correct parameters and no error occurs</td>
    <td>
    <details><summary>ossec.conf</summary>

    ```XML
    <gcp-pubsub>
        <pull_on_start>yes</pull_on_start>
        <logging>debug</logging>
        <project_id>wazuh-dev</project_id>
        <subscription_name>qa_subscription</subscription_name>
        <credentials_file>wodles/gcp-pubsub/credentials.json</credentials_file>
        <max_message>250</max_message>
    </gcp-pubsub>
    ```

    </details>
    </td>
    </tr>

    </table>

    ### Steps

    1. Apply the test case configuration to the `ossec.conf`
    1. Restart wazuh-manager service
    1. Monitor the `ossec.log` waiting until the wazuh service is restarted or there is a timeout
    1. Monitor the `ossec.log` waiting until the module is triggered or there is a timeout
    1. Check the command was called with the correct parameters
    1. Check the expected number of events were forwarded to analysisd
    1. Check no error messages are present in the `ossec.log`

</details>

- <details><summary>Pub/Sub integration works properly with num_threads option</summary>

    ### Pre-conditions

    * There are already configured credentials in `wodles/gcp-pubsub/credentials.json`.
    * There is already created subscription `qa_subscription`
    * Debug mode is enabled in the internal_configuration file.

    ### Cases

    <table>
    <tr>
    <td>Case</td>
    <td>Expected Result</td>
    <td>Configuration</td>
    </tr>

    <tr>
    <td>Generate events and consume with defaults option</td>
    <td>The module is invoked with the default num_threads values and no error occurs</td>
    <td>
    <details><summary>ossec.conf</summary>

    ```XML
    <gcp-pubsub>
        <pull_on_start>yes</pull_on_start>
        <logging>debug</logging>
        <project_id>wazuh-dev</project_id>
        <subscription_name>qa_subscription</subscription_name>
        <credentials_file>wodles/gcp-pubsub/credentials.json</credentials_file>
    </gcp-pubsub>
    ```

    </details>
    </td>
    </tr>

    <tr>
    <td>Generate events and consume with num_thread setted with 12</td>
    <td>The module is invoked with the correct parameters and no error occurs</td>
    <td>
    <details><summary>ossec.conf</summary>

    ```XML
    <gcp-pubsub>
        <pull_on_start>yes</pull_on_start>
        <logging>debug</logging>
        <project_id>wazuh-dev</project_id>
        <subscription_name>qa_subscription</subscription_name>
        <credentials_file>wodles/gcp-pubsub/credentials.json</credentials_file>
        <num_thread>250</num_thread>
    </gcp-pubsub>
    ```

    </details>
    </td>
    </tr>

    </table>

    ### Steps

    1. Apply the test case configuration to the `ossec.conf`
    1. Restart wazuh-manager service
    1. Monitor the `ossec.log` waiting until the wazuh service is restarted or there is a timeout
    1. Monitor the `ossec.log` waiting until the module is triggered or there is a timeout
    1. Check the command was called with the correct parameters
    1. Check the expected number of events were forwarded to analysisd
    1. Check no error messages are present in the `ossec.log`

</details>

**Comment by nico-stefani** [comment]
# Storage Test Cases

## Tier 0

- <details><summary>Storage integration works properly using the default configuration</summary>

    ### Pre-conditions

    * There are already configured credentials in `wodles/gcp-pubsub/credentials.json`.
    * Debug mode is enabled in the internal_configuration file.

    ### Cases

    <table>
    <tr>
    <td>Case</td>
    <td>Expected Result</td>
    <td>Configuration</td>
    </tr>

    <tr>
    <td>Use an existing bucket</td>
    <td>The module is invoked with the expected parameters and no error occurs</td>
    <td>
    <details><summary>ossec.conf</summary>

    ```XML
    <gcp-bucket>
        <run_on_start>yes</run_on_start>
        <logging>debug</logging>
        <name>qa_bucket</name>
        <credentials_file>wodles/gcp-pubsub/credentials.json</credentials_file>
    </gcp-bucket>
    ```

    </details>
    </td>
    </tr>

    </table>

    ### Steps

    1. Apply the test case configuration to the `ossec.conf`
    1. Restart wazuh-manager service
    1. Monitor the `ossec.log` waiting until the wazuh service is restarted or there is a timeout
    1. Monitor the `ossec.log` waiting until the module is triggered or there is a timeout
    1. Check the command was called with the correct parameters
    1. Check no error messages are present in the `ossec.log`

</details>

- <details><summary>Storage integration works properly with remove_from_bucket option</summary>

     ### Pre-conditions

    * There are already configured credentials in `wodles/gcp-pubsub/credentials.json`.
    * Debug mode is enabled in the internal_configuration file.

    ### Cases

    <table>
    <tr>
    <td>Case</td>
    <td>Expected Result</td>
    <td>Configuration</td>
    </tr>

    <tr>
    <td>Use an existing bucket, upload a file and consume it</td>
    <td>The uploaded file was removed after the execution</td>
    <td>
    <details><summary>ossec.conf</summary>

    ```XML
    <gcp-bucket>
        <run_on_start>yes</run_on_start>
        <logging>debug</logging>
        <name>qa_bucket</name>
        <credentials_file>wodles/gcp-pubsub/credentials.json</credentials_file>
        <remove_from_bucket>yes</remove_from_bucket>
    </gcp-bucket>
    ```

    </details>
    </td>
    </tr>

    </table>

    ### Steps

    1. Apply the test case configuration to the `ossec.conf`
    1. Restart wazuh-manager service
    1. Monitor the `ossec.log` waiting until the wazuh service is restarted or there is a timeout
    1. Monitor the `ossec.log` waiting until the module is triggered or there is a timeout
    1. Check the command was called with the correct parameters
    1. Make sure that the uploaded log was removed by the module after the execution

</details>

- <details><summary>Storage integration works properly with only_logs_after option</summary>

     ### Pre-conditions

    * There are already configured credentials in `wodles/gcp-pubsub/credentials.json`.
    * Debug mode is enabled in the internal_configuration file.
    * There are already logs with timestamps older than the date specified in the configuration.
    * There are already logs with timestamps more recent timestamp than the date specified in the configuration.

    ### Cases

    <table>
    <tr>
    <td>Case</td>
    <td>Expected Result</td>
    <td>Configuration</td>
    </tr>

    <tr>
    <td>Don't set a date in the configuration</td>
    <td>Only the log uploaded during execution is processed</td>
    <td>
    <details><summary>ossec.conf</summary>

    ```XML
    <gcp-bucket>
        <run_on_start>yes</run_on_start>
        <logging>debug</logging>
        <name>qa_bucket</name>
        <credentials_file>wodles/gcp-pubsub/credentials.json</credentials_file>
    </gcp-bucket>
    ```

    </details>
    </td>
    </tr>

    <tr>
    <td>Set a date greater than the older logs in the bucket</td>
    <td>All logs whith a timestamp greater than the only_logs_after value are processed</td>
    <td>
    <details><summary>ossec.conf</summary>

    ```XML
    <gcp-bucket>
        <run_on_start>yes</run_on_start>
        <logging>debug</logging>
        <name>qa_bucket</name>
        <credentials_file>wodles/gcp-pubsub/credentials.json</credentials_file>
        <only_logs_after>date-to-test</only_logs_after>
    </gcp-bucket>
    ```

    </details>
    </td>
    </tr>

    </table>

    ### Steps

    1. Delete the DB file using a fixture
    1. Apply the test case configuration to the `ossec.conf`
    1. Restart wazuh-manager service
    1. Monitor the `ossec.log` waiting until the wazuh service is restarted or there is a timeout
    1. Monitor the `ossec.log` waiting until the module is triggered or there is a timeout
    1. Check the command was called with the correct parameters
    1. Check the expected number of events were sent to analysisd. Only the logs whose timestamp is greater than the date specified in the configuration should be processed
    1. Check no error messages are present in the `ossec.log`
    1. Check the database was created and updated accordingly

</details>

- <details><summary>Storage integration works properly with path option</summary>

     ### Pre-conditions

    * There are already configured credentials in `wodles/gcp-pubsub/credentials.json`.
    * Debug mode is enabled in the internal_configuration file.
    * There are already logs with timestamps older than the date specified in the configuration.
    * There are already logs with timestamps more recent timestamp than the date specified in the configuration.

    ### Cases

    <table>
    <tr>
    <td>Case</td>
    <td>Expected Result</td>
    <td>Configuration</td>
    </tr>

    <tr>
    <td>Use an existing path with data</td>
    <td>Only the contents of *test_prefix* are processed and sent to analysisd</td>
    <td>
    <details><summary>ossec.conf</summary>

    ```XML
    <gcp-bucket>
        <run_on_start>yes</run_on_start>
        <logging>debug</logging>
        <name>qa_bucket</name>
        <credentials_file>wodles/gcp-pubsub/credentials.json</credentials_file>
        <path>test_prefix</path>
    </gcp-bucket>
    ```

    </details>
    </td>
    </tr>

    <tr>
    <td>Use an existing path without data</td>
    <td>No logs were processed. No logs were sent analysisd</td>
    <td>
    <details><summary>ossec.conf</summary>

    ```XML
    <gcp-bucket>
        <run_on_start>yes</run_on_start>
        <logging>debug</logging>
        <name>qa_bucket</name>
        <credentials_file>wodles/gcp-pubsub/credentials.json</credentials_file>
        <path>empty_prefix</path>
    </gcp-bucket>
    ```

    </details>
    </td>
    </tr>

    <tr>
    <td>Use an inexisting path</td>
    <td>No logs were processed. No logs were sent analysisd. A message warning that the path does not exist should be displayed</td>
    <td>
    <details><summary>ossec.conf</summary>

    ```XML
    <gcp-bucket>
        <run_on_start>yes</run_on_start>
        <logging>debug</logging>
        <name>qa_bucket</name>
        <credentials_file>wodles/gcp-pubsub/credentials.json</credentials_file>
        <path>inexistent_prefix</path>
    </gcp-bucket>
    ```

    </details>
    </td>
    </tr>

    </table>

    ### Steps

    1. Delete the DB file using a fixture
    1. Apply the test case configuration to the `ossec.conf`
    1. Restart wazuh-manager service
    1. Monitor the `ossec.log` waiting until the wazuh service is restarted or there is a timeout
    1. Monitor the `ossec.log` waiting until the module is triggered or there is a timeout
    1. Check the command was called with the correct parameters
    1. If a path that does not exist was specified, make sure that a message is displayed in the `ossec.log` warning the user
    1. Check the expected number of events were forwarded to analysisd
    1. Check the database was created and updated accordingly, using the correct path for each entry

</details>


## Tier 1

- <details><summary>Storage integration don't fetch logs that already were processed </summary>

    ### Pre-conditions

    * There are already configured credentials in `wodles/gcp-pubsub/credentials.json`.
    * There are already logs generated after the date specified in the configurations.

    ### Steps

    1. Delete the DB file using a fixture
    1. Call the module without `only_logs_after` and check that no logs were processed:

        ```bash
        /var/ossec/wodles/gcloud/gcloud --bucket_name qa_bucket \
            --integration_type access_logs \
            --credentials_file /var/ossec/wodles/gcloud/credentials.json
            --log_level 2
        ```

    1. Upload a log file to the test bucket for the day of the test execution
    1. Call the module with the same parameters in `2` and check that the uploaded logs were processed
    1. Call the module with the same parameters in `2` and check that no logs were processed, there were no duplicates
    1. Call the module with `only_logs_after` set in the past and check that the expected number of logs were processed:

        ```bash
        /var/ossec/wodles/gcloud/gcloud --bucket_name qa_bucket \
            --integration_type access_logs \
            --credentials_file /var/ossec/wodles/gcloud/credentials.json
            --only_logs_after <date-to-test> \
            --log_level 2
        ```

    1. Call the module with the same parameters in `6` and check there were no duplicates
    1. Call the module with `only_logs_after` set with an older date than setted in `6` and check that old logs were processed without duplicates:

        ```bash
        /var/ossec/wodles/gcloud/gcloud --bucket_name qa_bucket \
            --integration_type access_logs \
            --credentials_file /var/ossec/wodles/gcloud/credentials.json
            --only_logs_after <older-date-than-step-6> \
            --log_level 2
        ```

    1. Call the module with `only_logs_after` set with an early date than setted in `6` and check that no logs were processed, there were no duplicates:

        ```bash
        /var/ossec/wodles/gcloud/gcloud --bucket_name qa_bucket \
            --integration_type access_logs \
            --credentials_file /var/ossec/wodles/gcloud/credentials.json
            --only_logs_after <early-date-than-step-6> \
            --log_level 2
        ```
    1. Delete the uploaded log file. This must be done even if the test fails


</details>

**Comment by nico-stefani** [comment]
# Parser Test Cases


## Tier 0

- <details><summary>The ossec.conf parser detects when a mandatory parameter is not present</summary>

    ### Pre-conditions

    * There are already configured credentials in `wodles/gcp-pubsub/credentials.json`.
    * Debug mode is enabled in the internal_configuration file.

    ### Cases

    <table>
    <tr>
    <td>Case</td>
    <td>Expected Result</td>
    <td>Configuration</td>
    </tr>

    <tr>
    <td>type attribute in bucket tag is missing</td>
    <td>An error occurs and was displayed in `ossec.log</td>
    <td>
    <details><summary>ossec.conf</summary>

    ```XML
    <gcp-bucket>
        <run_on_start>yes</run_on_start>
        <logging>debug</logging>
        <bucket>
            <name>qa_bucket</name>
            <credentials_file>wodles/gcp-pubsub/credentials.json</credentials_file>
        </bucket>
    </gcp-bucket>
    ```
    </details>
    </td>
    </tr>

    <tr>
    <td>credentials_file tag is missing in bucket</td>
    <td>An error occurs and was displayed in `ossec.log</td>
    <td>
    <details><summary>ossec.conf</summary>

    ```XML
    <gcp-bucket>
        <run_on_start>yes</run_on_start>
        <logging>debug</logging>
        <bucket>
            <name>qa_bucket</name>
        </bucket>
    </gcp-bucket>
    ```
    </details>
    </td>
    </tr>

    <tr>
    <td>credentials_file tag is missing in gcp-pubsub</td>
    <td>An error occurs and was displayed in `ossec.log</td>
    <td>
    <details><summary>ossec.conf</summary>

    ```XML
    <gcp-pubsub>
        <pull_on_start>yes</pull_on_start>
        <logging>debug</logging>
        <project_id>wazuh-dev</project_id>
        <subscription_name>qa_subscription</subscription_name>
    </gcp-pubsub>
    ```
    </details>
    </td>
    </tr>

    </table>

    ### Steps

    1. Apply the test case configuration to the `ossec.conf`
    1. Restart wazuh-manager service
    1. Monitor the ossec.log waiting until the wazuh service is restarted or there is a timeout
    1. Monitor the ossec.log waiting until the module is triggered or there is a timeout
    1. Check the command wasn't called and error message was displayed in `ossec.log`
</details>


- <details><summary>The ossec.conf parser handles correctly when parameters has no values</summary>

    ### Pre-conditions

    * There are already configured credentials in `wodles/gcp-pubsub/credentials.json`.
    * Debug mode is enabled in the internal_configuration file.

    ### Cases

    <table>
    <tr>
    <td>Case</td>
    <td>Expected Result</td>
    <td>Configuration</td>
    </tr>

    <tr>
    <td>Set an empty value for attribute type in tag bucket</td>
    <td>An error occurs and was displayed in `ossec.log`</td>
    <td>
    <details><summary>ossec.conf</summary>

    ```XML
    <gcp-bucket>
        <run_on_start>yes</run_on_start>
        <logging>debug</logging>
        <bucket type="">
            <name>qa_bucket</name>
            <credentials_file>wodles/gcp-pubsub/credentials.json</credentials_file>
        </bucket>
    </gcp-bucket>
    ```
    </details>
    </td>
    </tr>

    <tr>
    <td>Set an empty value for only_logs_after in tag bucket</td>
    <td>An error occurs and was displayed in `ossec.log</td>
    <td>
    <details><summary>ossec.conf</summary>

    ```XML
    <gcp-bucket>
        <run_on_start>yes</run_on_start>
        <logging>debug</logging>
        <bucket type="access_logs">
            <name>qa_bucket</name>
            <credentials_file>wodles/gcp-pubsub/credentials.json</credentials_file>
            <only_logs_after></only_logs_after>
        </bucket>
    </gcp-bucket>
    ```
    </details>
    </td>
    </tr>

    <tr>
    <td>Set an empty value for name in tag bucket</td>
    <td>An error occurs and was displayed in `ossec.log</td>
    <td>
    <details><summary>ossec.conf</summary>

    ```XML
    <gcp-bucket>
        <run_on_start>yes</run_on_start>
        <logging>debug</logging>
        <bucket type="access_logs">
            <name></name>
            <credentials_file>wodles/gcp-pubsub/credentials.json</credentials_file>
        </bucket>
    </gcp-bucket>
    ```
    </details>
    </td>
    </tr>

    <tr>
    <td>Set an empty value for subscription_name in tag gcp-pubsub</td>
    <td>An error occurs and was displayed in `ossec.log</td>
    <td>
    <details><summary>ossec.conf</summary>

    ```XML
    <gcp-pubsub>
        <pull_on_start>yes</pull_on_start>
        <logging>debug</logging>
        <project_id>wazuh-dev</project_id>
        <subscription_name></subscription_name>
        <credentials_file>wodles/gcp-pubsub/credentials.json</credentials_file>
    </gcp-pubsub>
    ```
    </details>
    </td>
    </tr>

    <tr>
    <td>Set an empty value for path in tag bucket</td>
    <td>An error occurs and was displayed in `ossec.log</td>
    <td>
    <details><summary>ossec.conf</summary>

    ```XML
    <gcp-bucket>
        <run_on_start>yes</run_on_start>
        <logging>debug</logging>
        <bucket type="access_logs">
            <name>qa_bucket</name>
            <credentials_file>wodles/gcp-pubsub/credentials.json</credentials_file>
            <path></path>
        </bucket>
    </gcp-bucket>
    ```
    </details>
    </td>
    </tr>

    <tr>
    <td>Set an empty value for credentials_file in tag bucket</td>
    <td>An error occurs and was displayed in `ossec.log</td>
    <td>
    <details><summary>ossec.conf</summary>

    ```XML
    <gcp-bucket>
        <run_on_start>yes</run_on_start>
        <logging>debug</logging>
        <bucket type="access_logs">
            <name>qa_bucket</name>
            <credentials_file></credentials_file>
        </bucket>
    </gcp-bucket>
    ```
    </details>
    </td>
    </tr>

    <tr>
    <td>Set an empty value for credentials_file in tag gcp-pubsub</td>
    <td>An error occurs and was displayed in `ossec.log</td>
    <td>
    <details><summary>ossec.conf</summary>

    ```XML
    <gcp-pubsub>
        <pull_on_start>yes</pull_on_start>
        <logging>debug</logging>
        <project_id>wazuh-dev</project_id>
        <subscription_name>qa_subscription</subscription_name>
        <credentials_file></credentials_file>
    </gcp-pubsub>
    ```
    </details>
    </td>
    </tr>

    <tr>
    <td>Set an empty value for remove_from_bucket in tag bucket</td>
    <td>An error occurs and was displayed in `ossec.log</td>
    <td>
    <details><summary>ossec.conf</summary>

    ```XML
    <gcp-bucket>
        <run_on_start>yes</run_on_start>
        <logging>debug</logging>
        <bucket type="access_logs">
            <name>qa_bucket</name>
            <credentials_file>wodles/gcp-pubsub/credentials.json</credentials_file>
            <remove_from_bucket></remove_from_bucket>
        </bucket>
    </gcp-bucket>
    ```
    </details>
    </td>
    </tr>

    <tr>
    <td>Set an empty value for max_messages in tag gcp-pubsub</td>
    <td>An error occurs and was displayed in `ossec.log</td>
    <td>
    <details><summary>ossec.conf</summary>

    ```XML
    <gcp-pubsub>
        <pull_on_start>yes</pull_on_start>
        <logging>debug</logging>
        <project_id>wazuh-dev</project_id>
        <subscription_name>qa_subscription</subscription_name>
        <credentials_file>wodles/gcp-pubsub/credentials.json</credentials_file>
        <max_messages></max_messages>
    </gcp-pubsub>
    ```
    </details>
    </td>
    </tr>

    <tr>
    <td>Set an empty value for num_threads in tag gcp-pubsub</td>
    <td>An error occurs and was displayed in `ossec.log</td>
    <td>
    <details><summary>ossec.conf</summary>

    ```XML
    <gcp-pubsub>
        <pull_on_start>yes</pull_on_start>
        <logging>debug</logging>
        <project_id>wazuh-dev</project_id>
        <subscription_name>qa_subscription</subscription_name>
        <credentials_file>wodles/gcp-pubsub/credentials.json</credentials_file>
        <num_threads></num_threads>
    </gcp-pubsub>
    ```
    </details>
    </td>
    </tr>

    </table>

    ### Steps

    1. Apply the test case configuration to the `ossec.conf`
    1. Restart wazuh-manager service
    1. Monitor the ossec.log waiting until the wazuh service is restarted or there is a timeout
    1. Monitor the ossec.log waiting until the module is triggered or there is a timeout
    1. Check the command wasn't called and error message was displayed in `ossec.log`
</details>

- <details><summary>The ossec.conf parser handles correctly when invalid values are used</summary>

    ### Pre-conditions

    * There are already configured credentials in `wodles/gcp-pubsub/credentials.json`.
    * Debug mode is enabled in the internal_configuration file.

    ### Cases

    <table>
    <tr>
    <td>Case</td>
    <td>Expected Result</td>
    <td>Configuration</td>
    </tr>

    <tr>
    <td>Set an invalid value for attribute type in tag bucket</td>
    <td>An error occurs and was displayed in `ossec.log`</td>
    <td>
    <details><summary>ossec.conf</summary>

    ```XML
    <gcp-bucket>
        <run_on_start>yes</run_on_start>
        <logging>debug</logging>
        <bucket type="invalid_type">
            <name>qa_bucket</name>
            <credentials_file>wodles/gcp-pubsub/credentials.json</credentials_file>
        </bucket>
    </gcp-bucket>
    ```
    </details>
    </td>
    </tr>

    <tr>
    <td>Set an invalid value for only_logs_after in tag bucket</td>
    <td>An error occurs and was displayed in `ossec.log</td>
    <td>
    <details><summary>ossec.conf</summary>

    ```XML
    <gcp-bucket>
        <run_on_start>yes</run_on_start>
        <logging>debug</logging>
        <bucket type="access_logs">
            <name>qa_bucket</name>
            <credentials_file>wodles/gcp-pubsub/credentials.json</credentials_file>
            <only_logs_after>JUL-10</only_logs_after>
        </bucket>
    </gcp-bucket>
    ```
    </details>
    </td>
    </tr>

    <tr>
    <td>Set an invalid value for name in tag bucket</td>
    <td>An error occurs and was displayed in `ossec.log</td>
    <td>
    <details><summary>ossec.conf</summary>

    ```XML
    <gcp-bucket>
        <run_on_start>yes</run_on_start>
        <logging>debug</logging>
        <bucket type="access_logs">
            <name>invalid_bucket_name</name>
            <credentials_file>wodles/gcp-pubsub/credentials.json</credentials_file>
        </bucket>
    </gcp-bucket>
    ```
    </details>
    </td>
    </tr>

    <tr>
    <td>Set an invalid value for subscription_name in tag gcp-pubsub</td>
    <td>An error occurs and was displayed in `ossec.log</td>
    <td>
    <details><summary>ossec.conf</summary>

    ```XML
    <gcp-pubsub>
        <pull_on_start>yes</pull_on_start>
        <logging>debug</logging>
        <project_id>wazuh-dev</project_id>
        <subscription_name>invalid_subscription_name</subscription_name>
        <credentials_file>wodles/gcp-pubsub/credentials.json</credentials_file>
    </gcp-pubsub>
    ```
    </details>
    </td>
    </tr>

    <tr>
    <td>Set an invalid value for path in tag bucket</td>
    <td>An error occurs and was displayed in `ossec.log</td>
    <td>
    <details><summary>ossec.conf</summary>

    ```XML
    <gcp-bucket>
        <run_on_start>yes</run_on_start>
        <logging>debug</logging>
        <bucket type="access_logs">
            <name>qa_bucket</name>
            <credentials_file>wodles/gcp-pubsub/credentials.json</credentials_file>
            <path>invalid_path</path>
        </bucket>
    </gcp-bucket>
    ```
    </details>
    </td>
    </tr>

    <tr>
    <td>Set an invalid value for credentials_file in tag bucket</td>
    <td>An error occurs and was displayed in `ossec.log</td>
    <td>
    <details><summary>ossec.conf</summary>

    ```XML
    <gcp-bucket>
        <run_on_start>yes</run_on_start>
        <logging>debug</logging>
        <bucket type="access_logs">
            <name>qa_bucket</name>
            <credentials_file>invalid_value</credentials_file>
        </bucket>
    </gcp-bucket>
    ```
    </details>
    </td>
    </tr>

    <tr>
    <td>Set an invalid value for credentials_file in tag gcp-pubsub</td>
    <td>An error occurs and was displayed in `ossec.log</td>
    <td>
    <details><summary>ossec.conf</summary>

    ```XML
    <gcp-pubsub>
        <pull_on_start>yes</pull_on_start>
        <logging>debug</logging>
        <project_id>wazuh-dev</project_id>
        <subscription_name>qa_subscription</subscription_name>
        <credentials_file>invalid_value</credentials_file>
    </gcp-pubsub>
    ```
    </details>
    </td>
    </tr>

    <tr>
    <td>Set an invalid value for remove_from_bucket in tag bucket</td>
    <td>An error occurs and was displayed in `ossec.log</td>
    <td>
    <details><summary>ossec.conf</summary>

    ```XML
    <gcp-bucket>
        <run_on_start>yes</run_on_start>
        <logging>debug</logging>
        <bucket type="access_logs">
            <name>qa_bucket</name>
            <credentials_file>wodles/gcp-pubsub/credentials.json</credentials_file>
            <remove_from_bucket>nein</remove_from_bucket>
        </bucket>
    </gcp-bucket>
    ```
    </details>
    </td>
    </tr>

    <tr>
    <td>Set an invalid value for max_messages in tag gcp-pubsub</td>
    <td>An error occurs and was displayed in `ossec.log</td>
    <td>
    <details><summary>ossec.conf</summary>

    ```XML
    <gcp-pubsub>
        <pull_on_start>yes</pull_on_start>
        <logging>debug</logging>
        <project_id>wazuh-dev</project_id>
        <subscription_name>qa_subscription</subscription_name>
        <credentials_file>wodles/gcp-pubsub/credentials.json</credentials_file>
        <max_messages>invalid</max_messages>
    </gcp-pubsub>
    ```
    </details>
    </td>
    </tr>

    <tr>
    <td>Set an invalid value for num_threads in tag gcp-pubsub</td>
    <td>An error occurs and was displayed in `ossec.log</td>
    <td>
    <details><summary>ossec.conf</summary>

    ```XML
    <gcp-pubsub>
        <pull_on_start>yes</pull_on_start>
        <logging>debug</logging>
        <project_id>wazuh-dev</project_id>
        <subscription_name>qa_subscription</subscription_name>
        <credentials_file>wodles/gcp-pubsub/credentials.json</credentials_file>
        <num_threads>invalid</num_threads>
    </gcp-pubsub>
    ```
    </details>
    </td>
    </tr>

    </table>

    ### Steps

    1. Apply the test case configuration to the `ossec.conf`
    1. Restart wazuh-manager service
    1. Monitor the ossec.log waiting until the wazuh service is restarted or there is a timeout
    1. Monitor the ossec.log waiting until the module is triggered or there is a timeout
    1. Check the command wasn't called and error message was displayed in `ossec.log`
</details>

- <details><summary>The ossec.conf parser handles correctly when several bucket and gcp-pubsub tags are used in the same configuration</summary>

    ### Pre-conditions

    * There are already configured credentials in `wodles/gcp-pubsub/credentials.json`.
    * Debug mode is enabled in the internal_configuration file.

    ### Cases

    <table>
    <tr>
    <td>Case</td>
    <td>Expected Result</td>
    <td>Configuration</td>
    </tr>

    <tr>
    <td>Have two valid buckets and one valid pubsub subscription configured</td>
    <td>The command is invoked two times for buckets and one times for pubsub</td>
    <td>
    <details><summary>ossec.conf</summary>

    ```XML
    <gcp-pubsub>
        <pull_on_start>yes</pull_on_start>
        <logging>debug</logging>
        <project_id>wazuh-dev</project_id>
        <subscription_name>qa_subscription</subscription_name>
        <credentials_file>wodles/gcp-pubsub/credentials.json</credentials_file>
    </gcp-pubsub>

    <gcp-bucket>
        <run_on_start>yes</run_on_start>
        <logging>debug</logging>
        <bucket type="access_logs">
            <name>qa_bucket</name>
            <credentials_file>wodles/gcp-pubsub/credentials.json</credentials_file>
        </bucket>
        <bucket type="access_logs">
            <name>qa_bucket_1</name>
            <credentials_file>wodles/gcp-pubsub/credentials.json</credentials_file>
        </bucket>
    </gcp-bucket>
    ```
    </details>
    </td>
    </tr>

    </table>

    ### Steps

    1. Apply the test case configuration to the `ossec.conf`
    1. Restart wazuh-manager service
    1. Monitor the ossec.log waiting until the wazuh service is restarted or there is a timeout
    1. Monitor the ossec.log waiting until the module is triggered or there is a timeout
    1. Check the command was called the expected number of times

</details>
