### ISSUE TITLE
QA testing - Fix agent upgrade module settings parser to set a default CA file

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-qa#3377]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
| 4.3.9 |https://github.com/wazuh/wazuh/issues/14970|https://github.com/wazuh/wazuh/pull/15023|

## Description

As described in the issue, the agent upgrade module does not set the default CA file when unspecified unless block `<agent-upgrade>` is defined in _ossec.conf_.

The fix aims to let the module set a default value for `<ca_store>` if `<ca_verification>` is set to `yes` or unspecified.

## Proposed checks

In addition to the tests performed in the issue (before the fix) and the PR (applying the fix), we expect the behavior described in the table below, no matter if we use the legacy configuration (`<active-response>`) or the modern setting (`<agent-upgrade>`).

### Legacy settings (`<active-response>`)

- [x] Verification enabled and CA defined (default).
- [x] Verification enabled and custom CA defined.
- [x] Verification enabled but no CA defined.
- [x] Verification disabled but CA defined.
- [x] Verification not specified but CA defined.
- [x] Verification not specified but custom CA defined.
- [x] Verification not specified and no CA defined.

### Modern settings (`<agent-upgrade>`)

- [x] Verification enabled and CA defined (default).
- [x] Verification enabled and custom CA defined.
- [x] Verification enabled but no CA defined.
- [x] Verification disabled but CA defined.
- [x] Verification not specified but CA defined.
- [x] Verification not specified but custom CA defined.
- [x] Verification not specified and no CA defined.
- [x] Agent upgrade disabled.

## Steps to reproduce

If we remove `<active-response>` and `<agent-upgrade>` from _ossec.conf_, the agent takes no value for `<ca_store>`, thus it accepts whatever WPK file.

## Expected results

|`<ca_verification>`|`<ca_store>`|Expected `ca_store` value applied|Expected behavior|
|---|---|---|---|
|`yes`|`/path`|`/path`|The agent accepts only WPK files signed with a certificate validated by `/path`.|
|`yes`|None|`etc/wpk_root.pem`|The agent accepts only WPK files signed with a certificate created by Wazuh.|
|None|`/path`|`/path`|The agent accepts only WPK files signed with a certificate validated by `/path`.|
|None|None|`etc/wpk_root.pem`|The agent accepts only WPK files signed with a certificate created by Wazuh.|
|`no`|`/path`|None|The agent accepts any WPK file.|
|`no`|None|None|The agent accepts any WPK file.|

**Comment by juliamagan** [comment]
## Review data

| Tester | PR commit               |
|--------|-------------------------|
| @juliamagan  |  [0439bff](https://github.com/wazuh/wazuh/pull/15023/commits/0439bffd54c221909205a04bb713de6278242637)   |

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
| Centos   |    8      | Vagrant |    qactl/centos_8        |


### Tested packages

| `wazuh-manager` | `wazuh-agent` | `wpk` |
|-----------------|---------------|-------------|
|  [4.3.9](https://packages-dev.wazuh.com/warehouse/pullrequests/4.3/rpm/var/wazuh-manager-4.3.9-0.commit0439bff.x86_64.rpm)               | [4.3.8](https://packages.wazuh.com/4.x/yum/wazuh-agent-4.3.8-1.x86_64.rpm)    | [WPK Wazuh cert](https://packages-dev.wazuh.com/warehouse/test/4.3/wpk/linux/x86_64/wazuh_agent_v4.3.9-3377.upgrade.ca_linux_x86_64.wpk),  [WPK custom cert]()

### Status

- [ ] In progress
- [ ] Pending Review
- [ ] QA Manager approved (@jmv74211)
- [ ] Development team leader approved  ()


### Conclusion

**Comment by juliamagan** [comment]
## Tasks results

### Legacy settings (`<active-response>`)

<details>
<summary>Verification enabled and CA defined (default) :green_circle:</summary>
<br>

- `ossec.conf`:

```xml
  <!-- Active response -->
  <active-response>
    <disabled>no</disabled>
    <ca_store>etc/wpk_root.pem</ca_store>
    <ca_verification>yes</ca_verification>
  </active-response>
```

- Active configuration:

  - Request:

    ```
    curl -k -X GET "https://localhost:55000/agents/001/config/wmodules/wmodules?pretty=true" -H  "Authorization: Bearer $TOKEN"
    ```
  - Response:

    ```json
    {
       "agent-upgrade": {
          "enabled": "yes",
          "ca_verification": "yes",
          "ca_store": [
             "etc/wpk_root.pem"
          ]
       }
    }
    ```

- `/var/ossec/bin/agent_upgrade -a 001 -f /home/qa/wazuh_agent_v4.3.9-3377.upgrade.ca_linux_x86_64.wpk -F`:

```
Upgrading...

Upgraded agents:
	Agent 001 upgraded: Wazuh v4.3.9 -> Wazuh v4.3.9
```

- Manager logs:

```
2022/09/29 14:34:22 wazuh-modulesd:agent-upgrade: INFO: (8164): Received upgrade notification from agent '1'. Error code: '0', message: 'Upgrade was successful'
```

</details>

<details>
<summary>Verification enabled and custom CA defined :green_circle:</summary>
<br>

- `ossec.conf`:

```xml
  <!-- Active response -->
  <active-response>
    <disabled>no</disabled>
    <ca_store>/home/qa/certs/wpk_root.pem</ca_store>
    <ca_verification>yes</ca_verification>
  </active-response>
```

- Active configuration:

  - Request:

    ```
    curl -k -X GET "https://localhost:55000/agents/001/config/wmodules/wmodules?pretty=true" -H  "Authorization: Bearer $TOKEN"
    ```
  - Response:

    ```json
    {
       "agent-upgrade": {
          "enabled": "yes",
          "ca_verification": "yes",
          "ca_store": [
             "/home/qa/certs/wpk_root.pem"
          ]
       }
    }
    ```

- `/var/ossec/bin/agent_upgrade -a 001 -f /home/qa/LinuxAgent.wpk -F`:

```
Upgrading...

Upgraded agents:
	Agent 001 upgraded: Wazuh v4.3.9 -> Wazuh v4.3.9
```

- Manager logs:

```
2022/09/29 14:46:38 wazuh-modulesd:agent-upgrade: INFO: (8164): Received upgrade notification from agent '1'. Error code: '0', message: 'Upgrade was successful'
```

</details>


<details>
<summary>Verification enabled but no CA defined :green_circle:</summary>
<br>

- `ossec.conf`:

```xml
  <!-- Active response -->
  <active-response>
    <disabled>no</disabled>
    <!--<ca_store>etc/wpk_root.pem</ca_store>-->
    <ca_verification>yes</ca_verification>
  </active-response>
```

- Active configuration:

  - Request:

    ```
    curl -k -X GET "https://localhost:55000/agents/001/config/wmodules/wmodules?pretty=true" -H  "Authorization: Bearer $TOKEN"
    ```
  - Response:

    ```json
    {
       "agent-upgrade": {
          "enabled": "yes",
          "ca_verification": "yes",
          "ca_store": [
             "etc/wpk_root.pem"
          ]
       }
    }
    ```

- `/var/ossec/bin/agent_upgrade -a 001 -f /home/qa/wazuh_agent_v4.3.9-3377.upgrade.ca_linux_x86_64.wpk -F`:

```
Upgrading...

Upgraded agents:
	Agent 001 upgraded: Wazuh v4.3.9 -> Wazuh v4.3.9
```

- Manager logs:

```
2022/09/29 14:54:41 wazuh-modulesd:agent-upgrade: INFO: (8164): Received upgrade notification from agent '1'. Error code: '0', message: 'Upgrade was successful'
```

</details>

<details>
<summary>Verification disabled but CA defined :green_circle:</summary>
<br>

- `ossec.conf`:

```xml
  <!-- Active response -->
  <active-response>
    <disabled>no</disabled>
    <ca_store>etc/wpk_root.pem</ca_store>
    <ca_verification>no</ca_verification>-
  </active-response>
```

- Active configuration:

  - Request:

    ```
    curl -k -X GET "https://localhost:55000/agents/001/config/wmodules/wmodules?pretty=true" -H  "Authorization: Bearer $TOKEN"
    ```
  - Response:

    ```json
    {
       "agent-upgrade": {
          "enabled": "yes",
          "ca_verification": "no"
       }
    }
    ```

- `/var/ossec/bin/agent_upgrade -a 001 -f /home/qa/wazuh_agent_v4.3.9-3377.upgrade.ca_linux_x86_64.wpk -F`:

```
Upgrading...

Upgraded agents:
	Agent 001 upgraded: Wazuh v4.3.9 -> Wazuh v4.3.9
```

- Manager logs:

```
2022/09/29 15:06:16 wazuh-modulesd:agent-upgrade: INFO: (8164): Received upgrade notification from agent '1'. Error code: '0', message: 'Upgrade was successful'
```

</details>

<details>
<summary>Verification not specified but CA defined :green_circle:</summary>
<br>

- `ossec.conf`:

```xml
  <!-- Active response -->
  <active-response>
    <disabled>no</disabled>
    <ca_store>etc/wpk_root.pem</ca_store>
    <!--<ca_verification>no</ca_verification>-->
  </active-response>
```

- Active configuration:

  - Request:

    ```
    curl -k -X GET "https://localhost:55000/agents/001/config/wmodules/wmodules?pretty=true" -H  "Authorization: Bearer $TOKEN"
    ```
  - Response:

    ```json
    {
       "agent-upgrade": {
          "enabled": "yes",
          "ca_verification": "yes",
          "ca_store": [
             "etc/wpk_root.pem"
          ]
       }
    }
    ```

- `/var/ossec/bin/agent_upgrade -a 001 -f /home/qa/wazuh_agent_v4.3.9-3377.upgrade.ca_linux_x86_64.wpk -F`:

```
Upgrading...

Upgraded agents:
	Agent 001 upgraded: Wazuh v4.3.9 -> Wazuh v4.3.9
```

- Manager logs:

```
2022/09/29 15:16:03 wazuh-modulesd:agent-upgrade: INFO: (8164): Received upgrade notification from agent '1'. Error code: '0', message: 'Upgrade was successful'
```

</details>

<details>
<summary>Verification not specified but custom CA defined :green_circle:</summary>
<br>

- `ossec.conf`:

```xml
  <!-- Active response -->
  <active-response>
    <disabled>no</disabled>
    <ca_store>/home/qa/certs/wpk_root.pem</ca_store>
    <!--<ca_verification>no</ca_verification>-->
  </active-response>
```

- Active configuration:

  - Request:

    ```
    curl -k -X GET "https://localhost:55000/agents/001/config/wmodules/wmodules?pretty=true" -H  "Authorization: Bearer $TOKEN"
    ```
  - Response:

    ```json
    {
       "agent-upgrade": {
          "enabled": "yes",
          "ca_verification": "yes",
          "ca_store": [
             "/home/qa/certs/wpk_root.pem"
          ]
       }
    }
    ```

- `/var/ossec/bin/agent_upgrade -a 001 -f /home/qa/LinuxAgent.wpk -F`:

```
Upgrading...

Upgraded agents:
	Agent 001 upgraded: Wazuh v4.3.9 -> Wazuh v4.3.9
```

- Manager logs:

```
2022/09/29 15:24:45 wazuh-modulesd:agent-upgrade: INFO: (8164): Received upgrade notification from agent '1'. Error code: '0', message: 'Upgrade was successful'
```

</details>

**Comment by jmv74211** [comment]
🟢 Everything seems to be working properly
