### ISSUE TITLE
QA planning: New Wazuh Engine

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3385]
EPIC: New Wazuh Engine development [#11334](https://github.com/wazuh/wazuh/issues/11334)
Documento: https://docs.google.com/document/d/125d8tpj192MNdggLcNjk_R0tQWEuhjBEmtjONHbUkHo/edit
Proyecto:https://github.com/orgs/wazuh/projects/7/views/1

 ## Description

This problem aims to investigate [New Wazuh Engine development](https://github.com/wazuh/wazuh/issues/11334) to define the test cases to be carried out.

# Development stage

- [x] Research the applied change. (epics, issues, [documents](https://docs.google.com/document/d/125d8tpj192MNdggLcNjk_R0tQWEuhjBEmtjONHbUkHo/edit), [project](https://github.com/orgs/wazuh/projects/7/views/1))
- [x] Research if we have a test for this case.
- [x] Define the new test cases. 
- [x] Define whether it is necessary to test systems, integration, or E2E. Create the corresponding issues.

**Comment by roronoasins** [comment]
# Task results

<details><summary>Research the applied change.</summary>

The team has been developing a new engine so this new one is more user-friendly. The rule set will be easier to modify, so it won't require a lot of effort with regexes as it is currently.

</details>


<details><summary>Research if we have a test for this case.</summary>

There are no tests in wazuh-qa for the engine, so we will work on that. Also, the current analysisd tests will be deprecated.

</details>


<details><summary>Define the test cases. Identify the base cases, and then the rest of the tests as tier 2.</summary>

As we can see, we have this issue to start with the engine testing https://github.com/wazuh/wazuh/issues/15083. Now we have to research and start with the module testing in our repo.

The first approach will be to add a module for each test purpose(input, resources, output, etc.) and a test within the module for each case(events, API, ruleset, etc.). They could be general tests that run using yaml files with the cases we've mentioned. So, we can start working on the first fixtures to be able to run the engine with python and pytest with a few minimal cases, and then, we can add all cases we need to these yaml files.

</details>


<details><summary>Define whether it is necessary to test systems, integration, or E2E. Create the corresponding issues.</summary>

During the process of creating the first fixtures and module structure, we will study the testing we can do.

</details>
