### ISSUE TITLE
Analyzing Wazuh's api.log breaks indexing of active-responses.log due to field type conflict and loss of AR alerts

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh-qa#3388]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|                 4.4.0       |        https://github.com/wazuh/wazuh/issues/14774                |           https://github.com/wazuh/wazuh/pull/14807         |

## Description

Fix the above-referenced wazuh-api-fields static decoder to extract the parameters material to a different field name like wazuh-api.parameters. Bug fix, changed "parameter" field name to "api-parameter".

The old name caused a conflict with json decoder. The details are explained at length in https://github.com/wazuh/wazuh/issues/14774

## Proposed checks

- [x] Verifiy api-logs alerts include the new api-parameter field instead of a single parameter field.

Tested logs:

2021/04/20 16:00:35 INFO: wazuh 127.0.0.1 "PUT /agents/group" with parameters {"group_id": "group1", "agents_list": "629,650,654,682"} and body {} done in 0.075s: 200

2021/10/05 10:30:21 INFO: Generated private key file in WAZUH_PATH/api/configuration/ssl/server.key

**Comment by Rebits** [comment]
## Review data

| Tester | PR commit               | 
|--------|-------------------------|
| @Rebits  |  [5cfeb34](https://github.com/wazuh/wazuh/pull/14807/commits/5cfeb341ed17970f0b4a40d7013c57aaf8fd55b6)

### Testing environment

| OS | OS version | Deployment | Image/AMI 
|-- |-- |-- |-- 
| Ubuntu | 22 |  EC2 | `ami-003530de8839921c4` |


### Tested packages

| OS | Package
|-- |--
| Ubuntu |  [Manager](packages-dev.wazuh.com/warehouse/pullrequests/4.4/deb/var/wazuh-manager_4.4.0-0.commit5cfeb34_amd64.deb)




### Status

- [x] In progress
- [ ] Pending Review
- [ ] QA team leader approved 
- [ ] QA manager approved @jmv74211 
- [ ] Development team leader approved @72nomada

**Comment by Rebits** [comment]
##  Tasks

<details>

<summary> Preconditions </summary>


</details>
<details>

<summary> Bug replication in v4.3.8 </summary>


</details>
<details>

<summary> Verifiy api-logs alerts include the new api-parameter field instead of a single parameter field. </summary>


</details>

**Comment by jmv74211** [comment]
## QA review

- **Type**: Manual testing.
- **Status**: Pending to discuss results with the development team  🟡 
- **Comments**: The development seems to fix the bug satisfactorily. However, it was detected minor issues in the wazuh-dashboard and the documentation:

  - (1) The "Index pattern was refreshed successfully" panel always appears for each active response alert. Even reloading the page the panel appears (cc @wazuh/frontend).

  - (2): Improve the decoder field usage documentation. It's easy for users to use wrong parameter names in their custom ruleset producing similar errors (cc @wazuh/content).

This will be discussed with the development team, and the PR will be approved or not on this basis.

**Comment by Desvelao** [comment]
> ## QA review
> * **Type**: Manual testing.
> * **Status**: Pending to discuss results with the development team  yellow_circle
> * **Comments**: The development seems to fix the bug satisfactorily. However, it was detected minor issues in the wazuh-dashboard and the documentation:
>   
>   * (1) The "Index pattern was refreshed successfully" panel always appears for each active response alert. Even reloading the page the panel appears (cc @wazuh/frontend).
>   * (2): Improve the decoder field usage documentation. It's easy for users to use wrong parameter names in their custom ruleset producing similar errors (cc @wazuh/content).
> 
> This will be discussed with the development team, and the PR will be approved or not on this basis.

1. There is a related PR that defines the field mapping of `data.parameters.extra_args` field in the `wazuh-template.json` https://github.com/wazuh/wazuh/pull/14077. This could solve the problem of toast appearing constantly when the field has no defined type. More information: https://wazuh-team.slack.com/archives/CNW3KJVDG/p1656495348259349

**Comment by jmv74211** [comment]
## Closing conclusion 👍🏼  

|| |
|-|-|
| 🔵 | Proposed to be fixed in future versions or developments | 


The development has been approved taking into account the following considerations proposed in the [QA review](https://github.com/wazuh/wazuh-qa/issues/3410#issuecomment-1269747560):

***(1)*:  The "Index pattern was refreshed successfully" panel always appears for each active response alert. Even reloading the page the panel appears.** 🔵 

Known bug and will be fixed in future releases [wazuh-kibana#14077](https://github.com/wazuh/wazuh/pull/14077).

***(2)*: Improve the decoder field usage documentation. It's easy for users to use wrong parameter names in their custom ruleset producing similar errors** 🔵 

The following issue has been opened [wazuh-documentation#5661](https://github.com/wazuh/wazuh-documentation/issues/5661)
