### ISSUE TITLE
QA testing - Update Wazuh MITRE ATT&CK database to version 11.3

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh-qa#3395]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|               4.4.0         |           https://github.com/wazuh/wazuh/pull/13622             |          https://github.com/wazuh/wazuh/pull/13622          |

## Description

Add the new MITRE ATT&CK Enterprise version 11.3.

## Proposed checks

- [x] Verify wazuh-manager package starts without warning or errors related to the MITRE database. 
- [x] Run the runtest.py testing tool to verify no MITRE technique or tactic is missing in the DB.

**Comment by Rebits** [comment]
## Review data

| Tester | PR commit               | 
|--------|-------------------------|
| @Rebits  |  [0b9a97a](https://github.com/wazuh/wazuh/pull/13622/commits/0b9a97ade73db112fe94844b1796ed9ec6f4f1ea) | 



### Testing environment

| OS | OS version | Deployment | Image/AMI |
|-- |-- |-- |-- |
| Ubuntu |  22 |  EC2 | `ami-003530de8839921c4` |


### Tested packages

| OS | Package |
|-- |-- |
| Ubuntu |  [Manager](https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/deb/var/wazuh-manager_4.4.0-0.commit4d26998_amd64.deb)



### Status

- [x] In progress
- [ ] Pending Review
- [ ] QA team leader approved
- [ ] QA manager approved @jvm
- [ ] Development team leader approved @jose

**Comment by Rebits** [comment]
## Tasks :green_circle: 


<details>


<summary> wazuh-manager package starts without warning or errors related to the MITRE database.  :green_circle: </summary>


No errors or warnings related to MITRE

```
root@ip-172-31-3-189:/home/qa# cat /var/ossec/logs/ossec.log | grep -i warn
2022/10/04 08:36:15 wazuh-modulesd: WARNING: The <ignore_time> tag at module 'vulnerability-detector' is deprecated for version newer than 4.3.
2022/10/04 08:36:26 wazuh-modulesd: WARNING: The <ignore_time> tag at module 'vulnerability-detector' is deprecated for version newer than 4.3.
2022/10/04 08:36:35 wazuh-modulesd: WARNING: The <ignore_time> tag at module 'vulnerability-detector' is deprecated for version newer than 4.3.
2022/10/04 08:36:46 wazuh-modulesd: WARNING: The <ignore_time> tag at module 'vulnerability-detector' is deprecated for version newer than 4.3.
```


</details>



<details>

<summary> Run the runtest.py testing tool to verify no MITRE technique or tactic is missing in the DB.  </summary> <blockquote>


<details>

The runtest.py script runs correctly, without generating any warning in the manager log.

<summary> runtest result </summary>



```
|Component |  Tested  |  Total   | Coverage |
| -------- | -------- | -------- | -------- |
|  Rules   |   1164   |   4102   |  28.38%  |
| Decoders |   120    |   165    |  72.73%  |


|          File           |  Passed  |  Failed  |  Status  |
|        --------         | -------- | -------- | -------- |
|./tests/sysmon.ini       |    3     |    0     |   ✅    |
|./tests/proftpd.ini      |    7     |    0     |   ✅    |
|./tests/junos.ini        |    3     |    0     |   ✅    |
|./tests/dovecot.ini      |    15    |    0     |   ✅    |
|./tests/test_expr_negation.ini|    56    |    0     |   ✅    |
|./tests/exim.ini         |    7     |    0     |   ✅    |
|./tests/gcp.ini          |    31    |    0     |   ✅    |
|./tests/pix.ini          |    22    |    0     |   ✅    |
|./tests/api.ini          |    20    |    0     |   ✅    |
|./tests/sophos.ini       |    8     |    0     |   ✅    |
|./tests/SonicWall.ini    |    11    |    0     |   ✅    |
|./tests/pfsense.ini      |    2     |    0     |   ✅    |
|./tests/iptables.ini     |    8     |    0     |   ✅    |
|./tests/cisco_asa.ini    |    88    |    0     |   ✅    |
|./tests/dropbear.ini     |    3     |    0     |   ✅    |
|./tests/systemd.ini      |    2     |    0     |   ✅    |
|./tests/web_appsec.ini   |    31    |    0     |   ✅    |
|./tests/vsftpd.ini       |    4     |    0     |   ✅    |
|./tests/panda_paps.ini   |    8     |    0     |   ✅    |
|./tests/mailscanner.ini  |    1     |    0     |   ✅    |
|./tests/owlh.ini         |    4     |    0     |   ✅    |
|./tests/fortiauth.ini    |    4     |    0     |   ✅    |
|./tests/cisco_ios.ini    |    17    |    0     |   ✅    |
|./tests/openldap.ini     |    9     |    0     |   ✅    |
|./tests/firewalld.ini    |    2     |    0     |   ✅    |
|./tests/oscap.ini        |    32    |    0     |   ✅    |
|./tests/glpi.ini         |    3     |    0     |   ✅    |
|./tests/f5_big_ip.ini    |    48    |    0     |   ✅    |
|./tests/mcafee_epo.ini   |    1     |    0     |   ✅    |
|./tests/opensmtpd.ini    |    7     |    0     |   ✅    |
|./tests/exchange.ini     |    2     |    0     |   ✅    |
|./tests/unbound.ini      |    0     |    0     |   ✅    |
|./tests/netscreen.ini    |    4     |    0     |   ✅    |
|./tests/php.ini          |    2     |    0     |   ✅    |
|./tests/doas.ini         |    4     |    0     |   ✅    |
|./tests/huawei_usg.ini   |    3     |    0     |   ✅    |
|./tests/arbor.ini        |    2     |    0     |   ✅    |
|./tests/nginx.ini        |    12    |    0     |   ✅    |
|./tests/office365.ini    |   128    |    0     |   ✅    |
|./tests/paloalto.ini     |    16    |    0     |   ✅    |
|./tests/auditd.ini       |    31    |    0     |   ✅    |
|./tests/fortigate.ini    |    45    |    0     |   ✅    |
|./tests/nextcloud.ini    |    8     |    0     |   ✅    |
|./tests/ossec.ini        |    5     |    0     |   ✅    |
|./tests/web_rules.ini    |    10    |    0     |   ✅    |
|./tests/test_osregex_regex.ini|    28    |    0     |   ✅    |
|./tests/sudo.ini         |    8     |    0     |   ✅    |
|./tests/squid_rules.ini  |    2     |    0     |   ✅    |
|./tests/vuln_detector.ini|    2     |    0     |   ✅    |
|./tests/fortiddos.ini    |    1     |    0     |   ✅    |
|./tests/rsh.ini          |    2     |    0     |   ✅    |
|./tests/github.ini       |   324    |    0     |   ✅    |
|./tests/postfix.ini      |    2     |    0     |   ✅    |
|./tests/syslog.ini       |    6     |    0     |   ✅    |
|./tests/kernel_usb.ini   |    6     |    0     |   ✅    |
|./tests/samba.ini        |    4     |    0     |   ✅    |
|./tests/win_application.ini|    0     |    0     |   ✅    |
|./tests/apparmor.ini     |    5     |    0     |   ✅    |
|./tests/checkpoint_smart1.ini|    18    |    0     |   ✅    |
|./tests/fortimail.ini    |    6     |    0     |   ✅    |
|./tests/named.ini        |    5     |    0     |   ✅    |
|./tests/test_pcre2_regex.ini|    33    |    0     |   ✅    |
|./tests/sophos_fw.ini    |    10    |    0     |   ✅    |
|./tests/openvpn_ldap.ini |    2     |    0     |   ✅    |
|./tests/cimserver.ini    |    2     |    0     |   ✅    |
|./tests/test_osmatch_regex.ini|    6     |    0     |   ✅    |
|./tests/freepbx.ini      |    6     |    0     |   ✅    |
|./tests/overwrite.ini    |    10    |    0     |   ✅    |
|./tests/sshd.ini         |    48    |    0     |   ✅    |
|./tests/modsecurity.ini  |    6     |    0     |   ✅    |
|./tests/audit_scp.ini    |    8     |    0     |   ✅    |
|./tests/test_features.ini|    5     |    0     |   ✅    |
|./tests/cloudflare-waf.ini|    13    |    0     |   ✅    |
|./tests/cpanel.ini       |    7     |    0     |   ✅    |
|./tests/pam.ini          |    5     |    0     |   ✅    |
|./tests/su.ini           |    5     |    0     |   ✅    |
|./tests/apache.ini       |    12    |    0     |   ✅    |
|./tests/gitlab.ini       |    27    |    0     |   ✅    |
|./tests/aws_s3_access.ini|    10    |    0     |   ✅    |
|./tests/test_static_filters.ini|    28    |    0     |   ✅    |
|./tests/eset.ini         |    8     |    0     |   ✅    |
|./tests/fireeye.ini      |    3     |    0     |   ✅    |
|./tests/cisco_ftd.ini    |    42    |    0     |   ✅    |


```


</details>


</blockquote>


</details>

**Comment by Rebits** [comment]
## Out of the box :green_circle: 

<details>

<summary> enterprise-attack file correspond to the <code>ATT&CK version 11.3</code>  :green_circle: </summary>

No differences were founded
```
$ curl -o original.json  https://raw.githubusercontent.com/mitre/cti/ATT%26CK-v11.3/enterprise-attack/enterprise-attack.json
$curl -o wazuh.json https://github.com/wazuh/wazuh/blob/4d26998a35c27014c77f35d83d72d2ef9838aa5e/ruleset/mitre/enterprise-attack.json
$ diff original.json wazuh.json 
$
```

</details>

**Comment by jmv74211** [comment]
## QA review

- **Type**: Manual testing.
- **Status**: Approved 🟢 
- **Comments**:  Nothing unusual has been detected. Everything seems to be working properly
