### ISSUE TITLE
WPK Update on ALAS 2022 

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#3415]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|   4.4.0             |  https://github.com/wazuh/wazuh/issues/14982                    |    https://github.com/wazuh/wazuh/pull/15151          |

## Description
This development fixes WPK upgrade process for ALAS2022 agents. Testing needs to be done in order to verify it works properly.

## Proposed checks

- [x]  Update with WPK built from Sources

## Steps to reproduce

1. Install the 4.3.8-1 agent
2. Install 4.4.0 Manager
3. Build WPK (from sources/Jenkins)
4. Update agent with WPK file
5. Check agent has been properly updated
6. Check agent is working

## Expected results
Agent upgrades to 4.4.0 and works properly.

**Comment by chemamartinez** [comment]
@Deblintrake09 finally the issue was related to upgrading any agent with `aarch64` architecture. Doesn't matter the OS.

**Comment by Deblintrake09** [comment]
## Review data

| Tester | PR commit               | 
|--------|-------------------------|
| @Deblintrake09   | [46f61b0](https://github.com/wazuh/wazuh/commit/46f61b09036b4b6e701c760d8838f24566a31ba0) | 



### Testing environment

| OS | OS version | Deployment | Image/AMI 
|-- |-- |-- |-- 
| Centos | 8 | `Local \| Vagrant` | qactl/centos_8
| Windows Server | 2019 | `Local \| Vagrant` | qactl/windows_server_2019

### Tested packages

| OS | Package
|-- |--
| Centos |  [Manager 4.3.9-1](https://packages.wazuh.com/4.x/yum/wazuh-manager-4.3.9-1.x86_64.rpm)
| Windows | [Agent 4.3.9-1](https://packages.wazuh.com/4.x/windows/wazuh-agent-4.3.9-1.msi)


### Conclusion


### Status

- [ ] In progress
- [ ] Pending Review
- [ ] QA team leader approved @damarisg 
- [ ] QA manager approved @jmv74211 
- [ ] Development team leader approved @chemamartinez

**Comment by Deblintrake09** [comment]
# Task Results

1. Install Manager
2. Install agent 4.3.9-1
```
# /var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.3.9"
WAZUH_REVISION="40322"
WAZUH_TYPE="agent"
```
3. Build WPK from sources

**Comment by Deblintrake09** [comment]
# Task updates

## Update 2022/10/17
- Setup enviroment and test on aarch64 ALAS2 AMI - could not find ALAS2022 AMI used by core team.
- AMI could not connect to local VM or Deployer pipeline VM.

## Update 2022/10/18
- Setup new ALAS2 AMI and was able to configure connection
- Building WPK package failed while following the steps taken on the Issue.
- Got AMI used by core team. 
- Setup AMI and try to build package. Got Exception when building wpk.
- Research cause of error. Fixed error.
- Build WPK package.

**Comment by Deblintrake09** [comment]
## Update 2022/10/18
- Setup new ALAS2 AMI and was able to configure connection
- Building WPK package failed while following the steps taken on the Issue.
- Got AMI used by core team. 
- Setup AMI and try to build package. Got Exception when building wpk.
- Research cause of error. Fixed error.
- Build WPK package. 
- Tried to upgrade - Failed :red_circle:

**Comment by Deblintrake09** [comment]
# Task Results - Round 2


## Work on Fixed Branch

<details><summary>Build WPK and upgrade agent through CLI - Service Active :green_circle: </summary>

**In the manager **

. Install Manager
```
  Ejecutando scriptlet: wazuh-manager-4.4.0-3415.aarch64.wpk.   1/1 
  Verificando         : wazuh-manager-4.4.0-3415.aarch64.wpk.   1/1 

Instalado:
  wazuh-manager-4.4.0-3415.aarch64.wpk.fix.x86_64                   
```

**In Agent **
2. Install agent 4.3.9-1
```
# /var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.3.9"
WAZUH_REVISION="40322"
WAZUH_TYPE="agent"
```
3. Install dependencies
4.  Clone repo and modify the etc/preloaded-vars.conf file uncommenting the following lines:
```
# git clone https://www.github.com/wazuh/wazuh
# cd wazuh/src
# git checkout 14982-fix-aarch64-not-found
# nano etc/preloaded-vars.conf

USER_LANGUAGE="en"
USER_NO_STOP="y"
USER_UPDATE="y"
USER_BINARYINSTALL="y"
```
5. Build agent from sources
```
# make deps TARGET=agent && make TARGET=agent
    -DOSSECHIDS -DUSER="wazuh" -DGROUPGLOBAL="wazuh" -DLinux -DINOTIFY_ENABLED -D_XOPEN_SOURCE=600 -D_GNU_SOURCE -DENABLE_SYSC -DENABLE_CISCAT -DENABLE_AUDIT -DCLIENT
Compiler:
    CFLAGS            -pthread -Iexternal/libdb/build_unix/ -Iexternal/pacman/lib/libalpm/ -Iexternal/libarchive/libarchive -Wl,--start-group -Iexternal/audit-userspace/lib -DNDEBUG -O2 -DOSSECHIDS -DUSER="wazuh" -DGROUPGLOBAL="wazuh" -DLinux -DINOTIFY_ENABLED -D_XOPEN_SOURCE=600 -D_GNU_SOURCE -DENABLE_SYSC -DENABLE_CISCAT -DENABLE_AUDIT -DCLIENT -pipe -Wall -Wextra -std=gnu99 -I./ -I./headers/ -Iexternal/openssl/include -Iexternal/cJSON/ -Iexternal/libyaml/include -Iexternal/curl/include -Iexternal/msgpack/include -Iexternal/bzip2/ -Ishared_modules/common -Ishared_modules/dbsync/include -Ishared_modules/rsync/include -Iwazuh_modules/syscollector/include  -Idata_provider/include  -Iexternal/libpcre2/include -Iexternal/rpm//builddir/output/include 
    LDFLAGS           '-Wl,-rpath,/../lib' -pthread -lrt -ldl -O2 -Lshared_modules/dbsync/build/lib -Lshared_modules/rsync/build/lib  -Lwazuh_modules/syscollector/build/lib -Ldata_provider/build/lib
    LIBS              -lrt -ldl -lm 
    CC                cc
    MAKE              make
make[1]: Leaving directory '/home/ec2-user/wazuh/src'

Done building agent
```
6. Generate certificate WPK to sign wpk and replace root certificate
```
cd /tmp
openssl req -x509 -new -nodes -newkey rsa:2048 -keyout wpk_root.key -out wpk_root.pem -batch
openssl req -new -nodes -newkey rsa:2048 -keyout wpkcert.key -out wpkcert.csr -subj '/C=US/ST=CA/O=Wazuh'
openssl x509 -req -days 365 -in wpkcert.csr -CA wpk_root.pem -CAkey wpk_root.key -out wpkcert.pem -CAcreateserial
cd -
```
7. Delete unnecessary files
```
cd ../
rm -rf doc wodles/oscap/content/* gen_ossec.sh add_localfiles.sh Jenkinsfile*
rm -rf src/{addagent,analysisd,client-agent,config,error_messages,external/*,headers,logcollector,monitord,os_auth,os_crypto,os_csyslogd,os_dbdos_execd}
rm -rf src/{os_integrator,os_maild,os_netos_regex,os_xml,os_zlib,remoted,reportd,shared,syscheckd,tests,update,wazuh_db,wazuh_modules}
rm -rf src/win32
rm -rf src/*.a
rm -rf etc/{decoders,lists,rules}
find etc/templates/* -maxdepth 0 -not -name "en" | xargs rm -rf
```
8. Compile wpk package
```
tools/agent-upgrade/wpkpack.py /tmp/fixedagent.wpk /tmp/wpkcert.pem /tmp/wpkcert.key *
```
9. Copy wpk_root.pem to agent
```
scp -i KEY-PATH /tmp/wpk_root.pem user@ip:/var/ossec/etc
```
10. Check agent status in systemctl
```
● wazuh-agent.service - Wazuh agent
     Loaded: loaded (/etc/systemd/system/wazuh-agent.service; enabled; vendor preset: disabled)
     Active: active (running) since Thu 2022-10-20 16:32:25 UTC; 1min 5s ago
    Process: 40604 ExecStart=/usr/bin/env /var/ossec/bin/wazuh-control start (code=exited, status=0/S>
      Tasks: 21 (limit: 2109)
     Memory: 61.4M
        CPU: 7.376s
     CGroup: /system.slice/wazuh-agent.service
             ├─ 40632 /var/ossec/bin/wazuh-execd
             ├─ 40644 /var/ossec/bin/wazuh-agentd
             ├─ 40659 /var/ossec/bin/wazuh-syscheckd
             └─ 40672 /var/ossec/bin/wazuh-logcollector
```
11. Check that agent is registered
```
/var/ossec/bin/agent_control -i 003

Wazuh agent_control. Agent information:
   Agent ID:   003
   Agent Name: ip-172-31-12-133.ec2.internal
   IP address: any
   Status:     Active

   Operating system:    Linux |ip-172-31-12-133.ec2.internal |5.15.57-30.131.amzn2022.aarch64 |#1 SMP Wed Aug 17 23:50:18 UTC 2022 |aarch64
   Client version:      Wazuh v4.3.9
   Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
   Shared file hash:    4a8724b20dee0124ff9656783c490c4e
   Last keep alive:     1666283465

   Syscheck last started at:  Thu Oct 20 16:06:51 2022
   Syscheck last ended at:    Thu Oct 20 16:06:54 2022
```
12.  Upgrade agent
**In the Manager**
```
# /var/ossec/bin/agent_upgrade -a 002 -f /home/qa/fixedagent.wpk
Upgrading...

# cat /var/ossec/log/ossec.log
2022/10/20 16:36:12 wazuh-modulesd:agent-upgrade[137107] wm_agent_upgrade_manager.c:196 at wm_agent_upgrade_listen_messages(): DEBUG: (8156): Response message: '{"error":0,"data":[{"error":0,"message":"Success","agent":3,"task_id":5,"node":"node01","module":"upgrade_module","command":"upgrade_custom","status":"Updating","create_time":"2022/10/20 16:31:23","update_time":"2022/10/20 16:31:23"}],"message":"Success"}'
```

**In the agent**
13. Check upgrade status in log
```
# tail -f /var/ossec/logs/ossec.log

```
14. Check agent's info on manager
```
# /var/ossec/bin/agent_control -i 003

Wazuh agent_control. Agent information:
   Agent ID:   003
   Agent Name: ip-172-31-12-133.ec2.internal
   IP address: any
   Status:     Active

   Operating system:    Linux |ip-172-31-12-133.ec2.internal |5.15.57-30.131.amzn2022.aarch64 |#1 SMP Wed Aug 17 23:50:18 UTC 2022 |aarch64
   Client version:      Wazuh v4.4.0
   Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
   Shared file hash:    4a8724b20dee0124ff9656783c490c4e
   Last keep alive:     1666283772

   Syscheck last started at:  Thu Oct 20 16:32:20 2022
   Syscheck last ended at:    Thu Oct 20 16:32:23 2022
```
**In Agent**
15. Check upgrade.log results
```
# cat /var/ossec/logs/upgrade.log 
2022/10/20 16:32:02 - Generating Backup.
tar: ./var/ossec/queue/alerts/cfgaq: socket ignored
tar: ./var/ossec/queue/alerts/execq: socket ignored
tar: ./var/ossec/queue/sockets/com: socket ignored
tar: ./var/ossec/queue/sockets/logcollector: socket ignored
tar: ./var/ossec/queue/sockets/wmodules: socket ignored
tar: ./var/ossec/queue/sockets/control: socket ignored
tar: ./var/ossec/queue/sockets/upgrade: socket ignored
tar: ./var/ossec/queue/sockets/queue: socket ignored
tar: ./var/ossec/queue/sockets/syscheck: socket ignored
2022/10/20 16:32:04 - Upgrade started.

 Wazuh v4.4.0 (Rev. 40400) Installation Script - https://www.wazuh.com

 You are about to start the installation process of Wazuh.
 You must have a C compiler pre-installed in your system.

  - System: Linux ip-172-31-12-133.ec2.internal 5.15.57-30.131.amzn2022.aarch64 (amzn 1.0)
  - User: root
  - Host: ip-172-31-12-133.ec2.internal


  -- Press ENTER to continue or Ctrl-C to abort. --

 - You already have Wazuh installed. Do you want to update it? (y/n): 
    - Installation will be made at  /var/ossec .

4- Installing the system

DIR="/var/ossec"
 - Running the Makefile

Stopping Wazuh...
agent
Wait for success...
success
install: cannot stat 'wazuh_modules/syscollector/norm_config.json': No such file or directory
libsemanage.semanage_get_lock: Could not get direct transaction lock at /var/lib/selinux/targeted/semanage.trans.LOCK. (Resource temporarily unavailable).
semodule:  Failed on /tmp/wazuh.pp!
libsemanage.semanage_get_lock: Could not get direct transaction lock at /var/lib/selinux/targeted/semanage.trans.LOCK. (Resource temporarily unavailable).
semodule:  Failed on wazuh!
SCA policies are not available for this OS version amzn 1 0.


Wait for success...
success
Starting Wazuh...

 - Configuration finished properly.

 - To start Wazuh:
      /var/ossec/bin/wazuh-control start

 - To stop Wazuh:
      /var/ossec/bin/wazuh-control stop

 - The configuration can be viewed or modified at /var/ossec/etc/ossec.conf


   Thanks for using Wazuh.
   Please don't hesitate to contact us if you need help or find
   any bugs.

   Use our public Mailing List at:
          https://groups.google.com/forum/#!forum/wazuh

   More information can be found at:
          - http://www.wazuh.com

    ---  Press ENTER to finish (maybe more information below). ---

 - Update completed.

2022/10/20 16:32:25 - Installation result = 0
2022/10/20 16:32:26 - Waiting connection... Status = connected. Remaining attempts: 29.
2022/10/20 16:32:26 - Connected to manager.
2022/10/20 16:32:26 - Upgrade finished successfully.
```
</details>




<details><summary>Build WPK and upgrade agent through CLI - Service Inctive :green_circle: </summary>

**In Agent **
1. Install agent 4.3.9-1
```
# /var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.3.9"
WAZUH_REVISION="40322"
WAZUH_TYPE="agent"
```
2. Check agent status in systemctl
```
# systemctl status wazuh-agent.service 
○ wazuh-agent.service - Wazuh agent
     Loaded: loaded (/usr/lib/systemd/system/wazuh-agent.service; disabled; vendor preset: disabled)
     Active: inactive (dead)
```
3. Check that agent is registered
```
/var/ossec/bin/agent_control -i 004

Wazuh agent_control. Agent information:
   Agent ID:   004
   Agent Name: ALAS22-3
   IP address: any
   Status:     Active

   Operating system:    Linux |ip-172-31-12-133.ec2.internal |5.15.57-30.131.amzn2022.aarch64 |#1 SMP Wed Aug 17 23:50:18 UTC 2022 |aarch64
   Client version:      Wazuh v4.3.9
   Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
   Shared file hash:    4a8724b20dee0124ff9656783c490c4e
   Last keep alive:     1666284126

   Syscheck last started at:  Thu Oct 20 16:41:37 2022
   Syscheck last ended at:    Thu Oct 20 16:41:41 2022
```
4.  Upgrade agent
**In the Manager**
```
# /var/ossec/bin/agent_upgrade -a 004 -f /home/qa/fixedagent.wpk
Upgrading...

# cat /var/ossec/log/ossec.log
2022/10/20 16:36:12 wazuh-modulesd:agent-upgrade[137107] wm_agent_upgrade_manager.c:196 at wm_agent_upgrade_listen_messages(): DEBUG: (8156): Response message: '{"error":0,"data":[{"error":0,"message":"Success","agent":3,"task_id":5,"node":"node01","module":"upgrade_module","command":"upgrade_custom","status":"Updating","create_time":"2022/10/20 16:31:23","update_time":"2022/10/20 16:31:23"}],"message":"Success"}'
```

**In the agent**
5. Check upgrade status in log
```
# cat /var/ossec/log/upgrade.log
2022/10/20 16:43:16 - Generating Backup.
tar: ./var/ossec/queue/alerts/cfgaq: socket ignored
tar: ./var/ossec/queue/alerts/execq: socket ignored
tar: ./var/ossec/queue/sockets/wmodules: socket ignored
tar: ./var/ossec/queue/sockets/logcollector: socket ignored
tar: ./var/ossec/queue/sockets/control: socket ignored
tar: ./var/ossec/queue/sockets/com: socket ignored
tar: ./var/ossec/queue/sockets/upgrade: socket ignored
tar: ./var/ossec/queue/sockets/queue: socket ignored
tar: ./var/ossec/queue/sockets/syscheck: socket ignored
2022/10/20 16:43:18 - Upgrade started.

 Wazuh v4.4.0 (Rev. 40400) Installation Script - https://www.wazuh.com

 You are about to start the installation process of Wazuh.
 You must have a C compiler pre-installed in your system.

  - System: Linux ip-172-31-12-133.ec2.internal 5.15.57-30.131.amzn2022.aarch64 (amzn 1.0)
  - User: root
  - Host: ip-172-31-12-133.ec2.internal


  -- Press ENTER to continue or Ctrl-C to abort. --

 - You already have Wazuh installed. Do you want to update it? (y/n): 
    - Installation will be made at  /var/ossec .

4- Installing the system

DIR="/var/ossec"
 - Running the Makefile

Stopping Wazuh...
agent
Wait for success...
success
install: cannot stat 'wazuh_modules/syscollector/norm_config.json': No such file or directory
libsemanage.semanage_get_lock: Could not get direct transaction lock at /var/lib/selinux/targeted/semanage.trans.LOCK. (Resource temporarily unavailable).
semodule:  Failed on /tmp/wazuh.pp!
libsemanage.semanage_get_lock: Could not get direct transaction lock at /var/lib/selinux/targeted/semanage.trans.LOCK. (Resource temporarily unavailable).
semodule:  Failed on wazuh!
SCA policies are not available for this OS version amzn 1 0.


Wait for success...
success
Starting Wazuh...

 - Configuration finished properly.

 - To start Wazuh:
      /var/ossec/bin/wazuh-control start

 - To stop Wazuh:
      /var/ossec/bin/wazuh-control stop

 - The configuration can be viewed or modified at /var/ossec/etc/ossec.conf


   Thanks for using Wazuh.
   Please don't hesitate to contact us if you need help or find
   any bugs.

   Use our public Mailing List at:
          https://groups.google.com/forum/#!forum/wazuh

   More information can be found at:
          - http://www.wazuh.com

    ---  Press ENTER to finish (maybe more information below). ---

 - Update completed.

2022/10/20 16:43:38 - Installation result = 0
2022/10/20 16:43:39 - Waiting connection... Status = connected. Remaining attempts: 29.
2022/10/20 16:43:39 - Connected to manager.
2022/10/20 16:43:39 - Upgrade finished successfully.
```
6. Check agent's info on manager
```
# /var/ossec/bin/agent_control -i 004

Wazuh agent_control. Agent information:
   Agent ID:   004
   Agent Name: ALAS22-3
   IP address: any
   Status:     Active

   Operating system:    Linux |ip-172-31-12-133.ec2.internal |5.15.57-30.131.amzn2022.aarch64 |#1 SMP Wed Aug 17 23:50:18 UTC 2022 |aarch64
   Client version:      Wazuh v4.4.0
   Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
   Shared file hash:    4a8724b20dee0124ff9656783c490c4e
   Last keep alive:     1666284376

   Syscheck last started at:  Thu Oct 20 16:43:33 2022
   Syscheck last ended at:    Thu Oct 20 16:43:37 2022
```
6. Check agentd service status
```
# systemctl status wazuh-agent.service 
● wazuh-agent.service - Wazuh agent
     Loaded: loaded (/etc/systemd/system/wazuh-agent.service; disabled; vendor preset: disabled)
     Active: active (running) since Thu 2022-10-20 16:43:38 UTC; 3min 44s ago
    Process: 43825 ExecStart=/usr/bin/env /var/ossec/bin/wazuh-control start (code=exited, status=0/S>
      Tasks: 21 (limit: 2109)
     Memory: 8.0M
        CPU: 7.341s
     CGroup: /system.slice/wazuh-agent.service
             ├─ 43853 /var/ossec/bin/wazuh-execd
             ├─ 43865 /var/ossec/bin/wazuh-agentd
             ├─ 43880 /var/ossec/bin/wazuh-syscheckd
             └─ 43893 /var/ossec/bin/wazuh-logcollector

Oct 20 16:43:31 ip-172-31-12-133.ec2.internal systemd[1]: Starting wazuh-agent.service - Wazuh agent.>
Oct 20 16:43:31 ip-172-31-12-133.ec2.internal env[43825]: Starting Wazuh v4.4.0...
```
</details>

**Comment by jmv74211** [comment]
## Closing conclusion 👍🏼  

|| |
|-|-|
| 🔵 | Proposed to be fixed in future versions or developments | 

After talking with the team, the testing has been approved taking into account the following considerations proposed in the [QA review](https://github.com/wazuh/wazuh-qa/issues/2995#issuecomment-1282133037):

**(1). The steps indicated in the documentation for WPK generation are not correct.** 🔵

This is a known bug and it will be fixed in this PR https://github.com/wazuh/wazuh-documentation/pull/5701
