### ISSUE TITLE
OpenWRT decoder fixed and UFW decoder improved

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh-qa#3422]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|          4.4.0              |       https://github.com/wazuh/wazuh/issues/11609                 |           https://github.com/wazuh/wazuh/pull/11613         |

## Description

An OpenWRT decoder's prematch was too generic and it was not capturing the `action` field as expected. This was causing that events were not collected because the `action` field was missing.

## Proposed checks

- [x] Verify that the decoder now collects the `action` field
- [x] Verify that ufw events are now gathered in archives/alerts

## Steps to reproduce

If you use any log that follows this format, it will be consumed:
```
[NUMBER.NUMBER]⎵SOMETHING⎵SOMETHING_ELSE⎵IN=
```
For example:
```
Dec 26 09:05:47 server01 kernel: [126140.629122] [UFW BLOCK] IN=eth0 OUT= MAC=00:11:22:33:44:55:66:77:88:99:aa:bb:cc:dd SRC=254.253.252.251 DST=191.192.193.194 LEN=52 TOS=0x02 PREC=0x00 TTL=128 ID=9209 DF PROTO=TCP SPT=17833 DPT=22 WINDOW=8192 RES=0x00 CWR ECE SYN URGP=0
```

## Expected results

The `action` field should be collected correctly.

<details><summary>Example</summary>

```
# /var/ossec/bin/wazuh-logtest
Starting wazuh-logtest v4.3.8
Type one log per line

Sep 20 15:52:00 managerHost kernel: [ 2870.303541] [UFW AUDIT] IN= OUT=ppp0 SRC=117.197.243.67 DST=218.248.255.163 LEN=62 TOS=0x00 PREC=0x00 TTL=64 ID=52751 DF PROTO=UDP SPT=57548 DPT=53 LEN=42

**Phase 1: Completed pre-decoding.
	full event: 'Sep 20 15:52:00 managerHost kernel: [ 2870.303541] [UFW AUDIT] IN= OUT=ppp0 SRC=117.197.243.67 DST=218.248.255.163 LEN=62 TOS=0x00 PREC=0x00 TTL=64 ID=52751 DF PROTO=UDP SPT=57548 DPT=53 LEN=42'
	timestamp: 'Sep 20 15:52:00'
	hostname: 'managerHost'
	program_name: 'kernel'

**Phase 2: Completed decoding.
	name: 'kernel'
	parent: 'kernel'
	action: 'AUDIT'
	dstip: '218.248.255.163'
	dstport: '53'
	protocol: 'UDP'
	srcip: '117.197.243.67'
	srcport: '57548'

**Phase 3: Completed filtering (rules).
	id: '4100'
	level: '0'
	description: 'Firewall rules grouped.'
	groups: '['firewall']'
	firedtimes: '8'
	mail: 'False'
```
</details>

**Comment by roronoasins** [comment]
## Review data

| Tester | PR commit               | 
|--------|-------------------------|
| @roronoasins   |  [64580a3](https://github.com/wazuh/wazuh/pull/11613/commits/64580a3d304549172c72a11dfb3172b975a68333)   | 

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
|  Ubuntu  | 22 | `AWS` | `ami-003530de8839921c4`| Deployed and provisioned with internal pipeline |

### Tested packages

| `wazuh-manager` |
|-----------------|
|  [4.4.0 - deb](https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/deb/var/wazuh-manager_4.4.0-0.commit)  |

### Status

- [x] In progress (@roronoasins)
- [ ] Pending Review
- [ ] QA team leader approved (@damarisg)
- [ ] QA manager approved (@jmv74211)
- [ ] Development team leader approved

### Conclusion :large_blue_circle:

**Comment by roronoasins** [comment]
# Tasks

## Unfixed version

<details><summary>Verify that the decoder collects the <code>action</code> field :red_circle:</summary>

1. Install `4.3.8` manager from production

2. Run `wazuh-logtest` and check the following logs

    <details><summary><code>Dec 26 09:05:47 server01 kernel: [126140.629122] [UFW BLOCK] IN=eth0 OUT=ppp0 MAC=00:11:22:33:44:55:66:77:88:99:aa:bb:cc:dd SRC=254.253.252.251 DST=191.192.193.194 LEN=52 TOS=0x02 PREC=0x00 TTL=128 ID=9209 DF PROTO=TCP SPT=17833 DPT=22 WINDOW=8192 RES=0x00 CWR ECE SYN URGP=0</code> :red_circle:</summary>
       
       Dec 26 09:05:47 server01 kernel: [126140.629122] [UFW BLOCK] IN=eth0 OUT=ppp0 MAC=00:11:22:33:44:55:66:77:88:99:aa:bb:cc:dd SRC=254.253.252.251 DST=191.192.193.194 LEN=52 TOS=0x02 PREC=0x00 TTL=128 ID=9209 DF PROTO=TCP SPT=17833 DPT=22 WINDOW=8192 RES=0x00 CWR ECE SYN URGP=0

       **Phase 1: Completed pre-decoding.
           full event: 'Dec 26 09:05:47 server01 kernel: [126140.629122] [UFW BLOCK] IN=eth0 OUT=ppp0 MAC=00:11:22:33:44:55:66:77:88:99:aa:bb:cc:dd SRC=254.253.252.251 DST=191.192.193.194 LEN=52 TOS=0x02 PREC=0x00 TTL=128 ID=9209 DF PROTO=TCP SPT=17833 DPT=22 WINDOW=8192 RES=0x00 CWR ECE SYN URGP=0'
           timestamp: 'Dec 26 09:05:47'
           hostname: 'server01'
           program_name: 'kernel'
   
       **Phase 2: Completed decoding.
           name: 'kernel'
           parent: 'kernel'
           dstip: '191.192.193.194'
           dstport: '22'
           protocol: 'TCP'
           srcip: '254.253.252.251'
           srcport: '17833'
   
       **Phase 3: Completed filtering (rules).
           id: '4100'
           level: '0'
           description: 'Firewall rules grouped.'
           groups: '['firewall']'
           firedtimes: '4'
           mail: 'False'

    </details>

    <details><summary><code>Sep 20 15:52:00 managerHost kernel: [ 2870.303541] [UFW AUDIT] IN=eth0 OUT=ppp0 SRC=117.197.243.67 DST=218.248.255.163 LEN=62 TOS=0x00 PREC=0x00 TTL=64 ID=52751 DF PROTO=UDP SPT=57548 DPT=53 LEN=42</code> :green_circle:</summary>
       
        Sep 20 15:52:00 managerHost kernel: [ 2870.303541] [UFW AUDIT] IN=eth0 OUT=ppp0 SRC=117.197.243.67 DST=218.248.255.163 LEN=62 TOS=0x00 PREC=0x00 TTL=64 ID=52751 DF PROTO=UDP SPT=57548 DPT=53 LEN=42

        **Phase 1: Completed pre-decoding.
            full event: 'Sep 20 15:52:00 managerHost kernel: [ 2870.303541] [UFW AUDIT] IN=eth0 OUT=ppp0 SRC=117.197.243.67 DST=218.248.255.163 LEN=62 TOS=0x00 PREC=0x00 TTL=64 ID=52751 DF PROTO=UDP SPT=57548 DPT=53 LEN=42'
            timestamp: 'Sep 20 15:52:00'
            hostname: 'managerHost'
            program_name: 'kernel'

        **Phase 2: Completed decoding.
            name: 'kernel'
            parent: 'kernel'
            action: 'UFW AUDIT'
            dstip: '218.248.255.163'
            dstport: '53'
            protocol: 'UDP'
            srcip: '117.197.243.67'
            srcport: '57548'

        **Phase 3: Completed filtering (rules).
            id: '4100'
            level: '0'
            description: 'Firewall rules grouped.'
            groups: '['firewall']'
            firedtimes: '6'
            mail: 'False'

    </details>


    <details><summary><code>Feb  4 23:33:37 hostname kernel: [ 3529.289825] [UFW BLOCK] IN=eth0 OUT=ppp0 MAC=00:11:22:33:44:55:66:77:88:99:aa:bb:cc:dd SRC=444.333.222.111 DST=111.222.333.444 LEN=103 TOS=0x00 PREC=0x00 TTL=52 ID=0 DF PROTO=UDP SPT=53 DPT=36427 LEN=83</code> :green_circle:</summary>
            
        Feb  4 23:33:37 hostname kernel: [ 3529.289825] [UFW BLOCK] IN=eth0 OUT=ppp0 MAC=00:11:22:33:44:55:66:77:88:99:aa:bb:cc:dd SRC=444.333.222.111 DST=111.222.333.444 LEN=103 TOS=0x00 PREC=0x00 TTL=52 ID=0 DF PROTO=UDP SPT=53 DPT=36427 LEN=83

        **Phase 1: Completed pre-decoding.
            full event: 'Feb  4 23:33:37 hostname kernel: [ 3529.289825] [UFW BLOCK] IN=eth0 OUT=ppp0 MAC=00:11:22:33:44:55:66:77:88:99:aa:bb:cc:dd SRC=444.333.222.111 DST=111.222.333.444 LEN=103 TOS=0x00 PREC=0x00 TTL=52 ID=0 DF PROTO=UDP SPT=53 DPT=36427 LEN=83'
            timestamp: 'Feb  4 23:33:37'
            hostname: 'hostname'
            program_name: 'kernel'

        **Phase 2: Completed decoding.
            name: 'kernel'
            parent: 'kernel'
            action: 'UFW BLOCK'
            dstip: '111.222.333.444'
            dstport: '36427'
            protocol: 'UDP'
            srcip: '444.333.222.111'
            srcport: '53'

        **Phase 3: Completed filtering (rules).
            id: '4100'
            level: '0'
            description: 'Firewall rules grouped.'
            groups: '['firewall']'
            firedtimes: '7'
            mail: 'False'

    </details>


    <details><summary><code>Aug 17 10:03:37 myhostname kernel: SFW2-INext-DROP-DEFLT IN=eth0 OUT=ppp0 MAC=00:08:02:da:c8:51:00:0f:f7:74:31:8a:08:00 SRC=1.2.3.36 DST=1.2.3.194 LEN=28 TOS=0x00 PREC=0x00 TTL=44 ID=60200 PROTO=ICMP TYPE=8 CODE=0 ID=10466 SEQ=21229</code> :green_circle:</summary>
       
        Aug 17 10:03:37 myhostname kernel: SFW2-INext-DROP-DEFLT IN=eth0 OUT=ppp0 MAC=00:08:02:da:c8:51:00:0f:f7:74:31:8a:08:00 SRC=1.2.3.36 DST=1.2.3.194 LEN=28 TOS=0x00 PREC=0x00 TTL=44 ID=60200 PROTO=ICMP TYPE=8 CODE=0 ID=10466 SEQ=21229 

        **Phase 1: Completed pre-decoding.
            full event: 'Aug 17 10:03:37 myhostname kernel: SFW2-INext-DROP-DEFLT IN=eth0 OUT=ppp0 MAC=00:08:02:da:c8:51:00:0f:f7:74:31:8a:08:00 SRC=1.2.3.36 DST=1.2.3.194 LEN=28 TOS=0x00 PREC=0x00 TTL=44 ID=60200 PROTO=ICMP TYPE=8 CODE=0 ID=10466 SEQ=21229 '
            timestamp: 'Aug 17 10:03:37'
            hostname: 'myhostname'
            program_name: 'kernel'

        **Phase 2: Completed decoding.
            name: 'kernel'
            parent: 'kernel'
            action: 'SFW2-INext-DROP-DEFLT'
            dstip: '1.2.3.194'
            protocol: 'ICMP'
            srcip: '1.2.3.36'

        **Phase 3: Completed filtering (rules).
            id: '4100'
            level: '0'
            description: 'Firewall rules grouped.'
            groups: '['firewall']'
            firedtimes: '13'
            mail: 'False'
    

    </details>


    <details><summary><code>Aug 17 10:03:37 myhostname kernel:FIREWALL_OUT IN=eth0 OUT=eth0 SRC=192.168.6.57 DST=216.161.248.225 LEN=40 TOS=0x00 PREC=0x00 TTL=64 ID=18547 DF PROTO=TCP SPT=46388 DPT=37628 WINDOW=6930 RES=0x00 ACK RST URGn=0</code> :green_circle:</summary>
       
        Aug 17 10:03:37 myhostname kernel:FIREWALL_OUT IN=eth0 OUT=eth0 SRC=192.168.6.57 DST=216.161.248.225 LEN=40 TOS=0x00 PREC=0x00 TTL=64 ID=18547 DF PROTO=TCP SPT=46388 DPT=37628 WINDOW=6930 RES=0x00 ACK RST URGn=0

        **Phase 1: Completed pre-decoding.
            full event: 'Aug 17 10:03:37 myhostname kernel:FIREWALL_OUT IN=eth0 OUT=eth0 SRC=192.168.6.57 DST=216.161.248.225 LEN=40 TOS=0x00 PREC=0x00 TTL=64 ID=18547 DF PROTO=TCP SPT=46388 DPT=37628 WINDOW=6930 RES=0x00 ACK RST URGn=0'
            timestamp: 'Aug 17 10:03:37'
            hostname: 'myhostname'
            program_name: 'kernel'

        **Phase 2: Completed decoding.
            name: 'kernel'
            parent: 'kernel'
            action: 'FIREWALL_OUT'
            dstip: '216.161.248.225'
            dstport: '37628'
            protocol: 'TCP'
            srcip: '192.168.6.57'
            srcport: '46388'

        **Phase 3: Completed filtering (rules).
            id: '4100'
            level: '0'
            description: 'Firewall rules grouped.'
            groups: '['firewall']'
            firedtimes: '17'
            mail: 'False'
       
    </details>


    <details><summary><code>Aug 17 10:03:37 myhostname kernel: IPTABLE IN=eth0 OUT= MAC=ff:ff:ff:ff:ff:ff:00:03:93:db:2e:b4:08:00 SRC=10.4.11.40 DST=255.255.255.255 LEN=180 TOS=0x00 PREC=0x00 TTL=64 ID=4753 PROTO=UDP SPT=49320 DPT=2222 LEN=160</code> :green_circle:</summary>
       
        Aug 17 10:03:37 myhostname kernel: IPTABLE IN=eth0 OUT= MAC=ff:ff:ff:ff:ff:ff:00:03:93:db:2e:b4:08:00 SRC=10.4.11.40 DST=255.255.255.255 LEN=180 TOS=0x00 PREC=0x00 TTL=64 ID=4753 PROTO=UDP SPT=49320 DPT=2222 LEN=160

        **Phase 1: Completed pre-decoding.
            full event: 'Aug 17 10:03:37 myhostname kernel: IPTABLE IN=eth0 OUT= MAC=ff:ff:ff:ff:ff:ff:00:03:93:db:2e:b4:08:00 SRC=10.4.11.40 DST=255.255.255.255 LEN=180 TOS=0x00 PREC=0x00 TTL=64 ID=4753 PROTO=UDP SPT=49320 DPT=2222 LEN=160'
            timestamp: 'Aug 17 10:03:37'
            hostname: 'myhostname'
            program_name: 'kernel'

        **Phase 2: Completed decoding.
            name: 'kernel'
            parent: 'kernel'
            action: 'IPTABLE'
            dstip: '255.255.255.255'
            dstport: '2222'
            protocol: 'UDP'
            srcip: '10.4.11.40'
            srcport: '49320'

        **Phase 3: Completed filtering (rules).
            id: '4100'
            level: '0'
            description: 'Firewall rules grouped.'
            groups: '['firewall']'
            firedtimes: '16'
            mail: 'False'

    </details>
   
</details>

<details><summary>Verify that ruleset tests pass :large_blue_circle:</summary>

</details>

<details><summary>Verify that ufw events are now gathered in archives/alerts :large_blue_circle:</summary>

</details>

## Upgrade to fixed version

<details><summary>Verify that the decoder collects the <code>action</code> field</summary>

</details>

<details><summary>Verify that ruleset tests pass</summary>

</details>

<details><summary>Verify that ufw events are now gathered in archives/alerts</summary>

</details>

## Fresh install with fix

<details><summary>Verify that the decoder collects the <code>action</code> field</summary>

</details>

<details><summary>Verify that ruleset tests pass</summary>

</details>

<details><summary>Verify that ufw events are now gathered in archives/alerts</summary>

</details>

**Comment by jmv74211** [comment]
## QA review

- **Type**: Manual testing.
- **Status**: Requested changes 🔴 
- **Comments**: The tester has not found any related issues with the new made changes, but I have found the following:
    - ***(1)* Action field seems to be not decoded correctly**.

        Given the following log:

        ```
        Dec 26 09:05:47 server01 kernel: [126140.629122] [UFW BLOCK] IN=eth0 OUT=ppp0 MAC=00:11:22:33:44:55:66:77:88:99:aa:bb:cc:dd SRC=254.253.252.251 DST=191.192.193.194 LEN=52 TOS=0x02 PREC=0x00 TTL=128 ID=9209 DF PROTO=TCP SPT=17833 DPT=22 WINDOW=8192 RES=0x00 CWR ECE SYN URGP=0 green_circle
        ```

        the action field is decoded as `BLOCK`, however, it should be decoded as `UFW BLOCK`, right?


All of this will be discussed with the development team, and approved or not based on these findings.

**Comment by JcabreraC** [comment]
> ## QA review
> 
>     * **Type**: Manual testing.
> 
>     * **Status**: Requested changes red_circle
> 
>     * **Comments**: The tester has not found any related issues with the new made changes, but I have found the following:
>       
>       * **_(1)_ Action field seems to be not decoded correctly**.
>         Given the following log:
>         ```
>         Dec 26 09:05:47 server01 kernel: [126140.629122] [UFW BLOCK] IN=eth0 OUT=ppp0 MAC=00:11:22:33:44:55:66:77:88:99:aa:bb:cc:dd SRC=254.253.252.251 DST=191.192.193.194 LEN=52 TOS=0x02 PREC=0x00 TTL=128 ID=9209 DF PROTO=TCP SPT=17833 DPT=22 WINDOW=8192 RES=0x00 CWR ECE SYN URGP=0 green_circle
>         ```
>         
>         
>             
>               
>             
>         
>               
>             
>         
>             
>           
>         the action field is decoded as `BLOCK`, however, it should be decoded as `UFW BLOCK`, right?
> 
> 
> All of this will be discussed with the development team, and approved or not based on these findings.

Done ! 

The `action` field has `UFW` again since it changed not only the `Block`, but also others like `audit` when it was removed.

The output is again `UFW BLOCK`.

**Comment by roronoasins** [comment]
## Testing after requested changes

- Tester: @roronoasins 
- PR commit: https://github.com/wazuh/wazuh/pull/11613/commits/15740c5ed9bfe13c06d8ccd8887dfa2c4d34f1bc

***

### Results


<details><summary><code>Dec 26 09:05:47 server01 kernel: [126140.629122] [UFW BLOCK] IN=eth0 OUT=ppp0 MAC=00:11:22:33:44:55:66:77:88:99:aa:bb:cc:dd SRC=254.253.252.251 DST=191.192.193.194 LEN=52 TOS=0x02 PREC=0x00 TTL=128 ID=9209 DF PROTO=TCP SPT=17833 DPT=22 WINDOW=8192 RES=0x00 CWR ECE SYN URGP=0</code> :green_circle:</summary>

  ```
  Dec 26 09:05:47 server01 kernel: [126140.629122] [UFW BLOCK] IN=eth0 OUT=ppp0 MAC=00:11:22:33:44:55:66:77:88:99:aa:bb:cc:dd SRC=254.253.252.251 DST=191.192.193.194 LEN=52 TOS=0x02 PREC=0x00 TTL=128 ID=9209 DF PROTO=TCP SPT=17833 DPT=22 WINDOW=8192 RES=0x00 CWR ECE SYN URGP=0

  **Phase 1: Completed pre-decoding.
    full event: 'Dec 26 09:05:47 server01 kernel: [126140.629122] [UFW BLOCK] IN=eth0 OUT=ppp0 MAC=00:11:22:33:44:55:66:77:88:99:aa:bb:cc:dd SRC=254.253.252.251 DST=191.192.193.194 LEN=52 TOS=0x02 PREC=0x00 TTL=128 ID=9209 DF PROTO=TCP SPT=17833 DPT=22 WINDOW=8192 RES=0x00 CWR ECE SYN URGP=0'
    timestamp: 'Dec 26 09:05:47'
    hostname: 'server01'
    program_name: 'kernel'

  **Phase 2: Completed decoding.
    name: 'kernel'
    parent: 'kernel'
    action: 'UFW BLOCK'
    dstip: '191.192.193.194'
    dstport: '22'
    protocol: 'TCP'
    srcip: '254.253.252.251'
    srcport: '17833'

  **Phase 3: Completed filtering (rules).
    id: '4100'
    level: '0'
    description: 'Firewall rules grouped.'
    groups: '['firewall']'
    firedtimes: '1'
    mail: 'False'
  ```

</details>

<details><summary><code>Sep 20 15:52:00 managerHost kernel: [ 2870.303541] [UFW AUDIT] IN=eth0 OUT=ppp0 SRC=117.197.243.67 DST=218.248.255.163 LEN=62 TOS=0x00 PREC=0x00 TTL=64 ID=52751 DF PROTO=UDP SPT=57548 DPT=53 LEN=42</code> :green_circle:</summary>
  
  ```
  Sep 20 15:52:00 managerHost kernel: [ 2870.303541] [UFW AUDIT] IN=eth0 OUT=ppp0 SRC=117.197.243.67 DST=218.248.255.163 LEN=62 TOS=0x00 PREC=0x00 TTL=64 ID=52751 DF PROTO=UDP SPT=57548 DPT=53 LEN=42

  **Phase 1: Completed pre-decoding.
    full event: 'Sep 20 15:52:00 managerHost kernel: [ 2870.303541] [UFW AUDIT] IN=eth0 OUT=ppp0 SRC=117.197.243.67 DST=218.248.255.163 LEN=62 TOS=0x00 PREC=0x00 TTL=64 ID=52751 DF PROTO=UDP SPT=57548 DPT=53 LEN=42'
    timestamp: 'Sep 20 15:52:00'
    hostname: 'managerHost'
    program_name: 'kernel'

  **Phase 2: Completed decoding.
    name: 'kernel'
    parent: 'kernel'
    action: 'UFW AUDIT'
    dstip: '218.248.255.163'
    dstport: '53'
    protocol: 'UDP'
    srcip: '117.197.243.67'
    srcport: '57548'

  **Phase 3: Completed filtering (rules).
    id: '4100'
    level: '0'
    description: 'Firewall rules grouped.'
    groups: '['firewall']'
    firedtimes: '2'
    mail: 'False'
  ```

</details>


<details><summary><code>Feb  4 23:33:37 hostname kernel: [ 3529.289825] [UFW BLOCK] IN=eth0 OUT=ppp0 MAC=00:11:22:33:44:55:66:77:88:99:aa:bb:cc:dd SRC=444.333.222.111 DST=111.222.333.444 LEN=103 TOS=0x00 PREC=0x00 TTL=52 ID=0 DF PROTO=UDP SPT=53 DPT=36427 LEN=83</code> :green_circle:</summary>
  
  ```
  Feb  4 23:33:37 hostname kernel: [ 3529.289825] [UFW BLOCK] IN=eth0 OUT=ppp0 MAC=00:11:22:33:44:55:66:77:88:99:aa:bb:cc:dd SRC=444.333.222.111 DST=111.222.333.444 LEN=103 TOS=0x00 PREC=0x00 TTL=52 ID=0 DF PROTO=UDP SPT=53 DPT=36427 LEN=83

  **Phase 1: Completed pre-decoding.
    full event: 'Feb  4 23:33:37 hostname kernel: [ 3529.289825] [UFW BLOCK] IN=eth0 OUT=ppp0 MAC=00:11:22:33:44:55:66:77:88:99:aa:bb:cc:dd SRC=444.333.222.111 DST=111.222.333.444 LEN=103 TOS=0x00 PREC=0x00 TTL=52 ID=0 DF PROTO=UDP SPT=53 DPT=36427 LEN=83'
    timestamp: 'Feb  4 23:33:37'
    hostname: 'hostname'
    program_name: 'kernel'

  **Phase 2: Completed decoding.
    name: 'kernel'
    parent: 'kernel'
    action: 'UFW BLOCK'
    dstip: '111.222.333.444'
    dstport: '36427'
    protocol: 'UDP'
    srcip: '444.333.222.111'
    srcport: '53'

  **Phase 3: Completed filtering (rules).
    id: '4100'
    level: '0'
    description: 'Firewall rules grouped.'
    groups: '['firewall']'
    firedtimes: '3'
    mail: 'False'
  ```

</details>


<details><summary><code>Aug 17 10:03:37 myhostname kernel: SFW2-INext-DROP-DEFLT IN=eth0 OUT=ppp0 MAC=00:08:02:da:c8:51:00:0f:f7:74:31:8a:08:00 SRC=1.2.3.36 DST=1.2.3.194 LEN=28 TOS=0x00 PREC=0x00 TTL=44 ID=60200 PROTO=ICMP TYPE=8 CODE=0 ID=10466 SEQ=21229</code> :green_circle:</summary>
  
  ```
  Aug 17 10:03:37 myhostname kernel: SFW2-INext-DROP-DEFLT IN=eth0 OUT=ppp0 MAC=00:08:02:da:c8:51:00:0f:f7:74:31:8a:08:00 SRC=1.2.3.36 DST=1.2.3.194 LEN=28 TOS=0x00 PREC=0x00 TTL=44 ID=60200 PROTO=ICMP TYPE=8 CODE=0 ID=10466 SEQ=21229 

  **Phase 1: Completed pre-decoding.
    full event: 'Aug 17 10:03:37 myhostname kernel: SFW2-INext-DROP-DEFLT IN=eth0 OUT=ppp0 MAC=00:08:02:da:c8:51:00:0f:f7:74:31:8a:08:00 SRC=1.2.3.36 DST=1.2.3.194 LEN=28 TOS=0x00 PREC=0x00 TTL=44 ID=60200 PROTO=ICMP TYPE=8 CODE=0 ID=10466 SEQ=21229 '
    timestamp: 'Aug 17 10:03:37'
    hostname: 'myhostname'
    program_name: 'kernel'

  **Phase 2: Completed decoding.
    name: 'kernel'
    parent: 'kernel'
    action: 'SFW2-INext-DROP-DEFLT'
    dstip: '1.2.3.194'
    protocol: 'ICMP'
    srcip: '1.2.3.36'

  **Phase 3: Completed filtering (rules).
    id: '4100'
    level: '0'
    description: 'Firewall rules grouped.'
    groups: '['firewall']'
    firedtimes: '4'
    mail: 'False'
  ```

</details>


<details><summary><code>Aug 17 10:03:37 myhostname kernel:FIREWALL_OUT IN=eth0 OUT=eth0 SRC=192.168.6.57 DST=216.161.248.225 LEN=40 TOS=0x00 PREC=0x00 TTL=64 ID=18547 DF PROTO=TCP SPT=46388 DPT=37628 WINDOW=6930 RES=0x00 ACK RST URGn=0</code> :green_circle:</summary>

  ```
  Aug 17 10:03:37 myhostname kernel:FIREWALL_OUT IN=eth0 OUT=eth0 SRC=192.168.6.57 DST=216.161.248.225 LEN=40 TOS=0x00 PREC=0x00 TTL=64 ID=18547 DF PROTO=TCP SPT=46388 DPT=37628 WINDOW=6930 RES=0x00 ACK RST URGn=0

  **Phase 1: Completed pre-decoding.
    full event: 'Aug 17 10:03:37 myhostname kernel:FIREWALL_OUT IN=eth0 OUT=eth0 SRC=192.168.6.57 DST=216.161.248.225 LEN=40 TOS=0x00 PREC=0x00 TTL=64 ID=18547 DF PROTO=TCP SPT=46388 DPT=37628 WINDOW=6930 RES=0x00 ACK RST URGn=0'
    timestamp: 'Aug 17 10:03:37'
    hostname: 'myhostname'
    program_name: 'kernel'

  **Phase 2: Completed decoding.
    name: 'kernel'
    parent: 'kernel'
    action: 'FIREWALL_OUT'
    dstip: '216.161.248.225'
    dstport: '37628'
    protocol: 'TCP'
    srcip: '192.168.6.57'
    srcport: '46388'

  **Phase 3: Completed filtering (rules).
    id: '4100'
    level: '0'
    description: 'Firewall rules grouped.'
    groups: '['firewall']'
    firedtimes: '5'
    mail: 'False'
  ```

</details>


<details><summary><code>Aug 17 10:03:37 myhostname kernel: IPTABLE IN=eth0 OUT= MAC=ff:ff:ff:ff:ff:ff:00:03:93:db:2e:b4:08:00 SRC=10.4.11.40 DST=255.255.255.255 LEN=180 TOS=0x00 PREC=0x00 TTL=64 ID=4753 PROTO=UDP SPT=49320 DPT=2222 LEN=160</code> :green_circle:</summary>
    
  ```
  Aug 17 10:03:37 myhostname kernel: IPTABLE IN=eth0 OUT= MAC=ff:ff:ff:ff:ff:ff:00:03:93:db:2e:b4:08:00 SRC=10.4.11.40 DST=255.255.255.255 LEN=180 TOS=0x00 PREC=0x00 TTL=64 ID=4753 PROTO=UDP SPT=49320 DPT=2222 LEN=160

  **Phase 1: Completed pre-decoding.
    full event: 'Aug 17 10:03:37 myhostname kernel: IPTABLE IN=eth0 OUT= MAC=ff:ff:ff:ff:ff:ff:00:03:93:db:2e:b4:08:00 SRC=10.4.11.40 DST=255.255.255.255 LEN=180 TOS=0x00 PREC=0x00 TTL=64 ID=4753 PROTO=UDP SPT=49320 DPT=2222 LEN=160'
    timestamp: 'Aug 17 10:03:37'
    hostname: 'myhostname'
    program_name: 'kernel'

  **Phase 2: Completed decoding.
    name: 'kernel'
    parent: 'kernel'
    action: 'IPTABLE'
    dstip: '255.255.255.255'
    dstport: '2222'
    protocol: 'UDP'
    srcip: '10.4.11.40'
    srcport: '49320'

  **Phase 3: Completed filtering (rules).
    id: '4100'
    level: '0'
    description: 'Firewall rules grouped.'
    groups: '['firewall']'
    firedtimes: '6'
    mail: 'False'
  ```

</details>


### Conclusion :green_circle:

After the required re-testing the compound `UFW X` action is collected and everything seems to works as expected.

**Comment by jmv74211** [comment]
## Closing conclusion 👍🏼  

|| |
|-|-|
| 🟢 | Solved 

The development has been approved taking into account the following considerations proposed in the [QA review](https://github.com/wazuh/wazuh-qa/issues/3410#issuecomment-1269747560):

***(1)*: Action field seems to be not decoded correctly.** 🟢 

After reporting this bug, it has been fixed and not it seems to work properly.
