### ISSUE TITLE
Check the engine's behavior with the first iteration of the refactor.

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh-qa#3469]
| Target version | Related issue | Related PR/dev branch |
|--------------------|--------------------|-----------------|
|           5.0             |          https://github.com/wazuh/wazuh/issues/15083              |          https://github.com/wazuh/wazuh/issues/11334          |

# Description

We need to test the engine to ensure that the rework works as expected. All the testing will be performed in the epic we will create. In this first issue will make our first contact with the engine and create the engine module within the qa framework.

# Proposed test cases

- [x] Compile the engine
- [x] Create the KVDB
- [x] Run the engine
- [x] Send events to the engine
- [x] Check that it creates the output

# Considerations

### Required

- Wazuh's branch with the development: `11334-dev-new-wazuh-engine`
-  [gcc-9](https://gist.github.com/alexandreelise/192a63e287018ddfc896bbcb70b219d4) installed.

### Steps to follows

<details><summary>Install dependecies</summary>
  
  ```
  install cmake 3.24.2 -> https://cmake.org/download/
  install libcurl4-openssl-dev 
  install go
  ```
  **Note:** When we have the wazuh repo with the engine's branch, the engine is located in `wazuh/src/engine`. 
</details>

<details><summary>Build the engine</summary>

  ```
  cd wazuh/src/engine
  mkdir build
  cd build
  cmake ..
  make
  ```
</details>

<details><summary>Setup engine and send events</summary>

- Create the KVDB(Key-Value DataBase)
    ```
    ./main kvdb -p /tmp/ -n win-security-categorization -i ../test/kvdb_input_files/windows/win-security-categorization.json -t json
    ```

- Run the engine:
    ```
    ./main run -f ../test/assets/ -e tcp:localhost:5054 -t 1 -k /tmp/ --environment demo-environment
    ```

- Check the output:
    ```
    tail -f /tmp/filepath.txt | jq
    ```

- Send the events to the engine:
    ```
    go run ../test/scripts/write_message.go -p tcp -s localhost:5054 -q 1 -l location "192.128.0.1 - - [26/Dec/2016:16:16:29 +0200] \"GET /favicon.ico HTTP/1.1\" 404 209"
    ```

</details>

**Comment by roronoasins** [comment]
# Tasks

<details><summary>Running the engine and testing a few events</summary>

1. Build the engine (this takes a long time)

2. Create the KVDB(Key-Value DataBase)
    ```
    ./main kvdb -p /tmp/ -n win-security-categorization -i ../test/kvdb_input_files/windows/win-security-categorization.json -t json
    ```

3. Run the engine:
    ```
    ./main run -f ../test/assets/ -e tcp:localhost:5054 -t 1 -k /tmp/ --environment demo-environment
    ```

4. We can check the output as follows:
    ```
    tail -f /tmp/filepath.txt | jq
    ```

5. Send the events to the engine:
    1. `192.128.0.1 - - [26/Dec/2016:16:16:29 +0200] \"GET /favicon.ico HTTP/1.1\`
        ```
        go run ../test/scripts/write_message.go -p tcp -s localhost:5054 -q 1 -l location "192.128.0.1 - - [26/Dec/2016:16:16:29 +0200] \"GET /favicon.ico HTTP/1.1\" 404 209"
        ```

        `/tmp/filepath.txt`
        ```
        {
            "wazuh": {
            "queue": 49,
            "origin": "location"
            },
            "event": {
            "original": "192.128.0.1 - - [26/Dec/2016:16:16:29 +0200] \"GET /favicon.ico HTTP/1.1\" 404 209",
            "kind": "event",
            "dataset": "apache.access",
            "category": [
                "web"
            ],
            "module": "apache",
            "outcome": "failure"
            },
            "http": {
            "response": {
                "status_code": 404,
                "body": {
                "bytes": 209
                }
            },
            "version": "1.1",
            "request": {
                "method": "GET"
            }
            },
            "url": {
            "original": "/favicon.ico"
            },
            "timestamp": "26/Dec/2016:16:16:29 +0200",
            "source": {
            "ip": "192.128.0.1"
            },
            "service": {
            "type": "apache"
            }
        }
        ```

    2. `Apr  8 10:34:43 omissis sshd[20220]: Did not receive identification string from 192.168.5.55`
        ```
        go run ../test/scripts/write_message.go -p tcp -s localhost:5054 -q 1 -l location "Apr  8 10:34:43 omissis sshd[20220]: Did not receive identification string from 192.168.5.55" 404 209"
        ```

        `/tmp/filepath.txt`
        ```
        {
            "wazuh": {
                "queue": 49,
                "origin": "location"
            },
            "event": {
                "original": "Apr  8 10:34:43 omissis sshd[20220]: Did not receive identification string from 192.168.5.55",
                "kind": "event"
            },
            "message": "Did not receive identification string from 192.168.5.55",
            "_": " ",
            "process": {
                "pid": 20220,
                "name": "sshd"
            },
            "host": {
                "hostname": "omissis"
            },
            "timestamp": "Apr  8 10:34:43",
            "related": {
                "hosts": [
                "omissis"
                ],
                "ip": [
                "192.168.5.55"
                ]
            },
            "source": {
                "ip": "192.168.5.55"
            }
        }
        ```

</details>


(`In Progress`) To be able to check more cases, a module will be added to our framework with the basic features so we can start adding modules, tests and cases.

The team has a go script that allows us to send events to the engine. This feature has been (researched and)recreated in Python, so we had a basic script that allows us to connect with he socket and to send messages to the engine using the expected format. The engine is waiting for messages like: `event_size:queue:location_string:event` in binary. The event size must be in little endian.

All these basic features had been added to the framework:

- Engine script: This one is being reworked so it is used with pytest(all the methods will be fixtures)
- `modules/engine`: contains the basic method that start and clean the engine environment. It uses the event monitor from the framework to check that event's output are generated.

As the framework needs the product, the engine script methods will be moved as fixtures and the test will be parametrized with the cases as yaml files.

**Comment by roronoasins** [comment]
## 14/10/22
I could not set up an environment with Wazuh and the engine to test the engine's pytest module with some aws logs I collected. Need to check and fix the module so it can be added to dev branch so it can be used in the test development of this module.

**Comment by roronoasins** [comment]
## 15/10/22

The wazuh+engine environment worked today and the pytest module has been tested. Few of AWS logs within the yaml case has been used within this minimal test. This first module approach will be added so we can start with tests dev.
```
============================================================================== 2 failed, 19 passed in 4.29s ==============================================================================
```

**Comment by roronoasins** [comment]
## 16/10/22

I've been working on cleaning the engine module that has been created for its testing dev. It will be added in https://github.com/wazuh/wazuh-qa/issues/3470 epic branch as the first approach. With the first module working, we can refactor and/or extend what we need to create new modules/tests/cases.
