### ISSUE TITLE
Add ITs for the new engine

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3488]
| Target version | Related issue | Related PR/dev branch |
|--------------------|--------------------|-----------------|
|           5.0             |          https://github.com/wazuh/wazuh-qa/issues/3470              |          https://github.com/wazuh/wazuh/issues/11334          |

## Description

Since the team is reworking the engine, we need to cover this new engine rework. This issue will test the new engine to ensure all is correct. 

## Proposed test cases

- [x] [Check the engine's behavior with the first iteration of the refactor.](https://github.com/wazuh/wazuh-qa/issues/3469)
- [ ] [Add engine inputs tests ](https://github.com/wazuh/wazuh-qa/issues/3474)
- [ ] [Add engine resources tests](https://github.com/wazuh/wazuh-qa/issues/3476)
- [ ] [Add engine output tests](https://github.com/wazuh/wazuh-qa/issues/3477)

> Note: 
> Branch with each development `3470-engine-testing-module`

**Comment by damarisg** [comment]
Duplicated.
