### ISSUE TITLE
Create a reliability test suite

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh-qa#3490]
## Description

It is necessary to create a test suite to test the reliability of Wazuh.

To achieve this objective we need to work on several tasks.

### Tasks

- [ ] Define which of the existing tests ensure the reliability of the product and divide them by module
- [ ] Define the missing tests that are required for each module
- [ ] Create the missing tests
- [ ] Create a pipeline to launch reliability tests
