### ISSUE TITLE
Tests development - Check SCA scan runs properly with the new PCRE2 regex engine 

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3505]
| Target version | Related issue | Related PR/dev branch | QA Epic
|--------------------|--------------------|-----------------|--|
|      4.5.0          |   https://github.com/wazuh/wazuh/issues/13931     | https://github.com/wazuh/wazuh/pull/17124  | https://github.com/wazuh/wazuh-qa/issues/3406

## Description
This development adds `PCRE2` regex engine support for SCA rule checks. IT test development is recommended for testing the correct working of SCA with `pcre2` and `osregex` as well, since there is no current testing done.

## Configurations
- SCA enabled.

### Tier 0

- [x] Check SCA scan runs properly
   - Steps to test
   ```
   - Configure SCA rule file
   - Start manager
   - Check SCA scan is completed
   - Check alerts are generated
   ```

## Considerations

- Test checks should be done in both engines osregex and pcre2
- When the sca policy file is changed, or the checksum changes, a new full scan is ran (This is useful to fire complete initial checks)

## To Do

- [x] Research with Manual Tests
- [x] Create IT Structure
- [x] Add IT + Documentation

**Comment by Deblintrake09** [comment]
### Tasks done

- Work on adding support on Jenkins pipeline
- Launch Jenkins instances :red_circle: 
- Asked for help on error

**Comment by Deblintrake09** [comment]
# Tasks Done
- Added support on jenkins pipeline on PR https://github.com/wazuh/wazuh-jenkins/pull/4383

**Comment by Deblintrake09** [comment]
### Update 2022/11/23
- Apply requested changes
- Launched jenkins instances

**Comment by Deblintrake09** [comment]
## Update 23/03/2023
- Check tests with updated Core Branch
- Check failing tests in Agent
