### ISSUE TITLE
Add performance tests for the new Vulnerability Detector 

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3522]
| Target version |Related PR/dev branch |Epic QA| QA branch | QA PR
|---|-------|---|--|--|
| - | - | https://github.com/wazuh/wazuh-qa/issues/3526 | 3493-e2e-performance | https://github.com/wazuh/wazuh-qa/pull/3511
## Description

It is necessary to create a test suite to test the performance of the new Vulnerability Detector. To achieve this objective a list of possible test cases was defined.

### Tasks

- [x] https://github.com/wazuh/wazuh-qa/issues/3493
- [x] #3521
- [ ] https://github.com/wazuh/wazuh-qa/issues/3570
- [ ] https://github.com/wazuh/wazuh-qa/issues/3571
- [ ] https://github.com/wazuh/wazuh-qa/issues/3572
- [ ] Add new issues when the development will ready

**Comment by BelenValdivia** [comment]
Testing will be redefined
