### ISSUE TITLE
Add data integrity tests for the new Vulnerability Detector 

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3525]
| Target version | Related PR/dev branch |Epic QA | QA branch | PR QA |
|---|-------|---|--|--|
| - | - | #3306| 3491-vd-data-integrity| https://github.com/wazuh/wazuh-qa/pull/3518

## Description

It is necessary to create a test suite to test the data integrity of the new Vulnerability Detector. To achieve this objective a list of possible test cases was defined:

- Check that the vulnerable package information matches the information collected by Wazuh in the last Syscollector scan

### Tasks

- [x] https://github.com/wazuh/wazuh-qa/issues/3491
- [ ] https://github.com/wazuh/wazuh-qa/issues/3573
- [ ] https://github.com/wazuh/wazuh-qa/issues/3574
- [ ] Add new issues when development is ready

**Comment by BelenValdivia** [comment]
Testing will be redefined

**Comment by BelenValdivia** [comment]
Testing will be redefined
