### ISSUE TITLE
Verify input behavior with the new engine

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3533]
| Target version | Related issue | Related PR/dev branch |
|--------------------|--------------------|-----------------|
|           5.0             |          https://github.com/wazuh/wazuh/issues/15083              |          https://github.com/wazuh/wazuh/issues/11334          |

## Description

Since the team is reworking the engine, we need to cover this new engine rework. This issue will add the new tests to the qa framework and if it was necessary, the manual testing.

First of all, the engine module should be added to the framework so we could start adding modules, their tests and their cases.

## Proposed test cases

- [ ] We want to test a correct input returns a valid result, an incorrect input returns an error and an unexpected input doesn't crash the program. The module to test are:
  - [x] https://github.com/wazuh/wazuh-qa/issues/3475
  - [x] https://github.com/wazuh/wazuh-qa/issues/3530
  - [x] https://github.com/wazuh/wazuh-qa/issues/3535
  - [x] https://github.com/wazuh/wazuh-qa/issues/3537

## Considerations

After the research and when the first module approach is created, we will add a module for each type(input, resources, output) and a test for each scenario(events, api, etc.) and its specific Tcases.

**Comment by roronoasins** [comment]
## Review data
| Tester | PR commit               |
|--------|-------------------------|
| @   |  |
### Testing environment
| OS | OS version | Deployment | Image/AMI
|-- |-- |-- |--|
### Tested packages
| OS | Package
|-- |--
### Conclusion

**Comment by roronoasins** [comment]
## Test results

**Comment by damarisg** [comment]
# [API](https://github.com/wazuh/wazuh-qa/issues/3475#issuecomment-1297460645)

## The `catalog` command
  - `list` parameter 
    - List loaded decoders :green_circle:
    - List loaded schemas :green_circle:
    - List loaded environments :green_circle:
    - List loaded outputs :green_circle:
    - List loaded rule 🔴 
    - List loaded filter 🔴 
  - `get` parameter
    - Obtain some decoders by its id and version :green_circle:
    - Obtain some decoders with non-existing version :yellow_circle:
  - `update` parameter
    - Update an existing decoder version :green_circle:
    - Update a non-existent item-type :red_circle:
    - Update a uncorrect id or version for a given item-type :yellow_circle:
  - `create` parameter
    - Create a custom decoder using a yml file :green_circle:
    - Create a custom decoder that already exists using a yml file :yellow_circle:
    - Create an item using a type that is not expected :yellow_circle:
  - `delete` parameter
    - Delete an existing decoder :green_circle:
    - Try to delete empty item type :yellow_circle:
    - Missing required parameter :yellow_circle:
    - Delete non-valid types, ids and versions :yellow_circle:
  - `validate` parameter
    - Validate a decoder with valid syntax 🟡 
    - Validate a decoder with no name section :yellow_circle:
    - Validate a decoder with no sources section :green_circle:
    - Validate a decoder with no check section :green_circle:
    - Validate a decoder with no parse section :green_circle:
  - `load` parameter
    - Could not load existing decoders :yellow_circle:
    - Load some decoders that already exists and other that do not :yellow_circle:
    - Path with special and unicode characters :green_circle:
    - Load decoders :green_circle:
    - Load decoder version :green_circle:
      
## The `kvdb` command
  - `-i/--input-file` parameter
    - Create a db using a json input file :green_circle:
    - Create db with a wrong formatted json :yellow_circle:
    - Create db using a non-existent input file :green_circle:
  - `-t/--input-type`
    - Create a db using a non valid input file format :green_circle:

**Comment by damarisg** [comment]
# RULESET

- Test the decoder addition process 🟢 

  > Note: Details in [3535 issue](https://github.com/wazuh/wazuh-qa/issues/3535#issuecomment-1302396782).
