### ISSUE TITLE
Syscollector coverage research

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3539]
## Description

The objective is to know the behavior of the syscollector, and the coverage supported for our framework.

## Tasks

- [x] Research of  Sycollector Behavior
- [x] Check coverage added
- [x] Propose new cases to test.
- [x] Analyze and create cases after validating them.

**Comment by mauromalara** [comment]
## Update 01/11/2022

WIP.

**Comment by mauromalara** [comment]
## Update 02/11/2022

- New tests proposed:
  - Integration:
    - Integration with Vuln Detector
    - Integration with WazuhDB
    - Integration with API

**Comment by mauromalara** [comment]
## Update 02/11/2022

<details><summary>Analysis</summary>

<br>

<table>
<thead>
  <tr>
    <th colspan="2"></th>
    <th colspan="6">Input values</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td rowspan="13">Conditions</td>
    <td>disabled</td>
    <td>yes</td>
    <td>no</td>
    <td>no</td>
    <td>no</td>
    <td>-</td>
    <td>invalid</td>
  </tr>
  <tr>
    <td>interval</td>
    <td>5s</td>
    <td>5s</td>
    <td>1s</td>
    <td>5s</td>
    <td>-</td>
    <td>-1</td>
  </tr>
  <tr>
    <td>scan_on_start</td>
    <td>yes</td>
    <td>no</td>
    <td>yes</td>
    <td>yes</td>
    <td>-</td>
    <td>invalid</td>
  </tr>
  <tr>
    <td>hardware</td>
    <td>yes</td>
    <td>no</td>
    <td>yes</td>
    <td>no</td>
    <td>-</td>
    <td>invalid</td>
  </tr>
  <tr>
    <td>os</td>
    <td>yes</td>
    <td>no</td>
    <td>yes</td>
    <td>no</td>
    <td>-</td>
    <td>invalid</td>
  </tr>
  <tr>
    <td>network</td>
    <td>yes</td>
    <td>no</td>
    <td>yes</td>
    <td>no</td>
    <td>-</td>
    <td>invalid</td>
  </tr>
  <tr>
    <td>packages</td>
    <td>yes</td>
    <td>no</td>
    <td>yes</td>
    <td>no</td>
    <td>-</td>
    <td>invalid</td>
  </tr>
  <tr>
    <td>ports</td>
    <td>yes</td>
    <td>no</td>
    <td>yes</td>
    <td>yes</td>
    <td>-</td>
    <td>invalid</td>
  </tr>
  <tr>
    <td>ports-&gt; all</td>
    <td>no</td>
    <td>no</td>
    <td>no</td>
    <td>yes</td>
    <td>-</td>
    <td>invalid</td>
  </tr>
  <tr>
    <td>processes</td>
    <td>yes</td>
    <td>no</td>
    <td>yes</td>
    <td>no</td>
    <td>-</td>
    <td>invalid</td>
  </tr>
  <tr>
    <td>hotfixes</td>
    <td>no</td>
    <td>no</td>
    <td>yes</td>
    <td>no</td>
    <td>-</td>
    <td>invalid</td>
  </tr>
  <tr>
    <td>synchronization</td>
    <td>yes</td>
    <td>yes</td>
    <td>yes</td>
    <td>yes</td>
    <td>-</td>
    <td>invalid</td>
  </tr>
  <tr>
    <td>max_eps</td>
    <td>10</td>
    <td>10</td>
    <td>0</td>
    <td>10</td>
    <td>-</td>
    <td>-1</td>
  </tr>
  <tr>
    <td rowspan="17">Expected results</td>
    <td>Syscollector is disabled </td>
    <td>X</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>Scan does not start</td>
    <td>X</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>Start scanning after X seconds</td>
    <td></td>
    <td>X</td>
    <td>X</td>
    <td>X</td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>Start scanning on startup</td>
    <td></td>
    <td></td>
    <td>X</td>
    <td>X</td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>Do not store any information</td>
    <td></td>
    <td>X</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>Scan hardware</td>
    <td></td>
    <td></td>
    <td>X</td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>Scan the os info</td>
    <td></td>
    <td></td>
    <td>X</td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>Scan network</td>
    <td></td>
    <td></td>
    <td>X</td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>Scan packages</td>
    <td></td>
    <td></td>
    <td>X</td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>Scan listening ports</td>
    <td></td>
    <td></td>
    <td>X</td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>Scan all ports</td>
    <td></td>
    <td></td>
    <td></td>
    <td>X</td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>Scan processes</td>
    <td></td>
    <td></td>
    <td>X</td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>Scan hotfixes</td>
    <td></td>
    <td></td>
    <td>X</td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>Do not synchronize anything</td>
    <td></td>
    <td>X</td>
    <td>X</td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>Synchronize the agent database with the manager's database</td>
    <td></td>
    <td></td>
    <td></td>
    <td>X</td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>X synchronization events per second are sending</td>
    <td></td>
    <td></td>
    <td></td>
    <td>X</td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td>Syscollector does not start and show errors</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td>X</td>
    <td>X</td>
  </tr>
</tbody>
</table>

</details>

<details><summary>Design</summary>

<br>

- Verify that the module does not start when it's disabled
- Verify that the scan starts after 5 seconds but no information is collected or synchronized when all scans are disabled
- Verify that the scan starts on startup and collects information, but no sync is performed and the scan starts again after 1 second (scanning only listening ports)
- Verify that the scan starts on startup scanning all ports and synchronizing the DB at 10 EPS
- Verify that the module doesn't start and show errors when invalid or empty options are configured

</details>
