### ISSUE TITLE
QA Planning: Process to open ports in syscollector (Linux)

### ISSUE THREAD

**Issue by BelenValdivia** [wazuh/wazuh-qa#3543]
## Description

This problem aims to investigate [Add process to open ports in syscollector (Linux)](https://github.com/wazuh/wazuh/issues/3859) to define the test cases to be carried out.

There is a lack of functionality for Linux port inventory.

# Development stage

- [x] Research the applied change.
- [x] Research if we have a test for this case.
- [x] Define the test cases. Identify the base cases, and then the rest of the tests as tier 2.
- [x] Define whether it is necessary to test systems, integration, or E2E. Create the corresponding issues.

**Comment by BelenValdivia** [comment]
# Task results

<details><summary>Research the applied change.</summary>

    This change affects `syscollector` , the goal is to increase the information provider by the `sys_ports` inventory by including, as now missing, process id and name data.
    

</details>

<details><summary>Research if we have a test for this case.</summary>

    We don't have tests for this case

</details>

<details><summary>Define the test cases. Identify the base cases, and then the rest of the tests as tier 2.</summary>

  <details><summary>Test cases </summary>
  
  ## Proposed checks


### Fresh Install

#### Ubuntu
- [ ] Check process id appears with default syscollector config (ports all="yes")
- [ ] Check process name appears with default syscollector config ports all="yes")
- [ ] Check process id appears with ports all="no" in  syscollector config
- [ ] Check process name appears with ports all="no" in syscollector config
- [ ] Check if the data of the process id or process name don't appear it's because it's NFS
- [ ] Modify process ports information and force a new scan and verify the changes are reflected in the inventory.

#### CentOS
-  Check process id appears with default syscollector config (ports all="yes")
-  Check process name appears with default syscollector config ports all="yes")
-  Check process id appears with ports all="no" in  syscollector config
-  Check process name appears with ports all="no" in syscollector config
-  Check if the data of the process id or process name don't appear it's because it's NFS


### Upgrade from production version to dev branch

#### Ubuntu
-  Check process id appears with default syscollector config (ports all="yes")
-  Check process name appears with default syscollector config ports all="yes")
-  Check process id appears with ports all="no" in  syscollector config
-  Check process name appears with ports all="no" in syscollector config
-  Check if the data of the process id or process name don't appear it's because it's NFS

#### CentOS
- Check process id appears with default syscollector config (ports all="yes")
- Check process name appears with default syscollector config ports all="yes")
-  Check process id appears with ports all="no" in  syscollector config
-  Check process name appears with ports all="no" in syscollector config
-  Check if the data of the process id or process name don't appear it's because it's NFS
-  Modify process ports information and force a new scan and verify the changes are reflected in the inventory.
...

## Expected results


- Agent:
   Process name and process id are in /var/ossec/queue/syscollector/db/local.db

- Manager:
  Process name and process id are in /var/ossec/queue/syscollector/db/centos_agent.db or /var/ossec/queue/syscollector/db/ubuntu_agent.db
</details>
   
<details><summary>Define whether it is necessary to test systems, integration, or E2E. Create the corresponding issues. </summary>

    - Add` syscollector` tests to cover ports inventory

</details>
