### ISSUE TITLE
Analysisd crashes when invalid if_sid is passed in

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#3557]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|    4.3.10          |  https://github.com/wazuh/wazuh/issues/15280                      |   https://github.com/wazuh/wazuh/pull/15303           |

## Description
This Issue aims to test the fix done in Analysisd to avoid segfault and crashes caused when a rule is loaded with an invalid if_sid.

When a rule with an invalid `if_sid` field is used, it is expected that the rule is ignored and Analysisd skips it, showing a log similar to:
```
2022/10/24 14:33:33 wazuh-analysisd: WARNING: (7606): Signature ID '255042' was not found. Invalid 'if_sid'. Rule '10078' will be ignored.
```

## Proposed checks

- [x] Loading rule with invalid `if_sid` does not crash analysisd.

## Steps to reproduce

- Install manager
- Copy invalid rules and configurations that cause error
```
# curl -OL https://github.com/wazuh/wazuh-saas/files/9798354/cf9eb9gh6m7t_config_20221017T0821_tqXPc68hvkMuwXGC.tar.gz
# tar -xvzf cf9eb9gh6m7t_config_20221017T0821_tqXPc68hvkMuwXGC.tar.gz
# cd var/ossec/etc/
# cp -f ossec.conf /var/ossec/etc/ossec.conf
# cp -rf decoders/* /var/ossec/etc/decoders/
# cp -rf rules/* /var/ossec/etc/rules/
# cp -rf lists/* /var/ossec/etc/lists/
# cd /var/ossec/etc/
# chown -R wazuh:wazuh decoders/
# chown -R wazuh:wazuh rules/
# chown -R wazuh:wazuh lists/
```
- Start manager

## Expected results
Starting the Wazuh manager with an invalid rule in the ruleset does not crash Analysisd.

**Comment by Deblintrake09** [comment]
## Review data

| Tester | PR commit               | 
|--------|-------------------------|
| @Deblintrake09   | https://github.com/wazuh/wazuh/commit/2258bdcd82c43dabe831e4b8b6694c308a12bb9d  | 



### Testing environment

| OS | OS version | Deployment | Image/AMI 
|-- |-- |-- |--|
| Centos | 8 | `Local \| Vagrant` | qactl/centos_8

### Tested packages

| OS | Package
|-- |--
| Manager | [4.3.6](https://packages.wazuh.com/4.x/yum/wazuh-manager-4.3.9-1.x86_64.rpm) -  [4.3.10 - fixed branch](https://packages-dev.wazuh.com/warehouse/test/4.3/rpm/var/wazuh-manager-4.3.10-3557.analysisd.crash.fix.x86_64.rpm)

### Conclusion
### Status

- [ ] In progress
- [ ] Pending Review
- [ ] QA team leader approved @damarisg 
- [ ] QA manager approved @jmv74211 
- [ ] Development team leader approved @chemamartinez

**Comment by Deblintrake09** [comment]
## Testing Results

### Tasks on 4.3.6

<details> <summary>Analysisd crashes on start with custom configuration - Replicate error :green_circle: </summary>

1. Install manager
```
# yum install -y https://packages.wazuh.com/4.x/yum/wazuh-manager-4.3.6-1.x86_64.rpm
Installed:
  wazuh-manager-4.3.6-1.x86_64                                                  

Complete!
```
3. Copy configuration, decoders and list files that cause segfault
```
# curl -OL https://github.com/wazuh/wazuh-saas/files/9798354/cf9eb9gh6m7t_config_20221017T0821_tqXPc68hvkMuwXGC.tar.gz
# tar -xvzf cf9eb9gh6m7t_config_20221017T0821_tqXPc68hvkMuwXGC.tar.gz
# cd var/ossec/etc/
# cp -f ossec.conf /var/ossec/etc/ossec.conf
# cp -rf decoders/* /var/ossec/etc/decoders/
# cp -rf rules/* /var/ossec/etc/rules/
# cp -rf lists/* /var/ossec/etc/lists/
# cd /var/ossec/etc/
# chown -R wazuh:wazuh decoders/
# chown -R wazuh:wazuh rules/
# chown -R wazuh:wazuh lists/

```
4. Rename rules file that causes crash
```
# mv /var/ossec/etc/rules/MSSQL_Maggie.xml.disable /var/ossec/etc/rules/MSSQL_Maggie.xml
```
5. Start manager
```
# /var/ossec/bin/wazuh-control start
2022/11/08 13:24:30 wazuh-analysisd: WARNING: (7606): Signature ID '255042' was not found. Invalid 'if_sid'. Rule '10078' will be ignored.
2022/11/08 13:24:30 wazuh-analysisd: WARNING: (7606): Signature ID '510000' was not found. Invalid 'if_sid'. Rule '10079' will be ignored.
2022/11/08 13:24:30 wazuh-analysisd: WARNING: (7616): List 'etc/lists/kernel-control-commands' could not be loaded. Rule '221010' will be ignored.
/var/ossec/bin/wazuh-control: line 239:  4032 Segmentation fault      ${DIR}/bin/${i} -t ${DEBUG_CLI}
wazuh-analysisd: Configuration error. Exiting
```
</details>


### Tasks on Fixed Branch

<details> <summary>Clean Install - Analysisd does not crash on start with custom configuration :green_circle:</summary>

1. Install manager
```
# yum install -y https://packages-dev.wazuh.com/warehouse/test/4.3/rpm/var/wazuh-manager-4.3.10-3557.analysisd.crash.fix.x86_64.rpm
Installed:
  wazuh-manager-4.3.10-3557.analysisd.crash.fix.x86_64                                                  

Complete!
```
2. Copy configuration, decoders and list files that cause segfault
```
# curl -OL https://github.com/wazuh/wazuh-saas/files/9798354/cf9eb9gh6m7t_config_20221017T0821_tqXPc68hvkMuwXGC.tar.gz
# tar -xvzf cf9eb9gh6m7t_config_20221017T0821_tqXPc68hvkMuwXGC.tar.gz
# cd var/ossec/etc/
# cp -f ossec.conf /var/ossec/etc/ossec.conf
# cp -rf decoders/* /var/ossec/etc/decoders/
# cp -rf rules/* /var/ossec/etc/rules/
# cp -rf lists/* /var/ossec/etc/lists/
# cd /var/ossec/etc/
# chown -R wazuh:wazuh decoders/
# chown -R wazuh:wazuh rules/
# chown -R wazuh:wazuh lists/
```
3. Rename rules file that causes crash
```
# mv /var/ossec/etc/rules/MSSQL_Maggie.xml.disable /var/ossec/etc/rules/MSSQL_Maggie.xml
```
4. Start manager
```
# /var/ossec/bin/wazuh-control start
2022/11/08 13:48:11 wazuh-analysisd: WARNING: (7617): Signature ID '255042' was not found and will be ignored in the 'if_sid' option of rule '10078'.
2022/11/08 13:48:11 wazuh-analysisd: WARNING: (7617): Signature ID '255008' was not found and will be ignored in the 'if_sid' option of rule '10078'.
2022/11/08 13:48:11 wazuh-analysisd: WARNING: (7617): Signature ID '510000' was not found and will be ignored in the 'if_sid' option of rule '10079'.
2022/11/08 13:48:11 wazuh-analysisd: WARNING: (7617): Signature ID '510002' was not found and will be ignored in the 'if_sid' option of rule '10079'.
2022/11/08 13:48:11 wazuh-analysisd: WARNING: (7617): Signature ID '111037' was not found and will be ignored in the 'if_sid' option of rule '10079'.
2022/11/08 13:48:11 wazuh-analysisd: WARNING: (7617): Signature ID '510001' was not found and will be ignored in the 'if_sid' option of rule '10079'.
2022/11/08 13:48:11 wazuh-analysisd: WARNING: (7617): Signature ID '510003' was not found and will be ignored in the 'if_sid' option of rule '10079'.
2022/11/08 13:48:11 wazuh-analysisd: WARNING: (7619): Empty 'if_sid' value. Rule '10079' will be ignored.
2022/11/08 13:48:11 wazuh-analysisd: WARNING: (7616): List 'etc/lists/kernel-control-commands' could not be loaded. Rule '221010' will be ignored.
2022/11/08 13:48:11 wazuh-modulesd: WARNING: The <ignore_time> tag at module 'vulnerability-detector' is deprecated for version newer than 4.3.
Starting Wazuh v4.3.10...
Started wazuh-apid...
Started wazuh-csyslogd...
Started wazuh-dbd...
Started wazuh-integratord...
Started wazuh-agentlessd...
Started wazuh-authd...
Started wazuh-db...
Started wazuh-execd...
Started wazuh-analysisd...
2022/11/08 13:48:17 wazuh-syscheckd: INFO: (6678): No directory provided for syscheck to monitor.
2022/11/08 13:48:17 wazuh-syscheckd: INFO: (6001): File integrity monitoring disabled.
Started wazuh-syscheckd...
Started wazuh-remoted...
Started wazuh-logcollector...
Started wazuh-monitord...
2022/11/08 13:48:19 wazuh-modulesd: WARNING: The <ignore_time> tag at module 'vulnerability-detector' is deprecated for version newer than 4.3.
Started wazuh-modulesd...
Started wazuh-clusterd...
Completed.
```
</details>

<details> <summary>Upgrade Install - Analysisd does not crash on start with custom configuration :green_circle: </summary>

1. Install 4.3.6 manager 
```
# yum install -y https://packages.wazuh.com/4.x/yum/wazuh-manager-4.3.6-1.x86_64.rpm
Installed:
  wazuh-manager-4.3.10-3557.analysisd.crash.fix.x86_64                                                  

Complete!
```
2. Copy configuration, decoders and list files that cause segfault
```
# curl -OL https://github.com/wazuh/wazuh-saas/files/9798354/cf9eb9gh6m7t_config_20221017T0821_tqXPc68hvkMuwXGC.tar.gz
# tar -xvzf cf9eb9gh6m7t_config_20221017T0821_tqXPc68hvkMuwXGC.tar.gz
# cd var/ossec/etc/
# cp -f ossec.conf /var/ossec/etc/ossec.conf
# cp -rf decoders/* /var/ossec/etc/decoders/
# cp -rf rules/* /var/ossec/etc/rules/
# cp -rf lists/* /var/ossec/etc/lists/
# cd /var/ossec/etc/
# chown -R wazuh:wazuh decoders/
# chown -R wazuh:wazuh rules/
# chown -R wazuh:wazuh lists/
```
3. Rename rules file that causes crash
```
# mv /var/ossec/etc/rules/MSSQL_Maggie.xml.disable /var/ossec/etc/rules/MSSQL_Maggie.xml
```
4. Start manager
```
# /var/ossec/bin/wazuh-control start
2022/11/08 13:24:30 wazuh-analysisd: WARNING: (7606): Signature ID '255042' was not found. Invalid 'if_sid'. Rule '10078' will be ignored.
2022/11/08 13:24:30 wazuh-analysisd: WARNING: (7606): Signature ID '510000' was not found. Invalid 'if_sid'. Rule '10079' will be ignored.
2022/11/08 13:24:30 wazuh-analysisd: WARNING: (7616): List 'etc/lists/kernel-control-commands' could not be loaded. Rule '221010' will be ignored.
/var/ossec/bin/wazuh-control: line 239:  4032 Segmentation fault      ${DIR}/bin/${i} -t ${DEBUG_CLI}
wazuh-analysisd: Configuration error. Exiting
```
5. Install fixed manager
```
yum install -y https://packages-dev.wazuh.com/warehouse/test/4.3/rpm/var/wazuh-manager-4.3.10-3557.analysisd.crash.fix.x86_64.rpm
```
6. Start manager
```
# /var/ossec/bin/wazuh-control start
2022/11/08 13:30:15 wazuh-analysisd: WARNING: (7617): Signature ID '255042' was not found and will be ignored in the 'if_sid' option of rule '10078'.
2022/11/08 13:30:15 wazuh-analysisd: WARNING: (7617): Signature ID '255008' was not found and will be ignored in the 'if_sid' option of rule '10078'.
2022/11/08 13:30:15 wazuh-analysisd: WARNING: (7617): Signature ID '510000' was not found and will be ignored in the 'if_sid' option of rule '10079'.
2022/11/08 13:30:15 wazuh-analysisd: WARNING: (7617): Signature ID '510002' was not found and will be ignored in the 'if_sid' option of rule '10079'.
2022/11/08 13:30:15 wazuh-analysisd: WARNING: (7617): Signature ID '111037' was not found and will be ignored in the 'if_sid' option of rule '10079'.
2022/11/08 13:30:15 wazuh-analysisd: WARNING: (7617): Signature ID '510001' was not found and will be ignored in the 'if_sid' option of rule '10079'.
2022/11/08 13:30:15 wazuh-analysisd: WARNING: (7617): Signature ID '510003' was not found and will be ignored in the 'if_sid' option of rule '10079'.
2022/11/08 13:30:15 wazuh-analysisd: WARNING: (7619): Empty 'if_sid' value. Rule '10079' will be ignored.
2022/11/08 13:30:15 wazuh-analysisd: WARNING: (7616): List 'etc/lists/kernel-control-commands' could not be loaded. Rule '221010' will be ignored.
2022/11/08 13:30:15 wazuh-modulesd: WARNING: The <ignore_time> tag at module 'vulnerability-detector' is deprecated for version newer than 4.3.
Starting Wazuh v4.3.10...
Started wazuh-apid...
Started wazuh-csyslogd...
Started wazuh-dbd...
Started wazuh-integratord...
Started wazuh-agentlessd...
Started wazuh-authd...
Started wazuh-db...
Started wazuh-execd...
Started wazuh-analysisd...
2022/11/08 13:30:21 wazuh-syscheckd: INFO: (6678): No directory provided for syscheck to monitor.
2022/11/08 13:30:21 wazuh-syscheckd: INFO: (6001): File integrity monitoring disabled.
Started wazuh-syscheckd...
Started wazuh-remoted...
Started wazuh-logcollector...
Started wazuh-monitord...
2022/11/08 13:30:25 wazuh-modulesd: WARNING: The <ignore_time> tag at module 'vulnerability-detector' is deprecated for version newer than 4.3.
Started wazuh-modulesd...
Started wazuh-clusterd...
Completed.
```
7. Check ossec.log
```
2022/11/08 13:30:15 wazuh-analysisd: WARNING: (7617): Signature ID '255042' was not found and will be ignored in the 'if_sid' option of rule '10078'.
2022/11/08 13:30:15 wazuh-analysisd: WARNING: (7617): Signature ID '255008' was not found and will be ignored in the 'if_sid' option of rule '10078'.
2022/11/08 13:30:15 wazuh-analysisd: WARNING: (7617): Signature ID '510000' was not found and will be ignored in the 'if_sid' option of rule '10079'.
2022/11/08 13:30:15 wazuh-analysisd: WARNING: (7617): Signature ID '510002' was not found and will be ignored in the 'if_sid' option of rule '10079'.
2022/11/08 13:30:15 wazuh-analysisd: WARNING: (7617): Signature ID '111037' was not found and will be ignored in the 'if_sid' option of rule '10079'.
2022/11/08 13:30:15 wazuh-analysisd: WARNING: (7617): Signature ID '510001' was not found and will be ignored in the 'if_sid' option of rule '10079'.
2022/11/08 13:30:15 wazuh-analysisd: WARNING: (7617): Signature ID '510003' was not found and will be ignored in the 'if_sid' option of rule '10079'.
2022/11/08 13:30:15 wazuh-analysisd: WARNING: (7619): Empty 'if_sid' value. Rule '10079' will be ignored.
2022/11/08 13:30:15 wazuh-analysisd: WARNING: (7616): List 'etc/lists/kernel-control-commands' could not be loaded. Rule '221010' will be ignored.
2022/11/08 13:30:15 wazuh-modulesd: WARNING: The <ignore_time> tag at module 'vulnerability-detector' is deprecated for version newer than 4.3.
2022/11/08 13:30:16 wazuh-testrule: WARNING: (7617): Signature ID '255042' was not found and will be ignored in the 'if_sid' option of rule '10078'.
2022/11/08 13:30:16 wazuh-testrule: WARNING: (7617): Signature ID '255008' was not found and will be ignored in the 'if_sid' option of rule '10078'.
2022/11/08 13:30:16 wazuh-testrule: WARNING: (7617): Signature ID '510000' was not found and will be ignored in the 'if_sid' option of rule '10079'.
2022/11/08 13:30:16 wazuh-testrule: WARNING: (7617): Signature ID '510002' was not found and will be ignored in the 'if_sid' option of rule '10079'.
2022/11/08 13:30:16 wazuh-testrule: WARNING: (7617): Signature ID '111037' was not found and will be ignored in the 'if_sid' option of rule '10079'.
2022/11/08 13:30:16 wazuh-testrule: WARNING: (7617): Signature ID '510001' was not found and will be ignored in the 'if_sid' option of rule '10079'.
2022/11/08 13:30:16 wazuh-testrule: WARNING: (7617): Signature ID '510003' was not found and will be ignored in the 'if_sid' option of rule '10079'.
2022/11/08 13:30:16 wazuh-testrule: WARNING: (7619): Empty 'if_sid' value. Rule '10079' will be ignored.
2022/11/08 13:30:16 wazuh-testrule: WARNING: (7616): List 'etc/lists/kernel-control-commands' could not be loaded. Rule '221010' will be ignored.
2022/11/08 13:30:17 wazuh-csyslogd: INFO: Remote syslog server not configured. Clean exit.
2022/11/08 13:30:17 wazuh-dbd: INFO: Database not configured. Clean exit.
2022/11/08 13:30:17 wazuh-integratord: INFO: Started (pid: 4434).
2022/11/08 13:30:17 wazuh-integratord: ERROR: (1103): Could not open file 'logs/alerts/alerts.json' due to [(2)-(No such file or directory)].
2022/11/08 13:30:17 wazuh-agentlessd: INFO: Not configured. Exiting.
2022/11/08 13:30:17 wazuh-authd: INFO: Started (pid: 4455).
2022/11/08 13:30:17 wazuh-authd: INFO: Accepting connections on port 1515. Random password chosen for agent authentication: e1ea0277ab0f4f003c9f80afd49c7f92
2022/11/08 13:30:17 wazuh-authd: INFO: Setting network timeout to 1.000000 sec.
2022/11/08 13:30:18 wazuh-integratord: ERROR: (1103): Could not open file 'logs/alerts/alerts.json' due to [(2)-(No such file or directory)].
2022/11/08 13:30:18 wazuh-db: INFO: Started (pid: 4474).
2022/11/08 13:30:19 wazuh-integratord: ERROR: (1103): Could not open file 'logs/alerts/alerts.json' due to [(2)-(No such file or directory)].
2022/11/08 13:30:19 wazuh-execd: INFO: Started (pid: 4504).
2022/11/08 13:30:20 wazuh-integratord: ERROR: (1103): Could not open file 'logs/alerts/alerts.json' due to [(2)-(No such file or directory)].
2022/11/08 13:30:20 wazuh-analysisd: WARNING: (7617): Signature ID '255042' was not found and will be ignored in the 'if_sid' option of rule '10078'.
2022/11/08 13:30:20 wazuh-analysisd: WARNING: (7617): Signature ID '255008' was not found and will be ignored in the 'if_sid' option of rule '10078'.
2022/11/08 13:30:20 wazuh-analysisd: WARNING: (7617): Signature ID '510000' was not found and will be ignored in the 'if_sid' option of rule '10079'.
2022/11/08 13:30:20 wazuh-analysisd: WARNING: (7617): Signature ID '510002' was not found and will be ignored in the 'if_sid' option of rule '10079'.
2022/11/08 13:30:20 wazuh-analysisd: WARNING: (7617): Signature ID '111037' was not found and will be ignored in the 'if_sid' option of rule '10079'.
2022/11/08 13:30:20 wazuh-analysisd: WARNING: (7617): Signature ID '510001' was not found and will be ignored in the 'if_sid' option of rule '10079'.
2022/11/08 13:30:20 wazuh-analysisd: WARNING: (7617): Signature ID '510003' was not found and will be ignored in the 'if_sid' option of rule '10079'.
2022/11/08 13:30:20 wazuh-analysisd: WARNING: (7619): Empty 'if_sid' value. Rule '10079' will be ignored.
2022/11/08 13:30:20 wazuh-analysisd: WARNING: (7616): List 'etc/lists/kernel-control-commands' could not be loaded. Rule '221010' will be ignored.
2022/11/08 13:30:20 wazuh-analysisd: INFO: Total rules enabled: '9173'
2022/11/08 13:30:20 wazuh-analysisd: INFO: Started (pid: 4518).
2022/11/08 13:30:20 wazuh-analysisd: INFO: (7200): Logtest started
2022/11/08 13:30:21 wazuh-integratord: ERROR: Unable to enable integration for: 'custom-abuseipdb.py'. File not found inside 'integrations'.
2022/11/08 13:30:21 wazuh-integratord: ERROR: Unable to enable integration for: 'custom-misp.py'. File not found inside 'integrations'.
2022/11/08 13:30:21 wazuh-syscheckd: INFO: (6678): No directory provided for syscheck to monitor.
2022/11/08 13:30:21 wazuh-syscheckd: INFO: (6001): File integrity monitoring disabled.
2022/11/08 13:30:21 rootcheck: INFO: Starting rootcheck scan.
2022/11/08 13:30:22 wazuh-remoted: INFO: Started (pid: 4583). Listening on port 1514/TCP (secure).
2022/11/08 13:30:22 wazuh-remoted: INFO: (1410): Reading authentication keys file.
2022/11/08 13:30:23 wazuh-logcollector: INFO: (1950): Analyzing file: '/var/ossec/logs/active-responses.log'.
2022/11/08 13:30:23 wazuh-logcollector: INFO: Started (pid: 4614).
2022/11/08 13:30:24 wazuh-monitord: INFO: Started (pid: 4634).
2022/11/08 13:30:25 wazuh-modulesd: WARNING: The <ignore_time> tag at module 'vulnerability-detector' is deprecated for version newer than 4.3.
2022/11/08 13:30:25 wazuh-modulesd: INFO: Started (pid: 4659).
2022/11/08 13:30:25 wazuh-modulesd:database: INFO: Module started.
2022/11/08 13:30:25 wazuh-modulesd:download: INFO: Module started.
2022/11/08 13:30:25 wazuh-modulesd:control: INFO: Starting control thread.
2022/11/08 13:30:25 wazuh-modulesd:task-manager: INFO: (8200): Module Task Manager started.
2022/11/08 13:30:25 wazuh-modulesd:agent-upgrade: INFO: (8153): Module Agent Upgrade started.
```
8. Check status
```
# systemctl status wazuh-manager.service 
● wazuh-manager.service - Wazuh manager
   Loaded: loaded (/usr/lib/systemd/system/wazuh-manager.service; enabled; vendor preset: disabled)
   Active: active (exited) since Tue 2022-11-08 13:36:30 UTC; 2s ago
  Process: 6275 ExecStart=/usr/bin/env /var/ossec/bin/wazuh-control start (code=exited, status=0/SU>

Nov 08 13:36:28 c3 env[6275]: wazuh-execd already running...
Nov 08 13:36:28 c3 env[6275]: wazuh-analysisd already running...
Nov 08 13:36:28 c3 env[6275]: wazuh-syscheckd already running...
Nov 08 13:36:28 c3 env[6275]: wazuh-remoted already running...
Nov 08 13:36:28 c3 env[6275]: wazuh-logcollector already running...
Nov 08 13:36:28 c3 env[6275]: wazuh-monitord already running...
Nov 08 13:36:28 c3 env[6275]: wazuh-modulesd already running...
Nov 08 13:36:28 c3 env[6275]: wazuh-clusterd already running...
Nov 08 13:36:30 c3 env[6275]: Completed.
Nov 08 13:36:30 c3 systemd[1]: Started Wazuh manager.
```
</details>

**Comment by damarisg** [comment]
## QA review

- **Type**: Manual Testing
- **Status**: Approved 🟢 
- **Comments**: Everything seems to be working properly.

**Comment by jmv74211** [comment]
## Closing conclusion 👍🏼

Everything seems to be working properly.
