### ISSUE TITLE
Wazuh Ansible, Chef and Puppet 3.11.0_7.5.1

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-qa#358]
Wazuh version: 3.11.0
Elastic version: 7.5.1

### Tasks

- [x] Update Ansible tests to 3.11.0_7.5.1

- [x] Update Chef tests to 3.11.0_7.5.1

- [x] Udate PUppet tests to 3.11.0_7.5.1

**Comment by jm404** [comment]
Done in #359
