### ISSUE TITLE
QA Planning: FIM issues in %WINDIR%\System32 directory

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3615]
## Description

This aims to investigate [FIM issues in %WINDIR%\System32 directory ](https://github.com/wazuh/wazuh/issues/14796) to define the test cases to be carried out.

# Development stage

- [x] Research the applied change.
- [x] Research if we have a test for this case.
- [x] Define the test cases. Identify the base cases, and then the rest of the tests as tier 2.
- [x] Define whether it is necessary to test systems, integration, or E2E. Create the corresponding issues.

**Comment by Deblintrake09** [comment]
# Task results

### Research

The change applied pertains to monitoring the `windows/system32` folder and avoiding the automatic Windows redirection to sysWOW64 instead of system32.

Currently there is no test support for this issue. This could be tested with IT tests, by monitoring the folder and checking the expected events are generated.

In order to correctly monitor `windows/system32` folder, the folder needs to be configured to `Sysnative` as:

```xml
<directories recursion_level="0" realtime="yes">%WINDIR%/Sysnative</directories>
```
The following event will be displaying confirming the redirection:

```
2022/11/18 09:20:55 wazuh-agent[4860] syscheck-config.c:2143 at fim_adjust_path(): DEBUG: (6307): Convert '%windir%/sysnative' to '%windir%/system32' to process the FIM events.
```

### Define test cases

- [ ] Monitor `system32` folder and generate events
   - [ ] monitor in realtime
   - [ ] monitor in whodata
   - [ ] monitor in scheduled
