### ISSUE TITLE
QA Planning: Check behavior and reorganization of the ruleset

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#3620]
# Description

After the minimum viable product engine's version that has been released by the dev team, is required to research the new changes and study the possible testing cases. 

# Tasks

- [x] Research https://github.com/wazuh/wazuh/issues/15312
- [x] Propose new cases to test.
- [x] Analyze and create cases after validating them.

**Comment by roronoasins** [comment]
## 2022/11/24

Possible testing cases:

- [ ] Recursively load each item-type
  - [ ] decoder
  - [ ] rule
  - [ ] filter
  - [ ] output
  - [ ] environment
  - [ ] schema
- [ ] Retesting previous catalog's subcommand: `load` using `-r` option
