### ISSUE TITLE
QA Planning: Wildcard (*) usage on Windows Registry Paths for FIM

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#3670]
## Description

This aims to investigate [Wildcard (*) usage on Windows Registry Paths for FIM](https://github.com/wazuh/wazuh/issues/14321) to define the test cases to be carried out.

# Development stage

- [x] Research the applied change.
- [x] Research if we have a test for this case.
- [x] Define the test cases. Identify the base cases, and then the rest of the tests as tier 2.
- [ ] Define whether it is necessary to test systems, integration, or E2E. Create the corresponding issues.

**Comment by Deblintrake09** [comment]
# Task Results

### Research if we have a test for this case

Currently we have no tests supporting this case, because it is a new feature.  It adds new wildcard support to FIM to monitor registries using wildcards. 

It adds support for `*` and `?` wildcards,  and works similarly to the Wildcards used on file and directories monitoring, feature that has integration tests located in the `test_fim/test_files/test_wildcards_complex` suite.

### Define the test cases. Identify the base cases, and then the rest of the tests as tier 2.

- Base Test Case - Tier 1:
   - Scenario: One star in the path
```
Given I want to monitor everything under a root key
And I have entered ROOTKEY\*
When The configuration file has been read
Then All valid paths will be monitorable
Examples:
  | Path | Result |
  | HKEY_CURRENT_CONFIG\* | HKEY_CURRENT_CONFIG\Software,HKEY_CURRENT_CONFIG\System  |
```
- Tier 2:

   - Scenario: Two o more star in the path
```
Given I want to monitor everything under a root key and the subkeys
And I have entered ROOTKEY\*\* or ROOTKEY\*\Matcher
When The configuration file has been read
Then All valid paths will be monitorable
Examples:
  | Path | Result |
  | HKEY_CURRENT_CONFIG\*\* | HKEY_CURRENT_CONFIG\Software\Fonts,HKEY_CURRENT_CONFIG\System\CurrentControlSet  |
```

-   Scenario: A star in the beggining of the path
```
Given I want to monitor everything
And I have entered *\Software\ or *\*
When The configuration file has been read
Then An error will be raised
Examples:
  | Path | Result |
  | *\Software | Error: Undefined root key  |
```

   - Scenario: One question mark in the path
```
Given I want to monitor everything that matches with something
And I have entered ROOTKEY\SOME?\
When The configuration file has been read
Then All valid paths that matches with the question mark will be monitorable 
Examples:
  | Path | Result |
  | HKEY_CURRENT_CONFIG\Soft? | HKEY_CURRENT_CONFIG\Software  |
```

   - Scenario: Two o more question mark in the path
```
Given I want to monitor everything that matches with something
And I have entered ROOTKEY\SOME?\SOME?
When The configuration file has been read
Then All valid paths that matches with the question mark will be monitorable 
Examples:
  | Path | Result |
  | HKEY_CURRENT_CONFIG\Soft?\Goo? | NULL: No paths matches with the condition  |
```

   - Scenario: A question mark in the beggining of the path
```
Given I want to monitor everything
And I have entered HKEY?\SOMETHING\
When The configuration file has been read
Then An error will be raised
Examples:
  | Path | Result |
  | HKEY?\ | Error: Undefined root key  |
```
   - Scenario: A star and question mark in the path
```
Given I want to monitor everything
And I have entered ROOTKEY\SOMETHING?\* or ROOTKEY\*\SOMETHING?
When The configuration file has been read
Then All valid paths that matches with the question mark will be monitorable 
Examples:
  | Path | Result |
  | HKEY_CURRENT_CONFIG\Soft?\* | HKEY_CURRENT_CONFIG\Software\Fonts  |
  | HKEY_CURRENT_CONFIG\*\F? | HKEY_CURRENT_CONFIG\Software\Fonts  |
```

### Define whether it is necessary to test systems, integration, or E2E. Create the corresponding issues.

The testing will be done using Integration Tests. For the development the Issue https://github.com/wazuh/wazuh-qa/issues/3693 has been created.
