### ISSUE TITLE
Syscollector deltas alerts should still work if the agent changes of worker

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh-qa#3672]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|v4.4| wazuh/wazuh#15639|https://github.com/wazuh/wazuh/pull/15675|

## Description

Currently, syscollector has two mechanisms of synchronization with the manager: rsync and deltas. Both works together using the next flow
1. First scan is synchronized using rsync
2. Second scan is synchronized using deltas, and rsync after.
3. ...

A delta is a diff between the current scan and the last one, leading to 3 types of them: insertion, modification or delete.

- Insertion delta: contain all the information since is new and must be synchronized
- Modification delta: contains only the changed values and an entity identifier (primary key)
- Insertion delta: contains only the entity identifier (primary key)

Deltas advantages were
- Low bandwith usage
- Reduce rsync interaction because they were explicitly changed by deltas
- Allow the creation of rules, and therefore, alerts

_The problem_

In a Wazuh Cluster, agents could freely change from worker to worker depending on the load balancer policy/availability, but the fact that deltas do not always contain all the information is not allowed to create alerts on those workers that do not have a previous information to modify/delete

## Proposed checks

- [x] Regular syscollector workflow
- [x] Agent changing of worker after first scan
- [x] Agent changing of worker after first scan and agent restart with the last worker
- [x] Multi-hoping agent after first scan and agent restart with the last worker

## Steps to reproduce

1. Agent starts. First syscollector scan is sync with Worker A using rsync
2. Agent changes (on the fly) from worker A to Worker B
3. Agent executes second syscollector scan and sync the results using deltas
4. Agente sync the second scan using rsync

## Expected results

3. Worker B generate alerts  related to the second scan
4. Rsync between Worker B and the agent have only sync the left information that was not synced on the deltas sync

### Current results

3. Worker B does not generate any alerts  related to the second scan
4. Rsync between Worker B and the agent have to recreate the full information in this worker

## Configuration and considerations
- No error should be shown whether the agent change from worker or during regular workflow
- Inventory shown using API/Dashboard should be the one from the current worker
- Deltas should create and index proper alerts if a custom ruleset like this one exist on the workers

## Checks proposed by QA

- Check that the first scan is completed correctly when connected to the manager
  - All scans were completed successfully
  - The DB exists in both agent and manager
  - The deltas have the expected information (**before the change**: update and delete operations had not all the info - **after the change**: all op. have all the information) in the second scan
  - The alerts are generated correctly
- Check that the alerts are not lost when changing from Manager to worker A (stopping the Master node)
  - The alerts are generated correctly
- Check that the alerts are not lost when changing from Worker B to worker A during the second scan and restarting the agent after changing of node
  - The alerts are generated correctly
- Check that the inventory obtained via API is the same as the last scan (made by Worker B) when changing from Master to Worker A to Worker B
  - The alerts are generated correctly

> **Consideration**: Set the rules in each manager instance, and set wazuh_db in debug mode (in each manager). Turn off FIM, SCA, and all the modules that interact with wazuh-db.

**Comment by mauromalara** [comment]
## Update 23/12/2022

- Configuring environment
- Solving problems with VPN and AWS environment

**Comment by mauromalara** [comment]
## Task result

WIP.

**Comment by mauromalara** [comment]
## Fresh installation

<details><summary>Check that the first scan is completed correctly when connected to the manager</summary>

<br>


  - All scans were completed successfully
  - The DB exists in both agent and manager
  - The deltas have the expected information (**before the change**: update and delete operations had not all the info - **after the change**: all op. have all the information) in the second scan
  - The alerts are generated correctly

</details>

<details><summary>Check that the alerts are not lost when changing from Manager to worker A (stopping the Master node)</summary>

<br>

- The alerts are generated correctly

</details>
  
- Check that the alerts are not lost when changing from worker A to worker B during the first scan
  - The alerts are generated correctly
- Check that the alerts are not lost when changing from Worker B to worker A during the second scan and restarting the agent after changing of node
  - The alerts are generated correctly
- Check that the inventory obtained via API is the same as the last scan (made by Worker B) when changing from Master to Worker A to Worker B

**Comment by damarisg** [comment]
## QA review

- **Type**: Manual Testing
- **Status**: Approved 🟢 
- **Comments**: Everything seems to be working properly.

**Comment by mauromalara** [comment]
## Update

- Worked on reproducing the bug but I could not achieve this because I could not detect the alert being lost

**Comment by jnasselle** [comment]
# Update
Updating @mauromalara reproducing the bug
## Reproduce the bug :green_circle:
<details>

<br>

1. Follow the steps to prepare the environment
1.1. Deploy an agent + wazuh cluster (1 master + 2 worker) with 4.4 branch https://ci.wazuh.info/job/Wazuh_QA_environment/115/
1.2. On cluster env: enable wazuh_modulesd logs; disable rootcheck,syscheck,syscollector,sca (to avoid wazuh-db log flood); enable archives.json; add the next custom rules https://github.com/wazuh/wazuh-qa/blob/4.4/tests/integration/test_analysisd/test_syscollector/data/syscollector_rules.xml
1.3. On agent: add worker1 and worker2 as servers
3. Follow the Agent's log file
4. Wait for the agent to start and end first and second syscollector scan (rsync , deltas + rsync)
5. Check that deltas received by worker1 have their own alerts
8. Wait for the agent to start syscollector scan with worker 2
9. Check that deltas received on worker2 do not generate alerts with all the information
</details>

---
## Conclusions
The manual test concludes that
- Bug was reproduced using 4.4 alpha2 (since Syscollector delta support was introduced in 4.4) by @jnasselle 
- Bug was solved in the current branch and was tested by @mauromalara
