### ISSUE TITLE
Merge Elasticsearch and Kibana testing scenarios on Molecule tests

### ISSUE THREAD

**Issue by xr09** [wazuh/wazuh-qa#371]
## Description

Due to new changes in `v3.11` (removal of `.wazuh` index) and our approach of doing the  migration manually, a merge of both testing scenarios (Elastic and Kibana) is required to correctly emulate a real world environment.

## Tasks

- [x] Integrate Kibana scenario into Elasticsearch
- [x] Migrate testinfra tests
- [x] Pass Molecule tests locally
- [x] Pass Molecule tests on Jenkins

**Comment by jm404** [comment]
Done in #372
