### ISSUE TITLE
Validate improved requests to wazuh-db in `process_multi_groups()` function

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#3717]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
| 4.4 | [#15665](https://github.com/wazuh/wazuh/issues/15665) |[#15742](https://github.com/wazuh/wazuh/pull/15742)|

## Description

This issue aims to validate the improvement of the requests to `wazuh-db` in multigroups. After the fix, it is expected that only one query will be made to the database, instead of one per agent as previously.

## Proposed checks

- [x] Check that requests to the database have decreased

  <details>
  <summary>Steps to reproduce</summary>
  <br>

  1. Register 23 agents (in the master node)
  2. Restart the master node to reset the statistics
  3. Create 127 groups per agent
  4. Use the [connect_to_socket.py](https://github.com/wazuh/wazuh-qa/files/10410010/connect_to_socket.txt) script to send queries to `wazuh-db`
  
  </details>

**Comment by mauromalara** [comment]
## Review data

| Testers | PR commit               | 
|--------|-------------------------|
| @mauromalara   |  []()   |
| @juliamagan | IDEM |

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
|   |  |  | []()


### Tested packages

| `wazuh-manager` | `wazuh-agent` | 
|-----------------|---------------|    
|[]()| |       

### Status

- [ ] In progress @mauromalara | @juliamagan  
- [ ] Pending Review
- [ ] QA team leader approved @damarisg 
- [ ] QA manager approved @jmv74211 
- [ ] Development team leader approved @TomasTurina 

### Conclusion :green_circle: 
The [test execution](https://github.com/wazuh/wazuh-qa/issues/3370#issuecomment-1312027249) was successful :green_circle:. In the [benchmark](https://github.com/wazuh/wazuh-qa/issues/3370#issuecomment-1373031132)  you can notice the performance improvement :green_circle:

**Comment by mauromalara** [comment]
## Task results

### Reproduce the bug

1. Create a cluster
```
/var/ossec/bin/cluster_control -l
NAME    TYPE    VERSION  ADDRESS    
node01  master  4.4.0    10.88.0.5  
worker  worker  4.4.0    10.88.0.6 
```
2. Simulate agents
```

```
3.

**Comment by mauromalara** [comment]
## Task results

### Fresh install

#### Fresh install: Cluster synchronization

<details><summary>Cluster doesn't re-synchronize multigroups files when a worker node is restarted</summary>

<br>

1. Configure a `wazuh-cluster` with a master and two workers.
```sql
/var/ossec/bin/cluster_control -l
```
2. Connect 10 `wazuh-agents` and generate multigroups.
3. Desconnect the `wazuh-agents`
4. Check the multigroups files generated in all nodes.
```log
ll /var/ossec/var/multigroups/
```
5. Restart any worker and verify it doesn't re-synchronize multigroups files.
```log
ll /var/ossec/var/multigroups/
```
</details>



<details><summary>Cluster doesn't re-synchronize multigroups files when a the master node is restarted </summary>

<br>

1. Configure a `wazuh-cluster` with a master and two workers.
```sql
/var/ossec/bin/cluster_control -l
```
2. Connect 10 `wazuh-agents` and generate multigroups.
3. Desconnect the `wazuh-agents`
4. Check the multigroups files generated in all nodes.
```log
ll /var/ossec/var/multigroups/
```
5. Restart the master node and verify the cluster doesn't re-synchronize multigroups files.
```log
ll /var/ossec/var/multigroups/
```

</details>



<details><summary>Cluster re-synchronize a multigroup files when a change is detected </summary>

<br>

1. Configure a `wazuh-cluster` with a master and two workers.
```sql
/var/ossec/bin/cluster_control -l
```
2. Connect 10 `wazuh-agents` and generate multigroups.
3. Desconnect the `wazuh-agents`
4. Check the multigroups files generated in all nodes.
```log
ll /var/ossec/var/multigroups/
```
5. Create a new file inside a group's folder.
```
echo "testing" > /var/ossec/etc/shared/g1/test.txt
```
6. Restart the master node and verify the cluster doesn't re-synchronize multigroups files.
```log
ll /var/ossec/var/multigroups/
```

</details>

**Comment by mauromalara** [comment]
## Task results

By: @juliamagan 

### Upgrade 🔵

#### Performance - Multigroups ⚫

...

#### Cluster synchronization 🔵

**Comment by damarisg** [comment]
## QA review
- **Type**: Manual Testing
- **Status**: Approved  🟢 
- **Comments**: Everything seems to work correctly.
