### ISSUE TITLE
Test Analysisd timestamp granularity support fix

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#3728]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
| 4.5.0                | https://github.com/wazuh/wazuh/issues/15730            |https://github.com/wazuh/wazuh/pull/15826                    |

## Description

This Issue aims to test the fix done Analysisd to enable decoding logs with millisecond timestamp granularity.  Logs in the following formats are currently contemplated:

> - 2007-06-14T15:48:55-04:00
> - 2009-05-22T09:36:46.214994-07:00

When a timestamp has 3 digits after the seconds . delimiter, the decoded timestamp is showing characters that do not belong to the timestamp itself

With the following log:
```
2022-12-20T15:02:53.123+00:00 localhost sshd[25474]: Accepted password for rromero from 192.168.1.133 port 49765 ssh2' 
```

The timestamp shows an invalid `l` character at the end, that comes from localhost in the log:
```
2023-01-20 16:08:54,007 wazuh-logtest[INFO] 	timestamp: '2022-12-20T15:02:53.123+00:00 l'
```

## Proposed checks

- [x] Test a log with milliseconds granularity is decoded properly.

## Steps to reproduce

- Start logtest in debug mode
- Insert log with milliseconds granularity to logtest

   ```
   2022-12-20T15:02:53.123+00:00 localhost sshd[25474]: Accepted password for rromero from 192.168.1.133 port 49765 ssh2' 
   ```

- Check results

## Expected results
Log is decoded properly and all phases are completed. The decoded timestamp is not showing extra characters.

**Comment by Deblintrake09** [comment]
## Review data

| Tester | PR commit               | 
|--------|-------------------------|
| @Deblintrake09   | https://github.com/wazuh/wazuh/pull/15826/commits/98d8cfe2fce8f41b6178fa4993497d07fe27408a | 

### Testing environment

| OS | OS version |  Deployment | Image/AMI | Notes
|-- |-- |-- |--|--|
| Centos | 8 | `Local \| Vagrant` | QACTL/centos_8 |


### Tested packages
|Component| Version|
|---|---|
|Manager | [4.4.0](https://packages-dev.wazuh.com/pre-release/yum/wazuh-manager-4.4.0-1.x86_64.rpm) - [Dev Branch](https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/rpm/var/wazuh-manager-4.4.0-0.commit98d8cfe.x86_64.rpm) |

## Conclusion  

### Status

- [x] In progress
- [ ] Pending Review
- [ ] QA team leader approved @damarisg 
- [ ] QA manager approved @jmv74211 
- [ ] Development team leader approved @chemamartinez

**Comment by Deblintrake09** [comment]
## Task Results

### Testing in 4.3.10 - Replicate error
<details> <summary>Analysisd properly decodes log with 3 digits after `.` delimiter </summary>

- Install manager
- Start Wazuh-logtest in debug mode
```
# /var/ossec/bin/wazuh-logtest -d
2023-01-20 16:22:35,995 wazuh-logtest[INFO] Starting wazuh-logtest v4.3.10
2023-01-20 16:22:35,995 wazuh-logtest[INFO] Type one log per line
```
- Insert logs and check results
```
2022-12-20T15:02:53.288+00:00 INFO program[123]: this is a test

**Phase 1: Completed pre-decoding.
	full event: '2022-12-20T15:02:53.288+00:00 INFO program[123]: this is a test'
	timestamp: '2022-12-20T15:02:53.288+00:00 I'
	program_name: 'program'

**Phase 2: Completed decoding.
	No decoder matched.
```
- Try log that matches a decoder 
```
2022-12-20T15:02:53.288+00:00 INFO sshd[123]: Bad protocol version identification


2023-01-20 16:22:38,086 wazuh-logtest[INFO] 
2023-01-20 16:22:38,086 wazuh-logtest[DEBUG] Request: {"version": 1, "origin": {"name": "wazuh-logtest", "module": "wazuh-logtest"}, "command": "log_processing", "parameters": {"location": "stdin", "log_format": "syslog", "event": "2022-12-20T15:02:53.288+00:00 INFO sshd[123]: Bad protocol version identification"}}

2023-01-20 16:22:38,483 wazuh-logtest[INFO] **Phase 1: Completed pre-decoding.
2023-01-20 16:22:38,483 wazuh-logtest[INFO] 	full event: '2022-12-20T15:02:53.288+00:00 INFO sshd[123]: Bad protocol version identification'
2023-01-20 16:22:38,483 wazuh-logtest[INFO] 	timestamp: '2022-12-20T15:02:53.288+00:00 I'
2023-01-20 16:22:38,483 wazuh-logtest[INFO] 	program_name: 'sshd'
2023-01-20 16:22:38,483 wazuh-logtest[INFO] 
2023-01-20 16:22:38,483 wazuh-logtest[INFO] **Phase 2: Completed decoding.
2023-01-20 16:22:38,484 wazuh-logtest[INFO] 	name: 'sshd'
2023-01-20 16:22:38,484 wazuh-logtest[INFO] 	parent: 'sshd'
2023-01-20 16:22:38,484 wazuh-logtest[INFO] 
2023-01-20 16:22:38,484 wazuh-logtest[INFO] **Phase 3: Completed filtering (rules).
2023-01-20 16:22:38,484 wazuh-logtest[INFO] 	id: '5701'
2023-01-20 16:22:38,484 wazuh-logtest[INFO] 	level: '8'
2023-01-20 16:22:38,484 wazuh-logtest[INFO] 	description: 'sshd: Possible attack on the ssh server (or version gathering).'
2023-01-20 16:22:38,484 wazuh-logtest[INFO] 	groups: '['syslog', 'sshd', 'recon']'
2023-01-20 16:22:38,485 wazuh-logtest[INFO] 	firedtimes: '1'
2023-01-20 16:22:38,485 wazuh-logtest[INFO] 	gdpr: '['IV_35.7.d']'
2023-01-20 16:22:38,485 wazuh-logtest[INFO] 	gpg13: '['4.12']'
2023-01-20 16:22:38,485 wazuh-logtest[INFO] 	mail: 'False'
2023-01-20 16:22:38,485 wazuh-logtest[INFO] 	mitre.id: '['T1190']'
2023-01-20 16:22:38,485 wazuh-logtest[INFO] 	mitre.tactic: '['Initial Access']'
2023-01-20 16:22:38,485 wazuh-logtest[INFO] 	mitre.technique: '['Exploit Public-Facing Application']'
2023-01-20 16:22:38,485 wazuh-logtest[INFO] 	nist_800_53: '['SI.4']'
2023-01-20 16:22:38,486 wazuh-logtest[INFO] 	pci_dss: '['11.4']'
2023-01-20 16:22:38,486 wazuh-logtest[INFO] 	tsc: '['CC6.1', 'CC6.8', 'CC7.2', 'CC7.3']'
2023-01-20 16:22:38,486 wazuh-logtest[INFO] **Alert to be generated.

```
</details>

**Comment by jmv74211** [comment]
## Closing conclusion 👍🏼  

Everything seems to work properly.
