### ISSUE TITLE
QA Panning - Auto causes copy - Coverity issue

### ISSUE THREAD

**Issue by BelenValdivia** [wazuh/wazuh-qa#3737]
## Description

Based on the execution delivered in https://github.com/wazuh/wazuh/issues/14657, some issues appear on this execution.
Check if syscollector still working on Windows, Linux, and macOS

Core issue: https://github.com/wazuh/wazuh/issues/14673

# Development stage

- [ ] Research the applied change.
- [ ] Research if we have a test for this case.
- [ ] Define the test cases. Identify the base cases, and then the rest of the tests as tier 2.
- [ ] Define whether it is necessary to test systems, integration, or E2E. Create the corresponding issues.

**Comment by BelenValdivia** [comment]
# Task results

<details><summary>Research the applied change.</summary>

-    This issue aims to resolve a Coverity bug

</details>

<details><summary>Research if we have a test for this case.</summary>

-    We don't have tests for this case

</details>

<details><summary>Define the test cases. Identify the base cases, and then the rest of the tests as tier 2.</summary>

- Issue created:

  <details><summary>Test cases </summary>
  
    The following test cases must be executed in macOS, Linux and Windows

  - <details><summary>Upgrade to core-branch and check  syscollector continue working </summary>

     1.  Install wazuh agent 
     2. Check the syscollector database 
     3. Check the inventory 

    </details>

  - <details><summary>Fresh install core-branch and check  syscollector continue working </summary>

     1.  Install wazuh agent 
     2. Check the syscollector database 
     3. Check the inventory 

    </details>
    
     
  </details>


</details>

<details><summary>Define whether it is necessary to test systems, integration, or E2E. Create the corresponding issues. </summary>

- Syscollector tests are being developed

</details>
