### ISSUE TITLE
vpgrp/kitchen docker image is failing when updating the system packages

### ISSUE THREAD

**Issue by rshad** [wazuh/wazuh-qa#375]
Hi all!

Today, and when I tried to build the image we use for `wazuh-puppet` tests, found in https://github.com/wazuh/wazuh-qa/blob/devel/kitchen/wazuh-puppet/dockerfile. if fails in the second step: 

```
Step 2/7 : RUN apt-get update
```

```ruby
Step 2/7 : RUN apt-get update
 ---> Running in 0a7c57b62e8b
Err:1 http://mirror.vpgrp.io/debian stretch InRelease
  Could not connect to mirror.vpgrp.io:80 (185.183.113.129). - connect (111: Connection refused)
Err:2 http://mirror.vpgrp.io/debian stretch-updates InRelease
  Unable to connect to mirror.vpgrp.io:http:
Err:3 http://mirror.vpgrp.io/debian stretch-backports InRelease
  Unable to connect to mirror.vpgrp.io:http:
Err:4 http://mirror.vpgrp.io/debian-security stretch/updates InRelease
  Unable to connect to mirror.vpgrp.io:http:
Err:5 https://mirror.vpgrp.io/debian-docker stretch InRelease
  Failed to connect to mirror.vpgrp.io port 443: Connection refused
Reading package lists...
W: Failed to fetch http://mirror.vpgrp.io/debian/dists/stretch/InRelease  Could not connect to mirror.vpgrp.io:80 (185.183.113.129). - connect (111: Connection refused)
W: Failed to fetch http://mirror.vpgrp.io/debian/dists/stretch-updates/InRelease  Unable to connect to mirror.vpgrp.io:http:
W: Failed to fetch http://mirror.vpgrp.io/debian/dists/stretch-backports/InRelease  Unable to connect to mirror.vpgrp.io:http:
W: Failed to fetch http://mirror.vpgrp.io/debian-security/dists/stretch/updates/InRelease  Unable to connect to mirror.vpgrp.io:http:
W: Failed to fetch https://mirror.vpgrp.io/debian-docker/dists/stretch/InRelease  Failed to connect to mirror.vpgrp.io port 443: Connection refused
W: Some index files failed to download. They have been ignored, or old ones used instead.
``` 

It looks like the repository https://mirror.vpgrp.io/* is down.

**Tasks**

- [x] Determine the required libraries and packages.
- [x] Choose a clean official image of Debian.
- [x] Install the corresponding libraries and packages.

Kr,

Rshad

**Comment by rshad** [comment]
Working branch: [feature-375-dockerfile-implement](https://github.com/wazuh/wazuh-qa/tree/feature-375-dockerfile-implement).

**Comment by rshad** [comment]
Hi all!

This task can be considered as done, and the following tasks were done:

#### 1. Choose a clean official image of Debian:
- We choose Ubuntu 18.04 official docker image `ubuntu:18.04` which can be found [here].(https://github.com/tianon/docker-brew-ubuntu-core/blob/14faa76f80e543f7507828430ff50b4a58466ffd/bionic/Dockerfile)

#### 2. **Determine the required libraries, packages and gems**:

- **OS related packages:**
  - build-essential 
  - apt-transport-https 
  - ca-certificates 
  - curl 
  - software-properties-common 
  - dirmngr 
  - libreadline-dev 
  - libssl-dev 
  - lsb-release 
  - puppet 
  - rbenv 
  - ruby 
  - ruby-dev 
  - rubygems 
  - sudo 
  - systemd 
  - systemd-sysv 
  - wget 
  - zlib1g-dev

- **Ruby Gems:**
  - rake  
  - bundler  
  - kitchen-ansible  
  - kitchen-docker  
  - kitchen-docker_cli  
  - kitchen-puppet  
  - kitchen-verifier-serverspec  
  - librarian-puppet  
  - test-kitchen  
  - kitchen-goss 

#### 3. Implement the corresponding Dockerfile:

The changes can be found in https://github.com/wazuh/wazuh-qa/commit/d31286637676a1935330be1f3808661c8af7a9dd.

Kr,

Rshad
