### ISSUE TITLE
Update agents DB version to 10

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-qa#3751]
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|4.4.0|https://github.com/wazuh/wazuh/issues/15897|https://github.com/wazuh/wazuh/pull/15936|

## Description

This PR aims to fix the following warning that Wazuh DB appears as of the second execution of the manager:

```
2023/01/13 16:38:19 wazuh-db: WARNING: DB(000) wdb_sql_exec returned error: 'no such column: status'
```

## Proposed checks

- [x] Run the manager multiple times. No warnings from Wazuh DB should appear.

## Steps to reproduce

Run the manager, wait a few seconds and restart it.

## Expected results

The manager should not print any warning.

**Comment by jmv74211** [comment]
In addition to perform the corresponding manual testing, we will have to automate new tests for doing the agent's DB version.

**Comment by juliamagan** [comment]
## Review data

| Tester | PR commit               |
|--------|-------------------------|
| @juliamagan   | https://github.com/wazuh/wazuh/pull/15936/commits/68ebaaaec7ed64a410b2c6782f84cf81951f3299   |

### Testing environment

| OS | OS version | Deployment                                    | Box | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
| Centos    |     8     | Vagrant |   qactl/centos_8         |


### Tested packages

| `wazuh-manager` | 
|-----------------|
|   |  

### Status

- [x] In progress
- [ ] Pending Review
- [ ] QA manager approved (@jmv74211)
- [ ] Development team leader approved (@vikman90)

## Conclusion

**Comment by juliamagan** [comment]
## Task results

<details>
<summary>Reproduce the error in 4.4.0-Beta 1 :green_circle:</summary>
<br>

1. Start the manager for the first time
2. Restart the manager systemctl restart wazuh-manager
3. Check that new wazuh-db warning were triggered for the manager id (000)
  
  ```shell
  [root@wazuh-manager vagrant]# cat /var/ossec/logs/ossec.log | grep -iE "WARNING"
  2023/01/17 09:55:26 wazuh-db: WARNING: DB(000) wdb_sql_exec returned error: 'no such column: status'
  2023/01/17 09:55:26 wazuh-db: WARNING: Creating DB backup and create clear DB for agent: '000'
  ```

4. Check database version
  
  ```shell
  [root@wazuh-manager vagrant]#  sqlite3 /var/ossec/queue/db/000.db "SELECT value FROM metadata WHERE key='db_version'"
  9
  ```
</details>

<details>
<summary>Check that the warning does not appear in the fixed version :green_circle:</summary>
<br>

1. Start the manager for the first time
2. Restart the manager systemctl restart wazuh-manager
3. Check that new wazuh-db warning were triggered for the manager id (000)
  
  ```shell
  [root@wazuh-manager vagrant]# cat /var/ossec/logs/ossec.log | grep -iE "WARNING"
  [root@wazuh-manager vagrant]#
  ```

4. Check database version
  
  ```shell
  [root@wazuh-manager vagrant]# sqlite3 /var/ossec/queue/db/000.db "SELECT value FROM metadata WHERE key='db_version'"
  10
  ```

</details>

**Comment by jmv74211** [comment]
## Closing conclusion 👍🏼  

Everything seems to be working properly 🟢
