### ISSUE TITLE
Auto-loading for the components versions in Molecule/Kitchen tests

### ISSUE THREAD

**Issue by rshad** [wazuh/wazuh-qa#378]
Hi all!

It's preffered to parameterize and auto-load the components' versions when running molecule tests for `wazuh-ansible`. This way we make the tests independent of the repository to test and in this case we refer to `wazuh-ansible`, it also makes it unnecessary to `bump version` `wazuh-qa:molecule` on each release.

`Components` refers to:
- wazuh-manager
- wazuh-agent
- ELK stack (Filebeat, Elasticsearch, and Kibana).

**Tasks**

- [x] Study the possible ways to do the requested changes.
- [x] Apply the proper changes.
- [x] Verify the changes.

Kr,

Rshad

**Comment by rshad** [comment]
Working branch: [feature-378-auto_load-ansible-vars](https://github.com/wazuh/wazuh-qa/tree/feature-378-auto_load-ansible-vars).

**Comment by rshad** [comment]
Hi all!

The changes for both Molecule and Kitchen are completed and tested. Here we describe the followed steps and the added configuration.

We added two auxiliary functions in the tests were we were still using a hard-coded version. The functions are based on loading the corresponding variables of the role we're testing, as a dictionary in the actual host.

#### Molecule (wazuh-ansible)

- `wazuh-agent` module.
```py
@pytest.fixture(scope="module")
def AgentRoleDefaults(host):
    return host.ansible(
        "include_vars",
        (
            "../../roles/wazuh/"
            "ansible-wazuh-agent/defaults/main.yml"
        ),
    )["ansible_facts"]
```

- `wazuh-manager` module
```py
@pytest.fixture(scope="module")
def ManagerRoleDefaults(host):
    return host.ansible(
        "include_vars",
        (
            "../../roles/wazuh/"
            "ansible-wazuh-manager/defaults/main.yml"
        ),
    )["ansible_facts"]
```

We also add the corresponding code to auto-load `Filebeat` version in the scenario `worker`.

```py

@pytest.fixture(scope="module")
def FilebeatRoleDefaults(host):
    return host.ansible(
        "include_vars",
        (
            "../../roles/wazuh/"
            "ansible-filebeat/defaults/main.yml"
        ),
    )["ansible_facts"]

def test_filebeat_is_installed(host, FilebeatRoleDefaults):
    """Test if the elasticsearch package is installed."""
    filebeat = host.package("filebeat")
    filebeat_version = FilebeatRoleDefaults["filebeat_version"]
    assert filebeat.is_installed
    assert filebeat.version.startswith(filebeat_version) #Changed
```


---

#### Kitchen (wazuh-puppet)

In the case of `Kitchen`, there's no original way to access Puppet user-defined variables and in this case, we refer to the manifests parameters. However Puppet provides a shell command to check the variables names using Hiera, we at Wazuh do not support Hiera until Today.

So to access Wazuh version variable we created an auxiliary function in `conftest.py` which load the file `VERSION` from `wazuh` module, installed in /tmp/kitchen/modules in the target host and then we extract the version as a string.

https://github.com/wazuh/wazuh-qa/blob/59deb73cf14bb59bdb96fdb70cf4c924960c827c/kitchen/wazuh-puppet/kitchen/test/conftest.py#L13-L21


Kr,

Rshad
