### ISSUE TITLE
Research about FIM whodata delays packages installation time

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#3810]
## Description

This aims to investigate [FIM whodata delays packages installation time](https://github.com/wazuh/wazuh/issues/13920) to define the test cases to be carried out.

# Development stage

- [x] [Research on new changes made.](https://github.com/wazuh/wazuh-qa/issues/3810#issuecomment-1433375481)
- [x] [Design of test scenarios and use cases](https://github.com/wazuh/wazuh-qa/issues/3810#issuecomment-1433515609)
- [x] [Evaluate the current state of testing](https://github.com/wazuh/wazuh-qa/issues/3810#issuecomment-1433515814)
- [x] [Identify and justify the test "tier"](https://github.com/wazuh/wazuh-qa/issues/3810#issuecomment-1433516145)
- [x] [Conclusion - Open issues in relation to the designed planning](https://github.com/wazuh/wazuh-qa/issues/3810#issuecomment-1433519596)

**Comment by Deblintrake09** [comment]
## Task results

###  (T1) - Research on new changes made.

The new development adds a new feature, to handle the data received from auditd for the `whodata` mode. A new queue four audit data blocks is added, so events are handled and the socket is not blocked.

A new option `whodata_queue_size` is added. Values 1 to 1048576 (Default 16384)

This options handles the size of the new queue, which stores the events and processes them. As the events are processed, file events will be handled according to the `max_file_per_second` and `rt_delay` options.

###  (T2) - Design of test scenarios and use cases

- Scenario 1: Queue does not overflow and drop events
   ```
   GIVEN that `whodata_queue_size` is set to 3 and  `max_file_per_second` is set to  5
   WHEN X amount of files is created
   THEN all files are processed after X/5 seconds
   ```

- 
- Scenario 2: Queue overflows and drop events from single insertion
   ```
   GIVEN that `whodata_queue_size` is set to 3 and  `max_file_per_second` is set to  5
   WHEN X amount of files is created
   THEN as files are processed at rate X/5 seconds the last set of files is missing (was dropped out of queue)
   ```

- Scenario 3: Queue overflows and drop events - 2 Insertions - Drop from first set
   ```
   GIVEN that `whodata_queue_size` is set to 3 and  `max_file_per_second` is set to  5
   WHEN X amount of files is created
   THEN as files are processed at rate X/5 seconds
   AND a second X amount of files is created before events have finished appearing
   WHEN files are processed some events from first batch are dropped before files from second batch appear.
   ```

###  (T3) - Evaluate the current state of testing

Currently there is no testing done for this feature, since it is new.

###  (T4) - Identify and justify the test "tier"

The proposed test cases are not sure to work as is, since auditd sends blocks of information that might contain different amounts of file events in them. This feature should be tested manually, before we can generate IT's

Proposed Tiers:

T0 - Manual Testing
T2 - Nightly


###  Conclusion - Open issues in relation to the designed planning

**Comment by Deblintrake09** [comment]
##  (T2) - Design of test scenarios and use cases

### Configuration test cases

<details><summary> Scenario 1: Default value</summary>
   ```
   GIVEN that `whodata_queue_size` is removed from ossec conf
   WHEN manager/agent is restarted
   THEN an INFO level message shows the configured value to be `16384`
   ```
</details>

<details><summary> Scenario 2:  Valid values - whodata_queue_size is set to limit values</summary>
   ```
   GIVEN that `whodata_queue_size` set to `1` or `1048576`
   WHEN manager/agent is restarted
   THEN an INFO level message shows the correct configured value
   ```
</details>

<details><summary> Scenario 3: Invalid values - whodata_queue_size is set to limit values</summary>
   ```
   GIVEN that `whodata_queue_size` set to `-1` or `1048577`
   WHEN manager/agent is restarted
   THEN an ERROR level message appears 
   AND syscheck is not restarted.
   ```
</details>


<details><summary> Scenario 4: Invalid values - whodata_queue_size has characters</summary>
   ```
   GIVEN that `whodata_queue_size` set to `10a`
   WHEN manager/agent is restarted
   THEN an ERROR level message appears explaining the conf error
   AND syscheck is not restarted.
   ```
</details>


### Behavior test cases

<details><summary> Scenario 1: Queue does not overflow and drop events</summary>
   ```
   GIVEN that `whodata_queue_size` is set to 3 and  `max_file_per_second` is set to  5
   WHEN X amount of files is created
   THEN all files are processed after X/5 seconds
   ```
</details>
 
<details><summary>Scenario 2: Queue overflows and drop events from single insertion</summary>
   ```
   GIVEN that `whodata_queue_size` is set to 3 and  `max_file_per_second` is set to  5
   WHEN X amount of files is created
   THEN as files are processed at rate X/5 seconds the last set of files is missing (was dropped out of queue)
   ```
</details>
<details><summary>Scenario 3: Queue overflows and drop events - 2 Insertions - Drop from first set</summary>
   ```
   GIVEN that `whodata_queue_size` is set to 3 and  `max_file_per_second` is set to  5
   WHEN X amount of files is created
   THEN as files are processed at rate X/5 seconds
   AND a second X amount of files is created before events have finished appearing
   WHEN files are processed some events from first batch are dropped before files from second batch appear.
   ```
</details>

**Comment by Deblintrake09** [comment]
##  (T3) - Evaluate the current state of testing

Currently there is no testing done for this feature, since it is new.

**Comment by Deblintrake09** [comment]
##  (T4) - Identify and justify the test "tier"

The proposed test cases are not sure to work as is, since auditd sends blocks of information that might contain different amounts of file events in them. This feature should be tested manually, before we can generate IT's

Proposed Tiers:

T0 - Manual Testing
T2 - Nightly

**Comment by Deblintrake09** [comment]
##  Conclusion - Open issues in relation to the designed planning

The following Issues have been created:

- Manual Testing: https://github.com/wazuh/wazuh-qa/issues/3962
- IT Development: https://github.com/wazuh/wazuh-qa/issues/3963
