### ISSUE TITLE
QA Planning - Unnecessary sanity check removed on wdb_syscollector_save2 function

### ISSUE THREAD

**Issue by BelenValdivia** [wazuh/wazuh-qa#3814]
## Description

This development aims to fix a segmentation fault in Wazuh db in versions less than 4.2

Core issue: https://github.com/wazuh/wazuh/pull/16008

# Development stage

- [ ] Research the applied change.
- [ ] Research if we have a test for this case.
- [ ] Define the test cases. Identify the base cases, and then the rest of the tests as tier 2.
- [ ] Define whether it is necessary to test systems, integration, or E2E. Create the corresponding issues.

**Comment by BelenValdivia** [comment]
# Task results
