### ISSUE TITLE
macOS Ventura SCA policy

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh-qa#3850]
| Target version | Related issue | Related PR |
|---|---|---|
|         4.4.x               |     https://github.com/wazuh/wazuh/issues/15566   |      https://github.com/wazuh/wazuh/pull/16027             |

## Description

Create a new SCA Policy for macOS Ventura
## Main Checks

- [x] Use the latest CIS benchmark PDF - macOS Ventura
- [x] Verify IDs numbers.
- [x] Verify texts are correct: Title, Description, Rationale, Impact, and Remediation.
- [x] Verify Compliance: CIS, CIS_CSC.
- [x] Verify conditions and rules:
  - [x] To Pass.
  - [x] To Fail.
  
### Syntax and semantic

- [x] a) ID of each policy must be contiguous.
- [x] b) The order and format set in [Documentation](https://documentation.wazuh.com/current/user-manual/capabilities/sec-config-assessment/creating-custom-policies.html) must be respected.
- [x] c) YML must be valid to avoid errors.

### Content

- [x] a) Compare each check with its analog from CIS Benchmark.
- [x] b) Try maintaining each rule as similar as possible with the `Audit` section from the CIS check.
- [x] c) Check that the commands provide the expected output.
- [x] d) When a failure is discovered, check similar policies to avoid repetition of the issue.

### Unit testing

- [x] a) Output from `ossec.log` after the SCA scan and a raw output of the result of the checks.
<details><summary>Required internal options</summary>
<p>

#### Analysisd (server or local)
analysisd.debug=2

#### Auth daemon debug (server)
authd.debug=0

#### Exec daemon debug (server, local, or Unix agent)
execd.debug=0

#### Monitor daemon debug (server, local, or Unix agent)
monitord.debug=0

#### Log collector (server, local or Unix agent)
logcollector.debug=0

#### Integrator daemon debug (server, local, or Unix agent)
integrator.debug=0

#### Unix agentd
agent.debug=2

</p>
</details>

### Deployment

- [x] a) If the policy it's new, it must be added to the `sca.files` templates.
- [x] b) If the OS has many supported SCA policies, a policy must be set as the default policy. ([as example](https://github.com/wazuh/wazuh/blob/master/etc/templates/config/centos/sca.files))

### Documentation

- [x] a) Ensure documentation SCA list includes the created or updated SCA.

# Related QA Issues

- [x] https://github.com/wazuh/wazuh-qa/issues/3851
- [x] https://github.com/wazuh/wazuh-qa/issues/3852
- [x] https://github.com/wazuh/wazuh-qa/issues/3853
- [x] https://github.com/wazuh/wazuh-qa/issues/3854

**Comment by ChristopherSchultz** [comment]
How can I help with this effort?

I have macos Ventura 13.2.1 and I'm actively trying to get the currently-running SCA checks "CIS Apple macOS 10.15 Benchmark applied to macOS 11.x" (which of course are somewhat inappropriate or done differently for other macos versions) to be reliable.

If there is anything I can do to help validate the work so far or to develop new/updated conditions, I'd be happy to do so.

**Comment by 72nomada** [comment]
Yeah, Thanks so much, We will be running the QA process in a while (coming weeks), and we may ask you to help us to verify after our work is done. Will ping you if you are ok with that.

**Comment by Rebits** [comment]
## Testing review :red_circle:


<details>

<summary> The policy is correctly provisioned :red_circle: </summary>


macOS Ventura agents include monterey policy instead of the expected one.

```
sh-3.2# ls /Library/Ossec/ruleset/
sca
sh-3.2# ls /Library/Ossec/ruleset/sca/
cis_apple_macOS_12.0.yml
sh-3.2# sw_vers
ProductName:		macOS
ProductVersion:		13.3.1
BuildVersion:		22E261
```

</details>


<details>

<summary> Compliance :large_blue_circle: </summary>

</details>


<details>

<summary> No ID duplication :large_blue_circle: </summary>

</details>

**Comment by 72nomada** [comment]
https://github.com/wazuh/wazuh-qa/issues/3850#issuecomment-1520238004


- The policy is correctly provisioned - Solved
- Compliance - Solved

Commit - https://github.com/wazuh/wazuh/pull/16027/commits/1155f0bf242566ceceb7e705ac927c713cc63695

**Comment by Rebits** [comment]
## Testing review :green_circle:



| Tester  | PR commit Wazuh                                                                            |   PR Commit Wazuh-Packages  | 
| ------- | ------------------------------------------------------------------------------------------ | --- |
| @Rebits | https://github.com/wazuh/wazuh/pull/16027/commits/bb3b9bc31375ec376beeac521277bee433c15c0b |   https://github.com/wazuh/wazuh-packages/pull/2148/commits/94e590ca42c1abc625199a4c29645864f1a03689  |



***



<details>

<summary> The policy is correctly provisioned :green_circle: </summary>


<blockquote>


<details>

<summary> Agent Installation :green_circle: </summary>

```
sh-3.2# launchctl setenv WAZUH_MANAGER "10.0.0.2" && installer -pkg wazuh-agent-4.4.2-0.commit1155f0b.pkg -target /
installer: Package name is Wazuh Agent
installer: Installing at base path /
installer: The install was successful.
```

</details>


<details>

<summary> macOS 13 policy is provided in the installation :green_circle: </summary>

```
sh-3.2# ls /Library/Ossec/ruleset/sca/
cis_apple_macOS_13.x.yml
```

</details>



</blockquote>


</details>



<details>

<summary> No errors appears in the agent's logs :green_circle: </summary>

No errors or warnings appears in the environment

</details>


<details>

<summary> macOS policy work as expected :green_circle: </summary>

Policy is correctly used in the environment. In addition, there is no invalid checks for the environment.

```
** Alert 1682418090.352186: - sca,gdpr_IV_35.7.d,pci_dss_2.2,nist_800_53_CM.1,tsc_CC7.1,tsc_CC7.2,
2023 Apr 25 06:21:30 (MacBook-Air-de-Mariajo.local) any->sca
Rule: 19003 (level 5) -> 'SCA summary: SCA policy for Apple macOS 13.x Ventura based on CIS benchmark for Apple macOS 13.x Ventura. 11-14-2022: Score less than 80% (62)'
{"type":"summary","scan_id":560223079,"name":"SCA policy for Apple macOS 13.x Ventura based on CIS benchmark for Apple macOS 13.x Ventura. 11-14-2022","policy_id":"cis_macOS_13","file":"cis_apple_macOS_13.x.yml","description":"This document provides prescriptive guidance for establishing a secure configuration posture for Apple macOS 13.x. This guide was tested against Apple macOS 13.x.","references":"https://www.cisecurity.org/cis-benchmarks/","passed":38,"failed":23,"invalid":0,"total_checks":61,"score":62.295078277587891,"start_time":1682418066,"end_time":1682418077,"hash":"feac32e9e7c893e2b7eeea2e96e9c7ccdb35329fd8cd3ca11ad4aada17643dac","hash_file":"b0ad3b04ec26a47ba9ba9104bfdc0b2796a2ffd73503baf1e6932b32aae24f2b","force_alert":"1"}
sca.type: summary
sca.scan_id: 560223079
sca.policy: SCA policy for Apple macOS 13.x Ventura based on CIS benchmark for Apple macOS 13.x Ventura. 11-14-2022
sca.description: This document provides prescriptive guidance for establishing a secure configuration posture for Apple macOS 13.x. This guide was tested against Apple macOS 13.x.
sca.policy_id: cis_macOS_13
sca.passed: 38
sca.failed: 23
sca.invalid: 0
sca.total_checks: 61
sca.score: 62
sca.file: cis_apple_macOS_13.x.yml
```


</details>


<details>

<summary> Compliance :green_circle: </summary>


- [ComplianceReport](https://github.com/wazuh/wazuh-qa/files/11321538/compliance_results.txt)

</details>

**Comment by Rebits** [comment]
### Conclusion :yellow_circle: 

After the testing review process, we found that the development met the desired requirements. The following is a list of changes produced by the testing review:

- Fixed macOS Ventura agents provided incorrect policy bug
- Fixed wrong iso compliance value

In addition, It has been detected wrong compliance mapping numbers for Ubuntu22 and RHEL9:
Opened issues:
-  https://github.com/wazuh/wazuh/issues/16858
- https://github.com/wazuh/wazuh/issues/16859

**Comment by juliamagan** [comment]
## Closing conclusion 👍🏼

Everything seems to be working properly for the macOS policy. In addition, It has been detected wrong compliance mapping numbers for Ubuntu22 and RHEL9:
Opened issues:
- https://github.com/wazuh/wazuh/issues/16858
- https://github.com/wazuh/wazuh/issues/16859
