### ISSUE TITLE
QA Planning - Update groups deletion 

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#3872]
## Description

This problem aims to investigate [Fix wazuh-db race condition](https://github.com/wazuh/wazuh/issues/16045) to define the test cases to be carried out.

# Development stage

- [x] [(T1)](https://github.com/wazuh/wazuh-qa/issues/3872#issuecomment-1420672888) - Research the applied change.
- [x] [(T2)](https://github.com/wazuh/wazuh-qa/issues/3872#issuecomment-1421017310) - Research if we have a test for this case.
- [x] [(T3)](https://github.com/wazuh/wazuh-qa/issues/3872#issuecomment-1421212225) - Define the new test cases if needed.

**Comment by QU3B1M** [comment]
# Task 1 - Research the applied change.

This changes affects the deletion of groups and recalculation of `group_hash`.

**Before** this modification, when a group was deleted it was the framework that was responsible for unassigning the agents from the group and deleting the group folder.
**Now** is the `wazuh_db` who is in charge of the deletion in cascade of each group relationship in the `global.db`, and then recalculate the `group_hash` of each affected agent and update it on the `agent` table

**Comment by QU3B1M** [comment]
# Task 2 - Research if we have a test for this case

We have system tests that apply for this case

<details><summary><code>test_agent_groups.py</code></summary>

**Given** a master node
**And** two worker nodes
**And** one Active agent with a group assigned with agent-groups
**When** group is removed
**Then** the `wazuh_db` in the master and workers is updated with the correct information
</details>

This test should pass, also it is needed to do some manual testing and/or develop new tests with a much bigger amount of agents and groups

**Comment by QU3B1M** [comment]
# Task 3 - Define the new test cases if needed

> The changes from the issue [#16103](https://github.com/wazuh/wazuh/issues/16103) are needed for the cases where the `API` or `CLI` is used.

<details><summary><strong>Case 1 - Remove a group using the API</strong></summary> 

1. **Given** a `cluster` with 2 `worker` nodes 
2. **And** 50k `wazuh-agents` connected assigned to 4 groups
3. **When** remove one group using _API_.
    ```shell
    curl -k -X DELETE "https://localhost:55000/groups?groups_list=<GROUP_NAME>&pretty=true" -H  "Authorization: Bearer $TOKEN"
    ```
4. **Then** all group data is deleted from `global.db`
    ```sql
    sqlite3 /var/ossec/queue/db/global.db 
    
    select * from `group`;
    select * from `agent`;
    select * from `belongs`;
    ```
    ```shell
    ls /var/ossec/etc/shared/
    ```
</details>
<details><summary><strong>Case 2 - Remove a group by deleting its folder</strong></summary> 

1. **Given** a `cluster` with 2 `worker` nodes 
2. **And** 50k `wazuh-agents` connected assigned to 4 groups
3. **When** delete the _folder_ of a group.
    ```shell
    rm -rf /var/ossec/etc/shared/<GROUP_NAME>
    ```
4. **Then** all group data is deleted from `global.db`
    ```sql
    sqlite3 /var/ossec/queue/db/global.db 
    
    select * from `group`;
    select * from `agent`;
    select * from `belongs`;
    ```
    ```bash
    ls /var/ossec/etc/shared/
    ```
</details>
<details><summary><strong>Case 3 - Remove a group using the CLI</strong></summary>

1. **Given** a `cluster` with 2 `worker` nodes 
2. **And** 50k `wazuh-agents` connected assigned to 4 groups
3. **When** remove one group using _CLI_.
    ```shell
    /var/ossec/bin/agent_groups -r -g <GROUP_NAME>
    ```
4. **Then** all group data is deleted from `global.db`
    ```sql
    sqlite3 /var/ossec/queue/db/global.db 
    
    select * from `group`;
    select * from `agent`;
    select * from `belongs`;
    ```
    ```shell
    ls /var/ossec/etc/shared/
    ```
</details>
<details><summary><strong>Case 4 - Remove all groups using the API</strong></summary> 

1. **Given** a `cluster` with 2 `worker` nodes 
2. **And** 50k `wazuh-agents` connected assigned to 4 groups
3. **When** remove all groups using _API_.
    ```shell
    curl -k -X DELETE "https://localhost:55000/groups?groups_list=all&pretty=true" -H  "Authorization: Bearer $TOKEN"
    ```
4. **Then** all groupS data is deleted from `global.db`
    ```sql
    sqlite3 /var/ossec/queue/db/global.db 
    
    select * from `group`;
    select * from `agent`;
    select * from `belongs`;
    ```
    ```shell
    ls /var/ossec/etc/shared/
    ```
</details>
<details><summary><strong>Case 5 - Remove all groups by deleting their folder</strong></summary> 

1. **Given** a `cluster` with 2 `worker` nodes 
2. **And** 50k `wazuh-agents` connected assigned to 4 groups
3. **When** delete all group's _folder_ .
    ```shell
    rm -rf /var/ossec/etc/shared/!(default)
    ```
4. **Then** all group data is deleted from `global.db`
    ```sql
    sqlite3 /var/ossec/queue/db/global.db 
    
    select * from `group`;
    select * from `agent`;
    select * from `belongs`;
    ```
    ```bash
    ls /var/ossec/etc/shared/
    ```
</details>

<details><summary><strong>Case 6 - Remove all groups using the CLI</strong></summary>

1. **Given** a `cluster` with 2 `worker` nodes 
2. **And** 50k `wazuh-agents` connected assigned to 4 groups
3. **When** remove all groups using _CLI_.
    > Run the following command for each group. 
    ```shell
    /var/ossec/bin/agent_groups -r -g <GROUP_NAME>
    ```
4. **Then** all group data is deleted from `global.db`
    ```sql
    sqlite3 /var/ossec/queue/db/global.db 
    
    select * from `group`;
    select * from `agent`;
    select * from `belongs`;
    ```
    ```shell
    ls /var/ossec/etc/shared/
    ```
</details>

**Comment by QU3B1M** [comment]
# Conclusion 
After proper investigation, it is concluded that this development will need the following issues to be approved:
- #3907
- #3908

**Comment by jmv74211** [comment]
QA planning approved 👍🏼
