### ISSUE TITLE
QA Planning - Remove 'Agent-groups sync' task from cluster

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#3875]
## Description

This problem aims to investigate [Remove 'Agent-groups sync' task from cluster](https://github.com/wazuh/wazuh/pull/16050) to define the test cases to be carried out.

# Development stage

- [x] [**(T1)**](https://github.com/wazuh/wazuh-qa/issues/3875#issuecomment-1411831313): - Research the applied change.
- [x] [**(T2)**](https://github.com/wazuh/wazuh-qa/issues/3875#issuecomment-1411875881): - Research if we have a test for this case.
- [x] [**(T3)**](https://github.com/wazuh/wazuh-qa/issues/3875#issuecomment-1412263720): - Define the test cases. Identify the base cases, and then the rest of the tests as tier 2.

**Comment by juliamagan** [comment]
## Task 1: Research the applied change

**Comment by juliamagan** [comment]
## Task 2: Research if we have a test for this case

**Comment by juliamagan** [comment]
## Task 3: Define the test cases

**Comment by juliamagan** [comment]
## Conclusion

After the research done, we have concluded that the above mentioned tests need to be fixed, for this, we will work on the following issues:

- https://github.com/wazuh/wazuh-qa/issues/3865
-

**Comment by jmv74211** [comment]
Research completed. We will work on the above issues to complete the required work.
