### ISSUE TITLE
QA Planning - Centralize the guess group functionality in the master node

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#3876]
## Description

This problem aims to investigate [Centralize the guess group functionality in the master node](https://github.com/wazuh/wazuh/issues/16038) to define the test cases to be carried out.

# Development stage

- [x] [**(T1)**](https://github.com/wazuh/wazuh-qa/issues/3876#issuecomment-1413433623): - Research the applied change.
- [x] [**(T2)**](https://github.com/wazuh/wazuh-qa/issues/3876#issuecomment-1413447115): - Research if we have a test for this case.
- [x] [**(T3)**](https://github.com/wazuh/wazuh-qa/issues/3876#issuecomment-1413479096): - Define the test cases. Identify the base cases, and then the rest of the tests as tier 2.

**Comment by juliamagan** [comment]
## Task 1: Research the applied change

It is proposed to move the guessing functionality to the master node.

When a node receives a keep-alive from an agent for the first time, at the time it tries to guess the group (by default this is disabled, but there is a possibility to enable it), the idea is that now the node should redirect a request to the master node to determine which group the agent will belong to.

This can easily be done using the communication mechanism provided by wazuh-clusterd and already used by many other modules.

Now, in a cluster architecture, the master node is in charge of all group assignments:

 - If an agent connects to the master node, it assigns the group where the agent belongs (nothing changes).
 - If an agent connects to a worker node, it redirects a request to the master node and waits for a response with the group where the agent is assigned.

**Comment by juliamagan** [comment]
## Task 2: Research if we have a test for this case

We have `test_assign_groups_guess` which tests this feature. This test should pass with the new development. However it should be improved since we can check some logs.

**Comment by juliamagan** [comment]
## Task 3: Define the test cases

Test cases are already covered. We can improve the test by looking for the logs discussed in the development PR:

- Worker

```
2023/02/01 13:40:28 wazuh-remoted[1718] manager.c:556 at assign_group_to_agent_worker(): DEBUG: Sending message to master node: '{"daemon_name":"remoted","message":{"command":"assigngroup","parameters":{"agent":"060","md5":"x"}}}'
2023/02/01 13:40:28 wazuh-remoted[1718] manager.c:560 at assign_group_to_agent_worker(): DEBUG: Message received from master node: '{"error":0,"message":"ok","data":{"group":"default"}}'
2023/02/01 13:40:28 wazuh-remoted[1718] manager.c:1598 at wait_for_msgs(): DEBUG: Sending file 'default/merged.mg' to agent '060'.
2023/02/01 13:40:28 wazuh-remoted[1718] manager.c:1614 at wait_for_msgs(): DEBUG: End sending file 'default/merged.mg' to agent '060'.
```

- Master

```
2023/02/01 13:40:28 wazuh-remoted[1877] manager.c:508 at assign_group_to_agent(): DEBUG: Agent '060' with file 'merged.mg' MD5 'x'
2023/02/01 13:40:28 wazuh-remoted[1877] manager.c:527 at assign_group_to_agent(): DEBUG: Group assigned: 'default'
```

**Comment by juliamagan** [comment]
## Conclusion

After the research done, we have concluded that the above mentioned test could be improved and no manual testing will be needed. We will work on the following issue:

- https://github.com/wazuh/wazuh-qa/issues/3863

**Comment by jmv74211** [comment]
Research completed. We will work on the above issues to complete the required work.
