### ISSUE TITLE
QA Planning - Synchronize complete `agent-group` information 

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#3887]
## Description

This problem aims to investigate [Synchronize complete agent-group information](https://github.com/wazuh/wazuh/issues/16076) to define the test cases to be carried out.

# Development stage

- [x] [**(T1)**](https://github.com/wazuh/wazuh-qa/issues/3887#issuecomment-1420799663): - Research the applied change.
- [x] [**(T2)**](https://github.com/wazuh/wazuh-qa/issues/3887#issuecomment-1420816096): - Research if we have a test for this case.
- [x] [**(T3)**](https://github.com/wazuh/wazuh-qa/issues/3887#issuecomment-1420980604): - Define the test cases. Identify the base cases, and then the rest of the tests as tier 2.

**Comment by juliamagan** [comment]
## Update 06/02/2023

While testing the applied change, we can see that if we overwrite an agent so that it has no groups, after a few seconds, it is assigned the `default` group. We are checking with the development team if this is normal.

**Comment by juliamagan** [comment]
## Task 1

The worker requests the full agent-groups information. However, when clusterd on the master asks `wazuh-db` for the complete information, it only gets the information for those agents with at least 1 group.

As a consequence, the worker updates agents where both nodes have information, but does not replace empty ones in the master, so the discrepancy remains between both DBs.

The solution is that the master sends the worker the group information of all agents, regardless of whether or not they are assigned to any group.

**Comment by juliamagan** [comment]
## Task 2: Research if we have a test for this case

We have `test_sync_agent_groups_get`, but it doesn't check when an agent has no groups. We could add this test case.

In addition, `test_set_agent_groups` is being affected by this change, we need to update it.

**Comment by juliamagan** [comment]
## Conclusion

After the investigation, we can conclude that this development will require:

- https://github.com/wazuh/wazuh-qa/issues/3904 (manual testing)

- https://github.com/wazuh/wazuh-qa/issues/3902 (fix)

**Comment by jmv74211** [comment]
QA planning approved 👍🏼
