### ISSUE TITLE
Research about the order in which the global DB is populated

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#3967]
## Description

The objective of this issue is to investigate and design a testing plan for the development issue https://github.com/wazuh/wazuh/pull/16233.

### Planning stage

- [x] [Research on new changes made](https://github.com/wazuh/wazuh-qa/issues/3967#issuecomment-1434492473)
- [x] [Design of test scenarios and use cases](https://github.com/wazuh/wazuh-qa/issues/3967#issuecomment-1434523181) 
- [x] [Evaluate the current state of testing](https://github.com/wazuh/wazuh-qa/issues/3967#issuecomment-1434533520) 
- [x] [Identify and justify the test "tier"](https://github.com/wazuh/wazuh-qa/issues/3967#issuecomment-1434537247)
- [x] [Conclusion - Open issues in relation to the designed planning ](https://github.com/wazuh/wazuh-qa/issues/3967#issuecomment-1434605931)

**Comment by juliamagan** [comment]
## Research on new changes made

Before the change, the order in which the global DB was populated was incorrect:

- First, `agent-group` files were synchronized.
- Later, `group` files were synchronized.

By modifying the order of these steps, we ensure that the manager will never try to add an entry in the belongs table before synchronizing the groups in the DB.

**Comment by juliamagan** [comment]
## Design of test scenarios and use cases

- Test upgrade:

    <details>
  <summary>Case 1: Upgrade from 3.x to 4.4.0</summary>
  <br>

   **Given** one manager 
   **And** one agent without a group assigned
   **When** upgrading to 4.4.0
   **Then** no errors appear in `ossec.log`
   **and** agent is `Active`

  </details>

  <details>
  <summary>Case 2: Upgrade from 3.x to 4.4.0</summary>
  <br>

   **Given** one manager 
   **And** one agent with a group assigned
   **When** upgrading to 4.4.0
   **Then** no errors appear in `ossec.log`
   **and** agent is `Active`
   **and** group is assigned

  </details>

  <details>
  <summary>Case 3: Upgrade from 4.x to 4.4.0</summary>
  <br>

   **Given** one manager 
   **And** one agent without a group assigned
   **When** upgrading to 4.4.0
   **Then** no errors appear in `ossec.log`
   **and** agent is `Active`

  </details>

  <details>
  <summary>Case 4: Upgrade from 4.x to 4.4.0</summary>
  <br>

   **Given** one manager 
   **And** one agent with a group assigned
   **When** upgrading to 4.4.0
   **Then** no errors appear in `ossec.log`
   **and** agent is `Active`
   **and** group is assigned

  </details>

**Comment by juliamagan** [comment]
## Evaluate the current state of testing

- Case 1 is covered by https://ci.wazuh.info/job/Test_upgrade/.
- Case 2 is not covered by any test.
- Case 3 is covered by https://ci.wazuh.info/job/Test_upgrade/.
- Case 4 is not covered by any test.

**Comment by juliamagan** [comment]
## Identify and justify the test "tier"

| Test | Tier | Justification |
|:------:|:-----:|:-----------------:|
|Test upgrade| Tier | |

**Comment by juliamagan** [comment]
## Conclusion

**Comment by jmv74211** [comment]
QA planning approved 👍🏼
