### ISSUE TITLE
Research about Increase the maximum EPS for the agent bucket

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#3999]
# Description

The objective of this issue is to investigate and design a testing plan for the development issue: [Increase the maximum EPS for the agent bucket](https://github.com/wazuh/wazuh/issues/3766) 

# Planning stage
- [x] [Research on new changes made](https://github.com/wazuh/wazuh-qa/issues/3999#issuecomment-1462200152)
- [x] [Design of test scenarios and use cases](https://github.com/wazuh/wazuh-qa/issues/3999#issuecomment-1462282662) 
- [x] [Evaluate the current state of testing](https://github.com/wazuh/wazuh-qa/issues/3999#issuecomment-1462456026) 
- [x] [Identify and justify the test "tier"](https://github.com/wazuh/wazuh-qa/issues/3999#issuecomment-1462456330)
- [x] [Conclusion](https://github.com/wazuh/wazuh-qa/issues/3999#issuecomment-1462456330)

**Comment by Deblintrake09** [comment]
# Research on new changes made

This research aims to fix raise the agent's `client_buffer`  events per second behavior. For this the `limits.c` library has been adapted to be used with the agent bucket. 

Two new options have been added `events_per_second` and `limit_timeframe`. This two new options will determine how many events can be sent in a given timeframe. Events that overflow this limit, will be saved on the bucket up to a `client_buffer` amount.

With a configuration like the following:
```xml
<client_buffer>
  <!-- Agent buffer options -->
  <disabled>no</disabled>
  <queue_size>5000</queue_size>
  <events_per_second>100000</events_per_second>
  <limit_timeframe>10</limit_timeframe>
</client_buffer>
```
The behavior would be:
- Up to 100000 events would be sent out in within a `limit_timeframe` of 10 seconds. Roughly 1000 events a second.
- Events can all be sent in the first seconds, leaving the following `x` seconds without events to be able to be sent. The events that are generated in this timeframe would be saved to the client buffer.
- After each `limit_timeframe`, the events can be sent again, counting from 0 up to `events_per_second`.

**Comment by Deblintrake09** [comment]
# Design of test scenarios and use cases


<details><summary>Events per second overflow - Events saved up to queue_size</summary>

- Case Configuration
```xml
<client_buffer>
  <!-- Agent buffer options -->
  <disabled>no</disabled>
  <queue_size>5000</queue_size>
  <events_per_second>30</events_per_second>
  <limit_timeframe>10</limit_timeframe>
</client_buffer>
```

```Gherkin
Given that `client_buffer` is set to the given configuration
When When events are sent that exceed the `events_per_second` within the `limit_timeframe`
Then exceeding events are saved on `queue_size`
Then after the `limit_timeframe` has passed and events can be sent again the events in the queue are sent
And no event is lost
```
</details>

<details><summary>Events per second overflow - Client Buffer overflow - Events are lost</summary>

- Case Configuration
```xml
<client_buffer>
  <!-- Agent buffer options -->
  <disabled>no</disabled>
  <queue_size>10</queue_size>
  <events_per_second>30</events_per_second>
  <limit_timeframe>10</limit_timeframe>
</client_buffer>
```

```Gherkin
Given that `client_buffer` is set to the given configuration
When events are sent that exceed the `events_per_second` within the `limit_timeframe`
Then exceeding events are saved on `queue_size` up until the buffer is overflown
Then after the `limit_timeframe` has passed and events can be sent again the events in the queue are sent
And events are lost.
```
</details>


<details><summary>Invalid value for events_per_second - Agent fails to start</summary>

- Case Configuration
```xml
<client_buffer>
  <!-- Agent buffer options -->
  <disabled>no</disabled>
  <queue_size>5000</queue_size>
  <events_per_second>EPS_VALUES</events_per_second>
  <limit_timeframe>10</limit_timeframe>
</client_buffer>
```
EPS_Values can be:
   - [ ] Below minimum: -1
   - [ ] Above maximum: 100001
   - [ ] Containing characters: 100a
   - [ ] Non numeric: Invalid

```Gherkin
Given that `client_buffer` is set to the given configuration
When agent is restarted
Then it fails to restart and gives a descriptive message
```
</details>


<details><summary>Invalid value for queue_size - Agent fails to start</summary>

- Case Configuration
```xml
<client_buffer>
  <!-- Agent buffer options -->
  <disabled>no</disabled>
  <queue_size>QUEUE_VALUE</queue_size>
  <events_per_second>100000</events_per_second>
  <limit_timeframe>10</limit_timeframe>
</client_buffer>
```
QUEUE_VALUE can be:
   - [ ] Below minimum: -1
   - [ ] Above maximum: 100001
   - [ ] Containing characters: 100a
   - [ ] Non numeric: Invalid

```Gherkin
Given that `client_buffer` is set to the given configuration
When agent is restarted
Then it fails to restart and gives a descriptive message
```
</details>


<details><summary>Invalid value for limit_timeframe - Agent fails to start</summary>

- Case Configuration
```xml
<client_buffer>
  <!-- Agent buffer options -->
  <disabled>no</disabled>
  <queue_size>5000</queue_size>
  <events_per_second>100000</events_per_second>
  <limit_timeframe>LIMIT_VALUE</limit_timeframe>
</client_buffer>
```
LIMIT_VALUE can be:
   - [ ] Below minimum: -1
   - [ ] Above maximum:  100001
   - [ ] Containing characters: 100a
   - [ ] Non numeric: Invalid

```Gherkin
Given that `client_buffer` is set to the given configuration
When agent is restarted
Then it fails to restart and gives a descriptive message
```

**Comment by Deblintrake09** [comment]
# Evaluate the current state of testing

Currently there is not test cases related to the agent's `client_buffer` options.

**Comment by Deblintrake09** [comment]
# Define tiers

**Comment by chemamartinez** [comment]
Every test case seems good and they cover all the possible use cases!

**Comment by damarisg** [comment]
QA Planning Approved.
