### ISSUE TITLE
Research about Don't report a solved vulnerability when the package is updated and still vulnerable

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#4039]
# Description

The objective of this issue is to investigate and design a testing plan for the development issue: [Don't report a solved vulnerability when the package is updated and still vulnerable](https://github.com/wazuh/wazuh/issues/13354) 

# Planning stage
- [x] [Research on new changes made](https://github.com/wazuh/wazuh-qa/issues/4039#issuecomment-1480284952)
- [x] [Design of test scenarios and use cases](https://github.com/wazuh/wazuh-qa/issues/4039#issuecomment-1480297259) 
- [x] [Evaluate the current state of testing](https://github.com/wazuh/wazuh-qa/issues/4039#issuecomment-1480298207) 
- [x] [Identify and justify the test "tier"](https://github.com/wazuh/wazuh-qa/issues/4039#issuecomment-1480300189)
- [x] [Conclusion]()

**Comment by Deblintrake09** [comment]
## Research on new changes made

The changes made aim to fix Vulnerability Detector, when a package with a valid CVE is removed it would normally show the vulnerability as solved, even if it has been updated with a newer version of the package that is vulnerable to the same CVE, so the vulnerability has not been actually solved.

**Comment by Deblintrake09** [comment]
## Design of test scenarios and use cases

<details><summary>Tier 0 -Updating package that is still vulnerable does not show CVE as solved</summary>
```Gherkin
   Given an agent with a vulnerable package associated to a CVE
   When the package is replaced by another version that is still vulnerable to the same CVE
   Then an alert about the new version being vulnerable is fired
   And no alert about the removed version being "solved" is fired
```
</details>

**Comment by Deblintrake09** [comment]
## Evaluate the current state of testing

Currently there is not tests about this case, as this is a new scenario. This will need to be developed. Also it should be manually tested to make sure it works properly.

**Comment by Deblintrake09** [comment]
## Identify and justify the test "tier"

| Test | Tier | Justification |
|---|---|-----|
| Updating package that is still vulnerable does not show CVE as solved |1| should be run with any PR that applies changes to Vulnerability detector. |

**Comment by Deblintrake09** [comment]
## Conclusion

- For manual testing of this Issue, the Issue https://github.com/wazuh/wazuh-qa/issues/4044 has been created
- For IT development for this cases, the Issue https://github.com/wazuh/wazuh-qa/issues/4045 has been created

**Comment by damarisg** [comment]
QA Planning Approved!
