### ISSUE TITLE
Refactors and Enhancements IT framework for migration to Core repository

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#4157]
| Target version | 
|--------------------|
|           4.5         |  

## Description

Since Core and Framework teams will be handling the `tests_integration`  test suites, and will migrate it to the `wazuh/wazuh` repository to be used as part of GitHub Actions, it is necessary to make sure the migration is done as optimally contemplating:

- Clean code and well structured code
- Avoid duplicating code.
- Make the migrated code as reusable as possible.
- Avoid bad practices and improve code usability

For all of this, in this issue, we will track all proposed changes that can be applied to the framework to avoid a bad migration process. Issues on each task must be added to the list below .

## Tasks

- [ ] Fix `FileMonitor` to stop using exceptions on timeout
- [ ] Refactor Callbacks and Event monitors to be more generic
- [ ] Fix tests to avoid using the `TimeMachine` function
