### ISSUE TITLE
FIM System Tests: Provisioning and Deployment

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-qa#419]
### Objective

This issue aims to keep track of the current progress of the tasks related to the provisioning and deployment phases

### Phases

The provisioning phases are:

- Render the AWS template according to the number of Wazuh Agents, Workers, etc...
- Launch template and async wait until the Stacks is complete
- Extract the information from AWS Stack and render the required host file.
- Render the required playbook
- Launch the provisioning playbook against the hosts declared in the host file.

It's important to mention that Elasticsearch and FIlebeat will be installed from packages but Wazuh Manager and Agent will be installed either from packages or sources, with a target branch defined (can be done with `wazuh-ansible`)

### Tasks

- [x] https://github.com/wazuh/wazuh-qa/issues/424 Select required OS's and generate AMIs for them to freeze dependencies and machine status

- [x] https://github.com/wazuh/wazuh-qa/issues/428 Make the AWS template dynamic using Jinja2

- [x] https://github.com/wazuh/wazuh-qa/issues/431 Create deployment playbooks to provision: Wazuh, Filebeat, Elasticsearch

Best regards,

Jose
