### ISSUE TITLE
QA framework onboarding to Core 

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#4211]
## Description

The goal here is to be able to perform the complete migration of each TI created in the `wazuh-qa` repository to the `wazuh/wazuh` repository. For that reason, some task is required.

## To Do

- [x] Create a document with the IT coverage of the wazuh-qa repository.
- [x] The QA responsible must hold weekly meetings with a responsible Core to teach him about the assigned tests.
- [x] The QA responsible must ensure that Core migrates at least one IT to the wazuh/wazuh repository. 
- [x] The QA responsible must correct and close each priority task related to the ITs that will be migrated.

## Notes

- Each failure found needs to create an issue on the wazuh/wazuh repository to fix.

**Comment by damarisg** [comment]
## Create a document with the IT coverage of the wazuh-qa repository. 🟢 

- Document: [link](https://docs.google.com/spreadsheets/d/1OL8QL_gWimxXNDzzAEhWyMrAfWegtZbBpRzPDEK54iQ/edit#gid=1327833555)

**Comment by damarisg** [comment]
## The QA responsible must hold weekly meetings with a responsible Core to teach him about the assigned tests. 🔵 (WIP)
- This helps define and clarify doubts.

**Comment by damarisg** [comment]
## The QA responsible must ensure that Core migrates at least one IT to the wazuh/wazuh repository 🔵(WIP)

- You can check details [here](https://docs.google.com/spreadsheets/d/1OL8QL_gWimxXNDzzAEhWyMrAfWegtZbBpRzPDEK54iQ/edit#gid=1327833555).

**Comment by damarisg** [comment]
## The QA responsible must correct and close each priority task related to the ITs that will be migrated. 🔵(WIP)  

You can follow the progress of this on [Refactors and Enhancements IT framework for migration to Core repository](https://github.com/wazuh/wazuh-qa/issues/4157)

**Comment by QU3B1M** [comment]
The ITs tests migration is completely on charge of Core by now. This issue is outdated and may not be relevant now.

**Comment by damarisg** [comment]
As Kevin mentioned, it's outdated. As part of quality control, everything agreed was delivered.

The rest of the migration is in progress, but Core will continue it as responsible.


It could be closed by QA team or change project to Core. Our manager will take the decision.
