### ISSUE TITLE
FIM System tests:  Select required OS's and generate AMIs for them

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-qa#424]
It's required to generate AMIs from selected OS in order to freeze the machine in order to get a controlled environment that always generates the same alerts by default.

Some OS are deleted because there are no differences in the `syscheck` scan between them use the same code and generate the same reports. EG: Debian 9 and Ubuntu Xenail. So we are choosing the more convenient depending on the AWS images

### Supported OS's

**Agent**:

~- [ ] Redhat 7~

- [x] Redhat 8 - AMI: `ami-08fd0327843172233`

- [x] Centos 7 - AMI: `ami-003e6a885a4c48abd`

~- [ ] Centos 8~

- [x] Ubuntu 16.04 - AMI:`ami-03f1d906751fb41be`

- [x] Ubuntu 18.04 - AMI:`ami-03f1d906751fb41be`

- [x] Ubuntu 14.04 - AMI:`ami-08616032211db381e`

- [x] Amazon Linux 2 - AMI: `ami-0d2cf1d4a5e5f521d`

- [x] Windows 2019 - AMI : `ami-007237e458f14c2a2`

- [x] Windows 2016 - AMI: `ami-07eb732e1bd85e2c0`

- [x] Windows 2012 - AMI:`ami-01a34d7a4ece6a3e2`

~- [ ] Debian 9~

~- [ ] Debian 10~

**Manager:**

- [x] Amazon Linux 2 - AMI: `ami-0d2cf1d4a5e5f521d`

### Dependencies

- make
- gcc
- policycoreutils-python
- automake
- autoconf
- libtool
- epel-release
- git
- which
- sudo
- wget
- groupinstall "Development Tools"
- python36
- python36-pip
- python36-devel
- pytest
- freezegun
- jq
- jsonschema
- pyyaml
- psutil
- paramiko
- distro

### Tasks

- [x] Instantiate an AMI for every OS, remove automatic updates and install required dependencies. Then generate the AMI

Best regards,

Jose

Best

**Comment by jm404** [comment]
### Centos 7

- [ ] Deps

- [ ] Packages locked

- [ ] Firewalld disabled

`etc-osrelease`:

![image](https://user-images.githubusercontent.com/46649922/73454961-6ef1e980-436f-11ea-841a-00bdf3cdb9cb.png)

**Comment by jm404** [comment]
### RHEL8

- [x] Deps

- [x] Packages locked

- [x] Firewalld disabled

**etc-osrelease**:
```
NAME="Red Hat Enterprise Linux"
VERSION="8.1 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.1"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.1 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.1:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.1
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.1"
```

**history**:

```
	2  yum update -y
    3  yum install make gcc policycoreutils-python automake autoconf libtool epel-release git which sudo wget -y
    4  sudo yum install python3-policycoreutils
    5  yum groupinstall "Development Tools" -y
    6  yum install python36 python3-pip python36-devel -y
    7  yum install yum-plugin-versionlock -y
   	8  yum versionlock *
```

**Comment by jm404** [comment]
### RHEL8

- [x] Deps

- [x] Packages locked

- [x] Firewalld disabled

**etc-osrelease**:
```
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic


```

**history**:

```
apt update
apt upgrade
apt install make gcc policycoreutils-python-utils automake autoconf libtool git sudo wget -y
apt install build-essential
apt  install python3.6 python3-pip python3.6-dev -y
pip3 install pytest freezegun jq jsonschema pyyaml psutil paramiko distro
sudo apt-mark hold *
```

**/etc/apt/apt.conf.d/10periodic**

```
APT::Periodic::Update-Package-Lists "0";
APT::Periodic::Download-Upgradeable-Packages "0";
APT::Periodic::AutocleanInterval "0";
```

**Comment by jm404** [comment]
### UBUNTU 16.04

- [x] Deps

- [x] Packages locked

- [x] Firewalld disabled

**etc-osrelease**:
```
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial


```

**history**:

```
apt update
apt upgrade
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt update
apt install make gcc policycoreutils automake autoconf libtool -y
apt install python3
apt install python3-pip python3-dev
pip3 install pytest freezegun jq jsonschema pyyaml psutil paramiko distro
sudo apt-mark hold *
```
**updates_config**
```
root@ip-10-0-0-89:/home/ubuntu# cat /etc/apt/apt.conf.d/10periodic 
APT::Periodic::Update-Package-Lists "0";
APT::Periodic::Download-Upgradeable-Packages "0";
APT::Periodic::AutocleanInterval "0";
root@ip-10-0-0-89:/home/ubuntu# cat /etc/apt/apt.conf.d/20auto-upgrades
APT::Periodic::Update-Package-Lists "0";
APT::Periodic::Unattended-Upgrade "0";
```

**Comment by jm404** [comment]
### UBUNTU 14.04

- [x] Deps

- [x] Packages locked

- [x] Firewalld disabled

**etc-osrelease**:
```
NAME="Ubuntu"
VERSION="14.04.6 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.6 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

```

**history**:

```
apt update
apt upgrade
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt update
apt install make gcc policycoreutils automake autoconf libtool -y
apt install python3.6
ln -s /usr/bin/python3.6 /usr/bin/python3 -f
apt install python3-pip python3-dev
wget https://bootstrap.pypa.io/ez_setup.py -O - | python3
curl -sS https://bootstrap.pypa.io/get-pip.py | sudo python3
pip3 install pytest freezegun jq jsonschema pyyaml psutil paramiko distro
apt install jq #(fails on pytest)
sudo apt-mark hold '.*' # NOT executed, freezes in the middle of packages holding

```
**updates_config**
```
root@ip-10-0-0-89:/home/ubuntu# cat /etc/apt/apt.conf.d/10periodic 
APT::Periodic::Update-Package-Lists "0";
APT::Periodic::Download-Upgradeable-Packages "0";
APT::Periodic::AutocleanInterval "0";
```

**Comment by jm404** [comment]
Finished:

![image](https://user-images.githubusercontent.com/46649922/73477409-75468c80-4394-11ea-9a5e-ab8d61199a58.png)
