### ISSUE TITLE
Make the AWS template dynamic using Jinja2

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-qa#428]
We will use an AWS Template dynamically rendered according to stated number of instances. This way we can give flexibility to the deployment by simply modifying a variable.

The AWS template will be based on the one at `wazuh-cloudformation` and we will use Jinja2 to render it using Ansible

### Tasks

- [x] Create the template file and remove unrequired resources like Splunk https://github.com/wazuh/wazuh-qa/commit/bb41639ea16561adc4ae4a352e1d1f2f4918caac

- [x] Create variables that configure the template under the `/default` folder https://github.com/wazuh/wazuh-qa/commit/94e2d7a3d77f3ab01b16057cb4048a96391ee772 & https://github.com/wazuh/wazuh-qa/commit/d66f5a6e5638312f6df34024ce9eeaaa3e06e292

- [x] Remove Elastic IPs https://github.com/wazuh/wazuh-qa/commit/0041a75659301c0f6aa1f12dafd75702b94f2dca

- [x] Parametrize Elasticsearch Instances https://github.com/wazuh/wazuh-qa/commit/b06665f2ec300d7efb35705bc6dea0eb9fb2e5c0

- [x] Parametrize the Wazuh Worker and Agent Instances https://github.com/wazuh/wazuh-qa/commit/91424a4fc6b61e0cac687cda34a2e164a84b2b27

### Tests

- [x] Template YAML validation

- [x] Stack deploys succesfully

**Working on:** https://github.com/wazuh/wazuh-qa/tree/feature-428-make-aws-template-dynamic

Best regards,

Jose

**Comment by jm404** [comment]
### Deployment

The Stack has been successfully deployed. Tested with agents number set to 2:


![image](https://user-images.githubusercontent.com/46649922/73535809-c4d49900-4424-11ea-91de-9f6d5d45e59e.png)

- [ ] Check correct AMIs

- [ ] Check TAGs

- [ ] Test SSH access
