### ISSUE TITLE
Support new version `4.4.5` in QA repositories

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-qa#4289]
## Related

- https://github.com/wazuh/wazuh/issues/17772

## Description

This issue attempts to support a new version 4.4.5 for the Wazuh system.

# CRITICAL NOTICE

Each step from below must be thoroughly completed before the next one can be tackled

## Tasks

- [x] Create a 4.4.5 branch from the 4.4 branch in each repository listed below.
- [x] Bump version/revision in the 4.4.5 branch from 4.4.4 to 4.4.5 and add a changelog entry in each repository listed below. A pull request must be created to perform this action.

### Repositories

- [x] https://github.com/wazuh/wazuh-automation
- [x] https://github.com/wazuh/wazuh-qa
- [x] https://github.com/wazuh/wazuh-jenkins

**Comment by jnasselle** [comment]
- wazuh-jenkins branch bump was already handled here https://github.com/wazuh/wazuh-jenkins/pull/5296
https://github.com/wazuh/wazuh-jenkins/tree/4.4.5
- Created PR https://github.com/wazuh/wazuh-qa/pull/4288
- Created PR https://github.com/wazuh/wazuh-automation/pull/1160
