### ISSUE TITLE
FIM System Tests: Create playbooks for provisioning Wazuh, and EFK stack

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-qa#431]
### Objective

The main goal here is to adapt required tasks and playbooks to properly install and configure Wazuh, Elasticsearch, Filebeat, and Kibana in required hosts

### Tasks

- [x] Remove unused tasks related with the use cases from demo environment

- [x] Adapt tasks and templates to new CF template

- [x] Implement required variables and tasks to update the installation

### Tests

- [x] Default installation

- [x] Installation with custom number of Agents, Workers and ES nodes

**Working on:** https://github.com/wazuh/wazuh-qa/tree/feature-431-create-provisioning-playbooks
Best regards,

Jose

**Comment by jm404** [comment]
### Remove unused tasks related with the use cases from demo environment

Unrequired tasks have been deleted (`use_cases_install`, `use_cases_actions`,`use_cases_tests`) aswell as their references

Related commits:
- https://github.com/wazuh/wazuh-qa/commit/1a6a5f2c519f2c481157c9f07cffee5b42b08fd7
- https://github.com/wazuh/wazuh-qa/commit/6f65922791a8a18472a570acf6b8cb23e55785f7
- https://github.com/wazuh/wazuh-qa/commit/8ef2403e1a7b4ac24c61b4af60309be96b4c7d87

### Adapt tasks and templates to new CF template

The template has been updated to be dynamic, it now can be configured using variables to create n number of required instances:
**Related variables**:

https://github.com/wazuh/wazuh-qa/blob/1a6a5f2c519f2c481157c9f07cffee5b42b08fd7/tests/system/fim/vars/aws.yml#L8-L29



**Cloudformation template**:

https://github.com/wazuh/wazuh-qa/blob/1a6a5f2c519f2c481157c9f07cffee5b42b08fd7/tests/system/fim/roles/aws/templates/environment_template.j2

**Comment by jm404** [comment]
###  Installation with custom number of Agents, Workers and ES nodes

I scalated the deployment to:

- 3 Wazuh Managers
- 5 ES nodes
-1 Kibana
- 27 Agents (every agent x3)

**Results**

![image](https://user-images.githubusercontent.com/46649922/73739019-c4e6d880-4745-11ea-9dbd-76cc28beee81.png)

![image](https://user-images.githubusercontent.com/46649922/73739047-d16b3100-4745-11ea-8976-5519a0cfb374.png)

![image](https://user-images.githubusercontent.com/46649922/73739061-d92ad580-4745-11ea-83c5-38161e1f4618.png)

**Comment by jm404** [comment]
### Fix availability zones

The Subnets does not have a stated availability zone. As Loadbalancer can have only 1 subnet, if 2 subnets are in different availability zones, the LoadBalancer does not redirect the Kibana traffic.

In order to fix this I added the `AvailabilityZone` parameter to the subnet blocks:

**Comment by jm404** [comment]
Done in #442
