### ISSUE TITLE
Support new stage Alpha 1 for 4.5.1 in wazuh-qa repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-qa#4395]
## Description

This issue attempts to support a new stage Alpha 1 for 4.5.1 in the wazuh-qa repository.

## Tasks

- [x] Ensure changelog is updated for 4.5.1https://github.com/wazuh/wazuh-qa/pull/4398
- [x] Create tag v4.5.1-alpha1 from branch 4.5.1 on wazuh-qa repository.
- [x] Create a pre-release: https://github.com/wazuh/wazuh-qa/releases/tag/v4.5.1-alpha1

**Comment by Rebits** [comment]
LGTM
