### ISSUE TITLE
Support new stage RC 1 for 4.5.0 in wazuh-qa repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-qa#4396]
## Description

This issue attempts to support a new stage RC 1 for 4.5.0 in the wazuh-qa repository.

## Tasks

- [x] Ensure changelog is updated for 4.5.0 https://github.com/wazuh/wazuh-qa/pull/4397
- [x] Create tag v4.5.0-rc1 from branch 4.5.0 on wazuh-qa repository.
- [x] Create a pre-release: https://github.com/wazuh/wazuh-qa/releases/tag/v4.5.0-rc1

**Comment by Rebits** [comment]
LGTM
