### ISSUE TITLE
Support new stage RC 1 for 4.5.1 in wazuh-qa repository

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh-qa#4420]
## Description

This issue attempts to support a new stage RC 1 for 4.5.1 in the wazuh-qa repository.

## Tasks

- [x] Ensure changelog is updated for 4.5.1
- [x] Create tag v4.5.1-rc1 from branch 4.5.1 on wazuh-qa repository.
- [x] Create a pre-release: https://github.com/wazuh/wazuh-qa/releases/tag/v4.5.1-rc1

**Comment by Rebits** [comment]
No new changes were introduced between alpha1 and rc1
```
commit 395fd7c9e09f60b676c23f96314e31bf57ffe216 (HEAD -> 4.5.1, origin/4.5.1)
Merge: b51f4ad69 c2f9ac15b
Author: Víctor Rebollo Pérez <victorrebollop@gmail.com>
Date:   Fri Aug 11 08:42:48 2023 +0100

    Merge pull request #4416 from wazuh/merge-4.5-into-4.5.1
    
    Merge 4.5 into 4.5.1

commit c2f9ac15bc25727ddd8865078b0dd3d3f8a522a7 (origin/merge-4.5-into-4.5.1)
Merge: b51f4ad69 dc5ba5a15
Author: BelenValdivia <belen.valdivia@wazuh.com>
Date:   Thu Aug 10 17:32:33 2023 -0300

    Merge branch 4.5 into 4.5.1

commit b51f4ad6913a3f7d0922df0604660ebb0ef6ad77 (tag: v4.5.1-alpha1)
Merge: 703efb7fb e124b3687
Author: Julia Magán <80041853+juliamagan@users.noreply.github.com>
Date:   Fri Aug 4 13:45:16 2023 +0200

    Merge pull request #4398 from wazuh/enhancement/4395-update-changelog
    
    Update 4.5.1 changelog

```

It is not required to update the changelog

**Comment by Rebits** [comment]
Created tag: https://github.com/wazuh/wazuh-qa/releases/tag/v4.5.1-rc1

**Comment by damarisg** [comment]
LGTM!
