### ISSUE TITLE
Support new stage RC 2 for 4.5.1 in wazuh-qa repository

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh-qa#4431]
## Description

This issue attempts to support a new stage RC 2 for 4.5.1 in the wazuh-qa repository.

## Tasks

- [x] Bump revision
  - https://github.com/wazuh/wazuh-qa/pull/4433
  - https://github.com/wazuh/wazuh-qa/pull/4434
- [x] Ensure changelog is updated for 4.5.1 https://github.com/wazuh/wazuh-qa/pull/4432
- [x] Create tag v4.5.1-rc2 from branch 4.5.1 on wazuh-qa repository.
- [x] Create a pre-release: https://github.com/wazuh/wazuh-qa/releases/tag/v4.5.1-rc2

**Comment by Rebits** [comment]
LGTM

**Comment by juliamagan** [comment]
We are re-opening this issue because the revision bump still needs to be done.

**Comment by damarisg** [comment]
Add the correct revision to 4.5.1-rc2. [PR](https://github.com/wazuh/wazuh-qa/pull/4435).
