### ISSUE TITLE
FIM System tests: Create common actions to create, modify and delete files

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-qa#444]
### Objective

The purpose of this issue is to keep track of the progress when developing the required test scenarios and other required tasks.

### Required tasks

There are some actions that are generic and apply to every scenario like creating n files/folders or deleting them. They must be created before addressing the tests scenarios

- [x] #459 **Create Vagrantfile and required scripts to create a demo environment for the actions**

- [x] https://github.com/wazuh/wazuh-qa/issues/445 **Create n files on the specified path**

- [x] #461 **Randomly delete n files**.

- [x] #460  **Modify attributes and content of selected files**

- [x]  #465 **Clean up all hosts (Managers and Agents and ES index)**

### Folder structure and flow 

The folder structure will be similar to the following:

```
/common_tasks
	create_files.yaml (create n files in path)
	create_folders.yaml (creates folders, including nested)
	cleanup.yaml (deletes folders and files)
	check_files_json.yml
	check_files_es.yml


/scenario_realtime
	/actions
		folders.yaml (imports task from /common_tasks/create_folders.yaml with custom paths as args)
		files.yaml (same as above but with files)
		cleanup.yml (same as above but for files and folders)
	/configs
		ossec_manager.conf
		ossec_agent.conf
		agent.conf (we can configure it in the actions to push config to certain group of agents)
	/tests
		files_json.yml
		files_es.yml

	launch_scenario.yml (master playbook to launch the scenario)


/scenario_whodata
	/actions
		folders.yaml
		files.yaml
	/configs
		ossec_manager.conf
		ossec_agent.conf
		agent.conf
	/tests
		check_files_json.yml
		check_files_es.yml

	launch_tests.yml (master playbook to launch the scenario)


```

As described in the comments, every test will inherit required tasks with custom parameters to create it's own scenario, an example off the defined parameters could be:

```
- import_tasks: ../common_tasks/create_files.yml
  vars:
    paths:
        - path: /home
          n_files: 10000
          depth: 4
          max_size: 1024
        - path: /etc
          n_files: 5000
          depth: 4
          max_size: 1024
```

So our task will iterate over it creating required files in the under specified folders.

**Comment by jm404** [comment]
Done in #481
