### ISSUE TITLE
FIM System tests: Tasks to create files on specified paths

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-qa#445]
### Objective

Develop required tasks to create `n` number of files inside a custom `path` attending to `depth` and `size` criteria.

### Design

The main challenge here is to keep track of created files and have the flexibility of creating them with custom size but being fast enough with a large number of files.

Some approaches are:

- Render custom text file with Ansible module `template`
- Use `split`, `truncate` or `fallocate` binaries for Linux hosts and `fsutil` for Windows hosts
- Download files from AWS S3 bucket

**Note:** This options are not mutually exclusive and may be combined

### Files generation

The files generation function must accept the following parameters:

```json
{
    "root_folder": "/opt/testing/",
    "recursion_level": 3,
    "folder_length": 5,
    "file_length": 5,
    "file_size_specifications":[
        { "size": 10240, "amount": 10000},
        { "size": 524288, "amount": 500},
        { "size": 1048576, "amount": 1000},
        { "size": 10485760, "amount": 10},
        { "size": 1073741824, "amount": 1}
    ],
    "output_file": "created_files.txt"
}
```

Attending to these parameters, the script will generate required folders and alerts. It's important to mention that **every file's path generated will be saved in a json file** in order to parse it later with the dictionary obtained from `alerts.json`

### Tasks

- [x] Test different generation methods attending to time

- [x] Initialize the folders structure

- [x] Python script: Create folders

- [x] Python script: Create JSON of files and it's size

- [x] Python script: Generate files

- [x] Python script: Create list of generated files

### Tests

- [x] 1 folder, 1 depth, 1.000 files, 1024 bytes size

- [x] 1 folder, 1 depth, 10 files, 1024*1024 * 1024 bytes size

- [x] 1 folder, 4 depth, 1.000 files, 1024*1024 bytes size

- [x] 3 folders, 8 depth, 1.000 files, 1024*1024 bytes size

- [x] 3 folders, 8 depth, 10.000 files, 1024*1024 bytes size

- [x] 5 folders, 16 depth, 10.000 files, 1024*1024 bytes size

- [x] 20 folders, 30 depth, 100.000 files, 1024*1024 bytes size

**Comment by jm404** [comment]
### Test different generation methods attending to time, size and randomness

- **Linux**:

**Comment by jm404** [comment]
### Folder structure path

```
/common_tasks
	create_files.yaml (create n files in path)
	create_folders.yaml (creates folders, including nested)
	cleanup_files.yaml (deletes folders and files)
	cleanup_folders.yaml
	reset_
	check_files_json.yml
	check_files_es.yml
	configure


/scenario_realtime_default
	/defaults
		paths.yml
	/actions
		folders.yaml (imports task from /common_tasks/create_folders.yaml with custom paths as args)
		files.yaml (same as above but with files)
		cleanup.yml (same as above but for files and folders)
	/configs
		ossec_manager.conf
		ossec_agent.conf
		agent.conf (we can configure it in the actions to push config to certain group of agents)
	/tests
		files_json.yml
		files_es.yml

	launch_tests.yml
		- import tasks_  (master playbook to launch the scenario)

	

/scenario_whodata
	/actions
		folders.yaml
		files.yaml
	/configs
		ossec_manager.conf
		ossec_agent.conf
		agent.conf
	/tests
		check_files_json.yml
		check_files_es.yml

	launch_tests.yml (master playbook to launch the scenario)
```

**Comment by xr09** [comment]
### Code updates

#### File creation logic

Files are now being written with the real size instead of creating sparse files, allowing for a more real-like testing scenario.

A multiplatform approach for folder creation and path handling was defined.

#### Config file

The script logic was updated to compute automatically the value `number_of_files`, no longer necessary on the config.

Now the script takes this config file as a paramenter, allowing the usage of different settings for each scenario.
