### ISSUE TITLE
Maintain production and numbered branches post release 4.5.1 in wazuh-qa repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-qa#4456]
## Description

The goal is to complete the following tasks, each task must have a PR associated with this issue.

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, `merge-4.5.1-into-4.5.2`.

## Tasks

- [x] Merge branch `4.5.1` into branch `4.5.2` on wazuh-qa repository.
- [x] Merge branch `4.5.2` into branch `4.6.0` on wazuh-qa repository.
- [x] Merge branch `4.5.2` into branch `4.6.0` on wazuh-qa repository (bis). https://github.com/wazuh/wazuh-qa/pull/4469
- [x] Merge branch `4.6.0` into branch `4.7.0` on wazuh-qa repository.
- [x] Merge branch `4.6.0` into branch `4.7.0` on wazuh-qa repository https://github.com/wazuh/wazuh-qa/pull/4470
- [x] Merge branch `4.7.0` into branch `master` on wazuh-qa repository.

**Comment by jnasselle** [comment]
Reopening this due to repos missing alignment on PRs merges

**Comment by jnasselle** [comment]
- [ ] Merge branch `4.6.0` into branch `4.7.0` on wazuh-qa repository https://github.com/wazuh/wazuh-qa/pull/4470

**Comment by Rebits** [comment]
- Merge branch `4.7.0` into branch `master` on wazuh-qa repository https://github.com/wazuh/wazuh-qa/pull/4471
