### ISSUE TITLE
Support new stage RC 1 for 4.5.2 in wazuh-qa repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-qa#4464]
## Description

This issue attempts to support a new stage RC 1 for 4.5.2 in the wazuh-qa repository.

## Tasks

- [ ] Ensure changelog is updated for 4.5.2
- [ ] Create tag v4.5.2-rc1 from branch 4.5.2 on wazuh-qa repository.
- [ ] Create a pre-release: https://github.com/wazuh/wazuh-qa/releases/tag/v4.5.2-rc1
