### ISSUE TITLE
Support new stage RC 1 for 4.5.2 in wazuh-qa repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-qa#4466]
## Description

This issue attempts to support a new stage RC 1 for 4.5.2 in the wazuh-qa repository.

## Tasks

- [x] Ensure changelog is updated for 4.5.2 https://github.com/wazuh/wazuh-qa/pull/4468
- [x] Create tag v4.5.2-rc1 from branch 4.5.2 on wazuh-qa repository.
- [x] Create a pre-release: https://github.com/wazuh/wazuh-qa/releases/tag/v4.5.2-rc1

**Comment by BelenValdivia** [comment]
## Review

- Changelog is updated
- Tag v4.5.2-rc1 has the same information that the branch 4.5.2
- Pre-release created


LGTM!
