### ISSUE TITLE
Support new stage Alpha 1 for 4.6.0 in wazuh-qa repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-qa#4473]
## Description

This issue attempts to support a new stage Alpha 1 for 4.6.0 in the wazuh-qa repository.

## Tasks

- [x] Ensure changelog is updated for 4.6.0 (if applicable): https://github.com/wazuh/wazuh-qa/pull/4475
- [x] Bump 4.6.0 revision  (if applicable): https://github.com/wazuh/wazuh-qa/pull/4476
- [x] Create tag v4.6.0-alpha1 from branch 4.6.0 on wazuh-qa repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-qa/releases/tag/v4.6.0-alpha1.

**Comment by Rebits** [comment]
Updated 4.6.0 changelog: https://github.com/wazuh/wazuh-qa/pull/4475

**Comment by davidjiglesias** [comment]
LGTM!

**Comment by damarisg** [comment]
- [ ] Ensure changelog is updated for 4.6.0 
- [ ] Create tag v4.6.0-alpha1 from branch 4.6.0 on wazuh-qa repository.
- [ ] Create and publish a pre-release: [ ] https://github.com/wazuh/wazuh-qa/releases/tag/v4.6.0-alpha1
