### ISSUE TITLE
Support new stage RC 2 for 4.5.2 in wazuh-qa repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-qa#4487]
## Description

This issue attempts to support a new stage RC 2 for 4.5.2 in the wazuh-qa repository.

## Tasks

- [x] Ensure changelog is updated for 4.5.2 (if applicable). 
  - https://github.com/wazuh/wazuh-qa/pull/4488
  - https://github.com/wazuh/wazuh-qa/pull/4490
- [x] Bump revision for branch 4.5.2 on wazuh-qa repository. https://github.com/wazuh/wazuh-qa/pull/4489
- [x] Create tag v4.5.2-rc2 from branch 4.5.2 on wazuh-qa repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-qa/releases/tag/v4.5.2-rc2.

**Comment by verdx** [comment]
LGTM

**Comment by juliamagan** [comment]
- [ ] Update changelog. https://github.com/wazuh/wazuh-qa/pull/4494
- [ ] Delete previous tag and release.
- [ ] Create new tag.
- [ ] Create new release.

**Comment by verdx** [comment]
LGTM
