### ISSUE TITLE
Maintain production and numbered branches post release 4.5.2 in wazuh-qa repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-qa#4499]
## Description

The goal is to complete the following tasks, each task must have a PR associated with this issue.

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, `merge-4.5.2-into-4.5.3`.

## Tasks

- [ ] Merge branch `4.5.2` into branch `4.5.3`.
- [ ] Merge branch `4.5.3` into branch `4.6.0`.
- [ ] Merge branch `4.6.0` into branch `4.7.0`.
- [ ] Merge branch `4.7.0` into branch `master`.
- [ ] Delete all stage tags for 4.5.2 (Example: v4.5.2-rc1, 4.5.2-alpha1, etc).
- [ ] Delete branch 4.5.2.
