### ISSUE TITLE
Determine VDT System tests tiers, preconditions, implications and expectations

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#4531]
| Target version | Related issue | 
|--------------------|--------------------|
|    4.8.0 Alpha 1            |   #4369                     |

## Description

This Issue aims to add detail to the test cases proposed in #4369. The goal is to determine tiers,  preconditions, considerations, and expectations of each test case. 

## Tasks

- [x] Assign tiers to test cases
- [x] Determine test preconditions
- [x] Determine results expectations and implications (Security, Performance, etc).
- [x] Identify the dependencies among test cases.

**Comment by Deblintrake09** [comment]
# Research Update

## Determine tiers for test cases

### Tier 0 - Basic Cases

- First syscollector scan (Rsync)
- Subsequent scan (Dbsync) without any installation

### Tier 1 - Common usage

- Installation of a vulnerable package
- Updating a vulnerable package that remains vulnerable to the same CVE
- Updating a vulnerable package that becomes vulnerable to another CVE
- Updating a vulnerable package that becomes vulnerable to another CVE and retains the previous one
- Updating a vulnerable package that ceases to be vulnerable
- Deleting a vulnerable package
- Installation of a non-vulnerable package
- Updating a non-vulnerable package that becomes vulnerable
- Updating a non-vulnerable package that remains non-vulnerable
- Deleting a non-vulnerable package
- Updating the vulnerability feed with a new applicable vulnerability
- Updating the vulnerability feed with a new non-applicable vulnerability

### Tier 2 - Non common cases

- Deleting the states index
- Modifying the vulnerability feed to remove a CVE that applies to my system

**Comment by Deblintrake09** [comment]
## Determine test preconditions

### Tier 0  - Basic Cases

<details><summary>First syscollector scan (Rsync)</summary>

```Gherkin
Scenario: First syscollector scan (Rsync)
   Given the Manager has updated the feeds and a new Agent is connected
   When the Agent's syscollector scan is run
   And a Vulnerability Scan is started on the Manager
   Then Vulnerability alerts are generated as "added" And the Agent's System states are stored
```
</details>

<details><summary>Subsequent scan (Dbsync) without any installation</summary>

```Gherkin
Scenario: Subsequent scan (Dbsync) without any installation
   Given the Manager has an agent connected
   And a first Vulnerability Scan has been executed
   And no changes have been done in the agent
   When a second Vulnerability Scan is started on the Manager
   Then Vulnerability the agent System states and vulnerability alerts remain unchanged
```
</details>

**Comment by Deblintrake09** [comment]
## Performance considerations

- Tests that require the feeds to download will take more time over time, as the feeds get larger. As real feeds are to be used, this should be taken into account.
- Tests that require the install or upgrade of a given package, will need to take into account the size of the packages for download, installation times and the time it takes between syscollector scans, for alerts to be generated and indexed.
   - It is important that the package's to be used are stored in S3 storage so the tests are not dependent on other companies' servers.

## Security implications
- It is important that as actual vulnerable packages will be installed, it is important to verify that the possible exploitabilities are protected in the endpoints used.

**Comment by Rebits** [comment]
### Tests Dependencies

<details>

<summary> Tests Codes </summary>

E2E-VD-1
E2E-VD-1
E2E-VD-1
E2E-VD-1
E2E-VD-1
E2E-VD-1
E2E-VD-1



    First syscollector scan (Rsync) 1 
    Subsequent scan (Dbsync) without any installation 2

Tier 1 - Common usage
E2E-VD-1
    Installation of a vulnerable package 3 
    Updating a vulnerable package that remains vulnerable to the same CVE 4
    Updating a vulnerable package that becomes vulnerable to another CVE 5
    Updating a vulnerable package that becomes vulnerable to another CVE and retains the previous one 6
    Updating a vulnerable package that ceases to be vulnerable 7
    Deleting a vulnerable package 8
    Installation of a non-vulnerable package 9
    Updating a non-vulnerable package that becomes vulnerable 10
    Updating a non-vulnerable package that remains non-vulnerable 11
    Deleting a non-vulnerable package 12
    Updating the vulnerability feed with a new applicable vulnerability 13
    Updating the vulnerability feed with a new non-applicable vulnerability 14
    Updating the vulnerability feed causes vulnerable agent to cease to be vulnerable 15

Tier 2 - Non common cases

    Deleting the states index
    Updating the vulnerability feed removes a CVE and causes agent to cease to be vulnerable


</details>

```mermaid
flowchart TD
    O[E2E-VD-1] -->  P[E2E-VD-2]
    P[E2E-VD-2] -->  L[E2E-VD-3]
    P[E2E-VD-2] -->  S[E2E-VD-9]
    P[E2E-VD-2] --> K[E2E-VD-15]
    L[E2E-VD-3] --> R[E2E-VD-4]
    R[E2E-VD-4] --> R2[E2E-VD-5]
    R2[E2E-VD-5] --> R3[E2E-VD-6]
    R3[E2E-VD-6] --> R4[E2E-VD-7]


    R4[E2E-VD-7] --> R5[E2E-VD-11]
    R5[E2E-VD-11] --> R7[E2E-VD-12]

    S[E2E-VD-9] --> R9[E2E-VD-10]
    R9[E2E-VD-10] --> R10[E2E-VD-8]
    
    S[E2E-VD-9]  --> S1[E2E-VD-13]
    S[E2E-VD-9]  --> S2[E2E-VD-14]
```


> **Note**
> Because of constraints related to installing multiple packages simultaneously, we've opted not to pursue a parallel approach for test cases. Instead, we will leverage parallelism solely for launching distinct use cases across the agents

**Comment by davidjiglesias** [comment]
LGTM!
