### ISSUE TITLE
Support new stage RC 1 for 4.5.3 in wazuh-qa repository

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh-qa#4537]
## Description

This issue attempts to support a new stage RC 1 for 4.5.3 in the wazuh-qa repository.

## Tasks

- [x] Ensure changelog is updated for 4.5.3 (if applicable).
- [x] ~Bump revision for branch 4.5.3 on wazuh-qa repository.~
- [x] Create tag v4.5.3-rc1 from branch 4.5.3 on wazuh-qa repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-qa/releases/tag/v4.5.3-rc1.

**Comment by rauldpm** [comment]
## Update report

- Created PR: https://github.com/wazuh/wazuh-qa/pull/4538
- Revision and version do not need to be modified as they are actually updated to 4.5.3 - 40506

**Comment by jnasselle** [comment]
LGTM

**Comment by fcaffieri** [comment]
LGTM
