### ISSUE TITLE
Support new stage Beta 1 for 4.6.0 in wazuh-qa repository

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh-qa#4550]
## Description

This issue attempts to support a new stage Beta 1 for 4.6.0 in the wazuh-qa repository.

## Tasks

- [x] Ensure changelog is updated for 4.6.0 (if applicable).
- [x] ~Bump revision for branch 4.6.0 on wazuh-qa repository.~ not bumped in order to align with wazuh/wazuh revision
- [x] Create tag v4.6.0-beta1 from branch 4.6.0 on wazuh-qa repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-qa/releases/tag/v4.6.0-beta1.

**Comment by rauldpm** [comment]
lgtm
