### ISSUE TITLE
Support new stage RC 2 for 4.5.3 in wazuh-qa repository

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh-qa#4563]
## Description

This issue attempts to support a new stage RC 2 for 4.5.3 in the wazuh-qa repository.

## Tasks

- [x] Ensure changelog is updated for 4.5.3 (if applicable). https://github.com/wazuh/wazuh-qa/pull/4566
- [x] Bump revision for branch 4.5.3 on wazuh-qa repository. https://github.com/wazuh/wazuh-qa/pull/4567
- [x] Create tag v4.5.3-rc2 from branch 4.5.3 on wazuh-qa repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-qa/releases/tag/v4.5.3-rc2.

**Comment by damarisg** [comment]
LGTM
