### ISSUE TITLE
Support new stage RC 1 for 4.6.0 in wazuh-qa repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-qa#4583]
## Description

This issue attempts to support a new stage RC 1 for 4.6.0 in the wazuh-qa repository.

## Tasks

- [x] Ensure changelog is updated for 4.6.0 (if applicable).
- [x] Bump revision for branch 4.6.0 on wazuh-qa repository. https://github.com/wazuh/wazuh-qa/pull/4584
- [x] Create tag v4.6.0-rc1 from branch 4.6.0 on wazuh-qa repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-qa/releases/tag/v4.6.0-rc1.
