### ISSUE TITLE
Publish release 4.5.3

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-qa#4596]
## Description
This issue attempts to track steps necessary to publish packages, OVA, AMI, docker images, and puppet forge for 4.5.3.

## Tasks
- [x] Launch [`Publish_release`](https://ci.wazuh.info/job/Publish_release) pipeline
- [x] Build and release debug packages
- [x] Build and push [Docker Hub images](https://ci.wazuh.info/job/procedure_push_docker_images)
- [x] Edit Docker Hub readme to include 4.5.3 in the compatibility matrix
- [x] Publish AMI

**NOTE**

Until https://github.com/wazuh/wazuh-jenkins/issues/5564, the next steps should also be executed https://github.com/wazuh/wazuh-qa/issues/4596#issuecomment-1755215375

**Comment by jnasselle** [comment]
- Notify that pre-release is broken by 4.5.3 publication
- Copy all 4.6.0 packages (packages, checksums, versions) to another directory outside of pre-release
- Modify WPK versions (linux,macos, windows) to remove 4.6.0 and upload it again
- Launch Publish_release without unattended
- Launch unattended
- Publish IAM
- Execute https://github.com/wazuh/wazuh-qa/issues/4597
- 4.6.0 pestoration packages on pre-release
- Ensure that the pre-release is functional.

**Comment by davidjiglesias** [comment]
LGTM!
