### ISSUE TITLE
Post publication live checks for 4.5.3

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-qa#4597]
## Description
This issue attempts to ensure the publication process is correct, attempting checks and live tests for published packages and images.

## Tasks

- [x] Ensure that production files are present
- [x] [Live installation test](https://ci.wazuh.info/job/Test_install_tier)
  - [x] AMD64: https://ci.wazuh.info/job/Test_install_tier/755/
- [x] WPK versions check
- [x] WPK upgrade test
  - [x] Linux
  - [x] MacOS Intel
  - [x] MacOS Apple Silicon
  - [x] Windows
- [x] AMI published
  - https://aws.amazon.com/marketplace/pp/prodview-eju4flv5eqmgq 
- [x] Puppet forge module published
  - https://forge.puppet.com/modules/wazuh/wazuh/readme 
- [x] DockerHub images published: https://ci.wazuh.info/view/Procedures/job/procedure_push_docker_images/88/
- [x] Deploy the Wazuh Installation Assistant and check that the versions installed are 4.5.3

**Comment by rauldpm** [comment]
### Check if the script of Wazuh Installation Assistant makes reference to the last version 4.5.3 internally :green_circle: 

```
[root@centos71 vagrant]# curl -sO https://packages.wazuh.com/4.5/wazuh-install.sh && sudo bash ./wazuh-install.sh -a
10/10/2023 14:12:58 INFO: Starting Wazuh installation assistant. Wazuh version: 4.5.3
10/10/2023 14:12:58 INFO: Verbose logging redirected to /var/log/wazuh-install.log
10/10/2023 14:13:03 INFO: --- Dependencies ---
10/10/2023 14:13:03 INFO: Installing lsof.
10/10/2023 14:13:09 INFO: Wazuh web interface port will be 443.
10/10/2023 14:13:10 INFO: Wazuh repository added.
10/10/2023 14:13:10 INFO: --- Configuration files ---
10/10/2023 14:13:10 INFO: Generating configuration files.
10/10/2023 14:13:10 INFO: Created wazuh-install-files.tar. It contains the Wazuh cluster key, certificates, and passwords necessary for installation.
10/10/2023 14:13:10 INFO: --- Wazuh indexer ---
10/10/2023 14:13:10 INFO: Starting Wazuh indexer installation.
10/10/2023 14:14:23 INFO: Wazuh indexer installation finished.
10/10/2023 14:14:23 INFO: Wazuh indexer post-install configuration finished.
10/10/2023 14:14:23 INFO: Starting service wazuh-indexer.
10/10/2023 14:14:30 INFO: wazuh-indexer service started.
10/10/2023 14:14:30 INFO: Initializing Wazuh indexer cluster security settings.
10/10/2023 14:14:40 INFO: Wazuh indexer cluster initialized.
10/10/2023 14:14:40 INFO: --- Wazuh server ---
10/10/2023 14:14:40 INFO: Starting the Wazuh manager installation.
10/10/2023 14:15:09 INFO: Wazuh manager installation finished.
10/10/2023 14:15:09 INFO: Starting service wazuh-manager.
10/10/2023 14:15:21 INFO: wazuh-manager service started.
10/10/2023 14:15:21 INFO: Starting Filebeat installation.
10/10/2023 14:15:26 INFO: Filebeat installation finished.
10/10/2023 14:15:26 INFO: Filebeat post-install configuration finished.
10/10/2023 14:15:26 INFO: Starting service filebeat.
10/10/2023 14:15:26 INFO: filebeat service started.
10/10/2023 14:15:26 INFO: --- Wazuh dashboard ---
10/10/2023 14:15:26 INFO: Starting Wazuh dashboard installation.
10/10/2023 14:16:15 INFO: Wazuh dashboard installation finished.
10/10/2023 14:16:15 INFO: Wazuh dashboard post-install configuration finished.
10/10/2023 14:16:15 INFO: Starting service wazuh-dashboard.
10/10/2023 14:16:15 INFO: wazuh-dashboard service started.
10/10/2023 14:16:29 INFO: Initializing Wazuh dashboard web application.
10/10/2023 14:16:31 INFO: Wazuh dashboard web application initialized.
10/10/2023 14:16:31 INFO: --- Summary ---
10/10/2023 14:16:31 INFO: You can access the web interface https://<wazuh-dashboard-ip>:443
    User: admin
    Password: KODTIaPSfSKCePMox.+82d7.BzGgTJ7w
10/10/2023 14:16:31 INFO: Installation finished.
```

![image](https://github.com/wazuh/wazuh-qa/assets/14913942/a212f937-e038-4cc8-a9dd-d1ac05d79cb5)

```
[root@centos71 vagrant]# cat /usr/share/wazuh-indexer/VERSION 
4.5.3
[root@centos71 vagrant]# cat /usr/share/wazuh-dashboard/VERSION 
4.5.3
[root@centos71 vagrant]# /var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.5.3"
WAZUH_REVISION="40508"
WAZUH_TYPE="server"
```

**Comment by juliamagan** [comment]
### WPK upgrade

<details><summary>Linux agent :green_circle:</summary>
<br>

- Agent info:

```shell
[root@wazuh-manager vagrant]# /var/ossec/bin/agent_control -i 001

Wazuh agent_control. Agent information:
   Agent ID:   001
   Agent Name: test
   IP address: any
   Status:     Active

   Operating system:    Linux |test |5.4.0-86-generic |#97-Ubuntu SMP Fri Sep 17 19:19:40 UTC 2021 |x86_64
   Client version:      Wazuh v4.5.2
   Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
   Shared file hash:    4a8724b20dee0124ff9656783c490c4e
   Last keep alive:     1696953131

   Syscheck last started at:  Tue Oct 10 15:51:54 2023
   Syscheck last ended at:    Tue Oct 10 15:51:58 2023
```

- Upgrade:

```shell
[root@wazuh-manager vagrant]# /var/ossec/bin/agent_upgrade -a 001

Upgrading...

Upgraded agents:
	Agent 001 upgraded: Wazuh v4.5.2 -> Wazuh v4.5.3

```

- Agent info:

```shell
[root@wazuh-manager vagrant]# /var/ossec/bin/agent_control -i 001

Wazuh agent_control. Agent information:
   Agent ID:   001
   Agent Name: test
   IP address: any
   Status:     Active

   Operating system:    Linux |test |5.4.0-86-generic |#97-Ubuntu SMP Fri Sep 17 19:19:40 UTC 2021 |x86_64
   Client version:      Wazuh v4.5.3
   Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
   Shared file hash:    4a8724b20dee0124ff9656783c490c4e
   Last keep alive:     1696953456

   Syscheck last started at:  Tue Oct 10 15:55:48 2023
   Syscheck last ended at:    Tue Oct 10 15:55:53 2023

```

</details>


<details><summary>Windows agent :green_circle:</summary>
<br>

- Agent info:

```shell
[root@wazuh-manager vagrant]# /var/ossec/bin/agent_control -i 002

Wazuh agent_control. Agent information:
   Agent ID:   002
   Agent Name: WIN-JLGVA4CR4VI
   IP address: any
   Status:     Active

   Operating system:    Microsoft Windows Server 2019 Standard Evaluation
   Client version:      Wazuh v4.5.2
   Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
   Shared file hash:    4a8724b20dee0124ff9656783c490c4e
   Last keep alive:     1696953214

   Syscheck last started at:  Tue Oct 10 15:52:44 2023
   Syscheck last ended at:    Tue Oct 10 15:52:58 2023

```

- Upgrade:

```shell
[root@wazuh-manager vagrant]# /var/ossec/bin/agent_upgrade -a 002

Upgrading...

Upgraded agents:
	Agent 002 upgraded: Wazuh v4.5.2 -> Wazuh v4.5.3

```

- Agent info:

```shell
[root@wazuh-manager vagrant]# /var/ossec/bin/agent_control -i 002

Wazuh agent_control. Agent information:
   Agent ID:   002
   Agent Name: WIN-JLGVA4CR4VI
   IP address: any
   Status:     Active

   Operating system:    Microsoft Windows Server 2019 Standard Evaluation
   Client version:      Wazuh v4.5.3
   Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
   Shared file hash:    4a8724b20dee0124ff9656783c490c4e
   Last keep alive:     1696953552

   Syscheck last started at:  Tue Oct 10 15:58:32 2023
   Syscheck last ended at:    Tue Oct 10 15:58:44 2023

```

</details>

**Comment by Rebits** [comment]
## WPK Upgrade - MacOS

<details>

<summary> Manager info </summary>

```
[root@ip-172-31-32-19 ec2-user]# /var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.5.3"
WAZUH_REVISION="40508"
WAZUH_TYPE="server"
```

</details>


<details>

<summary> MacOS Intel :yellow_circle:  </summary>

MacOS agent upgrade initially fails due to `Send open file error`. Regarding this error as @Nicogp specified in [this comment](https://github.com/wazuh/wazuh/issues/17984#issuecomment-1650417770) this error occur in low resource environment or in unstable network

Impossible to replicate and probably related with the environment network.

- Agent Info

```
[root@ip-172-31-32-19 ec2-user]# /var/ossec/bin/agent_control -i 001

Wazuh agent_control. Agent information:
   Agent ID:   001
   Agent Name: ip-172-31-40-220.ec2.internal
   IP address: any
   Status:     Active

   Operating system:    Darwin |ip-172-31-40-220.ec2.internal |22.6.0 |Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:56 PDT 2023; root:xnu-8796.141.3~6/RELEASE_X86_64 |x86_64
   Client version:      Wazuh v4.5.2
   Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
   Shared file hash:    4a8724b20dee0124ff9656783c490c4e
   Last keep alive:     1696958469

   Syscheck last started at:  Tue Oct 10 17:21:06 2023 (Scan in progress)
   Syscheck last ended at:    Unknown
[root@ip-172-31-32-19 ec2-user]# 
```


- Upgrade

```
[root@ip-172-31-32-19 ec2-user]# /var/ossec/bin/agent_upgrade -a 001

Upgrading...

Failed upgrades:
	Agent 001 status: Send open file error
[root@ip-172-31-32-19 ec2-user]# /var/ossec/bin/agent_upgrade -a 001

Upgrading...

Upgraded agents:
	Agent 001 upgraded: Wazuh v4.5.2 -> Wazuh v4.5.3
[root@ip-172-31-32-19 ec2-user]# 
```


- Agent Info

```
[root@ip-172-31-32-19 ec2-user]# /var/ossec/bin/agent_control -i 001

Wazuh agent_control. Agent information:
   Agent ID:   001
   Agent Name: ip-172-31-40-220.ec2.internal
   IP address: any
   Status:     Active

   Operating system:    Darwin |ip-172-31-40-220.ec2.internal |22.6.0 |Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:56 PDT 2023; root:xnu-8796.141.3~6/RELEASE_X86_64 |x86_64
   Client version:      Wazuh v4.5.3
   Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
   Shared file hash:    4a8724b20dee0124ff9656783c490c4e
   Last keep alive:     1696958591

   Syscheck last started at:  Tue Oct 10 17:22:21 2023
   Syscheck last ended at:    Tue Oct 10 17:22:24 2023

```



</details>

**Comment by davidjiglesias** [comment]
LGTM!
