### ISSUE TITLE
FIM System tests: Tasks to modify attributes of selected files

### ISSUE THREAD

**Issue by xr09** [wazuh/wazuh-qa#460]
### Objective

This task will provide the functionality to change file attributes like permissions and file owner/group.

### Design

A Python function will be created which will acept a tuple of file definitions, each definition will be a dictionary with the following keys:

```
definitions = ( {
  "filepath": "/var/sample/myfile",
  "owner": "newuser",
  "group": "newgroup",
  "mode": "0644"
},
  "filepath": "/var/exec_file",
  "mode": "0777"
},
)

def modify_attributes(definitions=None):
   ...
```

The function will iterate over these definitions and apply changes accordingly, only `filepath` is required, the fields `owner`, `group` and `mode` will be applied if found on the dictionary.

### Tasks

- [x] Implement Python function with multiplatform support

### Tests

- [x] Test basic execution on Linux  (max 1000 files)
- [x] Test basic execution on Windows (max 1000 files)
- [x] Test advanced execution on Linux (max 100000 files)
- [x] Test advanced execution on Windows (max 100000 files)

**Comment by xr09** [comment]
We have initial support for modifying file content and its attributes.

The function `modify_file_content(filepath)` will append a random number of bytes to the file.

The function `modify_file(filepath, owner, group, mode)` modifies file owner, group and permissions.

There is a wokring branch at https://github.com/wazuh/wazuh-qa/tree/feature-460-modify-files
