### ISSUE TITLE
Publish release 4.5.3

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-qa#4602]
## Description
This issue attempts to track steps necessary to publish packages, OVA, AMI, docker images, and puppet forge for 4.5.3.

## Tasks
- [ ] Send AMI to analysis
- [ ] Launch [`Publish_release`](https://ci.wazuh.info/job/Publish_release) pipeline
- [ ] Build and release debug packages
- [ ] Build and push [Docker Hub images](https://ci.wazuh.info/job/procedure_push_docker_images)
- [ ] Publish AMI
