### ISSUE TITLE
Post publication live checks for 4.5.3

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-qa#4612]
## Description
This issue attempts to ensure the publication process was correct, attempting checks and live tests for published packages and images.

## Tasks
- [ ] Ensure that production files are present.
- [ ] Deploy the `Wazuh Installation Assistant` and check the version installed is 4.5.3.
- [ ] [AMD64 Live installation test](https://ci.wazuh.info/job/Test_install_tier).
- [ ] WPK versions check.
- [ ] WPK upgrade test.
  - [ ] Linux
  - [ ] MacOS Intel
  - [ ] MacOS Apple Silicon
  - [ ] Windows
- [ ] [AMI published](https://aws.amazon.com/marketplace/pp/prodview-eju4flv5eqmgq).
- [ ] [Puppet forge module published](https://forge.puppet.com/modules/wazuh/wazuh/readme).
- [ ] [Docker images published](https://hub.docker.com/u/wazuh).
