### ISSUE TITLE
Post release tasks for 4.5.3

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-qa#4615]
## Description
This issue attempts to track steps necessary to complete post-release maintenance tasks for 4.5.3.
The goal is to complete the following tasks, each task must have a PR associated with this issue.

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, `merge-4.5.3-into-4.6.0`.

## Tasks

- [x] ~Merge branch `4.5.3` into branch `4.6.0`~. https://github.com/wazuh/wazuh-qa/issues/4615#issuecomment-1757073960
- [x] ~Merge branch `4.6.0` into branch `4.7.0`~. https://github.com/wazuh/wazuh-qa/issues/4615#issuecomment-1757078446
- [x] ~Merge branch `4.7.0` into branch `4.7.1`~. https://github.com/wazuh/wazuh-qa/issues/4615#issuecomment-1757082745
- [x] ~Merge branch `4.7.1` into branch `master`~. https://github.com/wazuh/wazuh-qa/issues/4615#issuecomment-1757086960
- [x] Publish GitHub release as latest.
- [x] Delete all stage pre-releases for 4.5.3 (https://github.com/wazuh/wazuh-qa/releases).
- [x] Delete all stage tags for v4.5.3. **BE CAREFUL NOT TO DELETE DEFINITIVE TAG**. Example: v4.5.3-rc1, 4.5.3-alpha1, etc.
- [x] Delete branch `4.5.3`.

**Comment by Rebits** [comment]
`4.6.0` has already been populated with latests 4.5.3 changes
```
commit 8e3cbf373b6ac81ae1fb8aa780407f6771b683e5 (HEAD -> 4.5.3, tag: v4.5.3, origin/4.5.3)
Merge: 2268196ae a3a1e731d
...
➜  wazuh-qa-maintenance git:(4.6.0) ✗ git log | grep 8e3cbf373b6ac81ae1fb8aa780407f6771b683e5                                        
commit 8e3cbf373b6ac81ae1fb8aa780407f6771b683e5

➜  wazuh-qa-maintenance git:(4.5.3) ✗ git log 4.6.0..4.5.3 --oneline > commits
➜  wazuh-qa-maintenance git:(4.5.3) ✗ cat commits 
```

**Comment by Rebits** [comment]
`4.7.1` has already been populated with latest `4.7.0` changes
```
commit 0d734c384912679294b99a8310181cfd9cde2e65 (HEAD -> 4.7.0, origin/4.7.0)
Merge: e81906f42 799b583ee
➜  wazuh-qa-maintenance git:(4.7.1) ✗ git log | grep 0d734c384912679294b99a8310181cfd9cde2e65                                        
commit 0d734c384912679294b99a8310181cfd9cde2e65


➜  wazuh-qa-maintenance git:(4.7.1) ✗ git log 4.7.1..4.7.0 --oneline > commits           
➜  wazuh-qa-maintenance git:(4.7.1) ✗ cat commits 
```

**Comment by Rebits** [comment]
`master` has already been populated with latest `4.7.1` changes
```
commit 474318a9a32ba5075b4c0f09d262f860a6a61cb3 (HEAD -> 4.7.1, origin/4.7.1)
Merge: 596c52d2f 987e105fb
➜  wazuh-qa-maintenance git:(master) ✗ git log | grep 474318a9a32ba5075b4c0f09d262f860a6a61cb3                                        
commit 474318a9a32ba5075b4c0f09d262f860a6a61cb3

➜  wazuh-qa-maintenance git:(master) ✗ git log master..4.7.1 --oneline > commits        
➜  wazuh-qa-maintenance git:(master) ✗ cat commits

```

**Comment by juliamagan** [comment]
LGTM
