### ISSUE TITLE
Support new stage Alpha 1 for 4.7.0 in wazuh-qa repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-qa#4619]
## Description

This issue attempts to support a new stage Alpha 1 for 4.7.0 in the wazuh-qa repository.

## Tasks

- [x] Ensure changelog is updated for 4.7.0 (if applicable). 
  - https://github.com/wazuh/wazuh-qa/pull/4621
  - https://github.com/wazuh/wazuh-qa/pull/4623
- [x] Bump revision for branch 4.7.0 on wazuh-qa repository. https://github.com/wazuh/wazuh-qa/pull/4622
- [x] Create tag v4.7.0-alpha1 from branch 4.7.0 on wazuh-qa repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-qa/releases/tag/v4.7.0-alpha1.

**Comment by pro-akim** [comment]
## Update Notes
LGTM
