### ISSUE TITLE
Support new stage Alpha 1 for 4.5.4 in wazuh-qa repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-qa#4628]
## Description

This issue attempts to support a new stage Alpha 1 for 4.5.4 in the wazuh-qa repository.

## Tasks

- [x] Ensure changelog is updated for 4.5.4 (if applicable). https://github.com/wazuh/wazuh-qa/pull/4629
- [x] Bump revision for branch 4.5.4 on wazuh-qa repository. https://github.com/wazuh/wazuh-qa/pull/4630
- [x] Create tag v4.5.4-alpha1 from branch 4.5.4 on wazuh-qa repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-qa/releases/tag/v4.5.4-alpha1

**Comment by juliamagan** [comment]
The ETA of the release should not be updated until post release.

Also, check the links in the main comment, as there is one that does not work correctly.

**Comment by Rebits** [comment]
Fixed release link

In my humble opinion, to prevent the need for re-tagging version 4.5.4, I will diligently update the Estimated Time of Arrival (ETA) in the changelog. If any adjustments are required post-release, I'll make them promptly.


IMHO to prevent the need for re-tagging version 4.5.4, I would maintain the ETA in the changelog for this case and I in case is necessary, we will change it accordingly in the post-release stage.
