### ISSUE TITLE
Publish release 4.5.4

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-qa#4644]
## Description
This issue attempts to track the steps necessary to publish packages, OVA, AMI, docker images, and puppet forge for 4.5.4.

## Tasks
- [x] Send AMI to analysis.
- [x] Launch [`Publish_release`](https://ci.wazuh.info/job/Publish_release) pipeline.
- [x] Build and release debug packages.
- [x] Build and push [Docker Hub images](https://ci.wazuh.info/job/procedure_push_docker_images).
  - https://ci.wazuh.info/job/procedure_push_docker_images/92/
- [x] Publish AMI.

**Comment by juliamagan** [comment]
The following tasks must be completed in order:

- [ ] Notify that pre-release is broken by the 4.5.3 publication
- [ ] Copy all 4.6.0 packages (packages, debug-packages, checksums, versions) to another directory outside of pre-release
  - https://s3.console.aws.amazon.com/s3/buckets/packages-dev.wazuh.com?prefix=pre-release-4.6.0-backup/&region=us-west-1 
- [ ] Remove 4.6.0 files
  - [ ] pre-debug
  - [ ] pre-release
- [ ] Modify WPK versions (Linux,macOS, Windows) to remove 4.6.0 and upload it again
  - [ ] Ensure that the versions files are publicly available
- [ ] Launch Publish_release without unattended
  - https://ci.wazuh.info/view/Releases/job/Publish_release/368/
- [ ] Send AMI to analysis
  - AMI analysis request: https://aws.amazon.com/marketplace/management/manage-products/#/ami-09f7f1037739f17fe/details
- [ ] Wait for the Publish_release pipeline to finish
- [ ] Launch unattended
  - https://ci.wazuh.info/view/Releases/job/publish_unattended/171/
- [ ] Publish AMI
  - https://aws.amazon.com/marketplace/management/products/79ced6c9-1e2d-4f22-ada6-dc528473b3f8/overview
- [ ] Publish pre-debug packages

**Comment by davidjiglesias** [comment]
LGTM!
