### ISSUE TITLE
Post publication live checks for 4.5.4

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-qa#4645]
## Description
This issue attempts to ensure the publication process was correct, attempting checks and live tests for published packages and images.

## Tasks
- [x] Ensure that production files are present.
- [x] [AMD64 Live installation test](https://ci.wazuh.info/job/Test_install_tier).
- [x] WPK versions check.
- [x] Deploy the `Wazuh Installation Assistant` and check the version installed is 4.5.4.
- [x] WPK upgrade test.
  - [x] Linux
  - [x] MacOS Intel
  - [x] Windows
- [x] [AMI published](https://aws.amazon.com/marketplace/pp/prodview-eju4flv5eqmgq).
- [x] [Puppet forge module published](https://forge.puppet.com/modules/wazuh/wazuh/readme).
- [x] [Docker images published](https://ci.wazuh.info/view/Procedures/job/procedure_push_docker_images/92/).

**Comment by damarisg** [comment]
###  Deploy the Wazuh Installation Assistant and check the version installed is 4.5.4. 🟢
<details>
<Summary> Deploy the Wazuh Installation Assistant </Summary>

  > [root@localhost vagrant]# curl -sO https://packages.wazuh.com/4.5/wazuh-install.sh && sudo bash ./wazuh-install.sh -a
  > 23/10/2023 17:24:17 INFO: Starting Wazuh installation assistant. Wazuh version: 4.5.4
  > 23/10/2023 17:24:17 INFO: Verbose logging redirected to /var/log/wazuh-install.log
  > 23/10/2023 17:24:23 INFO: --- Dependencies ---
  > 23/10/2023 17:24:23 INFO: Installing lsof.
  > 23/10/2023 17:24:59 INFO: Wazuh web interface port will be 443.
  > 23/10/2023 17:25:02 INFO: Wazuh repository added.
  > 23/10/2023 17:25:02 INFO: --- Configuration files ---
  > 23/10/2023 17:25:02 INFO: Generating configuration files.
  > 23/10/2023 17:25:04 INFO: Created wazuh-install-files.tar. It contains the Wazuh cluster key, certificates, and passwords necessary for installation.
  > 23/10/2023 17:25:04 INFO: --- Wazuh indexer ---
  > 23/10/2023 17:25:04 INFO: Starting Wazuh indexer installation.
  > 23/10/2023 17:28:15 INFO: Wazuh indexer installation finished.
  > 23/10/2023 17:28:15 INFO: Wazuh indexer post-install configuration finished.
  > 23/10/2023 17:28:15 INFO: Starting service wazuh-indexer.
  > 23/10/2023 17:28:40 INFO: wazuh-indexer service started.
  > 23/10/2023 17:28:40 INFO: Initializing Wazuh indexer cluster security settings.
  > 23/10/2023 17:28:50 INFO: Wazuh indexer cluster initialized.
  > 23/10/2023 17:28:50 INFO: --- Wazuh server ---
  > 23/10/2023 17:28:50 INFO: Starting the Wazuh manager installation.
  > 23/10/2023 17:30:30 INFO: Wazuh manager installation finished.
  > 23/10/2023 17:30:30 INFO: Starting service wazuh-manager.
  > 23/10/2023 17:30:47 INFO: wazuh-manager service started.
  > 23/10/2023 17:30:47 INFO: Starting Filebeat installation.
  > 23/10/2023 17:30:58 INFO: Filebeat installation finished.
  > 23/10/2023 17:31:03 INFO: Filebeat post-install configuration finished.
  > 23/10/2023 17:31:03 INFO: Starting service filebeat.
  > 23/10/2023 17:31:03 INFO: filebeat service started.
  > 23/10/2023 17:31:03 INFO: --- Wazuh dashboard ---
  > 23/10/2023 17:31:03 INFO: Starting Wazuh dashboard installation.
  > 23/10/2023 17:33:12 INFO: Wazuh dashboard installation finished.
  > 23/10/2023 17:33:12 INFO: Wazuh dashboard post-install configuration finished.
  > 23/10/2023 17:33:12 INFO: Starting service wazuh-dashboard.
  > 23/10/2023 17:33:12 INFO: wazuh-dashboard service started.
  > 23/10/2023 17:33:37 INFO: Initializing Wazuh dashboard web application.
  > 23/10/2023 17:33:39 INFO: Wazuh dashboard web application initialized.
  > 23/10/2023 17:33:39 INFO: --- Summary ---
  > 23/10/2023 17:33:39 INFO: You can access the web interface https://<wazuh-dashboard-ip>:443
  >     User: admin
  >     Password: ?uJeBw6r2FBjeN.YBq2STANYUZzSkBfM
  > 23/10/2023 17:33:39 INFO: Installation finished.
 </details>

<details>
<Summary>Check the version installed is 4.5.4.</Summary>  

  > [root@localhost vagrant]# cat /usr/share/wazuh-indexer/VERSION
  > 4.5.4
  
  > [root@localhost vagrant]# cat /usr/share/wazuh-dashboard/VERSION
  > 4.5.4
  
  > [root@localhost vagrant]# /var/ossec/bin/wazuh-control info
  > WAZUH_VERSION="v4.5.4"
  > WAZUH_REVISION="40510"
  > WAZUH_TYPE="server"

 </details>

**Comment by rauldpm** [comment]
### WPK upgrade test 4.5.3 -> 4.5.4

#### Ubuntu manager

<details><summary>Manager info and agent connection</summary>

```
root@ubuntu18stack:/home/vagrant# /var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.5.4"
WAZUH_REVISION="40510"
WAZUH_TYPE="server"
```

```
root@ubuntu18stack:/home/vagrant# /var/ossec/bin/agent_control -l

Wazuh agent_control. List of available agents:
   ID: 000, Name: ubuntu18stack (server), IP: 127.0.0.1, Active/Local
   ID: 002, Name: WIN-OED6N048SU6, IP: any, Active
   ID: 003, Name: ubuntu18agent, IP: any, Active

List of agentless devices:
```

</details>

#### Ubuntu agent

<details><summary>Agent upgrade</summary>

```
root@ubuntu18stack:/home/vagrant# /var/ossec/bin/agent_control -i 003

Wazuh agent_control. Agent information:
   Agent ID:   003
   Agent Name: ubuntu18agent
   IP address: any
   Status:     Active

   Operating system:    Linux |ubuntu18agent |4.15.0-213-generic |#224-Ubuntu SMP Mon Jun 19 13:30:12 UTC 2023 |x86_64
   Client version:      Wazuh v4.5.3
   Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
   Shared file hash:    4a8724b20dee0124ff9656783c490c4e
   Last keep alive:     1698083694

   Syscheck last started at:  Mon Oct 23 17:54:46 2023
   Syscheck last ended at:    Mon Oct 23 17:54:47 2023

root@ubuntu18stack:/home/vagrant# /var/ossec/bin/agent_upgrade -a 003

Upgrading...

Upgraded agents:
	Agent 003 upgraded: Wazuh v4.5.3 -> Wazuh v4.5.4

root@ubuntu18stack:/home/vagrant# /var/ossec/bin/agent_control -i 003

Wazuh agent_control. Agent information:
   Agent ID:   003
   Agent Name: ubuntu18agent
   IP address: any
   Status:     Active

   Operating system:    Linux |ubuntu18agent |4.15.0-213-generic |#224-Ubuntu SMP Mon Jun 19 13:30:12 UTC 2023 |x86_64
   Client version:      Wazuh v4.5.4
   Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
   Shared file hash:    4a8724b20dee0124ff9656783c490c4e
   Last keep alive:     1698083896

   Syscheck last started at:  Mon Oct 23 17:57:37 2023
   Syscheck last ended at:    Mon Oct 23 17:57:39 2023
```

</details>

<details><summary>Agent version change and upgrade log</summary>

```
root@ubuntu18agent:/home/vagrant# /var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.5.3"
WAZUH_REVISION="40508"
WAZUH_TYPE="agent"

root@ubuntu18agent:/home/vagrant# /var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.5.4"
WAZUH_REVISION="40510"
WAZUH_TYPE="agent"

root@ubuntu18agent:/home/vagrant# cat /var/ossec/logs/upgrade.log 
2023/10/23 17:57:31 - Generating Backup.
tar: ./var/ossec/queue/sockets/wmodules: socket ignored
tar: ./var/ossec/queue/sockets/syscheck: socket ignored
tar: ./var/ossec/queue/sockets/com: socket ignored
tar: ./var/ossec/queue/sockets/control: socket ignored
tar: ./var/ossec/queue/sockets/upgrade: socket ignored
tar: ./var/ossec/queue/sockets/logcollector: socket ignored
tar: ./var/ossec/queue/sockets/queue: socket ignored
tar: ./var/ossec/queue/alerts/execq: socket ignored
tar: ./var/ossec/queue/alerts/cfgaq: socket ignored
2023/10/23 17:57:32 - Upgrade started.

 Wazuh v4.5.4 (Rev. 40510) Installation Script - https://www.wazuh.com

 You are about to start the installation process of Wazuh.
 You must have a C compiler pre-installed in your system.

  - System: Linux ubuntu18agent 4.15.0-213-generic (ubuntu 18.04)
  - User: root
  - Host: ubuntu18agent


  -- Press ENTER to continue or Ctrl-C to abort. --

 - You already have Wazuh installed. Do you want to update it? (y/n): 
    - Installation will be made at  /var/ossec .

4- Installing the system

DIR="/var/ossec"
 - Running the Makefile

Stopping Wazuh...
agent
Wait for success...
success
Removing old SCA policies...
Installing SCA policies...


Wait for success...
success
Starting Wazuh...

 - Configuration finished properly.

 - To start Wazuh:
      /var/ossec/bin/wazuh-control start

 - To stop Wazuh:
      /var/ossec/bin/wazuh-control stop

 - The configuration can be viewed or modified at /var/ossec/etc/ossec.conf


   Thanks for using Wazuh.
   Please don't hesitate to contact us if you need help or find
   any bugs.

   Use our public Mailing List at:
          https://groups.google.com/forum/#!forum/wazuh

   More information can be found at:
          - http://www.wazuh.com

    ---  Press ENTER to finish (maybe more information below). ---

 - Update completed.

2023/10/23 17:57:42 - Installation result = 0
2023/10/23 17:57:43 - Waiting connection... Status = connected. Remaining attempts: 29.
2023/10/23 17:57:43 - Connected to manager.
2023/10/23 17:57:43 - Upgrade finished successfully.
```

</details>


#### Windows agent

<details><summary>Agent upgrade</summary>

```
root@ubuntu18stack:/home/vagrant# /var/ossec/bin/agent_control -i 002

Wazuh agent_control. Agent information:
   Agent ID:   002
   Agent Name: WIN-OED6N048SU6
   IP address: any
   Status:     Active

   Operating system:    Microsoft Windows Server 2016 Datacenter Evaluation
   Client version:      Wazuh v4.5.3
   Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
   Shared file hash:    4a8724b20dee0124ff9656783c490c4e
   Last keep alive:     1698082999

   Syscheck last started at:  Mon Oct 23 17:42:40 2023
   Syscheck last ended at:    Mon Oct 23 17:42:46 2023

root@ubuntu18stack:/home/vagrant# /var/ossec/bin/agent_upgrade -a 002

Upgrading...

Upgraded agents:
	Agent 002 upgraded: Wazuh v4.5.3 -> Wazuh v4.5.4

root@ubuntu18stack:/home/vagrant# /var/ossec/bin/agent_control -i 002

Wazuh agent_control. Agent information:
   Agent ID:   002
   Agent Name: WIN-OED6N048SU6
   IP address: any
   Status:     Active

   Operating system:    Microsoft Windows Server 2016 Datacenter Evaluation
   Client version:      Wazuh v4.5.4
   Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
   Shared file hash:    4a8724b20dee0124ff9656783c490c4e
   Last keep alive:     1698084049

   Syscheck last started at:  Mon Oct 23 18:00:09 2023
   Syscheck last ended at:    Mon Oct 23 18:00:15 2023
```

</details>

<details><summary>Agent version change and upgrade log</summary>

![1](https://github.com/wazuh/wazuh-qa/assets/14913942/26a7dbbc-ace1-40f9-929e-8f4d2f168c5e)
![2](https://github.com/wazuh/wazuh-qa/assets/14913942/ef4e6a70-f5db-4098-a91b-f324227c0861)
![3](https://github.com/wazuh/wazuh-qa/assets/14913942/0ab3c49c-e62e-41e3-a161-a36bde354a59)

</details>

**Comment by damarisg** [comment]
# WPK upgrade test 4.5.3 -> 4.5.4

## macOS

### Manager:

- Check Status
  > [root@ip-172-31-36-188 ec2-user]# systemctl status wazuh-manager
  > ● wazuh-manager.service - Wazuh manager
  >    Loaded: loaded (/usr/lib/systemd/system/wazuh-manager.service; enabled; vendor preset: disabled)
  >    Active: active (running) since Mon 2023-10-23 18:51:20 UTC; 1min 5s ago
  >   Process: 5083 ExecStop=/usr/bin/env /var/ossec/bin/wazuh-control stop (code=exited, status=0/SUCCESS)
  >   Process: 5224 ExecStart=/usr/bin/env /var/ossec/bin/wazuh-control start (code=exited, status=0/SUCCESS)
  >    CGroup: /system.slice/wazuh-manager.service
  >            ├─5285 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
  >            ├─5327 /var/ossec/bin/wazuh-authd
  >            ├─5344 /var/ossec/bin/wazuh-db
  >            ├─5369 /var/ossec/bin/wazuh-execd
  >            ├─5371 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
  >            ├─5374 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
  >            ├─5390 /var/ossec/bin/wazuh-analysisd
  >            ├─5402 /var/ossec/bin/wazuh-syscheckd
  >            ├─5450 /var/ossec/bin/wazuh-remoted
  >            ├─5482 /var/ossec/bin/wazuh-logcollector
  >            ├─5504 /var/ossec/bin/wazuh-monitord
  >            └─5528 /var/ossec/bin/wazuh-modulesd
  > 
  > Oct 23 18:51:11 ip-172-31-36-188.ec2.internal env[5224]: Started wazuh-execd...
  > Oct 23 18:51:12 ip-172-31-36-188.ec2.internal env[5224]: Started wazuh-analysisd...
  > Oct 23 18:51:13 ip-172-31-36-188.ec2.internal env[5224]: Started wazuh-syscheckd...
  > Oct 23 18:51:14 ip-172-31-36-188.ec2.internal env[5224]: Started wazuh-remoted...
  > Oct 23 18:51:15 ip-172-31-36-188.ec2.internal env[5224]: Started wazuh-logcollector...
  > Oct 23 18:51:16 ip-172-31-36-188.ec2.internal env[5224]: Started wazuh-monitord...
  > Oct 23 18:51:17 ip-172-31-36-188.ec2.internal env[5224]: Started wazuh-modulesd...
  > Oct 23 18:51:18 ip-172-31-36-188.ec2.internal crontab[5623]: (root) LIST (root)
  > Oct 23 18:51:20 ip-172-31-36-188.ec2.internal env[5224]: Completed.
  > Oct 23 18:51:20 ip-172-31-36-188.ec2.internal systemd[1]: Started Wazuh manager.

- Check Version

  > [root@ip-172-31-36-188 ec2-user]# /var/ossec/bin/wazuh-control info -v
  > v4.5.4

- Check Agent connected

  > 
  > [root@ip-172-31-36-188 ec2-user]#  /var/ossec/bin/agent_control -i 001
  > 
  > Wazuh agent_control. Agent information:
  >    Agent ID:   001
  >    Agent Name: ip-172-31-32-59.ec2.internal
  >    IP address: any
  >    Status:     Active
  > 
  >    Operating system:    Darwin |ip-172-31-32-59.ec2.internal |22.6.0 |Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:56 PDT 2023; root:xnu-8796.141.3~6/RELEASE_X86_64 |x86_64
  >    Client version:      Wazuh v4.5.3
  >    Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
  >    Shared file hash:    4a8724b20dee0124ff9656783c490c4e
  >    Last keep alive:     1698087649
  > 
  >    Syscheck last started at:  Mon Oct 23 18:59:20 2023
  >    Syscheck last ended at:    Mon Oct 23 18:59:39 2023


### Agent:

- Check version installed

  > sh-3.2#  /Library/Ossec/bin/wazuh-control info -v
  > v4.5.3

**Comment by davidjiglesias** [comment]
LGTM!
