### ISSUE TITLE
FIM System tests: Clean up all hosts (Managers, Agents and, ES index)

### ISSUE THREAD

**Issue by rshad** [wazuh/wazuh-qa#465]
#### Objective

Restore both `wazuh-manager` and `wazuh-agent` to their default configuration. This task is needed after the execution of each of the testing scenarios.

#### Design

Assuming we are dealing with `Package` installations for both `wazuh-manager` and `wazuh-agent` then we will proceed to uninstall them and make a clean up of all the related ELK indexes, once a scenario execution is completed.

All the required tasks will be implemented using Ansible

#### Tasks

- [x] Implement the required Ansible tasks. These include:

**Services Stoppage and `/var/ossec` and ELK indexes deletion.**

- - [x] Stop and Uninstall `wazuh-agent`  and `wazuh-manager, wazuh-api and, filebeat` services.
- - [x] Ensure the deletion of the folder `/var/ossec`. on the hosts:
- - - [x] masters and workers.
- - - [x] linuxagents.
- - [x] Ensure the deletion of the folder `...` on the hosts:
- - - [x] windowsagents.
- - [x] Delete ELK related indexes.
- - [x] Stop Elasticsearch service.
- - [x] Stop Kibana service. 
- [x] Include execution `Parallelism` to reduce execution time.

**Services Installation and Starting up**
- [x] Services to start:
- - - [x] wazuh-manager.
- - - [x] wazuh-api.
- - - [x] filebeat.
- - - [ ] elasticsearch.
- - - [ ] kibana.
- - - [x] wazuh-agent.

Kr,

Rshad

**Comment by rshad** [comment]
Working branch: [feature-465-clean-up](https://github.com/wazuh/wazuh-qa/tree/feature-465-clean-up).

**Comment by jm404** [comment]
Done in #473
