### ISSUE TITLE
Publish release 4.6.0

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-qa#4660]
## Description
This issue attempts to track the steps necessary to publish packages, OVA, AMI, docker images, and puppet forge for 4.6.0.

## Tasks
- [x] Send AMI to analysis.
- [x] Launch [`Publish_release`](https://ci.wazuh.info/job/Publish_release) pipeline.
- [x] Build and release debug packages.
- [x] Build and push [Docker Hub images](https://ci.wazuh.info/job/procedure_push_docker_images).
  - https://ci.wazuh.info/job/procedure_push_docker_images/94/
- [x] Publish AMI.

**Comment by juliamagan** [comment]
The following tasks must be completed in order:

- [ ] Notify that pre-release is broken by the 4.6.0 publication
- [ ] Copy all 4.7.0  packages (packages, debug-packages, checksums, versions) to another directory outside of pre-release
  - https://s3.console.aws.amazon.com/s3/buckets/packages-dev.wazuh.com?prefix=pre-release-backup/&region=us-west-1
  - https://s3.console.aws.amazon.com/s3/buckets/packages-dev.wazuh.com?region=us-west-1&prefix=pre-debug-backup/&showversions=false
- [ ] Remove  4.7.0 files
  - [ ] pre-debug
  - [ ] pre-release
- [ ] Modify WPK versions (Linux,macOS, Windows) to remove 4.7.0 and upload it again
  - [ ] Ensure that the versions files are publicly available
- [ ] Launch Publish_release without unattended
  - https://ci.wazuh.info/job/Publish_release/369/
- [ ] Send AMI to analysis
  - AMI analysis request: https://aws.amazon.com/marketplace/management/manage-products/#/ami-0243a72728a1efe63/details
- [ ] Wait for the Publish_release pipeline to finish
- [ ] Launch unattended
  - https://ci.wazuh.info/view/Releases/job/publish_unattended/181/
- [ ] Publish AMI
  - https://aws.amazon.com/marketplace/management/requests/4u8fee5vnyc81texorus1cmne
- [ ] Publish pre-debug packages

**Comment by pro-akim** [comment]
## Review Notes

- 4.7.0 packages are not available anymore in pre-release
- WPK are publicly available
- AMI is tested and published.


LGTM
