### ISSUE TITLE
Post publication live checks for 4.6.0

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-qa#4661]
## Description
This issue attempts to ensure the publication process was correct, attempting checks and live tests for published packages and images.

## Tasks
- [x] Ensure that production files are present.
- [x] Deploy the `Wazuh Installation Assistant` and check the version installed is 4.6.0. 
  - https://github.com/wazuh/wazuh-qa/issues/4661#issuecomment-1787101788
- [x] [AMD64 Live installation test](https://ci.wazuh.info/job/Test_install_tier).
  - https://ci.wazuh.info/job/Test_install_tier/772/
- [x] WPK versions check.
- [x] WPK upgrade test. https://github.com/wazuh/wazuh-qa/issues/4661#issuecomment-1787194731
  - [x] Linux
  - [x] MacOS Intel
  - [x] Windows
- [x] [AMI published](https://aws.amazon.com/marketplace/pp/prodview-eju4flv5eqmgq).
- [x] [Puppet forge module published](https://forge.puppet.com/modules/wazuh/wazuh/readme).
- [x] [Docker images published](https://hub.docker.com/u/wazuh).

**Comment by juliamagan** [comment]
## WIA test

<details>
<summary>Install :green_circle:</summary>
<br>


```shell
[root@ip-172-31-68-32 ec2-user]# curl -sO https://packages.wazuh.com/4.6/wazuh-install.sh && sudo bash ./wazuh-install.sh -a
31/10/2023 12:03:46 INFO: Starting Wazuh installation assistant. Wazuh version: 4.6.0
31/10/2023 12:03:46 INFO: Verbose logging redirected to /var/log/wazuh-install.log
31/10/2023 12:03:59 INFO: Wazuh web interface port will be 443.
31/10/2023 12:04:00 INFO: Wazuh repository added.
31/10/2023 12:04:00 INFO: --- Configuration files ---
31/10/2023 12:04:00 INFO: Generating configuration files.
31/10/2023 12:04:02 INFO: Created wazuh-install-files.tar. It contains the Wazuh cluster key, certificates, and passwords necessary for installation.
31/10/2023 12:04:02 INFO: --- Wazuh indexer ---
31/10/2023 12:04:02 INFO: Starting Wazuh indexer installation.
31/10/2023 12:05:32 INFO: Wazuh indexer installation finished.
31/10/2023 12:05:32 INFO: Wazuh indexer post-install configuration finished.
31/10/2023 12:05:32 INFO: Starting service wazuh-indexer.
31/10/2023 12:05:54 INFO: wazuh-indexer service started.
31/10/2023 12:05:54 INFO: Initializing Wazuh indexer cluster security settings.
31/10/2023 12:06:05 INFO: Wazuh indexer cluster initialized.
31/10/2023 12:06:05 INFO: --- Wazuh server ---
31/10/2023 12:06:05 INFO: Starting the Wazuh manager installation.
31/10/2023 12:06:30 INFO: Wazuh manager installation finished.
31/10/2023 12:06:30 INFO: Starting service wazuh-manager.
31/10/2023 12:06:48 INFO: wazuh-manager service started.
31/10/2023 12:06:48 INFO: Starting Filebeat installation.
31/10/2023 12:07:16 INFO: Filebeat installation finished.
31/10/2023 12:07:17 INFO: Filebeat post-install configuration finished.
31/10/2023 12:07:17 INFO: Starting service filebeat.
31/10/2023 12:07:17 INFO: filebeat service started.
31/10/2023 12:07:17 INFO: --- Wazuh dashboard ---
31/10/2023 12:07:18 INFO: Installing chrome.
31/10/2023 12:08:04 INFO: --- Dependencies ---
31/10/2023 12:08:04 INFO: Installing xorg-x11-fonts-100dpi.
31/10/2023 12:08:08 INFO: Installing xorg-x11-fonts-75dpi.
31/10/2023 12:08:13 INFO: Installing xorg-x11-utils.
31/10/2023 12:08:18 INFO: Installing xorg-x11-fonts-cyrillic.
31/10/2023 12:08:22 INFO: Installing xorg-x11-fonts-Type1.
31/10/2023 12:08:27 INFO: Installing xorg-x11-fonts-misc.
31/10/2023 12:08:33 INFO: Starting Wazuh dashboard installation.
31/10/2023 12:09:36 INFO: Wazuh dashboard installation finished.
31/10/2023 12:09:36 INFO: Wazuh dashboard post-install configuration finished.
31/10/2023 12:09:36 INFO: Starting service wazuh-dashboard.
31/10/2023 12:09:36 INFO: wazuh-dashboard service started.
31/10/2023 12:10:13 INFO: Initializing Wazuh dashboard web application.
31/10/2023 12:10:15 INFO: Wazuh dashboard web application initialized.
31/10/2023 12:10:15 INFO: --- Summary ---
31/10/2023 12:10:15 INFO: You can access the web interface https://<wazuh-dashboard-ip>:443
    User: admin
    Password: IUFV9an51uFrNAR?4Ztw8?Wh+99fT7Yz
31/10/2023 12:10:15 INFO: Installation finished.
```

</details>

<details>
<summary>Versions :green_circle:</summary>
<br>

```shell
[root@ip-172-31-68-32 ec2-user]# cat /usr/share/wazuh-indexer/VERSION
4.6.0
[root@ip-172-31-68-32 ec2-user]# cat /usr/share/wazuh-dashboard/VERSION
4.6.0
[root@ip-172-31-68-32 ec2-user]# /var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.6.0"
WAZUH_REVISION="40603"
WAZUH_TYPE="server"
```

</details>

**Comment by juliamagan** [comment]
## WPK upgrade test

<details>
<summary>macOS</summary>
<br>

The cache has been manually invalidated by @teddytpc1 due to https://github.com/wazuh/wazuh-jenkins/issues/5848

- Agent info:

```shell
sh-3.2# /Library/Ossec/bin/wazuh-control info
WAZUH_VERSION="v4.5.4"
WAZUH_REVISION="40510"
WAZUH_TYPE="agent"
```

- Agent info (in manager):

```shell
[root@ip-172-31-68-32 ec2-user]# /var/ossec/bin/agent_control -i 001

Wazuh agent_control. Agent information:
   Agent ID:   001
   Agent Name: macos-1201
   IP address: any
   Status:     Active

   Operating system:    Darwin |macos-1201 |21.1.0 |Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64 |x86_64
   Client version:      Wazuh v4.5.4
   Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
   Shared file hash:    4a8724b20dee0124ff9656783c490c4e
   Last keep alive:     1698754560

   Syscheck last started at:  Tue Oct 31 12:15:12 2023
   Syscheck last ended at:    Tue Oct 31 12:15:49 2023
```

- Agent update:

```

```

</details>

<details>
<summary>Linux :green_circle:</summary>
<br>

- Agent info:

```shell
root@test:/home/vagrant# /var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.5.4"
WAZUH_REVISION="40510"
WAZUH_TYPE="agent"
```

- Agent info (in manager):

```shell
root@test:/home/vagrant# /var/ossec/bin/agent_control -i 002

Wazuh agent_control. Agent information:
   Agent ID:   002
   Agent Name: ubuntu_agent
   IP address: any
   Status:     Active

   Operating system:    Linux |test |5.4.0-86-generic |#97-Ubuntu SMP Fri Sep 17 19:19:40 UTC 2021 |x86_64
   Client version:      Wazuh v4.5.4
   Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
   Shared file hash:    4a8724b20dee0124ff9656783c490c4e
   Last keep alive:     1698757116

   Syscheck last started at:  Tue Oct 31 12:54:28 2023
   Syscheck last ended at:    Tue Oct 31 12:54:33 2023
```

- Agent update:

```shell
root@test:/home/vagrant# /var/ossec/bin/agent_upgrade -a 002

Upgrading...

Upgraded agents:
	Agent 002 upgraded: Wazuh v4.5.4 -> Wazuh v4.6.0

```

- Agent info:

```shell
root@test:/home/vagrant# /var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.6.0"
WAZUH_REVISION="40603"
WAZUH_TYPE="agent"
```

- Agent info (in manager):

```shell
root@test:/home/vagrant# /var/ossec/bin/agent_control -i 002

Wazuh agent_control. Agent information:
   Agent ID:   002
   Agent Name: ubuntu_agent
   IP address: any
   Status:     Active

   Operating system:    Linux |test |5.4.0-86-generic |#97-Ubuntu SMP Fri Sep 17 19:19:40 UTC 2021 |x86_64
   Client version:      Wazuh v4.6.0
   Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
   Shared file hash:    4a8724b20dee0124ff9656783c490c4e
   Last keep alive:     1698757320

   Syscheck last started at:  Tue Oct 31 12:58:53 2023
   Syscheck last ended at:    Tue Oct 31 12:58:57 2023

```

</details>

<details>
<summary>Windows :green_circle:</summary>
<br>

- Agent info:
![version1](https://github.com/wazuh/wazuh-qa/assets/80041853/ad1b6515-13db-4c58-8aeb-bd3bc10c501f)

- Agent info (in manager):

```shell
root@test:/home/vagrant# /var/ossec/bin/agent_control -i 003

Wazuh agent_control. Agent information:
   Agent ID:   003
   Agent Name: WIN-JLGVA4CR4VI
   IP address: any
   Status:     Active

   Operating system:    Microsoft Windows Server 2019 Standard Evaluation
   Client version:      Wazuh v4.5.4
   Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
   Shared file hash:    4a8724b20dee0124ff9656783c490c4e
   Last keep alive:     1698757844

   Syscheck last started at:  Tue Oct 31 13:08:04 2023
   Syscheck last ended at:    Tue Oct 31 13:08:16 2023
```

- Agent update:

```shell
root@test:/home/vagrant# /var/ossec/bin/agent_upgrade -a 003

Upgrading...

Upgraded agents:
	Agent 003 upgraded: Wazuh v4.5.4 -> Wazuh v4.6.0
```

- Agent info:
![version2](https://github.com/wazuh/wazuh-qa/assets/80041853/48355255-55f2-431d-bf04-7d8780274ed4)

- Agent info (in manager):

```shell
root@test:/home/vagrant# /var/ossec/bin/agent_control -i 003

Wazuh agent_control. Agent information:
   Agent ID:   003
   Agent Name: WIN-JLGVA4CR4VI
   IP address: any
   Status:     Active

   Operating system:    Microsoft Windows Server 2019 Standard Evaluation
   Client version:      Wazuh v4.6.0
   Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
   Shared file hash:    4a8724b20dee0124ff9656783c490c4e
   Last keep alive:     1698757977

   Syscheck last started at:  Tue Oct 31 13:09:43 2023
   Syscheck last ended at:    Tue Oct 31 13:09:55 2023

```

</details>

**Comment by mauromalara** [comment]
LGTM!
