### ISSUE TITLE
Post release tasks for 4.6.0

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-qa#4662]
## Description
This issue attempts to track the steps necessary to complete post-release maintenance tasks for 4.6.0.
The goal is to complete the following tasks, each task must have a PR associated with this issue.

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, `merge-4.6.0-into-4.7.0`.

## Tasks

- [x] ~Merge branch `4.6.0` into branch `4.7.0`.~ https://github.com/wazuh/wazuh-qa/issues/4662#issuecomment-1787498809
- [x] Merge branch `4.7.0` into branch `4.7.1`. https://github.com/wazuh/wazuh-qa/pull/4664
- [x] Merge branch `4.7.1` into branch `4.8.0`. https://github.com/wazuh/wazuh-qa/pull/4669
- [x] Merge branch `4.8.0` into branch `master`. https://github.com/wazuh/wazuh-qa/pull/4670
- [x] Publish GitHub release as latest.
- [x] Delete all stage pre-releases for 4.6.0 (https://github.com/wazuh/wazuh-qa/releases).
- [x] Delete all stage tags for v4.6.0. **BE CAREFUL NOT TO DELETE DEFINITIVE TAG**. Example: v4.6.0-rc1, 4.6.0-alpha1, etc.
- [x] Delete branch `4.6.0`.

**Comment by juliamagan** [comment]
`4.7.0` has already been populated with latest 4.6.0 changes
```
commit dab08c4295646358f85907804b14d25603c5a5a3 (HEAD -> 4.6.0, tag: v4.6.0, origin/4.6.0)
Merge: 551f1b142 b6bd1d5b1
Author: Julia Magán <80041853+juliamagan@users.noreply.github.com>
Date:   Tue Oct 24 10:55:55 2023 +0200

    Merge pull request #4650 from wazuh/merge-4.5.4-into-4.6.0
    
    Merge 4.5.4 into 4.6.0
```
```
juliamagan@pop-os:~/wazuh-qa$ git checkout 4.7.0
Switched to branch '4.7.0'
Your branch is up to date with 'origin/4.7.0'.
juliamagan@pop-os:~/wazuh-qa$ git log | grep dab08c4295646358f85907804b14d25603c5a5a3
commit dab08c4295646358f85907804b14d25603c5a5a3
```

```
juliamagan@pop-os:~/wazuh-qa$ git log 4.7.0..4.6.0 --oneline > commits
juliamagan@pop-os:~/wazuh-qa$ cat commits
juliamagan@pop-os:~/wazuh-qa$ 
```

**Comment by damarisg** [comment]
LGTM!
