### ISSUE TITLE
FIM system tests: Create Jenkins pipeline to automate testing process

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh-qa#467]
### Objective

Our development process requires tasks to automate the deploy and testing process through Jenkins pipeline.

### Design

The main challenge here is to orchestrate all ansible playbooks to get what we want in only one pipeline.

### Tasks
- [x] Initialize Jenkins environment (Clone repositories).
- [x] Deploy all required hosts with Cloud Formation.
- [x] Provide and set up all hosts to testing process.
- [x] Launch required tests.
- [x] Show results in a intelligible way.
- [x] Destroy given environment.

### Tests
- [x] Deploy environment.
- [x] Destroy environment.
- [x] Provide hosts.
- [x] Launch tests.
- [x] Received data.
- [x] Data is published.

Regards.

**Comment by okynos** [comment]
Hello team,

We have approach many goals:
* We have done package building stage that build all required packages to install on deploy process. [L116-L156](https://github.com/wazuh/wazuh-jenkins/blob/qa467-system-tests/jenkins-files/tests/test_system.groovy#L116-L156)
* We have done the Cloud Formation deploy stage (Jenkins stage that deploy AWS EC2 instances and resources). [L162-L185](https://github.com/wazuh/wazuh-jenkins/blob/qa467-system-tests/jenkins-files/tests/test_system.groovy#L162-L185)
* Split generate inventory for provision [L190-L232](https://github.com/wazuh/wazuh-jenkins/blob/qa467-system-tests/jenkins-files/tests/test_system.groovy#L190-L232)
* Split setup provisioning stage from launch environment playbook [L236-L250](https://github.com/wazuh/wazuh-jenkins/blob/qa467-system-tests/jenkins-files/tests/test_system.groovy#L236-L250)
* Split setup instances stage from launch environment playbook [L254-L274](https://github.com/wazuh/wazuh-jenkins/blob/qa467-system-tests/jenkins-files/tests/test_system.groovy#L254-L274)
* Added stage to provision instances deployed with cloud formation [L278-L297](https://github.com/wazuh/wazuh-jenkins/blob/qa467-system-tests/jenkins-files/tests/test_system.groovy#L278-L297)
* Included stage to register Linux and Windows agents with master [L301-L320](https://github.com/wazuh/wazuh-jenkins/blob/qa467-system-tests/jenkins-files/tests/test_system.groovy#L301-L320)
* Launched stage to perform post installation tasks [L324-L338](https://github.com/wazuh/wazuh-jenkins/blob/qa467-system-tests/jenkins-files/tests/test_system.groovy#L324-L338)
* Set up stage to launch each scenario in a loop [L342-L355](https://github.com/wazuh/wazuh-jenkins/blob/qa467-system-tests/jenkins-files/tests/test_system.groovy#L342-L355)
* Added a stage to destroy environment in any circumstance [L359-L367](https://github.com/wazuh/wazuh-jenkins/blob/qa467-system-tests/jenkins-files/tests/test_system.groovy#L359-L367)

In addition to that we have added options inside Jenkins pipeline:
* Select what package to build.
* Selected commit.
* Number of scenarios and iterate over them.
* Elastic version selector.
* Branches selector.

We are working on set inside Ansible inventory the required options to install our custom packages through `wazuh-ansible` repository, anyway we still waiting for a working scenario to test the entire process.

Regards.

**Comment by jm404** [comment]
I've been launching the Pipeline with the scenarios created at #493 . I found some issues that required little changes:

- Don't stop Kibana and ES in the cleanup phase
- Change the ossec.conf scenario's files to include only the `syscheck` block & add a task to remove the old one
- Remove the task that copies the manager configuration file. The `ossec.conf` file generated by Ansible has precedence.

**Comment by jm404** [comment]
Hi all, let me summarize here some of the changes I applied:

- Add task to ensure every instance has been properly initialized: eb09eacdfb97075678ea9d2b78f7deac9b14ba83
- Update Ubuntu AMI (new one contains Python3.6 binary): ba4f2c6aee66c43bc538c518eacd1b8a32dfc7d2

- Added a task in the groovyfile to clear the `agents_output` files between executions:
 ```groovy
 dir(test_path){
          // Cleaning old scenario logs
          scenarios.tokenize(',').each{ scenario ->
            sh "ls -lah ./${scenario}/agents_outputs"
            sh "rm -rf ./${scenario}/agents_outputs"
          }
}
```

```

**Comment by jm404** [comment]
Hi team, during the execution I encountered that the sleep time and retries are really big, making a scenario spend a lot of time before finishing.

In order to fix it, I will decrease the sleep and retries to:

- Sleep: `30` seconds
- Retries: `3`
