### ISSUE TITLE
Migrate system framework

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#4702]
## Description

We were working for a while on a new framework for system tests in the [qa-system-framework](https://github.com/wazuh/qa-system-framework) repository, however, this framework is now required to be in this repository, so it is necessary to migrate it. This involves a few more tasks than simply moving it from one repository to another.

### Tasks

- [ ] Migrate system framework
- [ ] Solve conflicts with the current framework
- [ ] Adapt current system tests to this framework

**Comment by davidjiglesias** [comment]
To be done as part of QA migration, functionality testing tier 1
