### ISSUE TITLE
Support new stage RC 2 for 4.7.0 in wazuh-qa repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-qa#4707]
## Description

This issue attempts to support a new stage RC 2 for 4.7.0 in the wazuh-qa repository.

## Tasks

- [x] Ensure changelog is updated for 4.7.0 (if applicable).
- [x] Bump revision for branch 4.7.0 on wazuh-qa repository. https://github.com/wazuh/wazuh-qa/pull/4708
- [x] Create tag v4.7.0-rc2 from branch 4.7.0 on wazuh-qa repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-qa/releases/tag/v4.7.0-rc2.

**Comment by damarisg** [comment]
LGTM!
