### ISSUE TITLE
Compare generated files with the alerts at alerts.json file

### ISSUE THREAD

**Issue by Zenidd** [wazuh/wazuh-qa#471]
### Objective

Creating a mechanism to match generated files with its related alerts at alerts.json file.

### Tasks

- [x] Filename list elements parsing.
- [x] `alerts.json` alerts parsing.
- [x] Mode selector to switch the target among addition alerts, modification alerts or deletion alerts.

Syntax concept:

`./compareFiles filenames_list.txt /var/ossec/logs/alerts/alerts.json add`
`./compareFiles filenames_list.txt /var/ossec/logs/alerts/alerts.json modification`
`./compareFiles filenames_list.txt /var/ossec/logs/alerts/alerts.json deletion`

Greetings, 

JP Sáez
