### ISSUE TITLE
 Release automation design - Tier 1

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#4710]

**Comment by damarisg** [comment]
- [ ] Collect general information
- [ ] Identify the general process
- [ ] Planning
  - [ ] Create an initial draft 
  - [ ] Create a complete draft 
  - [ ] Identify the plan
  - [ ] Identify tasks

**Comment by damarisg** [comment]
# QA - Release Protocol: Phase 1

## Wazuh version: version synchronization

Description

This issue attempts to support a new stage for a specific version in the wazuh-qa repository.

Feature: Version Sync

       Scenario: Keep the change log up to date
         Given a version of Wazuh
         And a review of Wazuh
         And a Wazuh repository
         And a Wazuh branch
         When I go to the change log file
         Then the changelog file has with every version change of wazuh.

       Scenario: Review and version update
         Given a version of Wazuh
         And a review of Wazuh.
         And a Wazuh repository
         And a Wazuh branch
         When I go to the version file
         And I change the wazuh version
         And I change the wazuh review
         Then the version file is updated

       Scenario: Creating the version control tag
         Given a Wazuh repository
         And a Wazuh branch
         And a tag name
         When I create a tag name from Wazuh branch
         Then the label is created successfully

       Scenario: Creating release notes from the version control tag
         Given a version of Wazuh
         And a Wazuh repository
         And a Wazuh label
         When I create release notes as pre-release from the Wazuh tag
         Then the release note is created successfully

**Comment by damarisg** [comment]
# QA - Release Protocol: Phase 1

## Wazuh version: version synchronization

Support a new stage for a specific version in the wazuh-jenkins repository. 

> I define cases for the current state. However, I consider that:
> 
> - New Jenkins development should contain Changelog.
> - New Jenkins development should contain Review and Version. This will help keep libraries up to date without having to revert shared libraries.


**`Feature: Version Sync`**

**Comment by damarisg** [comment]
# QA - Release Protocol: Phase 1

## Wazuh version: version synchronization

`Feature: Version Sync`

       Scenario Outline: Report Version Sync
         Given a version of Wazuh
         And a Wazuh repository <repository_name>
         And a Wazuh branch
         And a Wazuh team <team_name>
         When I create an issue for <repository_name>
         And I run the <repository_name> script
         Then I see the <repository_name> script finish successfully
         And I see a message in the Slack channel with a report for each <team_name>
    
        Examples:
          | team_name| repository_name |
          | @wazuh/qa      | wazuh-qa|
          | @wazuh/qa | wazuh-jenkins |
          | @wazuh/cicd | wazuh-automation|
          | @wazuh/cicd     | wazuh-ansible|
          | @wazuh/cicd      | wazuh-docker |
          | @wazuh/cicd    |wazuh-puppet |
          | @wazuh/cicd     | wazuh-kubernetes|
          | @wazuh/frontend  | wazuh-dashboard-plugins|
          | @wazuh/framework    | qa-integration-framework|
          | @wazuh/documentation| wazuh-documentation |
          | @wazuh/core      | wazuh|
          | @wazuh/core     | wazuh-packages    |

**Comment by damarisg** [comment]
# QA - Release Protocol: Phase 1

## Wazuh version: version synchronization

Support a new stage for a specific version in the wazuh-qa repository.

**`Feature: Version Sync`**

       Scenario: Keep the change log up to date
         Given a version of Wazuh
         And a review of Wazuh
         And a Wazuh repository
         And a Wazuh branch
         When I go to the change log file
         Then the changelog file has with every version change of wazuh.

       Scenario: Review and version update
         Given a version of Wazuh
         And a review of Wazuh.
         And a Wazuh repository
         And a Wazuh branch
         When I go to the version file
         And I change the wazuh version
         And I change the wazuh review
         Then the version file is updated

       Scenario: Creating the version control tag
         Given a Wazuh repository
         And a Wazuh branch
         And a tag name
         When I create a tag name from Wazuh branch
         Then the label is created successfully

       Scenario: Creating release notes from the version control tag
         Given a version of Wazuh
         And a Wazuh repository
         And a Wazuh label
         When I create release notes as pre-release from the Wazuh tag
         Then the release note is created successfully

**Comment by damarisg** [comment]
# QA - Release Protocol: Phase 1

## Wazuh version: version synchronization

Support a new stage for a specific version in the wazuh-jenkins repository. 

> I define cases for the current state. However, I consider that:
> 
> - New Jenkins development should contain Changelog.
> - New Jenkins development should contain Review and Version. This will help keep libraries up to date without having to revert shared libraries.


**`Feature: Version Sync`**

    
      Scenario: Update the shared library 
        Given a Wazuh version tag
        And a Wazuh repository
        And a Wazuh branch
        When I modify the current version of the shared libraries to the new version
        Then I see the shared libraries with the new label.
         
    
      Scenario: Create the version tag
       Given a Wazuh repository
       And a Wazuh branch
       And a tag name
       When I create a tag name from Wazuh branch
       Then I see the tag created successfully.
         
    
      Scenario: Create release notes from the release tag
       Given a version of Wazuh
       And a Wazuh repository
       And a Wazuh tag
       When I create release notes as pre-release from the Wazuh tag
       Then I see the release note created successfully.
    
      
      Scenario: Roll back shared library with a specific version
       Given a tag version of Wazuh
       And a Wazuh repository
       And a Wazuh branch
       When I modify the new version of the shared libraries to the current version
       Then I see libraries shared with the previous version.

**Comment by damarisg** [comment]
# QA - Release Protocol: Phase 1

## Wazuh Packages: Creating Packages

> Recommendation:Task to executed sequentially.

Each task is in a new pipeline to release everything as a set, and if there are failures, the pipeline should stop and send a message to c-release reporting the new problem.

However, each subtask will consist of launching and reporting but the main task of building packages, images or verifying the checksum is another task that will be covered by another script or pipeline that needs to be defined.

`Feature: Buid packages`

**Comment by damarisg** [comment]
# QA - Release Protocol: Phase 1

## Wazuh Resources: Providing the Demo Environment
            
      Scenario: Create a demo environment
        Since I have a wazuh review.
        And I have a wazuh version
        When I set up the demo environment.
        Then I see the demo environment.
        And I see a message in the Slack channel with a report

**Comment by damarisg** [comment]
# QA - Release Protocol: Phase 1

## Wazuh Testing: Test Plan

  Scenario: Create a Test Plan
    Given I have a wazuh review
    And I have a wazuh version
    And I have wazuh team 
    When I execute the script to create issues
    Then I see issues created
    And I see a message in the Slack channel with a each issue assigned for each <team_wazuh> team.

**Comment by damarisg** [comment]
# CONCLUSION - Phase 1:

  > In this first investigation you can see a general idea of all the tasks that must be carried out.
  > 
  > After a call to sync, we'll add whatever details we decide to get started.
  > 
  > Currently, Phase 1 has been added with general cases that the QA team should start working on.
