### ISSUE TITLE
Publish release 4.7.0

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-qa#4718]
## Description
This issue attempts to track the steps necessary to publish packages, OVA, AMI, docker images, and puppet forge for 4.7.0.

## Tasks
- [x] Send AMI to analysis. https://aws.amazon.com/marketplace/management/manage-products/?#/ami-05b6aef225bd47376/details
- [x] Launch [`Publish_release`](https://ci.wazuh.info/job/Publish_release) pipeline. https://ci.wazuh.info/job/Publish_release/376/
- [x] Upload latest Filebeat version.
- [x] Build and release debug packages.
- [x] Build and push [Docker Hub images](https://ci.wazuh.info/job/procedure_push_docker_images). https://ci.wazuh.info/job/procedure_push_docker_images/105/
- [x] Publish AMI. https://aws.amazon.com/marketplace/management/requests/943n5igcluhodkann1wge96r9

**Comment by pro-akim** [comment]
## Review Notes
LGTM
