### ISSUE TITLE
Post publication live checks for 4.7.0

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-qa#4719]
## Description
This issue attempts to ensure the publication process was correct, attempting checks and live tests for published packages and images.

## Tasks
- [x] Ensure that production files are present.
- [x] Deploy the `Wazuh Installation Assistant` and check the version installed is 4.7.0. 
  - https://github.com/wazuh/wazuh-qa/issues/4719#issuecomment-1827828715
- [x] [AMD64 Live installation test](https://ci.wazuh.info/job/Test_install_tier).
  - https://ci.wazuh.info/job/Test_install_tier/786/
  - https://ci.wazuh.info/job/Test_install/146848/ (macOS test failed in the deployment)
- [x] WPK versions check.
- [x] WPK upgrade test.
  - [x] Linux
  - [x] MacOS Intel
  - [x] Windows
- [x] [AMI published](https://aws.amazon.com/marketplace/pp/prodview-eju4flv5eqmgq).
- [x] [Puppet forge module published](https://forge.puppet.com/modules/wazuh/wazuh/readme).
- [x] [Docker images published](https://hub.docker.com/u/wazuh).

**Comment by juliamagan** [comment]
### WIA

**Comment by juliamagan** [comment]
## WPK upgrade test

<details>
<summary>Linux</summary>
<br>


</details>

**Comment by pro-akim** [comment]
## Review Notes
LGTM

**Comment by davidjiglesias** [comment]
LGTM!
