### ISSUE TITLE
Support new stage RC 1 for 4.7.1 in wazuh-qa repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-qa#4722]
## Description

This issue attempts to support a new stage RC 1 for 4.7.1 in the wazuh-qa repository.

## Tasks

- [x] Ensure changelog is updated for 4.7.1 (if applicable). https://github.com/wazuh/wazuh-qa/pull/4723
- [x] Bump revision for branch 4.7.1 on wazuh-qa repository. https://github.com/wazuh/wazuh-qa/pull/4724
- [x] Create tag v4.7.1-rc1 from branch 4.7.1 on wazuh-qa repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-qa/releases/tag/v4.7.1-rc1.

**Comment by pro-akim** [comment]
## Review Notes
LGTM
