### ISSUE TITLE
DTT1 - Iteration 2 - Test module

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/wazuh-qa#4750]
> Epic: https://github.com/wazuh/wazuh-qa/issues/4495

---

## Description

This issue aims to englobe all the subtasks required for the completion of the DTT1 Test module

### Subtasks

- [x] Create a class to handles the data validation and test execution
- [x] Update launcher script to use the new class
- [x] Update tests to match the requirements

**Comment by QU3B1M** [comment]
## Update report

- Add InputPayload model to validate the required payload for the tests execution
- Update the test launcher moving several responsibilities to a Tester class
```python
```
- Create Tester class to handle the test playbooks execution and data validation

**Comment by QU3B1M** [comment]
## Update report

- Create generic test template to render with Jinja2
  ```yml
  - hosts: all
    become: true
    tasks:
      - name: Clone tests into the endpoint
        block:
        - name: Create test directory
          file:
            path: "{{ working_dir }}"
            state: directory
        - name: Copy files to endpoints
          copy:
            src: "{{ local_path }}/"
            dest: "{{ working_dir }}"
  
  ```
- Update Tester class to correctly run the setup, test and cleanup playbooks
  ```python
  from pathlib import Path
  
  from modules.generic import Playbook, Ansible, Inventory
  from modules.generic.utils import Utils
  
  from .models import InputPayload, ExtraVars
  
  
  class Tester:
      _playbooks_dir = Playbook.PLAYBOOKS_PATH / 'tests'
      _test_playbook = str(_playbooks_dir / 'test.yml')
      _setup_playbook = str(_playbooks_dir / 'setup.yml')
      _cleanup_playbook = str(_playbooks_dir / 'cleanup.yml')
  
      @classmethod
      def run(cls, payload: InputPayload) -> None:
          payload = InputPayload(**dict(payload))
          inventory = Inventory(**Utils.load_from_yaml(payload.inventory))
          extra_vars = cls._get_extra_vars(payload)
          ansible = Ansible(ansible_data=inventory.model_dump())
          cls._setup(ansible, extra_vars.working_dir)
          cls._run_tests(payload.tests, ansible, extra_vars)
          if payload.cleanup:
              cls._cleanup(ansible, extra_vars.working_dir)
  
      @classmethod
      def _get_extra_vars(cls, payload: InputPayload) -> ExtraVars:
          if not payload.dependency:
              return ExtraVars(**payload.model_dump())
  
          dep_inventory = Inventory(**Utils.load_from_yaml(payload.dependency))
          dep_ip = dep_inventory.ansible_host
          return ExtraVars(**payload.model_dump(exclude={'dependency'}), dependency=dep_ip)
  
      @classmethod
      def _run_tests(cls, test_list: list[str], ansible: Ansible, extra_vars: ExtraVars) -> None:
          # Run tests playbooks
          for test in test_list:
              rendering_vars = {**dict(extra_vars), 'test': test}
              playbook = ansible.render_playbook(cls._test_playbook, rendering_vars)
              if not playbook:
                  print(f'ERROR: Playbook for test "{test}" not found')
                  continue
              ansible.run_playbook(playbook)
  
      @classmethod
      def _setup(cls, ansible: Ansible, remote_working_dir: str = '/tmp') -> None:
          extra_vars = {'local_path': str(Path(__file__).parent / 'tests'),
                        'working_dir': remote_working_dir}
          ansible.run_playbook(cls._setup_playbook, extra_vars)
  
      @classmethod
      def _cleanup(cls, ansible: Ansible, remote_working_dir: str = '/tmp') -> None:
          extra_vars = {'working_dir': remote_working_dir}
          ansible.run_playbook(cls._cleanup_playbook, extra_vars)
  
  ```
- Add test task to workflow

**Comment by fcaffieri** [comment]
### Review

We need to fix the following test error:

- test_agent_connection_status
- test_agent_register
- test_wazuh_revision (basic info)
- test uninstall

**Comment by fcaffieri** [comment]
LGTM

Improvements and implementations were noted for the next iteration:

1. Add Utils to test using the Wazuh API
2. Add Utils to check all file permissions and ownership
3. Add a test for the manager
4. Test uninstall
5. Remove the usage of the Playbook class to use just Ansible
