### ISSUE TITLE
Support new stage RC 2 for 4.7.1 in wazuh-qa repository

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#4753]
## Description

This issue attempts to support a new stage RC 2 for 4.7.1 in the wazuh-qa repository.

## Tasks

- [x] Ensure the changelog is updated for 4.7.1 (if applicable). https://github.com/wazuh/wazuh-qa/pull/4755
- [x] Bump revision for branch 4.7.1 on wazuh-qa repository. https://github.com/wazuh/wazuh-qa/pull/4756
- [x] Create tag v4.7.1-rc2 from branch 4.7.1 on wazuh-qa repository:
  - [x] `git tag -s -m "v4.7.1-rc2" v4.7.1-rc2 4.7.1`
  - [x] `git push origin v4.7.1-rc2`
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-qa/releases/tag/v4.7.1-rc2.

**Comment by QU3B1M** [comment]
LGTM!
