### ISSUE TITLE
 Support new stage RC 2 for 4.7.1 in wazuh-jenkins repository  

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#4754]
## Description

This issue attempts to support a new stage RC 2 for 4.7.1 in the wazuh-jenkins repository.

## Tasks

- [ ] Ensure changelog is updated for 4.7.1 (if applicable).
- [ ] Bump revision for branch 4.7.1 on wazuh-jenkins repository.
- [ ] Change shared libraries to tag v4.7.1-rc2in branch 4.7.1
- [ ] Create tag v4.7.1-rc2from branch 4.7.1 on wazuh-jenkins repository.
- [ ] Create and publish a pre-release: https://github.com/wazuh/wazuh-jenkins/releases/tag/v4.7.1-rc2.
- [ ] Change shared libraries back to 4.7.1 in branch 4.7.1
