### ISSUE TITLE
Support new stage RC 3 for 4.7.1 in wazuh-qa repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-qa#4768]
## Description

This issue attempts to support a new stage RC 3 for 4.7.1 in the wazuh-qa repository.

## Tasks

- [x] Ensure changelog is updated for 4.7.1 (if applicable).
  - Not needed, latest 4.7.1 commit match the latest v4.7.1-rc2 commit 
  - https://github.com/wazuh/wazuh-qa/compare/4.7.1..v4.7.1-rc2
  - https://github.com/wazuh/wazuh-qa/compare/v4.7.1-rc2..4.7.1
- [x] Bump revision for branch 4.7.1 on wazuh-qa repository.
  - https://github.com/wazuh/wazuh-qa/pull/4769
- [x] Create tag v4.7.1-rc3 from branch 4.7.1 on wazuh-qa repository.
  - https://github.com/wazuh/wazuh-qa/tree/v4.7.1-rc3
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-qa/releases/tag/v4.7.1-rc3.

**Comment by damarisg** [comment]
LGTM!
