### ISSUE TITLE
Update Vulnerability Detector Configuration and Disable Local Tests

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh-qa#4771]
**Description:**

This issue focuses on updating the configuration of the Vulnerability Detector and Indexer within the Wazuh project. The new configurations are provided in the following links:

- [wodle-indexer.manager.template](https://github.com/wazuh/wazuh/blob/dev-14153-vulndet-refactor/etc/templates/config/generic/wodle-indexer.manager.template)
- [wodle-vulnerability-detection.manager.template](https://github.com/wazuh/wazuh/blob/dev-14153-vulndet-refactor/etc/templates/config/generic/wodle-vulnerability-detection.manager.template)

Additionally, this issue involves the deactivation of any local tests within this repository. These tests will be executed in the Wazuh repository.

**User Stories:**

- As a developer, I want to ensure that the Vulnerability Detector and Indexer configurations are up to date.
- As a developer, I want to disable local tests in this repository to avoid redundancy with the Wazuh repository.

**Tasks:**

1. Configuration Update:
   - Retrieve the new configurations from the provided links.
   - Replace the old configurations in this repository with the updated ones.

2. Disable Local Tests:
   - Identify and deactivate any local tests within this repository.
   - Provide instructions or updates in the repository's documentation regarding the removal of local tests.

**Definition of Done:**

- The Vulnerability Detector and Indexer configurations have been successfully updated in this repository.
- Local tests, if present, have been disabled, and documentation reflects this change.
- Testing confirms that the updated configurations do not introduce issues.

**Related Issues:**
TBD

**Comment by mauromalara** [comment]
## Update

After checking our repositories, I've concluded that we've to do the following to achieve the proposed objectives:

- [ ] Update tests in `wazuh/wazuh` with the new configuration
- [ ] Update tests in `wazuh/wazuh-jenkins` with the new configuration
- [ ] Deactivate tests in `wazuh/wazuh-qa`
- [ ] Remove execution of tests in `wazuh/wazuh-jenkins` (Wazuh PR, Nightly, etc.) [TBD]

**Comment by mauromalara** [comment]
## Task: Update tests in `wazuh/wazuh-jenkins` with the new configuration

### Affected tests

- Stress tests
- Service tests

As the following tests will fail because they need to be refactored to deploy/provision a Wazuh Indexer instance. We'll disable the `<indexer>` configuration and create an issue to refactor the tests to add the publication functionality.

**Comment by mauromalara** [comment]
## Task: Update tests in `wazuh/wazuh` with the new configuration

### Affected tests

- Integration tests

The following tests will fail because they need to be refactored to deploy/provision a Wazuh Indexer instance. We'll disable the <indexer> configuration.

**Comment by mauromalara** [comment]
## Update

- https://github.com/wazuh/wazuh/issues/20933: The merge from `4.7.2` to `4.8.0` was done so I can continue my task.
- The packages were built successfully https://ci.wazuh.info/job/Packages_builder_tier/3337/ except for: Alpine (wrong revision), and Manager ARM (Task Definition failed)

**Comment by mauromalara** [comment]
## Update

An error was found in `Test_service` during testing. But they seem not related to the development: https://github.com/wazuh/wazuh-qa/pull/4784

**Comment by Rebits** [comment]
The objective of the issue is not clear enough. It is not clear if it necessarily to perform the upgrade of the vulnerability detector configuration in this repo or in all the organization repos

> This issue focuses on updating the configuration of the Vulnerability Detector and Indexer within the Wazuh project. The new configurations are provided in the following links:

> Replace the old configurations in this repository with the updated ones.

> The Vulnerability Detector and Indexer configurations have been successfully updated in this repository.

***

> Identify and deactivate any local tests within this repository.

Some questions regarding this task
- Why deactivate tests that will no longer be effective?
- What means local tests in this context? Vulnerability Detector integration/E2E/System tests?

**Comment by jnasselle** [comment]
Reviewing https://github.com/wazuh/wazuh-qa/pull/4784 and https://github.com/wazuh/wazuh-jenkins/pull/6094
