### ISSUE TITLE
Publish release 4.7.1

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-qa#4777]
## Description
This issue attempts to track the steps necessary to publish packages, OVA, AMI, docker images, and puppet forge for 4.7.1.

## Tasks
- [x] Send AMI to analysis.
  - https://aws.amazon.com/marketplace/management/manage-products/#/ami-0566980733a8774f2/details
- [x] Launch [`Publish_release`](https://ci.wazuh.info/job/Publish_release) pipeline.
  - https://ci.wazuh.info/job/Publish_release/377/
- [x] ~Upload latest Filebeat version.~
- [x] Build and release debug packages.
- [x] Build and push [Docker Hub images](https://ci.wazuh.info/job/procedure_push_docker_images).
  - https://ci.wazuh.info/job/procedure_push_docker_images/114/
- [x] Publish AMI.
  - https://aws.amazon.com/marketplace/management/requests/3ob13y5on5bf54l8ql3j22nup
  
More steps in https://github.com/wazuh/wazuh-qa/issues/4777#issuecomment-1862543295

**Comment by juliamagan** [comment]
The following tasks must be completed in order:

- [ ] Copy all 4.8.0  packages (packages, debug-packages, checksums, versions) to another directory outside of pre-release
- [ ] Remove  4.8.0 files
  - [ ] pre-debug
  - [ ] pre-release
- [ ] Modify WPK versions (Linux,macOS, Windows) to remove 4.8.0 and upload it again
  - [ ] Ensure that the versions files are publicly available
- [ ] Launch Publish_release without unattended
- [ ] Send AMI to analysis
  - AMI analysis request: 
- [ ] Wait for the Publish_release pipeline to finish
- [ ] Launch unattended
- [ ] Publish AMI
- [ ] Publish pre-debug packages

**Comment by juliamagan** [comment]
We are starting again, after the research carried out at https://github.com/wazuh/wazuh-jenkins/issues/6086.

### Tasks

- [ ] Copy all 4.8.0  packages (packages, debug-packages, checksums, versions) to another directory outside of pre-release
  - https://s3.console.aws.amazon.com/s3/buckets/packages-dev.wazuh.com?region=us-west-1&prefix=pre-backup/
- [ ] Remove  4.8.0 files
  - [ ] pre-debug
  - [ ] pre-release
- [ ] Modify WPK versions (Linux,macOS, Windows) to remove 4.8.0 and upload it again
  - [ ] Ensure that the versions files are publicly available
- [ ] Launch Publish_release without unattended
  - https://ci.wazuh.info/job/Publish_release/377/
- [ ] Send AMI to analysis
  - AMI analysis request: https://aws.amazon.com/marketplace/management/manage-products/#/ami-0566980733a8774f2/details
- [ ] Wait for the Publish_release pipeline to finish
- [ ] Launch unattended
  - https://ci.wazuh.info/view/Releases/job/publish_unattended/219/
- [ ] Publish AMI
  - https://aws.amazon.com/marketplace/management/requests/3ob13y5on5bf54l8ql3j22nup
- [ ] Publish pre-debug packages

**Comment by fcaffieri** [comment]
### Update

Debug packages OK

![image](https://github.com/wazuh/wazuh-qa/assets/89791732/bcadfe45-6b26-4e85-b6eb-33dfafdd0758)

![image](https://github.com/wazuh/wazuh-qa/assets/89791732/f4c649ee-7918-4dc6-89b0-56ac6f66ab60)

**Comment by davidjiglesias** [comment]
LGTM
