### ISSUE TITLE
Post publication live checks for 4.7.1

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-qa#4778]
## Description
This issue attempts to ensure the publication process was correct, attempting checks and live tests for published packages and images.

## Tasks
- [x] Ensure that production files are present.
- [x] Deploy the `Wazuh Installation Assistant` and check the version installed is 4.7.1.
- [x] [AMD64 Live installation test](https://ci.wazuh.info/job/Test_install_tier).
  - https://ci.wazuh.info/job/Test_install_tier/823/
- [x] WPK versions check.
- [x] WPK upgrade test.
  - [x] Linux
  - [x] MacOS Intel
  - [x] Windows
- [x] [AMI published](https://aws.amazon.com/marketplace/pp/prodview-eju4flv5eqmgq).
- [x] [Puppet forge module published](https://forge.puppet.com/modules/wazuh/wazuh/readme).
- [x] [Docker images published](https://hub.docker.com/u/wazuh) and README updated.

**Comment by rauldpm** [comment]
## Wazuh installation assistant check

```
[root@centos7 vagrant]# curl -sO https://packages.wazuh.com/4.7/wazuh-install.sh && sudo bash ./wazuh-install.sh -a
19/12/2023 14:18:22 INFO: Starting Wazuh installation assistant. Wazuh version: 4.7.1
19/12/2023 14:18:22 INFO: Verbose logging redirected to /var/log/wazuh-install.log
19/12/2023 14:18:27 INFO: --- Dependencies ---
19/12/2023 14:18:27 INFO: Installing lsof.
19/12/2023 14:18:33 INFO: Wazuh web interface port will be 443.
19/12/2023 14:18:34 INFO: Wazuh repository added.
19/12/2023 14:18:34 INFO: --- Configuration files ---
19/12/2023 14:18:34 INFO: Generating configuration files.
19/12/2023 14:18:34 INFO: Created wazuh-install-files.tar. It contains the Wazuh cluster key, certificates, and passwords necessary for installation.
19/12/2023 14:18:34 INFO: --- Wazuh indexer ---
19/12/2023 14:18:34 INFO: Starting Wazuh indexer installation.
19/12/2023 14:19:18 INFO: Wazuh indexer installation finished.
19/12/2023 14:19:18 INFO: Wazuh indexer post-install configuration finished.
19/12/2023 14:19:18 INFO: Starting service wazuh-indexer.
19/12/2023 14:19:25 INFO: wazuh-indexer service started.
19/12/2023 14:19:25 INFO: Initializing Wazuh indexer cluster security settings.
19/12/2023 14:19:35 INFO: Wazuh indexer cluster initialized.
19/12/2023 14:19:35 INFO: --- Wazuh server ---
19/12/2023 14:19:35 INFO: Starting the Wazuh manager installation.
19/12/2023 14:19:58 INFO: Wazuh manager installation finished.
19/12/2023 14:19:58 INFO: Starting service wazuh-manager.
19/12/2023 14:20:09 INFO: wazuh-manager service started.
19/12/2023 14:20:09 INFO: Starting Filebeat installation.
19/12/2023 14:20:12 INFO: Filebeat installation finished.
19/12/2023 14:20:13 INFO: Filebeat post-install configuration finished.
19/12/2023 14:20:13 INFO: Starting service filebeat.
19/12/2023 14:20:13 INFO: filebeat service started.
19/12/2023 14:20:13 INFO: --- Wazuh dashboard ---
19/12/2023 14:20:13 INFO: Starting Wazuh dashboard installation.
19/12/2023 14:20:53 INFO: Wazuh dashboard installation finished.
19/12/2023 14:20:53 INFO: Wazuh dashboard post-install configuration finished.
19/12/2023 14:20:53 INFO: Starting service wazuh-dashboard.
19/12/2023 14:20:53 INFO: wazuh-dashboard service started.
19/12/2023 14:21:08 INFO: Initializing Wazuh dashboard web application.
19/12/2023 14:21:09 INFO: Wazuh dashboard web application initialized.
19/12/2023 14:21:09 INFO: --- Summary ---
19/12/2023 14:21:09 INFO: You can access the web interface https://<wazuh-dashboard-ip>:443
    User: admin
    Password: gEw?v6U95576MwL+MCS923CldwlhWX.G
19/12/2023 14:21:09 INFO: Installation finished.
[root@centos7 vagrant]# cat /usr/share/wazuh-indexer/VERSION 
4.7.1
[root@centos7 vagrant]# cat /usr/share/wazuh-dashboard/VERSION 
4.7.1
[root@centos7 vagrant]# /var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.7.1"
WAZUH_REVISION="40709"
WAZUH_TYPE="server"
```

![image](https://github.com/wazuh/wazuh-qa/assets/14913942/0be3f2ff-8657-4005-b345-c36526b4d149)

**Comment by juliamagan** [comment]
## WPK upgrade test

<details>
<summary>Linux :green_circle:</summary>
<br>

- Agent info:

```shell
root@test:/home/vagrant# /var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.7.0"
WAZUH_REVISION="40704"
WAZUH_TYPE="agent"
```

- Agent info (in manager):

```shell
root@test:/home/vagrant# /var/ossec/bin/agent_control -i 001

Wazuh agent_control. Agent information:
   Agent ID:   001
   Agent Name: ubuntu_agent
   IP address: any
   Status:     Active

   Operating system:    Linux |test |5.4.0-86-generic |#97-Ubuntu SMP Fri Sep 17 19:19:40 UTC 2021 |x86_64
   Client version:      Wazuh v4.7.0
   Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
   Shared file hash:    4a8724b20dee0124ff9656783c490c4e
   Last keep alive:     1702996368

   Syscheck last started at:  Tue Dec 19 14:32:48 2023
   Syscheck last ended at:    Tue Dec 19 14:32:52 2023
```

- Agent update:

```shell
root@test:/home/vagrant# /var/ossec/bin/agent_upgrade -a 001

Upgrading...

Upgraded agents:
	Agent 001 upgraded: Wazuh v4.7.0 -> Wazuh v4.7.1
```

- Agent info:

```shell
root@test:/home/vagrant# /var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.7.1"
WAZUH_REVISION="40709"
WAZUH_TYPE="agent"
```

- Agent info (in manager):

```shell
root@test:/home/vagrant# /var/ossec/bin/agent_control -i 001

Wazuh agent_control. Agent information:
   Agent ID:   001
   Agent Name: ubuntu_agent
   IP address: any
   Status:     Active

   Operating system:    Linux |test |5.4.0-86-generic |#97-Ubuntu SMP Fri Sep 17 19:19:40 UTC 2021 |x86_64
   Client version:      Wazuh v4.7.1
   Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
   Shared file hash:    4a8724b20dee0124ff9656783c490c4e
   Last keep alive:     1702996610

   Syscheck last started at:  Tue Dec 19 14:35:59 2023
   Syscheck last ended at:    Tue Dec 19 14:36:04 2023

```

</details>

**Comment by rauldpm** [comment]
## WPK upgrade test - macOS

<details><summary>Wazuh manager</summary>

```
[root@centos7 vagrant]# /var/ossec/bin/agent_control -i 001

Wazuh agent_control. Agent information:
   Agent ID:   001
   Agent Name: This-MacBook-Pro.local
   IP address: any
   Status:     Active

   Operating system:    Darwin |This-MacBook-Pro.local |16.7.0 |Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 |x86_64
   Client version:      Wazuh v4.6.0
   Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
   Shared file hash:    4a8724b20dee0124ff9656783c490c4e
   Last keep alive:     1702996652

   Syscheck last started at:  Tue Dec 19 14:36:32 2023
   Syscheck last ended at:    Tue Dec 19 14:36:56 2023

[root@centos7 vagrant]# /var/ossec/bin/agent_upgrade -a 001

Upgrading...

Upgraded agents:
	Agent 001 upgraded: Wazuh v4.6.0 -> Wazuh v4.7.1


[root@centos7 vagrant]# /var/ossec/bin/agent_control -i 001

Wazuh agent_control. Agent information:
   Agent ID:   001
   Agent Name: This-MacBook-Pro.local
   IP address: any
   Status:     Active

   Operating system:    Darwin |This-MacBook-Pro.local |16.7.0 |Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 |x86_64
   Client version:      Wazuh v4.7.1
   Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
   Shared file hash:    4a8724b20dee0124ff9656783c490c4e
   Last keep alive:     1702997229

   Syscheck last started at:  Tue Dec 19 14:46:20 2023
   Syscheck last ended at:    Tue Dec 19 14:46:23 2023
```

</details>

<details><summary>Wazuh agent</summary>

```
sh-3.2# curl -sO https://packages.wazuh.com/4.x/macos/wazuh-agent-4.6.0-1.intel64.pkg
sh-3.2# echo "WAZUH_MANAGER='192.168.56.4'" > /tmp/wazuh_envs && installer -pkg wazuh-agent-4.6.0-1.intel64.pkg -target /
installer: Package name is Wazuh Agent
installer: Installing at base path /
installer: The install was successful.
sh-3.2# /Library/Ossec/bin/wazuh-control start
Starting Wazuh v4.6.0...
Started wazuh-execd...
Started wazuh-agentd...
Started wazuh-syscheckd...
Started wazuh-logcollector...
Started wazuh-modulesd...
Completed.
sh-3.2# /Library/Ossec/bin/wazuh-control info
WAZUH_VERSION="v4.6.0"
WAZUH_REVISION="40603"
WAZUH_TYPE="agent"


sh-3.2# /Library/Ossec/bin/wazuh-control info
WAZUH_VERSION="v4.7.1"
WAZUH_REVISION="40709"
WAZUH_TYPE="agent"
```

```
sh-3.2# cat /Library/Ossec/logs/upgrade.log 
2023/12/19 06:46:12 - Generating Backup.
tar: Removing leading '/' from member names
a Library/Ossec/active-response
a Library/Ossec/active-response/bin
a Library/Ossec/active-response/bin/default-firewall-drop
a Library/Ossec/active-response/bin/disable-account
a Library/Ossec/active-response/bin/firewall-drop
a Library/Ossec/active-response/bin/firewalld-drop
a Library/Ossec/active-response/bin/host-deny
a Library/Ossec/active-response/bin/ip-customblock
a Library/Ossec/active-response/bin/ipfw
a Library/Ossec/active-response/bin/kaspersky
a Library/Ossec/active-response/bin/kaspersky.py
a Library/Ossec/active-response/bin/npf
a Library/Ossec/active-response/bin/pf
a Library/Ossec/active-response/bin/restart-wazuh
a Library/Ossec/active-response/bin/restart.sh
a Library/Ossec/active-response/bin/route-null
a Library/Ossec/active-response/bin/wazuh-slack
a Library/Ossec/bin
a Library/Ossec/bin/agent-auth
a Library/Ossec/bin/manage_agents
a Library/Ossec/bin/wazuh-agentd
a Library/Ossec/bin/wazuh-control
a Library/Ossec/bin/wazuh-execd
a Library/Ossec/bin/wazuh-logcollector
a Library/Ossec/bin/wazuh-modulesd
a Library/Ossec/bin/wazuh-syscheckd
a Library/Ossec/etc
a Library/Ossec/etc/client.keys
a Library/Ossec/etc/internal_options.conf
a Library/Ossec/etc/local_internal_options.conf
a Library/Ossec/etc/localtime
a Library/Ossec/etc/ossec.conf
a Library/Ossec/etc/shared
a Library/Ossec/etc/wpk_root.pem
a Library/Ossec/etc/shared/agent.conf
a Library/Ossec/etc/shared/ar.conf
a Library/Ossec/etc/shared/cis_apache2224_rcl.txt
a Library/Ossec/etc/shared/cis_debian_linux_rcl.txt
a Library/Ossec/etc/shared/cis_mysql5-6_community_rcl.txt
a Library/Ossec/etc/shared/cis_mysql5-6_enterprise_rcl.txt
a Library/Ossec/etc/shared/cis_rhel5_linux_rcl.txt
a Library/Ossec/etc/shared/cis_rhel6_linux_rcl.txt
a Library/Ossec/etc/shared/cis_rhel7_linux_rcl.txt
a Library/Ossec/etc/shared/cis_rhel_linux_rcl.txt
a Library/Ossec/etc/shared/cis_sles11_linux_rcl.txt
a Library/Ossec/etc/shared/cis_sles12_linux_rcl.txt
a Library/Ossec/etc/shared/cis_win2012r2_domainL1_rcl.txt
a Library/Ossec/etc/shared/cis_win2012r2_domainL2_rcl.txt
a Library/Ossec/etc/shared/cis_win2012r2_memberL1_rcl.txt
a Library/Ossec/etc/shared/cis_win2012r2_memberL2_rcl.txt
a Library/Ossec/etc/shared/merged.mg
a Library/Ossec/etc/shared/rootkit_files.txt
a Library/Ossec/etc/shared/rootkit_trojans.txt
a Library/Ossec/etc/shared/system_audit_rcl.txt
a Library/Ossec/etc/shared/system_audit_ssh.txt
a Library/Ossec/etc/shared/win_applications_rcl.txt
a Library/Ossec/etc/shared/win_audit_rcl.txt
a Library/Ossec/etc/shared/win_malware_rcl.txt
a Library/Ossec/lib
a Library/Ossec/lib/libdbsync.dylib
a Library/Ossec/lib/libfimdb.dylib
a Library/Ossec/lib/librsync.dylib
a Library/Ossec/lib/libsyscollector.dylib
a Library/Ossec/lib/libsysinfo.dylib
a Library/Ossec/lib/libwazuhext.dylib
a Library/Ossec/lib/libwazuhshared.dylib
a Library/Ossec/queue
a Library/Ossec/queue/alerts
a Library/Ossec/queue/fim
a Library/Ossec/queue/logcollector
a Library/Ossec/queue/rids
a Library/Ossec/queue/sockets
a Library/Ossec/queue/syscollector
a Library/Ossec/queue/syscollector/db
a Library/Ossec/queue/syscollector/norm_config.json
a Library/Ossec/queue/syscollector/db/local.db
a Library/Ossec/queue/syscollector/db/local.db-journal
a Library/Ossec/queue/sockets/.agent_info
a Library/Ossec/queue/sockets/com: tar format cannot archive socket
a Library/Ossec/queue/sockets/control: tar format cannot archive socket
a Library/Ossec/queue/sockets/logcollector: tar format cannot archive socket
a Library/Ossec/queue/sockets/queue: tar format cannot archive socket
a Library/Ossec/queue/sockets/syscheck: tar format cannot archive socket
a Library/Ossec/queue/sockets/upgrade: tar format cannot archive socket
a Library/Ossec/queue/sockets/wmodules: tar format cannot archive socket
a Library/Ossec/queue/rids/001
a Library/Ossec/queue/rids/sender_counter
a Library/Ossec/queue/fim/db
a Library/Ossec/queue/fim/db/fim.db
a Library/Ossec/queue/fim/db/fim.db-journal
a Library/Ossec/queue/alerts/cfgaq: tar format cannot archive socket
a Library/Ossec/queue/alerts/execq: tar format cannot archive socket
a Library/Ossec/ruleset
a Library/Ossec/ruleset/sca
a Library/Ossec/ruleset/sca/cis_apple_macOS_10.12.yml
a Library/Ossec/wodles
a Library/Ossec/wodles/__init__.py
a Library/Ossec/wodles/aws
a Library/Ossec/wodles/azure
a Library/Ossec/wodles/docker
a Library/Ossec/wodles/gcloud
a Library/Ossec/wodles/utils.py
a Library/Ossec/wodles/gcloud/buckets
a Library/Ossec/wodles/gcloud/exceptions.py
a Library/Ossec/wodles/gcloud/gcloud
a Library/Ossec/wodles/gcloud/integration.py
a Library/Ossec/wodles/gcloud/pubsub
a Library/Ossec/wodles/gcloud/tools.py
a Library/Ossec/wodles/gcloud/pubsub/subscriber.py
a Library/Ossec/wodles/gcloud/buckets/access_logs.py
a Library/Ossec/wodles/gcloud/buckets/bucket.py
a Library/Ossec/wodles/docker/DockerListener
a Library/Ossec/wodles/azure/azure-logs
a Library/Ossec/wodles/azure/orm.py
a Library/Ossec/wodles/aws/aws-s3
a Library/Ossec/agentless
a Library/Ossec/agentless/main.exp
a Library/Ossec/agentless/register_host.sh
a Library/Ossec/agentless/ssh.exp
a Library/Ossec/agentless/ssh_asa-fwsmconfig_diff
a Library/Ossec/agentless/ssh_foundry_diff
a Library/Ossec/agentless/ssh_generic_diff
a Library/Ossec/agentless/ssh_integrity_check_bsd
a Library/Ossec/agentless/ssh_integrity_check_linux
a Library/Ossec/agentless/ssh_nopass.exp
a Library/Ossec/agentless/ssh_pixconfig_diff
a Library/Ossec/agentless/sshlogin.exp
a Library/Ossec/agentless/su.exp
a Library/Ossec/logs/wazuh
a Library/Ossec/var/selinux
a Library/LaunchDaemons/com.wazuh.agent.plist
a Library/StartupItems/WAZUH
a Library/StartupItems/WAZUH/StartupParameters.plist
a Library/StartupItems/WAZUH/WAZUH
a Library/StartupItems/WAZUH/Wazuh-launcher
2023/12/19 06:46:13 - Backup generated in /Library/Ossec/backup/backup_[12-19-2023_06-46-12].tar.gz
2023/12/19 06:46:13 - Upgrade started.
installer: Package name is Wazuh Agent
installer: Upgrading at base path /
installer: The upgrade was successful.
2023/12/19 06:46:26 - Installation result = 0
2023/12/19 06:46:26 - Waiting connection... Remaining attempts: 30.
2023/12/19 06:46:27 - Status = connected. 
2023/12/19 06:46:27 - Connected to manager.
2023/12/19 06:46:27 - Upgrade finished successfully.
```

</details>

Notes: :warning: 

- macOS ossec.log has been erased after the upgrade, this needs to be investigated
- After trying to upgrade the agent without the upgrade module started (after shared configuration restart), multiple errors has been observed (expected) but after the error messages, a restart occurs, this needs to be investigated

**Comment by Rebits** [comment]
### WPK upgrade test - Linux 


<details>

<summary> Agent Info</summary>

```
root@ubuntu2:/home/vagrant# /var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.7.0"
WAZUH_REVISION="40704"
WAZUH_TYPE="agent"
```



</details>


<details>

<summary>Agent info in manager </summary>

```
root@ubuntu22:/home/vagrant# /var/ossec/bin/agent_control -i 001

Wazuh agent_control. Agent information:
   Agent ID:   001
   Agent Name: ubuntu2
   IP address: any
   Status:     Active

   Operating system:    Linux |ubuntu2 |5.4.0-139-generic |#156-Ubuntu SMP Fri Jan 20 17:27:18 UTC 2023 |x86_64
   Client version:      Wazuh v4.7.0
   Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
   Shared file hash:    4a8724b20dee0124ff9656783c490c4e
   Last keep alive:     1703088526

   Syscheck last started at:  Wed Dec 20 16:07:52 2023
   Syscheck last ended at:    Wed Dec 20 16:07:58 2023
```


</details>




<details>

<summary> Agent update</summary>

```
root@ubuntu22:/home/vagrant# /var/ossec/bin/agent_upgrade -a 001

Upgrading...



Upgraded agents:
	Agent 001 upgraded: Wazuh v4.7.0 -> Wazuh v4.7.1
```

</details>



<details>

<summary> Agent info </summary>
```
root@ubuntu2:/var/ossec# /var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.7.1"
WAZUH_REVISION="40709"
WAZUH_TYPE="agent"
```

</details>


<details>

<summary> Agent info in manager </summary>

```
root@ubuntu22:/home/vagrant# /var/ossec/bin/agent_control -i 001

Wazuh agent_control. Agent information:
   Agent ID:   001
   Agent Name: ubuntu2
   IP address: any
   Status:     Active

   Operating system:    Linux |ubuntu2 |5.4.0-139-generic |#156-Ubuntu SMP Fri Jan 20 17:27:18 UTC 2023 |x86_64
   Client version:      Wazuh v4.7.1
   Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
   Shared file hash:    4a8724b20dee0124ff9656783c490c4e
   Last keep alive:     1703088817

   Syscheck last started at:  Wed Dec 20 16:12:32 2023
   Syscheck last ended at:    Wed Dec 20 16:12:38 2023
```

</details>


<details>

<summary> upgrade.log </summary>

``` 
2023/12/20 16:12:25 - Generating Backup.
tar: Removing leading `/' from member names
/var/ossec/active-response/
/var/ossec/active-response/bin/
/var/ossec/active-response/bin/host-deny
tar: Removing leading `/' from hard link targets
/var/ossec/active-response/bin/disable-account
/var/ossec/active-response/bin/restart-wazuh
/var/ossec/active-response/bin/firewalld-drop
/var/ossec/active-response/bin/route-null
/var/ossec/active-response/bin/wazuh-slack
/var/ossec/active-response/bin/default-firewall-drop
/var/ossec/active-response/bin/firewall-drop
/var/ossec/active-response/bin/pf
/var/ossec/active-response/bin/kaspersky.py
/var/ossec/active-response/bin/npf
/var/ossec/active-response/bin/kaspersky
/var/ossec/active-response/bin/ipfw
/var/ossec/active-response/bin/restart.sh
/var/ossec/active-response/bin/ip-customblock
/var/ossec/bin/
/var/ossec/bin/manage_agents
/var/ossec/bin/wazuh-syscheckd
/var/ossec/bin/wazuh-execd
/var/ossec/bin/wazuh-agentd
/var/ossec/bin/wazuh-modulesd
/var/ossec/bin/agent-auth
/var/ossec/bin/wazuh-logcollector
/var/ossec/bin/wazuh-control
/var/ossec/etc/
/var/ossec/etc/shared/
/var/ossec/etc/shared/cis_win2012r2_domainL2_rcl.txt
/var/ossec/etc/shared/rootkit_files.txt
/var/ossec/etc/shared/win_applications_rcl.txt
/var/ossec/etc/shared/cis_win2012r2_domainL1_rcl.txt
/var/ossec/etc/shared/merged.mg
/var/ossec/etc/shared/rootkit_trojans.txt
/var/ossec/etc/shared/win_audit_rcl.txt
/var/ossec/etc/shared/cis_sles12_linux_rcl.txt
/var/ossec/etc/shared/cis_win2012r2_memberL2_rcl.txt
/var/ossec/etc/shared/cis_debian_linux_rcl.txt
/var/ossec/etc/shared/system_audit_ssh.txt
/var/ossec/etc/shared/cis_rhel6_linux_rcl.txt
/var/ossec/etc/shared/cis_mysql5-6_enterprise_rcl.txt
/var/ossec/etc/shared/cis_mysql5-6_community_rcl.txt
/var/ossec/etc/shared/cis_rhel5_linux_rcl.txt
/var/ossec/etc/shared/cis_rhel7_linux_rcl.txt
/var/ossec/etc/shared/cis_sles11_linux_rcl.txt
/var/ossec/etc/shared/cis_rhel_linux_rcl.txt
/var/ossec/etc/shared/win_malware_rcl.txt
/var/ossec/etc/shared/ar.conf
/var/ossec/etc/shared/system_audit_rcl.txt
/var/ossec/etc/shared/agent.conf
/var/ossec/etc/shared/cis_apache2224_rcl.txt
/var/ossec/etc/shared/cis_win2012r2_memberL1_rcl.txt
/var/ossec/etc/internal_options.conf
/var/ossec/etc/wpk_root.pem
/var/ossec/etc/localtime
/var/ossec/etc/ossec.conf.save
/var/ossec/etc/client.keys
/var/ossec/etc/local_internal_options.conf
/var/ossec/etc/ossec.conf
/var/ossec/etc/client.keys.save
/var/ossec/etc/local_internal_options.conf.save
/var/ossec/lib/
/var/ossec/lib/libsysinfo.so
/var/ossec/lib/libwazuhext.so
/var/ossec/lib/libdbsync.so
/var/ossec/lib/librsync.so
/var/ossec/lib/libgcc_s.so.1
/var/ossec/lib/libstdc++.so.6
/var/ossec/lib/libwazuhshared.so
/var/ossec/lib/libfimdb.so
/var/ossec/lib/libsyscollector.so
/var/ossec/queue/
/var/ossec/queue/rids/
/var/ossec/queue/rids/sender_counter
/var/ossec/queue/rids/001
/var/ossec/queue/alerts/
tar: /var/ossec/queue/alerts/cfgaq: socket ignored
tar: /var/ossec/queue/alerts/execq: socket ignored
/var/ossec/queue/logcollector/
/var/ossec/queue/logcollector/file_status.json
/var/ossec/queue/sockets/
/var/ossec/queue/sockets/.agent_info
tar: /var/ossec/queue/sockets/wmodules: socket ignored
tar: /var/ossec/queue/sockets/queue: socket ignored
tar: /var/ossec/queue/sockets/com: socket ignored
tar: /var/ossec/queue/sockets/syscheck: socket ignored
tar: /var/ossec/queue/sockets/logcollector: socket ignored
tar: /var/ossec/queue/sockets/control: socket ignored
tar: /var/ossec/queue/sockets/upgrade: socket ignored
/var/ossec/queue/fim/
/var/ossec/queue/fim/db/
/var/ossec/queue/fim/db/fim.db-journal
/var/ossec/queue/fim/db/fim.db
/var/ossec/queue/syscollector/
/var/ossec/queue/syscollector/db/
/var/ossec/queue/syscollector/db/local.db
/var/ossec/queue/syscollector/db/local.db-journal
/var/ossec/queue/syscollector/norm_config.json
/var/ossec/ruleset/
/var/ossec/ruleset/sca/
/var/ossec/ruleset/sca/cis_ubuntu20-04.yml
/var/ossec/wodles/
/var/ossec/wodles/gcloud/
/var/ossec/wodles/gcloud/gcloud
/var/ossec/wodles/gcloud/tools.py
/var/ossec/wodles/gcloud/exceptions.py
/var/ossec/wodles/gcloud/buckets/
/var/ossec/wodles/gcloud/buckets/bucket.py
/var/ossec/wodles/gcloud/buckets/access_logs.py
/var/ossec/wodles/gcloud/integration.py
/var/ossec/wodles/gcloud/pubsub/
/var/ossec/wodles/gcloud/pubsub/subscriber.py
/var/ossec/wodles/docker/
/var/ossec/wodles/docker/DockerListener
/var/ossec/wodles/__init__.py
/var/ossec/wodles/aws/
/var/ossec/wodles/aws/aws-s3
/var/ossec/wodles/utils.py
/var/ossec/wodles/azure/
/var/ossec/wodles/azure/orm.py
/var/ossec/wodles/azure/azure-logs
/var/ossec/agentless/
/var/ossec/agentless/sshlogin.exp
/var/ossec/agentless/ssh_pixconfig_diff
/var/ossec/agentless/register_host.sh
/var/ossec/agentless/ssh_integrity_check_bsd
/var/ossec/agentless/ssh_generic_diff
/var/ossec/agentless/ssh_integrity_check_linux
/var/ossec/agentless/ssh.exp
/var/ossec/agentless/ssh_nopass.exp
/var/ossec/agentless/su.exp
/var/ossec/agentless/ssh_asa-fwsmconfig_diff
/var/ossec/agentless/ssh_foundry_diff
/var/ossec/agentless/main.exp
/var/ossec/logs/wazuh/
/var/ossec/var/selinux/
/var/ossec/var/selinux/wazuh.pp
/usr/lib/systemd/system/wazuh-agent.service
2023/12/20 16:12:26 - Backup generated in /var/ossec/backup/backup_[12-20-2023_16-12-25].tar.gz
2023/12/20 16:12:26 - Upgrade started.

 Wazuh v4.7.1 (Rev. 40709) Installation Script - https://www.wazuh.com

 You are about to start the installation process of Wazuh.
 You must have a C compiler pre-installed in your system.

  - System: Linux ubuntu2 5.4.0-139-generic (ubuntu 20.04)
  - User: root
  - Host: ubuntu2


  -- Press ENTER to continue or Ctrl-C to abort. --

 - You already have Wazuh installed. Do you want to update it? (y/n): 
    - Installation will be made at  /var/ossec .

4- Installing the system

DIR="/var/ossec"
 - Running the Makefile

Stopping Wazuh...
agent
Wait for success...
success
Removing old SCA policies...
Installing SCA policies...


Wait for success...
success
Starting Wazuh...

 - Configuration finished properly.

 - To start Wazuh:
      /var/ossec/bin/wazuh-control start

 - To stop Wazuh:
      /var/ossec/bin/wazuh-control stop

 - The configuration can be viewed or modified at /var/ossec/etc/ossec.conf


   Thanks for using Wazuh.
   Please don't hesitate to contact us if you need help or find
   any bugs.

   Use our public Mailing List at:
          https://groups.google.com/forum/#!forum/wazuh

   More information can be found at:
          - http://www.wazuh.com

    ---  Press ENTER to finish (maybe more information below). ---

 - Update completed.

2023/12/20 16:12:37 - Installation result = 0
2023/12/20 16:12:37 - Waiting connection... Remaining attempts: 30.
2023/12/20 16:12:38 - Status = connected. 
2023/12/20 16:12:38 - Connected to manager.
2023/12/20 16:12:38 - Upgrade finished successfully.
```

</details>

**Comment by pro-akim** [comment]
## Review Notes
LGTM
