### ISSUE TITLE
Adapt agent simulator in order to generate Vulnerability detector alerts

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#4781]
| Development branch |
| --- |
| `enhancement/4781-adapt-syscollector-agent-simulator` |   

### Description

The Agent Simulator facilitates agent simulation, enabling the generation of custom events across various modules such as logcollector, syscheck, syscollector, etc.

Currently it has been identified that the agent simulator is not triggering correctly Vulnerability detector alerts for simulated package insertion events. Several issues were detected

### Tasks
- [x] https://github.com/wazuh/wazuh-qa/issues/4772
- [x] https://github.com/wazuh/wazuh-qa/issues/4783
- [x] https://github.com/wazuh/wazuh-qa/issues/4793
- [x] https://github.com/wazuh/wazuh-qa/issues/4794

**Comment by Rebits** [comment]
Established the development branch `enhancement/4781-adapt-syscollector-agent-simulator` to facilitate seamless integration of all updates related to the agent simulator.

**Comment by Rebits** [comment]
- Currently testing https://github.com/wazuh/wazuh-qa/pull/4868 locally and using with pipeline https://github.com/wazuh/wazuh/issues/20779

**Comment by davidjiglesias** [comment]
LGTM!
