### ISSUE TITLE
Update Agent Simulator Syscollector format messages

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#4783]
## Description
During our analysis of https://github.com/wazuh/wazuh-qa/issues/4781, it has been identified that the agent simulator is not triggering correctly Vulnerability detector alerts for simulated package insertion events. Several issues were detected

- The Syscollector message format is now outdated, having undergone changes in version 4.2. It is imperative to update the syscollector message template to align with the current version, enhancing its similarity to authentic 4.7.0 agents. Upgrade is essential to ensure compatibility and optimal performance.

**Previous to 4.2 Syscollector message format**
```
d:syscollector:{"type":"program","ID":50,"timestamp":"2023/12/19 00:00:00","program":{"format":"rpm","name":"JIYTNZ2ZJZ","description":"JSON::XS compatible pure-Perl module","size":126,"vendor":"CentOS","group":"Unspecified","architecture":"noarch","source":"perl-JSON-PP-2.97.001-3.el8.src.rpm","install_time":"2021/03/12 12:23:17","version":"1:2.97.001-3.el8"}}
```

 **4.2 and after Syscollector message format**
```
d:syscollector:{"agent_info":{"agent_id":"001","agent_ip":"any","agent_name":"testAgen1","node_name":"node01"},"data_type":"dbsync_packages","data":{"architecture":"amd64","checksum":"66e8140425c4e12c2d35e8267d31deb2853f1f5e","description":"Vi IMproved - enhanced vi editor","format":"deb","groups":"editors","install_time":" ","item_id":"6bbdd1d1b4337b9cb73b2e6520528b013a9aab0c","location":" ","multiarch":null,"name":"vim","priority":"optional","scan_time":"2023/12/19 15:33:14","size":3221,"source":" ","vendor":"Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>","version":"2:8.2.0716-3ubuntu2"},"operation":"DELETED"}
```

- Syscollector messages does not triggers Vulnerability detector alerts, producing this warning error during the vulnerability detector scan time

`2023/12/20 13:15:28 wazuh-modulesd:vulnerability-detector[57623] wm_vuln_detector.c:5832 at wm_vuldet_collect_agent_software(): WARNING: (5515): Agent '026' software could not be requested.`

This is originated due there are missing synchronization messages during Syscollector message generation

### Tasks
- [x] Enhance Syscollector package generation events to align with the new format.
- [x] Upgrade the GeneratorSyscollector class to produce the necessary synchronization events, ensuring the triggering of alerts for the Vulnerability Detector

### Validation

- [x] Simulated agents are capable of triggering Vulnerability detector alerts

**Comment by Rebits** [comment]
The manager did not approve the proposed new format. Consequently, the Syscollector event generator underwent a modification. Now, it initiates by transmitting an 'osinfo' message, followed by the transmission of multiple 'insert package' events in accordance with the specified templates.

```
SYSCOLLECTOR_OSINFO_INSERT_EVENT_TEMPLATE = '{"type":"dbsync_osinfo", "data":{"checksum":"1634140017886803554","architecture":"x86_64","hostname":"<agent_name>", "os_codename":"focal", "os_major":"20","os_minor":"04","os_name":"Ubuntu", "os_platform":"ubuntu", "os_patch": "6", "os_release":"sp1","os_version":"20.04.6 LTS (Focal Fossa)", "os_build":"4.18.0-305.12.1.el8_4.x86_64","release":"6.2.6-76060206-generic","scan_time":"2023/12/20 11:24:58", "sysname":"Linux","version":"#202303130630~1689015125~22.04~ab2190e SMP PREEMPT_DYNAMIC"}, "operation": "INSERTED"}'



SYSCOLLECTOR_PACKAGES_INSERT_EVENT_TEMPLATE = '{"type":"dbsync_packages", "data":{"architecture":"amd64","checksum":"66e8140425c4e12c2d35e8267d31deb2853f1f5e","description":"Python bindings for apps which will manipulate perf events","format":"deb","groups":"editors","install_time":" ","item_id":"6bbdd1d1b4337b9cb73b2e6520528b013a9aab0c","location":" ","multiarch":null,"name":"python3-perf","priority":"optional","scan_time":"2023/12/19 15:32:25","size":3221,"source":" ","vendor":"Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>","version":"4.18.0-305.12.1.el8_4"},"operation":"INSERTED"}'
```

Following this approach we successfully initialize the mocked agent syscollector databases. However it is produced the following error in the manager:

`2023/12/20 13:15:28 wazuh-modulesd:vulnerability-detector[57623] wm_vuln_detector.c:5832 at wm_vuldet_collect_agent_software(): WARNING: (5515): Agent '026' software could not be requested.`


Leading into the Vulnerability Detector scan ignoring the mocked agent. 

Currently researching this issue

**Comment by Rebits** [comment]
Conducting a research about the syscollector message format, we've encountered challenges in resolving the issue detailed at https://github.com/wazuh/wazuh-qa/issues/4783#issuecomment-1864787971. Currently, we are actively engaging with the development team to incorporate the essential logic required to emulate real agents, aiming to address the identified problem comprehensively.

**Comment by Rebits** [comment]
Planned a meeting with @wazuh/data-pirates regarding this matter

**Comment by Rebits** [comment]
Had a productive meeting with @davidjiglesias, @Dwordcito, and @Damian-Mangold. We've decided to move away from the approach suggested in https://github.com/wazuh/wazuh-qa/issues/4783#issuecomment-1875291286.

Instead, we'll be emulating Syscollector messages in the Agent simulator to generate the expected alerts for the Vulnerability Detector refactor targeting version 4.8.0.

Currently, actively engaged in testing the proposed Syscollector messages within a VD refactor environment.

**Comment by Rebits** [comment]
We have successfully developed a Vulnerability Detector that generates alerts using the agent simulator, focusing specifically on the inserted package type. Presently, our efforts are directed towards enhancing the adaptability of the agent simulator to generate alerts for all types of events while preserving the legacy syscollector message format.

**Comment by Rebits** [comment]
Achieved simulation of most of the syscollector types of events

```

sqlite> SELECT * FROM sys_programs;
0|2023/12/19 15:32:25|rpm|nettle|optional|editors|666475|Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>|2023-09-22T19:06:13.000Z|2.7.1-9.el7_9|x86_64||vim|A low-level cryptographic library| |0|||66e8140425c4e12c2d35e8267d31deb2853f1f5e|ff5f53a5ed3d2659c0f0b5de579951d332ca47b3
sqlite> SELECT * FROM sys_processes;
0|2024/01/09 00:00:00||T5B13B30ZH|S|6|6|6||<random_int|T5B13B30ZH|T5B13B30ZH|T5B13B30ZH|T5B13B30ZH|T5B13B30ZH|T5B13B30ZH|T5B13B30ZH|6|6|6|6|6|6|6|6|6|6|6|6|6|T5B13B30ZH
0|2024/01/09 00:00:00||6IEUH9NJF6|S|15|15|15||<random_int|6IEUH9NJF6|6IEUH9NJF6|6IEUH9NJF6|6IEUH9NJF6|6IEUH9NJF6|6IEUH9NJF6|6IEUH9NJF6|15|15|15|15|15|15|15|15|15|15|15|15|15|6IEUH9NJF6
0|2024/01/09 00:00:00||AM9T969B38|S|24|24|24||<random_int|AM9T969B38|AM9T969B38|AM9T969B38|AM9T969B38|AM9T969B38|AM9T969B38|AM9T969B38|24|24|24|24|24|24|24|24|24|24|24|24|24|AM9T969B38
0|2024/01/09 00:00:00||QVY1DWYEXK|S|33|33|33||<random_int|QVY1DWYEXK|QVY1DWYEXK|QVY1DWYEXK|QVY1DWYEXK|QVY1DWYEXK|QVY1DWYEXK|QVY1DWYEXK|33|33|33|33|33|33|33|33|33|33|33|33|33|QVY1DWYEXK
0|2024/01/09 00:00:00||9JQDYLPCFD|S|42|42|42||<random_int|9JQDYLPCFD|9JQDYLPCFD|9JQDYLPCFD|9JQDYLPCFD|9JQDYLPCFD|9JQDYLPCFD|9JQDYLPCFD|42|42|42|42|42|42|42|42|42|42|42|42|42|9JQDYLPCFD
0|2024/01/09 00:00:00||R76YEQBOPH|S|51|51|51||<random_int|R76YEQBOPH|R76YEQBOPH|R76YEQBOPH|R76YEQBOPH|R76YEQBOPH|R76YEQBOPH|R76YEQBOPH|51|51|51|51|51|51|51|51|51|51|51|51|51|R76YEQBOPH
0|2024/01/09 00:00:00||QRXIEC85X6|S|60|60|60||<random_int|QRXIEC85X6|QRXIEC85X6|QRXIEC85X6|QRXIEC85X6|QRXIEC85X6|QRXIEC85X6|QRXIEC85X6|60|60|60|60|60|60|60|60|60|60|60|60|60|QRXIEC85X6
sqlite> SELECT * FROM sys_ports;
0|2024/01/09 00:00:00|tcp|0.0.0.0|2|0.0.0.0|2|2|2|0|listening|2|NULL|GGYRRH40G6|GGYRRH40G6
0|2024/01/09 00:00:00|tcp|0.0.0.0|11|0.0.0.0|11|11|11|0|listening|11|NULL|BTEST1Y2QC|BTEST1Y2QC
0|2024/01/09 00:00:00|tcp|0.0.0.0|20|0.0.0.0|20|20|20|0|listening|20|NULL|EBQ6V0J4JX|EBQ6V0J4JX
0|2024/01/09 00:00:00|tcp|0.0.0.0|29|0.0.0.0|29|29|29|0|listening|29|NULL|CMYRJL2HLI|CMYRJL2HLI
0|2024/01/09 00:00:00|tcp|0.0.0.0|38|0.0.0.0|38|38|38|0|listening|38|NULL|H2V4N6JB5H|H2V4N6JB5H
0|2024/01/09 00:00:00|tcp|0.0.0.0|47|0.0.0.0|47|47|47|0|listening|47|NULL|QQ9ATZG2TS|QQ9ATZG2TS
0|2024/01/09 00:00:00|tcp|0.0.0.0|56|0.0.0.0|56|56|56|0|listening|56|NULL|RIAU6S2632|RIAU6S2632
sqlite> SELECT * FROM sys_osinfo;
0|2023/12/20 11:24:58|1-Mn2vZ3bxi7ougOHa-ubuntu20.04|x86_64|Ubuntu|20.04.6 LTS (Focal Fossa)|focal|20|04|6|4.18.0-305.12.1.el8_4.x86_64|ubuntu|Linux|6.2.6-76060206-generic|#202303130630~1689015125~22.04~ab2190e SMP PREEMPT_DYNAMIC|sp1|1634140017886803554||0|
sqlite> SELECT * FROM sys_hwinfo;
0|2024/01/09 00:00:00|5BQ1ZHSATE|5BQ1ZHSATE|3|3.0|3|3|3|5BQ1ZHSATE
0|2024/01/09 00:00:00|SBP7K9M6TH|SBP7K9M6TH|12|12.0|12|12|12|SBP7K9M6TH
0|2024/01/09 00:00:00|QVE8TOMKP0|QVE8TOMKP0|21|21.0|21|21|21|QVE8TOMKP0
0|2024/01/09 00:00:00|VKS4W6R4E2|VKS4W6R4E2|30|30.0|30|30|30|VKS4W6R4E2
0|2024/01/09 00:00:00|O8131XBJNZ|O8131XBJNZ|39|39.0|39|39|39|O8131XBJNZ
0|2024/01/09 00:00:00|VTVSQQ89G2|VTVSQQ89G2|48|48.0|48|48|48|VTVSQQ89G2
0|2024/01/09 00:00:00|ZI6TIU91PD|ZI6TIU91PD|57|57.0|57|57|57|ZI6TIU91PD
sqlite> SELECT * FROM sys_netiface;
0|2024/01/09 00:00:00|4||4|4|4|4|4|4|4|4|4|4|4|4|4|4
0|2024/01/09 00:00:00|13||13|13|13|13|13|13|13|13|13|13|13|13|13|13
0|2024/01/09 00:00:00|22||22|22|22|22|22|22|22|22|22|22|22|22|22|22
0|2024/01/09 00:00:00|31||31|31|31|31|31|31|31|31|31|31|31|31|31|31
0|2024/01/09 00:00:00|40||40|40|40|40|40|40|40|40|40|40|40|40|40|40
0|2024/01/09 00:00:00|49||49|49|49|49|49|49|49|49|49|49|49|49|49|49
0|2024/01/09 00:00:00|58||58|58|58|58|58|58|58|58|58|58|58|58|58|58
sqlite> SELECT * FROM sys_hotfixes;
0||M7UB2IRXEH|ded25e55c93121675adcb8d429dc586cbb351e3a
0||LTGN8OSRUW|ded25e55c93121675adcb8d429dc586cbb351e3a
0||OINYE7PSHM|ded25e55c93121675adcb8d429dc586cbb351e3a
0||KYACAGJL44|ded25e55c93121675adcb8d429dc586cbb351e3a
0||X4HHC1KHXW|ded25e55c93121675adcb8d429dc586cbb351e3a
0||RG2R1QFO70|ded25e55c93121675adcb8d429dc586cbb351e3a
0||55I3FIH2FD|ded25e55c93121675adcb8d429dc586cbb351e3a

```

**Comment by Rebits** [comment]
- Included syslog events for the rests of the messages
- Refactor GeneratorSyscollector to allow maintain legacy syscollector messages
- Allow to change syscollector frequency in simulate agents script
- Allow to change syscollector event types in simulate agents script 
- Researching how to simulate real events based on vulnerability list content

**Comment by Rebits** [comment]
Support for the previous syscollector format will be maintained until a final decision is reached regarding the matter discussed in the following: https://github.com/wazuh/wazuh/issues/21319.
