### ISSUE TITLE
DTT1 - Iteration 2 - QA Workflow Engine

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh-qa#4796]
> Epic: https://github.com/wazuh/wazuh-qa/issues/4495

---

## Description

This issue aims to develop the bare basic implementation of a DAG engine

## Tasks
- [x] Define a YAML input file schema and mechanism to handle DAG definition that allows templates to improve design logic.
  - [x] Use DTT1 agent / DTT1 agent as use cases for such definition
  - [x] Provide a YAML schema validator to decouple the validation
  - [x] Provide a bunch of YAML examples, from simple to complex
- [x] Allow dry-run execution
- [x] Allow parallel execution and explicitly set how many threads will be used
- [x] Task could execute some pre-agreed tasks that will be executed with its own parameters logic
  - [x] process: allow the execution of a process
  - [x] dummy
  - [x] dummy-random 
- [x] requirements.txt
- [x] README.md
- [x] ~Unit tests~

## Known issues
- [x] Task duplication: there's no validation that two tasks have the same name after expansion
- [x] Missing task validation: dry-run does not validate task existence. It fails during runtime
- [x] `cleanup` feature (code support): allow optional cleanup block in tasks, that allows undo dag execution to release resources  or whatever scenario
- [x] `on-error` feature: allow pre-agreed handling mechanism if a task fails
  - [x] continue
  - [x] abort-related-flows -> This should be the default value
  - [x] abort-all

**Comment by fcaffieri** [comment]
### Update

- Added the schema validations to the Workflow engine.
- Fix the requirements.txt adding all the new library dependencies.
- Add schema.json with the validator template.
- Add new class SchemaValidator to handle the validations.
- Execute test with the Workflow Engine.

**Comment by QU3B1M** [comment]
LGTM!

**Comment by fcaffieri** [comment]
Unit test will be launched in https://github.com/wazuh/wazuh-qa/issues/4751 Integrating this new module with the others.
LGTM

**Comment by fcaffieri** [comment]
Unit test will be launched in https://github.com/wazuh/wazuh-qa/issues/4751 Integrating this new module with the others.
LGTM
