### ISSUE TITLE
Support new Wazuh version 4.8.2 in wazuh-qa repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-qa#4804]
## Description

This issue attempts to support a new version 4.8.2 in the wazuh-qa repository.

## Tasks
- [x] https://github.com/wazuh/wazuh-qa/pull/4805
- [x] Create numbered branch for version (4.8.2) using branch 4.8.1 on wazuh-qa repository. https://github.com/wazuh/wazuh-qa/tree/4.8.2
- [x] Bump 4.8.2 branch to 4.8.2 version on wazuh-qa repository, including revision and changelog. https://github.com/wazuh/wazuh-qa/pull/4806

**Comment by Rebits** [comment]
It seems that current 4.8.1 revision mismatch with development revision of the same branch
https://github.com/wazuh/wazuh/blob/4.8.1/src/REVISION

Open https://github.com/wazuh/wazuh-qa/pull/4805 to correct this before the creation of the new 4.8.2 branch

**Comment by fcaffieri** [comment]
LGTM
