### ISSUE TITLE
Support new stage RC 2 for 4.7.2 in wazuh-qa repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-qa#4819]
## Description

This issue attempts to support a new stage RC 2 for 4.7.2 in the wazuh-qa repository.

## Tasks

- [x] Ensure changelog is updated for 4.7.2 (if applicable).
- [x] Bump revision for branch 4.7.2 on wazuh-qa repository. https://github.com/wazuh/wazuh-qa/pull/4821
- [x] Create tag v4.7.2-rc2 from branch 4.7.2 on wazuh-qa repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-qa/releases/tag/v4.7.2-rc2.

**Comment by jnasselle** [comment]
# Review

@pro-akim the tag should be created from the last commit on 4.7.2 branch
Current: https://github.com/wazuh/wazuh-qa/commit/81a18e8949f33303e73b3660c61cdc064994aedc
Expected: https://github.com/wazuh/wazuh-qa/commit/0781d78e55e558aef4bc79f3f3a4869c3ac6f8a1

![image](https://github.com/wazuh/wazuh-qa/assets/1791430/bbb1668e-a551-42e4-909a-459920f3ec6b)
This header should be avoided in order to be aligned with latest release notes

**Comment by jnasselle** [comment]
LGTM!
