### ISSUE TITLE
Publish release 4.7.2

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#4828]
## Description
This issue attempts to track the steps necessary to publish packages, OVA, AMI, docker images, and puppet forge for 4.7.2.

## Tasks
- [x] Send AMI to analysis.
- [x] Launch [`Publish_release`](https://ci.wazuh.info/job/Publish_release) pipeline.
- [x] ~Upload latest Filebeat version.~
- [x] Build and release debug packages.
- [x] Build and push [Docker Hub images](https://ci.wazuh.info/job/procedure_push_docker_images).
  - https://ci.wazuh.info/job/procedure_push_docker_images/118/
- [x] Publish AMI.
  

More steps in https://github.com/wazuh/wazuh-qa/issues/4828#issuecomment-1884579902

**Comment by juliamagan** [comment]
The following tasks must be completed in order:

- [ ] Copy all 4.8.0  packages (packages, debug-packages, checksums, versions) to another directory outside of pre-release
  - https://s3.console.aws.amazon.com/s3/buckets/packages-dev.wazuh.com?region=us-west-1&prefix=pre-backup/
- [ ] Remove  4.8.0 files
  - [ ] pre-debug
  - [ ] pre-release
- [ ] Modify WPK versions (Linux,macOS, Windows) to remove 4.8.0 and upload it again
  - [ ] Ensure that the versions files are publicly available
- [ ] Launch Publish_release without unattended
- [ ] Send AMI to analysis
  - AMI analysis request: 
- [ ] Wait for the Publish_release pipeline to finish
- [ ] Launch unattended
- [ ] Publish AMI
- [ ] Publish pre-debug packages

**Comment by rauldpm** [comment]
LGTM
