### ISSUE TITLE
Post publication live checks for 4.7.2

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#4829]
## Description
This issue attempts to ensure the publication process was correct, attempting checks and live tests for published packages and images.

## Tasks
- [x] Ensure that production files are present.
- [x] Deploy the `Wazuh Installation Assistant` and check the version installed is 4.7.2.
- [x] [AMD64 Live installation test](https://ci.wazuh.info/job/Test_install_tier).
  - https://ci.wazuh.info/job/Test_install_tier/838/
- [x] WPK versions check.
- [x] WPK upgrade test.
  - [x] Linux
  - [x] MacOS Intel
  - [x] Windows
- [x] [AMI published](https://aws.amazon.com/marketplace/pp/prodview-eju4flv5eqmgq).
- [x] [Puppet forge module published](https://forge.puppet.com/modules/wazuh/wazuh/readme).
- [x] [Docker images published](https://hub.docker.com/u/wazuh).

**Comment by Rebits** [comment]
### WPK upgrade test Linux :large_blue_circle:

**Comment by juliamagan** [comment]
## WIA

**Comment by juliamagan** [comment]
## WPK upgrade test


<details>
<summary>macOS </summary>
<br>

**Comment by rauldpm** [comment]
## WPK upgrade test

<details><summary>Windows</summary>

</details>

**Comment by davidjiglesias** [comment]
LGTM
