### ISSUE TITLE
FIM System tests: Unify parameters in Python scripts

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-qa#483]
Hi team,

It's required to unify the parameters of the Python scripts for the FIM System tests actions according to a common convention.

**Pre-Tasks:**

- [x] #489 Create folder `common_vars` and a `main.yml` file to specify default variables (@jm404) 

**List of Target Scripts**

- [x]  Create n files on the specified path  (@xr09 ) #488

- [x]  Randomly delete n files. by (@rshad), _**PR**_ https://github.com/wazuh/wazuh-qa/pull/484

- [x]  Modify attributes and content of selected files (@xr09) #485 

- [x]  Alerts logged to alerts.json (@Zenidd) https://github.com/wazuh/wazuh-qa/pull/490

- [x]  Alerts logged to Elasticsearch (@DFolchA) #492 

### Parameters

**Input raw files list `-i`**
```python
    parser.add_argument("-i", "--input-list", type=str, required=True, dest='input_file',
                        help="File containing the list of files from which we will randomly \
                              select files to be deleted, one per line")
```
**Number of files: `-n`** - _**Optional, by default all files will be modified/deleted**_
```python
    parser.add_argument("-n", "--n_files", type=int, required=False, dest='n_files',
                        help="Number of files to be randomly selected and deleted or modified ..")
```
**Output raw files list `-o`**
```python
    parser.add_argument("-o", "--output-list", type=str, required=True, dest='output_file',
                        help="<corresponding description>")
```
**Event to execute `-e`**
```python
    parser.add_argument("-e", "--event", type=str, required=True, dest='event',
                        choices=['added', 'modified', 'deleted'],
                        help="Type of event that we expect: added, modified, deleted")
```
**`alerts.json` as Input file `-l`**
```python
    parser.add_argument("-l", "--log_json", type=str, required=False, dest='log_json_path',
                        help="alerts.json path. default value '/var/ossec/logs/alerts/alerts.json'",
                        default="/var/ossec/logs/alerts/alerts.json")
```

Kr,

**Comment by rshad** [comment]
Working branch for the task `Randomly delete n files` is [feature-483-delete-files](https://github.com/wazuh/wazuh-qa/tree/feature-483-delete-files).

**Comment by rshad** [comment]
#### Task: _Randomly delete n files_
Hi all!

The required arguments to the script `wazuh-qa/tests/system/fim/common_tasks/delete_files.py` are:

- **_Input file_**: contains the list of the files to be deleted or to randomly select and delete x files of them.
- **_Number of files_** _(Optional)_: The number of files to be deleted. It's the total number of files by default.
- **_Output file_**: The path of the file to save the list of the deleted files into.

```python
    parser.add_argument("-i", "--input-list", type=str, required=True, dest='input_file',
                        help="File containing the list of files from which we will randomly \
                              select files to be deleted, one per line")
    parser.add_argument("-n", "--n_files", type=int, required=False, dest='n_files',
                        help="Number of files to be randomly selected and deleted")
    parser.add_argument("-o", "--output-list", type=str, required=True, dest='output_file',
                        help="File containing the list of the deleted files, one per line")
```

We also adapted the function to delete all the files in case of not specifying the argument `-n or --n_files`.
```python
    if n is not None: # Randomly select n paths from data
        to_delete = random.sample(data,n)
    else: # Delete all files
        to_delete = data
```

Kr,

Rshad

**Comment by Zenidd** [comment]
### Arguments Summary table


| Scripts   | Arg0| Arg1| Arg2| Arg3|Arg4|
| --------------- | ----------- |--------------- | ----------- |--------------- | ----------- |
| Create(short)  | -  |-    | -  | -  |-  |
| Create  | -  |-    | -  | -  |-  |
| Modify(short)  | -  |-    | -  | -  | -  |
| Modify  | -  |-    | -  | -  | -  |
| Delete(short)   | -  |-    | -  | -  | -  |
| Delete   | -  |-    | -  | -  | -  |
| **Verification Scripts**   | **Arg0** | **Arg1** | **Arg2** | **Arg3**| **Arg4**|
| verify_alerts_json.py(short)     |   "-f"   | "-e" |"-l"|"-o"| -  |
| verify_alerts_json.py    | "--files"   | "--event" |"--log_json"|"--output_path"| -  |
| verify_alerts_elasticsearch.py(short)     | -  |-    | -  |-    | -  |
| verify_alerts_elasticsearch.py    | -  |-    | -  |-    | -  |

**Comment by rshad** [comment]
Working branch for the task `Alerts logged to alerts.json` is [feature-483-unify-params-alerts-logging](https://github.com/wazuh/wazuh-qa/tree/feature-483-unify-params-alerts-logging).
