### ISSUE TITLE
Post release tasks for 4.7.2

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#4830]
## Description

This issue attempts to track the steps necessary to complete post-release maintenance tasks for 4.7.2.
The goal is to complete the following tasks, each task must have a PR associated with this issue.

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, `merge-4.7.2-into-4.8.0`.

## Tasks

- [x] Restore 4.8.0 packages
- [x] Disable pre-release upload
- [x] Merge branch `4.7.2` into branch `4.8.0`. https://github.com/wazuh/wazuh-qa/pull/4832
- [x] Merge branch `4.8.0` into branch `4.8.1`. https://github.com/wazuh/wazuh-qa/pull/4833
- [x] Merge branch `4.8.1` into branch `4.8.2`. https://github.com/wazuh/wazuh-qa/pull/4834
- [x] Merge branch `4.8.2` into branch `master`. https://github.com/wazuh/wazuh-qa/pull/4836
- [x] Publish GitHub release as latest. https://github.com/wazuh/wazuh-qa/releases/tag/v4.7.2
- [x] Delete all stage pre-releases for 4.7.2 (https://github.com/wazuh/wazuh-qa/releases).
- [x] Delete all stage tags for v4.7.2. **BE CAREFUL NOT TO DELETE DEFINITIVE TAG**. Example: v4.7.2-rc1, 4.7.2-alpha1, etc.
- [x] Delete branch `4.7.2`.

**Comment by rauldpm** [comment]
## Disable pre-release upload

![image](https://github.com/wazuh/wazuh-qa/assets/14913942/500ce00d-64bd-43d4-ab2f-e4fe3729b5af)

**Comment by QU3B1M** [comment]
LGTM!
