### ISSUE TITLE
DTT2 - Observability module - Improvements and adaptations

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/wazuh-qa#4837]
> Epic: https://github.com/wazuh/wazuh-qa/issues/4495

---

## Description

The objective of this issue is to adapt the observability module so that it is coupled to the improvements made to the modules in DTT1 Iteration 2 and to consider the new TaskFlow module.

## Tasks

- [ ] https://github.com/wazuh/wazuh-qa/issues/4856
- [x]  https://github.com/wazuh/wazuh-qa/issues/4845
- [x] https://github.com/wazuh/wazuh-qa/issues/4847
- [ ] https://github.com/wazuh/wazuh-qa/issues/5075
- [ ] https://github.com/wazuh/wazuh-qa/issues/5076
- [ ] https://github.com/wazuh/wazuh-qa/issues/5077
- [ ] https://github.com/wazuh/wazuh-qa/issues/5078
- [ ] https://github.com/wazuh/wazuh-qa/issues/5091

**Comment by fcaffieri** [comment]
This issue is passed for tier 2 due to the need to have the [Jenkins redesign](https://github.com/wazuh/wazuh-jenkins/issues/5927) implementation ready.

**Comment by fcaffieri** [comment]
Moves to blocks to finalize DTT1 delivery

**Comment by juliamagan** [comment]
These issues have taken a lot of effort, however, we are not ready to deal with them right now, so we will close them, but we will keep them in mind for the future.
