### ISSUE TITLE
DTT1 - Iteration 3 - Test module - Improve Wazuh agent tests

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#4843]
> Epic #4495

## Description
This issue aims to improve and complete the wazuh-agent tests generated in the first iterations of **DTT1**

### Tasks
- [x] Test **install** - Add checkfiles close-word
- [x] Test **registration** - Add validations through Wazuh API
- [x] Test **restart** - Add validations through Wazuh API
- [x] Test **stop** - Validate process and services
- [x] Test **uninstall** - Expect the agent uninstalled by the provision module & validate process and services
- [x] Test in AWS EC2 instances

**Comment by QU3B1M** [comment]
## Update report

Created a small library to handle WazuhAPI requests and responses with the purpose of simplifying the API testing for current and future tests. The library contains three files and for now is included inside the tests helpers, later, if its approved it could be configured to be an installable library.

Files:
- `endpoints.py` - Lists all the WazuhAPI endpoints used by the library
    <details>

    ```python
    #   - Wazuh API endpoints
    
    # -- Security --
    SECURITY = '/security'
    # Users
    SECURITY_USER = f'{SECURITY}/user'
    SECURITY_USERS = f'{SECURITY}/users'
    # Authentication
    SECURITY_AUTHENTICATE = f'{SECURITY_USER}/authenticate'
    # Configuration
    SECURITY_CONFIG = f'{SECURITY}/config'
    
    # -- Groups --
    GROUPS = '/groups'
    
    # -- Agents --
    AGENTS = '/agents'
    AGENTS_GROUP = f'{AGENTS}/group'
    
    ```
    </details>
- `exceptions.py` - Defines exceptions to be raised by the library corresponding to failing status codes
    <details>

    ```python
    from requests import RequestException
    
    
    
    class BadRequest(RequestException):
        """A bad request error occurred."""
    
    
    class Unauthorized(RequestException):
        """An unauthorized error occurred."""
    
    
    class Forbidden(RequestException):
        """A forbidden error occurred."""
    
    
    class NotFound(RequestException):
        """A not found error occurred."""
    
    
    class MethodNotAllowed(RequestException):
        """A method not allowed error occurred."""
    
    
    class TooManyRequests(RequestException):
        """A request limit exceeded error occurred."""
    
    
    class InternalServerError(RequestException):
        """An internal server error occurred."""
    
    
    class ServiceUnavailable(RequestException):
        """A service unavailable error occurred."""
    
    
    class GatewayTimeout(RequestException):
        """A gateway timeout error occurred."""
    
    
    responses_errors = {
        400: BadRequest,
        401: Unauthorized,
        403: Forbidden,
        404: NotFound,
        405: MethodNotAllowed,
        429: TooManyRequests,
        500: InternalServerError,
        501: ServiceUnavailable,
        503: GatewayTimeout
    }
    ```
    </details>
- `api.py` - The main file of the library where the class WazuhAPI resides.  
    <details>

    ```python
    import requests
    
    from datetime import datetime, timedelta
    
    from .exceptions import responses_errors
    from . import endpoints
    
    
    class WazuhAPI:
    
        def __init__(self, user: str, password: str, host: str = 'localhost', port: int = 55000) -> None:
            self.user = user
            self.password = password
            self.host = host
            self.port = port
            # Token default values
            self.token = None
            self.token_lifetime = 900
            self.token_expiration = None
            # Create a requests session and disable the warnings
            self.session = requests.Session()
            requests.packages.urllib3.disable_warnings()
            # Authenticate and save the token value and expiration
            self.authenticate()
    
        # Security
    
        def authenticate(self) -> str:
            endpoint = self._get_complete_url(endpoints.SECURITY_AUTHENTICATE)
            credentials = (self.user, self.password)
            # _send_request is not used here because of the auth parameter.
            response = self.session.get(endpoint, auth=credentials, verify=False)
            if response.status_code in responses_errors.keys():
                print(f'Authentication error: {response.content}')
                raise responses_errors[response.status_code]
            self.token_expiration = datetime.now() + timedelta(seconds=self.token_lifetime)
            self.token = response.json()['data']['token']
    
        def extend_token_life(self, timeout: int = 99999999) -> dict:
            endpoint = self._get_complete_url(endpoints.SECURITY_CONFIG)
            payload = {"auth_token_exp_timeout": timeout, "rbac_mode": "white"}
            response = self._send_request('put', endpoint, payload=payload)
            self.token_lifetime = timeout
            return response
    
        # Agents
    
        def add_agent(self, name: str, ip: str) -> dict:
            endpoint = self._get_complete_url(endpoints.AGENTS)
            payload = {'name': name, 'ip': ip}
            return self._send_request('post', endpoint, payload=payload)
    
        def get_agent(self, agent_id: str) -> dict:
            endpoint = self._get_complete_url(endpoints.AGENTS)
            params = {'agents_list': [agent_id]}
            response = self._send_request('get', endpoint, query_params=params)
            return response[0] if response else {}
    
        def get_agents(self, **kwargs: dict) -> list[dict]:
            endpoint = self._get_complete_url(endpoints.AGENTS)
            return self._send_request('get', endpoint, query_params=kwargs)
    
        def delete_agent(self, agent_id: str) -> dict:
            endpoint = self._get_complete_url(endpoints.AGENTS)
            params = {'agents_list': [agent_id], 'status': 'all'}
            return self._send_request('delete', endpoint, query_params=params)
    
        def delete_agents(self, agents_list: list, **kwargs: dict) -> dict:
            endpoint = self._get_complete_url(endpoints.AGENTS)
            params = {**kwargs, 'agents_list': agents_list}
            return self._send_request('delete', endpoint, query_params=params)
    
        # --- INTERNAL METHODS ---
    
        def _send_request(self, method: str, endpoint: str, payload: dict = None, query_params: dict = {}) -> dict:
            if not self.token:
                self.authenticate()
            elif self.token_expiration <= datetime.now():
                self.authenticate()
            # Set the headers and send the request
            headers = {'Authorization': f'Bearer {self.token}'}
            query_params['pretty'] = 'true'
            response = self.session.request(
                method, endpoint, data=payload, headers=headers, params=query_params, verify=False)
            # Check if the response is an error
            if response.status_code in responses_errors.keys():
                print(f'Failing request to: {endpoint}\nError: {response.content}')
                raise responses_errors[response.status_code]
            return response.json().get('data', {}).get('affected_items', {})
    
        def _get_complete_url(self, endpoint) -> str:
            if endpoint.startswith('/'):
                endpoint = endpoint[1:]
            return f'https://{self.host}:{self.port}/{endpoint}'
    
    ```
    </details>

**Comment by QU3B1M** [comment]
### Update report

#### About **`check-files`** on _test Install_:
In the current approach the provision module is in charge of installing the `wazuh-agent`, so there is no easy way to take a snapshot of the system files before and after the installation to validate for changes.

If we want to maintain the test "simple" and "modularized" to only do validations, we won't be able to do the check-files, at least with the desired approach.

**Comment by fcaffieri** [comment]
### Review

All test LGTM

The item `Test install - Add checkfiles close-word` will be analyzed and discussed with @davidjiglesias  and then the appropriate implementation since the current implementation is not valid.

**Comment by pro-akim** [comment]
## Update
First of all, it was determined in the discussion with the team that the installation and uninstallation tests should consider the installation and uninstallation of components within the test module itself.

On the other hand, we will investigate how to instrument the checkfile.

### Steps to follow:
- [ ] Research about checkfiles
- [ ] Define functions to install and uninstall depending the OS => create a list of actions and their variations
- [ ] Apply all
- [ ] Test

-----
### Research about checkfiles

It is clear that to achieve the checkfile, we will have to take a snapshot of the directories and files before and after the 'action'.

**Comment by pro-akim** [comment]
## Update
1. Without the provision, the agent host does not have pip, pytest, and basic libraries installed.

**Comment by pro-akim** [comment]
## Update

Some changes have been done in the check-file comparison function:

Install scenario:
1. /var snapshot_pre
2. Wazuh Agent installation
3. /var snapshot_post
4. comparison between snapshot_pre and snapshot_post

```
postinstall =  {'changed_files': ['/var/log/dpkg.log', '/var/log/auth.log', '/var/log/syslog', '/var/log/journal/ea8d563452674de897687e4c554abfba/system.journal', '/var/lib/dpkg/status', '/var/cache/apt/pkgcache.bin'], 'added_files': ['/var/lib/dpkg/info/wazuh-agent.postinst', '/var/lib/dpkg/info/wazuh-agent.conffiles', '/var/lib/dpkg/info/wazuh-agent.preinst', '/var/lib/dpkg/info/wazuh-agent.postrm', '/var/lib/dpkg/info/wazuh-agent.templates', '/var/lib/dpkg/info/wazuh-agent.prerm', '/var/lib/dpkg/info/wazuh-agent.shlibs', '/var/lib/dpkg/info/wazuh-agent.list', '/var/lib/dpkg/info/wazuh-agent.md5sums', '/var/ossec/ruleset/sca/cis_ubuntu22-04.yml', '/var/ossec/wodles/utils.py', '/var/ossec/wodles/__init__.py', '/var/ossec/wodles/aws/aws-s3', '/var/ossec/wodles/azure/orm.py', '/var/ossec/wodles/azure/azure-logs', '/var/ossec/wodles/docker/DockerListener', '/var/ossec/wodles/gcloud/exceptions.py', '/var/ossec/wodles/gcloud/integration.py', '/var/ossec/wodles/gcloud/tools.py', '/var/ossec/wodles/gcloud/gcloud', '/var/ossec/wodles/gcloud/pubsub/subscriber.py', '/var/ossec/wodles/gcloud/buckets/bucket.py', '/var/ossec/wodles/gcloud/buckets/access_logs.py', '/var/ossec/var/run/wazuh-syscheckd-120670.pid', '/var/ossec/var/run/wazuh-agentd.state', '/var/ossec/var/run/wazuh-agentd-120657.pid', '/var/ossec/var/run/wazuh-execd-120646.pid', '/var/ossec/var/run/wazuh-modulesd-120700.pid', '/var/ossec/var/run/wazuh-logcollector-120683.pid', '/var/ossec/var/selinux/wazuh.pp', '/var/ossec/agentless/register_host.sh', '/var/ossec/agentless/ssh_integrity_check_linux', '/var/ossec/agentless/ssh_asa-fwsmconfig_diff', '/var/ossec/agentless/sshlogin.exp', '/var/ossec/agentless/ssh_foundry_diff', '/var/ossec/agentless/ssh_generic_diff', '/var/ossec/agentless/main.exp', '/var/ossec/agentless/su.exp', '/var/ossec/agentless/ssh.exp', '/var/ossec/agentless/ssh_pixconfig_diff', '/var/ossec/agentless/ssh_nopass.exp', '/var/ossec/agentless/ssh_integrity_check_bsd', '/var/ossec/bin/wazuh-control', '/var/ossec/bin/agent-auth', '/var/ossec/bin/wazuh-agentd', '/var/ossec/bin/wazuh-logcollector', '/var/ossec/bin/wazuh-modulesd', '/var/ossec/bin/manage_agents', '/var/ossec/bin/wazuh-syscheckd', '/var/ossec/bin/wazuh-execd', '/var/ossec/lib/libsysinfo.so', '/var/ossec/lib/libstdc++.so.6', '/var/ossec/lib/libwazuhshared.so', '/var/ossec/lib/libfimdb.so', '/var/ossec/lib/libsyscollector.so', '/var/ossec/lib/librsync.so', '/var/ossec/lib/libwazuhext.so', '/var/ossec/lib/libgcc_s.so.1', '/var/ossec/lib/libdbsync.so', '/var/ossec/etc/client.keys', '/var/ossec/etc/localtime', '/var/ossec/etc/wpk_root.pem', '/var/ossec/etc/local_internal_options.conf', '/var/ossec/etc/internal_options.conf', '/var/ossec/etc/ossec.conf', '/var/ossec/etc/shared/rootkit_trojans.txt', '/var/ossec/etc/shared/cis_win2012r2_memberL2_rcl.txt', '/var/ossec/etc/shared/win_audit_rcl.txt', '/var/ossec/etc/shared/cis_rhel_linux_rcl.txt', '/var/ossec/etc/shared/cis_mysql5-6_community_rcl.txt', '/var/ossec/etc/shared/win_malware_rcl.txt', '/var/ossec/etc/shared/cis_sles11_linux_rcl.txt', '/var/ossec/etc/shared/cis_win2012r2_domainL2_rcl.txt', '/var/ossec/etc/shared/cis_mysql5-6_enterprise_rcl.txt', '/var/ossec/etc/shared/cis_rhel5_linux_rcl.txt', '/var/ossec/etc/shared/system_audit_ssh.txt', '/var/ossec/etc/shared/cis_sles12_linux_rcl.txt', '/var/ossec/etc/shared/cis_apache2224_rcl.txt', '/var/ossec/etc/shared/cis_rhel7_linux_rcl.txt', '/var/ossec/etc/shared/win_applications_rcl.txt', '/var/ossec/etc/shared/system_audit_rcl.txt', '/var/ossec/etc/shared/cis_win2012r2_domainL1_rcl.txt', '/var/ossec/etc/shared/cis_debian_linux_rcl.txt', '/var/ossec/etc/shared/cis_rhel6_linux_rcl.txt', '/var/ossec/etc/shared/cis_win2012r2_memberL1_rcl.txt', '/var/ossec/etc/shared/rootkit_files.txt', '/var/ossec/active-response/bin/firewall-drop', '/var/ossec/active-response/bin/kaspersky.py', '/var/ossec/active-response/bin/route-null', '/var/ossec/active-response/bin/restart-wazuh', '/var/ossec/active-response/bin/ip-customblock', '/var/ossec/active-response/bin/firewalld-drop', '/var/ossec/active-response/bin/default-firewall-drop', '/var/ossec/active-response/bin/pf', '/var/ossec/active-response/bin/restart.sh', '/var/ossec/active-response/bin/host-deny', '/var/ossec/active-response/bin/ipfw', '/var/ossec/active-response/bin/disable-account', '/var/ossec/active-response/bin/wazuh-slack', '/var/ossec/active-response/bin/npf', '/var/ossec/active-response/bin/kaspersky', '/var/ossec/logs/active-responses.log', '/var/ossec/logs/ossec.log', '/var/ossec/queue/syscollector/norm_config.json', '/var/ossec/queue/syscollector/db/local.db-journal', '/var/ossec/queue/syscollector/db/local.db', '/var/ossec/queue/fim/db/fim.db', '/var/ossec/queue/fim/db/fim.db-journal', '/var/ossec/queue/sockets/wmodules', '/var/ossec/queue/sockets/control', '/var/ossec/queue/sockets/com', '/var/ossec/queue/sockets/.wait', '/var/ossec/queue/sockets/upgrade', '/var/ossec/queue/sockets/queue', '/var/ossec/queue/sockets/logcollector', '/var/ossec/queue/sockets/syscheck', '/var/ossec/queue/alerts/cfgaq', '/var/ossec/queue/alerts/execq', '/var/ossec/queue/logcollector/file_status.json'], 'deleted_files': []}
```

Number of files added:
```
print(len(postinstall['added_files']))
```
Print results
```
119
```
---

Uninstall scenario:
1. /var snapshot_pre
2. Wazuh Agent uninstall
3. /var snapshot_post
4. comparison between snapshot_pre and snapshot_post

```
postdelete =  {'changed_files': ['/var/log/dpkg.log', '/var/log/auth.log', '/var/log/syslog', '/var/log/apt/history.log', '/var/log/apt/term.log', '/var/log/journal/ea8d563452674de897687e4c554abfba/system.journal', '/var/lib/dpkg/status', '/var/cache/apt/pkgcache.bin'], 'added_files': [], 'deleted_files': ['/var/lib/dpkg/info/wazuh-agent.postinst', '/var/lib/dpkg/info/wazuh-agent.conffiles', '/var/lib/dpkg/info/wazuh-agent.preinst', '/var/lib/dpkg/info/wazuh-agent.postrm', '/var/lib/dpkg/info/wazuh-agent.templates', '/var/lib/dpkg/info/wazuh-agent.prerm', '/var/lib/dpkg/info/wazuh-agent.shlibs', '/var/lib/dpkg/info/wazuh-agent.list', '/var/lib/dpkg/info/wazuh-agent.md5sums', '/var/ossec/ruleset/sca/cis_ubuntu22-04.yml', '/var/ossec/wodles/utils.py', '/var/ossec/wodles/__init__.py', '/var/ossec/wodles/aws/aws-s3', '/var/ossec/wodles/azure/orm.py', '/var/ossec/wodles/azure/azure-logs', '/var/ossec/wodles/docker/DockerListener', '/var/ossec/wodles/gcloud/exceptions.py', '/var/ossec/wodles/gcloud/integration.py', '/var/ossec/wodles/gcloud/tools.py', '/var/ossec/wodles/gcloud/gcloud', '/var/ossec/wodles/gcloud/pubsub/subscriber.py', '/var/ossec/wodles/gcloud/buckets/bucket.py', '/var/ossec/wodles/gcloud/buckets/access_logs.py', '/var/ossec/var/run/wazuh-syscheckd-120670.pid', '/var/ossec/var/run/wazuh-agentd.state', '/var/ossec/var/run/wazuh-agentd-120657.pid', '/var/ossec/var/run/wazuh-execd-120646.pid', '/var/ossec/var/run/wazuh-modulesd-120700.pid', '/var/ossec/var/run/wazuh-logcollector-120683.pid', '/var/ossec/var/run/wazuh-logcollector.state', '/var/ossec/var/selinux/wazuh.pp', '/var/ossec/agentless/register_host.sh', '/var/ossec/agentless/ssh_integrity_check_linux', '/var/ossec/agentless/ssh_asa-fwsmconfig_diff', '/var/ossec/agentless/sshlogin.exp', '/var/ossec/agentless/ssh_foundry_diff', '/var/ossec/agentless/ssh_generic_diff', '/var/ossec/agentless/main.exp', '/var/ossec/agentless/su.exp', '/var/ossec/agentless/ssh.exp', '/var/ossec/agentless/ssh_pixconfig_diff', '/var/ossec/agentless/ssh_nopass.exp', '/var/ossec/agentless/ssh_integrity_check_bsd', '/var/ossec/bin/wazuh-control', '/var/ossec/bin/agent-auth', '/var/ossec/bin/wazuh-agentd', '/var/ossec/bin/wazuh-logcollector', '/var/ossec/bin/wazuh-modulesd', '/var/ossec/bin/manage_agents', '/var/ossec/bin/wazuh-syscheckd', '/var/ossec/bin/wazuh-execd', '/var/ossec/lib/libsysinfo.so', '/var/ossec/lib/libstdc++.so.6', '/var/ossec/lib/libwazuhshared.so', '/var/ossec/lib/libfimdb.so', '/var/ossec/lib/libsyscollector.so', '/var/ossec/lib/librsync.so', '/var/ossec/lib/libwazuhext.so', '/var/ossec/lib/libgcc_s.so.1', '/var/ossec/lib/libdbsync.so', '/var/ossec/etc/client.keys', '/var/ossec/etc/localtime', '/var/ossec/etc/wpk_root.pem', '/var/ossec/etc/local_internal_options.conf', '/var/ossec/etc/internal_options.conf', '/var/ossec/etc/ossec.conf', '/var/ossec/etc/shared/rootkit_trojans.txt', '/var/ossec/etc/shared/cis_win2012r2_memberL2_rcl.txt', '/var/ossec/etc/shared/win_audit_rcl.txt', '/var/ossec/etc/shared/cis_rhel_linux_rcl.txt', '/var/ossec/etc/shared/cis_mysql5-6_community_rcl.txt', '/var/ossec/etc/shared/win_malware_rcl.txt', '/var/ossec/etc/shared/cis_sles11_linux_rcl.txt', '/var/ossec/etc/shared/cis_win2012r2_domainL2_rcl.txt', '/var/ossec/etc/shared/cis_mysql5-6_enterprise_rcl.txt', '/var/ossec/etc/shared/cis_rhel5_linux_rcl.txt', '/var/ossec/etc/shared/system_audit_ssh.txt', '/var/ossec/etc/shared/cis_sles12_linux_rcl.txt', '/var/ossec/etc/shared/cis_apache2224_rcl.txt', '/var/ossec/etc/shared/cis_rhel7_linux_rcl.txt', '/var/ossec/etc/shared/win_applications_rcl.txt', '/var/ossec/etc/shared/system_audit_rcl.txt', '/var/ossec/etc/shared/cis_win2012r2_domainL1_rcl.txt', '/var/ossec/etc/shared/cis_debian_linux_rcl.txt', '/var/ossec/etc/shared/cis_rhel6_linux_rcl.txt', '/var/ossec/etc/shared/cis_win2012r2_memberL1_rcl.txt', '/var/ossec/etc/shared/rootkit_files.txt', '/var/ossec/active-response/bin/firewall-drop', '/var/ossec/active-response/bin/kaspersky.py', '/var/ossec/active-response/bin/route-null', '/var/ossec/active-response/bin/restart-wazuh', '/var/ossec/active-response/bin/ip-customblock', '/var/ossec/active-response/bin/firewalld-drop', '/var/ossec/active-response/bin/default-firewall-drop', '/var/ossec/active-response/bin/pf', '/var/ossec/active-response/bin/restart.sh', '/var/ossec/active-response/bin/host-deny', '/var/ossec/active-response/bin/ipfw', '/var/ossec/active-response/bin/disable-account', '/var/ossec/active-response/bin/wazuh-slack', '/var/ossec/active-response/bin/npf', '/var/ossec/active-response/bin/kaspersky', '/var/ossec/logs/active-responses.log', '/var/ossec/logs/ossec.log', '/var/ossec/queue/syscollector/norm_config.json', '/var/ossec/queue/syscollector/db/local.db-journal', '/var/ossec/queue/syscollector/db/local.db', '/var/ossec/queue/fim/db/fim.db', '/var/ossec/queue/fim/db/fim.db-journal', '/var/ossec/queue/sockets/wmodules', '/var/ossec/queue/sockets/control', '/var/ossec/queue/sockets/com', '/var/ossec/queue/sockets/.wait', '/var/ossec/queue/sockets/upgrade', '/var/ossec/queue/sockets/queue', '/var/ossec/queue/sockets/logcollector', '/var/ossec/queue/sockets/syscheck', '/var/ossec/queue/alerts/cfgaq', '/var/ossec/queue/alerts/execq', '/var/ossec/queue/logcollector/file_status.json']}
```

Number of files deleted:
```
print(len(postdelete['deleted_files'])
```

Print results
```
120
```

**Comment by pro-akim** [comment]
## Update
Moving to an issue with higher priority.

**Comment by pro-akim** [comment]
## Update
Considering the highlighted point in https://github.com/wazuh/wazuh-qa/issues/4843#issuecomment-1941938284, depending on the test, the provision should receive variables from installing only the manager, only the dependencies and libraries or those tasks should be handled by the test module as well. This point should be discussed with the team.

**Comment by pro-akim** [comment]
## Update
Created install and uninstall + file verification system.

Regarding the check-file, some changes were applied:
1. Hashing: The hashing methods have failed. Some files used were too unstable to hash the file.
2. As the method is install (create new files) and uninstall (delete created files), I was able to find a common pattern of those files. This pattern is that they have wazuh or ossec in the path or file name. This point will be used as validation.
3. All methods were tested and applied.

It only remains to add the new parameters required for the installation and uninstallation methods

**Comment by pro-akim** [comment]
## Update 

Changes done

**Comment by pro-akim** [comment]
## Update

The merge between the old and new branches remained pending

**Comment by pro-akim** [comment]
## Update
Testing Merge

**Comment by pro-akim** [comment]
## Summary

Some points to keep in mind:

1. Install installs, register registers and uninstall uninstalls so there is an order to follow

If the list of tests does not include install, the agent must be provisioned from provisioning

Otherwise, if it is installed, it will need to go first.

2. Register registers the agent, if one_line = False, the register will change the MANAGER_IP to the corresponding ip and restart.
In case of one_line = True, only the system will be rebooted

3. Uninstall should go last in case it is executed since it uninstalls the system.

4. Stop does stop, but a restart has been added at the end of the test

5. If a test series was run and the manager contains the agent information. If you execute register on that manager with the agent registration, it may fail, since the agent must be deleted from the manager.
Otherwise the clientkey may take time (by product design) to replace the dead agent with the new one with the same name and the same ip

6. Once https://github.com/wazuh/wazuh-qa/issues/4859 is completed, where the provisioning of the agent includes the installation of the dependencies, the modules/testing/setup.yml file must be restored

**Comment by pro-akim** [comment]
## Update

Requested fixes done and tested

**Comment by QU3B1M** [comment]
LGTM!

**Comment by pro-akim** [comment]
## Update
Some error handling test will be done

**Comment by pro-akim** [comment]
## Update

Testing Error logs:

|N|Error|Log|Status|
|--|--|--|--|
|1|Wrong inventory|pydantic_core._pydantic_core.ValidationError: 1 validation error for InputPayload|:green_circle:
|2|Wrong component| main.py: error: argument --component: invalid choice: 'agento' (choose from 'manager', 'agent')|:green_circle:
|3|Wrong dependencies entry| FileNotFoundError: File "/tmp/dtt1-poc/no_manager-linux-ubuntu-22.04-amd64/inventory.yaml" not found.|:green_circle:
|4|Wrong live| pydantic_core._pydantic_core.ValidationError: 1 validation error for InputPayload live|:green_circle:
|5|Wrong one_line| pydantic_core._pydantic_core.ValidationError: 1 validation error for InputPayload one_line |:green_circle:
|6| Wrong test name| Error is present, but not hanled|:red_circle:

**Comment by pro-akim** [comment]
## Update

Install

After obtaining all the files generated in var and comparing them with the pre install files, we could see that (except for those that contained ossec or wazuh in their path)

<details><summary>Rhel7</summary>

```
['/var/lib/rpm/__db.001', '/var/cache/yum/x86_64/7Server/epel/metalink.xml', '/var/cache/yum/x86_64/7Server', '/var/cache/yum/x86_64/7Server/epel/228b14c6993c17f29d685c24f81902ab92cb1d3eb1b219fd2db396c5db656751-updateinfo.xml.bz2', '/var/cache/yum/x86_64/7Server/epel/645d6e0f00f5e7cdebd5d547c1a11506048edf6505cf30c01554e4255b2456ad-comps-Everything.x86_64.xml.gz', '/var/cache/yum/x86_64', '/var/cache/yum/x86_64/7Server/epel/packages', '/var/log/yum.log', '/var/cache/yum/x86_64/7Server/timedhosts', '/var/lib/rpm/__db.002', '/var/cache/yum/x86_64/7Server/epel/cachecookie', '/var/cache/yum/x86_64/7Server/epel/repomd.xml', '/var/cache/yum/x86_64/7Server/epel', '/var/cache/yum/x86_64/7Server/epel/686ce8ed6fe8321eec6c42a4cf164265e2ffc78268818d131813b142b860ee0f-primary.sqlite.bz2', '/var/cache/yum/x86_64/7Server/epel/gen', '/var/cache/yum/x86_64/7Server/epel/gen/primary_db.sqlite', '/var/lib/rpm/__db.003']
```

</details>


<details><summary>Ubuntu18.04</summary>

```
['/var/lib/lxcfs/cgroup/pids/user.slice/user-1000.slice/session-55.scope/cgroup.clone_children', '/var/lib/lxcfs/cgroup/pids/user.slice/user-1000.slice/session-55.scope/pids.current', '/var/lib/lxcfs/cgroup/pids/user.slice/user-1000.slice/session-55.scope/cgroup.procs', '/var/lib/lxcfs/cgroup/name=systemd/user.slice/user-1000.slice/session-55.scope/cgroup.clone_children', '/var/lib/lxcfs/cgroup/name=systemd/user.slice/user-1000.slice/session-55.scope/tasks', '/var/lib/lxcfs/cgroup/name=systemd/user.slice/user-1000.slice/session-55.scope/cgroup.procs', '/var/lib/lxcfs/cgroup/pids/user.slice/user-1000.slice/session-55.scope', '/var/lib/lxcfs/cgroup/pids/user.slice/user-1000.slice/session-55.scope/pids.max', '/var/lib/lxcfs/cgroup/pids/user.slice/user-1000.slice/session-55.scope/notify_on_release', '/var/lib/lxcfs/cgroup/pids/user.slice/user-1000.slice/session-55.scope/pids.events', '/var/lib/lxcfs/cgroup/name=systemd/user.slice/user-1000.slice/session-55.scope', '/var/lib/lxcfs/cgroup/name=systemd/user.slice/user-1000.slice/session-55.scope/notify_on_release', '/var/lib/lxcfs/cgroup/pids/user.slice/user-1000.slice/session-55.scope/tasks']
```

</details>


<details><summary>Debian12</summary>

```
['/var/log/dpkg.log']
```

</details>

<details><summary>Oracle9</summary>

```
['/var/lib/selinux/targeted/active/modules/disabled', '/var/log/dnf.log', '/var/cache/dnf/ol9_developer_EPEL-31156a4a0bdc10c2/tmpdir.8Hy41i/repodata/59bd9acc641d81ca06a9cda14adba6a2e02ab1ac-filelists.xml.gz', '/var/cache/dnf/ol9_developer_EPEL-31156a4a0bdc10c2/tmpdir.8Hy41i/repodata/2aec878d4765a214e29bb7b62b54470ce281110f-primary.xml.gz', '/var/cache/dnf/ol9_developer_EPEL-31156a4a0bdc10c2/tmpdir.8Hy41i/repodata/53816cf5147400235d31ae75d3467935d1ced86e-updateinfo.xml.gz', '/var/cache/dnf/ol9_developer_EPEL-31156a4a0bdc10c2/tmpdir.8Hy41i', '/var/cache/dnf/ol9_developer_EPEL-31156a4a0bdc10c2/tmpdir.8Hy41i/repodata', '/var/cache/dnf/metadata_lock.pid', '/var/lib/selinux/targeted/active/modules/400', '/var/cache/dnf/ol9_developer_EPEL-31156a4a0bdc10c2/tmpdir.8Hy41i/repodata/repomd.xml']
```

</details>


<details><summary>Amazonlinux2</summary>

```
[]
```

</details>

<details><summary>SUSE15</summary>

```
[]
```

</details>

<details><summary>Fedora38</summary>

```
[]
```

</details>

<details><summary>Centos7</summary>

```
['/var/cache/yum/x86_64/7/base/packages', '/var/cache/yum/x86_64/7/base/cachecookie', '/var/cache/yum/x86_64/7/updates/9c12a6244db35e0d9ba3110b417fc06e8a28196a9bdd43d5e22c48d99b39e619-primary.sqlite.bz2', '/var/cache/yum/x86_64/7/updates/repomd.xml', '/var/lib/rpm/__db.001', '/var/cache/yum/x86_64/7/extras/cachecookie', '/var/cache/yum/x86_64/7/timedhosts.txt', '/var/cache/yum/x86_64', '/var/cache/yum/x86_64/7/base/gen', '/var/log/yum.log', '/var/cache/yum/x86_64/7/timedhosts', '/var/cache/yum/x86_64/7/base/repomd.xml', '/var/lib/yum/repos/x86_64/7/updates', '/var/cache/yum/x86_64/7/base/mirrorlist.txt', '/var/cache/yum/x86_64/7/base', '/var/cache/yum/x86_64/7/base/gen/primary_db.sqlite', '/var/cache/yum/x86_64/7/updates/gen', '/var/cache/yum/x86_64/7', '/var/lib/rpm/__db.003', '/var/cache/yum/x86_64/7/updates', '/var/cache/yum/x86_64/7/updates/mirrorlist.txt', '/var/cache/yum/x86_64/7/extras/packages', '/var/lib/yum/repos/x86_64/7/base', '/var/cache/yum/x86_64/7/updates/cachecookie', '/var/cache/yum/x86_64/7/extras/0a5413843d4b238fd3894be760ed384be82139b517ce77a3a71a7b3c6a774a8b-primary.sqlite.bz2', '/var/cache/yum/x86_64/7/base/6d0c3a488c282fe537794b5946b01e28c7f44db79097bb06826e1c0c88bad5ef-primary.sqlite.bz2', '/var/cache/yum/x86_64/7/extras/repomd.xml', '/var/cache/yum/x86_64/7/extras/mirrorlist.txt', '/var/cache/yum/x86_64/7/extras', '/var/lib/yum/repos/x86_64/7/extras', '/var/cache/yum/x86_64/7/base/a4e2b46586aa556c3b6f814dad5b16db5a669984d66b68e873586cd7c7253301-c7-x86_64-comps.xml.gz', '/var/lib/rpm/__db.002', '/var/cache/yum/x86_64/7/updates/packages', '/var/cache/yum/x86_64/7/extras/gen']
```

</details>

<details><summary>Rocky9</summary>

```
[]
```
</details>

Same additional filters will be added to https://github.com/wazuh/wazuh-qa/issues/4844#issuecomment-1983070759

**Comment by pro-akim** [comment]
## Update

New changes are required due to the new requirements.

**Comment by pro-akim** [comment]
## Update

Tests were created
During testing, some additional filters for checkfiles were required in uninstall process.

Those filters were in /boot directory

filter_data = {'/boot': {'added': ['grub2', 'loader', 'vmlinuz', 'System.map', 'config-', 'initramfs'], 'removed': [], 'modified': ['grubenv']}, '/usr/bin': {'added': ['filebeat'], 'removed': [], 'modified': []}, '/root': {'added': ['trustdb.gpg'], 'removed': [], 'modified': []}, '/usr/sbin': {'added': [], 'removed': [], 'modified': []}}

**Comment by pro-akim** [comment]
## Update

|Os|Result|Adjustments|
|--|---|--|
|ubuntu 16.04|:green_circle:|-
|ubuntu 18.04|:green_circle:|-
|ubuntu 20.04|:green_circle:|-
|ubuntu 22.04|:green_circle:|-
|debian 9|:green_circle:|-
|debian 10|:green_circle:|-
|debian 11|:green_circle:|-
|debian 12|:green_circle:|-
|centos 7|:green_circle:|-
|centos 8|:green_circle:|-
|redhat 7|:green_circle:|-
|redhat 8|:green_circle:|-
|redhat 9|:green_circle:|-
|oracle 9|:green_circle:|Filters added
|amazon2|:green_circle:|-
|opensuse 15|:green_circle:|zyp uninstallation added

**Comment by pro-akim** [comment]
## Update

Testing in AWS

**Comment by rauldpm** [comment]
Meet defined: `Sync allocation module` - `Wednesday, March 20⋅8:00 – 8:30pm`
Changed status to Blocked for third-party

**Comment by pro-akim** [comment]
## Update
Testing in AWS
1. Port added in the command, the AWS instance has worked in 2200 instead of 22 due to https://github.com/wazuh/wazuh-qa/pull/5027

**Comment by pro-akim** [comment]
## Update
Changes done. Moved to pending review

**Comment by fcaffieri** [comment]
LGTM
