### ISSUE TITLE
DTT1 - Iteration 3 - Observability module - Implement pytest-influxdb plugin for the tests

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/wazuh-qa#4845]
> EPIC: #4837

## Description

This issue aims to implement the `pytest-influxdb` plugin to obtain information about the execution of the tests in a friendly and centralized way for the end user.

## Tasks

- [ ] Implement the plugin
- [ ] Set up the test to expose the information to the InfluxDB
- [ ] Use the same InfluxDB defined in the Observability module

**Comment by fcaffieri** [comment]
This issue is closed as it will be addressed at https://github.com/wazuh/wazuh-qa/issues/5078
