### ISSUE TITLE
DTT2 - Jenkins - Pipeline

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/wazuh-qa#4849]
> Epic: https://github.com/wazuh/wazuh-qa/issues/4495

---

## Description

The objective of this issue is to adapt the Jenkins pipeline to execute the TaskFlow.

## Tasks

- [ ] Adapt the Jenkins pipeline to execute the Taskflow with dry-run to generate the DAG
- [ ] Adapt the Jenkins pipeline to execute the Taskflow to stop the process running
- [ ] Fix paths to the scripts

**Comment by rauldpm** [comment]
Moved to tier 2

**Comment by damarisg** [comment]
Worked on https://github.com/wazuh/wazuh-jenkins/issues/5927
