### ISSUE TITLE
DTT1 - Iteration 3 - Provision module improvements and fixes

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/wazuh-qa#4852]
> Epic: https://github.com/wazuh/wazuh-qa/issues/4495

---

## Description

The objective of this issue is to make the improvements and findings detected in iteration 2 on the Provision module.

## Tasks

- [x] https://github.com/wazuh/wazuh-qa/issues/4851
- [x] https://github.com/wazuh/wazuh-qa/issues/4853
- [x] https://github.com/wazuh/wazuh-qa/issues/4857
- [x] https://github.com/wazuh/wazuh-qa/issues/4858
- [x] https://github.com/wazuh/wazuh-qa/issues/4859 
- [x] https://github.com/wazuh/wazuh-qa/issues/4861
- [x] https://github.com/wazuh/wazuh-qa/issues/4903
- [x] #4940

**Comment by fcaffieri** [comment]
Move to on hold due to this [issue](https://github.com/wazuh/wazuh-qa/issues/4908) have priority

**Comment by fcaffieri** [comment]
Move to In progress due to https://github.com/wazuh/wazuh-qa/issues/4905 was finished.

**Comment by rauldpm** [comment]
LGTM
