### ISSUE TITLE
DTT1 - Iteration 3 - Provision module - Improvement support actions

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/wazuh-qa#4853]
> Epic: https://github.com/wazuh/wazuh-qa/issues/4852

---

## Description

The goal of this issue is to add the uninstall action for any component sent by parameter.

## Tasks

- [x] Add the new parameter
- [x] Add Jinja2 templates.
- [x] Add implementation of the new uninstall action
- [x] Add new `Action` class
- [x] Add new `componentType` class
- [x] Remove custom credentials

**Comment by fcaffieri** [comment]
### Update

Some new classes were generated to facilitate the management of actions on the provision.
A new action class that is inherited by the install and uninstall classes and gives the possibility to add more:

```
classAction:
     def __init__(self, component_type):
         self.component_type = component_type

     def execute(self):
         pass

class Install(Action):
     def __init__(self, component_type):
         super().__init__(component_type)

     def execute(self):
         # Logic for installation using Ansible and Jinja2 templates
         pass

class Uninstall(Action):
     def __init__(self, component_type):
         super().__init__(component_type)

     def execute(self):
         # Logic for uninstallation using Ansible and Jinja2 templates
         pass
```
and a new component_type class:

```


class ComponentType:
     def __init__(self):
         pass

     def get_template_path(self):
         # Abstract method to get the template path
         pass

class Package(ComponentType):
     def __init__(self):
         super().__init__()

     def get_template_path(self):
         # Logic to obtain the template path for packages
         pass

class AIO(ComponentType):
     def __init__(self):
         super().__init__()

     def get_template_path(self):
         # Logic to obtain the template path for AIO
         pass

```

The implementation of these new classes within the provision is being finalized, to then move on to unit testing.

**Comment by fcaffieri** [comment]
### Update

Performing unit tests on changes in the provision structure and the addition of uninstall

**Comment by fcaffieri** [comment]
### Update

Improve the way we define the task, only with modification in the provision module:

![image](https://github.com/wazuh/wazuh-qa/assets/89791732/8bb6f810-fd8c-4c9a-9482-fc0b6184dfa9)


Testing the module, I encounter some problems and errors with the new structure such as:

- Only admit 1 action for the execution of the provision.
- Review the way we set the inventories.
- Improve the Pydantic validation, now generate the object `componentTyppe` that will be used by the Action class.
- Fix the manager IP configuration into the agent.

**Comment by QU3B1M** [comment]
LGTM!
