### ISSUE TITLE
DTT1 - Iteration 3 - Allocation module

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#4855]
> Epic #4495

## Description
This issue aims to list all the subtask that need to be completed in order to meet the **Allocation module** requirements for **DTT1** _Iteration 3_

### Tasks

For CICD team:
- [x] #4854 
- [x] #4862
- [x] #4863
- [x] #4864
- [x] #4865
- [x] #4866
- [x] #4867
- [x] #4870
- [x] #4874
- [x] #4901
- [x] #4988
- [x] #4933
- [x] #4934
- [x] #4928
- [x] https://github.com/wazuh/wazuh-automation/issues/1546
- [x] https://github.com/wazuh/wazuh-qa/issues/5085
- [x] https://github.com/wazuh/wazuh-qa/issues/5084
- [x] https://github.com/wazuh/wazuh-qa/issues/5142
- [x] https://github.com/wazuh/wazuh-qa/issues/5161
