### ISSUE TITLE
DTT1 - Iteration 3 - Provision module - Allow installing any version of wazuh with Package

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/wazuh-qa#4857]
> Epic: https://github.com/wazuh/wazuh-qa/issues/4852

---

## Description

The objective of this issue is to allow the installation of any version of Wazuh with the package manager. Currently, it allows it only with AIO.

## Tasks

- [x] Allow installing a version of Wazuh sent by parameter.
- [x] Implement the logic and modify Jinja2 templates as necessary.
- [x] Extra not planned: Fix AIO certificate generation.
- [x] Extra not planned: Fix quick start installation due to the module separations and old versions

**Comment by fcaffieri** [comment]
### Update report

The changes made to the branch are already there, but I have had some errors:

- After an extensive reserach I have an error when installing with the wizard on a version other than the live one, due to a problem of arriving that tries to download from the release repo and must go to the in release.

```
stderr: 'E: The repository ''https://packages-dev.wazuh.com/pre-release/apt stable Release'' does not have a Release file.'
   stderr_lines: <omitted>
   stdout: |-
     Hit:1 http://us.archive.ubuntu.com/ubuntu focal InRelease
     Get:2 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
     Hit:3 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease
     Get:4 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [3,058 kB]
     Get:5 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
     Ign:6 https://packages-dev.wazuh.com/pre-release/apt stable InRelease
     Err:7 https://packages-dev.wazuh.com/pre-release/apt stable Release
       404 Not Found [IP: 65.8.248.12 443]
     Get:8 http://us.archive.ubuntu.com/ubuntu focal-updates/main i386 Packages [926 kB]
     Get:9 http://security.ubuntu.com/ubuntu focal-security/main i386 Packages [700 kB]
     Get:10 http://us.archive.ubuntu.com/ubuntu focal-updates/main Translation-en [493 kB]
     Get:11 http://us.archive.ubuntu.com/ubuntu focal-updates/restricted amd64 Packages [2,619 kB]
     Get:12 http://us.archive.ubuntu.com/ubuntu focal-updates/restricted i386 Packages [36.8 kB]
     Get:13 http://us.archive.ubuntu.com/ubuntu focal-updates/restricted Translation-en [365 kB]
     Get:14 http://us.archive.ubuntu.com/ubuntu focal-updates/universe i386 Packages [771 kB]
     Get:15 http://us.archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [1,160 kB]
     Get:16 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages [2,679 kB]
     Get:17 http://us.archive.ubuntu.com/ubuntu focal-updates/universe Translation-en [279 kB]
     Get:18 http://security.ubuntu.com/ubuntu focal-security/main Translation-en [410 kB]

```

- The installation with the wizard has a problem that does not generate the certificates, therefore the manager manages to raise it, working on the creation of the certificates:

```
  stdout: |-
     02/01/2024 20:55:30 INFO: Starting Wazuh installation assistant. Wazuh version: 4.6.0
     02/01/2024 20:55:30 INFO: Verbose logging redirected to /var/log/wazuh-install.log
     02/01/2024 20:55:47 ERROR: Cannot find /home/vagrant/wazuh-install-files.tar. Run the script with the option -g|--generate-config-files to create it or copy it from another node.
   stdout_lines: <omitted>
```


The following tests were carried out:

| tests | result |
| :-- | :-- |
| Test manager with package live | OK |
| Test manager with AIO live | Problem with certificates |
| Test manager with package old version | OK |
| Test manager with AIO old version | Problem with certificates |
| Test manager with package pre-release version | Problem with you set repo stable |
| Test manager with AIO with pre-release version | Problem with certificates |
| Test agent with package live | OK |
| Test agent with AIO live | Problem with certificates |
| Test agent with package old version | OK |
| Test agent with AIO old version | Problem with certificates |
| Test agent with package pre-release version | Problem with the set repo stable |
| Test agent with AIO with pre-release version | OK because it did not exist AIO set by default package |

**Comment by fcaffieri** [comment]
### Update report

- Allow installing a version of Wazuh sent by parameter. Done
-  Implement the logic and modify Jinja2 templates as necessary. Done
- Extra not planned: Fix AIO certificate generation. (WIP)
- Extra not planned: Fix quick start installation due to the module separations and old versions (Pending)

**Comment by fcaffieri** [comment]
Move to In progress due to https://github.com/wazuh/wazuh-qa/issues/4905 was finished.

**Comment by fcaffieri** [comment]
This issue will be Blocked by this [other issue](https://github.com/wazuh/wazuh-qa/issues/4859), due to a refactor into some class of the provision module

**Comment by QU3B1M** [comment]
LGTM!
