### ISSUE TITLE
DTT2 - Provision module - Validate dependencies according macOS and Windows systems

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/wazuh-qa#4860]
> Epic: https://github.com/wazuh/wazuh-qa/issues/4852

---

## Description

The objective of this issue is to validate that the dependencies of each system are correct to execute the tests.

OS to validate:

| Operating System           | Version                | Component                          | Architectures           |
|----------------------------|------------------------|------------------------------------|-------------------------|
| macOS                    | Ventura                | agents                             | x86_64, aarch64         |
| macOS                    | Sonoma                 | agents                             | x86_64, aarch64         |
|Windows| -- | agents| x86_64|

## Tasks

- [ ] Validate that the dependencies for the OS in Vagrant work
- [ ] Validate that the dependencies for the OS in AWS work
- [ ] Adapt the dependencies required by the tests for each OS

**Comment by fcaffieri** [comment]
Issue is moved to the next tier, since macOS instances are not available due to allocation.
