### ISSUE TITLE
DTT1 - Iteration 3 - Allocation module - Standardize models, composite-names & sizes

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#4867]
> Epic #4495

## Description
This issue aims to review and set standards for the `composite-names`, `sizes` and `models` that will be used by the tool.

### Tasks
- [x] Standardize `composite-names` for all the providers
- [x] Standardize `sizes` for all the providers
- [x] Set a generic `Inventory` model for all the modules to use
  > Now each module has an Inventory defined "locally", we need a generic model used on every module

**Comment by QU3B1M** [comment]
The objectives of this issue have already been met by other developments.
