### ISSUE TITLE
DTT1 - Iteration 3 - Test module - Multiple dependencies in InputPayload

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#4880]
> Epic #4495

## Description
This issue aims to add support for multiple dependencies in the Test InputPayload
### Tasks
- [ ] Modify the `InputPayload` & `ExtraVars` models
- [ ] Modify `Tester` class to get the IP of every dependency received and configure the `ExtraVars` with it
- [ ] Update the workflow's .yaml to send a list of key values (`component_name: inventory_path`)
- [ ] Update test.yml template to receive the `dependencies` argument

**Comment by QU3B1M** [comment]
```python
class ExtraVars(BaseModel):
    """Extra vars for testing module."""
    component: Literal['manager', 'agent']
    dependencies: list[dict] | None = None
    wazuh_version: str
    wazuh_revision: str
    wazuh_branch: str | None = None
    working_dir: str = '/tmp/tests'


class InputPayload(ExtraVars):
    """Input payload for testing module."""
    tests: list[str]
    inventory: Path
    dependency: list[dict] = None # Dict comes component: inventory_path
    cleanup: bool = True
```

**Comment by pro-akim** [comment]
Running it with some additional prints (for testing) with the following command:

-  print(extra_vars)
```
    @classmethod
    def run(cls, payload: InputPayload) -> None:
        payload = InputPayload(**dict(payload))
        inventory = Inventory(**Utils.load_from_yaml(payload.inventory))
        extra_vars = cls._get_extra_vars(payload).model_dump()

        extra_vars_list = []
        dependencies = extra_vars['dependencies']
        for dep_key, dep_value in dependencies.items():
            new_dict = extra_vars.copy()
            new_dict['dependencies'] = {dep_key: dep_value}
            extra_vars_list.append(new_dict)

        print(extra_vars)
        for extra_vars in extra_vars_list:
            ansible = Ansible(ansible_data=inventory.model_dump())
            cls._setup(ansible, extra_vars['working_dir'])
            cls._run_tests(payload.tests, ansible, extra_vars)
            if payload.cleanup:
                cls._cleanup(ansible, extra_vars['working_dir'])
```
- print(rendering_var)
```
    @classmethod
    def _run_tests(cls, test_list: list[str], ansible: Ansible, extra_vars: ExtraVars) -> None:
        for test in test_list:
            rendering_var = {**extra_vars, 'test': test}
            print(rendering_var)
            template = str(ansible.playbooks_path / cls._test_template)
            playbook = ansible.render_playbook(template, rendering_var)
            if not playbook:
                print(f'ERROR: Playbook for test "{test}" not found')
                continue
            ansible.run_playbook(playbook, extra_vars)
```

Using the following command:

```
(deployability) akim@akim-PC:~/Desktop/wazuh-qa/deployability$ python3 launchers/test.py --inventory /tmp/dtt1-poc/agent-linux-ubuntu-22.04-amd64/inventory.yaml --dependencies '{"manager": "/tmp/dtt1-poc/manager-linux-ubuntu-22.04-amd64/inventory.yaml", "agent": "/tmp/dtt1-poc/agent-linux-ubuntu-22.04-amd64/inventory.yaml" }' --tests install --wazuh-version 4.7.1 --wazuh-revision 1 --component agent
```

It is possible to see that 

- Result of print(extra_vars)
```
{'component': 'agent', 'dependencies': {'manager': '127.0.0.2', 'agent': '127.0.0.1'}, 'wazuh_version': '4.7.1', 'wazuh_revision': '1', 'wazuh_branch': None, 'working_dir': '/tmp/tests'}
```

- Result of print(rendering_var)
```
{'component': 'agent', 'dependencies': {'manager': '127.0.0.2'}, 'wazuh_version': '4.7.1', 'wazuh_revision': '1', 'wazuh_branch': None, 'working_dir': '/tmp/tests', 'test': 'install'}
```

- Result of print(rendering_var)
```
{'component': 'agent', 'dependencies': {'agent': '127.0.0.1'}, 'wazuh_version': '4.7.1', 'wazuh_revision': '1', 'wazuh_branch': None, 'working_dir': '/tmp/tests', 'test': 'install'}
```


<details><summary>Complete result</summary>

```
{'component': 'agent', 'dependencies': {'manager': '127.0.0.2', 'agent': '127.0.0.1'}, 'wazuh_version': '4.7.1', 'wazuh_revision': '1', 'wazuh_branch': None, 'working_dir': '/tmp/tests'}
No config file found; using defaults

PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [127.0.0.1]

TASK [Create test directory] ***************************************************
changed: [127.0.0.1] => changed=true 
  gid: 0
  group: root
  mode: '0755'
  owner: root
  path: /tmp/tests
  size: 4096
  state: directory
  uid: 0

TASK [Copy files to endpoints] *************************************************
changed: [127.0.0.1] => changed=true 
  dest: /tmp/tests/
  src: /home/akim/Desktop/wazuh-qa/deployability/modules/testing/tests/

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=3    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
{'component': 'agent', 'dependencies': {'manager': '127.0.0.2'}, 'wazuh_version': '4.7.1', 'wazuh_revision': '1', 'wazuh_branch': None, 'working_dir': '/tmp/tests', 'test': 'install'}
No config file found; using defaults

PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [127.0.0.1]

TASK [Test install for agent] **************************************************
fatal: [127.0.0.1]: FAILED! => changed=true 
  cmd:
  - pytest
  - test_agent/test_install.py
  - -v
  - --wazuh_version=4.7.1
  - --component=agent
  - '--dependencies={manager:'
  - 127.0.0.2}
  delta: '0:00:00.256073'
  end: '2024-01-26 09:07:56.915496'
  msg: non-zero return code
  rc: 4
  start: '2024-01-26 09:07:56.659423'
  stderr: |-
    /usr/local/lib/python3.10/dist-packages/_pytest/config/__init__.py:331: PluggyTeardownRaisedWarning: A plugin raised an exception during an old-style hookwrapper teardown.
    Plugin: helpconfig, Hook: pytest_cmdline_parse
    UsageError: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
    pytest: error: unrecognized arguments: --dependencies={manager: 127.0.0.2}
      inifile: None
      rootdir: /tmp/tests
    For more information see https://pluggy.readthedocs.io/en/stable/api_reference.html#pluggy.PluggyTeardownRaisedWarning
      config = pluginmanager.hook.pytest_cmdline_parse(
    ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
    pytest: error: unrecognized arguments: --dependencies={manager: 127.0.0.2}
      inifile: None
      rootdir: /tmp/tests
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
No config file found; using defaults

PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [127.0.0.1]

TASK [Clean test directory] ****************************************************
changed: [127.0.0.1] => changed=true 
  path: /tmp/tests
  state: absent

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
No config file found; using defaults

PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [127.0.0.1]

TASK [Create test directory] ***************************************************
changed: [127.0.0.1] => changed=true 
  gid: 0
  group: root
  mode: '0755'
  owner: root
  path: /tmp/tests
  size: 4096
  state: directory
  uid: 0

TASK [Copy files to endpoints] *************************************************
changed: [127.0.0.1] => changed=true 
  dest: /tmp/tests/
  src: /home/akim/Desktop/wazuh-qa/deployability/modules/testing/tests/

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=3    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
{'component': 'agent', 'dependencies': {'agent': '127.0.0.1'}, 'wazuh_version': '4.7.1', 'wazuh_revision': '1', 'wazuh_branch': None, 'working_dir': '/tmp/tests', 'test': 'install'}
No config file found; using defaults

PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [127.0.0.1]

TASK [Test install for agent] **************************************************
fatal: [127.0.0.1]: FAILED! => changed=true 
  cmd:
  - pytest
  - test_agent/test_install.py
  - -v
  - --wazuh_version=4.7.1
  - --component=agent
  - '--dependencies={agent:'
  - 127.0.0.1}
  delta: '0:00:00.254978'
  end: '2024-01-26 09:08:12.758850'
  msg: non-zero return code
  rc: 4
  start: '2024-01-26 09:08:12.503872'
  stderr: |-
    /usr/local/lib/python3.10/dist-packages/_pytest/config/__init__.py:331: PluggyTeardownRaisedWarning: A plugin raised an exception during an old-style hookwrapper teardown.
    Plugin: helpconfig, Hook: pytest_cmdline_parse
    UsageError: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
    pytest: error: unrecognized arguments: --dependencies={agent: 127.0.0.1}
      inifile: None
      rootdir: /tmp/tests
    For more information see https://pluggy.readthedocs.io/en/stable/api_reference.html#pluggy.PluggyTeardownRaisedWarning
      config = pluginmanager.hook.pytest_cmdline_parse(
    ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
    pytest: error: unrecognized arguments: --dependencies={agent: 127.0.0.1}
      inifile: None
      rootdir: /tmp/tests
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
No config file found; using defaults

PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [127.0.0.1]

TASK [Clean test directory] ****************************************************
changed: [127.0.0.1] => changed=true 
  path: /tmp/tests
  state: absent

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0  
```

</details>

**Comment by QU3B1M** [comment]
LGTM
