### ISSUE TITLE
DTT1 - Iteration 3 - General improvements - Standard logging 

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/wazuh-qa#4888]
> Epic #4871

## Description

The objective of this issue is to incorporate a standard log for all modules

### Tasks

- [x] Set up a central logger configuration.
- [x] Set up the same log format
- [x] Set logging both by console and by file
- [x] Set logging by module

**Comment by QU3B1M** [comment]
### Generic Logger

- Created a Logger class that generates loggers for the modules or files
    `deployability/modules/generic/logger/logger.py`
    ```python
    import logging
    import yaml
    
    
    class Logger:
        """
        A Logger class that configures and provides a logger using a configuration file.
    
        Attributes:
            logger (logging.Logger): The configured logger.
        """
    
        def __init__(self, name: str) -> None:
            """
            Initializes the Logger object.
    
            Args:
                name (str): The name of the logger.
            """
            self._load_config()
            self.logger = logging.getLogger(name)
    
        def _load_config(self) -> None:
            """
            Loads the logging configuration from 'config.yaml' file.
            """
            with open('config.yaml', 'r') as f:
                config = yaml.safe_load(f.read())
                logging.config.dictConfig(config)
    
        def get_logger(self) -> logging.Logger:
            """
            Returns the configured logger.
    
            Returns:
                logging.Logger: The configured logger.
            """
            return self.logger
    
    ```
- Added a central configuration for the loggers
    `deployability/modules/generic/logger/config.yaml`
    ```yaml
    version: 1
    formatters:
      simple:
        format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        level: DEBUG
        formatter: simple
        filename: /tmp/deployability.log
    root:
      level: DEBUG
      handlers: [console, file]
    ```

#### Usage

This class could generate loggers for specific files or entire modules. E.g:

- Logger for specific file/class:
    `deployability/modules/generic/ansible.py`
    ```python
    ...
    from modules.generic.logger import Logger
        
    class Ansible:
        def __init__(self, ansible_data, path=None):
        ...
        self.logger = Logger(__name__).get_logger()
    ...
    ```
- Logger for a entire module:
    `deployability/modules/allocation/logger.py`
    ```python
    from modules.generic.logger import Logger
    
    logger = Logger("allocator").get_logger()
    
    ```

**Comment by QU3B1M** [comment]
## Update progress

- Implemented logger on generic tools (`ansible` & `scheme_validator`)
- Replaced logger handler of the `workflow_engine` with the new generic logger
- Implemented logger on **Provision** module

**Comment by pro-akim** [comment]
## Review Notes
LGTM

**Comment by fcaffieri** [comment]
Request some improvements and changes [here](https://github.com/wazuh/wazuh-qa/pull/4897#pullrequestreview-1859621502)

**Comment by fcaffieri** [comment]
Because the addition of modifications referring to the IDs of processes and threads requires analysis, these changes will be made in this issue https://github.com/wazuh/wazuh-qa/issues/4907

LGTM
