### ISSUE TITLE
Refactor StatesMonitoring class to utilize API instead of .state files

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#4890]
### Description:

The [CLUSTER-Workload_benchmarks_metrics](https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics) pipeline currently relies on the Wazuh QA library scripts to monitor Wazuh process and daemon statistics. However, a crucial aspect is the utilization of the `wazuh-statistics` script, which currently fetches information through `.state` files instead of utilizing the designated API. This has led to the following issues:

- Presently, certain information related to the analysisd statatistics information is unavailable. For instance, it is not feasible to ascertain the quantity of Vulnerability Detector events has been decoded in the environment.
- The use of `.state` files is planned to be deprecated.

This change is imperative to ensure the acquisition of reliable data for benchmarking the Vulnerability Detector refactor. Further details can be found in the related issue [wazuh/wazuh#20776](https://github.com/wazuh/wazuh/issues/20776).

> [!NOTE]
> Footprint tests were already updated in  https://github.com/wazuh/wazuh-jenkins/issues/4551. We should consider unifiy monitoring tools in order to avoid this discrepancies in the future.

### Tasks to Perform

- [ ] Modify the StatisticsMonitor class and the wazuh-statistic script to utilize the API instead of relying on the deprecated .state files.

### Validation
- [ ] Ensure all the daemons statistics information is obtained in a local testing 
- [ ] Ensure all the daemons statistics information is obtained in the  CLUSTER-Workload_benchmarks_metrics pipeline

**Comment by Deblintrake09** [comment]
## Update

After discussing in meeting the changes to apply, it was decided that the following approach is going to be taken:
- Mantain support of state files while they are still available.
- Add option to use API as source of data, so it can be used if needed.
- When state files are removed and all data is moved to the API we can then remove the state file support.

Development is done in branch https://github.com/wazuh/wazuh-qa/tree/4890-statistics-monitor-enhancement

**Comment by Deblintrake09** [comment]
## Update

- Fixing statistic.py script Done
- Working on retrieving new artifacts on Pipeline.
   - last build https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/418/

**Comment by davidjiglesias** [comment]
LGTM
