### ISSUE TITLE
Support new stage Beta 1 for 4.8.0 in wazuh-qa repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-qa#4911]
## Description

This issue attempts to support a new stage Beta 1 for 4.8.0 in the wazuh-qa repository.

## Tasks

- [x] Ensure changelog is updated for 4.8.0 (if applicable). https://github.com/wazuh/wazuh-qa/pull/4912
- [x] Bump revision for branch 4.8.0 on wazuh-qa repository. https://github.com/wazuh/wazuh-qa/pull/4913
- [x] Create tag v4.8.0-beta1 from branch 4.8.0 on wazuh-qa repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-qa/releases/tag/v4.8.0-beta1.

**Comment by Deblintrake09** [comment]
LGTM!

**Comment by damarisg** [comment]
- [ ] Added new fix. https://github.com/wazuh/wazuh-jenkins/issues/6238
- [ ] Removed v4.8.0-beta1  tag 
- [ ] Created new tag from the new changes.

**Comment by Rebits** [comment]
LGTM

**Comment by Deblintrake09** [comment]
LGTM!
