### ISSUE TITLE
FIM System tests: Create scenarios

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-qa#493]
### Objective

This issue aim to keep track of created scenarios as well as required changes to make them work. The scenarios are described in: [FIM System tests: Scenarios list](https://github.com/wazuh/wazuh-qa/wiki/FIM-System-tests:-Scenarios-list)

### Pre-tasks

- [x] Re-evaluate the folder structure and tasks

### Creation process

- Generate required `ossec.conf` with the scenario's specs
- Create actions tasks in Ansible format which will import required actions from `common_tasks` folder
- Create required tasks to launch the JSON and ES verification scripts
- Create master playbook `launch_environment.yml` which will import the scenario's tasks and launch them

### Testing process

The testing process is performed by the two main scripts that check the alerts, [ES script](https://github.com/wazuh/wazuh-qa/blob/feature-483-unify-parameters/tests/system/fim/common_tasks/verify_alerts_elasticsearch.py) and [JSON script](https://github.com/wazuh/wazuh-qa/blob/feature-483-unify-parameters/tests/system/fim/common_tasks/verify_alerts_json.py)

### Scenarios

- [x] 0201: Default configuration (Done in #480)

- [x] 0202: Realtime monitoring (@grg121) #531

- [x] 0203: Whodata (@jm404) #528

- [x] 0204: Whodata - `auditd` not installed (@Zenidd ) #520

- [x] 0205:  Restrict option (@xr09 ) #526 

- [x] 0206: Tag option (@DFolchA ) #524

- [x] 0207: Use of  report changes (@rshad) #523 

- [x] 0208: Use of ignore files (@xr09) #538 

- [x] 0209: Recursion level  (@Zenidd ) #540

- [x] 0210: Scheduled scan (@DFolchA ) #553 

- [x] 0211: Check overlap of scheduled syscheck scan and realtime scan (@grg121) #556

### Required fixes/changes:

- [x] Improve ES alerts verification (@rshad) #544 

- [x] Update default `ossec.conf`  for different os families (@Zenidd) #557 

- [x] Clean and Reinstall tasks (@xr09) #561
