### ISSUE TITLE
DTT1 - Iteration 3 - Provision - Multiple dependencies inventories in InputPayload

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#4940]
> Epic #4852

## Description
This issue aims to add support for multiple dependencies in the Test InputPayload
### Tasks
- [x] Modify the `InputPayload` & `ComponentInfo` models
- [x] Modify the Provisioner to get the IP of every dependency received and configure the `ComponentInfo` with it
- [x] Update the workflow's .yaml to send a list of key values (`component_name: inventory_path`)
- [x] Update playbooks templates to receive the `dependencies` argument

**Comment by pro-akim** [comment]
## Review Notes
Proposed minor edits to the docstrings only.

**Comment by pro-akim** [comment]
## Review Notes
LGTM
