### ISSUE TITLE
Implement scenario 201

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh-qa#497]
### Objective

Hello team,

This issue's aim is to implement scenario 201 is specified in #493.

### Tasks

- [ ] Generate ossec.conf
- At the moment we will just generate a plain `ossec.conf` for each scenario.
- [ ] Create a playbook that imports and launches common tasks.
-  Copy osse.conf and restart agent.
- Generate needed files.
- Wait for the alerts to be generated.
- Check if the corresponding alerts have been generated
- [ ] Extract logs and other files from the different hosts.

Regards,
Daniel Folch
