### ISSUE TITLE
DTT2 - Iteration 3 - Unit test - Unit tests for each module

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/wazuh-qa#4993]
> Epic: https://github.com/wazuh/wazuh-qa/issues/4495

---

## Description

The objective of this issue is to generate automated unit tests for each module.

## Taks

- [ ] https://github.com/wazuh/wazuh-qa/issues/4996
- [ ] https://github.com/wazuh/wazuh-qa/issues/4994
- [ ] https://github.com/wazuh/wazuh-qa/issues/4995

## Resources

- https://github.com/wazuh/wazuh-qa/pull/4990
  - `/deployability/modules/workflow_engine/`
- https://github.com/wazuh/wazuh-qa/issues/4906
- https://github.com/wazuh/wazuh-qa/tree/enhancement/4495-DTT1

## Observations/Requirements

- Pytest will be used to develop the unit test
- Minimum execution according to changes, but for now each module will be tested in full
  - To be improved in the future
- Tests should be executed locally and through GitHub Actions
- The GitHub Actions workflows should allow to be run on demand

## Branch

- https://github.com/wazuh/wazuh-qa/tree/enhancement/4993-dtt1-unit-tests
  - Created from https://github.com/wazuh/wazuh-qa/tree/enhancement/4495-DTT1

**Comment by fcaffieri** [comment]
The issue is moved to DTT2 since it was not within the requirements or scope of DTT1.
