### ISSUE TITLE
DTT1 - Iteration 3 - Unit test - Unit tests for the Provision module

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/wazuh-qa#4994]
> Epic: https://github.com/wazuh/wazuh-qa/issues/4993

---

## Description

The objective of this issue is to generate automatic unit tests for the Provision module.

## Tasks

- [x] Generate use cases
- [x] Validate generated use cases
- [x] Automate with GH actions

**Comment by mhamra** [comment]
### UPDATE
- I was reading the source code generated for the allocation, provisioning, and testing modules.

**Comment by mhamra** [comment]
### UPDATE
I've started developing the unit tests. I've almost finished the UTs for the Action class.

**Comment by mhamra** [comment]
### UPDATE
I've finished the UTs:
- test_actions.py
- test_component_type.py
- test_provision.py: started

**Comment by mhamra** [comment]
### UPDATE
I've finished the UTs:
- provison_mock Fixture.
- test_provision_constructor.
- test_provision_run.
- test_provision_run_fail.

**Comment by mhamra** [comment]
### UPDATE
I've finished these UTs:
- test_provision
- test_model

**Comment by rauldpm** [comment]
Moved the ETA to tomorrow, PR changes applied and must be reviewed again

**Comment by fcaffieri** [comment]
LGTM
