### ISSUE TITLE
Support new stage Beta 2 for 4.8.0 in wazuh-qa repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-qa#5017]
## Description

This issue attempts to support a new stage Beta 2 for 4.8.0 in the wazuh-qa repository.

## Tasks

- [ ] Ensure changelog is updated for 4.8.0 (if applicable).
- [ ] Bump revision for branch 4.8.0 on wazuh-qa repository.
- [ ] Create tag v4.8.0-beta2 from branch 4.8.0 on wazuh-qa repository.
- [ ] Create and publish a pre-release: https://github.com/wazuh/wazuh-qa/releases/tag/v4.8.0-beta2.

**Comment by QU3B1M** [comment]
LGTM!
