### ISSUE TITLE
Support new stage Beta 3 for 4.8.0 in wazuh-qa repository

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-qa#5052]
## Description

This issue attempts to support a new stage Beta 3 for 4.8.0 in the wazuh-qa repository.

## Tasks

- [x] Ensure changelog is updated for 4.8.0 (if applicable). https://github.com/wazuh/wazuh-qa/pull/5054 https://github.com/wazuh/wazuh-qa/pull/5056
- [x] Bump revision for branch 4.8.0 on wazuh-qa repository. https://github.com/wazuh/wazuh-qa/pull/5055
- [x] Create tag v4.8.0-beta3 from branch 4.8.0 on wazuh-qa repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-qa/releases/tag/v4.8.0-beta3

**Comment by rauldpm** [comment]
LGTM
