### ISSUE TITLE
DTT2 - Observability module - Develop and configure Test module

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/wazuh-qa#5078]
> Epic: https://github.com/wazuh/wazuh-qa/issues/4837

---

## Description

The objective of this issue is to develop the dashboards and make the necessary configurations for the Test module to show the information of its execution to the Observability module.

### Tasks

- [ ] Develop Dashboard
- [ ] Create and Configure the InfluxDB 
- [ ] Configure the InfluxDB plugin for the test
- [ ] Exploit the information obtained in the database
