### ISSUE TITLE
The macOS agent is not in the same time zone as the node

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#5175]
## Description

During the execution of the tests to check that the development of https://github.com/wazuh/wazuh-qa/issues/5108 was correct, it was seen that the macOS agent is not in the same time zone as the node, so the test fails because it uses `greater_than_timestamp` to filter the logs.

Failure:

```
TimeoutError: Element not found: {'regex': '(\\d{4}\\/\\d{2}\\/\\d{2} \\d{2}:\\d{2}:\\d{2}) .*? INFO: Starting evaluation', 'file': '/Library/Ossec/logs/ossec.log', 'timeout': 90, 'n_iterations': 1, 'greater_than_timestamp': '2024-04-02T13:44:04.985046'}
```

Agent logs:

```
2024/04/02 06:47:22 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2024/04/02 06:47:26 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2024/04/02 06:49:27 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2024/04/02 06:49:32 wazuh-modulesd:syscollector: INFO: Evaluation finished.
```

### Tasks

- [x] Change the vagrant time and check that it is maintained
- [x] Create a session fixture that performs this change
- [x] Check that tests pass as expected

**Comment by Rebits** [comment]
This problem is also present in Windows nodes. We can solve it through fixtures using the following command:
```
Set-TimeZone -Id "UTC"
```
