### ISSUE TITLE
DTT2 - Iteration 1 - Allocation module

### ISSUE THREAD

**Issue by c-bordon** [wazuh/wazuh-qa#5181]
> Epic #4495

## Description
This issue aims to list all the subtask that need to be completed in order to meet the **Allocation module** requirements for **DTT2** _Iteration 1_

### Tasks

- [ ] Allow machines to be deployed in different AWS regions
- [ ] https://github.com/wazuh/wazuh-qa/issues/4927
- [ ] Define roles and policies for the creation of the different machines in AWS and external infrastructure (macStadium, PowerPC)
- [ ] Update documentation with the new changes
- [ ] Add intel macStadium for macOS intel deployment
