### ISSUE TITLE
FIM System tests: 0207 Use of report changes

### ISSUE THREAD

**Issue by rshad** [wazuh/wazuh-qa#523]
Hi!

In this issue, we will comment on all the related activities to complete the design and the implementation of the scenario `Use of report_changes` for FIM system tests.

### Configuration

- **Related branch**: [feature-523-scenario-report-changes](https://github.com/wazuh/wazuh-qa/tree/feature-523-scenario-report-changes).
- **wazuh-manager** `ossec.conf` 
- **Linux wazuh-agent** `ossec.conf` file: _Enable `report_changes` in _Syscheck_._
- **Windows wazuh-agent** `ossec.conf` file: _Enable `report_changes` in _Syscheck_._
_All of them can be found in_
  -  `wazuh-qa/tests/system/fim/scenarios/207_use_of_report_changes/config/`

**Tasks**
- [x] Create the corresponding `ossec.conf` with the scenario specifications.
  - [x] wazuh-agent config.
    - [x] Linux.
    - [x] Windows.

- [x] Apply the required changes on the corresponding scripts.
  - [x] `create_files.py`
  - [x] `modify_files.py`
  - [x] `alerts.json` verification script.
  - [x] `ES` verification scripts.

- [x]  Adapt actions tasks in Ansible format which will import required actions from common_tasks folder, so it takes into account the newly added parameters for each action script.
  - [x] `create_files.yml`
  - [x] `modify_files.yml`
  - [x] `delete_files.yml`
  - [x] `../vars/main.yml`

- _**Done in**_ https://github.com/wazuh/wazuh-qa/pull/530 

- [x] Create master playbook `launch_test_scenario.yml` which will import the scenario's tasks and launch them.

### Actions

- Created 5010 _text_ file in both agents Linux and Windows.
- Modified all 5010 files by adding a text sentence after the last line.

### Tests

- Checked the expected alerts for `added` event, using the corresponding scripts and manually. ✔️
- Checked the expected alerts for `mdofied` event and the _diff_ text in the diff field, using the corresponding scripts and manually. `Timeout with files of 11MB` ❌ 

**_Note_**: Between almost 15 execution, in 1 of them, the alerts from Windows took more time to reach the usual in reaching `alerts.json` or `Elasticsearch` index. From my perspective was lead due to the low performance of the host where Windows is running, because no errors were detected. `Pending` of testing with higher dedicated RAM memory for such host. ❌ 

### Conclusions
The tests applied on this scenario have been passed successfully. All changes made on the target files were reported by `syscheck:report_changes`. But we detected the issue of taking a long time to run the diff in Windows.

_`Note`_: The description may be updated in the future if needed.

Kr,

Rshad

**Comment by rshad** [comment]
Working branch: [feature-523-scenario-report-changes](https://github.com/wazuh/wazuh-qa/tree/feature-523-scenario-report-changes).

**Comment by rshad** [comment]
Hi all!

Here we comment on some details about the essential changes we applied to reach this issue goals.

**- Adapted `generate_files.yml`**:
Adapted this script to differentiate two possible types of files to be created, both binary and text files. We needed the text files because `syscheck:report_changes` it's only valid with text files.

https://github.com/wazuh/wazuh-qa/blob/cf3678ab26c271477a6b288b919d9fa48cc2d2a0/tests/system/fim/common_tasks/generate_files.py#L165-L167

 **- Adapted `modify_files.yml`**:
Adapted this script to receive a new argument `-t or --text-mode` used to modify text files and not binary ones.

https://github.com/wazuh/wazuh-qa/blob/cf3678ab26c271477a6b288b919d9fa48cc2d2a0/tests/system/fim/common_tasks/modify_files.py#L110-L112

In this case, added a new function to add a new sentence at the beginning of the target file, so the difference between the file before and after the change would be printable in the generated alert. as Syscheck will print the whole document in case of inserting the new text at the end of the file and in case of passing over x bytes of length, Syscheck will print _Line x changed, More Changes ..._ and then our tests will not be applicable.

```python
def modify_file_text_content(filepath, sentence):
    """
    Modify file content by adding sentence at the end of filepath
    in a new line.

    :param str filepath: The path of the file to modify
    :param str sentence: A setnence of 1 or more words.
    """
    with open(filepath, 'r+') as file:
        content = file.read()
        file.seek(0, 0)
        file.write(sentence.rstrip('\r\n') + '\n' + content)
```

 **- Adapted `verify_alerts_json.yml`**:

Added a new argument `"-d", "--diff"` to receive the text to be added into the target file with the purpose to cause a `syscheck:report_changes` kind alert.

```python
        parser.add_argument("-d", "--diff", type=str, required=False, dest='diff_string',
                            help="When syscheck:report_changes enabled, represents the diff text")
        args = parser.parse_args()
```

As you can see, in the function  `alerts_prune` we added a new conditional check for the case of testing `syscheck:report_changes` alerts.

```python
def alerts_prune(path, target_event, diff_statement=None):
.
.
                   if (diff_statement is not None) and \
                       ('diff' in data['syscheck']) and \
                       (diff_statement not in data['syscheck']['diff']):
                            add_path = False
                    if add_path:
                        alerts_list.append(data)
                    add_path = True
.
.
```

 **- Adapted `verify_alerts_elasticsearch.yml`**:
Here, we also adapted the script to check the field `diff` in case of `syscheck:report_changes` alerts.
```
    diff_statement = args.diff_string

    with open(args.files, 'r') as file_list:
.
.
            for line in file_list:
                query['query']['bool']['filter'][0]['term']['syscheck.path'] =\
                    line.rstrip()

                query_result = makeQuery(query, es, index_name)

                if query_result['hits']['total']['value'] == 1:

                    if (diff_statement is not None) and \
                       ('diff' in query_result['syscheck']) and \
                       (diff_statement not in query_result['syscheck']['diff']):
                        success_ = False

                    if success_:
                        success += 1
                    success_ = True
.
.
```

Kr,

Rshad

**Comment by rshad** [comment]
Hi all!

Regarding the issue on Windows host, where the alerts of `syscheck:modified` are taking a lot of time to be sent to the manager, almost 8 alerts per minute only. 

### CPU and RAM memory are not related
We decided to repeat the experiment with higher RAM memory and CPU.

**Default Machine Characteristics**
- 1 GB of RAM memory.
- 1 Core.

**Custom Machine Characteristics**
- 2 GB of RAM memory.
- 2 Cores.

But nothing has been changed, the alert still taking a long time to be sent with the same amount (~8 alerts per minute).

After checking the Windows machine RAM and CPU behavior we found that there is no leak of RAM memory or CPU, as you can check on the following capture.

![image](https://user-images.githubusercontent.com/19154337/75336934-513f7380-588c-11ea-9f01-b09ff98ccd0a.png)


We can clearly see that the process of  `wazuh-agent` is consuming only ~ 10 MB of RAM and nothing of CPU. but we also can notice the process `DOS 5 File Compare Utility (32 bit)` which is the background process used by `wazuh-agent` to run the `diff` for `Syscheck` and it's consuming almost half of the available CPU. This process seems to be running so slowly.

---

#### Syscheck `modified - report_changes` alert is different between Linux and Windows

After checking the format of the `modified` is different in Windows from the one coming from Linux agent. In Windows more file content is printed.

**Linux `wazuh-agent` alert**
```json
{
  "timestamp": "2020-02-26T10:19:03.975+0000",
  "rule": {
    "level": 7,
    "description": "Integrity checksum changed.",
    "id": "550",
    "firedtimes": 17,
    "mail": false,
    "groups": [
      "ossec",
      "syscheck"
    ],
    "pci_dss": [
      "11.5"
    ],
    "gpg13": [
      "4.11"
    ],
    "gdpr": [
      "II_5.1.f"
    ],
    "hipaa": [
      "164.312.c.1",
      "164.312.c.2"
    ],
    "nist_800_53": [
      "SI.7"
    ]
  },
  "agent": {
    "id": "002",
    "name": "Centos",
    "ip": "10.0.2.15"
  },
  "manager": {
    "name": "serv-test-manager-centos-1"
  },
  "id": "1582712343.14471979",
  "full_log": "File '/opt/fim_testing/uajtd/dglgwdie' modified\nMode: real-time\nChanged attributes: size,mtime,md5,sha1,sha256\nSize changed from '10257' to '10269'\nOld modification time was: '1582711921', now it is '1582712342'\nOld md5sum was: '27a99e7758a0ac1130212548ca346da1'\nNew md5sum is : 'e5b3f8aa3dfc64ea7b35a032058fe505'\nOld sha1sum was: 'fda41b6a597c4e53774f20079b61f19b3b8013de'\nNew sha1sum is : '300de55516a228748d0faf8bb0cb52833d017757'\nOld sha256sum was: '59fe17de107a5dc55f16635cba05c9f0aebe51fb2d76dd002635ddfef046945c'\nNew sha256sum is : '2fb1bbd4c99a285318b5f61f0ec165d86b9683bee054d3c711fb43fb0e9e1e35'\n",
  "syscheck": {
    "path": "/opt/fim_testing/uajtd/dglgwdie",
    "size_before": "10257",
    "size_after": "10269",
    "perm_after": "rw-r--r--",
    "uid_after": "0",
    "gid_after": "0",
    "md5_before": "27a99e7758a0ac1130212548ca346da1",
    "md5_after": "e5b3f8aa3dfc64ea7b35a032058fe505",
    "sha1_before": "fda41b6a597c4e53774f20079b61f19b3b8013de",
    "sha1_after": "300de55516a228748d0faf8bb0cb52833d017757",
    "sha256_before": "59fe17de107a5dc55f16635cba05c9f0aebe51fb2d76dd002635ddfef046945c",
    "sha256_after": "2fb1bbd4c99a285318b5f61f0ec165d86b9683bee054d3c711fb43fb0e9e1e35",
    "uname_after": "root",
    "gname_after": "root",
    "mtime_before": "2020-02-26T10:12:01",
    "mtime_after": "2020-02-26T10:19:02",
    "inode_after": 67165478,
    "diff": "0a1\n> Hello World\n",
    "changed_attributes": [
      "size",
      "mtime",
      "md5",
      "sha1",
      "sha256"
    ],
    "event": "modified"
  },
  "decoder": {
    "name": "syscheck_integrity_changed"
  },
  "location": "syscheck"
}
```

**Windows `wazuh-agent` alert**
```json
{
  "timestamp": "2020-02-26T10:01:01.914+0000",
  "rule": {
    "level": 7,
    "description": "Integrity checksum changed.",
    "id": "550",
    "firedtimes": 20,
    "mail": false,
    "groups": [
      "ossec",
      "syscheck"
    ],
    "pci_dss": [
      "11.5"
    ],
    "gpg13": [
      "4.11"
    ],
    "gdpr": [
      "II_5.1.f"
    ],
    "hipaa": [
      "164.312.c.1",
      "164.312.c.2"
    ],
    "nist_800_53": [
      "SI.7"
    ]
  },
  "agent": {
    "id": "001",
    "name": "Windows",
    "ip": "10.0.2.15"
  },
  "manager": {
    "name": "serv-test-manager-centos-1"
  },
  "id": "1582711261.33578",
  "full_log": "File 'c:\\fim_testing\\ovxxj\\cykjj\\obujmeee' modified\nMode: scheduled\nChanged attributes: size,mtime,md5,sha1,sha256\nSize changed from '10258' to '10271'\nOld modification time was: '1582709728', now it is '1582710810'\nOld md5sum was: '319b9fcd86079b32f461c137e6d149de'\nNew md5sum is : '499efb8b9186766492dcdc5b91d214c0'\nOld sha1sum was: '417cb6656c60338cf6303daa831cef4a37f39920'\nNew sha1sum is : '9b72ad950e42d42cc2a317ec0ccba7d7c2da200e'\nOld sha256sum was: '6a76f6fbf3f0eaf4d20ad0cd1313f31e964546d22fb09e5bcb14608dcee2de48'\nNew sha256sum is : '69e6436bab6c28e73325ff525bda0fe86201cc6eb0aebd5ddbd40f2972af22de'\n",
  "syscheck": {
    "path": "c:\\fim_testing\\ovxxj\\cykjj\\obujmeee",
    "size_before": "10258",
    "size_after": "10271",
    "win_perm_after": [
      {
        "name": "SYSTEM",
        "allowed": [
          "DELETE",
          "READ_CONTROL",
          "WRITE_DAC",
          "WRITE_OWNER",
          "SYNCHRONIZE",
          "READ_DATA",
          "WRITE_DATA",
          "APPEND_DATA",
          "READ_EA",
          "WRITE_EA",
          "EXECUTE",
          "READ_ATTRIBUTES",
          "WRITE_ATTRIBUTES"
        ]
      },
      {
        "name": "Administrators",
        "allowed": [
          "DELETE",
          "READ_CONTROL",
          "WRITE_DAC",
          "WRITE_OWNER",
          "SYNCHRONIZE",
          "READ_DATA",
          "WRITE_DATA",
          "APPEND_DATA",
          "READ_EA",
          "WRITE_EA",
          "EXECUTE",
          "READ_ATTRIBUTES",
          "WRITE_ATTRIBUTES"
        ]
      },
      {
        "name": "Users",
        "allowed": [
          "READ_CONTROL",
          "SYNCHRONIZE",
          "READ_DATA",
          "READ_EA",
          "EXECUTE",
          "READ_ATTRIBUTES"
        ]
      }
    ],
    "uid_after": "S-1-5-32-544",
    "md5_before": "319b9fcd86079b32f461c137e6d149de",
    "md5_after": "499efb8b9186766492dcdc5b91d214c0",
    "sha1_before": "417cb6656c60338cf6303daa831cef4a37f39920",
    "sha1_after": "9b72ad950e42d42cc2a317ec0ccba7d7c2da200e",
    "sha256_before": "6a76f6fbf3f0eaf4d20ad0cd1313f31e964546d22fb09e5bcb14608dcee2de48",
    "sha256_after": "69e6436bab6c28e73325ff525bda0fe86201cc6eb0aebd5ddbd40f2972af22de",
    "attrs_after": [
      "ARCHIVE"
    ],
    "uname_after": "Administrators",
    "mtime_before": "2020-02-26T09:35:28",
    "mtime_after": "2020-02-26T09:53:30",
    "diff": "< 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000\n< 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000\n---\n> Hello World\n> 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000\n---\n< 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000\n< 00000000000000000000000000000000000000000000000000000000000000000000000000000000hgnhldiksllswusx\n---\n> 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000\n> 0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000\n> 00000000000000000000000000000000000000000000000000000000000000000000000000000000hgnhldiksllswusx\n",
    "changed_attributes": [
      "size",
      "mtime",
      "md5",
      "sha1",
      "sha256"
    ],
    "event": "modified"
  },
  "decoder": {
    "name": "syscheck_integrity_changed"
  },
  "location": "syscheck"
}
```

Kr,

Rshad

**Comment by rshad** [comment]
Hi all!

It's clear that Windows is taking a long time to run the diff process of each file, but to know what time it exactly takes depending on each group of files of a determined size, we estimated the time between the first received alert and the last one, testing with the different files groups depending on the file size, separately.

`Time refers to "Time needed till all the alerts are received"`.

| File Size| Number of Files | Time (min) | Average time/alert (s) |
|---|---|---|---|
|11 KB|4000|~11|0.165|  


`Note`: the table above will be filled each time we run a new experiment.

Kr,

Rshad
