### ISSUE TITLE
Support new stage RC 1 for 4.7.4 in wazuh-qa repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-qa#5282]
## Description

This issue attempts to support a new stage RC 1 for 4.7.4 in the wazuh-qa repository.

## Tasks

- [x] ~Ensure changelog is updated for 4.7.4 (if applicable).~ Already updated
- [x] Bump revision for branch 4.7.4 on wazuh-qa repository. https://github.com/wazuh/wazuh-qa/pull/5283
- [x] Create tag v4.7.4-rc1 from branch 4.7.4 on wazuh-qa repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-qa/releases/tag/v4.7.4-rc1.

**Comment by santipadilla** [comment]
LGTM
