### ISSUE TITLE
Vulnerability state testing for clustered environments

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#5300]
## Description

This issue aims to encompass the testing of various use cases for solutions provided by development teams to prevent vulnerability duplication in cluster environments.

- @wazuh/devel-framework development: https://github.com/wazuh/wazuh/issues/23058
- @wazuh/devel-core2 development: https://github.com/wazuh/wazuh/issues/22867

### Environment Requirements

| Component              | Quantity | Operating System | CPU (cores) | RAM (GB) | Disk (GB) |
|------------------------|----------|------------------|-------------|----------|-----------|
| **Master**             | 1        | Ubuntu 22        | 4           | 8        | 50        |
| **Workers**            | 2        | Ubuntu 22        | 4           | 8        | 50        |
| **Agent 1**            | 1        | Ubuntu 22        | 2           | 4        | 30        |
| **Agent 2**            | 1        | Windows 11       | 2           | 4        | 30        |
| **Load Balancer**      | 1        | Ubuntu 22        | 4           | 8        | 50        |
| **Indexers**           | 2        | Ubuntu 22        | 2           | 4        | 30        |

> [!NOTE] 
The load balancer is located on the master node.

- Two identical environments will be deployed.
- Each environment will use packages from one development.

| Architecture           | Framework development package URL                                                                                      | Core development package URL                                                                                        |
|------------------------|----------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------|
| DEB                    | [4.8.0-python.vd.spike.deb.1](https://packages-dev.wazuh.com/warehouse/pullrequests/4.8/deb/var/wazuh-manager_4.8.0-python.vd.spike.deb.1_amd64.deb) | [4.8.0-0.commitd31b277](https://packages-dev.wazuh.com/warehouse/pullrequests/4.8/deb/var/wazuh-manager_4.8.0-0.commitd31b277_amd64.deb) |
| RPM                    | [4.8.0-python.vd.spike.rpm.1](https://packages-dev.wazuh.com/warehouse/pullrequests/4.8/rpm/var/wazuh-manager-4.8.0-python.vd.spike.rpm.1.x86_64.rpm) | [4.8.0-0.commitd31b277](https://packages-dev.wazuh.com/warehouse/pullrequests/4.8/rpm/var/wazuh-manager-4.8.0-0.commitd31b277.x86_64.rpm) |

### Plan

- [x] https://github.com/wazuh/wazuh-qa/issues/5301
- [x] https://github.com/wazuh/wazuh-qa/issues/5302
- [x] https://github.com/wazuh/wazuh-qa/issues/5303
- [x] https://github.com/wazuh/wazuh-qa/issues/5313
