### ISSUE TITLE
Publish release 4.7.4

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-qa#5305]
## Description
This issue attempts to track the steps necessary to publish packages, OVA, AMI, docker images, and puppet forge for 4.7.4.

## Tasks
- [x] Send AMI to analysis.
- [x] Launch [`Publish_release`](https://ci.wazuh.info/job/Publish_release) pipeline.
  - https://ci.wazuh.info/job/publish_unattended/267/
- [x] ~Upload latest Filebeat version.~
  - Without changes
- [x] Build and release debug packages.
- [x] Build and push [Docker Hub images](https://ci.wazuh.info/job/procedure_push_docker_images).
  - https://ci.wazuh.info/job/procedure_push_docker_images/134/
- [x] Publish AMI.
  - In progress, it is being published by AWS

**Comment by rauldpm** [comment]
- Created pre-release backup
- Checked packages of higher versions

**Comment by juliamagan** [comment]
- [x] Modify WPK versions (Linux,macOS, Windows) to remove 4.8.0 and upload it again
  - [x] Ensure that the versions files are publicly available

**Comment by rauldpm** [comment]
AMI analyzed and approved 
![image](https://github.com/wazuh/wazuh-qa/assets/14913942/bd2a1da3-ec07-48a3-b71c-d912610ab9ed)
