### ISSUE TITLE
DTT1 - Testing module. Agent's OS version check procedure.

### ISSUE THREAD

**Issue by mhamra** [wazuh/wazuh-qa#5359]
| Target version | Related issue | Related PR/dev branch |
|---|---|---|
| 4.9.0 | #5191   | 4495-dtt1-release  |

## Description
The current implementation of the testing module compares the result of the Wazuh agent API endpoint with the OS version reported by the inventory file.

The testing module should obtain the OS version using OS native commands.

## Tasks
- [x] Modify the module's procedure to obtain the OS version using Linux commands.
- [x] Modify the module's procedure to obtain the OS version using Windows commands.
- [x] Modify the module's procedure to obtain the OS version using MacOS commands.
- [x] Run the existing tests to verify this new feature in all the platforms.

**Comment by mhamra** [comment]
### UPDATE
I'm verifying the commands to use in each platform

- Ubuntu
```
(dtt-test) marcelo@marcelo-B460-AORUS-PRO-AC:~/wazuh/wazuh-qa/deployability$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy
```

- Amazon Linux
```
(dtt-test) marcelo@marcelo-B460-AORUS-PRO-AC:~/wazuh/wazuh-qa/deployability$ docker run -ti amazonlinux:2 bash
Unable to find image 'amazonlinux:2' locally
2: Pulling from library/amazonlinux
0b2952a75473: Pull complete 
Digest: sha256:3bc2191fa2d5f467217e5ca947485bc203b73c02b9a23b164818fa6e37647625
Status: Downloaded newer image for amazonlinux:2
bash-4.2# cat /etc/system-release
Amazon Linux release 2 (Karoo)
bash-4.2# exit
exit
(dtt-test) marcelo@marcelo-B460-AORUS-PRO-AC:~/wazuh/wazuh-qa/deployability$ docker run -ti amazonlinux:2023 bash
Unable to find image 'amazonlinux:2023' locally
2023: Pulling from library/amazonlinux
6f59c9417334: Pull complete 
Digest: sha256:5478f82c47e435ed988fa12a00b623ef3c920fadd669d40c596249cf81960c4c
Status: Downloaded newer image for amazonlinux:2023
bash-5.2# cat /etc/system-release
Amazon Linux release 2023.4.20240416 (Amazon Linux)
bash-5.2# exit
exit
```

- RedHat
```
(dtt-test) marcelo@marcelo-B460-AORUS-PRO-AC:~/wazuh/wazuh-qa/deployability$ docker run -ti redhat/ubi9 bash
Unable to find image 'redhat/ubi9:latest' locally
latest: Pulling from redhat/ubi9
6b20e0c6c1e1: Pull complete 
Digest: sha256:ed84f34cd929ea6b0c247b6daef54dd79602804a32480a052951021caf429494
Status: Downloaded newer image for redhat/ubi9:latest
[root@09792c738fc3 /]# cat /etc/redhat-release
Red Hat Enterprise Linux release 9.4 (Plow)
[root@09792c738fc3 /]# exit
exit
(dtt-test) marcelo@marcelo-B460-AORUS-PRO-AC:~/wazuh/wazuh-qa/deployability$ docker run -ti redhat/ubi8 bash
Unable to find image 'redhat/ubi8:latest' locally
latest: Pulling from redhat/ubi8
2efec45cd878: Pull complete 
Digest: sha256:edc34f89cf9c818c2fb28b8ea1780f384db563ce4293dc0ab8e73ec01791e5af
Status: Downloaded newer image for redhat/ubi8:latest
[root@4787131b4ded /]# cat /etc/redhat-release
Red Hat Enterprise Linux release 8.9 (Ootpa)

```

**Comment by mhamra** [comment]
### UPDATE
I've investigated the agent's C++ source code to define how to get the OS version on each platform. 

The source code is in the `src/data_provider/src/osinfo` folder in the `wazuh/wazuh` repository.

I've started coding the logic to replace the current testing logic based on the info obtained from the inventory of the VM instance provided by the allocation module.

**Comment by mhamra** [comment]
### UPDATE
I've investigated the `/etc/os-release` file. It is standardized and usually found in all `systems` Unix systems. It will be used as the first source of information for OS version detection.

I've used Vagrant for development and committed the first version of the modifications to the repo after checking runs and fixing errors. I've launched a workflow in AWS with all the UNIX agent versions.

**Comment by mhamra** [comment]
### UPDATE
I've found a bug in the installation of the wazuh agent in `rmp arm` platform. 

New issue reported https://github.com/wazuh/wazuh-qa/issues/5380

**Comment by fcaffieri** [comment]
### Update report


Modification made to all linux system.

Test with two linux agents :green_circle: :

Input yaml:

```
version: 0.1
description: This workflow is used to test agents deployment for DDT1 PoC
variables:
  agent-os:
    - linux-redhat-7-amd64
    #- linux-redhat-7-arm64
    #- linux-redhat-8-amd64
    #- linux-redhat-8-arm64
    #- linux-redhat-9-amd64
    #- linux-redhat-9-arm64
    #- linux-centos-7-amd64
    #- linux-centos-7-arm64
    #- linux-centos-8-amd64
    #- linux-centos-8-arm64
    #- linux-debian-10-amd64
    #- linux-debian-10-arm64
    #- linux-debian-11-amd64
    #- linux-debian-11-arm64
    #- linux-debian-12-amd64
    #- linux-debian-12-arm64
    - linux-ubuntu-22.04-amd64
    #- linux-ubuntu-22.04-arm64
    #- linux-ubuntu-18.04-amd64
    #- linux-ubuntu-18.04-arm64
    #- linux-ubuntu-20.04-amd64
    #- linux-ubuntu-20.04-arm64
    #- linux-oracle-9-amd64
    #- linux-amazon-2-amd64
    #- linux-amazon-2-arm64
    #- linux-amazon-2023-amd64
    #- linux-amazon-2023-arm64
    #- windows-desktop-10-amd64
    #- windows-server-2012r2-amd64
    #- windows-server-2016-amd64
    #- windows-server-2019-amd64
    #- windows-server-2022-amd64

  macos-agent-os:
    - macos-ventura-13.4.1-amd64
    - macos-sonoma-14.4.1-amd64

  manager-os: linux-ubuntu-22.04-amd64
  infra-provider: aws
  macos-infra-provider: vagrant
  working-dir: /tmp/dtt1-poc

tasks:
  # Unique manager allocate task
  - task: "allocate-manager-{manager-os}"
    description: "Allocate resources for the manager."
    do:
      this: process
      with:
        path: python3
        args:
          - modules/allocation/main.py
          - action: create
          - provider: "{infra-provider}"
          - size: large
          - composite-name: "{manager-os}"
          - inventory-output: "{working-dir}/manager-{manager-os}/inventory.yaml"
          - track-output: "{working-dir}/manager-{manager-os}/track.yaml"
          - label-termination-date: "1d"
          - label-team: "qa"
          - label-issue: "https://github.com/wazuh/wazuh-qa/issues/5191"
    on-error: "abort-all"
    cleanup:
      this: process
      with:
        path: python3
        args:
          - modules/allocation/main.py
          - action: delete
          - track-output: "{working-dir}/manager-{manager-os}/track.yaml"

  # Unique agent allocate task
  - task: "allocate-agent-{agent}"
    description: "Allocate resources for the agent."
    do:
      this: process
      with:
        path: python3
        args:
          - modules/allocation/main.py
          - action: create
          - provider: "{infra-provider}"
          - size: small
          - composite-name: "{agent}"
          - inventory-output: "{working-dir}/agent-{agent}/inventory.yaml"
          - track-output: "{working-dir}/agent-{agent}/track.yaml"
          - label-termination-date: "1d"
          - label-team: "qa"
          - label-issue: "https://github.com/wazuh/wazuh-qa/issues/5191"
    on-error: "abort-all"
    foreach:
      - variable: agent-os
        as: agent
    cleanup:
      this: process
      with:
        path: python3
        args:
          - modules/allocation/main.py
          - action: delete
          - track-output: "{working-dir}/agent-{agent}/track.yaml"

  # Unique macOS agent allocate task
  #- task: "allocate-macos-agent-{agent}"
  #  description: "Allocate resources for the agent."
  #  do:
  #    this: process
  #    with:
  #      path: python3
  #      args:
  #        - modules/allocation/main.py
  #        - action: create
  #        - provider: "{macos-infra-provider}"
  #        - size: small
  #        - composite-name: "{agent}"
  #        - inventory-output: "{working-dir}/agent-{agent}/inventory.yaml"
  #        - track-output: "{working-dir}/agent-{agent}/track.yaml"
  #        - label-termination-date: "1d"
  #        - label-team: "qa"
  #        - label-issue: "https://github.com/wazuh/wazuh-qa/issues/5191"
  #  on-error: "abort-all"
  #  foreach:
  #    - variable: macos-agent-os
  #      as: agent
  #  cleanup:
  #    this: process
  #    with:
  #      path: python3
  #      args:
  #        - modules/allocation/main.py
  #        - action: delete
  #        - track-output: "{working-dir}/agent-{agent}/track.yaml"

  # Unique manager provision task
  - task: "provision-manager-{manager-os}"
    description: "Provision the manager."
    do:
      this: process
      with:
        path: python3
        args:
          - modules/provision/main.py
          - inventory: "{working-dir}/manager-{manager-os}/inventory.yaml"
          - install:
            - component: wazuh-manager
              type: assistant
              version: 4.7.4
              live: True
    depends-on:
      - "allocate-manager-{manager-os}"
    on-error: "abort-all"

  # Generic agent test task
  - task: "run-agent-{agent}-tests"
    description: "Run tests install for the agent {agent}."
    do:
      this: process
      with:
        path: python3
        args:
          - modules/testing/main.py
          - targets:
            - wazuh-1: "{working-dir}/manager-{manager-os}/inventory.yaml"
            - agent: "{working-dir}/agent-{agent}/inventory.yaml"
          - tests: "install,registration,basic_info"
          - component: "agent"
          - wazuh-version: "4.7.4"
          - wazuh-revision: "40717"
          - live: "True"
    foreach:
      - variable: agent-os
        as: agent
    depends-on:
      - "allocate-agent-{agent}"
      - "provision-manager-{manager-os}"

  # Generic macOS agent test task
  #- task: "run-agent-{agent}-tests"
  #  description: "Run tests install for the agent {agent}."
  #  do:
  #    this: process
  #    with:
  #      path: python3
  #      args:
  #        - modules/testing/main.py
  #        - targets:
  #          - wazuh-1: "{working-dir}/manager-{manager-os}/inventory.yaml"
  #          - agent: "{working-dir}/agent-{agent}/inventory.yaml"
  #        - tests: "install,registration,basic_info,connection,restart,stop,uninstall"
  #        - component: "agent"
  #        - wazuh-version: "4.7.4"
  #        - wazuh-revision: "40717"
  #        - live: "True"
  #  foreach:
  #    - variable: macos-agent-os
  #      as: agent
  #  depends-on:
  #    - "allocate-macos-agent-{agent}"
  #    - "provision-manager-{manager-os}"
```

Result:

![image](https://github.com/wazuh/wazuh-qa/assets/89791732/d921b195-a32d-443d-99a5-98326aad94c2)


![image](https://github.com/wazuh/wazuh-qa/assets/89791732/493b45e2-daab-4836-b163-db284d0174a3)

[test-agents-basic-info.log](https://github.com/wazuh/wazuh-qa/files/15342496/test-agents-basic-info.log)


Test with all linux agents :green_circle: :

Input yaml:

```
version: 0.1
description: This workflow is used to test agents deployment for DDT1 PoC
variables:
  agent-os:
    - linux-redhat-7-amd64
    - linux-redhat-7-arm64
    - linux-redhat-8-amd64
    - linux-redhat-8-arm64
    - linux-redhat-9-amd64
    - linux-redhat-9-arm64
    - linux-centos-7-amd64
    - linux-centos-7-arm64
    - linux-centos-8-amd64
    - linux-centos-8-arm64
    - linux-debian-10-amd64
    - linux-debian-10-arm64
    - linux-debian-11-amd64
    - linux-debian-11-arm64
    - linux-debian-12-amd64
    - linux-debian-12-arm64
    - linux-ubuntu-22.04-amd64
    - linux-ubuntu-22.04-arm64
    - linux-ubuntu-18.04-amd64
    - linux-ubuntu-18.04-arm64
    - linux-ubuntu-20.04-amd64
    - linux-ubuntu-20.04-arm64
    - linux-oracle-9-amd64
    - linux-amazon-2-amd64
    - linux-amazon-2-arm64
    - linux-amazon-2023-amd64
    - linux-amazon-2023-arm64
    #- windows-desktop-10-amd64
    #- windows-server-2012r2-amd64
    #- windows-server-2016-amd64
    #- windows-server-2019-amd64
    #- windows-server-2022-amd64

  macos-agent-os:
    - macos-ventura-13.4.1-amd64
    - macos-sonoma-14.4.1-amd64

  manager-os: linux-ubuntu-22.04-amd64
  infra-provider: aws
  macos-infra-provider: vagrant
  working-dir: /tmp/dtt1-poc

tasks:
  # Unique manager allocate task
  - task: "allocate-manager-{manager-os}"
    description: "Allocate resources for the manager."
    do:
      this: process
      with:
        path: python3
        args:
          - modules/allocation/main.py
          - action: create
          - provider: "{infra-provider}"
          - size: large
          - composite-name: "{manager-os}"
          - inventory-output: "{working-dir}/manager-{manager-os}/inventory.yaml"
          - track-output: "{working-dir}/manager-{manager-os}/track.yaml"
          - label-termination-date: "1d"
          - label-team: "qa"
          - label-issue: "https://github.com/wazuh/wazuh-qa/issues/5191"
    on-error: "abort-all"
    cleanup:
      this: process
      with:
        path: python3
        args:
          - modules/allocation/main.py
          - action: delete
          - track-output: "{working-dir}/manager-{manager-os}/track.yaml"

  # Unique agent allocate task
  - task: "allocate-agent-{agent}"
    description: "Allocate resources for the agent."
    do:
      this: process
      with:
        path: python3
        args:
          - modules/allocation/main.py
          - action: create
          - provider: "{infra-provider}"
          - size: small
          - composite-name: "{agent}"
          - inventory-output: "{working-dir}/agent-{agent}/inventory.yaml"
          - track-output: "{working-dir}/agent-{agent}/track.yaml"
          - label-termination-date: "1d"
          - label-team: "qa"
          - label-issue: "https://github.com/wazuh/wazuh-qa/issues/5191"
    on-error: "abort-all"
    foreach:
      - variable: agent-os
        as: agent
    cleanup:
      this: process
      with:
        path: python3
        args:
          - modules/allocation/main.py
          - action: delete
          - track-output: "{working-dir}/agent-{agent}/track.yaml"

  # Unique macOS agent allocate task
  #- task: "allocate-macos-agent-{agent}"
  #  description: "Allocate resources for the agent."
  #  do:
  #    this: process
  #    with:
  #      path: python3
  #      args:
  #        - modules/allocation/main.py
  #        - action: create
  #        - provider: "{macos-infra-provider}"
  #        - size: small
  #        - composite-name: "{agent}"
  #        - inventory-output: "{working-dir}/agent-{agent}/inventory.yaml"
  #        - track-output: "{working-dir}/agent-{agent}/track.yaml"
  #        - label-termination-date: "1d"
  #        - label-team: "qa"
  #        - label-issue: "https://github.com/wazuh/wazuh-qa/issues/5191"
  #  on-error: "abort-all"
  #  foreach:
  #    - variable: macos-agent-os
  #      as: agent
  #  cleanup:
  #    this: process
  #    with:
  #      path: python3
  #      args:
  #        - modules/allocation/main.py
  #        - action: delete
  #        - track-output: "{working-dir}/agent-{agent}/track.yaml"

  # Unique manager provision task
  - task: "provision-manager-{manager-os}"
    description: "Provision the manager."
    do:
      this: process
      with:
        path: python3
        args:
          - modules/provision/main.py
          - inventory: "{working-dir}/manager-{manager-os}/inventory.yaml"
          - install:
            - component: wazuh-manager
              type: assistant
              version: 4.7.4
              live: True
    depends-on:
      - "allocate-manager-{manager-os}"
    on-error: "abort-all"

  # Generic agent test task
  - task: "run-agent-{agent}-tests"
    description: "Run tests install for the agent {agent}."
    do:
      this: process
      with:
        path: python3
        args:
          - modules/testing/main.py
          - targets:
            - wazuh-1: "{working-dir}/manager-{manager-os}/inventory.yaml"
            - agent: "{working-dir}/agent-{agent}/inventory.yaml"
          - tests: "install,registration,basic_info"
          - component: "agent"
          - wazuh-version: "4.7.4"
          - wazuh-revision: "40717"
          - live: "True"
    foreach:
      - variable: agent-os
        as: agent
    depends-on:
      - "allocate-agent-{agent}"
      - "provision-manager-{manager-os}"

  # Generic macOS agent test task
  #- task: "run-agent-{agent}-tests"
  #  description: "Run tests install for the agent {agent}."
  #  do:
  #    this: process
  #    with:
  #      path: python3
  #      args:
  #        - modules/testing/main.py
  #        - targets:
  #          - wazuh-1: "{working-dir}/manager-{manager-os}/inventory.yaml"
  #          - agent: "{working-dir}/agent-{agent}/inventory.yaml"
  #        - tests: "install,registration,basic_info,connection,restart,stop,uninstall"
  #        - component: "agent"
  #        - wazuh-version: "4.7.4"
  #        - wazuh-revision: "40717"
  #        - live: "True"
  #  foreach:
  #    - variable: macos-agent-os
  #      as: agent
  #  depends-on:
  #    - "allocate-macos-agent-{agent}"
  #    - "provision-manager-{manager-os}"
```

Result:

[test-agents-basic-info-full-linux.log](https://github.com/wazuh/wazuh-qa/files/15342498/test-agents-basic-info-full-linux.log)

**Comment by fcaffieri** [comment]
### Update report

The modifications were made to obtain the Windows version.

The unit tests were satisfactory.

Then when performing a full test, I encounter the following problem:

The agent is installed correctly, but for some reason winrm is now returning empty std_out and std_err, and the pytest validations fail. An example:

Logs:

![image](https://github.com/wazuh/wazuh-qa/assets/89791732/3065d752-32c6-4e6c-bc85-b585f9c1dcb7)

Inside Windows agent:

![image](https://github.com/wazuh/wazuh-qa/assets/89791732/a9a57701-ae0d-4c8b-a9f4-8440997f9d49)

The agent was installed successfully:

![image](https://github.com/wazuh/wazuh-qa/assets/89791732/baaa447b-b741-40a3-ad86-6b7bc8eda428)


I continue analyzing the problem

**Comment by fcaffieri** [comment]
### Update report

The problem was due to the winrm version. It was updated and the unit tests were successful:

![image](https://github.com/wazuh/wazuh-qa/assets/89791732/8cf6c483-f8b3-4d3e-acf5-785af49b74fc)


Full test:

Input yaml:

```

```


Result:

```

```

**Comment by fcaffieri** [comment]
### Update report


Obtaining the version from the agent was implemented based on dict_detect.sh:

```
     #Darwin
     elif [ "$(uname)" = "Darwin" ]; then
         DIST_NAME="darwin"
         DIST_VER=$(uname -r | sed -En 's/[^0-9]*([0-9]+).*/\1/p')
         DIST_SUBVER=$(uname -r | sed -En 's/[^0-9]*[0-9]+\.([0-9]+).*/\1/p')
```

But for Somona it brings the wrong version and produces a failure in the test due to disparity of versions.

![image](https://github.com/wazuh/wazuh-qa/assets/89791732/04b83744-ea94-4916-9b3f-1c8e27992fae)

The following command was used, obtaining the correct version from the agent:

```
sw_vers -productVersion
```

Unit test:

![image](https://github.com/wazuh/wazuh-qa/assets/89791732/4bc55516-d75d-4683-aa6c-7bf9cc853ca4)

**Comment by pro-akim** [comment]
## Review Notes
Windows test's log has errors that should be reviewed

![image](https://github.com/wazuh/wazuh-qa/assets/125690423/d51fba54-4e7c-4745-b852-18026df4e475)

**Comment by fcaffieri** [comment]
### Update report

The tests that failed were for the Windows systems windows-desktop-10-amd64 and windows-server-2016-amd64 because instances of the small type were used to create the VMs. This causes the allocator and consequently, the test to fail because the VMs are not instantiated. The logs display:

```
[33m[2024-05-20 09:59:20] [WARNING] ALLOCATOR: Error on attempt 28 of 30: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))[0m
[33m[2024-05-20 10:00:12] [WARNING] ALLOCATOR: Error on attempt 29 of 30: [0m
[33m[2024-05-20 10:01:05] [WARNING] ALLOCATOR: Error on attempt 30 of 30: [0m
```

The maximum waiting time was exceeded and then the instance was deleted due to failure from the allocator.

Tests were carried out with instances of the large type, to verify that the PR changes had no impact on this failure and the tests were satisfactory:


Intput yaml:

```
version: 0.1
description: This workflow is used to test agents deployment for DDT1 PoC
variables:
  agent-os:
    - windows-desktop-10-amd64
    - windows-server-2016-amd64
  manager-os: linux-ubuntu-22.04-amd64
  infra-provider: aws
  working-dir: /tmp/dtt1-poc

tasks:
  # Unique manager allocate task
  - task: "allocate-manager-{manager-os}"
    description: "Allocate resources for the manager."
    do:
      this: process
      with:
        path: python3
        args:
          - modules/allocation/main.py
          - action: create
          - provider: "{infra-provider}"
          - size: large
          - composite-name: "{manager-os}"
          - inventory-output: "{working-dir}/manager-{manager-os}/inventory.yaml"
          - track-output: "{working-dir}/manager-{manager-os}/track.yaml"
          - label-termination-date: "1d"
          - label-team: "qa"
          - label-issue: "https://github.com/wazuh/wazuh-qa/issues/5191"
    on-error: "abort-all"
    cleanup:
      this: process
      with:
        path: python3
        args:
          - modules/allocation/main.py
          - action: delete
          - track-output: "{working-dir}/manager-{manager-os}/track.yaml"

  # Unique agent allocate task
  - task: "allocate-agent-{agent}"
    description: "Allocate resources for the agent."
    do:
      this: process
      with:
        path: python3
        args:
          - modules/allocation/main.py
          - action: create
          - provider: "{infra-provider}"
          - size: large
          - composite-name: "{agent}"
          - inventory-output: "{working-dir}/agent-{agent}/inventory.yaml"
          - track-output: "{working-dir}/agent-{agent}/track.yaml"
          - label-termination-date: "1d"
          - label-team: "qa"
          - label-issue: "https://github.com/wazuh/wazuh-qa/issues/5191"
    on-error: "abort-all"
    foreach:
      - variable: agent-os
        as: agent
    cleanup:
      this: process
      with:
        path: python3
        args:
          - modules/allocation/main.py
          - action: delete
          - track-output: "{working-dir}/agent-{agent}/track.yaml"

  # Unique manager provision task
  - task: "provision-manager-{manager-os}"
    description: "Provision the manager."
    do:
      this: process
      with:
        path: python3
        args:
          - modules/provision/main.py
          - inventory: "{working-dir}/manager-{manager-os}/inventory.yaml"
          - install:
            - component: wazuh-manager
              type: assistant
              version: 4.7.4
              live: True
    depends-on:
      - "allocate-manager-{manager-os}"
    on-error: "abort-all"

  # Generic agent test task
  - task: "run-agent-{agent}-tests"
    description: "Run tests install for the agent {agent}."
    do:
      this: process
      with:
        path: python3
        args:
          - modules/testing/main.py
          - targets:
            - wazuh-1: "{working-dir}/manager-{manager-os}/inventory.yaml"
            - agent: "{working-dir}/agent-{agent}/inventory.yaml"
          - tests: "install,registration,basic_info"
          - component: "agent"
          - wazuh-version: "4.7.4"
          - wazuh-revision: "40717"
          - live: "True"
    foreach:
      - variable: agent-os
        as: agent
    depends-on:
      - "allocate-agent-{agent}"
      - "provision-manager-{manager-os}"

```

Result :green_circle: :

[test-agents-basic-info-windows-new.log](https://github.com/wazuh/wazuh-qa/files/15392431/test-agents-basic-info-windows-new.log)

**Comment by pro-akim** [comment]
## Review Notes
LGTM

**Comment by rauldpm** [comment]
LGTM
