### ISSUE TITLE
Migrate packages to S3 repository for E2E vulnerability detection testing

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#5365]
### Description

Our Vulnerability Detection End-to-End (E2E) tests utilize specific vulnerable packages to assess the effectiveness of our vulnerability detection mechanisms during package installation, removal, or upgrade.

To ensure test stability and resilience against third-party service fluctuations, we are migrating these packages to an S3 repository. The suggested storage path for these testing packages is `ci.wazuh.com/qa/testing_files`.

### Tasks

- [x] Upload currently used packages to the proposed directory.
- [x] Update the URLs of vulnerable packages to reflect the new uploads.

### Validation
- [x] E2E tests works as expected

**Comment by MARCOSD4** [comment]
## Update

All packages have been migrated to the S3 repository and the links to those packages have been changed, except some Grafana packages which are being changed in this [issue](https://github.com/wazuh/wazuh-qa/issues/5368).
The tests have been launched to check that what is currently in place works.

**Comment by MARCOSD4** [comment]
## Update

Blocked until the issue https://github.com/wazuh/wazuh-qa/issues/5368 is finished.

**Comment by MARCOSD4** [comment]
## Update

The migration of the missing packages to [S3](https://us-east-1.console.aws.amazon.com/s3/buckets/ci.wazuh.com?prefix=qa/testing_files/end_to_end/vulnerability_detector/&region=us-east-1&bucketType=general) has been completed and the changes made in this [PR](https://github.com/wazuh/wazuh-qa/pull/5369) have been taken for this. In addition, old packages that are no longer used have been removed from the repository in order to keep the repository clean and save space.
Tests have been launched to check the correct functioning:

Report:

**Comment by santipadilla** [comment]
LGTM
