### ISSUE TITLE
Agent simulator Hotfixes syscollector messages produces analysisd errors

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#5374]
### Description

Since v4.8.0-beta6, it has been observed that the format of syscollector's hotfixes messages, as utilized by the agent simulator, is causing multiple errors in the manager.
```
2024/05/14 08:35:22 :router: ERROR: Error sending message to provider: Error parsing message, 1: 140: error: unknown enum value: dbsync_hotfix
2024/05/14 08:35:22 :router: ERROR: Error sending message to provider: Error parsing message, 1: 140: error: unknown enum value: dbsync_hotfix
2024/05/14 08:35:22 :router: ERROR: Error sending message to provider: Error parsing message, 1: 140: error: unknown enum value: dbsync_hotfix
2024/05/14 08:35:22 wazuh-analysisd: ERROR: (1287): Incorrect/unknown type value hotfix.
2024/05/14 08:35:22 wazuh-analysisd: ERROR: (1287): Incorrect/unknown type value hotfix.
2024/05/14 08:35:22 wazuh-analysisd: ERROR: (1287): Incorrect/unknown type value hotfix.
2024/05/14 08:35:22 :router: ERROR: Error sending message to provider: Error parsing message, 1: 140: error: unknown enum value: dbsync_hotfix
2024/05/14 08:35:22 wazuh-analysisd: ERROR: (1287): Incorrect/unknown type value hotfix.
2024/05/14 08:35:22 wazuh-analysisd: ERROR: (1287): Incorrect/unknown type value hotfix.
2024/05/14 08:35:22 :router: ERROR: Error sending message to provider: Error parsing message, 1: 140: error: unknown enum value: dbsync_hotfix
2024/05/14 08:35:23 wazuh-analysisd: ERROR: (1287): Incorrect/unknown type value hotfix.
2024/05/14 08:35:23 :router: ERROR: Error sending message to provider: Error parsing message, 1: 140: error: unknown enum value: dbsync_hotfix
2024/05/14 08:35:23 wazuh-analysisd: ERROR: (1287): Incorrect/unknown type value hotfix.
2024/05/14 08:35:23 wazuh-analysisd: ERROR: (1287): Incorrect/unknown type value hotfix.
2024/05/14 08:35:23 :router: ERROR: Error sending message to provider: Error parsing message, 1: 140: error: unknown enum value: dbsync_hotfix
2024/05/14 08:35:23 :router: ERROR: Error sending message to provider: Error parsing message, 1: 140: error: unknown enum value: dbsync_hotfix
2024/05/14 08:35:23 wazuh-analysisd: ERROR: (1287): Incorrect/unknown type value hotfix.
2024/05/14 08:35:23 wazuh-analysisd: ERROR: (1287): Incorrect/unknown type value hotfix.
2024/05/14 08:35:23 :router: ERROR: Error sending message to provider: Error parsing message, 1: 140: error: unknown enum value: dbsync_hotfix
2024/05/14 08:35:23 :router: ERROR: Error sending message to provider: Error parsing message, 1: 140: error: unknown enum value: dbsync_hotfix
```
### Tasks

- [ ]  Verify the implementation of the new hotfixes message format introduced in v4.8.0
- [ ]  Update hotfixes messages to adhere to the new standard in the AgentSimulator class

### Validation

- [ ] Simulate all syscollector message types on a v4.8.0 manager

**Comment by Rebits** [comment]
Duplicated https://github.com/wazuh/wazuh-qa/issues/5378
