### ISSUE TITLE
Support new stage RC 1 for 4.7.5 in wazuh-qa repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-qa#5416]
## Description

This issue attempts to support a new stage RC 1 for 4.7.5 in the wazuh-qa repository.

## Tasks

- [x] ~Ensure changelog is updated for 4.7.5 (if applicable)~ No changes
- [x] Bump revision for branch 4.7.5 on wazuh-qa repository.  https://github.com/wazuh/wazuh-qa/pull/5420
- [x] Create tag v4.7.5-rc1 from branch 4.7.5 on wazuh-qa repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-qa/releases/tag/v4.7.5-rc1.

**Comment by QU3B1M** [comment]
LGTM!

**Comment by jnasselle** [comment]
Back to In progress since REVISION was changed

**Comment by QU3B1M** [comment]
LGTM!
