### ISSUE TITLE
Publish release 4.7.5

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#5440]
## Description
This issue attempts to track the steps necessary to publish packages, OVA, AMI, docker images, and puppet forge for 4.7.2.

## Tasks
- [ ] Send AMI to analysis.
- [ ] Launch [`Publish_release`](https://ci.wazuh.info/job/Publish_release) pipeline.
- [ ] Upload latest Filebeat version.
- [ ] Build and release debug packages.
- [ ] Build and push [Docker Hub images](https://ci.wazuh.info/job/procedure_push_docker_images).
  - https://ci.wazuh.info/job/procedure_push_docker_images/
- [ ] Publish AMI.
  

More steps in https://github.com/wazuh/wazuh-qa/issues/4828#issuecomment-1884579902
