### ISSUE TITLE
Post release tasks for 4.7.5

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#5442]
## Description

This issue attempts to track the steps necessary to complete post-release maintenance tasks for 4.7.5.
The goal is to complete the following tasks, each task must have a PR associated with this issue.

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, `merge-4.7.5-into-4.8.0`.

## Tasks

- [x] Restore 4.8.0 packages
- [x] Disable pre-release upload
- [x] Merge branch `4.7.5` into branch `4.8.0`.
- [x] Merge branch `4.8.0` into branch `4.8.1`. 
- [x] Merge branch `4.8.1` into branch `4.8.2`. 
- [x] Merge branch `4.8.2` into branch `master`. 
- [x] Publish GitHub release as latest. https://github.com/wazuh/wazuh-qa/releases/tag/v4.7.5
- [x] Delete all stage pre-releases for 4.7.5 (https://github.com/wazuh/wazuh-qa/releases).
- [x] Delete all stage tags for v4.7.5. **BE CAREFUL NOT TO DELETE DEFINITIVE TAG**. Example: v4.7.5-rc1, 4.7.5-alpha1, etc.
- [x] Delete branch `4.7.5`.
