### ISSUE TITLE
Include an option to run E2E Vulnerability Detector tests with debug mode enabled

### ISSUE THREAD

**Issue by MARCOSD4** [wazuh/wazuh-qa#5469]
## Description

This issue proposes a modification to the Vulnerability Detector E2E tests to include the possibility of executing them with debug mode enabled. This would allow us to obtain more detailed logs in the event of a bug or error, which could provide us with more information and assist the development team in identifying and resolving the root cause of the problem.

### Tasks

- [ ] Adapt tests to allow execution in debug mode
- [ ] Include debug mode check in the pipeline

### Validation
- [ ] E2E test works as expected
