### ISSUE TITLE
Publish release 4.8.0

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-qa#5490]
## Description
This issue attempts to track the steps necessary to publish packages, OVA, AMI, docker images, and puppet forge for 4.8.0.

## Tasks
- [ ] Send AMI to analysis.
- [ ] Launch [`Publish_release`](https://ci.wazuh.info/job/Publish_release) pipeline.
- [ ] Upload latest Filebeat version.
- [ ] Build and release debug packages.
- [ ] Build and push [Docker Hub images](https://ci.wazuh.info/job/procedure_push_docker_images).
- [ ] Publish AMI.

**Comment by Rebits** [comment]
LGTM
