### ISSUE TITLE
Post publication live checks for 4.8.0

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-qa#5491]
## Description
This issue attempts to ensure the publication process was correct, attempting checks and live tests for published packages and images.

## Tasks
- [x] Ensure that production files are present.
    - https://github.com/wazuh/wazuh-qa/issues/5491#issuecomment-2162923019
- [x] Deploy the `Wazuh Installation Assistant` and check the version installed is 4.8.0.
- [x] [AMD64 Live installation test](https://ci.wazuh.info/job/Test_install_tier).
    - https://ci.wazuh.info/job/Test_install_tier/932
    - https://ci.wazuh.info/job/Test_install/163968 (Solaris replay)
- [x] WPK versions check.
- [x] WPK upgrade test.
  - [x] Linux
  - [x] MacOS Intel
  - [x] Windows
- [x] [AMI published](https://aws.amazon.com/marketplace/pp/prodview-eju4flv5eqmgq).
- [x] [Puppet forge module published](https://forge.puppet.com/modules/wazuh/wazuh/readme).
- [x] [Docker images published](https://hub.docker.com/u/wazuh).

**Comment by Rebits** [comment]
<details>
<summary>Deploy the Wazuh Installation Assistant and check the version installed is 4.8.0</summary>

**Ubuntu 22.04**

```
root@ip-172-31-0-10:/home/qa# curl -sO https://packages.wazuh.com/4.8/wazuh-install.sh && sudo bash ./wazuh-install.sh -a
12/06/2024 12:29:44 INFO: Starting Wazuh installation assistant. Wazuh version: 4.8.0
12/06/2024 12:29:44 INFO: Verbose logging redirected to /var/log/wazuh-install.log
12/06/2024 12:29:45 INFO: Verifying that your system meets the recommended minimum hardware requirements.
12/06/2024 12:30:10 INFO: Wazuh web interface port will be 443.
12/06/2024 12:30:15 INFO: Wazuh repository added.
12/06/2024 12:30:15 INFO: --- Configuration files ---
12/06/2024 12:30:15 INFO: Generating configuration files.
12/06/2024 12:30:15 INFO: Generating the root certificate.
12/06/2024 12:30:15 INFO: Generating Admin certificates.
12/06/2024 12:30:16 INFO: Generating Wazuh indexer certificates.
12/06/2024 12:30:16 INFO: Generating Filebeat certificates.
12/06/2024 12:30:16 INFO: Generating Wazuh dashboard certificates.
12/06/2024 12:30:17 INFO: Created wazuh-install-files.tar. It contains the Wazuh cluster key, certificates, and passwords necessary for installation.
12/06/2024 12:30:17 INFO: --- Wazuh indexer ---
12/06/2024 12:30:17 INFO: Starting Wazuh indexer installation.
12/06/2024 12:32:27 INFO: Wazuh indexer installation finished.
12/06/2024 12:32:35 INFO: Wazuh indexer post-install configuration finished.
12/06/2024 12:32:35 INFO: Starting service wazuh-indexer.
12/06/2024 12:32:46 INFO: wazuh-indexer service started.
12/06/2024 12:32:46 INFO: Initializing Wazuh indexer cluster security settings.
12/06/2024 12:32:57 INFO: Wazuh indexer cluster security configuration initialized.
12/06/2024 12:32:57 INFO: Wazuh indexer cluster initialized.
12/06/2024 12:32:57 INFO: --- Wazuh server ---
12/06/2024 12:32:57 INFO: Starting the Wazuh manager installation.
12/06/2024 12:34:53 INFO: Wazuh manager installation finished.
12/06/2024 12:34:53 INFO: Wazuh manager vulnerability detection configuration finished.
12/06/2024 12:34:53 INFO: Starting service wazuh-manager.
12/06/2024 12:35:08 INFO: wazuh-manager service started.
12/06/2024 12:35:08 INFO: Starting Filebeat installation.
12/06/2024 12:35:35 INFO: Filebeat installation finished.
12/06/2024 12:35:36 INFO: Filebeat post-install configuration finished.
12/06/2024 12:35:36 INFO: Starting service filebeat.
12/06/2024 12:35:38 INFO: filebeat service started.
12/06/2024 12:35:38 INFO: --- Wazuh dashboard ---
12/06/2024 12:35:38 INFO: Starting Wazuh dashboard installation.
12/06/2024 12:38:58 INFO: Wazuh dashboard installation finished.
12/06/2024 12:38:58 INFO: Wazuh dashboard post-install configuration finished.
12/06/2024 12:38:58 INFO: Starting service wazuh-dashboard.
12/06/2024 12:38:59 INFO: wazuh-dashboard service started.
12/06/2024 12:39:00 INFO: Updating the internal users.
12/06/2024 12:39:04 INFO: A backup of the internal users has been saved in the /etc/wazuh-indexer/internalusers-backup folder.
12/06/2024 12:39:47 INFO: Initializing Wazuh dashboard web application.
12/06/2024 12:39:47 INFO: Wazuh dashboard web application not yet initialized. Waiting...
12/06/2024 12:40:03 INFO: Wazuh dashboard web application not yet initialized. Waiting...
12/06/2024 12:40:18 INFO: Wazuh dashboard web application initialized.
12/06/2024 12:40:18 INFO: --- Summary ---
12/06/2024 12:40:18 INFO: You can access the web interface https://<wazuh-dashboard-ip>:443
    User: admin
    Password: 5OhbguMKYx4pjmbRYxtUYIS3Q+Zoem9e
12/06/2024 12:40:18 INFO: Installation finished.
```


![image](https://github.com/wazuh/wazuh-qa/assets/11089305/31ae063c-5b95-4797-856f-9d99db020b0a)


</details>

**Comment by santipadilla** [comment]
## WPK Upgrade Test Windows

**Comment by juliamagan** [comment]
## WPK upgrade test

<details>
<summary>macOS :green_circle:</summary>
<br>

- Agent info:

```shell
sh-3.2# /Library/Ossec/bin/wazuh-control info
WAZUH_VERSION="v4.7.5"
WAZUH_REVISION="40720"
WAZUH_TYPE="agent"
```

- Agent info (in manager):

```shell
root@wazuh-manager:/home/vagrant# /var/ossec/bin/agent_control -i 001

Wazuh agent_control. Agent information:
   Agent ID:   001
   Agent Name: macos1012
   IP address: any
   Status:     Active

   Operating system:    Darwin |macos1012 |16.7.0 |Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 |x86_64
   Client version:      Wazuh v4.7.5
   Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
   Shared file hash:    4a8724b20dee0124ff9656783c490c4e
   Last keep alive:     1718198015

   Syscheck last started at:  Wed Jun 12 13:11:00 2024
   Syscheck last ended at:    Wed Jun 12 13:11:04 2024
```

- Agent update:

```shell
root@wazuh-manager:/home/vagrant# /var/ossec/bin/agent_upgrade -a 001

Upgrading...

Upgraded agents:
	Agent 001 upgraded: Wazuh v4.7.5 -> Wazuh v4.8.0
```

- Agent info:

```shell
sh-3.2# /Library/Ossec/bin/wazuh-control info
WAZUH_VERSION="v4.8.0"
WAZUH_REVISION="40812"
WAZUH_TYPE="agent"
```

- Agent info (in manager):

```shell
root@wazuh-manager:/home/vagrant# /var/ossec/bin/agent_control -i 001

Wazuh agent_control. Agent information:
   Agent ID:   001
   Agent Name: macos1012
   IP address: any
   Status:     Active

   Operating system:    Darwin |macos1012 |16.7.0 |Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 |x86_64
   Client version:      Wazuh v4.8.0
   Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
   Shared file hash:    4a8724b20dee0124ff9656783c490c4e
   Last keep alive:     1718198122

   Syscheck last started at:  Wed Jun 12 13:14:22 2024
   Syscheck last ended at:    Wed Jun 12 13:14:26 2024
```


</details>

**Comment by MARCOSD4** [comment]
LGTM
