### ISSUE TITLE
Remove hardcoded references to branch in provision playbooks for E2E tests

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#5509]
## Description

The E2E vulnerability detection tests currently use playbooks from the QA repository to provision the environment. However, these playbooks are inherited from the Wazuh Ansible repository and include hardcoded versions, making the repository difficult to maintain. More information can be found in this [discussion](https://github.com/wazuh/wazuh-qa/pull/5499#discussion_r1644645097).

To address this issue, it has been proposed to remove these hardcoded references, adapt the Ansible playbook modules to our needs, and update the provisioning modules in the Jenkins libraries accordingly.

## Tasks
- [x] Remove any hardcoded references in the provision modules in the QA repository
- [x] Include necessary parameters in Jenkins pipelines to replace hardcoded values

## Validation

- [x] Ensure E2E vulnerability detection tests are provisioned and run correctly after removing hardcoded references.

**Comment by santipadilla** [comment]
- Branch with hardcoded code removal from qa repository: `enhancement/5509-remove-hardcoded-branch-references`
  - In this PR: https://github.com/wazuh/wazuh-qa/pull/5517
  
- Branch with the parameters in jenkins to replace the hardcoded values `enhancement/5509-include-parameters-replace-harcoded`
  - In this PR: https://github.com/wazuh/wazuh-jenkins/pull/6635

- Created copy of the pipeline for testing VD test: `https://ci.wazuh.info/job/Test_e2e_system_dev_5509/`

**Comment by santipadilla** [comment]
## Update

Machines were destroyed in the pipeline copy due to name change with suffix _dev. More details [here](https://wazuh-team.slack.com/archives/C038AR25C8N/p1718886397417389).
Launched and modified original pipeline with the new parameter: `https://ci.wazuh.info/job/Test_e2e_system/`

**Comment by Rebits** [comment]
Moved ETA to 02/07/2024 to allow apply requested changes
