### ISSUE TITLE
Support new stage Alpha 1 for 4.9.0 in wazuh-qa repository

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#5513]
## Description

This issue attempts to support a new stage Alpha 1 for 4.9.0 in the wazuh-qa repository.

## Tasks

- [ ] Ensure changelog is updated for 4.9.0 (if applicable).
- [ ] Bump revision for branch 4.9.0 on wazuh-qa repository.
- [ ] Create tag v4.9.0-alpha1 from branch 4.9.0 on wazuh-qa repository.
- [ ] Create and publish a pre-release: https://github.com/wazuh/wazuh-qa/releases/tag/v4.9.0-alpha1.
