### ISSUE TITLE
CentOS9 not working in the Allocator module

### ISSUE THREAD

**Issue by davidcr01** [wazuh/wazuh-qa#5522]
## Description

I've found that the CentOS9 in the AWS provider is not working in the Allocator module:
```console
> python3 modules/allocation/main.py --action create --provider aws --size large --composite-name linux-centos-9-amd64 --inventory-output "/tmp/dtt1-poc/test-centos/inventory.yaml" --track-output "/tmp/dtt1-poc/test-centos/track.yaml" --label-issue "https://github.com/wazuh/wazuh/issues/24136" --label-termination-date "1d" --label-team "devops"
[2024-06-28 10:50:48] [DEBUG] SPNEGO._GSS: Python gssapi not available, cannot use any GSSAPIProxy protocols: No module named 'gssapi'
[2024-06-28 10:50:48] [DEBUG] SPNEGO._GSS: Python gssapi IOV extension not available: No module named 'gssapi'
[2024-06-28 10:50:48] [INFO] ALLOCATOR: Creating instance at /tmp/wazuh-qa
[2024-06-28 10:50:49] [DEBUG] ALLOCATOR: No config provided. Generating from payload
[2024-06-28 10:50:49] [DEBUG] ALLOCATOR: Generating new key pair
[2024-06-28 10:50:49] [DEBUG] ALLOCATOR: Creating base directory: /tmp/wazuh-qa/AWS-C8DB2F49-D0E8-4479-A0A5-2BCF1A451FF3
Traceback (most recent call last):
  File "/home/davidcr01/Wazuh/wazuh-qa/deployability/modules/allocation/main.py", line 39, in <module>
    main()
  File "/home/davidcr01/Wazuh/wazuh-qa/deployability/modules/allocation/main.py", line 35, in main
    Allocator.run(InputPayload(**vars(parse_arguments())))
  File "/home/davidcr01/Wazuh/wazuh-qa/deployability/modules/allocation/allocation.py", line 40, in run
    return cls.__create(payload)
  File "/home/davidcr01/Wazuh/wazuh-qa/deployability/modules/allocation/allocation.py", line 59, in __create
    instance = provider.create_instance(
  File "/home/davidcr01/Wazuh/wazuh-qa/deployability/modules/allocation/generic/provider.py", line 71, in create_instance
    return cls._create_instance(base_dir, params, config, ssh_key)
  File "/home/davidcr01/Wazuh/wazuh-qa/deployability/modules/allocation/aws/provider.py", line 119, in _create_instance
    instance_id = cls.__create_ec2_instance(config)
  File "/home/davidcr01/Wazuh/wazuh-qa/deployability/modules/allocation/aws/provider.py", line 200, in __create_ec2_instance
    root_device_name = ami['Images'][0]['RootDeviceName']
IndexError: list index out of range
```

It seems that the AMI does not exists, so the Allocator module fails.

## Tasks

- [x] Found a valid AMI for CentOS8. If not, we should create one.
- [x] Add it to the Allocator module.
- [ ] Launch the AMI with the Allocator module.

**Comment by davidcr01** [comment]
# Update Report

The AMI was replaced by: `ami-0df2a11dd1fe1f8e3`

## Testing

```console
> python3 modules/allocation/main.py --action create --provider aws --size large --composite-name linux-centos-9-amd64 --inventory-output "/tmp/dtt1-poc/test-centos/inventory.yaml" --track-output "/tmp/dtt1-poc/test-centos/track.yaml" --label-issue "https://github.com/wazuh/wazuh-qa/issues/5522" --label-termination-date "1d" --label-team "devops"
[2024-06-28 12:04:52] [DEBUG] SPNEGO._GSS: Python gssapi not available, cannot use any GSSAPIProxy protocols: No module named 'gssapi'
[2024-06-28 12:04:52] [DEBUG] SPNEGO._GSS: Python gssapi IOV extension not available: No module named 'gssapi'
[2024-06-28 12:04:52] [INFO] ALLOCATOR: Creating instance at /tmp/wazuh-qa
[2024-06-28 12:04:53] [DEBUG] ALLOCATOR: No config provided. Generating from payload
[2024-06-28 12:04:53] [DEBUG] ALLOCATOR: Generating new key pair
[2024-06-28 12:04:53] [DEBUG] ALLOCATOR: Creating base directory: /tmp/wazuh-qa/AWS-C0864B0B-AA94-475C-8284-0C9BF4956207
[2024-06-28 12:05:13] [DEBUG] ALLOCATOR: Renaming temp /tmp/wazuh-qa/AWS-C0864B0B-AA94-475C-8284-0C9BF4956207 directory to /tmp/wazuh-qa/i-0b25a2cee37fb6da2
[2024-06-28 12:05:13] [INFO] ALLOCATOR: Instance i-0b25a2cee37fb6da2 created.
[2024-06-28 12:05:15] [INFO] ALLOCATOR: Instance i-0b25a2cee37fb6da2 started.
[2024-06-28 12:05:15] [INFO] ALLOCATOR: The inventory file generated at /tmp/dtt1-poc/test-centos/inventory.yaml
[2024-06-28 12:05:15] [INFO] ALLOCATOR: The track file generated at /tmp/dtt1-poc/test-centos/track.yaml
[2024-06-28 12:05:17] [WARNING] ALLOCATOR: Error on attempt 1 of 30: [Errno None] Unable to connect to port 2200 on 34.227.190.76
[2024-06-28 12:05:49] [INFO] ALLOCATOR: SSH connection successful.
[2024-06-28 12:05:49] [INFO] ALLOCATOR: Instance i-0b25a2cee37fb6da2 created successfully.

> ssh -i /tmp/wazuh-qa/i-0b25a2cee37fb6da2/qa-5522-centos-9-key-7977 ec2-user@ec2-34-227-190-76.compute-1.amazonaws.com -p
2200
The authenticity of host '[ec2-34-227-190-76.compute-1.amazonaws.com]:2200 ([34.227.190.76]:2200)' can't be established.
ED25519 key fingerprint is SHA256:wavZNC5dM91CXNteEYgU5iY9X4ED9AdIj/dbRcA2i4U.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '[ec2-34-227-190-76.compute-1.amazonaws.com]:2200' (ED25519) to the list of known hosts.
[ec2-user@ip-172-31-28-139 ~]$ cat /etc/os-release 
NAME="CentOS Stream"
VERSION="9"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="9"
PLATFORM_ID="platform:el9"
PRETTY_NAME="CentOS Stream 9"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:centos:centos:9"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"
[ec2-user@ip-172-31-28-139 ~]$ 
```
