### ISSUE TITLE
Review the wazuh-qa repository for relevant code to migrate

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#5531]
| Main issue|
|-----|
| https://github.com/wazuh/wazuh-qa/issues/5527 |

## Description

Analyze the content of the repository `wazuh-qa`, detect and document the code pertinent to migrate to the new QA repository.

## Tasks

- [x] Review the `wazuh-qa` repository
- [x] Identify relevant code for migration to the new QA repository
- [x] Document a proposal for migration with a possible directory structure

## Conclusion

Content found relevant:

- `deployability\`: It needs improved code, but it should be moved.
- `deps\wazuh_testing\data\data_visualizer`: Used on e2e, at the moment, I will suggest improving it.
- `deps\wazuh_testing\wazuh_testing\data\vulnerability_parsed_packages.json`: It depends. If there aren't changes on VD, they should be moved, else we can remove them.
- `deps\wazuh_testing\wazuh_testing\data\syscollector.py`: If there aren't changes on Syscollector test for 4.10.0 should be moved and then apply improvements elsenot requires moved.
- `deps\wazuh_testing\wazuh_testing\end_to_end`: Must be refactored, and could be used as a reference for new tests. It's OK to migrate them only to have some e2e tests for now.
  > Also we have to define if these are E2E tests or just another tier of System tests
- `deps\wazuh_testing\wazuh_testing\modules`: If required by the new System tests, use the version from [qa-integration-framework](https://github.com/wazuh/qa-integration-framework/tree/main/src/wazuh_testing/modules) instead of this one.
- `deps\wazuh_testing\wazuh_testing\tools`: These tools were refactored/improved on the [qa-integration-framework](https://github.com/wazuh/qa-integration-framework/) repository, the code from that repository must be used as reference.

Structure proposed:
```shellsession
Wazuh-qa
├ dependencies
├ scripts
├ deployability
├ compoment
├ systems
├ e2e
└ Documentación con Changelog, versionado y Readme.
```

**Comment by damarisg** [comment]
### 03/07/2024 

- Review the wazuh-qa repository
- Start to Identify relevant code.

**Comment by QU3B1M** [comment]
LGTM!
