### ISSUE TITLE
Review the wazuh-jenkins repository for relevant code to migrate

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#5532]
| Main issue|
|-----|
| https://github.com/wazuh/wazuh-qa/issues/5527 |

## Description

Analyze the content of the repository `wazuh-jenkins`, detect and document the code pertinent to migrate to the new QA repository.

## Tasks

- [x] Identify the content of each section from the `wazuh-jenkins` repository in a generic way.  
- [x] Detect the code belonging to the QA team
- [x] Identify relevant code for migration to the new QA repository
- [x] Document a proposal for migration with a possible directory structure

_Note: For each task add a comment._

## Task Conclusion

Content found relevant:

- `.github\workflows\`:  contains part that was worked on Jenkins redesign.
- `ansible\playbooks\`: It should be migrated, or review the code that is used.
- `ansible\roles\`: It's instantiated by some tests.
- `bootstrap\`: contains part that was worked on Jenkins redesign.
- `jenkins-ui\`: contains part that was worked on Jenkins redesign.
- `new-jenkins\`: contains part that was worked on Jenkins redesign.
- `jenkins-files\live\`: contains a pipeline to publish a release
- `jenkins-files\test\`: most of this code should be migrated.
- `quality\`: I think the tests and deployments folders should be migrated or reviewed, I have doubts about the rest of the content.
- `doc\`: If migration is required, I think it should be updated.
- `quality\deployments`: part of the code should be migrated or at least reviewed to reuse.
- `quality\tests`: part of the code should be migrated or at least reviewed to reuse.
- `scripts\`: I'm not sure if the contents of this folder should be migrated, but I think there could be a "scripts" folder in the new repository.
- `testing-tools\`:I have doubts if it is relevant to migrate. It contains files that help generate test data, but I see that they were created a long time ago and apparently were not maintained.
- `vars\`: We need most of the content of this folder. It used by tests and contains constants representing paths, configs, etc.

## Document a proposal for migration with a possible directory structure

```
│
├── .github/
│   └── workflows/ 
├── ansible/
│   ├── playbooks/          
│   └── roles/              
├── jenkins/            
│   ├── pipelines/      
│   ├── deploy/         
│   ├── release/        
│   │   └── procedures/                      
│   └── bootstrap/                          
├── docs/                                   
├── src/
│   ├── data/  
│   └── tests/
│       └── connection/
│       └── install/
│       └── upgrade/
│       └── register/                                         
├── scripts/
├── utils/
│   └── testing-tools//                             
└── constants/                   
```

**Comment by pcapellan** [comment]
I started working on 07/03/2024
- Download and review the wazuh-jenkins repository

**Comment by pcapellan** [comment]
- Analize each folder of the repository

**Comment by pcapellan** [comment]
Summary of main project folders and my opinion on what I consider relevant to migrate to the new repository
```
├───.github/                            # Migrate "workflows" section
├───ansible-playbooks/                  # It should be migrated, or review the code that is used. 
├───ansible-roles/                      # This is instantiated by some tests.
├───bootstrap/                          # It should be migrated. Is part of jenkins redesign.
├───doc/                                # If migration is required, I think it should be updated.
├───dockers/                            # I have doubts if this is relevant to migrate.
├───jenkins-files/                      # The "tests" folder is the most important to migrate. I have doubts about the rest of the content. 
├───jenkins-ui/                         # It should be migrated. Is part of jenkins redesign.
├───new-jenkins/                        # It should be migrated. Is part of jenkins redesign.
├───quality/                            # I think the tests and deployments folders should be migrated or reviewed, I have doubts about the rest of the content.
├───scripts/                            # I don't know if we need to migrate this folder.
├───src/                                # I have doubts if we should migrate all the content, but I think there are things that can help us.
├───testing-tools/                      #I have doubts if it is relevant to migrate. It contains files that help generate test data, but I see that 
│                                       they were created a long time ago and apparently were not maintained.
└───vars/                               # We need most of the content of this folder. It used by tests and contains constants representing paths, configs, etc.
```

**Comment by pcapellan** [comment]
### Project Structure for "jenkins-files" folder.

```
├───jenkins-file/
│    ├───analysis/
│    ├───deploy/
│    ├───launchers/
│    ├───live/
│    ├───monitoring/
│    ├───packages/
│    ├───procedures/
│    ├───pull_requests/
│    └───tests/
│        ├───generic/    
│        ├───performance/
│        ├───pre-release/
│        └───reliability/
└───unit_testing/    
```

<details>
<summary>"jenkins-files" tests folder</summary>

```
├───jenkins-files/
│       ├──tests/
│       │      ├──generic/
│       │      │       └──test_re_registration_agents.groovy
│       │      ├──performance/
│       │      │       └──test_cluster.groovy
│       │      │       └──test_fim.groovy
│       │      ├───pre-release/
│       │      │         └──test_install_tier.groovy
│       │      │         └──test_stack_tier.groovy
│       │      │         └──test_stress_tier.groovy
│       │      │         └──test_unattended_tier.groovy
│       │      │         └──test_upgrade_tier.groovy
│       │      └───reliability/
│       │      │         └──relibility_launcher.groovy
│       │      │         └──test_reliability.groovy
│       │      └─────test_reliability.groovy
│       │      └─────test_reliability.groovy
│       │      └─────test_reliability.groovy
│       │      └─────test_reliability.groovy
│       │      └─────test_reliability.groovy
│       │      └─────test_reliability.groovy
│       │      └─────test_reliability.groovy
│       │      └─────test_reliability.groovy
│       │      └─────test_reliability.groovy
│       │      └─────test_reliability.groovy
│       │      └─────test_reliability.groovy


  
```
</details>

**Comment by pcapellan** [comment]
### Document a proposal for migration with a possible directory structure
#### Then analyzing the wazuh-jenkins repository and considering the parts of the code that could be migrated or reused, I think a directory structure could be:

```
│
├── .github/
│   └── workflows/ 
├── ansible/
│   ├── playbooks/          
│   └── roles/              
├── jenkins/            
│   ├── pipelines/      
│   ├── deploy/         
│   ├── release/        
│   │   └── procedures/                      
│   └── bootstrap/                          
├── docs/                                   
├── src/
│   ├── data/  
│   ├── tests/
│   │   └── connection/
│   │   └── install/
│   │   └── upgrade/
│   │   └── register/                                         
├── scripts/
├── utils/
│   └── testing-tools//                             
└── constants/                   
```

**Comment by QU3B1M** [comment]
Requested some minor changes.

**Comment by QU3B1M** [comment]
LGTM!
