### ISSUE TITLE
Review the wazuh-tools repository for relevant code to migrate

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#5534]
| Main issue|
|-----|
| https://github.com/wazuh/wazuh-qa/issues/5527 |

## Description

Analyze the content of the repository `wazuh-tools`, detect and document the code pertinent to migrate to the new QA repository.

## Tasks

- [x] Review the `wazuh-tools` repository
- [x] Detect the code belonging to the QA team
- [x] Identify relevant code for migration to the new QA repository
- [x] Document a proposal for migration with a possible directory structure

### Review the repository

[`wazuh-tools`](https://github.com/wazuh/wazuh-tools) repository contains a lot of scripts and tools that belongs to different teams. The QA team has some outdated scripts and some that are still in use, this code must be migrated to the new QA repository.

### Detect the code belonging to the QA team

The QA team only own a few directories in the wazuh-tools repository, so the mandatory migration from wazuh-tools to the new QA repo wont be a big task. The following is a list of directories owned by the QA team: 

- `footprint/sca`: This directory contains the footprint tests owned by the QA team.
- `documentation-scripts/`: This directory contains the tests for the documentation redirects. The QA team does not fully own this.

### Identify relevant code for migration to the new QA repository

As mentioned previously, only a few directories are owned by the QA team. But more directories could be useful for the QA team. The following is a list of directories owned by QA that must be migrated along with other directories that could be useful for the QA team, at least the idea of the approach:

#### Mandatories refactor and migration
- `footprint/sca`: Current sca footprint tests. Must be migrated alongside the rest of the stress tests used for footprint that resides on _wazuh-jenkins_
#### Possible content to use as a reference for new approaches.
- `cluster_docker`: This directory contains deployment tests for the wazuh-cluster. It is outdated but the tests can be used as a reference for the new QA repository.
- `documentation-scripts/check-redirects`: Tests for the documentation redirects. Outdated but could be refactored
- `documentation-scripts/visual-test`: Visual tests for the documentation, could be used as a reference for the new QA repository.
- `indexer_benchmarks`: Indexer benchmarks, it does not belong to QA, but we could implement something similar in our new QA repository.
- `testing/performance`: Performance tests owned by Core team. We could implement something similar in our new QA repository.
- `utils/enrollment-bench.py`: Enrollment benchmark, not owned by QA but the idea could be useful for the new QA repository.

### Document a proposal for migration with a possible directory structure

The identified relevant code for a migration could be organized into two groups, non-functional tests and benchmarks (documentation tests could also be moved to a group of their own), taking this in mind, the following is a proposal for the new QA repository directory structure:

```shellsession
[qa-repo]
│
├── non_functional_tests
│   ├── stress_tests
│   │   └── sca_test
│   ├── performance_tests
│   └── documentation_tests
│       ├── redirects_test
│       └── visual_test
└── benchmarks
    ├── indexer_benchmark
    └── enrollment_benchmark
```

**Comment by QU3B1M** [comment]
## Update report

- Review the wazuh-tools repository. Done
- Detect the code belonging to the QA team. Done
- Identify relevant code for migration to the new QA repository. Done
- Document a proposal for migration with a possible directory structure. WIP

**Comment by damarisg** [comment]
### Review

According to what was analyzed and proposed, we should migrate only "footprint/sca" and improve it, but nothing about the rest. The proposed proposal will remain in the epic of definition.
