### ISSUE TITLE
Review the qa-integration-framework repository for relevant code to migrate

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#5547]
| Main issue|
|-----|
| https://github.com/wazuh/wazuh-qa/issues/5527 |

## Description

Analyze the content of the repository `qa-integration-framework`, detect and document the code pertinent to migrate to the new QA repository.

## Tasks

- [x] Review the `qa-integration-framework` repository
- [x] Identify relevant code for migration to the new QA repository
- [x] Document a proposal for migration with a possible directory structure

### Review the qa-integration-framework repository

This repository is a migration of the current _wazuh-qa_ framework with also some code taken from `qa-system-framework` repository, currently, it belongs to the core and framework teams (now named _server_, _agent_ and _pyserver_ teams). It contains several useful tools and scripts that could be used in in our new framework, and as this repository is fairly recently migrated, the code is more up-to-date and could be used as a reference for the migration without needing many changes.
It also has a lot of Integration-Tests-specific code that is not useful for our case, so we just ignore that part.

### Identify relevant code for migration to the new QA repository

In this case, similar to the analysis in https://github.com/wazuh/wazuh-qa/issues/5535, the file structure could be used as inspiration for the new framework, it needs some changes and re-ordering of the scripts, but there is a lot of useful code in here. Basically we could just ignore the `modules/`, `simulators/`, and the majority of `data/` and take everything else (with the pertinent modifications) to the new framework.
> **Note:** The `simulators/` folder could be useful if we need to mock specific Wazuh services on the new framework, but it requires a deeper analysis to know if our tests will need to mock those services.

<details><summary>Files to migrate</summary>

```bash
./
└── src/
    └── wazuh_testing/
        ├── constants/  # Constants that represents several Wazuh's Binaries, configurations, and logs paths, and also Daemons, Sockets, etc.
        ├── data/ 
        │   └── feeds/                      # Contains a set of feeds for VD
        ├── scripts/
        │   └── syslog_simulator.py         # Sislog simulator needs a refactor and be moved to simulators
        ├── tools/
        │   ├── certificate_controller.py   # Class to handle certificates.
        │   ├── db_administrator.py         # Could be a module that also includes the database scripts from utils/.
        │   ├── mitm.py                     # Must be separated into different modules
        │   ├── monitors/                   # Set of classes to monitor Files and Queues
        │   │   ├── base_monitor.py
        │   │   ├── file_monitor.py
        │   │   └── queue_monitor.py
        │   ├── simulators/                 # ONLY MIGRATE IF WE NEED TO MOCK SPECIFIC WAZUH SERVICES ON THE NEW FRAMEWORK
        │   │   ├── agent_simulator.py      # If migrated [REQUIRES REFACTOR]
        │   │   ├── authd_simulator.py
        │   │   ├── base_simulator.py
        │   │   ├── remoted_simulator.py
        │   │   └── run_syslog_simulator.py
        │   ├── socket_controller.py        # Class to handle sockets, could be moved to utils
        │   └── thread_executor.py          # Class to handle and execute Python threads, could be moved to utils
        └── utils/      # Set of useful utils that could be taken to the new framework.
            ├── agent_groups.py             # Agent groups using binaries, could be moved to a wazuh-agent related utils module - Specific util
            ├── callbacks.py                # Callbacks utils for monitors, could be part of monitors as util of that module - Specific utils
            ├── client_keys.py              # client.keys file interaction, could be moved to a wazuh-agent related utils module - Specific util
            ├── cluster.py                  # Cluster message generation, could be part of a Cluster simulator - Specific util
            ├── commands.py                 # Run commands on Linux, which could be useful - Generic utils
            ├── configuration.py            # Wazuh configuration files handling, could be moved to a related module - Specific util
            ├── database.py                 # Wazuh database handling, could be moved to a wazuh-database related module - Specific util
            ├── db_queries/                 # Queries belonging to the database, must be moved with the previous script - Specific util
            ├── decorators.py               # Stores one decorator that could be moved to a more general module - Generic utils
            ├── file.py                     # Set of functions to work with files - Generic utils
            ├── manage_agents.py            # Manage agent using binaries, could be moved to a wazuh-agent related utils module - Specific util
            ├── mocking.py                  # Mocks agents, another version of the agent simulator, could be moved to a wazuh-agent related utils module - Specific util
            ├── network.py                  # Network-related utils - Generic utils
            ├── random.py                   # Random generation related utils - Generic utils
            ├── secure_message.py           # Wazuh secure message utils, could be moved to a related module - Specific util
            ├── services.py                 # Wazuh control services interaction utils, could be moved to a related module - Specific util
            ├── sockets.py                  # Wazuh sockets utils, could be moved to a related module - Specific util
            ├── string.py                   # Only one function, random string generation, must be moved to the random module - Generic utils
            └── time.py                     # Time-related utils - Generic utils
```
</details>

### Document a proposal for migration with a possible directory structure

As mentioned previously, a big part of the code in this repository could be used at least as a reference for the new framework, so by ignoring the non-relevant code for our case, we could take the following code to the new framework:

> This is a simplified description of the proposed directories to migrate.
- `constants/` Store the constants that represents several Wazuh's Binaries, configurations, and logs paths, and also Daemons, Sockets, etc.
- `data/feed/` Store a set of feeds for VD.
- `tools/` Store the classes to handle _certificates_, _database_, _mitm_, _monitors_, _simulators_, _sockets_, and _thread executor_.
- `scripts/syslog_simulator.py` [Only if simulators are needed] Used to simulate syslog, but it needs a refactor and be moved to simulators.
- `utils/` Store the generic utils used by the framework or the tests themself.

Taking the detected useful code, we could fit it in the following directory structure on the new framework:

```shellsession
./
└── src/
    └── wazuh_testing/
        ├── constants/
        ├── data/ 
        │   └── feeds/
        ├── scripts/
        ├── tools/
        │   ├── database/                   
        │   │   ├── database.py
        │   │   ├── db_administrator.py
        │   │   └── db_queries/
        │   ├── monitors/                   
        │   │   ├── base_monitor.py
        │   │   ├── file_monitor.py
        │   │   ├── queue_monitor.py
        │   │   └── callbacks.py 
        │   ├── simulators/ # ONLY IF WE NEED TO MOCK SPECIFIC WAZUH SERVICES ON THE NEW FRAMEWORK
        │   │   ├── agent_simulator.py      
        │   │   ├── authd_simulator.py
        │   │   ├── base_simulator.py
        │   │   ├── cluster_simulator.py
        │   │   ├── remoted_simulator.py 
        │   │   ├── run_syslog_simulator.py
        │   │   └── syslog_simulator.py      
        │   ├── binaries/
        │   │   ├── agent_groups.py
        │   │   └── manage_agents.py
        │   ├── sockets/          
        │   │   ├── socket_controller.py
        │   │   └── base_socket.py
        │   ├── certificate_controller.py
        │   ├── client_keys.py
        │   ├── configuration.py
        │   ├── mitm.py
        │   ├── services.py                 
        │   ├── secure_message.py
        │   └── thread_executor.py
        └── utils/
            ├── commands.py
            ├── decorators.py
            ├── file.py
            ├── network.py
            ├── random.py
            └── time.py
```

**Comment by QU3B1M** [comment]
# QA System Framework

This repository contains a proposed framework for the QA system tests, which development was stopped since September 2023. It has an interesting design, and it is a good starting point for the development of a new QA framework.

## What to migrate from this repository?

As mentioned previously, the design of this repository is interesting, and it is a good starting point for the development of a new QA framework, anyway the code is outdated and some if it was taken for the qa-integration-framework and improved by the Core team.

### Code

Parts of the code that could be taken from this repository to the new QA framework are:
- `src/wazuh_qa_framework/`
    - `generic_modules`: A set of generic tools and scripts that can be used in any kind of test. A lot of this code could be taken and improved if necesary.
        - `exceptions/`: A generic set of exceptions.
        - `file/`: A set of functions to work with files. A lot of functions are missing that could be taken from [qa-integration-framework utils](https://github.com/wazuh/qa-integration-framework/blob/main/src/wazuh_testing/utils/file.py).
        - `logging/framework_logger.py`: A logger for the framework. (the repo also has another logger named pytest_logger tha is not needed)
        - `process/`: A set of classes to run and monitor OS processes.
        - `requests/`: A set of functions to make HTTP requests. Could be improved
        - `threading/`: A class to handle python threads.
        - `time/`: A class make the work with time easier.
        - `tools/`: Includes simplified version of the FileMonitor. This was also implemented and improved in [qa-integration-framework tools](https://github.com/wazuh/qa-integration-framework/tree/main/src/wazuh_testing/tools/monitors)
    - `global_variables`: Could be renamed to `Constants`, a set of global constants that are used in the framework.
    - `meta_testing`: A set of not so related functions. From here, only the functions inside `utils.py` are useful
        - `utils.py`: A set of functions to work with the framework, if migrated, most of the functions should be moved to other directory. functions `read_file`, `write_file`, `remove_file`, `clean_file`, `append_log` must be stored inside `generic_modules/file/` directory, the remaining `custom_callback` function could be left here.
    - `wazuh_components`: A set of modules that are used to interact with Wazuh components. The mayority of the modules are empty, but the `wazuh_api` module is interesting to migrate and improve.
        - `api`: A set of functions to interact with the Wazuh API. This module could be migrated and improved.

- `tests/`: Unit tests for the framework. This must be migrated and improved.

### File strcuture

The file structure of this repository is interesting and could be taken as a base for the new QA framework. Using this structure as base I could propose something like this:
```bash
./
├── README.md
├── wazuh_qa_framework/
│   ├── __init__.py
│   ├── requirements.txt
│   ├── setup.py
│   ├── generic/
│   ├── constants/
│   ├── utils/
│   └── wazuh/
└── tests
    ├── __init__.py
    ├── generic/
    ├── constants/
    ├── utils/
    └── wazuh/
```

**Comment by QU3B1M** [comment]
## Update report
- Analyzing the repository looking for relevant code to migrate
- Writing a document with the analysis done, it will be posted in this issue's main comment

**Comment by damarisg** [comment]
LGTM!
