### ISSUE TITLE
Create new Wazuh QA repository with the defined scaffold

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#5556]
| Objective |
|---|
| https://github.com/wazuh/wazuh-packages/issues/2904 | 

## Description

This issue aims for the creation of the new _"[wazuh-qa-automation](https://github.com/wazuh/wazuh-qa-automation)"_ private repository with the defined directory structure _(the conclusion of https://github.com/wazuh/wazuh-qa/issues/5527)_.

All the, currently dispersed in several repositories, content related to the _QA team_ analyzed on the issue https://github.com/wazuh/wazuh-qa/issues/5527 (Task _Investigate current repositories and their content_) must be migrated to the new **wazuh-qa** repository.

> [!important]
>
> Migration must be performed keeping the commit history from the files intact. Follow the research about this topic: https://github.com/wazuh/wazuh-qa/issues/5574

## Tasks

- [x] Create the private repository _"[wazuh-qa-automation](https://github.com/wazuh/wazuh-qa-automation)"_
- [x] Create branch 4.10.0: [PR wazuh/wazuh-qa#8](https://github.com/wazuh/wazuh-qa-automation/pull/8)
- [x] Define structure of "main" branch: [PR wazuh/wazuh-qa#36](https://github.com/wazuh/wazuh-qa-automation/pull/36)
- [x] https://github.com/wazuh/wazuh-qa/issues/5557
- [x] https://github.com/wazuh/wazuh-qa/issues/5561
- [x] https://github.com/wazuh/wazuh-qa/issues/5560
- [x] https://github.com/wazuh/wazuh-qa/issues/5563
- [x] https://github.com/wazuh/wazuh-qa/issues/5562
- [ ] https://github.com/wazuh/wazuh-qa-automation/issues/348
- [x] https://github.com/wazuh/wazuh-qa-automation/issues/52
- [x] Update README/documentation/branch
        - https://github.com/wazuh/wazuh-qa-automation/pull/12
        - https://github.com/wazuh/wazuh-qa-automation/pull/112
        - https://github.com/wazuh/wazuh-qa-automation/pull/172     
        - https://github.com/wazuh/wazuh-qa-automation/pull/121
        - https://github.com/wazuh/wazuh-qa-automation/issues/301

**Comment by damarisg** [comment]
<details><summary> 2024/07/24</summary>

- Create branch 4.10.0
- Create and work on the `Apply Structure` task in the `enhancement/5556-add-directory-structure` branch.
</details>
