### ISSUE TITLE
Migrate new Jenkins and QA tools to the new QA repository

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#5557]
| Main issue |
|-----|
| https://github.com/wazuh/wazuh-qa/issues/5556 |

## Description

Migrate the new Jenkins code developed for https://github.com/wazuh/wazuh-jenkins/issues/5927 and the new QA tools made on https://github.com/wazuh/wazuh-qa/issues/4495 and on https://github.com/wazuh/wazuh-jenkins/issues/6359 to the _new **wazuh-qa**_ repository respecting the defined structure: https://github.com/wazuh/wazuh-qa/issues/5475#issuecomment-2239970249

- **Main issue PR:** https://github.com/wazuh/wazuh-qa-automation/pull/20

## Tasks
- [x] Migrate JobFlow (ex Workflow engine) tool - https://github.com/wazuh/wazuh-qa-automation/pull/9
- [x] Migrate Provision module - https://github.com/wazuh/wazuh-qa-automation/pull/10
- [x] Migrate release procedures - https://github.com/wazuh/wazuh-qa-automation/pull/15
- [x] Migrate new Jenkins's code - https://github.com/wazuh/wazuh-qa-automation/pull/16
- [x] Migrate Tests module and DTT workflows - https://github.com/wazuh/wazuh-qa-automation/pull/17
    - CSV with the migrated DTT coverage: [Coverage.xlsx](https://github.com/user-attachments/files/16599916/Coverage.xlsx)
- [x] Identify and list the possible improvements to each migrated module - https://github.com/wazuh/wazuh-qa/issues/5557#issuecomment-2271262817

> [!important]
>
> Once all the tasks' PRs are approved and merged, review and merge the main migrations branch PR: https://github.com/wazuh/wazuh-qa-automation/pull/20

**Comment by QU3B1M** [comment]
## Update report

- Migrate JobFlow's code to new QA repository: https://github.com/wazuh/wazuh-qa-automation/pull/9

**Comment by QU3B1M** [comment]
## Identify and list the possible improvements to each migrated module

### JobFlow

Medium priority improvements:
- **tools/jobflow/README.md:** Main documentation file of the JobFlow tool
    Currently, the documentation is DTT1-specific, it does not help the user to understand what the tool does, and how it can be used for different cases.

Low priority improvements:
- **tools/jobflow/tests:** Unit Tests suite
    This suite uses Python's default test runner UnitTests utilities and pytest as the runner, it could be improved by only using pytest and its utilities, which is recommended.
- **tools/jobflow/examples:** Workflows examples directory
    We must add more Workflows as examples of different use cases.

### Provision

Medium priority improvements:
- **tools/provision/README.md:** Main documentation file of the Provision tool
    This README is strongly related to the JobFlow, it could be improved detailing mainly the standalone execution and having the JobFlow workflow as a secondary use.

Low-priority improvements:
- **tools/provision/src/provision/playbooks/wazuh:** Wazuh-related playbooks
    This directory could be re-structured, probably the non install/uninstall actions (register, services, set repo) could be separated on a different folder as these actions are not specifically related to an installation type.
- **tools/provision/tests:** Unit Tests suite
    This suite uses Python's default test runner UnitTests utilities and pytest as the runner, it could be improved by only using pytest and its utilities, which is recommended.

**Comment by damarisg** [comment]
GJ!
