### ISSUE TITLE
Migrate all QA-related code to the new wazuh-qa repository

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#5558]
## Description

All the, currently dispersed in several repositories, content related to the _QA team_ analyzed on the issue https://github.com/wazuh/wazuh-qa/issues/5527 (Task _Investigate current repositories and their content_) must be migrated to the new **wazuh-qa** repository.

## Tasks

- [ ] https://github.com/wazuh/wazuh-qa/issues/5557
- [ ] https://github.com/wazuh/wazuh-qa/issues/5560
- [ ] https://github.com/wazuh/wazuh-qa/issues/5561
- [ ] https://github.com/wazuh/wazuh-qa/issues/5562
- [ ] https://github.com/wazuh/wazuh-qa/issues/5563
- [ ] https://github.com/wazuh/wazuh-qa/issues/5564
