### ISSUE TITLE
FIM system tests:  Adapt Agents/Manager ossec.conf file according to OS family

### ISSUE THREAD

**Issue by Zenidd** [wazuh/wazuh-qa#557]
### Objective

This issue aims to maintain and distribute the Linux agents different configuration files depending on its operating system. Currently, it is intended to introduce RPM and DEB templates.

Also, a task to automatically detect and assign the right `ossec.conf` file is required.

### Tasks

- [x] agents - **deb**  and  **rpm** `ossec.conf` file segregation. https://github.com/wazuh/wazuh-qa/commit/4c0a242f7a754a38e2bb3b9741bcca64423d9cd9
- [x]  manager - **rpm** `ossec.conf`file  https://github.com/wazuh/wazuh-qa/commit/96b915dc1c2aa2e526058d4d0cb7d290d284e126
- [x] automation task https://github.com/wazuh/wazuh-qa/pull/565/commits/65be2d503438eff3045a12daf6d775c18376ae66

Related wiki entry: https://github.com/wazuh/wazuh-qa/wiki/FIM-System-tests:-Default-ossec.conf-files
