### ISSUE TITLE
Support new stage RC 3 for 4.8.1 in wazuh-qa repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-qa#5572]
## Description

This issue attempts to support a new stage RC 3 for 4.8.1 in the wazuh-qa repository.

## Tasks

- [x] Ensure changelog is updated for 4.8.1 (if applicable). Not needed
- [x] Bump revision for branch 4.8.1 on wazuh-qa repository. https://github.com/wazuh/wazuh-qa/pull/5573
- [x] Create tag v4.8.1-rc3 from branch 4.8.1 on wazuh-qa repository. https://github.com/wazuh/wazuh-qa/releases/tag/v4.8.1-rc3
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-qa/releases/tag/v4.8.1-rc3.

**Comment by rafabailon** [comment]
### LGTM
