### ISSUE TITLE
Publish release 4.8.1

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-qa#5581]
## Description
This issue attempts to track the steps necessary to publish packages, OVA, AMI, docker images, and puppet forge for 4.8.1.

## Tasks
- [x] Send AMI to analysis: https://aws.amazon.com/marketplace/management/manage-products/?#/ami-0a5241a34db4c3a20/details
- [x] Launch [`Publish_release`](https://ci.wazuh.info/job/Publish_release) pipeline without Kibana, Splunk, templates and unattended. https://ci.wazuh.info/job/Publish_release/399/console
- [x] Wait for `Publish_release` to finish.
- [x] Publish unattended and templates. https://ci.wazuh.info/job/publish_unattended/304/
- [x] ~Upload the latest Filebeat version.~ Not needed, same version pre-release and production
- [x] Release debug packages and checksums.

<details>

<summary> Output </summary>

```
➜  ~ aws s3 cp s3://packages-dev.wazuh.com/pre-debug/4.8/deb/ s3://packages.wazuh.com/cloud/4.8.x/deb/ --recursive --acl public-read

copy: s3://packages-dev.wazuh.com/pre-debug/4.8/deb/wazuh-agent_4.8.0-0.debug_amd64.deb to s3://packages.wazuh.com/cloud/4.8.x/deb/wazuh-agent_4.8.0-0.debug_amd64.deb
copy: s3://packages-dev.wazuh.com/pre-debug/4.8/deb/wazuh-agent_4.8.0-0.debug_i386.deb to s3://packages.wazuh.com/cloud/4.8.x/deb/wazuh-agent_4.8.0-0.debug_i386.deb
copy: s3://packages-dev.wazuh.com/pre-debug/4.8/deb/wazuh-agent_4.8.0-0.debug_arm64.deb to s3://packages.wazuh.com/cloud/4.8.x/deb/wazuh-agent_4.8.0-0.debug_arm64.deb
copy: s3://packages-dev.wazuh.com/pre-debug/4.8/deb/wazuh-agent_4.8.0-0.debug_ppc64el.deb to s3://packages.wazuh.com/cloud/4.8.x/deb/wazuh-agent_4.8.0-0.debug_ppc64el.deb
copy: s3://packages-dev.wazuh.com/pre-debug/4.8/deb/wazuh-agent_4.8.0-0.debug_armhf.deb to s3://packages.wazuh.com/cloud/4.8.x/deb/wazuh-agent_4.8.0-0.debug_armhf.deb
copy: s3://packages-dev.wazuh.com/pre-debug/4.8/deb/wazuh-agent_4.8.1-0.debug_armhf.deb to s3://packages.wazuh.com/cloud/4.8.x/deb/wazuh-agent_4.8.1-0.debug_armhf.deb
copy: s3://packages-dev.wazuh.com/pre-debug/4.8/deb/wazuh-agent_4.8.1-0.debug_i386.deb to s3://packages.wazuh.com/cloud/4.8.x/deb/wazuh-agent_4.8.1-0.debug_i386.deb
copy: s3://packages-dev.wazuh.com/pre-debug/4.8/deb/wazuh-agent_4.8.1-0.debug_amd64.deb to s3://packages.wazuh.com/cloud/4.8.x/deb/wazuh-agent_4.8.1-0.debug_amd64.deb
copy: s3://packages-dev.wazuh.com/pre-debug/4.8/deb/wazuh-agent_4.8.1-0.debug_arm64.deb to s3://packages.wazuh.com/cloud/4.8.x/deb/wazuh-agent_4.8.1-0.debug_arm64.deb
copy: s3://packages-dev.wazuh.com/pre-debug/4.8/deb/wazuh-agent_4.8.1-0.debug_ppc64el.deb to s3://packages.wazuh.com/cloud/4.8.x/deb/wazuh-agent_4.8.1-0.debug_ppc64el.deb
copy: s3://packages-dev.wazuh.com/pre-debug/4.8/deb/wazuh-manager_4.8.0-0.debug_amd64.deb to s3://packages.wazuh.com/cloud/4.8.x/deb/wazuh-manager_4.8.0-0.debug_amd64.deb
copy: s3://packages-dev.wazuh.com/pre-debug/4.8/deb/wazuh-manager_4.8.0-0.debug_arm64.deb to s3://packages.wazuh.com/cloud/4.8.x/deb/wazuh-manager_4.8.0-0.debug_arm64.deb
copy: s3://packages-dev.wazuh.com/pre-debug/4.8/deb/wazuh-manager_4.8.1-0.debug_amd64.deb to s3://packages.wazuh.com/cloud/4.8.x/deb/wazuh-manager_4.8.1-0.debug_amd64.deb
copy: s3://packages-dev.wazuh.com/pre-debug/4.8/deb/wazuh-manager_4.8.1-0.debug_arm64.deb to s3://packages.wazuh.com/cloud/4.8.x/deb/wazuh-manager_4.8.1-0.debug_arm64.deb
➜  ~ ╰─➤  aws s3 cp s3://packages-dev.wazuh.com/pre-debug/4.8/rpm/ s3://packages.wazuh.com/cloud/4.8.x/rpm/ --recursive --acl public-read
➜  ~ aws s3 cp s3://packages-dev.wazuh.com/pre-debug/4.8/rpm/ s3://packages.wazuh.com/cloud/4.8.x/rpm/ --recursive --acl public-read
copy: s3://packages-dev.wazuh.com/pre-debug/4.8/rpm/wazuh-agent-4.8.0-0.debug.aarch64.rpm to s3://packages.wazuh.com/cloud/4.8.x/rpm/wazuh-agent-4.8.0-0.debug.aarch64.rpm
copy: s3://packages-dev.wazuh.com/pre-debug/4.8/rpm/wazuh-agent-4.8.0-0.debug.x86_64.rpm to s3://packages.wazuh.com/cloud/4.8.x/rpm/wazuh-agent-4.8.0-0.debug.x86_64.rpm
copy: s3://packages-dev.wazuh.com/pre-debug/4.8/rpm/wazuh-agent-4.8.0-0.debug.armv7hl.rpm to s3://packages.wazuh.com/cloud/4.8.x/rpm/wazuh-agent-4.8.0-0.debug.armv7hl.rpm
copy: s3://packages-dev.wazuh.com/pre-debug/4.8/rpm/wazuh-agent-4.8.0-0.debug.i386.rpm to s3://packages.wazuh.com/cloud/4.8.x/rpm/wazuh-agent-4.8.0-0.debug.i386.rpm
copy: s3://packages-dev.wazuh.com/pre-debug/4.8/rpm/wazuh-agent-4.8.1-0.debug.aarch64.rpm to s3://packages.wazuh.com/cloud/4.8.x/rpm/wazuh-agent-4.8.1-0.debug.aarch64.rpm
copy: s3://packages-dev.wazuh.com/pre-debug/4.8/rpm/wazuh-agent-4.8.1-0.debug.armv7hl.rpm to s3://packages.wazuh.com/cloud/4.8.x/rpm/wazuh-agent-4.8.1-0.debug.armv7hl.rpm
copy: s3://packages-dev.wazuh.com/pre-debug/4.8/rpm/wazuh-agent-4.8.1-0.debug.ppc64le.rpm to s3://packages.wazuh.com/cloud/4.8.x/rpm/wazuh-agent-4.8.1-0.debug.ppc64le.rpm
copy: s3://packages-dev.wazuh.com/pre-debug/4.8/rpm/wazuh-agent-4.8.1-0.debug.i386.rpm to s3://packages.wazuh.com/cloud/4.8.x/rpm/wazuh-agent-4.8.1-0.debug.i386.rpm
copy: s3://packages-dev.wazuh.com/pre-debug/4.8/rpm/wazuh-agent-4.8.1-0.debug.x86_64.rpm to s3://packages.wazuh.com/cloud/4.8.x/rpm/wazuh-agent-4.8.1-0.debug.x86_64.rpm
copy: s3://packages-dev.wazuh.com/pre-debug/4.8/rpm/wazuh-manager-4.8.0-0.debug.aarch64.rpm to s3://packages.wazuh.com/cloud/4.8.x/rpm/wazuh-manager-4.8.0-0.debug.aarch64.rpm
copy: s3://packages-dev.wazuh.com/pre-debug/4.8/rpm/wazuh-agent-4.8.0-0.debug.ppc64le.rpm to s3://packages.wazuh.com/cloud/4.8.x/rpm/wazuh-agent-4.8.0-0.debug.ppc64le.rpm
copy: s3://packages-dev.wazuh.com/pre-debug/4.8/rpm/wazuh-manager-4.8.0-0.debug.x86_64.rpm to s3://packages.wazuh.com/cloud/4.8.x/rpm/wazuh-manager-4.8.0-0.debug.x86_64.rpm
copy: s3://packages-dev.wazuh.com/pre-debug/4.8/rpm/wazuh-manager-4.8.1-0.debug.aarch64.rpm to s3://packages.wazuh.com/cloud/4.8.x/rpm/wazuh-manager-4.8.1-0.debug.aarch64.rpm
copy: s3://packages-dev.wazuh.com/pre-debug/4.8/rpm/wazuh-manager-4.8.1-0.debug.x86_64.rpm to s3://packages.wazuh.com/cloud/4.8.x/rpm/wazuh-manager-4.8.1-0.debug.x86_64.rpm
➜  ~ aws s3 cp s3://packages-dev.wazuh.com/pre-debug/checksums/wazuh/4.8.1/ s3://packages.wazuh.com/cloud/checksums/wazuh/4.8.1/ --recursive --acl public-read
copy: s3://packages-dev.wazuh.com/pre-debug/checksums/wazuh/4.8.1/wazuh-agent_4.8.1-0.debug_arm64.deb.sha512 to s3://packages.wazuh.com/cloud/checksums/wazuh/4.8.1/wazuh-agent_4.8.1-0.debug_arm64.deb.sha512
copy: s3://packages-dev.wazuh.com/pre-debug/checksums/wazuh/4.8.1/wazuh-agent-4.8.1-0.debug.aarch64.rpm.sha512 to s3://packages.wazuh.com/cloud/checksums/wazuh/4.8.1/wazuh-agent-4.8.1-0.debug.aarch64.rpm.sha512
copy: s3://packages-dev.wazuh.com/pre-debug/checksums/wazuh/4.8.1/wazuh-agent_4.8.1-0.debug_armhf.deb.sha512 to s3://packages.wazuh.com/cloud/checksums/wazuh/4.8.1/wazuh-agent_4.8.1-0.debug_armhf.deb.sha512
copy: s3://packages-dev.wazuh.com/pre-debug/checksums/wazuh/4.8.1/wazuh-agent-4.8.1-0.debug.armv7hl.rpm.sha512 to s3://packages.wazuh.com/cloud/checksums/wazuh/4.8.1/wazuh-agent-4.8.1-0.debug.armv7hl.rpm.sha512
copy: s3://packages-dev.wazuh.com/pre-debug/checksums/wazuh/4.8.1/wazuh-agent-4.8.1-0.debug.i386.rpm.sha512 to s3://packages.wazuh.com/cloud/checksums/wazuh/4.8.1/wazuh-agent-4.8.1-0.debug.i386.rpm.sha512
copy: s3://packages-dev.wazuh.com/pre-debug/checksums/wazuh/4.8.1/wazuh-agent-4.8.1-0.debug.ppc64le.rpm.sha512 to s3://packages.wazuh.com/cloud/checksums/wazuh/4.8.1/wazuh-agent-4.8.1-0.debug.ppc64le.rpm.sha512
copy: s3://packages-dev.wazuh.com/pre-debug/checksums/wazuh/4.8.1/wazuh-agent_4.8.1-0.debug_amd64.deb.sha512 to s3://packages.wazuh.com/cloud/checksums/wazuh/4.8.1/wazuh-agent_4.8.1-0.debug_amd64.deb.sha512
copy: s3://packages-dev.wazuh.com/pre-debug/checksums/wazuh/4.8.1/wazuh-agent_4.8.1-0.debug_ppc64el.deb.sha512 to s3://packages.wazuh.com/cloud/checksums/wazuh/4.8.1/wazuh-agent_4.8.1-0.debug_ppc64el.deb.sha512
copy: s3://packages-dev.wazuh.com/pre-debug/checksums/wazuh/4.8.1/wazuh-agent_4.8.1-0.debug_i386.deb.sha512 to s3://packages.wazuh.com/cloud/checksums/wazuh/4.8.1/wazuh-agent_4.8.1-0.debug_i386.deb.sha512
copy: s3://packages-dev.wazuh.com/pre-debug/checksums/wazuh/4.8.1/wazuh-agent-4.8.1-0.debug.x86_64.rpm.sha512 to s3://packages.wazuh.com/cloud/checksums/wazuh/4.8.1/wazuh-agent-4.8.1-0.debug.x86_64.rpm.sha512
copy: s3://packages-dev.wazuh.com/pre-debug/checksums/wazuh/4.8.1/wazuh-manager-4.8.1-0.debug.aarch64.rpm.sha512 to s3://packages.wazuh.com/cloud/checksums/wazuh/4.8.1/wazuh-manager-4.8.1-0.debug.aarch64.rpm.sha512
copy: s3://packages-dev.wazuh.com/pre-debug/checksums/wazuh/4.8.1/wazuh-manager_4.8.1-0.debug_arm64.deb.sha512 to s3://packages.wazuh.com/cloud/checksums/wazuh/4.8.1/wazuh-manager_4.8.1-0.debug_arm64.deb.sha512
copy: s3://packages-dev.wazuh.com/pre-debug/checksums/wazuh/4.8.1/wazuh-manager-4.8.1-0.debug.x86_64.rpm.sha512 to s3://packages.wazuh.com/cloud/checksums/wazuh/4.8.1/wazuh-manager-4.8.1-0.debug.x86_64.rpm.sha512
copy: s3://packages-dev.wazuh.com/pre-debug/checksums/wazuh/4.8.1/wazuh-manager_4.8.1-0.debug_amd64.deb.sha512 to s3://packages.wazuh.com/cloud/checksums/wazuh/4.8.1/wazuh-manager_4.8.1-0.debug_amd64.deb.sha512
``` 

</details>

- [x] Push [Docker Hub images](https://ci.wazuh.info/job/procedure_push_docker_images). https://ci.wazuh.info/job/procedure_push_docker_images/158/

**Comment by Rebits** [comment]
- Sent AMI to analysis

**Comment by rauldpm** [comment]
LGTM
