### ISSUE TITLE
Post publication live checks for 4.8.1

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-qa#5582]
## Description
This issue attempts to ensure the publication process was correct, attempting checks and live tests for published packages and images.

## Tasks
- [x] Ensure that production files are present.
- [x] Deploy the `Wazuh Installation Assistant` and check the version installed is 4.8.1.
- [x] [AMD64 Live installation test](https://ci.wazuh.info/job/Test_install_tier): https://ci.wazuh.info/job/Test_install_tier/954/
- [x] WPK versions check.
- [x] WPK upgrade test.
  - [x] Linux
  - [x] MacOS Intel
  - [x] ~MacOS Apple Silicon~
  - [x] Windows
- [x] [Puppet forge module published](https://forge.puppet.com/modules/wazuh/wazuh/readme).
- [x] [Docker images published](https://hub.docker.com/u/wazuh).

**Comment by Rebits** [comment]
- Checking production files

**Comment by Rebits** [comment]
#  Deploy the Wazuh Installation Assistant and check the version installed is 4.8.1.

**Comment by MARCOSD4** [comment]
## WPK upgrade test

<details><summary>Linux</summary>



</details>

**Comment by Rebits** [comment]
### WPK versions check

**Comment by Rebits** [comment]
## WPK macOS :large_blue_circle: 

<details>

<summary> ARM </summary>

</details>



<details>

<summary> Intel </summary>

</details>

**Comment by jnasselle** [comment]
LGTM!

**Comment by rauldpm** [comment]
LGTM
