### ISSUE TITLE
Post release tasks for 4.8.1

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-qa#5583]
## Description
This issue attempts to track the steps necessary to complete post-release maintenance tasks for 4.8.1.
The goal is to complete the following tasks, each task must have a PR associated with this issue.

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, `merge-4.8.1-into-4.9.0`.

## Tasks

- [x] Update 4.8.1 Changelog release date https://github.com/wazuh/wazuh-qa/pull/5595/
- [x] Merge branch `4.8.1` into branch `4.9.0`.  https://github.com/wazuh/wazuh-qa/pull/5596
- [x] Merge branch `4.9.0` into branch `4.10.0`. https://github.com/wazuh/wazuh-qa/pull/5592, https://github.com/wazuh/wazuh-qa/pull/5597
- [x] Merge branch `4.10.0` into branch `master`. https://github.com/wazuh/wazuh-qa/pull/5594
- [x] Publish GitHub release as latest. https://github.com/wazuh/wazuh-qa/releases/tag/v4.8.1
- [x] Delete all stage pre-releases for 4.8.1 (https://github.com/wazuh/wazuh-qa/releases).
- [x] Delete all stage tags for v4.8.1. **BE CAREFUL NOT TO DELETE DEFINITIVE TAG**. Example: v4.8.1-rc1, 4.8.1-alpha1, etc.

**Comment by MARCOSD4** [comment]
LGTM

**Comment by rauldpm** [comment]
LGTM
