### ISSUE TITLE
Footprint test for 4.9.0 not working properly - `write_logs` function stopped executing

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/wazuh-qa#5584]
## Description

After running the footprint tests for release 4.9.0 Alpha 2 and analyzing the [issue](https://github.com/wazuh/wazuh/issues/24663), a big decrease in the events was detected, compared to 4.8.0 RC 4. So we need to investigate the following:

In the logs of 4.8.0, it is seen that the `write_logs` and `create_delete_logs` messages go from the beginning to the end of the test, however in the 4.9.0 logs it reaches a point after starting the test that `write_logs` is stopped, it coincides with the change of slope on the graph.

![image](https://github.com/user-attachments/assets/f91d0ff5-8173-40bc-99c4-c2352e056371)

<details>
   <summary>Logs:</summary>

```
[2024-07-13_10:10:54] [INFO] (write_logs): Appended message to 100 files.
[2024-07-13_10:10:54] [INFO] (write_logs): Sleep of 10 seconds started.
[2024-07-13_10:11:04] [INFO] (write_logs): Sleep of 10 seconds ended.
[2024-07-13_10:11:04] [INFO] (write_logs): Remaining test time 147202.
[2024-07-13_10:11:04] [INFO] (write_logs): Appending message to logs.
[2024-07-13_10:11:04] [INFO] (write_logs): Appended message to 100 files.
[2024-07-13_10:11:04] [INFO] (write_logs): Sleep of 10 seconds started.
[2024-07-13_10:11:14] [INFO] (write_logs): Sleep of 10 seconds ended.
[2024-07-13_10:11:14] [INFO] (write_logs): Remaining test time 147192.
[2024-07-13_10:11:14] [INFO] (write_logs): Appending message to logs.
[2024-07-13_10:11:14] [INFO] (write_logs): Appended message to 100 files.
[2024-07-13_10:11:14] [INFO] (write_logs): Sleep of 10 seconds started.
[2024-07-13_10:11:24] [INFO] (write_logs): Sleep of 10 seconds ended.
[2024-07-13_10:11:24] [INFO] (write_logs): File size exceeded. Deleting. File size: 25181 KB
[2024-07-13_10:14:32] [INFO] (create_delete_logs): Sleep of 300 seconds ended.
[2024-07-13_10:14:32] [INFO] (create_delete_logs): Starting log file deletion.
[2024-07-13_10:14:32] [INFO] (create_delete_logs): 1000 log files deleted.
[2024-07-13_10:14:32] [INFO] (create_delete_logs): Sleep of 300 seconds started.
[2024-07-13_10:19:32] [INFO] (create_delete_logs): Sleep of 300 seconds ended.
[2024-07-13_10:19:32] [INFO] (create_delete_logs): Remaining test time 146694.
[2024-07-13_10:19:32] [INFO] (create_delete_logs): Starting logs file creation.
[2024-07-13_10:19:32] [INFO] (create_delete_logs): 1000 log files created.
[2024-07-13_10:19:32] [INFO] (create_delete_logs): Sleep of 300 seconds started.
[2024-07-13_10:24:32] [INFO] (create_delete_logs): Sleep of 300 seconds ended.
[2024-07-13_10:24:32] [INFO] (create_delete_logs): Appending message to logs.
[2024-07-13_10:24:32] [INFO] (create_delete_logs): Appended message to 1000 files.
[2024-07-13_10:24:32] [INFO] (create_delete_logs): Sleep of 300 seconds started.
[2024-07-13_10:29:32] [INFO] (create_delete_logs): Sleep of 300 seconds ended.
[2024-07-13_10:29:32] [INFO] (create_delete_logs): Starting log file deletion.
[2024-07-13_10:29:32] [INFO] (create_delete_logs): 1000 log files deleted.
```

</details>

## Tasks

- [ ] Investigate why the `write_logs` function stopped executing
- [ ] Verify that the `syscollector` configuration is correct with the new changes
- [ ] Research the tmp/logcollector_test/logcollector.log files of each test, we have a big difference in the generation of events.

- 4.8.0
   - Appended message to 100 files. Appears 14,980 times
   - Appended message to 1000 files. Appears 168 times
   - Total Appended messages: 1,666,000
- 4.9.0
   - Appended message to 100 files. Appears 400 times
   - Appended message to 1000 files. Appears 168 times
   - Total Appended messages: 208,000

**Comment by joaquinsgi** [comment]
# Analysis Report

- It seems that the write_logs function stops working when it finds that size and feed are greater than 25165. After this, it reports that the size has been exceeded and then the function stops executing.
