### ISSUE TITLE
Support new stage Alpha 3 for 4.9.0 in wazuh-qa repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-qa#5585]
## Description

This issue attempts to support a new stage Alpha 3 for 4.9.0 in the wazuh-qa repository.

## Tasks

- [x] Ensure changelog is updated for 4.9.0 (if applicable). Not needed https://github.com/wazuh/wazuh-qa/pull/5568
- [x] Bump revision for branch 4.9.0 on wazuh-qa repository. https://github.com/wazuh/wazuh-qa/pull/5593
- [x] Create tag v4.9.0-alpha3 from branch 4.9.0 on wazuh-qa repository. https://github.com/wazuh/wazuh-qa/releases/tag/v4.9.0-alpha3
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-qa/releases/tag/v4.9.0-alpha3.

**Comment by Rebits** [comment]
We can start with this due to 4.9.0 was already updated with 4.8.1 in https://github.com/wazuh/wazuh-qa/issues/5583

**Comment by santipadilla** [comment]
LGTM

**Comment by Rebits** [comment]
New changes included in https://github.com/wazuh/wazuh-qa/issues/5583. Reopening to include them in the tag

**Comment by santipadilla** [comment]
LGTM
