### ISSUE TITLE
FIM system tests: Clean and Reinstall tasks

### ISSUE THREAD

**Issue by xr09** [wazuh/wazuh-qa#561]
### Description

Setup a clean and a reinstall playbook to setup the test environments from scratch.

### Tasks

- [x] Move `clean_environment.yml` to provision folder
- [x] Create `reinstall_environment.yml`
- [x] Test cleaning tasks
- [x] Test reinstall tasks

#### Working branch

- [561-clean-reinstall](https://github.com/wazuh/wazuh-qa/tree/feature-561-clean-reinstall)

### Usage

The workflow will be as follows:

#### Cleaning

```
ansible-playbook -i dev_hosts clean_environment.yml -e 'ansible_hosts_destination=dev_hosts'
```
#### Reinstall

```
ansible-playbook -i dev_hosts reinstall_environment.yml -e 'ansible_hosts_destination=dev_hosts'
```

#### Local Environment

Remember to modify `vars/elastic_nginx.yml` with `elastic_api_protocol: http` on the local vagrant environment.

**Comment by xr09** [comment]
Currently hitting a bug while uninstalling the Windows agent, we're using a 3.12.0 development version and the playbook is trying to uninstall 3.11.3, the clean tasks should take into account if the agent was provisioned with a custom version.

**Comment by xr09** [comment]
Cleaning playbook is ready, tasks were limited to just removing the packages and for elastic only index deletion, the service is kept running for minimizing waiting time on next execution.

**Comment by xr09** [comment]
Just discovered the reason Elastic index keeps getting data after cleaning the manager was a dangling filebeat process that kept sending logs even after being removed. A new action to detect it and stop it was [added](https://github.com/wazuh/wazuh-qa/pull/575/commits/9339dde082042311d33f298b703b6bc6429da72d).

**Comment by jm404** [comment]
Done in #575
