### ISSUE TITLE
Support new stage Beta 1 for 4.9.0 in wazuh-qa repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-qa#5632]
## Description

This issue attempts to support a new stage Beta 1 for 4.9.0 in the wazuh-qa repository.

## Tasks

- [ ] Ensure changelog is updated for 4.9.0 (if applicable).
- [ ] Bump revision for branch 4.9.0 on wazuh-qa repository.
- [ ] Create tag v4.9.0-beta1 from branch 4.9.0 on wazuh-qa repository.
- [ ] Create and publish a pre-release: https://github.com/wazuh/wazuh-qa/releases/tag/v4.9.0-beta1.

**Comment by Rebits** [comment]
- Missing changelogs:
  - https://github.com/wazuh/wazuh-qa/pull/5630
  - https://github.com/wazuh/wazuh-qa/pull/5627/
  - https://github.com/wazuh/wazuh-qa/pull/5625/
  - https://github.com/wazuh/wazuh-qa/pull/5624
  - https://github.com/wazuh/wazuh-qa/pull/5623/
  - https://github.com/wazuh/wazuh-qa/pull/5621
  - https://github.com/wazuh/wazuh-qa/pull/5620/
  - https://github.com/wazuh/wazuh-qa/pull/5612
  - https://github.com/wazuh/wazuh-qa/pull/5546/
  - ...

**Comment by fcaffieri** [comment]
LGTM
