### ISSUE TITLE
Migrate the `procedure_push_docker_images` pipeline to GHA

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-qa#5651]
| Objective |
|---|
| https://github.com/wazuh/wazuh-packages/issues/2904 | 

## Description
Because of the `Wazuh packages redesign tier 2` objective we need to migrate the `procedure_push_docker_images` pipeline from Jenkins to the new Jenkins.

## Tasks
- [x] Replicate the `procedure_push_docker_images` pipeline in new Jenkins
- [x] The pipeline should allow the following parameters:
    - IMAGE_TAG
    - DOCKER_REFERENCE
    - IMAGE_NAMES
    - FILEBEAT_MODULE_VERSION
    - REVISION
    - PUSH_IMAGES
- [x] The pipeline should allow to be executed on demand
- [x] Validate the Docker images build and publish procedure with the new Jenkins works

**Comment by YisDav** [comment]
First version of the code for the workflow job steps was added
Tests are still pending

![image](https://github.com/user-attachments/assets/b9902680-4475-417a-93ca-98b6cf3bd3b9)

**Comment by YisDav** [comment]
First successful test was completed
A test DockerHub account was used for performing the tests.

![image](https://github.com/user-attachments/assets/609f6064-7a03-44ec-a1e4-2ad10b3f95fa)

**Comment by YisDav** [comment]
## Tests
### Single node
Single node setup using the pushed test images (v4.8.2)

![image](https://github.com/user-attachments/assets/66dc1afb-3300-44f8-8bcb-2181dcdc0600)

Results

![image](https://github.com/user-attachments/assets/dc7a128d-46ae-47be-88fd-caae606c25a5)

![image](https://github.com/user-attachments/assets/d32ff67a-75de-41b3-9a5d-5fe4f44c0de1)

### Multi node
Multi node setup using the pushed test images (v4.8.2)

![image](https://github.com/user-attachments/assets/6318a3fd-dc8f-4aa5-ae8d-a2cf0c399729)

Results

![image](https://github.com/user-attachments/assets/97c22d9f-89ad-4c9c-ae26-76abfa4bab23)

![image](https://github.com/user-attachments/assets/ae22d7d4-ed03-4870-8e8a-866347d7a269)

**Comment by YisDav** [comment]
## Tests:

### Error code handling
If any error occurs, it must exit with non-zero code

![image](https://github.com/user-attachments/assets/1189de94-fb5c-4e22-b499-47fb1f6cba3a)

### Succeeded workflow execution
Workflow execution

![image](https://github.com/user-attachments/assets/54931e9e-1b5c-45a1-b382-852658c08483)

**Comment by teddytpc1** [comment]
The GH secrets were updated to use the `wazuhci` user to upload the Docker images.
