### ISSUE TITLE
Migrate the `procedure_push_docker_images` pipeline to GHA

### ISSUE THREAD

**Issue by teddytpc1** [wazuh/wazuh-qa#5653]
| Objective |
|---|
| https://github.com/wazuh/wazuh-packages/issues/2904 | 

## Description
Because of the `Wazuh packages redesign tier 2` objective we need to migrate the `procedure_push_docker_images` pipeline from Jenkins to GHA.

## Tasks
- [ ] Replicate the `procedure_push_docker_images` pipeline in GHA
- [ ] The GHA should allow the following parameters:
    - IMAGE_TAG
    - DOCKER_REFERENCE
    - IMAGE_NAMES
    - FILEBEAT_MODULE_VERSION
    - REVISION
    - PUSH_IMAGES
- [ ] The GHA should allow to be executed on demand
- [ ] Validate the Docker images build and publish procedure with the GHA works

**Comment by damarisg** [comment]
Duplicated
