### ISSUE TITLE
Adapt workflows that use the Allocator module for 4.10.0

### ISSUE THREAD

**Issue by c-bordon** [wazuh/wazuh-qa#5681]
Related: https://github.com/wazuh/wazuh-automation/issues/1767

With the migration of the allocation module to the wazuh-automation repository, it is necessary to adapt the workflows for version 4.10.0 to use this repository instead of wazuh-qa.

An important consideration is that wazuh-automation is a private repository, so additional permissions may need to be requested to download the module.

### Tasks (TBD)

- [ ] Analyze the impact of the change
- [ ] Request access to download the repository (module)
- [ ] Implement the changes
- [ ] Run the corresponding tests

**Comment by jnasselle** [comment]
# Update

Moving this to wazuh/wazuh-qa-automation
