### ISSUE TITLE
Post publication live checks for 4.8.2

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-qa#5687]
## Description
This issue attempts to ensure the publication process was correct, attempting checks and live tests for published packages and images.

## Tasks
- [ ] Ensure that production files are present.
- [ ] Deploy the `Wazuh Installation Assistant` and check the version installed is 4.8.2.
- [ ] [AMD64 Live installation test](https://ci.wazuh.info/job/Test_install_tier).
- [ ] WPK versions check.
- [ ] WPK upgrade test.
  - [ ] Linux
  - [ ] MacOS Intel
  - [ ] MacOS Apple Silicon
  - [ ] Windows
- [ ] [AMI published](https://aws.amazon.com/marketplace/pp/prodview-eju4flv5eqmgq).
- [ ] [Puppet forge module published](https://forge.puppet.com/modules/wazuh/wazuh/readme).
- [ ] [Docker images published](https://hub.docker.com/u/wazuh).

**Comment by Rebits** [comment]
### Checking production files :large_blue_circle:  
 

- [ ] Alpine
  - [ ] Agent x86_64
  - [ ] Agent aarch64
  - [ ] Agent armv7
  - [ ] Agent ppc64le
  - [ ] Agent x86
  - [ ] Agent armhf
- [ ] APT
  - [ ] Wazuh dashboard
  - [ ] Wazuh indexer
  - [ ] Manager amd64
  - [ ] Manager arm64
  - [ ] Agent i386
  - [ ] Agent x86_64
  - [ ] Agent armhf
  - [ ] Agent ppc64el
  - [ ] Agent arm64
- [ ] macOS
  - [ ] Agent intel64
  - [ ] Agent arm64v8
- [ ] Solaris
  - [ ] Agent Solaris 10 i386
  - [ ] Agent Solaris 11 i386
- [ ] Stack
  - [ ] Wazuh dashboard base
  - [ ] Wazuh indexer base
- [ ] UI
  - [ ] Wazuh dashboard app
    - [ ] 2.10.0
    - [ ] wazuhCore
    - [ ] wazuhCheckUpdates
- [ ] Windows
  - [ ] Agent
- [ ] WPK
  - [ ] Linux
  - [ ] Windows
  - [ ] macOS
- [ ] OVA
- [ ] YUM
  - [ ] Wazuh dashboard
  - [ ] Wazuh indexer
  - [ ] Manager x86_64
  - [ ] Manager aarch64
  - [ ] Agent i386
  - [ ] Agent x86_64
  - [ ] Agent armv7hl
  - [ ] Agent ppc64le
  - [ ] Agent aarch64
- [ ] YUM5
  - [ ] Agent i386
  - [ ] Agent x86_64
- [ ] Puppet module
  - [ ] Puppet
- [ ] Unattended 
- [ ] Checksums
- [ ] Special
  - [ ] AIX
  - [ ] HP-UX
  - [ ] Solaris 10
  - [ ] Solaris 11

**Comment by Rebits** [comment]
## Deploy the Wazuh Installation Assistant and check the version installed is 4.8.2 :large_blue_circle:

**Comment by Rebits** [comment]
### AMD64 Live installation test :large_blue_circle: 

**Build**: https://ci.wazuh.info/job/Test_install_tier/988/

**Comment by Rebits** [comment]
##  WPK versions check :large_blue_circle:

**Comment by pro-akim** [comment]
WPK Windows :construction:

**Comment by fcaffieri** [comment]
### Windows 11  :green_circle:  

<details>

Agent Check

![image](https://github.com/user-attachments/assets/fe4e30f1-3b09-4bd9-807b-2eab12621414)


Manager Check



```
root@stack-ubuntu2204:/home/vagrant# /var/ossec/bin/agent_control -l

Wazuh agent_control. List of available agents:
   ID: 000, Name: stack-ubuntu2204 (server), IP: 127.0.0.1, Active/Local
   ID: 002, Name: agent-win-wpk-2, IP: any, Active

List of agentless devices:

root@stack-ubuntu2204:/home/vagrant# /var/ossec/bin/agent_control -i 002

Wazuh agent_control. Agent information:
   Agent ID:   002
   Agent Name: agent-win-wpk-2
   IP address: any
   Status:     Active

   Operating system:    Microsoft Windows 11 Enterprise Evaluation
   Client version:      Wazuh v4.8.1
   Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
   Shared file hash:    4a8724b20dee0124ff9656783c490c4e
   Last keep alive:     1724174617

   Syscheck last started at:  Tue Aug 20 17:23:37 2024 (Scan in progress)
   Syscheck last ended at:    Unknown
root@stack-ubuntu2204:/home/vagrant# 
root@stack-ubuntu2204:/home/vagrant# /var/ossec/bin/agent_upgrade -a 002

Upgrading...

Upgraded agents:
	Agent 002 upgraded: Wazuh v4.8.1 -> Wazuh v4.8.2
root@stack-ubuntu2204:/home/vagrant# 
root@stack-ubuntu2204:/home/vagrant# /var/ossec/bin/agent_control -l

Wazuh agent_control. List of available agents:
   ID: 000, Name: stack-ubuntu2204 (server), IP: 127.0.0.1, Active/Local
   ID: 002, Name: agent-win-wpk-2, IP: any, Active

List of agentless devices:

root@stack-ubuntu2204:/home/vagrant# /var/ossec/bin/agent_control -i 002

Wazuh agent_control. Agent information:
   Agent ID:   002
   Agent Name: agent-win-wpk-2
   IP address: any
   Status:     Active

   Operating system:    Microsoft Windows 11 Enterprise Evaluation
   Client version:      Wazuh v4.8.2
   Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
   Shared file hash:    4a8724b20dee0124ff9656783c490c4e
   Last keep alive:     1724174789

   Syscheck last started at:  Tue Aug 20 17:24:49 2024
   Syscheck last ended at:    Tue Aug 20 17:25:09 2024

root@stack-ubuntu2204:/home/vagrant# 


```

Agent Check
![image](https://github.com/user-attachments/assets/8183bd47-e096-4800-953d-a8805727da90)


</details>

**Comment by Rebits** [comment]
### Windows WPK Upgrade

The detailed error was already reported in https://github.com/wazuh/wazuh/issues/20727 and fixed in 4.9.0. We can continue with the release

**Comment by jseg380** [comment]
LGTM
