### ISSUE TITLE
Maintain production and numbered branches post release 4.9.0 in wazuh-qa repository

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#5703]
## Description

The goal is to complete the following tasks, each task must have a PR associated with this issue.

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, `merge-4.9.1-into-4.10.0`.

## Tasks

- [ ] Merge branch `4.9.1` into branch `4.10.0`.
- [ ] Delete all stage pre-releases for 4.9.0 (https://github.com/wazuh/wazuh-qa/releases).
- [ ] Delete all stage tags for v4.9.0. **BE CAREFUL NOT TO DELETE DEFINITIVE TAG**. Example: v4.9.0-rc1, 4.9.0-alpha1, etc.
- [ ] Delete branch `4.9.0`.
### 5.0.0 (master)

- [ ] Update changelog.

**Comment by juliamagan** [comment]
This is a test for https://github.com/wazuh/wazuh-tools/issues/296
