### ISSUE TITLE
Discrepancies between number of request using same configuration for simulate_api_load

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#5706]
## Description
A potential bug has been detected in the `simulate_api_load` script, which could affect the number of final requests received in the Vulnerability Detector performance tests. As noted by @GGP1 [here](https://github.com/wazuh/wazuh/issues/25420#issuecomment-2315589885), there appears to be an issue between versions 4.9.0-beta2 and 4.9.0-rc1. During the Vulnerability performance tests, the number of final requests received by the managers in Beta2 was lower than expected.

Reviewing the `wazu_api_simulator.log` we can see that both tests were launched indeed with the same parameters. 

<details>

<summary> RC 1: wazu_api_simulator.log</summary>

```shell
2024/08/26 07:10:40 INFO: [Main] Loaded configuration file: {'remote': {'host': '172.31.2.194', 'port': 55000}, 'kibana': {'enabled': True}, 'extra_load': {'enabled': True, 'api_requests_percentage': 10}}
2024/08/26 07:10:40 INFO: [ExtraLoad] Loaded template in api_extra_load_template.yaml
2024/08/26 07:10:40 INFO: [ExtraLoad] Initializing process
2024/08/26 07:10:40 INFO: [ExtraLoad] 5 requests per loop
2024/08/26 07:10:40 INFO: [ExtraLoad] Frequency: 60
2024/08/26 07:10:40 INFO: [ExtraLoad] Trying to obtain API token
2024/08/26 07:10:40 INFO: [Kibana] Loaded template in api_kibana_template.yaml
2024/08/26 07:10:40 INFO: [Kibana] Initializing process
2024/08/26 07:10:40 INFO: [Kibana] 7 requests per loop
2024/08/26 07:10:40 INFO: [Kibana] Frequency: 60
```

</details>

<details>

<summary> Beta 2: wazu_api_simulator.log </summary>

```shell
2024/08/09 18:26:43 INFO: [Main] Loaded configuration file: {'remote': {'host': '172.31.9.58', 'port': 55000}, 'kibana': {'enabled': True}, 'extra_load': {'enabled': True, 'api_requests_percentage': 10}}
2024/08/09 18:26:43 INFO: [ExtraLoad] Loaded template in api_extra_load_template.yaml
2024/08/09 18:26:43 INFO: [ExtraLoad] Initializing process
2024/08/09 18:26:43 INFO: [ExtraLoad] 5 requests per loop
2024/08/09 18:26:43 INFO: [ExtraLoad] Frequency: 60
2024/08/09 18:26:43 INFO: [ExtraLoad] Trying to obtain API token
2024/08/09 18:26:43 INFO: [Kibana] Loaded template in api_kibana_template.yaml
2024/08/09 18:26:43 INFO: [Kibana] Initializing process
2024/08/09 18:26:43 INFO: [Kibana] 7 requests per loop
2024/08/09 18:26:43 INFO: [Kibana] Frequency: 60
```

</details>

However, it's clear the discrepancy between both tests (8315 request in Beta 2 vs 11822 in RC1). This could be related due to some error in the request of the analysisd, although no changes in the api configuration were performed. Further research is required and it will be carried on in  

### Evidences

- Artifacts RC 1: https://github.com/user-attachments/files/16759342/artifacts1.zip
- Artifacts Beta2: https://github.com/user-attachments/files/16582914/artifacts.tgz.zip

### Tasks

- [x] Research why in provided tests the final number of requests is not consistent
- [x] Check the results consistency of simulate_api_load
- [ ] ~Implement fix in the saturation scripts if needed to avoid possible discrepancies~ There are no fixes to be performed

**Comment by pro-akim** [comment]
## Update
Checking artifacts to understand the problem
Locating pipeline code and analyzing the logic of its behavior

**Comment by GGP1** [comment]
@pro-akim 

FYI, I have analyzed many workload benchmark metrics logs and none of them had this API requests pattern.

If we take a look at the API and Kibana load templates, they are not lister, so the API simulator script shouldn't be doing them.

I think they were performed manually for debugging purposes and ended up in the artifacts because of that. I don't think there's any issue regarding this particular part of the test.

**Comment by GGP1** [comment]
@pro-akim 

FYI, I have analyzed many workload benchmark metrics logs and none of them had this API requests pattern.

If we take a look at the API and Kibana load templates, they are not listed, so the API simulator script shouldn't be doing them.

I think they were performed manually for debugging purposes and ended up in the artifacts because of that. I don't think there's any issue regarding this particular part of the test.

> PD: I closed the issue by mistake, but it may be closed if you agree with my conclusion.

**Comment by pro-akim** [comment]
As @GGP1 mentions, I have been able to observe in the artifacts of several CLUSTER-Workload_benchmarks_metrics tests that the appearance of the API requests are in patterns of 3 and not in patterns of 2 requests. This would rule out any inconvenience on the part of the test as mentioned, which is why I am closing this issue, but since the graphs have not been explained by this behavior, I am reopening the issue: https://github.com/wazuh/wazuh/issues/25420 for re-analysis.


4.8.1-RC2 High Activity Test

```
2024/07/09 09:20:22 INFO: [Main] Loaded configuration file: {'remote': {'host': '172.31.10.74', 'port': 55000}, 'kibana': {'enabled': True}, 'extra_load': {'enabled': True, 'api_requests_percentage': 10}}
2024/07/09 09:20:22 INFO: [ExtraLoad] Loaded template in api_extra_load_template.yaml
2024/07/09 09:20:22 INFO: [ExtraLoad] Initializing process
2024/07/09 09:20:22 INFO: [ExtraLoad] 5 requests per loop
2024/07/09 09:20:22 INFO: [ExtraLoad] Frequency: 60
2024/07/09 09:20:22 INFO: [ExtraLoad] Trying to obtain API token
2024/07/09 09:20:22 INFO: [Kibana] Loaded template in api_kibana_template.yaml
2024/07/09 09:20:22 INFO: [Kibana] Initializing process
2024/07/09 09:20:22 INFO: [Kibana] 7 requests per loop
2024/07/09 09:20:22 INFO: [Kibana] Frequency: 60
```

```
2024/07/09 09:18:48 INFO: wazuh 127.0.0.1 "GET /security/user/authenticate" with parameters {} and body {} done in 0.614s: 200
2024/07/09 09:18:48 INFO: wazuh 127.0.0.1 "GET /security/user/authenticate" with parameters {} and body {} done in 0.780s: 200
2024/07/09 09:18:48 INFO: wazuh 127.0.0.1 "GET /security/user/authenticate" with parameters {} and body {} done in 0.403s: 200
2024/07/09 09:18:49 INFO: wazuh 127.0.0.1 "GET /manager/daemons/stats" with parameters {"daemons_list": "wazuh-remoted", "wait_for_complete": "true"} and body {} done in 0.070s: 200
2024/07/09 09:18:49 INFO: wazuh 127.0.0.1 "GET /manager/daemons/stats" with parameters {"daemons_list": "wazuh-analysisd", "wait_for_complete": "true"} and body {} done in 0.030s: 200
2024/07/09 09:18:49 INFO: wazuh 127.0.0.1 "GET /manager/daemons/stats" with parameters {"daemons_list": "wazuh-db", "wait_for_complete": "true"} and body {} done in 0.020s: 200
```
4.9.0-Beta1 High Activity Test


```
2024/08/06 15:28:55 INFO: [Main] Loaded configuration file: {'remote': {'host': '172.31.15.129', 'port': 55000}, 'kibana': {'enabled': True}, 'extra_load': {'enabled': True, 'api_requests_percentage': 10}}
2024/08/06 15:28:55 INFO: [ExtraLoad] Loaded template in api_extra_load_template.yaml
2024/08/06 15:28:55 INFO: [ExtraLoad] Initializing process
2024/08/06 15:28:55 INFO: [ExtraLoad] 5 requests per loop
2024/08/06 15:28:55 INFO: [ExtraLoad] Frequency: 60
2024/08/06 15:28:55 INFO: [ExtraLoad] Trying to obtain API token
2024/08/06 15:28:55 INFO: [Kibana] Loaded template in api_kibana_template.yaml
2024/08/06 15:28:55 INFO: [Kibana] Initializing process
2024/08/06 15:28:55 INFO: [Kibana] 7 requests per loop
2024/08/06 15:28:55 INFO: [Kibana] Frequency: 60
```


```
2024/08/06 15:27:43 INFO: wazuh 127.0.0.1 "GET /security/user/authenticate" with parameters {} and body {} done in 0.654s: 200
2024/08/06 15:27:43 INFO: wazuh 127.0.0.1 "GET /security/user/authenticate" with parameters {} and body {} done in 0.654s: 200
2024/08/06 15:27:43 INFO: wazuh 127.0.0.1 "GET /security/user/authenticate" with parameters {} and body {} done in 0.437s: 200
2024/08/06 15:27:43 INFO: wazuh 127.0.0.1 "GET /manager/daemons/stats" with parameters {"daemons_list": "wazuh-remoted", "wait_for_complete": "true"} and body {} done in 0.063s: 200
2024/08/06 15:27:43 INFO: wazuh 127.0.0.1 "GET /manager/daemons/stats" with parameters {"daemons_list": "wazuh-db", "wait_for_complete": "true"} and body {} done in 0.064s: 200
2024/08/06 15:27:43 INFO: wazuh 127.0.0.1 "GET /manager/daemons/stats" with parameters {"daemons_list": "wazuh-analysisd", "wait_for_complete": "true"} and body {} done in 0.068s: 200
```

4.9.0-RC1 High Activity Test


```
2024/08/26 11:03:05 INFO: [Main] Loaded configuration file: {'remote': {'host': '172.31.12.16', 'port': 55000}, 'kibana': {'enabled': True}, 'extra_load': {'enabled': True, 'api_requests_percentage': 10}}
2024/08/26 11:03:05 INFO: [ExtraLoad] Loaded template in api_extra_load_template.yaml
2024/08/26 11:03:05 INFO: [ExtraLoad] Initializing process
2024/08/26 11:03:05 INFO: [ExtraLoad] 5 requests per loop
2024/08/26 11:03:05 INFO: [ExtraLoad] Frequency: 60
2024/08/26 11:03:05 INFO: [ExtraLoad] Trying to obtain API token
2024/08/26 11:03:05 INFO: [Kibana] Loaded template in api_kibana_template.yaml
2024/08/26 11:03:05 INFO: [Kibana] Initializing process
2024/08/26 11:03:05 INFO: [Kibana] 7 requests per loop
2024/08/26 11:03:05 INFO: [Kibana] Frequency: 60
```


```
2024/08/26 11:01:49 INFO: wazuh 127.0.0.1 "GET /security/user/authenticate" with parameters {} and body {} done in 0.648s: 200
2024/08/26 11:01:49 INFO: wazuh 127.0.0.1 "GET /security/user/authenticate" with parameters {} and body {} done in 0.646s: 200
2024/08/26 11:01:49 INFO: wazuh 127.0.0.1 "GET /security/user/authenticate" with parameters {} and body {} done in 0.417s: 200
2024/08/26 11:01:49 INFO: wazuh 127.0.0.1 "GET /manager/daemons/stats" with parameters {"daemons_list": "wazuh-analysisd", "wait_for_complete": "true"} and body {} done in 0.062s: 200
2024/08/26 11:01:49 INFO: wazuh 127.0.0.1 "GET /manager/daemons/stats" with parameters {"daemons_list": "wazuh-remoted", "wait_for_complete": "true"} and body {} done in 0.063s: 200
2024/08/26 11:01:49 INFO: wazuh 127.0.0.1 "GET /manager/daemons/stats" with parameters {"daemons_list": "wazuh-db", "wait_for_complete": "true"} and body {} done in 0.028s: 200
```

4.9.0-RC2 High Activity Test

```
2024/09/02 15:54:48 INFO: [Main] Loaded configuration file: {'remote': {'host': '172.31.10.253', 'port': 55000}, 'kibana': {'enabled': True}, 'extra_load': {'enabled': True, 'api_requests_percentage': 10}}
2024/09/02 15:54:48 INFO: [ExtraLoad] Loaded template in api_extra_load_template.yaml
2024/09/02 15:54:48 INFO: [ExtraLoad] Initializing process
2024/09/02 15:54:48 INFO: [ExtraLoad] 5 requests per loop
2024/09/02 15:54:48 INFO: [ExtraLoad] Frequency: 60
2024/09/02 15:54:48 INFO: [ExtraLoad] Trying to obtain API token
2024/09/02 15:54:48 INFO: [Kibana] Loaded template in api_kibana_template.yaml
2024/09/02 15:54:48 INFO: [Kibana] Initializing process
2024/09/02 15:54:48 INFO: [Kibana] 7 requests per loop
2024/09/02 15:54:48 INFO: [Kibana] Frequency: 60
```


```
2024/09/02 15:53:28 INFO: wazuh 127.0.0.1 "GET /security/user/authenticate" with parameters {} and body {} done in 0.492s: 200
2024/09/02 15:53:28 INFO: wazuh 127.0.0.1 "GET /security/user/authenticate" with parameters {} and body {} done in 0.387s: 200
2024/09/02 15:53:29 INFO: wazuh 127.0.0.1 "GET /security/user/authenticate" with parameters {} and body {} done in 0.362s: 200
2024/09/02 15:53:29 INFO: wazuh 127.0.0.1 "GET /manager/daemons/stats" with parameters {"daemons_list": "wazuh-analysisd", "wait_for_complete": "true"} and body {} done in 0.145s: 200
2024/09/02 15:53:29 INFO: wazuh 127.0.0.1 "GET /manager/daemons/stats" with parameters {"daemons_list": "wazuh-remoted", "wait_for_complete": "true"} and body {} done in 0.024s: 200
2024/09/02 15:53:29 INFO: wazuh 127.0.0.1 "GET /manager/daemons/stats" with parameters {"daemons_list": "wazuh-db", "wait_for_complete": "true"} and body {} done in 0.044s: 200
```

**Comment by joaquinsgi** [comment]
LGTM!
