### ISSUE TITLE
Publish release 4.9.0

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#5721]
## Description
This issue attempts to track the steps necessary to publish packages, OVA, AMI, docker images, and puppet forge for 4.9.0.

## Tasks
- [x] Create manual production backup 
  - ~Commandline execution fails~. Permission fails https://github.com/wazuh/internal-devel-requests/issues/1521
  - Modified Jenkinsfile pipeline: https://ci.wazuh.info/job/Publish_release/402
- [x] Send AMI to analysis. 
  - https://github.com/wazuh/internal-devel-requests/issues/1522
- [x] Copy files from pre-release to production
  - [x] Clone the wazuh-jenkins repository and checkout to the `v4.9.0` tag
  - [x] Follow the steps of the README file located at `new-jenkins/procedure/publish_release/README.md` (Container of `release_tool`)
    - Use the recipe `recipes/staging-to-prod.yaml`
    - Make sure that the YAML has the correct `global-variables`
    - For 4.9.0, we don't need to publish Filebeat
      - [release_tool_2024-09-05_13-36-59-500.log](https://github.com/user-attachments/files/16893781/release_tool_2024-09-05_13-36-59-500.log)
- [x] Publish unattended and templates.
  - [x] https://ci.wazuh.info/job/publish_unattended/319/console
- [x] Publish Puppet forge
  - [x] https://ci.wazuh.info/job/Publish_release/404/console

**Comment by rauldpm** [comment]
## Packages released to packages.wazuh.com

```
╰─➤  aws s3 ls packages.wazuh.com/4.x/ --recursive  --summarize --human-readable | grep "4.9.0"                   
2024-09-05 13:37:03   14.4 MiB 4.x/aix/wazuh-agent-4.9.0-1.aix.ppc.rpm
2024-09-05 14:55:48   10.2 MiB 4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.9.0-1_amd64.deb
2024-09-05 14:55:48    5.6 MiB 4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.9.0-1_arm64.deb
2024-09-05 14:55:48    5.2 MiB 4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.9.0-1_armhf.deb
2024-09-05 14:55:48   10.8 MiB 4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.9.0-1_i386.deb
2024-09-05 14:55:48  158.3 MiB 4.x/apt/pool/main/w/wazuh-dashboard/wazuh-dashboard_4.9.0-1_amd64.deb
2024-09-05 14:55:51  810.9 MiB 4.x/apt/pool/main/w/wazuh-indexer/wazuh-indexer_4.9.0-1_amd64.deb
2024-09-05 14:56:00  307.1 MiB 4.x/apt/pool/main/w/wazuh-manager/wazuh-manager_4.9.0-1_amd64.deb
2024-09-05 13:38:52  146 Bytes 4.x/checksums/wazuh/4.9.0/wazuh-4.9.0.ova.sha512
2024-09-05 13:37:05  172 Bytes 4.x/checksums/wazuh/4.9.0/wazuh-agent-4.9.0-1-hpux-11v3-ia64.tar.gz.sha512
2024-09-05 14:35:32  162 Bytes 4.x/checksums/wazuh/4.9.0/wazuh-agent-4.9.0-1.aarch64.rpm.sha512
2024-09-05 13:37:05  162 Bytes 4.x/checksums/wazuh/4.9.0/wazuh-agent-4.9.0-1.aix.ppc.rpm.sha512
2024-09-05 13:37:08  203 Bytes 4.x/checksums/wazuh/4.9.0/wazuh-agent-4.9.0-1.arm64.pkg.sha512
2024-09-05 14:35:39  162 Bytes 4.x/checksums/wazuh/4.9.0/wazuh-agent-4.9.0-1.armv7hl.rpm.sha512
2024-09-05 13:38:02  163 Bytes 4.x/checksums/wazuh/4.9.0/wazuh-agent-4.9.0-1.el5.i386.rpm.sha512
2024-09-05 13:37:50  165 Bytes 4.x/checksums/wazuh/4.9.0/wazuh-agent-4.9.0-1.el5.x86_64.rpm.sha512
2024-09-05 14:35:25  159 Bytes 4.x/checksums/wazuh/4.9.0/wazuh-agent-4.9.0-1.i386.rpm.sha512
2024-09-05 13:37:05  205 Bytes 4.x/checksums/wazuh/4.9.0/wazuh-agent-4.9.0-1.intel64.pkg.sha512
2024-09-05 13:37:05  159 Bytes 4.x/checksums/wazuh/4.9.0/wazuh-agent-4.9.0-1.msi.sha512
2024-09-05 14:35:19  161 Bytes 4.x/checksums/wazuh/4.9.0/wazuh-agent-4.9.0-1.x86_64.rpm.sha512
2024-09-05 14:27:02  160 Bytes 4.x/checksums/wazuh/4.9.0/wazuh-agent_4.9.0-1_amd64.deb.sha512
2024-09-05 14:27:15  160 Bytes 4.x/checksums/wazuh/4.9.0/wazuh-agent_4.9.0-1_arm64.deb.sha512
2024-09-05 14:27:22  160 Bytes 4.x/checksums/wazuh/4.9.0/wazuh-agent_4.9.0-1_armhf.deb.sha512
2024-09-05 14:27:08  159 Bytes 4.x/checksums/wazuh/4.9.0/wazuh-agent_4.9.0-1_i386.deb.sha512
2024-09-05 13:37:05  164 Bytes 4.x/checksums/wazuh/4.9.0/wazuh-agent_v4.9.0-sol10-i386.pkg.sha512
2024-09-05 13:37:09  165 Bytes 4.x/checksums/wazuh/4.9.0/wazuh-agent_v4.9.0-sol10-sparc.pkg.sha512
2024-09-05 13:37:14  164 Bytes 4.x/checksums/wazuh/4.9.0/wazuh-agent_v4.9.0-sol11-i386.p5p.sha512
2024-09-05 13:37:18  165 Bytes 4.x/checksums/wazuh/4.9.0/wazuh-agent_v4.9.0-sol11-sparc.p5p.sha512
2024-09-05 14:34:23  165 Bytes 4.x/checksums/wazuh/4.9.0/wazuh-dashboard-4.9.0-1.x86_64.rpm.sha512
2024-09-05 14:25:49  164 Bytes 4.x/checksums/wazuh/4.9.0/wazuh-dashboard_4.9.0-1_amd64.deb.sha512
2024-09-05 14:35:12  178 Bytes 4.x/checksums/wazuh/4.9.0/wazuh-indexer-4.9.0-1.x86_64.rpm.sha512
2024-09-05 14:26:55  177 Bytes 4.x/checksums/wazuh/4.9.0/wazuh-indexer_4.9.0-1_amd64.deb.sha512
2024-09-05 14:34:04  163 Bytes 4.x/checksums/wazuh/4.9.0/wazuh-manager-4.9.0-1.x86_64.rpm.sha512
2024-09-05 14:25:33  162 Bytes 4.x/checksums/wazuh/4.9.0/wazuh-manager_4.9.0-1_amd64.deb.sha512
2024-09-05 13:37:05  155 Bytes 4.x/checksums/wazuh/4.9.0/wazuh-wazuh-4.9.0.tar.gz.sha512
2024-09-05 13:37:05  169 Bytes 4.x/checksums/wazuh/4.9.0/wazuh_agent_v4.9.0_linux_amd64.deb.wpk.sha512
2024-09-05 13:37:21  170 Bytes 4.x/checksums/wazuh/4.9.0/wazuh_agent_v4.9.0_linux_x86_64.rpm.wpk.sha512
2024-09-05 13:37:31  171 Bytes 4.x/checksums/wazuh/4.9.0/wazuh_agent_v4.9.0_macos_intel64.pkg.wpk.sha512
2024-09-05 13:37:05  161 Bytes 4.x/checksums/wazuh/4.9.0/wazuh_agent_v4.9.0_windows.wpk.sha512
2024-09-05 13:37:03   16.5 MiB 4.x/hp-ux/wazuh-agent-4.9.0-1-hpux-11v3-ia64.tar.gz
2024-09-05 13:37:07    5.9 MiB 4.x/macos/wazuh-agent-4.9.0-1.arm64.pkg
2024-09-05 13:37:03    6.5 MiB 4.x/macos/wazuh-agent-4.9.0-1.intel64.pkg
2024-09-05 13:37:03   58.1 KiB 4.x/puppet-module/wazuh-wazuh-4.9.0.tar.gz
2024-09-05 13:37:03   16.6 MiB 4.x/solaris/i386/10/wazuh-agent_v4.9.0-sol10-i386.pkg
2024-09-05 13:37:13    7.0 MiB 4.x/solaris/i386/11/wazuh-agent_v4.9.0-sol11-i386.p5p
2024-09-05 13:37:07   17.6 MiB 4.x/solaris/sparc/10/wazuh-agent_v4.9.0-sol10-sparc.pkg
2024-09-05 13:37:16    6.9 MiB 4.x/solaris/sparc/11/wazuh-agent_v4.9.0-sol11-sparc.p5p
2024-09-05 13:37:03    3.7 GiB 4.x/vm/wazuh-4.9.0.ova
2024-09-05 13:37:03    6.9 MiB 4.x/windows/wazuh-agent-4.9.0-1.msi
2024-09-05 13:37:03   10.2 MiB 4.x/wpk/linux/deb/amd64/wazuh_agent_v4.9.0_linux_amd64.deb.wpk
2024-09-05 13:37:20   10.3 MiB 4.x/wpk/linux/rpm/x86_64/wazuh_agent_v4.9.0_linux_x86_64.rpm.wpk
2024-09-05 13:37:30    6.5 MiB 4.x/wpk/macos/pkg/intel64/wazuh_agent_v4.9.0_macos_intel64.pkg.wpk
2024-09-05 13:37:03    6.6 MiB 4.x/wpk/windows/wazuh_agent_v4.9.0_windows.wpk
2024-09-05 14:36:16   10.2 MiB 4.x/yum/wazuh-agent-4.9.0-1.aarch64.rpm
2024-09-05 14:36:15    9.5 MiB 4.x/yum/wazuh-agent-4.9.0-1.armv7hl.rpm
2024-09-05 14:36:15   10.9 MiB 4.x/yum/wazuh-agent-4.9.0-1.i386.rpm
2024-09-05 14:36:16   10.4 MiB 4.x/yum/wazuh-agent-4.9.0-1.x86_64.rpm
2024-09-05 14:36:16  252.6 MiB 4.x/yum/wazuh-dashboard-4.9.0-1.x86_64.rpm
2024-09-05 14:36:19  812.6 MiB 4.x/yum/wazuh-indexer-4.9.0-1.x86_64.rpm
2024-09-05 14:36:29  303.4 MiB 4.x/yum/wazuh-manager-4.9.0-1.x86_64.rpm
2024-09-05 13:38:06    9.1 MiB 4.x/yum5/i386/wazuh-agent-4.9.0-1.el5.i386.rpm
2024-09-05 13:37:54    8.5 MiB 4.x/yum5/x86_64/wazuh-agent-4.9.0-1.el5.x86_64.rpm
```

**Comment by fcaffieri** [comment]
LGTM
