### ISSUE TITLE
Post publication live checks for 4.9.0

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#5722]
## Description
This issue attempts to ensure the publication process was correct, attempting checks and live tests for published packages and images.

## Tasks
- [x] Ensure that production files are present.
- [x] Deploy the `Wazuh Installation Assistant` and check the version installed is 4.9.0.
- [x] [AMD64 Live installation test](https://ci.wazuh.info/job/Test_install_tier).
  - [x] https://ci.wazuh.info/job/Test_install_tier/997/console :green_circle: 
- [x] WPK versions check.
- [x] WPK upgrade test.
  - [x] Linux DEB
  - [x] Linux RPM
  - [x] MacOS Intel
  - [x] Windows
- [x] [Puppet forge module published](https://forge.puppet.com/modules/wazuh/wazuh/readme).
- [ ] ~[Docker images published](https://hub.docker.com/u/wazuh).~
  - To be done after wazuh/wazuh GitHub release notes

**Comment by rauldpm** [comment]
## Ensure that production files are present.

```
╰─➤  aws s3 ls packages.wazuh.com/4.x/ --recursive  --summarize --human-readable | grep "4.9.0"                   
2024-09-05 13:37:03   14.4 MiB 4.x/aix/wazuh-agent-4.9.0-1.aix.ppc.rpm
2024-09-05 14:55:48   10.2 MiB 4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.9.0-1_amd64.deb
2024-09-05 14:55:48    5.6 MiB 4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.9.0-1_arm64.deb
2024-09-05 14:55:48    5.2 MiB 4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.9.0-1_armhf.deb
2024-09-05 14:55:48   10.8 MiB 4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.9.0-1_i386.deb
2024-09-05 14:55:48  158.3 MiB 4.x/apt/pool/main/w/wazuh-dashboard/wazuh-dashboard_4.9.0-1_amd64.deb
2024-09-05 14:55:51  810.9 MiB 4.x/apt/pool/main/w/wazuh-indexer/wazuh-indexer_4.9.0-1_amd64.deb
2024-09-05 14:56:00  307.1 MiB 4.x/apt/pool/main/w/wazuh-manager/wazuh-manager_4.9.0-1_amd64.deb
2024-09-05 13:38:52  146 Bytes 4.x/checksums/wazuh/4.9.0/wazuh-4.9.0.ova.sha512
2024-09-05 13:37:05  172 Bytes 4.x/checksums/wazuh/4.9.0/wazuh-agent-4.9.0-1-hpux-11v3-ia64.tar.gz.sha512
2024-09-05 14:35:32  162 Bytes 4.x/checksums/wazuh/4.9.0/wazuh-agent-4.9.0-1.aarch64.rpm.sha512
2024-09-05 13:37:05  162 Bytes 4.x/checksums/wazuh/4.9.0/wazuh-agent-4.9.0-1.aix.ppc.rpm.sha512
2024-09-05 13:37:08  203 Bytes 4.x/checksums/wazuh/4.9.0/wazuh-agent-4.9.0-1.arm64.pkg.sha512
2024-09-05 14:35:39  162 Bytes 4.x/checksums/wazuh/4.9.0/wazuh-agent-4.9.0-1.armv7hl.rpm.sha512
2024-09-05 13:38:02  163 Bytes 4.x/checksums/wazuh/4.9.0/wazuh-agent-4.9.0-1.el5.i386.rpm.sha512
2024-09-05 13:37:50  165 Bytes 4.x/checksums/wazuh/4.9.0/wazuh-agent-4.9.0-1.el5.x86_64.rpm.sha512
2024-09-05 14:35:25  159 Bytes 4.x/checksums/wazuh/4.9.0/wazuh-agent-4.9.0-1.i386.rpm.sha512
2024-09-05 13:37:05  205 Bytes 4.x/checksums/wazuh/4.9.0/wazuh-agent-4.9.0-1.intel64.pkg.sha512
2024-09-05 13:37:05  159 Bytes 4.x/checksums/wazuh/4.9.0/wazuh-agent-4.9.0-1.msi.sha512
2024-09-05 14:35:19  161 Bytes 4.x/checksums/wazuh/4.9.0/wazuh-agent-4.9.0-1.x86_64.rpm.sha512
2024-09-05 14:27:02  160 Bytes 4.x/checksums/wazuh/4.9.0/wazuh-agent_4.9.0-1_amd64.deb.sha512
2024-09-05 14:27:15  160 Bytes 4.x/checksums/wazuh/4.9.0/wazuh-agent_4.9.0-1_arm64.deb.sha512
2024-09-05 14:27:22  160 Bytes 4.x/checksums/wazuh/4.9.0/wazuh-agent_4.9.0-1_armhf.deb.sha512
2024-09-05 14:27:08  159 Bytes 4.x/checksums/wazuh/4.9.0/wazuh-agent_4.9.0-1_i386.deb.sha512
2024-09-05 13:37:05  164 Bytes 4.x/checksums/wazuh/4.9.0/wazuh-agent_v4.9.0-sol10-i386.pkg.sha512
2024-09-05 13:37:09  165 Bytes 4.x/checksums/wazuh/4.9.0/wazuh-agent_v4.9.0-sol10-sparc.pkg.sha512
2024-09-05 13:37:14  164 Bytes 4.x/checksums/wazuh/4.9.0/wazuh-agent_v4.9.0-sol11-i386.p5p.sha512
2024-09-05 13:37:18  165 Bytes 4.x/checksums/wazuh/4.9.0/wazuh-agent_v4.9.0-sol11-sparc.p5p.sha512
2024-09-05 14:34:23  165 Bytes 4.x/checksums/wazuh/4.9.0/wazuh-dashboard-4.9.0-1.x86_64.rpm.sha512
2024-09-05 14:25:49  164 Bytes 4.x/checksums/wazuh/4.9.0/wazuh-dashboard_4.9.0-1_amd64.deb.sha512
2024-09-05 14:35:12  178 Bytes 4.x/checksums/wazuh/4.9.0/wazuh-indexer-4.9.0-1.x86_64.rpm.sha512
2024-09-05 14:26:55  177 Bytes 4.x/checksums/wazuh/4.9.0/wazuh-indexer_4.9.0-1_amd64.deb.sha512
2024-09-05 14:34:04  163 Bytes 4.x/checksums/wazuh/4.9.0/wazuh-manager-4.9.0-1.x86_64.rpm.sha512
2024-09-05 14:25:33  162 Bytes 4.x/checksums/wazuh/4.9.0/wazuh-manager_4.9.0-1_amd64.deb.sha512
2024-09-05 13:37:05  155 Bytes 4.x/checksums/wazuh/4.9.0/wazuh-wazuh-4.9.0.tar.gz.sha512
2024-09-05 13:37:05  169 Bytes 4.x/checksums/wazuh/4.9.0/wazuh_agent_v4.9.0_linux_amd64.deb.wpk.sha512
2024-09-05 13:37:21  170 Bytes 4.x/checksums/wazuh/4.9.0/wazuh_agent_v4.9.0_linux_x86_64.rpm.wpk.sha512
2024-09-05 13:37:31  171 Bytes 4.x/checksums/wazuh/4.9.0/wazuh_agent_v4.9.0_macos_intel64.pkg.wpk.sha512
2024-09-05 13:37:05  161 Bytes 4.x/checksums/wazuh/4.9.0/wazuh_agent_v4.9.0_windows.wpk.sha512
2024-09-05 13:37:03   16.5 MiB 4.x/hp-ux/wazuh-agent-4.9.0-1-hpux-11v3-ia64.tar.gz
2024-09-05 13:37:07    5.9 MiB 4.x/macos/wazuh-agent-4.9.0-1.arm64.pkg
2024-09-05 13:37:03    6.5 MiB 4.x/macos/wazuh-agent-4.9.0-1.intel64.pkg
2024-09-05 13:37:03   58.1 KiB 4.x/puppet-module/wazuh-wazuh-4.9.0.tar.gz
2024-09-05 13:37:03   16.6 MiB 4.x/solaris/i386/10/wazuh-agent_v4.9.0-sol10-i386.pkg
2024-09-05 13:37:13    7.0 MiB 4.x/solaris/i386/11/wazuh-agent_v4.9.0-sol11-i386.p5p
2024-09-05 13:37:07   17.6 MiB 4.x/solaris/sparc/10/wazuh-agent_v4.9.0-sol10-sparc.pkg
2024-09-05 13:37:16    6.9 MiB 4.x/solaris/sparc/11/wazuh-agent_v4.9.0-sol11-sparc.p5p
2024-09-05 13:37:03    3.7 GiB 4.x/vm/wazuh-4.9.0.ova
2024-09-05 13:37:03    6.9 MiB 4.x/windows/wazuh-agent-4.9.0-1.msi
2024-09-05 13:37:03   10.2 MiB 4.x/wpk/linux/deb/amd64/wazuh_agent_v4.9.0_linux_amd64.deb.wpk
2024-09-05 13:37:20   10.3 MiB 4.x/wpk/linux/rpm/x86_64/wazuh_agent_v4.9.0_linux_x86_64.rpm.wpk
2024-09-05 13:37:30    6.5 MiB 4.x/wpk/macos/pkg/intel64/wazuh_agent_v4.9.0_macos_intel64.pkg.wpk
2024-09-05 13:37:03    6.6 MiB 4.x/wpk/windows/wazuh_agent_v4.9.0_windows.wpk
2024-09-05 14:36:16   10.2 MiB 4.x/yum/wazuh-agent-4.9.0-1.aarch64.rpm
2024-09-05 14:36:15    9.5 MiB 4.x/yum/wazuh-agent-4.9.0-1.armv7hl.rpm
2024-09-05 14:36:15   10.9 MiB 4.x/yum/wazuh-agent-4.9.0-1.i386.rpm
2024-09-05 14:36:16   10.4 MiB 4.x/yum/wazuh-agent-4.9.0-1.x86_64.rpm
2024-09-05 14:36:16  252.6 MiB 4.x/yum/wazuh-dashboard-4.9.0-1.x86_64.rpm
2024-09-05 14:36:19  812.6 MiB 4.x/yum/wazuh-indexer-4.9.0-1.x86_64.rpm
2024-09-05 14:36:29  303.4 MiB 4.x/yum/wazuh-manager-4.9.0-1.x86_64.rpm
2024-09-05 13:38:06    9.1 MiB 4.x/yum5/i386/wazuh-agent-4.9.0-1.el5.i386.rpm
2024-09-05 13:37:54    8.5 MiB 4.x/yum5/x86_64/wazuh-agent-4.9.0-1.el5.x86_64.rpm

╰─➤  aws s3 ls packages.wazuh.com/4.9/ --recursive  --summarize --human-readable               
2024-09-05 14:59:47  636 Bytes 4.9/config.yml
2024-09-05 14:59:48  922 Bytes 4.9/tpl/elastic-basic/elasticsearch.yml
2024-09-05 14:59:48  938 Bytes 4.9/tpl/elastic-basic/elasticsearch_all_in_one.yml
2024-09-05 14:59:47    1.1 KiB 4.9/tpl/elastic-basic/elasticsearch_cluster.yml
2024-09-05 14:59:47    1.2 KiB 4.9/tpl/elastic-basic/elasticsearch_cluster_initial_node.yml
2024-09-05 14:59:48    1.2 KiB 4.9/tpl/elastic-basic/elasticsearch_cluster_subsequent_nodes.yml
2024-09-05 14:59:48  893 Bytes 4.9/tpl/elastic-basic/filebeat.yml
2024-09-05 14:59:48  913 Bytes 4.9/tpl/elastic-basic/filebeat_all_in_one.yml
2024-09-05 14:59:48   59 Bytes 4.9/tpl/elastic-basic/instances_aio.yml
2024-09-05 14:59:48  720 Bytes 4.9/tpl/elastic-basic/kibana.yml
2024-09-05 14:59:48  707 Bytes 4.9/tpl/elastic-basic/kibana_all_in_one.yml
2024-09-05 14:59:48  867 Bytes 4.9/tpl/wazuh/filebeat/filebeat.yml
2024-09-05 14:59:48   35.6 KiB 4.9/wazuh-certs-tool.sh
2024-09-05 14:59:48  185.3 KiB 4.9/wazuh-install.sh
2024-09-05 14:59:48   43.1 KiB 4.9/wazuh-passwords-tool.sh
```

**Comment by rauldpm** [comment]
## Deploy the Wazuh Installation Assistant and check the version installed is 4.9.0.

```
root@ubuntu2204:/home/vagrant# curl -sO https://packages.wazuh.com/4.9/wazuh-install.sh && sudo bash ./wazuh-install.sh -a
05/09/2024 13:25:49 INFO: Starting Wazuh installation assistant. Wazuh version: 4.9.0
05/09/2024 13:25:49 INFO: Verbose logging redirected to /var/log/wazuh-install.log
05/09/2024 13:26:05 INFO: Verifying that your system meets the recommended minimum hardware requirements.
05/09/2024 13:26:05 INFO: Wazuh web interface port will be 443.
05/09/2024 13:26:09 INFO: --- Dependencies ----
05/09/2024 13:26:09 INFO: Installing apt-transport-https.
05/09/2024 13:26:10 INFO: Installing debhelper.
05/09/2024 13:26:58 INFO: Wazuh repository added.
05/09/2024 13:26:58 INFO: --- Configuration files ---
05/09/2024 13:26:58 INFO: Generating configuration files.
05/09/2024 13:26:58 INFO: Generating the root certificate.
05/09/2024 13:26:58 INFO: Generating Admin certificates.
05/09/2024 13:26:58 INFO: Generating Wazuh indexer certificates.
05/09/2024 13:26:58 INFO: Generating Filebeat certificates.
05/09/2024 13:26:59 INFO: Generating Wazuh dashboard certificates.
05/09/2024 13:26:59 INFO: Created wazuh-install-files.tar. It contains the Wazuh cluster key, certificates, and passwords necessary for installation.
05/09/2024 13:26:59 INFO: --- Wazuh indexer ---
05/09/2024 13:26:59 INFO: Starting Wazuh indexer installation.
05/09/2024 13:27:20 INFO: Wazuh indexer installation finished.
05/09/2024 13:27:20 INFO: Wazuh indexer post-install configuration finished.
05/09/2024 13:27:20 INFO: Starting service wazuh-indexer.
05/09/2024 13:27:29 INFO: wazuh-indexer service started.
05/09/2024 13:27:29 INFO: Initializing Wazuh indexer cluster security settings.
05/09/2024 13:27:31 INFO: Wazuh indexer cluster security configuration initialized.
05/09/2024 13:27:31 INFO: Wazuh indexer cluster initialized.
05/09/2024 13:27:31 INFO: --- Wazuh server ---
05/09/2024 13:27:31 INFO: Starting the Wazuh manager installation.
05/09/2024 13:28:11 INFO: Wazuh manager installation finished.
05/09/2024 13:28:11 INFO: Wazuh manager vulnerability detection configuration finished.
05/09/2024 13:28:11 INFO: Starting service wazuh-manager.
05/09/2024 13:28:27 INFO: wazuh-manager service started.
05/09/2024 13:28:27 INFO: Starting Filebeat installation.
05/09/2024 13:28:32 INFO: Filebeat installation finished.
05/09/2024 13:28:33 INFO: Filebeat post-install configuration finished.
05/09/2024 13:28:33 INFO: Starting service filebeat.
05/09/2024 13:28:34 INFO: filebeat service started.
05/09/2024 13:28:34 INFO: --- Wazuh dashboard ---
05/09/2024 13:28:34 INFO: Starting Wazuh dashboard installation.
05/09/2024 13:29:18 INFO: Wazuh dashboard installation finished.
05/09/2024 13:29:18 INFO: Wazuh dashboard post-install configuration finished.
05/09/2024 13:29:18 INFO: Starting service wazuh-dashboard.
05/09/2024 13:29:19 INFO: wazuh-dashboard service started.
05/09/2024 13:29:20 INFO: Updating the internal users.
05/09/2024 13:29:23 INFO: A backup of the internal users has been saved in the /etc/wazuh-indexer/internalusers-backup folder.
05/09/2024 13:29:30 INFO: The filebeat.yml file has been updated to use the Filebeat Keystore username and password.
05/09/2024 13:29:56 INFO: Initializing Wazuh dashboard web application.
05/09/2024 13:29:57 INFO: Wazuh dashboard web application initialized.
05/09/2024 13:29:57 INFO: --- Summary ---
05/09/2024 13:29:57 INFO: You can access the web interface https://<wazuh-dashboard-ip>:443
    User: admin
    Password: 4QE8ffRUXYK*MDausfYv7rrnmV7D28Gk
05/09/2024 13:29:57 INFO: Installation finished.
```

![image](https://github.com/user-attachments/assets/49940861-c259-476a-bc0d-d4c16513ba44)

**Comment by pro-akim** [comment]
## WPK upgrade test.

**Comment by rauldpm** [comment]
## Puppet forge module published.

![image](https://github.com/user-attachments/assets/78518abf-50b3-4385-aa5c-f1ad91a32cc5)

**Comment by pro-akim** [comment]
## WPK Linux  DEB :green_circle: 
    
 
Check Agent
```
root@ip-172-31-38-97:/home/ubuntu# /var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.8.2"
WAZUH_REVISION="40819"
WAZUH_TYPE="agent"
```

Check Manager
```
root@ip-172-31-90-25:/home/ubuntu# /var/ossec/bin/agent_control -i 003

Wazuh agent_control. Agent information:
   Agent ID:   001
   Agent Name: ubuntu-agent1
   IP address: any
   Status:     Active

   Operating system:    Linux |ubuntu-agent1 |5.4.0-169-generic |#187-Ubuntu SMP Thu Nov 23 14:52:28 UTC 2023 |x86_64
   Client version:      Wazuh v4.8.2
   Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
   Shared file hash:    4a8724b20dee0124ff9656783c490c4e
   Last keep alive:     1725543385

   Syscheck last started at:  Thu Sep  5 13:36:15 2024
   Syscheck last ended at:    Thu Sep  5 13:36:23 2024


root@ip-172-31-90-25:/home/ubuntu# /var/ossec/bin/agent_upgrade -a 003

Upgrading...

Upgraded agents:
        Agent 003 upgraded: Wazuh v4.8.2 -> Wazuh v4.9.0

root@ip-172-31-90-25:/home/ubuntu# /var/ossec/bin/agent_control -i 003

Wazuh agent_control. Agent information:
   Agent ID:   003
   Agent Name: ip-172-31-38-97
   IP address: any
   Status:     Active

   Operating system:    Linux |ip-172-31-38-97 |5.19.0-1025-aws |#26~22.04.1-Ubuntu SMP Mon Apr 24 01:58:15 UTC 2023 |x86_64
   Client version:      Wazuh v4.9.0
   Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
   Shared file hash:    4a8724b20dee0124ff9656783c490c4e
   Last keep alive:     1725545286

   Syscheck last started at:  Thu Sep  5 14:07:07 2024
   Syscheck last ended at:    Thu Sep  5 14:07:13 2024

```

Check Agent
```
root@ip-172-31-38-97:/home/ubuntu# /var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.9.0"
WAZUH_REVISION="40907"
WAZUH_TYPE="agent"
```

**Comment by fcaffieri** [comment]
##  WPK versions check :green_circle: 

```
╰─➤  cat versions_deb
v4.9.0 55050c0c74a097504279972d3f3e5aaf79e33b87
╰─➤  sha1sum wazuh_agent_v4.9.0_linux_amd64.deb.wpk
55050c0c74a097504279972d3f3e5aaf79e33b87  wazuh_agent_v4.9.0_linux_amd64.deb.wpk
```

```
╰─➤  cat versions_rpm 
v4.9.0 97da1570a71ab51f1d027acf37c4faff28564b70
╰─➤  sha1sum wazuh_agent_v4.9.0_linux_x86_64.rpm.wpk 
97da1570a71ab51f1d027acf37c4faff28564b70  wazuh_agent_v4.9.0_linux_x86_64.rpm.wpk
```

```
╰─➤  cat versions_macos 
v4.9.0 595046e0fe208a75e5fb679c2b3ce02c90142802
╰─➤  sha1sum wazuh_agent_v4.9.0_macos_intel64.pkg.wpk 
595046e0fe208a75e5fb679c2b3ce02c90142802  wazuh_agent_v4.9.0_macos_intel64.pkg.wpk
```

```
╰─➤  cat versions_windows 
v4.9.0 e6091d109a5f75ed713097824101c7417e98d5df
... 
╰─➤  sha1sum wazuh_agent_v4.9.0_windows.wpk          
e6091d109a5f75ed713097824101c7417e98d5df  wazuh_agent_v4.9.0_windows.wpk

**Comment by fcaffieri** [comment]
## WPK macOS :yellow_circle: 
 
Known issue: https://github.com/wazuh/wazuh/issues/12479
Agent was correctly upgraded

<details>

<summary> macOS Intel </summary>

- Install 4.8.2

```
sh-3.2# uname -a
Darwin macos-14 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:11:05 PDT 2024; root:xnu-10063.101.17~1/RELEASE_X86_64 x86_64
sh-3.2# curl -LO https://packages.wazuh.com/4.x/macos/wazuh-agent-4.8.2-1.intel64.pkg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 6631k  100 6631k    0     0  17.6M      0 --:--:-- --:--:-- --:--:-- 17.5M
sh-3.2# installer -pkg wazuh-agent-4.8.2-1.intel64.pkg -target /
installer: Package name is Wazuh Agent
installer: Installing at base path /
installer: The install was successful.
sh-3.2# nano /Library/Ossec/etc/ossec.conf
sh-3.2# /Library/Ossec/bin/wazuh-control start
Starting Wazuh v4.8.2...
Started wazuh-execd...
Started wazuh-agentd...
Started wazuh-syscheckd...
Started wazuh-logcollector...
Started wazuh-modulesd...
Completed.
sh-3.2# 

```

- Check in manager

```
root@ip-xx-xx-xx-xx:/home/ubuntu# /var/ossec/bin/agent_control -l

Wazuh agent_control. List of available agents:
   ID: 000, Name: ip-xx-xx-xx-xx (server), IP: 127.0.0.1, Active/Local
   ID: 001, Name: macos-14, IP: any, Active

List of agentless devices:

root@ip-xx-xx-xx-xx:/home/ubuntu# /var/ossec/bin/agent_control -i 001

Wazuh agent_control. Agent information:
   Agent ID:   001
   Agent Name: macos-14
   IP address: any
   Status:     Active

   Operating system:    Darwin |macos-14 |23.4.0 |Darwin Kernel Version 23.4.0: Fri Mar 15 00:11:05 PDT 2024; root:xnu-10063.101.17~1/RELEASE_X86_64 |x86_64
   Client version:      Wazuh v4.8.2
   Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
   Shared file hash:    4a8724b20dee0124ff9656783c490c4e
   Last keep alive:     1725545543

   Syscheck last started at:  Thu Sep  5 14:09:34 2024
   Syscheck last ended at:    Thu Sep  5 14:09:46 2024

root@ip-xx-xx-xx-xx:/home/ubuntu# 

```


- Upgrade agent 

```
root@ip-xx-xx-xx-xx:/home/ubuntu# /var/ossec/bin/agent_upgrade -a 001

Upgrading...

Failed upgrades:
	Agent 001 status: Timeout reached while waiting for the response from the agent, check the result manually on the agent for more information
root@ip-xx-xx-xx-xx:/home/ubuntu# 

```

- Check version on the agent
```
sh-3.2# /Library/Ossec/bin/wazuh-control info
WAZUH_VERSION="v4.9.0"
WAZUH_REVISION="40907"
WAZUH_TYPE="agent"
sh-3.2# 
```

- Check version on the manager
```
root@ip-xx-xx-xx-xx:/home/ubuntu# /var/ossec/bin/agent_control -l

Wazuh agent_control. List of available agents:
   ID: 000, Name: ip-xx-xx-xx-xx (server), IP: 127.0.0.1, Active/Local
   ID: 001, Name: macos-14, IP: any, Active

List of agentless devices:

root@ip-xx-xx-xx-xx:/home/ubuntu# /var/ossec/bin/agent_control -i 001

Wazuh agent_control. Agent information:
   Agent ID:   001
   Agent Name: macos-14
   IP address: any
   Status:     Active

   Operating system:    Darwin |macos-14 |23.4.0 |Darwin Kernel Version 23.4.0: Fri Mar 15 00:11:05 PDT 2024; root:xnu-10063.101.17~1/RELEASE_X86_64 |x86_64
   Client version:      Wazuh v4.9.0
   Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
   Shared file hash:    4a8724b20dee0124ff9656783c490c4e
   Last keep alive:     1725546581

   Syscheck last started at:  Thu Sep  5 14:27:12 2024
   Syscheck last ended at:    Thu Sep  5 14:27:21 2024

root@ip-xx-xx-xx-xx:/home/ubuntu# 

```

- Complete macOS upgrade log

```
sh-3.2# cat /Library/Ossec/logs/upgrade.log 
2024/09/05 07:26:53 - Upgrade started.
2024/09/05 07:26:53 - Checking execution path.
installer: Package name is Wazuh Agent
installer: Upgrading at base path /
installer: The upgrade was successful.
2024/09/05 07:27:08 - Installation result = 0
2024/09/05 07:27:08 - Checking for Wazuh Agent control script.
2024/09/05 07:27:08 - Restarting Wazuh Agent.
Killing wazuh-modulesd... 
Killing wazuh-logcollector... 
Killing wazuh-syscheckd... 
Killing wazuh-agentd... 
Killing wazuh-execd... 
Wazuh v4.9.0 Stopped
Starting Wazuh v4.9.0...
Started wazuh-execd...
Started wazuh-agentd...
Started wazuh-syscheckd...
Started wazuh-logcollector...
Started wazuh-modulesd...
Completed.
2024/09/05 07:27:18 - Waiting connection... Remaining attempts: 30.
2024/09/05 07:27:19 - Status = connected. 
2024/09/05 07:27:19 - Connected to manager.
2024/09/05 07:27:19 - Upgrade finished successfully.
sh-3.2# 
```

</details>

**Comment by rauldpm** [comment]
## WPK Linux RPM

- Agent

```
[root@centos7 vagrant]# /var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.8.2"
WAZUH_REVISION="40819"
WAZUH_TYPE="agent"
[root@centos7 vagrant]# ls /var/ossec/var/upgrade/
pkg_installer.sh  upgrade_in_progress_pid  upgrade.sh  wazuh-agent-4.9.0-1.x86_64.rpm
[root@centos7 vagrant]# /var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.9.0"
WAZUH_REVISION="40907"
WAZUH_TYPE="agent
```

- Manager upgrade

```
root@ubuntu2204:/home/vagrant# /var/ossec/bin/agent_control -i 001

Wazuh agent_control. Agent information:
   Agent ID:   001
   Agent Name: centos7
   IP address: any
   Status:     Active

   Operating system:    Linux |centos7 |3.10.0-1127.el7.x86_64 |#1 SMP Tue Mar 31 23:36:51 UTC 2020 |x86_64
   Client version:      Wazuh v4.8.2
   Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
   Shared file hash:    4a8724b20dee0124ff9656783c490c4e
   Last keep alive:     1725546568

   Syscheck last started at:  Thu Sep  5 14:29:03 2024
   Syscheck last ended at:    Thu Sep  5 14:29:25 2024

root@ubuntu2204:/home/vagrant# /var/ossec/bin/agent_upgrade -a 001

Upgrading...

Upgraded agents:
	Agent 001 upgraded: Wazuh v4.8.2 -> Wazuh v4.9.0
root@ubuntu2204:/home/vagrant# /var/ossec/bin/agent_upgrade -a 001
Agents that cannot be upgraded:
	Agent 001 upgrade failed. Status: Error 1822 - Current agent version is greater or equal
root@ubuntu2204:/home/vagrant# /var/ossec/bin/agent_control -i 001

Wazuh agent_control. Agent information:
   Agent ID:   001
   Agent Name: centos7
   IP address: any
   Status:     Active

   Operating system:    Linux |centos7 |3.10.0-1127.el7.x86_64 |#1 SMP Tue Mar 31 23:36:51 UTC 2020 |x86_64
   Client version:      Wazuh v4.9.0
   Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
   Shared file hash:    4a8724b20dee0124ff9656783c490c4e
   Last keep alive:     1725546719

   Syscheck last started at:  Thu Sep  5 14:31:11 2024
   Syscheck last ended at:    Thu Sep  5 14:31:12 2024
```

**Comment by rauldpm** [comment]
## WPK Windows

![image](https://github.com/user-attachments/assets/a3da0eb8-82d9-47e1-8187-a7dfc855a46f)

```
root@ubuntu2204:/home/vagrant# /var/ossec/bin/agent_control -i 002

Wazuh agent_control. Agent information:
   Agent ID:   002
   Agent Name: WIN-8JBPE4J7I16
   IP address: any
   Status:     Active

   Operating system:    Microsoft Windows Server 2016 Datacenter Evaluation
   Client version:      Wazuh v4.8.2
   Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
   Shared file hash:    4a8724b20dee0124ff9656783c490c4e
   Last keep alive:     1725547189

   Syscheck last started at:  Thu Sep  5 14:39:52 2024
   Syscheck last ended at:    Thu Sep  5 14:39:57 2024

root@ubuntu2204:/home/vagrant# /var/ossec/bin/agent_upgrade -a 002

Upgrading...

Upgraded agents:
	Agent 002 upgraded: Wazuh v4.8.2 -> Wazuh v4.9.0
root@ubuntu2204:/home/vagrant# /var/ossec/bin/agent_control -i 002

Wazuh agent_control. Agent information:
   Agent ID:   002
   Agent Name: WIN-8JBPE4J7I16
   IP address: any
   Status:     Active

   Operating system:    Microsoft Windows Server 2016 Datacenter Evaluation
   Client version:      Wazuh v4.9.0
   Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
   Shared file hash:    4a8724b20dee0124ff9656783c490c4e
   Last keep alive:     1725547297

   Syscheck last started at:  Thu Sep  5 14:40:59 2024
   Syscheck last ended at:    Thu Sep  5 14:41:04 2024

```

![image](https://github.com/user-attachments/assets/308ab599-567c-4e8d-ba73-907b2e1d7d4f)

**Comment by Rebits** [comment]
LGTM
