### ISSUE TITLE
Revert test_api_endpoint_performance expected fails logic

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#5724]
## Description
During testing of the 4.9.0 release, a critical regression was identified in the Workload benchmarks metrics tests. After investigating the issue in [Research possible break change in Workload benchmarks metrics tests](https://github.com/wazuh/wazuh-jenkins/issues/6920), it was determined that the regression was caused by changes introduced in the test_api_endpoint_performance test, as part of https://github.com/wazuh/wazuh-qa/pull/4657.

It is necessary to revert the changes in test_api_endpoint_performance to align with standardized test procedures.

## Tasks

- [x] Revert https://github.com/wazuh/wazuh-jenkins/issues/6920
- [x] Analyze the [original issue](https://github.com/wazuh/wazuh-qa/issues/3665) and determine if the suggested changes need to be implemented differently. Develop a coherent plan to test the expected failing tests.

## Validation
- [x] Workload benchmarks metrics tests pass and results match with 4.8.x

**Comment by GGP1** [comment]
## Update

I reverted the changes to the API performance tests. Given that the `active-response` endpoint won't be part of the 5.0 development, I don't think we should bother to make it work in 4.9.x.

**Comment by GGP1** [comment]
## Update

Applied suggested changes.
