### ISSUE TITLE
Support new OS - QA issue analysis and design

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-qa#5736]
# Description

Actually, the following [issue](https://github.com/wazuh/wazuh/issues/23748) is created to the QA team to test and support each new OS, we need to analyze the requirements and the tasks to be done, as some of them require clarification, due to the migration and new CI development we are working on.

> - We need to request a new machine to:
>   - Test the deployment one-liner for the new OS.
>   - Do basic E2E test functionality for all stateful modules according to the OS's tier.
> - We need to add/update/check new tests according to the OS's tier.
> - We need to add the new OS to the E2E UX testing template.
> - We need to add proper documentation.

## Related 

- https://github.com/wazuh/wazuh/issues/23748

# Tasks

- [x] Propose a new issue
- [ ] Update wazuh/wazuh template
- [ ] Update Wazuh documentation for Support new OS when PR is accepted

**Comment by rauldpm** [comment]
# Update report

- After analysis, the following proposal is made:

---

# QA Support new OS tasks

## Considerations

- Testing environment: Deploy the new OS taking into account the following notes:
  - If the Wazuh central components are supported: 1 VM
  - If the Wazuh agent is supported: 1 VM for each architecture supported.
  - If the Wazuh central components or the Wazuh agent is not supported, deploy a Debian 12 VM for the non-supported component.
- All testing tasks must be completed for each OS architecture supported.
- The following tasks should be completed in order.

## Tasks

- [ ] Test the Wazuh dashboard one-liner deployment.
  - [ ] Deploy a Wazuh agent using the Wazuh dashboard one-liner feature provided in the Wazuh user interface with the following cases.
    - [ ] Only IP address.
    - [ ] Only FQDN.
    - [ ] IP address, agent name, and group.
- [ ] E2E tests: Stateful modules test based on the Tier OS compatibility:
  - [ ] Log Collection
  - [ ] File Integrity Monitoring
  - [ ] Vulnerability Detection
  - [ ] Active Response
  - [ ] Wodle - Syscollector
  - [ ] Wodle - CIS-CAT
  - [ ] Wodle - Docker Listener
  - [ ] Wodle - osquery
- [ ] Add/Update/Check CI
  - [ ] Add the OS and each architecture to the JobFlow testing tool.
  - [ ] Add the OS and each architecture to the GitHub Deployability and Upgrade release templates.
  - [ ] Test the JobFlow testing tool for that specific system.
- [ ] Add the OS and its supported architectures to the E2E UX Tests spreadsheet (OS sheet)
- [ ] Add the OS and its supported architectures to the 5.x compatibility matrix.


---

- Waiting a review to accept those changes

**Comment by rauldpm** [comment]
QA documentation changed, now it has the following tasks

- Test the deployment one-liner for the new OS.
- We need to add the new OS to the E2E UX testing template.
- We need to add/update/check new tests according to the OS's tier.
- We need to add proper documentation.

So, the changes proposed changed to:

```
# QA Support new OS tasks

## Considerations

- Testing environment: Deploy the new OS taking into account the following notes:
  - If the Wazuh central components are supported: 1 VM
  - If the Wazuh agent is supported: 1 VM for each architecture supported.
  - If the Wazuh central components or the Wazuh agent is not supported, deploy a Debian 12 VM for the non-supported component.
- All testing tasks must be completed for each OS architecture supported.
- The following tasks should be completed in order.

## Tasks

- [ ] Test the Wazuh dashboard one-liner deployment.
  - [ ] Deploy a Wazuh agent using the Wazuh dashboard one-liner feature provided in the Wazuh user interface with the following cases.
    - [ ] Only IP address.
    - [ ] Only FQDN.
    - [ ] IP address, agent name, and group.
- [ ] Add/Update/Check CI
  - [ ] Test the JobFlow testing tool for that specific system.
  - [ ] Add the OS and each architecture to the JobFlow testing tool.
  - [ ] Add the OS and each architecture to the GitHub Deployability and Upgrade release templates.
- [ ] Add the OS and its supported architectures to the E2E UX Tests spreadsheet (OS sheet).
- [ ] Add the OS and its supported architectures to the 5.x compatibility matrix.
```

**Comment by hossam1522** [comment]
LGTM!
