### ISSUE TITLE
Publish release 4.8.1

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh-qa#5744]
## Description
This issue attempts to track the steps necessary to publish packages, OVA, AMI, docker images, and puppet forge for 4.8.1.

## Tasks
- [ ] Send AMI to analysis.
- [ ] Launch [`Publish_release`](https://ci.wazuh.info/job/Publish_release) pipeline without Kibana, Splunk, templates and unattended.
- [ ] Wait for `Publish_release` to finish.
- [ ] Publish unattended and templates.
- [ ] Upload latest Filebeat version.
- [ ] Release debug packages and checksums.
- [ ] Push [Docker Hub images](https://ci.wazuh.info/job/procedure_push_docker_images).

**Comment by pro-akim** [comment]
This issue was opened for testing purposes.
