### ISSUE TITLE
Support new stage RC 1 for 4.9.1 in wazuh-qa repository

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#5756]
## Description

This issue attempts to support a new stage RC 1 for 4.9.1 in the wazuh-qa repository.

## Tasks

- [x] Bump revision for branch 4.9.1 on wazuh-qa repository. https://github.com/wazuh/wazuh-qa/pull/5757
- [x] Ensure changelog is updated for 4.9.1 (if applicable). https://github.com/wazuh/wazuh-qa/pull/5758
- [x] Create tag v4.9.1-rc1 from branch 4.9.1 on wazuh-qa repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-qa/releases/tag/v4.9.1-rc1.

**Comment by Rebits** [comment]
LGTM
