### ISSUE TITLE
Publish release 4.8.1

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#5772]
## Description
This issue attempts to track the steps necessary to publish packages, OVA, AMI, docker images, and puppet forge for 4.8.1.

## Tasks
- [ ] Create manual production backup.
- [ ] Send AMI to analysis.
- [ ] Copy files from pre-release to production
    - [ ] Clone the wazuh-jenkins repository and checkout to the `v4.8.1` tag.
    - [ ] Follow the steps of the README file located at `new-jenkins/procedure/publish_release/README.md` (Container of `release_tool`)
        - Check if Filebeat should be published
        - Use the recipe `recipes/staging-to-prod.yaml`
        - Make sure that the YAML has the correct `global-variables`
- [ ] Publish unattended and templates.
- [ ] Publish Puppet forge.

**Comment by QU3B1M** [comment]
### Issue created for testing purposes. Closed as not planned
