### ISSUE TITLE
Publish release 4.9.1

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#5816]
## Description
This issue attempts to track the steps necessary to publish packages, OVA, AMI and puppet forge for 4.9.1.

## Tasks
- [x] Create manual production backup.
- [x] Send AMI to analysis.
- [x] Copy files from pre-release to production
    - [x] Clone the wazuh-jenkins repository and checkout to the `v4.9.1` tag.
    - [x] Follow the steps of the README file located at `new-jenkins/procedure/publish_release/README.md` (Container of `release_tool`)
        - Check if Filebeat should be published: Not necessary
        - Use the recipe `recipes/staging-to-prod.yaml`
        - Make sure that the YAML has the correct `global-variables`
- [x] Publish unattended and templates. https://ci.wazuh.info/job/publish_unattended/347/
- [x] Publish Puppet forge. https://ci.wazuh.info/job/Publish_release/410/

**Comment by Rebits** [comment]
- **Create manual production backup**:  Used pipeline for better tracking https://ci.wazuh.info/job/Publish_release/407 :green_circle: 
-  **Send AMI to analysis**: Sent and approved :green_circle:   
  
***

~Blocked due to retag in dashboard https://github.com/wazuh/wazuh-dashboard/issues/359~ 
-  **Copy files from pre-release to production** :construction: :  In progress


**Global variables validated by**:
- [x] @juliamagan 

<details>

<summary> staging-to-prod.yaml global variables</summary>

```yaml
description: Deploy files from STAGING to PROD
global-variables:
  major: "4"
  minor: "9"
  patch: "1"
  revision: "1"
  wazuh-version: "4.9.1"
  filebeat-version: "0.4"
  global-acl: "public-read"
  from: "staging"
  to: "prod" 
  workspace: "4.x"
... 
```

</details> 


In addition, it was validated dry mode output.


I am currently working on some errors detected during some package releases. Only a part of the release was successful. Release currently in process by @rauldpm (check https://github.com/wazuh/wazuh-qa/issues/5816#issuecomment-2419296663).
Notice to @wazuh-devel-devops regarding founds errors

**Comment by rauldpm** [comment]
Release to packages.wazuh.com launched, ETA ~1h


YAML: [staging-to-prod.yaml.txt](https://github.com/user-attachments/files/17412776/staging-to-prod.yaml.txt)
Log: [release_tool_2024-10-17_13-35-01-726.log](https://github.com/user-attachments/files/17412785/release_tool_2024-10-17_13-35-01-726.log)

<details><summary>Packages released</summary>

```
╰─➤  aws s3 ls s3://packages.wazuh.com/4.x/ --recursive --human-readable | grep "4\.9\.1" | grep "2024-10-17" 
2024-10-17 13:35:05   14.4 MiB 4.x/aix/wazuh-agent-4.9.1-1.aix.ppc.rpm
2024-10-17 14:51:05   10.3 MiB 4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.9.1-1_amd64.deb
2024-10-17 14:51:05    5.6 MiB 4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.9.1-1_arm64.deb
2024-10-17 14:51:05    5.2 MiB 4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.9.1-1_armhf.deb
2024-10-17 14:51:05   10.8 MiB 4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.9.1-1_i386.deb
2024-10-17 14:51:05  158.4 MiB 4.x/apt/pool/main/w/wazuh-dashboard/wazuh-dashboard_4.9.1-1_amd64.deb
2024-10-17 14:51:08  810.9 MiB 4.x/apt/pool/main/w/wazuh-indexer/wazuh-indexer_4.9.1-1_amd64.deb
2024-10-17 14:51:17  317.2 MiB 4.x/apt/pool/main/w/wazuh-manager/wazuh-manager_4.9.1-1_amd64.deb
2024-10-17 14:51:21  308.5 MiB 4.x/apt/pool/main/w/wazuh-manager/wazuh-manager_4.9.1-1_arm64.deb
2024-10-17 13:36:37  146 Bytes 4.x/checksums/wazuh/4.9.1/wazuh-4.9.1.ova.sha512
2024-10-17 13:35:07  172 Bytes 4.x/checksums/wazuh/4.9.1/wazuh-agent-4.9.1-1-hpux-11v3-ia64.tar.gz.sha512
2024-10-17 14:30:34  162 Bytes 4.x/checksums/wazuh/4.9.1/wazuh-agent-4.9.1-1.aarch64.rpm.sha512
2024-10-17 13:35:07  162 Bytes 4.x/checksums/wazuh/4.9.1/wazuh-agent-4.9.1-1.aix.ppc.rpm.sha512
2024-10-17 13:35:11    0 Bytes 4.x/checksums/wazuh/4.9.1/wazuh-agent-4.9.1-1.arm64.pkg.sha512
2024-10-17 14:30:40  162 Bytes 4.x/checksums/wazuh/4.9.1/wazuh-agent-4.9.1-1.armv7hl.rpm.sha512
2024-10-17 13:36:08  163 Bytes 4.x/checksums/wazuh/4.9.1/wazuh-agent-4.9.1-1.el5.i386.rpm.sha512
2024-10-17 13:35:55  165 Bytes 4.x/checksums/wazuh/4.9.1/wazuh-agent-4.9.1-1.el5.x86_64.rpm.sha512
2024-10-17 14:30:27  159 Bytes 4.x/checksums/wazuh/4.9.1/wazuh-agent-4.9.1-1.i386.rpm.sha512
2024-10-17 13:35:07    0 Bytes 4.x/checksums/wazuh/4.9.1/wazuh-agent-4.9.1-1.intel64.pkg.sha512
2024-10-17 13:35:07  159 Bytes 4.x/checksums/wazuh/4.9.1/wazuh-agent-4.9.1-1.msi.sha512
2024-10-17 14:30:20  161 Bytes 4.x/checksums/wazuh/4.9.1/wazuh-agent-4.9.1-1.x86_64.rpm.sha512
2024-10-17 14:23:52  160 Bytes 4.x/checksums/wazuh/4.9.1/wazuh-agent_4.9.1-1_amd64.deb.sha512
2024-10-17 14:24:05  160 Bytes 4.x/checksums/wazuh/4.9.1/wazuh-agent_4.9.1-1_arm64.deb.sha512
2024-10-17 14:24:11  160 Bytes 4.x/checksums/wazuh/4.9.1/wazuh-agent_4.9.1-1_armhf.deb.sha512
2024-10-17 14:23:59  159 Bytes 4.x/checksums/wazuh/4.9.1/wazuh-agent_4.9.1-1_i386.deb.sha512
2024-10-17 13:35:07  164 Bytes 4.x/checksums/wazuh/4.9.1/wazuh-agent_v4.9.1-sol10-i386.pkg.sha512
2024-10-17 13:35:11  165 Bytes 4.x/checksums/wazuh/4.9.1/wazuh-agent_v4.9.1-sol10-sparc.pkg.sha512
2024-10-17 13:35:15  164 Bytes 4.x/checksums/wazuh/4.9.1/wazuh-agent_v4.9.1-sol11-i386.p5p.sha512
2024-10-17 13:35:19  165 Bytes 4.x/checksums/wazuh/4.9.1/wazuh-agent_v4.9.1-sol11-sparc.p5p.sha512
2024-10-17 14:29:24  165 Bytes 4.x/checksums/wazuh/4.9.1/wazuh-dashboard-4.9.1-1.x86_64.rpm.sha512
2024-10-17 14:22:37  164 Bytes 4.x/checksums/wazuh/4.9.1/wazuh-dashboard_4.9.1-1_amd64.deb.sha512
2024-10-17 14:30:14  163 Bytes 4.x/checksums/wazuh/4.9.1/wazuh-indexer-4.9.1-1.x86_64.rpm.sha512
2024-10-17 14:23:45  162 Bytes 4.x/checksums/wazuh/4.9.1/wazuh-indexer_4.9.1-1_amd64.deb.sha512
2024-10-17 14:29:06  164 Bytes 4.x/checksums/wazuh/4.9.1/wazuh-manager-4.9.1-1.aarch64.rpm.sha512
2024-10-17 14:28:42  163 Bytes 4.x/checksums/wazuh/4.9.1/wazuh-manager-4.9.1-1.x86_64.rpm.sha512
2024-10-17 14:21:56  162 Bytes 4.x/checksums/wazuh/4.9.1/wazuh-manager_4.9.1-1_amd64.deb.sha512
2024-10-17 14:22:23  162 Bytes 4.x/checksums/wazuh/4.9.1/wazuh-manager_4.9.1-1_arm64.deb.sha512
2024-10-17 13:35:07  155 Bytes 4.x/checksums/wazuh/4.9.1/wazuh-wazuh-4.9.1.tar.gz.sha512
2024-10-17 13:35:07  169 Bytes 4.x/checksums/wazuh/4.9.1/wazuh_agent_v4.9.1_linux_amd64.deb.wpk.sha512
2024-10-17 13:35:27  170 Bytes 4.x/checksums/wazuh/4.9.1/wazuh_agent_v4.9.1_linux_x86_64.rpm.wpk.sha512
2024-10-17 13:35:38  171 Bytes 4.x/checksums/wazuh/4.9.1/wazuh_agent_v4.9.1_macos_intel64.pkg.wpk.sha512
2024-10-17 13:35:07  161 Bytes 4.x/checksums/wazuh/4.9.1/wazuh_agent_v4.9.1_windows.wpk.sha512
2024-10-17 13:35:05   16.5 MiB 4.x/hp-ux/wazuh-agent-4.9.1-1-hpux-11v3-ia64.tar.gz
2024-10-17 13:35:09    6.0 MiB 4.x/macos/wazuh-agent-4.9.1-1.arm64.pkg
2024-10-17 13:35:05    6.5 MiB 4.x/macos/wazuh-agent-4.9.1-1.intel64.pkg
2024-10-17 13:35:05   58.2 KiB 4.x/puppet-module/wazuh-wazuh-4.9.1.tar.gz
2024-10-17 13:35:05   16.6 MiB 4.x/solaris/i386/10/wazuh-agent_v4.9.1-sol10-i386.pkg
2024-10-17 13:35:14    7.0 MiB 4.x/solaris/i386/11/wazuh-agent_v4.9.1-sol11-i386.p5p
2024-10-17 13:35:09   17.6 MiB 4.x/solaris/sparc/10/wazuh-agent_v4.9.1-sol10-sparc.pkg
2024-10-17 13:35:18    6.9 MiB 4.x/solaris/sparc/11/wazuh-agent_v4.9.1-sol11-sparc.p5p
2024-10-17 13:35:05    3.7 GiB 4.x/vm/wazuh-4.9.1.ova
2024-10-17 13:35:05    6.9 MiB 4.x/windows/wazuh-agent-4.9.1-1.msi
2024-10-17 13:35:05   10.2 MiB 4.x/wpk/linux/deb/amd64/wazuh_agent_v4.9.1_linux_amd64.deb.wpk
2024-10-17 13:35:26   10.3 MiB 4.x/wpk/linux/rpm/x86_64/wazuh_agent_v4.9.1_linux_x86_64.rpm.wpk
2024-10-17 13:35:36    6.5 MiB 4.x/wpk/macos/pkg/intel64/wazuh_agent_v4.9.1_macos_intel64.pkg.wpk
2024-10-17 13:35:05    6.6 MiB 4.x/wpk/windows/wazuh_agent_v4.9.1_windows.wpk
2024-10-17 14:31:09   10.2 MiB 4.x/yum/wazuh-agent-4.9.1-1.aarch64.rpm
2024-10-17 14:31:09    9.5 MiB 4.x/yum/wazuh-agent-4.9.1-1.armv7hl.rpm
2024-10-17 14:31:09   10.9 MiB 4.x/yum/wazuh-agent-4.9.1-1.i386.rpm
2024-10-17 14:31:09   10.4 MiB 4.x/yum/wazuh-agent-4.9.1-1.x86_64.rpm
2024-10-17 14:31:10  252.8 MiB 4.x/yum/wazuh-dashboard-4.9.1-1.x86_64.rpm
2024-10-17 14:31:13  812.6 MiB 4.x/yum/wazuh-indexer-4.9.1-1.x86_64.rpm
2024-10-17 14:31:22  306.4 MiB 4.x/yum/wazuh-manager-4.9.1-1.aarch64.rpm
2024-10-17 14:31:25  313.6 MiB 4.x/yum/wazuh-manager-4.9.1-1.x86_64.rpm
2024-10-17 13:36:12    9.1 MiB 4.x/yum5/i386/wazuh-agent-4.9.1-1.el5.i386.rpm
2024-10-17 13:35:59    8.5 MiB 4.x/yum5/x86_64/wazuh-agent-4.9.1-1.el5.x86_64.rpm
```

</details>

**Comment by jnasselle** [comment]
LGTM!

NOTE: description was modified to remove docker images, since @rauldpm clarifies that they are executed after packages go to prod to build from there

**Comment by rauldpm** [comment]
Docker images are released as a task of the https://github.com/wazuh/wazuh-jenkins/issues/7039 issue
