### ISSUE TITLE
Publish release 4.9.2

### ISSUE THREAD

**Issue by wazuhci** [wazuh/wazuh-qa#5836]
## Description
This issue attempts to track the steps necessary to publish packages, OVA, AMI, docker images, and puppet forge for 4.9.2.

## Tasks
- [x] Create manual production backup.
- [x] Send AMI to analysis.
- [x] Copy files from pre-release to production
    - [x] Clone the wazuh-jenkins repository and checkout to the `v4.9.2` tag.
    - [x] Follow the steps of the README file located at `new-jenkins/procedure/publish_release/README.md` (Container of `release_tool`)
        - ~Check if Filebeat should be published~ No changes here https://github.com/wazuh/wazuh-jenkins/issues/7060
        - Use the recipe `recipes/staging-to-prod.yaml`
        - Make sure that the YAML has the correct `global-variables`
- [x] Publish unattended and templates. https://ci.wazuh.info/job/publish_unattended/351/console
- [x] Publish Puppet forge. https://ci.wazuh.info/job/Publish_release/413/console

**Comment by Rebits** [comment]
-  Create manual production backup :green_circle:  
    - **Build**: https://ci.wazuh.info/job/Publish_release/411
    - Manually reviewing the backup
    - Backup correctly created
![image](https://github.com/user-attachments/assets/bef8bfb0-11a4-4b56-88f1-0af17a959ef1)
-  Send AMI to analysis :construction: 
![image](https://github.com/user-attachments/assets/7df03563-ac64-415e-b35a-7a32b1d88d79)

- Copy files from pre-release to production. Release to packages.wazuh.com launched, ETA ~1h :construction:

<details>

<summary> YAML </summary>

```yaml
description: Deploy files from STAGING to PROD
global-variables:
  major: "4"
  minor: "9"
  patch: "2"
  revision: "1"
  wazuh-version: "{major}.{minor}.{patch}"
  filebeat-version: "0.4"
  global-acl: "public-read"
  from: "staging"
  to: "prod"
  workspace: "storage/prod"
tasks:
  deb:
    type: "deb-repo"
    common:
      remote-repo: "{to}/apt"
      working-dir: "{workspace}/apt"
      invalidate-cache: "{to}/apt/*"
      distribution: "stable"
      acl: "{global-acl}"
      sign-key-passphrase: "package-signer-passphrase"
      sign-key: "package-signer-key"
    subtask:
      label: "deb-{subsystem}-{arch}"
      operations:
        - add-package:
            from: "{from}/apt/pool/main/w/{subsystem}/{subsystem}_{wazuh-version}-{revision}_{arch}.deb"
        - copy:
            from: "{from}/checksums/wazuh/{wazuh-version}/{subsystem}_{wazuh-version}-{revision}_{arch}.deb.sha512"
            to: "{to}/checksums/wazuh/{wazuh-version}/{subsystem}_{wazuh-version}-{revision}_{arch}.deb.sha512"
            acl: "{global-acl}"
        - invalidate-cache:
            - "{to}/checksums/wazuh/{wazuh-version}/{subsystem}_{wazuh-version}-{revision}_{arch}.deb.sha512"
    substitution-groups:
      managers:
        subsystem: "wazuh-manager"
        arch: [ "amd64", "arm64" ]
      dashboards:
        subsystem: "wazuh-dashboard"
        arch: "amd64"
      indexers:
        subsystem: "wazuh-indexer"
        arch: "amd64"
      agents:
        subsystem: "wazuh-agent"
        arch: [ "amd64", "i386", "arm64", "armhf" ]
  rpm:
    type: "rpm-repo"
    common:
      working-dir: "{workspace}/yum"
      remote-repo: "{to}/yum"
      acl: "{global-acl}"
      rpm-hash: "sha256"
      invalidate-cache: "{to}/yum/*"
      sign-key-passphrase: "package-signer-passphrase"
      sign-key: "package-signer-key"
    subtask:
      label: "rpm-{subsystem}-{arch}"
      operations:
        - add-package:
            from: "{from}/yum/{subsystem}-{wazuh-version}-{revision}.{arch}.rpm"
        - copy:
            from: "{from}/checksums/wazuh/{wazuh-version}/{subsystem}-{wazuh-version}-{revision}.{arch}.rpm.sha512"
            to: "{to}/checksums/wazuh/{wazuh-version}/{subsystem}-{wazuh-version}-{revision}.{arch}.rpm.sha512"
            acl: "{global-acl}"
        - invalidate-cache:
            - "{to}/checksums/wazuh/{wazuh-version}/{subsystem}-{wazuh-version}-{revision}.{arch}.rpm.sha512"
    substitution-groups:
      managers:
        subsystem: "wazuh-manager"
        arch: [ "x86_64", "aarch64" ]
      dashboards:
        subsystem: "wazuh-dashboard"
        arch: "x86_64"
      indexers:
        subsystem: "wazuh-indexer"
        arch: "x86_64"
      agents:
        subsystem: "wazuh-agent"
        arch: [ "x86_64", "i386", "aarch64", "armv7hl" ]
  rpm5-i386:
    type: "rpm-repo"
    common:
      remote-repo: "{to}/yum5/i386"
      acl: "{global-acl}"
      working-dir: "{workspace}/yum5/i386"
      rpm-hash: "sha"
      invalidate-cache: "{to}/yum5/i386/*"
      sign-key-passphrase: "package-signer-passphrase"
      sign-key: "package-signer-legacy-key"
    subtask:
      label: "rpm5-wazuh-agent-i386"
      operations:
        - add-package:
            from: "{from}/yum5/i386/wazuh-agent-{wazuh-version}-{revision}.el5.i386.rpm"
        - copy:
            from: "{from}/checksums/wazuh/{wazuh-version}/wazuh-agent-{wazuh-version}-{revision}.el5.i386.rpm.sha512"
            to: "{to}/checksums/wazuh/{wazuh-version}/wazuh-agent-{wazuh-version}-{revision}.el5.i386.rpm.sha512"
            acl: "{global-acl}"
        - invalidate-cache:
            - "{to}/checksums/wazuh/{wazuh-version}/wazuh-agent-{wazuh-version}-{revision}.el5.i386.rpm.sha512"
  rpm5-x86_64:
      type: "rpm-repo"
      common:
        working-dir: "{workspace}/yum5/x86_64"
        remote-repo: "{to}/yum5/x86_64"
        rpm-hash: "sha"
        acl: "{global-acl}"
        invalidate-cache: "{to}/yum5/x86_64/*"
        sign-key-passphrase: "package-signer-passphrase"
        sign-key: "package-signer-legacy-key"
      subtask:
        label: "rpm5-wazuh-agent-x86_64"
        operations:
          - add-package:
              from: "{from}/yum5/x86_64/wazuh-agent-{wazuh-version}-{revision}.el5.x86_64.rpm"
          - copy:
              from: "{from}/checksums/wazuh/{wazuh-version}/wazuh-agent-{wazuh-version}-{revision}.el5.x86_64.rpm.sha512"
              to: "{to}/checksums/wazuh/{wazuh-version}/wazuh-agent-{wazuh-version}-{revision}.el5.x86_64.rpm.sha512"
              acl: "{global-acl}"
          - invalidate-cache:
              - "{to}/checksums/wazuh/{wazuh-version}/wazuh-agent-{wazuh-version}-{revision}.el5.x86_64.rpm.sha512"
  windows:
    type: "s3-to-s3"
    subtask:
      label: "windows-wazuh-agent-i386"
      operations:
        - copy:
            from: "{from}/windows/wazuh-agent-{wazuh-version}-{revision}.msi"
            to: "{to}/windows/wazuh-agent-{wazuh-version}-{revision}.msi"
            acl: "{global-acl}"
        - copy:
            from: "{from}/checksums/wazuh/{wazuh-version}/wazuh-agent-{wazuh-version}-{revision}.msi.sha512"
            to: "{to}/checksums/wazuh/{wazuh-version}/wazuh-agent-{wazuh-version}-{revision}.msi.sha512"
            acl: "{global-acl}"
        - invalidate-cache:
            - "{to}/windows/wazuh-agent-{wazuh-version}-{revision}.msi"
            - "{to}/checksums/wazuh/{wazuh-version}/wazuh-agent-{wazuh-version}-{revision}.msi.sha512"
  macos:
    type: "s3-to-s3"
    subtask:
      label: "macos-wazuh-agent-{arch}"
      operations:
        - copy:
            from: "{from}/macos/wazuh-agent-{wazuh-version}-{revision}.{arch}.pkg"
            to: "{to}/macos/wazuh-agent-{wazuh-version}-{revision}.{arch}.pkg"
            acl: "{global-acl}"
        - copy:
            from: "{from}/checksums/wazuh/{wazuh-version}/wazuh-agent-{wazuh-version}-{revision}.{arch}.pkg.sha512"
            to: "{to}/checksums/wazuh/{wazuh-version}/wazuh-agent-{wazuh-version}-{revision}.{arch}.pkg.sha512"
            acl: "{global-acl}"
        - invalidate-cache:
            - "{to}/macos/wazuh-agent-{wazuh-version}-{revision}.{arch}.pkg"
            - "{to}/checksums/wazuh/{wazuh-version}/wazuh-agent-{wazuh-version}-{revision}.{arch}.pkg.sha512"
    substitution-groups:
      agents:
        arch: [ "intel64", "arm64" ]
  wpk:
    type: "wpk"
    subtask:
      label: "wpk-{os}-{extension}-{arch}"
      operations:
        - copy:
            from: "{from}/wpk/{os}/{extension}/{arch}/wazuh_agent_v{wazuh-version}_{os}_{arch}.{extension}.wpk"
            to: "{to}/wpk/{os}/{extension}/{arch}/wazuh_agent_v{wazuh-version}_{os}_{arch}.{extension}.wpk"
            acl: "{global-acl}"
        - copy:
            from: "{from}/checksums/wazuh/{wazuh-version}/wazuh_agent_v{wazuh-version}_{os}_{arch}.{extension}.wpk.sha512"
            to: "{to}/checksums/wazuh/{wazuh-version}/wazuh_agent_v{wazuh-version}_{os}_{arch}.{extension}.wpk.sha512"
            acl: "{global-acl}"
        - update-wpk-versions:
            working-dir: "{workspace}/wpk/{os}/{extension}/{arch}"
            remote-repo: "{to}/wpk/{os}/{extension}/{arch}"
            acl: "{global-acl}"
        - invalidate-cache:
            - "{to}/wpk/{os}/{extension}/{arch}/wazuh_agent_v{wazuh-version}_{os}_{arch}.{extension}.wpk"
            - "{to}/checksums/wazuh/{wazuh-version}/wazuh_agent_v{wazuh-version}_{os}_{arch}.{extension}.wpk.sha512"
            - "{to}/wpk/{os}/{extension}/{arch}/versions"
    substitution-groups:
      linux-deb:
        os: "linux"
        extension: "deb"
        arch: "amd64"
      linux-rpm:
        os: "linux"
        extension: "rpm"
        arch: "x86_64"
      macos:
        os: "macos"
        extension: "pkg"
        arch: "intel64"
  wpk-windows:
    type: "wpk"
    subtask:
      label: "wpk-windows-msi-i386"
      operations:
        - copy:
            from: "{from}/wpk/windows/wazuh_agent_v{wazuh-version}_windows.wpk"
            to: "{to}/wpk/windows/wazuh_agent_v{wazuh-version}_windows.wpk"
            acl: "{global-acl}"
        - copy:
            from: "{from}/checksums/wazuh/{wazuh-version}/wazuh_agent_v{wazuh-version}_windows.wpk.sha512"
            to: "{to}/checksums/wazuh/{wazuh-version}/wazuh_agent_v{wazuh-version}_windows.wpk.sha512"
            acl: "{global-acl}"
        - update-wpk-versions:
            working-dir: "{workspace}/wpk-windows/"
            remote-repo: "{to}/wpk/windows/"
            acl: "{global-acl}"
        - invalidate-cache:
            - "{to}/wpk/windows/wazuh_agent_v{wazuh-version}_windows.wpk"
            - "{to}/checksums/wazuh/{wazuh-version}/wazuh_agent_v{wazuh-version}_windows.wpk.sha512"
            - "{to}/wpk/windows/versions"
  # Packages that only exist on STAGING and PROD
  solaris:
    type: "s3-to-s3"
    subtask:
      label: "solaris-{solaris-numeric}-agent-{arch}"
      operations:
        - copy:
            from: "{from}/solaris/{arch}/{solaris-numeric}/wazuh-agent_v{wazuh-version}-sol{solaris-numeric}-{arch}.{extension}"
            to: "{to}/solaris/{arch}/{solaris-numeric}/wazuh-agent_v{wazuh-version}-sol{solaris-numeric}-{arch}.{extension}"
            acl: "{global-acl}"
        - copy:
            from: "{from}/checksums/wazuh/{wazuh-version}/wazuh-agent_v{wazuh-version}-sol{solaris-numeric}-{arch}.{extension}.sha512"
            to: "{to}/checksums/wazuh/{wazuh-version}/wazuh-agent_v{wazuh-version}-sol{solaris-numeric}-{arch}.{extension}.sha512"
            acl: "{global-acl}"
        - invalidate-cache:
            - "{to}/solaris/{arch}/{solaris-numeric}/wazuh-agent_v{wazuh-version}-sol{solaris-numeric}-{arch}.{extension}"
            - "{to}/checksums/wazuh/{wazuh-version}/wazuh-agent_v{wazuh-version}-sol{solaris-numeric}-{arch}.{extension}.sha512"
    substitution-groups:
      sol10:
        solaris-numeric: "10"
        arch: ["i386", "sparc"]
        extension: "pkg"
      sol11:
        solaris-numeric: "11"
        arch: ["i386", "sparc"]
        extension: "p5p"
  hp-ux:
    type: "s3-to-s3"
    subtask:
      label: "hp-ux"
      operations:
        - copy:
            from: "{from}/hp-ux/wazuh-agent-{wazuh-version}-{revision}-hpux-11v3-ia64.tar.gz"
            to: "{to}/hp-ux/wazuh-agent-{wazuh-version}-{revision}-hpux-11v3-ia64.tar.gz"
            acl: "{global-acl}"
        - copy:
            from: "{from}/checksums/wazuh/{wazuh-version}/wazuh-agent-{wazuh-version}-{revision}-hpux-11v3-ia64.tar.gz.sha512"
            to: "{to}/checksums/wazuh/{wazuh-version}/wazuh-agent-{wazuh-version}-{revision}-hpux-11v3-ia64.tar.gz.sha512"
            acl: "{global-acl}"
        - invalidate-cache:
            - "{to}/hp-ux/wazuh-agent-{wazuh-version}-{revision}-hpux-11v3-ia64.tar.gz"
            - "{to}/checksums/wazuh/{wazuh-version}/wazuh-agent-{wazuh-version}-{revision}-hpux-11v3-ia64.tar.gz.sha512"
  aix:
    type: "s3-to-s3"
    subtask:
      label: "aix"
      operations:
        - copy:
            from: "{from}/aix/wazuh-agent-{wazuh-version}-{revision}.aix.ppc.rpm"
            to: "{to}/aix/wazuh-agent-{wazuh-version}-{revision}.aix.ppc.rpm"
            acl: "{global-acl}"
        - copy:
            from: "{from}/checksums/wazuh/{wazuh-version}/wazuh-agent-{wazuh-version}-{revision}.aix.ppc.rpm.sha512"
            to: "{to}/checksums/wazuh/{wazuh-version}/wazuh-agent-{wazuh-version}-{revision}.aix.ppc.rpm.sha512"
            acl: "{global-acl}"
        - invalidate-cache:
            - "{to}/aix/wazuh-agent-{wazuh-version}-{revision}.aix.ppc.rpm"
            - "{to}/checksums/wazuh/{wazuh-version}/wazuh-agent-{wazuh-version}-{revision}.aix.ppc.rpm.sha512"
  ova:
    type: "s3-to-s3"
    subtask:
      label: "ova"
      operations:
        - copy:
            from: "{from}/vm/wazuh-{wazuh-version}.ova"
            to: "{to}/vm/wazuh-{wazuh-version}.ova"
            acl: "{global-acl}"
        - copy:
            from: "{from}/checksums/wazuh/{wazuh-version}/wazuh-{wazuh-version}.ova.sha512"
            to: "{to}/checksums/wazuh/{wazuh-version}/wazuh-{wazuh-version}.ova.sha512"
            acl: "{global-acl}"
        - invalidate-cache:
            - "{to}/vm/wazuh-{wazuh-version}.ova"
            - "{to}/checksums/wazuh/{wazuh-version}/wazuh-{wazuh-version}.ova.sha512"
  puppet:
    type: "s3-to-s3"
    subtask:
      label: "puppet"
      operations:
        - copy:
            from: "{from}/puppet-module/wazuh-wazuh-{wazuh-version}.tar.gz"
            to: "{to}/puppet-module/wazuh-wazuh-{wazuh-version}.tar.gz"
            acl: "{global-acl}"
        - copy:
            from: "{from}/checksums/wazuh/{wazuh-version}/wazuh-wazuh-{wazuh-version}.tar.gz.sha512"
            to: "{to}/checksums/wazuh/{wazuh-version}/wazuh-wazuh-{wazuh-version}.tar.gz.sha512"
            acl: "{global-acl}"
        - invalidate-cache:
            - "{to}/puppet-module/wazuh-wazuh-{wazuh-version}.tar.gz"
            - "{to}/checksums/wazuh/{wazuh-version}/wazuh-wazuh-{wazuh-version}.tar.gz.sha512"

```

</details> 



Permission error, reported in  https://github.com/wazuh/wazuh-qa-automation/issues/333

**Comment by rauldpm** [comment]
## Release

- Packages released to packages.wazuh.com
  - [release_tool_2024-11-04_15-32-41-101.log](https://github.com/user-attachments/files/17620825/release_tool_2024-11-04_15-32-41-101.log)



<details><summary>Packages list</summary>

```
╰─➤  aws s3 ls s3://packages.wazuh.com/4.x --recursive --human-readable | grep "4\.9\.2"        
2024-11-04 15:32:44   14.4 MiB 4.x/aix/wazuh-agent-4.9.2-1.aix.ppc.rpm
2024-11-04 16:51:41   10.3 MiB 4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.9.2-1_amd64.deb
2024-11-04 16:51:41    5.6 MiB 4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.9.2-1_arm64.deb
2024-11-04 16:51:41    5.2 MiB 4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.9.2-1_armhf.deb
2024-11-04 16:51:41   10.8 MiB 4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.9.2-1_i386.deb
2024-11-04 16:51:41  158.4 MiB 4.x/apt/pool/main/w/wazuh-dashboard/wazuh-dashboard_4.9.2-1_amd64.deb
2024-11-04 16:51:44  810.9 MiB 4.x/apt/pool/main/w/wazuh-indexer/wazuh-indexer_4.9.2-1_amd64.deb
2024-11-04 16:51:53  317.7 MiB 4.x/apt/pool/main/w/wazuh-manager/wazuh-manager_4.9.2-1_amd64.deb
2024-11-04 16:51:57  308.9 MiB 4.x/apt/pool/main/w/wazuh-manager/wazuh-manager_4.9.2-1_arm64.deb
2024-11-04 15:34:46  146 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-4.9.2.ova.sha512
2024-11-04 15:32:45  172 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-agent-4.9.2-1-hpux-11v3-ia64.tar.gz.sha512
2024-11-04 16:30:27  162 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-agent-4.9.2-1.aarch64.rpm.sha512
2024-11-04 15:32:45  162 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-agent-4.9.2-1.aix.ppc.rpm.sha512
2024-11-04 15:32:49  160 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-agent-4.9.2-1.arm64.pkg.sha512
2024-11-04 16:30:34  162 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-agent-4.9.2-1.armv7hl.rpm.sha512
2024-11-04 15:33:36  163 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-agent-4.9.2-1.el5.i386.rpm.sha512
2024-11-04 15:33:37  165 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-agent-4.9.2-1.el5.x86_64.rpm.sha512
2024-11-04 16:30:20  159 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-agent-4.9.2-1.i386.rpm.sha512
2024-11-04 15:32:45  162 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-agent-4.9.2-1.intel64.pkg.sha512
2024-11-04 15:32:45  159 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-agent-4.9.2-1.msi.sha512
2024-11-04 16:30:14  161 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-agent-4.9.2-1.x86_64.rpm.sha512
2024-11-04 16:23:44  160 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-agent_4.9.2-1_amd64.deb.sha512
2024-11-04 16:23:56  160 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-agent_4.9.2-1_arm64.deb.sha512
2024-11-04 16:24:06  160 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-agent_4.9.2-1_armhf.deb.sha512
2024-11-04 16:23:51  159 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-agent_4.9.2-1_i386.deb.sha512
2024-11-04 15:32:45  164 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-agent_v4.9.2-sol10-i386.pkg.sha512
2024-11-04 15:32:49  165 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-agent_v4.9.2-sol10-sparc.pkg.sha512
2024-11-04 15:32:52  164 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-agent_v4.9.2-sol11-i386.p5p.sha512
2024-11-04 15:32:57  165 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-agent_v4.9.2-sol11-sparc.p5p.sha512
2024-11-04 16:29:02  165 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-dashboard-4.9.2-1.x86_64.rpm.sha512
2024-11-04 16:22:24  164 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-dashboard_4.9.2-1_amd64.deb.sha512
2024-11-04 16:29:58  163 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-indexer-4.9.2-1.x86_64.rpm.sha512
2024-11-04 16:23:22  162 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-indexer_4.9.2-1_amd64.deb.sha512
2024-11-04 16:28:44  164 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-manager-4.9.2-1.aarch64.rpm.sha512
2024-11-04 16:28:22  163 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-manager-4.9.2-1.x86_64.rpm.sha512
2024-11-04 16:21:42  162 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-manager_4.9.2-1_amd64.deb.sha512
2024-11-04 16:22:07  162 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-manager_4.9.2-1_arm64.deb.sha512
2024-11-04 15:32:45  155 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-wazuh-4.9.2.tar.gz.sha512
2024-11-04 15:32:45  169 Bytes 4.x/checksums/wazuh/4.9.2/wazuh_agent_v4.9.2_linux_amd64.deb.wpk.sha512
2024-11-04 15:33:02  170 Bytes 4.x/checksums/wazuh/4.9.2/wazuh_agent_v4.9.2_linux_x86_64.rpm.wpk.sha512
2024-11-04 15:33:14  171 Bytes 4.x/checksums/wazuh/4.9.2/wazuh_agent_v4.9.2_macos_intel64.pkg.wpk.sha512
2024-11-04 15:32:45  161 Bytes 4.x/checksums/wazuh/4.9.2/wazuh_agent_v4.9.2_windows.wpk.sha512
2024-11-04 15:32:43   16.5 MiB 4.x/hp-ux/wazuh-agent-4.9.2-1-hpux-11v3-ia64.tar.gz
2024-11-04 15:32:47    6.0 MiB 4.x/macos/wazuh-agent-4.9.2-1.arm64.pkg
2024-11-04 15:32:44    6.5 MiB 4.x/macos/wazuh-agent-4.9.2-1.intel64.pkg
2024-11-04 15:32:44   58.2 KiB 4.x/puppet-module/wazuh-wazuh-4.9.2.tar.gz
2024-11-04 15:32:44   16.6 MiB 4.x/solaris/i386/10/wazuh-agent_v4.9.2-sol10-i386.pkg
2024-11-04 15:32:51    7.0 MiB 4.x/solaris/i386/11/wazuh-agent_v4.9.2-sol11-i386.p5p
2024-11-04 15:32:47   17.6 MiB 4.x/solaris/sparc/10/wazuh-agent_v4.9.2-sol10-sparc.pkg
2024-11-04 15:32:55    6.9 MiB 4.x/solaris/sparc/11/wazuh-agent_v4.9.2-sol11-sparc.p5p
2024-11-04 15:32:44    3.7 GiB 4.x/vm/wazuh-4.9.2.ova
2024-11-04 15:32:43    6.9 MiB 4.x/windows/wazuh-agent-4.9.2-1.msi
2024-11-04 15:32:44   10.2 MiB 4.x/wpk/linux/deb/amd64/wazuh_agent_v4.9.2_linux_amd64.deb.wpk
2024-11-04 15:33:01   10.3 MiB 4.x/wpk/linux/rpm/x86_64/wazuh_agent_v4.9.2_linux_x86_64.rpm.wpk
2024-11-04 15:33:13    6.5 MiB 4.x/wpk/macos/pkg/intel64/wazuh_agent_v4.9.2_macos_intel64.pkg.wpk
2024-11-04 15:32:44    6.6 MiB 4.x/wpk/windows/wazuh_agent_v4.9.2_windows.wpk
2024-11-04 16:31:04   10.2 MiB 4.x/yum/wazuh-agent-4.9.2-1.aarch64.rpm
2024-11-04 16:31:04    9.5 MiB 4.x/yum/wazuh-agent-4.9.2-1.armv7hl.rpm
2024-11-04 16:31:04   10.9 MiB 4.x/yum/wazuh-agent-4.9.2-1.i386.rpm
2024-11-04 16:31:05   10.4 MiB 4.x/yum/wazuh-agent-4.9.2-1.x86_64.rpm
2024-11-04 16:31:05  252.8 MiB 4.x/yum/wazuh-dashboard-4.9.2-1.x86_64.rpm
2024-11-04 16:31:08  812.6 MiB 4.x/yum/wazuh-indexer-4.9.2-1.x86_64.rpm
2024-11-04 16:31:21  306.9 MiB 4.x/yum/wazuh-manager-4.9.2-1.aarch64.rpm
2024-11-04 16:31:17  314.1 MiB 4.x/yum/wazuh-manager-4.9.2-1.x86_64.rpm
2024-11-04 15:33:39    9.1 MiB 4.x/yum5/i386/wazuh-agent-4.9.2-1.el5.i386.rpm
2024-11-04 15:33:41    8.5 MiB 4.x/yum5/x86_64/wazuh-agent-4.9.2-1.el5.x86_64.rpm
```

</details>

**Comment by Rebits** [comment]
- Puppet correctly published :heavy_check_mark:  https://forge.puppet.com/modules/wazuh/wazuh/readme
![image](https://github.com/user-attachments/assets/d8895e72-96c0-4824-bc4b-cf994a4a6a59)

- Unattended and templates were correctly published :heavy_check_mark: 

LGTM
