### ISSUE TITLE
Post publication live checks for 4.9.2

### ISSUE THREAD

**Issue by wazuhci** [wazuh/wazuh-qa#5837]
## Description
This issue attempts to ensure the publication process was correct, attempting checks and live tests for published packages and images.

## Tasks
- [x] Ensure that production files are present.
- [x] Deploy the `Wazuh Installation Assistant` and check the version installed is 4.9.2.
- [x] [AMD64 Live installation test](https://ci.wazuh.info/job/Test_install_tier).
- [x] WPK versions check.
- [x] WPK upgrade test.
  - [x] Linux DEB
  - [x] Linux RPM
  - [x] MacOS Intel
  - [x] Windows
- [x] [Puppet forge module published](https://forge.puppet.com/modules/wazuh/wazuh/readme).

**Comment by rauldpm** [comment]
## Ensure that production files are present. :green_circle: 

<details><summary>Packages list</summary>

```
╰─➤  aws s3 ls s3://packages.wazuh.com/4.x --recursive --human-readable | grep "4\.9\.2" 
2024-11-04 15:32:44   14.4 MiB 4.x/aix/wazuh-agent-4.9.2-1.aix.ppc.rpm
2024-11-04 16:51:41   10.3 MiB 4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.9.2-1_amd64.deb
2024-11-04 16:51:41    5.6 MiB 4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.9.2-1_arm64.deb
2024-11-04 16:51:41    5.2 MiB 4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.9.2-1_armhf.deb
2024-11-04 16:51:41   10.8 MiB 4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.9.2-1_i386.deb
2024-11-04 16:51:41  158.4 MiB 4.x/apt/pool/main/w/wazuh-dashboard/wazuh-dashboard_4.9.2-1_amd64.deb
2024-11-04 16:51:44  810.9 MiB 4.x/apt/pool/main/w/wazuh-indexer/wazuh-indexer_4.9.2-1_amd64.deb
2024-11-04 16:51:53  317.7 MiB 4.x/apt/pool/main/w/wazuh-manager/wazuh-manager_4.9.2-1_amd64.deb
2024-11-04 16:51:57  308.9 MiB 4.x/apt/pool/main/w/wazuh-manager/wazuh-manager_4.9.2-1_arm64.deb
2024-11-04 15:34:46  146 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-4.9.2.ova.sha512
2024-11-04 15:32:45  172 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-agent-4.9.2-1-hpux-11v3-ia64.tar.gz.sha512
2024-11-04 16:30:27  162 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-agent-4.9.2-1.aarch64.rpm.sha512
2024-11-04 15:32:45  162 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-agent-4.9.2-1.aix.ppc.rpm.sha512
2024-11-04 15:32:49  160 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-agent-4.9.2-1.arm64.pkg.sha512
2024-11-04 16:30:34  162 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-agent-4.9.2-1.armv7hl.rpm.sha512
2024-11-04 15:33:36  163 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-agent-4.9.2-1.el5.i386.rpm.sha512
2024-11-04 15:33:37  165 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-agent-4.9.2-1.el5.x86_64.rpm.sha512
2024-11-04 16:30:20  159 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-agent-4.9.2-1.i386.rpm.sha512
2024-11-04 15:32:45  162 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-agent-4.9.2-1.intel64.pkg.sha512
2024-11-04 15:32:45  159 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-agent-4.9.2-1.msi.sha512
2024-11-04 16:30:14  161 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-agent-4.9.2-1.x86_64.rpm.sha512
2024-11-04 16:23:44  160 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-agent_4.9.2-1_amd64.deb.sha512
2024-11-04 16:23:56  160 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-agent_4.9.2-1_arm64.deb.sha512
2024-11-04 16:24:06  160 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-agent_4.9.2-1_armhf.deb.sha512
2024-11-04 16:23:51  159 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-agent_4.9.2-1_i386.deb.sha512
2024-11-04 15:32:45  164 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-agent_v4.9.2-sol10-i386.pkg.sha512
2024-11-04 15:32:49  165 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-agent_v4.9.2-sol10-sparc.pkg.sha512
2024-11-04 15:32:52  164 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-agent_v4.9.2-sol11-i386.p5p.sha512
2024-11-04 15:32:57  165 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-agent_v4.9.2-sol11-sparc.p5p.sha512
2024-11-04 16:29:02  165 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-dashboard-4.9.2-1.x86_64.rpm.sha512
2024-11-04 16:22:24  164 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-dashboard_4.9.2-1_amd64.deb.sha512
2024-11-04 16:29:58  163 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-indexer-4.9.2-1.x86_64.rpm.sha512
2024-11-04 16:23:22  162 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-indexer_4.9.2-1_amd64.deb.sha512
2024-11-04 16:28:44  164 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-manager-4.9.2-1.aarch64.rpm.sha512
2024-11-04 16:28:22  163 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-manager-4.9.2-1.x86_64.rpm.sha512
2024-11-04 16:21:42  162 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-manager_4.9.2-1_amd64.deb.sha512
2024-11-04 16:22:07  162 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-manager_4.9.2-1_arm64.deb.sha512
2024-11-04 17:11:21  155 Bytes 4.x/checksums/wazuh/4.9.2/wazuh-wazuh-4.9.2.tar.gz.sha512
2024-11-04 15:32:45  169 Bytes 4.x/checksums/wazuh/4.9.2/wazuh_agent_v4.9.2_linux_amd64.deb.wpk.sha512
2024-11-04 15:33:02  170 Bytes 4.x/checksums/wazuh/4.9.2/wazuh_agent_v4.9.2_linux_x86_64.rpm.wpk.sha512
2024-11-04 15:33:14  171 Bytes 4.x/checksums/wazuh/4.9.2/wazuh_agent_v4.9.2_macos_intel64.pkg.wpk.sha512
2024-11-04 15:32:45  161 Bytes 4.x/checksums/wazuh/4.9.2/wazuh_agent_v4.9.2_windows.wpk.sha512
2024-11-04 15:32:43   16.5 MiB 4.x/hp-ux/wazuh-agent-4.9.2-1-hpux-11v3-ia64.tar.gz
2024-11-04 15:32:47    6.0 MiB 4.x/macos/wazuh-agent-4.9.2-1.arm64.pkg
2024-11-04 15:32:44    6.5 MiB 4.x/macos/wazuh-agent-4.9.2-1.intel64.pkg
2024-11-04 17:11:10   58.2 KiB 4.x/puppet-module/wazuh-wazuh-4.9.2.tar.gz
2024-11-04 15:32:44   16.6 MiB 4.x/solaris/i386/10/wazuh-agent_v4.9.2-sol10-i386.pkg
2024-11-04 15:32:51    7.0 MiB 4.x/solaris/i386/11/wazuh-agent_v4.9.2-sol11-i386.p5p
2024-11-04 15:32:47   17.6 MiB 4.x/solaris/sparc/10/wazuh-agent_v4.9.2-sol10-sparc.pkg
2024-11-04 15:32:55    6.9 MiB 4.x/solaris/sparc/11/wazuh-agent_v4.9.2-sol11-sparc.p5p
2024-11-04 15:32:44    3.7 GiB 4.x/vm/wazuh-4.9.2.ova
2024-11-04 15:32:43    6.9 MiB 4.x/windows/wazuh-agent-4.9.2-1.msi
2024-11-04 15:32:44   10.2 MiB 4.x/wpk/linux/deb/amd64/wazuh_agent_v4.9.2_linux_amd64.deb.wpk
2024-11-04 15:33:01   10.3 MiB 4.x/wpk/linux/rpm/x86_64/wazuh_agent_v4.9.2_linux_x86_64.rpm.wpk
2024-11-04 15:33:13    6.5 MiB 4.x/wpk/macos/pkg/intel64/wazuh_agent_v4.9.2_macos_intel64.pkg.wpk
2024-11-04 15:32:44    6.6 MiB 4.x/wpk/windows/wazuh_agent_v4.9.2_windows.wpk
2024-11-04 16:31:04   10.2 MiB 4.x/yum/wazuh-agent-4.9.2-1.aarch64.rpm
2024-11-04 16:31:04    9.5 MiB 4.x/yum/wazuh-agent-4.9.2-1.armv7hl.rpm
2024-11-04 16:31:04   10.9 MiB 4.x/yum/wazuh-agent-4.9.2-1.i386.rpm
2024-11-04 16:31:05   10.4 MiB 4.x/yum/wazuh-agent-4.9.2-1.x86_64.rpm
2024-11-04 16:31:05  252.8 MiB 4.x/yum/wazuh-dashboard-4.9.2-1.x86_64.rpm
2024-11-04 16:31:08  812.6 MiB 4.x/yum/wazuh-indexer-4.9.2-1.x86_64.rpm
2024-11-04 16:31:21  306.9 MiB 4.x/yum/wazuh-manager-4.9.2-1.aarch64.rpm
2024-11-04 16:31:17  314.1 MiB 4.x/yum/wazuh-manager-4.9.2-1.x86_64.rpm
2024-11-04 15:33:39    9.1 MiB 4.x/yum5/i386/wazuh-agent-4.9.2-1.el5.i386.rpm
2024-11-04 15:33:41    8.5 MiB 4.x/yum5/x86_64/wazuh-agent-4.9.2-1.el5.x86_64.rpm
```


</details>

## Deploy the `Wazuh Installation Assistant` and check the version installed is 4.9.2. :green_circle: 

<details><summary>Installation output</summary>

```
[root@centos7 vagrant]# curl -sO https://packages.wazuh.com/4.9/wazuh-install.sh && sudo bash ./wazuh-install.sh -a
04/11/2024 16:17:01 INFO: Starting Wazuh installation assistant. Wazuh version: 4.9.2
04/11/2024 16:17:01 INFO: Verbose logging redirected to /var/log/wazuh-install.log
04/11/2024 16:17:01 INFO: Verifying that your system meets the recommended minimum hardware requirements.
04/11/2024 16:17:01 INFO: Wazuh web interface port will be 443.
04/11/2024 16:17:01 INFO: --- Dependencies ---
04/11/2024 16:17:01 INFO: Installing lsof.
04/11/2024 16:17:08 INFO: Wazuh repository added.
04/11/2024 16:17:08 INFO: --- Configuration files ---
04/11/2024 16:17:08 INFO: Generating configuration files.
04/11/2024 16:17:08 INFO: Generating the root certificate.
04/11/2024 16:17:08 INFO: Generating Admin certificates.
04/11/2024 16:17:08 INFO: Generating Wazuh indexer certificates.
04/11/2024 16:17:08 INFO: Generating Filebeat certificates.
04/11/2024 16:17:08 INFO: Generating Wazuh dashboard certificates.
04/11/2024 16:17:08 INFO: Created wazuh-install-files.tar. It contains the Wazuh cluster key, certificates, and passwords necessary for installation.
04/11/2024 16:17:08 INFO: --- Wazuh indexer ---
04/11/2024 16:17:08 INFO: Starting Wazuh indexer installation.
04/11/2024 16:17:29 INFO: Wazuh indexer installation finished.
04/11/2024 16:17:29 INFO: Wazuh indexer post-install configuration finished.
04/11/2024 16:17:29 INFO: Starting service wazuh-indexer.
04/11/2024 16:17:37 INFO: wazuh-indexer service started.
04/11/2024 16:17:37 INFO: Initializing Wazuh indexer cluster security settings.
04/11/2024 16:17:39 INFO: Wazuh indexer cluster security configuration initialized.
04/11/2024 16:17:39 INFO: Wazuh indexer cluster initialized.
04/11/2024 16:17:39 INFO: --- Wazuh server ---
04/11/2024 16:17:39 INFO: Starting the Wazuh manager installation.
04/11/2024 16:18:10 INFO: Wazuh manager installation finished.
04/11/2024 16:18:10 INFO: Wazuh manager vulnerability detection configuration finished.
04/11/2024 16:18:10 INFO: Starting service wazuh-manager.
04/11/2024 16:18:21 INFO: wazuh-manager service started.
04/11/2024 16:18:21 INFO: Starting Filebeat installation.
04/11/2024 16:18:25 INFO: Filebeat installation finished.
04/11/2024 16:18:26 INFO: Filebeat post-install configuration finished.
04/11/2024 16:18:26 INFO: Starting service filebeat.
04/11/2024 16:18:27 INFO: filebeat service started.
04/11/2024 16:18:27 INFO: --- Wazuh dashboard ---
04/11/2024 16:18:27 INFO: Starting Wazuh dashboard installation.
04/11/2024 16:19:16 INFO: Wazuh dashboard installation finished.
04/11/2024 16:19:17 INFO: Wazuh dashboard post-install configuration finished.
04/11/2024 16:19:17 INFO: Starting service wazuh-dashboard.
04/11/2024 16:19:17 INFO: wazuh-dashboard service started.
04/11/2024 16:19:17 INFO: Updating the internal users.
04/11/2024 16:19:18 INFO: A backup of the internal users has been saved in the /etc/wazuh-indexer/internalusers-backup folder.
04/11/2024 16:19:24 INFO: The filebeat.yml file has been updated to use the Filebeat Keystore username and password.
04/11/2024 16:19:50 INFO: Initializing Wazuh dashboard web application.
04/11/2024 16:19:51 INFO: Wazuh dashboard web application initialized.
04/11/2024 16:19:51 INFO: --- Summary ---
04/11/2024 16:19:51 INFO: You can access the web interface https://<wazuh-dashboard-ip>:443
    User: admin
    Password: u0HJlb+8z7YcPEg54lh6YQd5xuBbP1Sg
04/11/2024 16:19:51 INFO: --- Dependencies ---
04/11/2024 16:19:51 INFO: Removing lsof.
04/11/2024 16:19:52 INFO: Installation finished.
[root@centos7 vagrant]# /var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.9.2"
WAZUH_REVISION="40921"
WAZUH_TYPE="server"
[root@centos7 vagrant]# cat /usr/share/wazuh-indexer/VERSION 
4.9.2
[root@centos7 vagrant]# cat /usr/share/wazuh-dashboard/VERSION 
4.9.2
```

</details>

## AMD64 Live installation test :green_circle: 

- https://ci.wazuh.info/job/Test_install_tier/1034/
  - Known issue: https://github.com/wazuh/wazuh/issues/18179
    - https://ci.wazuh.info/job/Test_install/166977/

## WPK versions check. :green_circle: 

```
╰─➤  cat versions               
v4.9.2 ecb696e810f902df3a5b6d0aebe31296c073c4f9
v4.9.1 6b1738f70a11fa9b0d47981d4ea2afb545c08135
v4.9.0 55050c0c74a097504279972d3f3e5aaf79e33b87
╰─➤  sha1sum wazuh_agent_v4.9.2_linux_amd64.deb.wpk 
ecb696e810f902df3a5b6d0aebe31296c073c4f9  wazuh_agent_v4.9.2_linux_amd64.deb.wpk
```

```
╰─➤  cat versions               
v4.9.2 2a52c44ad5dba3df4ba82d88adea7c27072d8e39
v4.9.1 c802069006579b1b78d53d6630125af39e2e545a
v4.9.0 97da1570a71ab51f1d027acf37c4faff28564b70
╰─➤  sha1sum wazuh_agent_v4.9.2_linux_x86_64.rpm.wpk 
2a52c44ad5dba3df4ba82d88adea7c27072d8e39  wazuh_agent_v4.9.2_linux_x86_64.rpm.wpk
```

```
╰─➤  cat versions               
v4.9.2 bff32987be5ec5f6504cbeae5e8e0f830b3e9886
v4.9.1 0749d386f8c996c6c18ead9f2cac217587ff7f0e
v4.9.0 595046e0fe208a75e5fb679c2b3ce02c90142802
╰─➤  sha1sum wazuh_agent_v4.9.2_macos_intel64.pkg.wpk 
bff32987be5ec5f6504cbeae5e8e0f830b3e9886  wazuh_agent_v4.9.2_macos_intel64.pkg.wpk
```

```
╰─➤  head -6 versions
v4.9.2 6831391321f54d31f408938f39ca61905e225140
v4.9.1 8ddb7fd7674ce9def0b150f7149300437d69b5b4
v4.9.0 e6091d109a5f75ed713097824101c7417e98d5df
v4.8.2 e6a6da9719e930cea210dc0921d26f07503c982a
v4.8.1 c689f81e7a34499e8778f36da7c85456643cdc85
v4.8.0 1d36c13bd4f7d24860e54a2a22f546de36b51b04
╰─➤  sha1sum wazuh_agent_v4.9.2_windows.wpk          
6831391321f54d31f408938f39ca61905e225140  wazuh_agent_v4.9.2_windows.wpk
```


## WPK upgrade test. :green_circle: 

<details><summary>Linux DEB</summary>

```
[root@centos7 vagrant]# /var/ossec/bin/agent_control -i 002

Wazuh agent_control. Agent information:
   Agent ID:   002
   Agent Name: ubuntu20stack
   IP address: any
   Status:     Active

   Operating system:    Linux |ubuntu20stack |5.4.0-169-generic |#187-Ubuntu SMP Thu Nov 23 14:52:28 UTC 2023 |x86_64
   Client version:      Wazuh v4.9.1
   Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
   Shared file hash:    4a8724b20dee0124ff9656783c490c4e
   Last keep alive:     1730738183

   Syscheck last started at:  Mon Nov  4 16:35:03 2024
   Syscheck last ended at:    Mon Nov  4 16:35:05 2024

[root@centos7 vagrant]# /var/ossec/bin/agent_upgrade -a 002

Upgrading...

Upgraded agents:
	Agent 002 upgraded: Wazuh v4.9.1 -> Wazuh v4.9.2
[root@centos7 vagrant]# /var/ossec/bin/agent_control -i 002

Wazuh agent_control. Agent information:
   Agent ID:   002
   Agent Name: ubuntu20stack
   IP address: any
   Status:     Active

   Operating system:    Linux |ubuntu20stack |5.4.0-169-generic |#187-Ubuntu SMP Thu Nov 23 14:52:28 UTC 2023 |x86_64
   Client version:      Wazuh v4.9.2
   Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
   Shared file hash:    4a8724b20dee0124ff9656783c490c4e
   Last keep alive:     1730738286

   Syscheck last started at:  Mon Nov  4 16:37:26 2024
   Syscheck last ended at:    Mon Nov  4 16:37:29 2024
```

```
root@ubuntu20stack:/home/vagrant# /var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.9.1"
WAZUH_REVISION="40914"
WAZUH_TYPE="agent"
root@ubuntu20stack:/home/vagrant# /var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.9.2"
WAZUH_REVISION="40921"
WAZUH_TYPE="agent"

```

</details>

<details><summary>Linux RPM</summary>

```
[root@centos7 vagrant]# /var/ossec/bin/agent_control -i 004

Wazuh agent_control. Agent information:
   Agent ID:   004
   Agent Name: centos8
   IP address: any
   Status:     Active

   Operating system:    Linux |centos8 |4.18.0-240.1.1.el8_3.x86_64 |#1 SMP Thu Nov 19 17:20:08 UTC 2020 |x86_64
   Client version:      Wazuh v4.9.1
   Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
   Shared file hash:    4a8724b20dee0124ff9656783c490c4e
   Last keep alive:     1730738463

   Syscheck last started at:  Mon Nov  4 16:37:14 2024
   Syscheck last ended at:    Mon Nov  4 16:37:16 2024

[root@centos7 vagrant]# /var/ossec/bin/agent_upgrade -a 004

Upgrading...

Upgraded agents:
	Agent 004 upgraded: Wazuh v4.9.1 -> Wazuh v4.9.2
[root@centos7 vagrant]# /var/ossec/bin/agent_control -i 004

Wazuh agent_control. Agent information:
   Agent ID:   004
   Agent Name: centos8
   IP address: any
   Status:     Active

   Operating system:    Linux |centos8 |4.18.0-240.1.1.el8_3.x86_64 |#1 SMP Thu Nov 19 17:20:08 UTC 2020 |x86_64
   Client version:      Wazuh v4.9.2
   Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
   Shared file hash:    4a8724b20dee0124ff9656783c490c4e
   Last keep alive:     1730738613

   Syscheck last started at:  Mon Nov  4 16:42:23 2024
   Syscheck last ended at:    Mon Nov  4 16:42:25 2024
```

```
[root@centos8 vagrant]# /var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.9.1"
WAZUH_REVISION="40914"
WAZUH_TYPE="agent"
[root@centos8 vagrant]# /var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.9.2"
WAZUH_REVISION="40921"
WAZUH_TYPE="agent"

```

</details>

<details><summary>MacOS Intel</summary>

```
[root@centos7 vagrant]# /var/ossec/bin/agent_control -i 003

Wazuh agent_control. Agent information:
   Agent ID:   003
   Agent Name: sierra
   IP address: any
   Status:     Active

   Operating system:    Darwin |sierra |16.7.0 |Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 |x86_64
   Client version:      Wazuh v4.9.1
   Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
   Shared file hash:    4a8724b20dee0124ff9656783c490c4e
   Last keep alive:     1730738307

   Syscheck last started at:  Mon Nov  4 16:35:17 2024
   Syscheck last ended at:    Mon Nov  4 16:35:24 2024

[root@centos7 vagrant]# /var/ossec/bin/agent_upgrade -a 003

Upgrading...

Upgraded agents:
	Agent 003 upgraded: Wazuh v4.9.1 -> Wazuh v4.9.2
[root@centos7 vagrant]# /var/ossec/bin/agent_control -i 003

Wazuh agent_control. Agent information:
   Agent ID:   003
   Agent Name: sierra
   IP address: any
   Status:     Active

   Operating system:    Darwin |sierra |16.7.0 |Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 |x86_64
   Client version:      Wazuh v4.9.2
   Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
   Shared file hash:    4a8724b20dee0124ff9656783c490c4e
   Last keep alive:     1730738404

   Syscheck last started at:  Mon Nov  4 16:39:25 2024
   Syscheck last ended at:    Mon Nov  4 16:39:31 2024

```

```
sh-3.2# /Library/Ossec/bin/wazuh-control info
WAZUH_VERSION="v4.9.1"
WAZUH_REVISION="40914"
WAZUH_TYPE="agent"
sh-3.2# /Library/Ossec/bin/wazuh-control info
WAZUH_VERSION="v4.9.2"
WAZUH_REVISION="40921"
WAZUH_TYPE="agent"
```

</details>

<details><summary>Windows</summary>

```
[root@centos7 vagrant]# /var/ossec/bin/agent_control -i 005

Wazuh agent_control. Agent information:
   Agent ID:   005
   Agent Name: WIN-E1A3KFSBIVE
   IP address: any
   Status:     Active

   Operating system:    Microsoft Windows Server 2016 Datacenter Evaluation
   Client version:      Wazuh v4.9.1
   Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
   Shared file hash:    4a8724b20dee0124ff9656783c490c4e
   Last keep alive:     1730738814

   Syscheck last started at:  Mon Nov  4 16:46:34 2024
   Syscheck last ended at:    Mon Nov  4 16:46:50 2024

[root@centos7 vagrant]# /var/ossec/bin/agent_upgrade -a 005

Upgrading...

Upgraded agents:
	Agent 005 upgraded: Wazuh v4.9.1 -> Wazuh v4.9.2
[root@centos7 vagrant]# /var/ossec/bin/agent_control -i 005

Wazuh agent_control. Agent information:
   Agent ID:   005
   Agent Name: WIN-E1A3KFSBIVE
   IP address: any
   Status:     Active

   Operating system:    Microsoft Windows Server 2016 Datacenter Evaluation
   Client version:      Wazuh v4.9.2
   Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
   Shared file hash:    4a8724b20dee0124ff9656783c490c4e
   Last keep alive:     1730738885

   Syscheck last started at:  Mon Nov  4 16:47:25 2024
   Syscheck last ended at:    Mon Nov  4 16:47:30 2024


```

![image](https://github.com/user-attachments/assets/4528cb45-2bf6-45f5-bd0c-d4e7d0e91690)
![image](https://github.com/user-attachments/assets/7c303dce-b15c-40cc-a1d9-1e49814e8233)


</details>

## Puppet forge module published :green_circle: 

![image](https://github.com/user-attachments/assets/6bad4004-6617-42bc-86c6-4d0a79a1f336)

**Comment by Rebits** [comment]
LGTM
