### ISSUE TITLE
Support new stage Alpha 3 for 4.10.0 in wazuh-qa repository

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-qa#5840]
## Description

This issue attempts to support a new stage Alpha 3 for 4.10.0 in the wazuh-qa repository.

## Tasks

- [x] ~Ensure changelog is updated for 4.10.0 (if applicable).~ the changelog is up to date
- [x] Bump revision for branch 4.10.0 on wazuh-qa repository. https://github.com/wazuh/wazuh-qa/pull/5841
- [x] Create tag v4.10.0-alpha3 from branch 4.10.0 on wazuh-qa repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-qa/releases/tag/v4.10.0-alpha3.
