### ISSUE TITLE
Support new stage Beta 1 for 4.10.0 in wazuh-qa repository

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#5843]
## Description

This issue attempts to support a new stage Beta 1 for 4.10.0 in the wazuh-qa repository.

## Tasks

- [x]  Ensure changelog is updated for 4.10.0 https://github.com/wazuh/wazuh-qa/issues/5843#issuecomment-2497342053
- [x] Bump revision for branch 4.10.0 on wazuh-qa repository. https://github.com/wazuh/wazuh-qa/pull/5844
- [x] Create tag v4.10.0-beta1 from branch 4.10.0 on wazuh-qa repository. https://github.com/wazuh/wazuh-qa/releases/tag/v4.10.0-beta1
- [x] Create and publish a pre-release https://github.com/wazuh/wazuh-qa/releases/tag/v4.10.0-beta1

**Comment by Rebits** [comment]
No changelog is required. Migrated to wazuh-qa-automation. In addition no new developments were merged to 4.10.0 branch
![image](https://github.com/user-attachments/assets/44df32f9-3677-4896-bece-ad3b545d9219)

**Comment by MARCOSD4** [comment]
LGTM
