### ISSUE TITLE
FIM system tests: Reporting Phase

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-qa#585]
### Objective

Create a reporting phase that extracts all required information from the Agents and generates a report about it.

### Tasks

- [x] https://github.com/wazuh/wazuh-qa/issues/586 Evaluate the logging level of the verification scripts and implement any required updates on them

- [x] https://github.com/wazuh/wazuh-qa/issues/588 Create reporting tasks under `/common_tasks` that will extract the Agent status information (results from verifying scripts, files generated count, ossec.log, syscheck config, agentd.state)

- [x] https://github.com/wazuh/wazuh-qa/issues/610 Transfer the agents status summary obtained in the previous reporting step to the master0 Jenkins node so the results can be accessed through the pipeline script.

- [x] https://github.com/wazuh/wazuh-qa/issues/589 Create required tasks to create a report after extracting all the information from the scenario, format and display it in the associated PR

- [ ] https://github.com/wazuh/wazuh-qa/issues/590 Adapt the Jenkins Pipeline with the new tasks and phases

- [x] Review PEP8

### Scheme

Every scenario will contain the list of the Agents, it's results and the generated report, e.g:

#### Scenario 201:

- Ubuntu 14: **PASSED**
- Ubuntu 16: **PASSED**
- Ubuntu 18: **FAILED**
- Ubuntu Centos7: **FAILED**
...

The report will contain the following information:
- For **every agent**:  files generated wc -l, ossec.log, <syscheck> block from ossec.conf, ossec_agentd.state (linux)
- Every **scenario**: , missing_alerts_elasticsearch.txt, log_json_verify.txt, log_elasticsearch_verify.txt, alerts.json, ES index

Result: Failed (when any of the Agent tests are failed, the scenario result is failed)
