### ISSUE TITLE
FIM System Tests: Extract Agent information and tests results

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-qa#588]
### Objective

Create Ansible tasks to extract information about the Wazuh Agent status and the results of the system tests performed on it

### Tasks

Verify and extract the following information from every Agent:

- [x] Results of generating, modify and delete scripts (extract only few lines that resume the execution)

- [x] Results of verifying scripts (extract only few lines that resume the execution)

- [x] `ossec.log` (grep syscheck, warning and errors)

- [x] `<syscheck>` configuration from `ossec.conf`

- [x] `ossec-agentd.state`

- [x] `/etc/ossec-init`

#### Agent state

The tasks on `save_agent_stage.yml` are imported and executed at the end of every scenario. This will create a folder hierarchy on the manager with every scenario/agent relevant state.

`/opt/fim_test_results/<SCENARIO_NAME>/agent_state/<HOSTNAME>/`

![Screenshot_20200323_201246](https://user-images.githubusercontent.com/1380243/77354189-aadb7680-6d42-11ea-995d-2a3c31e6f7bc.png)

#### Final summarize

The playbook `complete_summarize.yml` must be executed from the pipeline itself after all scenarios are completed.

The final summarize file will be located at `/opt/fim_test_results/summary.json`

**Comment by xr09** [comment]
This reporting phase will gather the output from the testing and summarize the relevant data.

The task will read 2 json files, each one containing the output from **verify_alerts_json** and **verify_elastic** tests for all agents on the test.

Sample json file:

```
			202_realtime: {

					172.16.0.161: {
						host_arch: amd64,
						result: OK,
						host_os: Linux,
						expected_alerts: 5010,
						received_alerts: 5010,
						missing_alerts: 0,
						missing_paths: [],
					},
					172.16.0.162: {
						host_arch: amd64,
						result: FAILED,
						host_os: Linux,
						expected_alerts: 5010,
						received_alerts: 5000,
						missing_alerts: 10,
						missing_paths: ["asdf", "asdf"],
					}

					}
```

These two data sources will be parsed, analized and a relevant output will be generated. This output will include related configuration data like errors from `ossec.log` and `syscheck` settings.


Sample output:

```
{
    201_default_configuration: "OK on all agents",
    202_realtime: 
        {
            "Debian 9": "OK",
            "Debian 10": "OK",
            "CentOS 7": "OK",
            "Ubuntu 16.04": {
					result: FAILED,
                    host_arch: amd64,
					host_os: Linux,
					expected_alerts: 5010,
					received_alerts: 5000,
					missing_alerts: 10,
					missing_paths: ["asdf", "asdf"],
                    extra_info: {
                            syscheck_conf: "syscheck section on ossec.conf...",
                            errors_log: "relevant error lines on ossec.log..."
                        }
                },
            "Windows 2012 R2": "OK"
        
        },
    203_whoodata: "OK on all agents",
    ...
}
```


The intention is to provide the most succint piece of information, avoiding verbosity in the passed tests but also providing extra debug data on the failed ones.

**Comment by xr09** [comment]
### Reporting Workflow

#### Summarize actions

This phase will create a summary of the actions (added, delete, modified) by executing `summarize_action.py` from `common_tasks` against each one of the action outputs on `agent_outputs` folder. Results will be stored under `test_results/actions`.


#### Fetch test results from the manager

Next it will fetch the results (json format) from alerts.json and Elastic checks, then store it locally on the scenario folder under `test_results/json`.

#### Summarize scenario

Finally the script `summarize_scenario.py` will take these two json files and create `summary.json` under `test_results`.


This is will be the final state of the `test_tesults` directory.

![Screenshot_20200313_195754](https://user-images.githubusercontent.com/1380243/76651483-ef0d9080-6564-11ea-9a17-a0a9fe1c161e.png)

**Comment by xr09** [comment]
### summary.json

Mockup for the final summary format:

```json
{
    "201":{
        "state":"SUCCESS"
    
},
    "202":{
        "state":"SUCCESS"
    
},
    "203":{
        "state":"FAILED",
        "data":{
            "10.0.0.1":{
                "errors":{
                    "added":{
                        "generated":5000,
                        "received":4500
                    
},
                    "deleted":{
                        "generated":5000,
                        "received":4960
                    
}
                
},
                "info":{
                    "host_os":"windows",
                    "host_release":"2012 R2",
                    "host_arch":"64"
                
}
            
}
        
}
    
},
    "204":{
        "state":"SUCCESS"
    
}
}
```

**Comment by xr09** [comment]
Latest `summary.json` format was updated on the previous comment, today the summarize algorithm was refactored to deliver more complete reports with less code.

The main function iterates over the scenarios and uses `update_scenario` to add or update its status accordingly. In case the status is failed then any related info will be inserted as host metadata.


```python
def update_scenario(scenario, verification, content, results_dict):
    current_dict = deepcopy(results_dict)
    if content['passed']:
        # scenario SUCCESS
        if scenario in current_dict:
            # no need to update scenario results
            return current_dict
        else:
            # create new entry for scenario
            current_dict[scenario] = {'state': 'SUCCESS'}
    else:
        # scenario FAILED
        if scenario in current_dict:
            if current_dict[scenario]['state'] == 'SUCCESS':
                # overwrite with FAILED
                current_dict[scenario]['state'] = 'FAILED'
                current_dict[scenario]['errors'] = {verification: content}
            else:
                # add more FAILED
                current_dict[scenario]['errors'][verification] = content
        else:
            # create new entry with FAILED
            current_dict[scenario] = {'state': 'FAILED'}
            current_dict[scenario]['errors'] = {verification: content}
    return current_dict
```

**Comment by xr09** [comment]
The final_summarize is ready for heavy testing. I'll explain the script logic:


- On every scenario the `save_agent_state` will save the state of all agents to the manager.

- The `complete_summarize` will get executed and parse the output from verify_alerts_json and verify_alerts_elastic.

#### alerts.json

```json
{
  "alerts_json_verification": {
    "passed": true,
    "scenarios": {
      "201_default_scenario": {
        "passed": false,
        "added": {
          "passed": false,
          "hosts": {
            "Windows": {
              "host_os": "windows",
              "host_arch": "...",
              "passed": false,
              "expected_alerts": 5010,
              "received_alerts": 4500,
              "missing_alerts": 510,
              "missing_paths": [
                "path1",
                "path2"
              ]
            },
            "Centos": {
              "host_os": "ubuntu",
              "host_arch": "debian",
              "passed": false,
              "expected_alerts": 5010,
              "received_alerts": 4500,
              "missing_alerts": 510,
              "missing_paths": [
                "path1",
                "path2"
              ]
            }
          }
        }
      },
      "203_whodata_frequency": {
        "passed": true,
        "added": {
          "passed": true,
          "hosts": {
            "Centos": {
              "host_os": "ubuntu",
              "host_arch": "debian",
              "passed": true,
              "expected_alerts": 5010,
              "received_alerts": 5010,
              "missing_alerts": 0,
              "missing_paths": []
            }
          }
        }
      }
    }
  }
}
```

#### Elasticsearch:

```json
{
  "alert_elasticsearch_verification": {
    "passed": true,
    "scenarios": {
      "201_default_scenario": {
        "passed": false,
        "added": {
          "passed": false,
          "hosts": {
            "Windows": {
              "host_os": "windows",
              "host_arch": "64",
              "passed": false,
              "expected_alerts": 5010,
              "received_alerts": 4500,
              "missing_alerts": 510,
              "missing_paths": [
                "path1",
                "path2"
              ]
            },
            "Centos": {
              "host_os": "ubuntu",
              "host_arch": "64",
              "passed": false,
              "expected_alerts": 5010,
              "received_alerts": 4500,
              "missing_alerts": 510,
              "missing_paths": [
                "path1",
                "path2"
              ]
            }
          }
        }
      },
      "203_whodata_frequency": {
        "passed": true,
        "added": {
          "passed": true,
          "hosts": {
            "Centos": {
              "host_os": "ubuntu",
              "host_arch": "64",
              "passed": true,
              "expected_alerts": 5010,
              "received_alerts": 5010,
              "missing_alerts": 0,
              "missing_paths": []
            }
          }
        }
      }
    }
  }
}
```



#### Summary 

This is the corresponding summary:

```json
{
  "209_recursion_level": {
    "state": "FAILED",
    "errors": {
      "json": {
        "passed": false,
        "added": {
          "passed": false,
          "hosts": {
            "dc1": {
              "host_os": "windows",
              "host_arch": "...",
              "passed": false,
              "expected_alerts": 5010,
              "received_alerts": 4500,
              "missing_alerts": 510,
              "missing_paths": [
                "path1",
                "path2"
              ],
              "ossec_log": [
                "2020/03/13 13:43:57 agent-auth: WARNING: Registering agent to unverified manager.\n",
                "2020/03/13 13:44:13 ossec-agent: WARNING: The check_winaudit option is deprecated in favor of the SCA module.\n",
                "2020/03/13 13:44:14 ossec-agent: WARNING: The check_winaudit option is deprecated in favor of the SCA module.\n",
                "2020/03/13 13:56:07 ossec-agent: ERROR: (1137): Lost connection with manager. Setting lock.\n",
                "2020/03/13 13:56:08 ossec-agent: WARNING: Process locked due to agent is offline. Waiting for connection...\n",
                "2020/03/13 13:56:08 ossec-agent: ERROR: (1218): Unable to send message to 'server': An established connection was aborted by the software in your host machine.\n",
                "2020/03/13 13:56:11 ossec-agent: ERROR: (1218): Unable to send message to 'server': An established connection was aborted by the software in your host machine.\n",
                "2020/03/13 13:56:17 ossec-agent: ERROR: (1216): Unable to connect to '172.16.0.111': 'No connection could be made because the target machine actively refused it.'.\n",
                "2020/03/13 13:56:27 ossec-agent: WARNING: Process locked due to agent is offline. Waiting for connection...\n",
                "2020/03/13 13:56:28 ossec-agent: WARNING: Process locked due to agent is offline. Waiting for connection...\n",
                "2020/03/13 13:56:28 ossec-agent: ERROR: (1216): Unable to connect to '172.16.0.111': 'No connection could be made because the target machine actively refused it.'.\n",
                "2020/03/13 14:24:59 ossec-agent: WARNING: At get_user(c:\\fim_testing\\lhdoi\\wqjmrxfp): CreateFile(): The system cannot find the file specified. (2)\n",
                "2020/03/13 18:35:21 ossec-agent: ERROR: Could not get message for (rationale)\n",
                "2020/03/13 20:18:42 ossec-agent: WARNING: The eventlog service is down. Unable to collect logs from '255.255.255.0' channel.\n",
                "2020/03/13 20:18:42 ossec-agent: WARNING: The eventlog service is down. Unable to collect logs from 'process' channel.\n",
                "2020/03/13 20:18:42 ossec-agent: WARNING: The eventlog service is down. Unable to collect logs from 'rationale' channel.\n",
                "2020/03/16 12:57:45 ossec-agent: ERROR: Could not get message for (remediation)\n",
                "2020/03/16 13:06:39 ossec-agent: ERROR: Could not get message for (remediation)\n",
                "2020/03/16 18:35:46 ossec-agent: ERROR: Could not get message for (remediation)\n",
                "2020/03/16 21:08:27 ossec-agent: WARNING: The eventlog service is down. Unable to collect logs from 'rationale' channel.\n",
                "2020/03/16 21:08:27 ossec-agent: ERROR: Could not get message for (remediation)\n",
                "2020/03/16 21:08:27 ossec-agent: WARNING: The eventlog service is down. Unable to collect logs from '14005' channel.\n",
                "2020/03/16 21:08:27 ossec-agent: WARNING: The eventlog service is down. Unable to collect logs from 'remediation' channel.\n",
                "2020/03/17 11:02:53 ossec-agent: ERROR: Could not get message for (rationale)\n",
                "2020/03/17 11:11:37 ossec-agent: ERROR: Could not get message for (rationale)\n",
                "2020/03/17 16:35:31 ossec-agent: ERROR: Could not get message for (rationale)\n",
                "2020/03/17 21:17:22 ossec-agent: WARNING: The eventlog service is down. Unable to collect logs from 'rationale' channel.\n",
                "2020/03/17 21:17:22 ossec-agent: WARNING: The eventlog service is down. Unable to collect logs from 'description' channel.\n",
                "2020/03/17 21:17:23 ossec-agent: ERROR: Could not get message for (cis_csc)\n",
                "2020/03/17 21:17:23 ossec-agent: WARNING: The eventlog service is down. Unable to collect logs from 'cis_csc' channel.\n",
                "2020/03/18 10:47:38 ossec-agent: WARNING: (4101): Waiting for server reply (not started). Tried: '172.16.0.111'.\n",
                "2020/03/18 10:49:17 ossec-agent: ERROR: Could not get message for (rationale)\n",
                "2020/03/18 10:57:17 ossec-agent: ERROR: Could not get message for (rationale)\n",
                "2020/03/18 16:35:43 ossec-agent: ERROR: Could not get message for (rationale)\n",
                "2020/03/18 20:51:15 ossec-agent: WARNING: The eventlog service is down. Unable to collect logs from 'rationale' channel.\n",
                "2020/03/18 20:51:15 ossec-agent: WARNING: The eventlog service is down. Unable to collect logs from 'ID' channel.\n",
                "2020/03/18 20:51:15 ossec-agent: WARNING: The eventlog service is down. Unable to collect logs from '255.255.255.0' channel.\n",
                "2020/03/19 09:30:14 ossec-agent: ERROR: Could not get message for (remediation)\n",
                "2020/03/19 09:35:17 ossec-agent: ERROR: Could not get message for (remediation)\n",
                "2020/03/19 14:35:11 ossec-agent: ERROR: Could not get message for (remediation)\n",
                "2020/03/19 19:35:35 ossec-agent: ERROR: Could not get message for (remediation)\n",
                "2020/03/19 20:37:05 ossec-agent: WARNING: The eventlog service is down. Unable to collect logs from 'remediation' channel.\n",
                "2020/03/19 20:37:05 ossec-agent: ERROR: Could not get message for (process)\n",
                "2020/03/19 20:37:05 ossec-agent: WARNING: The eventlog service is down. Unable to collect logs from 'rationale' channel.\n",
                "2020/03/19 20:37:05 ossec-agent: WARNING: The eventlog service is down. Unable to collect logs from 'process' channel.\n",
                "ERROR: line .....\n",
                "ERROR: line .....\n",
                "ERROR: line .....\n",
                "ERROR: line .....\n"
              ]
            },
            "Centos": {
              "host_os": "ubuntu",
              "host_arch": "debian",
              "passed": false,
              "expected_alerts": 5010,
              "received_alerts": 4500,
              "missing_alerts": 510,
              "missing_paths": [
                "path1",
                "path2"
              ],
              "ossec_log": [
                "ERROR: line .....\n",
                "ERROR: line .....\n",
                "ERROR: line .....\n",
                "ERROR: line .....\n"
              ]
            }
          }
        }
      },
      "elasticsearch": {
        "passed": false,
        "added": {
          "passed": false,
          "hosts": {
            "Windows": {
              "host_os": "windows",
              "host_arch": "64",
              "passed": false,
              "expected_alerts": 5010,
              "received_alerts": 4500,
              "missing_alerts": 510,
              "missing_paths": [
                "path1",
                "path2"
              ],
              "ossec_log": [
                "2020/03/13 13:43:57 agent-auth: WARNING: Registering agent to unverified manager.\n",
                "2020/03/13 13:44:13 ossec-agent: WARNING: The check_winaudit option is deprecated in favor of the SCA module.\n",
                "2020/03/13 13:44:14 ossec-agent: WARNING: The check_winaudit option is deprecated in favor of the SCA module.\n",
                "2020/03/13 13:56:07 ossec-agent: ERROR: (1137): Lost connection with manager. Setting lock.\n",
                "2020/03/13 13:56:08 ossec-agent: WARNING: Process locked due to agent is offline. Waiting for connection...\n",
                "2020/03/13 13:56:08 ossec-agent: ERROR: (1218): Unable to send message to 'server': An established connection was aborted by the software in your host machine.\n",
                "2020/03/13 13:56:11 ossec-agent: ERROR: (1218): Unable to send message to 'server': An established connection was aborted by the software in your host machine.\n",
                "2020/03/13 13:56:17 ossec-agent: ERROR: (1216): Unable to connect to '172.16.0.111': 'No connection could be made because the target machine actively refused it.'.\n",
                "2020/03/13 13:56:27 ossec-agent: WARNING: Process locked due to agent is offline. Waiting for connection...\n",
                "2020/03/13 13:56:28 ossec-agent: WARNING: Process locked due to agent is offline. Waiting for connection...\n",
                "2020/03/13 13:56:28 ossec-agent: ERROR: (1216): Unable to connect to '172.16.0.111': 'No connection could be made because the target machine actively refused it.'.\n",
                "2020/03/13 14:24:59 ossec-agent: WARNING: At get_user(c:\\fim_testing\\lhdoi\\wqjmrxfp): CreateFile(): The system cannot find the file specified. (2)\n",
                "2020/03/13 18:35:21 ossec-agent: ERROR: Could not get message for (rationale)\n",
                "2020/03/13 20:18:42 ossec-agent: WARNING: The eventlog service is down. Unable to collect logs from '255.255.255.0' channel.\n",
                "2020/03/13 20:18:42 ossec-agent: WARNING: The eventlog service is down. Unable to collect logs from 'process' channel.\n",
                "2020/03/13 20:18:42 ossec-agent: WARNING: The eventlog service is down. Unable to collect logs from 'rationale' channel.\n",
                "2020/03/16 12:57:45 ossec-agent: ERROR: Could not get message for (remediation)\n",
                "2020/03/16 13:06:39 ossec-agent: ERROR: Could not get message for (remediation)\n",
                "2020/03/16 18:35:46 ossec-agent: ERROR: Could not get message for (remediation)\n",
                "2020/03/16 21:08:27 ossec-agent: WARNING: The eventlog service is down. Unable to collect logs from 'rationale' channel.\n",
                "2020/03/16 21:08:27 ossec-agent: ERROR: Could not get message for (remediation)\n",
                "2020/03/16 21:08:27 ossec-agent: WARNING: The eventlog service is down. Unable to collect logs from '14005' channel.\n",
                "2020/03/16 21:08:27 ossec-agent: WARNING: The eventlog service is down. Unable to collect logs from 'remediation' channel.\n",
                "2020/03/17 11:02:53 ossec-agent: ERROR: Could not get message for (rationale)\n",
                "2020/03/17 11:11:37 ossec-agent: ERROR: Could not get message for (rationale)\n",
                "2020/03/17 16:35:31 ossec-agent: ERROR: Could not get message for (rationale)\n",
                "2020/03/17 21:17:22 ossec-agent: WARNING: The eventlog service is down. Unable to collect logs from 'rationale' channel.\n",
                "2020/03/17 21:17:22 ossec-agent: WARNING: The eventlog service is down. Unable to collect logs from 'description' channel.\n",
                "2020/03/17 21:17:23 ossec-agent: ERROR: Could not get message for (cis_csc)\n",
                "2020/03/17 21:17:23 ossec-agent: WARNING: The eventlog service is down. Unable to collect logs from 'cis_csc' channel.\n",
                "2020/03/18 10:47:38 ossec-agent: WARNING: (4101): Waiting for server reply (not started). Tried: '172.16.0.111'.\n",
                "2020/03/18 10:49:17 ossec-agent: ERROR: Could not get message for (rationale)\n",
                "2020/03/18 10:57:17 ossec-agent: ERROR: Could not get message for (rationale)\n",
                "2020/03/18 16:35:43 ossec-agent: ERROR: Could not get message for (rationale)\n",
                "2020/03/18 20:51:15 ossec-agent: WARNING: The eventlog service is down. Unable to collect logs from 'rationale' channel.\n",
                "2020/03/18 20:51:15 ossec-agent: WARNING: The eventlog service is down. Unable to collect logs from 'ID' channel.\n",
                "2020/03/18 20:51:15 ossec-agent: WARNING: The eventlog service is down. Unable to collect logs from '255.255.255.0' channel.\n",
                "2020/03/19 09:30:14 ossec-agent: ERROR: Could not get message for (remediation)\n",
                "2020/03/19 09:35:17 ossec-agent: ERROR: Could not get message for (remediation)\n",
                "2020/03/19 14:35:11 ossec-agent: ERROR: Could not get message for (remediation)\n",
                "2020/03/19 19:35:35 ossec-agent: ERROR: Could not get message for (remediation)\n",
                "2020/03/19 20:37:05 ossec-agent: WARNING: The eventlog service is down. Unable to collect logs from 'remediation' channel.\n",
                "2020/03/19 20:37:05 ossec-agent: ERROR: Could not get message for (process)\n",
                "2020/03/19 20:37:05 ossec-agent: WARNING: The eventlog service is down. Unable to collect logs from 'rationale' channel.\n",
                "2020/03/19 20:37:05 ossec-agent: WARNING: The eventlog service is down. Unable to collect logs from 'process' channel.\n",
                "ERROR: line .....\n",
                "ERROR: line .....\n",
                "ERROR: line .....\n",
                "ERROR: line .....\n"
              ]
            },
            "Centos": {
              "host_os": "ubuntu",
              "host_arch": "64",
              "passed": false,
              "expected_alerts": 5010,
              "received_alerts": 4500,
              "missing_alerts": 510,
              "missing_paths": [
                "path1",
                "path2"
              ],
              "ossec_log": [
                "ERROR: line .....\n",
                "ERROR: line .....\n",
                "ERROR: line .....\n",
                "ERROR: line .....\n"
              ]
            }
          }
        }
      }
    }
  },
  "203_whodata_frequency": {
    "state": "SUCCESS"
  }
}
```
