### ISSUE TITLE
FIM System Tests: Create report and comment on the associated PR

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-qa#589]
### Objective

Create a report with the extracted information from the System tests, format it and comment on the associated PR using Github API

### Description 

Related branchs:
- The related **wazuh-jenkins** branch for this issue is [qa589-system-tests-reporting](https://github.com/wazuh/wazuh-jenkins/tree/qa589-system-tests-reporting)
- The related **wazuh-qa** branch for this issue is [feature-610-transfer-status](https://github.com/wazuh/wazuh-qa/tree/feature-610-transfer-status)

Related Issues/PRs:

- Dummy **wazuh/wazuh** issue and PR for debugging purposes:
    - issue: https://github.com/wazuh/wazuh/issues/4788
    - PR: https://github.com/wazuh/wazuh/pull/4789
- Related Jenkins pipeline: `Test_system_reporting`

Related draft PR: 

- https://github.com/wazuh/wazuh-qa/pull/613

### Tasks

- [x] Format the data to avoid flooding (grep Warnings, Errors, etc... from logs)

- [x] Implement formatting changes like titles, bolds, etc...

- [x] Use Github API to report all data in the related Pull Request

**Comment by Zenidd** [comment]
Hi team,

- The scenarios applicable to a triggered test appear in the report comment and are linked to their description in the FIM system test wiki.
- The commit ID is also included in the report.
- Example report:
![image](https://user-images.githubusercontent.com/14923294/76883763-ee367080-687c-11ea-9971-76e9e4968919.png)

**Comment by Zenidd** [comment]
Three different approaches for the final reporting:
- https://github.com/wazuh/wazuh-qa/pull/596#issuecomment-600560455 (Plain text)
- https://github.com/wazuh/wazuh-qa/pull/596#issuecomment-600569061 (Mixed)
- https://github.com/wazuh/wazuh-qa/pull/596#issuecomment-600574292 (JSON approach)

**Comment by Zenidd** [comment]
### Status update

- The first reporting phase iteration is finished. An example of the current report format is available [here](https://github.com/wazuh/wazuh/pull/4789#issuecomment-607897865).
- The commit regarding the PR, the agent's list and a detailed collapsable scenarios summary is is included in the report comment. 

Current reporting status example:
![image](https://user-images.githubusercontent.com/14923294/78264899-0a384400-7504-11ea-9593-76bdb50cb3a0.png)

Greetings, JP Sáez

**Comment by jm404** [comment]
Done in #613
