### ISSUE TITLE
FIM System Tests: Adapt the Jenkins Pipeline with the new tasks and phases

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-qa#590]
### Objective

Implement the reporting phases on Jenkins

### Tasks

- [ ] Create required phases to launch the system tests information gathering

- [ ] Launch the playbook that reports to GitHub ensuring the credentials are properly managed

- [ ] Test the whole pipeline by launching it x times

**Comment by manuasir** [comment]
We're not using Jenkins any longer, probably GitHub actions will be chosen for this kind of task.
