### ISSUE TITLE
FIM System tests: Agent status information transfer

### ISSUE THREAD

**Issue by Zenidd** [wazuh/wazuh-qa#610]
### Objective

Transfer the agents status summary obtained in the previous reporting step to the master0 Jenkins node so this data can be accessed through the pipeline script.

### Description

Related branchs:
- The related **wazuh-jenkins** branch for this issue is [qa589-system-tests-reporting](https://github.com/wazuh/wazuh-jenkins/tree/qa589-system-tests-reporting)
- The related **wazuh-qa** branch for this issue is [feature-610-transfer-status](https://github.com/wazuh/wazuh-qa/tree/feature-610-transfer-status)

Related draft PR: 

- https://github.com/wazuh/wazuh-qa/pull/613

### Tasks

- [x] Create Playbook to gather the needed files
- [x] Set eligibility of each agent summary
- [x] Destroy the gathered files

**Comment by Zenidd** [comment]
### Update

- The playbook to gather the summary data is ready:

```yaml
---
  - hosts: all
    tasks:
      - name: Get agents status from manager node
        become: true
        synchronize:
          mode: pull
          src: /opt/fim_testing
          dest: ./agents_status
        when:
          - inventory_hostname in groups['masters'] 
```

-  Further tests and changes will be performed as soon as the summary data is reachable on the manager node.
