### ISSUE TITLE
Include integration tests for Google Cloud: Pub/Sub integration

### ISSUE THREAD

**Issue by danimegar** [wazuh/wazuh-qa#619]
| Version | Revision | Branch | Related issue |
| --- | --- | --- | --- |
| 3.12.0 | 1 | [4015-gcp-integration](https://github.com/wazuh/wazuh/tree/4015-gcp-integration) | /wazuh/wazuh#4015

## Description
This module allows Wazuh to pull logs from Google Cloud Pub/Sub. It will be wodle based similar to what it already has with AWS.

## Configuration settings
- `project_id`: _String_. Google Cloud Project ID (name, not number). Required.
- `subscription_name`: _String_. Name of the subscription to read from. Required.
- `credentials_file`: _String_. The path to the Google Cloud credentials file. JWT Tokens. It must allow both relative (to $HOME_INSTALLATION) and absolute paths. Required.
- `interval`: _String_. The amount of time between each pull. Default: 1h. (It must allow the format: 1h, 1d, 20m, 1405s). 
- `max_messages`: _Integer_. The number of maximum messages pulled in each iteration. Default: 100.
- `enabled`: _String_. Enable or disabled the module. Values: yes/no.
- `pull_on_start`: _String_. Trigger the pulling in case of an agent start or restart. Values: yes/no. Default: yes.
- `logging`: _String_. Toggle between the different logging levels. Values: disabled/info/debug/error/critical. Default: info.

This is a configuration example:
```
<gcp-pubsub>
  <enabled>yes</enabled>
  <pull_on_start>yes</pull_on_start>
  <interval>1h</interval>
  <max_messages>100</max_messages>
  <project_id>wazuh-dev</project_id>
  <subscription_name>wazuhdns</subscription_name>
  <credentials_file>credentials.json</credentials_file>
  <logging>info</logging>
</gcp-pubsub>
```
This configuration has to be added to ossec.conf file (Manager or agent). Windows agent are not able to have this configuration.

Also, there are more three options that can be added to the configuration:
`day`, `wday` and `time` tags

Requirements for these three options:
- `day` and `wday` cannot be together as options.
- If `day` tag is used, the interval must be a multiple of one month: (1M, 2M...).
- If `wday` tag is used, the interval must be a multiple of one week: (1w, 2w, ...).
- if `time` tag is used, the interval must be a multiple of one day: (1d, 2d, ...).

## Integration Tests
- [x] max messages test #616 
- [x] logging test #617 
- [x] pull on start test #618 
- [x] rules test
- [x] invalid values test #614 
- [x] schedule test #615
