### ISSUE TITLE
FIM System tests Wiki: Iteration 2

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-qa#633]
###  Objective

The aim of this issue is to create the FIM service tests Wiki. 

### Description

The goal of FIM service tests wiki is to gather, unify and summarize all the needed testing processes. It will contain the methodology, specifications, desired workflow, and serializations to be applied in the context of the FIM service tests.

The wiki will allow better coordination between the implied teams, more readable and easily reproducible service tests.

### Tasks

- [ ] Tests scope and objectives 
- [ ] Test workflow explanation and diagram
- [ ] Serialization system for test scenarios
- [ ] Steps to set the test environment
