### ISSUE TITLE
Add interval to vulnerability detector integration tests 

### ISSUE THREAD

**Issue by grg121** [wazuh/wazuh-qa#667]
# Vulnerability detector

| Version | Revision |
| --- | --- |
| v3.12.3| 31208 |

## Tasks Summary
- [x] Test interval with seconds suffix
- [x] Test interval with minutes suffix 
- [x] Test interval with houres suffix
- [x] Test interval with days suffix

## Test Interval parameter.

**Short description**

Once a scan is completed, the module should wait the **interval** time until running the next one.

This parameter is a positive number that should contain a suffix character indicating a time unit: s (seconds), m (minutes), h (hours) or d (days).

**Category**

Vulnerability-detector

**Subcategory**

General settings

**Description**
Integration test for interval general parameter of VD. 

Using 
```
$> cat /var/ossec/logs/ossec.log | grep "wm_vuldet_run_scan(): INFO
2020/04/23 13:58:15 wazuh-modulesd:vulnerability-detector[9012] wm_vuln_detector.c:5175 at wm_vuldet_run_scan(): INFO: (5452): Starting vulnerability scanning.
2020/04/23 13:58:18 wazuh-modulesd:vulnerability-detector[9012] wm_vuln_detector.c:5183 at wm_vuldet_run_scan(): INFO: (5453): Vulnerability scanning finished.
2020/04/23 14:03:19 wazuh-modulesd:vulnerability-detector[9012] wm_vuln_detector.c:5175 at wm_vuldet_run_scan(): INFO: (5452): Starting vulnerability scanning.
2020/04/23 14:03:20 wazuh-modulesd:vulnerability-detector[9012] wm_vuln_detector.c:5183 at wm_vuldet_run_scan(): INFO: (5453): Vulnerability scanning finished.
2020/04/23 14:08:21 wazuh-modulesd:vulnerability-detector[9012] wm_vuln_detector.c:5175 at wm_vuldet_run_scan(): INFO: (5452): Starting vulnerability scanning.
2020/04/23 14:08:23 wazuh-modulesd:vulnerability-detector[9012] wm_vuln_detector.c:5183 at wm_vuldet_run_scan(): INFO: (5453): Vulnerability scanning finished.
2020/04/23 14:13:24 wazuh-modulesd:vulnerability-detector[9012] wm_vuln_detector.c:5175 at wm_vuldet_run_scan(): INFO: (5452): Starting vulnerability scanning.
2020/04/23 14:13:26 wazuh-modulesd:vulnerability-detector[9012] wm_vuln_detector.c:5183 at wm_vuldet_run_scan(): INFO: (5453): Vulnerability scanning finished.
```

We will mesure the interval required by vulnerability detector.

**Comment by BraulioV** [comment]
Related issue #660
