### ISSUE TITLE
Automated tests for Syscheck

### ISSUE THREAD

**Issue by Cerv1** [wazuh/wazuh-qa#7]
## Description

We need to automate integration tests in order to guarantee that `syscheckd` behaves like expected. These tests will be written from a 'black box' perspective trying to simulate the interaction with a user. A special effort will be done to test limit and non common cases in addition to the basic functionality.

Stress or service tests are out of the scope and will be faced later in a different issue.

## Branch

The main development branch is https://github.com/wazuh/wazuh-qa/tree/fim-integration-tests. All finished work will be merge in this branch before the final merge into `master`.

## Implementation

All integration tests will be written using `pytest`. Avoiding repeating code is a must. To achieve this, a new Python package will support new tests with the following skeleton:
- wazuh_testing
  - tools.py: module with generic tools such as log parsing and file handling
  - fim.py: specific utilities to test syscheck module
  - data: auxiliary static data, such as a json schema for syscheck events

## Subtasks

The features to be tested will be faced from the most basic to the most complex. The important thing here is preserving the good sense and organization of the code, so the testing framework scale as much as needed.

The following subtasks are proposed:
- [x] Framework foundations to write tests easier and avoid repeating code (#152)
- Check basic configurations (including scheduled, whodata, realtime). Intended to test how `syscheckd` works in a simple environment (a single manager or a single agent) playing with one parameter simultaneously:
  - Linux
    - [x] Check events are generated with minimal configurations (#147)
    - [x] Check `ignore` parameter (#145 )
    - [x] Check `recursion_level` parameter (#146 )
    - [x] Check `check_*` parameters (#149)
    - [x] Check `report_changes` parameter (#150)
    - [x] Check `tags` parameter (#148)
    - [x] Check `restrict` parameter (#164)
    - [ ] Check `follow_symbolic_link` parameter
    - [x] Check `nodiff` parameter (#166)
    - [x] Check `scan_*` parameter (#167)
    - [x] ~Check `auto_ignore` parameter~
    - [x] ~Check `alert_new_files` parameter~
    - [x] Check `prefilter_cmd` parameter (#171)
    - [x] Check `skip_nfs` parameter
    - [x] Check `whodata` options (#173)
    - [x] Check `sync_interval` and `response_timeout` (#174)
  - Windows:
    - [x] Check events are generated with minimal configurations
    - [x] Check `ignore` parameter
    - [x] Check `recursion_level` parameter
    - [x] Check `check_*` parameters
    - [x] Check `report_changes` parameter
    - [x] Check `tags` parameter
    - [x] Check `restrict` parameter
    - [ ] Check `follow_symbolic_link` parameter
    - [x] Check `nodiff` parameter
    - [x] Check `scan_*` parameter
    - [ ] ~Check `auto_ignore` parameter~
    - [ ] ~Check `alert_new_files` parameter~
    - [x] Check `windows_registry` and `registry_ignore` parameters (only Windows)
    - [ ] ~Check `prefilter_cmd` parameter~
    - [ ] ~Check `skip_nfs` parameter~
    - [x] Check `windows_audit_interval` (only Windows)
    - [x] Check `whodata` options
    - [ ] ~Check `sync_interval` and `response_timeout`~
  - Mac:
    - [x] Check events are generated with minimal configurations
    - [x] Check `ignore` parameter
    - [x] Check `recursion_level` parameter
    - [x] Check `check_*` parameters
    - [x] Check `report_changes` parameter
    - [x] Check `tags` parameter
    - [x] Check `restrict` parameter
    - [x] Check `follow_symbolic_link` parameter
    - [x] Check `nodiff` parameter
    - [x] Check `scan_*` parameter
    - [ ] ~Check `auto_ignore` parameter~
    - [ ] ~Check `alert_new_files` parameter~
    - [x] Check `prefilter_cmd` parameter
    - [x] Check `skip_nfs` parameter
    - [x] Check `whodata` options
    - [x] Check `sync_interval` and `response_timeout`
- Check advanced configurations (including scheduled, whodata, realtime). Intended to test how `syscheckd` works in a simple environment (a single manager or a single agent) playing with several parameter simultaneously:
  - All basic configurations must be tested before studying the advanced ones.
