### ISSUE TITLE
JWT tests for the Wazuh API in 4.0

### ISSUE THREAD

**Issue by vicferpoy** [wazuh/wazuh-qa#739]
# Summary

Since we are using JWT in the new API (`4.0`) as the main security mechanism, we need a solid test environment to assure everything is working as intended.

Token related information will be stored in the RBAC database in order to invalidate non-expired ones when changing roles or policies from the system.

We need to test every possible case where these tokens will be invalidated.

# Design

We need an environment with a functional cluster. To achieve this, we could use **Ansible** as the orchestrator, since we will have to run different commands on different nodes at the same time.

We could adapt the environment from the **agent key-polling** tests: https://github.com/wazuh/wazuh-qa/tree/master/tests/system

For this case, we only need a cluster with:
- 1 master node
- 2 worker nodes

No agents are needed to test this.

# Tasks

- [ ] Create a **new environment** for these tests adapting the agent key-polling one. 

## Test cases (WIP)

- [ ] Check that an existing token is revoked when **updating the password** from the user that requested it.

- [ ] Check that an existing token is revoked when **changing roles** related to the user that requested it.

- [ ] Check that an existing token is revoked when **changing policies** related to the user that requested it.

**Comment by vicferpoy** [comment]
| Working branch |
| --- |
|[739-jwt-invalidation-tests](https://github.com/wazuh/wazuh-qa/tree/739-jwt-invalidation-tests)|

**Comment by vicferpoy** [comment]
# Status update
The new environment is finished.

```PLAY RECAP ********************************************************************************************************************************************************************************************************
localhost                  : ok=7    changed=3    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
wazuh-master               : ok=9    changed=8    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
wazuh-worker1              : ok=10   changed=9    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
wazuh-worker2              : ok=10   changed=9    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

Thursday 28 May 2020  12:56:35 +0200 (0:00:13.763)       0:11:02.602 ********** 
=============================================================================== 
roles/worker-role : Install worker ----------------------------------------------------------------------------------------------------------------------------------------------------------------------- 170.89s
roles/master-role : Install master ----------------------------------------------------------------------------------------------------------------------------------------------------------------------- 160.62s
roles/worker-role : Install worker ----------------------------------------------------------------------------------------------------------------------------------------------------------------------- 155.58s
roles/worker-role : Clone wazuh repository ---------------------------------------------------------------------------------------------------------------------------------------------------------------- 18.02s
roles/worker-role : Clone wazuh repository ---------------------------------------------------------------------------------------------------------------------------------------------------------------- 17.93s
roles/master-role : Clone wazuh repository ---------------------------------------------------------------------------------------------------------------------------------------------------------------- 17.71s
roles/master-role : Restart Wazuh ------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 14.45s
roles/worker-role : Restart Wazuh ------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 14.18s
roles/worker-role : Restart Wazuh ------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 13.76s
roles/worker-role : Installing dependencies using apt ------------------------------------------------------------------------------------------------------------------------------------------------------ 9.95s
roles/worker-role : Installing dependencies using apt ------------------------------------------------------------------------------------------------------------------------------------------------------ 9.40s
roles/master-role : Installing dependencies using apt ------------------------------------------------------------------------------------------------------------------------------------------------------ 8.15s
Gathering Facts -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 6.02s
Gathering Facts -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 6.01s
Gathering Facts -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 5.99s
roles/worker-role : Copy ossec.conf file ------------------------------------------------------------------------------------------------------------------------------------------------------------------- 4.21s
roles/worker-role : Copy ossec.conf file ------------------------------------------------------------------------------------------------------------------------------------------------------------------- 4.04s
roles/master-role : Copy ossec.conf file ------------------------------------------------------------------------------------------------------------------------------------------------------------------- 4.04s
Gathering Facts -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 1.69s
roles/worker-role : Set cluster key ------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 1.48s
Playbook run took 0 days, 0 hours, 11 minutes, 2 seconds
```

## Pending
- Testing framework
- Tests

**Comment by vicferpoy** [comment]
# Status update
- Test environment has been improved with the addition of port forwarding to make debugging easier (each API is the port 55010, 55011 and 55012 respectively)
- `body_request` argument has been added to `make_api_call` function. We can now pass data to the API call in JSON format. 
- The first test helped us find a bug with `PUT /security/user/revoke`. It is fixed now.

```
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.8.2, pytest-5.4.2, py-1.8.1, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/vicferpoy/Desktop/Git/wazuh-qa/tests/system
plugins: testinfra-5.0.0, tavern-1.0.0
collected 3 items                                                                                                                                                                                                 

test_jwt_invalidation/test_jwt_revoke_endpoint/test_revoke_endpoint.py::test_revoke_all_tokens_with_api[wazuh-master] PASSED                                                                                [ 33%]
test_jwt_invalidation/test_jwt_revoke_endpoint/test_revoke_endpoint.py::test_revoke_all_tokens_with_api[wazuh-worker1] PASSED                                                                               [ 66%]
test_jwt_invalidation/test_jwt_revoke_endpoint/test_revoke_endpoint.py::test_revoke_all_tokens_with_api[wazuh-worker2] PASSED                                                                               [100%]

========================================================================================== 3 passed in 62.65s (0:01:02) ===========================================================================================
```

## Pending
- Tests

**Comment by vicferpoy** [comment]
# Status update
Development is finished. Unless the team finds new test cases, this issue is done.

## Tests performed
```
================================================================================== test session starts ==================================================================================
platform linux -- Python 3.8.2, pytest-5.4.2, py-1.8.1, pluggy-0.13.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/vicferpoy/Desktop/Git/wazuh-qa/tests/system
plugins: asyncio-0.12.0, testinfra-5.0.0, tavern-1.0.0
collected 8 items                                                                                                                                                                       

test_jwt_invalidation/test_change_policy_and_role.py::test_change_user_policy_and_role[wazuh-master-wazuh-worker1] PASSED                                                         [ 12%]
test_jwt_invalidation/test_change_policy_and_role.py::test_change_user_policy_and_role[wazuh-worker1-wazuh-worker2] PASSED                                                        [ 25%]
test_jwt_invalidation/test_disconnected_nodes.py::test_create_user_when_node_is_disconnected PASSED                                                                               [ 37%]
test_jwt_invalidation/test_revoke_endpoint.py::test_revoke_all_tokens_with_api[wazuh-master] PASSED                                                                               [ 50%]
test_jwt_invalidation/test_revoke_endpoint.py::test_revoke_all_tokens_with_api[wazuh-worker1] PASSED                                                                              [ 62%]
test_jwt_invalidation/test_revoke_endpoint.py::test_revoke_all_tokens_with_api[wazuh-worker2] PASSED                                                                              [ 75%]
test_jwt_invalidation/test_update_password.py::test_update_password[wazuh-master-None-Newpass1*] PASSED                                                                           [ 87%]
test_jwt_invalidation/test_update_password.py::test_update_password[wazuh-worker1-Newpass1*-Newpass2*] PASSED                                                                     [100%]

============================================================================= 8 passed in 274.38s (0:04:34) =============================================================================

```
