### ISSUE TITLE
Integration test for wazuh-logtest

### ISSUE THREAD

**Issue by Lopuiz** [wazuh/wazuh-qa#811]
| Working branch |
| --- |
| 5337-logtest-enhancement-qa |

Hello team!

New Logtest will be an Analysisd thread that listens in the `/var/ossec/queue/ossec/logtest` Unix socket for logs to process.
We have to create tests that connect with this socket and check Logtest works correctly.

**Test List:**
- [x] Connect socket `/var/ossec/queue/ossec/analysis` and request `rule_test` configuration. Test multiples configurations
- [x] Load incorrect rules (bad value options), connect to `/var/ossec/queue/ossec/logtest`, and check error and warning messages
- [x] Send invalid message and check the output
- [x] Load multiples rules and decoders, send logs to `/var/ossec/queue/ossec/logtest` and check response is correct

On the other hand, there will be a python script to communicate with Logtest by console instead of the user interface. (tests undefined)

Best regards,
Eva

**Comment by Lopuiz** [comment]
**PR number [816](https://github.com/wazuh/wazuh-qa/pull/816)**
PR 816 has the following tests:
+ Get multiples configurations using analysis queue. Check the configurations are correct. If it has high `threads`, `max_sessions`, or `max_timeouts` values, check it set the max value allowed.
+ Puts multiples configurations and, if they are invalid, check Wazuh prints warning messages.
