### ISSUE TITLE
Authorization context tests for the Wazuh API

### ISSUE THREAD

**Issue by vicferpoy** [wazuh/wazuh-qa#840]
| Working branch |
| --- |
|[dev-840-auth-context-tests](https://github.com/wazuh/wazuh-qa/tree/dev-840-auth-context-tests)|

# Summary

We have added a new endpoint to the Wazuh API in order to log in using an authorization context (`POST /security/user/authenticate/run_as`). We need to test that every token this endpoint provides is revoked when any security resource associated to it is modified and assure this endpoint is working properly.

# Tasks

This issue will cover both system and integration tests. The system tests will handle the token invalidation and the integration ones will test the endpoint behaviour.

## System tests

- [x] Check that an existing token is revoked when updating the password from the user that requested it.

- [x] Check that an existing token is revoked when changing roles related to the user that requested it.

- [x] Check that an existing token is revoked when changing policies related to the user that requested it.

- [x] Check that an existing token is revoked when changing rules related to the user that requested it.

- [x] Check that every token is revoked when making a call to `PUT /security/user/revoke`.

- [x] Check that both master and worker nodes retrieve token information when one of them disconnects from the cluster.

- [x] Check that an existing token is revoked when changing the RBAC mode.

Regards,
Víctor.
