### ISSUE TITLE
Integration test for the Windows registry rework.

### ISSUE THREAD

**Issue by antoniomanuelfr** [wazuh/wazuh-qa#845]
Hi team.
Windows registry monitoring is going to be improved. In order to test the new functionality that is going to be introduced, the Windows registries integration tests will also need to be changed.

Specifics of checks made by each of the new tests can be found in the individual issues and PRS

**Comment by jotacarma90** [comment]
### Integration test

I have been analyzing the current state of the integration tests related to the Windows registries, about what we are going to need after the improvement of them:

- `test_windows_registry`
Modify to accept the different options in the attributes of the registries, check all possible attributes:
    - check_all
    - check_sum
    - check_sha1sum
    - check_md5sum
    - check_sha256sum
    - check_size, check_owner
    - check_group, check_perm
    - check_attrs, check_mtime
    - (the **tag** and the **arch** attributes already exist and it is checked in this same test, check if something has to be changed to keep them working)

- Other new registries options like **report_changes**, **restrict** or **recursion_level** have tests for the same options in the directories:
    - test_report_changes
    - test_restrict
    - test_recursion_level

        We have to modify them so they also include a check of the registries (or if necessary create independent tests within those directories)


- `test_synchronization`
    Add a synchronization check with new databases of the registries.


- `test_multiple_registries`
    Currently, exist the `test_multiple_dirs`, we could consider a similar test to check that this works correctly also for the registries.


- `test_nodiff`
    Add a check of the nodiff functionality of the registries.


- `test_ignore_registry`
    Check when changing a subkey of an ignored registries, it seems that currently, it does not work.

- Another possible test for Windows registries:
    Some of the options that already exist in the `test_basic_usage`, could be useful adapt for check with the registries, for example:
    - delete_folder
    - move_dir
    - move_file
    - new_dirs
    - no_dir
    - rename

**Comment by antoniomanuelfr** [comment]
These are the test that are going to be developed: 

### AMBIGUOUS
- [ ] test_fim\registries\test_ambiguous_confs\test_ambiguous_complex.py
- [ ] test_fim\registries\test_ambiguous_confs\test_ambiguous_simple.py
- [ ] test_fim\registries\test_ambiguous_confs\test_ambiguous_whodata_thread.py
- [ ] test_fim\registries\test_ambiguous_confs\test_duplicate_entries.py
- [ ] test_fim\registries\test_ambiguous_confs\test_ignore_works_over_restrict.py
### BASIC USAGE
- [ ] test_fim\registries\test_basic_usage\test_basic_usage_baseline_generation.py
- [ ] test_fim\registries\test_basic_usage\test_basic_usage_changes.py
- [ ] test_fim\registries\test_basic_usage\test_basic_usage_create_after_delete_key.py
- [ ] test_fim\registries\test_basic_usage\test_basic_usage_create_wd.py
- [ ] test_fim\registries\test_basic_usage\test_basic_usage_delete_key.py
- [ ] test_fim\registries\test_basic_usage\test_basic_usage_entries_match_key_count.py
- [ ] test_fim\registries\test_basic_usage\test_basic_usage_new_key.py
- [ ] test_fim\registries\test_basic_usage\test_basic_usage_no_key.py
- [ ] test_fim\registries\test_basic_usage\test_basic_usage_quick_changes.py
- [ ] test_fim\registries\test_basic_usage\test_basic_usage_rename.py
### CHECKS
- [ ] test_fim\registries\test_checks\test_check_all.py
- [ ] test_fim\registries\test_checks\test_check_others.py
- [ ] test_fim\registries\test_checks\test_checksums_all.py
- [ ] test_fim\registries\test_checks\test_checksums.py
### IGNORE
- [ ] test_fim\registries\test_ignore\test_ignore_registry.py
- [ ] test_fim\registries\test_ignore\test_ignore_valid.py
### MULTIPLE REGS
- [ ] test_fim\registries\test_multiple_regs\test_multiple_keys.py
- [ ] test_fim\registries\test_multiple_regs\test_multiple_entries.py
### NO DIFF
- [ ] test_fim\registries\test_nodiff\test_no_diff_valid.py
### RECURSION LEVEL
- [ ] test_fim\registries\test_recursion_level\test_recursion_level.py
### RESTIRCT
- [ ] test_fim\registries\test_restrict\test_restrict_valid.py
### TAGS
- [ ] test_fim\registries\test_tags\test_tags.py
### FILE LIMIT
- [ ] test_fim\registries\test_file_limit\test_file_limit_capacity_alerts.py
### REPORT CHANGES
- [ ] test_fim\registries\test_report_changes\test_report_changes_and_diff.py
- [ ] test_fim\registries\test_report_changes\test_report_deleted_diff.py
