### ISSUE TITLE
Vulnerability Detector: Add local Debian Security Tracker feed support to Vulnerability Detector integration tests

### ISSUE THREAD

**Issue by danimegar** [wazuh/wazuh-qa#853]
## Description
The Debian Security Tracker feed (https://security-tracker.debian.org/tracker/data/json) can be used offline now. For that we use the tag `<path>` or `<url>`:
```xml
<provider name="debian">
    <enabled>yes</enabled>
    <os path="/home/user/oval-definitions-buster.xml">buster</os>
    <os path="/home/user/oval-definitions-stretch.xml">stretch</os>
    <path>/home/user/debian-security-tracker.json</path>
    <update_interval>1h</update_interval>
</provider>
```
or 

```xml
<provider name="debian">
    <enabled>yes</enabled>
    <os url="http://local_repo/oval-definitions-buster.xml">buster</os>
    <os url="http://local_repo/oval-definitions-stretch.xml">stretch</os>
    <url>http://local_repo/debian-security-tracker.json</url>
    <update_interval>1h</update_interval>
</provider>
```
## Tests
- [x] Verify the Debian Security Tracker feed content
- [x] Verify that there are no conflicts when using `<os path=...>` or `<os url=...>` with `<path>` or `<url>`
- [x] Verify feed is not parsed when a different/invalid feed is used.

**Comment by chemamartinez** [comment]
Merged #863
