### ISSUE TITLE
Automatic tests for unlimited agents epic

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh-qa#882]
It is necessary to create automatic tests to test this new capability that will allow have unlimited agents registered to a single manager.

Some checks that have to be done:

### Rootcheck

- [x] Simulate rootcheck messages from one agent: logs inserted in the agent's database.

- [x] Simulate rootcheck messages from two agents: logs inserted in the agents' databases.

- [x] Simulate repeated rootcheck messages from one agent: last time updated in the agent's database.

- [x] Simulate delete messages from one agent: logs deleted from agent's database.

- [x] Simulate delete messages from two agents: logs deleted from agents' databases.

### RIDS

- [x] Simulate keep-alive messages from one agent: RIDS file blocked.

- [x] Simulate keep-alive messages from one agent and stop the messages for a period of time: RIDS file unblocked.

- [x] Simulate keep-alive messages from three agents and stop the messages from one of them for a period of time: Two RIDS files blocked and one unblocked.
