### ISSUE TITLE
Test for Syscheck configuration

### ISSUE THREAD

**Issue by Lopuiz** [wazuh/wazuh-qa#96]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| - | Syscheck | Manager/Agent | Packages/Sources | Windows/Linux |

### Description

A test should be created to check that the `syscheck` configuration is working correctly. To do this, several Python scripts with the following functionalities will be created:
1. Write the test configuration in `ossec.conf`.
2. Create, modify, change permissions, change owner, change group and delete files in the monitored directories.
3. Check that the alerts are generated correctly in `alert.json`.

### Requirements
+ The tests must be able to run on the manager, Linux agents, and Windows agents.

### Test to do for Linux
- [x] `check_all` in frequency, whodata and realtime
- [x] `check_sum`, `check_sha1`, `check_md5`  and `check_sha256` in frequency, whodata and realtime
- [x] `check_size` in frequency, whodata and realtime
- [x] `check_owner` in frequency, whodata and realtime
- [x] `check_perm` in frequency, whodata, realtime
- [x] `check_mtime` in frequency, whodata and realtime
- [x] `check_inode` in frequency, whodata and realtime
- [x] `report_changes` in frequency, whodata and realtime
- [x] `restrict` in frequency, whodata and realtime
- [x] `tags` in frequency, whodata and realtime
- [x] `recursion_level` in frequency, whodata and realtime

### Test to do for Windows
- [x] `check_all` in frequency, whodata and realtime
- [x] `check_sum`, `check_sha1`, `check_md5`  and `check_sha256` in frequency, whodata and realtime
- [x] `check_size` in frequency, whodata and realtime
- [ ] `check_owner` in frequency, whodata and realtime
- [ ] `check_perm` in frequency, whodata and realtime
- [x] `check_mtime` in frequency, whodata and realtime
- [x] `check_attr` in frequency, whodata and realtime
- [x] `report_changes` in frequency, whodata and realtime
- [x] `restric` in frequency, whodata and realtime
- [x] `tags` in frequency, whodata and realtime
- [x] `recursion_level` in frequency, whodata and realtime

**Comment by Lopuiz** [comment]
**Test for Linux:**
+ The tests for `tag`, `restrict` and `recursion_level` must be approached differently.
+ The `time.sleep(60)` statements must be changed by a call to a function that checks in `ossec.log` that the condition has occurred in order to continue executing. For example, it does not generate events until this log appears: `ossec-syscheckd: INFO: (6011): Initializing real time file monitoring engine.`
+ File name must randomly generate. This will help to avoid erroneous results if you run the script several times consecutively. - *Done*

**Test for Windows**
+ I use `PyWin32` to create the script that generates the test environment

**Enhancement:**
+ Once the test core has been created, i can modify the way in which the fields that should contain the alerts are stored.

**Comment by Lopuiz** [comment]
### Done:

Three Python scripts have been created, two to generate the environment and another to check that the alerts are correct. The fields that each alert must contain are stored in a YAML file.

### Todo
+ We can improve the tests for `tags` and `recursion_level`. Now it is only verified that it does not generate an alert when it should not, it should also be verified if it generates alert when it should.
+ The fact that the `syscheck` frequency is 180s causes some alerts (either realtime, whodata or frequency) to be lost. The three options must be separated. This can be done by entering as parameter the script you want to test.
+ The `time.sleep(60)` statements must be changed by a call to a function that checks in `ossec.log` that the condition has occurred in order to continue executing. For example, it does not generate events until this log appears: `ossec-syscheckd: INFO: (6011): Initializing real time file monitoring engine`. Think how you can do this in Windows

### Enhancement:
+ Add test for `follow_symbolic_link` and `ignore`
+ Add test for `windows_registry` and `registry_ignore`

**Comment by bah07** [comment]
This issue will be completed with the integration tests described in https://github.com/wazuh/wazuh-qa/issues/321
